### PR TITLE
Shortcodes - Spotify: Fix embed when text not preceded by HTML tag.

### LINKED ISSUE #15800: Shortcodes - Spotify: Embed text not converted if Spotify text not at beginning of string
#### Steps to reproduce the issue

1. Create a new post in the classic editor or using a `classic` block.
2. If using the classic editor, open the `Text` view.
3. Add some arbitrary text (not wrapped in an HTML tag).
4. Add `spotify:track:4bz7uB4edifWKJXSDxwHcs`.
5. View post and see that the embed did not get converted.
6. Wrap your arbitrary text in any HTML tag.
7. View post and see that the embed is rendered properly.

#### What I expected
I would expect that the `spotify:track:4bz7uB4edifWKJXSDxwHcs` text would be converted into the embedded Spotify player.

#### What happened instead
The `spotify:track:4bz7uB4edifWKJXSDxwHcs` gets rendered as is.

**Screenshots**
spotify-embed-editor
spotify-embed-view

The issue here is that `wp_html_split()` [here](https://github.com/Automattic/jetpack/blob/cd3275c8d049b6a9e9b49110c12b2599c7a49335/modules/shortcodes/spotify.php#L71) splits up the content by HTML tags into an array of "elements" and then [this line](https://github.com/Automattic/jetpack/blob/cd3275c8d049b6a9e9b49110c12b2599c7a49335/modules/shortcodes/spotify.php#L78) only checks the first 8 characters of the element to see if they are `spotify:`. If they aren't, as such is the case where no HTML element immediately precedes the Spotify embed, the embed isn't processed and rendered as expected. I can submit a PR with a suggested fix shortly.

### PR DESCRIPTION
**Pull request by brettshumaker**
Fixes #15800 

#### Changes proposed in this Pull Request:

* Check if `spotify:` exists anywhere in the `$element` string instead of just the first 8 characters of the string.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Create a new post in the classic editor or using a classic block.
* If using the classic editor, open the `Text` view.
* Add some arbitrary text (not wrapped in an HTML tag).
* Add spotify:track:4bz7uB4edifWKJXSDxwHcs on its own line below the other text.
* View post and verify that the embed is rendered properly.

#### Proposed changelog entry for your changes:

* Embeds: ensure that all valid Spotify embeds are being rendered.

### CODE REVIEW

File: modules/shortcodes/spotify.php [hunk 1]
```diff
@@ -75,7 +75,8 @@ function jetpack_spotify_embed_ids( $content ) {
 			continue;
 		}
 
-		if ( substr( ltrim( $element ), 0, 8 ) !== 'spotify:' ) {
+		// If this element does not contain a Spotify embed, continue.
+		if ( strpos( $element, 'spotify:' ) === false ) {
```
Comment (jeherve) [inline modules/shortcodes/spotify.php:79]: What do you think about using yoda conditions here?

```suggestion
		if ( false === strpos( $element, 'spotify:' ) ) {
```

Comment (brettshumaker) [reply modules/shortcodes/spotify.php:79]: Ahh. Yep. Let's do that instead.

**Comment by jeherve** [comment]
r207546-wpcom
