### PR TITLE
VideoPress: Fix video counter on VideoPress library page

### LINKED ISSUE #26346: VideoPress: fix video counter on the VideoPress library
The video counter on the VideoPress library is actually showing the number of videos on the page, and not the total of videos. After #26326 the total of videos is available on the code, so we can fix the counter and show something like "X of Y videos", where X is the number of videos on the page, and Y is the total of videos.

**Edit:** we have a designed state for this available on p1HpG7-gQf-p2. It shows just `1 Video` or `N Videos`, so there is no need for the number of videos on the page.

Example:

* on this site, we have 9 videos on the library
* the page 1 shows the counter as "6 Video":

counter-on-videopress-media-library-pagination-1

* it could be more informative showing "6 of 9 videos", for example
* the page 2 shows the counter as "3 Video":

counter-on-videopress-media-library-pagination-2

* it could be more informative showing "3 of 9 videos", for example

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #26346.

#### Changes proposed in this Pull Request:

* Change the VideoPressLibrary and LocalLibrary component to expect a `totalVideos` prop
* Use the information returned by `useVideos()` to set this prop on when rendering the components
* Set proper plural and internationalization for the counter words

Visual changes:

* **Before the fix:** the counter would show the number of videos on the current page

Counter on VideoPress Library, page 1

Counter on VideoPress Library, page 2

* **After the fix:** The counter will always show the total of videos from the library, regardless of the page; singular ("Video") and plural ("Videos") are properly handled, as well as internationalization

Counter on VideoPress Library with proper singular label

Counter on VideoPress Library, page 1, showing the total of videos

Counter on VideoPress Library, page 2, still showing the total of videos

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

Based on the designs from p1HpG7-gQf-p2.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Use a connected site with the VideoPress plugin installed and an active VideoPress upgrade
* If you don't have any videos, add one through `Media > Add New`
* Go to `Jetpack > VideoPress` to open the VideoPress library
* The counter will show the total of videos from your library
* If you have less than 6 videos on the library, add a few more using `Media > Add New` so you get more than one page on the listing
* Go to `Jetpack > VideoPress` to open the VideoPress library again
* The counter will show always the total of videos from your library, always the same number regardless of the page

### CODE REVIEW

File: projects/packages/videopress/src/client/admin/components/admin-page/libraries.tsx [hunk 1]
```diff
@@ -62,13 +62,19 @@ const VideoLibraryWrapper = ( {
 
 	const [ isFilterActive, setIsFilterActive ] = useState( false );
 
+	const singularTotalVideosLabel = __( 'Video', 'jetpack-videopress-pkg' );
+	const pluralTotalVideosLabel = __( 'Videos', 'jetpack-videopress-pkg' );
+	const totalVideosLabel = totalVideos === 1 ? singularTotalVideosLabel : pluralTotalVideosLabel;
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/admin/components/admin-page/libraries.tsx:67]: Since it relies on `totalVideos`, it could be `const singularTotalVideosLabel = __( '1 Video', 'jetpack-videopress-pkg' );` and
```js
const pluralTotalVideosLabel = sprintf(
	// translators: %$1s is the number of videos
	__( '%1$s Videos', 'jetpack-backup-pkg' ),
	totalVideos
);
```

**Review by dhasilva — APPROVED** [review]
LGTM, just left a suggestion :rocket:
