### PR TITLE
Fix/launch task completion

### LINKED ISSUE #88007: The users are not able to complete the "Launch your site" task
The truth is that the site is launched by the time we get the design selection step on the **sell** flow. I suspect that the `launch-status` is being set directly for the flow instead of using `set_status_launched` function.

### Steps to reproduce it
* Create a site through the `/start` flow.
* On the Goals step, select sell.
* Go through the flow until you reach the Customer Home page.
* Click on the `Launch your site` task.
* It won't get marked as complete.

### PR DESCRIPTION
**Pull request by nelsonec87**
Fixes https://github.com/Automattic/wp-calypso/issues/88007

## Proposed changes:
The "Launch site" task remains incomplete even when the site is launched. 

This PR adds logic to the task to check the launch_status and be "completed" if the site is launched.

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

- Enable sandbox and apply this PR
- Create a site through the /start flow.
- On the Goals step, select sell.
- Go through the flow until you reach the Customer Home page.
- Click on the Launch your site task.
- Click on Show site setup
- Check if the Launch your Site task is completed.

image

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php [hunk 1]
```diff
@@ -730,6 +731,16 @@ function wpcom_launchpad_get_task_definitions() {
 	return array_merge( $extended_task_definitions, $task_definitions );
 }
 
+/**
+ * Returns true if the current site is launched.
+ *
+ * @return boolean
+ */
+function wpcom_launchpad_is_site_launched() {
```
Comment (valterlorran) [inline projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php]: We should also check if the status is already complete, so we don't need always to check the option:
https://github.com/Automattic/jetpack/blob/ff17b59347cd29f9113174420ced10c7526670f4/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L1058-L1061

**Review by valterlorran — CHANGES_REQUESTED** [review]

**Comment by nelsonec87** [comment]
Rebased to keep the PR "up-to-date"

**Review by sixhours — APPROVED** [review]
This is working for me!

**Review by valterlorran — APPROVED** [review]
LGTM!
