### PR TITLE
Map Block: Tweak the scroll-to-zoom behaviour.

### LINKED ISSUE #11904: Map Block: Add option to prevent map zoom if you scroll while cursor is on the map
#### Steps to reproduce
1. Add a map to a page.
2. View the page.
3. Scroll down the page using trackpad or scroll wheel
4. Try to scroll while the cursor is over the map.

#### What I expected

The page will continue to scroll.

#### What happened instead

The map zoomed in/out instead

#### Browser / OS version

Chrome Version 70.0.3538.110 (Official Build) (64-bit)
MacOS 10.14

#### Screenshot / Video

map-scroll-zoom

#### Context / Source

Reported in 1618575-zen

### PR DESCRIPTION
**Pull request by pento**
This PR changes the behaviour of scroll-to-zoom on the map block.

Currently, it will capture the scroll event whenever the pointer is over the map block: this means that you can accidentally zoom when scrolling through a post.

In the block editor, it now only zooms when the block is selected: scrolling through a post won't accidentally be captured by an unselected map block.

On the front end, the there is now an option (defaulting to off) for enabling scroll to zoom.

Fixes #11904.

#### Changes proposed in this Pull Request:
* Improve the usability of scroll to zoom.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Changes the behaviour of the map block.

#### Testing instructions:

* Create a new post in the block editor, and add a map block.
* Test that zooming only happens when the map block is selected.
* Publish the post.
* Test that zooming only happens on the front end when the "Scroll to zoom" option is toggled.

#### Proposed changelog entry for your changes:
* Map Block: Prevent an unselected block from accidentally capturing scrolling, and add an option for toggling zoom to scroll behaviour in the published post.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This worked as expected on in the editor, and on the frontend it didn't zoom on scroll by default, but with the scrollToZoom toggle set to true it still didn't capture the scroll to zoom. The scrollToZoom prop seems to always be false on frontend render for me:

Screen Shot 2020-02-14 at 2 37 48 PM

**Comment by pento** [comment]
Thanks for the review, @glendaviesnz! f6143f5 fixes that up, looks like I needed to save the attribute onto the `<div>`.

**Comment by pento** [comment]
A note on there only being one item in the Settings panel, which looks a bit lonely: #14557 is also on my radar, that would go in it, too.

File: extensions/blocks/map/save.js [hunk 1]
```diff
@@ -28,6 +37,7 @@ class MapSave extends Component {
 				data-zoom={ zoom }
 				data-map-center={ JSON.stringify( mapCenter ) }
 				data-marker-color={ markerColor }
+				data-scroll-to-zoom={ scrollToZoom ? scrollToZoom : null }
```
Comment (Copons) [inline extensions/blocks/map/save.js]: We could simplify this as `scrollToZoom || null`—maybe `undefined` is more correct here? 🤔

**Review by Copons — DISMISSED** [review]
I've left a nitpick comment, but otherwise this LGTM!

**Review by jeherve — DISMISSED** [review]
This works well in my tests! 👍

File: extensions/blocks/map/save.js (hunk 1 above)
Comment (pento) [reply extensions/blocks/map/save.js]: Aye, I'll simplify it a little bit. I went with `null` as it's also used for the `alignClassName` asssignment above, and it appears to have the desired effect: if the `scrollToZoom` option isn't set, `data-scroll-to-zoom` won't be added to the output HTML.

Comment (pento) [reply extensions/blocks/map/save.js]: Tweaked in 1b31139ef.

**Comment by pento** [comment]
Ugh, auto-dismissing reviews is the worst, especially for a minor fix.

@jeherve, could you approve it again, so I can merge?

File: extensions/blocks/map/save.js (hunk 1 above)
Comment (Copons) [reply extensions/blocks/map/save.js]: Yup, I did notice the behaviour was identical with `null` and `undefined`, but for some reasons I was sure only `undefined` would omit the prop. 🤷‍♂️

**Review by Copons — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
