### PR TITLE
VideoPress: hide VideoPress block and update Video block description

### LINKED ISSUE #11480: Blocks: Video vs VideoPress blocks
Within WordPress Core, since it supports VideoPress oembeds out of the box, it generates a VideoPress block.

Our own work to better support Jetpack Videos/VideoPress is by amending the Core video block.

This may be confusing to customers, so should/could we suppress the VideoPress block in some way?

#### Steps to reproduce the issue

1. Go to Block Editor with a Jetpack site with video hosting enabled.
2. Click the UI to add a new block.
3. See both a Video and VideoPress block.

#### What I expected
No confusion on what block to use.

#### What happened instead
It can be confusing.

When pasting a VideoPress link, auto-converting to a VideoPress block is fine, but could we just remove it as an option in the new block UI?

cc: @mmtr

### PR DESCRIPTION
**Pull request by thedebian**
Fixes Automattic/greenhouse#990
Fixes #11480

#### Changes proposed in this Pull Request:

The VideoPress embed block is confusing when using VideoPress.
This PR hides the VideoPress embed block in favor of the Video block (where we could still embed a VideoPress URL there).
It also updates the video block example and description to be more VideoPress-specific when VideoPress is enabled.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* On a Jetpack site with VideoPress enabled
* Create a new post or edit an existing one
* Type /videopress
* ✅ The video block should appear and the VideoPress embed block should not be visible

Capture d’écran 2021-11-15 à 12 06 41

* Clear your line and click on the "+" button 
* Search for "videopress"
* ✅ The video block should appear and the VideoPress embed block should not be visible

Capture d’écran 2021-11-15 à 12 07 39

* Click on "Browse all"
* ✅ The VideoPress embed block should not be visible in this list
* ✅ The Video block should have an updated example and description

Capture d’écran 2021-11-15 à 12 09 20

* Add a video block
* Click on "Insert from URL"
* Insert a VideoPress link ( you can try https://videopress.com/v/Ygmx4akX )
* ✅ The block should be transformed to a VideoPress embed

Capture d’écran 2021-11-15 à 12 11 03

* In a new tab, go to your Jetpack settings and disable VideoPress
* Refresh your edited post 
* ✅ The VideoPress embed block should be available again and the video block description should be the default core video description (no mentions of VideoPress)

### CODE REVIEW

**Review by roundhill — CHANGES_REQUESTED** [review]
Tested well for me, have one suggestion for the image url.

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js [hunk 1]
```diff
@@ -113,6 +133,18 @@ const addVideoPressSupport = ( settings, name ) => {
...
+		// If VideoPress is available, we update the block description and example with VideoPress-specific content.
+		settings.description = __(
+			'Embed a video from your media library or upload a new one with VideoPress.',
+			'jetpack'
+		);
+		settings.example.attributes = {
+			caption: __( 'Upload or embed videos with VideoPress', 'jetpack' ),
+			isVideoPressExample: true,
+			src:
+				'https://s0.wp.com/wp-content/themes/a8c/jetpackme-new/images/2021/videopress/device-mashup-desktop.jpg',
```
[the remark this answers is not in the document]
Comment (thedebian) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js:146]: That's perfect, thanks !

**Comment by thedebian** [comment]
@roundhill I updated the image URL and also added some check to make sure we only hide the core/embed VideoPress block and update the core/video example when VideoPress is available (the testing instructions have been updated too)

**Review by roundhill — DISMISSED** [review]
Latest changes look good, looks it needs a rebase 😬

**Review by roundhill — DISMISSED** [review]
Still good after rebase 👍

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js [hunk 2]
```diff
@@ -114,6 +138,17 @@ const addVideoPressSupport = ( settings, name ) => {
...
+	} else if ( available ) {
+		// If VideoPress is available, we update the block description and example with VideoPress-specific content.
+		settings.description = __(
+			'Embed a video from your media library or upload a new one with VideoPress.',
+			'jetpack'
+		);
+		settings.example.attributes = {
+			caption: __( 'Upload or embed videos with VideoPress', 'jetpack' ),
+			isVideoPressExample: true,
+			src: 'https://videopress2.files.wordpress.com/2021/11/videopress-devices.jpg',
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/videopress/editor.js:150]: In the past we've uploaded them to the plugin, so they can be served locally. Here is an example:
https://github.com/Automattic/jetpack/blob/2704efac24c831348233c68f6ab35893d706ddf7/projects/plugins/jetpack/extensions/blocks/tiled-gallery/index.js#L32-L40

Should we do that here too?

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js [hunk 3]
```diff
@@ -114,6 +138,17 @@ const addVideoPressSupport = ( settings, name ) => {
...
 			withHasWarningIsInteractiveClassNames( `core/video` )
 		);
+	} else if ( available ) {
+		// If VideoPress is available, we update the block description and example with VideoPress-specific content.
+		settings.description = __(
+			'Embed a video from your media library or upload a new one with VideoPress.',
+			'jetpack'
+		);
+		settings.example.attributes = {
+			caption: __( 'Upload or embed videos with VideoPress', 'jetpack' ),
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/videopress/editor.js:148]: Since we have a description right below the example, do we need the caption? Maybe it would be enough if the image showed a Play button on top of a blurry image, so folks understand it's a player?

**Review by jeherve — COMMENTED** [review]
It all works well. I only have a couple of questions about the example.

**********

> Click on "Insert from URL"
> Insert a VideoPress link ( you can try videopress.com/v/Ygmx4akX )
> ✅ The block should be transformed to a VideoPress embed

This works well. I was wondering if in the future, we could do a full transform so you get Video settings in the editor sidebar?

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js (hunk 2 above)
Comment (thedebian) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js:150]: Sure, I'll update the PR ! :)

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js (hunk 3 above)
Comment (thedebian) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js:148]: The idea was to emphasize on "VideoPress" so people can know we're actually doing something and it's the right block to use, but this part is so hidden that I don't really know what would be best tbh; I'm okay with removing the caption though, it doesn't add much information while requiring a new translation, so I'll update the PR 👍

**Comment by thedebian** [comment]
Last changes : rebase, remove caption and store example image locally

**Review by jeherve — COMMENTED** [review]
The thumbnail seems to be cut off for me:
image

Is that to be expected?

(this site is not using the Gutenberg plugin)

**Comment by thedebian** [comment]
> Is that to be expected?

🤦 Of course not, I must have had some client cache or whatever when testing, I'm really sorry for the useless roundtrip, I'll update that !

**Review by jeherve — DISMISSED** [review]
I cannot reproduce the above issue anymore. This should be good to merge now, after a `git merge origin/master`

**Comment by samiff** [comment]
@thedebian Hmm I'm seeing the block preview with scrollbars 🤔 

Screen Shot 2021-12-16 at 11 40 49 AM

Could you check on your end please. I've added the image being used to the wpcom diff.

**Comment by thedebian** [comment]
> Could you check on your end please. I've added the image being used to the wpcom diff.

I still can't reproduce this, but I went ahead and reduced the image size + cleaned up the output a bit by only returning an img (as we don't care about the caption anymore);
Is it better now ?
It's supposed to be max-width 100% too, from what I can see in the inspector, but I can force it somehow on the block output itself or something along the line if it doesn't get any better.

**Comment by samiff** [comment]
@thedebian I figured out what was different on my end - I'm running WP 5.9 nightlies and that along with a theme like Twenty Nineteen seems to change the editor wrapper styles being applied, causing the scrollbars I've seen. I'm thinking this one should be good to go 👍

**Review by samiff — DISMISSED** [review]

**Comment by thedebian** [comment]
@samiff Sorry, I tried resyncing the wpcom PR by rebasing this diff, so the ✅ is now gone here (and I had to manually sync the wpcom diff anyway because of the new image file 🙄 ); Could you reapprove it please so it could be merged ?

**Review by samiff — APPROVED** [review]

**Comment by thedebian** [comment]
Changeset 237530
