### PR TITLE
Blaze: bail earlier when there are connection issues

### LINKED ISSUE #38068: Blaze eligibility checks under failure conditions
### Impacted plugin

Jetpack

### Quick summary

When a Jetpack connection is not completely healthy, Blaze repeatedly triggers public-api calls for wp-admin requests to check a site's eligibility status because failure modes are not cached or handled.

### Steps to reproduce

1. Load /wp-admin for an affected blog.
2. A background HTTP request to https://public-api.wordpress.com/wpcom/v2/sites/###/blaze/status?home=example.com&siteurl=https%3A%2F%2Fexample.com?idc=1 will be recorded by debug bar with status 403.
3. Reloading the /wp-admin page will again trigger a background HTTP request.

### A clear and concise description of what you expected to happen.

I do not expect an over-the-wire request checking Blaze eligibility for every wp-admin request to the site.

### What actually happened

Navigating wp-admin continues to make blocking over-the-wire requests to public-api, slowing down the site's response time in wp-admin.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

public-api endpoint request/response excerpts:
```
            [blocking] => 1
            [headers] => Array
                (
                    [Authorization] => X_JETPACK token="..." timestamp="1719417921" nonce="..." body-hash="" signature="...=" version="13.6-a.5"
                )

            [cookies] => Array
                (
                )

            [body] => {"code":"unauthorized","message":"User cannot access this private blog.","data":{"status":403}}
            [response] => Array
                (
                    [code] => 403
                    [message] => Forbidden
                )
```

Stack trace:
```
    [class] => WpOrg\Requests\Requests
    [stack_trace] => Array
        (
            [0] => Atomic_Debug_Bar_WP_Http->after_http_request
            [1] => WP_Hook->apply_filters
            [2] => WP_Hook->do_action
            [3] => do_action('http_api_debug')
            [4] => WP_Http->request
            [5] => wp_remote_request
            [6] => Automattic\Jetpack\Connection\Client::_wp_remote_request
            [7] => Automattic\Jetpack\Connection\Client::remote_request
            [8] => Automattic\Jetpack\Connection\Client::wpcom_json_api_request_as_blog
            [9] => Automattic\Jetpack\Blaze::site_supports_blaze
            [10] => Automattic\Jetpack\Blaze::should_initialize
            [11] => Automattic\Jetpack\Blaze::enable_blaze_menu
            [12] => WP_Hook->apply_filters
            [13] => WP_Hook->do_action
            [14] => do_action('admin_menu')
            [15] => require_once('wp-admin/includes/menu.php')
            [16] => require('wp-admin/menu.php')
            [17] => require_once('wp-admin/admin.php')
        )
```

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #38068 

## Proposed changes:

When a site or user is not properly connected to WordPress.com, or when there are sync issues on the site, we can estimate that the site is not eligible to Blaze, since they won't be able to create Blaze campaigns when those things are not working properly.

Let's consequently bail earlier, consider Blaze as not ready to be initialized. That will save us a lot of failed remote requests later.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Related discussion: p1719416484308139-slack-CBG1CP4EN

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

This will be easier to test on a site with a broken Jetpack connection.

There, when the Blaze module is enabled in Jetpack > Settings > Traffic:

1. You should not see the navigation menu in Tools > Advertize.
2. You should not see any requests to WordPress.com being made.

### CODE REVIEW

**Comment by jmdodd** [comment]
I tested with this patch. The broken site where I encountered this condition passes both the connection and sync checks, but still fails authentication. In this case, I think we should fall back to storing the failure in a transient.

**Comment by jeherve** [comment]
> In this case, I think we should fall back to storing the failure in a transient.

I implemented that in f418608ce2dba4a519761a4e9e01e2c2b2ebfc79

**Comment by jeherve** [comment]
> The broken site where I encountered this condition passes both the connection and sync checks, but still fails authentication.

@Automattic/jetpack-vulcan Can you think of ways we could catch the errors @jmdodd described in p1719418092056169/1719416484.308139-slack-CBG1CP4EN , besides the existing `is_connected` and `is_user_connected` checks?

**Comment by fgiannar** [comment]
> > The broken site where I encountered this condition passes both the connection and sync checks, but still fails authentication.
> 
> @Automattic/jetpack-vulcan Can you think of ways we could catch the errors @jmdodd described in p1719418092056169/1719416484.308139-slack-CBG1CP4EN , besides the existing `is_connected` and `is_user_connected` checks?

Those errors occur because we are attempting to access a private WoA site on an `wpcom/v2` endpoint on WPCOM using a blog token. 
We need to update the corresponding endpoint on WPCOM explicitly to allow requests signed with blog tokens.

Prior art: p1712319459536349/1706626329.415869-slack-C01U2KGS2PQ

File: projects/packages/blaze/src/class-blaze.php [hunk 1]
```diff
@@ -189,16 +199,27 @@ public static function site_supports_blaze( $blog_id ) {
...
+		$connection = new Jetpack_Connection();
+		$site_id    = Jetpack_Connection::get_site_id();
 
 		// Only admins should be able to Blaze posts on a site.
 		if ( ! current_user_can( 'manage_options' ) ) {
 			return false;
 		}
 
+		// Allow short-circuiting the Blaze initialization via a filter.
+		if ( has_filter( 'jetpack_blaze_enabled' ) ) {
```
Comment (fgiannar) [inline projects/packages/blaze/src/class-blaze.php:212]: Is it intentional that we prioritized the filter over the Connection and Sync checks below? I would expect that even if the filter is used, we should still return `false` if there are connection issues or Sync is disabled.

**Comment by jeherve** [comment]
> Those errors occur because we are attempting to access a private WoA site on an `wpcom/v2` endpoint on WPCOM using a blog token.
> We need to update the corresponding endpoint on WPCOM explicitly to allow requests signed with blog tokens.

Thank you! I just opened D153591-code to try to tackle this.

File: projects/packages/blaze/src/class-blaze.php (hunk 1 above)
Comment (jeherve) [reply projects/packages/blaze/src/class-blaze.php:212]: In practice, the filter is really used in 2 scenarios:

- In tests
- In third-party plugins / themes' `functions.php` files as a way to force Blaze to false.

With that in mind, I think it's okay to prioritize the filter, since in real life I don't see folks use it to force Blaze to true?

**Review by fgiannar — CHANGES_REQUESTED** [review]
The `if ( ! is_array( $result ) || empty( $result['approved'] ) ) {` check in `class-blaze.php` line 175 will result in returning early and not caching the result if `$result['approved']` is false.
Maybe consider using `isset`?

**Comment by jeherve** [comment]
> The `if ( ! is_array( $result ) || empty( $result['approved'] ) ) {` check in `class-blaze.php` line 175 will result in returning early and not caching the result if `$result['approved']` is false.
> Maybe consider using `isset`?

👍 Done in 0ff1eaa7f392d4d1982c5f652f06370751955a68

**Comment by jeherve** [comment]
> Btw are there any existing unit tests for Blaze::site_supports_blaze ? Maybe we could add the transient logic there too

I worked on a test in 5045a01c710c93bdead36ed702e0f2fb86f68b96, but cannot get it to work:
https://github.com/Automattic/jetpack/actions/runs/9697982621/job/26763577490?pr=38066#step:9:287

At this point I've spent too much time on it already, so I'm pushing my work in progress, and hoping someone can tell me what I did wrong :)

Thank you!

**Comment by fgiannar** [comment]
> At this point I've spent too much time on it already, so I'm pushing my work in progress, and hoping someone can tell me what I did wrong :)

The request using `Client::wpcom_json_api_request_as_blog` was failing early because 1) the [blog token was missing](https://github.com/Automattic/jetpack/blob/a954b88239c722671bc27fc02c3d9265af5a7923/projects/packages/connection/src/class-client.php#L114) and 2) the `host` part for the remote request [was missing](https://github.com/Automattic/jetpack/blob/a954b88239c722671bc27fc02c3d9265af5a7923/projects/packages/connection/legacy/class-jetpack-signature.php#L209)

Fixed via https://github.com/Automattic/jetpack/pull/38066/commits/54c72b86f3b8ec6619bc5a6607471e5493c71391

**Review by fgiannar — APPROVED** [review]
Great work here, Jer! Many thanks for these performance improvements for Blaze and adding a relevant unit test too 👍
