### PR TITLE
Fix form submission with no name but mail

### LINKED ISSUE #30456: Form: Submission view - If name field kept empty, email entry shows in name field
**Input Form:**

skipping the name field

Image

**Submission View:**

unexpected duplication of email in the name field ... 

Image

**Responses Inbox:**

As expected.

Image

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes https://github.com/Automattic/jetpack/issues/30456

## Proposed changes:
Currently if we have a form with a `name` field and an `email` field where the `name` is not required, when we submit the form with an empty name, the success messages shows the `name` with the `email` value.

This happens because during submission there [is code](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/forms/src/contact-form/class-contact-form.php#L1228) that sets the email as a fallback. That `$comment_author` is later on used in more places (like headers, entity title, etc..) so I didn't make any update there.

Instead in the time of rendering the success message I added a check whether name and email have the same values. In that case, we don't render the `name`.

Ideally we should check if the original `name` value was provided or not, but I couldn't find a way to get that value and I think it's not stored anywhere else, without having the fallback applied during submission.

My check though introduces a new edge case where in a form like the one described here, if a user submits an `email` to both `name and email` fields, we will not render the `name` in the success message.

I'd consider edge cases both the linked issue and my approach and I'm not sure if it's even worth it to handle this.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
1. In a post add a contact form
2. make the `name` field **not** required
3. submit the form in the front end without providing a `name`
4. Observe that the `name` is not part of the success message
5. Test the form with different combinations of input (ex. provide both `email and name`, only `email`, etc..).

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-contact-form-plugin.php [hunk 1]
```diff
@@ -2046,10 +2046,7 @@ public static function parse_fields_from_content( $post_id ) {
 			if ( str_contains( $content, 'JSON_DATA' ) ) {
 				$chunks     = explode( "\nJSON_DATA", $content );
 				$all_values = json_decode( $chunks[1], true );
-				if ( is_array( $all_values ) ) {
```
Comment (ntsekouras) [inline projects/packages/forms/src/contact-form/class-contact-form-plugin.php:2049]: This is not related, but I observed that `$fields_array` is only used in the `else` block.

**Review by enejb — APPROVED** [review]
Nice work! 

This now works as expected for me. See 
Screenshot 2025-01-10 at 08-17-34 Enej Dev jetpack 1

Screenshot 2025-01-10 at 08-18-27 Enej Dev jetpack 1

Screenshot 2025-01-10 at 08-18-53 Enej Dev jetpack 1

> My check though introduces a new edge case where in a form like the one described here, if a user submits an email to both name and email fields, we will not render the name in the success message.

I was able to confirm that this is now an edge case. I don't think we need to solve for it though.

**Review by edanzer — APPROVED** [review]
Changes look straightforward and safe, and work as expected. And confirmation looks better without outputting the email as the name. 

Agree with @enejb on the edge case. I think it's fine as is.

Lots of e2e testing issues that all seem unrelated?
