### PR TITLE
Masterbar: be more defensive when fetching site menus

### LINKED ISSUE #36780: Jetpack masterbar causes fatal when submenu items return false
### Impacted plugin

Jetpack

### Quick summary

An example of this is outlined in p9F6qB-eMr-p2 where installing the `Ditty News Ticker` plugin on a site with PHP 8.0 active caused a fatal error 

```
[08-Apr-2024 11:51:44 UTC] PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, bool given in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php:514
```

This refers to the `hide_parent_of_hidden_submenus()` function in the Jetpack masterbar. 

### Steps to reproduce

1. Have a site with the latest Jetpack installed, running PHP 8+
2. Install the `ditty-news-ticker` plugin
3. Fatal should occur

### A clear and concise description of what you expected to happen.

The site should load and the menus and submenus should appear

### What actually happened

Fatal error shown below appears

```
[08-Apr-2024 11:51:44 UTC] PHP Fatal error:  Uncaught TypeError: array_values(): Argument #1 ($array) must be of type array, bool given in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php:514
Stack trace:
#0 /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php(514): array_values(false)
#1 /wordpress/core/6.5/wp-includes/class-wp-hook.php(324): Automattic\Jetpack\Dashboard_Customizations\Base_Admin_Menu->hide_parent_of_hidden_submenus('')
#2 /wordpress/core/6.5/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.5/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.5/wp-admin/includes/menu.php(161): do_action('admin_menu', '')
#5 /wordpress/core/6.5/wp-admin/menu.php(422): require_once('/wordpress/core...')
#6 /wordpress/plugins/jetpack/13.3-beta/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php(95): require_once('/wordpress/core...')
#7 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(1230): WPCOM_REST_API_V2_Endpoint_Admin_Menu->get_item(Object(WP_REST_Request))
#8 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wpcom/v2/admin...', Array, NULL)
#9 /wordpress/core/6.5/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
#10 /wordpress/core/6.5/wp-includes/rest-api.php(428): WP_REST_Server->serve_request('/wpcom/v2/admin...')
#11 /wordpress/core/6.5/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#12 /wordpress/core/6.5/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#13 /wordpress/core/6.5/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
#14 /wordpress/core/6.5/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#15 /wordpress/core/6.5/wp-includes/class-wp.php(813): WP->parse_request('')
#16 /wordpress/core/6.5/wp-includes/functions.php(1336): WP->main('')
#17 /wordpress/core/6.5/wp-blog-header.php(16): wp()
#18 /wordpress/core/6.5/index.php(17): require('/wordpress/core...')
#19 {main}
  thrown in /wordpress/plugins/jetpack/13.3-beta/modules/masterbar/admin-menu/class-base-admin-menu.php on line 514
```

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #36780

## Proposed changes:

This is a bit more defensive and should avoid fatals like the one outlined in the issue above.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* You can test this on a WoA site where you have installed the `ditty-news-ticker` plugin.
* Once the plugin is activated, you should not see any fatal error on the site.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 1]
```diff
@@ -504,7 +504,7 @@ public function hide_parent_of_hidden_submenus() {
 			$has_submenus = isset( $submenu[ $menu_item[2] ] );
 
 			// Skip if the menu doesn't have submenus.
-			if ( ! $has_submenus ) {
+			if ( ! $has_submenus || ! is_array( $has_submenus ) ) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: The `is_array( $has_submenus )` will always be false, because `$has_submenus` is always a boolean.

What you'll probably want to do is make line 504 be something like
```php
$has_submenus = isset( $submenu[ $menu_item[2] ] ) && is_array( $submenu[ $menu_item[2] ] );
```

Comment (jeherve) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: I was just looking at that, seeing the failed tests I realized I should have spent more time on this. I went in another direction from your suggestion, which I think should work too.

**Review by anomiex — APPROVED** [review]
Should work. Haven't tested.
