### PR TITLE
Form: Fix form block alignment by removing contact form wrapping `<div>` element

### LINKED ISSUE #41202: Forms: Alignment options do not work in the editor
### Impacted plugin

Jetpack

### Quick summary

Selecting an alignment option, such as wide or full, does not work in the editor. 

https://github.com/user-attachments/assets/592f561a-8d7c-497e-91fb-6067a7b41196

This is due to the block being wrapped in a `div` for apparent styling purposes in the editor. The extra wrapper means the `.is-layout-constrained > .alignwide` styles etc do not match on the block.

Image

### Steps to reproduce

1. Add Form block of any flavour to a post
2. Select the Form block and select wide or full alignment from the block toolbar
3. Note that the block's alignment doesn't visibly change

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### PR DESCRIPTION
**Pull request by talldan**
Fixes #41202

## Proposed changes:
Removes the wrapping `<div>` element from the form block, and tidies up the component, removing all use of Higher Order Components.

Doing this should fix wide/full alignments for the form block.

The wrapping div was being inserted by the `withThemeProvider` HOC. That HOC sets lots of CSS vars on this wrapper div. Removing this HOC and using `ThemeProvider` inline makes it easier to pass a `targetDom` prop with a reference to the block wrapper element, and it results in the CSS vars being added to the block wrapper instead.

After that I moved all the other HOCs inline, as they add quite a lot of unnecessary complexity.

This is best reviewed with white space hidden, as there's a big indentation change, it makes the diff a lot less intimidating!

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
1. Add the contact form block
2. Select a variation
3. Try changing the form to wide/full alignments and see that it now works
4. Try changing a range of styles on the form and on the inner elements
5. Switch between trunk and this branch and compare whether it works the same
6. Let me know if you see any bugs!

### CODE REVIEW

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 1]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+				blockType: getBlockType && getBlockType( name ),
+				canUserInstallPlugins: canUser( 'create', 'plugins' ),
+				defaultVariation: getDefaultBlockVariation && getDefaultBlockVariation( name, 'block' ),
+				variations: getBlockVariations && getBlockVariations( name, 'block' ),
+				hasInnerBlocks: innerBlocks.length > 0,
+				postAuthorEmail: authorEmail,
+			};
+		},
+		[ clientId, name ]
+	);
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:122]: withInstanceId, withSelect and withDispatch moved to hooks.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 2]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+	const [ isPatternsModalOpen, setIsPatternsModalOpen ] = useState( false );
+	const wrapperRef = useRef();
+	const innerRef = useRef();
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:125]: The `wrapperRef` is for `ThemeProvider` and its `targetDom` prop.

The `innerRef` is replacing the `fowardRef` that wrapped the component and was used for `withStyleVariables`. Now that the logic from that HOC is moved into the component, `forwardRef` isn't needed and an internal ref can be used instead.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 3]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
-				window.location.search.indexOf( 'showJetpackFormsPatterns' ) !== -1
-			) {
-				setIsPatternsModalOpen( true );
-			}
-			// eslint-disable-next-line react-hooks/exhaustive-deps
-		}, [] );
+		selectBlock( clientId );
+	};
 
-		const renderSubmissionSettings = () => {
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:162]: This was only used in one place, so I moved it inline.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 4]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+			elt = (
+				<ContactFormPlaceholder
+					changeStatus={ changeStatus }
+					isModuleActive={ isModuleActive }
+					isLoading={ isChangingStatus }
+				/>
 			);
-		};
-
-		const renderVariationPicker = () => {
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:216]: Again, this was only used in one place, so it's moved inline.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 5]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+								return pattern.content.indexOf( 'jetpack/contact-form' ) !== -1;
+							} }
+							clientId={ clientId }
+						/>
+					</Modal>
+				) }
+			</div>
+		);
+	} else {
+		const style = window.jetpackForms.generateStyleVariables( innerRef.current );
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:249]: This is the `withStyleVariables` HOC moved in line. It's nice that it can be moved into this branch of the `if` statement.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 6]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
-			submitButton.attributes.lock = lock;
-		}
-
-		return {
-			blockType: getBlockType && getBlockType( props.name ),
-			canUserInstallPlugins,
-			defaultVariation: getDefaultBlockVariation && getDefaultBlockVariation( props.name, 'block' ),
-			variations: getBlockVariations && getBlockVariations( props.name, 'block' ),
+	return (
+		<ThemeProvider targetDom={ wrapperRef.current }>
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:364]: This is `withThemeProvider` moved inline.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 7]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+							<PanelBody title={ __( 'Creative Mail', 'jetpack-forms' ) } initialOpen={ false }>
+								<NewsletterIntegrationSettings />
+							</PanelBody>
+						</>
+					) }
+				</InspectorControls>
 
-		return <div { ...blockProps }>{ elt }</div>;
+				<div className={ formClassnames } style={ style } ref={ innerRef }>
+					<InnerBlocks
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/edit.js:353]: Can probably also reduce these two `<div>` elements down to one with `useInnerBlocksProps`.

Comment (ntsekouras) [reply projects/packages/forms/src/blocks/contact-form/edit.js:353]: That would be good to do. There are just two css rules to change too with `block-editor-inner-blocks`.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 8]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+				const lock = { move: false, remove: true };
+				submitButton.attributes.lock = lock;
+			}
 
-		const isSalesForceExtensionEnabled =
-			!! window?.Jetpack_Editor_Initial_State?.available_blocks[
-				'contact-form/salesforce-lead-form'
-			];
+			return {
+				blockType: getBlockType && getBlockType( name ),
```
Comment (ntsekouras) [inline projects/packages/forms/src/blocks/contact-form/edit.js:113]: It seems there are some weird checks like this ( if selector is available ) and I believe it's just legacy code. The APIs checked are for years in WP and I believe it's safe to remove and simplify.

Another example is this [effect](https://github.com/Automattic/jetpack/pull/41274/files#diff-0048b4bd8ab00791237cc8a6b752332593a1e3d6e411b60e2d2fe983205eae72L143) that can be removed.

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 9]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
+		blockType,
+		canUserInstallPlugins,
+		defaultVariation,
+		variations,
+		hasInnerBlocks,
+		postAuthorEmail,
+	} = useSelect(
+		select => {
+			const { getBlockType, getBlockVariations, getDefaultBlockVariation } =
+				select( 'core/blocks' );
```
Comment (ntsekouras) [inline projects/packages/forms/src/blocks/contact-form/edit.js:98]: Nit: we can start using `store as blockEditorStore`, etc..

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 10]
```diff
@@ -72,332 +72,299 @@ const PRIORITIZED_INSERTER_BLOCKS = [ ...map( validFields, block => `jetpack/${
...
-						variations={ filter( variations, v => ! v.hiddenFromPicker ) }
-						onSelect={ ( nextVariation = defaultVariation ) => {
-							setVariation( nextVariation );
-						} }
-					/>
-					<div className="form-placeholder__footer">
-						<Button variant="secondary" onClick={ () => setIsPatternsModalOpen( true ) }>
-							{ __( 'Explore Form Patterns', 'jetpack-forms' ) }
+		}
+	} else if ( ! hasInnerBlocks && registerBlockVariation ) {
```
Comment (ntsekouras) [inline projects/packages/forms/src/blocks/contact-form/edit.js:192]: Let's remove `registerBlockVariation`. Related [comment](https://github.com/Automattic/jetpack/pull/41274/files#r1926618292)

File: projects/packages/forms/src/blocks/contact-form/edit.js (hunk 4 above)
Comment (ntsekouras) [reply projects/packages/forms/src/blocks/contact-form/edit.js:216]: I think it would be even better to make this a separate component too. Half of the calls to store are for the picker.

**Comment by simison** [comment]
Let's get this in soon to avoid too much rebase hassle; some of the changes might be fine for small follow-up PRs, for example.

**Review by simison — COMMENTED** [review]
Haven't reviewed code but did a bunch of smoke-testing, and this is working well.

Something I didn't test yet but wanted to was RTL support and if this improves things, see issue:
- https://github.com/Automattic/jetpack/issues/40737

**Review by edanzer — APPROVED** [review]
Nice PR! The resulting code after these changes is so much nicer to to work with. Really nice to remove all the HOCs and modernize the code. Good tip on white space removal - was otherwise impossible to follow the code changes here.

I tested this thoroughly and was unable to 'break' form styles or cause styling issues. I'm actually a bit surprised given lots of code changes and the removal of a major parent div. But that's great.

Things I tested: inserting editing a wide range of form fields; adjusted padding, margin on the form; shifting form field into multiple columns using 50% width on the field; adjusting label and input styles; alignment settings (only the button has this I think); few different themes; RTL language in the editor (Hebrew). 

There was chatter this might resolve a button alignment issue ([issue](https://github.com/Automattic/jetpack/issues/38779), [pending fix](https://github.com/Automattic/jetpack/pull/41139)), but this PR did not have an effect on that for me.

I was also trying to think hard if and how any of these changes might cause issues with backwards compatibility for existing forms, but I can't see anything myself, particularly given the changes are confined to the editor and not the frontend for the block.

@simison - you also mentioned an [issue](https://github.com/Automattic/jetpack/issues/40737) with form styles breaking for RTL, but from what I can see that issue affects the frontend and should not be affected here? Since I was test RTL anyways, I did check frontend. Oddly I was unablee to duplicate the reported issues. Not sure if I missing something, or another PR affected that. 

I would agree with @simison that it would be good to get this out quick-ish to avoid rebase issues, and maybe defer other small improvements to follow ups. Lots of pending form-related PRs. 

Anyway, given everything above, looks good here!

File: projects/packages/forms/src/blocks/contact-form/edit.js (hunk 10 above)
Comment (talldan) [reply projects/packages/forms/src/blocks/contact-form/edit.js:192]: @ntsekouras Thanks so much for the comments. I can work on another follow up PR to address these.
