### PR TITLE
Move AMP rendering of [youtube] shortcode to Jetpack from AMP plugin

### LINKED ISSUE #3309: Migrate Jetpack shortcode handling out of AMP plugin and into Jetpack
The AMP plugin includes shortcodes for several various embed handlers, including:

* `tweet`
* `vimeo`
* `soundcloud`
* `youtube`
* `dailymotion`
* `instagram`
 
For example, the AMP plugin includes a `vimeo` shortcode as part of its `AMP_Vimeo_Embed_Handler` for historical reasons, but over time more and more Jetpack code has been moved from the AMP plugin to… Jetpack. See #1021. This code needs to be extracted from the AMP plugin to move over to Jetpack. All such shortcode handling needs to be moved to Jetpack since the shortcodes are only being registered for AMP responses, leaving non-AMP pages without any shortcode defined.

----
Hi there!

I am trying to convert my website's theme to be fully AMP compatible. 

In the blog posts from my website, we use the Jetpack Vimeo shortcode. As the [documentation](https://en.support.wordpress.com/videos/vimeo/) states, we can use the shortcode by providing the URL or the video ID. We have used the shortcode exclusively using the [vimeo 123456] format, and it has worked as intended so far.

While testing the AMP version of my site, I noticed that the Vimeo videos were not showing. Further debugging took me to the AMP plugin, to the file `includes/embeds/class-amp-vimeo-embed.php`, to the function `shortcode` in line 71.

```php
public function shortcode( $attr ) {
	$video_id = false;

	if ( isset( $attr['id'] ) ) {
		$video_id = $attr['id'];
	} elseif ( isset( $attr['url'] ) ) {
		$video_id = $this->get_video_id_from_url( $attr['url'] );
	} elseif ( isset( $attr[0] ) ) {
		$video_id = $this->get_video_id_from_url( $attr[0] );
	} elseif ( function_exists( 'shortcode_new_to_old_params' ) ) {
		$video_id = shortcode_new_to_old_params( $attr );
	}

	if ( empty( $video_id ) ) {
		return '';
	}

	return $this->render(
		[
			'video_id' => $video_id,
		]
	);
}
```
The issue here is that the way the Jetpack documentation says it's possible to use the shortcode there is no need to use an `id` or `url` attribute, so the first two if statements do not apply to my case. Now, the third statement applies because I have submitted the Vimeo ID to the shortcode, and therefore `$attr[0]` is set. However, the statement assumes that I have passed a URL, as it calls `get_video_id_from_url`, where as I have passed an ID. 

I think this shortcode function needs to parse the `$attr` variable first, similar to how Jetpack does it:

```php
$attr = array_map(
	'intval',
	shortcode_atts(
		array(
			'id'       => 0,
			'width'    => 0,
			'height'   => 0,
			'autoplay' => 0,
			'loop'     => 0,
		),
		$atts
	)
);

if ( isset( $atts[0] ) ) {
	$attr['id'] = jetpack_shortcode_get_vimeo_id( $atts );
}

if ( ! $attr['id'] ) {
	return '<!-- vimeo error: not a vimeo video -->';
}
```

My other option is to do a search and replace on all my posts, but I think making the function be compatible with Jetpack's documentation would be easier.

Thanks!

### PR DESCRIPTION
**Pull request by kienstra**
#### Summary

This moves the AMP handling of the `[youtube]` shortcode from the [AMP plugin](https://github.com/ampproject/amp-wp/blob/b0bd40c18ce61741a366d54a9297dc440bf4330d/includes/embeds/class-amp-youtube-embed-handler.php#L138) to Jetpack. Very similar to #13921, but for `[youtube]` instead of `[vimeo]`.

Fixes https://github.com/ampproject/amp-wp/issues/3309

#### Changes proposed in this Pull Request:

* Apply the `[youtube]` shortcode handling [from the AMP plugin](https://github.com/ampproject/amp-wp/blob/b0bd40c18ce61741a366d54a9297dc440bf4330d/includes/embeds/class-amp-youtube-embed-handler.php#L138)
* Only refactor existing non-AMP `[youtube]` shortcode logic for reuse with the AMP shortcode, no intended change to it

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
This is a new feature for Jetpack, but moved from the AMP plugin

#### Testing instructions:
1. Ensure that `wp-config.php` has `define( 'JETPACK_DEV_DEBUG', true);`
2. In `/wp-admin`, in the Jetpack 'Settings' page, and in the 'Writing' tab, ensure this is toggled on:

jetpack-here

3. Fetch this PR's branch
4. Clone the AMP plugin 
```
$ git clone --recursive https://github.com/ampproject/amp-wp.git amp && cd amp
```
5. Fetch this PR of the AMP plugin, which deactivates the AMP plugin's `[youtube]` shortcode callback: https://github.com/ampproject/amp-wp/pull/3678
6. Do `$ npm install && composer install`
7. Activate the AMP plugin
8. Create a new post with a Shortcode block
9. Add a shortcode, like:
```
[youtube https://www.youtube.com/watch?v=_Oh12ROTQCE]
```
10. Preview the front-end of the AMP URL, like by adding `&amp` or `?amp`to the URL, and look at how the Vimeo shortcode looks
11. `checkout` the `master` branch of Jetpack, not this PR's branch
12. Preview the front-end of the AMP URL, and notice how the Vimeo shortcode looks
13. Expected: The shortcode should look the same, whether using this PR's branch, or the Jetpack plugin's `master` branch
14. Test more shortcodes under the [More Examples heading here](https://en.support.wordpress.com/videos/youtube/)

## Before

amp-pr-before

## After

amp-pr-after

#### Proposed changelog entry for your changes:
Migrate AMP-conversion of `[youtube]` shortcode to Jetpack from the AMP plugin

### CODE REVIEW

**Comment by kienstra** [comment]
**Separate PRs?**

Hi @jeherve,
Hope you had a great weekend.

Is it alright to open a separate PR for each shortcodes to migrate to Jetpack?

If it's alright, there are [4 more AMP shortcodes](https://github.com/ampproject/amp-wp/issues/3309#issue-495949833) after this that we'd like to migrate to Jetpack. 

Though this isn't urgent, I know reviewing them can be a lot of work.

Also, let me know if you'd like me to fix the [Code Climate issues](https://codeclimate.com/github/Automattic/jetpack/pull/14010).

Thanks, Jeremy!

**Comment by jeherve** [comment]
> Is it alright to open a separate PR for each shortcodes to migrate to Jetpack?

That's absolutely fine, yes. In fact, separate PRs are better I think, they're easier to review and to work on.

File: modules/shortcodes/youtube.php [hunk 1]
```diff
@@ -365,16 +294,203 @@ function youtube_id( $url ) {
...
+/**
+ * Gets the video ID from the URL.
+ *
+ * @since 8.0.0
+ *
+ * @param string $url The YouTube URL.
+ *
+ * @return string|bool The video ID based on that URL, or false.
+ */
+function get_amp_youtube_id_from_url( $url ) {
```
Comment (jeherve) [inline modules/shortcodes/youtube.php]: We currently have a `jetpack_get_youtube_id` function one can use to get an ID from a YouTube URL. Do you think it would be helpful to you here, or are there changes from `get_amp_youtube_id_from_url` you think we should bring to `jetpack_get_youtube_id`? In any case, I think it'd be nice if we only had one function to take care of that.

https://github.com/Automattic/jetpack/blob/792b26b5539d07cc35fdd93567942f2ad481eef2/functions.compat.php#L20

**Review by jeherve — CHANGES_REQUESTED** [review]

File: modules/shortcodes/youtube.php (hunk 1 above)
Comment (kienstra) [reply modules/shortcodes/youtube.php]: Great point, I didn't see that function.

Comment (kienstra) [reply modules/shortcodes/youtube.php]: https://github.com/Automattic/jetpack/pull/14010/commits/d7c05647435878c32ee1bece9814c4c933bad32e uses `jetpack_get_youtube_id()` instead of the custom function ported from AMP. 

There doesn't look to be an regression from this. It even passed this unit test when substituting `jetpack_get_youtube_id` for `get_amp_youtube_id_from_url()` on [this line](https://github.com/Automattic/jetpack/pull/14010/commits/d7c05647435878c32ee1bece9814c4c933bad32e#diff-7835daad42d569641fcb9ae94cce9f51L280).

File: modules/shortcodes/youtube.php [hunk 2]
```diff
@@ -365,16 +294,162 @@ function youtube_id( $url ) {
...
  */
 function youtube_shortcode( $atts ) {
-	return youtube_id( ( isset( $atts[0] ) ) ? ltrim( $atts[0], '=' ) : shortcode_new_to_old_params( $atts ) );
+	if (
+		class_exists( 'Jetpack_AMP_Support' )
+		&& Jetpack_AMP_Support::is_amp_request()
+	) {
+		return jetpack_amp_youtube_shortcode( $atts );
+	} else {
+		return youtube_id( ( isset( $atts[0] ) ) ? ltrim( $atts[0], '=' ) : shortcode_new_to_old_params( $atts ) );
```
Comment (jeherve) [inline modules/shortcodes/youtube.php]: What do you think about setting the URL at the beginning of the `youtube_shortcode` function, so you don't have to repeat that `isset( $atts[0] ) ) ? ltrim( $atts[0], '=' ) : shortcode_new_to_old_params( $atts )` twice (here and in the `jetpack_amp_youtube_shortcode` function)?

**Review by jeherve — CHANGES_REQUESTED** [review]

File: modules/shortcodes/youtube.php [hunk 3]
```diff
@@ -365,16 +294,162 @@ function youtube_id( $url ) {
...
+function jetpack_amp_youtube_shortcode( $atts ) {
+	$url = ( isset( $atts[0] ) ) ? ltrim( $atts[0], '=' ) : shortcode_new_to_old_params( $atts );
+	if ( empty( $url ) ) {
+		return '';
+	}
+
+	$video_id = jetpack_get_youtube_id( $url );
+	if ( empty( $video_id ) ) {
+		return sprintf(
+			'<a href="%s" class="amp-wp-embed-fallback">',
```
[the remark this answers is not in the document]
Comment (kienstra) [reply modules/shortcodes/youtube.php]: Good point, https://github.com/Automattic/jetpack/pull/14010/commits/08c760b66e61ef4bbc1ce1dda96ff53f3e2c8d7f closes it.

File: modules/shortcodes/youtube.php (hunk 2 above)
Comment (kienstra) [reply modules/shortcodes/youtube.php]: That's a good idea. Is https://github.com/Automattic/jetpack/pull/14010/commits/51a5eb78c534d1c9b7c2edef2718b04d167fb5f4 what you had in mind?

File: modules/shortcodes/youtube.php [hunk 4]
```diff
@@ -181,87 +181,16 @@ function youtube_id( $url ) {
 	$url = youtube_sanitize_url( $url );
 	$url = wp_parse_url( $url );
 
-	$qargs = array();
-	if ( ! empty( $url['query'] ) ) {
-		wp_parse_str( $url['query'], $qargs );
-	} else {
+	$qargs = jetpack_shortcode_youtube_query_args( $url );
```
[the remark this answers is not in the document]
Comment (kienstra) [reply modules/shortcodes/youtube.php]: Yeah, that's a good idea. It's renamed in https://github.com/Automattic/jetpack/pull/14010/commits/eb7c5e77afe069463ded3731764e65aa51f0d839.

File: modules/shortcodes/youtube.php [hunk 5]
```diff
@@ -181,87 +181,16 @@ function youtube_id( $url ) {
...
+	if ( empty( $qargs ) ) {
 		return false;
```
[the remark this answers is not in the document]
Comment (kienstra) [reply modules/shortcodes/youtube.php]: Good idea. How does https://github.com/Automattic/jetpack/pull/14010/commits/bed7e2cd4ce363849e6b35b419342db965082b4a look?

File: modules/shortcodes/youtube.php (hunk 2 above)
Comment (kienstra) [reply modules/shortcodes/youtube.php]: That's a good idea, it should be more DRY. How does https://github.com/Automattic/jetpack/pull/14010/commits/51a5eb78c534d1c9b7c2edef2718b04d167fb5f4 look?

File: modules/shortcodes/youtube.php [hunk 6]
```diff
@@ -365,16 +294,159 @@ function youtube_id( $url ) {
...
+ *
+ * @param string $url The YouTube URL.
+ *
+ * @return string The AMP-compatible rendered shortcode.
+ */
+function jetpack_amp_youtube_shortcode( $url ) {
+	$video_id = jetpack_get_youtube_id( $url );
+	if ( empty( $video_id ) ) {
+		return sprintf(
+			'<a href="%s" class="amp-wp-embed-fallback"></a>',
```
Comment (jeherve) [inline modules/shortcodes/youtube.php]: What do you think about adding something to the link to be more descriptive? Even the URL alone may be nice I think.

```suggestion
			'<a href="%s" class="amp-wp-embed-fallback">%s</a>',
```

**Review by jeherve — CHANGES_REQUESTED** [review]
Nice edits, we are getting there I think. I only have one remark right now.

File: modules/shortcodes/youtube.php (hunk 6 above)
Comment (kienstra) [reply modules/shortcodes/youtube.php]: That's a good idea.

Comment (kienstra) [reply modules/shortcodes/youtube.php]: Ah, I might need to update a test for that.

**Review by jeherve — DISMISSED** [review]
This looks good to me. I'll merge on Monday after testing on WordPress.com as well. Thank you!

**Comment by kienstra** [comment]
Thanks, Jeremy! Have a great weekend.

**Review by jeherve — APPROVED** [review]
