### PR TITLE
VideoPress: Fix custom CSS classes removal

### LINKED ISSUE #28780: VideoPress: custom CSS class are removed from video block
Also, if I apply a CSS class to VideoPress Block, then the class is automatically getting removed there:

https://video.wordpress.com/v/8S2zYKqs

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #28780

## Proposed changes:

* The custom classes were removed because a transformation from the embed block added some aspect-ration classes. This cleanup was moved to the embed transform function and reduced to remove only the aspect-ration classes.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor
* Add an embed block with a VideoPress link (e.g. https://videopress.com/v/Ygmx4akX)
* Add a custom class to the embed block:

* Transform the block to a VideoPress block:

* Check that the custom class is not removed, but the other classes are:

* Publish the post and visit it
* Check that the custom class is added to the block (`figure` tag):

### CODE REVIEW

File: projects/packages/videopress/src/client/block-editor/blocks/video/transforms/index.tsx [hunk 1]
```diff
@@ -16,19 +16,26 @@ const transfromFromCoreEmbed = {
 		const guid = pickGUIDFromUrl( src );
 
 		/*
-		 * Do transform when the block
+		 * Don't transform when the block
```
Comment (lhkowalski) [inline projects/packages/videopress/src/client/block-editor/blocks/video/transforms/index.tsx:19]: Nice catch, misleading docs can hurt so much!

**Comment by lhkowalski** [comment]
Code change looks good. Going to test it now.

**Comment by lhkowalski** [comment]
I added an embed block and added a custom class to it:

Screen Shot 2023-02-09 at 18 05 51

After it, I transformed the block to a VideoPress one, and the class was there:

Screen Shot 2023-02-09 at 18 07 03

It's also being included on the frontend, as explained on the testing instructions:

Screen Shot 2023-02-09 at 18 08 25

**Review by lhkowalski — APPROVED** [review]
Working as expected. As a follow up, we may fix the reverse transformation, from VideoPress block to embed, as it's losing the classes as well.
