### PR TITLE
Social: Update the admin page for use by Editors and Authors

### LINKED ISSUE #38335: Publicize: editors cannot connect an account
### Impacted plugin

Jetpack

### Quick summary

Editors do not have access to the Publicize settings in wp-admin, and do not have a link to Jetpack Cloud to manage their social connections there instead.

### Steps to reproduce

1. Start with a site running the Jetpack plugin, and connected to WordPress.com.
2. Go to Jetpack > Settings > Sharing
3. Enable Publicize
4. Go to Users > Add New
5. Create a new user with the editor role
6. In a new browser, log in to the site with that new role.
7. In another tab, log in to another WordPress.com account of yours.
8. Go to Jetpack > Settings > Sharing
9. Connect your editor account to that other WordPress.com account.

### A clear and concise description of what you expected to happen.

Once the connection is complete, I expect I would find settings to connect my own social networks.

### What actually happened

`configCard()` isn't displayed at all:

Screenshot 2024-07-15 at 16 25 07

`Initial_State.socialInitialState.useAdminUiV1` returns `true`, because `Current_Plan::supports( 'social-connections-management' )` returns `true`.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by pablinos**
Fixes #38335

## Proposed changes:

This updates the Social admin page, so that it is rendered for Editors and Authors, so they can manage their connections outside of the editor.

Additionally, it updates the Jetpack settings logic, which used to enable the same functionality. The settings would still be displayed if someone could `publish_posts`, but it seems we must have broken this logic at some point, so the settings screen would be blank without the `manage_options` capability. With the new social admin page this is not needed anymore, but the logic checks the feature is enabled, just in case we need to swap back at some point.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Connect two accounts to a site, one being an admin account and another being an author or editor.
* On the admin account, check that you can still manage connections, change settings and the overall module state on the social admin page.
* Using the author/editor account, check that you can see the social admin page and manage connections
* Have the admin disable the Publicize module
* Check that the Social admin page is not rendered for the author/editor
* Swap from the Jetpack to Scoial plugin and ensure that it behaves in the same way

Author Account view with this change

CleanShot 2025-02-17 at 22 29 46@2x

Without this change the admin page isn't available to non-admins.

### CODE REVIEW

File: projects/packages/sync/src/class-main.php [hunk 1]
```diff
@@ -40,6 +40,30 @@ public static function configure() {
...
+	}
+
+	/**
+	 * Sets the Module custom capabilities.
+	 *
+	 * @param  string[] $caps Array of the user's capabilities.
+	 * @param  string   $cap  Capability name.
+	 * @return string[] The user's capabilities, adjusted as necessary.
+	 */
+	public static function module_custom_caps( $caps, $cap ) {
```
Comment (pablinos) [inline projects/packages/sync/src/class-main.php:55]: As I've said in the commit message. I'm not certain if this is the best place for it, but it seems the most natural shared package as the Modules class lives in Sync.

File: projects/js-packages/script-data/src/utils.ts [hunk 2]
```diff
@@ -128,3 +129,13 @@ export function isWpcomPlatformSite() {
...
 	return ! NON_SELF_HOSTED_TYPES.includes( getSiteData()?.host );
 }
+
+/**
+ * Check if the current user has a particular permission.
+ *
+ * @param permission - The feature to check.
+ * @return Whether the current user has that permission.
+ */
+export function canUser( permission: keyof CurrentUserData[ 'permissions' ] ): boolean {
```
Comment (pablinos) [inline projects/js-packages/script-data/src/utils.ts]: I couldn't get the typechecker to use the JSDoc types, it kept thinking `permission` was `any`, so I added the types in the code. We've got a weird mixture of JSDoc and TS now.

File: projects/packages/assets/src/class-script-data.php [hunk 3]
```diff
@@ -215,6 +215,10 @@ protected static function get_current_user_data() {
 		return array(
 			'display_name' => $current_user->display_name,
 			'id'           => $current_user->ID,
+			'permissions'  => array(
+				'manage_options' => current_user_can( 'manage_options' ),
+				'manage_modules' => current_user_can( 'jetpack_manage_modules' ),
+			),
```
Comment (pablinos) [inline projects/packages/assets/src/class-script-data.php]: I think these can be added via the connection initial state. It's probably something that we should look at it soon, and have the connection use script-data too.

**Comment by pablinos** [comment]
Tests are failing, I'll pick that up tomorrow, but it's probably still worth a look through in the meantime

File: projects/js-packages/script-data/src/types.ts [hunk 4]
```diff
@@ -33,6 +33,10 @@ export interface SiteData extends PublicSiteData, Partial< AdminSiteData > {}
 export interface CurrentUserData {
 	id: number;
 	display_name: string;
+	permissions: {
```
Comment (manzoorwanijk) [inline projects/js-packages/script-data/src/types.ts]: I think it's better to call it `capabilities` instead of `permissions` like what WP calls it.

File: projects/js-packages/script-data/src/utils.ts (hunk 2 above)
Comment (manzoorwanijk) [reply projects/js-packages/script-data/src/utils.ts]: A few suggestions here:
- I think calling it `currentUserCan` is better, as that is what it actually is.
- Let us name it `capability` instead of `permission`.
- I would type the param as `keyof CurrentUserData[ 'permissions' ] | ( string & {} )` to allow the auto-completion as well as allow any other strings as caps which we don't know upfront.

image

File: projects/packages/assets/src/class-script-data.php (hunk 3 above)
Comment (manzoorwanijk) [inline projects/packages/assets/src/class-script-data.php]: Why not simply use this?

```suggestion
			'permissions'  => $current_user->allcaps,
```

File: projects/plugins/jetpack/_inc/client/sharing/publicize.jsx [hunk 5]
```diff
@@ -61,14 +61,16 @@ export const Publicize = withModuleSettingsFormHelpers(
 				isOfflineMode = this.props.isOfflineMode;
 
 			const showUpgradeLink =
+				userCanManageModules &&
```
Comment (manzoorwanijk) [inline projects/plugins/jetpack/_inc/client/sharing/publicize.jsx:64]: I think we are going to get rid of this component soon, given that we now have a dedicated Social admin page.

**Review by manzoorwanijk — COMMENTED** [review]
This looks good but I have some suggestions for improvement and naming.

File: projects/js-packages/script-data/src/utils.ts (hunk 2 above)
Comment (pablinos) [reply projects/js-packages/script-data/src/utils.ts]: Thanks @manzoorwanijk, I was going to ask your thoughts on the type.

> any other strings as caps which we don't know upfront

That's the point though, is that we only want it to be the capabilities we know about, as they'll be the only ones available in the `permissions` object. I suppose other code could add them in? Could they then extend the type?

Comment (manzoorwanijk) [reply projects/js-packages/script-data/src/utils.ts]: Yeah, if we want to limit it, that is fine as well. The devs will then need to update the type accordingly. Then we can update `CurrentUserData` type to be

```ts
...
permissions: Record< 'manage_options' | 'manage_modules', boolean >;
...
```

File: projects/js-packages/script-data/src/types.ts (hunk 4 above)
Comment (pablinos) [reply projects/js-packages/script-data/src/types.ts]: Yes. The reason I called it permissions is that it's called that in [the current connection initial state](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/connection/src/class-rest-connector.php#L627), which gets added to by other packages etc.

Perhaps we should change it now we're updating things!

File: projects/packages/assets/src/class-script-data.php (hunk 3 above)
Comment (pablinos) [reply projects/packages/assets/src/class-script-data.php]: I don't think that will work for `jetpack_manage_modules` as it's a custom one handled with the map_meta_cap filter.

File: projects/js-packages/script-data/src/utils.ts (hunk 2 above)
Comment (pablinos) [reply projects/js-packages/script-data/src/utils.ts]: Great. I've updated that in 983f9f01ae993474901a07e139be3118e2ed00e0

File: projects/plugins/jetpack/_inc/client/sharing/publicize.jsx (hunk 5 above)
Comment (pablinos) [reply projects/plugins/jetpack/_inc/client/sharing/publicize.jsx:64]: Yeah I thought I'd update it for now

File: projects/packages/assets/src/class-script-data.php (hunk 3 above)
Comment (manzoorwanijk) [reply projects/packages/assets/src/class-script-data.php]: I think `$user->caps` should contain those extra caps.

File: projects/js-packages/script-data/src/utils.ts [hunk 6]
```diff
@@ -1,7 +1,8 @@
-import { AdminSiteData } from './types';
+import { AdminSiteData, CurrentUserData } from './types';
 
 /**
  * Values come from https://github.com/Automattic/jetpack/blob/128db0505a27dcdcdef5946d60f443173b2ef6cd/projects/packages/status/src/class-host.php#L240
+ * @type {Array<import('@automattic/jetpack-script-data').AdminSiteData['host']>}
```
Comment (manzoorwanijk) [inline projects/js-packages/script-data/src/utils.ts]: You don't need this as the TS type annotation is already set on like 7.

```suggestion
```

File: projects/js-packages/script-data/src/types.ts [hunk 7]
```diff
@@ -33,6 +33,7 @@ export interface SiteData extends PublicSiteData, Partial< AdminSiteData > {}
 export interface CurrentUserData {
 	id: number;
 	display_name: string;
+	capabilities: Record< 'manage_options' | 'manage_modules', boolean >;
```
Comment (manzoorwanijk) [inline projects/js-packages/script-data/src/types.ts]: Thinking about this a second time, I realize it may be better to have this as a separate interface which can be modified by [module augmentation](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation).

For example, if capabilities from the backend are added via some filter, we should provide the same mechanism for the front-end and that is what module augmentation does.

So, we can define the interface separately

```ts
export interface UserCapabilities {
	manage_options: boolean;
	manage_modules: boolean;
}
```

Then use it in `CurrentUserData`

```ts
export interface CurrentUserData {
	...
	capabilities: UserCapabilities;
}
```

Then someone can add the caps like this

```ts
declare module '@automattic/jetpack-script-data' {
	interface UserCapabilities {
		edit_others_posts: boolean;
	}
}
```

You will then get type-checking and auto-completions for the caps

image

**Review by manzoorwanijk — COMMENTED** [review]
This works pretty good.

I just have some additional code improvement suggestions and also a question:

Does this toggle description make sense for authors?
`When enabled, you’ll be able to connect...`
image

Should we use the same description here that we use for WPCOM where the module cannot be toggled?

So, in [this component](https://github.com/Automattic/jetpack/pull/41859/files#diff-afb482f0e766906f3917dad09e8ec3a44c0154c8ec920b5692122213b8e95ded), we can use something like this

```tsx
const hideToggle = is_wpcom || ! currentUserCan( 'manage_modules' );

<ToggleSection
	hideToggle={ hideToggle }
	// other props
>

<Text className={ styles.text }>
	{ hideToggle
		? __( 'Connect your social media accounts…', 'jetpack-publicize-components' )
		: __( 'When enabled, you’ll be able to connect…', 'jetpack-publicize-components' ) }
// Rest of the logic

File: projects/js-packages/script-data/src/types.ts (hunk 7 above)
Comment (pablinos) [reply projects/js-packages/script-data/src/types.ts]: Excellent, that's a good solution. Added in 908510e3ba

**Comment by pablinos** [comment]
> Should we use the same description here that we use for WPCOM where the module cannot be toggled?

Nice spot. For some reason I thought I'd already done that! Implemented in 31d151d00a

**Review by manzoorwanijk — DISMISSED** [review]
This works great now. Works fine on WPCOM too.

File: projects/js-packages/script-data/src/utils.ts (hunk 6 above)
Comment (pablinos) [reply projects/js-packages/script-data/src/utils.ts]: How strange! I don't remember adding that, and it isn't related to what I'm changing. Thanks, I'll remove it.

**Review by gmjuhasz — APPROVED** [review]
This works well for me per the description
