### PR TITLE
VideoPress: Fix minimum loop duration and default hover values

### LINKED ISSUE #29917: VideoPress: Persist hover duration and start point when default values are chosen
The initial values of the hover effect duration and start point are not persisted if the user does not change them manually.

https://user-images.githubusercontent.com/8486249/229877079-a38d04a2-0154-4bb2-a72d-145787d3b39b.mp4

### LINKED ISSUE #29919: VideoPress: Fix minimum loop duration and out-of-bounds values for hover effect
The minimum loop duration is not currently respected, and changing the max loop duration does not update the duration value when it gets out of bound:

https://user-images.githubusercontent.com/8486249/229898630-5aefdfcb-e0ea-4ce4-a980-ea28b4fee0f0.mp4

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #29917
Fixes #29919

## Proposed changes:

* Adds the default values when first enabling hover effect and checks for minimum loop duration

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor and add a VideoPress video block
* Go to the `Poster and preview` panel
* Enable the preview on hover feature and do not change the default values
* Save the post and reload
* Check the block attributes for the `previewAtTime` and `previewLoopDuration` values, they should be persisted with the default values
* Change the starting point to a value that makes the maximum loop duration value get below the current loop duration
* Check that the loop duration is updated to the max value

https://user-images.githubusercontent.com/8486249/229915226-0feebb08-9804-4e48-9bde-8af9501dc170.mp4

### CODE REVIEW

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx [hunk 1]
```diff
@@ -332,6 +332,12 @@ export function VideoHoverPreviewControl( {
 		Math.min( MAX_LOOP_DURATION, videoDuration - previewAtTime )
 	);
 
+	useEffect( () => {
+		if ( loopDuration > maxLoopDuration ) {
+			onLoopDurationChange( maxLoopDuration );
+		}
+	}, [ maxLoopDuration ] );
```
Comment (retrofox) [inline projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx]: The callback function should handle it, IMO. That's why I suggest that it may have only one callback to take both data: starting point and duration. It could be doable by passing an object.

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx [hunk 2]
```diff
@@ -430,11 +437,22 @@ export default function PosterPanel( {
...
+			};
+
+			// Add default values for the preview options on activation
+			if ( shouldPreviewOnHover ) {
+				newPosterData = {
+					previewAtTime,
+					previewLoopDuration,
+					...newPosterData,
+				};
+			}
```
Comment (retrofox) [inline projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx:453]: I'm still trying to figure out this part. The fundamental issue is the block doesn't provide default values. We can add them to the block definition in the blocks.json file. Something like...

```json
		"posterData": {
			"type": "object",
			"default": {
				"previewOnHover": false,
				"previewAtTime": 0,
				"previewLoopDuration": 5000
			}
		},
```

Comment (dhasilva) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx:453]: > block doesn't provide default values

It does:
https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx#L405-L407

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx (hunk 1 above)
Comment (retrofox) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx]: Instead of using the effect hook, I think it should be handled when the starting point changes, it's in the callback passed to the onDebounceChange property. Something like:

```es6
<TimestampControl
	label={ __( 'Starting point', 'jetpack-videopress-pkg' ) }
	onDebounceChange={ timestamp => {
		onPreviewAtTimeChange( timestamp );
		const max = Math.min( MAX_LOOP_DURATION, videoDuration - timestamp );

		setMaxLoopDuration( max );

		// Adjust loop duration if it's needed
		if ( loopDuration > max ) {
			onLoopDurationChange( max );
		}
	} }
/>
```

Comment (dhasilva) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx]: The callback is only called when the value changes, not when the max value changes, there is no callback for that.

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx (hunk 2 above)
Comment (retrofox) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx:453]: [These default values](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx#L405-L407) are handled at `< PosterPanel />` component level, but the `posterData` block attribute doesn't have values when it's just created.
So, out of the PosterPanel component context, `posterData` will be undefined.

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx (hunk 1 above)
Comment (retrofox) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx]: > The callback is only called when the value changes, not when the max value changes,

The `max` value is updated when the _value_(the starting point `previewAtTime`) changes:

```es6
const max = Math.min( MAX_LOOP_DURATION, videoDuration - timestamp );
setMaxLoopDuration( max );
```

>  there is no callback for that.

No, there isn't. The component has two properties for that: `onPreviewAtTimeChange` and `onLoopDurationChange`

Considering that the max value of the loop duration can change, we should recalculate the loop duration based on it:
```es6
// Adjust loop duration if it's needed
if ( loopDuration > max ) {
	onLoopDurationChange( max );
}
```

It does the same thing you suggested but avoids using the useEffect() hook.

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx (hunk 2 above)
Comment (dhasilva) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx:453]: > but the posterData block attribute doesn't have values when it's just created.

When `previewOnHover` is enabled, the `posterData` object is set to `{ previewOnHover: true }`.
What this change does is add the default values when enabling it if those are not already defined (they are added before the `...newPosterData`). It will not be undefined.

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx (hunk 1 above)
Comment (dhasilva) [reply projects/packages/videopress/src/client/block-editor/blocks/video/components/poster-panel/index.tsx]: Updated

**Review by retrofox — APPROVED** [review]
LGTM 🚢 !
