### PR TITLE
VideoPress: recognize admin actions to handle generated chapter

### LINKED ISSUE #27722: VideoPress: AutoGeneration chapter doesn't recognize when the track is deleted
* Upload a Chapter track file
* Confirm the app shows the chapter already added a notice

* Remove the chapter from the tracks list
* Confirm the Notice goes out
* However, the auto-generation chapter doesn't work. You have to do a hard refresh.

### LINKED ISSUE #29002: VideoPress: do not recognize auto-generated chapter when switching privacy
* Go to the block editor
* Add/edit a VideoPress video block
* Set privacy public
* Generate chapters from the description
* Set privacy public
* Save the post
* hard refresh
* Set privacy private
* Confirm the app says the video has already a chapter 

Image

### PR DESCRIPTION
**Pull request by retrofox**
~# branched off from https://github.com/Automattic/jetpack/pull/28797~

This PR iterates over the autogenerated chapter feature of the VideoPress video block:

* Refact the code that detects if the chapter has been auto-generated
* Recognize when the chapter is uploaded or removed to allow, or not, overwrite it.
* Move the logic to detect the autogenerated chapter from edit to sync hook

Fixes https://github.com/Automattic/jetpack/issues/27722
Fixes https://github.com/Automattic/jetpack/issues/29002

## Proposed changes:

* VideoPress: recognize properly admin actions to handle auto-generated chapter feature

### Other information:

- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

### Check uploaded/deleted chapter

* Go to the block editor
* Create/edit a video block
* Upload a chapter track, `en` language
Screen Shot 2023-02-16 at 18 00 55

* Save the tracks form
* Confirm the sidebar shows the message about not being possible to overwrite the chapter.

Screen Shot 2023-02-16 at 18 02 29

* Delete the chapter by clicking on the `Delete` link.
* Confirm the message goes away
* You can take a look at the debug() lines

Screen Shot 2023-02-16 at 18 04 53

### Check the auto-generated chapter

* Define the chapter in the video description
* Save the post
* Confirm the chapter is auto-generated

Screen Shot 2023-02-16 at 18 09 32

image

* Repeat the process of switching the block privacy. Confirm it keeps working as expected.
* debug() lines:

Screen Shot 2023-02-16 at 18 10 27

### CODE REVIEW

File: projects/packages/videopress/src/client/lib/video-tracks/index.ts [hunk 1]
```diff
@@ -19,6 +24,56 @@ export const TRACK_KIND_OPTIONS = [
...
+	// Try to anticipate the video privacy, based on the block attributes.
+	if ( params.isPrivate ) {
+		tokenData = await getMediaToken( 'playback', { guid: params.guid } );
+		queryString = '?' + new URLSearchParams( { metadata_token: tokenData?.token } ).toString();
+	}
+
+	let response = await fetch( fileUrl + queryString );
+
+	// If the file is private, and response is 403, try with the token.
+	if ( ! response.ok && response.status === 403 && params.guid ) {
```
Comment (lhkowalski) [inline projects/packages/videopress/src/client/lib/video-tracks/index.ts:63]: Good point. Even if the `param.isPrivate` is `false`, by receiving a `403` we have an indication that the privacy is set to private on the backend.

**Comment by lhkowalski** [comment]
Code change looks good. I am going to test it now.

**Comment by lhkowalski** [comment]
Testing on a Jetpack site.

Uploaded a chapter file and got the message on the sidebar, as expected:

Screen Shot 2023-02-17 at 11 55 04

Also could spot the debug messages related to detecting the chapters:

Screen Shot 2023-02-17 at 12 08 10

Confirmed the chapter generation:

Screen Shot 2023-02-17 at 12 14 32

After changing the video to private, the generation keeps working as expected:

Screen Shot 2023-02-17 at 12 19 08

Uploading new chapter files also works as expected on a private video.

---

Going to test on Atomic and Simple.

**Comment by lhkowalski** [comment]
Testing on an Atomic site.

Uploaded a chapter file and got the message on the sidebar, as expected. Also could spot the debug messages related to detecting the chapters:

Screen Shot 2023-02-17 at 12 44 23

Confirmed the chapter generation:

Screen Shot 2023-02-17 at 12 47 26

After changing the video to private, the generation keeps working as expected:

Screen Shot 2023-02-17 at 12 51 24

Uploading new chapter files also works as expected on a private video.

---

Going to test on Simple.

**Comment by lhkowalski** [comment]
Testing on a Simple site.

Uploaded a chapter file and got the message on the sidebar, as expected. Also could spot the debug messages related to detecting the chapters:

Screen Shot 2023-02-17 at 13 13 27

Confirmed the chapter generation:

Screen Shot 2023-02-17 at 13 17 00

After changing the video to private, the generation keeps working as expected:

Screen Shot 2023-02-17 at 13 18 42

Uploading new chapter files also works as expected on a private video.

**Review by lhkowalski — APPROVED** [review]
Code change looks great and the tests are good on Jetpack, Atomic and Simple.
