### PR TITLE
SSO: fixing authentication with custom login page URL's.

### LINKED ISSUE #17782: SSO doesn't work when the WP login URL is changed.
Changing the URL for `wp-login.php` is a popular security measure. It's usually done via third-party plugins (e.g. WPS Hide Login).

When somebody tries to authenticate via SSO, they get redirected back to `wp-login.php` instead of the new login URL.
Therefore, the final step of the SSO auth does not work.

#### Steps to reproduce the issue

1. Connect Jetpack, enable the Jetpack SSO module.
2. Install the WPS Hide Login plugin, replace the default login URL with a custom one.
3. Logout from your site.
4. Try to login using the SSO.

#### What I expected
Logged in successfully.

#### What happened instead
I was redirected to the default `wp-login.php` URL, which resulted in 404.

#### Suggested solution
Pass the `wp_login_url()` value from the Jetpack site to WP.com along with other SSO parameters.
Then return back to this correct URL instead of the default `wp-login.php`.
**Important: The solution needs to be properly reviewed before being implemented.**

### PR DESCRIPTION
**Pull request by sergeymitr**
If the login page URL has been changed from `wp-login.php` to a custom one, WP.com redirects users back to `wp-login.php`, which throws "error 404". Therefore, Jetpack SSO will not work.

This PR and D55722-code fix the issue by sending along the custom login URL (if there's one). Then WP.com will redirect users not to `wp-login.php`, but to that custom path.

Fixes #17782

#### Changes proposed in this Pull Request:
* Detect custom login page URL
* Pass it to WP.com along with other SSO data
* WP.com will use it to redirect the user back to the Jetpack site

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Connect Jetpack, enable SSO (Jetpack -> Settings -> Security -> WordPress.com login -> Allow users to log in...)
2. Install the [WPS Hide Login](https://wordpress.org/plugins/wps-hide-login/) plugin, set a custom login page URL (Settings -> WPS Hide Login).
3. Logout from the WP admin area, and try to login using SSO. After being redirected back to the Jetpack site, you should see the 404 page. You should not get logged into the admin area.
4. Switch to your sandbox and checkout the diff D55722-code. Make sure that the domain `wordpress.com` is mapped to the sandbox.
5. Go back to the custom login page URL and try to login using the SSO again. You should be successfully logged in and redirected to your site's `/wp-admin/`.

#### Proposed changelog entry for your changes:
* Jetpack SSO: support of custom login page URL's.

### CODE REVIEW

File: projects/plugins/jetpack/modules/sso.php [hunk 1]
```diff
@@ -1126,6 +1131,30 @@ public function is_user_connected( $user_id ) {
...
+		}
+
+		$site_url = trailingslashit( site_url() );
+
+		if ( 0 !== strpos( $login_url, $site_url ) ) {
+			// Something went wrong, we can't properly extract the custom URL.
+			return null;
+		}
+
+		return str_ireplace( $site_url, '', $login_url );
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/sso.php:1156]: Could you explain a bit why we need to do this? I'm not sure I understand.

**Review by jeherve — COMMENTED** [review]
I just have a question about `get_custom_login_url`. Maybe we could have some tests for it, that would also serve to introduce the different scenarios it aims to cover and correct?

File: projects/plugins/jetpack/modules/sso.php (hunk 1 above)
Comment (sergeymitr) [reply projects/plugins/jetpack/modules/sso.php]: Hi @jeherve, thanks for the review!
Good point about the unit test, I added it.

> Could you explain a bit why we need to do this? I'm not sure I understand.

The `wp_login_url()` function returns the full URL, including the domain name (e.g. `https://example.org/custom-login-page/`). We only need the `custom-login-page/` part of this, because it wouldn't be quite safe to pass the full URL to redirect the user to.

So first we check if we can actually extract that part by by removing the `site_url` from the beginning of the string (the `strpos()` condition).
If we can do that, we use `str_ireplace` to actually remove it.
In the end, function returns `custom-login-page/` only, which gets sent to WP.com

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 🚢
