### PR TITLE
Sharing: add a Mastodon sharing button

### LINKED ISSUE #7148: Sharing: issues decoding Social Logos font on pages including sharing buttons
```
Failed to decode downloaded font: wp-content/plugins/jetpack/_inc/social-logos/social-logos.eot?51b607ee5b5cb2a0e4517176475a424c
OTS parsing error: invalid version tag
```

screen shot 2017-05-08 at 22 49 16

I haven't been able to reproduce the issue yet. We've seen this happen in the past with [the Make theme](https://wordpress.org/themes/make/) and a Storefront child theme. In both cases, this was solved by adding the following to the theme's stylesheet:

```css
.share-icon {
    text-rendering: auto;
}
```

However this doesn't seem to work for all themes, and we've had 3 new reports in the past few days.

Reported here:
- https://wordpress.org/support/topic/failed-to-decode-downloaded-font/
- https://wordpress.org/support/topic/jetpack-sm-fonts-not-loading-console-error/
- https://wordpress.org/support/topic/ots-parsing-error-invalid-version-tag/
- https://wordpress.org/support/topic/invalid-version-tag-error/

Related:
- https://stackoverflow.com/q/34133808/1045686
- http://stackoverflow.com/q/34288778/1045686
- http://stackoverflow.com/q/31001842/1045686
- https://css-tricks.com/forums/topic/custom-fonts-returns-failed-to-decode-downloaded-font/

Internal discussion about the issue when it first popped up for Make:
- p1HpG7-3An-p2

The font face syntax we use is called [bulletproof font face syntax](http://blog.fontspring.com/2011/02/the-new-bulletproof-font-face-syntax/) and relies on CSS hacks to serve the right font format to the right browser. It can break as soon as you make the tiniest change.
Since this was created to help support IE7 and IE8, and since [WordPress will only support IE11+ soon](https://make.wordpress.org/core/2017/04/23/target-browser-coverage/), maybe we could just get rid of this altogether. Problem solved! 😄 

@jasmussen This is your territory. What would you say about it?

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #7148

## Proposed changes:

This introduces a new Mastodon sharing button:

image
Screenshot 2023-02-13 at 14 56 17
Screenshot 2023-02-13 at 14 58 56

### Notes

**Class name**

In the past, we once had to give a unique name to a sharing service's class (`Jetpack_Share_WhatsApp`) to avoid conflicting with an existing plugin that already extended the sharing module. I looked around a bit, but could not find any plugin that does that for Mastodon today; folks who want a sharing button on their site today use the "custom sharing button" option we provide in the sharing settings.

**Mastodon support**

This will only support Mastodon. There are many other ActivityPub clients out there, but Mastodon is the biggest one so far, and is one that does offer a standardized "sharing" interface via the web.

In the future, if other clients become more and more popular, we can consider supporting those as well.

**Custom instance support**

We do, however, want to allow site visitors to select on which instance they want to post. The sharing button will consequently need to support inputing an instance name.

**Publicize**

This adds a sharing button, to allow site visitors to manually share blog posts to a Mastodon instance. For automated posting to Mastodon, we track requests and will post updates in #7790.

Until this is implemented, one can use [the ActivityPub plugin](https://wordpress.org/plugins/activitypub/) to have your site publish all your posts to the Fediverse. You can then Boost those posts from your Mastodon / Fediverse account if you have one.

### To do

- [x] Add a first modal view where one can enter their instance URL (or maybe rather their full Mastodon username, and we'd pull the instance name from that.
- [x] Consider a different default message, maybe pulling in a post's tags as hashtags.
- [x] Add a filter so site owners can customize that default message.
- [x] Ensure the Mastodon sharing button can also be added and managed from the Calypso UI (at `https://wordpress.com/marketing/sharing-buttons/yoursite.com`). This will require a Calypso PR: https://github.com/Automattic/wp-calypso/pull/72876

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* pewaj1-3x-p2

## Does this pull request change what data or activity we track or use?
* No

## Testing instructions:

You'll want to start with a site that's connected to WordPress.com, or where you've enabled [Jetpack's Offline Mode](https://jetpack.com/support/development-mode/).

* Go to Jetpack > Settings > Sharing
* Enable the sharing buttons
* Go to Settings > Sharing
* Drag a Mastodon sharing button to one of the sharing areas.
    *  You will want with different button styles.
* Check that the button works on the frontend.

### CODE REVIEW

**Comment by jeherve** [comment]
@kraftbj As an active Mastodon user, I was wondering if you could give this a try, and let me know what you think of it?

It is a bit heavy with a full template page for the interstitial, but I figured it may be better that way.

**Comment by kraftbj** [comment]
I didn't dig into any of this, just initial thoughts:


2023-02-08 at 11 27 AM

The icon didn't resolve.

2023-02-08 at 11 27 AM

I like this. It *looks* right. The downside is if Mastodon's default theme changes, we need to keep up. But, it feels good to me.

2023-02-08 at 11 28 AM

Cool, but the tags should camel case or hyphen or something( see `#distributed work`)

**Comment by jeherve** [comment]
> The icon didn't resolve.

This is interesting, I'm not sure why this would happen. Do you happen to have another plugin that would load its own version of the social logos, maybe?
Do you see any errors in the console? Does this happen in a specific browser?

Edit: I see it on your site now. I should have checked :)

```
kraft.blog/:1 Failed to decode downloaded font: https://kraft.blog/wp-content/plugins/jetpack-dev/_inc/social-logos/social-logos.eot?5d3b4da4f6c2460dd842dbf9e0992ea6
kraft.blog/:1 OTS parsing error: invalid sfntVersion: 1882128384
```

I'll look into that. This reminds me of #7148.

> Cool, but the tags should camel case or hyphen or something( see #distributed work)

Ah yes, that's a good catch. I fixed that in abad01a7a846a0400633e952abfbaef982bbbad0

**Comment by jeherve** [comment]
> I'll look into that. This reminds me of #7148.

Do you have a way to disable Fontawesome in the Genesis Blocks plugin? In this linked issue, there was a suspicion that having multiple `@font-face` declarations could cause issues. I wonder if that could be it.

Although I do not really understand why this is only popping up now for you, and only for that one icon. If the browser "cannot decode downloaded font", why do we see the Twitter logo just fine? 🤔

**Comment by jeherve** [comment]
> I'll look into that. This reminds me of #7148.

I think I'll just take this opportunity to simplify things and get rid of eot. That's what we had considered back in 2016. We really only need `woff` and `woff2` these days, but I'll leave `ttf` as well for good measure. This dates back to times when we needed to support IE11. We do not need to worry about eot anymore. Removing it fixes the issue on your site, in Firefox, Chrome, Safari, and Edge.

I just pushed 84c2ecee17ef6d313c296959d0f21c06ead04950 to remove eot.

> Things are [shifting heavily toward WOFF](http://caniuse.com/#feat=woff) and [WOFF 2](http://caniuse.com/#feat=woff2)
-- https://css-tricks.com/snippets/css/using-font-face-in-css/#aa-practical-level-of-browser-support

Since that change is not really directly related to this PR, I'm happy to pull it into its own PR => #28849.

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+/**
+ * Class Mastodon_Modal
+ */
+class Jetpack_Mastodon_Modal {
+	/**
+	 * Mastodon SVG icon.
+	 *
+	 * @var string
+	 */
+	private static $svg = '<svg width="261" height="66" viewBox="0 0 261 66" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:17]: Would it make sense to put this image in the images directory, and read it with `file_get_contents()` if necessary instead of embedding it in the PHP file?

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+	/**
+	 * Decide whether the modal should be displayed.
+	 * We want to show it when the user clicks on the Mastodon share button,
+	 * thus loading a page with ?share=mastodon&nb=1.
+	 *
+	 * @return bool
+	 */
+	public static function should_display_modal() {
+		if (
+			// phpcs:disable WordPress.Security.NonceVerification.Recommended -- we only check if the query strings exist, we do not use them.
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php]: Not really a good reason. p9dueE-4z8-p2#we-re-not-using-the-submitted-data-just-the-fact-that-a-field-is-set

The good reason is that we only use this to display a UI, not to change anything on the site.

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+		}
+	</style>
+</head>
+<body class="sd-mastodon-modal">
+	<div class="sd-mastodon-modal__inner">
+		<h2 class="sd-mastodon-modal__title"><?php esc_html_e( 'Share to Mastodon', 'jetpack' ); ?></h2>
+		<div class="sd-mastodon-modal__logo">
+			<?php echo self::$svg; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- SVG is safe. ?>
+		</div>
+		<form action="" method="post">
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php]: The `action` attribute [shouldn't be empty in HTML5](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fs-action). If you want it to submit back to the same page, it should just be omitted.

Back in HTML 4 it was required and an empty string was ok, but the doctype used here is an HTML5 doctype.

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php [hunk 4]
```diff
@@ -153,6 +153,46 @@ public function get_share_title( $post_id ) {
...
+		 * @module sharedaddy
+		 * @since $$next-version$$
+		 *
+		 * @param string $tags     Comma-separated list of tags.
+		 * @param int    $post_id  Post ID.
+		 * @param int    $this->id Sharing ID.
+		 */
+		$tag_list = (string) apply_filters( 'jetpack_sharing_tag_list', implode( ', ', $tags ), $post_id, $this->id );
+
+		return html_entity_decode( wp_kses( $tag_list, null ), ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401 );
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: `wp_kses()` is documented as taking a `string[]|string` for its `$allowed_html` parameter, not `null`.

It looks like, assuming something doesn't blow up on getting passed null, that this will behave the same as the empty string, allowing a small default set of tags.

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php [hunk 5]
```diff
@@ -3041,3 +3081,125 @@ public function display_footer() {
...
+	 */
+	public $icon = '\f10a';
+
+	/**
+	 * Constructor.
+	 *
+	 * @param int   $id       Sharing source ID.
+	 * @param array $settings Sharing settings.
+	 */
+	public function __construct( $id, array $settings ) { // phpcs:ignore Generic.CodeAnalysis.UselessOverridingMethod.Found
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Why ignore the sniff instead of removing the unneeded overriding method?

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php [hunk 6]
```diff
@@ -3041,3 +3081,125 @@ public function display_footer() {
...
+		$post_link  = $this->get_share_url( $post->ID );
+		$post_tags  = $this->get_share_tags( $post->ID );
+
+		/**
+		 * Allow filtering the default message that gets posted to Mastodon.
+		 *
+		 * @module sharedaddy
+		 * @since $$next-version$$
+		 *
+		 * @param string  $share_url The default message that gets posted to Mastodon. This will get rawurlencoded.
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Why mention "This will get rawurlencoded"? Do filter hooks need to know how it's going to get processed to be sent to Mastodon?

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+				<?php esc_html_e( 'Enter the full URL of the Mastodon instance where you’d like to share this post.', 'jetpack' ); ?>
+			</label>
+			<input
+				required
+				aria-required="true"
+				type="url"
+				id="jetpack-mastodon-instance"
+				name="jetpack-mastodon-instance"
+				placeholder="<?php echo esc_url( 'https://mastodon.social' ); ?>"
+			/>
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:184]: I suspect a nice TODO would be to allow the user to save the value they enter for use as the default next time. But I'd be fine with that being done in a future PR.

**Review by anomiex — COMMENTED** [review]
Gave the code a once-over.

When I try the UI on a JN site

> Drag a Mastodon sharing button to one of the sharing areas.
> * You will want with different button styles.

When I select "Official buttons" I get tofu for the Mastodon button in the settings page. Frontend looks ok though.

**Comment by anomiex** [comment]
> When I select "Official buttons" I get tofu for the Mastodon button in the settings page.

Looks like there's special casing here that would need another case added:
https://github.com/Automattic/jetpack/blob/e8ac2a7943a87fae7dc76796cae874de305a3714/projects/plugins/jetpack/modules/sharedaddy/admin-sharing.js#L166-L172

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:17]: Right now I don't really imagine that logo will be used anywhere else, so I'm okay with hardcoding it in here. If we ever start using a full logo like that, I'll definitely move it out to its own file.

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 2 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php]: That's true. 3eb672f9a370f98fe8340d1b807ee7633555956c

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 3 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php]: Done in c1197e23a8ab9573874676c65a4e3718dc30c91e

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php (hunk 4 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Good point. I had copied from `get_share_title`. I updated both methods in 79ca98343bbd6fc98957c1c8a3c55c1d33fae72f

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php (hunk 5 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Because that's what we do for all the other sources in this file, and I copied and pasted one of the existing services and started from that? :)

I've removed the method entirely in bbba2e508f58d8f8bb13ea0aeca7d65205e2a1dd

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php (hunk 6 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Removed in e2b292b2a0506946cd9fd78c1dc6421f26850886

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 7 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:184]: Thta's a good point. Definitely something for a v2 though. Where would you suggest we save this? In localStorage?

**Comment by jeherve** [comment]
> When I select "Official buttons" I get tofu for the Mastodon button in the settings page.

Thanks for letting me know, I had missed that. I pushed a commit to fix it.

Also, I have to ask; does "tofu" mean something specific? It's the first time I hear this used and not referring to the soy-based food. :)

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 1 above)
Comment (anomiex) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:17]: I was thinking more that it would be easier to deal with as an actual SVG file than as a long PHP string.

File: projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php (hunk 7 above)
Comment (anomiex) [reply projects/plugins/jetpack/modules/sharedaddy/services/class-jetpack-mastodon-modal.php:184]: Good question. When I wrote the comment I had mistakenly thought this was like Publicize where it was the site owner using it, rather than the sharing buttons where readers are re-sharing.

**Comment by anomiex** [comment]
> Also, I have to ask; does "tofu" mean something specific? It's the first time I hear this used and not referring to the soy-based food. :)

Sorry. In this context it refers to the little box (sometimes with numbers in it) that's used as a placeholder when no font provides the character. See https://fonts.google.com/knowledge/glossary/tofu for example.

**Review by anomiex — APPROVED** [review]
Ok with this as it is, so I'll hit Approve. The remaining comments IMO are ok to ignore or to leave for a followup if you want.

**Comment by jeherve** [comment]
> Sorry. In this context it refers to the little box (sometimes with numbers in it) that's used as a placeholder when no font provides the character. See [fonts.google.com/knowledge/glossary/tofu](https://fonts.google.com/knowledge/glossary/tofu) for example.

Oh! TIL, I had no idea it was named like that. It all makes sense. Thank you!
