### PR TITLE
Content Options: Add a check for WooCommerce Shop page in order to exclude it from the is_archive check

### LINKED ISSUE #8835: Content Options: Featured Images setting affect WooCommerce products
If you uncheck "Display on blog and archives" under Content Options > Featured Images, it affects both the blog and shop.

#### Steps to reproduce the issue

1. Starting with a site with both WooCommerce products set up, and using a theme that supports content options
2. Under Content Options > Featured Images, uncheck "Display on blog and archives"

#### What I expected

That it will affect the blog posts only.

#### What happened instead

The setting also affects the shop pages generated by WooCommerce. They are technically archive pages, but it seems unexpected.

Originally reported as a theme issue here: 4888-wpcom-themes

User's report: 776624-zen

### PR DESCRIPTION
**Pull request by alaczek**
Fixes #8835.

#### Changes proposed in this Pull Request:

* Added a function that checks if WooCommerce Shop page is being displayed. It's a copy of a function we include in our WooCommerce compatible themes.

### Testing:
1. Activate a theme that supports Content Options, for example Lodestar or Shoreditch.
2. Activate WooCommerce and add a few products.
3. Go to Customizer > Content Options and make sure "Display on blog and archives" under Featured Images is checked.
4. Visit Shop page - the product images should be visible. Visit blog page - the featured images should be visible.
5. Go to Customizer > Content Options and uncheck "Display on blog and archives" under Featured.
6. Visit Shop page - the product images should be visible. Visit blog page - the featured images should not be visible.
7. Deactivate WooCommerce and check if Content Options are working as expected, and there aren't any errors or warnings.

### CODE REVIEW

File: modules/theme-tools/content-options/featured-images.php [hunk 1]
```diff
@@ -57,3 +58,22 @@ function jetpack_featured_images_remove_post_thumbnail( $metadata, $object_id, $
...
+ */
+function jetpack_is_shop_page() {
+	global $wp_query;
+
+	$front_page_id        = get_option( 'page_on_front' );
+	$current_page_id      = $wp_query->get( 'page_id' );
+	$is_static_front_page = 'page' === get_option( 'show_on_front' );
+
+	if ( $is_static_front_page && $front_page_id === $current_page_id  ) {
+		$is_shop_page = ( $current_page_id === wc_get_page_id( 'shop' ) ) ? true : false;
```
Comment (jeherve) [inline modules/theme-tools/content-options/featured-images.php]: Should we check that `wc_get_page_id` exists before to use it?

Comment (alaczek) [reply modules/theme-tools/content-options/featured-images.php]: You're totally right! There's another WooCommerce function in there too - `is_shop()`. I'll update shortly.
