### PR TITLE
AI Extension: handle errors from extended block actions

### LINKED ISSUE #31382: AI Assistant: show errors in the UI when something fails
We need to show the errors in the UI when something fails.
We can offer a message similar to what we do for the AI Assistant block, but we also should keep in mind that we are extending other blocks. It could be intrusive.

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #31382.

## Proposed changes:

* Add event handlers for the error events emitted by `SuggestionsEventSource`
* Create custom onError callback to display the error on the editor, [using native editor notice support](https://developer.wordpress.org/block-editor/how-to-guides/notices/#notices-in-the-block-editor)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* To test this, you need to force some errors on the backend; refer to the "How to force errors on the backend" section below to see how to do it
* With the backend changed to force an error return, go to the block editor
* Write some content on a paragraph
* Click the AI Assistant extension button and select some action:

Screen Shot 2023-06-21 at 19 31 38

* Since you are forcing an error on the backend, you will see a notice on the top of the editor:

Screen Shot 2023-06-22 at 15 22 07

* Change the `status` code returned on the backend error to the following values and repeat the test
   * 422
   * 429
   * 500
   * 503
* Each `status` code has it's own message on the frontend, so you will see different messages on each occasion

### How to force errors on the backend

* Sandbox your `public-api`
* If you are running this branch on JN, don't forget to point it to your sandbox
* Update the `jetpack-ai-query.php` file on your sandbox to add the following snippet:

```
return new \WP_Error( 'error_jetpack_ai', __( 'Generic error message.' ), [ 'status' => 503 ] );
```

* Add it as the first line of the function:

Screen Shot 2023-06-21 at 19 29 33

* You will test changing the `status` value, so keep the file open and ready to edit

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx [hunk 1]
```diff
@@ -142,6 +146,13 @@ export const withAIAssistant = createHigherOrderComponent(
 
 		return (
 			<>
+				{ suggestionError && (
+					<ErrorNotice
+						message={ suggestionError.message }
+						onRemove={ () => setSuggestionError( null ) }
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx]: Could we consider avoiding the arrow function here?

```suggestion
						onRemove={ setSuggestionError }
```

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/components/error-notice/index.tsx [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+
+/**
+ * React component to render a notice with a message.
+ *
+ * @param {ErrorNoticeProps} props - The props for the component.
+ * @returns {React.ReactElement } The Notice component.
+ */
+export default function ErrorNotice( { message, onRemove }: ErrorNoticeProps ): React.ReactElement {
+	return (
+		<Notice className="jetpack-ai-assistant__error-notice" status="warning" onRemove={ onRemove }>
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/components/error-notice/index.tsx]: `status` could be a component prop, with a `warning` value as default. just a comment.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts [hunk 3]
```diff
@@ -125,12 +149,68 @@ export default function useSuggestionsFromAI( {
...
+						onError( {
+							code: 'error_network',
+							message: __(
+								'It was not possible to process your request. Mind trying again?',
+								'jetpack'
+							),
+							status: 'info',
+						} );
+					} );
+				}
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts:207]: Could we expose this errors list in an isolated function based on the error code?
We can do that in a follow-up, no problem at all.

**Review by retrofox — CHANGES_REQUESTED** [review]
The notice is anchored at the top of the component:

image

Let's anchor it at the top of the post page. For instance:

image

The [Notice doc](https://developer.wordpress.org/block-editor/reference-guides/components/notice/) page has some cases of good and bad practices.

Btw, probably we'd like to implement the notices by using the [withNotice](https://developer.wordpress.org/block-editor/reference-guides/components/with-notices/) HOC.




https://developer.wordpress.org/block-editor/reference-guides/components/with-notices/

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts (hunk 3 above)
Comment (lhkowalski) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts:207]: Yeah, I think it's a good idea since we are using the same errors on the block as well, so we could reuse them on 2 places.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx (hunk 1 above)
Comment (lhkowalski) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx]: Going to create a small `clearSuggestionError` function to be used here.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts (hunk 3 above)
Comment (lhkowalski) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/hooks/use-suggestions-from-ai/index.ts:207]: Going to leave this for a followup so we can move forward with basic error handling.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx (hunk 1 above)
Comment (lhkowalski) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/ai-assistant/with-ai-assistant.tsx]: Was not necessary since using the native notice support made me remove the error state inside the hook.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/components/error-notice/index.tsx (hunk 2 above)
Comment (lhkowalski) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/components/error-notice/index.tsx]: I made it refer to `error.status`, that may be `error` or `info` so far.

**Review by retrofox — DISMISSED** [review]
Looks good to me! I believe this error handling is a great choice when compared to other alternatives available 🚀

**Review by retrofox — APPROVED** [review]
LGTM
