### PR TITLE
Social: Fix data store performance issues

### LINKED ISSUE #42441: Social: WordPress 6.8 Compatibility - Fix data manipulation within useSelect in select publicize-components components
### Issue

This is a sub-issue of https://github.com/Automattic/jetpack/issues/42421

Within the `publicize-components` package, there are various instances where the usage of `useSelect` will result in fairly bulky console warnings in WordPress 6.8, if script debug is enabled on a site, including:
-  `usePostMeta`, `useSocialMediaConnections`, `useIsSharingPossible`, `ConnectionManagement`, `getSocialSettings`
- More exist, these will be added to the parent issue.

These instances should be fixed.

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Fixes #42441 

Supercedes #42442 

This PR fixes the performance issues with social data store to fix the warnings for the same in WP 6.8.

The PR takes a different approach than #42442 to fix the root cause of the issue, which was that our selectors in the store returned the results like empty arrays `[]`, the result for `.map()` and `.filter()`, which have different reference each time, thus causing the data being flagged as changed.

## Proposed changes:

* Update the store selectors to use a constant empty array wherever needed to avoid creating an array with new reference each time.
* Wraps the dependent selectors with `createSelector` to have them changed only when the dependent data changes
* For some changes, where the manipulation was done inside `useSelect`, this PR moves that manipulation out of `useSelect` to avoid those warnings.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to connections management
* Confirm that you can add/update/delete connections
* Confirm that the changes reflect as expected
* Break a connection - for example, remove Jetpack from [here](https://www.facebook.com/settings/?tab=business_tools) for Facebook.
* Come back to connections management or reload the page
* If the connection test result doesn't return the broken status immediately, try marking that connections as shared.
* Confirm that the broken connections notice shows up in the editor
* Confirm that Social post UI works fine with custom message and custom media and SIG
* Schedule a few shares and wait for the list to update
* Confirm that the list updates correctly
* Confirm that you don't see the `useSelect` warnings anywhere related to social UIs

### CODE REVIEW

File: projects/js-packages/publicize-components/src/hooks/use-post-meta/index.js [hunk 1]
```diff
@@ -18,7 +23,7 @@ export function usePostMeta() {
 
 			const isPublicizeEnabled = meta.jetpack_publicize_feature_enabled ?? true;
 			const jetpackSocialOptions = meta.jetpack_social_options || {};
-			const attachedMedia = jetpackSocialOptions.attached_media || [];
+			const attachedMedia = jetpackSocialOptions.attached_media || DEFAULT_ATTACHED_MEDIA;
 			const imageGeneratorSettings = jetpackSocialOptions.image_generator_settings ?? {
```
Comment (pablinos) [inline projects/js-packages/publicize-components/src/hooks/use-post-meta/index.js]: Do you think we should have a DEFAULT_IMAGE_GENERATOR_SETTINGS  object too? That way we won't need to remember to list the individual properties in the dependency array.

Should we also have an empty object constant to handel the default for `jetpackSocialOptions`?

**Review by pablinos — COMMENTED** [review]
This works well. Just had one thought about the other elements of usePostMeta

File: projects/js-packages/publicize-components/src/hooks/use-post-meta/index.js (hunk 1 above)
Comment (manzoorwanijk) [reply projects/js-packages/publicize-components/src/hooks/use-post-meta/index.js]: Done in 57db8c947e4a6b5c99bcbf0ce6be013ac06924c9

**Review by pablinos — APPROVED** [review]
Works well. The warnings are gone, and the meta is still used, and saved correctly
