### PR TITLE
Likes: Bust iframe cache to facilitate string fix

### LINKED ISSUE #7958: Comment Likes: Like counts are not translated
#### Steps to reproduce the issue

1. Start on a site where Jetpack and its comment Likes modules are active.
2. Switch the site language to French.
3. Note that the strings for Comment Likes are translated into French:
https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bterm%5D=Liked+by&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
4. While the translation appears properly when a comment hasn't been liked yet, it is not correct for comments that have been liked at least once:

screenshot 2017-10-09 at 10 51 48

Reported in 693464-zen

### PR DESCRIPTION
**Pull request by hewsut**
We need to pull down new translations for comment likes.

Fixes #7958

#### Changes proposed in this Pull Request:

From the backend [when cache is busted]:
* New comment like strings with better context for translators.
* Denesting of some `if`s in `likes-rest.js`.

#### Testing instructions:

* Apply D8423-code
* Point widgets.wp.com to your SB.
* Clone this to your test site.
* Use a language that has translations for the new comment like strings.

#### Proposed changelog entry for your changes:
Fixed comment likes localization bugs.

### CODE REVIEW

File: modules/likes/jetpack-likes-master-iframe.php [hunk 1]
```diff
@@ -4,7 +4,7 @@
  * This function needs to get loaded after the like scripts get added to the page.
  */
 function jetpack_likes_master_iframe() {
-	$version = '20170629';
+	$version = '20171122v2';
```
Comment (vindl) [inline modules/likes/jetpack-likes-master-iframe.php]: I don't remember running into `v2` appended to date in rest of the codebase. Is there some specific reason for this, and could we just use `20171123` instead?

**Comment by vindl** [comment]
One thing I noticed while testing is that with new translations some longer strings are cropped due to fixed `iframe` width. This didn't occur with previous English translations, but could likely look broken in some other languages already.

oneotherperson

We can work around this by changing the width [here](https://github.com/Automattic/jetpack/blob/master/modules/likes/queuehandler.js#L305) to `100%` so the `iframe` assumes the width of parent container (in https://github.com/Automattic/jetpack/blob/master/modules/likes/queuehandler.js#L305). I can also spin up a separate PR for this if you'd like.

File: modules/likes/jetpack-likes-master-iframe.php (hunk 1 above)
Comment (vindl) [reply modules/likes/jetpack-likes-master-iframe.php]: Actually I think we can also use `JETPACK__VERSION` here to avoid the need to bump this manually in the future. Tested it and it seemed to work fine with new translations.

Comment (hewsut) [reply modules/likes/jetpack-likes-master-iframe.php]: > could we just use 20171123 instead?

At this point, sure, we're onto that date. I did `v2` as I seemed to cache a bad variant I tested with under `20171122`.

**Comment by hewsut** [comment]
> I can also spin up a separate PR for this if you'd like.

I am a little confused so, sounds good, let's do that if you would. I didn't see the issue on my test site:

screen shot 2017-11-26 at 10 37 25 pm

**Comment by vindl** [comment]
>  I am a little confused so, sounds good, let's do that if you would. I didn't see the issue on my test site:

Will do it. :+1: It only occurs when you have `one` instead of some one digit number (and `person` instead of `people`) due to higher number of characters.
