### PR TITLE
Widgets: if widget_media_image exists, flag migration as done

### LINKED ISSUE #7595: jetpack_migrate_image_widget runs on all page loads
It seems that 
Jetpack_Options::update_option( 'image_widget_migration', true );  https://github.com/Automattic/jetpack/blob/30cf0fa6188c4981ccd4323ad3cb4055a9d42093/modules/widgets/migrate-to-core/image-widget.php#L201

Is only run if the option is changed https://github.com/Automattic/jetpack/blob/30cf0fa6188c4981ccd4323ad3cb4055a9d42093/modules/widgets/migrate-to-core/image-widget.php#L186

This means that if the site had no image widget this code will never not run.

#### Steps to reproduce the issue

load a wp-admin page on a site with no image widget (the site had no sidebars and no widgets)

#### What I expected

Code to migrate images runs once

#### What happened instead

Code runs on every wp-admin page load.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #7595 

#### Changes proposed in this Pull Request:

* if the widget_media_image wasn't updated, maybe it already exists. If so, delete legacy option and set our flag so this code isn't always run

#### Testing instructions:

* delete `image_widget_migration` and test migrating an image widget from a previous WP version
* delete `image_widget_migration`
In both cases, the code should run once instead of every time WP Admin loads as is now

#### Proposed changelog entry for your changes:
Widgets: prevent code that migrated legacy Jetpack image widget to WordPress' new image widget from running on every WP Admin load.

### CODE REVIEW

File: modules/widgets/migrate-to-core/image-widget.php [hunk 1]
```diff
@@ -202,6 +202,12 @@ function jetpack_migrate_image_widget() {
 
 		// We need to refresh on widgets page for changes to take effect.
 		add_action( 'current_screen', 'jetpack_refresh_on_widget_page' );
+	} else {
+		$widget_media_image = get_option( 'widget_media_image' );
+		if ( is_array( $widget_media_image ) ) {
+			delete_option( 'widget_image' );
+			Jetpack_Options::update_option( 'image_widget_migration', true );
```
Comment (dereksmart) [inline modules/widgets/migrate-to-core/image-widget.php]: Any reason not to move this outside of the conditional completely?  Then we wouldn't need it twice in this conditional.

Comment (eliorivero) [inline modules/widgets/migrate-to-core/image-widget.php]: In this branch, if `widget_media_image` doesn't have data, `widget_image` won't be deleted.

Comment (dereksmart) [inline modules/widgets/migrate-to-core/image-widget.php]: I was just referring to setting the option flag

Comment (eliorivero) [inline modules/widgets/migrate-to-core/image-widget.php]: Same case, it's only set to true if widget data was found.

Comment (eliorivero) [inline modules/widgets/migrate-to-core/image-widget.php]: As per our talk yesterday in Slack, I've moved the line in b8d5ef341
