### PR TITLE
Payment Button Block: Use the shared ProductManagementControls

### LINKED ISSUE #23414: Payment Button Block: Replace the product management system with the Premium Content one
### Impacted plugin

Jetpack

### What

Second step in making all payment blocks use the same product management components.

### How

This is a follow up to https://github.com/Automattic/jetpack/issues/23412.

Once the Premium Content's product management system has been moved to a shared component, let's use it on the Payment Button block!

### LINKED ISSUE #23506: Payment Button Block: Unable to change plan if current plan does not exist
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Open the editor on a premium site with multiple payment plans.
2. Insert the Payment Button block.
3. Switch to the code editor.
4. Edit the block replacing the `planId` with a made-up product ID (e.g. `123456` or something).
  It should be enough to only change the first `planId` attribute which is what affects this issue.
5. Switch back to the visual editor.
6. Open the sidebar and try changing the plan.

### A clear and concise description of what you expected to happen.

For the Payment Button block's plan selection to be updated.

### What actually happened

The plan is not updated.

There is a console error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'price')
    at _.getFormattedPriceByProductId
```
It points to [`getFormattedPriceByProductId`](https://github.com/Automattic/jetpack/blob/61a7b7b81834321d48a060f4e72f786e694775a1/projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx#L309-L314), which on plan selection is called on [both the new and old product](https://github.com/Automattic/jetpack/blob/61a7b7b81834321d48a060f4e72f786e694775a1/projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx#L319-L330).
The old product does not exist, so `product.price` fails.

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes #23414
Fixes #23506

#### Changes proposed in this Pull Request:

* We now use the [Product Management Controls component](https://github.com/Automattic/jetpack/issues/23412) instead of having ad-hoc implementations of product management for each payment block.
* Cleaned up the code and refactored the block to a functional component.
* Removed the initial form for consistency between our different payment blocks.

#### Jetpack product discussion

None

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create or edit a Post.
* Add a Payments Block to the Post.
* You should not see a form above the button indicating to choose a plan.
* You should see the Product Management Controls.
* Change the subscription and save.
* Reload the editor, the subscription should be the one you've manually set.

You should also test a site that is on a free plan. In this case, you should see the upgrade nudge.

Also, test the Premium Content block. In this scenario, we should not see the membership controls for the main button, but any other Payment Button added should continue to work as expected.

#### Testing evidence, happy case
https://user-images.githubusercontent.com/1989914/159494023-9c5d7f82-6023-46f6-9356-a2bc4304746c.mp4

#### Testing evidence, Premium Content block nesting

https://user-images.githubusercontent.com/1989914/159494507-32b5ffb3-103b-4ecd-9d56-ec39a4fdc521.mp4

#### Testing evidence, Payments button on a free plan
https://user-images.githubusercontent.com/1989914/159495852-a8118fc0-6c31-4f4e-bdda-e0ccd426bbe3.mp4

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 1]
```diff
@@ -1,543 +1,68 @@
...
-		return (
-			<div className="membership-button__disclaimer">
-				<ExternalLink href="https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees">
-					{ __( 'Read more about Payments and related fees.', 'jetpack' ) }
-				</ExternalLink>
-			</div>
-		);
-	};
-
-	renderUpgradeNudges = () => {
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:376]: This feature will be re-implemented in a follow-up issue. This upgrade nudge only affects standalone WordPress sites that have the Jetpack plugin installed and are on a free Jetpack subscription.

The WPCOM upgrade nudge will still be shown as always.

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 2]
```diff
@@ -1,543 +1,69 @@
 /**
```
Comment (dsas) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:1]: Looking forward to resolving the merge conflict 🤣

**Review by dsas — COMMENTED** [review]
Just a minor thing, but while adding a new plan it still says premium-content

https://user-images.githubusercontent.com/93301/159734029-c2dfdbc5-fb46-4c40-8233-4c8472981646.mp4

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx (hunk 1 above)
Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:376]: I'll merge your branch into this one.

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:376]: > The [availability checks](https://github.com/Automattic/jetpack/pull/23580/files#diff-a41de8578e653f89cd1ace91e14f13ed157f6c27cd01c4dfa5c251de6bf9bf03R53) are used to determine if the block is showing the WPCOM nudge. Kind of not ideal, huh.

These checks can be simplified: https://github.com/Automattic/jetpack/pull/23580/files#r834136333
Since I'll be merging your branch into this one I'll apply the simplification here.

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:376]: Merged.

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:376]: I'm going to add the link to fees again since it won't be shown when a user doesn't have a paid Jetpack plan.

**Review by Copons — APPROVED** [review]
I've tested this quite a lot at this point, on all possible environments, with all conceivable variations.
Besides the [trivial change requested](https://github.com/Automattic/jetpack/pull/23545/files#r834160061), this LGTM!

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 3]
```diff
@@ -1,543 +1,107 @@
...
+ */
+import { icon, title } from './';
+import ProductManagementControls from '../../shared/components/product-management-controls';
+import { store as membershipProductsStore } from '../../store/membership-products';
+
+export default function Edit( { attributes, clientId, context, setAttributes } ) {
+	const { planId } = attributes;
+	const { isPremiumContentChild } = context;
+	const postLink = useSelect(
+		select => new URL( select( editorStore ).getCurrentPost().link ),
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:27]: This breaks in the site editor where `getCurrentPost()` is not set. 😞

**Comment by dsas** [comment]
When testing on a Jurassic Ninja site I got something a little different to the video above - the plan wasn't defaulted on the payment button, so I had to press the 'refresh' icon to select one.

1. Set-up a Jurassic Ninja site using this feature branch
2. Link jetpack etc
3. As part of FSE I connected stripe, created a plan etc
4. I created a new post
5. I added a payment button
6. It didn't automatically select the existing plan and it wasn't clear what I should do next.

https://user-images.githubusercontent.com/93301/160130822-75b0e300-1e0c-4c4e-8fcb-50ad3ca549b7.mov

I'll test in some more environments and update.

**Comment by Copons** [comment]
- Environments
  - [x] WPCOM Simple
  - [x] WPCOM Atomic
  - [x] WPCOM Atomic with Gutenberg deactivated
  - [x] Jetpack
  - [x] Jetpack with Gutenberg deactivated and on the oldest supported version of Core
- Plans
  - [x] WPCOM Simple Free
  - [x] WPCOM Simple Business
  - [x] WPCOM Atomic Business
  - [x] Jetpack Free
  - [x] Jetpack Complete
- Contexts
  - [x] Post editor
  - [x] Site editor
  - [x] Widgets editor (use regular Twenty Twenty-One)
  - [x] [Low priority] Widgets in Customizer (use regular Twenty Twenty-One)
  - [x] Front end
- Payments Scenarios
  - [x] Stripe not connected
  - [x] Stripe connected
  - [x] No payment plans
  - [x] Incorrect payment plan assigned to a block (e.g. the plan has been deleted after the block was created)
  - [x] One or more payment plans
- Gutenberg
  - [x] Migrate an old version of the block.
  - [x] Insert the block from scratch.

😰 

I've noticed a minor UI issue, unrelated to this PR. I'll file it separately:
> Toolbar control "Add product" doesn't work if there's the pre/post publish panel open.

---

> the plan wasn't defaulted on the payment button, so I had to press the 'refresh' icon to select one.

@dsas That's fixed by https://github.com/Automattic/jetpack/pull/23603/files#diff-f9320f13a7c5e60ad6f63b93e0c0b7cd1799da54f4350c1f64c627d2a517c249R29

**Comment by Copons** [comment]
The PR is ready to merge (pending a rebase requested by the GH actions), but we are holding it off until Monday. 🙂

**Comment by Copons** [comment]
r242591-wpcom
