### PR TITLE
Search: hide 'Media' from 'Excluded Post Types'

### LINKED ISSUE #24681: Search: media type is never returned even not set in excluded post type list
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

- Uncheck media from `excluded post typeq`
- Search for a media

### A clear and concise description of what you expected to happen.

Not so sure we should display media or not, but theoretically it should return media records.

### What actually happened

No media records showing up at all.

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium, Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #24681 

#### Changes proposed in this Pull Request:
The PR proposes changes that hide 'Media' from the 'Excluded Post Types', because we do not index 'Media' post type at all, meaning they are never returned from the search API.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Go to a site with Jetpack Search subscription
* Open Customizer `/wp-admin/customize.php`, find Jetpack Search section
* Ensure you do not see 'Media' from the 'Excluded Post Types'
* Open Customberg `/wp-admin/admin.php?page=jetpack-search-configure`
* Ensure you do not see 'Media' from the 'Excluded Post Types'

|Customizer|Customberg|
|-----------|-------------|
|image|image|

### CODE REVIEW

File: projects/packages/search/src/customizer/customize-controls/class-excluded-post-types-control.php [hunk 1]
```diff
@@ -51,7 +51,7 @@ public function enqueue() {
 	 * @return array $post_types An array of strings representing post type names.
 	 */
 	public function get_arrayed_value() {
-		return explode( ',', $this->value() );
+		return empty( $this->value() ) ? array() : explode( ',', $this->value() );
```
Comment (kangzj) [inline projects/packages/search/src/customizer/customize-controls/class-excluded-post-types-control.php:54]: This is an ancient issue, where empty string is exploded to `array('')`

**Review by bluefuton — APPROVED** [review]
🚢 Tests out well for me.

Noticed while testing that Customizer no longer fetches results on load, so filed a separate bug for that: https://github.com/Automattic/jetpack/issues/25000.
