### PR TITLE
OpenTable Block: Add mobile fallback when using wide style

### LINKED ISSUE #16156: OpenTable block: Style "wide" is not responsive.
The OpenTable embed has different layouts including a "Wide 840x150px" version with a width of 840 pixels. I noticed that this block is being cut off on mobile with no way of accessing the hidden parts of the form (including the button).

#### Steps to reproduce the issue

1. Add an OpenTable block to a post or a page. Pick the "Wide 840x150px" block style.
2. Visit the post/page on desktop. 
3. Visit the post/page on mobile. Compare to the desktop version and notice how part of the form is cut off and inaccessible.

Tested on Safari/iPhone 11, but the issue is also visible when resizing the browser on desktop.
Themes: TwentyTwenty, Stratford.

IMG_1673

#### What I expected
I expected the form would be responsive and all fields accessible across all devices.

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes #16156

#### Changes proposed in this Pull Request:
* When the page is being loaded via mobile and the current style is `wide`, the embed URL is switched to the standard theme and an `is-style-mobile` CSS class added. This results in widget more easily being fit on smaller viewports. 
* The choice to switch the widget entirely was made to avoid duplicating markup and scripts for the block. The trade-off being this approach will not help desktop users who resize their browser window smaller than the `wide` style.

#### Does this pull request change what data or activity we track or use?
No changes.

#### Testing instructions:
1. Apply this PR branch
2. Create a post and add an OpenTable block to it
3. Select the wide style for the block and save the post
4. Visit the post on the frontend.
5. Spoof the user agent in your browser to some kind of mobile device and reload the page. 
6. Ensure that the standard theme widget is displayed instead of the wide style.

| Before | After |
| --- | --- |
| Screen Shot 2020-09-04 at 7 58 25 pm | Screen Shot 2020-09-04 at 7 57 54 pm |

#### Proposed changelog entry for your changes:
* OpenTable Block: Display wide style widget as standard on mobile

### CODE REVIEW

**Comment by getdave** [comment]
@aaronrobertshaw are you going to be merging this one or shall the current @Automattic/ajax janitor rotation take this over?

**Comment by aaronrobertshaw** [comment]
@getdave You're welcome to though I was planning on merging this one just as soon as it got Crew approval.

**Comment by aaronrobertshaw** [comment]
I've rebased this branch after resolving a conflict with a recent merge to [update the OpenTable block to use native block styles](https://github.com/Automattic/jetpack/pull/16607).

While testing this update I found that the native block style CSS classes didn't play nice with the widget's iframe. They didn't provide an actual width and height from which the iframe could recalculate its size. This has been fixed with a couple of CSS tweaks. 

Previously, while the wide style was applied to a OpenTable block and it was aligned left or right, the iframe would also be cut off, displaying just a fragment of the widget. I've tweaked the CSS here as well so that the widget will display however these changes do not solve the overall issues around alignments of blocks.

Before | After
------ | -----
Screen Shot 2020-08-27 at 6 02 03 pm | Screen Shot 2020-08-27 at 6 02 12 pm

**Comment by allilevine** [comment]
@aaronrobertshaw When I choose an alignment other than "Full width" (like "Wide width") I'm still seeing the widget get cut off before it's replaced:

opentable-wide-alignment

Looks like it's happening when the browser width is 900px to about 1280px. Do we need to account for when the theme / alignment adds additional padding and margins to the 840px iframe width?

**Comment by aaronrobertshaw** [comment]
@allilevine Thanks for testing this again. The few themes I picked at random didn't have that same layout as say TwentyNineteen by the looks of that screenshot.

I'm not sure we can cover every theme here, the "wide" style for this block is fairly problematic. I did have a have a play with adding a ResizeObserver to the block's view JS. This would add a class to any wide style block's container whenever there was insufficient width to render the widget. An approach like this would mean we either solely rely on JS to add the CSS class (removing the media query CSS) or we duplicate a handful of the CSS rules to avoid rewriting all the CSS and block classes.

The ResizeObserver will make the wide style block much more robust across themes though I'm not convinced the added complexity will make it worth it. It also adds another degree of difference between what a user sees in the editor versus the frontend. 

I'm open to suggestions on this one.

In case it's decided we need to be more robust across themes and a JS hack is satisfactory, heres the JS I played with to explore this. The CSS needed is essentially what was added to the media query in this PR just modified to worked based on the additional class instead.

```
/**
 * External dependencies
 */
import domReady from '@wordpress/dom-ready';
import ResizeObserver from 'resize-observer-polyfill';

/**
 * Internal dependencies
 */
import './view.scss';

domReady( () => {
	const wideOpenTables = document.querySelectorAll( '.wp-block-jetpack-opentable.is-style-wide' );

	if ( wideOpenTables.length ) {
		const openTableObserver = new ResizeObserver( entries => {
			for ( let entry of entries ) {
				if ( entry.contentRect.width <= 820 ) {
					entry.target.classList.add( 'show-fallback' );
				} else {
					entry.target.classList.remove( 'show-fallback' );
				}
			}
		} );

		wideOpenTables.forEach( table => openTableObserver.observe( table ) );
	}
} );
```

**Review by allilevine — DISMISSED** [review]
> The ResizeObserver will make the wide style block much more robust across themes though I'm not convinced the added complexity will make it worth it. It also adds another degree of difference between what a user sees in the editor versus the frontend.

@aaronrobertshaw Thanks for explaining this approach! I agree that the tradeoff doesn't seem worth it. Bumping for Jetpack Crew to weigh in.

File: extensions/blocks/opentable/opentable.php [hunk 1]
```diff
@@ -72,6 +73,19 @@ function load_assets( $attributes ) {
...
+
+	// OpenTable's wide style has fixed widths within the embedded iframe.
+	// To improve the mobile experience we'll add a standard style widget as
+	// well and use CSS to switch display between the wide style and it.
+	if ( 'wide' === $style ) {
+		$fallback_attributes = array_merge( $attributes, array( 'style' => 'standard' ) );
+		$fallback_url        = build_embed_url( $fallback_attributes );
+		$content            .= '<div class="mobile-fallback">';
+		// phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript
+		$content .= '<script type="text/javascript" src="' . esc_url( $fallback_url ) . '"></script>';
```
Comment (jeherve) [inline extensions/blocks/opentable/opentable.php:85]: Do we need to load both this one and the default one all the time?

I wonder if we should / could only load one of them?

File: extensions/blocks/opentable/opentable.php [hunk 2]
```diff
@@ -72,6 +73,19 @@ function load_assets( $attributes ) {
 		$classes
 	);
 	$content = '<div class="' . esc_attr( $classes ) . '">';
+
+	// OpenTable's wide style has fixed widths within the embedded iframe.
+	// To improve the mobile experience we'll add a standard style widget as
+	// well and use CSS to switch display between the wide style and it.
+	if ( 'wide' === $style ) {
```
Comment (jeherve) [inline extensions/blocks/opentable/opentable.php:80]: If it's only on mobile, maybe we could rely on an additional `jetpack_is_mobile` check as well?

File: extensions/blocks/opentable/opentable.php (hunk 1 above)
Comment (aaronrobertshaw) [reply extensions/blocks/opentable/opentable.php:85]: If we ignore the possibility of users resizing their browser window, we could potentially only load one. Using JS to dynamically add or modify a fallback widget was a little clunky as well and seemed to overcomplicate things.

Do you think ignoring resized windows and just checking for a mobile user agent using `jetpack_is_mobile` would be sufficient?

Comment (jeherve) [reply extensions/blocks/opentable/opentable.php:85]: > Do you think ignoring resized windows and just checking for a mobile user agent using jetpack_is_mobile would be sufficient?

That's not something we do in blocks today, but we do it in other places in Jetpack. I'd personally say that's enough for most scenarios.

**Comment by aaronrobertshaw** [comment]
I've switched the approach to simply displaying the standard style widget if the `wide` style was selected but we are loading on mobile as determined by `jetpack_is_mobile()`. PR description has also been updated.

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]
Re-approving after 8978177b3b72854131ff952620283c175c73224e to fix linting issues that were causing test failures on WordPress.com.

**Comment by aaronrobertshaw** [comment]
The associated diff D49090-code has been approved and merged.
