### PR TITLE
Rename class to fix a theme clash.

### LINKED ISSUE #8851: Fatal error: Cannot declare class BeaverBuilderCompat
It seems caliber theme uses the same classname. This causes a fatal error.

See: https://wordpress.org/support/topic/after-update-plugin-stop-work/

### PR DESCRIPTION
**Pull request by Pross**
Fixes #8851 

#### Changes proposed in this Pull Request:
Simply changing classname.

### CODE REVIEW

File: 3rd-party/beaverbuilder.php [hunk 1]
```diff
@@ -2,7 +2,7 @@
 /**
  * Beaverbuilder Compatibility.
  */
-class BeaverBuilderCompat {
```
Comment (jeherve) [inline 3rd-party/beaverbuilder.php]: What do you think about using something like `Jetpack_BeaverBuilderCompat` instead, just to be sure this does not happen again in the future?

Comment (Pross) [reply 3rd-party/beaverbuilder.php]: Yea im happy with that, i'll update the pr.
