### PR TITLE
Facebook Embeds: add a white background for better readability

### LINKED ISSUE #40546: Embed Block: Facebook photo posts come with transparent backgrounds
### Quick summary

When you embed Facebook photo posts using the Embed Block, the posts come with transparent backgrounds, while other post types come with a white background.

### Steps to reproduce

1. Create a new page.
2. Embed two Facebook posts (Photo post type and other type to compare) using the Embed Blocks.

### What you expected to happen

All embeds come with a white background.

### What actually happened

A photo post comes with a transparent background, and other post type come with a white background.

Screen Shot on 2024-03-20 at 10:38:24

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

**Workaround:**

```
.fb_iframe_widget iframe {
    background: #ffffff;
}
```

Originally reported in 7915015-zen

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #40546

## Proposed changes:

Add a background to Facebook embeds to avoid transparent backgrounds interfering with readability.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Apply branch to your test site.
* In a new post, paste both a Facebook post and a Facebook image
    * `https://www.facebook.com/VenusWilliams/posts/10151647007373076?ref=embed_post`
    * `https://www.facebook.com/officialcuteoverload/photos/a.398410140072/10151609960150073/?type=3&ref=embed_post`
* Publish your post.
* Ensure that both embeds include a white background.

### CODE REVIEW

File: projects/plugins/jetpack/modules/shortcodes/facebook.php [hunk 1]
```diff
@@ -55,12 +55,18 @@
  * @return string Facebook embed markup.
  */
 function jetpack_facebook_embed_handler( $matches, $attr, $url ) {
+	$extra_styles = 'style="background-color: #fff;"';
```
Comment (fredrikekelund) [inline projects/plugins/jetpack/modules/shortcodes/facebook.php]:
```suggestion
	$extra_styles = 'style="background-color: #fff; display: inline-block;"';
```
There's currently a brief moment while the embed loads where the white background extends beyond the right edge of the actual embed (see ~00:03 in the attached video). I believe this change fixes that. Note that the Facebook embed eventually applies `display: inline-block` to these elements anyway—this change simply preempts that behavior.

https://github.com/user-attachments/assets/0235e898-e831-4de3-bf06-54dedd9bf928

**Review by fredrikekelund — DISMISSED** [review]
Thanks for the swift turnaround, @jeherve 👍 I recommend a small styling change (see my other comment), but aside from that, this works as expected.

File: projects/plugins/jetpack/modules/shortcodes/facebook.php (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/shortcodes/facebook.php]: Sure thing! Done in 257f819bfc0508e133fa5075b0dd2b91c3968d87

File: projects/plugins/jetpack/modules/shortcodes/facebook.php [hunk 2]
```diff
@@ -55,12 +55,18 @@
  * @return string Facebook embed markup.
  */
 function jetpack_facebook_embed_handler( $matches, $attr, $url ) {
+	$extra_styles = 'style="background-color: #fff; display: inline-block;"';
```
Comment (fredrikekelund) [inline projects/plugins/jetpack/modules/shortcodes/facebook.php:60]:
```suggestion
	// This is a stop-gap solution until Facebook hopefully resolves this ticket
	// https://developers.facebook.com/community/threads/1675075423353415/?post_id=1675075426686748
	$extra_styles = 'style="background-color: #fff; display: inline-block;"';
```
Might be worth including a link to the issue we reported, to make it easier to understand when this can be removed.

**Review by fredrikekelund — DISMISSED** [review]
Latest changes work as expected 👍

File: projects/plugins/jetpack/modules/shortcodes/facebook.php (hunk 2 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/shortcodes/facebook.php:60]: Good point. Done, and merging this now.
