### PR TITLE
[AI image] fix styling  issues

### LINKED ISSUE #28323: [Jetpack AI] Fix styling
The styling of the AI Image in the editor needs some work:

Per @poligilad-auto 

> 1. The layout of the text field seems a bit off to me. I would expect the text field to go all the way till the edge of the block.

image

> 2. After submitting the text, while hovering over the 4 options, the content of the block starts to “jitter”. Think this might be just a problem with the first image in the row.

image

Find any other styling issues you could find.

There are more styling issues with flexbox:

image

Per @frosty :

> AI Image: It would be nice to be able to preview images in a larger size before choosing which to commit to. I clicked on one of the 4 expecting to see it bigger, but it instantly turns into an image block and the other options disappeared. It’s hard to make a decision about which image to use when they’re all tiny.

So let's make this hover much, much bigger as we have the image data in memory already.

### PR DESCRIPTION
**Pull request by millerf**
Fixes #28323 

## Proposed changes:
* Fix textarea width

### Other information:

- [x] Fix textarea width
- [ ] ~Make textarea height change depending on input text ( see [this comment](https://github.com/Automattic/jetpack/pull/28339#issuecomment-1383910122))~ **created a separate task for it**
- [x] Fix result images overflow 
- [x] Fix result images hovering

## Testing instructions:

* Deploy to your sandbox (with `jetpack-dowbnloader` for example)
* Check that all changes were made

## Screenshots

Screenshot 2023-01-17 at 12 11 40
Screenshot 2023-01-17 at 12 07 41
Screenshot 2023-01-17 at 12 07 45
Screenshot 2023-01-17 at 12 08 04

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/ai-image/edit.js [hunk 1]
```diff
@@ -88,120 +93,127 @@ export default function Edit( { attributes, setAttributes, clientId } ) {
...
-			) }
-			{ ! errorMessage && ! loadingImages && resultImages.length > 0 && (
-				<Placeholder label={ __( 'AI Image', 'jetpack' ) }>
-					<div>
-						<div style={ { textAlign: 'center', margin: '12px', fontStyle: 'italic' } }>
+				) }
+				{ ! loadingImages && resultImages.length > 0 && (
+					<Flex direction="column" style={ { width: '100%' } }>
+						<FlexBlock
+							style={ { textAlign: 'center', margin: '12px', fontStyle: 'italic', width: '100%' } }
```
Comment (artpi) [inline projects/plugins/jetpack/extensions/blocks/ai-image/edit.js:186]: Class plz

**Review by artpi — DISMISSED** [review]
Code looks ok, and these are very welcome changes.

I have 2 points of issue:
1. We should move the "select" button to the modal. That way the user is motivated to inspact the image in more detail before selecting it. On top of that, these 4 selects tdo not look good
2. The modal for me has a height problem

Both of those points are not a big deal, we can fix that later as well.

Zrzut ekranu 2023-01-17 o 14 57 10

**Comment by artpi** [comment]
The bigger problem is that the build tests seem to fail and some JP checks are complaining

File: projects/plugins/jetpack/extensions/blocks/ai-image/edit.js [hunk 2]
```diff
@@ -88,120 +93,127 @@ export default function Edit( { attributes, setAttributes, clientId } ) {
...
+							<TextareaControl
+								label={ __( 'What would you like to see?', 'jetpack' ) }
+								placeholder={ placeholder }
+								allowedFormats={ [] }
+								onChange={ setPrompt }
+								rows={ 6 }
+							/>
 							<Button variant="primary" onClick={ submit }>
-								{ __( 'Retry', 'jetpack' ) }
+								{ errorMessage ? __( 'Retry', 'jetpack' ) : __( 'Submit', 'jetpack' ) }
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: This is breaking the build I'm afraid:

```
msgid argument is not a string literal: __(E?"Retry":"Submit","jetpack")
```

The building tooling doesn't seem to like the translations in a ternary like that, so I would recommend moving them out of there, maybe like so (it's not as pretty, but it does seem to build):

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/ai-image/edit.js b/projects/plugins/jetpack/extensions/blocks/ai-image/edit.js
index 3ed9e51195..f970a7d0b2 100644
--- a/projects/plugins/jetpack/extensions/blocks/ai-image/edit.js
+++ b/projects/plugins/jetpack/extensions/blocks/ai-image/edit.js
@@ -71,6 +71,9 @@ export default function Edit( { attributes, setAttributes, clientId } ) {
 	const { replaceBlock } = useDispatch( blockEditorStore );
 	const [ errorMessage, setErrorMessage ] = useState( null );
 	const [ placeholder ] = useState( getRandomItem( dalleExamplePrompts ) );
+	const errorButtonText = __( 'Retry', 'jetpack' );
+	const successButtonText = __( 'Submit', 'jetpack' );
+	const submitButtonText = errorMessage ? errorButtonText : successButtonText;
 
 	const { mediaUpload } = useSelect( select => {
 		const { getSettings } = select( blockEditorStore );
@@ -175,7 +178,7 @@ export default function Edit( { attributes, setAttributes, clientId } ) {
 								rows={ 6 }
 							/>
 							<Button variant="primary" onClick={ submit }>
-								{ errorMessage ? __( 'Retry', 'jetpack' ) : __( 'Submit', 'jetpack' ) }
+								{ submitButtonText }
 							</Button>
 						</FlexBlock>
 					</Flex>

```

**Review by jeherve — CHANGES_REQUESTED** [review]

**Comment by artpi** [comment]
> We should move the "select" button to the modal. That way the user is motivated to inspact the image in more detail before selecting it. On top of that, these 4 selects tdo not look good

Imo that select should be **above** the image in the modal so we are sure the user sees it without scrolling.

We can name it "Use this image"

**Comment by millerf** [comment]
> > We should move the "select" button to the modal. That way the user is motivated to inspact the image in more detail before selecting it. On top of that, these 4 selects tdo not look good
> 
> Imo that select should be **above** the image in the modal so we are sure the user sees it without scrolling.
> 
> We can name it "Use this image"

I tried and I could not place it right. Something wrong with he modal and flex positioning. But I'll try again 👍

File: projects/plugins/jetpack/extensions/blocks/ai-image/edit.js (hunk 2 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: Funny I didn't see any issue when building 🤔 

While you are here. Another question. My building keeps breaking until I do a `composer update` in `projects/plugins/jetpack`. Don't you push the new `composer.lock`?

Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: I see. You're talking about the GH actions build...

Comment (artpi) [reply projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: See discussion in https://github.com/Automattic/jetpack/pull/28285

Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: > See discussion in #28285

Thanks! I didn't see those!
So it looks like an issue with the PHP version?

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/ai-image/edit.js]: > You're talking about the GH actions build...

Yes. We get no build errors when doing a dev build locally with `jetpack build plugins/jetpack`.

> So it looks like an issue with the PHP version?

Yup, looks like it. You would need to update to PHP 8.0. Although in the case of this PR, you shouldn't have to run any kind of `composer` commands really, since you're not making any changes to composer packages. You should be able to build and update the blocks in your PRs with `jetpack build plugins/jetpack` and `jetpack watch plugins/jetpack`. I don't believe you need any other build commands at the moment. Maybe `jetpack rsync` to test on WordPress.com simple or WoA.

**Comment by millerf** [comment]
@artpi @jeherve 

Feedback has been addressed. 


Screenshot 2023-01-18 at 13 41 47
Screenshot 2023-01-18 at 13 41 42

> The modal for me has a height problem

I have not seen that... 🤔

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢
