### PR TITLE
Admin Page: update version reference in link to survey

### LINKED ISSUE #4360: Send us feedback link has wrong version number
Currently the send us feedback takes you to http://surveys.jetpack.me/research-plugin?rel=3.9.4
I think the last part should be dynamic.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #4360

#### Changes proposed in this Pull Request:
Updates version number using current Jetpack version.

### CODE REVIEW

**Comment by jeherve** [comment]
Fixes #4360

File: _inc/client/components/masthead/index.jsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ const Masthead = React.createClass( {
 							</a>
 						</li>
 						<li className="jp-masthead__link-li">
-							<a href="http://surveys.jetpack.me/research-plugin?rel=3.9.4" target="_blank" className="jp-masthead__link">
+							<a href="http://surveys.jetpack.me/research-plugin?rel=4.3.0" target="_blank" className="jp-masthead__link">
```
Comment (jeherve) [inline _inc/client/components/masthead/index.jsx]: Should we make this a dynamic value, so we don't have to update it manually for each release?

**Comment by oskosk** [comment]
LGTM !
