### PR TITLE
Theme Tools: Return early when there's no post context in jetpack_blog_display_custom_excerpt()

### LINKED ISSUE #19616: Theme Tools: PHP Notice during `jetpack_blog_display_custom_excerpt()`
#### Steps to reproduce the issue

1. Load a WordPress page which calls `get_the_content()` without having a global `$post` object setup.
2. Observe PHP notice.

#### What I expected

No PHP Notice.

#### What happened instead
```
E_NOTICE: Trying to get property 'post_content' of non-object
Request URI: /wp.serviceworker
File: wp-content/plugins/jetpack/modules/theme-tools/content-options/blog-display.php:37
Stack Trace: require('wp-blog-header.php'), wp, WP->main, WP->query_posts, WP_Query->query, WP_Query->get_posts, WP_Query->parse_query, do_action_ref_array('parse_query'), WP_Hook->do_action, WP_Hook->apply_filters, wp_service_worker_loaded, WP_Service_Workers->serve_request, do_action('wp_front_service_worker'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Service_Worker_Navigation_Routing_Component->serve, apply_filters('wp_offline_error_precache_entry'),  apply_filters('the_content'), WP_Hook->apply_filters, jetpack_the_content_to_the_excerpt, jetpack_blog_display_custom_excerpt
```

**Screenshots**

### PR DESCRIPTION
**Pull request by dd32**
Fixes #19616

This seems odd, as the filter completely ignores the provided `$content` from the filter normally, so not sure if this is correct or not.. it seems that Jetpack should be using `$content` instead of `$post->post_excerpt` below in the if-else instead.

#### Changes proposed in this Pull Request:

* Returns early when no context is provided

#### Jetpack product discussion

No

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

*  See Issue

### CODE REVIEW

File: projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php [hunk 1]
```diff
@@ -33,6 +33,10 @@
  */
 function jetpack_blog_display_custom_excerpt( $content ) {
 	$post = get_post();
+	if ( empty( $post ) ) {
+		return $content;
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php:37]: I wonder if this may cause issues in some cases since we check for `empty()` later:
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php#L120-L125

Maybe we should extend that check to avoid displaying the full content twice here?
https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php#L127

**Review by jeherve — COMMENTED** [review]
Left a quick note below.

Could you also provide a changelog entry for your change, using the built-in tool?
`cd projects/plugins/jetpack && composer install && vendor/bin/changelogger add`

In the future, do not hesitate to create branches in the upstream repo instead of in your fork :) This adds some more automated tools to the PR, to port the changes back to WordPress.com afterwards for example.

Thank you!

File: projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php (hunk 1 above)
Comment (dd32) [reply projects/plugins/jetpack/modules/theme-tools/content-options/blog-display.php:37]: Good catch, I missed that somehow.

I guess `jetpack_blog_display_custom_excerpt()` probably just shouldn't accept a `$content` param and should just return an empty string instead.

I'll update the PR.

**Review by jeherve — APPROVED** [review]
This tests well for me. Merging.

**Comment by jeherve** [comment]
r224692-wpcom
