### PR TITLE
Search: fix search widget not saving for block widget editor

### LINKED ISSUE #20755: Search: Jetpack Search widget filters do not save in the Block Widget editor
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add a Jetpack Search widget to the Jetpack Search Sidebar area using the new widget editor.
2. Add filters to the widget from (1).
3. Save your changes.
4. Refresh the page.

### A clear and concise description of what you expected to happen.

The Jetpack Search widget (1) should have retained the added filters (2).

### What actually happened

The Jetpack Search widget (1) does not retain any of the added filters from step (2).

### Other information

This only appears to happen with the new widget editor introduced in WordPress 5.8.

cc @Automattic/jetpack-search 

### Operating System

macOS

### Browser

Chrome/Chromium

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #20755 

#### Changes proposed in this Pull Request:
The problem is that for the block widget editor, the frontend passed the widget instance in another format (I would say a better format) the same as how the widget is saved in the db, but unfortunately our search widget save function only deals with its own format. 

| New  | Old |
| ------------- | ------------- |
| image | image|

The PR proposes a function to convert the format to the the format which Jetpack Search could consume.

We could potentially change the search widget form format, but that would require quite a few changes, and would likely break if not tested thoroughly. And also the widget is a legacy one, we'll probably create a block one in the future, so we'd better not put too much time in it.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Add a Jetpack Search widget to the Jetpack Search Sidebar area using the _NEW_ widget editor.
* Add filters to the widget from.
* Save your changes.
* Refresh the page.
* Ensure filter options stick.

-------------
* Disable the new widget editor by adding `add_filter( 'use_widgets_block_editor', '__return_false' );`
* Add a Jetpack Search widget to the Jetpack Search Sidebar area using the _OLD_ widget editor.
* Add filters to the widget from.
* Save your changes.
* Refresh the page.
* Ensure filter options stick.

### CODE REVIEW

File: projects/plugins/jetpack/modules/widgets/search.php [hunk 1]
```diff
@@ -675,6 +678,31 @@ public function update( $new_instance, $old_instance ) {
...
+			$instance['taxonomy_type'][]           = $filter['taxonomy'];
+			$instance['filter_name'][]             = $filter['name'];
+			$instance['num_filters'][]             = $filter['count'];
+			$instance['date_histogram_field'][]    = $filter['field'];
+			$instance['date_histogram_interval'][] = $filter['interval'];
+		}
+		unset( $instance['filters'] );
+		return $instance;
+	}
+
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/widgets/search.php:705]: new lines

File: projects/plugins/jetpack/modules/widgets/search.php [hunk 2]
```diff
@@ -622,7 +624,8 @@ private function sorting_to_wp_query_param( $sort ) {
 	 * @return array Settings to save.
 	 */
 	public function update( $new_instance, $old_instance ) {
-		$instance = array();
+		$new_instance = $this->maybe_new_block_widget_to_jp_search_format( $new_instance );
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/widgets/search.php:627]: new line

File: projects/plugins/jetpack/modules/widgets/search.php [hunk 3]
```diff
@@ -675,6 +678,31 @@ public function update( $new_instance, $old_instance ) {
...
+			$instance['taxonomy_type'][]           = isset( $filter['taxonomy'] ) ? $filter['taxonomy'] : '';
+			$instance['filter_name'][]             = isset( $filter['name'] ) ? $filter['name'] : '';
+			$instance['num_filters'][]             = isset( $filter['count'] ) ? $filter['count'] : 5;
+			$instance['date_histogram_field'][]    = isset( $filter['field'] ) ? $filter['field'] : '';
+			$instance['date_histogram_interval'][] = isset( $filter['interval'] ) ? $filter['interval'] : '';
+		}
+		unset( $instance['filters'] );
+		return $instance;
+	}
+
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/widgets/search.php:705]: new lines

**Review by jsnmoon — COMMENTED** [review]
Great sleuthing, @kangzj! This works exactly as described.

I left a code suggestion and a comment below. Not blocking, but worth your consideration.

File: projects/plugins/jetpack/modules/widgets/search.php [hunk 4]
```diff
@@ -675,6 +678,31 @@ public function update( $new_instance, $old_instance ) {
...
 
+	/**
+	 * Covert the format of new widget to search widget format when appropriate.
+	 *
+	 * @param array $new_instance - The updated widget instance.
+	 *
+	 * @return array - The widget instance of JP search format.
+	 */
+	protected function maybe_new_block_widget_to_jp_search_format( $new_instance ) {
+		if ( isset( $new_instance['filter_type'] ) || ! isset( $new_instance['filters'] ) || ! is_array( $new_instance['filters'] ) ) {
```
[the remark this answers is not in the document]
Comment (kangzj) [reply projects/plugins/jetpack/modules/widgets/search.php:690]: `$new_instance` is basically the form data posted in `$_POST`, which is an array. If it is not, then the data is corrupted or something, and we don't really want to process it anyway I guess 😄

**Review by jsnmoon — APPROVED** [review]
🚢 🚢 🚢

**Comment by kangzj** [comment]
🚢 shipped in r230556-wpcom
