### PR TITLE
Fix PHP 7.1 Warning: illegal string offset 'src'

### LINKED ISSUE #6117: PHP 7.1 Warning: illegal string offset 'src'
With PHP 7.1 and 7.1.1:

`PHP Warning:  Illegal string offset 'src' in /wp-content/plugins/jetpack/functions.opengraph.php on line 293`

#### Steps to reproduce the issue

Visit an author archive for any author with public posts.

### PR DESCRIPTION
**Pull request by ethitter**
Fixes #6117

#### Changes proposed in this Pull Request:

Ensures `$image` is always an array before it's treated as such.

#### Testing instructions:

* Visit an author archive for any author with public posts.
* Check error logs for instances of `PHP Warning:  Illegal string offset 'src' in /wp-content/plugins/jetpack/functions.opengraph.php on line 293`

### CODE REVIEW

**Comment by kraftbj** [comment]
Test error appears to be unrelated to the commit. Rerunning.

File: functions.opengraph.php [hunk 1]
```diff
@@ -261,22 +261,20 @@ function jetpack_og_tags() {
 }
 
 function jetpack_og_get_image( $width = 200, $height = 200, $max_images = 4 ) { // Facebook requires thumbnails to be a minimum of 200x200
-	$image = '';
+	$image = array();
 
 	if ( is_singular() && ! is_home() ) {
 		global $post;
```
Comment (georgestephanis) [inline functions.opengraph.php]: Would it be good to move this to the top of the function as well?  I'd always been taught that it's best to declare globals all at the beginning of the function, so they don't get lost when skimming.

Comment (ethitter) [inline functions.opengraph.php]: Normally I'd leave it, since it's only used within that conditional, but now that you've called it out, I'm inclined to remove it entirely. It's only there to provide access to the post ID, which `get_the_ID()` can do instead, simplifying this section. Update forthcoming.

Comment (ethitter) [inline functions.opengraph.php]: @georgestephanis I comitted fe54292a4 for the `$post` change. Since it's not directly related to this issue/PR, I'm fine with that change being reverted and/or committed to a new branch.

**Comment by georgestephanis** [comment]
:shipit:

File: functions.opengraph.php (hunk 1 above)
Comment (georgestephanis) [inline functions.opengraph.php]: It's a tiny change, I'm fine rolling it in here personally.
