### PR TITLE
Markdown: avoid processing URLs that may include Markdown syntax

### LINKED ISSUE #10595: Twitter auto embedding breaks if user name starts and ends with an underscore
#### Steps to reproduce the issue

1.  Try to embed a Tweet where the user's name starts and ends with `_`
1.   For example `https://twitter.com/_sagesharp_/status/1061094348152918017`
1.  The text is rendered as `https://twitter.com/<em>sagesharp</em>/status/1061094348152918017` rather than an oembed.
1.  The JetPack MarkDown processor is incorrectly interpreting the underscores in a URL as being valid MarkDown. 

Tried on a fresh install of 4.9.8, with only JetPack installed, MarkDown editing switched on, and using the classic editor.

This works fine for embedding `[tweet 1061094348152918017]`

#### What I expected
The tweet should OEmbed as per usual.

#### What happened instead
The underscores in the name get treated as MarkDown.  The resultant URL is not properly parsed.

**Screenshots**
MarkDown in classic editor:

screenshot at 2018-11-10 12-27-12 

The first link is rendered incorrectly but the second one works:
screenshot at 2018-11-10 12-27-56

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10595
Closes #17761

#### Changes proposed in this Pull Request:

* This is an alternative approach to #17761, trying to solve the issue for all types of links that may include underscores, whether we use the Shortcodes feature or not.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No 

#### Testing instructions:

* Go to Jetpack > Settings > Writing, and enable the Markdown feature.
* Go to Plugins > Add New, install and activate the Classic editor plugin.
* Go to Posts > Add New, and start writing a new post. 
* Try testing with different types of Markdown content; you can find some examples [here](https://daringfireball.net/projects/markdown/syntax).
* You can also focus on links in Markdown, in different formats, with or without underscores:
    - `https://twitter.com/_sagesharp_/status/1323662905716273152` on its own line.
    - `[A link with underscore in URL](https://jetpack.com/_features_/)`
    - `_[An italic link with underscore in URL](https://jetpack.com/_features_/)_`

#### Proposed changelog entry for your changes:

* Markdown: avoid processing URLs that may include Markdown syntax

### CODE REVIEW

**Comment by edent** [comment]
LGTM. Is there an upstream which is can also be sent to?

**Comment by jeherve** [comment]
> Is there an upstream which is can also be sent to?

I don't believe the upstream repo is still maintained, so we should be all set with this.

File: tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+				'https://jetpack.com/',
+			),
+			'link_underscore_alone' => array(
+				'https://jetpack.com/_features_/',
+				'https://jetpack.com/_features_/',
+			),
+			'ftp_link_underscore'   => array(
+				'ftp://_best_pack@jetpack.com:123',
+				'ftp://_best_pack@jetpack.com:123',
+			),
```
Comment (anomiex) [inline tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php:70]: Additional test cases to consider:
```
// This is current behavior before this patch.
'explicit URL' => array(
    'url: <https://jetpack.com/_features_/>',
    'url: <a href="https://jetpack.com/_features_/">https://jetpack.com/_features_/</a>',
),
// This too.
'URL in link text' => array(
    'url: [https://jetpack.com/](https://jetpack.com/#xyz)',
    'url: <a href="https://jetpack.com/#xyz">https://jetpack.com/</a>',
),

'bolded URL' => array(
    '**https://jetpack.com/_features_/**',
    '???',
),
'emphasized URL' => array(
    '_https://jetpack.com/_features_/_',
    '???',
),
'URL with odd but legal characters' => array(
    'https://example.com/_form?type=*&q=a+(b+or+c)&arr[]=1&arr[]=2&value=_foo_bar'
    '???',
),
```

**Comment by anomiex** [comment]
Too bad we can't just use something like [thephpleague/commonmark](https://github.com/thephpleague/commonmark). But that doesn't support PHP 5.6.

File: tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php (hunk 1 above)
Comment (jeherve) [reply tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php:70]: Ah, good catch. This complicates things quite a bit. I'm not quite sure how to catch all those with a single regex, to be honest. I'm not sure if this means we should reconsider the alternate approach, #17761, which only targets Twitter links. 

What do you think? Can you think of a way to address all those at once?

**Review by edent — CHANGES_REQUESTED** [review]

File: _inc/lib/markdown/gfm.php [hunk 2]
```diff
@@ -99,6 +99,9 @@ public function transform( $text ) {
 			$text = $this->latex_preserve( $text );
 		}
 
+		// Do not process characters inside URLs.
+		$text = $this->urls_preserve( $text );
```
[the remark this answers is not in the document]
Comment (edent) [reply _inc/lib/markdown/gfm.php:103]: I'd suggest just going back to excluding Twitter links. That's the only place I've noticed the problem.

File: tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php (hunk 1 above)
Comment (anomiex) [reply tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php:70]: It's a little hacky, but I think we can get most of the way there with something like
```
#(?<!<)(?:https?|ftp)://([^\s<>"\[\]()]+|\[(?1)*+\]|\((?1)*+\))+(?<![_*.?])#i
```
Explanation:
* The `(?<!<)` at the beginning avoids matching URLs immediately preceded by a `<`.
* The `(?<![_*.?!])` at the end avoids including any trailing `_`, `*`, `.`, `?`, or `!` in the URL.
* The `([^\s<>"\[\]()]+|\[(?1)*+\]|\((?1)*+\))+` is some PCRE magic that allows only balanced `[]` and `()` in the URL. So a URL like `https://example.com/foo(bar` would get cut off after "foo", while the whole of `https://example.com/foo(bar)` would be matched.
    * `[^\s<>"\[\]()]+` is the basic set of allowed characters.
    * `\[(?1)*+\]` allows an open-bracket, then any number of repetitions of anything capturing group 1 might match, then a close-bracket. The `*+` will hopefully avoid too much backtracking in case of an unmatched `[`.
    * `\((?1)*+\)` does the same for parens.

There are some edge cases, but hopefully they're rare enough that we can ignore them:
* `<http://example.com/_foo_` won't be protected.
* In something like `_emphasized text http://example.com/_foo_ more emphasized text_`, that trailing `_` won't be protected and it'll confuse Markdown into ending the emphasis early.
* Something like `http://example.com/(/_foo_` won't have the part after the unbalanced bracket/paren protected.

**Comment by edent** [comment]
Any update on this?

File: tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php (hunk 1 above)
Comment (jeherve) [reply tests/php/_inc/lib/markdown/test-class-wpcom-ghf-markdown-parser.php:70]: I committed your suggestions in b6f529e6ccc90b70bfe9d5f194f01966d132d168

File: _inc/lib/markdown/gfm.php (hunk 2 above)
[the remark this answers is not in the document]
Comment (jeherve) [reply _inc/lib/markdown/gfm.php]: The latest regex changes seem to handle this: ebac50a0386331065bf91172e55d078fb6b0e5b5

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r221702-wpcom
