### PR TITLE
Protect: Fix IPv6 handling in `jetpack_clean_ip`

### LINKED ISSUE #17566: Protect: Needs better IPv6 handling
#### Steps to reproduce the issue

1. Run `jetpack_clean_ip` on an IPv6 URL. (example `2001:db8:a0b:12f0::1` )

#### What I expected
The IP to be returned.

#### What happened instead
The initial `2001:` has been stripped.

It is being caused by a bug with `parse_url`. It doesn't handle IPv6 very well: https://github.com/php/php-src/pull/2079

The 2001 is being parsed by PHP as the scheme, as it proceeds the initial colon and there is no scheme present. But, adding a fake scheme (`https://` for the sake of conversation) also produces a problem:
```
>>> $parsed_url = parse_url( 'https://2001:db8:a0b:12f0::1');
=> [
     "scheme" => "https",
     "host" => "2001:db8:a0b:12f0:",
     "port" => 1,
```
and cuts off the end of the IP address.

### PR DESCRIPTION
**Pull request by anomiex**
Fixes #17566

#### Changes proposed in this Pull Request:

* Correctly remove the ports from input IPs, instead of trying to misuse `parse_url`.
* Validate that the cleaned IP is valid.
* Add tests.

#### Jetpack product discussion

#17566

#### Does this pull request change what data or activity we track or use?

It might correct tracking when IPv6 addresses are involved. It doesn't add anything new.

#### Testing instructions:

Based on https://wordpress.org/support/topic/truncated-log-of-ipv6-login-error/:
* Attempt a failed login via IPv6.
* Check that the log correctly includes the IPv6 address.

Another possibility:
* Configure Protect with some dummy header as the trusted IP header.
* Make requests that Protect will log with said dummy header set to `[2001:DB8::3]:80`
* Check that the logged IP is `2001:DB8::3`.

#### Proposed changelog entry for your changes:

* "Protect: Fix handling of IPv6 addresses."

### CODE REVIEW

File: tests/php/modules/protect/test-shared-functions.php [hunk 1]
```diff
@@ -0,0 +1,232 @@
...
+	 *
+	 * @covers jetpack_protect_get_ip
+	 * @covers jetpack_clean_ip
+	 * @dataProvider provide_jetpack_protect_get_ip
+	 * @param string|false $expect Expected output.
+	 * @param array        $server Data for `$_SERVER`.
+	 * @param object|null  $trusted_header_data Trusted header data.
+	 */
+	public function test_jetpack_protect_get_ip( $expect, $server, $trusted_header_data ) {
+		add_filter(
```
Comment (jeherve) [inline tests/php/modules/protect/test-shared-functions.php:27]: To avoid leaving things behind once we've completed this series of tests, should we `remove_filter` in a `tearDown` method?

**Review by jeherve — COMMENTED** [review]
Thanks for adding those tests, that's super helpful! I only have a single question.

File: tests/php/modules/protect/test-shared-functions.php (hunk 1 above)
Comment (anomiex) [reply tests/php/modules/protect/test-shared-functions.php:27]: It looks like `WP_UnitTestCase_Base::setUp()` and `WP_UnitTestCase_Base::tearDown()` already handle that, they back up and restore the global `$wp_filter` (and `$wp_actions` and `$wp_current_filter`).

I could add a comment here to make that clear, if you'd like.

Comment (jeherve) [reply tests/php/modules/protect/test-shared-functions.php:27]: Oh cool, I did not know that. 

> I could add a comment here to make that clear, if you'd like.

No, that's alright. I should have looked before to comment. :)

**Review by jeherve — APPROVED** [review]
