### PR TITLE
Instant Search: don't exclude any post types by default

### LINKED ISSUE #16982: Jetpack Search: posts are excluded from search by default
When freshly installing Jetpack Search (Instant), the post type 'post' is excluded by default. The vast majority of users will want this post type included in their search results.

#### Steps to reproduce the issue

1. Go to https://jurassic.ninja/ and set up a new Jetpack site
2. Set up Jetpack and choose the Jetpack Search plan
3. Return to your new site's Customizer (`/wp-admin/customize.php?autofocus[section]=jetpack_search`)
4. Notice that 'post' is one of the excluded post types by default

Screen Shot 2020-08-26 at 12 29 32

#### What I expected

The post type 'post' should not be excluded by default.

#### What happened instead
The post type 'post' was excluded by default.

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes #16982.

#### Changes proposed in this Pull Request:

In #16364 we made two changes:
* Added a site-wide setting for excluding certain post types from search results in the Instant Search overlay.
* Removed per-widget setting for including only certain post types from the Jetpack Search widget when Instant Search is enabled.

In order to seamlessly support the older per-widget setting, we kept honouring post types set up in widgets (see https://github.com/Automattic/jetpack/commit/ffd7fe0021b5f327dc34c429cbadfe2429fc56f7). Unfortunately, this change also seems to disable all post types for brand new sites that don't have any widget settings. 

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

On a test site with no Jetpack Search widgets set up, enable Jetpack Search and the instant search experience in `/wp-admin/admin.php?page=jetpack#/performance`.

Screen Shot 2020-08-26 at 15 19 18

Visit the Customizer and ensure that no post types have been disabled by default:

Screen Shot 2020-08-26 at 15 15 21

#### Proposed changelog entry for your changes:

* Ensure that all post types are enabled by default in Jetpack Instant Search.

### CODE REVIEW

File: modules/search/class-jetpack-instant-search.php [hunk 1]
```diff
@@ -575,7 +576,9 @@ public function auto_config_excluded_post_types() {
 			}
 		}
 
-		$post_types_to_disable = array_diff( $post_types, $enabled_post_types );
-		update_option( Jetpack_Search_Options::OPTION_PREFIX . 'excluded_post_types', join( ',', $post_types_to_disable ) );
+		if ( ! empty( $enabled_post_types ) ) {
```
Comment (bluefuton) [inline modules/search/class-jetpack-instant-search.php:579]: We only now do this step if we found some enabled post types in the widgets.

Previously, this would have disabled all post types when there were no enabled post types in the widgets:

```
$post_types = [ 'post', 'page'];
$enabled_post_types = [];
$post_types_to_disable = array_diff( $post_types, $enabled_post_types); // returns ['post', 'page']
```

**Review by jeherve — APPROVED** [review]
This makes sense to me, and tests well. I've moved this to this release as it seems important enough.

**Review by jsnmoon — APPROVED** [review]
I'm able to reproduce the bug on `master` and have verified that this branch fixes this issue on Jurassic Ninja.

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.9` in 1278bcdc69b29d23d1db2dc078644deabb553229
