### PR TITLE
VideoPress: skip rating checking when pulling video data for block

### LINKED ISSUE #28349: VideoPress: Video block is stuck on birthdate confirmation when rating is `R-17` in the block editor
Steps to reproduce:
- In the VideoPress dashboard, add a video and set its rating to `R`
- Add the video to the block editor

Notice that adding the birthdate does not load the video and that there is a `400` response for the video data, making it default to rating `G`.

Image

### PR DESCRIPTION
**Pull request by retrofox**
To skip the rating checking that the `videos/` endpoint does, this PR adds an option to the `useVideoData() `hook, which will pass birthdate arguments to the `videos/` endpoint to jump it finally.
Ideally, we might add a new argument to the endpoint that allows skip it explicitly, something like `skip_rating_control`.

Keep in mind this change won't affect the Rating control at the player level, meaning that it will keep showing the rating form to the users.

Fixes https://github.com/Automattic/jetpack/issues/28349

## Proposed changes:

* VideoPress: skip rating checking when pulling video data for the block

### Other information:

- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the VideoPress dashboard
* Go to a video details page
* Set the rating for a video with `R`

Screen Shot 2023-01-16 at 08 18 27

* Save the video details
* Go to the block editor
* Create a new block
* Set the via by selecting the previous video from the Media Gallery
* Confirm the video is not shown because of the rating setting
* Confirm the block populates with the video data (title, description, **rating**, etc.)
* Confirm the player shows the rating control from

Screen Shot 2023-01-16 at 08 18 01

### CODE REVIEW

File: projects/packages/videopress/src/client/block-editor/hooks/use-video-data/types.ts [hunk 1]
```diff
@@ -7,7 +7,7 @@ import { VideoGUID, VideoId } from '../../blocks/video/types';
 export type UseVideoDataArgumentsProps = {
 	id?: VideoId;
 	guid?: VideoGUID;
-	isPrivate?: boolean;
```
Comment (lhkowalski) [inline projects/packages/videopress/src/client/block-editor/hooks/use-video-data/types.ts:10]: `isPrivate` was not in use anymore?

Comment (retrofox) [reply projects/packages/videopress/src/client/block-editor/hooks/use-video-data/types.ts:10]: nop. Let me change it in another PR. I would avoid running the tests again

Comment (retrofox) [reply projects/packages/videopress/src/client/block-editor/hooks/use-video-data/types.ts:10]: oh I see. I removed it here 😅 Yes, `isPrivate` is not used now.

**Comment by lhkowalski** [comment]
I added a video to the site and set some data for it:

Screen Shot 2023-01-16 at 10 49 08

I then added it to a block on the editor, and it shows the birth date form as expected:

Screen Shot 2023-01-16 at 10 51 16

The data for the video gets fetched as expected, so now the request is working to get the metadata:

Screen Shot 2023-01-16 at 10 53 18

Screen Shot 2023-01-16 at 10 53 28

**Review by lhkowalski — APPROVED** [review]
The solution is a neat work around, code looks good and the main problem is now solved. We agreed to work on a follow up issue (#28375) right after the release of the next version.
