### PR TITLE
 Module Descriptions: add 3 missing modules.

### LINKED ISSUE #11711: All Modules Page: Support Link Consistency
#### Steps to reproduce the issue

1. Go to wp-admin/admin.php?page=jetpack_modules
2. Click on individual module titles to be redirected to their support page

#### What I expected

That all individual modules link to their respective support page.

#### What happened instead

- Comment Likes
- Progressive Web Apps
- Search

The above modules direct you to the page you are on in WP Admin. ( _The all modules page._ )

Their respective support links are following:
1) Comment Likes - https://jetpack.com/support/comment-likes/
2) Progressive Web Apps - _Not really sure which support article would apply here._
3) Search - https://jetpack.com/support/search/

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #11711

#### Changes proposed in this Pull Request:

* add 3 missing modules to the module info list.
* fix all phpcs warnings.
* add file to list of autolint files.

#### Testing instructions:

* Go to Jetpack > Debug in your dashboard.
* Click the link to view all modules at the bottom of the page.
* Make sure Comment Likes, PWA, and Search all link to their respective support docs.

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

**Review by kraftbj — DISMISSED** [review]

**Comment by jeherve** [comment]
@kraftbj This is going to need another review I am afraid, I had to rebase.

File: modules/module-info.php [hunk 1]
```diff
@@ -116,581 +142,772 @@ function notes_load_more_link() {
...
-function latex_more_info() { ?>
-	<?php printf( esc_html__(
-		'%1$s is a powerful markup language for writing complex mathematical equations and formulas.
-		Jetpack combines the power of %1$s and the simplicity of WordPress to give you the ultimate
+/**
+ * LaTeX description.
+ */
+function latex_more_info() {
+	esc_html_e(
+		'LaTeX is a powerful markup language for writing complex mathematical equations and formulas.
```
Comment (kraftbj) [inline modules/module-info.php]: I like the switch away from the image on this one.

**Review by kraftbj — APPROVED** [review]
