### PR TITLE
Forms: Fix `source` filtering in classic view for responses management

### LINKED ISSUE #42599: Form responses are not filtering by selected source
### Impacted plugin

Jetpack

### Quick summary

Within simple and atomic sites, filtering form responses by the "All sources" dropdown menu does not filter correctly. There is no change to the results.

### Steps to reproduce

1. Add two different forms to a test simple or atomic site. Ensure both forms are on two different pages.
2. Submit multiple form responses for each form.
3. Go to the dashboard, under Feedback > Form Responses.
4. Click the "All sources" dropdown menu and change a category. 
5. Click the "Filter" button.

**Expected behavior**
* The list should only filter the responses for the selected dropdown menu option.
* The total number of items (on the right under "Search Responses") should change based on the dropdown menu selection.

**Actual behavior**
* Nothing changes.
* The total number of items (on the right under "Search Responses") remains unchanged. It shows the total of form responses submitted for both forms.

Screen recording of this behavior:

https://github.com/user-attachments/assets/639a3816-6a88-4290-a9ad-27d97ed6d7cb

### Site owner impact

More than 60% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

Atomic, Simple

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes https://github.com/Automattic/jetpack/issues/42599

>Within simple and atomic sites, filtering form responses by the "All sources" dropdown menu does not filter correctly. There is no change to the results. This affects the classic wp-admin list.

### Proposed changes:

In the `wp-admin` list we perform two queries that trigger the `pre_get_posts` hook. One is for the main list and the other is for the `source` dropdown filter. We need to explicitly check one unique parameter between the two queries to avoid  filtering the dropdown query. The dropdown query is in `get_all_parent_post_ids`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:
1. Visit the forms responses management (`/wp-admin/edit.php?post_type=feedback`) and make sure you're in the `classic` view
2. Update a `source` filter
3. Observe the results and the `source` filter options are displayed as expected.

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-admin.php [hunk 1]
```diff
@@ -862,8 +862,13 @@ public function grunion_source_filter_results( $query ) {
 			return;
 		}
 
-		// Don't apply to the filter dropdown query
-		if ( $query->query_vars['fields'] === 'id=>parent' ) {
```
Comment (ntsekouras) [inline projects/packages/forms/src/contact-form/class-admin.php:866]: In https://github.com/Automattic/jetpack/pull/41602 we made the post type `hierarchical`. I tried to understand why this change affected this check the `fields` was `id=>parent` too, but couldn't figure it out. @anton-vlasenko do you have any thoughts?

**Review by simison — APPROVED** [review]
Tested with simple site classic view and seems to be working as expected

**Review by simison — APPROVED** [review]
Tested also on local jetpack and I can see the issue, and how this fixes it. I tested as rebased to latest trunk.

File: projects/packages/forms/src/contact-form/class-admin.php (hunk 1 above)
Comment (anton-vlasenko) [reply projects/packages/forms/src/contact-form/class-admin.php:866]: Sorry @ntsekouras, this ping somehow went unnoticed as there were many other notifications from the same PR.
