### PR TITLE
Simple payments: load CSS on demand

### LINKED ISSUE #7609: Stylesheet simple-payments.css is always being loaded.
#### Steps to reproduce the issue
See topic: https://wordpress.org/support/topic/what-is-simple-payments-module-and-how-do-i-disable-it/ 

#### What I expected
To `simple-payments.css` not being loaded when I don't have the module activated. 

#### What happened instead
It's being loaded everywhere.

### PR DESCRIPTION
**Pull request by artpi**
Resolves https://github.com/Automattic/jetpack/issues/7609

This loads simple-payments.css on demand only when simple payments feature used.

## Testing

1. Create simple payments button, insert to page
2. Go to a page where it is inserted, inspect source
3. See `simple-payments.css` being loaded
4. Go to a page where simple payments is not used
5. Inspect source - no css being loaded

### CODE REVIEW

File: modules/simple-payments/simple-payments.php [hunk 1]
```diff
@@ -103,6 +102,7 @@ function parse_shortcode( $attrs, $content = false ) {
 		$data['id'] = $attrs['id'];
 		if ( ! wp_script_is( 'paypal-express-checkout', 'enqueued' ) ) {
```
Comment (eliorivero) [inline modules/simple-payments/simple-payments.php]: The second parameter is `'enqueued'` by default so no need to pass it.

File: modules/simple-payments/simple-payments.php [hunk 2]
```diff
@@ -103,6 +102,7 @@ function parse_shortcode( $attrs, $content = false ) {
...
 			wp_enqueue_script( 'paypal-express-checkout' );
+			wp_enqueue_style( 'simple-payments', plugins_url( '/simple-payments.css', __FILE__ ) );
```
Comment (eliorivero) [inline modules/simple-payments/simple-payments.php]: It's not necessary to add the `/` in front of the file name in `plugins_url`. It will be [ltrimmed anyway](https://github.com/WordPress/WordPress/blob/master/wp-includes/link-template.php#L3226).

File: modules/simple-payments/simple-payments.php (hunk 1 above)
Comment (artpi) [inline modules/simple-payments/simple-payments.php]: I always like to err on the side of verbosity in such situations.

File: modules/simple-payments/simple-payments.php (hunk 2 above)
Comment (artpi) [inline modules/simple-payments/simple-payments.php]: Done!

**Review by eliorivero — APPROVED** [review]

**Comment by eliorivero** [comment]
lgtm 🐑
