### PR TITLE
Google Calendar block: Fix full width support

### LINKED ISSUE #14823: Google Calendar block: full width option not working properly
I tried this block with a couple of different themes, and the align-full option didn’t work on the fronted with most (tried a few Varia child themes, and some older ones like Independent Publisher, Shoreditch, Business). The only one where the option worked properly on the frontend was TwentyTwenty. 

#### Steps to reproduce the issue

1. Activate one of Varia child themes (for example Maywood), or an older theme, like Independent Publisher 2
2. Add Google Calendar block to a post or page. Set to full width. It should display properly in the editor.
3. View the post/page on the frontend. Notice it does not occupy full width of the page.

Video demo of the issue: https://cloudup.com/c6An_yxEIyC

There also seems to be an issue with the wide width option - Google Calendar block is not centred, and not as wide as other core blocks when set to wide width. See this example using Shawburn theme:

image

Found while testing the Google Calendar block.

### PR DESCRIPTION
**Pull request by apeatling**
Make sure that the Google Calendar block widths match in the editor and front end, and that full and wide widths are supported correctly.

Fixes #14823

#### Testing instructions:
* Add the Google Calendar block, and embed a calendar. Example: 
```<iframe src="https://calendar.google.com/calendar/embed?src=tl4njqffodltemv385vnifrjadm345g2%40import.calendar.google.com&ctz=America%2FVancouver" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>```
* Modify the alignment of the block to `full width`.
* Save the changes and look at the block on the front end and confirm it is full width (edge to edge).
* Try the `left` and `right` alignment options and confirm the width of the block matches in the front end and the editor.

Note: on some themes (e.g. Twenty Twenty) the left/right positioning of this block in the front end might overflow outside of the viewport because of its `min-width`. Eventually we decided that having a readable calendar on _most_ themes is better than having a squished calendar on _all_ themes. (See discussion in the PR comments)

#### Proposed changelog entry for your changes:
* None

### CODE REVIEW

**Comment by scruffian** [comment]
This looks good, and works as expected. However I can't see how the height attribute is used; it doesn't seem to be working. Is that expected?

**Comment by apeatling** [comment]
> This looks good, and works as expected. However I can't see how the height attribute is used; it doesn't seem to be working. Is that expected?

It seems to set a default initial height of the iframe in the editor. I originally removed it, but in the editor the height of the iframe was always collapsed with no way to override this with CSS.

**Review by scruffian — DISMISSED** [review]
The height attribute seems to be working now. LGTM...

**Review by glendaviesnz — DISMISSED** [review]
The removal of the [min-width on the iframe](https://github.com/Automattic/jetpack/commit/1334560308dfacdb246d095dcd0ada9b1a8355d9#diff-6c3f07277cda5eda687f141e3ef5e805) in the editor causes the calendar to squash to a smaller width on left and right align than on centre. Dave initially [picked this up here](https://github.com/Automattic/jetpack/pull/13999#issuecomment-584875359).

Screen Shot 2020-03-03 at 3 13 48 PM

I vaguely remember a discussion about this, apologies if there was and I didn't pipe up then.

**Comment by apeatling** [comment]
@davemart-in Thoughts on the widths of left and right alignment? I do think it needs to be narrower here to allow for content to sit beside it and not also be squished:

Screen Shot 2020-03-03 at 1 36 37 PM

**Comment by davemart-in** [comment]
@glendaviesnz [here's where it was discussed previously](https://github.com/Automattic/jetpack/pull/13999#issuecomment-585010434). Originating [here](https://github.com/Automattic/jetpack/pull/13999#issuecomment-584875359).

**Comment by davemart-in** [comment]
@apeatling We added a height property to the map block. Should we just add a width property/option in the sidebar here? That way the customer could set the width to whatever works best for their page.

**Comment by apeatling** [comment]
@davemart-in We can do that, I think the issue in my mind is how does this interact with the "full-width"  and "wide" alignment options? Does it just override this width setting?

**Comment by davemart-in** [comment]
@apeatling good question. 

Would it make sense to only show the width option when the alignment is left, right, or center. Or would that be too confusing do you think? 

Another option would be to fix the width to 100% when in full-width and wide mode and disable the control. Then maybe add a line under it saying "Full-width alignment applied", or something like that.

**Comment by Copons** [comment]
There are a couple of weird behaviours going on. 🤔

I don't understand why we set the `height` as block attribute, when there's no way to change it.
Might as well have it in a constant instead, and keep the block footprint lighter?

How the heck is the iframe width calculated when float aligned? 😮
It seems to be always 260px to me...
I've tried adding a `width="600"` to the iframe in the PHP side, and not only it was still rendered 260px wide, but it also changed the height to 260! 😅 
Changing the container's width doesn't seem to do anything as well...

**Comment by glendaviesnz** [comment]
> How the heck is the iframe width calculated when float aligned? 😮

Yeh, I couldn't for the life of me work out where that float width was being inherited from, but this does override it - https://github.com/Automattic/jetpack/commit/1334560308dfacdb246d095dcd0ada9b1a8355d9#diff-6c3f07277cda5eda687f141e3ef5e805

**Comment by glendaviesnz** [comment]
> I don't understand why we set the `height` as block attribute, when there's no way to change it.

It is extracted from the embed code as the user can specify custom height and width when setting up the embed - but we should also have an option for the user to change this once the block is added.

**Comment by apeatling** [comment]
I think we can add back the min width only when the block is aligned left and right. I pretty skeptical that adding a width control is a worth investment though. I think we could just set the min width to 50% when aligned left/right, and support full/width width and move on.

**Comment by apeatling** [comment]
All of the default themes provide default styles for alignleft and alignright floats that causes this to be really problematic. Not to mention themes like TwentyTwenty put floats in their own column with a restricted width.

**Comment by scruffian** [comment]
This opens of the question of how much control we should give users to do things that might not always work well. Its hard to know where to draw the line between giving them the freedom to break stuff and preventing them from creating bad designs.

**Comment by Copons** [comment]
I agree with @apeatling about it not being worth it to add more control over the width when the block is floating.
It would be very hard to make it work with themes that move the block outside the content.

For example, Twenty Twenty does this by forcing a max-width (of 29rem, or 290px) and adjusting the block negative margin of that max-width—and this only on some breakpoints.
By forcing the width to the block to, say, 600px, would mean the block would "overflow" of 310px to the left or right, which would end up being displayed "outside" the viewport.

Screenshot 2020-03-10 at 16 06 36

---

This said, I've found an issue with Twenty Twenty in which blocks don't have a specified width when floating, and for some reason the embed was not resizing correctly when resizing the browser:

Mar-10-2020 16-49-54

I've tried adding a `width: 100%` to the block wrapper, but unfortunately this only works on some themes (Twenty Twenty and Twenty Nineteen: ✅; Varia-based themes ❌).

All in all though I think this PR fixes everything it's in our power to fix, and slightly different behaviours across themes it's ultimately unavoidable.

**Comment by davemart-in** [comment]
> I think we can add back the min width only when the block is aligned left and right.

I'd vote to do this and then call it good.

**Comment by Copons** [comment]
> > I think we can add back the min width only when the block is aligned left and right.
> 
> I'd vote to do this and then call it good.

@davemart-in It was unclear in my previous comment, but I believe this to be very hard to develop.
The problem is that themes treat floaty-aligned blocks in unpredictable ways: some move them outside of the content, some resize them responsively, some calculate the position from the content width, etc.
We can add a min width to the block, but we might break some themes in the process. 😞

**Comment by davemart-in** [comment]
> We can add a min width to the block, but we might break some themes in the process. 😞

The alternative is that the calendar will look broken by default on ALL themes when the alignment is set to left or right. 

calendar-squished

This calendar just looks broken to me. I can't imagine that anyone would want this to show up like this on their site.

Themes can always override the min-width if they want.

**Comment by Copons** [comment]
@davemart-in 🤔 makes sense.

I've tried with `min-width: 420px` (which is roughly the size where an event popup is fully visible in the embed), and this is how it looks at different sizes on Twenty Nineteen and Twenty Twenty:

| 1920 | 1280 | 700 |
| - | - | - |
| Screenshot 2020-03-11 at 14 06 33 | Screenshot 2020-03-11 at 14 06 41 | Screenshot 2020-03-11 at 14 06 50 |
| Screenshot 2020-03-11 at 14 05 22 | Screenshot 2020-03-11 at 14 05 31 | Screenshot 2020-03-11 at 14 05 56 |

Unfortunately Twenty Twenty's float alignment is 290px wide, so at some screen sizes the calendar would end up outside, but there's not much we can do there.
I think this is good enough though, should I commit?

**Comment by davemart-in** [comment]
Aside: Odd that there would be more text content visible in the 700px resolution vs. the 1280px resolution:

text

> I think this is good enough though, should I commit?

I think this is better than the alternative of not setting a min-width, so yes, let's commit it. 

Thank you!

**Comment by apeatling** [comment]
@Copons Thanks for digging into and following up on this one! 🥇

**Comment by apeatling** [comment]
@Copons With your commit I think this is ready for final review, right?

**Comment by Copons** [comment]
> @Copons With your commit I think this is ready for final review, right?

@apeatling Yes I believe so

**Review by scruffian — APPROVED** [review]
Let's merge this 🚢

**Review by jeherve — APPROVED** [review]
This works well for me, it should be good to merge!

File: extensions/blocks/google-calendar/google-calendar.php [hunk 1]
```diff
@@ -35,31 +35,30 @@ function register_block() {
...
+	\Jetpack_Gutenberg::load_assets_as_required( 'google-calendar' );
+
 	if ( empty( $url ) ) {
 		return;
 	}
 
 	if ( class_exists( 'Jetpack_AMP_Support' ) && \Jetpack_AMP_Support::is_amp_request() ) {
 		return sprintf(
-			'<div class="%1$s"><amp-iframe src="%2$s" frameborder="0" style="border:0" scrolling="no" width="%3$d" height="%4$d" sandbox="allow-scripts allow-same-origin" layout="responsive"></amp-iframe></div>',
+			'<div class="%1$s"><amp-iframe src="%2$s" frameborder="0" style="border:0" scrolling="no" height="%3$d" sandbox="allow-scripts allow-same-origin" layout="responsive"></amp-iframe></div>',
```
Comment (westonruter) [inline extensions/blocks/google-calendar/google-calendar.php:52]: This change appears to have broken Google Calendar on AMP pages, since there is no `width` defined, and the `layout` was not changed from `responsive` to `fixed-height`. Opened PR to fix in #17251.
