### PR TITLE
Forms: Fixes date validation bug

### LINKED ISSUE #41599: Forms: date picker doesn't respect input's date format
When I create forms with date inputs:

Image

In the frontend the date picker doesn't actually respect those formats:

Image

Image

2nd and 3rd input are incorrect, but 2nd one isn't marked invalid because both `02` and `12` can be dates or months.

In the 3rd input for example we get:

Image

Expected this instead:

Image

We'll get this fixed with Zap.

### PR DESCRIPTION
**Pull request by enejb**
Fixes #41599

In this video you can see. 
1. The site is using a different locale. The calendar is translated into German. 
2. You are able to pick different formats and submit the form. 
3. If you enter wrong formats validate still works as expected. 

https://github.com/user-attachments/assets/5c544808-d592-4077-b846-12c9a0647ade

## Proposed changes:
* Make sure that we only include the date picker required js once on the page. 
* Make sure that we loop though the different date picker inputs and respect the date format if they are different. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
* Load this Pr. 
* Add 3 date pickers on the page. have different date picker formats. 
* As a visitor make sure that you can submit all the different date pickers as expected.

### CODE REVIEW

**Review by simison — APPROVED** [review]
Nice!

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 1]
```diff
@@ -889,8 +889,6 @@ public function render_date_field( $id, $label, $value, $class, $required, $requ
 
 		wp_enqueue_style( 'jp-jquery-ui-datepicker', plugins_url( '../../dist/contact-form/css/jquery-ui-datepicker.css', __FILE__ ), array( 'dashicons' ), '1.0' );
 
-		// Using Core's built-in datepicker localization routine
-		wp_localize_jquery_ui_datepicker();
```
Comment (edanzer) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php:893]: Is this change needed for this fix/PR to work, or is this code cleanup? 

Also, to confirm my understanding, we can exclude this line because it's included by core? Do we need to worry about situations where this is not included by core?

**Review by edanzer — COMMENTED** [review]
This works as expected now. Multiple date pickers on one page or in one form work correctly, including catching validation errors.

File: projects/packages/forms/src/contact-form/class-contact-form-field.php (hunk 1 above)
Comment (enejb) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php:893]: This is more of a code clean up task. I noticed that it was creating extra calls to jQuery datepicker

Screenshot 2025-02-06 at 12 26 58 PM
