### PR TITLE
Sharing: Change WhatsApp URL for Firefox for desktop

### LINKED ISSUE #12069: Sharing: WhatsApp share button returned "The address wasn't understood" on Firefox
#### Steps to reproduce the issue

1. Add a WhatsApp share button to be shown on posts/pages.
2. On a Firefox browser, click on the WhatsApp share button on the post/page.
3. A new tab will be opened for the WhatsApp API page.

#### What I expected

The new tab should show the WhatsApp API page like this screenshot:

The correct URL should be something like this:

`https://api.whatsapp.com/send?text=Gallery%20Slideshow%20https%3A%2F%2Fpremiumplantestsite20190311.wordpress.com%2F2019%2F04%2F01%2Fgallery-slideshow%2F`

#### What happened instead

The error "The address wasn't understood" was shown on Firefox with invalid URL:

`whatsapp://send?text=Gallery%20Slideshow%20https%3A%2F%2Fpremiumplantestsite20190311.wordpress.com%2F2019%2F04%2F01%2Fgallery-slideshow%2F`

*Note:* I can see a glimpse of the WhatsApp API page before Firefox showed me the error page.

#### Additional notes

The issue was originally reported in 1951401-zen.

### PR DESCRIPTION
**Pull request by kbrown9**
Fixes #12069 

The Firefox desktop browser redirects the "https://api.whatsapp.com/send?..." URL to an invalid address: "whatsapp://send?..."

#### Changes proposed in this Pull Request:

* Detect whether the user's browser is Firefox for desktop using the HTTP user-agent.
* Use the "web.whatsapp.com/..." URL for WhatsApp sharing in Firefox for desktop.
* Use the "api.whatsapp.com/..." URL for WhatsApp sharing in other browsers, including Firefox mobile. This URL is preferred because it shows a send confirmation page before showing the QR code page on desktops. Also, it opens the WhatApp app on mobile devices.

#### Testing instructions:

* Enable Sharing and the WhatsApp button on a post.
* Open the post in Firefox for desktop, and click the post's WhatsApp button.
* The resulting URL should be "https://web.whatsapp.com", and a QR code page should be displayed.
* Open the post in Chrome, Firefox mobile, and other supported browsers, and click the post's WhatsApp button.
* The resulting URL should be "https://api.whatsapp.com/send?...", and a send confirmation page should be displayed or the mobile app should be opened.

#### Proposed changelog entry for your changes:

* Sharing: use "web.whatsapp.com" instead of "api.whatsapp.com" in Firefox for desktop

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
What if we were to use `web.whatsapp.com` for everyone? Would there be any downsides to that? It would simplify things if it were possible.

**Comment by kbrown9** [comment]
> What if we were to use `web.whatsapp.com` for everyone? Would there be any downsides to that? It would simplify things if it were possible.

Unfortunately, `web.whatsapp.com/send?...` doesn't open the WhatsApp app on mobile devices. This URL just redirects to `www.whatsapp.com` on mobile devices.

On mobile devices, `api.whatsapp.com/send?...` opens the WhatsApp app if its installed. Then, the user can send the message from the app. So, `api.whatsapp.com` needs to be used for mobile devices.

File: modules/sharedaddy/sharing-sources.php [hunk 1]
```diff
@@ -1701,7 +1701,17 @@ public function get_display( $post ) {
 	public function process_request( $post, array $post_data ) {
 		// Record stats
 		parent::process_request( $post, $post_data );
-		$url = 'https://api.whatsapp.com/send?text=' . rawurlencode( $this->get_share_title( $post->ID ) . ' ' . $this->get_share_url( $post->ID ) );
+
+		$ua = strtolower( $_SERVER['HTTP_USER_AGENT'] );
```
Comment (jeherve) [inline modules/sharedaddy/sharing-sources.php]: I think it would make sense to use `Jetpack_User_Agent_Info` here, and create a new function in that class to detect Firefox for Desktop, just like we do with `is_firefox_mobile()` for example.
https://github.com/Automattic/jetpack/blob/8d9107fbc1f7d04446a24444c314b8e56e04f7df/class.jetpack-user-agent.php#L685

**Review by jeherve — CHANGES_REQUESTED** [review]
Quick recommendation to make the code cleaner and more explicit.

File: modules/sharedaddy/sharing-sources.php (hunk 1 above)
Comment (kbrown9) [reply modules/sharedaddy/sharing-sources.php]: Good point! The code is cleaner and more explicit now.

File: class.jetpack-user-agent.php [hunk 2]
```diff
@@ -695,6 +695,28 @@ static function is_firefox_mobile( ) {
...
+	 */
+	static function is_firefox_desktop() {
+
+		if ( empty( $_SERVER['HTTP_USER_AGENT'] ) ) {
+			return false;
+		}
+
+		$ua = strtolower( $_SERVER['HTTP_USER_AGENT'] );
+
+		if ( false !== strpos( $ua, 'firefox' ) && false === strpos( $ua, 'mobile' ) && false === strpos( $ua, 'tablet' ) ) {
```
Comment (jeherve) [inline class.jetpack-user-agent.php]: Since the `strpos()` function is case-sensitive, maybe we should say `Mobile` and `Tablet`?

**Review by jeherve — CHANGES_REQUESTED** [review]

File: class.jetpack-user-agent.php (hunk 2 above)
Comment (kbrown9) [reply class.jetpack-user-agent.php]: `$ua` is the user agent string converted to lowercase (see line 712). So, I think that `mobile` and `tablet` are the correct strings to use.

Comment (jeherve) [reply class.jetpack-user-agent.php]: Oh yeah, my bad!

**Review by jeherve — APPROVED** [review]
This is looking good. Thank you!
