### PR TITLE
Change priority of load_map_block_settings action

### LINKED ISSUE #32991: Map block: private sites show a form to enter map access token.
### Impacted plugin

Jetpack

### Quick summary

When the site is set to private **(not private post)**, Map blocks show a different input form stating an access token is required. This only happens on AT, and not on Simple private sites.

I searched internally and in closed issues but it does not appear the "why" is not documented anywhere.

### Steps to reproduce

1. set a site to private.
2. start a new post.
3. add the Map block.

### A clear and concise description of what you expected to happen.

Map block asks for the coordinates like with when the site is public.

### What actually happened

Map block requests a token.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by TimBroddin**
Fixes #32991

## Proposed changes:
The map block settings were not being loaded because the action ran before the script was registered. This PR changes the priority of the action, so the script is registered for sure.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [X] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
1. Apply this PR
2. Test using the instructions in FG: PCYsg-Osp-p2 
3. Mapkit should load on both WPCOM & Atomic

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ public static function init() {
 		add_action( 'admin_enqueue_scripts', array( __CLASS__, 'unbind_focusout_on_wp_admin_bar_menu_toggle' ) );
 
 		// Load the Map block settings.
-		add_action( 'enqueue_block_assets', array( __CLASS__, 'load_map_block_settings' ) );
+		add_action( 'enqueue_block_assets', array( __CLASS__, 'load_map_block_settings', 999 ) );
```
Comment (jeherve) [inline projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php]: I think you'd have to move the priority outside of the array here:

```suggestion
		add_action( 'enqueue_block_assets', array( __CLASS__, 'load_map_block_settings' ), 999 );
```

**Review by jeherve — CHANGES_REQUESTED** [review]

File: projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php (hunk 1 above)
Comment (TimBroddin) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php]: 🫠 My bad. I first (wrongly) made the PR on the wrong repo. I then used the Github editor to quickly make the fix here. I wanted to go too quickly. Thanks for catching this.

**Review by jeherve — APPROVED** [review]
