### PR TITLE
Search: hide unsupported taxonomies from widget

### LINKED ISSUE #24692: Jetpack Search: Taxonomy filters not displaying
### Impacted plugin

Search

### Steps to Reproduce

1. Go to https://tspa-iss-1219.mystagingwebsite.com/explore/resource-library/
2. Enter a keyword on the Search input (eg: "safety" returns valid results)
3. Check out the filters on the right panel

### A clear and concise description of what you expected to happen.

A taxonomy filter for Categories should be displayed

### What actually happened

A list of filters for Date and Post Type is displayed, but not the filter for Categories.

### Other information

- This happens for custom taxonomies as well. For all taxonomies actually.
- On the Production site, it happens only for custom taxonomies but not for Categories
- Could potentially be related to this old issue reported [here](https://github.com/Automattic/jetpack/issues/13813).
- On the cloned test site, there was a taxonomy rename that required SQL updates. However, the issue is also replicable in Production where none of these changes have taken place yet.

Below are screenshots of the configuration:

Screen Shot 2022-06-09 at 15 38 01

Screen Shot 2022-06-09 at 15 40 23

### Operating System

macOS

### OS Version

11.6.5

### Browser

Chrome/Chromium

### Browser Version(s)

100.0.4896

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #24692 

#### Changes proposed in this Pull Request:
<strike>

- Adds custom taxonomies: 
  - 'oecm_audience'
  - 'tspa-resources-topic'
  - 'tspa-resources-type'
  - 'tspa-curriculum-type'
- Added core taxonomies
  - 'category'
  - 'post_tag' 
  - 
</strike>

The PR Hides taxonomies that doesn't exists in our syned taxonomy list, and introduces a filter `jetpack_search_allowed_taxonomies_for_widget_filters` to allow user manage taxonomies shown in search widget filter drop down.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Add the following snippet in active theme's `functions.php`
```PHP
register_taxonomy(
	'foobar-resources-topic',
	'post',
	array(
		'label'             => __( 'Foobar Topic', 'foobar' ),
		'description'       => __( 'The resource topic to be grouped under.', 'foobar' ),
		'public'            => true,
		'hierarchical'      => true,
		'show_admin_column' => true,
	)
);

```
- Switch to branch `fix/hide-unsupported-taxonomies-from-widget-filters`
- Ensure 'Foobar Topic' is NOT shown is JP search widget Taxonomy dropdown

image

- Add the following snippet in active theme's `functions.php`
```PHP
add_filter( 'jetpack_search_allowed_taxonomies_for_widget_filters', function( $taxonomies ){
    $taxonomies[] = 'foobar-resources-topic';
    return $taxonomies;
} );
```
- Ensure 'Foobar Topic' is shown is JP search widget Taxonomy dropdown

image

### CODE REVIEW

**Comment by kangzj** [comment]
Hi @gibrown @robfelty, I'm trying to make the widget only show the supported taxonomies, but I'm a little concerned I could break something. Especially do you have any idea why `category` and `post_tag` are not in `$taxonomies_to_sync`? Thanks

------EDIT------
Also am I right that `class.jetpack-sync-module-search.php` on WPCOM has the white list of taxonomies for indexing?

**Comment by kangzj** [comment]
> I'm trying to make the widget only show the supported taxonomies, but I'm a little concerned I could break something. Especially do you have any idea why `category` and `post_tag` are not in `$taxonomies_to_sync`? Thanks
> 
> ------EDIT------
> Also am I right that `class.jetpack-sync-module-search.php` on WPCOM has the white list of taxonomies for indexing?

Hi @fgiannar @bisko do you have the answers please? Thanks.

PS: The WPCOM diff is `D82983`.

**Comment by fgiannar** [comment]
> I'm trying to make the widget only show the supported taxonomies, but I'm a little concerned I could break something. Especially do you have any idea why category and post_tag are not in $taxonomies_to_sync? Thanks

> Also am I right that class.jetpack-sync-module-search.php on WPCOM has the white list of taxonomies for indexing?

Hi @kangzj ! Looking at pcNPJE-5Y-p2#comment-917 my understanding is that currently `$taxonomies_to_sync` is simply a reference in the class and doesn’t provide any correlation to Sync behaviour.

Same applies for `Search::get_all_taxonomies` which looks like it's only used for testing so far.

This means that ALL taxonomies are synced unless they are blacklisted (see `Defaults::$blacklisted_taxonomies`), aka there's no need to make any changes to the whitelist or on WPCOM to sync any custom or core taxonomy.

However, looking at the same linked comment above my understanding is that there is the **intention** to change this functionality in the future and instead of syncing all taxonomies excluding the blacklisted ones, to only sync the whitelisted ones.

In any case I would recommend removing the `jetpack_sync_taxonomies_to_sync_for_search ` filter from `Search::get_all_taxonomies` _if you intend to use it for filtering which taxonomies to display in the widget_. `get_all_taxonomies` should only care about the taxonomies to sync.

Hopefully @gibrown can provide more context/guidance here since he was involved in the original implementation and discussions.

File: projects/packages/sync/src/modules/class-search.php [hunk 1]
```diff
@@ -1840,7 +1852,17 @@ public static function get_all_unindexed_postmeta_keys() {
...
+		 * Filters the taxonomies that get synced for search.
+		 *
+		 * Note: the list only controls whether to show the taxonomy in the search widget (at least for now).
+		 * If you want to change which taxonomies are indexed, you'd change `class.jetpack-sync-module-search.php` on WPCOM.
+		 *
+		 * @since  $$next-version$$
+		 *
+		 * @param array $taxonomies_to_sync List of taxonomies that get synced for search.
+		 */
+		return apply_filters( 'jetpack_sync_taxonomies_to_sync_for_search', self::$taxonomies_to_sync );
```
Comment (gibrown) [inline projects/packages/sync/src/modules/class-search.php]: This won't actually have any impact on what works because it can't control what we are indexing.

**Comment by gibrown** [comment]
Sorry, I guess we missed the original ping.

@fgiannar is correct, we Sync all taxonomies. The important part here, and what this list controls, is that we do not index all taxonomies. That's why we need to limit what we show in the widget because there are some taxonomies that won't work. This code also gets synced to wp.com where the list is used in our indexing. We also have the same issue with post meta, so having the taxonomy list in the same place as the post meta list makes it easier to manage.

**Comment by kangzj** [comment]
> This means that ALL taxonomies are synced unless they are blacklisted (see Defaults::$blacklisted_taxonomies), aka there's no need to make any changes to the whitelist or on WPCOM to sync any custom or core taxonomy. @fgiannar 

Thanks for the input @fgiannar 👍 

> In any case I would recommend removing the jetpack_sync_taxonomies_to_sync_for_search filter from Search::get_all_taxonomies if you intend to use it for filtering which taxonomies to display in the widget. get_all_taxonomies should only care about the taxonomies to sync. @fgiannar 

> This won't actually have any impact on what works because it can't control what we are indexing. @gibrown 

Thanks for the information. The reason I added the filter is that, we want to allow user to control what's in the filter drop down, because user might requested support for a taxonomy but we don't have it in the current plugin yet.  I'll change the filter name and move it out of the sync package to avoid confusion.


> @fgiannar is correct, we Sync all taxonomies. The important part here, and what this list controls, is that we do not index all taxonomies. That's why we need to limit what we show in the widget because there are some taxonomies that won't work. This code also gets synced to wp.com where the list is used in our indexing. We also have the same issue with post meta, so having the taxonomy list in the same place as the post meta list makes it easier to manage.

Thanks for your clarification @gibrown  👍 


It seems `projects/packages/sync/src/modules/class-search.php` is not synced to WPCOM - do we have any plan to do so? (seems in steps of `pcNPJE-5Y-p2`)  @gibrown

**Comment by kangzj** [comment]
The PR is ready for another review 🎉  It'll be great if you could take another look @fgiannar @gibrown . Thanks heaps

**Comment by gibrown** [comment]
> The reason I added the filter is that, we want to allow user to control what's in the filter drop down, because user might requested support for a taxonomy but we don't have it in the current plugin yet.

I think there could be an opportunity here to add a filter that maps how we sync data. We could add a filter that causes Sync to map one taxonomy to the generic jetpack-search taxonomies (and the same with meta) so that any custom taxonomy data will get copied/synced and the UI will show the custom user taxonomy. It would probably require a re-sync on their end, but that may be a better way for end users to customize their own cases.

Once we add a filter we can never really remove it, so we should make sure it really solves a user problem. I'm not sure adding to the list without actually making it work will solve any problems.

File: projects/packages/search/src/widgets/class-search-widget.php [hunk 2]
```diff
@@ -1053,4 +1054,32 @@ class="widefat filter-count"
...
+					$taxonomy->name,
+					/**
+					 * Filters the taxonomies that shows in filter drop downs of the search widget.
+					 *
+					 * @since  $$next-version$$
+					 *
+					 * @param array $taxonomies_to_show List of taxonomies that shown for search widget.
+					 */
+					apply_filters(
+						'jetpack_search_supported_taxonomies',
```
Comment (gibrown) [inline projects/packages/search/src/widgets/class-search-widget.php]: I feel like this filter could be confusing to users because they will assume that adding a taxonomy makes it work, but it won't.

**Review by gibrown — CHANGES_REQUESTED** [review]
LGTM other than I don't think that filter makes sense to have. I think there is the potential for a filter that does some remapping and that would be a better solution.

**Comment by kangzj** [comment]
> LGTM other than I don't think that filter makes sense to have. I think there is the potential for a filter that does some remapping and that would be a better solution. @gibrown 

Thanks for the feedback @gibrown 👍 

The current workflow to index a new taxonomy is that, 1. add the taxonomy to wpcom whitelist and then 2. add it to the search module in sync package. And we could whitelist a taxonomy anytime, but user wouldn't get the new search module before we release a new version. The filter is intended for the particular scenario. I've renamed the filter to avoid confusion.

I agree we could actually do some mappings thru filtering, but that sounds more like another story to me, and it seems quite a few big changes in a few places to me.

**Review by gibrown — DISMISSED** [review]
> And we could whitelist a taxonomy anytime, but user wouldn't get the new search module before we release a new version. The filter is intended for the particular scenario. I've renamed the filter to avoid confusion.

Ah... yes got it. That makes sense. So they don't have to wait for the next release. Cool.

File: projects/packages/search/src/widgets/class-search-widget.php [hunk 3]
```diff
@@ -1053,4 +1054,32 @@ class="widefat filter-count"
...
+	protected function get_allowed_taxonomies_for_widget_filters() {
+		return array_filter(
+			get_taxonomies( array( 'public' => true ), 'objects' ),
+			function ( $taxonomy ) {
+				return in_array(
+					$taxonomy->name,
+					/**
+					 * Filters the taxonomies that shows in filter drop downs of the search widget.
+					 *
+					 * @since  $$next-version$$
```
Comment (bluefuton) [inline projects/packages/search/src/widgets/class-search-widget.php:1070]: Do we need to change this or is it automatically populated?

Comment (kangzj) [reply projects/packages/search/src/widgets/class-search-widget.php:1070]: @bluefuton  This is a place holder for the next version, which will be replaced on release 😄 

The PR that brought this should be this one: https://github.com/Automattic/jetpack/pull/20386

Comment (bluefuton) [reply projects/packages/search/src/widgets/class-search-widget.php:1070]: Ah nice! TIL.

**Review by gibrown — APPROVED** [review]
Still looks gtg. Thanks!

**Review by bluefuton — APPROVED** [review]
