### PR TITLE
Fix AMP integration by deferring masterbar setup to wp action

### LINKED ISSUE #11081: Masterbar: add_styles_and_scripts not added to admin_enqueue_scripts on Jetpack admin page
#### Steps to reproduce the issue

1. Running `master`, go to Jetpack > Settings > Writing
2. Enable the masterbar
3. The page refreshes, but none of the masterbar scripts and styles are loaded on that page. They are loaded on all the other pages of the site.

image

### LINKED ISSUE #11082: Masterbar: PHP Notices when using the AMP plugin
#### Steps to reproduce the issue

1. Add the AMP plugin to your site.
2. In the plugin options, switch to the "Native" option.
3. Go to Jetpack > Settings > Writing and enable the Masterbar

```
( ! ) Notice: Trying to get property 'post_type' of non-object in /home/dereksma/public_html/wp-content/plugins/amp/includes/class-amp-post-type-support.php on line 80

( ! ) Notice: Trying to get property 'ID' of non-object in /home/dereksma/public_html/wp-content/plugins/amp/includes/class-amp-post-type-support.php on line 101
```

Possible fix: https://github.com/Automattic/jetpack/pull/10945#issuecomment-451312391

This will also require this PR from the AMP end:
https://github.com/ampproject/amp-wp/pull/1794

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #11082 
Fixes #11081

#### Changes proposed in this Pull Request:

* Defer masterbar setup until the `wp` action, instead of doing the setup at the `init` action. This is needed because the `is_amp_endpoint()` function cannot be called before the `wp` action, as it needs access to the queried object.

#### Testing instructions:

1. Ensure Jetpack's masterbar module is active.
2. Activate the AMP plugin v1.0.1
3. Enable the new paired mode via the AMP settings.
4. Navigate to a singular post.

Without the changes in this PR, there should be two PHP notices being raised:

```
( ! ) Notice: Trying to get property 'post_type' of non-object in .../amp/includes/class-amp-post-type-support.php on line 80

( ! ) Notice: Trying to get property 'ID' of non-object in .../amp/includes/class-amp-post-type-support.php on line 101
```

See also https://github.com/ampproject/amp-wp/pull/1794 which will catch the incorrect usage of `is_amp_endpoint()`.

#### Proposed changelog entry for your changes:

* Fix AMP integration with masterbar module.

### CODE REVIEW

**Comment by jeherve** [comment]
The changes in #10945 caused some issues with the Masterbar when on the Jetpack dashboard pages, as reported in #11081.

This PR now stops the masterbar from loading at all on those pages. It works well on other pages, though.

File: modules/masterbar.php [hunk 1]
```diff
@@ -14,7 +14,7 @@
 require dirname( __FILE__ ) . '/masterbar/masterbar.php';
 
 // In order to be able to tell if it's an AMP request or not we have to hook into parse_query at a later priority.
-add_action( 'parse_query', 'jetpack_initialize_masterbar', 99 );
+add_action( 'wp', 'jetpack_initialize_masterbar', 99 );
```
Comment (jeherve) [inline modules/masterbar.php]: It seems to work better (the masterbar loads well whether AMP is active or not) when I use `admin_bar_init` instead of `wp`:

```suggestion
add_action( 'admin_bar_init', 'jetpack_initialize_masterbar', 99 );
```

**Review by jeherve — COMMENTED** [review]
It seems to work better with `admin_bar_init`, although I can't really explain why.

**Comment by jeherve** [comment]
> Were you seeing the masterbar broken in the admin but working on the frontend?

Yep, that's what was happening. Thanks for digging into it!

**Review by jeherve — APPROVED** [review]
This seems to work well on my end. 👍 	🚢

**Comment by westonruter** [comment]
Should this be assigned to me now? I can't merge it 😄

**Comment by jeherve** [comment]
No worries :) Someone else will come around, review and merge :)

**Review by oskosk — APPROVED** [review]
LGTM!
