### PR TITLE
Resolves #40969 - Allow three-letter language code translations in notifications pane

### LINKED ISSUE #40969: Notifications shown in Romanian (ro) instead of Romansh (roh)
### Impacted plugin

Jetpack

### Quick summary

Romansh and Romanian are two completely separate languages.

The reason for this bug is this mistake here where only the two first letters of a locale are used:

https://github.com/Automattic/jetpack/blob/33cea4832d5a206d5a1aa45907d9cdb6516ec88c/projects/plugins/jetpack/modules/notes.php#L200

Not every locale has just 2 letters ⚠ 

At least split by `_` or something, but don't just take the first two letters...

### Steps to reproduce

1. Set locale to `roh` (Romansh) in WordPress
2. Enable Notifications widget
3. Wonder why translation is in Romanian instead of Romansh

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

One

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves #40969 - Allow three-letter language code translations in notifications pane

## Proposed changes:

As of #38871 we truncate the language code in the Notifications panel, but some language codes are three letters long.

This PR corrects this issue by using `explode()` on `_` rather than using `substr()`.

Note that I looked for similar instances of code but this was the only one I saw.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Set locale to `roh` (Romansh) in WordPress.
2. Connect to WordPress.com.
3. Open Notifications widget.

In `trunk`, the notification panel is in Romanian (`ro`). In the `fix/40969/notifications_pane_language_bug` branch, it's in Romansh (`roh`).

### CODE REVIEW

File: projects/plugins/jetpack/modules/notes.php [hunk 1]
```diff
@@ -192,12 +192,18 @@ public function admin_bar_menu() {
 		$third_party_cookie_check_iframe = '<span style="display:none;"><iframe class="jetpack-notes-cookie-check" src="https://widgets.wp.com/3rd-party-cookie-check/index.html"></iframe></span>';
 
 		$title = self::get_notes_markup();
+
+		// The default fallback is `en_US`. Remove underscore if present, noting that lang codes can be more than three chars.
+		if ( str_contains( '_' ) ) {
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/notes.php]: Do we need that `if` condition at all?

Comment (tbradsha) [reply projects/plugins/jetpack/modules/notes.php]: Heh, nope. It was an incomplete leftover when I was testing a less-efficient method. :^)

**Review by anomiex — APPROVED** [review]
Looks reasonable. Haven't tested.
