### PR TITLE
Nav Unification: Fix Upgrades, Jetpack and Settings default menu slugs in WP-Admin

### LINKED ISSUE #19598: Upgrades menu redirecting to `/wp-admin/paid-upgrades.php`
@Automattic/ajax, I have experienced something weird here with the Upgrades menu redirecting to `/wp-admin/paid-upgrades.php` on **Atomic** sites.

Is that expected?

_Originally posted by @cpapazoglou in https://github.com/Automattic/jetpack/issues/19574#issuecomment-823431368_

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes #19598 

#### Changes proposed in this Pull Request:

- In case of `Upgrades` menu, we are safe to remove the default `paid-upgrades.php` submenu item that's generated by core.
- In case of Jetpack menu, for non-administrator roles, the first submenu item (and therefore the default slug of the menu) is the generated by the core's menu behaviour. In this case, when clicking on the menu item, the user will be redirected to a broken page. Just as in the case of `Upgrades`, the core submenu item can be removed.
- The Settings menu item will not appear for Editor roles because the only item displayed in there was `Sharing` which it should be hidden. As in the case of the other pages mentioned above, we are safe to remove this page since it does not contain additional functionality.
#### Does this pull request change what data or activity we track or use?

No
#### Testing instructions:

_Simple_
- Apply D60482-code to your WP.com sandbox.
- Apply also D60627-code to your WP.COM sandbox.
- Sandbox the API and a simple site.
- Go to https://wordpress.com and switch to the sandboxed site.

_Atomic_
- Install Jetpack Beta on a Atomic site and switch to the branch of this PR.
- Go to https://wordpress.com and switch to the WoA site.

Testing paid-upgrades.php:
 - Go to wp-admin dashboard (e.g. `site-name.wordpress.com/wp-admin/` and `site-name.wpcomstaging.com/wp-admin`)
 - Make sure that when clicking on `Upgrades` menu the page is not broken.
 
Testing Jetpack menu:
- Go to wp-admin dashboard with a non-administrator user
- Make sure that when clicking on the `Jetpack` menu the user is not redirected to a broken page.

Testing Settings menu:
- Go to Wordpress.com and login with an admin user.
- Go to wordpress.com and login with a `Editor` user
- Make sure that the `Settings` menu item is not displayed in the navigation

Testing Tools menu:
- Go to wordpress.com and login with a Contributor user
- Make sure that `Tools` menu is no longer displayed.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php [hunk 1]
```diff
@@ -266,7 +266,8 @@ public function add_options_menu( $wp_admin = false ) {
 
 		add_submenu_page( 'options-general.php', esc_attr__( 'Hosting Configuration', 'jetpack' ), __( 'Hosting Configuration', 'jetpack' ), 'manage_options', 'https://wordpress.com/hosting-config/' . $this->domain, null, 6 );
 
-		$this->hide_submenu_page( 'options-general.php', 'sharing' );
+		// We are safe to remove this page because it does not have any additional information and it's not a main page.
+		remove_submenu_page( 'options-general.php', 'sharing' );
```
Comment (cpapazoglou) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php:270]: Should we do the same for Atomic sites?

With an `editor` user, I get a "Sharing" menu that has no link

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Tested this as an `admin` and as an `editor` both in Simple & Atomic sites and works as advertised.

I have just noticed that Settings menu is still displayed in Atomic sites for an `editor`.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php (hunk 1 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php:270]: If we'll remove it for Atomic, should we also remove it from Jetpack sites? 🤔  If so, we could move that snippet directly to class-admin-menu.

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php:270]: I think we should because it's already removed in WPCOM. I'll update the PR right now! :)

**Comment by jeherve** [comment]
I'm moving this out of the milestone since it seems that it's still in progress, and since we're approaching code freeze.

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php [hunk 2]
```diff
@@ -218,8 +211,17 @@ public function get_item_schema() {
 	private function prepare_menu_item( array $menu_item ) {
 		global $submenu;
 
-		// Exclude unauthorized menu items.
-		if ( ! current_user_can( $menu_item[1] ) ) {
+		$current_user_can_access_menu = current_user_can( $menu_item[1] );
+		$has_first_menu_item          = isset( $submenu[ $menu_item[2] ][0] );
```
Comment (mmtr) [inline projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:215]: Non-blocking: I know this is just a refactor keeping the existing behavior, but ideally we would show the parent menu as long as the user can access any of the submenus, not only the first one.

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php [hunk 3]
```diff
@@ -218,8 +211,17 @@ public function get_item_schema() {
...
+		$menu_slug                    = $menu_item[2];
+
+		// Exclude unauthorized menu items when the user does not have access to the menu and the first submenu item.
+		if ( ! $current_user_can_access_menu && $has_first_menu_item && ! current_user_can( $submenu[ $menu_slug ][0][1] ) ) {
+			return array();
+		}
+
+		// Exclude unauthorized menu items that don't have submenus.
```
Comment (mmtr) [inline projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:223]: Is this comment accurate? I think it's technically possible to have a submenu with the `0` position unset with other positions like `1` set, and in such cases we won't be excluding the menu item.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php [hunk 4]
```diff
@@ -68,6 +68,9 @@ public function reregister_menu_items() {
 			remove_menu_page( 'link-manager.php' );
 		}
 
+		$this->sort_hidden_submenus();
+		$this->hide_unauthorized_menus();
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: Seems this could be part of `Base_Admin_menu`?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php [hunk 5]
```diff
@@ -148,6 +151,7 @@ public function add_upgrades_menu( $plan = null ) {
 
 		if ( ! $menu_exists ) {
 			// Remove the submenu auto-created by Core.
+			// We remove it instead of hiding it because WP-Admin will see it as the first submenu item and therefore it acts as the menu's default URL.
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:154]: This comment confuses me. We're actually hiding the menu, aren't we? Why the comment says "We remove it instead of hiding it"?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 6]
```diff
@@ -455,6 +455,74 @@ public function override_svg_icons() {
 		}
 	}
 
+	/**
+	 * Hide menus that are unauthorized and don't have visible submenus.
+	 *
+	 * This must be done at the end of menu and submenu manipulation in order to avoid performing this check each time
+	 * the submenus are altered.
+	 */
+	public function hide_unauthorized_menus() {
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: TIL that Core does not filter out unauthorized menu items when rendering the URL of the first submenu as menu link ([there is a `current_user_can( $submenu_items[0][1] )` missing here](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/menu-header.php?rev=49193#L152)). That sounds like a bug to me, so it'd be good to maybe create a Trac ticket.

I think this logic runs both when rendering the menu in WP Admin and during requests to the `admin-menu` API endpoint (used for rendering the menu in Calypso). I noted this function slightly duplicates logic from the endpoint. Can we remove it and keep this function as the singe source?

This seems to duplicate some logic we're doing in the `admin-menu` endpoint. In theory, Core already filters out unauthorized menu items in WP Admin, and our `admin-menu` API endpoint already does it as well.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 7]
```diff
@@ -455,6 +455,74 @@ public function override_svg_icons() {
...
+		}
+	}
+
+	/**
+	 * Check if the given item is visible or not in the admin menu.
+	 *
+	 * @param array $item A menu or submenu array.
+	 */
+	public function is_item_visible( $item ) {
+		return ! isset( $item[4] ) || false === strpos( self::HIDE_CSS_CLASS, $item[4] );
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:523]: Non-blocking: We could refactor the `has_visible_items` function to use this new function.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 5 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:154]: Oh yeah, good catch. That comment should be removed. When I started working on this PR I  replaced the hide_submenu_page with `remove_submenu_page` and added that comment. 

However, I've found another way to keep this and re-added hide_* method but forgot to remove that comment. :)

**Review by mmtr — COMMENTED** [review]
Just went through the testing instruction, and everything worked as expected. Left some minor code-wise comments.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 5 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:154]: > I've found another way to keep this and re-added hide_* method

Should we do the same then in `add_jetpack_menu`?

https://github.com/Automattic/jetpack/blob/6d33f193152bcde58d68271908fabacbb571a634/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L423

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: It's not actually a bug, imho. The submenus are filtered based on their capabilities. The problem is with the `hide-if-js` css; submenus with that class would not be filtered. Because of this, if you hide the first submenu item the menu would still use that slug as a default URL.

Actually... If you think about it, we could simplify a bit the logic from admin-menu endpoint, I think, by removing those checks and try to use Core's way of filtering those submenus (from what I remember the menu and submenus arrays are not filtered in the admin-menu endpoint). But that's just a theory.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 7 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:523]: Sure, great idea! 👍

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: Imho, we should leave it as it is because, for example, in Domains only admin menu class we don't have any use for it.

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php (hunk 3 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:223]: Oh, yeah, you are right, thanks! :)

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: > The submenus are filtered based on their capabilities
Except when their links are used in the parent menu. [In that case](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/menu-header.php?rev=49193#L168) Core does not check any capability. 

> This method is used to apply the hide CSS class to the menu

Which in turn will prevent the menu/submenu items from showing up in the menu, so we wouldn't need the logic below, right?

https://github.com/Automattic/jetpack/blob/6d33f193152bcde58d68271908fabacbb571a634/projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php#L218-L226

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php (hunk 2 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:215]: I think we should look into how/where Core filters unauthorized submenus. From what I remember, in the endpoint, the submenus are not filtered yet based on their capabilities (I'll have to recheck) while in the Core menu, when they are displayed, I'm certain they are.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: That's true at the moment, but that's also a particularity of the domain only menu class which don't register with any submenu and don't need to deal with any hidden menu.

I'm worried about future cases where other developers may need it but they won't be aware that they need to perform these calls. `Base_Admin_Menu` is intended to be the default class for the menu manipulation, and I consider this sort/hiding functionality a pretty basic behavior that should be performed always.

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php (hunk 2 above)
Comment (mmtr) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:215]: > I think we should look into how/where Core filters unauthorized submenus

[All of them are filtered out](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/menu-header.php?rev=49193#L201).

Comment (mmtr) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php:215]: Scratch that, my previous comment was referring to how the submenus are rendered, but my original comment was referring to how the parent menu is rendered, which always uses the first submenu ([but doesn't check its capability](https://github.com/Automattic/jetpack/pull/19604#discussion_r621274338)), so it's fine to leave this as-is, so we're aligned with Core.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: > Except when their links are used in the parent menu. In that case Core does not check any capability.

hmmm... 🤔  I believe $submenu_items array from menu-header.php contains only submenus with the correct capability for the current user. I thought the same when I've looked over that implementation.

> Which in turn will prevent the menu/submenu items from showing up in the menu, so we wouldn't need the logic below, right?

🤔  The hide logic only applies to our own custom implementation (adding that css class), but this logic is used to check for the WP capabilities and filters out the response. It's unrelated to that implementation 🤔

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 5 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:154]: I think we should leave it removed for jetpack, I think. I know we had some troubles with that submenu on non-admin pages. Either way it's fine, I think. :)

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: > I believe $submenu_items array from menu-header.php contains only submenus with the correct capability for the current user

You're right! Not sure how I missed that. [The submenus are not added if the user doesn't have the proper capability](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/plugin.php?rev=49193#L1408).

In that case, why do we need the `hide_unauthorized_menus` function?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 5 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:154]: That's fine, I don't see why the behavior would be different, but happy to have a diverging logic if that's causing any trouble. It'd be great if we could add a comment clarifying it.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: Yeah, I know what you mean, I'm not too fond of it as well. My only concern with moving it to `Base_Admin_Menu` is that we would make `reregister_menu_items` a concrete again and forcing each child to call the parent, if not, the those methods will not be called. The parent method would also have to be called at the end of the child method, which other people might find it unintuitive (most of the time parent methods are called at the beginning of the method). 

Another approach would be to extract these two methods (and their implementation) into another class that would act like a Decorator or maybe Strategy class in the load.php script. 
This way, we:
- make sure that those two methods are called exactly right after the reregister method.
- We decouple this logic from admin menu classes which should contain only product specific business logic.

I think this should be pretty easy to do, we'll only have to create that class and move this add_action from the Base_Admin_Menu constructor:
```
add_action( 'admin_menu', array( $this, 'reregister_menu_items' ), 99998 )
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: It's needed because we need to simulate this for submenus that are hidden as well. I think an example would be helpful. 
- Let's say you login in wp-admin with a Contributor account. 
- The menu `Tools` contains only the default submenu `tools.php` which is hidden with our CSS class even though the user has the capability to access that page.
- Tools menu contains a link to tools.php since that's the default slug.
- In this case, we should hide the entire menu `Tools` since it would point to tools.php (which has been hidden by our implementation).

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: What if we move these calls to separate and independent `admin_menu` hooks that run` after `reregister_menu_items` runs??

```php
class Base_Admin_Menu {
  protected function __construct() {
    add_action( 'admin_menu', array( $this, 'reregister_menu_items' ), 99998 );
    add_action( 'admin_menu', array( $this, 'handle_hidden_submenus' ), 99999 );
    add_action( 'admin_menu', array( $this, 'hide_unauthorized_menus' ), 99999 );
  }
}
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: Ok, that makes sense, but it's not related to any unauthorized submenu, isn't it? The Tools menu is hidden because we don't want to show that WP Admin page to WP.com users, not because the user doesn't have the proper capability. As result, the `tools.php` submenu does not contain any visible submenu and therefore the parent menu is hidden. 

I wrongly assumed that `hide_unauthorized_menus` was handling only unauthorized menus/submenus.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: It could work, I thought about it as well but I wanted to be sure they are executed immediately after the menus are manipulated otherwise they'll be in an inconsistent state until those two methods are called. Also, the order of the methods is also important because `hide_unauthorized_menus` assumes that the hidden elements are always at the end of the array; that's why it checks if the first element is hidden (meaning that we are safe to say that all elements are hidden). 

The probability of it happening is small, haha. In the end, since we only have just one place were I we use them, I thought it's just simpler to call them at the end of that method. The possibility of someone adding another action just between reregister_menu_items and our cleanup methods are small. But hey, it's still a possibility right? :D

What do you think? :)

Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: > the order of the methods is also important because hide_unauthorized_menus assumes that the hidden elements are always at the end of the array

If that is a required dependency, why don't we call `sort_hidden_submenus` within `hide_unauthorized_menus `?

```php
public function hide_unauthorized_menus() {
  $this->sort_hidden_submenus();
  
  // ...
}
```

> The possibility of someone adding another action just between reregister_menu_items and our cleanup methods are small

I think that's a safe risk to take. If the resulting code is more maintainable and readable, let's not deal with edge cases that are extremely unlikely to happen.

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: > If that is a required dependency, why don't we call sort_hidden_submenus within hide_unauthorized_menus ?

The main purpose of the sort method is to move the hidden submenus at the end of the array, in order to be sure that hidden submenus will not be used as default menu slugs. `hide_unauthorized_menus` just benefits of that behaviour. :) 

Initially I had both functionalities in the same method, but I considered that it does too many things and I moved it to a separate method. 

Moving the sort in hide_unauthorized_menus  would make the method do too many things, imho, even though the actual implementation is in another place. I could add an anonymous function instead, so the change would like this: 
```
    add_action(
        'admin_menu', 
        function () {
            $this->sort_hidden_submenus();
            $this-> hide_unauthorized_menus();
       }, 
     99999 
   );
``` 
What do you think? 🤔

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 6 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:464]: Yes, that's correct. I'll rename the method to `hide_parent_of_hidden_submenus`. :)

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php (hunk 4 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: > Moving the sort in hide_unauthorized_menus would make the method do too many things

See it this way: does `hide_unauthorized_menus` work correctly if `sort_hidden_submenus` is not called first? If not, `hide_unauthorized_menus` should call `sort_hidden_submenus`.

> I could add an anonymous function instead

Actions should be hooked using a named function, otherwise they cannot be unhooked if needed.

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php:72]: > See it this way: does hide_unauthorized_menus work correctly if sort_hidden_submenus is not called first? If not, hide_unauthorized_menus should call sort_hidden_submenus.

Hmm... good point.

> Actions should be hooked using a named function, otherwise they cannot be unhooked if needed.

Oh, good to know that. :)

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php [hunk 8]
```diff
@@ -351,7 +350,44 @@ function ( $preference ) {
...
+		$sidebar_collapsed = isset( $calypso_preferences['sidebarCollapsed'] ) ? $calypso_preferences['sidebarCollapsed'] : false;
 		set_user_setting( 'mfold', $sidebar_collapsed ? 'f' : 'o' );
 	}
+
+	/**
+	 * Removes unwanted submenu items.
+	 *
+	 * These submenus are added across wp-content and should be removed together with these function calls.
+	 */
+	public function remove_submenus() {
```
Comment (BogdanUngureanu) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php:364]: This method was moved from the WPCOM repository in order to have the logic in one place.

File: projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php [hunk 9]
```diff
@@ -252,6 +252,44 @@ public function submenu_item_data() {
 		);
 	}
 
+	/**
+	 * Check if the menu URL is properly generated from the first submenu slug.
+	 */
+	public function test_if_the_first_submenu_url_is_used_for_menu_url() {
+		global $menu;
+
+		add_menu_page( '', __( 'Foo', 'jetpack' ), 'read', 'foo' );
```
Comment (mmtr) [inline projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php:261]: Nitpick: Given this is a test, we don't need to translate the title.
```suggestion
		add_menu_page( '', 'Foo', 'read', 'foo' );
```

File: projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php [hunk 10]
```diff
@@ -252,6 +252,44 @@ public function submenu_item_data() {
...
+			if ( 'foo' === $menu_item[2] ) {
+				$foo_item = $menu_item;
+				break;
+			}
+		}
+
+		$class = new ReflectionClass( 'WPCOM_REST_API_V2_Endpoint_Admin_Menu' );
+
+		$prepare_menu_item = $class->getMethod( 'prepare_menu_item' );
+		$prepare_menu_item->setAccessible( true );
```
Comment (mmtr) [inline projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php:277]: What if we change the signature of the `prepare_menu_item ` method so it's `public` to avoid this? I don't think we have any good reason for keeping it private.

**Review by mmtr — APPROVED** [review]
Fabulous work, @BogdanUngureanu. Thanks for adding the unit tests! I have not found any regression, so this should be good to go 🚀

**Review by cpapazoglou — DISMISSED** [review]

**Review by mmtr — APPROVED** [review]

File: projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php (hunk 10 above)
Comment (BogdanUngureanu) [reply projects/plugins/jetpack/tests/php/core-api/wpcom-endpoints/test-class-wpcom-rest-api-v2-endpoint-admin-menu.php:277]: Personally I prefer having them private, even though that means testing would be a bit harder, because we can differentiate between which methods are endpoints (and are part of the public API) and which are just helper methods. 

But if we'll make this public, then we should also make prepare_submenu_item public? :)

**Comment by cpapazoglou** [comment]
Tested this again on Simple by following the testing instructions. Issues were resolved and I can't see any regression! Great job @BogdanUngureanu!

**Review by mmtr — APPROVED** [review]
Re-tested Simple sites with the updated diff and everything looked great.

**Comment by mmtr** [comment]
Deployed to WP.com in r225022-wpcom

**Comment by jeherve** [comment]
Cherry-picked to `jetpack/branch-9.7` in 2cff2c41bd58233e27e7d79b0a685113460e4bdf
