### PR TITLE
Fix missing likers in likers popup 

### LINKED ISSUE #86471: Like block / widget: If the site's default Gravatar is set to "Mystery person", the "other likers" popover won't load likers that don't have any Gravatar set
If the site's default Gravatar is set to "Mystery person" (in the Discussion settings):

Image

 the "other likers" popover won't load likers that don't have any Gravatar set:

Image
Image

### PR DESCRIPTION
**Pull request by JuanLucha**
Fixes https://github.com/Automattic/wp-calypso/issues/86471

## Proposed changes:

When the user clicks in the "x likes" label in the likes block, a popup appears with the likers list:
Screenshot 2024-01-18 at 15 23 59

The problem was this: users without Gravatar profiles were missing from the list. This was happening because the avatar URL had this format:

`https://[url-of-the-gravatar-image]?d=[url-of-the-default-avatar-in-case-the-previous-url-fails]`

That redirection was because the redirection from the `d` parameter gave CORS problems from sites not hosted on WordPress.com. If there is any problem retrieving the avatar image (like this CORS problem), that liker was removed from the list. 

This PR checks manually for the URL in the `d` param after the CORS error happens, so the likers don't disappear from the list.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
No

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
- Apply this PR to your local repository and spin your JT site.
- Open a post with a like block on the site.
- You need to have at least 2 likers and at least 1 liker without Gravatar profile on that post. You can get one by opening the post in incognito and pressing the "like" button. In the login popup, create an account instead. That account won't have a Gravatar profile created yet.
- Click on the "x likes" label and see all of the likers appear in the popup, regardless of whether they have a profile picture or not.

### CODE REVIEW

**Comment by simison** [comment]
Why `fetch` the image instead of just using `` ?

**Comment by simison** [comment]
Does the fallback gravatar rely on what's set in site's WordPress settings as Gravatar setting?

I noticed it wasn't "mystery person" in the screenshot, for example.

**Comment by JuanLucha** [comment]
Hi @simison !

> Why fetch the image instead of just using  ?

You are right. After removing a double encoding, it works without fetching. And, as there is no script making the request, no CORS problem is found after the redirection to the `d` param. Good point! 👍 

> Does the fallback gravatar rely on what's set in site's WordPress settings as Gravatar setting?

Yes, indeed. If I change the default site avatar in the Discussion Settings...

Screenshot 2024-01-19 at 19 45 38

... I can see the new avatar in the frontend:

Screenshot 2024-01-19 at 19 45 27

Thanks for taking a look at the PR! I'll upload the change right away.

File: projects/plugins/jetpack/modules/likes/queuehandler.js [hunk 1]
```diff
@@ -236,40 +236,12 @@ function JetpackLikesMessageListener( event ) {
...
-							element.remove();
-							return;
-						}
-					} else {
-						// Error occurred while checking image existence, remove the element
-						element.remove();
-						return;
-					}
-				}
-
```
Comment (ivan-ottinger) [inline projects/plugins/jetpack/modules/likes/queuehandler.js]: Just noting here that the original thinking behind introducing this section was to keep `projects/plugins/jetpack/modules/likes/queuehandler.js` logic in sync to what we already have on the WPCOM side (since it has its own `queuehandler.js` from the times before we started working on the Like block project).

Here's related patch that introduced some of the changes to WPCOM: D133753-code.

From my perspective, we can skip fetching if we are ok that WPCOM side will work slightly differently than the JP side. Alternatively, we could remove fetching from the WPCOM side as well.

Comment (simison) [reply projects/plugins/jetpack/modules/likes/queuehandler.js]: >From my perspective, we can skip fetching if we are ok that WPCOM side will work slightly differently than the JP side. Alternatively, we could remove fetching from the WPCOM side as well.

Why would we need fetching at .com? Jetpack features should work as closely the same across both, without divergence in code because it becomes a pain to maintain otherwise.

Comment (ivan-ottinger) [reply projects/plugins/jetpack/modules/likes/queuehandler.js]: > Why would we need fetching at .com?

The fetch was introduced in D109839-code in May 2023 to check if the image exists.

What I think we could do is to look deeper why a certain image would not exist.

Comment (ivan-ottinger) [reply projects/plugins/jetpack/modules/likes/queuehandler.js]: I have reviewed sites that were used for testing of the D109839-code.

In both cases where the Gravatar did not load for particular like, the cause was in the way we use `encodeURI()` before outputting the image source into the markup.

The link in `liker.avatar_URL` is already encoded and hence we shouldn't need to encode it again.

**Example of broken image source (that won't load):** 

```
https://1.gravatar.com/avatar/d31ca30985696421ec80809ea6af03208eb0d819fb633e5e111ed9f7ccab9fea?s=96&d=https%253A%252F%252F1.gravatar.com%252Favatar%252Fad516503a11cd5ca435acc9bb6523536%253Fs%253D96&r=G
```

Correct image source (how it should be instead):

```
https://1.gravatar.com/avatar/d31ca30985696421ec80809ea6af03208eb0d819fb633e5e111ed9f7ccab9fea?s=96&d=https%3A%2F%2F1.gravatar.com%2Favatar%2Fad516503a11cd5ca435acc9bb6523536%3Fs%3D96&r=G
```

The Gravatars loaded to the side of the button don't encode the image source already (can be found in `widgets.wp.com/likes/master.html`). The issue is in the popup only:

| By the Like button | In the popup |
|--------|--------|
| Markup on 2024-01-22 at 17:30:33 | Markup on 2024-01-22 at 17:30:50 | 

---

What we can do is to remove the fetch from both WPCOM and JP side and just make sure we won't run that extra `encodeURI()`.

What do you think folks? 🙂

Comment (JuanLucha) [reply projects/plugins/jetpack/modules/likes/queuehandler.js]: Yeah, I agree. Following @simison suggestion, I removed the fetching of the avatar from the jetpack side. We can do the same in the wpcom side.

**Review by ivan-ottinger — APPROVED** [review]
Rebased & approved. ✅ 

Going to merge once the tests pass and prepare a WPCOM patch that will apply similar changes.

**Comment by ivan-ottinger** [comment]
Related D135617-code has landed to WPCOM as well.
