### PR TITLE
Paid newsletters fix access levels

### LINKED ISSUE #29205: Subscriptions: Disappearing access selector
When debugging, we found a weird state.

This post **does not have a newsletter panel:**

https://membershipsandbox1.wordpress.com/wp-admin/post.php?post=8&action=edit

Zrzut ekranu 2023-02-28 o 13 24 17

This post **does** have a newsletter panel

https://membershipsandbox1.wordpress.com/wp-admin/post.php?post=11&action=edit

Zrzut ekranu 2023-02-28 o 13 24 45

This is the same site. 

### Reproduction path

1. Sandbox the site, and public-api
2. Sandbox store
3. Visit those URLs

### PR DESCRIPTION
**Pull request by artpi**
This fixes issues 

- Fixes #29205 - access panel selector would disappear on previously published posts
- Also fixes the issue where the select panel would not show the selected option

## Does this pull request change what data or activity we track or use?

NO

## Testing instructions:

- Get a site with payments configured - you can use `membershipsandbox1.wordpress.com`
- Sandbox public-api, site domain, and store
- Create a post, publish it and reload the editor
- See the newsletter access there

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js [hunk 1]
```diff
@@ -104,7 +103,10 @@ export function NewsletterAccess( { accessLevel, setPostMeta, withModal = true }
 												help={ __( 'Control how this newsletter is viewed.', 'jetpack' ) }
 												onClose={ onClose }
 											/>
-											<NewsletterAccessChoices onChange={ setPostMeta } />
+											<NewsletterAccessChoices
+												accessLevel={ accessLevel }
+												onChange={ setPostMeta }
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js:108]: That is fixed in https://github.com/Automattic/jetpack/pull/29042

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js [hunk 2]
```diff
@@ -65,12 +81,7 @@ export default function SubscribePanels() {
 	const showNotices = Number.isFinite( subscriberCount ) && subscriberCount > 0;
 	return (
 		<>
-			{ isNewsletterFeatureEnabled() && (
-				<PluginDocumentSettingPanel title={ __( 'Newsletter', 'jetpack' ) }>
-					<NewsletterAccess setPostMeta={ setPostMeta } accessLevel={ accessLevel } />
-				</PluginDocumentSettingPanel>
-			) }
-
+			{ renderAccessLevelSelectorPanel( setPostMeta, accessLevel ) }
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: I think the React way would be 
```suggestion
			<RenderAccessLevelSelectorPanel accessLevel={accessLevel}  onChange={ setPostMeta } />
```

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js [hunk 3]
```diff
@@ -31,27 +45,29 @@ export default function SubscribePanels() {
...
 
-	// Subscriptions will not be triggered on private sites (on WordPress.com simple and WoA),
-	// nor on sites that have not been launched yet.
-	if ( isPrivateSite() || isComingSoon() ) {
-		return null;
+	// Subscriptions will not be triggered for a post that was already published in the past and the email was sent.
+	// We still need to render the access level selector, as historical posts need a way to edit their access level for people visiting them on the web.
+	// TODO: Additionally, pages also can be protected. They will not send an email, but can be a resource that needs the acces selector.
+	if ( postWasEverPublished ) {
+		return renderAccessLevelSelectorPanel( setPostMeta, accessLevel );
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Same. I think it would be best to use the tag version...

Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Maybe we could actually use that check directly isn the last "return" and prevent some complexity?

**Review by millerf — COMMENTED** [review]
The logic works perfectly, but I think there are some possible tweaks to be done...

File: projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js (hunk 1 above)
Comment (artpi) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js:108]: Which is not yet approved

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js (hunk 2 above)
Comment (artpi) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: No. React way would be `AccessLevelSelectorPanel`

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js (hunk 3 above)
Comment (artpi) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: > Maybe we could actually use that check directly isn the last "return" and prevent some complexity?

I am not sure I follow

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js (hunk 2 above)
Comment (artpi) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Done!

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js [hunk 4]
```diff
@@ -65,12 +81,7 @@ export default function SubscribePanels() {
 	const showNotices = Number.isFinite( subscriberCount ) && subscriberCount > 0;
 	return (
 		<>
-			{ isNewsletterFeatureEnabled() && (
-				<PluginDocumentSettingPanel title={ __( 'Newsletter', 'jetpack' ) }>
-					<NewsletterAccess setPostMeta={ setPostMeta } accessLevel={ accessLevel } />
-				</PluginDocumentSettingPanel>
-			) }
-
+			<AccessLevelSelectorPanel setPostMeta={ setPostMeta } accessLevel={ accessLevel } />
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:84]: This is what I meant earlier, if that makes sense:
```suggestion
			<AccessLevelSelectorPanel setPostMeta={ setPostMeta } accessLevel={ accessLevel } />
			 
			  { ! postWasEverPublished && (
			    
			    [ rest of the file ]
			  
			  )}
```
But it was only how I would do it...

File: projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js (hunk 1 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js:108]: Which I am gonna struggle to rebase after this one... :(

**Review by millerf — APPROVED** [review]
LGTM :)

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js (hunk 3 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: See https://github.com/Automattic/jetpack/pull/29247#discussion_r1124110423
But again, it doesn't make any difference.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js (hunk 1 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/settings.js:108]: > Which is not yet approved

But it is in review :)

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢 

(I should say that the `PluginDocumentSettingPanel` panel location still confuses me, vs. the other panels in the Jetpack plugin sidebar).
