### PR TITLE
Gold/fix/recurring payments plan ids

### LINKED ISSUE #34686: Payments Block: Payment Plan Deselected Upon Page Update
### Impacted plugin

Jetpack, mu wpcom

### Quick summary

When updating a page with a Payment button block on it, the payment plan gets deselected, and therefore the button disappears. 

### Steps to reproduce

1. Create a page with some text.
2. Add a Payment button block.
3. Select a payment plan.
4. Publish the page. Notice the payment button appears publicly.
5. Go back and make an edit to the text on the page.
6. Update the page. Notice the payment button is now gone from the public page.
7. Check the payment button block toolbar and the payment plan has been deselected.

Video of these steps below.

### A clear and concise description of what you expected to happen.

I expected my payment plan to stay selected and the button to stay on the page.

### What actually happened

The button disappears when making an edit on the page unrelated to the button. Video:

https://github.com/Automattic/jetpack/assets/30727666/f75b75a5-28ce-456f-90e5-d1e8e7052917

### Impact

All

### Available workarounds?

Yes, difficult to implement

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Encountered in #7430454-zen and recreated on a simple site on WordPress.com.

### PR DESCRIPTION
**Pull request by n3f**
Fixes #34686.

## Proposed changes:

* Moves attribute `planId` to `planIds`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Start with a memberships enabled site on JN/Atomic or WPCOM.
1. Create a post with a recurring payments button.
1. Create a post with a paid content block
1. Create a newsletter tier accessible post.
1. Verify checkout on those posts works. (in incognito window).
1. Add the jetpack code (On JN you can use the jetpack-beta plugin to apply the `gold/fix/recurring-payments-plan-ids` branch and on WPCOM you can use `bin/jetpack-downloader test jetpack gold/fix/recurring-payments-plan-ids`).  If you are testing on JN, apply the PR on WPCOM too.
1. Open the paid content block post and verify you can select and save multiple plans.
1. Verify checkout on all posts works (again). (in incognito window)
1. Verify the paid content and newsletter users can view the correct posts.
1. Ensure that refreshing a post and modifying text doesn't break any of the memberships blocks.

### CODE REVIEW

File: projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php [hunk 1]
```diff
@@ -359,13 +359,14 @@ public function render_button( $attributes, $content = null, $block = null ) {
...
 
-		if ( empty( $attributes['planId'] ) ) {
+		if ( empty( $attributes['planId'] ) && empty( $attributes['planIds'] ) ) {
 			return $this->render_button_error( new WP_Error( 'jetpack-memberships-rb-npi', __( 'No plan was configured for this button.', 'jetpack' ) . ' ' . __( 'Edit this post and confirm that an existing payment plan is selected for this block.', 'jetpack' ) ) );
 		}
 
 		// This is string of '+` separated plan ids. Loop through them and
 		// filter out the ones that are not valid.
-		$plan_ids    = explode( '+', $attributes['planId'] );
+		// phpcs:ignore Universal.Operators.DisallowShortTernary.Found
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php]: As long as WordPress Core has this rule, let's not ignore it.

And anyway, with an existing button (using planId), the line below is generating PHP warnings:
```
Warning:  Undefined array key "planIds" in /path/to/wp-content/plugins/jetpack-dev/modules/memberships/class-jetpack-memberships.php on line 369
```

File: projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php [hunk 2]
```diff
@@ -359,13 +359,14 @@ public function render_button( $attributes, $content = null, $block = null ) {
...
+		$plan_ids    = $attributes['planIds'] ?: explode( '+', $attributes['planId'] );
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php]:
```suggestion
		$plan_ids    = empty( $attributes['planIds'] ) ? explode( '+', $attributes['planId'] ) : $attributes['planIds'];
```
Or you could use `??` (which doesn't have a PHPCS rule complaining about it) in place of `?:` if we're not worried that planIds might come in as an empty array somehow.

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 3]
```diff
@@ -15,17 +15,41 @@ import { getBlockStyles } from './util';
...
-		const _planIds = ( '' + planId ).split( '+' ).map( id => parseInt( id, 10 ) );
-		return _planIds;
-	}, [ planId ] );
+	const { align, planId, planIds, width } = attributes;
+
+	const _planIds = useMemo( () => {
+		return planIds || ( planId ? [ planId ] : [] );
+	}, [ planId, planIds ] );
+
+	// planId is a integer, planIds is a plus-separated string of integers.
```
Comment (anomiex) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx]: planIds itself is an array, the plus-separated string is only in the URL and the uniqueId.
```suggestion
	// planId is a integer, planIds is an array of integers.
```

**Review by anomiex — COMMENTED** [review]
Payments Button seems to work in some quick testing of the original error, other than the PHP warning mentioned in an inline comment.

Haven't tested the paid contents block or other stuff.

**Comment by ice9js** [comment]
I tried testing the Paid Content Block but am getting the following JavaScript error. Nothing happens when I click 'Subscribe'. I'm not sure if it's relevant to the core issue or me missing some less obvious steps when testing:

Screenshot 2024-01-10 at 18 17 51

File: projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php (hunk 1 above)
Comment (n3f) [reply projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php]: Yup, this was a quick and dirty fix last night.  I agree.

File: projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php (hunk 2 above)
Comment (n3f) [reply projects/plugins/jetpack/modules/memberships/class-jetpack-memberships.php]: I expanded it out.

**Comment by n3f** [comment]
> I tried testing the Paid Content Block but am getting the following JavaScript error. Nothing happens when I click 'Subscribe'. I'm not sure if it's relevant to the core issue or me missing some less obvious steps when testing:
> 
> Screenshot 2024-01-10 at 18 17 51

That _should_ be unrelated (but it might not be). `tb_show` was originally part of the `thickbox` lightbox js library that opens the iframe. That should have all been removed but the `tb_show` might still be used as part of that code... It could be the URL isn't getting generated correctly. (what site are you using?)

**Comment by ice9js** [comment]
I was testing locally/self-hosted - I know you recommended JN and WoA but I figured since it's available it'd be good to test that too, especially ahead of the release.

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js [hunk 4]
```diff
@@ -59,14 +55,22 @@ function ButtonsEdit( { context, subscribeButton, setSubscribeButtonPlan } ) {
 	// Keep in sync the plan selected on the Premium Content block with the plan selected on the Recurring Payments
 	// inner block acting as a subscribe button.
 	useEffect( () => {
-		if ( ! planId || ! subscribeButton ) {
+		if ( ! planIds || ! subscribeButton ) {
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js]: I think this will always evaluate to true. You might want `planIds.length === 0`

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js [hunk 5]
```diff
@@ -12,13 +12,9 @@ const ALLOWED_BLOCKS = [
...
-	const planIds = context[ 'premium-content/planIds' ] || [];
-	const planId = planIds.reduce( ( acc, plan ) => {
-		if ( acc === null ) {
-			return plan;
-		}
-		return acc + '+' + plan;
-	}, null );
+	const planIds = useMemo( () => {
+		return context[ 'premium-content/planIds' ] || [];
+	}, [ context ] );
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js:18]: I think you should move this out of `useMemo` as the operation you're doing here is not expensive and I don't know if `context` is a reliable way of checking to see if planIds have changed.

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js [hunk 6]
```diff
@@ -59,14 +55,22 @@ function ButtonsEdit( { context, subscribeButton, setSubscribeButtonPlan } ) {
...
+		if (
+			subscribeButtonPlanIds.length === planIds.length &&
+			subscribeButtonPlanIds.every( i => planIds.includes( i ) )
+		) {
+			return;
 		}
-	}, [ planId, subscribeButton, setSubscribeButtonPlan ] );
+
+		setSubscribeButtonPlan( planIds );
+	}, [ planIds, subscribeButton, setSubscribeButtonPlan ] );
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js:74]: `setSubscribeButtonPlan` can be removed as it's not used inside the function.

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js [hunk 7]
```diff
@@ -120,13 +124,13 @@ export default compose( [
 	} ),
 	withDispatch( ( dispatch, props ) => ( {
 		/**
-		 * Updates the plan on the Recurring Payments block acting as a subscribe button.
+		 * Updates the plans on the Recurring Payments block acting as a subscribe button.
 		 *
-		 * @param {number} planId - Plan ID.
+		 * @param {number} planIds - Plan IDs.
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js]: This is an array now, correct?

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 8]
```diff
@@ -15,17 +15,40 @@ import { getBlockStyles } from './util';
...
-	const { align, planId, width } = attributes;
-	const planIds = useMemo( () => {
-		const _planIds = ( '' + planId ).split( '+' ).map( id => parseInt( id, 10 ) );
-		return _planIds;
-	}, [ planId ] );
+	const { align, planId, planIds, width } = attributes;
+
+	// planId is a integer, planIds is an array.
+	// if planIds is set, use it, otherwise use planId. Going forward we should only use planIds.
+	const _planIds = useMemo( () => {
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:23]: This code isn't expensive enough to be in a `useMemo`

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 9]
```diff
@@ -15,17 +15,40 @@ import { getBlockStyles } from './util';
...
+
 	const editorType = getEditorType();
 	const postLink = useSelect( select => select( editorStore )?.getCurrentPost()?.link, [] );
 
 	const updateSubscriptionPlans = useCallback(
 		newPlanIds => {
-			const newPlanId = newPlanIds !== planIds ? newPlanIds.join( '+' ) : planId;
+			// console.log( 'updateSubscriptionPlans', planIds, newPlanIds );
+
+			// verify _planIds is a non-empty array.
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx]: `newPlanIds`

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 10]
```diff
@@ -15,17 +15,40 @@ import { getBlockStyles } from './util';
...
+				return;
+			}
+			// ensure/convert all elements to integers.
+			const validatedPlanIds = newPlanIds
+				.map( id => parseInt( id, 10 ) )
+				.filter( id => ! isNaN( id ) );
+
+			// if all the elements match the existing planIds, do nothing.
+			if (
+				Array.isArray( planIds ) &&
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx]: `_planIds`?

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx [hunk 11]
```diff
@@ -15,17 +15,40 @@ import { getBlockStyles } from './util';
...
+				validatedPlanIds.length === planIds.length &&
+				validatedPlanIds.every( i => planIds.includes( i ) )
+			) {
+				return;
+			}
+
+			const newPlanId = validatedPlanIds.join( '+' );
```
Comment (pottedmeat) [inline projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:50]: Not sure what this is. `planId` is still an integer and I don't think this is necessary anyway.

**Review by pottedmeat — DISMISSED** [review]

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js (hunk 5 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js:18]: Originally this just was a simple assignment, but one of the later useCallback/useEffect (I don't remember which) complained about the variable not working with the hook.  This solved that issue

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js (hunk 6 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js:74]: Yes it is (see line 72).

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx (hunk 8 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:23]: Same response as above (do you have a better solution to the linter?)

File: projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js (hunk 5 above)
Comment (pottedmeat) [reply projects/plugins/jetpack/extensions/blocks/premium-content/buttons/edit.js:18]: Okay, that makes sense. Can you use `context[ 'premium-content/planIds' ]` instead of `context`?

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx (hunk 8 above)
Comment (pottedmeat) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:23]: That makes sense. Might want to add a comment that these are so that the resolved value can be used in other hooks.

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx (hunk 11 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx:50]: This is used to create the URL (in the function `resolvePaymentUrl()`).  I'm not sure it actually does much either but it creates a unique URL that gets saved with the block too.  I figured it was better to not mess with it too much.

File: projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx (hunk 10 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/recurring-payments/edit.jsx]: Thanks!

**Review by ice9js — APPROVED** [review]
The testing instructions tested well for me, code looks alright too, thanks!

**Comment by sdixon194** [comment]
cherry picked to release branch in 17bb1a2082ff38922e7bbd8390ed1c89afb87cad
