### PR TITLE
Changes to SEO Tools text

### LINKED ISSUE #5652: SEO Tools: offer option to upgrade
#### Steps to reproduce the issue

1. Go to Jetpack > Settings > Engagement on your site.
2. Activate the SEO Tools module.
3. I'm not exactly sure what to do now, so I'll click on the little toggle.

screen shot 2016-11-15 at 14 08 10

4. I don't know how to buy a plan, though. Shouldn't there be a link allowing me to buy a plan in there?

Our other paid module, VideoPress, takes a different approach. You have to upgrade before you can activate the module.

screen shot 2016-11-15 at 14 10 01

We should probably follow the same approach for all paid modules.

cc @vindl

### PR DESCRIPTION
**Pull request by richardmuscat**
Partly fixes #5652

### CODE REVIEW

File: _inc/client/components/module-settings/modules-per-tab-page.jsx [hunk 1]
```diff
@@ -91,15 +91,15 @@ const AllModuleSettingsComponent = React.createClass( {
 				if ( '' === module.configure_url ) {
 					return (
 						<div>
-							{ __( 'Your Jetpack plan doesn’t include SEO tools. You must upgrade to Jetpack Professional to use SEO tools.' ) }
+							{ __( 'Make sure your site is easily found on search engines with advanced SEO tools for your content and social posts.' ) }
```
Comment (jeherve) [inline _inc/client/components/module-settings/modules-per-tab-page.jsx]: I believe we moved away from the word "Advanced" in Jetpack SEO Tools.

**Comment by samhotchkiss** [comment]
CPed into branch-4.4
