### PR TITLE
Block: Opentable - fix the required plan name so upgrade nudge shows correctly

### LINKED ISSUE #15021: OpenTable Block: Upgrade nudge is missing plan needed and upgrade button
From @davemart-in 

#### Steps to reproduce the issue

1. Create a new page from a free WP.com account
2. Add the OpenTable block

#### What I expected

The Calendly upgrade prompt both mentions which plan must be upgraded to, and shows an upgrade button:

calendly

#### What happened instead

When viewing the OpenTable block on a free plan, here's what I'm seeing:

opentable

The plan you need to upgrade to (premium) is not explicitly mentioned, and for some reason the upgrade button is missing.

### PR DESCRIPTION
**Pull request by glendaviesnz**
The required plan was not set correctly so the upgrade nudge message and upgrade button was not showing correctly.

Fixes #15021
#### Changes proposed in this Pull Request:

* Changes required bundle from premium-plan to value_bundle for Opentable block

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Bug fix for existing feature

#### Testing instructions:

* Add OpenTable block on free simple site and notice that specific plan to upgrade to is not displayed in nudge, and upgrade button is missing
* Apply this patch to sandbox, and sandbox free simple site, then add OpenTable block again and check nudge specifies that upgrade to 'Premium' plan is needed and that upgrade button shows.

**Before:**
Screen Shot 2020-03-30 at 11 38 17 AM

**After:**

Screen Shot 2020-03-30 at 11 39 05 AM

#### Proposed changelog entry for your changes:
* WPcom specific bugfix so no entry needed

### CODE REVIEW

File: extensions/blocks/opentable/opentable.php [hunk 1]
```diff
@@ -65,12 +65,12 @@ function set_availability() {
...
 			array(
 				'required_feature' => 'opentable',
-				'required_plan'    => 'premium-plan',
+				'required_plan'    => 'value_bundle',
 			)
 		);
 	}
 }
-add_action( 'jetpack_register_gutenberg_extensions', __NAMESPACE__ . '\set_availability' );
+add_action( 'init', __NAMESPACE__ . '\set_availability' );
```
Comment (glendaviesnz) [inline extensions/blocks/opentable/opentable.php]: This change isn't required for the fix, but it aligns it with the Calendly block for consistency

**Review by Copons — APPROVED** [review]

**Review by davemart-in — APPROVED** [review]
Looks good. I'm not a fan of how the upgrade button wraps to a new line at such a wide screen resolution. I've kicked off a separate issue for the design though [here](https://github.com/Automattic/jetpack/issues/15190).

**Comment by davemart-in** [comment]
cc @jeherve in case we can get this in the upcoming release.

**Comment by kraftbj** [comment]
Adding it to the 8.4 milestone as a bug fix.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Cherry-picked to `branch-8.4` via 2d6cdbaa6.
Synced to wp.com via r205291-wpcom.
