### PR TITLE
VideoPress: Fix icon on privacy column

### LINKED ISSUE #27161: VideoPress: video privacy is not displayed on the video list view
On the video list view, there is a column to show the video privacy information, but it is not being showed, even after changing the privacy to any value (default, public or private):

image

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #27161

#### Changes proposed in this Pull Request:

* Removes `fill="none"` from local icons
* Fixes privacy check needed to show icon

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Go to the VideoPress dashboard with at least one video
* Change the view to List instead of Grid
* Change the privacy of a video to private
* Check that the icon now is visible

### CODE REVIEW

**Comment by lhkowalski** [comment]
I can confirm that the icons are now showing:

image

File: projects/packages/videopress/src/client/components/icons/crossed-eye-icon.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import { SVG, Path } from '@wordpress/components';
 
 const crossedEye = (
-	<SVG width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
```
Comment (lhkowalski) [inline projects/packages/videopress/src/client/components/icons/crossed-eye-icon.js:4]: I am curious about this change, is it something that you detected or these are generated files?

File: projects/packages/videopress/src/client/admin/components/video-list/index.tsx [hunk 2]
```diff
@@ -63,6 +64,9 @@ const VideoList = ( {
 				) }
 			</div>
 			{ videos.map( ( video, index ) => {
+				const isPrivate =
```
Comment (lhkowalski) [inline projects/packages/videopress/src/client/admin/components/video-list/index.tsx:67]: We can start to think about having a central place where we flag the video as private based on whatever properties we may consider, because we handling this privacy things on a lot of places. But not today :)

**Review by lhkowalski — APPROVED** [review]
Code looks good! Let's ship it :)

File: projects/packages/videopress/src/client/components/icons/crossed-eye-icon.js (hunk 1 above)
Comment (dhasilva) [reply projects/packages/videopress/src/client/components/icons/crossed-eye-icon.js:4]: I think those were copied from Figma, or maybe sent by the designers and adapted.
I changed the privacy settings to `true` manually and even then it did not show, so I had to inspect the page and change the icon. One of the icons, `play-icon` has a `fill="white"` in it, which made me check the other icons and only then I noticed the `fill="none"`. Removing it solved the problem.

If you take a look at one of the icons on `@wordpress/icons`, like `chevronDown`, you'll see there is no hardcoded `fill` there.

File: projects/packages/videopress/src/client/admin/components/video-list/index.tsx (hunk 2 above)
Comment (dhasilva) [reply projects/packages/videopress/src/client/admin/components/video-list/index.tsx:67]: Yes!
The `video.isPrivate`, as it is now, is misleading.
