### PR TITLE
Vimeo Embeds: support more URL formats, such as videos in playlists

### LINKED ISSUE #10529: Vimeo: embed reversal fails with some vimeo URL formats
#### Steps to reproduce the issue

1. Make sure Jetpack's Shortcodes module is enabled on your site.
2. Go to Posts > Add New and create a new post including the 3 following URLs, on separate lines:
```html
https://vimeo.com/289091934/cd1f466bcc
https://vimeo.com/album/2838732/video/6342264
https://vimeo.com/6342264
```

All 3 URL formats do work and return an embed in the post editor, since they are valid URL formats and Core's oEmbed method handles them. However, on the frontend of your site only the third video will work: the 2 first ones will only return the following error:

`<!-- vimeo error: not a vimeo video -->`

We would need to update our embed reversal method to support those URLs as well.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10529

#### Changes proposed in this Pull Request:

This PR makes some changes to both Vimeo shortcode tests (consolidate the existing tests, fix linting errors, avoid duplications and rely on data providers to simplify things), as well as update the oEmbed provider regex to pull out IDs from Vimeo URLs. We can then use those IDs in the existing shortcode.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Go to Jetpack > Settings, and enable the Shortcodes feature
* Go to Posts > Add New, add some test content.
* Between 2 paragraphs, add the following URLs on their own line (not as links, not formatted, just the URLs on their own):
    * `https://vimeo.com/289091934/cd1f466bcc`
    * `https://vimeo.com/album/2838732/video/6342264`
    * `https://vimeo.com/6342264`
    * `http://player.vimeo.com/video/18427511`
* Ensure those videos are then rendered on the frontend when publishing the post.
* Check that CI is happy with the new tests.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php [hunk 1]
```diff
@@ -258,19 +258,31 @@ class_exists( 'Jetpack_AMP_Support' )
...
+ * https://vimeo.com/6342264
+ * http://player.vimeo.com/video/18427511
  *
  * @since 3.9
  *
  * @uses wpcom_vimeo_embed_url
  */
 function wpcom_vimeo_embed_url_init() {
-	wp_embed_register_handler( 'wpcom_vimeo_embed_url', '#https?://(.+\.)?vimeo\.com/#i', 'wpcom_vimeo_embed_url' );
+	wp_embed_register_handler( 'wpcom_vimeo_embed_url', '#https?:\/\/(?:.+\.)?vimeo\.com\/(?:(?:album\/)(?<album_id>\d+)\/)?(?:video\/)?(?<video_id>\d+)(?:\/.*)?\/?$#i', 'wpcom_vimeo_embed_url' );
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php:285]: A few issues here:

* No need for [leaning toothpicks](https://en.wikipedia.org/wiki/Leaning_toothpick_syndrome), that's only necessary when `/` is used as a delimiter. This regex uses `#` as the delimiter specifically to avoid that.
* There's no need to group `(?:album/)`, you're not applying a quantifier to the group or alternation inside it.
* The `/?` bit at the end is redundant since you have `(?:/.*)?` just before it.
* The `(?:.+\.)` to match an arbitrary domain is a little risky, it could match a URL like `http://evil.com/domain.vimeo.com/123456` that it's not supposed to. Safer to exclude `/` from the match.

```suggestion
	wp_embed_register_handler( 'wpcom_vimeo_embed_url', '#https?://(?:[^/]+\.)?vimeo\.com/(?:album/(?<album_id>\d+)/)?(?:video/)?(?<video_id>\d+)(?:/.*)?$#i', 'wpcom_vimeo_embed_url' );
```

**Comment by jeherve** [comment]
r236764-wpcom

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/shortcodes/vimeo.php:285]: Here it is: #22116
