### PR TITLE
Asset CDN: do not try to serve assets from non-public versions.

### LINKED ISSUE #10633: CDN: Requests fail for unreleased versions
#### Steps to reproduce the issue

1. Create a new development site from `master` (for example with Jetpack Docker)
2. Enable the Asset CDN module
3. Try to use Jetpack Admin or other things that depend on Jetpack CDN files – `/wp-admin/admin.php?page=jetpack#/settings`
4. 💥 Broken pages. You'll see a lot of 404 requests

The CDN seems to naively CDNify requests for a version of Jetpack that's unavailable.

```
admin.php?page=jetpack:104 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/build/style.min.css net::ERR_ABORTED 404
admin.php?page=jetpack:70 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/build/admin.dops-style.css net::ERR_ABORTED 404
admin.php?page=jetpack:296 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/widgets/social-icons/social-icons-admin.js net::ERR_ABORTED 404
admin.php?page=jetpack:290 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/masterbar/tracks-events.js net::ERR_ABORTED 404
admin.php?page=jetpack:67 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-admin-jitm.css net::ERR_ABORTED 404
admin.php?page=jetpack:66 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-icons.min.css net::ERR_ABORTED 404
admin.php?page=jetpack:63 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/masterbar/overrides.css net::ERR_ABORTED 404
admin.php?page=jetpack:289 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/accessible-focus.js net::ERR_ABORTED 404
admin.php?page=jetpack:68 GET https://c0.wp.com/p/jetpack/6.8-alpha/_inc/genericons/genericons/genericons.css net::ERR_ABORTED 404
admin.php?page=jetpack:69 GET https://c0.wp.com/p/jetpack/6.8-alpha/css/jetpack-admin.css net::ERR_ABORTED 404
admin.php?page=jetpack:65 GET https://c0.wp.com/p/jetpack/6.8-alpha/modules/widgets/social-icons/social-icons-admin.css 
```

#### What I expected

Things work.

#### What happened instead

Things broke.

**Screenshots**

screen shot 2018-11-15 at 12 33 06
screen shot 2018-11-15 at 12 32 23

### PR DESCRIPTION
**Pull request by jeherve**
#### Changes proposed in this Pull Request:

- When checking for the files in Jetpack, only look for files to cdnize
if Jetpack's version is public (not a development version).

#### Testing instructions:

1. On a local installation of Jetpack (not using the Beta plugin), run this branch. Your Jetpack version will be 6.8-alpha.
2. Go to Jetpack > Settings and enable the Asset CDN feature.
3. Check that once you've done so, after refreshing, no Jetpack files are served from the CDN.

#### Proposed changelog entry for your changes:
* Asset CDN: do not try to serve assets from non-public versions.

Fixes #10633

### CODE REVIEW

File: modules/photon-cdn.php [hunk 1]
```diff
@@ -151,7 +151,11 @@ public static function cdnize_plugin_assets( $plugin_slug, $current_version ) {
 	 * @return array
 	 */
 	public static function get_plugin_assets( $plugin, $version ) {
-		if ( 'jetpack' === $plugin && JETPACK__VERSION === $version ) {
+		if (
+			'jetpack' === $plugin
+			&& JETPACK__VERSION === $version
+			&& self::is_public_version( $version )
```
Comment (mdawaffe) [inline modules/photon-cdn.php]: If it's not a public version of Jetpack, we'll end up failing this condition and proceeding to the (cached) plugins repo check below.

Since we know no non-public version of Jetpack will have assets in the plugins repo, we can bail early.

How about removing this condition from the `if` statement, and adding an:
```
if ( ! public ) {
  return array();
}
```

or whatever inside the current `if` statement.

**Review by mdawaffe — CHANGES_REQUESTED** [review]
Can we bail early for Jetpack if it's not a public version (see comment inline)?

**Review by mdawaffe — DISMISSED** [review]
Boom :shipit:

**Comment by dereksmart** [comment]
Pushed an update to the docblock to reflect possible falsey return.

**Review by dereksmart — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-6.8` in b49ff5c330446ec8d516fb8df9ad6d129f66968d
