### PR TITLE
[contact-form $attributes] now ok in do_shortcode

### LINKED ISSUE #3187: Contact Form: Dynamic attributes lost when submitting form, when using do_shortcode
I know there have been several other threads discussing this, but I can verify that trying to dynamically change the 'to' address of a Jetpack contact-form shortcode in a do_shortcode situation fails. The dynamic 'to' address isn't recognized. To repeat, try something like the following in your PHP:

`echo do_shortcode( "[contact-form to='".$dynamic_user_email_addy."' subject='Custom Subject'][contact-field label='Your Name' type='name' required='1'/][/contact-form]" );`

The custom 'to' attribute gets lost in the function _process_form_submission_. The shortcode is re-created, but the attributes don't come along with it.

I fixed the issue by 
    a) Saving the attributes via `update_post_meta()` in the `store_shortcode` function, like the shortcode content already is.
    b) Retrieving those attributes in the `process_form_submission` function using `get_post_meta()`, and then re-inserting the attributes into the shortcode just before `do_shortcode()` is run again.

I've tested my solution repeatedly and can verify it works. However, the whole process seems tortured. The do_shortcode function is being called twice. So while my 10 lines of code definitely fixes the surface problem, there might be a more elegant solution by simplifying the whole process. My fix feels like a band-aid, albeit a pretty good one.

I'm attaching my edited version. I made a pull request months ago, but nothing ever happened with it. However, I can make another pull request if it will help.

[grunion-contact-form.php.zip](https://github.com/Automattic/jetpack/files/66960/grunion-contact-form.php.zip)

### PR DESCRIPTION
**Pull request by jeherve**
Previously, when using the [contact-form] shortcode in do_shortcode situations like a page template, the attributes like 'to' and 'subject' were being dropped. $attributes and all its variations aren't available by the time we get to processing the submission, so I had to rewrite it as a string earlier in the process, in store_shortcode(), when we still have access to $attributes. If someone knows how to get access to the shortcode attributes in process_form_submission() then we could save a few lines of code and keep attributes as an array.

Fixes #3187

### CODE REVIEW

File: modules/contact-form/grunion-contact-form.php [hunk 1]
```diff
@@ -198,10 +198,12 @@ function process_form_submission() {
 
 			// Get shortcode from post meta
 			$shortcode = get_post_meta( $_POST['contact-form-id'], '_g_feedback_shortcode', true );
+			// Get the attributes from post meta. $attributes not available here
+			$atts = get_post_meta( $_POST['contact-form-id'], '_g_feedback_shortcode_atts', true );
 
 			// Format it
 			if ( $shortcode != '' ) {
-				$shortcode = '[contact-form]' . $shortcode . '[/contact-form]';
+				$shortcode = '[contact-form'.$atts.']' . $shortcode . '[/contact-form]';
```
Comment (eliorivero) [inline modules/contact-form/grunion-contact-form.php]: Missing spaces:
lines 206, 978, 980 between quotes and concatenation operator.
line 976 inside foreach brackets
Also, extra indentation in 977

**Comment by eliorivero** [comment]
Works fine! :100: Made a change to save `$attributes` as array instead of string until it's needed, perform checkings on feedback meta data and filter empty values before concatenation.

**Comment by zinigor** [comment]
Tested, works good!
