### PR TITLE
Fix sharing buttons in blog posts block

### LINKED ISSUE #46634: Blog Posts block: Share buttons showing with broken icons when excerpts are enabled
#### Steps to reproduce

1. Enabled sharing buttons on posts
2. Add a Blog Posts block to a page 
3. Set the settings to show three posts and show excerpts

#### What I expected

- Posts would be shown with excerpts and no Sharing buttons

#### What happened instead

- Posts are shown with excerpts and Sharing buttons with broken icons

- Disabling Show Excerpt seems to make the Sharing buttons go away

(Sidenote that there is also no Continue Reading link showing)

#### Browser / OS version

Firefox 81 on macOS (Catalina)

#### Screenshot / Video

Markup 2020-10-21 at 07 34 34

Markup 2020-10-21 at 07 31 47

#### Context / Source

#dogfooding, #manual-testing

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/wp-calypso/issues/46634 and https://github.com/Automattic/wp-calypso/issues/52347

##### Reasoning 
The docs say this about [sharing buttons](https://wordpress.com/support/sharing/):

> Posts – all individual blog posts will display the likes and sharing buttons
> Pages – all static pages (like an about or contact us page) will display the likes and sharing buttons

I understand that we should show sharing buttons for a single post and a single page, but not for items that are displayed on the list like in the Blog Posts block.

Thus I would remove sharing buttons for listed items altogether.

##### Technical details
There is a check for the `get_the_excerpt()` filter, which doesn’t show sharing buttons if the `sharing_display()` function is called via this filter. However, the function is added as a filter for `the_content()` and `the_excerpt()`. This condition wouldn’t be caught at all.

I modified this condition to check for `the_excerpt()` instead of `get_the_excerpt()`. It fixes the issue, however, I’m not sure about the following:

**why we add `sharing_display()` for `the_excerpt()` in the `init()` method? Is there any use case in which we want sharing buttons content displayed for the excerpt? Or could we delete it?**

This blame shows that we added this code 10-12 years ago:
https://github.com/Automattic/jetpack/blame/a7208f678a4239211bdc4f34d75d196b780c7a25/modules/sharedaddy/sharing-service.php

If the fix is valid and no code should add sharing buttons for `the_excerpt()`, we could modify the fix and remove all other calls related to `the_excerpt()` in the class.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

##### Main test case 
1. Start a Jetpack environment
2. Go to WP Admin
3. Install a WordPress.com Editing Toolkit plugin
4. Enable Sharing buttons in Jetpack -> Settings -> Sharing (works in Jetpack's offline mode)
5. Add a new page with a **Blog Posts** block (and not Posts Lists)
6. Confirm sharing buttons are not displayed under each post in the list of posts on the created page

##### Regression test

Let's test if we can still enable/disable sharing buttons for individual post and page:

1. Go to Jetpack -> Settings -> Sharing 
2. Click on “Configure your sharing buttons”
3. Disable Show buttons on Pages, Save changes

Then ensure that the page doesn't display sharing buttons. Check the same for posts.

### CODE REVIEW

**Review by danielbachhuber — COMMENTED** [review]
Personally, I'm a little bit terrified about changing 10 year old code that:
1. Doesn't have any sort of test coverage around the nature of its behavior.
2. Is _imprecise_ code in the first place (i.e. a hacky approach that solved whatever the immediate problem was, not a precise use of an API).

To me, this sort of change is one that can cause the "sky to fall on your head" (i.e. lots of random things breaking unexpectedly).

As an alternative to consider, here's a more precise fix specifically for the Blog Posts block: https://github.com/Automattic/newspack-blocks/pull/1190

What do you think?

**Comment by wojtekn** [comment]
@danielbachhuber I wanted to clean some code while working on a fix here. However, I agree that it may be a bit risky, especially since I couldn't find a use case that relies on sharing buttons appended to `the_excerpt()`.

To give more background, I thought that the following chain of events might happened:

1. We initially added that sharing buttons plugin code for `the_content()` and `the_excerpt()` hooks
2. At some point, we wanted to remove it for `the_excerpt()`, but we created the condition that checks for `get_the_excerpt()` filter.

At that time, the plugin was not set for `get_the_excerpt()`. Was it a mistake? If yes, the current PR fixes that mistake. However, the fix makes any code related to `the_excerpt()` unnecessary.

I've checked your revision and tested it, and I think it doesn't fix the issue we are fixing here yet - I understand that we should:

* show sharing buttons for a single post when it is enabled for Posts
* show sharing buttons for a single page when it is enabled for Pages
* do not show sharing buttons for items that are displayed on the list like in the Blog Posts block.

I commented on the other revision as well.

**Comment by danielbachhuber** [comment]
@wojtekn This might be the point of confusion:

> do not show sharing buttons for items that are displayed on the list like in the Blog Posts block.

I _think_, but I'm not certain, the expected behavior is to have the sharing buttons displayed in the Blog Posts block in certain contexts. This emulates the existing behavior of sharing buttons displayed within the loop when enabled for the context.

For example, here's the homepage of Twenty Nineteen with share buttons enabled for the Front Page:

image

With share buttons disabled for the Front Page, the buttons aren't displayed in the loop at all:

image

**Comment by wojtekn** [comment]
@danielbachhuber I was also wondering which is right, and based on the docs I would think that "Posts" setting should enable sharing buttons for individual posts only: 

> Front Page, Archive Pages, and Search Results – this includes your site’s home page, pages automatically created to display an archive of posts, and your search results page.
> Posts – all **individual** blog posts will display the likes and sharing buttons
> Pages – all static pages (like an about or contact us page) will display the likes and sharing buttons

I think the same understanding was used in related ticket acceptance criteria, and in some of the comments.

As regards the list, I've checked how it works for the front page and post list page in the newer theme (Twenty Twenty Two) and I couldn't make sharing buttons displayed for the front page or listing at all.

If we decide that we should show those sharing buttons for individual items and that we just want to fix the icons/styling, we could also consider another approach that doesn't require adding a dependency on sharedaddy logic to newspack module. 

We could modify the `sharing_display()` function to overwrite any result of `sharing_maybe_enqueue_scripts()` if we are processing sharing buttons. It would be about adding one line to overwrite the function result:

```
if ( count( $enabled['all'] ) > 0 ) {
    add_filter( 'sharing_enqueue_scripts', '__return_true' );
```

What do you think about this approach?

**Comment by wojtekn** [comment]
Checking more on the desired approach p9dueE-5ni-p2

**Comment by wojtekn** [comment]
> If we decide that we should show those sharing buttons for individual items and that we just want to fix the icons/styling, we could also consider another approach that doesn't require adding a dependency on sharedaddy logic to newspack module.
> 
> We could modify the `sharing_display()` function to overwrite any result of `sharing_maybe_enqueue_scripts()` if we are processing sharing buttons. It would be about adding one line to overwrite the function result:
> 
> ```
> if ( count( $enabled['all'] ) > 0 ) {
>     add_filter( 'sharing_enqueue_scripts', '__return_true' );
> ```

I've checked this approach again and I couldn't make it work anymore - it looks like it may work only if scripts are enqueued in the footer.

I'm interested in any more feedback on the original approach: to remove the sharing icons from child posts completely by fixing code that looks like a bug in the original implementation. @Automattic/build any thoughts?

**Review by jeherve — DISMISSED** [review]
This seems to introduce an issue in my tests.

1. Start with a simple theme that uses `the_excerpt();` for its main loop used to display the home page and archive pages.
2. Activate sharing and enable sharing buttons on the front page.
3. Publish a post.
4. On the frontend, when using this branch, you'll see this:

image

**Comment by wojtekn** [comment]
@jeherve, thanks for sharing that use case. I've reproduced it and fixed the code to ensure it works well for archives, search, and home pages that use excerpts.

It worked in all cases I tried, but now I'm worried about cases my condition potentially wouldn't catch. I'm unsure if we have other blocks that would display posts in which we want to display sharing buttons. I've checked the Query Loop, Latest Posts, and Posts Lists, and their behavior is not changed - they didn't show the sharing buttons before the change.

File: projects/plugins/jetpack/modules/sharedaddy/sharing-service.php [hunk 1]
```diff
@@ -947,6 +947,12 @@ function sharing_display( $text = '', $echo = false ) {
 		return $text;
 	}
 
+	// Ensure we don't display sharing buttons on excerpts unless we are on search, archive or home page.
+	if ( ! is_search() && ! is_home() && ! is_archive() &&
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: Should we have `is_front_page()` in there as well?

Comment (wojtekn) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: @jeherve, thanks for pointing that out. I've checked it, and I think we shouldn't add a check for `is_front_page()`. When we set a home page to display the static page, it returns' true'. In such a case, it wouldn't remove sharing buttons from the Blog Posts block displayed on home.

**Review by samiff — COMMENTED** [review]
This tested well for me. Though I did have one question, this PR seems focused around the Sharing buttons, but should the Like button receive the same treatment?

With the Twenty Twenty theme for example, here is a page with a custom excerpt and a Blog Posts block added:

Screen Shot 2022-07-20 at 12 35 09 PM

Screen Shot 2022-07-20 at 12 35 27 PM

**Comment by wojtekn** [comment]
@samiff, thanks for giving it a test. I've tested the "Like" feature, and I agree it makes sense to unify its behavior with sharing buttons. I've added a similar condition in the file responsible for likes.

However, I tested a few more test cases and found one more scenario that I haven't caught - buttons were still displayed in the Blog Posts block in themes that display post content on the post list page (Twenty Thirteen!).

I couldn't find any condition that would let us catch this case. I've checked `$wp_current_filter` more, and I found out that we can check for an action chain - to skip adding buttons if the function is called by `the_excerpt` and `the_content` together. It seems to be working in all cases now. What do you think?

**Review by samiff — DISMISSED** [review]
> to skip adding buttons if the function is called by `the_excerpt` and `the_content` together. It seems to be working in all cases now. What do you think?

That looks good to me! Gave it another test with a handful of themes and didn't run into any issues.

**Comment by coder-karen** [comment]
I did some additional testing after beginning to look into the WordPress.com diff (in that case looks like the incoming change needs adding to the equivalent likes file), and noticed that likes and share buttons will still show on a password-protected page. Since these don't appear on private or public pages given the testing scenario shared (using the Blog Posts block), shouldn't these also be hidden on password-protected pages?

**Review by coder-karen — COMMENTED** [review]
I did some additional testing after beginning to look into the WordPress.com diff (in that case looks like the incoming change needs adding to the equivalent likes file), and noticed that likes and share buttons will still show on a password-protected page. Since these don't appear on private or public pages given the testing scenario shared (using the Blog Posts block), shouldn't these also be hidden on password-protected pages?

**Comment by wojtekn** [comment]
> I did some additional testing after beginning to look into the WordPress.com diff (in that case looks like the incoming change needs adding to the equivalent likes file), 

@coder-karen I noticed that `likes.php` was not synchronized to WPCOM diff correctly due to conflicts. I fixed that, and the related diff builds fine now.

> noticed that likes and share buttons will still show on a password-protected page. 

I would like to avoid expanding this issue's scope, and this seems like an idea for another issue. What do you think?

**Comment by coder-karen** [comment]
> I noticed that likes.php was not synchronized to WPCOM diff correctly due to conflicts. I fixed that, and the related diff builds fine now.

👍 

> I would like to avoid expanding this issue's scope, and this seems like an idea for another issue. What do you think?

Yes I agree, I was on my way back to this PR to mention that I realized the behavior on password protected pages is like this anyway (not to say that's ideal, but changing it is beyond the scope of this PR anyway).

**Review by coder-karen — APPROVED** [review]

**Comment by coder-karen** [comment]
r249602-wpcom
