### PR TITLE
External Media: Disable for existing galleries

### LINKED ISSUE #16126: External Media: Can't add images to gallery
While the Gallery block [passes image objects as the current value](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-library/src/gallery/edit.js#L369), the MediaPlaceholder component [only passes on their IDs](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-editor/src/components/media-placeholder/index.js#L356).

While we need to pass full objects back to the gallery to properly set those images, [currently we're concatenating an array of sting IDs with the image objects](https://github.com/Automattic/jetpack/blob/14ab20d41e0c04b78a31a4b3db3928be4267edc3/extensions/shared/external-media/sources/with-media.js#L163) we get back from the API, resulting in empty images:

**Screenshots**
image

#### Steps to reproduce the issue

Consider testing with #16124 to avoid an annoying click propagation bug.

1. In the editor, create a gallery block and add at least one image.
2. In the dropzone at the bottom of the block, click "Select Images"
3. Dismiss the upload dialog whenever it pops up (it's annoying, I know) or test with #16124
4. Select at least one image and copy & insert it.
5. Note how the existing image(s) disappear and only the new images get rendered.

### LINKED ISSUE #16165: External Media: Unable to add pictures to Galleries with external images
While the Gallery block [passes image objects as the current value](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-library/src/gallery/edit.js#L369), the MediaPlaceholder component [only passes on their IDs](https://github.com/WordPress/gutenberg/blob/c711a16dbfd3858fecb1bbb306ad0962bb26d19a/packages/block-editor/src/components/media-placeholder/index.js#L356).

In order for us to be able to add images, we have to query full image objects and return them, see #16142. That doesn't work however, when the gallery contains images that are not in the media library. In that case, the media queries return `undefined` and let the `copyMedia` function silently fail.

#### Steps to reproduce the issue

1. Create a gallery with an image from the media library.
1. Save the draft/post/page.
1. Delete the image from the media library
1. Reload the post with the gallery you just added.
1. Try to add a Pexels of Google Photos image to that gallery.
1. Note how it fails with the following warning in the console: `Warning: Can't perform a React state update on an unmounted component.`

#### Possible next steps
We could:
* Disable External Media for existing Galleries. 
* Disable External Media only for galleries that contain images that are not in the media library (although for users that could cause unexpected disparities between gallery blocks).
* Update the Gallery only with images that are part of the media library (that's what the media modal currently does*)

*) In the media modal, users get a preview of the updated gallery and can cancel that flow. With External Media we can't do that. Users' only recourse to revert that would be to undo the change.

### PR DESCRIPTION
**Pull request by obenland**
Disables External Media for existing galleries. Users won't be able to add more images after they selected an initial set of images.

Fixes #16126.
Fixes #16165.
Reverts #16124.

#### Changes proposed in this Pull Request:

* Adds a check whether we're adding to a gallery and fails if so
* Removes now-unneeded click propagation cap.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* In the Editor, add a new Gallery block.
* Add an image to the Gallery, from either an external library or the media library
* After that, try adding more images to the gallery. Note how external libraries are not an option any longer
* All images should display correctly, no errors in the console.
* Make sure remaining media blocks still work as expected. (image, media/text, cover blocks, and featured image all still accept external media.

#### Proposed changelog entry for your changes:

* None needed.

### CODE REVIEW

File: extensions/shared/external-media/index.js [hunk 1]
```diff
@@ -28,10 +28,11 @@ if ( isCurrentUserConnected() ) {
 		'editor.MediaUpload',
 		'external-media/replace-media-upload',
 		OriginalComponent => props => {
+			const { addToGallery = false, allowedTypes } = props;
 			let { render } = props;
 
 			// Only replace button for components that expect images.
```
Comment (retrofox) [inline extensions/shared/external-media/index.js:34]: Could you update this doc?

Comment (retrofox) [inline extensions/shared/external-media/index.js:34]: My suggestion:

```suggestion
			// Replace button for components which the allowed
			// files types are only images,
			// and also whether it should not add to the gallery.
```

**Review by retrofox — APPROVED** [review]
Tested according to PR description and it works as expected. 👍 
Left a comment an a minor suggestion.
