### PR TITLE
Masterbar: Hide for WordPress mobile apps

### LINKED ISSUE #31157: Allow hiding of Masterbar within the mobile apps
#### Steps to reproduce
1. Use the mobile app and navigate to "My Sites"
2. Select a site and scroll down to "View My Site"
3. It should show you your site

#### What I expected
My website without the masterbar at the top

#### What happened instead
The masterbar is shown

#### Browser / OS version
WordPress iOS and Android app

#### Screenshot / Video
img_7487

#### Context / Source

We don't want the user navigating within the website while browsing through the app.

#dogfooding

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/31157

#### Changes proposed in this Pull Request:

Prevents the Masterbar from showing up on mobile apps. The aim of this change is to prevent users from navigating to pages they can access through the app.

This implementation relies on the fact that we can identify requests coming from the WP mobile apps by checking that the user agent contains `wp-iphone` ([iOS](https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/Utility/WPUserAgent.m#L33-L43)) or `wp-android` ([Android](https://github.com/wordpress-mobile/WordPress-iOS/blob/4ac54edd8c4db2978a0122f97e137c755e627d4a/WordPress/Classes/Utility/WPUserAgent.m#L33-L43)).

#### Testing instructions:

* Spin up a new JN site using this branch: https://jurassic.ninja/create/?jetpack-beta&branch=update/masterbar-hide-mobile-app&shortlived
* Connect the site to WordPress.com
* Go to Jetpack → Settings → Writing and activate the "WordPress.com toolbar" module.
* Note how the Masterbar shows up.
Screen Shot 2019-03-29 at 12 56 03

* Use a fake user agent that contains either `wp-iphone` or `wp-android`:
  * iOS example: `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91 wp-iphone/12.1`.
  * Android example: `Mozilla/5.0 (Linux; Android 6.0; Android SDK built for x86_64 Build/MASTER; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36 wp-android/4.7`.
  * On Chrome you can do this using the Network conditions on the browser devtools:
Screen Shot 2019-03-28 at 13 01 49
Screen Shot 2019-03-28 at 13 02 45

* Reload the page.
* Make sure the Masterbar doesn't show up now.

#### Proposed changelog entry for your changes:

* Masterbar: Hide for WordPress mobile apps

### CODE REVIEW

**Comment by obenland** [comment]
In my testing the masterbar indeed didn't show up, it did show the regular admin bar however. Is that expected?

File: modules/masterbar/masterbar.php [hunk 1]
```diff
@@ -31,6 +31,11 @@ function __construct() {
 			return;
 		}
 
+		// Don't show the masterbar on WordPress mobile apps.
+		if ( preg_match( '/wp-(android|iphone)/', $_SERVER['HTTP_USER_AGENT'] ) ) {
```
Comment (retrofox) [inline modules/masterbar/masterbar.php]: does it worth making this checking stronger? I did a quick research and maybe [it's useful](https://stackoverflow.com/questions/5335237/how-to-check-if-the-request-came-from-mobile-or-computer-in-php).

Comment (retrofox) [reply modules/masterbar/masterbar.php]: Also [wp_is_mobile()](https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-includes/vars.php#L136) is even better :-D

Comment (obenland) [reply modules/masterbar/masterbar.php]: We're checking specifically for webviews from the WordPress iOS or Android apps, not any mobile browser

**Comment by vindl** [comment]
> In my testing the masterbar indeed didn't show up, it did show the regular admin bar however. Is that expected?

IIRC masterbar is just restyling of the default admin bar with some added JS functionality, so removing it will resurface the default one. We can probably resolve this by hooking into `show_admin_bar` and removing it.

File: modules/masterbar/masterbar.php (hunk 1 above)
Comment (retrofox) [reply modules/masterbar/masterbar.php]: > The aim of this change is to prevent users from navigating to pages they can access through the app.

So it's just needed for iOS and Android? does it not happen for other mobile OS?

Comment (obenland) [reply modules/masterbar/masterbar.php]: It's fine if they're shown in mobile browsers. This is only meant to be hidden when accessed from within the WordPress iOS or Android apps.

Comment (jeherve) [reply modules/masterbar/masterbar.php]: fwiw we do have helper functions in Jetpack that can be used if we wanted to improve that check:
https://github.com/Automattic/jetpack/blob/f098dbe15b348e8d41a1ef97ea65b4e8d7224900/class.jetpack-user-agent.php

While that may not be needed here, I would recommend checking for `! empty( $_SERVER['HTTP_USER_AGENT'] )` before to actually use it.

**Review by jeherve — CHANGES_REQUESTED** [review]
Just a quick note to avoid any potential errors.

File: modules/masterbar/masterbar.php (hunk 1 above)
Comment (obenland) [reply modules/masterbar/masterbar.php]: `Jetpack_User_Agent_Info:: is_mobile_app()` seems to be the appropriate one

Comment (mmtr) [reply modules/masterbar/masterbar.php]: Didn't know about `Jetpack_User_Agent_Info::is_mobile_app()`. Thanks for the suggestion! Refactored the change to use it in fd1c2cf.

**Comment by mmtr** [comment]
> > In my testing the masterbar indeed didn't show up, it did show the regular admin bar however. Is that expected?
> 
> IIRC masterbar is just restyling of the default admin bar with some added JS functionality, so removing it will resurface the default one. We can probably resolve this by hooking into `show_admin_bar` and removing it.

Added the filter in fd1c2cf, thanks! Note that the admin bar will be always displayed on `wp-admin`, since we don't evaluate the filter there ([#](https://github.com/WordPress/WordPress/blob/0942dfc6d41d89e779b361b3be10f7776a570801/wp-includes/admin-bar.php#L1180)).

**Review by jeherve — APPROVED** [review]
This works well in my tests. 👍
