### PR TITLE
MU WPCOM: fix admin menu upsell layout shift

### LINKED ISSUE #87509: Delayed layout shift in wp-admin when upsell banner is injected
### Quick summary

👋🏻 There have been a few times recently when I've needed to repetitively shift between the front-end and admin views while testing some workflows.

On the front-end of the site, I'll hover over the site name, click dashboard, and then immediately move my mouse to where I see the "Posts" menu item and click.

But! That click happens milliseconds after a "Free domain available" upsell banner is injected into the menu. The entire navigation shifts down by 56px and I end up in the WordPress.com stats viewer instead of the list of posts.

The site is in development, so I can't show a video of the full front/back end, but here's a clip of the relevant section:

CleanShot 2024-02-15 at 10 02 44 2

Every time I refresh the page, it starts without the upsell banner and then shifts to include it.

### Steps to reproduce

1. Start on https://example.org
2. Navigate to https://example.org/wp-admin/
3. Try to click on Posts

### What you expected to happen

Ideally, the upsell banner is placed in a way that does not cause layout shift.

Or maybe: I have a way to enable developer mode where I'm not shown upsells while working on others' sites.

### What actually happened

The navigation layout shifted.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

I'm using Firefox 122.0.1 on macOS 12.7.2

### PR DESCRIPTION
**Pull request by ellatrix**
Fixes https://github.com/Automattic/wp-calypso/issues/87509 for wp-admin

https://github.com/user-attachments/assets/d9edbc1f-fa4f-481d-bd83-2e6d3e8302d5

## Proposed changes:

* Let's avoid JS and render it in good old PHP.
* Gets rid of a network request.
* Here's the trick: I'm using the `adminmenu` hook which allows us to insert random HTML _after_ the admin menu. With the help of a tiny little inline script that instantly executes we can move it to the top before the browser can even render it. `(function(el){el.parentNode.prepend(el)})(document.getElementById( "toplevel_page_site-notices" ))`

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Click admin menu links. The upsell notice shouldn't insert itself with a delay.

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-sidebar-notice/wpcom-sidebar-notice.js [hunk 1]
```diff
@@ -15,50 +15,15 @@ const wpcomSidebarNoticeRecordEvent = ( event, wpcomSidebarNoticeData ) => {
...
-						</div>
-					</div>
-				</a>
-			</li>
-		`
-	);
-
 	// Record impression event in Tracks.
-	wpcomSidebarNoticeRecordEvent( wpcomSidebarNoticeData.tracks?.display );
+	wpcomSidebarNoticeRecordEvent( wpcomSidebarNoticeData.tracks?.display, wpcomSidebarNoticeData );
```
Comment (ellatrix) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-sidebar-notice/wpcom-sidebar-notice.js:25]: Note that the second arg was missing here, causing an error in the function, and causing everything after this line to not be executed.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-sidebar-notice/wpcom-sidebar-notice.js [hunk 2]
```diff
@@ -74,32 +39,15 @@ const wpcomShowSidebarNotice = wpcomSidebarNoticeData => {
...
 		} else {
 			// Record click event in Tracks.
-			wpcomSidebarNoticeRecordEvent( wpcomSidebarNoticeData.tracks?.click );
+			wpcomSidebarNoticeRecordEvent( wpcomSidebarNoticeData.tracks?.click, wpcomSidebarNoticeData );
 		}
 	} );
 };
 
-const wpcomFetchSidebarNotice = async () => {
-	try {
```
Comment (ellatrix) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-sidebar-notice/wpcom-sidebar-notice.js:86]: This is the reason why no JS errors are currently visible in trunk.

**Comment by fditrapani** [comment]
Thank you for working on this. This looks great from the video! I unfortunately can't test it because I'm not set up.

**Review by arthur791004 — APPROVED** [review]
Tested and it works well! The layout won't shift anymore 👍
