### PR TITLE
Anchor.FM: Pass the cover art and feed URL to the episode template

### LINKED ISSUE #18477: Anchor.FM: Podcast information is not always available in the episode template
Sometimes the feed that is associated with a podcast does not include the `link` tag on the episodes, which we are using to set the feed URL for the podcast block, when populating the episode template. Also, the value of the link tag is usually the URL for the episode and not the podcast feed. With the improvements we've made, this should usually work, but it would be good to explicitly set it to the feed URL.

The feed URL can be obtained from the `self` link, if available, or can be set to the feed URL that we're using to obtain the episode and podcast information.

The same is true for the cover image, that we're taking from the episode information, but may not be present. In these cases, we should fall back to the main cover image for the podcast.

#### Steps to reproduce the issue

Trigger the episode template flow for anchor by going to `/wp-admin/post-new.php?anchor_episode=89113006-542a-11eb-b4f3-c3757114ae55&anchor_podcast=5243218` on a development site with beta extensions enabled.

This is an episode of the Dissect podcast and the feed doesn't set the `link` or `image` tags for the episodes, and so demonstrates the problem.

You should see that the post is produced with the image block and podcast block both not showing the appropriate information.

image

### PR DESCRIPTION
**Pull request by pablinos**
Fixes #18477

#### Changes proposed in this Pull Request:

This change passes the cover art URL and the feed URL to the front end so that they can be used when populating the podcast episode template. 

#### Jetpack product discussion

This is a bug fix.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
As explained in #18477:

* Go to ` /wp-admin/post-new.php?anchor_episode=89113006-542a-11eb-b4f3-c3757114ae55&anchor_podcast=5243218` on a development site with beta extensions enabled.
* Notice that the cover image block and the podcast player are both displayed as placeholders
* Apply this change and go to the above URL again. The new post should have blocks set up correctly.

#### Proposed changelog entry for your changes:
Not needed as this is a bug with a feature that's not yet launched.

### CODE REVIEW

**Review by retrofox — APPROVED** [review]
LGTM

**Comment by pablinos** [comment]
I had to rebase this, so if you could give it another look when you get a chance @retrofox, that would be great.

File: projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php [hunk 1]
```diff
@@ -119,10 +119,16 @@ function process_anchor_params() {
...
+						$self_links = $rss->get_links( 'self' );
+						$cover      = $rss->get_image_url();
+						$cover      = ! empty( $cover ) ? esc_url( $cover ) : null;
+
 						// Add insert basic template action.
 						$data['actions'][] = array(
 							'insert-episode-template',
 							array(
+								'feedUrl'         => ! empty( $self_links ) ? esc_url_raw( $self_links[0] ) : $feed,
+								'coverImage'      => $cover,
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php:131]:
```suggestion
								'coverImage'      => esc_url( $cover ),
```

File: projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php [hunk 2]
```diff
@@ -119,10 +119,16 @@ function process_anchor_params() {
 							),
 						);
 
+						$self_links = $rss->get_links( 'self' );
+						$cover      = $rss->get_image_url();
+						$cover      = ! empty( $cover ) ? esc_url( $cover ) : null;
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php:124]: Maybe we can escape later?

```suggestion
						$cover      = ! empty( $rss->get_image_url() ) ? $rss->get_image_url() : null;
```

Comment (pablinos) [reply projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php:124]: Definitely! Is the advantage that we escape at the last minute, in case the value gets used in a future change?

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/anchor-fm/anchor-fm.php:124]: That would be the idea, yes.

**Review by jeherve — APPROVED** [review]

File: projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js [hunk 3]
```diff
@@ -37,20 +37,22 @@ function podcastSection( { episodeTrack } ) {
...
+				'core/column',
+				{
 					width: '30%',
 				},
 				[
 					[
 						'core/image',
 						{
-							url: image ? image : null,
+							url: image ? image : coverImage,
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/blocks/anchor-fm/templates/index.js:48]: 💯

**Review by retrofox — APPROVED** [review]
This is a nice one. LGTM. 🚢

**Comment by pablinos** [comment]
r219919-wpcom
