### PR TITLE
External Media: Update Google Photo Filters

### LINKED ISSUE #15880: (5P) External Media: Fix Google Photos filters
#### Steps to reproduce the issue

1. Add `Image` block,
2. Click `Select Image` button and select Google Photos,

➡ The "Before/After Date" filter issue:

3. At the top of the modal window, select the "Before/After Date" filter and add it,
4. The filter element is added in a form of a link:
   Screenshot 2020-05-21 13 12 55
5. Clicking the "Before/After Date" opens the calendar, but it always sets the current date regardless of what's picked.

➡ The "Only favorite media" filter issue (**This should be fixed now**):

6. Add the "Only favorite media" filter,
7. There's no space between the title and the "Remove filter" button:
   Screenshot 2020-05-21 13 55 23
8. The favorite media filter has different wording for the select option vs added filter (might be resolved by https://github.com/Automattic/jetpack/pull/15717#discussion_r428567703):
   - Select option: "Favourite media only" (British),
   - Added filter: "Only favorites" (US).

➡ The "Category" filter issue:

9. Add "After date", "Before date", "Category" and "Favourite media only" filters in this exact order,
10. Remove "Only favorites" and "Category" filters in this exact order,
11. Add "Category" filter again,
12. Only the "Remove filter" button is added this time and the filter is still available from the select options:
    Screenshot 2020-05-21 14 08 31

#### Demo screencast:

Screen Capture on 2020-05-27 at 18-26-24

### PR DESCRIPTION
**Pull request by marekhrabe**
Fixes #15880

#### Changes proposed in this Pull Request:

* This addresses bugs discovered by dialing down the UI for filtering and starting with a few restricted options

#### Screenshot

Screenshot 2020-06-18 at 18 15 56

New filtering options allow you to:
- switch between All Photos (previously Recent Photos) and Albums
- for All Photos - we show the date range select with predefined options
- for Albums - we show breadcrumb links as you navigate in albums

In a separate PR, I will add an additional date range option that will allow you to customize it. Based on #15880 design

#### Testing instructions:
* Open the Google Photos modal
* Observe and test the new UI in the header of the modal - make sure it works as expected

#### Proposed changelog entry for your changes:
* none

### CODE REVIEW

File: extensions/shared/external-media/constants.js [hunk 1]
```diff
@@ -135,3 +135,36 @@ export const PEXELS_EXAMPLE_QUERIES = [
...
+	},
+	{
+		value: DATE_RANGE_LAST_6_MONTHS,
+		label: __( 'Last 6 months', 'jetpack' ),
+	},
+	{
+		value: DATE_RANGE_OLDER,
+		label: __( 'Older than a year', 'jetpack' ),
+	},
+	// TODO: Implement a UI for selecting month & year.
```
Comment (marekhrabe) [inline extensions/shared/external-media/constants.js:165]: Intentionally left in, as the filtering logic is fully implemented. UI will follow in a different PR.

File: extensions/shared/external-media/sources/google-photos/google-photos-media.js [hunk 2]
```diff
@@ -30,10 +36,15 @@ function GooglePhotosMedia( props ) {
 		allowedTypes,
 		path,
 		copyMedia,
+		showAdditionalFilters = false,
```
Comment (marekhrabe) [inline extensions/shared/external-media/sources/google-photos/google-photos-media.js:39]: I made this so we can simply bring back more filters.

File: extensions/shared/external-media/sources/google-photos/filter-request.js [hunk 3]
```diff
@@ -14,9 +32,35 @@ export default function getFilterRequest( filters ) {
...
 
-	if ( startDate || endDate ) {
-		const start = startDate ? startDate.substr( 0, 10 ) : '0000-00-00';
-		const end = endDate ? endDate.substr( 0, 10 ) : '0000-00-00';
+	if ( date ) {
+		let startDate = null;
+		let endDate = null;
+		switch ( date.range ) {
+			case DATE_RANGE_LAST_7_DAYS:
+				startDate = moment( TODAY ).subtract( 7, 'days' );
```
Comment (obenland) [inline extensions/shared/external-media/sources/google-photos/filter-request.js:40]: What's the benefit of passing `TODAY` into `moment()`? Does it save us from recreating that object every time?

File: extensions/shared/external-media/sources/google-photos/filter-request.js [hunk 4]
```diff
@@ -14,9 +32,35 @@ export default function getFilterRequest( filters ) {
 		query.push( 'feature=favorite' );
 	}
 
-	if ( startDate || endDate ) {
-		const start = startDate ? startDate.substr( 0, 10 ) : '0000-00-00';
-		const end = endDate ? endDate.substr( 0, 10 ) : '0000-00-00';
+	if ( date ) {
+		let startDate = null;
+		let endDate = null;
```
Comment (obenland) [inline extensions/shared/external-media/sources/google-photos/filter-request.js:37]: Would it make sense to have `endDate` default to `TODAY`? It looks like it'll be overwritten ever other case where that would not be desired.

**Comment by jancavan** [comment]
Thanks @marekhrabe! A few changes I'd like to suggest:

- I think we should just call it `Photos` since we use `Albums` for the second option vs `All albums`
- Instead of `Older than a year`, I think we should instead use `Last 12 months` to be consistent with rest of the options that say `Last - x`. Then if they want anything older than that, `Any time` can handle it. Thoughts? @lessbloat @lcollette @obenland 
- I can go with either `Filter by time period` or `Sort by time period` for the filtering options label. I think the latter is better - shorter and easier to understand (This was reviewed by Editorial. See: Slack-C029XD8PN-p1592510812364600)

File: extensions/shared/external-media/sources/google-photos/filter-request.js (hunk 3 above)
Comment (marekhrabe) [reply extensions/shared/external-media/sources/google-photos/filter-request.js:40]: It will actually make a new moment instance. Otherwise, calling the method directly on TODAY will mutate it and will throw all other calculations off

**Comment by marekhrabe** [comment]
All feedback addressed! 

Screenshot 2020-06-22 at 13 28 01

**Comment by jancavan** [comment]
@marekhrabe Can we please use Gutenberg text fields where the label is above the field?

Examples:

Screen Shot 2020-06-22 at 3 30 25 PM

Screen Shot 2020-06-22 at 3 30 35 PM

This way, we don't take up too much horizontal space and can accommodate [this design](https://github.com/Automattic/jetpack/issues/15880#issuecomment-647705847).

**Comment by jancavan** [comment]
I also noticed the "View" toggle moves a pixel up/down when switching views. See: https://cloudup.com/cb-bZ6ZVIwL

**Comment by marekhrabe** [comment]
Absolutely, I will look into the styling as a followup PR soon. I plan no more changes in this one and I think we are ready for a final code review.

**Comment by obenland** [comment]
@jan How strongly do you feel about `Sort by time period` vs `Filter by…`? It was the one thing that threw me off a little when testing it just now, since we're not actually sorting the pictures. Filter feels more appropriate to me 😬

File: extensions/shared/external-media/sources/google-photos/filter-option.js [hunk 5]
```diff
@@ -1,16 +1,19 @@
 /**
  * External dependencies
  */
-import { dateI18n, __experimentalGetSettings } from '@wordpress/date';
```
Comment (obenland) [inline extensions/shared/external-media/sources/google-photos/filter-option.js:4]: It looks like `__experimentalGetSettings` can get removed, too?

File: extensions/shared/external-media/sources/google-photos/google-photos-media.js (hunk 2 above)
Comment (obenland) [reply extensions/shared/external-media/sources/google-photos/google-photos-media.js:38]: I'm unclear on the latest status of those. Did we decide to remove all of them or keep the ones that are working?

**Comment by jancavan** [comment]
@obenland @marekhrabe I don't have strong opinions as long as we say, "... by time period".

**Comment by jancavan** [comment]
@obenland I think we should add events for this (if we don't have them already), to see if users ever use this? Would be nice to know which options in each dropdown they interact with. Can be in a separate PR of course.

**Review by obenland — APPROVED** [review]
Good to go from my end. Let's get it in and continue iterating!

File: extensions/shared/external-media/sources/google-photos/google-photos-media.js (hunk 2 above)
Comment (marekhrabe) [reply extensions/shared/external-media/sources/google-photos/google-photos-media.js:38]: Yeah, in the parent issue. The first version will be with a simplified UI but I didn't want to rewrite/remove all the logic for all other filters. Thus the default to `false` while keeping things around.

**Comment by marekhrabe** [comment]
Followup work started in… https://github.com/Automattic/jetpack/pull/16266

**Comment by obenland** [comment]
@jeherve #16069 is merged and it doesn't look like this one needs rebasing. Should be ready for your review

**Review by jeherve — APPROVED** [review]
If I use the view filter to switch to the Album view for example, the time period filter disappears. Is that on purpose for now?

Right now I can't say that the time period filter is really useful since it doesn't change what pictures I have access to; I still have to click on Load More if I want to access more than the last 12 pictures on my account. But I guess that will all change once we add more filters.

Approving this PR for now just in case the album use case is on purpose for now as well.

**Comment by obenland** [comment]
> If I use the view filter to switch to the Album view for example, the time period filter disappears. Is that on purpose for now?

It is, yes, we took that over like that from Tinker. It might be that Google's API doesn't support date filtering for albums?

**Comment by obenland** [comment]
r209626-wpcom
