### PR TITLE
Mobile Theme: do not redirect to referer

### LINKED ISSUE #11165: Mobile Theme: Redirecting to referer cause problems
#### Steps to reproduce the issue

1. Create a link from another website to a post on your wordpress and add "?ak_action=reject_mobile" to the end of the link. 
2. Try that link.
3. You will be redirected to wp-admin!

#### What I expected

We should be redirected to the post.
#### What happened instead
We are redirected to wp-admin.

#### Note
This is a very serious problem, since google might index your blogs with "?ak_action=reject_mobile" suffix. It will cause all visitors from google search unable to access your actual post!

### PR DESCRIPTION
**Pull request by BoleynSu**
Fixes #11165 

#### Changes proposed in this Pull Request:

* Delete redirect to referer.

#### Testing instructions:

1. Activate the Mobile Theme feature on site A running the patch.
2. Have a site B that uses HTTPS, and add the following links to one of your posts on that site:
```
<a href="https://yoursite.com/a-post/?ak_action=reject_mobile">check out this link</a>
<a href="https://yoursite.com/?ak_action=reject_mobile">check out this link</a>
<a href="https://yoursite.com/a-post/?ak_action=force_mobile">check out this link</a>
<a href="https://yoursite.com/?ak_action=force_mobile">check out this link</a>
<a href="https://yoursite.com/a-post/?ak_action=accept_mobile">check out this link</a>
<a href="https://yoursite.com/?ak_action=accept_mobile">check out this link</a>
```
3. Have a site C that does not use HTTPS. Add the same links to that site.
4. Visit the posts on site B and site C from a mobile device and a desktop device, and make sure each link behaves properly. Remember to flush your cookies after clicking on each link.

#### Proposed changelog entry for your changes:

* Fix unexpected redirection when mobile theme is enabled.

### CODE REVIEW

**Comment by jeherve** [comment]
> No need to test.

We do test all changes, so this does need to be tested :)

Here is what I would recommend for this section:

1. Activate the Mobile Theme feature on site A running the patch.
2. Have a site B that uses HTTPS, and add the following links to one of your posts on that site:
```
https://yoursite.com/a-post/?ak_action=reject_mobile
https://yoursite.com/?ak_action=reject_mobile
https://yoursite.com/a-post/?ak_action=force_mobile
https://yoursite.com/?ak_action=force_mobile
https://yoursite.com/a-post/?ak_action=accept_mobile
https://yoursite.com/?ak_action=accept_mobile
```
3. Have a site C that does not use HTTPS. Add the same links to that site.
4. Visit the posts on site B and site C from a mobile device, and make sure each link behaves properly

**Comment by jeherve** [comment]
> Is it Ok I just copy your recomended instructions for testing?

Sure thing!

File: modules/minileven/minileven.php [hunk 1]
```diff
@@ -117,7 +117,9 @@ function jetpack_mobile_template( $theme ) {
 }
 
 function jetpack_mobile_available() {
-	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. home_url( '?ak_action=accept_mobile' ) . '">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
+	global $wp;
+	$current_url =  trailingslashit( home_url( add_query_arg( array(), $wp->request ) ) );
+	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. $current_url . '?ak_action=accept_mobile">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
```
Comment (jeherve) [inline modules/minileven/minileven.php]: What is your rationale behind that change? It seems unrelated to the previous change, so it may be best to include this in a different pull request. 

I would also recommend, since you are using `add_query_arg` here, to use it to add the `ak_action` param.

**Review by jeherve — CHANGES_REQUESTED** [review]
Quick question about your second change.

File: modules/minileven/minileven.php (hunk 1 above)
Comment (BoleynSu) [reply modules/minileven/minileven.php]: Sure, I am considering doing so. I do so just because ` modules/minileven/theme/pub/minileven/footer.php` did the same way, so it is consistent. However, ` modules/minileven/theme/pub/minileven/footer.php` is doing things wrongly already.
I am testing if `$current_url =  home_url( add_query( array( 'ak_action' => 'accept_mobile' ), add_query_arg( $_GET, $wp->request ) ) );
` will work.

Comment (jeherve) [reply modules/minileven/minileven.php]: Thank you!

Comment (BoleynSu) [reply modules/minileven/minileven.php]: I have removed the second change. Could you review the pull request and merge it? I will request another soon.

Comment (BoleynSu) [reply modules/minileven/minileven.php]: Oh, I just remember why I put 2nd change here. Before I fix this bug, the link for web and full is consistent mostly. That is Page A => click web => Page A => click full => Page A. After my update, it becomes Page A => click web => home => click full => home. So should I
1) keep the second change which is buggy but consistent;
2) URL for both web an full;
3) just leave it as it is and create another PR?

Comment (jeherve) [reply modules/minileven/minileven.php]: It may be worth reconsidering your patch. We do need `HTTP_REFERER` in some cases, as this shows, for example when navigating within the site (instead of coming from a different site).

Comment (BoleynSu) [reply modules/minileven/minileven.php]: I added another commit (i.e. I chose option 2) which solves this issue. Now both navigating within the site and coming from a different site should work.
Anyway, I don't think use referer is a good idea.

Comment (BoleynSu) [reply modules/minileven/minileven.php]: Noting that the 2nd commit also fix the bug with URL like https://blog.example.com/?p=1.
I have apply the patch to my blog. If you want to do some test you can try it [here](blog.boleyn.su).

**Review by jeherve — CHANGES_REQUESTED** [review]
Quick notes about escaping just to be safe.

File: modules/minileven/minileven.php [hunk 2]
```diff
@@ -117,7 +117,9 @@ function jetpack_mobile_template( $theme ) {
 }
 
 function jetpack_mobile_available() {
-	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. home_url( '?ak_action=accept_mobile' ) . '">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
+	global $wp;
+	$current_url =  home_url( add_query_arg( array( 'ak_action' => 'accept_mobile' ), add_query_arg( $_GET, $wp->request ) ) );
+	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. $current_url . '">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
```
[the remark this answers is not in the document]
Comment (BoleynSu) [reply modules/minileven/minileven.php]: Done.

**Review by jeherve — APPROVED** [review]
This works well in my tests. 👍

**Comment by jeherve** [comment]
Matching WordPress.com diff: D11166-code

File: modules/minileven/minileven.php [hunk 3]
```diff
@@ -117,7 +117,9 @@ function jetpack_mobile_template( $theme ) {
 }
 
 function jetpack_mobile_available() {
-	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. home_url( '?ak_action=accept_mobile' ) . '">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
+	global $wp;
+	$current_url =  home_url( add_query_arg( array( 'ak_action' => 'accept_mobile' ), add_query_arg( $_GET, $wp->request ) ) );
```
Comment (jeherve) [inline modules/minileven/minileven.php]: Coming back to this, I'd like to offer a solution that should work regardless of your permalink settings, and even on sites where WP lives in a subdirectory. It's also a bit easier to read as it does not use a `add_query_arg` inside another `add_query_arg`.

```php
	global $wp;
	$url_params = array(
		'ak_action' => 'accept_mobile',
	);
	if ( is_array( $_GET ) && ! empty( $_GET ) ) {
		$url_params[] = $_GET;
	}
	$current_url = home_url(
		add_query_arg(
			$url_params,
			$wp->request
		)
	);

	echo '<div class="jetpack-mobile-link" style="text-align:center;margin:10px 0;"><a href="'. esc_url( $current_url ) . '">' . __( 'View Mobile Site', 'jetpack' ) . '</a></div>';
```

What do you think about this?

File: modules/minileven/theme/pub/minileven/footer.php [hunk 4]
```diff
@@ -30,9 +30,9 @@
 
 <?php
 	global $wp;
-	$current_url =  trailingslashit( home_url( add_query_arg( array(), $wp->request ) ) );
+	$current_url =  home_url( add_query_arg( array( 'ak_action' => 'reject_mobile' ), add_query_arg( $_GET, $wp->request ) ) );
```
Comment (jeherve) [inline modules/minileven/theme/pub/minileven/footer.php]: Using the same approach as above:

```php
	global $wp;
	$url_params = array(
		'ak_action' => 'reject_mobile',
	);
	if ( is_array( $_GET ) && ! empty( $_GET ) ) {
		$url_params[] = $_GET;
	}
	$current_url = home_url(
		add_query_arg(
			$url_params,
			$wp->request
		)
	);
```

**Review by jeherve — DISMISSED** [review]
Here is a somewhat different, maybe more readable approach.

File: modules/minileven/theme/pub/minileven/footer.php (hunk 4 above)
Comment (BoleynSu) [reply modules/minileven/theme/pub/minileven/footer.php]: Does wp->request keep _GET parameters? If not, your approach will not work when the original URL contains parameters. Otherwise, I think your approach is OK but
```php
home_url( add_query_arg( array( 'ak_action' => 'accept_mobile' ), $wp->request ) );
```
would be even better.

Comment (jeherve) [reply modules/minileven/theme/pub/minileven/footer.php]: > Does wp->request keep _GET parameters?

This should take care of that:

```
if ( is_array( $_GET ) && ! empty( $_GET ) ) {
	$url_params[] = $_GET;
}
```

Comment (BoleynSu) [reply modules/minileven/theme/pub/minileven/footer.php]: Hi, I have not been programming in PHP for years so didn't know it works. Now, I check, and it does work. However, I still don't think it is necessary to make things more complicated if it works with two add_query_arg. We can even use `home_url( add_query_arg('ak_action', 'reject_mobile') );` if we want a short solution. More complicated code means more likely to be buggy IMO.

Comment (jeherve) [reply modules/minileven/theme/pub/minileven/footer.php]: > We can even use home_url( add_query_arg('ak_action', 'reject_mobile') ); if we want a short solution

That won't work I am afraid, as you would then be missing the post slug when viewing single posts or pages. It would only be good on the home page.

Comment (BoleynSu) [reply modules/minileven/theme/pub/minileven/footer.php]: According to my testing, it works viewing single post or page. Could you show me a counter example?

Comment (jeherve) [reply modules/minileven/theme/pub/minileven/footer.php]: Did you test when using only `home_url( add_query_arg('ak_action', 'reject_mobile') ); `, or the patch in this PR?

Comment (BoleynSu) [reply modules/minileven/theme/pub/minileven/footer.php]: I tested both of them. They worked the same.

Comment (jeherve) [reply modules/minileven/theme/pub/minileven/footer.php]: It does indeed seem to work well in my tests; let's go with that simpler implementation!

Comment (BoleynSu) [reply modules/minileven/theme/pub/minileven/footer.php]: I have updated it with the simpler impl.

**Comment by kraftbj** [comment]
D24819-code for the referer change on wp.com.

**Comment by kraftbj** [comment]
Works for me in my testing.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
Brought into wp.com via r188164-wpcom and r53401-wpcom-themes

File: modules/minileven/theme/pub/minileven/footer.php (hunk 4 above)
Comment (dstein64) [reply modules/minileven/theme/pub/minileven/footer.php]: I ran into an issue that seemingly arises from omitting `$wp->request` in the call to `add_query_arg`.

Adding that argument alone isn't enough, since query string parameters aren't retained. I've implemented the approach proposed by @jeherve and submitted PR #12414, which describes the issue I encountered.
