### PR TITLE
Make url acceptance more liberal in admin-menus

### LINKED ISSUE #64691: Calypso: Some Third Party Plugin (Elementor) Navigation Links lead nowhere in Calypso, work in WP-Admin
### Quick summary

On WordPress.com sites with Elementor installed, some links under My Site → Templates do not work when on Calypso. For example, Templates → Theme Builder doesn't work. It links to whatever page you're on Calypso. But if you navigate to /wp-admin, the links work correctly. 

In this screenshot, check out the link at the bottom. This is on Calypso. 
Screen Shot 2022-06-16 at 9 26 02 AM

The same link works fine when I'm on /wp-admin: 

Screen Shot 2022-06-16 at 9 32 34 AM

### Steps to reproduce

1. Install Elementor on a WordPress.com site. 
2. Navigate to My Sites → Templates → Theme Builder

### What you expected to happen

Theme Builder page should open. Link: /wp-admin/admin.php?page=elementor-app&ver=3.6.6#/site-editor/templates (this requires Elementor Pro), but the "Theme Builder" should load something even without Elementor Pro installed. 

### What actually happened

Nothing happens. 

### Context

This was reported on a live chat, which I've since pushed to a ticket here: 5301448-zd-woothemes
I could replicate it on my test site. 

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Likely not. 

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround is to simply visit the wp-admin dashboard (like by clicking My Site → Plugins → Installed Plugins) and then click Templates → Theme Builder.

### PR DESCRIPTION
**Pull request by dsas**
Fixes https://github.com/Automattic/wp-calypso/issues/64691

## Proposed changes:

Treat menu items with a fully qualified url matching the site url the same as other internal URLs in the admin-menus rest api endpoint.

This API endpoint is used for nav-unification on wpcom. This change improves compatibility with 3rd party plugins, so that their menu links work on WordPress.com.
 

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

 1. Set-up a wpcom atomic dev site
 2. Install elementor on it
 3. Go to wordpress.com/home/yourdomain or any other calypso page
 4. Try Templates → Theme Builder, Templates → Kit Library & Templates → Add New menu items. They will all just link back to the current page.
 5. Apply this change to your wpcom atomic dev site
 6. Repeat step four, this time the links should take you to the appropriate page as they do in wp-admin

(You may note that the appropriate page looks like a mess, this is https://github.com/Automattic/page-optimize/issues/59

### CODE REVIEW

**Review by mmtr — COMMENTED** [review]
Nice finding!

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php [hunk 1]
```diff
@@ -377,8 +377,11 @@ private function prepare_menu_item_url( $url, $parent_slug = '' ) {
 				return wp_specialchars_decode( esc_url_raw( $url ) );
 			}
 
-			// Disallow other external URLs.
-			return '';
+			if ( 1 !== preg_match( '/^' . preg_quote( get_site_url(), '/' ) . '/i', $url ) ) {
+				// Disallow other external URLs.
+				return '';
+			}
+			// The URL matches that of the site, treat it as an internal URL.
```
Comment (mmtr) [inline projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php]: What do you think about checking if the URL points to WP Admin as well to make it safer?

I'd also use `strpos ` instead of a regex check (for consistency with the checks above, and for readability).

```suggestion
			// Disallow other external URLs that don't point to the admin area.
			if ( 0 !== strpos( $url, get_admin_url() ) ) {
				return '';
			}
			// The URL is an admin URL, treat it as internal.
```

Comment (dsas) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php]: > What do you think about checking if the URL points to WP Admin as well to make it safer?

I've no strong opinion. I'm not sure what it makes it safer from though, and I wonder if there were use-cases I never thought of, like if a plugin changes the front-end and needs special preview links to them for example.

> I'd also use strpos instead of a regex check (for consistency with the checks above, and for readability).

+1 that is clearer

Comment (mmtr) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php]: > I've no strong opinion. I'm not sure what it makes it safer from though, and I wonder if there were use-cases I never thought of, like if a plugin changes the front-end and needs special preview links to them for example.

I think the logic for internal URLs below checks anyway it's an admin URL so I don't think there is a case where a frontend URL would be allowed anyway.

Comment (dsas) [reply projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-admin-menu.php]: I temporarily added a test case for `menu_item_url_data`:
```php
array(
	'/made-up-front-end-page',
	'',
	null,
	'',
),
```

and it failed because it expected an empty string and received `/made-up-front-end-page`

**Review by mmtr — APPROVED** [review]
