### PR TITLE
Jetpack Footer: fix accessibility issues

### LINKED ISSUE #31422: [Flagship plugin] Footer: links could have a bigger target area

### LINKED ISSUE #31520: [Flagship plugin] Footer: include links in a list and footer tags

### LINKED ISSUE #31521: [Flagship plugin] Footer: remove the word 'logo' from Jetpack logo alt text

### LINKED ISSUE #31522: [Flagship plugin] Footer: include the Jetpack logo in the 'Jetpack' link

### LINKED ISSUE #31523: [Flagship plugin] Footer: 'An Automattic Airline' is read twice by screen readers

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes #31422 #31520 #31521 #31522 #31523

## Proposed changes:

This PR fixes several accessibility issues in the Jetpack Footer:
- it makes the target area of links bigger so that they can be hit more easily
- it adds the footer landmark so that screen readers can identify it as such
- it adds links in a list to provide screen reader users with a better browsing experience
- it makes sure the _Jetpack_ and _Automattic_  accessible names items are read only once by screen readers
- it includes the Jetpack logo in the matching link, making it clickable
- it adds more tests to make sure those improvements won't break

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pedMtX-Rg-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Spin up a test site with this branch
- Make sure the footer looks like before
- Optionally, use a screen reader to test the above, as illustrated in the screencast below

_Turn the sound on_

https://github.com/Automattic/jetpack/assets/1620183/717c8b30-b06d-46f3-9084-cc8ed4d3e1a3

### CODE REVIEW

File: projects/js-packages/components/components/jetpack-footer/index.tsx [hunk 1]
```diff
@@ -8,6 +8,10 @@ import JetpackLogo from '../jetpack-logo';
 import useBreakpointMatch from '../layout/use-breakpoint-match';
 import type { JetpackFooterProps } from './types';
 
+const JetpackIcon: React.FC = () => (
+	<JetpackLogo logoColor="#000" showText={ false } height={ 16 } aria-hidden="true" />
```
Comment (monsieur-z) [inline projects/js-packages/components/components/jetpack-footer/index.tsx:12]: Set `aria-hidden="true"` since the accessible name of the corresponding item is defined by `moduleName`.

File: projects/js-packages/components/components/jetpack-footer/index.tsx [hunk 2]
```diff
@@ -24,70 +28,69 @@ const JetpackFooter: React.FC< JetpackFooterProps > = ( {
...
+							>
+								{ item.label }
+								{ isExternalLink && <Icon icon={ external } size={ 16 } /> }
+							</a>
+						</li>
+					);
+				} ) }
+				<li className="jp-dashboard-footer__a8c-item">
+					<a href={ a8cLogoHref } aria-label={ __( 'An Automattic Airline', 'jetpack' ) }>
+						<AutomatticBylineLogo aria-hidden="true" />
```
Comment (monsieur-z) [inline projects/js-packages/components/components/jetpack-footer/index.tsx:89]: `aria-hidden="true"` prevents icon title from being read by screen readers. Accessible name is defined by `aria-label` on the link above.

File: projects/js-packages/components/components/jetpack-footer/style.scss [hunk 3]
```diff
@@ -1,116 +1,99 @@
 .jp-dashboard-footer {
```
Comment (monsieur-z) [inline projects/js-packages/components/components/jetpack-footer/style.scss:1]: Putting all links in a list and using flexboxes allows us to get rid of a bunch of rules.

**Review by kraftbj — DISMISSED** [review]
Worked well and confirmed with an independent screen read test 👍🏼

**Review by kraftbj — APPROVED** [review]
