### PR TITLE
cli: Recommend re-running with `-v` when certain commands fail

### LINKED ISSUE #37524: Tools: Jetpack Install fails with cryptic message when PHP version is wrong
When PHP's version is incompatible with `jetpack install` we get the following message:
```
 pnpm jetpack install
✔ What type of project are you working on today? · plugins
✔ Please choose which project · crm
  ⠹ Installing pnpm dependencies
  ✖ Installing composer dependencies for plugins/crm
    → Command failed with exit code 2: composer install
Error: Command failed with exit code 2: composer install
    at makeError (file:///home/gogdzl/dsk/git/avengers/jetpack/node_modules/.pnpm/execa@7.0.0/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///home/gogdzl/dsk/git/avengers/jetpack/node_modules/.pnpm/execa@7.0.0/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 2: composer install',
  command: 'composer install',
  escapedCommand: 'composer install',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  context: [Object: null prototype] {}
}
```

Environment:

```
 composer --version
Composer version 2.7.6 2024-05-04 23:03:15
PHP version 8.3.7 (/usr/bin/php)
Run the "diagnose" command to get more detailed diagnostics output.
```

By downgrading PHP everything runs smoothly.

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Some commands, particularly those using listr for more friendly output on successful runs, don't produce useful error messages when things fail. Have those commands recommend re-running with `-v` in those situations.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #37524

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

The new message inviting use of `-v` should appear for the following tests:

* Introduce an error for `composer install` in some project (e.g. change a composer dependency to a nonexistent version). Then:
  * Run `jetpack build` for the project.
  * Run `jetpack test` for the project.
  * Run `jetpack phan` for the project.
* Introduce a build error in some project. Then run `jetpack build` for it.
* Add `echo FAIL; exit 1` to `projects/packages/status/.phan/pre-run`, then run `jetpack phan packages/status`.
* Add a `throw` to some project's `.phan/config.php`, then run `jetpack phan` for that project.
* Arrange for `jetpack cli link` to fail (how? 🤷), and run that.

The new message inviting use of `-v` should _not_ appear for the following tests:

* Do any of the above with `-v`.
* Run `jetpack build`, `jetpack test`, and `jetpack phan` without having introduced any errors.
* Introduce a failing test (e.g. stick `$this->fail( "!" );` in any phpunit test), then run `jetpack test` for the project.
* Introduce a Phan issue (e.g. delete a suppression from `.phan/baseline.php`), then run `jetpack phan` for the project.

### CODE REVIEW

File: tools/cli/commands/phan.js [hunk 1]
```diff
@@ -468,11 +468,13 @@ export async function handler( argv ) {
 							}
 							if ( json.length ) {
 								issues.push( ...json );
-								throw new Error(
+								const err = new Error(
 									json.length === 1
 										? 'Phan reported 1 issue'
 										: `Phan reported ${ json.length } issues`
 								);
+								err.isSuccessfulError = true;
```
Comment (tbradsha) [inline tools/cli/commands/phan.js:476]: Yay, successful errors!

File: tools/cli/commands/phan.js [hunk 2]
```diff
@@ -662,4 +667,16 @@ export async function handler( argv ) {
 		reportStream.end();
 		console.log( `Report written to ${ argv.reportFile }` );
 	}
+	if ( ( process.exitCode & 2 ) !== 0 ) {
```
Comment (tbradsha) [inline tools/cli/commands/phan.js:670]: What exit codes are possible? This would account for 1 and 2, but if 4 (or 5, or 8...) are possible weird error codes, wouldn't we want to show the "try -v" message?

File: tools/cli/commands/phan.js [hunk 3]
```diff
@@ -662,4 +667,16 @@ export async function handler( argv ) {
...
+				'Errors were encountered while running Phan for one or more projects! Results may not be complete.'
+			)
+		);
+		if ( ! argv.v ) {
+			console.error(
+				chalk.yellow( 'You might try running with `-v` to get more information on the failure' )
+			);
+		}
+	}
 }
```
Comment (tbradsha) [inline tools/cli/commands/phan.js:682]: Should we exit this script with an exit code?

File: tools/cli/commands/phan.js (hunk 2 above)
Comment (anomiex) [reply tools/cli/commands/phan.js:670]: See line 499 above. The possible codes are:

0: Phan ran successfully, no issues found.
1: Phan ran successfully, issues found.
2: Phan failed to run for at least one project. No issues found in any that did run.
3: Phan failed to run for at least one project, and issues were found in some that did run.

File: tools/cli/commands/phan.js (hunk 3 above)
Comment (anomiex) [reply tools/cli/commands/phan.js:682]: Setting `process.exitCode` makes node exit with that code whenever it does exit.

File: tools/cli/commands/phan.js (hunk 2 above)
Comment (tbradsha) [reply tools/cli/commands/phan.js:670]: I saw 1 and 2, but didn't see 0 (it was undefined when I was looking, which works okay) or 3.

Comment (anomiex) [reply tools/cli/commands/phan.js:670]: To get 3, you have to do both of these tests at the same time in different projects, and run phan on both of the projects at once:

* Add `echo FAIL; exit 1` to `projects/packages/status/.phan/pre-run`
* Introduce a Phan issue (e.g. delete a suppression from `.phan/baseline.php`)

Comment (tbradsha) [reply tools/cli/commands/phan.js:670]: Ah, perfect, thanks!

**Review by tbradsha — APPROVED** [review]
This works!
