### PR TITLE
Search: Prevent user from excluding all post types

### LINKED ISSUE #17124: Search: prevent user from excluding all post types in Customizer
As of #17122, we automatically ignore the 'excluded post types' setting if the user has chosen to exclude all post types in the Customizer:

Screen Shot 2020-09-10 at 14 37 21

To avoid confusion, we should also be preventing the user from selecting all post types for exclusion in the Customizer.

#### Steps to reproduce the issue

1. Go to /wp-admin/customize.php and choose 'Jetpack Search'
2. Check all of the checkboxes in 'Excluded post types'
3. Notice that in search results, all post types are excluded, but there is nothing in the Customizer UI to tell you about this

#### What I expected

I am either prevented from excluding all post types, or there is a message telling me my selection will be ignored.

#### What happened instead
I was able to exclude all post types but my selection was not honoured.

**Screenshots**

Screen Shot 2020-09-10 at 14 37 21

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #17124

##### Prevent user from excluding all post types:
- When there is only one option unchecked, set the options as disabled and re-enable if there are more than two left.
- And add ‘At least one post type should be left unchecked…." to the description. Checked FG, I assumed the description would be translated before next release. 

##### Options considered
1. When there is only one options left, we set it disabled and re-enable if there are more than two left. And add ‘At least one post type should be left unchecked…’ to the description. This is the option proposed, as it interferes the user least and would still prevent the user from checking all the boxes. 
2. When the last option is selected, we show a message saying all post types excluded and the setting will not be respected. The do-not-respect-settings idea is not good, because if not respected whey it's there.
3. When user select the last option, we revert the selection and show a message saying that, ‘at least one option should be left unchecked…’. This option could be working, but just would uncheck user’s selection, could be frustrating for users sometimes.

#### Jetpack product discussion
p1617144549011100-slack-jetpack-search-backstage

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to customizer of a Jetpack Search enabled site, ensure when only one post type unchecked, the option is not selectable.
- Publish site and ensure the options stick

#### Gif
Untitled

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/customize-controls/class-excluded-post-types-control.js [hunk 1]
```diff
@@ -1,20 +1,23 @@
 /* eslint-disable no-var */
 
-jQuery( document ).ready( function( $ ) {
+jQuery( document ).ready( function ( $ ) {
 	// Refresh our hidden field value if any checkboxes change
-	$( '.customize-control-excluded-post-type-checkbox' ).on( 'change', function() {
-		var $parent = $( this )
-			.parent()
-			.parent();
+	$( '.customize-control-excluded-post-type-checkbox' ).on( 'change', function () {
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/customize-controls/class-excluded-post-types-control.js:5]: auto-formatted by commit hooks

File: projects/plugins/jetpack/modules/search/customize-controls/class-excluded-post-types-control.js [hunk 2]
```diff
@@ -1,20 +1,23 @@
 /* eslint-disable no-var */
 
-jQuery( document ).ready( function( $ ) {
+jQuery( document ).ready( function ( $ ) {
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/customize-controls/class-excluded-post-types-control.js:3]: Lines 3-13 were auto formatted by git commit hooks.

File: projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php [hunk 3]
```diff
@@ -158,7 +158,7 @@ public function customize_register( $wp_customize ) {
 				$wp_customize,
 				$id,
 				array(
-					'description' => __( 'Choose post types to exclude from search results.', 'jetpack' ),
+					'description' => __( 'Choose post types to exclude from search results. For search to work properly, please leave at least one post type unchecked.', 'jetpack' ),
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php:161]: I think we could be more direct here and say "you must...".

```suggestion
					'description' => __( 'Choose post types to exclude from search results. You must leave at least one post type unchecked.', 'jetpack' ),
```

**Review by jsnmoon — DISMISSED** [review]
Works well! Could use a master merge/rebase before lobbing it over for crew review.

**Comment by kangzj** [comment]
Thanks @jsnmoon I will do a quick rebase.

**Review by sdixon194 — APPROVED** [review]
This works for me! Even tried a few other custom post types and everything worked as expected.

Just thinking out loud, I wonder if it would be more intuitive to have this section be "Include in Search:" with everything checked by default, then you uncheck to exclude them. I know that was my initial thought when I saw this section when I tried Search for the first time and noticed everything unchecked, then had to read to recognize that checking them off meant I was excluding them.

**Comment by kangzj** [comment]
> > Just thinking out loud, I wonder if it would be more intuitive to have this section be "Include in Search:" with everything checked by default, then you uncheck to exclude them. I know that was my initial thought when I saw this section when I tried Search for the first time and noticed everything unchecked, then had to read to recognize that checking them off meant I was excluding them.
> 
> Thanks for the suggestion @sdixon194!
> 
> @kangzj please can we create a new feature request issue for this and add it to the backlog in the 'Jetpack Search - Product Development' board?

Hi @bluefuton @sdixon194, feature request added in our project board: https://github.com/orgs/Automattic/projects/160#card-58580665

Thanks @sdixon194 for the feedback 👍

**Comment by kangzj** [comment]
🚢  Shipped in r223936-wpcom.
