### PR TITLE
Resolve PHP Warning with array_filter usage in sync of action_links.

### LINKED ISSUE #17550: PHP Warning in class-callables.php
PHP Warnings can be triggered via Jetpack Sync.

```
'PHP message: PHP Warning: array_filter() expects parameter 1 to be array, null given in /home/MYSITE/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-callables.php on line 374'
```

#### Steps to reproduce the issue

1. Add a filter to `plugin_action_links` that returns null
2. delete_option( 'jetpack_callables_sync_checksum' );
3. delete_transient( 'jetpack_sync_callables_await' );
4. modify a post
5. Warning will be visible in error logs.

#### What I expected
Jetpack should not generate PHP Warnings

#### What happened instead
```
'PHP message: PHP Warning: array_filter() expects parameter 1 to be array, null given in /home/MYSITE/public_html/wp-content/plugins/jetpack/vendor/automattic/jetpack-sync/src/modules/class-callables.php on line 374'
```

### PR DESCRIPTION
**Pull request by mdbitz**
Verify that $action_links is still an array after filters before calling array_filter on it.

Fixes #17550

#### Changes proposed in this Pull Request:
* Resolve PHP Warning when $action_links has been filtered to not be an array.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

1. Add a filter to plugin_action_links that returns null
`add_filter( 'plugin_action_links', '__return_true' );`
2. delete_option( 'jetpack_callables_sync_checksum' );
3. delete_transient( 'jetpack_sync_callables_await' );
4. modify a post -> triggers sync

**Before PR**
Warning will be visible in error logs.

**After PR**
No Warning is generated.

#### Proposed changelog entry for your changes:
* Jetpack Sync - Resolve array_filter warning that can be triggered by filters returning unexpected data.

### CODE REVIEW

File: packages/sync/src/modules/class-callables.php [hunk 1]
```diff
@@ -370,8 +370,13 @@ public function set_plugin_action_links() {
...
 			$action_links = apply_filters( 'plugin_action_links', $action_links, $plugin_file, null, 'all' );
 			/** This filter is documented in src/wp-admin/includes/class-wp-plugins-list-table.php */
-			$action_links           = apply_filters( "plugin_action_links_{$plugin_file}", $action_links, $plugin_file, null, 'all' );
-			$action_links           = array_filter( $action_links );
+			$action_links = apply_filters( "plugin_action_links_{$plugin_file}", $action_links, $plugin_file, null, 'all' );
+			// Verify $action_links is still an array to resolve warnings from filters not returning an array.
+			if ( is_array( $action_links ) ) {
+				$action_links = array_filter( $action_links );
+			} else {
+				$action_links = array();
```
Comment (anomiex) [inline packages/sync/src/modules/class-callables.php:378]: Seems like there should be a `_doing_it_wrong()` or something though, rather than silently ignoring the problem.

Comment (mdbitz) [reply packages/sync/src/modules/class-callables.php:378]: Hey Brad, in this case we are simply hardening the code to not throw a warning if a plugin/theme is modifying plugin_action_links or plugin_action_links_{$plugin_file}. There is nothing directly to call _doing_it_wrong() on.

**Review by leogermani — APPROVED** [review]
I was not able to reproduce the exact problem but the change looks good to me. The hook is documented in WP core and describes what the expected return format is.
