### PR TITLE
Fix jetpack comments via chrome when logged in

### LINKED ISSUE #38520: Jetpack Comments: Chrome prevent a logged in used from posting comments.
### Impacted plugin

Jetpack

### Quick summary

When you are a logged in user of your site  and Wordpress.com in latest Chrome. You end up with an issue where the user is user is not able to submit a comment. 

This happends because when we submit the comment via the invisible form. There request is not done as a logged in user but as a logged out request. 

The request fails because the nonce fails on 
https://github.com/Automattic/jetpack/blob/ab38bc962ba79040a2ef7694bea64ea023456bd6/projects/plugins/jetpack/modules/comments/comments.php#L628

This happends because at this point the user is not logged any more when the request is done via the jetpack.wordpress.com iframe.

### Steps to reproduce

1. In Chrome  
2. Login as a user to both .com and the site you are currenly site.  
4. Leave a comment. 
5. You see the nonce error. 

Screenshot 2024-07-24 at 2 30 30 PM 

### A clear and concise description of what you expected to happen.

As a logged in user you should always be able to leave a comment without seeing a nonce error. 

### What actually happened

Your are not able to leave a comment.

### Impact

Many

### Available workarounds?

Yes, use a different browser such as Firefox or Edge. 

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

### PR DESCRIPTION
**Pull request by enejb**
Fixes https://github.com/Automattic/jetpack/issues/38520

Before:

https://github.com/user-attachments/assets/c3f0f718-362f-458a-9c98-d64b6e8b1097

After:

https://github.com/user-attachments/assets/aeb637d6-c352-4042-9426-aacb6480c5b7

## Proposed changes:
* This PR implements a retry process for users that try to submit comment but for some reason the browser that is submitting the comment from jetpack.wordpress.com iframe doesn't send the cookies. This will make it so that the nonce verification fails there is a retry process that happens on the jetpack site that submits make the same request as the remote one. This PR doesn't change the verification steps. That the comment goes though but since the request is now being done on from the jetpack site it the cookies are being forwarded as expected and the request succeeds. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
Enable jetpack comments. 
In latest Chrome login to wordpress.com as well the jetpack site. leave a comment. 
Notice that you are able to leave a comment successfully. There might be a slight glitch with the spinner that you might notice but I think this is a better solution that currently exists.

### CODE REVIEW

**Comment by coder-karen** [comment]
Just dropping a comment here as well to say I left a comment in Slack about this - p1721979363629269/1721951133.674309-slack-CDLH4C1UZ - but there appears to be related work happening in https://github.com/Automattic/jetpack/pull/38485 as well.

**Review by heavyweight — DISMISSED** [review]
Tested and works great!
I'm fine with merging this once the static analysis is fixed.

File: projects/plugins/jetpack/modules/comments/comments.php [hunk 1]
```diff
@@ -655,6 +657,56 @@ public function pre_comment_on_post() {
...
+	 * This function exists because when we submit the form via the jetpack.wordpress.com iframe
+	 * in Chrome the request comes in to jetpack but for some reason the request doesn't hace access to cookies yet.
+	 * By submitting the form again locally with the same data the process works as expected.
+	 *
+	 * @return never
+	 */
+	public function retry_submit_comment_form_locally() {
+		// We are not doing any valiodation here since all the validation will be done again by pre_comment_on_post().
+		// if the comment has been posted, this is where we do our service verification checks
+		$comment_data = stripslashes_deep( $_POST ); // phpcs:ignore WordPress.Security.NonceVerification.Missing
```
Comment (coder-karen) [inline projects/plugins/jetpack/modules/comments/comments.php]: Is the comment above this line related specifically to `$comment_data = stripslashes_deep( $_POST );`, and in response to the PHPCS ignore comment?

Generally in the monorepo I see we add the comment in-line after the PHPCS ignore in that case, and possibly because of that I was slightly confused as to what the above comment referenced.

If the comment above is meant to cover the whole function then it could be worth just adding '-- verification done in `pre_comment_on_post` - see comment above' or similar. Otherwise I'd add the information in-line.

Also there is a typo - `valiodation` - if keeping the above comment :)

File: projects/plugins/jetpack/modules/comments/comments.php [hunk 2]
```diff
@@ -655,6 +657,56 @@ public function pre_comment_on_post() {
 		}
 	}
 
+	/**
+	 * Handle Jetpack Comments POST requests: process the comment form, then client-side POST the results to the self-hosted blog
+	 *
+	 * This function exists because when we submit the form via the jetpack.wordpress.com iframe
+	 * in Chrome the request comes in to jetpack but for some reason the request doesn't hace access to cookies yet.
+	 * By submitting the form again locally with the same data the process works as expected.
```
Comment (coder-karen) [inline projects/plugins/jetpack/modules/comments/comments.php]:
```suggestion
	 * in Chrome the request comes in to Jetpack but for some reason the request doesn't have access to cookies yet.
	 * By submitting the form again locally with the same data the process works as expected.
```

**Review by coder-karen — DISMISSED** [review]
Looks good to me too 👍 Thanks for working on this fix!

I left two comments, but I wouldn't call them blockers, as they're just related to comments.

File: projects/plugins/jetpack/modules/comments/comments.php (hunk 1 above)
Comment (enejb) [reply projects/plugins/jetpack/modules/comments/comments.php]: The comment was mean to help future devs figure out why we are not doing any validation in this function. 

I simplified it a bit.

**Review by coder-karen — APPROVED** [review]

**Comment by jsnajdr** [comment]
Looking at this PR after @simison pinged me about it... If I understand it correctly, the `pre_comment_on_post` function runs only on `jetpack.wordpress.com`, integrated into the Simple site in wpcom code, is that right? And when the nonce verification fails, it will return a response with a form that auto-submits to the Jetpack site itself.

It's certainly a workaround -- the ideal solution will be that the Verbum iframe asks for storage access (`document.requestStorageAccess`) after you click on the "Comment" button and before it submits the POST request to `jetpack.wordpress.com`. Then the POST request will be properly authenticated and there will be no nonce mismatch.

But we are still a long way from that: first we need to migrate the WP.com REST proxy away from auth cookies and only then we can start calling Storage Access API on individual widgets.

**Comment by enejb** [comment]
I don't expect any changes for simple sites here since simple sites don't use the iframe. 

This PR is just for jetpack sites that are not atomic. Since I wasn't able to replicate this issue on atomic at all. 

No, `pre_comment_on_post` runs on the jetpack site. (it might run on simple sites as well but that is not what I was looking at) 

the reason why this is needed is because when the you submit the comment. The iframe make a JS POST form submission request to the site. See fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Szh%2Qcyhtvaf%2Swrgcnpx%2Spynff.wrgcnpx%2Qeraqrere.cuc%3Se%3Q0rrqp613%231288-og 

but in chrome that request doesn't contain any cookie info. So on the Jetpack side the nonce verification fails because the request doesn't have a logged in user. 

I think in the ideal case we would be making a different authenticated request request to the Jetpack site from the iframe. 
but that solution could have its own problems such as REST requests being blocked.
