### PR TITLE
MU WPCOM: Don't load ETK on agency sites on all pages

### LINKED ISSUE #98746: The "page-patterns" plugin has encountered an error and cannot be rendered error on WordPress.com/Automattic for Agencies development sites
### Context and steps to reproduce

When creating a [development site from Automattic for Agencies](https://agencieshelp.automattic.com/knowledge-base/free-development-licenses-for-wordpress-com-hosting/), the page editor shows an error `The "page-patterns" plugin has encountered an error and cannot be rendered.`

I do not see this error on regular sites with a hosting plan. 

The error disappears if Gutenberg is disable on the development site.

There is a console error in the editor when that message is shown:

```
react-dom.min.js?ver=18:1 TypeError: 

Cannot destructure property 'setUsedPageOrPatternsModal' of '(0 , o.useDispatch)(...)' as it is null.
    at g (starter-page-templat…58d7afd8a36c:1:8221)
    at gt (react-dom.min.js?ver=18:1:45667)
    at js (react-dom.min.js?ver=18:1:120123)
    at Sl (react-dom.min.js?ver=18:1:88331)
    at kl (react-dom.min.js?ver=18:1:88259)
    at bl (react-dom.min.js?ver=18:1:88122)
    at sl (react-dom.min.js?ver=18:1:84974)
    at dl (react-dom.min.js?ver=18:1:85354)
    at Nn (react-dom.min.js?ver=18:1:32432)
    at react-dom.min.js?ver=18:1:82942
```

Some previous discussion of a now resolved related issue in August 2024 here: p1723186454644719-slack-C02FMH4G8

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/wp-calypso/issues/98746

## Proposed changes:

* Don't load ETK on agency sites on all pages like below. However, it's not the root cause of this issue)
```
[23-Jan-2025 04:01:27 UTC] #0 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): test_disable_page_template(false)
#1 /wordpress/core/6.7.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(49): apply_filters('a8c_disable_sta...', false)
#3 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(84): Automattic\Jetpack\Jetpack_Mu_Wpcom\Starter_Page_Templates->__construct()
#4 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(451): Automattic\Jetpack\Jetpack_Mu_Wpcom\Starter_Page_Templates::get_instance()
#5 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php(244): require_once('/wordpress/plug...')
```
* Disable auto-loading class from [here](https://github.com/Automattic/jetpack/blob/ea0b6d3d7c034e456ba66c0b149d90f95ec88fbf/projects/packages/jetpack-mu-wpcom/src/features/block-patterns/class-wpcom-block-patterns-from-api.php#L106).
```
[23-Jan-2025 03:51:50 UTC] #0 /wordpress/core/6.7.1/wp-includes/class-wp-hook.php(324): test_disable_page_template(false)
#1 /wordpress/core/6.7.1/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#2 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(49): apply_filters('a8c_disable_sta...', false)
#3 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(84): Automattic\Jetpack\Jetpack_Mu_Wpcom\Starter_Page_Templates->__construct()
#4 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/starter-page-templates/class-starter-page-templates.php(451): Automattic\Jetpack\Jetpack_Mu_Wpcom\Starter_Page_Templates::get_instance()
#5 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/composer/ClassLoader.php(576): include('/wordpress/plug...')
#6 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('/wordpress/plug...')
#7 [internal function]: Composer\Autoload\ClassLoader->loadClass('Automattic\\Jetp...')
#8 /wordpress/plugins/wpcomsh/6.1.0-alpha+rolling.1737565780.g7050119/vendor/automattic/jetpack-mu-wpcom/src/features/block-patterns/class-wpcom-block-patterns-from-api.php(106): class_exists('\\Automattic\\Jet...')
```

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Create an agency site
* Add a new page
* Make sure the following error is gone
  ```
  The "page-patterns" plugin has encountered an error and cannot be rendered error on
  ```

### CODE REVIEW

**Review by fushar — DISMISSED** [review]
Nice 👍 

|Before|After|
|-|-|
|image|image|

**Review by fushar — APPROVED** [review]

File: projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php [hunk 1]
```diff
@@ -173,6 +173,13 @@ public static function load_wpcom_user_features() {
 	 * Can be removed once the feature no longer exists in the ETK plugin.
 	 */
 	public static function load_etk_features_flags() {
+		// Don't load on agency sites.
+		if ( is_fully_managed_agency_site() ) {
```
Comment (taipeicoder) [inline projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: Would this prevent ETK features from loading on the frontpage of A4A sites?
Looking at the comment added below, seems that we want to load them on the frontend page.

Comment (fushar) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: Hmmmmmmm.... you're right. `is_fully_managed_agency_site()` automatically entails `! is_wpcom_user()`, so for admin pages (like `page-new.php`), this change should have no effect 🤔 

But I'm not sure why it worked when I tested this change via Beta Tester (even before the last commit). 😅

Comment (fushar) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: Should we revert this particular change?

Comment (arthur791004) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: > Would this prevent ETK features from loading on the frontpage of A4A sites?

Yes. Do we want to load any features on the frontend page of A4A sites? I think all ETK features should be disabled on A4A sites

> Hmmmmmmm.... you're right. is_fully_managed_agency_site() automatically entails ! is_wpcom_user(), so for admin pages (like page-new.php), this change should have no effect 🤔

Yes. The change is to disable ETK features on A4A sites. I feel weird that the feature should depend on the site instead of the user but the `is_wpcom_user ` includes both logics  🤔

Comment (arthur791004) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: > But I'm not sure why it worked when I tested this change via Beta Tester (even before the last commit). 😅

I was also curious about this 😆

Comment (taipeicoder) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:177]: > Do we want to load any features on the frontend page of A4A sites?

Hmmm probably not. Can't think of any use case for it.

File: projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php [hunk 2]
```diff
@@ -206,6 +213,13 @@ public static function load_etk_features_flags() {
 	 * Can be moved back to load_features() once the feature no longer exists in the ETK plugin.
 	 */
 	public static function load_etk_features() {
+		// Don't load on agency sites.
+		if ( is_fully_managed_agency_site() ) {
+			return;
+		}
+
+		// Don't load if the user is not a wpcom user on WP Admin.
+		// The features is still required on the frontend page regardless of the user.
```
Comment (taipeicoder) [inline projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:222]: Could you give some example of such features?

**Review by taipeicoder — APPROVED** [review]
LGTM, left some questions.

File: projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php (hunk 2 above)
Comment (arthur791004) [reply projects/packages/jetpack-mu-wpcom/src/class-jetpack-mu-wpcom.php:222]: For example, we need to load the `view.js` for both `event-countdown` and `timeline` blocks. In addition, the `wpcom-global-styles` notices users to upgrade their site to apply global styles to visitors.
