### PR TITLE
Subscriptions: Fix Newsletter column width

### LINKED ISSUE #86161: Classic View: improve responsive view in /posts
The /pages _Classic View_ isn't very responsive.
This screenshot is 1440x900, and some columns are very difficult to read.

The _Title_ and the _Newsletter_ columns should expand more, and leave less room for _Categories_ and _Tags_.

Image

### PR DESCRIPTION
**Pull request by pkuliga**
Fixes https://github.com/Automattic/wp-calypso/issues/86161

## Proposed changes:

It:
- sets the Newsletter column width to 10% (the same width as the Author column)
- improves the performance a bit by not executing the Newsletter column-related code if it's not really needed

### Before

Screenshot 2024-01-18 at 10 58 18

### After

Screenshot 2024-01-18 at 10 57 57

<br>
<br>

The issue with the Title column is a Core thing and it's already reported:
https://core.trac.wordpress.org/ticket/52151

cc @crisbusquets 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Enable the Newsletter module
* Enable the Newsletter column for Posts by commenting out this check
https://github.com/Automattic/jetpack/blob/3a8e6a72096f80eb1cae425f6e483708bcfe0f66/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L151
* Shrink the window width making sure the Newsletter column is still readable

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 1]
```diff
@@ -213,6 +214,13 @@ function render_newsletter_access_rows( $column_id, $post_id ) {
 	}
 }
 
+/**
+ * Adds the Newsletter column styles
+ */
+function newsletter_access_column_styles() {
+	echo '<style id="jetpack-newsletter-newsletter-access-column"> table.fixed .column-newsletter_access { width: 10%; } </style>';
```
Comment (pkuliga) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:219]: Noticed that almost all inline styles have an id. Not sure if it's needed for admin but decided to add it.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 2]
```diff
@@ -174,7 +175,7 @@ function register_newsletter_access_column( $columns ) {
 	}
 
 	$position   = array_search( 'title', array_keys( $columns ), true );
-	$new_column = array( NEWSLETTER_COLUMN_ID => '<span>' . __( 'Newsletter', 'jetpack' ) . '</span>' );
+	$new_column = array( NEWSLETTER_COLUMN_ID => __( 'Newsletter', 'jetpack' ) );
```
Comment (pkuliga) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:176]: It seems the `span` wrapper is not needed.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 3]
```diff
@@ -149,6 +149,7 @@ function ( $allowed_meta ) {
 	// Add a 'Newsletter access' column to the Edit posts page
 	add_action( 'manage_post_posts_columns', __NAMESPACE__ . '\register_newsletter_access_column' );
 	add_action( 'manage_post_posts_custom_column', __NAMESPACE__ . '\render_newsletter_access_rows', 10, 2 );
+	add_action( 'admin_head', __NAMESPACE__ . '\newsletter_access_column_styles' );
```
Comment (simison) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php]: Note for future that we'll rename the label "Newsletter" to "Access", at which point it might make sense to rename functions to just `access_` without `newsletter_` as well.

**Comment by pkuliga** [comment]
One issue found with this PR, the styles will be added even when the Newsletter column is not visible. WDYT about moving this check:
https://github.com/Automattic/jetpack/blob/5488fa16aba06f7c81745817e45701a7bcb74612/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L171-L174
To the `register_block` like this:
```php
// Add a 'Newsletter access' column to the Edit posts page
// We only display the "NL access" column if we have published one paid-newsletter
if ( Jetpack_Memberships::has_configured_plans_jetpack_recurring_payments( 'newsletter' ) ) {
	add_action( 'manage_post_posts_columns', __NAMESPACE__ . '\register_newsletter_access_column' );
	add_action( 'manage_post_posts_custom_column', __NAMESPACE__ . '\render_newsletter_access_rows', 10, 2 );
	add_action( 'admin_head', __NAMESPACE__ . '\newsletter_access_column_styles' );
}
```
Thanks to that those actions will be added only if it's really needed.

**Comment by simison** [comment]
Yep, that sounds fine to me 👍 

I'll add Gold team as reviewers just as FYI, in case they wanna have a look. They worked on this originally.

**Comment by simison** [comment]
_"We only display the "NL access" column if we have published one paid-newsletter"_ comment in code doesn't sound exactly accurate, as it looks like we're checking if we've configured a paid newsletter plan — not if we've posted one post.

The check itself is correct.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php (hunk 3 above)
Comment (pkuliga) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php]: Sure, let's do it in the PR with changing the name, not here. Thanks!

**Comment by pkuliga** [comment]
> _"We only display the "NL access" column if we have published one paid-newsletter"_ comment in code doesn't sound exactly accurate, as it looks like we're checking if we've configured a paid newsletter plan — not if we've posted one post.

Fixed, thanks for spotting this!

**Comment by crisbusquets** [comment]
> The issue with the Title column is a Core thing and it's already reported:
https://core.trac.wordpress.org/ticket/52151

It looks like the last time that it was modified was 2 years ago.

This solution isn't great, but I understand it's the only we can do with what we have, so let's merge it!

**Review by n3f — APPROVED** [review]
LGTM
