### PR TITLE
Masterbar: remove Sites, Reader, and Account submenus

### LINKED ISSUE #7009: Masterbar: missing “Media” and “Feedback” options
The Calypso My Sites menu has “Media” and “Feedback” options while the Jetpack Masterbar does not.

screen shot 2017-04-19 at wed apr 19 6 43 19 pm
<sup>Seen at https://wordpress.com/pages/alittletestblog.com and http://alittletestblog.com/wp-admin/edit.php?post_type=page (click on My Sites) using Safari 10.1 on Mac OS X 10.12.4.</sup>

Tested with WordPress 4.7.3 and Jetpack Beta (Build 1736160) on WP Engine.

### LINKED ISSUE #7011: Masterbar: missing footer and linked help icon
The Calypso My Sites menu has an a footer with a linked help icon and Jetpack Masterbar does not.

screen shot 2017-04-19 at wed apr 19 6 58 05 pm
<sup>Seen at https://wordpress.com/settings/general/alittletestblog.com and http://alittletestblog.com/wp-admin/options-general.php (click on My Sites) using Safari 10.1 on Mac OS X 10.12.4.</sup>

Tested with WordPress 4.7.3 and Jetpack Beta (Build 1736160) on WP Engine.

### LINKED ISSUE #7642: WordPress.com Toolbar: Sign Out button is visible after signing out from WP.com
#### Steps to reproduce the issue

1. Enable WordPress.com Toolbar on your test Jetpack site.
2. Log out of WordPress.com.
3. Open up the `Me` (Profile) submenu.

#### What I expected

 - Sign Out button should not be visible or we should show an option to Log In instead.

#### What happened instead

- Sign Out button is still present.

### LINKED ISSUE #8038: Masterbar: Unable to use some features on touch device
#### Steps to reproduce the issue
Use a Windows computer (Chrome with touch features forced), or a mobile phone (Android/Chrome in this case)

To reproduce without a mobile device:
1. goto chrome://flags
2. set Touch Events API to Enabled from Automatic (this will send touch events instead of click events on pages that it would normally detect as non-touch friendly)
3. Then in Chrome dev tools, under sensors: set touch to be force enabled (mouse will turn into a circle instead of pointer when clicking on the page)

1. Visit wp-admin with wpcom Masterbar
2. The following features do not work:
  - Plan
 - Site Pages
 - Blog Posts
 - Comments
 - Themes
 - Sharing
 - People
 - Plugins
 - Settings
 - Switch Site

I should have just said that the only thing that works is Stats ...

#### What I expected
To navigate wp-admin from my mobile phone or touch screen

#### What happened instead
Unable to navigate

### LINKED ISSUE #8288: WordPress.com Toolbar: View Site no longer opens in a new tab
#### Steps to reproduce the issue

1. Use a test Jetpack site with WordPress.com Toolbar module enabled.
2. Navigate to any `wp-admin` page.
3. Open `My Sites` menu and click on `View Site` item.
4. Notice that the site's front end is loaded in the same browser tab. This should open up in a new tab (for reference compare with WP.com equivalent).

This is most likely caused by new analytics changes to the masterbar.
Please see https://github.com/Automattic/jetpack/pull/8275 for a similar issue/fix.

### LINKED ISSUE #9082: Issues with signing out from an Atomic front end in mobile (and Desktop) Safari
Currently, it is not possible to sign out on mobile Safari from the front end of an Atomic site. For a detailed description of the issue and investigation so far see p4k3M4-2qr-p2 (internal reference).

#### Steps to reproduce the issue

- Sign in on an Atomic site
- Navigate to the front end
- Try to sign out

#### What I expected

- Clicking the sign out button should log out the user

#### What happened instead

- Nothing happens when clicking the sign out button

### LINKED ISSUE #9098: Masterbar: Updates across Calypso, WP.com, and Jetpack versions
Following are screenshots of the different Masterbar menus across (left-right) Calypso, Jetpack site, WP.com (front-end or wp-admin). These are taken from a site with all custom post types enabled, and it's using the Canape theme which introduces the Food Menus CPT as well.

masterbar-my-sites
masterbar-reader
masterbar-me

There are a bunch of things going on here, so I'll try to make a checklist, but feel free to update it:

**My Sites**
- [ ] #7011 (Footer and Help Icon)
- [ ] "Switch Site" is capitalized, and uses a different arrow in WP.com and Jetpack
- [ ] Text/icon color (and size?) has been changed on Calypso, needs to be changed in Jetpack/WP.com
- [ ] No upgrade banner in Jetpack
- [ ] View Site link has a white background in Jetpack, but doesn't in Calypso (same in WP.com, although this screenshot doesn't show it because that link only appears within wp-admin)
- [ ] Stats sparkline on WP.com frontend, nowhere else?
- [ ] Media item is missing from Jetpack, see #7009
- [ ] Feedback item missing from Jetpack menu, again see #7009
- [ ] Portfolio & Testimonials items are in different order in Calypso vs Jetpack
- [ ] Food Menus CPT doesn't appear in Jetpack (does appear elsewhere)
- [ ] Food Menus (perhaps all CPTs?) don't have a (default) icon in WP.com
- [ ] Ads only appears in Calypso, not in Jetpack. I haven't confirmed if it appears in WP.com because I don't have a site there with Ads enabled
- [ ] Dashboard or WP Admin link does not appear in Calypso. See https://github.com/Automattic/wp-calypso/issues/21058

**Reader**
- [ ] Conversations item missing from Jetpack
- [x] Both Automattic-only menu items ("Automattic" and "A8C Conversations") missing from Jetpack, although we can ignore that one probably.
- [ ]  Recommendations appears in Jetpack, not in the others
- [ ] Lists and Tags appear only in Calypso

**Me**
- [ ] Gravatar is much bigger for Calypso than it is for either Jetpack or WP.com
- [ ] Notification Settings label is different in Calypso vs others
- [ ] Help item appears in Jetpack/WP.com, but not in Calypso

### LINKED ISSUE #11744: Masterbar: remove side navigation drawer
- Internal reference: p9Jlb4-ML-p2
- Related change on WordPress.com: D25769-code

In the Calypso Nav Drawer project, we've decided to completely remove the fake front-end menu that never gets updated. Instead we'll simply link folks to the stats section.

Here is the part that would disappear:

Screen Recording 2019-03-28 at 03 07 PM

For reference, you can view @apeatling's corresponding WP.com PR here: D25769-code

@dereksmart pointed me in the right direction. Apparently there is an optional setting in `/wp-admin/admin.php?page=jetpack#/writing` which shows the WP.com admin bar instead of the wp-admin one.

Derek also said that https://github.com/Automattic/jetpack/blob/master/modules/masterbar/masterbar.php would be a good place to start looking.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #11744

Closes #9098
Closes #9082
Closes #8288
Closes #8038
Closes #7642
Closes #7011
Closes #7009

#### Changes proposed in this Pull Request:

* Internal reference: p9Jlb4-ML-p2
* Related change on WordPress.com: D25769-code

The aim of this PR is to remove all drawer menus of the Masterbar, except for the Notifications.

Today, when you click on "My Site", "Reader", or on your avatar, a drawer menu opens up with sub-menus. This PR removes all those.

I also took that opportunity to fix all PHPCS warnings in the Masterbar module, and add it to the pre-commit hook.

#### Testing instructions:

* Go to Jetpack > Settings > Writing, and enable the "WordPress.com toolbar" feature.
* After refreshing, you should see the traditional masterbar, just like before:
image
* However, when clicking on any of the items you should be redirected to Calypso with no errors.

You can also take that opportunity to:

- Check for JavaScript errors on the page.
- Check if Tracks events are properly triggered when clicking on each link. You should see those events in your browser console after submitting `localStorage.setItem( 'debug', 'dops:analytics' );` to enable debugging tracks.
image

#### Follow-up:

- Once this is merged and shipped, and after a few versions so that we know that the majority of our userbase has updated, we should be able to update 2 things:
- `wp-content/mu-plugins/admin-bar/masterbar-overrides/masterbar.js` to remove unneeded elements.
- remove `wpcom_jetpack_masterbar_logout` on WordPress.com; it handles the sync of the log out event in the masterbar.

#### Proposed changelog entry for your changes:

* WordPress.com toolbar: simplify toolbar by removing drawer menus.

### CODE REVIEW

File: bin/pre-commit-hook.js [hunk 1]
```diff
@@ -29,14 +29,15 @@ function parseGitDiffToPathArray( command ) {
 function phpcsFilesToFilter( file ) {
 	// If the file path starts with anything like in the array below, it should be linted.
 	const whitelist = [
-		'_inc/lib/debugger/',
```
Comment (jeherve) [inline bin/pre-commit-hook.js]: There are a lot of changes here, but in fact I just reorganized the list alphabetically as it is getting longer and is easier to parse that way imo. I also added `'modules/masterbar/',`

File: modules/masterbar/masterbar.php [hunk 2]
```diff
@@ -77,31 +132,14 @@ function __construct() {
 		add_action( 'admin_enqueue_scripts', array( $this, 'remove_core_styles' ) );
 
 		if ( Jetpack::is_module_active( 'notes' ) && $this->is_rtl() ) {
-			// Override Notification module to include RTL styles
+			// Override Notification module to include RTL styles.
 			add_action( 'a8c_wpcom_masterbar_enqueue_rtl_notification_styles', '__return_true' );
 		}
-
-		add_action( 'wp_logout', array( $this, 'maybe_logout_user_from_wpcom' ) );
```
Comment (jeherve) [inline modules/masterbar/masterbar.php]: We don't need this anymore since you can't log out via the Masterbar anymore.

File: modules/masterbar/tracks-events.js [hunk 3]
```diff
@@ -1,66 +1,17 @@
 /*globals jQuery, JSON */
 ( function( $ ) {
-	var eventName = 'masterbar_click';
```
Comment (jeherve) [inline modules/masterbar/tracks-events.js]: All the changes in that file were made via Prettier.

File: sync/class.jetpack-sync-module-users.php [hunk 4]
```diff
@@ -55,7 +55,6 @@ public function init_listeners( $callable ) {
 		add_action( 'jetpack_wp_login', $callable, 10, 3 );
 
 		add_action( 'wp_logout', $callable, 10, 0 );
-		add_action( 'wp_masterbar_logout', $callable, 10, 0 );
```
Comment (jeherve) [inline sync/class.jetpack-sync-module-users.php]: No need to sync this anymore since there is log out option in the Masterbar anymore.

**Review by davemart-in — DISMISSED** [review]
LGTM! Thanks so much for tackling this @jeherve!

**Comment by jeherve** [comment]
Tests keep failing here, and I think it may be caused by #11550.

Here is an example of a failing test:

https://travis-ci.org/Automattic/jetpack/jobs/513087165

```
modules/masterbar/tracks-events.js
  line 3    col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 5    col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 14   col 5   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 47   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 58   col 13  'let' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 59   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 69   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 74   col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 93   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 98   col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 103  col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  ⚠  11 warnings
```

On the other hand, I can't just revert [my changes](https://github.com/Automattic/jetpack/pull/11766/commits/1ee7f9ef7ab780d93feeeda7b714f3e5cf27aeb0) because if I do so, the pre-commit hook stops me from committing:

```
husky > pre-commit (node v10.13.0)
Prettier formatting staged file: modules/masterbar/tracks-events.js
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/yannickcr/eslint-plugin-react#configuration .
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

jetpack/modules/masterbar/tracks-events.js
    3:2  error  Unexpected var, use let or const instead  no-var
    5:2  error  Unexpected var, use let or const instead  no-var
   14:2  error  Unexpected var, use let or const instead  no-var
   47:3  error  Unexpected var, use let or const instead  no-var
   58:4  error  Unexpected var, use let or const instead  no-var
   69:4  error  Unexpected var, use let or const instead  no-var
   74:4  error  Unexpected var, use let or const instead  no-var
   93:3  error  Unexpected var, use let or const instead  no-var
   98:3  error  Unexpected var, use let or const instead  no-var
  103:3  error  Unexpected var, use let or const instead  no-var

✖ 10 problems (10 errors, 0 warnings)
  10 errors and 0 warnings potentially fixable with the `--fix` option.

COMMIT ABORTED: The linter reported some problems. If you are aware of them and it is OK, repeat the commit command with --no-verify to avoid this check.
husky > pre-commit hook failed (add --no-verify to bypass)
```

@sirreal In https://github.com/Automattic/jetpack/pull/11507/files#diff-09da0d159e00b7be64d6cb64598a2069, how come the file wasn't automatically updated by Prettier to use `let` or `const` instead of `var`? How do you think I should move on with this?

**Comment by sirreal** [comment]
A reply in three parts 🙂:

In summary - jshint and eslint are serving different purposes and can't agree. The should exclusively:

- `eslint` -> `/_inc/client`, `extensions`, JS targetting `node` like webpack configuration.
- `jshint` -> js that's not in the `eslint` targets.

This is something that needs to happen, we can't continue using the same linters on all of the JavaScript in this repository.

---

`eslint` could probably apply changes that would resolve the `const` lints with `eslint --fix`, but the real problem is that `eslint` and `jshint` don't agree on what they're linting.

There are two different flavors of JavaScript in the Jetpack repository right now. That which is intended to be compiled into a bundle to be served to browsers, and that which is intended to be served directly without compilation.

I believe `jshint` is from the time when most or all of the code in Jetpack was shipped directly to browsers and still provides valuable information. By indicating that we're targetting `esversion: 5`, we exclude usage of things like `const`, which doesn't have [full support in browsers like ie11](https://kangax.github.io/compat-table/es6/#test-const). This also disallows `class`, `async/await`, `...spread`, and a variety of other syntaxes that aren't valid es5. This has value for these uncompiled files.

`eslint` as it is configured now is intended as a linter for modern JavaScript syntaxes that will be compiled by some tooling. This compilation includes a transformation that ensures our supported browsers will receive compatible syntax. Newer features will be transformed into a syntax that older browsers can understand.

---

To answer this specific question:

> @sirreal In https://github.com/Automattic/jetpack/pull/11507/files#diff-09da0d159e00b7be64d6cb64598a2069, how come the file wasn't automatically updated by Prettier to use `let` or `const` instead of `var`? How do you think I should move on with this?

Prettier is a formatter, so you'll see it changing things like indentation and quote types, but it will never change the abstract syntax tree. The following will be left [untouched by prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAJT7AA6U++AbgIYBO+AHvgLz4UgvcDcVGgBs4MfAE8OXEOP6D8kKAGcxALyndVcqAF8qIADQgIAB1zQlyUE0YQA7gAUmCSynq0IOACaGQAI0Z6MABrUQBlEyCcKABzZBhGdDgjAAsYAFshAHUUnHglSLA4MJc8nFo88WRwJUsjaKU4RhgHQJj0+mRUeiFGowArJRYAIUCQ8Pp0uAAZaLgunr6QQZYw6JiRAEV0CHgF3uSQSMZGxmq-ej9xIWhfE0ZomCzvGBTkAA4ABiN7iEaswImar3OCnWjzIyMOAAR3QOChrXo7U6SG6ByMjXSOHiiUOSnWWx2e1Ri0OMEuzy8r2QACYjAl6DghOsAMIQdIdapQaAQkDoRoAFUurjRjR0OiAA), although a linter would complain that all the declarations should be `const` (and removed because they're unused):

```js
function f() {
  var x = "x";
  let y = "y";
  const z = "z";
}
```

A bit about the difference between prettier and linters [here](https://prettier.io/docs/en/comparison.html).

**Comment by sirreal** [comment]
Did reverting the `const` changes fix the lint issues? (https://github.com/Automattic/jetpack/pull/11766/commits/5f8c300d0adcbf343e1bba824cb57a663a394884)

**Comment by sirreal** [comment]
> It fixed jshint, yup, but to do that commit I had to force things with git commit --no-verify.

🤔 I think we'll need to get away from sharing `.eslintignore` to ignore files for prettier and eslint.

File: bin/phpcs-whitelist.js [hunk 5]
```diff
@@ -8,7 +8,9 @@ module.exports = [
 	'functions.opengraph.php',
 	'_inc/lib/debugger/',
 	'_inc/lib/class.jetpack-password-checker.php',
+	'modules/masterbar/',
 	'modules/module-extras.php',
 	'modules/module-info.php',
 	'modules/theme-tools/social-menu/',
+	'sync/class.jetpack-sync-module-auth.php',
```
Comment (kraftbj) [inline bin/phpcs-whitelist.js]:
```suggestion
```

I believe this line needs to be removed. The file was removed and functions moved to the users module IIRC.

**Review by kraftbj — CHANGES_REQUESTED** [review]

**Review by kraftbj — APPROVED** [review]
