### PR TITLE
Business Hours block: provide defaults

### LINKED ISSUE #31533: Business Hours Block: Shows up while editing a page/post but it's not published
User reached us in #11315817-hc, they added a Business hours block. It's showing up on the preview but it's not showing up on the site. I was able to replicate the issue in my test site, which is using a different Theme.

#### Steps to reproduce
1. Starting at URL: https://machomestaging.com/contact-us
2. Edit the Page by using Gutenberg.
3. Add Business hours block.
4. Publish your changes.

#### What I expected
Business hours block should appear on the page.

#### What happened instead
It is not showing up, but it does show up on the edition page.

I replicated the steps in my test site and they're not showing up on there too.

Editor view:
Captura de pantalla 2019-03-18 a las 15 06 48

Page view:
Captura de pantalla 2019-03-18 a las 15 09 29

### PR DESCRIPTION
**Pull request by roccotripaldi**
Fixes https://github.com/Automattic/wp-calypso/issues/31533

#### Changes proposed in this Pull Request:

The editor portion of the Business Hours block provides defaults to make the editor experience work before any attributes are set.  If folks try to preview the block before configuring them, the front end is blank, because the front end doesn't have any default attributes.

This PR remedies that by using the same defaults that the editor uses.

#### Testing instructions:

- Spin up a Jurassic.ninja site using [this link](https://jurassic.ninja/create/?jetpack-beta&branch=fix/business-hours-block-defaults)
- Set-up Jetpack
- Start a new post, and add a business hours block
- Before making any changes to the block, click "Preview"
- Ensure the preview looks like you'd expect

#### Proposed changelog entry for your changes:

* Fixes a bug in the Business Hours block when blocks with the default attributes failed to appear on the front end

### CODE REVIEW

**Comment by enejb** [comment]
I tested this and it worked as expected. Nicely done. 
It fixed the error for me. I was able to replicate the error as well and test that this PR fixes as described.

I wonder it it would make sense to split the code up into a class with static methods? 
So this might also help with any future development. 

Instead of introducing another function. 

I think the change can be done in a different PR as well.

File: extensions/blocks/business-hours/business-hours.php [hunk 1]
```diff
@@ -20,11 +68,11 @@
  *
  * @return string
  */
-function jetpack_business_hours_render( $attributes, $content ) {
```
Comment (jeherve) [inline extensions/blocks/business-hours/business-hours.php]: Since you are removing this parameter, you'll want to update the docblock as well.

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to work well. I only have one minor comment

**Comment by roccotripaldi** [comment]
D25713-code was deployed this morning in r-189110-wpcom

**Review by jeherve — APPROVED** [review]
This should be all set now. 👍
