### PR TITLE
Testimonial CPT: Confirm get_current_screen exists

### LINKED ISSUE #7955: CPT: Fatal error when using Front End Editor
When using the Front End Editor feature plugin, a fatal is thrown due to us assuming the `enter_title_here` filter will only run within wp-admin

Fatal error: Uncaught Error: Call to undefined function get_current_screen() in 
/public_html/wp-content/plugins/jetpack-dev/modules/custom-post-types/testimonial.php:371 
Stack trace: #0 
/public_html/wp-includes/class-wp-hook.php(288): 
Jetpack_Testimonial->change_default_title('Enter title her...') #1 
/public_html/wp-includes/plugin.php(203): 
WP_Hook->apply_filters('Enter title her...', Array) #2 
/public_html/wp-content/plugins/wp-front-end-editor/class-fee.php(242): 
apply_filters('enter_title_her...', 'Enter title her...', Object(WP_Post)) #3 
public_html/wp-includes/class-wp-hook.php(286): 
FEE->register_scripts('') #4 
public_html/wp-includes/class-wp-hook.php(310): 
WP_Hook->apply_filters(NULL, Array) #5 
public_html/wp-includes/plugin.php(453): 
WP_Hook->do_action(Array) #6 in 
public_html/wp-content/plugins/jetpack-dev/modules/custom-post-types/testimonial.php 
on line 371 

Reported by beta tester in 722002-zen

### PR DESCRIPTION
**Pull request by kraftbj**
In front end editing situations, `get_current_screen` may not be available. If it isn't, return the title without modification.

Fixes #7955

#### Testing instructions:

* Using the Front End Editor feature plugin, confirm no fatals when the testimonial CPT is active.

#### Proposed changelog entry for your changes:
Compatibility fix when using Testimonials and a front-end editing plugin

### CODE REVIEW

File: modules/custom-post-types/testimonial.php [hunk 1]
```diff
@@ -368,6 +368,9 @@ function updated_messages( $messages ) {
 	 * Change ‘Enter Title Here’ text for the Testimonial.
 	 */
 	function change_default_title( $title ) {
+		if ( ! function_exists( 'get_current_screen' ) ) {
```
Comment (eliorivero) [inline modules/custom-post-types/testimonial.php]: All this function could be replaced with
```php
if ( self::CUSTOM_POST_TYPE == get_post_type() ) {
    $title = esc_html__( "Enter the customer's name here", 'jetpack' );
}
return $title;
```
I tested this in wp-admin only (01:21 am) but I'm confident it will work in front end as well because `get_post_type` is defined in `post.php` which is always loaded (in `wp-settings.php`, unless it's a SHORTINIT which is not the case here) so we would avoid checking that the function exists, getting the screen object, and finally using the property of the screen object. Since we're only interested in knowing that the current post type is `testimonial`, we can use this function.

**Comment by keoshi** [comment]
@kraftbj Did you see @eliorivero comment above? Let me know if there's anything I can do to move this PR forward. Thanks!

**Comment by brbrr** [comment]
Functionality tested - fatal gets fixed after applying this change. Tested on Jurassic.ninja using [this](https://wordpress.org/plugins/wp-front-end-editor/) plugin. It worth to mention that after installing that plugin I started to see these warning on my site:

image
