### PR TITLE
Forms: Fix form submissions across pages that have pagination applied

### LINKED ISSUE #41334: Form Block: Only the first form works if multiple forms have page breaks in between
### Impacted plugin

Jetpack

### Quick summary

If a page has more than one form with page-breaks in between, only the first form works. Subsequent forms will only send (if anything) a blank copy of the first form.

### Steps to reproduce

1. Start with ~a Simple~ any site on WP.com
2. Create a page and add two forms, preferably with different fields so the issue is more obvious, and don't make fields required
3. Add a page-break between them, then publish and view the page
4. Fill out and submit each form, then look at the email / feedbacks
5. Notice the email/feedback for the second form is blank. If first form has required fields, it may not go through at all.

### Editor View
Image
(I had to make these not required, or it wouldn't go through at all)

### Filling in the second form
Image

### Feedback  shows as a blank copy of the first form

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

It works fine without page breaks.

Also, for now, it works fine on Atomic.

### Platform (Simple and/or Atomic)

Simple

### PR DESCRIPTION
**Pull request by enejb**
Fixes https://github.com/Automattic/jetpack/issues/41334

Currently if you create a page and split it up using the  block or code. 
Forms on pages other then the first one will not work. See issue #41334. 

## Proposed changes:
* Add a hidden page field that lets the form know what page we are on. 
* Update the links that appear in the email as well as the form reponses linking to the correct page form. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
no 

## Testing instructions:

* Load this PR. 
* Create a page with multiple pages.
* Place forms across multiple pages. 
* Notice that you are able to submit each of the posts across the different pages.

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-contact-form.php [hunk 1]
```diff
@@ -1645,6 +1651,21 @@ public function process_submission() {
...
+	 * return string The permalink for the post ID.
+	 */
+	public static function get_permalink( $post_id ) {
+		$url  = get_permalink( $post_id );
+		$page = isset( $_POST['page'] ) ? sanitize_text_field( wp_unslash( $_POST['page'] ) ) : null; // phpcs:Ignore WordPress.Security.NonceVerification.Missing
+		if ( $page ) {
+			return add_query_arg( 'page', $page, $url );
+		}
+		return $url;
+	}
```
Comment (edanzer) [inline projects/packages/forms/src/contact-form/class-contact-form.php:1672]: Would absint() be better to sanitize $_POST['page'] if we assume its always a positive integer? Same question above in line 704 in class-contact-form-plugin.php.

Comment (enejb) [reply projects/packages/forms/src/contact-form/class-contact-form.php:1672]: Good call!

File: projects/packages/forms/src/contact-form/class-contact-form.php [hunk 2]
```diff
@@ -364,7 +366,7 @@ public static function parse( $attributes, $content ) {
 			 * @param $post $GLOBALS['post'] Post global variable.
 			 * @param int $id Contact Form ID.
 			 */
-			$url                     = apply_filters( 'grunion_contact_form_form_action', "{$url}#contact-form-{$id}", $GLOBALS['post'], $id );
+			$url                     = apply_filters( 'grunion_contact_form_form_action', "{$url}#contact-form-{$id}", $GLOBALS['post'], $id, $page );
```
Comment (edanzer) [inline projects/packages/forms/src/contact-form/class-contact-form.php:369]: Was trying to figure out if changing the number of parameters on this filter would cause any backward compatibility issues, but I think it's moot because as far as I can tell, the filter isn't used anywhere...

File: projects/packages/forms/src/contact-form/class-contact-form-plugin.php [hunk 3]
```diff
@@ -699,8 +699,16 @@ public function process_form_submission() {
...
 			// Process the content to populate Contact_Form::$last
 			if ( $post ) {
+				if ( str_contains( $post->post_content, '<!--nextpage-->' ) ) {
+					$postdata = generate_postdata( $post );
+					$page     = isset( $_POST['page'] ) ? sanitize_text_field( wp_unslash( $_POST['page'] ) ) : null; // phpcs:Ignore WordPress.Security.NonceVerification.Missing
+					$paged    = isset( $page ) ? $page : 1;
+					$content  = $postdata['pages'][ $paged - 1 ];
+				} else {
+					$content = $post->post_content;
+				}
```
Comment (edanzer) [inline projects/packages/forms/src/contact-form/class-contact-form-plugin.php:723]: Not sure if we need any extra checks on any of this? ie, to confirm generate_postdata doesn't return false or $postdata['pages'] is defined or $postdata['pages'][ $paged - 1 ] gives a valid page value?

**Review by edanzer — DISMISSED** [review]
I duplicated the original issue on trunk, and confirmed that the issue is fully resolved with this PR. Forms on paginated posts now submit accurately. 

The code changes seem to make sense. Added a few notes. I still lack some context on the surrounding code and logic, and was trying to think through backwards compatibility issues or edge cases in how pagination works. I can't identify specific concerns other than those I've already commented on.

File: projects/packages/forms/src/contact-form/class-contact-form.php (hunk 2 above)
Comment (enejb) [reply projects/packages/forms/src/contact-form/class-contact-form.php:369]: It shouldn't cause any issue. 
I am mostly including it so that folks using the filter can better take care of this use case in case they want to.

**Comment by enejb** [comment]
@edanzer Can you take another look? I addressed all the issue you found. :)

File: projects/packages/forms/src/contact-form/class-admin.php [hunk 4]
```diff
@@ -774,7 +780,7 @@ public function grunion_manage_post_column_response( $post ) {
 			echo '<div class="feedback_response__item-value">' . esc_html( $content_fields['_feedback_ip'] ) . '</div>';
 		}
 		echo '<div class="feedback_response__item-key">' . esc_html__( 'Source', 'jetpack-forms' ) . '</div>';
-		echo '<div class="feedback_response__item-value"><a href="' . esc_url( get_permalink( $post->post_parent ) ) . '" target="_blank" rel="noopener noreferrer">' . esc_html( get_permalink( $post->post_parent ) ) . '</a></div>';
+		echo '<div class="feedback_response__item-value"><a href="' . esc_url( $url ) . '" target="_blank" rel="noopener noreferrer">' . esc_html( $url ) . '</a></div>';
```
Comment (edanzer) [inline projects/packages/forms/src/contact-form/class-admin.php:776]: I think changes in this file are new since last time I reviewed. Good to include. Links under Feedback now link to the correct page where the form submission originated.

File: projects/packages/forms/src/contact-form/class-contact-form.php (hunk 1 above)
Comment (edanzer) [reply projects/packages/forms/src/contact-form/class-contact-form.php:1672]: Not sure what convention is - I often like avoiding creating method names that exactly match built in WP methods. If that's a concern, could update this. Not a biggie though - it's already in a class and is always called with that class.

**Review by edanzer — DISMISSED** [review]
Retested and still working great. Issues addressed. Good addition to update links in the Feedback list so they go to right page.

File: projects/packages/forms/src/contact-form/class-contact-form.php [hunk 5]
```diff
@@ -123,7 +123,7 @@ public function __construct( $attributes, $content = null ) {
 			if ( ! isset( $attributes['id'] ) ) {
 				$attributes['id'] = '';
 			}
-			$attributes['id'] = $attributes['id'] . '-' . ( count( self::$forms ) + 1 );
+			$attributes['id'] = $attributes['id'] . '-' . ( count( self::$forms ) + 1 ) . '-' . $page;
```
Comment (lezama) [inline projects/packages/forms/src/contact-form/class-contact-form.php:126]: page isn't an object here? should we use `https://developer.wordpress.org/reference/functions/get_the_id/` instead?

Comment (enejb) [reply projects/packages/forms/src/contact-form/class-contact-form.php:126]: `$page` is a WP global that is a number and tells WP that page to show.

**Comment by simison** [comment]
rebased

**Review by simison — DISMISSED** [review]
Did a basic test, and this seems to work well:

- Two forms separated by a page break
- Two forms on a single page without page break
- Three forms, first and 2nd separated by page break
    image

Everything submits correctly and multiple forms appearing on the same page get individual IDs.

I noticed that when two forms are separated by page break, first from on both pages gets ID by page ID `id="contact-form-950"`, i.e. there are two forms with the same ID on the "same page", just separated by the page break. Not an issue now and things still work as we intended, but this just highlights how we need to later [work on true unique IDs.](https://github.com/Automattic/jetpack/pull/40998#issuecomment-2594796355)

Correct source URL shows up in the email as well:

Screenshot 2025-02-04 at 13 14 21

**Comment by simison** [comment]
This `entry_page` appearing in the form response looks like it doesn't belong. It can be removed entirely, or if needed, it could be moved to "meta" section:

Screenshot 2025-02-04 at 10 58 32

In the classic view, I don't see it:

Screenshot 2025-02-04 at 10 59 26

I do see it in the export:

image

**Comment by enejb** [comment]
Good catch on the `entry_page` will work on removing this from the export and the new field.

**Comment by enejb** [comment]
@simison  Can you take another look when you have the chance. Thank you!

**Review by simison — APPROVED** [review]
Tests well now!
