### PR TITLE
VideoPress: fix setting title when uploading video file

### LINKED ISSUE #28070: VideoPress: propagate title attribute when uploading a new video
The video Title is not propagated correctly to the block attribute. Although the in-sync process takes over it, it would be better if it's immediately propagated to the block.

Image

### PR DESCRIPTION
**Pull request by retrofox**
This PR fixes the issue that happens when trying to set the video title when uploading the file. 

It got super complex since the implementation of setting the poster and uploading the title and the sync media process aren't aligned with the same idea.

Although these changes fix the issue and, in my opinion, it works well, we might need to rethink how the data is propagated among all components.

Additionally, it improves the way to update the video poster by running a sync request for it, reducing the time the user needs to wait to start using the block settings.

Fixes https://github.com/Automattic/jetpack/issues/28070

## Proposed changes:

* VideoPress: fix setting title when uploading video file

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor
* Create a new video instance

### Setting only the poster
* Select a frame to use for the video poster
* Wait until the `Done` button is enabled
* You can take a look at the network tab and check how the client performs a request to update the poster
* Click on the `Done` button
* Confirm everything works as expected 

### Setting only the title
* Edit the video title
* Wait until the `Done` button is enabled
* Click on the `Done` button
* Confirm everything works as expected 

### Setting Title and poster
* Select a frame to use for the video poster and edit the video title
* Wait until the `Done` button is enabled
* Click on the `Done` button
* Confirm everything works as expected

### CODE REVIEW

File: projects/packages/videopress/src/client/block-editor/blocks/video/components/videopress-uploader/uploader-progress.js [hunk 1]
```diff
@@ -104,27 +106,32 @@ const usePosterAndTitleUpdate = ( { setAttributes, attributes, onDone } ) => {
...
+		if ( ! guid ) {
+			return;
+		}
+
+		if ( videoPosterImageData ) {
+			return sendUpdatePoster( { poster_attachment_id: videoPosterImageData?.id } );
+		}
+
+		// Check if videoFrameMs is not undefined or null instead of bool check to allow 0ms. selection
+		if ( 'undefined' !== typeof videoFrameMs && null !== videoFrameMs ) {
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/block-editor/blocks/video/components/videopress-uploader/uploader-progress.js:126]: `videoFrameMs == null` checks for `null` and `undefined`.

**Review by dhasilva — APPROVED** [review]
Working as intended here :rocket:
