### PR TITLE
Fix type error for image array

### LINKED ISSUE #26106: Setting "fallback_to_avatars" for top-posts widget results in type error
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install jetpack plugin running on WordPress site with PHP version >= 8.0.
2. Set top-posts widget or shortcode on the page.
3. Go to theme's functions.php or a plugin.
4. use a filter hook `jetpack_top_posts_widget_image_options` to disable fallback gravatar option.
5. Try to open the top posts page.

### A clear and concise description of what you expected to happen.

By default, top posts set the fallback gravatar for the posts that do not have a featured image. There is filter hook `jetpack_top_posts_widget_image_options` that can be used to disable the fallback image. Disabling fallback images using the above hook should not display fallback images for the posts without featured images.

### What actually happened

Disabling the default fallback image using filter hook results in a type error with PHP 8.0 or higher.

For PHP versions lower than 8.0,  Instead of hiding the image tag, there is a broken image tag without a src value.

### Browser

Google Chrome/Chromium

### Other information

Error message:
```
Uncaught TypeError: Cannot access offset of type string on string in /wordpress/plugins/jetpack/11.3/modules/widgets/top-posts.php:422
```

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

- Add a check for array index/key before accessing the value.
- Remove broken image tag when image fallback is disabled and post does not have featured image set.

### PR DESCRIPTION
**Pull request by sagarnasit**
Fixes #26106

#### Changes proposed in this Pull Request:
* Fix type error for PHP version >= 8.0

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Install Jetpack plugin on WordPress installation with PHP version >= 8.0
* Use top posts and page widget or shortcode on page.
* Disable image fallback with `jetpack_top_posts_widget_image_options` hook.
```
add_filter( 'jetpack_top_posts_widget_image_options', function( $image_options ) {
	$image_options['fallback_to_avatars'] = false;

	return $image_options;
} );
```

### CODE REVIEW

**Review by anomiex — COMMENTED** [review]
Thanks for contributing!

While this looks like it will work, I think we could make it more semantically clearer by checking if `$image` is falsey before running any of the subsequent code in the loop, instead of adding `isset()` checks for each property.

If you want to go a step further, you could also improve the docs and return values of `Jetpack_PostImages::get_image()` and `Jetpack_PostImages::get_images()` as I mentioned in https://github.com/Automattic/jetpack/issues/26106#issuecomment-1240715073.

**Comment by sagarnasit** [comment]
Thank you for the suggestions @anomiex 
I have made some changes to the return values and added a check before showing the image.

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 1]
```diff
@@ -419,9 +419,13 @@ public function widget( $args, $instance ) {
 							'avatar_size'         => (int) $get_image_options['avatar_size'],
 						)
 					);
-					$post['image'] = isset( $image['src'] ) ? $image['src'] : null;
-					if ( isset( $image['from'] ) && 'blavatar' !== $image['from'] && 'gravatar' !== $image['from'] ) {
-						$post['image'] = jetpack_photon_url( $post['image'], array( 'resize' => "$width,$height" ) );
+
+					if ( ! empty( $image ) ) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php]: `! empty()` does two things, it's basically `isset( $image ) && $image`. But we already know `$image` is set, so we don't need the first bit (and, in fact, it could accidentally hide it if you typoed to `$imgae` or something). Better to just do like
```suggestion
					if ( $image ) {
```

(sorry, this is one of my pet peeves)

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 2]
```diff
@@ -454,15 +458,17 @@ public function widget( $args, $instance ) {
...
-						printf(
-							'<a href="%1$s" title="%2$s" class="bump-view" data-bump-view="tp"%3$s><img width="%4$d" height="%5$d" src="%6$s" alt="%2$s" data-pin-nopin="true"/></a>',
-							esc_url( $filtered_permalink ),
-							esc_attr( wp_kses( $post['title'], array() ) ),
-							( get_queried_object_id() === $post['post_id'] ? ' aria-current="page"' : '' ),
-							absint( $width ),
-							absint( $height ),
-							esc_url( $post['image'] )
-						);
+						if ( ! empty( $image ) ) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php]: This change doesn't really work. You're testing whatever `$image` was left at at the end of the loop, not the image for this particular post.

Here you'll want to do something like
```suggestion
						if ( isset( $post['image'] ) ) {
```
to check that the image got set on this post.

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 3]
```diff
@@ -489,20 +495,26 @@ public function widget( $args, $instance ) {
 						/** This filter is documented in modules/widgets/top-posts.php */
 						$filtered_permalink = apply_filters( 'jetpack_top_posts_widget_permalink', $post['permalink'], $post );
 
+						if ( ! empty( $image ) ) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php]: Same as above.
```suggestion
						if ( isset( $post['image'] ) ) {
```

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 4]
```diff
@@ -802,8 +814,8 @@ public function get_posts( $post_ids, $count, $types = array( 'post', 'page' ) )
  */
 function jetpack_do_top_posts_widget( $instance ) {
 	// Post Types can't be entered as an array in the shortcode parameters.
-	if ( isset( $instance['types'] ) && is_string( $instance['types'] ) ) {
-		$instance['types'] = explode( ',', $instance['types'] );
+	if ( isset( $instance['types'] ) && is_array( $instance['types'] ) ) {
+		$instance['types'] = implode( ',', $instance['types'] );
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php]: What's going on here?

File: projects/plugins/jetpack/modules/widgets/top-posts.php (hunk 1 above)
Comment (sagarnasit) [reply projects/plugins/jetpack/modules/widgets/top-posts.php]: Thanks for the suggestion @anomiex . I have updated all the $image references.

File: projects/plugins/jetpack/modules/widgets/top-posts.php (hunk 2 above)
Comment (sagarnasit) [reply projects/plugins/jetpack/modules/widgets/top-posts.php]: Fixed variable reference.

File: projects/plugins/jetpack/modules/widgets/top-posts.php (hunk 4 above)
Comment (sagarnasit) [reply projects/plugins/jetpack/modules/widgets/top-posts.php]: I reverted unwanted changes. Can be ignored now.

**Review by anomiex — APPROVED** [review]

**Comment by anomiex** [comment]
Thanks! Merged!
