### PR TITLE
Search package: allow auto config add search input for block themes

### LINKED ISSUE #22611: Search: Auto-configuration does not add search input for block-based themes
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Spin up a WordPress site using a block-based theme, like 2022. Ensure that it has no widget areas.
2. Connect Jetpack and purchase a Jetpack Search subscription for the site.

### A clear and concise description of what you expected to happen.

For a search control to be added to the header (button?) or the footer (input?).

### What actually happened

Neither. The Search module and Instant Search functionality were enabled. However, it was impossible to invoke the Search overlay without a valid search input on the page.

### Other information

Reported here: 
p8oabR-Nm-p2#comment-5987

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #22611

#### Changes proposed in this Pull Request:
Added functionality to add search input for block-based themes. 

<strike>The search input is added above footer and on the 3rd columns of three. If you think there's a better place to put it, let me know. 😄 As suggested by @gibrown, I moved the search block just below header:</strike>

After some internal and external discussions (please refer to the comments of the PR), we decided to add the search block in the footer. For one it's pretty obvious to notice and for two it doesn't disturb users too much.

- Not to add search block if there's already search block(s).

- Try to get the content of footer template and parse it. 
    - If there are columns in the footer, the code would try to append the search block to the first column.

image

    - If there's no columns, the code would try to add the search block to the inner group.

image

- Some templates has block patterns in templates, the code would replace them before doing changes described above.

- If there are not groups or columns then the template is not touched.

Note: the replacement is not recursive, considering to minimize the risk. The `auto_config` command is updated to work with the patch.
 

#### Jetpack product discussion
pcNPJE-Cx-p2
p1644361560289179-jetpack-search-backstage-slack

#### Does this pull request change what data or activity we track or use?
no

##### Test on JN
* Create a JN site with WP 5.9 and apply a block theme .e.g. [twentytwentytwo](https://wordpress.org/themes/twentytwentytwo/) (allows FSE)
* Purchase JP search product
* Ensure a search input is added in footer and looks reasonable
* Ensure it summons search overlay on input

#### Test on your local
- Ensure you have a instant search enabled
- Switch to a clean block theme ( I tested twentytwentytwo, alara, stewart )
- Run command `jetpack docker wp jetpack-search auto_config`
- Ensure search block is added in footer and looks reasonable
- Ensure PHP tests pass: `( cd projects/packages/search && composer test-php )`
- Please test more block themes if you could

##### how to test on JN
- Open JN special Ops, create a site with the following parameters:
image
- Connect the site with a WPCOM user
- Purchase a JP Search plan

### CODE REVIEW

**Comment by gibrown** [comment]
> If you think there's a better place to put it, let me know.

Why not in the menu bar or header? They just purchased it, seems like we should add it in the most obvious/prominent place on the site for providing the best end user UX.

**Comment by kangzj** [comment]
> Why not in the menu bar or header?  @gibrown 

I like the idea. Changed. Thanks

**Review by jsnmoon — COMMENTED** [review]
The code appears to work as described, but I'm not sure if adding a brand new row beneath the first header row is a good idea. Here's how this looks for the `Richmond` FSE theme:

<table>
<tr>
<td>Before
<td>After
<tr>
<td>
Screen Shot 2022-02-03 at 5 33 02 PM
<td>
Screen Shot 2022-02-03 at 5 33 09 PM
</table>

Furthermore, it looks like the added group block might be malformed?
> Screen Shot 2022-02-03 at 5 41 43 PM

---

Might I recommend a different, dual-pronged approach? 
1. If the header has a "navigation" block (like 2022), add a "custom link" block with the class name `jetpack-instant-search__open-overlay-button` for spawning the search overlay.
    - The custom link block could probably point to `#`.
    - We'll likely want to keep the link text short for reduced visual impact (e.g. `Search`).
    - A link button is probably more appropriate here, but I don't believe `button` blocks are valid children of `navigation` blocks.
    - If there is no navigation block, ignore the header.

2. Insert a new group block at the bottom of the footer, with a default search block as its only child.
    - The group block could be configured to justify items to the right.

What do you think? Also pinging @jeffgolenski, just in case :)

**Comment by kangzj** [comment]
Hi @jsnmoon thanks for your feedback and the possible solutions 👍 

IMO the main point of auto config / adding the search block is to give a user starting point. There are countless themes out there, I guess we wouldn't be able to cover them all. What I'm thinking is possibly we could just put **a center aligned search block below header**?

Would be great to hear some feedback from @jeffgolenski too.

**Comment by annacmc** [comment]
It's working well for me, awesome job! 🙌 

I'm also curious to see what Jeff (or anyone from design) thinks too. Is it possible for a user to remove it and place it elsewhere with FSE? It looks like it is, but also when I try to open the site/header editor I get an error with the block content:

image

Although, when I try to remove the block, it does allow it. 

On its own, that's okay. It all still works as expected, and if you 'attempt block recovery' it seems to fix it okay, but maybe it's not the nicest user experience and people may assume something is broken. 

Another suggestion thing to consider - is it too complex to build an icon in like twenty twenty one theme? I suspect from what I know of things it may be too much, but something to think about more so for mobile than for web. Because on mobile, the search field takes up a lot of the header currently. Which some people might like, and I do agree because they can remove it themselves, it's not a huge deal. But an idea to contemplate: 


| Twenty Twenty | Twenty Twenty Two |
| ------------- | ------------- |
| image | image |

**Comment by kangzj** [comment]
> Furthermore, it looks like the added group block might be malformed? @jsnmoon @annacmc 

This should be fixed now.

Changed the 3 columns layout to one, looking good actually:

Desktop:
image

Mobile:
image

> Is it possible for a user to remove it and place it elsewhere with FSE?  @annacmc 

I think this is possible, I could move the search block around or delete it.

**Comment by kangzj** [comment]
You could add to `init_hooks` for easier tests:
```PHP
add_action( 'init', array( $this, 'set_filters_from_widgets' ) );
```

File: projects/packages/search/src/instant-search/class-instant-search.php [hunk 1]
```diff
@@ -400,6 +400,63 @@ public function auto_config_overlay_sidebar_widgets() {
 
 		update_option( $widget_opt_name, $widget_options );
 		update_option( 'sidebars_widgets', $sidebars );
+
+		if ( \current_theme_supports( 'block-templates' ) ) {
+			$this->add_search_block_below_header();
+		}
```
Comment (jsnmoon) [inline projects/packages/search/src/instant-search/class-instant-search.php:406]: Could we move this into `auto_config_search`?

**Review by jsnmoon — CHANGES_REQUESTED** [review]
I'm wary of a potential backlash from our customers, given how significantly it disrupts the existing header design. In addition, [none of the top themes for WordPress include a search form in the header, let alone a second navigation row](https://wordpress.org/themes/); the closest I've seen might be [the 2020 theme](https://wordpress.org/themes/twentytwenty/) which included a Search button on the far right corner of the header navigation. Because of this, I don't feel comfortable approving this change even though it works as described.

Several plugins, such as WooCommerce, add navigation items upon plugin activation. Could we consider doing the same during our search auto-configuration for adding a simple "Search" link? If we must add a search input, could we add a full-width one in the footer instead of the header?

**Comment by kangzj** [comment]
> They just purchased it, seems like we should add it in the most obvious/prominent @gibrown 

Hi @jsnmoon, I initially placed the search input just above the footer. And @gibrown suggested above, which I think makes sense, so moved it below header. The point of doing this is _to make search work out of the box and to give the user a starting point_.

>given how significantly it disrupts the existing header design. @jsnmoon 

However I think your concern stands, because users might purchase Search for their well established websites. In that case, adding the search input to places like that would be disruptive of course.

I lean more to adding it below the header, because when user purchased a product, they'd expect something magic to happen. And user could move the search input anywhere they like or just remove it. However I feel comfortable to add it in footer as well. But I guess neither way is perfect and users best be provided a choice. IMO a setup guide would be an ideal solution or providing user options on purchase page ( not sure if this is doable ).

Loop in @brbrr who first raised the issue. 

cc @bluefuton

File: projects/packages/search/src/instant-search/class-instant-search.php (hunk 1 above)
Comment (kangzj) [reply projects/packages/search/src/instant-search/class-instant-search.php:406]: I put the logic here because search widget is added to theme sidebar in the same function. I refactored the way it works in https://github.com/Automattic/jetpack/pull/22632, where there would be a function for it. And it'll be placed [there](https://github.com/Automattic/jetpack/pull/22632/files#diff-eb54b635de49fca2ee1cdee9bf5ef2015d5eb056ce51338a313f7512a629c01dR364).

**Comment by kangzj** [comment]
Since we didn't get any feedback from the pings and @jsnmoon and I agreed a full width search input above footer would work, I'll progress the PR towards that.

**Comment by kangzj** [comment]
The PR is getting very much more complex than anticipated. But fortunately, another day is well spent. Could you please have a look again @jsnmoon and @Automattic/jetpack-search ? Thanks heaps

File: projects/packages/search/src/instant-search/class-instant-search.php [hunk 2]
```diff
@@ -402,6 +408,137 @@ public function auto_config_overlay_sidebar_widgets() {
...
+		if ( ! function_exists( 'get_block_template' ) ) {
+			return null;
+		}
+		$active_theme     = \wp_get_theme()->get_stylesheet();
+		$template_part_id = "{$active_theme}//{$template_part_name}";
+		$teplate_part     = \get_block_template( $template_part_id, 'wp_template_part' );
+		if ( is_wp_error( $teplate_part ) || empty( $teplate_part ) ) {
+			return null;
+		}
+		return $teplate_part;
```
Comment (jsnmoon) [inline projects/packages/search/src/instant-search/class-instant-search.php:489]:
```suggestion
		$template_part     = \get_block_template( $template_part_id, 'wp_template_part' );
		if ( is_wp_error( $template_part ) || empty( $template_part ) ) {
			return null;
		}
		return $template_part;
```

Typo 🙂

File: projects/packages/search/src/instant-search/class-instant-search.php [hunk 3]
```diff
@@ -402,6 +408,137 @@ public function auto_config_overlay_sidebar_widgets() {
...
+		return $controller->update_item( $request );
+	}
+
+	/**
+	 * Replace pattern blocks with their content.
+	 * We don't want to replace recursively for the sake of simplicity.
+	 *
+	 * @param string $block_content - Content of template part.
+	 */
+	protected function replace_block_patterns( $block_content ) {
```
Comment (jsnmoon) [inline projects/packages/search/src/instant-search/class-instant-search.php:442]: I don't think I quite understand what this function is doing. What does replacing pattern blocks with their content do for us here?

**Review by jsnmoon — COMMENTED** [review]
Read through the code once more and left some questions inline. Will give this PR another round of smoke testing tomorrow!

File: projects/packages/search/src/instant-search/class-instant-search.php (hunk 3 above)
Comment (kangzj) [reply projects/packages/search/src/instant-search/class-instant-search.php:442]: For some templates ( e.g. twentytwentytwo ), the footer  consists of block patterns like:
```
<!-- wp:group {"style":{"spacing":{"padding":{"top":"var(--wp--custom--spacing--large, 8rem)"}}},"layout":{"inherit":true}} -->
<div class="wp-block-group" style="padding-top:var(--wp--custom--spacing--large, 8rem)">
<!-- wp:pattern {"slug":"twentytwentytwo/footer-default"} /-->
</div>
<!-- /wp:group -->

```

The function is to find every block pattern and replace them with the actual content, so that we could find the perfect place to insert the search block. This is also what happen if user edit the block.

File: projects/packages/search/src/class-cli.php [hunk 4]
```diff
@@ -32,4 +34,23 @@ public function auto_config() {
 			WP_CLI::error( $e->getMessage() );
 		}
 	}
+
+	/**
+	 * Choose a admin user and set it.
+	 */
+	protected function set_admin_user() {
+		$user = get_user_by( 'ID', 1 );
```
[the remark this answers is not in the document]
Comment (kangzj) [reply projects/packages/search/src/class-cli.php:40]: I feel uncomfortable about doing this too tbh. There's somewhere in WP to create post to store the altered template part. When doing that, the current user is used to be the author of the post - if we don't set a current user, the post would be invisible due to some relationships not set ( template part belongs to which theme etc ) . 
Since it's CLI, I don't think there's a way to get the current user. Luckily the code could only be run from WPCLI, meaning it should only be run by a user privileged enough. 

The reason I prefer to use ID 1 is that if anything magic needs to be done, I would rather impersonate an initial admin.

Any suggestions appreciated, thanks.

[the remark this answers is not in the document]
Comment (kangzj) [reply projects/packages/search/src/class-cli.php:40]: Absolutely good question btw.

File: projects/packages/search/src/instant-search/class-instant-search.php (hunk 3 above)
Comment (kangzj) [reply projects/packages/search/src/instant-search/class-instant-search.php:446]: You could look at the input/output from its test: https://github.com/Automattic/jetpack/pull/22613/files#diff-1e0b7c3a5ac0caab76d82f0b747c1fa627d8ee203f62d53afd375567f3c1be66R229

File: projects/packages/search/src/class-cli.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (kangzj) [reply projects/packages/search/src/class-cli.php]: Now the CLI would require a user ID or login to run 3e87dff.

File: projects/packages/search/src/instant-search/class-instant-search.php (hunk 3 above)
Comment (jsnmoon) [reply projects/packages/search/src/instant-search/class-instant-search.php:446]: Excellent explanation, thank you!

File: projects/packages/search/src/class-cli.php [hunk 5]
```diff
@@ -19,15 +20,47 @@ class CLI extends WP_CLI_Command {
...
+			$ret = $this->set_user( $args[0] );
+			if ( is_wp_error( $ret ) ) {
+				WP_CLI::error( $ret->get_error_message() );
+			}
+
+			WP_CLI::line( 'Running as user ' . $ret->user_login . '…' );
 			$blog_id = Helper::get_wpcom_site_id();
 			Instant_Search::instance( $blog_id )->auto_config_search();
-			WP_CLI::line( 'Jetpack Search: auto config success!' );
+			WP_CLI::success( 'Auto config success!' );
```
Comment (jsnmoon) [inline projects/packages/search/src/class-cli.php:44]: Something for the future: It'd be nice if the CLI were more verbose about what it's doing in the future. It'd be nice if it printed something along these lines, for example:

> Auto-configuring Jetpack Search...
> - Search module is **already enabled**.
> - Instant Search **enabled**.
> - The theme sidebar **already contains a Jetpack Search widget**, ignoring.
> - The overlay sidebar has been **initialized with a Jetpack Search widget**.

**Review by jsnmoon — DISMISSED** [review]
Looks good and works well! I'd be lying if I said the regex in the Instant Search class didn't scare me, but it feels like an appropriate solution here.

🚢 🚢 🚢

**Comment by jsnmoon** [comment]
Heads up: It looks like the `Lock files are up to date` linting check is currently failing.

**Comment by kangzj** [comment]
Hi @jsnmoon Thanks for your speedy review. I think something weird is happening with the versions & locks where `tools/fixup-project-versions.sh` and `tools/composer-update-monorepo.sh --root-reqs "projects/plugins/jetpack"` wouldn't fix. 

Hi @Automattic/jetpack-crew do you have any insight on this please? Thanks

**Review by jeherve — APPROVED** [review]
This tests well for me. I have one remark, but this can be addressed in a follow-up PR I think.

File: projects/packages/search/src/instant-search/class-instant-search.php [hunk 6]
```diff
@@ -402,6 +409,143 @@ public function auto_config_overlay_sidebar_widgets() {
...
+		return preg_match( '/(<!--\swp:search\s[^>]*-->)/i', $block_content ) > 0;
+	}
+
+	/**
+	 * Append Search block to block if no 'wp:search' exists already.
+	 *
+	 * @param {string} $block_content - the content to append the search block.
+	 */
+	public static function inject_search_widget_to_block( $block_content ) {
+		$search_block = '<!-- wp:search {"label":"Jetpack Search","buttonText":"Search"} /-->';
```
[the remark this answers is not in the document]
Comment (kangzj) [reply projects/packages/search/src/instant-search/class-instant-search.php:532]: will address that in a following PR thanks

[the remark this answers is not in the document]
Comment (kangzj) [reply projects/packages/search/src/instant-search/class-instant-search.php:532]: Followup PR: https://github.com/Automattic/jetpack/pull/23049
