### PR TITLE
SSO: Show wp-admin login form if site has local users

### LINKED ISSUE #39037: SSO on dotcom: Allow Local Users to Access AT Sites Without Being Logged into wp.com
### Impacted plugin

Jetpack

### Quick summary

When a local user tries to log into a WordPress.com, they are required to sign up for WordPress.com and log in first.

**The only exception is Classic Interface sites**, where users can visit /wp-admin and log in without logging into WordPress.com

This is a significant departure from the dotorg experience and can be extremely confusing. I would argue that Local users should be able to access any AT sites (Classic or Default) without the need to log into WordPress.com first.

More context in p1724253856166289-slack-C048CUFRGFQ and pc4f5j-4IL-p2where

### Steps to reproduce

1. Create a Local Users on a Default Interface Site (example.com)
2. Open an incognito window, visit example.com/wp-admin 
3. Notice how you are redirected to https://wordpress.com/log-in and asked to login there first. 

### A clear and concise description of what you expected to happen.

Visiting example.com/wp-admin should work out of the box on ALL Atomic sites.

### What actually happened

I got redirected to dotcom and the credentials I had been given did not work
Screenshot 2024-08-22 at 20 14 03

### Impact

All

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/39037

## Proposed changes:

Stops enforcing the WP.com login for Atomic sites with local users.

Before | After
--- | ---
Screenshot 2024-08-29 at 16 15 27 | Screenshot 2024-08-29 at 16 16 32

Previously, we were disabling the enforced WP.com login on sites with the classic interface (except for users coming from Calypso), and kept it on sites with the default interface.

However, sites with the default interface can have local users as well (users not connected to WP.com) who are unable to use their wp-admin credentials to log in into wp-admin.

This PR fixes that by changing who is enforced to log in with a WP.com account:

- Sites without local users:
  - WP.com login, always.
- Sites with local users:
  - If user comes from Calypso: WP.com login
  - Otherwise: Jetpack SSO login, so they can decide whether to use a WP.com account or a local account.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
pc4f5j-4Ky-p2

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
- Install Jetpack Beta on a WoA dev site
- Open Jetpack Beta and activate the branch of this PR in the WordPress.com Site Helper plugin (`wpcomsh`).
- Go to https://wordpress.com/settings/general and select your WoA dev site
- Activate the default admin interface
- Go to `/wp-admin/users.php`
- Create a new local user (**do not invite the user to WP.com**)
- Open an incognito/private window
- Go to `/wp-admin`
- Make sure the Jetpack SSO login form shows up which allows you to use either a WP.com account or a local account
- Go to wordpress.com
- Log in
- While in Calypso, switch to your WoA dev site
- Click on any menu that links to wp-admin (e.g. Settings > Media)
- Make sure you're automatically logged in
- Close the incognito/private window
- Remove all the local users from your site
- Open an incognito/private window
- Go to `/wp-admin`
- Make sure you're redirected to the WP.com login
- Close the incognito/private window
- Activate the classic admin interface now
- Repeat the steps above and confirm that you get the same results

### CODE REVIEW

**Review by dsas — APPROVED** [review]
Works nicely

File: projects/plugins/wpcomsh/wpcomsh.php [hunk 1]
```diff
@@ -217,26 +217,37 @@ function wpcomsh_jetpack_sso_auth_cookie_expiration( $seconds ) {
...
+	);
+	if ( in_array( wp_get_referer(), $calypso_domains, true ) ) {
+		return true;
+	}
+
+	if ( class_exists( '\Automattic\Jetpack\Connection\Manager' ) ) {
+		$connection_manager = new \Automattic\Jetpack\Connection\Manager( 'jetpack' );
+		$users              = get_users( array( 'fields' => array( 'ID' ) ) );
+		foreach ( $users as $user ) {
+			if ( ! $connection_manager->is_user_connected( $user->ID ) ) {
```
Comment (obenland) [inline projects/plugins/wpcomsh/wpcomsh.php:245]: How does this perform for large sites? > 10k users?

Comment (mmtr) [reply projects/plugins/wpcomsh/wpcomsh.php:245]: Good question! I have no idea 😅 I'll see if there is an easy way to populate a test site with 10k fake users and check

Comment (mmtr) [reply projects/plugins/wpcomsh/wpcomsh.php:245]: I'd say though that if a site has 10k users, it's very likely that most of them will be non-connected, and we'll stop the loop when the first one is found.

Comment (mmtr) [reply projects/plugins/wpcomsh/wpcomsh.php:245]: Used FakerPress to create 5k users (not connected to WP.com) on a site:

Screenshot 2024-09-04 at 11 22 11

It seems that the performance is not largely affected in this scenario.

Before, it took 1.34s to show the Jetpack SSO login. Now, it takes 1.53s

Before | After
--- | ---
Screenshot 2024-09-04 at 11 24 03 | Screenshot 2024-09-04 at 11 22 51

Comment (BogdanUngureanu) [reply projects/plugins/wpcomsh/wpcomsh.php:245]: Imo, that's just one scenario. If 4.9k users are connected there would be a higher performance penalty. This has an O(n) complexity.
