### PR TITLE
Super cache: check that is_utf8_charset exists

### LINKED ISSUE #38358: WP Super Cache: call to undefined function is_utf8_charset() in WordPress 6.6
### Impacted plugin

Super Cache

### Quick summary

Update to WordPress 6.6 gives `Call to undefined function is_utf8_charset()` error when Super Cache enabled.

I'm unable to share a URL due to company policy.

### Steps to reproduce

1. Visit site with Super Cache enabled and updated to WordPress 6.6.

### A clear and concise description of what you expected to happen.

Blog homepage should display

### What actually happened

Error shown (see below)

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Disabling the cache removes the error but is far from ideal.

Error message shown (I've blanked out the path):

```
Fatal error: Uncaught Error: Call to undefined function is_utf8_charset() in /----------/wp-includes/compat.php:179
Stack trace:
#0 /----------/wp-includes/compat.php(152): _mb_strlen('<!DOCTYPE html>...', '8bit')
#1 /----------/wp-content/plugins/wp-super-cache/wp-cache-phase2.php(268): mb_strlen('<!DOCTYPE html>...', '8bit')
#2 /----------/wp-content/plugins/wp-super-cache/wp-cache-phase1.php(194): wp_cache_serve_cache_file()
#3 /----------/wp-content/advanced-cache.php(22): include_once('/----------/...')
#4 /----------/wp-settings.php(97): include('/----------/...')
#5 /----------/wp-config.php(102): require_once('/----------/...')
#6 /----------/wp-load.php(50): require_once('/----------/...')
#7 /----------/wp-blog-header.php(13): require_once('/----------/...')
#8 /----------/index.php(17): require('/----------/...')
#9 {main} thrown in /----------/wp-includes/compat.php on line 179
```

### PR DESCRIPTION
**Pull request by donnchawp**
WP 6.6 changed around where is_utf8_charset is defined and if you had compression enabled and didn't have the mbstring extension installed in your webserver then you'd get an error that is_utf8_charset was missing.
This PR adds a check for that along with the mb_strlen check.

Fixes #38358

## Proposed changes:

* Add function_exists() check on is_utf8_charset when using mb_strlen in the function that serves a cache file.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1721227781401669-slack-C016BBAFHHS

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

1. Enable compression in the advanced settings page.
2. Disable the mbstring extension in your webserver.
3. Make sure you're using WP 6.6.
4. Load a page twice and you'll see an error saying is_utf8_charset is undefined.
5. Load this PR or branch and repeat.
6. The cached page should be served now.

### CODE REVIEW

File: projects/plugins/super-cache/wp-cache-phase2.php [hunk 1]
```diff
@@ -265,7 +265,7 @@ function wp_cache_serve_cache_file() {
 			} else {
 				header( 'Cache-Control: max-age=3, must-revalidate' );
 			}
-			$size = function_exists( 'mb_strlen' ) ? mb_strlen( $cachefiledata, '8bit' ) : strlen( $cachefiledata );
+			$size = ( function_exists( 'mb_strlen' ) && function_exists( 'is_utf8_charset' ) ) ? mb_strlen( $cachefiledata, '8bit' ) : strlen( $cachefiledata );
```
Comment (dmsnell) [inline projects/plugins/super-cache/wp-cache-phase2.php:268]: Might be nice to add a note here about being a hotfix for a temporary issue in Core.

**Review by dmsnell — APPROVED** [review]

File: projects/plugins/super-cache/wp-cache-phase2.php (hunk 1 above)
Comment (donnchawp) [reply projects/plugins/super-cache/wp-cache-phase2.php:268]: Good idea.
