### PR TITLE
Search: avoid search query on component mount

### LINKED ISSUE #22231: Instant Search: search for default results should not always happen on page load
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Go to https://meyerbees.com/product/honey-bee-advent-calendar-12-day-sampler/
2. Inspect the API requests in your browser console. Note that the Jetpack search endpoint has been requested.
3. Inspect the HTML markup and look for `jetpack-instant-search__overlay`. Note that search results have been fetched. If there are images present they may have been loaded (see https://github.com/Automattic/jpop-issues/issues/7204).

### A clear and concise description of what you expected to happen.

Instant Search does not make any API requests or load any images before the overlay is in use.

### What actually happened

Instant Search makes an API request (and potentially some image requests) on every page load.

### Other information

Screen Shot 2022-01-06 at 09 59 42
Screen Shot 2022-01-06 at 09 59 26

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #22231

#### Changes proposed in this Pull Request:
The PR removes search API call on component loaded except for Customberg, and `getResults` still gets called by `onChangeQueryString` on all occasions.

<strike>It also fixed an when overlay is closed, search api is called again.</strike>

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Go to a site with a Search subscription and Instant Search enabled
* Open a frontend page
* Ensure no requests made to `https://public-api.wordpress.com/rest/v1.3/sites/xxx/search`
* Ensure Instant Search load as expected with parameter `?s=hello`
* Ensure Instant Search works
* Ensure Customberg works

### CODE REVIEW

**Review by jsnmoon — DISMISSED** [review]
Works as described. The original reason for performing this request upon mounting no longer appears applicable.

Filters continue to work correctly with these changes.

File: projects/packages/search/src/instant-search/components/search-app.jsx [hunk 1]
```diff
@@ -189,7 +186,10 @@ class SearchApp extends Component {
 	showResults = this.toggleResults.bind( this, true );
 
 	onChangeQueryString = isHistoryNav => {
-		this.getResults();
+		// `null` means the searchQuery is reset or not initialized.
+		if ( this.props.searchQuery !== null ) {
+			this.getResults();
+		}
```
Comment (jsnmoon) [inline projects/packages/search/src/instant-search/components/search-app.jsx:192]: This appears to prevent the search overlay from fetching results when only filter values are defined (e.g. `/?category=classic`).

Comment (kangzj) [reply projects/packages/search/src/instant-search/components/search-app.jsx:192]: @jsnmoon good catch. ah right... let me think..

Comment (kangzj) [reply projects/packages/search/src/instant-search/components/search-app.jsx:192]: @jsnmoon I'll reverse the change and leave it for the params to be reviewed all tegether. Thanks

Comment (jsnmoon) [reply projects/packages/search/src/instant-search/components/search-app.jsx]: Sounds good to me — let's do a holistic review of all the parameters in the future.

**Review by jsnmoon — APPROVED** [review]
