### PR TITLE
Instant Search: Improve history navigation handling, open results in current window

### LINKED ISSUE #18455: Search: open the search result in the same tab/window
We are currently opening the search results in separate tabs. We've had some requests to open in the same window, and @jeffgolenski thinks that behavior would be better.

### LINKED ISSUE #18555: Instant Search: 'Search' button in Twenty Twenty One theme does not trigger the modal
#### Steps to reproduce the issue

1. Activate the Twenty Twenty One theme.
2. Enter a search query in the footer search box. The modal appears.
3. Close the modal with the 'X' button.
4. Try clicking the 'Search' button to resubmit your search.

#### What I expected

The modal opens when I click 'Search'.

#### What happened instead
Nothing happened.

**Screenshots**

Screen Shot 2021-01-27 at 14 05 00

### LINKED ISSUE #18667: Instant Search: existing filter and sort selections are not re-populated to query string
#### Steps to reproduce the issue

1. Go to a site with Instant Search set up. Type a search string to open the search modal.
2. Click on a filter in the modal sidebar (for example: "2021" in a year filter). Notice that the filter selection is reflected in the query string: `/?s=dog&year_post_date=2021-01-01 00%3A00%3A00`
3. Close the modal with the close icon or Esc key.
4. Reopen the modal.

#### What I expected
When I reopen the modal, my filter is still selected, and the query string reflects what filter I have chosen.

#### What happened instead
When I reopen the modal, my filter is still selected, but the query string has been cleared. This means I can't share my exact results with someone else by copy and pasting the URL, or bookmark them for later.

Discovered while working on #18462.

**Screenshots**

Filter selected:

Screen Shot 2021-02-02 at 16 44 28

Browser address bar:

Screen Shot 2021-02-02 at 16 44 35

### LINKED ISSUE #18701: Jetpack Search: "Back" browser navigation doesn't always work
#### Steps to reproduce the issue

1. Start on a non-search page, like `/`.
2. Enter a query into a search input. Ensure that an overlay appears.
3. Close the search overlay via the close button on the top right (`X`).
4. Press "Back" on your browser.

#### What I expected
The search overlay re-appears with the requisite search query and filters.

#### What happened instead
Nothing. Only the location bar query string was updated.

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes https://github.com/Automattic/jetpack/issues/18455.
Fixes #18555.
Fixes #18701.
Fixes #18667.
Fixes 1250-gh-Automattic/p2.

#### Changes proposed in this Pull Request:

* Open search results in the current tab rather than opening a new tab with `target="_blank"`.
* Fixes integration with browser history navigation (back/forward). For example, if you search without a query, click a result link, then hit back, the search overlay will now reappear.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
On a site with Instant Search enabled, ensure that search result links all open in the same window (including image links). When you press the back button, the search modal should be redisplayed, even if you did not originally specify a search query.

On a site with a search modal trigger (like Twenty Twenty), make sure that the search modal opens with the URL `/?s=`. Make sure this is removed when the modal is closed.

Screen Shot 2021-01-27 at 14 07 09

#### Proposed changelog entry for your changes:

* Instant Search: open search result links in the current window rather than opening a new one.
* Instant Search: improves compatibility with browser forward/back navigation.

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx [hunk 1]
```diff
@@ -142,7 +146,7 @@ class SearchApp extends Component {
 	};
 
 	hasActiveQuery() {
-		return this.props.searchQuery !== '' || this.props.hasFilters;
+		return this.props.searchQuery !== '' || this.props.hasFilters || hasSearchQueryStringKey();
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:149]: Could we push `hasSearchQueryStringKey` into the Redux state?

I'd like for us to refrain from directly accessing `window.location` so we can rely purely on Redux as the source of truth. (I'm okay having `getResultFormat` in the component for the time being since it's just a temporary measure.)

**Review by jsnmoon — DISMISSED** [review]
Works as described, but I'm concerned about storing state in two places (Redux and `window.location`).

Could we figure out a way to store `hasSearchQueryStringKey` in the Redux state? We might even be able to get some unit tests out of it.

**Comment by bluefuton** [comment]
Pretty happy with the approach now. An empty `?s=` parameter denotes "launch the search experience with no query".

Todo: 
- [ ] check how this affects filtering and sorting started from outside the modal (filter widgets) - do we need to add `s=` to the query string in these situations?

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx (hunk 1 above)
Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx]: Working on it 👍 

I tried having a separate boolean in state and it got complicated - had to keep it in sync with the searchQuery and the modal open/closed state. After a bit of tinkering, I found the best answer was to throw away all my code and keep it simple:

`searchQuery` === null - search closed
`searchQuery` === '' - search open without a query

...so I've made some changes to handle the `null` value for the search query.

**Comment by bluefuton** [comment]
While working on this I discovered that filters are not re-populated to the query string when you close and re-open the modal. Reported in https://github.com/Automattic/jetpack/issues/18667.

**Comment by bluefuton** [comment]
Todo:
- [ ] fix tests (`searchQuery Reducer › defaults to an empty string`)

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx [hunk 2]
```diff
@@ -218,19 +219,25 @@ class SearchApp extends Component {
 	showResults = () => {
 		this.setState( { showResults: true } );
 		this.preventBodyScroll();
+
+		// If we've arrived via a filter or sort only, make sure the search query is set
+		if ( this.props.searchQuery === null ) {
+			this.props.setSearchQuery( '' );
+		}
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:226]: What happens if we omit this? Design-wise, I think omitting this search query mutation would make `showResults` easier to understand. 

If we need to set the search query to `''` due to filter or sort changes, I think we might want to implement that in the Redux state with corresponding reducer tests.

Additionally, we might want to add null query value handling to [`generateApiQueryString`](https://github.com/Automattic/jetpack/blob/fix/open-search-results-in-same-tab/projects/plugins/jetpack/modules/search/instant-search/lib/api.js#L188), since the API doesn't seem to handle `null` query values very well:
```js
	if ( query === null ) {
		query = '';
	}
```

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx [hunk 3]
```diff
@@ -218,19 +219,25 @@ class SearchApp extends Component {
...
 	};
 
-	onChangeQueryString = () => {
+	onChangeSearchQuery = () => {
 		this.getResults();
 
-		if ( this.hasActiveQuery() && ! this.state.showResults ) {
+		if ( this.props.searchQuery !== null && ! this.state.showResults ) {
 			this.showResults();
 		}
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:242]: Why did we have to split `onChangeQueryString` into two functions? Doesn't the new `hasActiveQuery` also perform this check?

If the `searchInputSelector` update is the issue, I think we can gate it behind a `this.props.searchQuery !== null` conditional.

**Review by jsnmoon — COMMENTED** [review]
Works as described, with some questions noted below in-line.

**Comment by jsnmoon** [comment]
I am commandeering this PR so that we can deliver the bugfixes from #18788 in a single release.

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx (hunk 2 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx]: Resolved in the latest code update.

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx (hunk 3 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx]: Resolved in the latest code update.

**Comment by bluefuton** [comment]
The query string and modal open/close all look good, but the latest changes seem to break the back button for me in Firefox:

**Comment by jsnmoon** [comment]
> The query string and modal open/close all look good, but the latest changes seem to break the back button for me in Firefox

This was caused by a new bug I'd accidentally introduced by modifying the clear filters action. It should now be [fixed](https://github.com/Automattic/jetpack/pull/18462/files#diff-5e158a91caffbbe74e5d6a27e81a265f75f7e318a0125fcd4c37c739ecb2b2e6R159)!

**Comment by bluefuton** [comment]
The basic back button behaviour is now working well. The result opens in the same window, and when I hit back I get the same results in the opened modal. Great!

I noticed one bit of filtering oddness. If you start at:

`/?s=dog`

...then click a filter (like Year = 2021), you lose the current search query in the input, but it remains in the query string.

**Comment by jsnmoon** [comment]
> I noticed one bit of filtering oddness. If you start at: `/?s=dog`
> ...then click a filter (like Year = 2021), you lose the current search query in the input, but it remains in the query string. (@bluefuton)

This was caused by the search query reducer's special handling of setFilter and setSort actions. I've refactored our store as well as SearchApp, removed the search query reducer's special handling, and added additional tests.

**Review by bluefuton — COMMENTED** [review]
Excellent! Works as expected now and retains query, sort and filtering when back button is used ✅

**Review by jeherve — DISMISSED** [review]
This tests well for me. 🚢

**Comment by jsnmoon** [comment]
While smoke testing these changes before merging, I discovered a bug that can be reproduced as follows:

- Navigate to `/` using the 2021 theme.
- Press the "Search" button next to the search input. The URL correctly updates to `/?s=` and opens the overlay.
- Press back on your browser. The URL correctly updates to `/`, but doesn't close the overlay.

This bug was caused by improperly handling the default sort in two places: the `initializeQueryValues` effects handler and the `getSort` selector. I went ahead and fixed this issue by determining the default sort value exclusively within the `getSort` selector via 8f4a19d0016f9af2516bfe2fe1f5d420f1b3f221.

**Review by jeherve — APPROVED** [review]
Still tests well for me. Merging this now. I'll let you handle the WordPress.com counterpart.

**Comment by jsnmoon** [comment]
Thanks @jeherve! Deployed in r221552-wpcom.
