### PR TITLE
Stats: Insist on a WP_Post when trying to fetch a post ID

### LINKED ISSUE #15582: Stats: Modernize Stats Footer Post ID
The stats footer inserts the post ID if this conditional matches true:
`if ( $wp_the_query->is_single || $wp_the_query->is_page || $wp_the_query->is_posts_page ) {`
but then inserts the post ID based on:
`$post = $wp_the_query->get_queried_object_id();`

There could exist situations where something matches those conditional but the queried ID is different.

We could likely make this more error-proof.

#### Steps to reproduce the issue

1. Based on the linked JPOP Issue. I'm not terribly sure how to get a Woo Product Category to think it is a page yet. Reading through the code, though, we probably can improve.

#### What I expected
Only insert the post ID if it is a page, post, or a CPT individual item.

#### What happened instead
It inserted a term_id instead.

**Screenshots**
n/a

### PR DESCRIPTION
**Pull request by anomiex**
#### Changes proposed in this Pull Request:

It's completely unclear what might be happening in #15582 or how it
might be reproduced. But some static analysis (see the issue) seems to
indicate that Stats wants a WP_Post object and not anything else, so
perhaps we can cut the spaghetti knot and just check for that class
directly in Stats.

Also, since phpcs is making me touch the surrounding lines anyway for
alignment of `=`, remove some extraneous parens and throw in some
try-finally logic to make it a little more robust.

Fixes #15582

#### Jetpack product discussion

None I'm aware of.

#### Does this pull request change what data or activity we track or use?

It stops incorrectly reporting a term ID as a post ID in some existing tracking. Instead "0" will be used, as for other cases where no post ID is available.

#### Testing instructions:

* Check that normal posts still have the post ID in the Stats footer as they did before.
* If you can figure out how to reproduce what was going wrong in #15582, check that that's fixed now too.

#### Proposed changelog entry for your changes:

* If this is worth mentioning, maybe "Stats: No longer incorrectly report a term ID as a post ID in some rare cases."

### CODE REVIEW

File: modules/stats.php [hunk 1]
```diff
@@ -221,11 +221,15 @@ function stats_build_view_data() {
...
-		$queried_object_id = ( isset( $wp_the_query->queried_object_id ) ) ? $wp_the_query->queried_object_id : null;
-		$post = $wp_the_query->get_queried_object_id();
-		$wp_the_query->queried_object = $queried_object;
-		$wp_the_query->queried_object_id = $queried_object_id;
+		$queried_object    = isset( $wp_the_query->queried_object ) ? $wp_the_query->queried_object : null;
+		$queried_object_id = isset( $wp_the_query->queried_object_id ) ? $wp_the_query->queried_object_id : null;
+		try {
+			$post_obj = $wp_the_query->get_queried_object();
+			$post     = $post_obj instanceof WP_Post ? $post_obj->ID : '0';
+		} finally {
```
Comment (kraftbj) [inline modules/stats.php:229]: Just for my own edification. You're using the `try/finally` block here to effectively reset the `$wp_the_query->queried_object` to the state before the `try` block, ensuring that running `get_queried_object` doesn't change it and cause other odd behavior?

**Review by kraftbj — APPROVED** [review]
Approving it, but with one question for my own edification.

File: modules/stats.php (hunk 1 above)
Comment (anomiex) [reply modules/stats.php:229]: Yes. The existing code was intending to do that already, but would fail to do so if an exception was thrown. I don't know if the called code _can_ throw an exception, but especially given PHP's move towards throwing Error objects it's probably good to account for the possibility.
