### PR TITLE
Jetpack button: fix width and alignment settings

### LINKED ISSUE #38779: Form Block: Align right Contact Form button is not displayed properly in editor
### Impacted plugin

Jetpack

### Quick summary

I wish the "Submit" contact form button to be aligned right. When I set the alignment right, its positioned is not affected in the editor, i.e. it still appears left aligned. However, if I save the changes and go to preview my site on the frontend the button is right aligned there. 

### Steps to reproduce

1. In the block editor add a Form block, and chose the **Contact Form** pattern.
2. In the block editor, select the submit button block and try to right align it, using the block's settings.

### A clear and concise description of what you expected to happen.

Button should become right aligned in the editor, and on the frontend of the site.

### What actually happened

Button remains left aligned in the editor, but is actually right aligned on the fronted of the site (when we save with the alignment set to right).

In the editor:
Screenshot 2024-08-08 at 11 11 16

On the frontend:
Screenshot 2024-08-08 at 11 12 26

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by monsieur-z**
Resolves https://github.com/Automattic/jetpack/issues/38779

Setting the width and alignment of a `jetpack/button` block doesn't work consistently, depending on how it is integrated with its parent block and whether we're in the editor or site frontend.

For instance, in a Form block, setting the button width to 50% in the editor shrinks it instead of making it half the container's width, which is what you'd expect from a user's perspective.
Screenshot 2025-01-16 at 3 32 57 PM

In a Mailchimp block, trying to align the button (to the right in the capture below) doesn't work.
Screenshot 2025-01-16 at 3 33 08 PM

The following blocks use the `jetpack/button` block and show one or both faulty behaviors we've highlighted: 
- Form
- Premium Content
- Mailchimp
- Calendly
- Eventbrite
- Recipe
- Recurring Payments/Payment Button
 
The AI Assistant might as well, though I haven't been able to experience it.

## Proposed changes:

To address that, this PR does two things in the `jetpack/button` block:

1. It removes a class-less `div` from the markup generated by the block
Screenshot 2025-01-16 at 3 37 38 PM

This `div` prevents the flexbox layout applied to `.block-editor-block-list__layout` from working as intended.

2. It applies the selected width to `.wp-block-button` instead of `.wp-block-button__link`.

Indeed, [this Gutenberg PR ](https://github.com/WordPress/gutenberg/pull/64770) forces `.wp-block-button__link` to have a width of 100%, breaking the width settings behavior.

Furthermore, the PR also updates the blocks consuming `jetpack/button` so the width and alignment settings work as expected. Here are some caveats:
- Setting the width or alignment of `jetpack/button` in the Recipe block doesn't work as one would expect, given the width is relative to the grid items of the block. Solving this should be part of a broader discussion.
- Similarly, aligning the `jetpack/button` of a Form is confusing when it's not in its row. It deserves a separate discussion too.
- The alignment of buttons in a similar row is not implemented (Premium Content and Recurring Payments blocks). Again, this should be a separate concern.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Do not checkout this branch just yet
- Spin up a test Jetpack site
- Create a new post
- Add the following blocks:
  - Form
  - Premium Content
  - Mailchimp
  - Calendly
  - Eventbrite
  - Recurring Payments/Payment Button.
- You'll need to connect various accounts. It's not worth adding the Recipe block (see caveat above)
- For Calendly and Eventbrite, select the view that renders a submit button (in the sidebar)
- Apply this PR
- Refresh the post in the editor
- Verify you're not seeing any block compatibility issues in the UI
- Set a width on all submit buttons
- Verify they're rendered with the proper width in both the editor and front end
Screenshot 2025-01-17 at 4 03 09 PM
Screenshot 2025-01-17 at 4 03 13 PM
Screenshot 2025-01-17 at 4 03 17 PM
Screenshot 2025-01-17 at 4 03 20 PM
Screenshot 2025-01-17 at 4 03 22 PM
Screenshot 2025-01-17 at 4 03 27 PM

- Play with the buttons' alignment
- Verify the alignment is correct in both the editor and front end, except for the Premium Content and Recurring blocks (see caveat above).
- Verify this works with a simple site too

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/button/edit.js [hunk 1]
```diff
@@ -90,6 +84,5 @@ export function ButtonEdit( props ) {
 }
 
 export default compose(
-	withColors( { backgroundColor: 'background-color' }, { textColor: 'color' } ),
-	applyFallbackStyles
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/button/edit.js:94]: `applyFallbackStyles` uses the `withFallbackStyles` high order component from `@wordpress/components`, which renders the unwanted extra div (at [this line](https://github.com/WordPress/gutenberg/blob/0016e8318ed0b2dd79063f56fd774b7389852e98/packages/components/src/higher-order/with-fallback-styles/index.tsx#L90)). The code suggests we could get rid of that extra div by specifying a `node` prop, but it's unclear to me what node we could pass at that stage.

In the following discussion, not using `applyFallbackStyles` was hinted by several persons: p1736773641027939/1736360651.812989-slack-C052XEUUBL4. I do think it's the way to go as well. As far as I can tell, what `applyFallbackStyles` does is make the default background and text colors available to `ButtonEdit`. Yet eventually, those two colors are passed to the `ContrastChecker` component, which doesn't render a warning when the contrast ratio is too low to be deemed accessible.

File: projects/packages/forms/src/blocks/contact-form/editor.scss [hunk 2]
```diff
@@ -52,6 +52,10 @@
 			flex: 0 0 100%;
 			margin: 0;
 
+			&.wp-block-jetpack-button {
+				flex-basis: auto;
```
Comment (monsieur-z) [inline projects/packages/forms/src/blocks/contact-form/editor.scss:57]: Overwrite the `100%` value. We want to be able to set the width through the button styling options in the editor.

File: projects/plugins/jetpack/extensions/blocks/button/button.php [hunk 3]
```diff
@@ -226,7 +220,7 @@ function get_button_wrapper_styles( $attributes ) {
 	$has_width = array_key_exists( 'width', $attributes );
 
 	if ( $has_width ) {
-		$styles[] = 'max-width: 100%';
+		$styles[] = sprintf( 'width: %s;', $attributes['width'] );
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/button/button.php:223]: Apply the width to the root of the `jetpack/button`, instead of its `__link` element that's now 100% wide.

File: projects/plugins/jetpack/extensions/blocks/button/edit.js [hunk 4]
```diff
@@ -8,21 +8,16 @@ import {
...
 
 export function ButtonEdit( props ) {
-	const { attributes, backgroundColor, className, clientId, context, setAttributes, textColor } =
-		props;
+	const { attributes, backgroundColor, className, clientId, setAttributes, textColor } = props;
 	const { borderRadius, element, placeholder, text, width, fontSize } = attributes;
-	const isWidthSetOnParentBlock = 'jetpack/parentBlockWidth' in context;
 
 	usePassthroughAttributes( { attributes, clientId, setAttributes } );
-	useWidth( { attributes, disableEffects: isWidthSetOnParentBlock, setAttributes } );
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/button/edit.js:25]: Calling this hook results in resetting the button width when it is aligned left or right. I don't get the rationale behind that decision. In the current UI, from a user standpoint, this doesn't seem like something we'd want.

File: projects/plugins/jetpack/extensions/blocks/button/edit.js [hunk 5]
```diff
@@ -39,6 +34,7 @@ export function ButtonEdit( props ) {
 
 	const blockProps = useBlockProps( {
 		className: clsx( 'wp-block-button', className ),
+		style: { width },
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/button/edit.js:37]: Set the `width` to the root instead of the `__link` element.

File: projects/plugins/jetpack/extensions/blocks/button/edit.js (hunk 1 above)
Comment (talldan) [reply projects/plugins/jetpack/extensions/blocks/button/edit.js:94]: > Yet eventually, those two colors are passed to the ContrastChecker component, which doesn't render a warning when the contrast ratio is too low to be deemed accessible.

It's because the `applyFallbackStyles` code is wrong. It checks the block's outer element for the background color, but it's actually applied to the inner element (what it calls the `textNode`).

That said, I think it's pretty trivial to rewrite withFallbackStyles/applyFallbackStyles in a more modern react way that won't result in an extra wrapper, so I agree with removing it, and I'd be happy to work on getting the contrast checker working again in a follow up PR.

**Review by tellthemachines — COMMENTED** [review]
I didn't get to test with anything except the contact form, and only browsed the code but I do like that this PR removes more than it adds!

One thing I did notice in testing is that, if the percentage width buttons are used to put the button side by side with a form field, the button grows out unexpectedly:

Screenshot 2025-01-23 at 3 30 25 pm

I'm not sure how likely this scenario is in practice, but we could consider adding `align-self: center;` to the button wrapper in order to prevent it, `align-self: end` might be nicer but unfortunately doesn't quite align it with the other field:

Screenshot 2025-01-23 at 3 50 39 pm

**Review by aaronrobertshaw — COMMENTED** [review]
Thanks for all the work on this @monsieur-z 👍 

There seems to be quite a bit going on in this PR, I wonder if there's an opportunity to split it up into smaller atomic chunks with the view to make it easier to review for new contributors to Jetpack (such as myself 🙂 ).

After some hassles getting Mailchimp, Eventbrite, and Calendly setup and working properly, I've given the PR a test. I didn't run into any invalid block errors but did hit a number of general issues with width or alignment.

I noticed that the submit button in the contact form now fails to honour any width set on it in the editor. 

Here's what I was seeing on trunk:

https://github.com/user-attachments/assets/2973b5af-519e-42b4-bf26-fe0d3a35c202



and with this PR checked out:

https://github.com/user-attachments/assets/375d4a58-d359-4e5d-93f4-b4962a52e7a5

The PR also addresses alignment for buttons. Are there specific testing instructions we should follow for this?

I've given alignments on these buttons a quick smoke test too but alignments don't appear to work for me:

1. The contact form button's full width issue prevents any alignment
2. Paid content's subscribe button alignment doesn't work in the editor or frontend
3. Payments button alignment isn't working in editor or frontend either.

Screenshot 2025-01-23 at 2 52 54 pm

Screenshot 2025-01-23 at 2 53 30 pm

**Comment by tellthemachines** [comment]
Oh, and a general question about the width control if I may 😄 

Why does the percentage toggle disappear when the block is aligned left or right? It's a bit disorienting. (To be clear this is on trunk, not specifically this PR)

**Comment by monsieur-z** [comment]
Thanks for the review @tellthemachines.

Regarding the submit button vertical alignment issue, I intended to see how we wanted to handle [that issue](https://github.com/Automattic/jetpack/issues/41265). And it's already broken (differently) on trunk:
Screenshot 2025-01-23 at 9 47 59 AM

But yes, let's fix it now! I'll do it in a separate PR.

> Why does the percentage toggle disappear when the block is aligned left or right? It's a bit disorienting. (To be clear this is on trunk, not specifically this PR)

Totally. I don't have an answer, though.

**Comment by monsieur-z** [comment]
Thanks @aaronrobertshaw.

> I wonder if there's an opportunity to split it up into smaller atomic chunks

Initially, the plan was to fix `jetpack/button` but it required updating blocks that consume it too. I chose to do all the changes in the same PR to avoid further breakage. I'd like to keep this PR as is to expedite it. I'll be mindful of that in the future, though.

Looking at the code, I suggest looking at the changes in `packages/forms` first. The updates to blocks in the `extensions` folder ensure we can set the width and alignment of the submit button in the context of the block. Blocks are independent from each other.

> The contact form button's full width issue prevents any alignment

I haven't been able to reproduce this. Are you testing the branch locally, or with a live test site?

> Paid content's subscribe button alignment doesn't work in the editor or frontend
> Payments button alignment isn't working in editor or frontend either.

These are the caveats I mentioned in the PR description. It's not implemented on trunk either at the moment, and I believe it deserves a broader discussion UX-wise. How do we handle cases with multiple buttons? Should we only be able to align the group? Or buttons individually?

**Comment by lezama** [comment]
Got this after loading this PR over an existing Contact Form. It could be my stack. 

Screenshot 2025-01-23 at 3 22 00 PM

File: projects/plugins/jetpack/extensions/blocks/button/edit.js (hunk 1 above)
Comment (talldan) [reply projects/plugins/jetpack/extensions/blocks/button/edit.js:94]: Here's a small PR that addresses that - #41294.

I'll keep it as a draft until this or another fix for the styles is merged.

**Comment by monsieur-z** [comment]
Thanks for the feedback @lezama. I didn't see any errors in my compatibility testing but I'll give it another go to be sure. By any chance, would you know which branch you were running when you created the form?

**Comment by lezama** [comment]
I think I was running trunk, maybe from a couple of days ago, not sure 😅

**Comment by talldan** [comment]
> Got this after loading this PR over an existing Contact Form. It could be my stack.

I'm also seeing this in my local docker env. It happens on trunk too for me. 🤔 

It could also be my stack 😄

**Review by coder-karen — COMMENTED** [review]
Thanks for working on this!

I gave this a test and noticed different results with different themes so decided to focus on one in particular as I was confused by the results. I wasn't sure if it was environment based as well but I'll share what I found below.

I created a test post with a contact form, Eventbrite, Mailchimp and Calendly block on it using Jurassic Ninja, locally, and on a Simple site. I used the Twenty Twenty theme.

Local development env, and Simple:
Before applying the PR, the buttons were left-aligned in the editor by default, after applying now they are centre aligned (unless alignment settings had been added, in which case those alignments were respected).

Here's an example of how this affected the Register button, with screenshot showing before and after:
Screenshot 2025-01-29 at 10 45 12

Afer:
Screenshot 2025-01-29 at 10 45 20



After, while the pre-existing widths have been respected, the display is different - for example the default with the Mailchimp button was full-width, now it's less than full-width.

Jurassic Ninja:

This is where I think there may have been some environmental differences or issues related to using the beta tester plugin. Before applying the changes, the width alignment settings all worked apart from the contact submit button (which I understand is expected). Left aligned by default.
After, alignment is unusual - it's central but off-centre depending on width in the editor, but still left aligned in preview.

Generally, should these differences be expected?

**Comment by monsieur-z** [comment]
Thanks for the review @coder-karen. Good catch, the issues you mention seem to be related to older themes, which use the `data-align` attribute instead of the `align*` classes. All CSS changes were therefore not applied. The updates I made to the PR should fix that.

I also had to increase the CSS specificity of some Jetpack button selectors so the styles are applied as expected on older and newer themes. It feels sketchy but I see no other way around.

I've tested with the Twenty Twenty, Twenty Twenty-Four, and Twenty Twenty-Five themes. The former uses the `float` property to align buttons so the layout is easy to mess up. What other themes have you used for testing?

Setting the width should work on all buttons (except for the Recipe block, which I excluded from the testing instructions). Setting the alignment doesn't work for buttons in the same row: in our case the Payments Buttons and Paid Content blocks. But it doesn't seem it ever worked properly. I don't want to tackle all issues in this PR, so as long as it doesn't make any blocks worse, I'd say let's ship it.

The width/alignment should be the same in the editor and front end.

**Comment by monsieur-z** [comment]
@talldan and @lezama: I still haven't been able to reproduce the warning you're both seeing. Is there any other information you could think of that'd be relevant?

Locally, I tried adding a new Contact form to a post while on trunk, then checking out this branch and rebuilding the forms package. Reloading the post didn't trigger any warning. I also tried switching from the latest plugin stable version to this branch with a JN site. Same results.

**Comment by talldan** [comment]
> I still haven't been able to reproduce the warning you're both seeing. Is there any other information you could think of that'd be relevant?

It seems to have gone away now after a clean and rebuild. Sorry, I should've posted an update here.

File: projects/plugins/jetpack/extensions/blocks/button/edit.js (hunk 4 above)
Comment (talldan) [reply projects/plugins/jetpack/extensions/blocks/button/edit.js:25]: I've been testing and I also couldn't see the use case that the hook caters to. I saw this was implemented in #25394 by @mmtr, maybe Miguel remembers.

If there's no apparent current use cases, I wonder if it can be removed completely from the codebase. It's also used by Payment Button, but that has no alignment tool on the toolbar, so perhaps it's not needed.

edit: it just occurred to me, a case where it might makes sense is when the button is 100% width and an alignment is set.

**Review by talldan — APPROVED** [review]
In general, this seems to be working much better than `trunk`, so I think I'd be inclined to merge it and if there are some small things that are still not working they can be fixed in follow up PRs. I went through the code pretty thoroughly and there are a lot of changes, but all explained fairly well.

There are still some oddities, but I think they're out of scope for this PR, and same behavior is mostly present in trunk:
- Width control - it was mentioned by others, but the way the width split button disappears when a left/right alignment is set feels like a bug.
- Payment Button(s) - The way Payment Button wraps Jetpack Button is quite confusing.  The innermost Button has width and alignment options, but alignments don't work (in trunk or in this PR), and I don't see how they would given the Payment Button(s) blocks use a flex layout. Let me know if there's something I missed in my testing here.

**Review by coder-karen — APPROVED** [review]
Thanks for the follow-up! I did a little more testing and I imagine the main thing that might generate some support requests is the change to default behavior (for Mailchimp, Calendly, Eventbrite buttons, also Contact Us depending on theme), which in my testing again just now were full-width in the editor and front-end before and now are not. That's based on the themes I looked at anyway. The new default behavior makes sense given the changes in this PR, I can't imagine there's any way around this though.

I did notice that with Twenty Twenty the Register / Contact Us alignment issue I'd mentioned before is not an issue anymore - they're side by side in the editor - but in preview they're where they should be (one right aligned, the other the line below but left aligned). It seems like this could be theme specific though.

So I agree with the previous approval, it looks like any possible iterations could be followed up with separately. :shipit:
