### PR TITLE
CRM: 35359 and 3430 - Add HPOS support to WooSync

### LINKED ISSUE #35359: Metabox not showing with new WooCommerce update
### Impacted plugin

CRM

### Quick summary

From the ticket 7654372-zen: 

> When in the newer version of WooCommerce choosing "High performance order storage" under WooCommerce > Settings > Advanced > Features > Order data storage, in the order edit screen, the Jetpack CRM metabox where displaying contact with its status and number of orders, bit showing up. The reason for this is that the orders are no longer a post type (shop_order) and they have their own database tables and order edit/view page is not post edit interface. So the old screen_id of "shop_order" no longer displays the metabox. You should rather use "woocommerce_page_wc-orders" instead.

### Steps to reproduce

I wasn't able to repro it as expected. I pinged @tbradsha about that on Slack -- see ticket for link
### A clear and concise description of what you expected to happen.

From what Thomas said, we need more investigation as this is a new feature. 

Related GH issue: https://github.com/Automattic/jetpack-crm-extensions/issues/781

### What actually happened

_No response_

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves #35359 and Automattic/zero-bs-crm#3430 - add HPOS support to WooSync

## Proposed changes:

This PR:

* Introduces `jpcrm_woosync_is_hpos_enabled()` to check for Woo HPOS. Originally I did it within the WooSync module class, but there are instances where we need it when the class isn't loaded.
* If HPOS, uses `woocommerce_shop_order_list_table_columns` filter instead of `manage_edit-shop_order_columns`.
* If HPOS, uses `woocommerce_shop_order_list_table_custom_column` action instead of `manage_shop_order_posts_custom_column`.
* If HPOS, uses `woocommerce_before_trash_order` action instead of `wp_trash_post`.
* If HPOS, uses `woocommerce_before_delete_order` action instead of `before_delete_post`.
* Updates the three callback functions to account for different param types depending on if HPOS or not.
* Adds a comment to `append_woo_products_to_crm_product_index`, which is not enabled but has non-HPOS calls.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Test on JPCRM + Woo (non-HPOS) as well as JPCRM + Woo (HPOS) to ensure no regressions. HPOS is enabled on all new empty Woo sites; one can disable it per these instructions:

https://woo.com/document/high-performance-order-storage/#section-7

1. Enable WooSync invoice creation: `/wp-admin/admin.php?page=zerobscrm-plugin-settings&tab=woosync`
2. Create a Woo product: `/wp-admin/post-new.php?post_type=product`
3. Create a Woo order with a billing name and email: `/wp-admin/admin.php?page=wc-orders&action=new`
4. Visit the Woo order listview: `/wp-admin/edit.php?post_type=shop_order`
5. Visit the individual Woo order.

In `trunk`, the order listview will only show the CRM contact button on the non-HPOS site, and the order page will only show the contact metabox on the non-HPOS site.

In the `fix/crm/35359-order_metabox_missing_on_HPOS` branch, the contact button and metabox show on the HPOS site as well.

image
image

### CODE REVIEW

File: projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-woo-admin-integration.php [hunk 1]
```diff
@@ -52,225 +47,239 @@ public static function instance() {
...
+		// phpcs:disable WordPress.NamingConventions.ValidVariableName.UsedPropertyNotSnakeCase
+
+		global $zbs;
+		if ( jpcrm_woosync_is_hpos_enabled() ) {
+			$order = $order_or_post;
+		} else {
+			$order = wc_get_order( $order_or_post->ID );
+		}
+
+		$this->render_metabox_styles();
```
Comment (gogdzl) [inline projects/plugins/crm/modules/woo-sync/includes/class-woo-sync-woo-admin-integration.php:171]: 💯

**Review by gogdzl — APPROVED** [review]
Clean code and works as advertised!

EDIT: Tested paired with a previous version of the CRM and WooCommerce and didn't find differences between both.

**Review by gogdzl — APPROVED** [review]
