### PR TITLE
Premium Content block: Don't allow block to be nested

### LINKED ISSUE #22619: Premium Content Block: It's possible to nest premium-content blocks
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Be on a paid jetpack plan
2. Create a new post
3. Add a premium content block to the post
4. Click on either logged out or subscriber view
4. Open the block inserter

### A clear and concise description of what you expected to happen.

I didn't expect to see premium-content as an option. I can't transform existing child blocks to a premium-content, so I shouldn't be able to add a fresh premium-content block either

### What actually happened

I saw premium content as an option and clicking it did insert it, I ended up with a block structure like this: 
image

Which looked like a confusing mess on the front-end to a non-subscriber:
image

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Since we currently don't allow for blocks to be transformed to a Premium Content from inside of an existing Premium content, we'll also block the possibility to add new block. This restriction happens only for direct children of the block.

However, a user can still add a premium content block if they use an intermediary block (e.g. Group). This behaviour was not restricted due to technical shortcomings of the current Gutenberg API.

While this is not an ideal solution, it partially handles the restriction and avoids the block navigation issues - the navigation issue is not reproducible when the block is added from an intermediary block.

Fixes #22619

#### Changes proposed in this Pull Request:

* Use allowedBlocks in subscriber view and guest view to filter the premium-content/container block.
#### Testing instructions:

* Use Jetpack Beta and switch to this branch on your Atomic site
* Apply D76012-code on your sandbox
* Create a new post and add a Premium content block
* Go to the subscriber view and try to add a Premium content block again.
* Notice that "Premium Content" block is not available in the list.
* Repeat the test for "Guest" view. 
* In the subscriber view, add a "Group" block
* Add Premium content inside the group, you'll notice that's possible.
* Make sure that the block navigation hierarchy is correct.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/premium-content/subscriber-view/edit.js [hunk 1]
```diff
@@ -48,6 +50,10 @@ export default compose( [
 			// @ts-ignore difficult to type with JSDoc
 			hasInnerBlocks: !! select( 'core/block-editor' ).getBlocksByClientId( props.clientId )[ 0 ]
 				.innerBlocks.length,
+			allowedInnerBlocks: select( 'core/blocks' )
+				.getBlockTypes()
+				.filter( blockType => blockType.name !== name )
+				.map( block => block.name ),
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/blocks/premium-content/subscriber-view/edit.js:56]: This logic is pretty much duplicated in logged-out-view/edit.js, maybe we could generalize this into a separate helper/util/shared so that we could import it here and potentially in any other place without needing to copy pasta. 
WDYT?

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/extensions/blocks/premium-content/subscriber-view/edit.js]: Sounds good, done! :)

File: projects/plugins/jetpack/extensions/blocks/premium-content/_inc/premium.js [hunk 2]
```diff
@@ -2,17 +2,25 @@
...
 
-export const blockHasParentPremiumBlock = ( block ) => {
+export const blockHasParentPremiumBlock = block => {
 	const { getBlocksByClientId, getBlockParents } = select( 'core/block-editor' );
 	const parents = getBlocksByClientId( getBlockParents( block.clientId ) );
-	return !! parents.find( ( parent ) => parent.name.indexOf( 'premium-content/' ) === 0 );
+	return !! parents.find( parent => parent.name.indexOf( 'premium-content/' ) === 0 );
+};
+
+export const blockSelectAllowedBlocks = selector => {
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/premium-content/_inc/premium.js:21]: This is a good use case for a hook.

```js
// Untested code!
// _inc/use-premium-content-allowed-blocks.js

import { store as blocksStore } from '@wordpress/blocks';
import { useSelect } from '@wordpress/data';

import { name } from '../index';

export default function usePremiumContentAllowedBlocks() {
  const blockTypes = useSelect(
    select => select( blocksStore ).getBlockTypes()
  );

  return blockTypes.reduce( ( allowedBlocks, block ) => {
    if ( block.name !== name ) {
      allowedBlocks.push( block.name );
    }
    return allowedBlocks;
  }, [] );
}

// Then in the block...

import usePremiumContentAllowedBlocks from '../_inc/use-premium-content-allowed-blocks';

const allowedInnerBlocks = usePremiumContentAllowedBlocks();
```

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/premium.js]: Done, thanks!

**Comment by rcrdortiz** [comment]
Tests well on Simple and Atomic sites.

**Review by rcrdortiz — APPROVED** [review]

**Review by samiff — APPROVED** [review]
Worked great for me ✅

**Comment by samiff** [comment]
r241301-wpcom
