### PR TITLE
Map Block: Map Controls UI Fixes

### LINKED ISSUE #11892: Map block: maps without markers forget their position
Map forgets its location in the published post if it doesn't contain markers.

I positioned a map in the editor and hit "publish post". I expected to see a map like I saw in the editor also at the theme side.

Instead:
- [x] it jumped back to default position.
- [x] The map isn't from site edge-to-edge like it's in the editor (using [TwentyNineteen](https://github.com/WordPress/twentynineteen/) theme)
- [ ] I see "full screen" icon at the theme side, although I don't see it in the editor. The editor version should look as close to the like the output as possible when the block is unselected.
- [ ] In the theme side, borders in +/- icons look a bit off: 
    image

## I expected this

screenshot 2018-11-22 at 09 38 30

## I got this instead

screenshot 2018-11-22 at 09 38 53

cc @MichaelArestad  @jeffersonrabb

### PR DESCRIPTION
**Pull request by Copons**
Fixes #11892

#### Changes proposed in this Pull Request:

* Prevent theme styles adding a border radius to all buttons affecting the Map block controls too.

| Before | After |
| - | - |
| image | Screenshot 2020-02-14 at 17 11 07 |

* Add the fullscreen control as a block attribute.

Screenshot 2020-02-19 at 15 00 05

In the editor, the fullscreen button will always be disabled.

#### Testing instructions:

* ⚠️ **Before applying the PR** add a Map block to a post in order to test if the block attributes are migrated correctly.
* Test the PR with a theme that adds border radius to buttons (e.g. Twenty Nineteen).
* Open the editor and make sure the pre-existing Map block show up without issues. Check in the code editor that has the new `showFullscreenButton` attribute. 
* Preview on the front end and make sure the horizontal separator in the zoom controls is straight (compare to before/after screens).
* Enable and disable the "Show fullscreen button" setting, and check that it works as expected in both editor and front end, and that the fullscreen control is always disabled in the editor.

#### Proposed changelog entry for your changes:

* Add a "show fullscreen button" setting to the Map block.

### CODE REVIEW

File: extensions/blocks/map/component.js [hunk 1]
```diff
@@ -115,8 +115,17 @@ export class Map extends Component {
...
-		const { map } = this.state;
+		const {
+			apiKey,
+			children,
+			points,
+			mapStyle,
+			mapDetails,
+			scrollToZoom,
+			showFullscreenButton,
+			admin,
```
Comment (jeherve) [inline extensions/blocks/map/component.js]: Since we're making changes to this, do you think you could order those alphabetically? It's a nit-pick I know, but the `admin` in there confused me at first, and I think ordering those may help maybe?

File: extensions/blocks/map/edit.js [hunk 2]
```diff
@@ -191,6 +192,12 @@ class MapEdit extends Component {
 							checked={ scrollToZoom }
 							onChange={ value => setAttributes( { scrollToZoom: value } ) }
 						/>
+						<ToggleControl
+							label={ __( 'Show Fullscreen Button', 'jetpack' ) }
+							help={ __( 'Allow the user to display the map in fullscreen.', 'jetpack' ) }
```
Comment (jeherve) [inline extensions/blocks/map/edit.js]: Maybe it should say "your visitors" instead "the user"? It sounds a bit friendlier to me.

**Review by jeherve — CHANGES_REQUESTED** [review]
This works quite nicely, that's a nice addition! I only have 2 minor nit-picky comments.

File: extensions/blocks/map/component.js (hunk 1 above)
Comment (Copons) [reply extensions/blocks/map/component.js]: It's totally not a nitpick, and it's something I always do myself! 😄 
This time I think I've missed it because Prettier automatically expanded the object and I didn't notice.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢
