### PR TITLE
Set OpenGraph title meta attribute on search pages.

### LINKED ISSUE #14677: OpenGraph: Improve default og:title for search results page
#### Steps to reproduce the issue

1. Do a front-end search on a site with Jetpack enabled.
2. View the source and look for og:title
3. Value is "(no title)"

#### What I expected

It would be good to have a default value of "Search results: {search term}" or something similar, for the og:title. Other OG tags may also benefit from being tweaked for the search results page.

#### What happened instead

```
<meta property="og:site_name" content="{redacted}" />
<meta property="og:image" content="https://{redacted}" />
<meta property="og:image:width" content="449" />
<meta property="og:image:height" content="449" />
<meta property="og:title" content="(no title)" />
<meta property="fb:app_id" content="{redacted}" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:site" content="{redacted}" />
<meta property="og:locale" content="en_GB" />
<meta property="fb:pages" content="{redacted}" />
```

Seems like [this code](https://github.com/Automattic/jetpack/blob/6bd4c590f6168376047e2c36483c323009e03c64/functions.opengraph.php#L69-L163) is missing `is_search()` condition and logic.

### PR DESCRIPTION
**Pull request by coleshaw**
Fixes #14677 

#### Changes proposed in this Pull Request:

* Adds an OpenGraph `title` metadata tag based on the search terms, to the search results page.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Adds a feature to the existing OpenGraph component.

#### Testing instructions:

* Go to a WP post. View the source and see in the `head` section a set of `meta` tags for OpenGraph, including a descriptive `og:title` tag.
* Search for a term. In the search results page, view the source and look in the `head` section again for `meta` tags. You should find an `og:title` one with a value of `Search results for "{search term}" - {site name}`.

The output should look like:

```
<!-- Jetpack Open Graph Tags -->
<meta property="og:title" content="Search Results for “foo” – blah">
<meta property="og:site_name" content="blah">
<meta property="og:image" content="https://s0.wp.com/i/blank.jpg">
<meta property="og:locale" content="en_US">

<!-- End Jetpack Open Graph Tags -->
```

#### Proposed changelog entry for your changes:

* Adds OpenGraph title attribute to the search results page.

### CODE REVIEW

File: functions.opengraph.php [hunk 1]
```diff
@@ -152,16 +152,17 @@ function jetpack_og_tags() {
...
+		$tags['article:published_time'] = gmdate( 'c', strtotime( $data->post_date_gmt ) );
+		$tags['article:modified_time']  = gmdate( 'c', strtotime( $data->post_modified_gmt ) );
 		if ( post_type_supports( get_post_type( $data ), 'author' ) && isset( $data->post_author ) ) {
 			$publicize_facebook_user = get_post_meta( $data->ID, '_publicize_facebook_user', true );
 			if ( ! empty( $publicize_facebook_user ) ) {
 				$tags['article:author'] = esc_url( $publicize_facebook_user );
 			}
 		}
+	} elseif ( is_search() ) {
+		$tags['og:title'] = 'Search results: ' . get_query_var( 's', '(no title)' );
```
Comment (jeherve) [inline functions.opengraph.php]: I think it would be better if this could be translatable.

I am also not sure I would add that "no title" default; if there are no keywords (i.e. if someone shares `mysite.com/?s=` on Facebook, maybe we shouldn't add a custom Open Graph title at all, since folks would most likely except to see the site title as their preview on Facebook in those cases. What do you think?

File: functions.opengraph.php [hunk 2]
```diff
@@ -152,16 +152,17 @@ function jetpack_og_tags() {
 			$tags['og:description'] = wp_kses( trim( convert_chars( wptexturize( $tags['og:description'] ) ) ), array() );
 		}
 
-		$tags['article:published_time'] = date( 'c', strtotime( $data->post_date_gmt ) );
-		$tags['article:modified_time']  = date( 'c', strtotime( $data->post_modified_gmt ) );
+		$tags['article:published_time'] = gmdate( 'c', strtotime( $data->post_date_gmt ) );
```
Comment (jeherve) [inline functions.opengraph.php]: Did you make that change to address another issue? It may be best to move it to its own Pull Request, since it's not really related to this issue.

**Review by jeherve — CHANGES_REQUESTED** [review]

File: functions.opengraph.php (hunk 2 above)
Comment (coleshaw) [reply functions.opengraph.php]: Yes, I was getting a PHPCS error:

 ```
155 | ERROR   | date() is affected by runtime timezone changes which
     |         | can cause date/time to be incorrectly displayed. Use
     |         | gmdate() instead.
     |         | (WordPress.DateTime.RestrictedFunctions.date_date)
 156 | ERROR   | date() is affected by runtime timezone changes which
     |         | can cause date/time to be incorrectly displayed. Use
     |         | gmdate() instead.
```

Should I ignore those and use the `--no-verify` flag when committing?

Comment (jeherve) [reply functions.opengraph.php]: Okay. In this case let's leave this in. Thanks!

File: functions.opengraph.php [hunk 3]
```diff
@@ -152,16 +152,20 @@ function jetpack_og_tags() {
...
 			$publicize_facebook_user = get_post_meta( $data->ID, '_publicize_facebook_user', true );
 			if ( ! empty( $publicize_facebook_user ) ) {
 				$tags['article:author'] = esc_url( $publicize_facebook_user );
 			}
 		}
+	} elseif ( is_search() ) {
+		$query_param = get_query_var( 's', '' );
+		if ( '' !== $query_param ) {
+			$tags['og:title'] = __( 'Search results: ', 'jetpack' ) . $query_param;
+		}
```
Comment (jeherve) [inline functions.opengraph.php]: Looking more into it, I wonder if we could use `wp_get_document_title()` here as well; it does seem to handle search result pages for us already, and we'd get something that's filterable by other plugins:
https://github.com/WordPress/WordPress/blob/master/wp-includes/general-template.php#L1056-L1059

**Review by jeherve — CHANGES_REQUESTED** [review]

File: functions.opengraph.php (hunk 3 above)
Comment (coleshaw) [reply functions.opengraph.php]: Oh nice, I wasn't aware of that method. Let me give it a shot.

**Comment by coleshaw** [comment]
I've updated the original PR comment with the expected `meta` tags. `wp_get_document_title()` seems to work well.

**Review by jeherve — APPROVED** [review]
This works well in my tests. Merging.

**Comment by jeherve** [comment]
Internal reference: r203217-wpcom
