### PR TITLE
Tiled gallery & Slideshow blocks: fix transforms between blocks

### LINKED ISSUE #12255: Slideshow block: Transform to slideshow removes all the images from the block
#### Steps to reproduce the issue

1. Start on `/wp-admin/post-new.php`
2. Add a gallery/tilled gallery block. Add few images to the block
3. Try to transform it to slideshow
4. See an empty slideshow block
5. Repeat steps 2-3 with Image block. See the image was persisted

#### What I expected
Image gallery copied to slideshow block

#### What happened instead
Image gallery got lost in transformation

**Screenshots**
screencast 2019-05-03 12-35-36

### PR DESCRIPTION
**Pull request by simison**
Fix lost attributes, fix colliding transforms and improve confusing variable names.

Fixes https://github.com/Automattic/jetpack/issues/12255, closes https://github.com/Automattic/jetpack/pull/12278 (supersedes)

#### Changes proposed in this Pull Request:
- In "from core/image" transforms use `images` instead of `attributes` for less confusion
- Remove "to tiled gallery" transform in Slideshow block since Tiled gallery already has "from Slideshow" transform. Otherwise, we get JS failure.
- Ensure we create `ids` attribute between core gallery, tiled gallery and slideshow transform so that blocks don't end up without them.
- Ensure we pass `attributes.images` array, not `attributes` object  to `getValidImages()` function.

#### Testing instructions:
There is lot to click but this is fairly straightforward: ensure that you can transform between _all_ these blocks with and without images: tiled gallery, slideshow, core gallery, image.

With image blocks test also by selecting multiple images (using shift key). Bonus points if one or all of the images contain URLs (and not uploaded images).

Confirm by looking at code editor that slideshow, tiled gallery and core gallery blocks have `ids` attribute after each transformation:
Screenshot 2019-05-07 at 14 29 26

Screenshot 2019-05-07 at 14 29 26

The only transform you won't find is from core/image to slideshow & tiled gallery when the block does not have an image. When the block has an image, the transform **is** available. No change with `master` here; just something to confirm it works as it used to.

Screenshot 2019-05-07 at 14 50 26

It's easy enough to add but that would be a new feature so not in the scope of this PR.

#### Proposed changelog entry for your changes:
*

### CODE REVIEW

**Comment by simison** [comment]
@kraftbj lemme know if you'd prefer to have another PR targetting 7.3 with minimal changes to fix only https://github.com/Automattic/jetpack/issues/12255

(This PR fixes several different bugs.)

File: extensions/blocks/slideshow/transforms.js [hunk 1]
```diff
@@ -57,12 +58,7 @@ const transforms = {
 		{
 			type: 'block',
 			blocks: [ 'core/gallery' ],
-			transform: ( { images } ) => createBlock( 'core/gallery', { images } ),
-		},
-		{
-			type: 'block',
-			blocks: [ 'jetpack/tiled-gallery' ],
-			transform: ( { images } ) => createBlock( 'jetpack/tiled-gallery', { images }, [] ),
```
Comment (simison) [inline extensions/blocks/slideshow/transforms.js]: Here I removed "from slideshow to tiled-gallery"  transform in slideshow block, since tiled gallery block already has the same transform:

https://github.com/Automattic/jetpack/blob/22ab2e1ef84599d432db2f3b755fce8cb31b0071/extensions/blocks/tiled-gallery/index.js#L169-L185

File: extensions/blocks/slideshow/transforms.js [hunk 2]
```diff
@@ -20,9 +20,9 @@ const transforms = {
 			type: 'block',
 			isMultiBlock: true,
 			blocks: [ 'core/image' ],
-			isMatch: attributes => getValidImages( attributes ).length > 0,
-			transform: attributes => {
-				const validImages = getValidImages( attributes );
+			isMatch: images => getValidImages( images ).length > 0,
+			transform: images => {
+				const validImages = getValidImages( images );
```
Comment (simison) [inline extensions/blocks/slideshow/transforms.js]: These are simple variable name changes — it was confusing to see `attributes` in place of `images` where in the rest of the transforms we have `attributes.images` (in form of `( { images } )`).

There are a few similar ones across the changeset.

File: extensions/blocks/slideshow/transforms.js [hunk 3]
```diff
@@ -37,8 +37,8 @@ const transforms = {
 		{
 			type: 'block',
 			blocks: [ 'core/gallery', 'jetpack/tiled-gallery' ],
-			transform: attributes => {
-				const validImages = getValidImages( attributes );
+			transform: ( { images } ) => {
+				const validImages = getValidImages( images );
```
Comment (simison) [inline extensions/blocks/slideshow/transforms.js]: Note how we were passing `attributes` to `getValidImages()` instead of `attributes.images`. This would always return 0 valid images.

**Comment by brbrr** [comment]
> The only transform you won't find is from core/image to slideshow & tiled gallery

To confirm - this PR **removes** transform from core/image to slideshow / tiled gallery?

**Comment by simison** [comment]
>> The only transform you won't find is from core/image to slideshow & tiled gallery
>
>To confirm - this PR **removes** transform from core/image to slideshow / tiled gallery? 

Sorry, my bad — the transform **isn't** available when there is no image uploaded in the core image block — no change here, that's how its in `master` as well. The transform **is** still available for core image block when it has image:

image

vs

Screenshot 2019-05-07 at 14 50 26

I'll update PR description to clarify.

File: extensions/blocks/slideshow/transforms.js (hunk 2 above)
Comment (kraftbj) [reply extensions/blocks/slideshow/transforms.js]: I appreciate this. It makes it far more clearer what is being passed between the functions.

**Review by kraftbj — APPROVED** [review]
