### PR TITLE
Backups/scan card: Fix broken status for personal plan.

### LINKED ISSUE #6995: Personal plan set up: "You have paid for backups but they're not yet active" message without a "set up" button to activate and configure VaultPress
#### Steps to reproduce the issue

1. Connect a new Jetpack site.
1. Upgrade to Personal plan on connect.
1. Checkout
1. Set up the plan (via button). This installs and activates VaultPress and Akismet.
1. When complete, return to Jetpack Settings > Security (`/wp-admin/admin.php?page=jetpack#/security`)
1. You should see the following confusing message, but there's no "Set Up" to click on:

   > Backups and security scanning
   > Learn more
   > You have paid for backups but they're not yet active. Click "Set Up" to finish installation.

#### What I expected

Everything works and is set up.

#### What happened instead

I'm confused! Where's the "Set Up" button? It's not clear what I'm supposed to do.

where-set-up

Related: #6902 

cc @rickybanister

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #6995

# This is not testable with the dev tools plan switcher.  You must actually change the plan to test this.  

The dev tools won't work in testing, because the dev tools only changes the plan class, and it's possible to have these features active without a Jetpack plan.  

This fixes an issue when we were showing the wrong text on personal plan.  It also re-writes the logic to show the content to make it more readable.

It also fixes an issue where we were not showing the `set up` button on professional plans if scan was not enabled for some reason.

To test: You should see the following statuses
**Free plan, no features active**
screen shot 2017-05-19 at 10 28 00 am

**Backups only enabled, (personal plan)**
screen shot 2017-05-19 at 10 29 07 am

**Backups and scan enabled (premium/business)**
screen shot 2017-05-19 at 10 27 44 am

**Personal plan, not enabled yet**
screen shot 2017-05-19 at 10 45 03 am

**Premium/business plan, but not enabled yet**
screen shot 2017-05-19 at 10 38 24 am

### CODE REVIEW

**Comment by jeherve** [comment]
One small unrelated remark too: I was surprised to be redirected to https://jetpack.com/pricing/settings-security-premium/ when clicking on "Upgrade" while on a free plan. I had no option to pick a Personal plan there.

cc @richardmuscat

**Comment by rickybanister** [comment]
This looks perfect. Thanks for hitting it @dereksmart !

**Comment by dereksmart** [comment]
> I noticed a small issue when using a Personal plan, but when VaultPress isn't active on the site

@jeherve what is wrong about that?  The setup link will activate VP, and the upgrade prompt is for the Scan feature.

**Comment by jeherve** [comment]
Well now that you mention it, it makes sense. I guess I didn't expect an additional prompt there, but  now I understand. 👍

**Comment by rickybanister** [comment]
@dereksmart I'm not 100% sure.

@MichaelArestad and @richardmuscat can you confirm how we handle this upgrade banner? Should it be 'progressive' and continue to advertise the higher tier of service as the user upgrades?

**Comment by MichaelArestad** [comment]
@rickybanister I don't understand the question as it pertains to this issue. @dereksmart asked if we should show an upgrade notice to enable scans if only backups is enabled (I think) which isn't really a plan upgrade. It's just encouraging the user to enable a feature.

To answer your question, though, I don't think we're showing any further upgrade notice to Professional plans (which would encourage upgrading for realtime backups).

**Comment by dereksmart** [comment]
@MichaelArestad 

> show an upgrade notice to enable scans if only backups is enabled (I think) which isn't really a plan upgrade. It's just encouraging the user to enable a feature.

It is a plan upgrade, since scan feature is not available for personal sites, but backups are.

**Comment by rickybanister** [comment]
We should show the prompt—if the user has the option to be even more safe we should be showing it to them. At least we can start with that mentality and see how it goes. 

As to the main purpose of this PR, the set up button will work great for folks that get to this stage without being autoconfigured properly. 

Let's get it merged.

**Comment by MichaelArestad** [comment]
@dereksmart @rickybanister Got it! Okay. We definitely should show an upgrade banner for that, but as Rick said, in another PR.

File: _inc/client/security/backups-scan.jsx [hunk 1]
```diff
@@ -32,59 +32,70 @@ export const BackupsScan = moduleSettingsForm(
...
-					hideButton
-				>
+					hideButton>
 					<SettingsGroup
 						disableInDevMode
 						module={ { module: 'backups' } }
-						support="https://help.vaultpress.com/get-to-know/"
-					>
-						{ cardText }
+						support="https://help.vaultpress.com/get-to-know/">
```
Comment (eliorivero) [inline _inc/client/security/backups-scan.jsx]: There's an issue here: when `this.getCardText()` returns empty, the SettingsGroup card is rendered without content, only displaying the information icon.
It should be changed to only show the SettingsGroup if there is something to show there.
captura de pantalla 2017-05-25 a las 15 38 33

File: _inc/client/security/backups-scan.jsx [hunk 2]
```diff
@@ -32,59 +32,70 @@ export const BackupsScan = moduleSettingsForm(
...
-				get( this.props.vaultPressData, [ 'data', 'features', 'backups' ], false ) &&
-				get( this.props.vaultPressData, [ 'data', 'features', 'security' ], false ),
+		getCardText() {
+			const backupsEnabled = get( this.props.vaultPressData, [ 'data', 'features', 'backups' ], false ),
+				scanEnabled = get( this.props.vaultPressData, [ 'data', 'features', 'security' ], false ),
 				planClass = getPlanClass( this.props.sitePlan.product_slug );
 			let cardText = '';
 
+			if ( this.props.isFetchingSiteData || this.props.isFetchingVaultPressData ) {
+				return __( 'Checking site status…' );
```
Comment (zinigor) [inline _inc/client/security/backups-scan.jsx]: The early return does wonders to this method's code, thank you for that!

File: _inc/client/security/backups-scan.jsx (hunk 1 above)
Comment (dereksmart) [inline _inc/client/security/backups-scan.jsx]: Not sure how you reproduced this, I'm not seeing the info icon.  The settingsGroup component [shouldn't be rendered](https://github.com/Automattic/jetpack/blob/master/_inc/client/components/settings-card/index.jsx#L202) here if on a free plan and scan is not enabled.
