### PR TITLE
VaultPress: if Rewind is enabled, remove its entry in sidebar and hide its notice

### LINKED ISSUE #8691: Remove VaultPress side menu item when deactivating
#### Steps to reproduce the issue
1. Activate VaultPress on a site which has Rewind active/working
2. Click on VaultPress in the sidebar menu

#### What I expected
VaultPress not to appear in the sidebar menu (because it's inactive)

#### What happened instead
Since we're deactivating VaultPress after the menu is registered, VP still appears in that menu.  Edit the menu array to remove VP and we're all good.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #8691

This PR fixes issues with VaultPress deactivation driven by Jetpack when Rewind is active:

#### Proposed changes

The Jetpack menu was previously still showing the VaultPress submenu and clicking it lead to a blank page. This is now fixed here.

The notice saying "VaultPress needs your attention!" was still shown before, but it's now hidden. It was complex to remove it since it wasn't possible to remove the actions hooked to `user_admin_notices` and `admin_notices`. To overcome this, a `<style>` tag was added with a rule to hide the notice.

Updated PHPDocs.

#### Testing instructions:

1. test with a site with Rewind active
2. activate the VaultPress plugin. It will be automatically deactivated and a notice will show.
3. ensure that:
    - there's not a **VaultPress** submenu entry under the **Jetpack** menu
    - the notice **VaultPress needs your attention!** is not visible

#### Proposed changelog entry for your changes:
VaultPress: menu item going nowhere is now suppressed.

### CODE REVIEW

File: 3rd-party/vaultpress.php [hunk 1]
```diff
@@ -1,26 +1,36 @@
...
+ * @since 5.8
+ */
 function jetpack_vaultpress_rewind_check() {
 	if ( Jetpack::is_active() &&
 		 Jetpack::is_plugin_active( 'vaultpress/vaultpress.php' ) &&
 		 Jetpack::is_rewind_enabled()
 		) {
+		remove_submenu_page( 'jetpack', 'vaultpress' );
+
+		deactivate_plugins( 'vaultpress/vaultpress.php' );
```
Comment (georgestephanis) [inline 3rd-party/vaultpress.php]: Moving this to here is probably a bad idea.

We had intentionally left it in the notice function, as there may be pages that `admin_init` runs on ([such as `admin_ajax`](https://github.com/WordPress/WordPress/blob/36b3f1707cd2a3d48a54a9637f37e2273b1fe319/wp-admin/admin-ajax.php#L45)) that would otherwise deactivate the plugin without the notification explaining ever being shown.

Comment (eliorivero) [reply 3rd-party/vaultpress.php]: Cool, I'll make the change and will add a comment explaining why it's there.
