### PR TITLE
Admin Page: Fix REST API URL for index permalinks

### LINKED ISSUE #5216: Admin Page: Use /index.php/wp-json/ when using index permalinks
WP has three styles of permalinks:
Pretty Permalinks:
example.com/wp-json/whatever/

Index Permalinks:
example.com/index.php/wp-json/

Default:
example.com/?rest_route=/whatever/

It appears that within the Admin Page, we're not using index permalinks when they're set.

### PR DESCRIPTION
**Pull request by kraftbj**
Adds a filter to insert the index value to the permalink when index permalinks are being used when the site is not using the updated version of WP.

Fixes #5216
See https://core.trac.wordpress.org/ticket/38182

Changelog: Bug: Fixes issue where certain administrative page actions would fail with sites using index permalinks.

### CODE REVIEW

**Comment by kraftbj** [comment]
Confirmed with Core that they are not going to backport the core fix, so we're good to go using this as the shim until 4.7 is the minimum version.

File: jetpack.php [hunk 1]
```diff
@@ -27,6 +27,24 @@
...
+ * Fix the REST API URL for sites using index permalinks
+ *
+ * @todo Remove when 4.7 is minimum version
+ * @see  https://core.trac.wordpress.org/ticket/38182
+ * @see  https://github.com/Automattic/jetpack/issues/5216
+ * @author kraftbj
+ **/
+function jetpack_index_permalinks_rest_api_url( $prefix ){
+	global $wp_rewrite, $wp_version;
+	if ( version_compare( $wp_version, '4.7-alpha-38790', '>=' ) && $wp_rewrite->using_index_permalinks() ){
```
Comment (zinigor) [inline jetpack.php]: If my reasoning is correct, then this should be `<` instead of `>=`. Here's my reasoning:
We only need this for versions of WordPress that have not yet fixed that problem, so the version should actually be less than `4.7-alpha-38790`. This expression returns true if it's later than `4.7-alpha-38790`. Please let me know if I'm wrong.

**Comment by samhotchkiss** [comment]
#5461

**Comment by samhotchkiss** [comment]
Great catch, @zinigor
