### PR TITLE
Subscriptions: load dashboard widget within the Subscriptions module

### LINKED ISSUE #102467: Newsletter widget: subscriber links are linking to the Stats page
### Context and steps to reproduce

The first two links from the Newsletter widget in
/index.php is redirecting to the stats page instead of the Subscriber's ones.

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### Platform

Simple

### PR DESCRIPTION
**Pull request by jeherve**
Fixes https://github.com/Automattic/wp-calypso/issues/102467

## Proposed changes:

This PR does a few things:

1. It moves the Newsletter dashboard widget PHP class from the root of the Jetpack plugin to the Subscriptions module directory, thus keeping the PHP close to its JS counterpart.
2. It loads the widget within that same file.
3. It requires the file from the Subscriptions module's main file. **As a result, the widget will only be displayed when the module is enabled.** It's better UX (most of the links and the graph are not useful when you don't use the feature), and better for performance too.
4. It removes the code that was added in #41807 to load the widget from the mu-wpcom plugin, to keep things simple. Instead, on wpcom simple the widget will be loaded via 179986-ghe-Automattic/wpcom

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

> [!NOTE]
> This is better tested on both self-hosted and WordPress.com simple.

**On self-hosted**

1. On a site that's connected to WordPress.com, go to Jetpack > Settings > Newsletter and enable the feature.
2. Go to the main wp-admin page
    * You should see the widget.
3. Go back to the Jetpack settings page, and disable the feature.
4. Go to the main wp-admin page
    * The widget should not be available

**On WordPress.com simple**

* ~Apply this PR as well as 179986-ghe-Automattic/wpcom~ This has now been committed.
* Ensure the widget is available in the main wp-admin screen.

### CODE REVIEW

File: projects/plugins/jetpack/class-jetpack-newsletter-dashboard-widget.php [hunk 1]
```diff
@@ -2,221 +2,14 @@
 /**
  * Jetpack Newsletter Dashboard Widget.
  *
- * @package jetpack
- */
-
-/**
- * Adds the Jetpack Newsletter widget to the WordPress admin dashboard.
+ * @deprecated $$next-version$$
```
Comment (jeherve) [inline projects/plugins/jetpack/class-jetpack-newsletter-dashboard-widget.php:5]: I'm not completely deleting that file just yet, to avoid fatal errors on plugin upgrade on sites that have an aggressive caching.

**Review by allilevine — APPROVED** [review]
I can hide/show the widget on Atomic and self-hosted by togging the module on and off. On Simple, I see the widget with these changes applied. Thanks for making this improvement!
