### PR TITLE
Forms: Fix submission if date field had errored

### LINKED ISSUE #41478: Forms: date field doesn't submit if previously errorer
### Impacted plugin

Jetpack

### Quick summary

Currently if you submit a form with an invalid date field there is no way to recover from that. 

Image

### Steps to reproduce

Create a form with a date field. 
On the front end. 
1. Type is `1` in the date field ( or something else invalid) and submit the form. 
You should see an invalid field error. 

2. Now select the a date via the date picker. and submit the form. 

You are not able to submit the form. Since the form still things that the field is invalid. 

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

Individual site owner revenue

### If a workaround is available, please outline it here.

The user can refresh the page. And resubmit the form with valid fields. Not making the error. 

The form will submit as expected. 

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/Automattic/jetpack/issues/41478

Currently if you submit a form with an invalid date field there is no way to recover from that. This PR fixes that.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
1. Create a form with a date field.
2. On the front end type `1` in the date field ( or something else invalid) and submit the form.
3. You should see an invalid field error.
4. Now select the a date via the date picker. and submit the form.
5. The form submission should be successful

### CODE REVIEW

File: projects/packages/forms/src/contact-form/js/accessible-form.js [hunk 1]
```diff
@@ -269,6 +269,7 @@ const isDateFieldValid = input => {
 	if ( value && format && typeof $ !== 'undefined' ) {
 		try {
 			$.datepicker.parseDate( format, value );
+			input.setCustomValidity( '' );
```
Comment (ntsekouras) [inline projects/packages/forms/src/contact-form/js/accessible-form.js:272]: The below `setCustomValidity` call would result in following invalidations of the field ([customError](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/customError)) and needs to be reset.

File: projects/packages/forms/src/contact-form/js/grunion-frontend.js [hunk 2]
```diff
@@ -6,5 +6,8 @@ jQuery( function ( $ ) {
 		dateFormat,
 		constrainInput: false,
 		showOptions: { direction: 'down' },
+		onSelect: function () {
+			$( this ).focus();
```
Comment (ntsekouras) [inline projects/packages/forms/src/contact-form/js/grunion-frontend.js:10]: Two things happening here:
1. jqueryUI doesn't trigger the input's `blur` event and by focusing the user has to `blur`
2. This is also better in general because before there was a focus loss (a11y issue).

**Comment by lezama** [comment]
heads up that @enejb is trying to remove the jquery dependency here: https://github.com/Automattic/jetpack/pull/41410

**Comment by simison** [comment]
Fine to merge this fix meanwhile, the other PR might need more work/testing.

**Comment by lezama** [comment]
tests great
