### PR TITLE
Forms: Migrate form fields to inner blocks JETPACK-262

### LINKED ISSUE #42358: Forms: Migrate form fields to inner blocks
Part of: https://github.com/Automattic/jetpack/issues/42353
Related: https://github.com/Automattic/jetpack/pull/41281
Project Thread: __TBA__

## Description

This issue finalizes the switch to form field inner blocks by introducing block deprecations that transform each form field into the new structure. We’ll also update the style syncing logic and shortcode rendering to handle child blocks correctly.

## Scope & Requirements

- Implement block deprecations mapping old attributes (label text, input type, etc.) into new `Label`, `Input`, and `Option` blocks.
- Update shortcode rendering functions to collect styling data from nested blocks and apply it to generated HTML.
- Ensure style syncing (if enabled) is compatible with multiple child blocks within a single field.

## Tasks
- [ ] Add block deprecations
  - For each current field type, define a deprecation transforming it into a parent container with inner blocks.
  - Test with posts that contain older forms to confirm a smooth upgrade experience.
- [ ] Update shortcode rendering  
  - Map nested child block attributes to the expected markup or classes.
  - Confirm frontend display remains consistent for non-migrated and migrated blocks alike
- [ ] Refactor style syncing
  - Refactor existing HoC to a new custom hook that handles style syncing in a manner compatible with child blocks.
- [ ] Final tests & validation
  - Add or update automated tests to confirm no regressions.
  - Check multiple field scenarios (text, email, radio, checkbox) in both old and new states.

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
JETPACK-262

Fixes #42358

⚠️ **This PR is now the sole source of truth for both adding new base form field blocks and migrating fields to them** ⚠️

## Proposed changes:

- Add new base blocks for form fields: 
  - Input
  - Label
  - Option
  - Options
- Migrate all form fields to use new base blocks
    - File field is pending and will be updated to inner blocks in due course
- Fixes for various minor forms bugs on trunk e.g. undo loops, minor style conflicts etc
- Change consent and checkbox fields to share option styles not label/input styles for better consistency across fields

## Does this pull request change what data or activity we track or use?

No changes.

## Testing instructions:

**General Notes**
- Please test undo and redo actions throughout all sequences. A number of improvements in this PR specifically enhance stability during these interactions
- As this PR is still under active development and testing, these test instructions may need to evolve over time.

---

1. 🧱 **Field Insertion & Pasting**

Goal: Confirm all form field blocks insert and behave as expected.

- Insert each of the following field types via the block inserter:
  - Text, Name, Email, Number, Website, Phone, Multiline (Textarea)
  - Dropdown
  - Checkbox, Terms Consent
  - Single Choice (Radio), Multiple Choice (Checkbox), 
  - Date Picker
- Paste a field from one form into another.
- Confirm all fields look correct, show relevant block controls, and function as expected.

⸻

2. 🎨 **Styling: Inputs, Labels, and Options**

Goal: Confirm block and global styles apply and override correctly.

- Apply styles via Global Styles (site editor).
- Apply per-block styles using the block inspector.
- Confirm styles render consistently in both the editor and frontend.
- Test toggling individual styles on/off and reapplying.

⸻

3. 🔁 **Style Syncing Between Fields**

Goal: Verify how styles are shared across synced fields of similar types.

- Update a style on one synced field (e.g., font size or text color for an input field).
- Confirm other synced input fields update accordingly.
- Opt a field out of syncing and confirm it no longer updates.
- Insert a new field and confirm it inherits current synced styles.
- Paste a field from another form into a synced form and observe behavior.

⸻

4. 🔀 **Field Transforms**

Goal: Ensure transforming between field types behaves as expected.

- Transform fields (e.g., Name → Email, Text → Phone).
- Confirm that styles and attributes are preserved only when appropriate.
- Confirm that irrelevant attributes (like a "Name" label value when transforming to an Email field) are discarded.

⸻

5. 🧩 **Form Variations & Patterns**

Goal: Ensure all form patterns insert correctly and render well.

Test inserting:

- Contact Form
- RSVP Form
- Registration Form
- Appointment Form
- Feedback Form
- Lead Capture Form
- Salesforce Lead Form

Verify:

- The default structure is valid and editable.
- Labels, placeholders, and field types are appropriate.

⸻

6. ✨ **Style Variants**

Goal: Validate style variations and layout combinations.

Insert:

- Outlined Style Form
- Animated Style Form

For both, test:
  - Base version
  - Version with field customizations
  - Upgrading from trunk form to refactor form
  - Confirm styles work.
  - Test columns and responsive behavior.

⸻

7. 📦 **Field Nesting**

Goal: Confirm fields can be used within layout blocks.

- Nest fields inside:
  - Group blocks
  - Columns
- Confirm style syncing still works across nesting levels.
- Check alignment and spacing behave as expected.

⸻

8. 🪄 **Automatic Form Wrapping**

Goal: Ensure orphaned fields are auto-wrapped in a Form block.

- Insert a field outside any form block.
- Paste one or more fields into a blank page.
- Confirm automatic wrapping behavior.
- Save and verify layout remains valid.

⸻

9. ⚙️ **Required Field Settings**

Goal: Validate required state control across all field types.

- Toggle required setting for fields via field and inner blocks' block toolbars
- Confirm required indicator displays appropriately.
- Add custom required text and check that it renders.
- Disable the required setting and confirm the indicator disappears.

⸻

10. 🧪 **Deprecations & Migrations**

Goal: Confirm legacy forms upgrade smoothly.

- On trunk, create a post containing all field types and apply styling. 
- Switch to the PR branch.

Confirm:

- Legacy form still displays correctly on the frontend
- No block validation errors in editor
- Fields are migrated to inner block structure
- Styling remains intact
- Save the post and confirm the frontend still matches. 

⸻

11. 🌐 **Additional Coverage**

🧑‍🦯 **Keyboard Accessibility**

- Tab through all form fields and verify correct focus behavior.
- Ensure field labels are associated correctly (label-input relationships).

📱 **Mobile Responsiveness**

- Test forms on small screens (phone/tablet viewports).
- Confirm layouts stack properly and remain usable.

↔️ **RTL Language Support**

Switch the site language to RTL (e.g., Hebrew, Arabic).

Check that:
- Layouts flip direction as expected
- Labels and fields align correctly

♻️ **Reusable Blocks**

- Save a form or field group as a reusable block.
- Insert it into another post.
- Confirm editing and layout integrity.

⚙️ **Editor Performance**

- Insert lots of fields (30+).
- Check for lag or editor slowdown during typing and style changes.

🌍 **Multilingual / i18n Support**

- Switch site language.
- Confirm labels, placeholders, and help texts are translatable and update correctly.

### CODE REVIEW

**Comment by andrewserong** [comment]
Just jotting down a note from testing: overall it's been working quite well for me so far! There's one issue with the Dropdown Field block that I ran into that looked a bit peculiar so just noting it down for now:

1. In the Site Editor, go to edit a page and add a Registration Form pattern (it includes a Dropdown Field)
2. In the Page tab on the right hand sidebar, click the button next to Template and then Swap Template
3. This opens the modal to select another template. In the preview of the current template, the Dropdown Field appears to go into an infinite loop setting itself up (this doesn't appear to happen on `trunk`):

https://github.com/user-attachments/assets/63d4763b-9858-46bb-b0ea-dc4390ae96ce

<details>

<summary>Screenshot of verbose logging from React in the console</summary>

I'm not _quite_ sure what's going on, but there's lots of verbose logging messages from React:

image

</details>

Unrelated to this PR, but I find the ability to edit options within the Dropdown Field pretty challenging. That appears to be the case in both this PR and on trunk, though, but could be good to circle back to further down the track.

**Comment by aaronrobertshaw** [comment]
> the Dropdown Field appears to go into an infinite loop setting itself up (this doesn't appear to happen on trunk):

Thanks for the testing @andrewserong :rocket: 

All patterns at this stage will have legacy blocks that need to run through the block deprecations. I'd recently seen a similar issue to what you described when only some blocks had been migrated previously. It's on my list to dig deeper into but got sidetracked today fixing the style syncing for option blocks across the different field types.

**Comment by aaronrobertshaw** [comment]
> In the Site Editor, go to edit a page and add a Registration Form pattern (it includes a Dropdown Field)

I hit a block validation error as soon as I attempted to add a Registration Form or the pattern. After tweaking the dropdown field's edit component to be a little more robust, I could replicate the issue you noted. 

My suspicion is that this could be related to the `useSyncStyleAttributes` hook. Adding an early return to that prevented the bouncing but the dropdown field never got setup to be the custom select. 

_Quick update: For now I've added a super basic check for whether we're in the template preview mode. In that scenario, the style syncing will return early. This seems to stabilize the preview however the custom JS select field doesn't seem to get setup. That's something I'll look into after some higher priority issues._

**Comment by andrewserong** [comment]
Another couple of wrinkles that might have already been captured elsewhere (Label block issues):

Hitting "Enter" from the beginning of a label block adds a new line character, where I'd expect it to insert a paragraph block preceding the parent block:

https://github.com/user-attachments/assets/c44a861b-a877-4663-b6d9-5fc88ae4f448

When removing the text from a Label field altogether, if you click out from the block and attempt to click back into it, it's not possible to start typing to add in label text again. You can get back to it via the up arrow by keyboard, but I imagine it's that we're not able to click the empty rich text field. Maybe we can add placeholder text while the Label block is selected or something like that?

https://github.com/user-attachments/assets/bf02cf99-18ca-41cc-9713-b8a19436bc0f

**Comment by aaronrobertshaw** [comment]
Appreciate the continued testing @andrewserong :bow:

> Hitting "Enter" from the beginning of a label block adds a new line character, where I'd expect it to insert a paragraph block preceding the parent block

This is the same behaviour as trunk at the moment but definitely something that can be improved.

> When removing the text from a Label field altogether, if you click out from the block and attempt to click back into it, it's not possible to start typing to add in label text again

Nice catch, that should be an easy enough fix. Until recently the label block had an auto width, I probably just missed also making the RichText component fill the available width when I tweaked the block for that same purpose.

I'll get an issue up for the first enhancement and tweak the other one shortly on this branch to hopefully avoid it tripping up others testing.

File: projects/packages/forms/src/blocks/field-checkbox/index.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+		// TODO: Audit all block attributes. Things like this label should be handled by inner blocks.
+		label: {
+			type: 'string',
+			default: 'Add label…',
+			role: 'content',
+		},
+	},
+	providesContext: {
+		'jetpack/field-required': 'required',
+		'jetpack/field-defaultValue': 'defaultValue',
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-checkbox/index.js]: Minor - I feel like `'jetpack/field/defaultValue'` might be preferable to reduce the mix of camel/kebab case mixing. I find it reads a little easier too.

File: projects/packages/forms/src/blocks/field-consent/edit.js [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+import useFormWrapper from '../shared/hooks/use-form-wrapper';
+
+export default function ConsentFieldEdit( props ) {
+	const { attributes, clientId, instanceId, setAttributes } = props;
+	const { consentType, width, implicitConsentMessage, explicitConsentMessage } = attributes;
+
+	useFormWrapper( props );
+
+	const blockProps = useBlockProps( {
+		id: `jetpack-field-consent-${ instanceId }`,
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-consent/edit.js]: Need to check that the `instanceId` still works now that the `withInstanceId` HOC isn't present.

It'd probably be best to switch to `useInstanceId` where possible.

File: projects/packages/forms/src/blocks/field-consent/edit.js [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+		},
+		[ setAttributes ]
+	);
+
+	const onConsentTypeChange = useCallback(
+		value => {
+			setAttributes( { consentType: value } );
+		},
+		[ setAttributes ]
+	);
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-consent/edit.js:146]: I'm not sure it's necessary to wrap these with `useCallback`. I think that's only really needed if the functions are being passed to something (component, effect, other callback) that's also memoized.

As it stands though, the `ToggleControl`, `SelectControl` are not memoized, so they will re-render whenever `ConsentFieldEdit` re-renders anyway.

File: projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+		...INNER_BLOCKS_DEPRECATION.attributes,
+		label: {
+			type: 'string',
+			default: 'Choose several options',
+		},
+	},
+	isEligible( _attributes, innerBlocks ) {
+		if ( innerBlocks.length !== 2 ) {
+			return true;
+		}
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js:54]: I don't think this condition is a good idea, because if another inner block type (e.g. a validation message block) is added in the future to the multiple choice block, `isEligible` would return `true` incorrectly, and that'll cause the migration to run when it shouldn't.

This kind of logic problem with `isEligible` has caused some bad bugs in the gutenberg codebase:
- https://github.com/WordPress/gutenberg/pull/63837
- https://github.com/WordPress/gutenberg/pull/65105

Maybe removing this `if` condition and reducing it to the `innerBlocks.some` check below is enough.

File: projects/packages/forms/src/blocks/field-multiple-choice/edit.js [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+	const { className, clientId, instanceId, setAttributes, isSelected, attributes } = props;
+	const { required, id, width } = attributes;
+
+	useFormWrapper( props );
+
+	const innerBlocks = useSelect(
+		select => select( blockEditorStore ).getBlock( clientId ).innerBlocks,
+		[ clientId ]
+	);
+	const options = innerBlocks?.[ 1 ]?.innerBlocks;
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-multiple-choice/edit.js:22]: This could be made more robust, just in case the blocks are reordered for some reason,

File: projects/packages/forms/src/blocks/field-select/edit.js [hunk 6]
```diff
@@ -1,32 +1,88 @@
...
+import JetpackFieldControls from '../shared/components/jetpack-field-controls';
+import useFormWrapper from '../shared/hooks/use-form-wrapper';
+import useJetpackFieldStyles from '../shared/hooks/use-jetpack-field-styles';
+import { getCaretPosition } from '../shared/util/caret';
+import { ALLOWED_INNER_BLOCKS } from '../shared/util/constants';
+import setFocus from '../shared/util/set-focus';
+
+const noop = () => undefined;
+
+export default function DropdownFieldEdit( props ) {
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-select/edit.js:20]: Nitpick
```suggestion
export default function SelectFieldEdit( props ) {
```

File: projects/packages/forms/src/blocks/field-single-choice/deprecated.js [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+		...INNER_BLOCKS_DEPRECATION.attributes,
+		label: {
+			type: 'string',
+			default: 'Choose one option',
+		},
+	},
+	isEligible( _attributes, innerBlocks ) {
+		if ( innerBlocks.length !== 2 ) {
+			return true;
+		}
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-single-choice/deprecated.js:54]: Same as for the other block, maybe this can be removed and it'll make the `isEligible` check more future-proof.

File: projects/packages/forms/src/blocks/field-textarea/edit.js [hunk 8]
```diff
@@ -0,0 +1,71 @@
...
+			[ 'jetpack/label', { label, required, defaultLabel, requiredText } ],
+			[ 'jetpack/input', { type: 'textarea' } ],
+		];
+	}, [ label, defaultLabel, required, requiredText ] );
+
+	const innerBlocksProps = useInnerBlocksProps( blockProps, {
+		allowedBlocks: ALLOWED_INNER_BLOCKS,
+		template,
+		templateLock: 'all',
+		type: 'textarea',
```
Comment (talldan) [inline projects/packages/forms/src/blocks/field-textarea/edit.js]: Is this prop right?

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 9]
```diff
@@ -141,11 +169,17 @@ public function __construct( $attributes, $content = null, $form = null ) {
 		if ( ! empty( $attributes['options'] ) && is_string( $attributes['options'] ) ) {
 			$attributes['options'] = array_map( 'trim', explode( ',', $attributes['options'] ) );
 
+			// TODO: Work out where these values are set? Are they actually set anywhere?
```
Comment (talldan) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php]: Could it be set by using a shortcode like `[contact-field type="checkbox-multiple" values="1,2,3" /]`?

Perhaps that was an old version of the shortcode.

I see there's also some code here to construct a shortcode with a values attribute like that:
https://github.com/Automattic/jetpack/blob/27ff4357597a0b385570fd0974ded07c27eafe2f/projects/packages/forms/src/contact-form/class-contact-form.php#L879-L884

**Review by talldan — COMMENTED** [review]
I've run out of time, so this is a partial review.

File: projects/packages/forms/src/blocks/field-consent/edit.js (hunk 3 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-consent/edit.js:146]: I'm not tied to this, my linting was warning about unstable or inline functions being passed as props.

File: projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js (hunk 4 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js:54]: Either way this `isEligible` check would need to be updated upon the addition of any validation inner block. For the time being, it's slightly quicker to check the length first.

File: projects/packages/forms/src/blocks/field-select/edit.js (hunk 6 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-select/edit.js:20]: I'd like to settle on what the field should be called and use that consistently. The original form components named the block `field-select` however gave the block a human readable label of "Dropdown" which was also used in the code too e.g. `JetpackDropdown`. 

Should this be "dropdown" as that's what most users might expect or "select" given it represents an actual select input?

File: projects/packages/forms/src/blocks/field-single-choice/deprecated.js (hunk 7 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-single-choice/deprecated.js:54]: As noted [here](https://github.com/Automattic/jetpack/pull/42890/files/e4ff0e2216784a2614d119ab755e380c7cc2fbbf#r2035186652), it won't make the check more future proof as the check below would still have to be updated in the event of further valid inner blocks being added

File: projects/packages/forms/src/blocks/field-textarea/edit.js (hunk 8 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-textarea/edit.js]: Nah, I think that's a rogue leftover after trying some different approaches for the inner Input block. I'll get rid of it. Thanks.

File: projects/packages/forms/src/contact-form/class-contact-form-field.php (hunk 9 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php]: Yeah, I came to the same conclusion it was for BC purposes. Thanks for looking into it.

**Comment by aaronrobertshaw** [comment]
:bug:  **Known Issue** :bug: 

Unfortunately, I think I broke the style syncing when adding some fields to a form. Possibly in: https://github.com/Automattic/jetpack/pull/42889/commits/9954d62f65a4173ea5f02a2fbd05709ff1565c64.

It will be worked on over the next couple of days, so ignore bugs there for the moment.

File: projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js (hunk 4 above)
Comment (talldan) [reply projects/packages/forms/src/blocks/field-multiple-choice/deprecated.js:54]: Ok, though there are ways that will make it more future proof:
- Return true if the are only option blocks, false otherwise
- Return false if there's a label and/or an options block present, true otherwise.

Both ways it wouldn't matter if a future new block type is supported.

**Comment by aaronrobertshaw** [comment]
Further to this [comment](https://github.com/Automattic/jetpack/pull/42890#issuecomment-2789459719), I've reverted the style syncing hook to an earlier state via https://github.com/Automattic/jetpack/pull/42890/commits/28e99d37734aa934c255ec42890414dad36371b2. 

This means that not all blocks (e.g. option blocks) are currently sync'd properly. It is still being worked on.

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 10]
```diff
@@ -740,9 +879,16 @@ public function render_radio_field( $id, $label, $value, $class, $required, $req
...
+		// TODO: Is it better to apply the option classes and styles to the wrapper or the label?
+		$label_class  = 'wp-block-jetpack-option grunion-field-label checkbox';
+		$label_class .= $this->is_error() ? ' form-error' : '';
+		$label_class .= $this->label_classes ? ' ' . $this->label_classes : '';
+		$label_class .= $this->option_classes ? ' ' . $this->option_classes : '';
+
 		$field  = "<div class='contact-form__checkbox-wrap'>";
 		$field .= "<input id='" . esc_attr( $id ) . "' type='checkbox' name='" . esc_attr( $id ) . "' value='" . esc_attr__( 'Yes', 'jetpack-forms' ) . "' " . $class . checked( (bool) $value, true, false ) . ' ' . ( $required ? "required aria-required='true'" : '' ) . "/> \n";
-		$field .= "<label for='" . esc_attr( $id ) . "' class='grunion-field-label checkbox" . ( $this->is_error() ? ' form-error' : '' ) . "' style='" . $this->label_styles . "'>";
+		$field .= "<label for='" . esc_attr( $id ) . "' class='" . esc_attr( $label_class ) . "' style='" . esc_attr( $this->_styles ) . esc_attr( $this->option_styles ) . "'>";
```
Comment (ramonjd) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php]:
```suggestion
		$field .= "<label for='" . esc_attr( $id ) . "' class='" . esc_attr( $label_class ) . "' style='" . esc_attr( $this->label_styles ) . esc_attr( $this->option_styles ) . "'>";
```

Comment (aaronrobertshaw) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php]: Thanks 🤦

File: projects/packages/forms/src/blocks/field-consent/edit.js (hunk 2 above)
Comment (talldan) [reply projects/packages/forms/src/blocks/field-consent/edit.js]: Another issue might be that block wrappers have their own ids (`id="block-6bb18e8e-1301-449d-880c-bdc272f0ad2d`), and in some cases the code is try set an id on a block wrapper and that isn't working. 🤔

**Comment by aaronrobertshaw** [comment]
I've added some transform and example definitions for fields using the inner blocks structure. 

There are still some questions about whether transformed fields should keep the same label, e.g. transforming a Name field to an Email and still having Name as a label doesn't make a lot of sense to me.

Additionally, there seems to be something off with the field block example definitions as they aren't reflecting the example definitions. I'll circle back to that on Monday.

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 11]
```diff
@@ -301,33 +333,94 @@ public function render() {
...
+
+			// Classes.
+			if ( ! empty( $label_classes ) ) {
+				$this->label_classes .= esc_attr( $label_classes );
+			}
+			if ( ! empty( $input_classes ) ) {
+				$class              .= $class ? ' ' . esc_attr( $input_classes ) : esc_attr( $input_classes );
+				$this->field_classes = $input_classes;
+			}
+			if ( ! empty( $option_classes ) ) {
```
Comment (ramonjd) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php:368]: Non urgent question:

In my testing I'm seeing that `optionclasses` passed to `Contact_Form_Field` will be added to the field wrapper element. 

```php
// Attributes passed to `new Contact_Form_Field()`
$attributes = array(
    ....some other attrs
    'optionclasses' => 'has-cheese',
);
```

```html
<div style="" class='grunion-field-checkbox-multiple-wrap lalala-wrap has-cheese-wrap grunion-field-wrap'  >
<fieldset ...>
```

Is that intentional?

Comment (ramonjd) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php:368]: Actually forget it. Sorry, I didn't see the `-wrap` suffix.

File: projects/packages/forms/src/contact-form/class-contact-form-plugin.php [hunk 12]
```diff
@@ -337,124 +391,196 @@ public static function block_attributes_to_shortcode_attributes( $atts, $type )
...
+					$atts['max']           = $inner_block['attrs']['max'] ?? '';
+					$input_attrs           = self::get_block_support_classes_and_styles( $block_name, $inner_block['attrs'] );
+					$atts['inputclasses']  = 'wp-block-jetpack-input';
+					$atts['inputclasses'] .= isset( $input_attrs['class'] ) ? ' ' . $input_attrs['class'] : '';
+					$atts['inputstyles']   = $input_attrs['style'] ?? null;
+				}
+
+				// The following handles when option blocks are a direct inner block for a field e.g. singular checkbox field.
+				if ( 'jetpack/option' === $block_name ) {
+					$atts['label']         = $inner_block['attrs']['label'] ?? $inner_block['attrs']['defaultLabel'] ?? '';
```
Comment (ramonjd) [inline projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Can a `jetpack/option` live next to a `jetpack/label`? 

Just wondering if `$atts['label']` set by the  `jetpack/label` block above will ever be overwritten here.

Comment (ramonjd) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: By the way, I checked in the editor and it doesn't look like `jetpack/option` and `jetpack/label` can be innerblock siblings. 

Just asking though in case I'm hallucinating again 😄

**Comment by talldan** [comment]
I've made some undo/redo fixes in https://github.com/Automattic/jetpack/pull/43036, which can be merged into this PR if the changes look good.

Some of these issues are also present in trunk, but by solving them it should hopefully make it easier to spot any undo issues that the new style syncing code causes.

File: projects/packages/forms/src/blocks/field-consent/edit.js (hunk 2 above)
Comment (talldan) [reply projects/packages/forms/src/blocks/field-consent/edit.js]: I've checked `trunk` and from what I can tell these instance ids do nothing because of the issue I mentioned above - the block wrapper has its own instance id that overrides the one the block edit functions try to provide.

The blocks that try to add these custom ids:
- Consent
- Checkbox
- Single / Multiple Choice

Even looking back at the PR that changed the ids to being specified via block props, #38916, I can see no purpose for them. It doesn't seem like they were added to mimic the frontend or for any accessibility reasons (pairing labels with inputs), the ids are added to divs. There are no styles that target the ids, and it'd be hard to do that because of the instance id.

My suggestion is to remove them from the new blocks. I'll make a PR.

edit: issue now resolved via #43055

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-consent/edit.js]: Sounds like a plan. Thanks for digging into the history here 🙇

File: projects/packages/forms/src/blocks/shared/hooks/use-synced-attributes.js [hunk 13]
```diff
@@ -0,0 +1,192 @@
...
+function getModifiedAttributes( sourceAttributes, attributeSets ) {
+	if ( ! sourceAttributes ) {
+		return {};
+	}
+
+	return Object.keys( sourceAttributes ).reduce( ( acc, key ) => {
+		// Use lodash `isEqual` to perform a deep comparison of the attributes.
+		// With `!==` this would return a lot of false positives where different blocks
+		// have objects with different references, but the same inner attribute values.
+		// TODO - replace this with not lodash.
```
Comment (aaronrobertshaw) [inline projects/packages/forms/src/blocks/shared/hooks/use-synced-attributes.js:90]: I had a quick look at alternatives here. 

Core uses `deepEqual` from the `fast-deep-equal` package. Unfortunately, that isn't already a dependency of the Jetpack Forms package. So given there are a lot of uses of Lodash, replacing this will be best done as part of a concerted effort to scrub Lodash out of the Forms package.

This isn't something we need to address to merge this PR

**Comment by aaronrobertshaw** [comment]
This PR branch now targets `trunk` as its base. 

The original base #42889 was proving difficult to keep up to date with tweaks to the underlying new form blocks without interfering with testing and fixes on this branch.

File: projects/packages/forms/src/blocks/field-telephone/index.js [hunk 14]
```diff
@@ -0,0 +1,48 @@
+import { Icon } from '@wordpress/components';
```
Comment (enejb) [inline projects/packages/forms/src/blocks/field-telephone/index.js:1]: Sometimes I in the jetpack code base I see 
```
import { Icon } from '@wordpress/components';
import { mobile } from '@wordpress/icons';
```
and other times
I see 
```
import { Icon, mobile } from '@wordpress/icons'; 
```
I am assuming the end result is the same thing. Does it make sense to just use the @wordpress/icons package ?

Since that Icon component is a bit more light wight?

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/field-telephone/index.js:1]: Both Icon components are light weight, so I don't think that aspect makes much difference in the scheme of things.

For me, I'd lean towards using `Icon` from the `@wordpress/components` package:
- This package is effectively a source of truth for WordPress components
- Contains some size logic to help ensure icons align with WordPress design systems
- There's also some validation before attempting to pass through additional props
- More flexible for future updates
- Jetpack already has `@wordpress/components` as a dependency

File: projects/packages/forms/src/blocks/field-telephone/deprecated.js [hunk 15]
```diff
@@ -0,0 +1,11 @@
+import INNER_BLOCKS_DEPRECATION from '../shared/deprecations/inner-blocks-deprecation';
+
+export default [
+	{
+		...INNER_BLOCKS_DEPRECATION,
+		attributes: {
+			...INNER_BLOCKS_DEPRECATION.attributes,
+			label: { type: 'string', default: 'Phone' },
```
Comment (andrewserong) [inline projects/packages/forms/src/blocks/field-telephone/deprecated.js:8]: (Nothing to action here): Tiny drive-by comment while I walk through the changes in the codebase: this `default: 'Phone'` does _not_ need a translate call because the original block did not translate this default label. Just thought I'd mention it in case anyone else runs into it.

File: projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js [hunk 16]
```diff
@@ -0,0 +1,154 @@
...
+			? __( 'Button Text', 'jetpack-forms' )
+			: __( 'Option Text', 'jetpack-forms', 0 );
+
+	const inputColorLabel = isChoicesBlock
+		? optionColorLabel
+		: __( 'Field Text', 'jetpack-forms', 0 );
+
+	const backgroundColorLabel = isChoicesBlock
+		? __( 'Background', 'jetpack-forms' )
+		: __( 'Field Background', 'jetpack-forms', 0 );
```
Comment (andrewserong) [inline projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: Are the zeros passed in to `__()` necessary? I thought that function only took two params 🤔

(This is just a drive-by comment, and it isn't urgent. I can fix these up tomorrow or next week if they're not there for a reason)

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: They're just copied and pasted from the original `JetpackFieldControls` component. So if it was "doing it wrong" so is this.

I suspect that now the fields have been migrated, those using this component from the `shared` folder won't need all that settings config. It probably isn't even used at the moment 🤷

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: I'll push a commit soon to clean up some of the dead code in this component and remove those odd extra params.

Comment (andrewserong) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: > They're just copied and pasted from the original JetpackFieldControls component. So if it was "doing it wrong" so is this [...] I'll push a commit soon to clean up some of the dead code

Ah, that makes sense. Thanks for tidying up! 🍻

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: Quick clean up done in https://github.com/Automattic/jetpack/pull/42890/commits/ef2cbe36cacb7b5f335acf8def9a3d3ad761742f. After an equally quick before and after comparison I didn't spot any regressions for field controls.

Comment (anomiex) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: FYI: The 0 is a workaround for a minifier optimization that can break i18n.

GlotPress relies on seeing calls like `__( 'string literal', 'textdomain' )` in order to extract strings for translation. However, the minifier may convert code like
```js
	const backgroundColorLabel = isChoicesBlock
		? __( 'Background', 'jetpack-forms' )
		: __( 'Field Background', 'jetpack-forms' );
```
into
```js
	const backgroundColorLabel = __( isChoicesBlock ? 'Background' : 'Field Background', 'jetpack-forms' );
```
which won't be found by GlotPress because the parameter is no longer a string literal.

Adding the dummy "0" parameter is one way to avoid that transformation. Another would be to use `_x()`, like
```js
	const backgroundColorLabel = isChoicesBlock
		? _x( 'Background', 'Some context text', 'jetpack-forms' )
		: _x( 'Field Background', 'Some different context text', 'jetpack-forms' );
```
(note the two contexts need to be different), or even just
```js
	const backgroundColorLabel = isChoicesBlock
		? __( 'Background', 'jetpack-forms' )
		: _x( 'Field Background', '', 'jetpack-forms' );
```
(note passing an empty string for the context seems to be equivalent to `__()`, but the minifier doesn't know that).

Since this is an easy thing to accidentally have happen, we have [a custom webpack plugin](https://www.npmjs.com/package/@automattic/i18n-check-webpack-plugin) that tries to detect when strings go missing in the production build. 🙂

Comment (andrewserong) [reply projects/packages/forms/src/blocks/shared/components/jetpack-field-controls.js]: Thanks for the context @anomiex! In this case, the code could be removed because it wasn't being used, but that's great to know for next time 👍

**Comment by simison** [comment]
FYI, I added label to disable code coverage test as things like that can be worked on separate PRs, but feel free to remove label if you need to run the check.

image
