### PR TITLE
Map block: Do not render the actual map if in block preview mode

### LINKED ISSUE #93852: Unable to Create New Page In Mobile Browser
### Quick summary

I am unable to create a new page in my mobile browser. Tested in both Safari and Chrome; when I create a new page from the Dashboard, it takes a moment to load. The patterns appear briefly, and then the page refreshes itself. The patterns appear again for a short time, and then the entire page closes and I see a browser error. 

iPhone 15
iOS 17.5.1
Tested in Chrome and Safari

### Steps to reproduce

1. Start on mobile Dashboard in a browser, not the Jetpack app
2. Use mobile Dashboard navigation to Create a New Page
3. The new page will not load, and the browser will eventually return an error message. 

### What you expected to happen

A new post will be created which I can then edit and publish.

### What actually happened

The browser returns an error message. If I hit back from there, it brings me to the last post I was working on, not back to the Dashboard. 

https://github.com/user-attachments/assets/5210d62f-f34f-4259-8716-feda0d03e549

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by zaguiini**
Fixes https://github.com/Automattic/wp-calypso/issues/93852.

## Proposed changes:

If rendering the Map block in preview mode (e.g., Patterns list) do not render the actual map but instead the placeholder image. This reduces the memory footprint and prevents crashes on iOS Safari.

https://github.com/user-attachments/assets/06cd3e24-550e-48a0-a9c7-70091ccbd3aa

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/wp-calypso/issues/93852

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Follow the [Simple and Atomic instructions](https://github.com/Automattic/jetpack/pull/39768#issuecomment-2412208098) to get the correct Jetpack version running.

### Atomic

It's much easier to test the fix on mobile by testing on your WoA site. 

### Simple

Proxy `public-api.wordpress.com` and your `siteaddress.wordpress.com` on the web so you can see the map preview image within the patterns list.

| Before | After |
| ------ | ------ |
|  Screenshot 2024-10-14 alle 6 22 07 PM | Screenshot 2024-10-14 alle 6 21 27 PM |

### CODE REVIEW

File: projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: other
+
+Map block: Use block editor store preview flag to determine whether or not to display the placeholder
```
Comment (p-jackson) [inline projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode]: Maybe more like? Rather than referring to stores in the release notes.

```suggestion
Map block: Display a static map image when the block is rendered in a pattern preview
```

File: projects/plugins/jetpack/extensions/blocks/map/edit.js [hunk 2]
```diff
@@ -223,14 +236,15 @@ const MapEdit = ( {
 
 	let content;
 
-	if ( preview ) {
+	if ( preview || isPreviewMode ) {
```
Comment (p-jackson) [inline projects/plugins/jetpack/extensions/blocks/map/edit.js]: The distinction between `preview` and `isPreviewMode` is kind of confusing for the casual reader of the code. I can't really think of a name that would be clearer though.

File: projects/plugins/jetpack/extensions/blocks/map/edit.js [hunk 3]
```diff
@@ -223,14 +236,15 @@ const MapEdit = ( {
...
 		const mapStyleObject = styles.find( styleObject => styleObject.name === mapStyle );
 
 		content = (
 			<div>
 				<img
 					alt={ __( 'Map Preview', 'jetpack' ) }
 					src={ mapStyleObject ? mapStyleObject.preview : previewPlaceholder }
+					style={ { width: '100%', maxHeight: '400px', objectFit: 'cover' } }
```
Comment (p-jackson) [inline projects/plugins/jetpack/extensions/blocks/map/edit.js]: This extra style unexpectedly changes the height of the map in the preview.

This is the hover preview, which uses the `preview` attribute from [the block's example data](https://arc.net/l/quote/ngxlkfad).

| Before | After |
| --- | --- |
| CleanShot 2024-10-15 at 15 36 39 | CleanShot 2024-10-15 at 12 49 51@2x |

It also changes the appearance of the pattern previews. The way they looked before matches the aspect ratio of the map when it is inserted into the page. So the preview was more accurate the way it was.

| Before | After |
| --- | --- |
| CleanShot 2024-10-15 at 12 52 35@2x | CleanShot 2024-10-15 at 12 54 14@2x |

Maybe something like this will fix it?

```suggestion
					style={ { width: '100%', maxHeight: mapHeight ?? 400, objectFit: 'cover' } }
```

Comment (p-jackson) [reply projects/plugins/jetpack/extensions/blocks/map/edit.js]: Actually looks like it has to be this. Something about adding those styles changes the way the hover preview works for some reason.

```suggestion
					style={ preview ? null : { width: '100%', height: mapHeight ?? 400, objectFit: 'cover' } }
```

**Review by p-jackson — COMMENTED** [review]
Can confirm that this replaces previews with images.

However I'm no longer able to reproduce the crash without this diff applied either. For some reason I no longer see map previews because I get an error about a missing token (a map API token maybe? I've never seen this before, it might be something to do with WoA dev blogs, because it works fine on a regular WoA site)

https://github.com/user-attachments/assets/d9c92e9a-ad6d-4464-aea7-91e7d01a3393

It's not crashing with the patch applied either though, and I think switching the map widget for the static image is the right move.

File: projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode (hunk 1 above)
Comment (zaguiini) [reply projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode]: Oh, great rewrite. I was stuck thinking about what to write and completely biased by the implementation :D

**Comment by zaguiini** [comment]
Thanks for the review @p-jackson!

>For some reason I no longer see map previews because I get an error about a missing token 

That's why it's not crashing. Since it's unable to render the tiles, it's not consuming a lot of memory. Also, because it uses a variable amount of memory (variable number of tiles depending on the map dimensions), the crashes were intermittent.

You're seeing this API error in the unpatched version, right? Or are you getting the error even with the patch applied?

>I think switching the map widget for the static image is the right move.

Yep, it consumes way less memory. Let's move forward with it.

File: projects/plugins/jetpack/extensions/blocks/map/edit.js (hunk 2 above)
Comment (zaguiini) [reply projects/plugins/jetpack/extensions/blocks/map/edit.js]: I'm thinking of dropping that attribute 🤷🏻

Comment (zaguiini) [reply projects/plugins/jetpack/extensions/blocks/map/edit.js]: Just dropped it.

Block list:

image

Pattern preview:

| Site editor | Sidebar | Pattern modal |
| ---------- | -------- | -------------- |
| image | image | image |

**Comment by p-jackson** [comment]
> You're seeing this API error in the unpatched version, right? Or are you getting the error even with the patch applied?

@zaguiini Yes I do. When I'm on a dev blog using the production version I get the token error. So applying the patch makes no difference to how the block is rendered once it's inserted.

The token error goes away when I'm _not_ on a dev blog.

I thought the Jetpack beta tester plugin only worked on dev blogs ... maybe I don't need to do that.

**Comment by zaguiini** [comment]
>I thought the Jetpack beta tester plugin only worked on dev blogs ... maybe I don't need to do that.

I'm able to add it to a regular WoA site. [These instructions](https://github.com/Automattic/jetpack/pull/39768#issuecomment-2412208098) worked for me.

**Comment by p-jackson** [comment]
A note on the use of the unstable API:

If `__unstablePreviewMode` disappears, then it will revert back to the existing behaviour. So we aren't in danger of the editor crashing if the API goes away.

If the API were to be removed, the block editor will have to use something else (since they need to deal with preview mode too) so I guess if it happens we'll just migrate to whatever the new block editor thing is.

The alternative to `__unstablePreviewMode` would be to use [a CSS selector like was suggested here](https://github.com/Automattic/wp-calypso/issues/93852#issuecomment-2348184207). But CSS selectors are prone to breaking too, perhaps more so than `__unstable` APIs. At least we might see the API change in a Gutenberg release note.

**Comment by zaguiini** [comment]
>The alternative to __unstablePreviewMode would be to use https://github.com/Automattic/wp-calypso/issues/93852#issuecomment-2348184207. But CSS selectors are prone to breaking too, perhaps more so than __unstable APIs. At least we might see the API change in a Gutenberg release note.

I agree with this 100%.

@youknowriad @jeherve any strong opinions against using `__unstableIsPreviewMode`? It's the only viable way (that we've found) to not render the map within the pattern preview.

**Comment by youknowriad** [comment]
> __unstableIsPreviewMode 

Assuming rendering a placeholder is a good UX tradeoff, the `__unstableIsPreviewMode ` API is fine to use IMO, I think ultimately we should stabilize it.

File: projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: other
+
+Map block: Display a static map image when the block is rendered in a pattern preview
```
Comment (p-jackson) [inline projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode:4]: Feels like we also need a release note about the change to the block attribute now

**Review by p-jackson — DISMISSED** [review]
I'm not familiar with the process of deprecating block attributes. I don't know if we need a whole `deprecated/v3/index.js` now.

But the change works as expected, I no longer get crashes in mobile Safari when I open up the inserter menu. I also like wrapping the hover preview and pattern preview logic into one.

**Comment by zaguiini** [comment]
>I don't know if we need a whole deprecated/v3/index.js now.

We're technically removing an attribute from the component, but it's an internal one. So I don't think we need a new version.

File: projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode (hunk 4 above)
Comment (zaguiini) [reply projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode:4]: I'm unsure since it's an internal attribute used only within the editor to signalize "skip rendering the actual map." We're not really changing any behavior, only internals.

Comment (p-jackson) [reply projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode:4]: Since attributes are written to post content they don't seem internal. We need to stay compatible with the existing data in folks' databases. The chances that someone would have post content that includes `preview:true` is pretty low though, since it's not something users can control in the block settings. And it's also quite hard to do manually using the code editor. Maybe it's a 0% chance someone would have a block with this attribute in the database? It's kind of hard to tell.

Maybe someone manually created a block pattern using a text editor and they used the `preview` attribute? I'm not sure how far fetched this is.

Comment (zaguiini) [reply projects/plugins/jetpack/changelog/display-map-block-as-preview-if-in-block-preview-mode:4]: Fair. Let's make them aware.

**Review by p-jackson — APPROVED** [review]

**Comment by p-jackson** [comment]
> I'm not familiar with the process of deprecating block attributes. I don't know if we need a whole `deprecated/v3/index.js` now.

We've found previous examples of removing block attributes in patch releases.
#36808
#36724
