### PR TITLE
Fix undefined notice on polldaddy shortcut.

### LINKED ISSUE #2874: Undefined variable notice in Polldaddy shortcode
I get this notice on the front-end for a page that contains the `[polldaddy]` shortcode:

> NOTICE: wp-content/plugins/jetpack/modules/shortcodes/polldaddy.php:48 - Undefined variable: type
require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/twentytwelve/page-templates/full-width.php'), get_template_part, locate_template, load_template, require('/themes/twentytwelve/content-page.php'), the_content, apply_filters('the_content'), call_user_func_array, do_shortcode, preg_replace_callback, do_shortcode_tag, call_user_func, PolldaddyShortcode->polldaddy_shortcode, PolldaddyShortcode->get_async_code

### PR DESCRIPTION
**Pull request by osiux**
Fixes #2874

I was able to reproduce the issue using type "slider" attribute on the shortcode.

### CODE REVIEW

**Comment by zinigor** [comment]
Thanks for catching that one! Tested, confirm that it fixes the notices. @dereksmart what do you say we include this into 3.8.1?

File: modules/shortcodes/polldaddy.php [hunk 1]
```diff
@@ -45,7 +45,7 @@ private function get_async_code( array $settings, $survey_link ) {
 			'<div class="pd-embed" data-settings="'
 			. esc_attr( json_encode( $settings ) )
 			. '"></div>';
-		if ( $type === 'button' ) {
+		if ( $settings['type'] === 'button' ) {
```
Comment (dereksmart) [inline modules/shortcodes/polldaddy.php]: :yoda: style please!
`button === $settings['type']`

(same for below changeset)

**Comment by osiux** [comment]
@dereksmart done!
