### PR TITLE
Fixes de/activation hooks that didn't work.

### LINKED ISSUE #13013: Full screen "set up" Jetpack CTA was removed in 7.5
Conversation and data here: p1HpG7-7dq-p2

**Expected behavior:**

When a customer installs and activates Jetpack from within the plugin directory inside wp-admin, a full screen "set up jetpack" prompt takes over wp-admin to help guide the customer to set up Jetpack. 

Screen Shot 2019-07-09 at 2 02 08 PM

**What happened:** 

with 7.5, this prompt was accidentally removed. If you Install and activate Jetpack, you'll notice a smaller connection banner, which doesn't drive the same amount of attention and set up as the full-screen page.

Screen Shot 2019-07-09 at 2 04 11 PM

**To test:**

* w/ jetpack 7.5 - you'll see the banner, not the full page prompt. Install and activate Jetpack from within the plugin directory within wp-admin

* w/ Jetpack 7.4 or prior, you'll see the full page prompt after you install and activate it

### PR DESCRIPTION
**Pull request by zinigor**
Because statements were moved to a different file, the hook was called incorrectly, causing problems, like activation banner never showing.

Fixes #13013

#### Changes proposed in this Pull Request:
* Adds activation/deactivation hooks back to Jetpack.

#### Testing instructions:

* Disconnect jetpack, reset options using the footer link.
* Deactivate Jetpack from the plugins view.
* Activate Jetpack using the plugins view link.
* Make sure you see the full-screen banner covering the entire plugins list.

#### Proposed changelog entry for your changes:
* Fixed broken activation/deactivation scripts.

### CODE REVIEW

**Review by dereksmart — APPROVED** [review]
Bummer. But thank you for finding and fixing! 

As we discussed in Slack, let's make sure to get tests in for this. Opened an issue for 7.6 milestone here #13060

File: jetpack.php [hunk 1]
```diff
@@ -187,5 +187,8 @@ function jetpack_admin_missing_autoloader() {
 	return;
 }
 
+register_activation_hook( __FILE__, array( 'Jetpack', 'plugin_activation' ) );
+register_deactivation_hook( __FILE__, array( 'Jetpack', 'plugin_deactivation' ) );
```
Comment (dereksmart) [inline jetpack.php]: Just a note that in this current place, it's possible for it to not get hit if the site is on an unsupported version of WP or PHP, right? Is it better to move to the top? The problem with moving to the top is we don't know what code the hook will trigger, and it could be incompatible code which would error.

Comment (zinigor) [reply jetpack.php]: Yes, you're right, it could trigger code that won't be compatible with the current software. We could try to  make sure we don't use anything incompatible in activation/deactivation hooks, but it would not be trivial, or easily maintainable.
Do we even need hooks in case Jetpack is not supported on the current software? The only case would be to clean up the options in case Jetpack just became unusable after an update, and the user wants to disable it.

**Comment by zinigor** [comment]
Ported into `branch-7.5` in fb0af3312.
