### PR TITLE
SEO Tools: remove obsolete meta title tag

### LINKED ISSUE #7190: Remove outputting 'meta name="title"' since <title> is standardized.
#### Steps to reproduce the issue

On any WPCOM site, Jetpack seems to be outputting site titles like`<meta name="title" content="Test Page | Test Site on WordPress.com" />` (slightly different on AT sites). The title format also tends not to match the user's intended set title in Settings > General.

Since all major search engines and other reputable social sites and tools use the standardized `<title>` tag (and we output correctly there), we should omit this.

[It's also not listed on W3C](https://www.w3schools.com/tags/tag_meta.asp), so it doesn't appear to even be valid HTML.

### PR DESCRIPTION
**Pull request by vindl**
Since we are already setting the `<title>` tags correctly, we no longer need to use the `<meta name="title" ...>` tag.

Fixes #7190

#### Testing instructions:

1. Use Jetpack test site with a professional plan. 
2. In Calypso, navigate to `settings/traffic/{siteSlug}`.
3. Set custom title formats for that site.
4. Verify that those custom title formats are no longer included in `<meta name="title" ...>` tags.

### CODE REVIEW

File: modules/seo-tools/jetpack-seo.php [hunk 1]
```diff
@@ -114,30 +114,14 @@ public function meta_tags() {
...
-		$meta['title'] = sprintf( _x( '%1$s', 'Site Title', 'jetpack' ), get_bloginfo( 'title' ) );
-
-		if ( ! empty( $site_host ) ) {
-			$meta['title'] = sprintf(
-				_x( '%1$s on %2$s', 'Site Title on WordPress', 'jetpack' ),
-				get_bloginfo( 'title' ),
-				$site_host
-			);
-		}
+		$site_host = apply_filters( 'jetpack_seo_site_host', '' );
```
Comment (jeherve) [inline modules/seo-tools/jetpack-seo.php]: Since we don't use `$site_host` anymore, maybe we should delete and deprecate this filter?
https://github.com/Automattic/jetpack/blob/master/class.jetpack.php#L5930

Comment (vindl) [inline modules/seo-tools/jetpack-seo.php]: Agreed and removed, I overlooked that one. Should I leave the doc block with `@depreceted` or is it fine to delete it too?

Comment (jeherve) [inline modules/seo-tools/jetpack-seo.php]: That's a good question. @dereksmart How do you think we should handle that to make sure developer.jetpack.com stays up to date?

Comment (eliorivero) [inline modules/seo-tools/jetpack-seo.php]: That phpDoc should stay there introducing `@deprecated`. Maybe something like
```
* @deprecated 5.0 This filter is no longer used.
```
should be enough. Maybe add why, but don't think it's necessary.

Comment (vindl) [inline modules/seo-tools/jetpack-seo.php]: Updated in 2fc760961e635ac47518dd9363a3fc35b496ea48.

**Comment by eliorivero** [comment]
I don't think this will work for the doc parser, that is, a doc block with no filter to relate to
https://github.com/Automattic/jetpack/blob/2fc760961e635ac47518dd9363a3fc35b496ea48/modules/seo-tools/jetpack-seo.php#L108
