### PR TITLE
Simple payments: Hide paypal when invalid

### LINKED ISSUE #17641: Pay with PayPal Block: error when attempting to process payment for invalid price
Follow-up to #17531. 

#### Steps to reproduce the issue

1. In the editor, add a Pay with PayPal block.
2. Enter a negative amount
3. See an error message.
4. Save and publish post anyway.
5. Attempt to purchase product.

PayPal returns a 500 and the frontend displays “We are sorry, there was a configuration problem. Please contact the site owner. Error:SP17”.

Maybe we shouldn't render the block on the frontend when there are validation errors?

cc @retrofox 

------

p8oabR-za-p2#comment-4694

### PR DESCRIPTION
**Pull request by dsas**
When the paypal block was misconfigured it was still rendered on the
front-end. When people tried to use it they would receive an opaque
error message from paypal.

To resolve this, the paypal block will not be rendered on the front end
if it's misconfigured. There are plenty of messages displayed in the
editor if it is misconfigured so post-editors should be able to see any
problems before they happen. This makes it more consistent with the
donations block which does not display anything if not connected to
stripe.

Fixes #17641
#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

1. Start up jetpack, jurassic tube etc or a wpcom site
2. Apply these changes
3. Ensure your site has either a wpcom premium or above plan or a jetpack complete plan
4. Create a new post
5. Add a Pay with paypal block
6. Without filling the details in, press Update
7. View the post in the front-end
8. You should see that the block does not appear
9. Repeat omitting various details e.g. title, email address, or invalid details e.g. negative currency, invalid email
10. Edit the post again, get the productId from code mode Markup 2022-01-13 at 16 38 40
11. Add a shortcode block with the contents like `[simple-payment id="THE_PRODUCT_ID"]Testing123[/simple-payment]`
12. View the post again, ensure the shortcode version renders too.

### CODE REVIEW

**Comment by rcrdortiz** [comment]
Reviewed code. Tested on WPCom. Everything works well, but I did notice that when using the shortcode version of the Pay with PayPal block, the pay button isn't visible for me. Does this happen to you too?
Captura de pantalla 2022-01-14 a las 11 34 20

**Review by rcrdortiz — DISMISSED** [review]

**Comment by dsas** [comment]
@rcrdortiz I can't reproduce that on WP.com or on a standalone Jetpack site. Does it happen without my changes applied too?

**Comment by dsas** [comment]
> when using the shortcode version of the Pay with PayPal block, the pay button isn't visible for me. Does this happen to you too?

@rcrdortiz can reproduce this with and without my changes, so we're happy it's not something introduced here.

File: projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php [hunk 1]
```diff
@@ -51,6 +51,11 @@ function render_block( $attr, $content ) {
 	}
 
 	$simple_payments = Jetpack_Simple_Payments::getInstance();
+
+	if ( ! $simple_payments->is_valid( $attr ) ) {
+		return '';
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php:56]: Shouldn't we return content here as well, like above?

```suggestion
		return $content;
```

File: projects/plugins/jetpack/modules/simple-payments/simple-payments.php [hunk 2]
```diff
@@ -149,15 +149,42 @@ function is_enabled_jetpack_simple_payments() {
...
+
+	/**
+	 * Creates the content from a shortcode
+	 *
+	 * @param array $attrs Shortcode attributes.
+	 * @param mixed $content unused.
+	 *
+	 * @return string|void
+	 */
+	public function parse_shortcode( $attrs, $content = false ) {
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/simple-payments/simple-payments.php:182]: You'll need to add a rule here so we can merge this:

```suggestion
	public function parse_shortcode( $attrs, $content = false ) { // phpcs:ignore VariableAnalysis.CodeAnalysis.VariableAnalysis.UnusedVariable
```

**Review by jeherve — COMMENTED** [review]
I have some minor questions / comments below.

File: projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php (hunk 1 above)
Comment (dsas) [reply projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php:56]: No, I think that'll defeat what we're trying to achieve here, but perhaps there is something I'm missing.

If we return the content here it'll show a product which can't be bought, with no error message. Basically it would look like this:
image

The link that says 'Click here to purchase' won't do anything - it depends upon the the rest of the code in this method to make it work.

It's probably ok to do that above - because people can see something in whatever context it is, and hopefully click through to the post to buy the product. Perhaps even that should be improved, but that's a separate issue I feel.

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/simple-payments/simple-payments.php:56]: That makes sense! 👍

**Review by jeherve — APPROVED** [review]

**Comment by dsas** [comment]
Deployed r238400-wpcom
