### PR TITLE
General: move requires and namespaces out of the main plugin file

### LINKED ISSUE #12634: DNA: use of namespace before PHP version check causes a fatal error on PHP 5.2
#### Steps to reproduce the issue

1. On a PHP 5.2 site, using WordPress 5.1, load the current development version of Jetpack (currently in the `feature/jetpack-packages` branch)
2. Get the following error: 
```
PHP Parse error:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /home/jptest/public_html/wp-content/plugins/jetpack-dev/jetpack.php on line 3
```
3. We'll need to avoid using PHP 5.3+ syntax before the actual PHP version check in `jetpack.php`.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #12634

#### Changes proposed in this Pull Request:

Moving most things into a separate file should solve our issues, as jetpack.php will not include any PHP 5.3+ code anymore, and the checks we have in that file will ensure that no other file is loaded.

#### Testing instructions:

* I am afraid the only way to test this is on a site that runs PHP 5.2. One of the sites in our testing pool should be good for that test. Reach out to me for more info.
* Other than that, you can try to use the plugin as usual on any other site.

#### Proposed changelog entry for your changes:

* None

### CODE REVIEW

File: jetpack.php [hunk 1]
```diff
@@ -102,9 +70,9 @@ function jetpack_should_use_minified_assets() {
 	 * @since 7.2.0
 	 */
 	function jetpack_admin_unsupported_wp_notice() { ?>
-        <div class="notice notice-error is-dismissible">
```
Comment (jeherve) [inline jetpack.php]: This was replacing spaces by tabs.

File: jetpack.php [hunk 2]
```diff
@@ -11,27 +9,26 @@
...
-defined( 'JETPACK_CLIENT__HTTPS' )           or define( 'JETPACK_CLIENT__HTTPS', 'AUTO' );
-defined( 'JETPACK__GLOTPRESS_LOCALES_PATH' ) or define( 'JETPACK__GLOTPRESS_LOCALES_PATH', JETPACK__PLUGIN_DIR . 'locales.php' );
-defined( 'JETPACK__API_BASE' )               or define( 'JETPACK__API_BASE', 'https://jetpack.wordpress.com/jetpack.' );
-defined( 'JETPACK_PROTECT__API_HOST' )       or define( 'JETPACK_PROTECT__API_HOST', 'https://api.bruteprotect.com/' );
-defined( 'JETPACK__WPCOM_JSON_API_HOST' )    or define( 'JETPACK__WPCOM_JSON_API_HOST', 'public-api.wordpress.com' );
-
-defined( 'JETPACK__SANDBOX_DOMAIN' ) or define( 'JETPACK__SANDBOX_DOMAIN', '' );
-
-defined( 'JETPACK__DEBUGGER_PUBLIC_KEY' ) or define(
+define( 'JETPACK__VERSION',             '7.5-alpha' );
```
Comment (jeherve) [inline jetpack.php]: These were minor changes (spacing and replacing `or` by `||`).

File: jetpack.php [hunk 3]
```diff
@@ -174,11 +144,11 @@ function jetpack_admin_unsupported_php_notice() { ?>
 	require $jetpack_autoloader;
 } else {
 	if ( defined( 'WP_DEBUG' ) && WP_DEBUG ) {
-		error_log(
+		error_log( // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
 			sprintf(
 				/* translators: Placeholder is a link to a support document. */
-				__( 'Your installation of Jetpack is incomplete. If you installed Jetpack from GitHub, please refer to <a href="%1$s" target="_blank" rel="noopener noreferrer">this document</a> to set up your development environment.', 'jetpack' ),
```
Comment (jeherve) [inline jetpack.php]: It's useless to use HTML here, since it's in the error log.

File: jetpack.php [hunk 4]
```diff
@@ -174,11 +144,11 @@ function jetpack_admin_unsupported_php_notice() { ?>
...
-				esc_url( 'https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md' )
```
Comment (jeherve) [inline jetpack.php]: No need to escape that URL here.

File: load-jetpack.php [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+function jetpack_should_use_minified_assets() {
+	if ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) {
+		return false;
+	}
+	return true;
+}
+add_filter( 'jetpack_should_use_minified_assets', 'jetpack_should_use_minified_assets', 9 );
+
+// @todo: Abstract out the admin functions, and only include them if is_admin()
+require_once JETPACK__PLUGIN_DIR . 'class.jetpack.php';
```
Comment (lezama) [inline load-jetpack.php]: do we break something if we put all the `require_once` at the top?

**Review by lezama — APPROVED** [review]

File: load-jetpack.php (hunk 5 above)
Comment (jeherve) [reply load-jetpack.php]: I haven't tried, I followed how things were before they were moved to a separate file.

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.5` in 171ece1998c64deeb959188d79577947b0d80ff8

**Comment by simison** [comment]
Looks like this PR broke the splash screen that appears right after activating the plugin:

### Before
image


### After
image
