### PR TITLE
Jetpack: Check block dependencies after build

### LINKED ISSUE #28561: Slideshow: loads the editor JS on every page view
### Impacted plugin

Jetpack

### Quick summary

The Slideshow block currently loads the editor JS on every page view. This is a huge amount of JS, which severely affects page performance. The issue appears to have started with #27936, because `view.js` now imports from `slideshow.js`, which imports from the editor.

This is a classic case of insufficient modularity; the function that `view.js` is importing from `slideshow.js` (`paginationCustomRender`) should be split into its own module, that doesn't depend on the editor.

### Steps to reproduce

1. Create a simple page with a slideshow
2. Load the page on a browser, with DevTools open
3. Observe that a large amount of JS gets loaded, including the editor and all of its dependencies (React, moment, etc.)

### A clear and concise description of what you expected to happen.

The editor and its dependencies should not be loaded on a regular page view.

### What actually happened

The editor and its dependencies were loaded on a regular page view.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Block view scripts should avoid large dependencies such as React. Add a script checking the `view.asset.php` files to ensure these aren't added accidentally.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #28561

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* Revert 87eb8515cd363e43852a624df3563b264ff247e7 and try building Jetpack. It should fail with appropriate messages.
* Try making various adjustments to the configuration arrays and try building.

### CODE REVIEW

File: projects/plugins/jetpack/tools/check-block-assets.php [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+ */
+
+// phpcs:disable WordPress.Security.EscapeOutput.OutputNotEscaped -- This is not WordPress code.
+
+/**
+ * Non-WP dependencies to check for.
+ *
+ * @var string[]
+ */
+$bad_deps = array(
```
Comment (anomiex) [inline projects/plugins/jetpack/tools/check-block-assets.php:16]: This is all the non-WP scripts externalized by `@wordpress/dependency-extraction-webpack-plugin`, since all seem large.

File: projects/plugins/jetpack/tools/check-block-assets.php [hunk 2]
```diff
@@ -0,0 +1,170 @@
...
+	'react',
+	'react-dom',
+);
+
+/**
+ * WP dependencies to allow.
+ *
+ * @var string[]
+ */
+$ok_wp_deps = array(
```
Comment (anomiex) [inline projects/plugins/jetpack/tools/check-block-assets.php:30]: I went with a whitelist here versus the above blacklist since it seems likely new packages should be checked before being allowed.

This list consists of all the Gutenberg packages that are registered with WordPress and that don't depend on anything in `$bad_deps`. Plus `wp-polyfill`, which is often added by the extraction plugin.

File: projects/plugins/jetpack/tools/check-block-assets.php [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+	'wp-url',
+	'wp-warning',
+);
+
+/**
+ * Blocks allowed to have extra dependencies.
+ *
+ * @var string[][] Keys are block names, value is an array of dependencies to not complain about.
+ */
+$allowed = array(
```
Comment (anomiex) [inline projects/plugins/jetpack/tools/check-block-assets.php:61]: These are all the current blocks with dependencies the script would complain about. Feel free to consider this a todo list. 😀

**Review by sgomes — COMMENTED** [review]
Thank you so much, @anomiex! This looks great from a library / performance point of view! 👍

The allowlist is also great, in that I now have a small work list of items to try and tackle 😄

**Review by jeherve — APPROVED** [review]
This tests well for me, nice work!
