### PR TITLE
Calypsoify: Refactor and add autoupdate functionality

### LINKED ISSUE #10474: Mods.js throws TypeError when using jQuery alias ($)
The mods.js file includes a jQuery alias ($) that throws a TypeError and probably needs to be replaced with `jQuery` - https://github.com/Automattic/jetpack/blob/2a01b10ba931c94f79c8add0f2dea06c4f5892c1/modules/calypsoify/mods.js#L34

#### Steps to reproduce the issue

1. Make sure `JETPACK_DEV_DEBUG` is set to true.
2. Go to any page in the admin dashboard.
3. Append `calypsoify=1` to the URL to enable Calypsoify.
4. Check console for error.

#### What I expected
Expected no TypeError to be thrown.

#### What happened instead
TypeError was thrown.

**Screenshots**
screen shot 2018-10-29 at 8 13 26 am

### PR DESCRIPTION
**Pull request by georgestephanis**
Iterations on the current pass.  Reorganize some assets, tidy up some formatting and code patterns, convert the css to scss to make for easier maintenance going forward and abstract out the color codes to allow for semantic renaming in a future pass.

Oh, and add autoupdate management functionality to the plugins page.

pageshot of plugins test local wordpress thingy wordpress 2018-11-09-0843 24

Fixes #10474

#### Changes proposed in this Pull Request:

* Improve Calypso integration for relevant sites, and add admin ui autoupdate functionality.

#### Testing instructions:

* Install some plugins that are not in the repository (you should be able to select some from jurassic.ninja/specialops)
* Open your dev console and keep an eye out for js errors 
* Visit `/wp-admin/plugins.php?calypsoify=1`
* Test out the autoupdate plugin toggles
* Test out the bulk-select of auto-updates 
* Visit `/wp-admin/` to clear calypsoify skin.

### CODE REVIEW

File: modules/calypsoify/mods-gutenberg.js [hunk 1]
```diff
@@ -1,7 +1,7 @@
 /* global calypsoifyGutenberg */
 jQuery( function( $ ) {
-	var editPostHeaderInception = setInterval( function() {
-		var $editPostHeader = $( '.edit-post-header' );
+	const editPostHeaderInception = setInterval( function() {
```
Comment (dereksmart) [inline modules/calypsoify/mods-gutenberg.js]: Let's actually keep it `var` - since our configs is not yet set up to approve these, it's throwing errors on build and in the CI.

File: modules/calypsoify/class.jetpack-calypsoify.php [hunk 2]
```diff
@@ -38,11 +38,134 @@ public function setup() {
...
+
+		$autoupdating_plugins = Jetpack_Options::get_option( 'autoupdate_plugins', array() );
+		// $autoupdating_plugins_translations = Jetpack_Options::get_option( 'autoupdate_plugins_translations', array() );
+		if ( 'autoupdate' === $column_name ) {
+			// Shamelessly swiped from https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/client/components/forms/form-toggle
+			?>
+
+			<span class="form-toggle__wrapper">
+				<input
+						id="autoupdate_plugin-toggle-<?php echo esc_attr( $slug ) ?>"
```
Comment (dereksmart) [inline modules/calypsoify/class.jetpack-calypsoify.php]: Supersized indents!

File: modules/calypsoify/class.jetpack-calypsoify.php [hunk 3]
```diff
@@ -38,11 +38,134 @@ public function setup() {
...
+		return $bulk_actions;
+	}
+
+	public function handle_bulk_actions_plugins( $redirect_to, $action, $slugs ) {
+		$redirect_to = remove_query_arg( array( 'jetpack_enable_plugin_autoupdates', 'jetpack_disable_plugin_autoupdates' ), $redirect_to );
+		if ( in_array( $action, array( 'jetpack_enable_plugin_autoupdates', 'jetpack_disable_plugin_autoupdates' ) ) ) {
+			$list = Jetpack_Options::get_option( 'autoupdate_plugins', array() );
+			$initial_qty = sizeof( $list );
+
+			if ( $action === 'jetpack_enable_plugin_autoupdates' ) {
```
Comment (dereksmart) [inline modules/calypsoify/class.jetpack-calypsoify.php]: yoda-ize

**Review by dereksmart — DISMISSED** [review]
Just a few minor nitpicks for now, with a couple of over-arching things we need to look at: 

1. I'm not seeing the success notices (via toggling). Doesn't look like anything in the .js to handle the `wp_send_json_success` sent from PHP yet, so probably just haven't gotten to it yet. 
2. We will need to add some logic to disable the toggles for plugins that are not in the repo (cannot set to auto-update)

Over all, looking good!

File: modules/calypsoify/mods-gutenberg.js (hunk 1 above)
Comment (georgestephanis) [reply modules/calypsoify/mods-gutenberg.js]: Swapping back, but our precommit checks are conflicting with some of our configs in ci it seems --

screen shot 2018-10-30 at 10 28 37 am

Comment (dereksmart) [reply modules/calypsoify/mods-gutenberg.js]: yeah, that's annoying and we should fix that inconsistency. For now, you can add `/* eslint-disable no-var */` to the files.

Comment (jeherve) [reply modules/calypsoify/mods-gutenberg.js]: That's a known issue, you can use `--no-verify` here, Travis does not run the same tests.

More details about this:
p1540478539000100-slack-jetpack-crew

**Comment by jeherve** [comment]
I believe this will now need a rebase because of #10368

File: modules/calypsoify/build-sass.sh [hunk 4]
```diff
@@ -0,0 +1,4 @@
+#!/bin/bash
+
+sass style.scss | perl -pe 's/^    /\t\t/g' | perl -pe 's/^  /\t/g' > style.css
```
Comment (dereksmart) [inline modules/calypsoify/build-sass.sh]: Let's add these to our existing build process

Comment (georgestephanis) [reply modules/calypsoify/build-sass.sh]: Sure.  For the moment this was faster and easier to just do in place.

File: modules/calypsoify/class.jetpack-calypsoify.php [hunk 5]
```diff
@@ -90,17 +227,25 @@ public function add_plugin_menus() {
 	}
 
 	public function enqueue() {
-		wp_enqueue_style( 'calypsoify_wpadminmods_css', plugin_dir_url( __FILE__ ) . 'calypsoify/style.css', false, JETPACK__VERSION );
+		wp_enqueue_style( 'calypsoify_wpadminmods_css', plugin_dir_url( __FILE__ ) . 'style.min.css', false, JETPACK__VERSION );
```
Comment (jeherve) [inline modules/calypsoify/class.jetpack-calypsoify.php]: What would you say about using `Jetpack::get_file_url_for_environment` for those minified files, so we can get both the minified or full versions when needed?

**Review by jeherve — COMMENTED** [review]
A quick note. I also wonder if we should leave a placeholder in place of `class.jetpack-calypsoify.php`, like we usually do to avoid issues (e.g. https://github.com/Automattic/jetpack/blob/master/modules/debug.php#L3 )?

**Comment by georgestephanis** [comment]
The placeholder isn't necessary as it was only included by a hardcoded file, not a dynamic one based on database settings like modules are managed via -- so there shouldn't be any instances where the old file is attempted to be included.

File: modules/calypsoify/class.jetpack-calypsoify.php (hunk 5 above)
Comment (georgestephanis) [reply modules/calypsoify/class.jetpack-calypsoify.php]: From what I saw it didn't seem as though the build tools were generating unminified versions of the non-rtl css files?  I'll recheck to be sure.

File: modules/calypsoify/build-sass.sh (hunk 4 above)
Comment (georgestephanis) [reply modules/calypsoify/build-sass.sh]: Done.

File: modules/calypsoify/class.jetpack-calypsoify.php (hunk 5 above)
Comment (georgestephanis) [reply modules/calypsoify/class.jetpack-calypsoify.php]: Yeah, it's not generating unminified versions of the css files -- there's just the `scss` and `-min`

**Comment by rickybanister** [comment]
How can I test this with a plugin that isn't eligible for auto-updates? Something like the woo-beta-tester plugin? I was unable to build a site that both used this branch and had that plugin pre-installed. Whenever I added the url parameter for calypsoify I saw the traditional styles. 

My goal is to confirm how the toggle UI looks when auto-updates are not available. Everything else looks good.

**Comment by rickybanister** [comment]
I tested this out, everything functions as expected, even when auto-updates are not available (like for the Jetpack beta plugin). 

The only thing I noticed was the toggle's off state doesn't match the Calypso toggle's color:

https://wpcalypso.wordpress.com/devdocs/design/form-fields

I believe the color should be `background: $gray-lighten-10;` which compiles to #a8bece

**Review by dereksmart — DISMISSED** [review]
Works well! Tried to break as much as I could. Let's update those colors that Rick pointed out and ship it!

**Comment by rickybanister** [comment]
I just tried again (using the short-lived site link above) and didn't see a change. Does that link need to be updated or anything?

image

**Comment by georgestephanis** [comment]
THERE WE GO, should work now.

**Comment by rickybanister** [comment]
I just tried again using the same short-lived link from the description and there's no change to the color.

**Comment by georgestephanis** [comment]
It's changed in the selector that you indicated, not sure why it's not showing for you -- are you sure that's what you'e looking at?

screen shot 2018-11-14 at 2 53 47 pm

**Comment by dereksmart** [comment]
@rickybanister Something must have got stuck again in the beta plugin :( I'm seeing the correct color so I'll approve on your behalf and assuming there's no other blocking design feedback. 

image

**Comment by rickybanister** [comment]
Perfect, thanks @georgestephanis and @dereksmart, sorry I didn't bother to check the branch manually in the beta plugin.

Ship it.

**Review by dereksmart — APPROVED** [review]
let's do it

**Comment by jeherve** [comment]
Cherry-picked to `branch-6.7` in d760501e4af8f7947fcae0cdbd35a7fe9820a01b
