### PR TITLE
My Jetpack: Avoid user error on connection status card when is not needed

### LINKED ISSUE #23054: Boost + My Jetpack: "Require user connection"?
### Impacted plugin

Boost

### Steps to Reproduce

1. Only installing Boost and connecting (thus a site-only connection).
2. Visit My Jetpack

### A clear and concise description of what you expected to happen.

The "user connection" bit to not be so "scary" (red with error icon).

Maybe a gentle nudge to upgrade to user authenticated? 

(also what language are we using? "user authenticated" or "user connected"?)

### What actually happened

2022-02-22 at 9 16 PM

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by renatoagds**
Fixes #23054

#### Changes proposed in this Pull Request:
* Introduces new prop `requiresUserConnection` to connection status card
* Updates My Jetpack to use this property
* Updates tests to comply
* Introduces tests for when `requiresUserConnection` equals `false`.

#### Does this pull request change what data or activity we track or use?

no
#### Testing instructions:
* Admin 1 - None user connection, and some plugin requires a connection (Should see a red message about requires connection)
* Admin 1 - None user connection, and none plugin requires a connection (Should see a regular message without being red, asking to connect user)
* Admin 2 - None user connection, and some plugin requires a connection (Should see a red message about requires connection)
* Admin 2 - None user connection, and none plugin requires a connection (Should see a regular message without being red, asking to connect user)
* Admin 2 - Admin 1 user is connected, and itself is not, and some plugin requires a connection (Should not see connection message)
* Admin 2 - Admin 1 user is connected, and itself is not, and none plugin requires a connection (Should not see connection message)

### CODE REVIEW

File: projects/js-packages/connection/components/connection-status-card/index.jsx [hunk 1]
```diff
@@ -195,6 +200,8 @@ ConnectionStatusCard.propTypes = {
 	context: PropTypes.string,
 	/** Function to override default action for connect user account */
 	onConnectUser: PropTypes.func,
+	/** Shows an requires user connection message if true */
```
Comment (leogermani) [inline projects/js-packages/connection/components/connection-status-card/index.jsx:203]: Minor:

I'd call this prop `requiresUserConnection` instead of only `requiresConnection`

Also make it clear in the comment that will display the error if this prop is true AND user connection is missing

**Comment by oskosk** [comment]
Moved out of draft mode and inside My Jetpack 1.0 project and milestone

**Comment by oskosk** [comment]
Pushed a few commits (An update and a rebase)

Renamed `requiresConnection` prop to `requiresUserConnection` prop as proposed by Leo in 2a0a1184e1d94b940de775215c2cbf3ce9a2b558

File: projects/js-packages/connection/components/connection-status-card/index.jsx (hunk 1 above)
Comment (oskosk) [reply projects/js-packages/connection/components/connection-status-card/index.jsx]: Addressedini 2a0a1184e1d94b940de775215c2cbf3ce9a2b558

**Review by oskosk — APPROVED** [review]
