### PR TITLE
Infinite Scroll: Add privacy policy link

### LINKED ISSUE #9435: Infinite Scroll: Privacy Policy link missing from footer
WP 4.9.6 is adding an extra link to the footer on bundled themes, see [#43715-core](https://core.trac.wordpress.org/ticket/43715).

If a site has the the infinite footer enabled, though, then it will not appear.

It seems like it might be worth adding similar a similar link to `$credits`, to mimic the default themes, and help users be GDPR-compliant.

#### Steps to reproduce the issue

1. Check out Core `trunk` (or `4.9.6-beta1` once it's available on Tuesday)
1. Enable one of the bundled themes
1. Create a page for the privacy policy text
1. Set that page as the privacy policy page
1. View the site, you'll see the privacy policy link in the footer
1. Enable the Infinite Scroll module and the infinite footer
1. Refresh the front end, and the privacy link will be gone

#### What I expected

The privacy link should remain, since it's important for GDPR compliance.

#### What happened instead

The link is gone, because the infinite footer is hardcoded.

### PR DESCRIPTION
**Pull request by laghee**
Fixes #9435 

WP bundled themes now have a privacy policy link in their footer, which
is helpful for complying with GDPR rules, but users who enable the infinite
footer lose that link. This adds a similar link to the infinity footer $credits.

#### Changes proposed in this Pull Request:

* Add a privacy policy link to `$credits` to mimic the new WP bundled theme link

#### Testing instructions:

* Publish the privacy policy page on test site
* Enable infinite scroll with this patch applied
* Scroll down to display the infinite footer
* Confirm that it now includes a link to the privacy policy page

(Edit: Added extra step for testing.)

### CODE REVIEW

**Comment by brbrr** [comment]
Hi @laghee. Thanks for your contribution!

I've tested your PR, but I wasn't able to see Privacy Policy link in IS footer:
(IS Enabled)
screen shot on 2018-07-24 at 17 29 49

(IS Disabled)
helloword just another wordpress site 2018-07-24 17-32-31

Also, as you can see - there is redundant '/' just before "Proudly powered by WordPress" text. So I would expect that `the_privacy_policy_link()` return an empty string in my case.

**Comment by brbrr** [comment]
Moving it into next release

cc @laghee

**Comment by laghee** [comment]
Thanks, @brbrr ! You're right -- I can see this locally (now that I unbroke my MAMP setup).

I did some investigation, and it's not that `the_privacy_policy_link()` is returning an empty string, but rather, it's not inserting the link into the `credits` class, so the link is just floating around in the ether, in its `privacy policy link` class, above the infinite footer `div` ... 🤔 ... weird.

screenshot 2018-07-31 17 27 38

I'll poke around a little to see if I can figure out what's going wrong and try to push a fix in the next couple of days.

**Comment by laghee** [comment]
@brbrr I changed the retrieval method to use `get_privacy_policy_url()` instead of `the_privacy_policy_link`, and that appears to have fixed the problem. This works for me locally both with the privacy policy page enabled and not.

Using `the_privacy_policy_link` meant the link was coming back already formatted, so it wasn't being inserted into the `blog-credits` div. (It also made the link text inaccessible for easy translation.)

The Travis checks look like they have to do with a new build configuration and not anything I did, but let me know if I need to tweak something.

**Comment by brbrr** [comment]
Thanks for your contribution! Now I can see the Privacy Policy link.
screen shot on 2018-08-03 at 18 30 36

File: modules/infinite-scroll/infinity.php [hunk 1]
```diff
@@ -1538,9 +1538,19 @@ function footer() {
...
 	 * @return string
+	 *
 	 */
 	private function default_footer() {
-		$credits = sprintf(
+		if ( get_privacy_policy_url() !== '' ) {
+			$credits = sprintf(
+				'<a href="%1$s" rel="noopener noreferrer" target="_blank">%2$s</a><span role="separator" aria-hidden="true"> / </span>',
+				get_privacy_policy_url(),
+				__('Privacy Policy', 'jetpack' )
```
Comment (brbrr) [inline modules/infinite-scroll/infinity.php]: Missing space between '(' & 'Privacy Policy'

Comment (laghee) [reply modules/infinite-scroll/infinity.php]: @brbrr Oops! I can push another commit right now. I assume I should amend the last one so it's not just a typo fix?

Comment (brbrr) [reply modules/infinite-scroll/infinity.php]: No worries about number of commits. We are squashing before merge. Thanks!

**Comment by mdawaffe** [comment]
Nice! I see that the default themes (twentyten, etc.) all use `the_privacy_policy_link()`/`get_the_privacy_policy_link()`, which uses the Privacy Policy's page title as the link text. Should we be using those functions instead so that we use that title as well?

**Comment by laghee** [comment]
@mdawaffe I started out with that approach, but ran into problems because of how `get_the_privacy_policy_link()` returns the link way a `privacy-policy-link` class tag. I didn't see a way to keep it in the `blog-credits` class without some messy manipulation or reformatting the credits template, so I went with what seemed like the simplest solution. 

I see your point with the title, though. Maybe using a filter to change or delete the `class` tag would work? I'll try a few things and see if I can find another solution.

**Comment by laghee** [comment]
@mdawaffe You're right -- that worked like a charm! I should have realized that since the privacy page is just another blog page, the title could be customized like anything else. Displaying just "Privacy Policy" would be annoying to anyone who had bothered to write their own title.

Thanks for the help!

**Comment by mdawaffe** [comment]
Do we still need that `<span role="separator" aria-hidden="true">` from before? I don't know :)

File: modules/infinite-scroll/infinity.php [hunk 2]
```diff
@@ -1538,9 +1538,15 @@ function footer() {
 	 *
 	 * @uses __, wp_get_theme, apply_filters, home_url, esc_attr, get_bloginfo, bloginfo
 	 * @return string
+	 *
 	 */
 	private function default_footer() {
-		$credits = sprintf(
+		if ( get_privacy_policy_url() !== '' ) {
```
Comment (oskosk) [inline modules/infinite-scroll/infinity.php]: Should we check if `get_privacy_policy_url()` is defined (Only WP 4.9.6 and later define it ) ?

**Comment by laghee** [comment]
I made changes requested by @oskosk & @mdawaffe. Sorry about the delay!

**Comment by mdawaffe** [comment]
Thanks for your persistence! Looks good to me.
