### PR TITLE
Instant Search: set the default overlay trigger to 'immediate'

### LINKED ISSUE #19881: Search: when installing as a new user, overlay trigger defaults to "open when results are available"
#### Steps to reproduce the issue

1. Signup for a new Jetpack Search plan via `/jetpack-search`.
2. Visit the Customizer > Jetpack Search.
3. Check the overlay trigger method.
 
#### What I expected
Search defaults to one of the more useful overlay trigger methods: either "immediate" or "on submit".

"Open when results are available" doesn't appear to often any advantage over "immediate". It can offer a more jarring UX if the modal opens when you are still typing. I suggest we should consider removing it completely.

#### What happened instead
Search overlay trigger defaults to "when results are available".

**Screenshots**
Screen Shot 2021-05-19 at 15 23 24

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes #19881.

#### Changes proposed in this Pull Request:
Set the Instant Search overlay trigger to 'immediate' for new users.

As outlined in #19881, "open when results are available" doesn't appear to often any advantage over "immediate". It can offer a more jarring UX if the modal opens when you are still typing. I suggest we should consider removing it completely in the future.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Create up a new Jetpack site using jurassic.ninja and use Jetpack Beta to switch to this PR's branch.
2. Signup for Jetpack Search for the new site at https://wordpress.com/jetpack-search.
3. Go to Customizer and ensure that the selected overlay trigger is 'immediate'.
4. Ensure you can still select and save other overlay triggers in the Customizer.

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php [hunk 1]
```diff
@@ -126,7 +126,7 @@ public function customize_register( $wp_customize ) {
 		$wp_customize->add_setting(
 			$id,
 			array(
-				'default'   => 'results',
+				'default'   => Jetpack_Search_Options::OVERLAY_TRIGGER_IMMEDIATE,
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php:129]: If we're changing the default value here, it's not necessary to manually update the value in `auto_config_search`.

We use `auto_config_search` as a way to define an updated `default` value for new customers since directly changing the default value will affect both old and new customers alike.

When we rolled out the new expanded result format, we wanted to preserve our existing customers' `minimal` result format while ensuring all new customers would default to the `expanded` result format.

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php [hunk 2]
```diff
@@ -502,6 +502,9 @@ public function auto_config_search() {
 		// Set default result format to "expanded".
 		update_option( Jetpack_Search_Options::OPTION_PREFIX . 'result_format', Jetpack_Search_Options::RESULT_FORMAT_EXPANDED );
 
+		// Set default overlay trigger to "immediate".
+		update_option( Jetpack_Search_Options::OPTION_PREFIX . 'overlay_trigger', Jetpack_Search_Options::OVERLAY_TRIGGER_IMMEDIATE );
+
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:507]:
```suggestion
```

**Review by jsnmoon — CHANGES_REQUESTED** [review]
Works as expected.

However, I recommend that we remove the newly introduced `update_option` call in `auto_config_search`; doing so will preserve the intended functionality of this PR.

File: projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php (hunk 1 above)
Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php:129]: 👍 Sounds sensible - I'll remove it. How will the default work in the new customization experience?

Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/class-jetpack-search-customize.php:129]: With this code, any customers that haven't modified their overlay trigger will now use the `immediate` overlay trigger. This will affect both new and existing customers.

**Review by jsnmoon — DISMISSED** [review]

**Comment by bluefuton** [comment]
🚢 Deployed in r227719-wpcom.

**Comment by bluefuton** [comment]
@jsnmoon I had to rebase against master - can I persuade you to re-approve please? Thanks 🙂

**Review by jeherve — APPROVED** [review]
Approving, but this is going to need one last merge. Doing it now. :)
