### PR TITLE
Contact Forms: Update webpack to rename RTL files to match WP core expectations

### LINKED ISSUE #8559: Spiel Theme Corrupting Contact Form in RTL languages
### Quick summary

The contact form in the "pages" default template on the Speil theme corrupts the contact form.

### Steps to reproduce

1. Create a Premium plan site
2. Add Spiel theme
3. Create a page.
4. Add in a default contact form.
5. Ensure the page uses the default Pages template (which comes with a sidebar)
6. Look at the page. It looks ok.
7. Set the site language via site settings->general to a RTL language e.g. Hebrew
8. The form is now corrupted in look.

Replicated on a test site.

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

Image

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

9231637-zd-a8c

### PR DESCRIPTION
**Pull request by sixhours**
Fixes https://github.com/Automattic/themes/issues/8559

## Proposed changes:

* We're using the core `replace` method for CSS, which expects a format like `filename-rtl.css`, but our webpack config uses `filename.rtl.css`. This causes RTL styles to break in the Contact Forms plugin.
* This PR adds a webpack plugin, [cribbed from Jetpack core](https://github.com/Automattic/jetpack/blob/575e4d70811c3e5adacb9bbb837df4fe5dee0760/projects/plugins/jetpack/tools/webpack.config.css.js#L89-L113), that renames the RTL files to match the WordPress core standards.

Before
Screenshot 2025-01-07 at 4 41 18 PM

After
Screenshot 2025-01-07 at 4 40 51 PM

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Switch to this PR on a new JN site with Jetpack Beta
* Enable a RTL language like Arabic
* Create a new post or page with a Contact Form block
* View the post or page on the front end
* You should see the form formatted something like the above "After" picture
* Checking the source, you should see a linked stylesheet `grunion-rtl.css`
* The `grunion-rtl.css` stylesheet should exist (not 404) when you open it directly

### CODE REVIEW

**Comment by sixhours** [comment]
Tagging a couple folks who've worked on this file in the last year for a review since they might have more context than me.

**Review by jeherve — COMMENTED** [review]
> There is no grunion-rtl.css provided to load when RTL styles are active on a site,

Interestingly, we do have a `grunion.rtl.css` file:

https://github.com/Automattic/jetpack-forms/blob/trunk/dist/contact-form/css/grunion.rtl.css

Maybe we should fix the logic to get that file instead? Is there an advantage in not having any RTL CSS, over having that specific one?

If that logic doesn't work, it may also be worth checking if the other stylesheets from the Forms package that are loaded the same way are also broken?
https://github.com/Automattic/jetpack-forms/tree/trunk/dist/contact-form/css
https://github.com/Automattic/jetpack/blob/ad49374b17a8801f0faa493bfd5ee8e79acd5df7/projects/packages/forms/src/contact-form/class-editor-view.php#L93
https://github.com/Automattic/jetpack/blob/62e385bd0e83cbfda590fbc70927636109205e1c/projects/packages/forms/src/contact-form/class-admin.php#L462

**Comment by sixhours** [comment]
> Interestingly, we do have a grunion.rtl.css file:

> https://github.com/Automattic/jetpack-forms/blob/trunk/dist/contact-form/css/grunion.rtl.css

> Maybe we should fix the logic to get that file instead? Is there an advantage in not having any RTL CSS, over having that specific one?

Aha! I'm betting that file is automatically generated, because I don't see it in the src. But yes, rather than using `replace`, we can update the path to point to the correct filename.

It's definitely better to use the specially designed RTL file than not :D

**Comment by sixhours** [comment]
> If that logic doesn't work, it may also be worth checking if the other stylesheets from the Forms package that are loaded the same way are also broken?

Good call, I'll look into that and update this PR if so.

File: projects/packages/forms/changelog/update-contact-form-rtl-styles [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: changed
+
+Don't replace RTL styles; no stylesheet exists
```
Comment (anomiex) [inline projects/packages/forms/changelog/update-contact-form-rtl-styles]: This needs updating. The PR title should probably also be updated.

File: projects/packages/forms/src/contact-form/class-contact-form-plugin.php [hunk 2]
```diff
@@ -254,7 +254,7 @@ protected function __construct() {
 		 *  add_action('wp_print_styles', 'remove_grunion_style');
 		 */
 		wp_register_style( 'grunion.css', Jetpack_Forms::plugin_url() . '../dist/contact-form/css/grunion.css', array(), \JETPACK__VERSION );
-		wp_style_add_data( 'grunion.css', 'rtl', 'replace' );
+		wp_style_add_data( 'grunion.css', 'rtl', Jetpack_Forms::plugin_url() . '../dist/contact-form/css/grunion.rtl.css' );
```
Comment (anomiex) [inline projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Unfortunately neither is really correct. As noted, WordPress core with `'replace'` expects the file to be named `grunion-rtl.css` rather than `grunion.rtl.css`. When passing the filename here instead, it will load both `grunion.css` and `grunion.rtl.css` which is at best redundant.

Possibly the best thing to do would be to copy [the Renamer plugin](https://github.com/Automattic/jetpack/blob/575e4d70811c3e5adacb9bbb837df4fe5dee0760/projects/plugins/jetpack/tools/webpack.config.css.js#L89-L113) from Jetpack's webpack config and have it be applied to whichever CSS files are using `'replace'`, so they get named in the way WordPress core is expecting.

Comment (sixhours) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Okay, that makes sense, since it does look like this happens across multiple parts of the plugin. My experience with setting up webpack is zero :D but I've added the plugin to the existing webpack config for the contact forms plugin. Need to remind myself how to load Jetpack locally to actually test it.

Comment (anomiex) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: The way you did it doesn't quite work, it creates a bunch of files in `dist/contact-form/src/contact-form/css/` instead (and also still has the `.rtl.css` versions).

It'd probably be simpler to do like this, just embed the paths inside the plugin and add it into the existing css block:
```js
// CSS files using `wp_style_add_data( $handle, 'rtl', 'replace' )` need the
// RTL version to be named like "module-rtl.css" and "module-rtl.min.css"
// rather than "module.rtl.css" and "module.min.rtl.css" like our Webpack
// config does it.
// This minimal plugin renames the relevant assets to conform to that style.
const RenamerPlugin = {
	apply( compiler ) {
		compiler.hooks.thisCompilation.tap( 'Renamer', compilation => {
			compilation.hooks.processAssets.tap(
				{
					name: 'Renamer',
					stage: jetpackWebpackConfig.webpack.Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_INLINE,
					additionalAssets: true,
				},
				assets => {
					for ( const [ name, asset ] of Object.entries( assets ) ) {
						const m = name.match( /^(css\/(?:grunion|grunion-admin|editor-ui))((?:\.min)?)\.rtl\.css$/ );
						if ( m ) {
							delete assets[ name ];
							assets[ `${ m[ 1 ] }-rtl${ m[ 2 ] }.css` ] = asset;
						}
					}
				}
			);
		} );
	},
};

module.exports = [
	{
		...sharedWebpackConfig,
		entry: glob.sync( path.join( scriptSrcDir, '*.js' ) ).reduce( ( acc, filepath ) => {
			acc[ 'js/' + path.parse( filepath ).name ] = filepath;
			return acc;
		}, {} ),
	},
	{
		...sharedWebpackConfig,
		entry: glob.sync( path.join( styleSrcDir, '*.css' ) ).reduce( ( acc, filepath ) => {
			acc[ 'css/' + path.parse( filepath ).name ] = filepath;
			return acc;
		}, {} ),
		plugins: [
			...sharedWebpackConfig.plugins,
			RenamerPlugin,
		],
	},
];
```

Comment (sixhours) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Tried that but it's not working in testing (on WP.com and a JN site). 🤔 Is that expected since this is a change to webpack?

Comment (anomiex) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Seems to work on a JN site for me.

1. Created site.
2. Added a post with a contact form (https://medieval-tuna.jurassic.ninja/2025/01/08/form/).
3. Switched language to Arabic.
4. Checked that `grunion-rtl.css` is being loaded.

Comment (sixhours) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: Hmm, let me try on a fresh JN site. I only updated the PR on the existing one.

Comment (sixhours) [reply projects/packages/forms/src/contact-form/class-contact-form-plugin.php]: That did it. :)

**Review by anomiex — APPROVED** [review]
