### PR TITLE
Subscriptions Block: Stop saving localized attributes defaults in the block content

### LINKED ISSUE #15776: Subscriptions Block: Invalidates when edited in different language
If a Subscription Block is added to a post with one localization, then subsequently edited in another localization, the block will be invalidated with no good way of recovering. The default texts in the block must be maintained, customization of the texts will prevent invalidation.

Core Gutenberg is working out how to handle situations like this:
- https://github.com/WordPress/gutenberg/issues/21932
- https://github.com/WordPress/gutenberg/issues/7604

Some of the default block attributes are localized with `__`:

https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/attributes.js#L7-L10
https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/attributes.js#L19-L22

These attributes are stored directly in the save function:

https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/save.js#L24-L47
https://github.com/Automattic/jetpack/blob/db3e47183b64a343aa594fd32a815483bfdf302d/extensions/blocks/subscriptions/save.js#L105-L129

The block may be saved with a localized text `Enter your email address`, then when the editor loads and validates the block content, it finds an unexpected localization (e.g. _`Dirección de correo electrónico`_) and determines that the block content is not valid.

I wrote about the problem of "impure save" here in more detail: pafL3P-kL-p2
In this case, translations implicitly leak into the block's save, rendering them impure and susceptible to invalidation.

This causes the following issues:
- https://github.com/Automattic/jetpack/issues/15475
- https://github.com/Automattic/jetpack/issues/15076#issuecomment-603448947
- https://github.com/Automattic/wp-calypso/issues/41364#issuecomment-627642782

This has been present since the very first iteration of the block: https://github.com/Automattic/wp-calypso/pull/28887

cc: @obenland @iamtakashi 

#### Steps to reproduce the issue

1. Create a new site
1. Connect Jetpack
1. Enable [Subscriptions](https://jetpack.com/support/subscriptions/) (`/wp-admin/admin.php?page=jetpack#/discussion`)
1. Create a new post (`/wp-admin/post-new.php`)
1. Add a *Subscription Form* block (Start typing `/subscription`)
1. Save the post
1. Change the site language (e.g. Español) (`/wp-admin/options-general.php`)
1. Update localizations (`/wp-admin/update-core.php`)
1. Open the previous post
1. The block will be invalidated with errors in the console.

Save (English):

Screen Shot 2020-05-13 at 11 46 57

Load (Spanish):

Screen Shot 2020-05-13 at 11 47 40

```
Block validation: Block validation failed for `jetpack/subscriptions` ({name: "jetpack/subscriptions", icon: {…}, …

Content generated by `save` function:

<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_subscribers_total="false" show_only_email_and_button="true"]</div>

Content retrieved from post body:

<div class="wp-block-jetpack-subscriptions">[jetpack_subscription_form show_only_email_and_button="true" custom_background_button_color="undefined" custom_text_button_color="undefined" submit_button_text="Subscribe" submit_button_classes="undefined" show_subscribers_total="false" ]</div>
```

### PR DESCRIPTION
**Pull request by Copons**
Fixes #15776

#### Changes proposed in this Pull Request:

* Stop saving localized attributes defaults in the Subscriptions block content.

The Subscriptions block has two attributes with localized default values which are saved in the block content as shortcode attributes. Changing the site language will break the block validation, because the strings are saved in the previous language, while the validator expects them to be in the new language.

In this PR we stop adding those attributes to the shortcode if they are the same as the default (haven't been changed by the user).

The shortcode will take care of those missing attributes by using [its own defined defaults](https://github.com/Automattic/jetpack/blob/020effc64833fa2f378d1b8a9a18ff0b8a118672/modules/subscriptions/views.php#L625-L653).

#### Note

There have been two deprecated versions added. The first handles the normal migration when the language hasn't changed. The second almost identical one, allows for the placeholder text, if left to default values, to fall back to the known English version of the text. It does not change the attribute values just the generated content from the deprecated save so the block isn't invalidated. 

Unfortunately, this will only be able to solve the case when the block was created in English, the site switched to a new language and then the block loaded in the editor again afterwards. If the block was created in a non-English language then the site switched to English, we don't know what the original default text should be so can't fallback to it.

Migrating the block and saving the post _before_ changing the language would fix it.

Repro steps:
1. Add a Subscriptions block on master, and save the post.
2. Checkout this branch.
3. Change site language.
4. Reload the editor: the block breaks. 👎 

Working steps:
1. Add a Subscriptions block on master, and save the post.
2. Checkout this branch.
3. Reload the editor, let the block migrate, and save the post.
4. Change site language.
5. Reload the editor: the block works. 👍 

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Before checking out this PR:
	* Edit a post and add two Subscriptions block. (You will need to be connected to WordPress.com).
	* Leave one unchanged, and update the button label of the other.
	* Save the post.
* Checkout this PR, build the extensions, and reload the editor.
* Make sure the blocks have migrated without errors.
* Check the code view, and make sure the shortcode attributes are not output in separate lines anymore (this will confirm the blocks are using the new save function).
	E.g.
```diff
- [jetpack_subscription_form
-		attribute="value"
-		another_attribute="value"
- ]
+ [jetpack_subscription_form attribute="value" another_attribute="value"]
```

* Without saving the post, change the site language in `/wp-admin/options-general.php`, and make sure you also install the new language pack in `/wp-admin/update-core.php`.
* Reload the editor and make sure the blocks don't break anymore.
* Make sure that the button label of the block left unchanged is now translated in the new language.

#### Proposed changelog entry for your changes:

* Subscriptions Block: Stop saving localized attributes defaults in the block content

### CODE REVIEW

**Comment by scruffian** [comment]
Rebase ✅

**Comment by aaronrobertshaw** [comment]
This one was rebased already. D46159-code has been updated with new files.

**Comment by apeatling** [comment]
I'm testing this one, can confirm this breaks on master when switching languages. When I switch to this branch, rebuild, and reload the editor I get:

Screen Shot 2020-07-09 at 9 33 39 AM

File: extensions/blocks/subscriptions/deprecated/v3/get-subscriptions-shortcode.js [hunk 1]
```diff
@@ -0,0 +1,143 @@
...
+	DEFAULT_BORDER_RADIUS_VALUE,
+	DEFAULT_BORDER_WEIGHT_VALUE,
+	DEFAULT_PADDING_VALUE,
+	DEFAULT_SPACING_VALUE,
+	DEFAULT_FONTSIZE_VALUE,
+} from '../../constants';
+
+export default function getSubscriptionsShortcode( className, attributes, checkTextDefaults = null ) {
+	const {
+		subscribePlaceholder,
```
Comment (apeatling) [inline extensions/blocks/subscriptions/deprecated/v3/get-subscriptions-shortcode.js:26]: The error I'm seeing seems to be related to subscribePlaceholder not existing. Possibly an issue with the deprecation script?

Comment (aaronrobertshaw) [reply extensions/blocks/subscriptions/deprecated/v3/get-subscriptions-shortcode.js:26]: Thanks for testing this. I've fixed up the deprecation scripts and it tests well for me now.

**Comment by jeherve** [comment]
r211582-wpcom
