### PR TITLE
Sync: Bail initial sync if there is an ongoing full sync

### LINKED ISSUE #12548: Full Sync interrupted when user authorizes to blog
When a JP user authorizes to the blog, a full sync in progress will get interrupted and replaced with the small sync from `do_initial_sync()`, as we can only have one ongoing full sync: https://github.com/Automattic/jetpack/blame/19f9d99879d28bcdc51da94539cb26b0d1b117be/sync/class.jetpack-sync-actions.php#L529

#### Steps to reproduce the issue

1. Kick off a full sync in progress
2. Assuming your user isn't connected to JP yet, go to Jetpack > Dashboard
3. Scroll down to "Account Connection" and hit "Link to WordPress.com"
4. Sync will get interrupted and replaced

#### What I expected
The sync to not run at all because there is already one going on.

#### What happened instead
The sync interrupted with a smaller sync of just the options, callables, constants, etc.

### PR DESCRIPTION
**Pull request by rebeccahum**
Fixes #12548.

**Changes proposed in this Pull Request:**
do_initial_sync() will check if there is a current ongoing full sync before initializing the incremental sync.

**Testing instructions:**
1. Kick off a full sync in progress
2. Assuming your user isn't connected to JP yet, go to Jetpack > Dashboard
3. Scroll down to "Account Connection" and hit "Link to WordPress.com"
4. Current full sync will continue to sync without being overwritten
5. Alternatively, in lieu of steps 2. and 3., you could just call `Automattic\Jetpack\Sync\Actions::do_initial_sync();` in`wp shell`.

**Proposed changelog entry for your changes:**
Add check for ongoing full sync in before `do_initial_sync()` initializes.

### CODE REVIEW

File: packages/sync/src/Actions.php [hunk 1]
```diff
@@ -355,6 +356,12 @@ public static function do_initial_sync() {
 			return false;
 		}
 
+		// Don't start new sync if a full sync is in process.
+		$full_sync_module = Modules::get_module( 'full-sync' );
+		if ( $full_sync_module && ( $full_sync_module->is_started() && ! $full_sync_module->is_finished() ) ) {
```
Comment (tyxla) [inline packages/sync/src/Actions.php]: Seems like there's no need for the extra parens:

```suggestion
		if ( $full_sync_module && $full_sync_module->is_started() && ! $full_sync_module->is_finished() ) {
```

**Review by tyxla — DISMISSED** [review]
This works great and looks well too! Thanks for the tests 💯 ❤️

**Comment by enejb** [comment]
@jeherve I think this is more of a fix bug then an enhancement.  

@rebeccahum Thank for fixes!

**Review by tyxla — APPROVED** [review]
Re-approving after the minor change. Thanks again 🙌

**Comment by rebeccahum** [comment]
@nickdaugherty When this gets merged, we'll need to remove https://github.com/Automattic/vip-go-mu-plugins/commit/7733c0de1008d5cd9a354be89589eea36d7b01ad#diff-c6e3ac4f3b2df1ce87a29da11343a910 on VIP Go before updating JP.

**Comment by kraftbj** [comment]
I'm merging. @nickdaugherty @rebeccahum this missed our cutoff for the October 1 release, so this is slated to be shipped as a stable release on November 5th.

**Comment by nickdaugherty** [comment]
Thanks both - I've set a reminder to remove the VIP Go patch prior to upgrading around Nov 5th.
