### PR TITLE
Fix error with videos uploaded through the Video block

### LINKED ISSUE #42401: Video Block crashing: 'This block has encountered an error and cannot be previewed.'
### Quick summary

When a video block is added, and the video is uploaded through the block, the block crashes, showing this message:

`This block has encountered an error and cannot be previewed.`

https://github.com/user-attachments/assets/8495f367-e191-4109-a903-23785b48082f

### Steps to reproduce

1. Upload a video through regular video block
2. Notice how the block breaks and shows this message `This block has encountered an error and cannot be previewed.`

### A clear and concise description of what you expected to happen.

It should be possible to add a regular video block to a site without crashing. Video block is added, video uploaded, and video shows on site. 

### What actually happened

The block crashes.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Major

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

Convert the video block to a VideoPress block.

https://github.com/user-attachments/assets/142b2748-5382-4952-b61c-e5f83bfb85cc

### Platform

Simple, Atomic

### PR DESCRIPTION
**Pull request by renatho**
Fixes #42401

## Proposed changes:

This started breaking recently, after this PR: https://github.com/Automattic/jetpack/pull/42216

An error was happening because sometimes the variable `scripts` is `null`, and we were doing a push on that. Now we are returning the loading state earlier to avoid modifying the `scripts` variable when it's not ready.

Also, the `scripts` variable was a prop coming to the component and it was being mutated with the `push`, so I did a small refactor to avoid this.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the editor.
* Add the Video block.
* Upload a video, and make sure the block doesn't crash.
* Convert the block to VideoPress and then convert back to video to make sure we didn't break this fix: https://github.com/Automattic/jetpack/pull/42216.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/videopress/edit.js [hunk 1]
```diff
@@ -1049,6 +1050,35 @@ export const VpBlock = props => {
 		} ),
 	} );
 
+	const getSandboxScripts = useCallback( () => {
```
Comment (phcp) [inline projects/plugins/jetpack/extensions/blocks/videopress/edit.js:1053]: I think in this case, it could be replaced with a `useMemo` for `sandboxScripts`. With that, the function isn't called on every render, as the initial scripts array will likely be the same.

Comment (renatho) [reply projects/plugins/jetpack/extensions/blocks/videopress/edit.js:1053]: I agree that a `useMemo` would make more sense here.

But it would run before the conditional return of the `shouldRenderLoadingBlock`, and it wouldn't be needed in that scenario, even if the code is fixed to not break depending on the value of the `scripts`.

In terms of performance, I think we would have pros and cons in both approaches, but in the end it wouldn't be significant.

WDYT? Does it make sense for you?

Comment (phcp) [reply projects/plugins/jetpack/extensions/blocks/videopress/edit.js:1053]: Indeed, we can keep it that way then. I'll approve it, thanks for the follow-up!

**Review by phcp — APPROVED** [review]
Tested, and it works great! Thanks for the fix!
