### PR TITLE
In Media & Text block, replace video with a VideoPress block on the frontend

### LINKED ISSUE #13239: VideoPress block: not inserted when used in Text & Media block
#### Steps to reproduce the issue

1. Insert a Text & Media block inside a page or post.
2. Upload a video inside the Text & Media block.

#### What I expected

To see the thumbnail right when the page displays. 

#### What happened instead

Video thumbnail doesn't show up on mobile. 

IMG_7140

### PR DESCRIPTION
**Pull request by merkushin**
Fixes https://github.com/Automattic/jetpack/issues/13239

When Media & Text block is used, it uses an HTML5 video player on the frontend, which leads to some unexpected behavior that is especially well noticeable on mobile (there is no thumbnail/preview for the video).

In this PR, we replace the video tag with a VideoPress player **only on the frontend**. The block remains untouched in the editor and keeps its standard behavior.

The Media & Text block doesn't use internally a video block of any kind, so we can't substitute only part of it in the editor.

One alternative I considered was to replace the whole block with a two column structure, with a VideoPress block on the left and a Paragraph block on the right. However, this feels like a dramatic change that might lead to unexpected effects. So I discarded it for this issue.

## Proposed changes:

* On the frontend, replace the video tag with the VideoPress block if the video is available as a VideoPress video.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sandbox your test site if you test on WP.com.
* Insert a Text & Media block inside a page or post.
* Upload a video inside the Text & Media block.
  * Make sure it was uploaded to VideoPress and processed. You can check it in Jetpack -> VideoPress, for example.
* Open the post on the frontend and make sure it uses the VideoPress player.
* Open the post on your mobile and make sure it uses the VideoPress player (you should see a preview image).
  * Don't open it in the desktop browser with the responsive/mobile view: it behaves differently for a standard video tag.
* Make sure you can see a thumbnail/preview image for the video.
* Please test it in different environments, for example, on a Simple site.

### CODE REVIEW

File: projects/plugins/jetpack/modules/videopress/class.videopress-gutenberg.php [hunk 1]
```diff
@@ -37,6 +38,7 @@ private function __construct() {
 		add_action( 'jetpack_register_gutenberg_extensions', array( $this, 'set_extension_availability' ) );
 		add_action( 'enqueue_block_editor_assets', array( $this, 'override_video_upload' ) );
 		add_action( 'enqueue_block_editor_assets', array( $this, 'add_resumable_upload_support' ) );
+		Block_Replacement::init();
```
Comment (merkushin) [inline projects/plugins/jetpack/modules/videopress/class.videopress-gutenberg.php:41]: I'm not sure if it was a good place to include this call.

The other option was to add a new class that basically only does this call. However, I needed to include it in other parts as well to enable the module.

Since `Block_Replacement` class partially substitutes another Gutenberg block, I considered it a reasonable trade-off.

**Comment by merkushin** [comment]
@phcp tested it, and it didn't work for him on a Simple site.

**Comment by phcp** [comment]
> @phcp tested it, and it didn't work for him on a Simple site.

I finally made it work on both Atomic and Simple. I misunderstood and expected to see the player in the editor as well. However, @merkushin shared that due to the block limitation, it isn't possible without extensive changes. So, the VideoPress player is rendered correctly when viewing the post itself. I'm doing some additional tests on self-hosted now.

**Comment by merkushin** [comment]
Thanks, @phcp.
I'll update the PR description to clarify it.

File: projects/packages/videopress/src/class-initializer.php [hunk 2]
```diff
@@ -95,6 +95,10 @@ private static function unconditional_initialization() {
 		if ( is_admin() ) {
 			AJAX::init();
 		}
+
+		if ( ! is_admin() ) {
+			Block_Replacement::init();
```
Comment (phcp) [inline projects/packages/videopress/src/class-initializer.php:100]: Just for my understanding. Do you know why the init is also called here?

Comment (merkushin) [reply projects/packages/videopress/src/class-initializer.php:100]: This initializer is used in the VideoPress plugin, but is not used in Jetpack plugin.
So I needed to call the init method from two places and make sure the filter is added only once.

Comment (phcp) [reply projects/packages/videopress/src/class-initializer.php:100]: Got it, thank you!

**Review by phcp — APPROVED** [review]
I tested on simple, atomic, and self-hosted, and it works great. Thanks for the fix, @merkushin!
