### PR TITLE
Related Posts: fix accessibility issues

### LINKED ISSUE #34594: Related Posts - A11y issues
### Impacted plugin

Jetpack

### Quick summary

I've had a user report multiple accessibility issues with Jetpack Related posts: 

- List items (<li>) are not contained within <ul>, <ol> or <menu> parent elements.
- Elements with visible text labels do not have matching accessible names.
- Values assigned to role="" are not valid ARIA roles.

Screenshots from Pagespeed Insights report:

1fva87lpwpzckh-List Items Issue
1fva87lpwpzcx3-Visible Text Lables
1fva87lpwpzdf4-ARIA Roles Issue

### Steps to reproduce

1. Run a Pagespeed Insights report on a page with Related Posts using https://pagespeed.web.dev/
2. See these errors

Here's an example report from a Newspack publisher: https://pagespeed.web.dev/analysis/https-grehlakshmi-com-hindi-entertainment-madhuri-in-dance-deewane/4irtbgof5h?form_factor=mobile

### A clear and concise description of what you expected to happen.

The code would be accessible.

### What actually happened

There are several elements of the code which impede a11y.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

N/A

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/34594

## Proposed changes:
This PR fixes several accessibility issues of the _Related Posts_ block in the front-end.

- Add an accessible name to the component `nav` by adding an `aria-label` or `aria-labelled-by` attribute.
- Use `ul` and `li` tags for the markup of items and their container.
- Render all posts in the same list and handle layout in CSS instead.
- Remove the `ul` tag for each list item and use a `dl` list for the metadata only.
- Remove `role="menuitem"` from post items.  It's incorrectly used (see [these docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/menuitem_role)).
- Remove the `aria-labelledby` attribute from post items. It's used for interactive elements or landmarks.
- For each post item, merge the two links (image and text) into a single link that contains both the post thumbnail and title.
- Fix thumbnails so they don't appear stretched.
- Adjust spacing to better group post metadata (date, author, and tag).
- Add spacing between items in "list" view mode.

_Note: when set, the headline is rendered as a `h3`. This is wrong since assumptions are made about the outline of the page. Authors should be able to set the heading level themselves in the editor. This should be handled as a separate PR._

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

### Prerequisites

- Create a couple of posts that share the same tag
- For some of them, add a featured image

### Testing

- Spin up a test site with this branch
- Build the plugin
- Create a new post
- Add the tag you've used for the related posts
- Add the _Related Posts_ block
- Open the preview
- Play with different settings and views in the editor and verify nothing looks broken
- Optionally, test the component with a screen reader

_Settings_
Screenshot 2024-01-09 at 3 20 17 PM

_Views_
Screenshot 2024-01-10 at 1 40 01 PM

## Captures

Screenshot 2024-01-11 at 11 34 14 AM
Screenshot 2024-01-11 at 11 35 03 AM

### CODE REVIEW

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 1]
```diff
@@ -502,23 +509,27 @@ public function render_block( $attributes, $content ) {
...
-					esc_html( $headline )
+					'<h3 id="%2$s" class="jp-relatedposts-headline">%1$s</h3>',
+					esc_html( $headline ),
+					esc_attr( $headline_id )
 				);
 			}
 		}
 		$display_markup = sprintf(
-			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s">%4$s%5$s</nav>',
+			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" aria-labelledby="%6$s">%4$s%5$s</nav>',
```
Comment (monsieur-z) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php]: Use the content of the headline to label the navigation.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 2]
```diff
@@ -502,23 +509,27 @@ public function render_block( $attributes, $content ) {
...
 		$display_markup = sprintf(
-			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s">%4$s%5$s</nav>',
+			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" %6$s>%4$s%5$s</nav>',
 			! empty( $wrapper_attributes['class'] ) ? ' ' . esc_attr( $wrapper_attributes['class'] ) : '',
 			! empty( $wrapper_attributes['style'] ) ? ' style="' . esc_attr( $wrapper_attributes['style'] ) . '"' : '',
 			esc_attr( $block_attributes['layout'] ),
 			$headline_markup,
-			$rows_markup
+			$rows_markup,
+			empty( $headline_markup ) ? 'aria-label="' . esc_attr( __( 'Related Posts', 'jetpack' ) ) . '"' : 'aria-labelledby="' . esc_attr( $headline_id ) . '"'
```
Comment (monsieur-z) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:515]: Use the content of the headline to label the navigation when it's available.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 3]
```diff
@@ -470,55 +480,39 @@ public function render_block( $attributes, $content ) {
 			)
 		);
 
-		$display_lower_row = $block_attributes['size'] > 3;
-
 		if ( empty( $related_posts ) ) {
 			return '';
 		}
 
-		switch ( count( $related_posts ) ) {
```
Comment (monsieur-z) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:479]: Layout should be handled in CSS.

File: projects/plugins/jetpack/modules/related-posts/related-posts.css
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/related-posts.css:1]: Since you're updating CSS, you'll need to bump the version of the file here:
https://github.com/Automattic/jetpack/blob/059815fab7ea896ce02e160288e2524f48e2bc74/projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php#L16

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 4]
```diff
@@ -342,96 +342,106 @@ public function get_client_rendered_html_unsupported() {
 	public function render_block_item( $related_post, $block_attributes ) {
 		$instance_id = 'related-posts-item-' . uniqid();
 		$label_id    = $instance_id . '-label';
+		$title       = $related_post['title'];
+		$url         = $related_post['url'];
+		$rel         = $related_post['rel'];
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:347]: below we were checking if `$related_post['rel']` wasn't empty; maybe we should do the same here?

**Review by jeherve — CHANGES_REQUESTED** [review]
This seems to test well on my end. I only have 2 small remarks below.

File: projects/plugins/jetpack/modules/related-posts/related-posts.css
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/related-posts.css:1]: Thanks! I didn't notice that.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php (hunk 4 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:347]: Do you mean we should do the same for `$title` and `$url`? It's unlikely they'll be empty but I can do it.

**Review by jeherve — COMMENTED** [review]
This should be okay now, nice work! It is going to need a rebase though, there was another Related Posts change merged recently.

**Review by jeherve — APPROVED** [review]
