### PR TITLE
Fixed Page Optimize plugin conflict for RTL stylesheets

### LINKED ISSUE #19340: Nav Unification conflicts with Page Optimize plugin on RTL sites
#### Steps to reproduce the issue

1. Change the language to RTL one
2. Change the color scheme
3. Visit a WP-Admin page

#### What I expected

The color scheme should change to the one configured and the width to be 270px.
#### What happened instead
The color scheme remains black and Nav width is 160px

The issue is caused by a conflict with Page Optimize plugin on AT and any other site that has the plugin installed. Based on a quick research it seems that it's caused by the CSS concatenate feature of the plugin.

A quick workaround for it is to add `colors,jetpack-admin-menu,admin-bar,dashicons` in the CSS exclude list input located in `Settings > Performance` section

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes #19340 

#### Changes proposed in this Pull Request:

Added `rtl` extra data for `colors` and `jetpack-admin-menu` CSS handles. This in turn will make Page Optimize to ignore the stylesheets since the current implementation does not support RTL. 

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

_Simple_
- Apply D60626-code to your WP.com sandbox.
- Sandbox the API and a simple site.

_Atomic_
- Install Jetpack Beta on a Atomic site and switch to the branch of this PR.
- Go to https://wordpress.com and switch to the WoA site.

_Jetpack_
- Spin up a local environment and switch to this PR branch

To test this fix, on all environments, you'll need to:
- Have page optimize installed (except for Simple sites)
- Go to https://wordpress.com/me/account and change your language to an RTL language.
- Enable an RTL language on your site (Settings > General)
- Make sure that Page Optimize does not have `jetpack-admin-menu` and `colors` marked as excluded from CSS concatenation section.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 1]
```diff
@@ -268,6 +271,14 @@ public function enqueue_scripts() {
 		);
 	}
 
+	/**
+	 * Mark the core colors stylesheets as RTL depending on the value from the environment.
+	 */
+	public function configure_colors_for_rtl_stylesheets() {
+		// This also fixes the core issue.
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:278]: Can we add a link to the Trac issue here?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 2]
```diff
@@ -259,6 +259,9 @@ public function enqueue_scripts() {
 			JETPACK__VERSION
 		);
 
+		wp_style_add_data( 'jetpack-admin-menu', 'rtl', $this->is_rtl() );
+		$this->configure_colors_for_rtl_stylesheets();
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:263]: Non-blocking (and personal preference): `wp_styles()->add_data( 'colors', 'rtl', $this->is_rtl() );` is simple enough, it doesn't need a separate function.

**Review by mmtr — APPROVED** [review]
This tests well for me 🎉

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 2 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:263]: Can we also use `wp_style_add_data` instead of `wp_styles()->add_data` so both styles (`jetpack-admin-menu` and `colors`) use the same syntax?

Comment (tjcafferkey) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:263]: >it doesn't need a separate function.

It doesn't need to be but the reason we made it a separate function is because it's responsible for fixing a core bug. We wanted to make that clear by putting it into a separate method and naming it to be more descriptive around its responsibilities.

I'll add the trac issue here also, but knowing the above are you comfortable with leaving it or would you rather us move that into the `enqueue_scripts` method?

Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:263]: > We wanted to make that clear moving it and naming it to be more descriptive around its responsibilities.

That's fine 👍 We could state that in the docstring of the method to make it super clear.

**Review by mmtr — DISMISSED** [review]

**Comment by tjcafferkey** [comment]
@mmtr I had to rebase this PR. Any chance of a final approval? 🙏🏻

**Review by mmtr — APPROVED** [review]

**Comment by tjcafferkey** [comment]
Deployed to WPCOM in r224910-wpcom
