### PR TITLE
Slideshow: Add wp-escape-html dependency to view

### LINKED ISSUE #11910: Slideshow Block Not Working When Published
#### Steps to reproduce the issue

1. Go to post or page editor
2. Add a Slideshow block to the post or page
3. Add images to the block
4. Publish the page or post

#### What I expected

When viewing the page or post, the slideshow will advance when the forward/backward buttons are clicked and, if autoplay is enabled, slideshow will autoplay

#### What happened instead
Slideshow doesn't autoplay, and navigation buttons don't work

**Screenshots**
Screen recording: [https://cld.wthms.co/jIzmqE](https://cld.wthms.co/jIzmqE)

Reported in #11677427-hc / #1935045-zen and #11811004-hc

### PR DESCRIPTION
**Pull request by sirreal**
Fixes #11910

#### Changes proposed in this Pull Request:

* Add `wp-escape-html` dependency to Slideshow view script.

#### Testing instructions:

* Create a new post that only includes the Slideshow block.
* View the post on the frontend.
* Does the block work as expected?

#### Proposed changelog entry for your changes:

* Fix a bug that prevented the Slideshow block from functioning as expected on the frontend under most circumstances.

### CODE REVIEW

File: extensions/blocks/slideshow/slideshow.php [hunk 1]
```diff
@@ -25,6 +25,7 @@
 function jetpack_slideshow_block_load_assets( $attr, $content ) {
 	$dependencies = array(
 		'lodash',
+		'wp-escape-html',
```
Comment (sirreal) [inline extensions/blocks/slideshow/slideshow.php]: Should match current master:

https://github.com/Automattic/jetpack/blob/201ec52be66261a364f0805a6e44d25269d84793/extensions/blocks/slideshow/slideshow.php#L28

**Review by simison — APPROVED** [review]
Confirmed this isn't an issue in `master` branch and _it is_ an issue in `branch-7.2` and that this fixes it.

Tested with local Jetpack-Docker setup. My images had caption and "autoplay" was on, in case it matters.

Note that `branch-7.2` doesn't have `yarn build-extensions` so it's good to run that with `master` first, then switch the branch.

**Review by jeherve — APPROVED** [review]

**Comment by simison** [comment]
@kraftbj note that this was directly merged to `branch-7.2` branch so no cherry picking needed.

**Comment by kraftbj** [comment]
Thanks y'all and for confirming this is a php-only block change.
