### PR TITLE
Forms: Fix feedback source data

### LINKED ISSUE #44692: When forms are part of a template, the submission source is "Block Template" rather than the actual page URL.
### Impacted plugin

Jetpack

### Quick summary

When forms are part of a template, the submission source is "Block Template" rather than the actual page URL:

Image

It wasn't like this with the native WordPress submissions interface.

### Steps to reproduce

1. Add a form to a block template.
2. Submit the form.

### Site owner impact

Between 20% and 60% of the total website/platform users

### Severity

Major

### What other impact(s) does this issue have?

Individual site owner revenue

### If a workaround is available, please outline it here.

None that I currently know of.

### Platform (Simple and/or Atomic)

_No response_

### PR DESCRIPTION
**Pull request by enejb**
Fixes [FORMS-211](https://linear.app/a8c/issue/FORMS-211)

Resolves https://github.com/Automattic/jetpack/issues/44692

## Proposed changes:
* Update the Feedback_Source object to store more info. Such as the current page. 
* Pass the Feedback_Source object in the JWT token. 
* Store the Feedback_Source object in the feedback post type. 
* Update the Title of the source based on where the source was created. 
* Use the url that links to the correct place where the form was filled out. 
* Add a [Deleted] label to the title for posts/pages that were deleted. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
See Fixes [FORMS-211](https://linear.app/a8c/issue/FORMS-211)

## Does this pull request change what data or activity we track or use?
No

### Part 1. (Creat Forms) 
Create a Form on a page or post. 

#### Using a block theme
Create a Form in a site template (such as 404 page) 

Create as in a Template Part such as the footer or header. 

#### Using a Non Block theme. 
Add a widget that has the form. 

### Part 2. Fill out the Forms. 
Fill out the different forms that you created. 
Then visit the Feedback Inbox. 
Are you abel to navigate to the page that the Feedback was created? Are you able to navigate to the page where you can edit the form. ( See Edit Form ) in the dropdown)

Delete the page or post that has the form. 
Notice that the source page title stays the same but it tells you that the page or post is deleted.

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-feedback-source.php [hunk 1]
```diff
@@ -83,11 +111,81 @@ public static function from_submission( $current_post, int $current_page_number
 			return new self( 0, '', $current_page_number );
 		}
 
-		$title = $current_post->post_title ?? '';
+		$title = $current_post->post_title ?? __( '[Missing Title]', 'jetpack-forms' );
```
Comment (simison) [inline projects/packages/forms/src/contact-form/class-feedback-source.php]: How does the core show pages without titles in the pages list?

Separately, what if it's a template/archive/search/404/blog index - do those pages always have a title in this object, or do we need to fetch the rifle with the helper function from core?

Comment (simison) [inline projects/packages/forms/src/contact-form/class-feedback-source.php]: Also sentence case always 🙂

File: projects/packages/forms/src/contact-form/class-feedback-source.php [hunk 2]
```diff
@@ -100,6 +198,34 @@ public function get_permalink() {
...
+	/**
+	 * Get the edit URL of the form or page where the feedback was submitted from.
+	 *
+	 * @return string The edit URL of the form or page.
+	 */
+	public function get_edit_form_url() {
+
+		if ( current_user_can( 'edit_theme_options' ) ) {
+			if ( $this->source_type === 'block_template' && \wp_is_block_theme() ) {
+				return admin_url( 'site-editor.php?p=' . esc_attr( '/wp_template/' . addslashes( $this->id ) ) . '&canvas=edit' );
```
Comment (simison) [inline projects/packages/forms/src/contact-form/class-feedback-source.php:215]: I remember this template editor linking being particularly difficult because sometimes you need theme namespace added, or sometimes it's self created template. Worth testing well!

**Review by CGastrell — DISMISSED** [review]
I think this is an improvement, I'll leave here some results so to double check the expected behavior:

When form is in widget:
- no Edit Form on the actions dropdown
- Source column holds the link to where it was submitted from (links work as expected, even getting to a 404 when page/post has been deleted)

image

Working with pages/posts:
- links work as expected
- Edit Form is available on actions dropdown
- when post is deleted, Edit Form lands on a default "post is trashed" error page
image

Working with templates:
- links work as expected
- Edit Form shows in actions dropdown
- could not delete template, link works fine, Edit Form takes me to template edit screen, even when it didn't make sense (template part was "lost" due to theme change, but I got to edit it all the same)

image

File: projects/packages/forms/src/dashboard/inbox/dataviews/actions.js [hunk 3]
```diff
@@ -27,6 +27,21 @@ export const viewActionModal = {
...
+	id: 'edit-form',
+	label: __( 'Edit form', 'jetpack-forms' ),
+	icon: <Icon icon={ backup } />,
+	isEligible: item => !! item?.edit_form_url,
+	supportsBulk: false,
+	async callback( items ) {
+		const [ item ] = items;
+		if ( item?.edit_form_url ) {
+			const url = new URL( item.edit_form_url, window.location.origin );
+			window.open( url.toString(), '_blank', 'noopener' );
```
Comment (simison) [inline projects/packages/forms/src/dashboard/inbox/dataviews/actions.js]: Opening not in a new tab seems fine, no? New tabs tend to be disorienting, while in same tab you can return with back button. Especially on mobile.

File: projects/packages/forms/src/contact-form/class-feedback-source.php (hunk 1 above)
Comment (enejb) [reply projects/packages/forms/src/contact-form/class-feedback-source.php]: When the form is part of a template or a widget and the user fills out the form on a 404 page or an archive or search we use the new get_source_title() method to generate what the users sees.

Comment (enejb) [reply projects/packages/forms/src/contact-form/class-feedback-source.php]: The use `(no title)`

See: this was updated to match.

Image

File: projects/packages/forms/src/dashboard/inbox/dataviews/actions.js (hunk 3 above)
Comment (enejb) [reply projects/packages/forms/src/dashboard/inbox/dataviews/actions.js]: Fixed

File: projects/packages/forms/src/contact-form/class-feedback-source.php (hunk 2 above)
Comment (enejb) [reply projects/packages/forms/src/contact-form/class-feedback-source.php:215]: So far it has been working well for me. 
Should we test this across older versions of WP or Gutenberg?

Comment (simison) [reply projects/packages/forms/src/contact-form/class-feedback-source.php:215]: Jetpack supports current stable WP minus one, so no need to test anything older. I don't think there have been changes in recent versions to these URLs either.

File: projects/packages/forms/changelog/fix-feedback-source-data [hunk 4]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: fixed
+
+Forms: Store the feedback source info with more context
```
Comment (edanzer) [inline projects/packages/forms/changelog/fix-feedback-source-data:4]: (adding this as a comment on the changelog just to allow comment threading)

This is testing well! I did not test legacy theme or widget, but tested a range of scenarios with block themes. 

* **404 page**. I added a form to my 404 site editor template. 
  - _Confirm bug_: On trunk, when submitted, this shows the source as '/' (not accurate). There is no edit form button. 
  - _Confirm fix_: On this PR, it shows the source as '404 Not Found' with the url being the actual url I'd entered (/asdf). It takes me to that url, which is of course a 404 page. But this seems correct to me.
  - _Confirm edit button_: On this PR, if I click the 'Edit Form' button, it correctly takes me to the 404 template in the site editor (nice). 
  
* **Form in footer template pattern**. I added a form to my footer template. Then created a "Page with No Form".
  - _Confirm bug_: On trunk if I submit the footer form on "Page with no form", it shows the source as '/' (not accurate). There is no edit form button. 
  - _Confirm fix_: On this PR, if I submit the footer form, it shows the source a "Page with no form" with the correct URL. 
  - _Confirm edit button_: If I click the Edit Form button, it surprisingly takes me to the footer template where I created the form. Actually quite impressed on that. 
  - _Confirm delete page behavior_: If I delete "Page with no form", the source still says "Page with no form" and takes me to the accurate but now deleted url, so I get a 404. Seems like a very reasonable action. 
  
* **Blog archive pagination:** I set my home page to show blog posts, and then navigated to the third page of the blog archive (/page/3) and submitted the form that lives in the footer template pattern. 
  - _Confirm bug_: On trunk, when submitted, this shows the source as '/' (not accurate). There is no edit form button. 
  - _Confirm fix_: On this PR, it shows the source as the site title, and links to the correct page including pagination (/page/3). 
  - _Confirm edit button_: On this PR, if I click the 'Edit Form' button, it correctly takes me to the footer template pattern when the form lives. 
 
* **Page deletion**. I have some other old form pages that I deleted. In the new PR, I now see (deleted) in the link, and the link just goes back to Jetpack Forms admin. That seems reasonable, but also wondering if we should just remove the link? 

* **Tests pass.** I also confirmed tests pass. 

----
Only question: For deleted pages rather than link circularly back to forms admin, I wonder if we should just remove the link? Not a big deal though. 

----
Verdict on merging: This touches sensitive logic and there are lot of possible permutations, so it's possible we'll find an issue that needs fixing. BUT there's a lot of clearly broken behavior now, and this fixes all of it so far. Given that, I'd say LGTM.

**Review by edanzer — DISMISSED** [review]
