### PR TITLE
VideoPress: Fix JITM layout on video edit page

### LINKED ISSUE #30408: VideoPress: JITM renders in the wrong place when loading the details page first
The JITM should have a place in the details page and be correctly re-rendered when changing pages.

https://user-images.githubusercontent.com/8486249/235755125-e168cac7-6359-4b21-95b4-862052d28ab8.mp4

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #30408

## Proposed changes:

* Adds a container on video edit page with specific CSS
* Adds `jetpack-videopress` to the list of pages to refetch the JITM on hash change

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Have a JITM showing up on the VideoPress page. One way to do this is to have an unattached Jetpack Complete plan.
* Go to the VideoPress dashboard
* Check that the JITM displays as normal
* Navigate to a video's details edit page
* Check that the JITM is displayed in that page as well and the layout is not broken
* Click on `Go back` and check that the JITM is re-applied to the dashboard

https://user-images.githubusercontent.com/8486249/236276826-7d6f0f9b-2418-4944-b449-00be9e9a3a9b.mp4

### CODE REVIEW

File: projects/packages/jitm/src/js/jetpack-jitm.js [hunk 1]
```diff
@@ -283,7 +283,9 @@ jQuery( document ).ready( function ( $ ) {
 
 	$( window ).on( 'hashchange', function ( e ) {
 		const newURL = e.originalEvent.newURL;
-		const isJetpackPage = newURL.indexOf( 'jetpack#/' ) >= 0 || newURL.indexOf( 'my-jetpack' ) >= 0;
+		const isJetpackPage = [ 'jetpack', 'my-jetpack', 'jetpack-videopress' ].some( str =>
```
Comment (retrofox) [inline projects/packages/jitm/src/js/jetpack-jitm.js]: what about other Jetpack pages such as Protect, Social... ?

**Review by retrofox — DISMISSED** [review]
Tested. LGTM.

File: projects/packages/jitm/src/js/jetpack-jitm.js (hunk 1 above)
Comment (dhasilva) [reply projects/packages/jitm/src/js/jetpack-jitm.js]: Added.

**Review by retrofox — APPROVED** [review]
