### PR TITLE
eslint: Add eslint-plugin-package-json

### LINKED ISSUE #655: 🛠 Tooling: replace `jsonc-eslint-parser` with `@eslint/json`
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

As suggested in https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/601#issuecomment-2454704112, I am creating a separate issue to discuss replacing `jsonc-eslint-parser` dependency with `@eslint/json`.

[`@eslint/json`](https://bundlephobia.com/package/@eslint/json) is smaller and uses fewer dependencies than [`jsonc-eslint-parser`](https://bundlephobia.com/package/jsonc-eslint-parser). [The announcement post also says](https://eslint.org/blog/2024/10/eslint-json-markdown-support/#write-your-own-language-plugin) that it can be used as a parser for other plugins.

The main problem is that the plugin only works [since version 9.6.0 of ESLint](https://github.com/eslint/json#overview:~:text=Important%3A%20This%20plugin%20requires%20ESLint%20v9.6.0%20or%20higher%20and%20you%20must%20be%20using%20the%20new%20configuration%20system.), and also you can use only a flat config. So you will have to stop supporting eslint@8, but [now it still has more weekly downloads than eslint@9](https://www.npmjs.com/package/eslint?activeTab=versions).

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by anomiex**
Closes MONOREP-49

 

## Proposed changes:

This eslint plugin will sort package.json files and apply other cleanups, replacing the manual use of `sort-package-json` which we're currently only applying to the monorepo root file.
    
The configuration is slightly complex, in that we want different treatment for files in different places:
* Only js-packages require a `name` field.
* Only public js-packages require a description or version.

Note: once upstream fixes https://github.com/JoshuaKGoldberg/eslint-plugin-package-json/issues/655, we should be able to drop the added deps on `eslint-json-compat-utils` and `jsonc-eslint-parser`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None, but a bit of a followup to #44009.
P2 draft: pdWQjU-1mu-p2

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy?
* Try reverting some of the package.json changes here, then run eslint on the files.

### CODE REVIEW

**Comment by anomiex** [comment]
Reviewing by commit may work well for this PR, at least for the initial set of commits.
* [73c7f099](https://github.com/Automattic/jetpack/pull/44559/commits/73c7f099144e0c8f37d63a7827f3298043fe825e): Actual changes to add the plugin.
* [17f543d6](https://github.com/Automattic/jetpack/pull/44559/commits/17f543d60c9f54e27feeeb82349554b1f9b6bbba): Fixes that aren't auto-fixable.
* [d2fae3c3](https://github.com/Automattic/jetpack/pull/44559/commits/d2fae3c30dad7d4edb28306cae5dc15335e3701e): Auto-fixes.
* [cc7e8466](https://github.com/Automattic/jetpack/pull/44559/commits/cc7e8466eaa8fb0d29d51da27badf964ce9bf649): Just the changelogs.

File: tools/js-tools/eslintrc/base.mjs [hunk 1]
```diff
@@ -130,6 +134,18 @@ export function makeBaseConfig( configurl, opts = {} ) {
 	const envConditionNames =
 		process.env.npm_config_jetpack_webpack_config_resolve_conditions?.split( ',' ) ?? [];
 
+	const jsPackageJsons = glob
+		.sync( path.join( rootdir, 'projects/js-packages/*/package.json' ) )
+		.map( p => path.relative( basedir, p ) )
+		.filter( p => ! p.startsWith( '../' ) );
```
Comment (tbradsha) [inline tools/js-tools/eslintrc/base.mjs:140]: We could probably simplify this by passing options to `glob.sync`, e.g. (untested):
```
glob.sync( path.join( rootdir, 'projects/js-packages/*/package.json' ), { cwd: rootdir });
```

File: projects/plugins/paypal-payment-buttons/tests/e2e/package.json [hunk 2]
```diff
@@ -1,18 +1,6 @@
 {
 	"private": true,
 	"type": "module",
-	"description": "plugin--description.",
```
Comment (tbradsha) [inline projects/plugins/paypal-payment-buttons/tests/e2e/package.json:4]: But without this description, how will I know what it does?

**Review by tbradsha — APPROVED** [review]
Looks good and CI is happy. One on-task comment, but no blockers.

File: tools/js-tools/eslintrc/base.mjs (hunk 1 above)
Comment (anomiex) [reply tools/js-tools/eslintrc/base.mjs:140]: That wouldn't make any difference.

Looks like we could get the same effect with something like
```js
    .sync( path.join( rootdir, 'projects/js-packages/*/package.json' ), { cwd: basedir, absolute: false } )
    .filter( p => ! p.startsWith( '../' ) )`;
```
although I'm not sure whether that's actually more clear or not.

Comment (tbradsha) [reply tools/js-tools/eslintrc/base.mjs:140]: Ah, I was reading `rootdir` and `basedir` as the same thing. Let's leave it.
