### PR TITLE
Forms: Properly support formatting options for labels and required text

### LINKED ISSUE #29125: Forms: labels don't respect font styles(such as Italic)
### Quick summary

Italic font fields in the form block display in the Editor but not on the live site.

### Steps to reproduce

1. Add a contact form to a page.
2. Make one of the fields Italic
3. Changes appear in Editor but not on the site. 

https://user-images.githubusercontent.com/74204272/218224996-2c5b0988-7bb1-473f-8fe0-397dfacf5b8f.mp4

### What you expected to happen

To see the Italic font on the site. 

### What actually happened

The font style of the field remained the same. 

### Impact

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes https://github.com/Automattic/jetpack/issues/29125

## Proposed changes:

By investigating a bit it seems that label styles (including `font-weight:bold`) have been there for at least a couple of years. This means that the `bold and italic` options provided in the editor to format the labels doesn't work for a while - if it worked at all in the past.

The approach I'm suggesting here (after the provided feedback) is to remove the formatting `bold` option in the editor for labels, as it seems it's being handled by css and maybe it makes more sense to be a bit more opinionated like this here.

This PR also fixes the formatting for `italic` in labels and both `bold and italic` for required text by updating `strip_tags` to use `wp_kses_post`. I search for a while a better place to use `wp_kses_post` specifically for labels and required text, because `strip_tags` is used in other places too. I couldn't find a good fit though since this function and it's caller ([unesc_attr](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/forms/src/contact-form/class-contact-form-shortcode.php#L161))  is called in various places.

I wouldn't expect any issues to be honest, but more experienced Jetpack devs could help here with feedback.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:
1. Add some form fields and update some of them with `bold and italic`
2. observe that the labels and the `required text` renders in the front end the changes there.

### CODE REVIEW

**Comment by enejb** [comment]
I think we should try to support the bolding and the italicising of labels.  

As you said it currently is not supported as you mentioned because of predefined styles but also because we strip the tags out of the rendering in https://github.com/Automattic/jetpack/blob/528db4f8ebe72b0935c53828c3f8a0fc16459a94/projects/packages/forms/src/contact-form/class-contact-form-plugin.php#L120, https://github.com/Automattic/jetpack/blob/528db4f8ebe72b0935c53828c3f8a0fc16459a94/projects/packages/forms/src/contact-form/class-contact-form-plugin.php#L126 and esc_html in https://github.com/Automattic/jetpack/blob/528db4f8ebe72b0935c53828c3f8a0fc16459a94/projects/packages/forms/src/contact-form/class-contact-form-field.php#L492 

but adding that support would make the solution more wysiwyg and have less limitations.

**Comment by ntsekouras** [comment]
>I think we should try to support the bolding and the italicising of labels.

What about the existing styles that are css based about labels, which are also the default ones? If I'm not wrong in order to add the support for the formatting we should remove the styles which will result in existing labels in sites, changing from bold to normal.

**Comment by simison** [comment]
Yeah, Bold one is tougher to fix in backwards compatible way. :-/

Bold backwards compatibility would need to come from us injecting `strong` to labels if none exist, and removing it once they use the Rich text `strong`.

Let's try to keep supporting `em` though! That should be doable.

Screenshot 2025-01-10 at 12 45 33

Can we easily still support bold in `(required)` bits inside labels?

**Comment by simison** [comment]
If we removed bold support, do we need to add block deprecation path for blocks that were stored in content with `strong` already, so that we don't get "block failed to render" errors in editor?

**Comment by simison** [comment]
New lines probably aren't working currently either?

Screenshot 2025-01-10 at 12 58 14
Screenshot 2025-01-10 at 12 58 23
Screenshot 2025-01-10 at 12 59 18

**Review by edanzer — COMMENTED** [review]
To confirm my understanding: as is, the the bold/italic options in the toolbar don't work because we override them directly with CSS. So options are (a) remove the non-working controls, which is what we do here or (b) remove the CSS overrides so the controls work. 

Sounds like it's a matter of preference which way we go. I'm fine with either, but given that these are just basic core font controls, I'd probably lean in favor of keeping the controls and removing the CSS. It's easy to imaging some users wanting to tweak the form label styles. 

I have confirmed that the PR works as intended and removes those controls. 

@simison do you have preferences here? 

form-label-css

File: projects/packages/forms/src/blocks/contact-form/components/jetpack-field-label.js [hunk 1]
```diff
@@ -33,8 +33,7 @@ const FieldLabel = ( {
 					setAttributes( { label: value } );
 				} }
 				placeholder={ placeholder ?? __( 'Add label…', 'jetpack-forms' ) }
-				withoutInteractiveFormatting
-				allowedFormats={ [ 'core/bold', 'core/italic' ] }
+				__unstableDisableFormats
```
Comment (edanzer) [inline projects/packages/forms/src/blocks/contact-form/components/jetpack-field-label.js]: I haven't seen __unstableDisableFormats before. Is that something that's needed when removing font formatting controls?

**Comment by simison** [comment]
@edanzer if we can find a way to not change bold labels to non-bold ones for all existing forms out there, I'm all in trying to preserve the bold option. Otherwise, at leas as a temporary solution it's fine to remove bold and keep the `em`.

> because we override them directly with CSS.

The ultimate cause is `wp_kses` stripping out the tags from output; they do work in the editor, and CSS override for `bold` complicates this further.

We can add the Rich text tags to `wp_kses()` array so that they don't get stripped out.

**Comment by edanzer** [comment]
> find a way to not change bold labels to non-bold ones for all existing forms out there

I assume there's a way to it so bold is on by default, though I don't know how off the top of my head. But we could update from (a) bold applied via CSS to (b) bold applied via the toolbar controls. 

All that said, if we're comfortable just removing those, then I'm fine with that too.

File: projects/packages/forms/src/blocks/contact-form/components/jetpack-field-label.js (hunk 1 above)
Comment (ntsekouras) [reply projects/packages/forms/src/blocks/contact-form/components/jetpack-field-label.js]: `__unstableDisableFormats` is a core API that disables all kind of formatting. Despite its name, is considered stable as it has landed in core for many releases.

**Comment by ntsekouras** [comment]
I updated the PR per the suggestions but:

>This PR also fixes the formatting for italic in labels and both bold and italic for required text by updating strip_tags to use wp_kses_post. I search for a while a better place to use wp_kses_post specifically for labels and required text, because strip_tags is used in other places too. I couldn't find a good fit though since this function and it's caller ([unesc_attr](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/forms/src/contact-form/class-contact-form-shortcode.php#L161)) is called in various places.

>I wouldn't expect any issues to be honest, but more experienced Jetpack devs could help here with feedback.

**Review by edanzer — APPROVED** [review]
This works as expected. 

I'm not an expert Jetpack dev, but I'd think wp_kses_post here is fine. 

On the bigger question of the bold/italic controls... All things equal, I'd still prefer to keep both bold and italic controls - even at risk of breaking backwards compatibility. We'll be maintaining and building this plugin for long time, and that seems like a better and more sustainable and more usable approach for the future. But I understand the backwards compatibility concerns and don't feel too strongly - and would likely be overruled if I did :). 

For now, this works as expected and is inline with past feedback, so I'd say roll with it. We can always revisit the bold control later if worth it.
