### PR TITLE
Jetpack Boost: Improved page cache and error handling

### LINKED ISSUE #35896: [Boost] Disable Page Cache feature if setup fails
Suggested in pedxs5-oQ-p2#comment-294

Currently, the feature stays on, but we show an error notice if setup fails. This might be confusing to some users.

We can address that by toggling the feature off if there's an issue with the setup! This would also eliminate the "try again" button, as users would just have to toggle the feature back on again.

### PR DESCRIPTION
**Pull request by pyronaur**
Fixes #35896

## Proposed changes:
- Enhanced the page cache module state management and error messaging in Jetpack Boost
- Implemented a more responsive UI that reduces flickering
- Added actions to clear the cache and improved handling for setting up the cache
- Refactored error handling to restore proper message formatting
- Introduced a new 'dismissed' property for page cache errors to manage their visibility
- Removed the 'Meta' component for page cache and its associated styles, concentrating logic into the 'PageCache' component
- Added a callback for actions to take before toggling the page cache module
- Updated handling of cache bypass patterns and logging within the page cache module

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
N/A

## Testing instructions:
- Ensure that the page cache module can be enabled and disabled without issues
- Verify that error messages display correctly and can be dismissed
- Check the responsiveness of the UI, ensuring there's no excessive flickering during operations
- Test the error handling by introducing known errors and observing correct message formatting

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx [hunk 1]
```diff
@@ -1,34 +1,61 @@
...
+			setPageCache( false );
+		}
+	}, [ canReset, setCanReset, setPageCache ] );
+	return (
+		<>
+			{ setup && (
+				<MutationNotice
+					mutationId="page-cache-setup"
+					isPending={
+						setup.isPending || ( !! pageCache?.active && ( ! error || !! error.dismissed ) )
```
Comment (dilirity) [inline projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx]: I think this causes the `Setting up cache...` to show up when opening the page and caching is enabled (and working).

image

To reproduce, enable caching and wait for setup to complete. Then refresh the page and you should see the same notice.

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx [hunk 2]
```diff
@@ -1,34 +1,61 @@
...
+					}
+					isError={ setup.isError }
+					isSuccess={ setup.isSuccess && ! error }
```
Comment (dilirity) [inline projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx]: Is it possible to have setup success and an error? Just wondering why `! error` is needed here.

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/lib/get-error-data.tsx [hunk 3]
```diff
@@ -189,13 +189,10 @@ type FormattedError = {
 	title: string;
 	message: React.ReactNode;
 };
-function getErrorData( status?: PageCacheError ): FormattedError {
+function getErrorData( status?: PageCacheError ): false | FormattedError {
 	// Fall back to unknown error if no status
```
Comment (dilirity) [inline projects/plugins/boost/app/assets/src/js/features/page-cache/health/lib/get-error-data.tsx]: This comment is now outdated.

File: projects/plugins/boost/app/assets/src/js/pages/index/index.tsx [hunk 4]
```diff
@@ -154,10 +164,15 @@ const Index = () => {
...
+						<Health
+							error={ pageCacheError.data }
+							setError={ pageCacheErrorMutation.mutate }
+							setup={ pageCacheSetup }
+						/>
 					</>
 				}
 			>
-				<PageCache setup={ pageCacheSetup } error={ pageCacheError.data } />
+				{ ! pageCacheError.data && ! pageCacheSetup.isError && <PageCache /> }
```
Comment (dilirity) [inline projects/plugins/boost/app/assets/src/js/pages/index/index.tsx:201]: Bye bye prop drilling. Nice!

**Review by dilirity — DISMISSED** [review]
Nice work on this!

There's just one small thing and we can 🚢

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx (hunk 2 above)
Comment (pyronaur) [reply projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx]: This is to prevent sticky `isSuccess` true on `setup` when toggling on again.

**Comment by dilirity** [comment]
@pyronaur I hope you don't mind, but I did some updates to the feedback a user would get when working with the page cache module.

Previously, if on a slow connection and you enable the page cache module, the mutation notice for setting up cache would show up after the module's `set` request completed. During that time, the meta (summary, actions) would be visible and a user might think everything is okay and navigate away.

I've added a "Enabling page cache..." mutation notice right when the user toggles the module, to show an indication that something's happening right away. As soon as the `setup` request is sent, that mutation notice is removed and the "Setting up cache...` one is shown.

The second thing I fixed is when there was a setup error, you'd get the `An error occurred while setting up cache.` mutation notice. After toggling the module, the notice under the description disappears, but the mutation notice remained showing the `An error occurred while setting up cache.` message.

I've updated this so as soon as the user clicks to enable the module, the `setup` mutation notice is removed.

Please review the changes, as I'm not sure what I did is the best approach.

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx (hunk 1 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx]: With 112d204 this no longer happens.

**Comment by thingalon** [comment]
We've got a little style breakage here: 
image

**Review by thingalon — DISMISSED** [review]
Seems to work well :)

File: projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx [hunk 5]
```diff
@@ -1,34 +1,62 @@
...
+			setCanReset( true );
+		}
+	}, [ setup?.isError, error, setCanReset ] );
+
+	useEffect( () => {
+		if ( canReset ) {
+			setCanReset( false );
+			setPageCache( false );
+		}
+	}, [ canReset, setCanReset, setPageCache ] );
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/features/page-cache/health/health.tsx:29]: I think a coment explaining canReset would be a good idea. Can be done in a followup PR.

File: projects/plugins/boost/app/assets/src/js/features/page-cache/page-cache.tsx [hunk 6]
```diff
@@ -1,34 +1,290 @@
...
+	patterns: string;
+	setPatterns: ( newValue: string ) => void;
+	showErrorNotice: boolean;
+};
+
+const BypassPatterns = ( {
+	patterns,
+	setPatterns,
+	showErrorNotice = false,
+}: BypassPatternsProps ) => {
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/features/page-cache/page-cache.tsx:150]: This file seems to contain multiple meaty components. Would it make sense to split it up?

Can be a separate PR.

File: projects/plugins/boost/app/assets/src/js/features/ui/mutation-notice/mutation-notice.tsx [hunk 7]
```diff
@@ -1,34 +1,35 @@
...
- *		 />
+ *	useMutationNotice( {
+ *		"unique-mutation-id",
+ *		mutationState,
+ *		{
+ *			savingMessage: 'Saving…',
+ *			errorMessage: 'An error occurred while saving changes. Please, try again.',
+ *			successMessage: 'Changes saved.',
+ *		}
+ *	} );
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/features/ui/mutation-notice/mutation-notice.tsx:32]: ❤️

**Review by thingalon — APPROVED** [review]
This seems to work really well and this PR contains a bunch of improvements we very much want in. 

I have left about multiple complex components in one file - but that can be addressed in a separate PR. :)

**Comment by thingalon** [comment]
Cherry-picked to 3.1.0 in a2795a9fb2.
