### PR TITLE
My Jetpack: Fix Protect card Tooltip placement & content issues

### LINKED ISSUE #40433: My Jetpack: Protect card Threats tooltip styles/content issues
### Impacted plugin

My Jetpack - Jetpack, Protect

### Quick summary

- The threats tooltip styles do not appear to be applied.
- The logic for the tooltip text is incorrect, in the case of the image below I had 6 threats, 1 of which was critical - the wording suggests I have 6 critical threats.
- IMO the content here could be improved:
   - `threat..` should either be `threats...` (a full ellipsis) or `threats.`(the end of the sentence).
   - The final portion of the text may be a little misleading:
      - Not all threats are auto-fixable.
      - The use of `in the product` is not an especially clear directive.
 
Image

### Steps to reproduce

1. Install/activate Jetpack Protect with a Scan upgrade
2. Add various severity threats using the Scan Helper in the Jetpack Debug Tool
3. Run a scan to detect them
4. Proceed to the My Jetpack section
5. Hover over the icon to the right of the term Threats to view the tooltip
6. Note that I have only tested this particular scenario, its unclear if the issues persist in other card states

### A clear and concise description of what you expected to happen.

The Threats tooltip should be styled similar to the others and the content should be accurate, clear, and concise.

### What actually happened

See image provided in main description.

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by elliottprogrammer**
This PR fixes a few minor issues with the placement and content of the Tooltips in the Protect product card in My Jetpack.

Original issues (screenshots):

Mobile view - Tooltip issues
Threats Tooltip | Auto-firewall Tooltip (Mobile view)
--- | ---
protect-before | Screen Shot on 2024-12-19 at 16-04-06

** Notice in the "Auto-fix threats" tooltip (left img), it says "The last scan identified 6 critical threats.. But..."; **This is wrong**, as you can see, there is 6 (regular) threats and 1 critical threat.
This PR also fixes this incorrect wording ⤴️.

Fixes https://github.com/Automattic/jetpack/issues/40433

## Proposed changes:

* Fixes the appearance "Auto-fix threats" tooltip (increases the width to better fit the content)
* Fixes the wording/content in the "Auto-fix threats" tooltip with the correct distinction between the number of (regular) threats and critical threats. Also adjusts wording to make it a little more clear that not all threats can be auto-fixed.
* Fixes the "Auto-firewall" tooltip, on mobile so that half of it is no longer overflowing off the side of the viewport.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

- Install/activate Jetpack Protect with a Scan upgrade
- Using the Scan Helper in the Jetpack Debug Helper/Tools plugin, select the first EIACAR Threats selection to Add five EICAR threats to the site (one for every severity).
- Run a scan to detect them
- Proceed to the My Jetpack section, scroll down to the Protect product card.
- Hover over and click the "Threats" info icon tooltip to view the tooltip. It should look like this screenshot:

Desktop | Mobile
--- | ---
Screen Shot on 2024-12-20 at 02-01-38 | Screen Shot on 2024-12-20 at 02-02-35

- In mobile view Hover over and click the "Auto-firewall" info icon tooltip. It should look like this screenshot:

Screen Shot on 2024-12-19 at 14-06-38
- Thats it!

### CODE REVIEW

File: projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts [hunk 1]
```diff
@@ -0,0 +1,210 @@
+/* eslint-disable jsdoc/check-indentation */
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts:1]: Thank you for adding these types!

File: projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+	| 'overlay';
+
+export type PopoverAnchorRefReference = MutableRefObject< Element | null | undefined >;
+export type PopoverAnchorRefTopBottom = { top: Element; bottom: Element };
+
+export type VirtualElement = Pick< Element, 'getBoundingClientRect' > & {
+	ownerDocument?: Document;
+};
+
+export type PopoverProps = {
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts:34]: I'm guessing the Popover WordPress component doesn't have an exported types we could use instead? If not, how hard would it be to add them there? Only asking because the ideal scenario would be to have the component type itself, but I understand that may be more difficult than it's worth

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/scan-threats-status.tsx [hunk 3]
```diff
@@ -157,8 +157,22 @@ function ThreatStatus( {
...
+				<InfoTooltip
+					tracksEventName={ 'protect_card_tooltip_open' }
+					tracksEventProps={ {
+						location: 'threats',
+						feature: 'jetpack-protect',
+						has_paid_plan: true,
+						threats: numThreats,
+					} }
+				>
+					<>
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/scan-threats-status.tsx]: Does this fragment need to be here? It's wrapped in a component, I think it can be removed 🤔

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts [hunk 4]
```diff
@@ -49,13 +54,26 @@ export function useProtectTooltipCopy(): TooltipContent {
...
 			return 'admin.php?page=jetpack-protect#/firewall';
 		}
 		return isJetpackPluginActive() ? 'admin.php?page=jetpack#/settings' : null;
 	}, [ isProtectPluginActive ] );
 
+	const protectDashboardUrl = useMemo( () => {
+		if ( isProtectPluginActive ) {
+			return protectPluginDashboardUrl;
+		}
+		return `https://cloud.jetpack.com/scan/${ siteSuffix }`;
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts]: This is just an idea and I'm not sure how much better it would be, but it might be useful to have a `getJetpackCloudLink` utility function that could be used like
```
return getJetpackCloudLink( `/scan/${sitesuffix}` );
```
Let me know what you think 😄

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts [hunk 5]
```diff
@@ -173,23 +200,50 @@ export function useProtectTooltipCopy(): TooltipContent {
...
-									numThreats,
-									'jetpack-my-jetpack'
-								),
-								numThreats
-							)
-						),
+						text: criticalThreatCount
+							? createInterpolateElement(
+									sprintf(
+										/* translators: %1$s is the number of threats and %2$s is the numner of critical threats on the site. */
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts]: This comment is missing an explanation for %3$s

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts [hunk 6]
```diff
@@ -173,23 +200,50 @@ export function useProtectTooltipCopy(): TooltipContent {
...
+									{
+										a: createElement( 'a', {
+											href: protectDashboardUrl,
+											onClick: trackProtectDashboardLinkClick,
+										} ),
+									}
+							  )
+							: createInterpolateElement(
+									sprintf(
+										/* translators: %s is the singular or plural of number of detected threats on the site. */
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts]: This comment is missing one for %2$s

**Review by CodeyGuyDylan — DISMISSED** [review]
I left a few minor comments but I don't see any as blocking. The translator comment should be fixed before deploying but that won't require a re-review

File: projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts (hunk 2 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/info-tooltip/types.ts:34]: Yeah right, the Popover WordPress component doesn't have any exported types, unfortunately.  But yeah you're right, it would be nice if it did! 👍
I'll add a followup maintenance task to update the WordPress Popover component to export the Popover type, and then come back here to clean up the InfoTooltip types.

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/scan-threats-status.tsx (hunk 3 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/scan-threats-status.tsx]: Oh I guess not! Good catch! Thanks! 🙂

File: projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts (hunk 4 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-cards-section/protect-card/use-protect-tooltip-copy.ts]: Actually I refactored this..
Instead, I refactored class `Protect::get_manage_url()` function to return either the Protect plugin dashboard url or the Jetpack Cloud Scan url based on whether the standalone or Jetpack plugin is installed & activated.
Then I pull and use that url here in `use-protect-tooltip-copy.ts`.  I think this would be the more appropriate solution. What do you think?
