### PR TITLE
Forms: Add tracking for plugin installs

### LINKED ISSUE #2254: Stats: add width and height attributes to tracking pixel image
> the image g.gif that the stat module of jetpack outputs on the html fails when tested by Gtmetrix because no dimension (6x5) are specified
>
> The following image(s) are missing width and/or height attributes.
>
> http://pixel.wp.com/g.gif?v=ext&j=1%3A3.5.3&blog=22744152&post=3974&tz=2&srv=www.cookingwithpeachy.com&host=www.cookingwithpeachy.com&ref=&rand=0.5116504428442568 (Dimensions: 6 x 5)

Would it be possible to add the width and height attributes to the image?

Suggested here:
https://wordpress.org/support/topic/specify-image-dimension-for-ggif

### PR DESCRIPTION
**Pull request by edanzer**
Fixes #2254
Replaces #41695 and #41705

## Proposed changes:

Adds Tracks events when users click to install or activate either Jetpack CRM or Creative Mail from the contact form block sidebar. I copied the pattern we use for tracking Stripe clicks in the payment button blocks ([see here](https://github.com/Automattic/jetpack/blob/125c2430835f477bc255dae45246e6f8277f81d7/projects/plugins/jetpack/extensions/shared/components/stripe-nudge/index.jsx#L21)).

In one of the other PRs @enejb [suggested](https://github.com/Automattic/jetpack/pull/41695#issuecomment-2649406636) avoiding code duplication by putting the tracking in the installAndActivatePlugin method. But (a) we'd still need to add the changes twice in that method and the activatePlugin method and (b) we need to know the source of a plugin install or activation, not just that it happened. 

My other approach also didn't do (b), which is why I've prepared this this as an alternative. 

jetpack-forms-crm-button

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None.

## Does this pull request change what data or activity we track or use?

Yes. 

## Testing instructions:

Preparation: 
- Tracks Vigilante: You will need to ensure you can see Tracks events as they are fired. The best way is to install Tracks Vigilante here: https://github.com/Automattic/tracks-chrome-extension Once installed, you'll be able to see tracks events in the Chrome toolbar.
- Jetpack CRM Plugin. Deactivate and delete Jetpack CRM if you have it installed as a separate plugin.
- Creative Mail Plugin. Deactivate and delete this if you have it installed as a separate plugin.

Test: 
- Go to a page or post and insert a form block.
- Clear all current tracks events from Tracks Vigilante to make it easier to see new events.
- Go to the contact form block sidebar and click the button to install Jetpack CRM. 
- Confirm that the `jetpack_form_crm_plugin_install_click` Tracks event is fired.
- Also in the sidebar click the button to install Creative Mail. 
- Confirm that the `jetpack_forms_creativemail_plugin_install_click` Tracks event is fired.
- Go to your site's plugin page and deactivate both plugins but leave the installed.
- Return to your post with your contact form, refresh the page if needed, go to the contact form block sidebar, and click the buttons the activate Jetpack CRM and Creative Mail again.
- Confirm that the `jetpack_forms_crm_plugin_activate_click` and `jetpack_forms_creativemail_plugin_activate_click` Tracks events iare fired.

### CODE REVIEW

File: projects/packages/forms/src/blocks/contact-form/components/jetpack-crm-integration/jetpack-crm-integration-settings-plugin-state.js [hunk 1]
```diff
@@ -75,18 +83,25 @@ const CRMPluginIsNotInstalled = ( { installAndActivateCRMPlugin, isInstalling }
 };
 
 const CRMPluginIsInstalled = ( { activateCRMPlugin, isInstalling } ) => {
+	const { tracks } = useAnalytics();
 	return (
 		<p className="jetpack-contact-form__crm_text jetpack-contact-form__integration-panel">
 			<em>
 				{ __(
-					'You already have the Jetpack CRM plugin installed, but it’s not activated.',
+					"You already have the Jetpack CRM plugin installed, but it's not activated.",
```
Comment (edanzer) [inline projects/packages/forms/src/blocks/contact-form/components/jetpack-crm-integration/jetpack-crm-integration-settings-plugin-state.js:91]: These changes are unrelated to the PR, but were required by our commit checks.

File: projects/packages/forms/src/blocks/contact-form/components/jetpack-newsletter-integration-settings-plugin-state.js [hunk 2]
```diff
@@ -81,7 +95,7 @@ const CreativeMailPluginIsActive = () => {
 	return (
 		<p>
 			<em>
-				{ __( 'You’re all setup for email marketing with Creative Mail.', 'jetpack-forms' ) }
+				{ __( "You're all setup for email marketing with Creative Mail.", 'jetpack-forms' ) }
```
Comment (edanzer) [inline projects/packages/forms/src/blocks/contact-form/components/jetpack-newsletter-integration-settings-plugin-state.js:98]: These changes are unrelated to the PR, but were required by our commit checks.

**Review by enejb — APPROVED** [review]
The changes look good from my end. 
Thanks for adding these events
