### PR TITLE
Comments: Skip Photon resizing for Facebook avatars

### LINKED ISSUE #6992: Discussion: problems with avatar when user logs using facebook
The problem is quite simple. It seems like photon (used by jetpack) is unable to fetch facebook user profile image. The result is a broken image.

Opening the photon link the result is a message witch says
"We cannot complete this request, remote data could not be fetched"

Removing the suffix "https://i0.wp.com/" from the url the avatar seems to be accessible.

I have the latest version of Wordpress with the latest stable version of Jetpack

### PR DESCRIPTION
**Pull request by aduth**
Fixes Automattic/io#668
Fixes #6992

#### Changes proposed in this Pull Request:

* For comments left by users authenticated via Facebook or Twitter, no longer attempt to resize the avatar via Photon. This resolves an issue with Facebook avatars appearing broken due to limitations of Photon respecting query parameters of the source image URL. Specifically, the redirect of a picture resource from Facebook's Graph API includes query parameters that must be included in the CDN image request, otherwise resulting in a 403 status (broken image).

Note query parameters after following redirect:

http://graph.facebook.com/600634677/picture

#### Testing instructions:

* Verify that a post with comments left by either Facebook or Twitter users show their respective Facebook or Twitter avatar.

cc @KokkieH @kraftbj @chaitanyamsv

### CODE REVIEW

File: modules/comments/base.php [hunk 1]
```diff
@@ -277,18 +277,4 @@ public function set_comment_cookies( $comment_id ) {
 			setcookie( 'comment_author_url_'   . COOKIEHASH, esc_url($comment->comment_author_url), time() + $comment_cookie_lifetime, COOKIEPATH, COOKIE_DOMAIN );
 		}
 	}
-
-	/**
```
Comment (jeherve) [inline modules/comments/base.php]: Instead of creating a new function, I wonder if we could add the `graph.facebook.com` domain to the list of banned domains in Photon, here:
https://github.com/Automattic/jetpack/blob/master/functions.photon.php#L303

That would solve the issue everywhere where such URLs are being used, not just in comments.

That said, it would be interesting to find out why the domain was whitelisted in the first place:
https://github.com/Automattic/jetpack/blame/master/functions.photon.php#L275

It seems it was done here:
https://code.trac.wordpress.org/ticket/17

cc @mdawaffe

Comment (kraftbj) [inline modules/comments/base.php]: @mdawaffe is out for awhile, so it'll be best to add the domain to the banned list and circle back later if needed.

Agree with adding any domains that fail to the banned list instead of removing the functionality outright.

Comment (aduth) [inline modules/comments/base.php]: Banned domain seems like a more direct and safer approach, sure. Sorta begs the question why we call Photon functions with a banned domain in the first place (at least assuming we know it would be one, as is the case here).

The explicit whitelisting is interesting though... because the filter it's attached to is related to query arguments being preserved, not unlike the issue we're seeking to resolve here. But the case we're encountering is not that the URL passed through `jetpack_photon_url` needs query arguments but rather the URL it redirects to (only determined Photon server-side). It may be the case that this redirect had not always existed?

**Comment by aduth** [comment]
>I still see some issues in the WordPress.com comment iFrames

I imagine we'll need to sync equivalent changes to WordPress.com for this to be resolved.

>The PR also didn't change the behaviour for Twitter comments, although Twitter is mentioned in the PR title.

I'm not aware of any issues with Photon being applied to Twitter images. Excluding Twitter in the original changes was likely more a point of consistency in how we'd treated "foreign avatars" in the comment's `get_avatar` method.

**Comment by jeherve** [comment]
> Excluding Twitter in the original changes was likely more a point of consistency in how we'd treated "foreign avatars" in the comment's get_avatar method.

That makes sense. Should we then exclude the Twitter domain from Photon as well?

**Comment by aduth** [comment]
> Should we then exclude the Twitter domain from Photon as well?

I don't think we need to.

**Comment by jeherve** [comment]
It might be worth including Facebook's `fbcdn.net` CDN URLs as well, as they are not compatible with Photon either. Here is an example:

`https://scontent-mrs1-1.xx.fbcdn.net/v/t31.0-8/12465927_813290572132664_8975279368599689506_o.jpg?oh=dce7dae9c356386c5bb24e64cf3fa56d&oe=598B3042`

Reported in 3221931-t and in [this thread](https://wordpress.org/support/topic/problem-with-photon-1/#post-7623835).

**Comment by aduth** [comment]
Makes sense @jeherve . 6aeef69 takes a slightly different approach, testing against banned host name patterns to accommodate wildcard subdomain on Facebook's CDN URLs.

**Comment by billbennettnz** [comment]
I'm still seeing broken Twitter avatars in my Jetpack comments. Is this the same problem?

**Comment by zinigor** [comment]
@billbennettnz we can't be sure, can you provide a link to the page where you're seeing broken Twitter avatars please? Or at least copy the URL of the broken image and paste it here in a comment? Thanks!

**Comment by billbennettnz** [comment]
Hi Igor

I replied earlier to your colleague Anne MaCarthy can you see that or shall I resend to you?

**Comment by zinigor** [comment]
@billbennettnz yes, thank you, Anne has pointed me in the right direction, let's continue there.

**Comment by aheckler** [comment]
@annezazu @zinigor I have another user for whom this is still happening in 3136104-t. Do y'all have a link to the ticket I can check out? Or maybe @billbennettnz can chime in if the issue was fixed?

**Comment by annezazu** [comment]
3250576-t @aheckler

**Comment by billbennettnz** [comment]
Just checked, it still happens. See the bottom comment on this page:

https://billbennett.co.nz/2016/04/25/doing-one-thing-at-a-time-works-wonders/
