### PR TITLE
Jetpack Newsletter: Set the post access level to everyone when deleting the paywall block. 

### LINKED ISSUE #42663: Paywall Block Issue: Content Remains Hidden After Deletion of Paywall Block
### Impacted plugin

Jetpack

### Quick summary

After adding a [Paywall block](https://jetpack.com/support/newsletter/paid-newsletters/#use-the-paywall-block) to a post and publishing it, the content above the block remains visible while the content below stays hidden, as expected. However, after removing the Paywall block and reloading the post, the block still appears, and all post content remains hidden. Ideally, the Paywall block should be removed, and all content should be visible.

@bobmatyas also tested this and can reproduce the issue and found when the Paywall block is used, it seems to set an access flag » [Screenshot](https://github.com/user-attachments/assets/7b861d3a-e4dd-48cf-87a6-359a3773e0e6). Even after the block is removed from the post, it has a Newsletter access level, which looks like causing the Paywall block to render.

The issue was originally discussed at https://github.com/Automattic/jpop-issues/issues/9554#issuecomment-2740168121

### Steps to reproduce

1. Install the Jetpack plugin and any default WP theme like [Twenty Twenty](https://wordpress.org/themes/twentytwenty/).
2. Add a new post and add the "[Paywall](https://jetpack.com/support/newsletter/paid-newsletters/#use-the-paywall-block)" block.
3. Add some content above (visible area) and some below (hidden area) the "Paywall" block and publish the post.
4. Open the post in an incognito window and at this point content added in the visible area is showing and the content added in the hidden area is hidden - no problem up to this point.
5. Now go back to the post editor and remove the "Paywall" block.
6. Go to the incognito window, reload the same post, and here we can see all the content on the post is hidden and the "Paywall" block is still visible. Ideally, because we have removed the "Paywall" block in Step 5, the "Paywall" block should not show on the post and all content of the post should not get hidden behind the block.

### Site owner impact

More than 60% of the total website/platform users

### Severity

Major

### Platform (Simple and/or Atomic)

Self-hosted, Atomic, Simple

### PR DESCRIPTION
**Pull request by spsiddarthan**
Fixes https://github.com/Automattic/jetpack/issues/42663

When the paywall is added, the post's access status also changes with it. 
Screenshot 2025-04-01 at 2 06 55 PM

The paywall gives you only two options -> Anyone subscribed/paid subscribers only. These options are in sync with what we see in the right sidebar. 

However, when we delete the paywall block in Gutenberg, the previously saved option is persisted. 

## Proposed changes:

* When the paywall block is deleted, set the post access status to 'everyone'. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1743498522711249-slack-C083ZPVVDTK
## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* You need to setup a paid newsletter site on simple/atomic/jetpack to test this. 

* Without this branch, and on trunk, create a paid newsletter site.  
* Now, add a [paywall block](https://jetpack.com/support/newsletter/paid-newsletters/#use-the-paywall-block) and create a post with partially paywalled content.  

Screenshot 2025-04-01 at 3 39 00 PM

* In an incognito window, confirm that the post is paywalled as expected.  
* Now, return to the post and remove the paywall block. In the right sidebar, you will see that the option you selected earlier when you added the paywall block is still persisted.  

Screenshot 2025-04-01 at 2 06 55 PM

* If you open a new incognito window, the paid content will still not be visible. This is because deleting the block does not change the post's access status.  

* Run the command in [this comment](https://github.com/Automattic/jetpack/pull/42788#issuecomment-2766030202) to run this branch on your sandbox. You can skip this step on Jetpack/Atomic.  
* Create a new post with paywalled content and confirm that a user in an incognito window cannot see the paywalled content.  
* Now, delete the paywall from your post. Notice that in the right sidebar, the access level of the post is set to "Everyone."  

https://github.com/user-attachments/assets/601dce58-458c-4fd0-a93d-c14489516391

* Save the post and load it in an incognito window. You will see that the previously paywalled content loads.

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
I tested on Simple, Atomic, and Jetpack and deleting the block reset the access back to everyone. ✅ 

It was interesting that I had to enable the newsletter module and set up a paid tier to see the Paywall block, but not actually set up Stripe. I also didn't change the post access at all, but still saw the issue without the fix.

Edit: I re-tested with changing the access on Simple, and it worked correctly.

File: projects/plugins/jetpack/extensions/blocks/paywall/edit.js [hunk 1]
```diff
@@ -19,6 +19,17 @@ function PaywallEdit() {
...
+
+	// Add cleanup effect to reset access level when paywall is removed
+	useEffect( () => {
+		// This function will run when the component unmounts
+		return () => {
+			// Reset access level to "everybody" when the paywall block is removed
+			setAccess( accessOptions.everybody.key );
+		};
+		// eslint-disable-next-line react-hooks/exhaustive-deps
+	}, [] );
```
Comment (pablinos) [inline projects/plugins/jetpack/extensions/blocks/paywall/edit.js:32]: Hi @spsiddarthan! I'm not entirely sure how I got subscribed to this PR, but maybe I worked on this at some point. As I am, I thought I might stick my nose in, where it's not wanted 😄 

I'm not sure if unmount only gets run when the block is removed. I notice that the [access level is set](https://github.com/Automattic/jetpack/pull/42788/files#diff-2bb7e3e11a81533d6449c5a55f26bdf039f700feeee3f7219e72432b15c4eaeaR45-R49) if it hasn't been, as the component is mounted, which will happen as it's inserted, but could happen on other re-renders.

I can't test it quickly as I haven't got a site with subscribers and paid subscribers, but it might be worth checking that if you change other properties of the block (or have a really long post with the last couple of paragraphs being restricted, or some other circumstance that might make the block re-render) that the setting doesn't get reset to `accessOptions.subscribers.key` as we change it to `everybody` here and then the other useEffect updates it.

If that is a problem you might need to look into [subscribing](https://developer.wordpress.org/block-editor/reference-guides/packages/packages-data/#subscribe) to block changes in the document, and look for all instances of the block being removed.

Talking of all instances. Could you have two or three Paywall blocks, and this might cause the access level to be reset?

Comment (allilevine) [reply projects/plugins/jetpack/extensions/blocks/paywall/edit.js:32]: Your sticking your nose in is always appreciated, @pablinos. ❤️ I created a follow-up issue to investigate.
