### PR TITLE
RDV: Fix a performance issue and assign a12s treatment

### LINKED ISSUE #98603: Jetpack: Test assignments slowing page generation time for Atomic sites
### Context and steps to reproduce

When I load wp-admin, while proxied so that debug bar shows, for my atomic site, I see that there are two requests for assignments that are adding 320+ ms to the page generation time. 

Image

Naively, I assume that we're making these requests to get the bucket that this site/user has been assigned to. And I also assume that we need that bucket during page generation.

But, the issue is that it seems like we're making the same network requests with every page load. We should probably be caching the results of these calls in an option or transient.

### Site owner impact

More than 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### Platform

Atomic

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixed an issue that caused to make an API request to ExPlat on each page request for users that were in control or if they were a12s.

This PR also forces treatment to all a12s on both Simple and Atomic sites.

On Simple sites, we use is_automattician since that's more accurate than relying on proxy. Although not needed for performance, the result is also cached in the user option so that a12s to be able to use the escape hatch.

On Atomic sites, the logic is a bit more complicated. The switch for a12s is handled with two conditions: Calypo: if there's an admin_menu_a11n query param (which is passed by WPCOM admin-menu API mapper

WP-Admin: Rely on the is proxy check.

Since this PR comes after a revert, we also need to change the caching key to pull again the experiment assignment from ExPlat.

Fixes https://github.com/Automattic/wp-calypso/issues/98603

## Proposed changes:

* Add caching for Simple and Atomic explat assignment
* Apply treatment for a12s on Simple and Atomic
* Change the key

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

**Simple Sites**
* Use the Jetpack downloader and install the changes on your sandbox
* Go to a Simple Site
* Notice that you now get treatment

**Atomic Sites**
* Checkout this branch on your sandbox 171436-ghe-Automattic/wpcom
* Go to WPCOM and grab your user id (get_current_user_id() doesn't work well in `wp shell` on AT)
* SSH into your AT site and delete the option, just in case: `wp shell > delete_user_option('your-wpcom-simple-user-id', 'remove_duplicate_views_experiment_assignment_160125', true);`
* Go to an Atomic site with Calypso - like /home/your-site. It's important to be the first request (and not a WP-Admin one) because you're testing if the site gets treatment from the API request
* Notice that the admin menu is pointing to WP-Admin
* Go to an another Atomic site
* Go directly to a WP-Admin screen 
* Make sure you get treatment
* Open the debug panel and notice that we don't make an API request on each page load to explat

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 1]
```diff
@@ -409,6 +409,11 @@ function wpcom_is_duplicate_views_experiment_enabled() {
 
 	$variation = get_user_option( RDV_EXPERIMENT_FORCE_ASSIGN_OPTION, get_current_user_id() );
 
+	/**
+	 * We cache it for both AT and Simple because we want to give a12s to be able to switch between variations for their accounts - this can be useful during support.
```
Comment (mmtr) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:413]: Can we use ExPlat to switch between variations? Or will we be forced to use the escape hatch (p7DVsv-m73-p2)?

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 2]
```diff
@@ -417,9 +422,31 @@ function wpcom_is_duplicate_views_experiment_enabled() {
 	if ( ( new Host() )->is_wpcom_simple() ) {
 		\ExPlat\assign_current_user( $aa_test_name );
 		$is_enabled = 'treatment' === \ExPlat\assign_current_user( $experiment_name );
+
+		if ( is_automattician() ) {
```
Comment (mmtr) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:426]: Do we need to exclude support sessions from here? I honestly don't know if `is_automattician()` returns true for a12s doing support sessions.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 3]
```diff
@@ -417,9 +422,31 @@ function wpcom_is_duplicate_views_experiment_enabled() {
...
+			$is_enabled = true;
+			update_user_option( get_current_user_id(), RDV_EXPERIMENT_FORCE_ASSIGN_OPTION, 'treatment', true );
+		}
+
 		return $is_enabled;
 	}
 
+	$is_proxy_atomic    = defined( 'AT_PROXIED_REQUEST' ) && AT_PROXIED_REQUEST;
+	$is_support_session = WPCOMSH_Support_Session_Detect::is_probably_support_session();
```
Comment (mmtr) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:435]: To fix the Phan error you can do what I did in my previous exploration: https://github.com/Automattic/jetpack/pull/41157/files#diff-83c797b36007d4bbc95f7a8da5f7a750e9fe16930f8a3b7752da09d52899c4b2

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 4]
```diff
@@ -417,9 +422,31 @@ function wpcom_is_duplicate_views_experiment_enabled() {
...
+
+	/**
+	 * This handles two contexts: Calypso and WP-Admin.
+	 *
+	 * Calypso: WPCOM admin-menu API endpoint mapper sends a "admin_menu_is_a11n" param for a12s. If the param exists, then we'll switch to treatment.
```
Comment (mmtr) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:441]: Is this true? I couldn't find any reference to `admin_menu_is_a11n` in OpenGrok.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php (hunk 1 above)
Comment (mmtr) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:413]: Never mind. Just realized that we cannot rely on ExPlat because we're enforcing `treatment`, so the escape hatch is the only alternative.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 5]
```diff
@@ -417,9 +422,31 @@ function wpcom_is_duplicate_views_experiment_enabled() {
...
+	 * WP-Admin: We check if the user is proxied and if it's not in a support session.
+	 */
+	if ( isset( $_GET['admin_menu_is_a11n'] ) || ( $is_proxy_atomic && ! $is_support_session ) ) {
```
Comment (mmtr) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php]: Might be safer to also check if this is a request to the `admin-menu` endpoint. See https://github.com/Automattic/jetpack/blob/8200544475aa5e8365b9ebb5894b8919ff3d6fd4/projects/plugins/wpcomsh/feature-plugins/masterbar.php#L16-L19

**Review by mmtr — COMMENTED** [review]
This is looking good! It tests well for me except for the admin-menu on Atomic sites, but I think I'm missing a counterpart change in `wpcom`.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php (hunk 2 above)
Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:426]: Yep, it should work. is_automattician just gets the current user and searches it in an array of usernames. In a support session the username is the the impersonated one.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php (hunk 5 above)
Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php]: Sure!

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php (hunk 3 above)
Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:435]: Done! Thanks!

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php (hunk 4 above)
Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:441]: The param will be added in a new WPCOM PR. I didn't had time to open it last night :D

**Comment by BogdanUngureanu** [comment]
@mmtr I've updated the description of the PR mentioned the WPCOM PR needed for the `admin_menu_is_a11n` query parameter.

**Review by mmtr — COMMENTED** [review]
Tests well!

**Review by mmtr — APPROVED** [review]

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 6]
```diff
@@ -417,9 +422,33 @@ function wpcom_is_duplicate_views_experiment_enabled() {
 	if ( ( new Host() )->is_wpcom_simple() ) {
 		\ExPlat\assign_current_user( $aa_test_name );
 		$is_enabled = 'treatment' === \ExPlat\assign_current_user( $experiment_name );
+
+		if ( is_automattician() ) {
+			$is_enabled = true;
+			update_user_option( get_current_user_id(), RDV_EXPERIMENT_FORCE_ASSIGN_OPTION, 'treatment', true );
```
Comment (necronet) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:428]: Just note that the limitationhere is that it will only work with A/B experiments. If you're experiment will have different naming for `treatment` this will fail.

Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php:428]: @necronet that's fine. We only have one experiment with one treatment called "treatment". :)

**Review by necronet — APPROVED** [review]
LGTM minor a comment about the default use of `treatment` will only works with the default A/B experiment settings and not with those that have different naming for their `treatment`
