### PR TITLE
Boost: add Speculation Rules module

### LINKED ISSUE #41909: Boost: Create a Speculation Rules module for the settings page
The module will simply have an explanation of what it does and a toggle.

The exception textarea meta module will be done later.

ref: https://github.com/Automattic/jetpack/pull/37579
ref: pc9hqz-3ny-p2

### PR DESCRIPTION
**Pull request by donnchawp**
This PR adds a Speculation Rules module to the settings page. It's almost the same code as in https://github.com/Automattic/jetpack/pull/37579 by @haqadn but that PR was closed. To simplify, I'll make that PR into two.
I added a link to the MDN web docs for the rules.
I added PHP tests too.

Fixes https://github.com/Automattic/jetpack/issues/41909

## Proposed changes:

* Add a new Module to app/assets/src/js/pages/index/index.tsx
* Register it in app/modules/Modules_Index.php
* Create a class in app/modules/optimizations/speculation-rules/Speculation_Rules.php to set things up.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pc9hqz-3ny-p2

## Testing instructions:

* Apply PR
* Run `jetpack build plugins/boost` to build the UI.
* Define the constant JETPACK_BOOST_ALPHA_FEATURES and set it to true in an mu-plugin or wp-config.php
* Make sure there's a Speculation Rules module that can be toggled on and off.
* Run `composer phpunit` to run the PHP tests.

### CODE REVIEW

**Comment by donnchawp** [comment]
I restored the branch and reopened https://github.com/Automattic/jetpack/pull/37579 so I'll work from there.

**Comment by donnchawp** [comment]
Too many checks are failing in the other one, there's a request to merge or rebase, and I merged already, so I'll close it again. Development happens here..

File: projects/plugins/boost/app/assets/src/js/features/speculation-rules/speculation-method.tsx [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+import { z } from 'zod';
+import ModuleSubsection from '$features/ui/module-subsection/module-subsection';
+import { recordBoostEvent } from '$lib/utils/analytics';
+import { useMutationNotice } from '$features/ui/mutation-notice/mutation-notice';
+import styles from './speculation-method.module.scss';
+import { createInterpolateElement } from '@wordpress/element';
+import { getRedirectUrl } from '@automattic/jetpack-components';
+
+const unsafeSpeculationRulesLink =
+	getRedirectUrl( 'jetpack-boost-speculation-rules' ) + '#unsafe_speculative_loading_conditions';
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/speculation-rules/speculation-method.tsx]: We can provide hash URLs as redirects. This will allow us to control the redirect URL even when the hash anchor updates.

```suggestion
	getRedirectUrl( 'jetpack-boost-unsafe-speculation-rules' );
```

File: projects/plugins/boost/app/modules/optimizations/speculation-rules/Speculation_Rules.php [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+		$script = '<script type="speculationrules">
+		{
+			"' . esc_js( $fetch_method ) . '": [
+				{
+					"source": "document",
+					"where": {
+						"href_matches": "/*"
+					}
+				}
+			]
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/speculation-rules/Speculation_Rules.php:50]: I am guessing this is here mostly as a placeholder and we will flesh it out in a follow up PR?

Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/speculation-rules/Speculation_Rules.php:50]: Yeah, it's a placeholder. Next PR will add all the exclude bits.

File: projects/plugins/boost/app/assets/src/js/features/speculation-rules/speculation-method.tsx (hunk 1 above)
Comment (donnchawp) [reply projects/plugins/boost/app/assets/src/js/features/speculation-rules/speculation-method.tsx]: Thanks for making the redirect!

**Review by haqadn — APPROVED** [review]
LGTM!
