### PR TITLE
Forms: Add endpoint to check Akismet status

### LINKED ISSUE #42729: Forms: Akismet key not detected when activated
### Impacted plugin

Jetpack

### Quick summary

In the form block sidebar, we have a panel to check Akismet status (installed, active, has valid key). We prompt users through each state. 

If you have Akismet active with a key, deactivate it, then go to block panel, the form block will correctly prompt you to activate the plugin, but once activated, will not detect the key. That's because we do not check key status dynamically. We check the key status in PHP, and pass via a global variable to the editor, so there is no way to check or updated it dynamically. 

### Steps to reproduce

1. Activate Akismet and connect it with a valid key
2. Then deactivate the plugin from the plugins page
3. Add a page with a form block
4. In the form block sidebar, go to the Akismet panel. You'll see a button to activate Aksimet. Click that. 
5. When done, you'll see a prompt to add an Akismet key even though you already have one.

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

You can refresh the block editor page to get the correct Akismet status.

### Platform (Simple and/or Atomic)

Self-hosted

### PR DESCRIPTION
**Pull request by edanzer**
Fixes #42729

## Proposed changes:

**Issue:** In the form block sidebar, we prompt users to install, activate, and add a key for Akismet. If a key is already present when Akismet is activated, we fail to detect that and still prompt the user to add a key. That's because we do not check key status dynamically. We check the key status in PHP, and pass via a global variable to the editor, so there is no way to check or updated it dynamically.

**Broader relevance for third party integrations:** 
- We are starting work on a third party integrations modal for forms. This modal will need to be able to fetch up-to-date state for Akismet, Jetpack CRM, Google, Zapier, etc. This issue with Akismet is just one example of broader needs. So I'm trying to think how to solve this not just for Akismet but for all integrations. 
- I'm updating the AkismetPanel and PluginIntegrationPanel. While we'll be removing these components when we move integrations to the modal, we'll need most of the same logic. So we should be able to re-use the same logic. 
- Right now, we fetching plugin status via useSelect with const installedPlugins = select( coreStore ).getPlugins(). This works. But as the Akismet example shows, that check doesn't give us all the status we want, and I think as we move toward many integrations, we should consolidate everything on a single endpoint. I'll plan to replace the select( coreStore ).getPlugins() calls with this endpoint as we build out the modal and consolidate logic for integrations.

**Changes**
- Adds an 'integration-status' endpoint that takes as slug like 'akismet', 'jetpack-crm', 'google'. Right now, the endpoint really just handles the 'akismet' case. I added logic for generic plugins, which we can use for Jetpack CRM, Creative Mail, and others. I plan to update those in subsequent PR. We can then later update the endpoint for other integraitons.
- Adds a method to the AkismetPanel to fetch status from this endpoint and calls this method when Akismet is activated.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No. It does check for the status of another plugin (Akismet), but we were already doing that via other mean.s 

## Testing instructions:

* Install Akismet and add a valid key
* Deactivate Akismet from the plugin dashboard
* Create a page and add a form block
* Go to the block sidebar and Spam Protection tab. Click the button to activate Akismet.
* Confirm that the plugin activates, but also that it detects your active key. It should not prompt you to add a key, and you should just see buttons to view spam or stats if successful. 

akismet-status

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php [hunk 1]
```diff
@@ -496,4 +512,91 @@ public function get_file( $request ) {
...
+				/* translators: %s: plugin slug */
+				'error'       => sprintf( __( 'Unknown plugin: %s', 'jetpack-forms' ), $plugin_slug ),
+			);
+		}
+
+		$installed_plugins = get_plugins();
+		$is_installed      = isset( $installed_plugins[ $plugin_file ] );
+		$is_active         = is_plugin_active( $plugin_file );
+
+		return array(
```
Comment (lezama) [inline projects/packages/forms/src/contact-form/class-contact-form-endpoint.php]: noticed that for `get_akismet_status` you use `rest_ensure_response` while here you don't

File: projects/packages/forms/src/blocks/contact-form/components/jetpack-akismet-panel.js [hunk 2]
```diff
@@ -1,13 +1,42 @@
...
+		window?.jpFormsBlocks?.defaults?.akismetActiveWithKey || false
+	);
+	const [ akismetUrl, setAkismetUrl ] = useState(
+		window?.jpFormsBlocks?.defaults?.akismetUrl || ''
+	);
+
+	const checkAkismetStatus = useCallback( async () => {
+		try {
+			const response = await apiFetch( {
+				path: '/wp/v2/feedback/integration-status?slug=akismet',
```
Comment (lezama) [inline projects/packages/forms/src/blocks/contact-form/components/jetpack-akismet-panel.js]: wondering if `integrations/{slug}/status` wouldn't be cleaner?

Comment (lezama) [reply projects/packages/forms/src/blocks/contact-form/components/jetpack-akismet-panel.js]: in case we need specific integration endpoints in the future

Comment (edanzer) [reply projects/packages/forms/src/blocks/contact-form/components/jetpack-akismet-panel.js]: Yup, like that better. Will update.

Comment (edanzer) [reply projects/packages/forms/src/blocks/contact-form/components/jetpack-akismet-panel.js]: Done.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php (hunk 1 above)
Comment (edanzer) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php]: Added!

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php [hunk 3]
```diff
@@ -34,6 +34,26 @@ public function register_routes() {
...
+			$this->rest_base . '/integration-status/(?P<slug>[\w-]+)',
+			array(
+				'methods'             => \WP_REST_Server::READABLE,
+				'callback'            => array( $this, 'get_integration_status' ),
+				'permission_callback' => array( $this, 'get_items_permissions_check' ),
+				'args'                => array(
+					'slug' => array(
+						'type'              => 'string',
+						'required'          => true,
+						'sanitize_callback' => 'sanitize_text_field',
```
Comment (enejb) [inline projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:48]: This should check for the supported slugs and return any included ones.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php [hunk 4]
```diff
@@ -34,6 +34,26 @@ public function register_routes() {
...
+						'validate_callback' => function ( $param ) {
+							return preg_match( '/^[\w-]+$/', $param );
```
Comment (enejb) [inline projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:50]: What does this do? Lets leave a comment here.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php [hunk 5]
```diff
@@ -496,4 +516,93 @@ public function get_file( $request ) {
...
 		);
 	}
+
+	/**
+	 * Get the status of a forms integration.
+	 *
+	 * @param WP_REST_Request $request The request object.
+	 * @return WP_REST_Response|WP_Error Response object on success, or WP_Error object on failure.
+	 */
+	public function get_integration_status( WP_REST_Request $request ) {
```
Comment (enejb) [inline projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:526]: Instead of having a call for each integration. would it make sense to have one that returns the status for all integration? This would reduce he number of  backend calls.

Comment (edanzer) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:526]: I think we should have both. But you're right for something like the modal, the initial check should probably be for all integrations at once since we'll need them all. I'd also prefer to use react query if possible to cache the data response, so that if you close and open the modal, we don't send an extra, unneeded response.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php (hunk 4 above)
Comment (edanzer) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:50]: This pre-validates that the slug contains only letters, numbers, underscores, and hyphens; has at least one character; does no contain spaces or any other special characters.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php (hunk 3 above)
Comment (edanzer) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:48]: We do check for matching slugs in the callback. Does we think we also need a check here?
