### PR TITLE
Fix double-quotes handling in subscription button

### LINKED ISSUE #63196: Subscribe block: Custom button text is not visible after a double-quote
### Quick summary

Double-quotes don't play well with the custom text, it will hide some or show `Subscribe`.

### Steps to reproduce

1. Add a Subscribe block
2. Edit the text button that include one or a few double-quotes

### What you expected to happen

To have the text from the editor show in the live preview.

Editor view:
image1

### What actually happened

Issues:

* If there are the text starts with a double-quotes or the text has 2 double-quotes, then the text defaults back to `Subscribe`
* If there's a quote in the middle of the text, what's after will be not show

image1

### Context

5180721-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

Use single-quotes.

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/wp-calypso/issues/63196

#### Changes proposed in this Pull Request:

* it adds HTML encoding for double-quote characters used in Subscribe block's submit button

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

##### Test the fix

1. Open a New Post editor
2. Add Subscribe block
4. Use one or more double-quotes in the button
6. Save the post
7. Open post in the frontend

All double-quotes should be displayed.

Editor view:

Screen Shot 2022-06-16 at 08 43 39

Frontend:

Screen Shot 2022-06-16 at 08 43 32

##### Regression test

We should ensure that posts that were created before the fix can still be edited, and that re-saving such post fixes double-quotes. For that, before the fix is applied, prepare a post that includes Subscribe block, with a button that contains double-quotes.  Then:

1. Edit a Post that includes such a Subscribe block
2. Confirm that block is not broken and there is no prompt for recovery
3. Make any change to the post (add another block, or add a tag), save
4. Confirm that double quotes are displayed in frontend now

### CODE REVIEW

**Comment by wojtekn** [comment]
When I worked on the fix, I checked deprecation logic (https://developer.wordpress.org/block-editor/reference-guides/block-api/block-deprecation/), and I found out that the validator doesn't catch this as a change in the block. Thus I think there is a point in using the deprecation method. If it still needs to be used, I would appreciate the feedback.

**Review by danielbachhuber — DISMISSED** [review]
👍  Works well for me!

A couple of pieces to note:
1. In order for the Subscribe block to appear, Jetpack needs to be connected to WordPress.com. In my local environment, this required setting up a ngrok tunnel.
2. Because the `submitButtonText` is already properly encoded in the block's JSON attributes, no block warning appears with this change. The change solely impacts how the value is encoded in the shortcode attributes generated in the `save()` function.

image

An even more comprehensive fix would be to replace double quotes when the shortcode attributes are generated: https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/blocks/subscriptions/save.js#L137

Shortcake did this way back in the day: https://github.com/wp-shortcake/shortcake/blob/9748053a188e513d2b53126c01f1a0c7cd835a8c/js/build/shortcode-ui.js#L318

However, for the purposes of this issue, it's probably an over-optimization. I'm happy with this pull request as it is.

**Comment by anomiex** [comment]
> An even more comprehensive fix would be to replace double quotes when the shortcode attributes are generated:
> 
> https://github.com/Automattic/jetpack/blob/a99e0ccac5aeb9092b5c01d75af6846386182738/projects/plugins/jetpack/extensions/blocks/subscriptions/save.js#L137
> 
> Shortcake did this way back in the day: https://github.com/wp-shortcake/shortcake/blob/9748053a188e513d2b53126c01f1a0c7cd835a8c/js/build/shortcode-ui.js#L318
> 
> However, for the purposes of this issue, it's probably an over-optimization.

I was about to suggest the same change. I don't think it's an over-optimization, IMO it's less surprising for everyone reading the code to do the escaping at the place where the escaping is needed rather than doing it somewhere upstream.

Doing it there will also fix the similar problem that applies to the success message field. And would also affect the placeholder field, except I don't see an ability to edit the placeholder.

P.S. The code in the shortcake link doesn't seem too useful. I'd probably do something like this instead.
```javascript
/**
 * Apply HTML encoding to characters that are special inside shortcode attribute values.
 *
 * Shortcode attribute values may not contain brackets, angle brackets (unless valid HTML), or quotes.
 * Also non-breaking space and zero-width space will be mangled, and ampersand might otherwise be
 * interpreted as part of an entity.
 *
 * @see https://codex.wordpress.org/Shortcode_API#Attributes
 * @param {string} value - Value to encode.
 * @returns {string} Encoded value.
 */
function encodeValueForShortcodeAttribute( value ) {
	const entities = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }; 
	return value.replace( /[\[\]"'&<>\u00a0\u200b]/g, m => specials[m] || `&#${ m.codePointAt( 0 ) };` );
}
```
The `specials` bit isn't strictly necessary, but will probably be more readable if a human looks at the shortcode. Or you could put the other 5 characters into `specials` too (and rename it `entities` or something) and skip the `` || `&#${ m.codePointAt( 0 ) };` `` bit.

**Comment by danielbachhuber** [comment]
> P.S. The code in the shortcake link doesn't seem too useful. I'd probably do something like this instead.

Oh, that is a much better example than the Shortcake link 😄 Thanks for sharing it!

**Comment by wojtekn** [comment]
@danielbachhuber @anomiex, thank you for the feedback. I've extracted the code to the separate function and moved it to a place closer to the part that returns the value. Then I've added support for escaping for more characters. 

Screen Shot 2022-06-20 at 13 06 01

File: projects/plugins/jetpack/extensions/blocks/subscriptions/save.js [hunk 1]
```diff
@@ -128,13 +128,31 @@ export default function Save( { className, attributes } ) {
...
+	 * @see https://codex.wordpress.org/Shortcode_API#Attributes
+	 * @param {string} value - Value to encode.
+	 * @returns {string} Encoded value.
+	 */
+	const encodeValueForShortcodeAttribute = value => {
+		return value
+			.replace( /</g, '&lt;' )
+			.replace( />/g, '&gt;' )
+			.replace( /"/g, '&quot;' )
+			.replace( /'/g, '&#039;' );
```
Comment (anomiex) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/save.js]: It breaks in some cases unless we also include `[` and `]`.
```suggestion
			.replace( /'/g, '&#039;' )
			.replace( /\[/g, '&#091;' )
			.replace( /\]/g, '&#093;' );
```
And as mentioned earlier, we may want to include NBSP and ZWSP to avoid them being mangled.
```suggestion
			.replace( /'/g, '&#039;' )
			.replace( /\[/g, '&#091;' )
			.replace( /\]/g, '&#093;' )
			.replace( /\u00a0/g, '&nbsp;' )
			.replace( /\u200b/g, '&#x200b;' );
```
Looks like whether `&` should be encoded or not is tricky, as the value passed in for `submitButtonText` already has ampersands (and `<`) escaped while the value for `successMessage` does not. Hooray for consistency? I guess we should leave it out.

Comment (wojtekn) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/save.js]: @anomiex, thanks for finding those missing cases. I've added square brackets, nbsp, and zwsp to the chain. It looks like the square brackets were the biggest offender here, breaking the post entirely.

**Review by anomiex — DISMISSED** [review]

**Review by zaguiini — APPROVED** [review]

File: projects/plugins/jetpack/extensions/blocks/subscriptions/save.js [hunk 2]
```diff
@@ -128,13 +128,35 @@ export default function Save( { className, attributes } ) {
...
 	};
 
+	/**
+	 * Apply HTML encoding for special characters inside shortcode attributes.
+	 *
+	 * @see https://codex.wordpress.org/Shortcode_API#Attributes
+	 * @param {string} value - Value to encode.
+	 * @returns {string} Encoded value.
+	 */
+	const encodeValueForShortcodeAttribute = value => {
```
Comment (zaguiini) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/save.js]: I think we can extract this function to some kind of utility file because here it's going to get redefined on every render, and that's kind of useless.

If you don't feel like putting it in a separate file, moving out of the scope of the component should be enough.

**Review by zaguiini — DISMISSED** [review]
Looking good. Left a minor, non-blocking comment.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/save.js (hunk 2 above)
Comment (wojtekn) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/save.js]: Good idea, thanks. I've extracted the function to the `utils` file, which is a practice followed by other blocks.

**Review by kraftbj — APPROVED** [review]

**Comment by wojtekn** [comment]
It's r247994-wpcom
