### PR TITLE
Instant Search: User-friendly error messaging

### LINKED ISSUE #25380: Instant Search: Better error messaging
### Impacted plugin

Jetpack, Search

### What

Make Instant Search show proper error messages

### How

For now, when search API fails, Instant Search would show error message like the following regardless what exactly the error is:

image

Which I would say is almost 100% percent wrong, and there are multiple known causes, for example API glitches (higher than usual error rate as of the beginning of August 2022), purchase expired, malformed queries, unsupported filters, private blog etc. 

https://github.com/Automattic/jetpack/blob/45613b870f42538dd572bcd489e7edf6c1093d64/projects/packages/search/src/instant-search/components/search-results.jsx#L139

@gibrown reported few a couple of years back:

- https://github.com/Automattic/jetpack/issues/13639
- https://github.com/Automattic/jetpack/issues/13366

@ebinnion reported when he migrated a site from self hosted to Atomic which had a subscription before but not anymore. And it shows the error above too, where actually we should show user some error like: the site has no search subscription and need to contact administrator.

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #25380

#### Changes proposed in this Pull Request:
The PR replaces the old `It looks like you're offline. Please reconnect for results.` message with more accurate and user-friendly error messages. The PR is meant to work with `D85612-code`☑️, but could be tested and merged separately. <strike>Error codes that have messages mapped are as following.</strike> All errors are all shown user friendly and with error code returned from API for us to better diagnose issues.

- bad_request - 400
- payload_too_large - 413
- service_unavailable - 503 - basically when ES returns us error
- unauthorized - 403 - user doesn't have access
- not_supported - 403 - site needs search plan
-  unknown_blog - 404

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Open a website with Jetpack Search subscription and Instant Search enabled
* Sandbox `public-api.wordpress.com`
* Add `return new WP_Error( 'unauthorized', 'Yep the request is naughty', 400 );` as the first line of function `callback` in `public.api/rest/wpcom-json-endpoints/class.wpcom-json-api-search-site-v1-3-endpoint.php`
* Perform a search
* Ensure proper errors are displayed

For example if you change the error code to `not_supported`, the following error would be displayed:

image

### CODE REVIEW

File: projects/packages/search/src/instant-search/lib/errors.js [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+export function getErrorMessage( error ) {
+	switch ( error?.message ) {
+		case 'service_unavailable':
+			return __(
+				'Jetpack Search is currently unavailable. Please try again later.',
+				'jetpack-search-pkg'
+			);
+		case 'unknown_blog':
+		case 'unauthorized':
+			return __( 'You are not authorized to perform search on the website.', 'jetpack-search-pkg' );
```
Comment (dognose24) [inline projects/packages/search/src/instant-search/lib/errors.js]:
```suggestion
			return __( 'You are not authorized to perform a search on the website.', 'jetpack-search-pkg' );
```
Grammarly says there should be an `a`. 😄

Comment (kangzj) [reply projects/packages/search/src/instant-search/lib/errors.js]: @dognose24 it's funny that the error message was suggested by copilot 😂 Why you bots fight one another, you should be like brothers 🥹

Changed the wording to 'You are not authorized to search on the website.'.

File: projects/packages/search/src/instant-search/lib/errors.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+export function getErrorMessage( error ) {
+	switch ( error?.message ) {
+		case 'service_unavailable':
+			return __(
+				'Jetpack Search is currently unavailable. Please try again later.',
+				'jetpack-search-pkg'
+			);
+		case 'unknown_blog':
+		case 'unauthorized':
+			return __( 'You are not authorized to search on the website.', 'jetpack-search-pkg' );
```
Comment (a8ck3n) [inline projects/packages/search/src/instant-search/lib/errors.js]: I'm not sure about this one. Is this something the end user would see in the overlay? If so, it seems a bit nonsensical from an end users point of view. Mostly, as a visitor to the site, I don't expect to need special permissions to run a search.

I'd probably hide the underlying reason for the error and say something like:

"Jetpack Search has encountered an error. Please contact the site administrator if the issue persists."

Comment (a8ck3n) [reply projects/packages/search/src/instant-search/lib/errors.js]: To be honest, I think I'd only return two messages at the user-facing level. Those would be:

1. service_unavailable — Jetpack Search is currently unavailable. Please try again later.
2. default — Jetpack Search has encountered an error. Please contact the site administrator if the issue persists.

In my opinion, the other errors are surfacing a bit too much of the "sausage making" and would only be appropriate inside `/wp-admin` where the site admins could use the extra detail when dealing with them.

If we were to stick with these, I'd update them to the following:

1. service_unavailable — no change
2. unauthorized — Jetpack Search does not have the proper permissions to search this site. Please contact the site administrator if the issue persists.
3. bad_request — Jetpack Search was unable to process your request. Please contact the site administrator if the issue persists.
4. payload_too_large — same as bad_request
5. not_supported — Jetpack Search has encountered a configuration error. Please contact the site administrator if the issue persists.
6. default — An unknown error occurred. Please contact the site administrator if the issue persists.

From a user perspective, that's about as much info as I'd be interested in. As a site admin, it would be nice if these errors were logged or recorded and then surfaced inside **wp-admin** so I was alerted to any potential configuration issues.

Comment (kangzj) [reply projects/packages/search/src/instant-search/lib/errors.js]: Thanks heaps for the comments. They make a lot of sense. Change incoming 😄

File: projects/packages/search/src/instant-search/lib/errors.js [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+				error?.message
+			);
+
+		case 'offline':
+			return __(
+				"It looks like you're offline. Please reconnect to load the latest results.",
+				'jetpack-search-pkg'
+			);
+
+		case 'unknown_blog':
```
Comment (kangzj) [inline projects/packages/search/src/instant-search/lib/errors.js:27]: These `case`s here are more of documentation than code 😄

**Review by dognose24 — APPROVED** [review]
These error messages make sense to me!
