### PR TITLE
Carousel: Fixing comments issue with nonce checks

### LINKED ISSUE #23728: Tiled Gallery / Carousel: Comments not displaying under image in carousel
### Quick summary

Users are unable to see any comments added to images in their Tiled Gallery carousels. 

I've encountered this on the user's Twenty Eleven (Simple) theme, and on my test sites Blockbase (Atomic, Simple) and Hever (Simple). 

(I'm not aware of any workarounds so I'm selecting the high priority label in accordance with the priority graph. Please feel free to update if needed.)

### Steps to reproduce

1. Add a Tiled Gallery to a post and save
2. Visit the post and select a Tiled Gallery image to open the carousel
3. Select the comments icon to toggle the comments section and add a comment
4. Post comment (approve comment from dashboard if necessary)

### What you expected to happen

I expected the comment to show up as seen in this image taken from the [Jetpack Carousel guide page](https://jetpack.com/support/carousel/#carousel-options): 

image

### What actually happened

No comments show. Comments are available for viewing by accessing the Comments page in the dashboard, but not from within the Tiled Gallery Carousel.

### Context

I encountered this issue here: 4861753-zd-woothemes

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes #23728

#### Changes proposed in this Pull Request:

* PR #22770 introduced a nonce check which caused issues for comments in carousels. This PR fixes that by removing the nonce check.

#### Jetpack product discussion

p1648736983705859-slack-C01U2KGS2PQ

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* There are some great [testing instructions here](https://github.com/Automattic/jetpack/issues/23728#issuecomment-1084661729) - however the network tab response should now not show a failure message under 'Preview', and comments should show under the images in the carousel.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by coder-karen** [comment]
r242905-wpcom

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-10.8` in f1542882c8fa7608d2062148973656db87e171f7

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.php [hunk 1]
```diff
@@ -930,12 +930,10 @@ public function get_attachment_comments() {
 		 */
 		do_action( 'jp_carousel_check_blog_user_privileges' );
 
+		// phpcs:disable WordPress.Security.NonceVerification.Recommended -- we do not need to verify the nonce for this public request for publicly accessible data (as checked below).
```
Comment (kraftbj) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.php:933]: Great detail. This will save someone in the future.

Comment (coder-karen) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.php:933]: Absolutely. Thanks @jeherve for adding that in the review suggestion!
