### PR TITLE
Sync Health Tests: make messages easier to translate

### LINKED ISSUE #15379: Sync Health UI: Fix translations
Follow-up to #15199.

Marking for 8.4.2 since the translations are pretty hard to handle as they are.

#### Steps to reproduce the issue

Copying from 15199:

please don't write translatable strings like in https://github.com/Automattic/jetpack/pull/15199/files#diff-43ad69f84dbe6807242fdda0ebda84ffR563L:
```
'<p>%1$s</p><p><span class="dashicons fail"><span class="screen-reader-text">%2$s</span></span> %3$s<strong> %4$s <a id="full_sync_request_link" href="#">%5$s</a> %6$s</strong></p>',
__( 'The information synced by Jetpack ensures that Jetpack Search, Related Posts and other features are aligned with your site’s current content.', 'jetpack' ),
__( 'Error', 'jetpack' ),
__( 'Jetpack has detected an error while syncing your site', 'jetpack' ), /* translators: screen reader text indicating a test failed */
__( 'We recommend', 'jetpack' ),
__( 'full sync', 'jetpack' ),
__( 'to align Jetpack with your site data.', 'jetpack' )
```
This is string concat at its worst :( Please remember that translators don't see segments in sequence and are unaware about the placeholder-filled string. This should not have been approved.

There is another one:
```
'<p>%1$s</p><p><span class="dashicons dashicons-clock" style="color: orange;"><span class="screen-reader-text">%2$s</span></span> %3$s <strong>%4$s %5$d %6$s</strong></p>',
__( 'The information synced by Jetpack ensures that Jetpack Search, Related Posts and other features are aligned with your site’s current content.', 'jetpack' ),
__( 'Clock', 'jetpack' ),
__( 'Jetpack has identified a delay while syncing individual content updates. Certain features might be slower than usual, but this is only temporary while sync catches up with recent changes to your site.', 'jetpack' ), /* translators: screen reader text indicating a test failed */
__( 'We’re seeing a current delay of', 'jetpack' ),
intval( $sync_queue->lag() / MINUTE_IN_SECONDS ),
__( 'minutes.', 'jetpack' )
```
Could you please improve this with a follow-up? Thanks!

#### What I expected
Translations should be a single string, using sprintf, etc if needed.

#### What happened instead
A lot of individual strings.

**Screenshots**

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #15379

#### Changes proposed in this Pull Request:

This should make messages in the Site Health screen easier to translate, as per the feedback in #15379.

I've also taken the opportunity to make the message with a number translatable differently depending on the number.

#### Testing instructions:

* Enable Jetpack and Sync Module
* Go to the SIte Health Admin Page `/wp-admin/site-health.php`
* Under Passed Tests you should not see any Jetpack Sync warnings in critical or recommended
* Update the Sync Health to Out of Sync  `Sync_Health::update_status( Sync_Health::STATUS_OUT_OF_SYNC )` dropped into the wp.config.php or the functions theme file or etc.
* Refresh the Site Health Admin Page
* Verify that under critical issues the Jetpack Sync info displays and aligns with the designs p6TEKc-3uv-p2

image

* Reset the Sync Health to In Sync `Sync_Health::update_status( Sync_Health::STATUS_IN_SYNC )`
* Point your Jetpack Connection to a bad address  `define( 'JETPACK__SANDBOX_DOMAIN', 'badbadbad23434.example.com' );`
* Update or Create a new Post.
* Verify sync health is not displayed in recommendations
* Wait 5-10 minutes.
* Refresh the Site Health Admin Page
* Verify that under recommended issues the Jetpack Sync delayed test displays and aligns with the designs p6TEKc-3uv-p2. Check that the X minutes updates as time goes on.

image

* Remove the Jetpack Connection sandbox
* refresh the admin a few times (clear the queue )
* Refresh the Site Health Admin Page
* Verify sync health is not displayed in recommendations

#### Proposed changelog entry for your changes:

* Site Health Tools: improve messaging to make translations easier.

### CODE REVIEW

File: _inc/lib/debugger/class-jetpack-cxn-tests.php [hunk 1]
```diff
@@ -548,8 +548,29 @@ protected function test__sync_health() {
...
+				$description  = '<p>';
+				$description .= esc_html__( 'The information synced by Jetpack ensures that Jetpack Search, Related Posts and other features are aligned with your site’s current content.', 'jetpack' );
+				$description .= '</p>';
+				$description .= '<p>';
+				$description .= sprintf(
+					'<span class="dashicons fail"><span class="screen-reader-text">%1$s</span></span> ',
+					esc_html__( 'Error', 'jetpack' )
+				);
+				$description .= wp_kses(
+					__( 'Jetpack has detected an error while syncing your site. <strong>We recommend <a id="full_sync_request_link" href="#">a full sync</a> to align Jetpack with your site data.</strong>', 'jetpack' ),
```
Comment (jeherve) [inline _inc/lib/debugger/class-jetpack-cxn-tests.php:564]: @mdbitz Is this link supposed to lead somewhere special?

Comment (mdbitz) [reply _inc/lib/debugger/class-jetpack-cxn-tests.php:564]: its utilized in a javascript handler, so no :)

**Review by mdbitz — DISMISSED** [review]
Nice use of wpkses and also _n for pluralization of minute(s)

Tested locally and screens display / function the same.

**Review by akirk — DISMISSED** [review]
So much better, thank you!

**Review by dereksmart — DISMISSED** [review]

**Review by bisko — APPROVED** [review]

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.4` in 5c31681a02792bf2982aa216ff941f039d9c4a7c
