### PR TITLE
Fix Date constructor RangeError exception on Firefox when running alongside Gutenberg 9.4.1

### LINKED ISSUE #17850: Jetpack blocks not being loaded/found on Gutenberg 9.4 on WPCOM/AT when using Firefox
#### Steps to reproduce the issue

**IMPORTANT:** The issue only happens on Firefox.

##### WPCOM

1. Create a new WPCOM test site;
2. Add the `gutenberg-edge` sticker to it in order for it to load GB `9.4.1`;
3. Start a new post and try to search for/nsert a JP block (Tiled Gallery and Contact Info come to mind). 

##### AT

1. Create a new WPCOM test site;
1. Upgrade to the business plan and install a plugin in order for it to become AT;
1. SFTP into it _(Get the SFTP info @ `https://wordpress.com/hosting-config/<site>`)_ and remove the `gutenberg` symlink in `/htdocs/wp-content/plugins`
1. Download Gutenberg `9.4.1` from [here](https://wordpress.org/plugins/gutenberg/) and upload it to your AT site;
3. Start a new post and try to search for/insert a JP block _(`Tiled Gallery` and `Contact Info` come to mind)_. 

It also happens on an org instance with GB 9.4 (I used `jurassic.ninja` to test) as long as FF is being used to access it.

#### What I expected

I expect all JP blocks to load (and function) correctly so I can find them in the inserter and am able to add them to the editor.

#### What happened instead

You can't find them in the inserter _(which I guess is related to the error shown in the screenshot below)_. That also means any post that uses one of these blocks will render a "block not supported" error.

**Screenshots**

|  Trying to find the "Contact Info" block | Console errors (same error on WPCOM/AT) |
| ------------- | ------------- |
| jp2 | jetpack_ |

#### Env

- `Firefox Quantum Developer Edition, 84.0b3`
- `Ubuntu Linux 18.04`

#### Context

Originally reported here: p1605902335056900-slack-CBG1CP4EN.

### PR DESCRIPTION
**Pull request by fullofcaffeine**
Fixes #17850

### Changes proposed in this Pull Request:

The 'year' and 'month' args were passed wrapped in a single array argument to the `Date` constructor. This overload fails on Firefox. 

This started happening after Gutenberg 9.4 migrated to `dateFns` from `moment`. We still don't know why it worked before, but I have a hunch that `moment` (or other package in its dependency tree) monkeypatched/polyfilled the Data object in order to allow it to accept an array (?).

### Does this pull request change what data or activity we track or use?

No

#### Reproducing the issue

Run a WP instance (com or org) with Jetpack and Gutenberg 9.4.1, start a new post and watch the console for the exception. You'll also noticed JP blocks haven't loaded.

#### Testing the fix works

1. Apply this patch to your Jetpack instance;
1. Start a new post, be sure to have the JS console open and look for errors. A "RangeError" should not happen;
1. JP blocks should be present, test by searching for them in the inserter.

#### Proposed changelog entry for your changes:

* Fix Date constructor RangeError exception on Firefox when running alongside Gutenberg 9.4.1.

### CODE REVIEW

File: extensions/shared/external-media/constants.js [hunk 1]
```diff
@@ -176,7 +176,7 @@ export const MONTH_SELECT_OPTIONS = [
 	{ label: __( 'Any Month', 'jetpack' ), value: -1 },
 	...map( range( 0, 12 ), value => ( {
 		// Following call generates a new date object for the particular month and gets its name.
-		label: dateI18n( 'F', new Date( [ 0, value + 1 ] ) ),
+		label: dateI18n( 'F', new Date( 0, value + 1 ) ),
```
Comment (anomiex) [inline extensions/shared/external-media/constants.js:179]: It seems that, at least in Chrome, `new Date( [ year, month ] )` takes a 1-based month. The standard `new Date( year, month )`, on the other hand, takes a 0-based month. So the `+ 1` here winds up labeling the months incorrectly in the generated dropdown.
```suggestion
		label: dateI18n( 'F', new Date( 0, value ) ),
```

**Review by anomiex — CHANGES_REQUESTED** [review]
The generated dropdown can be viewed by

* Add an Image block
* Click "Select Image", then "Google Photos" in the popup menu.
* Change the "Filter by time period" to "Specific Month/Year". The dropdown generated here is then used for selecting the specific month.

File: extensions/shared/external-media/constants.js (hunk 1 above)
Comment (ockham) [reply extensions/shared/external-media/constants.js:179]: Yep, indeed:

image

Comment (ockham) [reply extensions/shared/external-media/constants.js]: Thanks @anomiex! Applied in dd5b632.

**Review by anomiex — APPROVED** [review]
Looks good now.

Keep in mind that code freeze for 9.2 is today, and today is about over, so please merge ASAP ;)

**Comment by ockham** [comment]
> Looks good now.

Thanks for reviewing/approving!

> Keep in mind that code freeze for 9.2 is today, and today is about over, so please merge ASAP ;)

Merging is still blocked by Travis which is still running it seems :sweat_smile:

**Comment by ockham** [comment]
@anomiex or @fullofcaffeine -- I'll be signing off soon, could either of you merge this once it goes green please? :pray:

**Review by kraftbj — DISMISSED** [review]

**Review by kraftbj — DISMISSED** [review]

**Review by kraftbj — APPROVED** [review]

**Comment by ockham** [comment]
Seems like this got merged with a 1-based month value after all :confused: 

https://github.com/Automattic/jetpack/blob/2e0d21b7878f61dd66af66fbf737b531dcda50c3/extensions/shared/external-media/constants.js#L179

-- see [this discussion](https://github.com/Automattic/jetpack/pull/17876#discussion_r528983884).

Looks like we'll need another PR to fix that. I'll file one.

**Comment by jeherve** [comment]
r217276-wpcom

**Comment by fullofcaffeine** [comment]
> (Maybe the result of a rebase? -- PSA: Use git push --force-with-lease rather than git push --force to avoid cases like these wink )

Yeah, we had to force-push in order to re-trigger Travis*, and I had missed the discussion about the Date constructor arg differences across browsers. Apologies. Thanks for pointing out `--force-with-lease`!

File: extensions/shared/external-media/constants.js (hunk 1 above)
Comment (fullofcaffeine) [reply extensions/shared/external-media/constants.js:179]: > It seems that, at least in Chromium, new Date( [ year, month ] ) takes a 1-based month. The standard new Date( year, month ), on the other hand, takes a 0-based month. So the + 1 here winds up labeling the months incorrectly in the generated dropdown.

TIL! Thanks for testing this out!
