### PR TITLE
Subscriptions: do not attempt to fetch or display elements from WordPress.com when user is not connected

### LINKED ISSUE #39911: Updating failed. Sorry, you are not allowed to edit the jetpack_post_was_ever_published custom field
### Impacted plugin

Jetpack

### Quick summary

From this thread: https://wordpress.org/support/topic/jetpack-error-when-user-with-author-role-submits-post-for-review/

I’ve spent all day looking for a fix and decided it’s time to finally ask here. I have a website that allows users with Author role to submit post for review, however, they’ve been seeing an error saying “Updating failed. Sorry, you are not allowed to edit the jetpack_post_was_ever_published custom field.” whenever they do so. I notice too that there’s this notification saying “Sorry, you are not allowed to do that” whenever the Newsletter component is clicked.

While the post is successfully submitted and appears in the Pending tab, it fails to register certain associated information such as Notes and an ACF custom field for an alternative headline. These remain blank while the taxonomies get saved just fine.

I temporarily implemented a workaround by adding a code snippet that deactivates Jetpack when the current user is an Author, Contributor, etc., which works, but it somehow causes the front-end to break when the same users view the site, so I’m thinking there must be a better fix for this issue. I have contacted my host to no avail.

Any input is appreciated.

### Steps to reproduce

I could replicate this on my site with the sorry you are not allowed to do this. The draft saved for me however I do not have custom fields which need to be saved like the ticket

Image

1. Create an Author level user
2. Enable the Newsletter module
3. Create a draft post 
4. Click on Publish
5. The toast error (bottom right) occurs
The same behaviour happens before and after the Author user connects their WP.com account. 

### A clear and concise description of what you expected to happen.

No errors should occur when saving a post.

### What actually happened

Error messages show up, 

Image

### Impact

One

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

The user can disable Jetpack for those roles, however this breaks the front end of the site

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #39911
Fixes CML-537

## Proposed changes:

This PR brings in changes that will impact the Newsletter features' display for non-connected users. **For users that are connected to WordPress.com already, there should be no change.**

- We no longer show Newsletter panels that require a connection when the user is not connected.
- We do not show the plan management toolbar item when the user is not connected.
- We do not attempt to make requests to WordPress.com when the user is not connected.

image
image

> [!NOTE]
> This is a replay of #40208 plus some added elements.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

> [!WARNING]
> This will need to be tested:
> - **On simple as well as on self-hosted or WoA**
> - **With both a connected admin and a non-connected user (can be admin or editor)**

* Start with a site that's connected to WordPress.com
* Create a new user.
* In another browser, access the site with that new user.
* **Run the next tests in both windows, when connected and when not connected**
* Open your browser's network tools, and watch for XHR requests made by Jetpack (filter by `wpcom`)
* Go to Posts > Add New
    * When not connected, you should not see any requests or error messages brought up by Jetpack
* Insert a Subscribe block
    * When connected, you should see a toolbar item to add or manage plans (see screenshot above).
    * When not connected, you should not see that button but the block should otherwise work as expected.
* Click on the Newsletter plugin icon in the top right bar
    * When not connected, you should only see an invitation to connect.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/menu.js [hunk 1]
```diff
@@ -47,12 +47,12 @@ const NewsletterMenu = ( { openPreviewModal } ) => {
 			className="jetpack-newsletter-settings-sidebar"
 		>
 			<PanelBody>
-				{ ! isPublished && <NewsletterEmailDocumentSettings /> }
-				<SubscribersAffirmation accessLevel={ accessLevel } prePublish={ ! isPublished } />
 				{ isSendEmailEnabled && ! isPublished && (
 					<>
 						{ ! shouldPromptForConnection ? (
 							<>
+								{ ! isPublished && <NewsletterEmailDocumentSettings /> }
```
Comment (allilevine) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/menu.js]: This is within the `isSendEmailEnabled` condition, which is causing the toggle to disappear when emails are toggled off:

Before | After
---- | ----
Screenshot 2025-06-03 at 1 45 24 PM | Screenshot 2025-06-03 at 1 29 08 PM

We could move the `isSendEmailEnabled` condition below it to wrap the preview and test email buttons.

**Review by allilevine — COMMENTED** [review]
Jetpack not connected:
- I needed to enable the newsletter module.
- I see fetch requests when I filter on wpcom, but not xhr requests.
- I see these console messages:
Screenshot 2025-06-03 at 1 27 11 PM

- I see the subscribe block without the add or manage plans button ✅ 
- I see the invitation to connect on the Newsletter panel ✅ 

Atomic not connected:
- I see an xhr request to `https://public-api.wordpress.com/rest/v1/sites/{site url}`
- Same console messages as Jetpack.
- Subscribe block and newsletter panel look good ✅ 

Simple worked correctly -- I don't think there's a way to add a not-connected user there.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/menu.js (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/menu.js]: Ah, that's a good catch! I just committed 279e29f6cfd2d32ca837124180093b6cadaa1607 to try to fix that.

**Comment by jeherve** [comment]
> I see these console messages:

Those are unfortunately known issues, unrelated to my changes.

**Review by allilevine — APPROVED** [review]
The fix is working for me and [my testing results](https://github.com/Automattic/jetpack/pull/43731#pullrequestreview-2893554457) match what's expected.

**Comment by mehmoodak** [comment]
> We do not show the plan management toolbar item when the user is not connected.

For my own info: Without plan management the subscribe and other related blocks are mostly useless, do we show any help text to give a brief explanation to the user?

**Comment by jeherve** [comment]
> For my own info: Without plan management the subscribe and other related blocks are mostly useless, do we show any help text to give a brief explanation to the user?

One can still subscribe to a site, and add a Subscribe block, even without a plan. That does in fact account for the majority of our users today.

Still, I agree we should point our customers to all the options available to them when possible.
We do that in the Newsletter dashboard like so:

Screenshot 2025-06-06 at 18 00 26

We also do it in the editor:

image

I think those are good starting points. In general, I would not expect secondary users, that did not connect Jetpack to WordPress.com in the first place, to be the ones configuring things like paid plans. With that in mind, I think that's okay that we don't nudge them a lot to connect to WordPress.com in the block editor.
