### PR TITLE
Sync Checksum - Enhance performance of postmeta range query

### LINKED ISSUE #19337: Sync: Uncaught Exception: Unable to get range edges
Over the last week, there have been 25 VIP customer applications that have had an "Uncaught Exception: Unable to get range edges" fatal error. The total is 188, but distributed across the week.

#### Steps to reproduce the issue

Not sure - but stack traces are below.

#### What I expected

No fatal error - range edges can be found.

#### What happened instead

Jetpack 9.4:

```
Uncaught Exception: Unable to get range edges in /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/replicastore/class-table-checksum.php:559
Stack trace:
#0 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(1362): Automattic\Jetpack\Sync\Replicastore\Table_Checksum->get_range_edges(NULL, NULL)
#1 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(1270): Automattic\Jetpack\Sync\Replicastore->calculate_buckets('postmeta', NULL, NULL)
#2 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(286): Automattic\Jetpack\Sync\Replicastore->checksum_histogram('postmeta', NULL, NULL, NULL)
#3 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-actions.php(863): Automattic\Jetpack\Sync\Replicastore->post_meta_checksum()
#4 /var/www/wp-content/mu-plugins/jetpack-9.4/json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php(70): Automattic\Jetpack\Sync\Actions::get_sync_status('started,send_st...')
#5 /var/www/wp-content/mu-plugins/jetpack-9.4/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php(30): Jetpack_JSON_API_Sync_Status_Endpoint->result()
#6 /var/www/wp-content/mu-plugins/jetpack-9.4/class.json-api.php(382): Jetpack_JSON_API_Endpoint->callback('/sites/15942265...', '159422659')
#7 /var/www/wp-content/mu-plugins/jetpack-9.4/class.json-api.php(366): WPCOM_JSON_API->process_request(Object(Jetpack_JSON_API_Sync_Status_Endpoint), Array)
#8 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php(929): WPCOM_JSON_API->serve(false)
#9 /var/www/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Server->json_api(Array)
#10 /var/www/wp-includes/IXR/class-IXR-server.php(206): IXR_Server->call('jetpack.jsonAPI', Array)
#11 /var/www/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#12 /var/www/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#13 /var/www/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#14 /var/www/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#15 /var/www/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#16 /var/www/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#17 {main}
```

Jetpack 9.5

```
Uncaught Exception: Unable to get range edges in /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/replicastore/class-table-checksum.php:591
Stack trace:
#0 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1362): Automattic\Jetpack\Sync\Replicastore\Table_Checksum->get_range_edges(NULL, NULL)
#1 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1270): Automattic\Jetpack\Sync\Replicastore->calculate_buckets('postmeta', NULL, NULL)
#2 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1173): Automattic\Jetpack\Sync\Replicastore->checksum_histogram('postmeta')
#3 /var/www/wp-content/mu-plugins/jetpack-9.5/json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php(79): Automattic\Jetpack\Sync\Replicastore->checksum_all()
#4 /var/www/wp-content/mu-plugins/jetpack-9.5/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php(30): Jetpack_JSON_API_Sync_Check_Endpoint->result()
#5 /var/www/wp-content/mu-plugins/jetpack-9.5/class.json-api.php(382): Jetpack_JSON_API_Endpoint->callback('/sites/18260523...', '182605232')
#6 /var/www/wp-content/mu-plugins/jetpack-9.5/class.json-api.php(366): WPCOM_JSON_API->process_request(Object(Jetpack_JSON_API_Sync_Check_Endpoint), Array)
#7 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php(929): WPCOM_JSON_API->serve(false)
#8 /var/www/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Server->json_api(Array)
#9 /var/www/wp-includes/IXR/class-IXR-server.php(211): IXR_Server->call('jetpack.jsonAPI', Array)
#10 /var/www/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#11 /var/www/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#12 /var/www/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#13 /var/www/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#14 /var/www/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#15 /var/www/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#16 {main}
```

### PR DESCRIPTION
**Pull request by mdbitz**
The way that checksums range queries function is that they use all the filters from the actual checksum. In the case of postmeta this is detrimental to performance of the where key for allowed white list leads to a long running query on larger sites. 

This update removes the filter for postmeta ranges. It means we will potentially include posts that don't have meta in the range but these won't be included in subsequent queries for the buckets.

Fixes #19337

#### Changes proposed in this Pull Request:
* Checksum query performance.

#### Does this pull request change what data or activity we track or use?
* NO

#### Testing instructions:

**DO NOT apply patch**
1 Enter wp shell. `yarn docker:wp shell --url=DOMAIN`
2 `$rs = new Automattic\Jetpack\Sync\Replicastore();`
3 `$rs->checksum_histogram( 'postmeta' );`
4 Record the checksum results
5 Exit wp shell
6 Apply Patch
7 Enter wp shell
8 `$rs = new Automattic\Jetpack\Sync\Replicastore();`
9 `$rs->checksum_histogram( 'postmeta' );`
10 Verify the checksum matches the prepatch value

### CODE REVIEW

**Comment by mdbitz** [comment]
POST PATCH -> [
     "2-393" => "1103226038073",
   ]
   
 PRE PATCH -> [
     "2-393" => "1103226038073",
   ]
   
   MATCH :)

File: projects/packages/sync/src/replicastore/class-table-checksum.php [hunk 1]
```diff
@@ -533,9 +533,22 @@ public function get_range_edges( $range_from = null, $range_to = null, $limit =
 
 		$this->validate_fields( array( $this->range_field ) );
 
+		// Performance :: When getting the postmeta range we do not want to filter by the whitelist.
+		// The reason for this is that it leads to a non-performant query that can timeout.
+		// Instead lets get the range based on posts regardless of meta.
+		$filter_valuess = $this->filter_values;
```
Comment (anomiex) [inline projects/packages/sync/src/replicastore/class-table-checksum.php:539]: `$filter_valuess` looks like a typo. Name it something like `$saved_filter_values` instead?

For that matter, code like this tends to make me wary versus something like
```php
$saved_filter_values = $this->filter_values;
$this->filter_values = null;
try {
    // `trim()` to make sure we don't add the statement if it's empty.
    $filters = trim( $this->build_filter_statement( $range_from, $range_to ) );
} finally {
    $this->filter_values = $saved_filter_values;
}
```
that won't forget to restore `$this->filter_values` in case something inside there throws. But maybe we don't need to care, if something throwing means the whole object should be considered invalid anyway.

**Review by anomiex — COMMENTED** [review]
I wonder whether you might run into the same problem with `commentmeta`. It looks like the query will have the same structure, trying to filter by `meta_key` then select min/max on something other than the primary key.

**Review by bisko — APPROVED** [review]
LGTM!

File: projects/packages/sync/src/replicastore/class-table-checksum.php (hunk 1 above)
Comment (bisko) [reply projects/packages/sync/src/replicastore/class-table-checksum.php]: That's definitely a good approach that we want to adopt for the future! 

In this case, if it throws, we don't need to care as it will propagate further up and toss out the result anyway.

Comment (mdbitz) [reply projects/packages/sync/src/replicastore/class-table-checksum.php]: > I wonder whether you might run into the same problem with commentmeta

As a note we have seen no indication that commentmeta has the same issue but that looks to be due to small number of keys in use. We will definitely conttinue to monitor but at this time it doesn't need any modifications.
