### PR TITLE
Simple Payments: Fix the upgrade nudge

### LINKED ISSUE #14743: Premium blocks on the front end
#### Steps to reproduce the issue

1. Open the editor on a free Simple site
2. Add an OpenTable block
3. Add a Calendly block
4. Add a Simple Payments block
5. Save the post
6. Open the post in the front end of your site

#### What I expected
I expected to see a message saying the block is unavailable (See paAmJe-so-p2).
screenshot-2019-06-06-at-15 11 07

#### What happened instead
Instead I saw links to opentable.com and calendly.com and nothing for Simple Payments.
Screenshot 2020-02-20 at 10 49 50

### PR DESCRIPTION
**Pull request by scruffian**
Fixes #14743

#### Changes proposed in this Pull Request:

* This makes sure we output the UpgradeNotice on WPCOM when a user has a SimplePayments block but no plan.
* Also fixes the display of a button

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* bug fix

#### Testing instructions:

* Apply the D40071-code patch
* Open the block editor on a Simple site without a plan
* Add a Simple Payments block
* Verify that you see the Upgrade Nudge
* Add all the block details and save the page
* Open the page in the front end
* Check that you see the upgrade nudge like this:
Screenshot 2020-03-09 at 16 55 02

#### Proposed changelog entry for your changes:

* no changelog

### CODE REVIEW

File: extensions/shared/components/block-nudge/index.jsx [hunk 1]
```diff
@@ -17,7 +17,8 @@ export const BlockNudge = ( { autosaveAndRedirect, buttonLabel, href, icon, subt
 					href={ href } // Only for server-side rendering, since onClick doesn't work there.
 					onClick={ autosaveAndRedirect }
 					target="_top"
-					isDefault
+					isSecondary
```
Comment (scruffian) [inline extensions/shared/components/block-nudge/index.jsx]: This doesn't work, but I'm not sure why yet...

Comment (scruffian) [reply extensions/shared/components/block-nudge/index.jsx]: It's working since I upgraded @wordpress/components

File: extensions/shared/components/block-nudge/index.jsx [hunk 2]
```diff
@@ -17,7 +17,7 @@ export const BlockNudge = ( { autosaveAndRedirect, buttonLabel, href, icon, subt
...
```
Comment (pablinos) [inline extensions/shared/components/block-nudge/index.jsx]: If we upgrade the components dependency and start using `isSecondary` here, are there other buttons that will need upgrading?

File: modules/simple-payments/simple-payments.php [hunk 3]
```diff
@@ -157,7 +157,7 @@ function parse_shortcode( $attrs, $content = false ) {
 
 		if ( ! $this->is_enabled_jetpack_simple_payments() ) {
 			if ( ! is_feed() ) {
-				$this->output_admin_warning( $data );
+				return $this->output_admin_warning( $data );
```
Comment (pablinos) [inline modules/simple-payments/simple-payments.php]: If the dependency change is an issue, then we could just make this change and deal with the dependency upgrade in another PR.

**Review by pablinos — DISMISSED** [review]
This works for me. It's probably worth checking that the dependency change doesn't have any knock on effects.

File: extensions/shared/components/block-nudge/index.jsx (hunk 2 above)
Comment (scruffian) [reply extensions/shared/components/block-nudge/index.jsx]: I don't think so, but the following components are also in that package so might have changed:
`TextControl`, `PanelBody`, `SVG`, `Path`, `withFallbackStyles`, `createSlotFill`, `Polygon`,`IconButton`, `ClipboardButton`, `TextControl`.

According to the [changelog](https://github.com/WordPress/gutenberg/blob/b3f900c34d41c282db5a6d5a43f8eaf5f091f3d6/packages/components/CHANGELOG.md) we should be ok except for IconButton...

Comment (scruffian) [reply extensions/shared/components/block-nudge/index.jsx]: I added a new PR for the dependency change: https://github.com/Automattic/jetpack/pull/14934

Comment (pablinos) [reply extensions/shared/components/block-nudge/index.jsx]: Cool, shall we back out the dependency change here or wait to merge #14934?

**Comment by scruffian** [comment]
I noticed we don't have tracking on this, so I added an issue for that, in case we want to add it: https://github.com/Automattic/jetpack/issues/14949

File: modules/simple-payments/simple-payments.php (hunk 3 above)
Comment (scruffian) [reply modules/simple-payments/simple-payments.php]: Done :)

File: extensions/shared/components/block-nudge/index.jsx (hunk 2 above)
Comment (scruffian) [reply extensions/shared/components/block-nudge/index.jsx]: Done!

File: extensions/shared/components/block-nudge/index.jsx (hunk 1 above)
Comment (Copons) [reply extensions/shared/components/block-nudge/index.jsx]: `isSecondary` is a new prop that replaces `isDefault`.
Here more info: https://github.com/Automattic/jetpack/pull/14588#issuecomment-582884443

**Review by Copons — APPROVED** [review]
Verified that this works as advertised!

**Review by jeherve — APPROVED** [review]

**Comment by scruffian** [comment]
r204197-wpcom
