### PR TITLE
VideoPress: fix video block conversion issue

### LINKED ISSUE #27630: VideoPress: converting existing video blocks to VideoPress v6 seems to lose some block settings
We have a report showing that a video block lost the "Show Controls" setting after being converted to the v6 block on the standalone VideoPress plugin.

* Last update on the issue: https://wordpress.org/support/topic/problem-with-videopress-blocks/#post-16236802
* Screencast showing the video without a setting that it was suposed to have: https://app.screencast.com/Sjyajk6ETMbWC

### PR DESCRIPTION
**Pull request by retrofox**
This PR issue when converting the core/video block to the `videopress/video` block. The issue [reported here](https://wordpress.org/support/topic/problem-with-videopress-blocks/) is that the new block loses all previous attributes.

Fixes https://github.com/Automattic/jetpack/issues/27630

#### Changes proposed in this Pull Request:

* VideoPress: fix video block conversion issue

#### Testing instructions:

* Activate Jetpack and VideoPress plugin
* Create a `core/video` block
* Set the video for the block
* Change block settings, for instance:

Screen Shot 2022-11-30 at 11 48 18

* Save the post
* Deactivate the Jetpack plugin
* Go back to the block editor
* Hard-refresh
* Confirm you see the dialog to convert the block to `v6`
image
* Confirm the app converts the block to video by clicking on the Attempt... button
* Confirm the new block preserves the same settings that the previous block

Screen Shot 2022-11-30 at 11 51 46

### CODE REVIEW

File: projects/packages/videopress/src/client/block-editor/extend/core-video/index.js [hunk 1]
```diff
@@ -54,10 +54,34 @@ addFilter(
...
+ * Organize the block attributes for the new videopress/video block
+ *
+ * @param {object} attributes        - core/video block attributes
+ * @param {object} defaultAttributes - default core/video block attributes
+ * @returns {object}                   The new attributes
+ */
+function getVideoPressVideoBlockAttributes( attributes, defaultAttributes ) {
+	const attrs = attributes || defaultAttributes;
+
+	// Upadte attributes names to match the new VideoPress Video block.
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/block-editor/extend/core-video/index.js]:
```suggestion
	// Update attributes names to match the new VideoPress Video block.
```

**Review by dhasilva — DISMISSED** [review]
LGTM

**Review by dhasilva — APPROVED** [review]

**Review by lhkowalski — APPROVED** [review]
Followed the steps and it works as described. Before the conversion:

Screen Shot 2022-11-30 at 12 10 31

After the conversion:

Screen Shot 2022-11-30 at 12 12 26

Nice job!
