### PR TITLE
Search: Always show save button for mobile Customberg

### LINKED ISSUE #20908: Instant Search: make mobile user experience clearer
### Impacted plugin

Jetpack

### Steps to Reproduce

1. On a site with Instant Search enabled, go to /wp-admin/admin.php?page=jetpack-search-customize.
2. Resize the window to the smallest mobile breakpoint.

### A clear and concise description of what you expected to happen.

It should be clear that we are on this page to update settings. 

### What actually happened

* When you land on the page, you see the modal preview, but you have to discover the cog icon to edit the settings.
* When you're done editing settings, you need to switch back to the modal preview in order to save the changes.

Possible solutions:
* Start the mobile user on the settings pane, and allow them to switch to the modal preview afterwards. The primary purpose of the screen is settings, so let's start them there.
* Add a Save button at the bottom of the settings pane so that is not necessary to switch back to the modal preview to complete the save.
* Add a simple instruction to direct the user towards the cog icon for customization, in case they miss it.

Screen Shot 2021-09-01 at 14 51 34

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #20908.

#### Changes proposed in this Pull Request:
- Refactors styles to always show the save button for all mobile headers.
- Changes labeling for the mobile sidebar button so that the "close sidebar" button is now a "show preview" button.

<table>
<tr>
	<td>Screen Shot 2021-09-28 at 3 55 30 PM
	<td>Screen Shot 2021-09-28 at 3 55 33 PM
<tr>
<td>Initial interface for mobile users
<td>Interface show after clicking the white image button
</table>

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your Jetpack site with a Search subscription.
* Navigate to `/wp-admin/admin.php?page=jetpack-search-configure` on a mobile viewport.
* Ensure that the Save button is always shown in the mobile header.

### CODE REVIEW

**Comment by bluefuton** [comment]
Really liking the new preview/settings toggle and the persistent save button at smaller breakpoints 🎉

I'm not seeing the Save button at all on larger breakpoints though (using Firefox Mac):

Screen Shot 2021-09-29 at 15 15 49

**Comment by jsnmoon** [comment]
> I'm not seeing the Save button at all on larger breakpoints though (using Firefox Mac) (@bluefuton)

Fixed!

**Comment by kangzj** [comment]
Hi @jsnmoon the button shows on phone view, but missing on larger screens (>788px or just try the iPad pro dimension). Could you have a look please?

image

**Comment by kangzj** [comment]
My bad.. I thought I updated the branch but apparently I didn't.

File: projects/plugins/jetpack/modules/search/customberg/components/sidebar/index.jsx [hunk 1]
```diff
@@ -30,13 +31,14 @@ export default function Sidebar( props ) {
 				tabindex="-1"
 			>
 				<Tabs enabledSidebarName={ enabledSidebarName } enableSidebar={ enableSidebar } />
+				<SaveButton />
 				<Button
-					aria-label={ __( 'Close settings', 'jetpack' ) }
+					aria-label={ __( 'Show preview', 'jetpack' ) }
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/customberg/components/sidebar/index.jsx:36]: Could we use the `label` attribute, which would fill `aria-label` and Tootip as well - I guess it would be nice to have some text for buttons with just an icon.

**Review by kangzj — COMMENTED** [review]
Good job Jason! This works for me and only one code quality related comment. Feel free to mark as `Needs Review` after looking at that 😄

File: projects/plugins/jetpack/modules/search/customberg/components/sidebar/index.jsx (hunk 1 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/customberg/components/sidebar/index.jsx:36]: The `label` attribute doesn't actually render the text within the button but instead applies it to `aria-label` and to the tooltip body. Tooltips are often ineffective in mobile contexts, so it won't be good for us here (and I don't think you were proposing that we adopt tooltips here, at any rate).

I'd like to push back against adding verbose labels like `Show preview` and `Show settings` in these buttons for mobile. For horizontally constrained viewports, doing so makes our layout break in undesirable ways:

|Before|After|
|---|---|
|Screen Shot 2021-10-04 at 5 35 39 PM|Screen Shot 2021-10-04 at 5 32 09 PM|
|Screen Shot 2021-10-04 at 5 35 36 PM|Screen Shot 2021-10-04 at 5 32 04 PM|

Comment (kangzj) [reply projects/plugins/jetpack/modules/search/customberg/components/sidebar/index.jsx:36]: ha I thought the text would be hovering tootip. All good mate, thanks for trying it out.

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 🚢

**Comment by jsnmoon** [comment]
Fusion generated an failing patch for diffusion; it created a modification patch for `modules/search/customberg/components/save-button/index.jsx` without moving the original `search/customberg/components/header/save-button.jsx` file first.

I manually created the patch by hand to resolve this issue. cc @Automattic/jetpack-crew

**Comment by jsnmoon** [comment]
🚢 r232817-wpcom
