### PR TITLE
SSO: do not display JITM when not in wp-admin

### LINKED ISSUE #14547: SSO JITM appears in Calypso Sidebar
It looks like an SSO JITM is showing up in the sidebar, probably unintentionally. This was originally found and reported by @rickybanister 

I believe this one is registered at https://github.com/Automattic/jetpack/blob/e17a5c667d9d7aaf5527e9c626911d00489aa073/modules/sso.php#L1113

Screen Shot 2020-01-31 at 2 16 51 PM

But appears in two API responses on the `calypso:stats-day:admin-notices` and `calypso:stats:sidebar_notice`. For the amount of content here the API should not be returning this.

Screen Shot 2020-01-31 at 2 18 31 PM

Screen Shot 2020-01-31 at 2 17 26 PM

We do have an A/B test running for sidebar banners, but this is unrelated since I see the same behavior in Calypso master at `9820c2fa70292fda1db438deca943ce1b29f0faa` before the PR was merged.

@Automattic/manage is happy to help review any PRs if folks have a fix.

#### To Reproduce This:
- Create a test site ([this branch](https://github.com/Automattic/jetpack/pull/14543) makes it easier for the SSO JITM to display), https://jurassic.ninja/create/?jetpack-beta&branch=try/sso-jitm
- Setup Jetpack and Connect to WordPress.com
- Turn on the following setting in Jetpack Settings:
Screen Shot 2020-01-31 at 1 43 35 PM

- Visit WordPress.com/stats/day/siteslug

Expected: Banner appears in Stats
Actual: Banner appears in Stats and in Sidebar

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #14547

#### Changes proposed in this Pull Request:

This PR introduces a change to the filter that can be used to customize the list of JITMs returned by a site for a specific query. We now pass the message path to that filter, so folks customizing the list of messages can choose to only do so on specific pages, for example.

We then use that new parameter to ensure that the custom JITM currently displayed the first time you log in to your site using SSO only appears when you access the main dashboard, where the message should be displayed.

#### Testing instructions:

- Create a test site using this branch.
- Setup Jetpack and Connect to WordPress.com
- Turn on the following setting in Jetpack Settings:
Screen Shot 2020-01-31 at 1 43 35 PM
- Visit WordPress.com/stats/day/siteslug
- You should not see a JITM telling you more about the SSO feature.
- Go back to wp-admin and log out.
- Log back in using SSO.
- You should see the JITM then.

#### Proposed changelog entry for your changes:

* Secure Sign On: do not display feature message when logging in to WordPress.com's central dashboard.

### CODE REVIEW

**Review by kwight — DISMISSED** [review]
Works wonderfully 👍

File: modules/sso.php [hunk 1]
```diff
@@ -1087,13 +1087,21 @@ public function get_user_data( $user_id ) {
...
-		if ( true != Jetpack_Options::get_option( 'sso_first_login' ) ) {
+	public function inject_sso_jitm( $envelopes, $message_path ) {
+		/*
+		 * Bail early if:
+		 * - the request does not originate from wp-admin main dashboard.
+		 * - that's not the first time the user uses SSO.
+		 */
+		if (
+			'wp:dashboard:admin_notices' !== $message_path
+			|| true != Jetpack_Options::get_option( 'sso_first_login' ) // phpcs:ignore WordPress.PHP.StrictComparisons.LooseComparison
```
Comment (gwwar) [inline modules/sso.php]: Non-blocking note, this was in the code before but do we need type conversion here? What values might `Jetpack_Options::get_option( 'sso_first_login' )` be?

**Review by gwwar — DISMISSED** [review]
Nice! Thanks for the fix @jeherve ✨ 

I verified that this only displays in wp-admin:
Screen Shot 2020-02-11 at 3 11 25 PM

And without any Calypso notices for SSO:
Screen Shot 2020-02-11 at 3 12 05 PM
Screen Shot 2020-02-11 at 3 11 58 PM

File: modules/sso.php (hunk 1 above)
Comment (jeherve) [reply modules/sso.php]: You're right, this could be simpler.

3f85104028468a53529a98aedbd32f46e76d2c56

File: modules/sso.php [hunk 2]
```diff
@@ -1087,13 +1087,21 @@ public function get_user_data( $user_id ) {
...
-	 * @param array $envelopes Array of JITM messages received after API call.
+	 * @param array  $envelopes    Array of JITM messages received after API call.
+	 * @param string $message_path The message path to ask for.
 	 *
 	 * @return array $envelopes New array of JITM messages. May now contain only one message, about SSO.
 	 */
-	public function inject_sso_jitm( $envelopes ) {
-		// Bail early if that's not the first time the user uses SSO.
-		if ( true != Jetpack_Options::get_option( 'sso_first_login' ) ) {
+	public function inject_sso_jitm( $envelopes, $message_path ) {
```
Comment (zinigor) [inline modules/sso.php]: Am I overthinking this, or should we add a default value to the `$message_path` parameter here for backwards compatibility? Just in case there's some other invocation that we've forgotten about, that will only use one argument.

**Review by zinigor — DISMISSED** [review]
The change looks good to me, with one minor comment. If you decide it's fine to go like this, let's go like this.

File: modules/sso.php (hunk 2 above)
Comment (kraftbj) [reply modules/sso.php]: d89edb2

**Review by kraftbj — APPROVED** [review]
