### PR TITLE
Subscribe block: move button to next line when width 100%

### LINKED ISSUE #20643: Subscription Form Block: if button width is set to 100%, place it on a new line
#### Steps to reproduce the issue

1. Add the Subscription Form block to a post or page
2. On the block settings, click on 'Spacing Settings'
3. For 'Button Width', choose 100%

#### What I expected
1. The button to be full width, which would force it to move to a new line
2. The setting `Place button on new line` to be toggled on automatically

#### What happened instead
The button is not 100% wide.

Screen Shot 2021-08-11 at 11 35 07

### PR DESCRIPTION
**Pull request by eoigal**
Fixes https://github.com/Automattic/jetpack/issues/20643

This PR sets the `buttonOnNewLine` attribute to move the subscribe button to a new line if the button width is set to 100%. If the user explicitly selects a width less than 100%, i.e. 25%, 50% or 75% the `buttonOnNewLine` attribute is set to false allowing the subscribe button to render inline.

## Proposed changes:

* Sets the `buttonOnNewLine` attribute to true if button width set to 100%
* Sets the `buttonOnNewLine` attribute to false if button width set to less than 100%

## Example

https://github.com/user-attachments/assets/99a1b47a-2957-430b-ba0a-497bc245cff4

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sandbox public-api.wordpress.com and your test WPCOM site
* Apply this PR to your WPCOM sandbox
* Create a new post with the subscribe block
* Edit the settings for the subscribe block - set width to 100% and confirm button now renders full width in a new line in the post

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/controls.js [hunk 1]
```diff
@@ -259,7 +259,10 @@ export default function SubscriptionControls( {
 
 				<WidthControl
 					width={ buttonWidth }
-					onChange={ newButtonWidth => setAttributes( { buttonWidth: newButtonWidth } ) }
+					onChange={ newButtonWidth => {
+						setAttributes( { buttonWidth: newButtonWidth } );
+						setAttributes( { buttonOnNewLine: newButtonWidth === '100%' } );
```
Comment (arcangelini) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/controls.js]: Can these be combined into one call? Also, I think it could also be better if you use the original value or the new width check. Currently when I set the button to be on a newline then toggle the sizes below 100 it repeatedly turns off my previous setting.

```suggestion
						setAttributes( {
							buttonWidth: newButtonWidth,
							buttonOnNewLine: buttonOnNewLine || newButtonWidth === '100%',
						} )
```

**Review by arcangelini — DISMISSED** [review]
Functionally works exactly as expected. I left one suggestion, but it is not necessarily blocking. 👍👍

**Review by arcangelini — DISMISSED** [review]
:rocket: :rocket:
