### PR TITLE
Photon: get rid of jQuery dependency

### LINKED ISSUE #11181: Photon JS: Remove dependency to jQuery
(Edited description to match the current scope of the issue)

#### Steps to reproduce the issue

0. Create a new WordPress, using Twenty Nineteen, and observe that on the frontend of the site, jQuery is not loaded/required.
1. Install/activate Jetpack
2. Go to the module list, activate Photon
3. Now on the frontend of the site, observe that jQuery is being loaded

#### What I expected
Photon to not unnecessarily load additional resources. `photon.js` currently uses jQuery, but it doesn't look like there's much there that needs it. It can be re-written to vanilla js. 

#### What happened instead
See above -- core's copy of jQuery is enqueued/loaded. To make matters worse, that version of jQuery has a known vulnerability (nothing to do with Jetpack, but that's what flagged this for me). https://snyk.io/vuln/npm:jquery?lh=1.12.4&utm_source=lighthouse&utm_medium=ref&utm_campaign=audit

### PR DESCRIPTION
**Pull request by brbrr**
Fixes #11181

#### Changes proposed in this Pull Request:

* replace jQuery dependency with vanilla javascript in Photon module

#### Testing instructions:

* Make sure that Photon module is enabled 
* Load a post with some images in it. Make sure that all `photon` hosted images have `width` & `height` CSS properties and HTML attributes. This can be checked (at least) in 2 ways:
- run this code snipped on in browser console: `document.querySelectorAll("img[src*='wp.com']").forEach( e => console.log('CSS value:', e.width, 'HTML attr:', e.getAttribute('width')))`. you should see pairs of same numbers. 
- Inspect image element in Chrome DevTools, under `Elements` tab select `Properties` tab in right column and inspect first node(`img.wp-image-*`) for `width` & `attributes > width` values
* Test with Lazy Load module enabled, with some images not loaded right away. 

#### Proposed changelog entry for your changes:

* Photon: replace jQuery dependency with vanilla javascript

### CODE REVIEW

File: modules/photon/photon.js [hunk 1]
```diff
@@ -1,55 +1,61 @@
...
+		} else {
+			document.addEventListener( 'DOMContentLoaded', fn );
+		}
+	};
 	/**
 	 * Check both when page loads, and when IS is triggered.
 	 */
-	$( document ).ready( restore_dims );
-
-	if ( 'on' in $.fn ) {
```
Comment (brbrr) [inline modules/photon/photon.js]: This condition only makes sense for jQuery which is basically a fallback for old jQuery versions

File: modules/photon/photon.js [hunk 2]
```diff
@@ -1,55 +1,61 @@
...
-					reset_for_retina( this );
-				}
-			}
-			else {
-				$this.load( recalc );
-			}
-		} );
+		var elements = document.querySelectorAll( 'img[data-recalc-dims]' );
+		for (var i = 0; i < elements.length; i++) {
+			recalculate.call( elements[i] );
```
Comment (brbrr) [inline modules/photon/photon.js]: Since `recalculate` is used as a function call _and_ an eventHandler - we need to make sure element is available in both cases.

**Review by kraftbj — COMMENTED** [review]
I tested this out and it provides the width/height as expected without lazy loading.

With lazy loading on, I did not observe the width/height CSS.
```document.querySelectorAll("img[src*='wp.com']").forEach( e => console.log('CSS value:', e.width, 'HTML attr:', e.getAttribute('width')))
CSS value: 640 HTML attr: null 
CSS value: 260 HTML attr: null
```

It looks like everything worked fine, but from the testing description, I believe this is not expected, right?

**Comment by brbrr** [comment]
@kraftbj Sorry for the late response. I double checked with current stable - and the behavior is the same: With lazy load enabled `HTML attr:` are `null`s.

**Review by kraftbj — DISMISSED** [review]

File: modules/photon/photon.js [hunk 3]
```diff
@@ -1,54 +1,60 @@
...
-	$( document ).ready( restore_dims );
-
-	if ( 'on' in $.fn ) {
-		$( document.body ).on( 'post-load', restore_dims );
-	} else {
-		$( document ).delegate( 'body', 'post-load', restore_dims );
-	}
-} )( jQuery );
+	ready( restore_dims );
+	document.body.addEventListener( 'post-load', restore_dims );
```
Comment (simison) [inline modules/photon/photon.js]: Here's another, what I think is more simple/readable approach for attaching onload event:

https://github.com/Automattic/jetpack/blob/201ec52be66261a364f0805a6e44d25269d84793/extensions/blocks/tiled-gallery/view.js#L57-L64

Note also window/document protector in case the script runs in context which doesn't have those (e.g. some test environments).

File: modules/photon/photon.js [hunk 4]
```diff
@@ -1,54 +1,60 @@
...
-
-					var width = this.width,
-						height = this.height;
-
-					if ( width && width > 0 && height && height > 0 ) {
-						$this.attr( {
-							width: width,
-							height: height,
-						} );
+		var elements = document.querySelectorAll( 'img[data-recalc-dims]' );
```
Comment (simison) [inline modules/photon/photon.js]: Note that `querySelectorAll` returns `NodeList`, not an array: https://developer.mozilla.org/en-US/docs/Web/API/NodeList

This is important in case anyone tries to loop it later with `forEach` or similar; it would break on IE11. Looping it with `for` [seems to be safe tho](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Example), so no changes required here. Just wanted you to be aware in case it wasn't conscious decision to use `for` here.

Comment (simison) [reply modules/photon/photon.js]: And most importantly, do test with IE11 just in case. :-)

File: modules/photon/photon.js [hunk 5]
```diff
@@ -1,54 +1,60 @@
 /* jshint onevar: false */
 
-( function( $ ) {
+( function() {
+	function recalculate() {
+		if ( this.complete ) {
+			// Support for lazy loading: if there is a lazy-src attribute and it's value
+			// is not the same as the current src we should wait until the image load event
+			var lazySrc = this.getAttribute('data-lazy-src');
```
Comment (simison) [inline modules/photon/photon.js]: I'm not familiar with how Lazy loading attributes work and if they are injected from backend or in frontend with JS, so just leaving some notes in case there are concerns to test:

- `skip-lazy` css class might be present, can it occur with `data-lazy-src` simultaneously? ([docs](https://jetpack.com/support/lazy-images/))
- Can this script run before Lazy scripts and can that affect if `data-lazy-src` is present?

**Comment by kraftbj** [comment]
@brbrr Can you review the comments? It's good to merge if you don't want to make changes, but want to give the option.

File: modules/photon/photon.js (hunk 3 above)
Comment (simison) [reply modules/photon/photon.js]: Just realised and got pointed out by @brbrr that these are different events (`DOMContentLoaded` and `post-load`). I'm not familiar of the difference. :-)

I was pointing out about code readability, not about which event to use. I felt that instead of:

```
ready( restore_dims );
document.body.addEventListener( 'post-load', restore_dims );
```

having the same as `if() { } else { }` format was clearer, but again I'm not perfectly sure if these examples do the same thing. :-)

I'd say don't worry and if it works, leave it as it is! 😅

Comment (brbrr) [reply modules/photon/photon.js]: `post-load` is an infinite scroll custom event, so I think we should use both 🤷‍♂️

File: modules/photon/photon.js (hunk 5 above)
Comment (brbrr) [reply modules/photon/photon.js]: > skip-lazy css class might be present, can it occur with data-lazy-src simultaneously?

According to lazy load code - `skip-lazy` is in the blacklisted classed, which bails before `data-lazy-src` is getting set.

> Can this script run before Lazy scripts and can that affect if data-lazy-src is present?

photon scripts have higher priority(9), which makes sure it gets loaded before lazy images. Lazy load script relies on jQuery `ready` function. But photon relies on `complete` to be true, which (I'd expect) to resolve after lazy images scripts would finish its work. FWIW we do not change any functionality in this PR

**Comment by kraftbj** [comment]
Rebased and needs testing after Travis is happy.

**Review by kraftbj — APPROVED** [review]
