### PR TITLE
Forms: Fix sorting of responses in classic view

### LINKED ISSUE #42599: Form responses are not filtering by selected source
### Impacted plugin

Jetpack

### Quick summary

Within simple and atomic sites, filtering form responses by the "All sources" dropdown menu does not filter correctly. There is no change to the results.

### Steps to reproduce

1. Add two different forms to a test simple or atomic site. Ensure both forms are on two different pages.
2. Submit multiple form responses for each form.
3. Go to the dashboard, under Feedback > Form Responses.
4. Click the "All sources" dropdown menu and change a category. 
5. Click the "Filter" button.

**Expected behavior**
* The list should only filter the responses for the selected dropdown menu option.
* The total number of items (on the right under "Search Responses") should change based on the dropdown menu selection.

**Actual behavior**
* Nothing changes.
* The total number of items (on the right under "Search Responses") remains unchanged. It shows the total of form responses submitted for both forms.

Screen recording of this behavior:

https://github.com/user-attachments/assets/639a3816-6a88-4290-a9ad-27d97ed6d7cb

### Site owner impact

More than 60% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

Atomic, Simple

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/Automattic/jetpack/issues/42599

In https://github.com/Automattic/jetpack/pull/41602 we updated the new responses inbox view and utilized the `WP_REST_Posts_Controller` for handling the data actions. While the `feedback` post type is not `hierarchical` in the traditional sense ( parent of the same post type), it behaves like one because we store the id of the post/page where the feedback was created in its `parent` property.

That was the reason for [updating](https://github.com/Automattic/jetpack/pull/41602/files#diff-8553b10e9f86366e46982a8e498ca06c0784d5e64c168a19ed759c2be4b2a986R219) its `hierarchical` value in that PR, so we could also filter by `parent` and fetch the `parent` prop in the REST responses 'for free'.

It seems though that particular change affects the classic view (wp-admin) in a quite convoluted way.
1. The `WP_Posts_List_Table` class used to render the admin list has no extension points
2. For `hierarchical` post types it [renders through ](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/class-wp-posts-list-table.php#L812)a different function that groups records by their `parent` value.

### Proposed changes
This PR reverts the `hierarchical` change to feedback post type and adds the neccessary arguments to the REST API endpoint to be able to filter by `parent` and fetch the `parent` prop in the REST responses.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?
no

## Testing instructions:
1. In responses classic (wp-admin) view ensure that the items are sorted by date  in descending order and there is no grouping by their parent
2. Ensure everything else works as before and no regressions are introduced
3. In responses `inbox` view ensure the filtering by parent works as expected and the `source` field have correct values
4. Ensure everything else works as before and no regressions are introduced

### CODE REVIEW

**Review by simison — APPROVED** [review]
Tested inbox & classic views, and filtering by month and source.

Newest responses are on top as expected, and when exporting list to google, newest are last lines as well as expected.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php [hunk 1]
```diff
@@ -155,6 +155,13 @@ static function ( $post_id ) {
 	public function get_item_schema() {
 		$schema = parent::get_item_schema();
 
+		$schema['properties']['parent'] = array(
+			'description' => __( 'The ID for the parent of the post. This refers to the post/page where the feedback was created.', 'jetpack-forms' ),
+			'type'        => 'integer',
+			'context'     => array( 'view', 'edit', 'embed' ),
```
Comment (anton-vlasenko) [inline projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:161]: Was enabling this parameter for the embed context necessary?
I'm asking because the parent controller uses:
```
array( 'view', 'edit' ),
```

**Review by anton-vlasenko — COMMENTED** [review]
I know this has already been merged, but I didn't get a chance to review it earlier.
Thanks.

File: projects/packages/forms/src/contact-form/class-contact-form-endpoint.php (hunk 1 above)
Comment (ntsekouras) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:161]: Not really, but I added it as I had done the same for the others (so for consistency). Do you think it's better to remove it from every prop?

Comment (anton-vlasenko) [reply projects/packages/forms/src/contact-form/class-contact-form-endpoint.php:161]: That could slightly increase the response size when this endpoint is queried using the `_embed` parameter. I'm not certain whether the `parent` value is required for the embed context.
