### PR TITLE
Simple Payments: pre-populate attributes when converting from classic block

### LINKED ISSUE #29870: Gutenberg: Simple Payments in Classic Block converts to an empty Simple Payments block
Simple Payments in the Calypso Classic block sometimes converts to a blank simple payments block.

To Reproduce:
1. In a fresh post, add a classic block
2. Click on the Add > Payment Button
3. Choose an existing Payment Button
4. On the Classic Block option, choose Convert to Blocks
Expected: The Simple Payments block is filled with the appropriate details from the existing simple payment
Actual: In many cases we see an empty Simple Payment block

breaks

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request:
It populates rightly the product properties gotten from the data/response when it comes from a shortcode transformation.

Fixes https://github.com/Automattic/wp-calypso/issues/29870

#### Testing instructions:
1. Get a post with a "Simple Payment Button". If it doesn't exist just create it:
a. Get the product ID (inspect the dom tree trying to find the ID, or inspect the XHR request from the network tab)
b. Once you get the product ID, create a new `Classic` block with the Simple Payments shortcode:
```
[simple-payment id="<product-id"]
```
image

2. Convert to Blocks
image

3. Once it's converted it should populate the fields with the right data.
populate-simple-payments

#### Proposed changelog entry for your changes:

Simple Payments Button: Convert classic Blocks (shortcode) rightly.

### CODE REVIEW

File: extensions/blocks/simple-payments/edit.js [hunk 1]
```diff
@@ -90,34 +90,26 @@ class SimplePaymentsEdit extends Component {
 		 * When subsequent saves occur, we should avoid injecting attributes so that we do not
 		 * overwrite changes that the user has made with stale state from the previous save.
 		 */
-		if ( ! this.shouldInjectPaymentAttributes ) {
+
+		const { simplePayment } = this.props;
+		if ( ! this.shouldInjectPaymentAttributes || ! Object.keys( simplePayment ).length ) {
```
Comment (mmtr) [inline extensions/blocks/simple-payments/edit.js]: This can be simplified since empty objects are _falsy_:

Screen Shot 2019-03-28 at 14 29 52
```suggestion
		if ( ! this.shouldInjectPaymentAttributes || ! simplePayment ) {
```

**Review by mmtr — DISMISSED** [review]
Nice fix! It worked as expected when I converted to blocks a existing post created in the classic editor that was containing a payment button.

File: extensions/blocks/simple-payments/edit.js (hunk 1 above)
Comment (retrofox) [reply extensions/blocks/simple-payments/edit.js]: Thanks. Updating.

Comment (retrofox) [reply extensions/blocks/simple-payments/edit.js]: updated and rebased

**Comment by simison** [comment]
@kraftbj FYI I've added this to 7.2 milestone as it's a bugfix, in case it makes it in before we ship blocks. Lemme know if you'd prefer to punt it for 7.3

**Comment by simison** [comment]
It seems like the main concerns there are addressed and any other changes would be good for follow up PRs. If we can get this merged soon, we could still make it tonight to 7.2 beta. :-)

**Comment by simison** [comment]
Obs, sorry, the previous comment was meant to another PR. Working on a small screen. 😅

**Comment by kraftbj** [comment]
Since it isn't a regression caused by 7.2, I would prefer to punt to 7.3 if it isn't critical. We've been burnt before by sliding in fixes late that caused new issues (I've done plenty of that burning).

One advantage of waiting too is don't need to worry about cherry-picking cross-repo :)

**Comment by simison** [comment]
Sure, works for me!

**Review by mmtr — DISMISSED** [review]

**Review by rodrigoi — DISMISSED** [review]
🚀 🌕 !

**Comment by roccotripaldi** [comment]
I think punting to 7.3 should be fine, but I'd like to get this on master ASAP so that we can fix the problem for wpcom sites.

**Review by jeherve — DISMISSED** [review]
This works well in my tests. 👍

**Comment by obenland** [comment]
@roccotripaldi Damian is on leave, would you be available to bring this over the finish line? 
/cc @vindl

**Comment by roccotripaldi** [comment]
> would you be available to bring this over the finish line?

@obenland 
Yeah, no problem. I'll see that it's merged here, and on wpcom!

**Review by kraftbj — APPROVED** [review]
Works as advertised.
