### PR TITLE
Widgets - Top Posts: use the WP.com REST API endpoint

### LINKED ISSUE #2196: Rewrite Top Posts and Pages Widget to use WP.com REST API
The current widget uses the csv API for determining the top posts. The REST API is much more flexible: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/top-posts/

There are a number of bugs that occur with the current API. Particularly corner cases where the posts returned are of the wrong post type or for some other reason cannot be displayed. This causes fewer posts than the user specified to be displayed. In these cases multiple queries to the API may be needed, and caching should be added (similar to related posts?) so the page load time does not go up too much.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #2196

#### Changes proposed in this Pull Request:
* stop fetching a CSV with posts stats and use the `/sites/%site%/stats/top-posts` endpoint in wpcom.

#### Testing instructions:
* add the widget, it should correctly display the top posts

#### Proposed changelog entry for your changes:
Widgets: the Top Posts widget now uses an endpoint from WP.com REST API which allows better performance and is more flexible for future updates.

### CODE REVIEW

File: modules/widgets/top-posts.php [hunk 1]
```diff
@@ -488,12 +488,14 @@ function get_by_views( $count, $args ) {
 			$days = 2;
 		}
 
-		$post_view_posts = stats_get_csv( 'postviews', array( 'days' => absint( $days ), 'limit' => 11 ) );
-		if ( ! $post_view_posts ) {
+		$post_view_posts = stats_get_from_restapi( array(), 'top-posts?max=10&summarize=1&num=' . absint( $days ) );
```
Comment (jeherve) [inline modules/widgets/top-posts.php]: Nice!

Did you add the query parameters to the sub-endpoint URL instead of the arguments array to bypass #5860?

Also, is there a reason why you went with `10` instead of `11`? in this case?

Comment (eliorivero) [inline modules/widgets/top-posts.php]: Exactly, if I added them as array in that first argument they were filtered out so I added them as query parameters.

There's no explanation about the 11 in [the commit that introduced it](https://github.com/Automattic/jetpack/commit/87f03f54e5e02ac1264a980745cd1dd02856042d#diff-dd11499ff5fdaf0fca3a7ec45dada777) and the widget says it will returns 10 at most so it makes sense to set it at 10. Please let me now if I'm missing something here.

Comment (jeherve) [inline modules/widgets/top-posts.php]: Yes, that commit message wasn't very helpful.

The widget can indeed be set to return 10 posts maximum. However, among those 10 posts you'll often find the home page, and that home page is not displayed in the Top Posts Widget.

That means that if you do a query for 10 posts, you may end up with only 9 unique posts that can be used in the widget.

To avoid displaying only 9 posts when the site owner asked for 10 posts in the widget settings, we decided to query for one more than the maximum (11). We then make sure to respect the specified `$count` by adding that limit to the array of posts that we build later on.

I hope this clarifies things a bit. I'll add a link to this comment in the original commit, just in case this conversation comes up again in the future :)

Comment (eliorivero) [inline modules/widgets/top-posts.php]: Thanks for the explanation! I've verified it works as you described so I set the number to 11 as before.

**Comment by thingalon** [comment]
Looks good to me, appears to work well. :)
