### PR TITLE
VideoPress: Fix mobile dashboard layout

### LINKED ISSUE #26019: VideoPress: VideoGrid - mobile support
Image

### PR DESCRIPTION
**Pull request by dhasilva**
Closes #26019

#### Changes proposed in this Pull Request:

* Fixes mobile layout on dashboard library

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* With at least one video, go to the dashboard on mobile or simulate mobile on your browser
* Check that the header fits the width correctly

Before | After
----------|-------
vp-mobile-before | vp-mobile-after

### CODE REVIEW

File: projects/packages/videopress/src/client/admin/components/admin-page/libraries.tsx [hunk 1]
```diff
@@ -64,26 +64,30 @@ const VideoLibraryWrapper = ( {
...
+	const [ isSm ] = useBreakpointMatch( 'sm' );
 
 	const [ isFilterActive, setIsFilterActive ] = useState( false );
 
-	const singularTotalVideosLabel = __( 'Video', 'jetpack-videopress-pkg' );
-	const pluralTotalVideosLabel = __( 'Videos', 'jetpack-videopress-pkg' );
+	const singularTotalVideosLabel = __( '1 Video', 'jetpack-videopress-pkg' );
+	const pluralTotalVideosLabel = sprintf(
+		/* translators: placeholder is the number of videos */
+		__( '%s Videos', 'jetpack-videopress-pkg' ),
```
Comment (retrofox) [inline projects/packages/videopress/src/client/admin/components/admin-page/libraries.tsx:74]: nice

**Review by retrofox — APPROVED** [review]
image

🚀
