### PR TITLE
Calendly Block: Fixes Widget Not Loading on P2 Front End

### LINKED ISSUE #15935: Calendly Block: Widget embed doesn't work on P2 front end
#### Steps to reproduce the issue

This can only be reproduced by a12s.

1. Create a post on a P2 with a paid plan.
2. Insert the Calendly block, and add a Calendly link.
3. The block should embed a Calendly widget in the editor.
4. Save the post and preview/view it in the front end.

#### What I expected

To see the Calendly widget embedded in the front end.

#### What happened instead

The widget is not embedded.

---

As far as I could see in my early investigation, all the necessary pieces are output as expected.
The block container gains the correct `id`, the inline JS (`Calendly.initInlineWidget( ... )`) that renders the widget shows up in the page source and target the correct element (which exists in the page), and it's even called _after_ the element is rendered.

Copying that inline JS and manually executing it in the browser console works fine, displaying the widget.

### PR DESCRIPTION
**Pull request by allilevine**
Fixes #15935 

#### Changes proposed in this Pull Request:

* If jQuery and o2 are available, bind the `ready.o2` [event](https://backbonejs.org/#Events-on) to the body element and initialize the Calendly widget in the callback. This loads the Calendly widget _after_ the o2 plugin has replaced main#content.

#### Jetpack product discussion

See 426-gh-p2tenberg

#### Does this pull request change what data or activity we track or use?

No changes.

#### Testing instructions:

Only a12s can test this fix.
* Apply D49317 to your sandbox with a premium plan.
* Activate the P2020 theme with wp cli: `wp theme activate pub/p2020 --url=[siteurl]`
* Enable Calendly blocks by commenting out wp-content/plugins/p2tenberg-wpcom/p2tenberg-wpcom.php line 159 (`'jetpack/calendly',`)
* Create a post and insert the Calendly block, and add a Calendly link.
* The block should embed a Calendly widget in the editor.
* Save the post and preview/view it in the front end.
* Check that the index can display multiple Calendly widgets.
* Regression test that the Calendly widget still displays correctly on Atomic, self-hosted, and simple non-P2 paid plan sites.

#### Proposed changelog entry for your changes:

* Update the Calendly block to work with a8c P2s.

### CODE REVIEW

File: extensions/blocks/calendly/calendly.php [hunk 1]
```diff
@@ -64,6 +64,7 @@ function load_assets( $attr, $content ) {
 	$classes                 = Jetpack_Gutenberg::block_classes( FEATURE_NAME, $attr, array( 'calendly-style-' . $style ) );
 	$block_id                = wp_unique_id( 'calendly-block-' );
 	$is_amp_request          = class_exists( 'Jetpack_AMP_Support' ) && \Jetpack_AMP_Support::is_amp_request();
+	$is_p2_site              = ( defined( 'IS_WPCOM' ) && IS_WPCOM ) && true === get_blog_option( get_current_blog_id(), 'o2_options' )['o2_enabled'];
```
Comment (allilevine) [inline extensions/blocks/calendly/calendly.php:67]: Is this the best way to check if it's WPCOM / get the blog ID?

File: extensions/blocks/calendly/calendly.php [hunk 2]
```diff
@@ -114,13 +115,26 @@ function load_assets( $attr, $content ) {
...
-});
-JS_END;
+
+			$init_calendly_widget_js = "Calendly.initInlineWidget({
+				url: '%s',
+				parentElement: document.getElementById('%s'),
+				inlineStyles: false,
+			});";
+
+			if ( $is_p2_site ) {
```
Comment (allilevine) [inline extensions/blocks/calendly/calendly.php:125]: To do: make the same changes for the Eventbrite block.

Comment (pablinos) [reply extensions/blocks/calendly/calendly.php:125]: If this needs to be done for Eventbrite (and presumably Opentable as well as other embed blocks) should we abstract this pattern to a function? Maybe in Jetpack Gutenberg? We could add the `is_p2_site` check to one of the site helper libs too, so it could be used like `is_atomic`

**Review by pablinos — COMMENTED** [review]
This works for me, but for some reason, I couldn't insert a Calendly block using the front-end editor. Is there another place where it's blocked? 

I could insert one using the Calypso/wp-admin editor and it rendered correctly on the front end. There's [some annoying UX related to the button style](https://github.com/Automattic/jetpack/issues/17129) which I think is unrelated.

I also checked some other test sites and I could still insert and use a Calendly block, so it's looking good!

File: extensions/blocks/calendly/calendly.php [hunk 3]
```diff
@@ -114,13 +115,26 @@ function load_assets( $attr, $content ) {
...
+				// For P2s only: wait until after o2 has
+				// replaced main#content to initialize widget.
+				$script = <<<JS_END
+jQuery('body').on( 'ready.o2', function( event, domRef ) {
```
Comment (jeherve) [inline extensions/blocks/calendly/calendly.php:129]: `jetpack-calendly-external-js` doesn't rely on jQuery, so it may be best to try to use vanilla JS here if possible.

File: extensions/blocks/calendly/calendly.php (hunk 1 above)
Comment (jeherve) [inline extensions/blocks/calendly/calendly.php:67]: If P2 is eventually available on self-hosted sites, it may be best not to gate things to WordPress.com. Could we limit it to only checking for P2, or to not gate at all, and look for a specific dom element in the existing Calendly JS?

**Comment by allilevine** [comment]
> This works for me, but for some reason, I couldn't insert a Calendly block using the front-end editor. Is there another place where it's blocked?

There is, thanks for catching this! Commenting out wp-content/plugins/p2tenberg-wpcom/p2tenberg-wpcom.php line 157 allowed me to insert a Calendly block using the front-end editor too.

File: extensions/blocks/calendly/calendly.php [hunk 4]
```diff
@@ -115,11 +115,25 @@ function load_assets( $attr, $content ) {
...
 			);
 			$script  = <<<JS_END
-Calendly.initInlineWidget({
-	url: '%s',
-	parentElement: document.getElementById('%s'),
-	inlineStyles: false,
-});
+// Initialize function as an array object
+// to allow for multiple widgets.
+var jetpackInitCalendly = [
```
Comment (allilevine) [inline extensions/blocks/calendly/calendly.php:120]: I tried using the unique `$block_id` to assign each function to a unique object key, but that got complicated, especially if we wanted to escape it. Alternatively we could print out the `Calendly.initInlineWidget` call twice, instead of assigning it to a function. But then we'd need to double the inserted strings in `sprintf...`.

File: extensions/blocks/calendly/calendly.php (hunk 2 above)
Comment (allilevine) [reply extensions/blocks/calendly/calendly.php]: > If this needs to be done for Eventbrite (and presumably Opentable as well as other embed blocks) should we abstract this pattern to a function? Maybe in Jetpack Gutenberg? We could add the `is_p2_site` check to one of the site helper libs too, so it could be used like `is_atomic`

🤔 I moved this logic into the inline script. It could still be abstracted to a separate script, but that would mean having to import it and adding complexity.

File: extensions/blocks/calendly/calendly.php (hunk 3 above)
Comment (allilevine) [reply extensions/blocks/calendly/calendly.php]: > `jetpack-calendly-external-js` doesn't rely on jQuery, so it may be best to try to use vanilla JS here if possible.

Unfortunately, o2 events are not visible to native DOM handlers. ☹️ jQuery is a dependency of o2, and will always be available if o2 is active.

File: extensions/blocks/calendly/calendly.php (hunk 1 above)
Comment (allilevine) [reply extensions/blocks/calendly/calendly.php]: > If P2 is eventually available on self-hosted sites, it may be best not to gate things to WordPress.com. Could we limit it to only checking for P2, or to not gate at all, and look for a specific dom element in the existing Calendly JS?

Thanks for pointing this out, I've been a bit confused about the future of P2. I changed the logic to check for jQuery and o2 instead of gating.

File: extensions/blocks/calendly/calendly.php [hunk 5]
```diff
@@ -88,41 +89,54 @@ function load_assets( $attr, $content ) {
...
 				'<div class="%1$s" id="%2$s"><a href="%3$s" role="button" target="_blank">%4$s</a></div>',
 				esc_attr( Blocks::classes( FEATURE_NAME, $attr ) ),
-				esc_attr( $block_id ),
+				esc_attr( $html_id ),
 				esc_js( $url ),
 				wp_kses_post( get_attribute( $attr, 'submitButtonText' ) )
 			);
 		} else {
-			$content = sprintf(
+			$content          = sprintf(
```
Comment (retrofox) [inline extensions/blocks/calendly/calendly.php:114]: Does it seem to be added by mistake?

File: extensions/blocks/calendly/calendly.php [hunk 6]
```diff
@@ -88,41 +89,54 @@ function load_assets( $attr, $content ) {
...
+// to allow for multiple widgets.
+function jetpackInitCalendly{$escaped_block_id}() {
+	Calendly.initInlineWidget({
+		url: '%s',
+		parentElement: document.getElementById('%s'),
+		inlineStyles: false,
+	});
+};
+// For P2s only: wait until after o2 has
+// replaced main#content to initialize widget.
```
Comment (retrofox) [inline extensions/blocks/calendly/calendly.php:131]: Minor suggestion. We should use the [multiline format](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#5-2-multi-line-comments) defined by WordPress core - PHP documentation standards.

```suggestion
/*
 * For P2s only: wait until after o2 has
 * replaced `main#content` to initialize widget.
 */
```

File: extensions/blocks/calendly/calendly.php [hunk 7]
```diff
@@ -88,41 +89,54 @@ function load_assets( $attr, $content ) {
...
-			$script  = <<<JS_END
-Calendly.initInlineWidget({
-	url: '%s',
-	parentElement: document.getElementById('%s'),
-	inlineStyles: false,
-});
+			$escaped_block_id = esc_js( $block_id );
+			$script           = <<<JS_END
+// Call function with block id in name
+// to allow for multiple widgets.
```
Comment (retrofox) [inline extensions/blocks/calendly/calendly.php:122]: Similar suggestion [here]( https://github.com/Automattic/jetpack/pull/17120/files#r500550298).

File: extensions/blocks/calendly/calendly.php (hunk 6 above)
Comment (retrofox) [reply extensions/blocks/calendly/calendly.php:131]: Just realized that it's the javascript code, generated in the dynamically in the backend. Feel free to ignore these comments.

File: extensions/blocks/calendly/calendly.php [hunk 8]
```diff
@@ -63,7 +63,8 @@ function load_assets( $attr, $content ) {
 	$text_color              = get_attribute( $attr, 'textColor' );
 	$primary_color           = get_attribute( $attr, 'primaryColor' );
 	$classes                 = Blocks::classes( FEATURE_NAME, $attr, array( 'calendly-style-' . $style ) );
-	$block_id                = wp_unique_id( 'calendly-block-' );
+	$block_id                = wp_unique_id();
+	$html_id                 = 'calendly-block-' . $block_id;
```
Comment (retrofox) [inline extensions/blocks/calendly/calendly.php:67]: A minor one. Not sure about this var name since it seems to be kind of ambiguous?
Maybe something like `calendly_html_attr_id` or just `calendly_attr_id`? Please feel free to ignore it, too.

File: extensions/blocks/calendly/calendly.php (hunk 3 above)
Comment (retrofox) [reply extensions/blocks/calendly/calendly.php]: I think now it's properly handled, considering that

* `o2` depends totally on jQuery
* it checks whether both window propertties are defined:

```js
if( window.jQuery && window.o2 ) {
  // ...
}
```

File: extensions/blocks/calendly/calendly.php [hunk 9]
```diff
@@ -88,41 +89,54 @@ function load_assets( $attr, $content ) {
...
-Calendly.initInlineWidget({
-	url: '%s',
-	parentElement: document.getElementById('%s'),
-	inlineStyles: false,
-});
+			$escaped_block_id = esc_js( $block_id );
+			$script           = <<<JS_END
+// Call function with block id in name
+// to allow for multiple widgets.
+function jetpackInitCalendly{$escaped_block_id}() {
```
Comment (retrofox) [inline extensions/blocks/calendly/calendly.php:123]: It doesn't look good to me creating a new function for each Calendly instance. I've just tested creating only one `jetpackInitCalendly()` function, and pass the `url` and the `id` attributes as parameters of it, in the javascript context. 
Do you think it worths it? I can push my changes if you agree.

Comment (allilevine) [reply extensions/blocks/calendly/calendly.php:123]: > It doesn't look good to me creating a new function for each Calendly instance. I've just tested creating only one `jetpackInitCalendly()` function, and pass the `url` and the `id` attributes as parameters of it, in the javascript context.
> Do you think it worths it? I can push my changes if you agree.

Sure, sounds good! 🙌 The goal was to allow for separate Calendly blocks with separate functions, but if you've found a way to do that with parameters that would be awesome.

Comment (retrofox) [reply extensions/blocks/calendly/calendly.php]: Handled here 59dd7cd, Allison.
**before**

image


**after**

image

Comment (pablinos) [reply extensions/blocks/calendly/calendly.php]: Could we put that `window.jQuery && window.o2` check in the `jetpackInitCalendly` function? It seems like that would get rid of some repeated code.

Comment (retrofox) [reply extensions/blocks/calendly/calendly.php]: I think it's even nicer.

* Always call the `jetpackInitCalendly()`, passing the proper parameters
* if jQuery & o2 are defined, subscribe to the `o2.ready` event
* If not, just call the init Calendly widget method.

Comment (allilevine) [reply extensions/blocks/calendly/calendly.php]: > Could we put that `window.jQuery && window.o2` check in the `jetpackInitCalendly` function? It seems like that would get rid of some more repeated code.

> 
> Always call the jetpackInitCalendly(), passing the proper parameters
> if jQuery & o2 are defined, subscribe to the o2.ready event
> If not, just call the init Calendly widget method.

Thanks! 🙌 I made the change. Let me know if you see any ways to streamline it further. 😄

Comment (retrofox) [reply extensions/blocks/calendly/calendly.php]: I'm afraid the last change breaks the rendering process, Allison. All blicks are rendered at the bottom, in the front-end.

image

**Review by retrofox — CHANGES_REQUESTED** [review]
Going to request changes, Allison. [Here](https://github.com/Automattic/jetpack/pull/17120#discussion_r501969834) more context.

**Review by retrofox — APPROVED** [review]
Tested with Regular and P2 sites. It works as expected.
It checks to either jQuery as well as o2 presence making the approach safer.
Nice improvement in reducing the generated code too.

**before**
P2 (widgets are wrongly rendered at the bottom of the page)
image


image


**after**

P2 site. Widgets are properly rendered.
image

**Handler function**
image

**Comment by jeherve** [comment]
r215130-wpcom
