### PR TITLE
External Media: don't show duplicate buttons for post thumbnails

### LINKED ISSUE #19555: Editor Settings: remove duplicate "Replace Image" button when editing the Featured Image
#### Steps to reproduce the issue

1. On a WordPress.com site (simple or atomic), create a new post
2. Open the settings sidebar (by clicking the cog icon in the top right of the editor)
3. Select the "Post" tab and scroll to the "Featured Image" section
4. Notice the "Select Image" button. When clicking this button, a dropdown appears showing media source selection.
4. Add a Featured Image
5. One the image has uploaded, notice the buttons UI: "Replace Image", "Select Image", "Remove featured image"

#### What I expected

When a featured image is selected:

- [ ] The original "Replace Image" button (coming from core gutenberg) should not be visible
- [ ] The "Select Image" button (from Jetpack plugin) should be visible, but its label text should say "Replace Image"
- [ ] There should be some vertical space before the "Remove featured image" link/button

#### What happened instead

The "Replace Image" button (from core Gutenberg) and the "Select Image" button are both shown to the user, and there are some misalignments in the buttons UI

**Screenshots**

image

#### Context

This issue was part of a larger exploration (see [this GitHub issue](https://github.com/Automattic/wp-calypso/issues/51943#issuecomment-819499234)) about the discrepancies between .org and .com sites when editing a post's featured image.

A good starting point when working on this issue is: https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/extensions/shared/external-media/index.js#L53-L60

### PR DESCRIPTION
**Pull request by mattwiebe**
Previously, our "Select Image" button would still show alongside Core's "Replace Image" button. Now, Cores' button is not shown, and our button shows as "Replace Image" when an image has been selected.

Fixes #19555

#### Changes proposed in this Pull Request:

* Post Thumbnail UI should no longer show duplicate buttons, and buttons shown are appropriate

#### Jetpack product discussion
* n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* apply soon-to-be-generated Diff to your WPCom sandbox
* Open an existing post (or create a new one)
* Open the "Featured Image" section in the Post sidebar
* No featured image selected should look like: 
 Screen Shot 2021-04-23 at 15 46 43
* With a selected featured image: 
Screen Shot 2021-04-23 at 15 44 55

Note that we use the Media Button in several locations throughout Gutenberg. These modifications should be isolated to featured image usage, but smoke testing other image-based blocks/settings since I can't find any tests for this.

### CODE REVIEW

**Comment by creativecoder** [comment]
@mattwiebe I pushed a change in https://github.com/Automattic/jetpack/pull/19644/commits/a327880a0b0dd85a693275890516394525aa1928 (feel free to discard if you don't agree).

It didn't seem necessary to add a button when there's no featured image set, so I turned the component into the dropdown trigger

image

**Comment by creativecoder** [comment]
Found an annoying issue I though we should fix, while we're at it: the media sources dropdown pops back open after you select an external media item. https://github.com/Automattic/jetpack/pull/19644/commits/78b57b53b272485f326e67ce7173deac9ed815d9 fixes this by closing the dropdown menu when an item is clicked.

**Review by creativecoder — DISMISSED** [review]
This is working as expected for me:

The featured image sidebar controls are now unchanged by the external media extension:

| Without Jetpack | With Jetpack |
| - | - |
| Screen Shot 2021-04-27 at 17 15 28 | Screen Shot 2021-04-27 at 17 15 50 |
|  Screen Shot 2021-04-27 at 17 15 02 | Screen Shot 2021-04-27 at 17 15 39 |

I spot checked the Media and Media & Text blocks and did not see any regressions.

File: projects/plugins/jetpack/extensions/shared/external-media/media-button/media-menu.js [hunk 1]
```diff
@@ -11,12 +11,11 @@ import { media } from '@wordpress/icons';
...
-	const { mediaProps, open, setSelectedSource, isFeatured, isReplace } = props;
+	const { mediaProps, open, setSelectedSource, isFeatured, isReplace, hasImage } = props;
 	const originalComponent = mediaProps.render;
-
-	if ( isFeatured && mediaProps.value === undefined ) {
-		return originalComponent( { open } );
-	}
+	let isPrimary = isFeatured;
+	let isTertiary = ! isFeatured;
+	const extraProps = {};
```
Comment (creativecoder) [inline projects/plugins/jetpack/extensions/shared/external-media/media-button/media-menu.js:18]: Nitpick: maybe this should just be `let isSecondary = false;`? I'm not sure I see an advantage to using an object here (unless all the `is*` props here are added to it)

Comment (mattwiebe) [reply projects/plugins/jetpack/extensions/shared/external-media/media-button/media-menu.js:18]: I enjoy nitpicks, and I would overall prefer that, too.

My reasoning is that I was trying to keep the surface area of changes as limited as possible, given the broad and varied use of media buttons throughout different parts of the Gutenberg UI. I wasn't confident that always adding the `isSecondary` prop (even set to `false` in all non-featured image uses) wouldn't disrupt those other uses.

Now, with a bit more distance, I can see that it will be fine. The prop is `false` by default in the Button component and will be in all situations save the "Replace Image" use here. I'll update it that way.

**Comment by mattwiebe** [comment]
@creativecoder Thanks for the review and improving the PR to boot! I took your nitpick above and appreciate it.

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Review by kraftbj — APPROVED** [review]

**Review by creativecoder — APPROVED** [review]
Confirming this still works after rebase, testing external media extension:

- Featured image adding and removing
- Image block, including replace image flow
- Media and Text block
