### PR TITLE
Subscribe Block: ensure custom button spacing is correct

### LINKED ISSUE #28037: Subscribe Block: Button has broken styling if "Place button on new line" is set
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Insert a Subscribe block
2. In Settings, set the "Place button on new line" toggle to true
3. The form in the editor looks correct
4. View the form on the front end, and notice how the button styling is broken:

image

The style tag comes through as the following: `width: calc(100%spx;font-size: 16px;padding: 15px 23px 15px 23px;margin-top: 10px;border-radius: 0px;border-width: 1px;`

It looks like the `width` property has not been calculated correctly, and it's running into the other styles.

Here is some example markup:

```
<!-- wp:jetpack/subscriptions {"subscribePlaceholder":"Email Address","buttonOnNewLine":true,"buttonWidth":"100%","submitButtonText":"Subscribe","buttonBackgroundColor":"black","customTextColor":"#ffe030","fontSize":"1.75rem","customFontSize":"1.75rem","borderRadius":50,"borderWeight":1,"borderColor":"black","padding":24,"spacing":15,"className":"is-style-split"} /-->
```

### A clear and concise description of what you expected to happen.

I expect the form to display the same on the front end as in the editor.

### What actually happened

The styles seem broken on the front end of the button.

### Browser

Google Chrome/Chromium

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #28037

#### Changes proposed in this Pull Request:

This is a follow-up to #26947.

Let's make sure the "100%" do not get in the way of our sprintf replacements.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?
* No

#### Testing instructions:

* Start with a site connected to WordPress.com with the Subscriptions module active.
* Go to Posts > Add New
* Switch to the Code editor

Screenshot 2022-12-22 at 12 57 07

* Paste the following: 
```
<!-- wp:jetpack/subscriptions {"subscribePlaceholder":"Email Address","buttonOnNewLine":true,"buttonWidth":"100%","submitButtonText":"Subscribe","buttonBackgroundColor":"black","customTextColor":"#ffe030","fontSize":"1.75rem","customFontSize":"1.75rem","borderRadius":50,"borderWeight":1,"borderColor":"black","padding":24,"spacing":15,"className":"is-style-split"} /-->
```
* Ensure the block's button is properly displayed on the frontend.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 1]
```diff
@@ -286,7 +286,7 @@ function get_element_styles_from_attributes( $attributes ) {
 
 		// Account for custom margins on inline forms.
 		$submit_button_styles .= true === get_attribute( $attributes, 'buttonOnNewLine' )
-			? sprintf( 'width: calc(100% - %spx;', get_attribute( $attributes, 'spacing', DEFAULT_SPACING_VALUE ) )
+			? sprintf( 'width: calc(100%% - %dpx);', get_attribute( $attributes, 'spacing', DEFAULT_SPACING_VALUE ) )
```
Comment (coder-karen) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:289]: Good catch. Should we actually have another case for buttons with 100% width on their own? By deducting the spacing from the width the subscribe button isn't quite full width which looks a little odd on my test site (on the front-end):

Screen Shot 2022-12-22 at 2 49 53 pm

Something like this:

```
		if (  get_attribute( $attributes, 'buttonWidth' ) === '100%' ) {
			$submit_button_styles .= 'width: 100%;';
		}
		else {
			// Account for custom margins on inline forms.
			$submit_button_styles .= true === get_attribute( $attributes, 'buttonOnNewLine' )
				? sprintf( 'width: calc(100%% - %dpx);', get_attribute( $attributes, 'spacing', DEFAULT_SPACING_VALUE ) )
				: 'width: 100%;'; 
		}
```

I'm not too sure why we deduct spacing from the width anyway (it seems to me it should just be the space between the email field and button in this case) so I may be misunderstanding the original code.

What do you think about this?

Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:289]: Actually that's probably better for a follow-up instead of here since it isn't really related to the bug. I'll make sure this current fix gets in to the next release regardless.

**Review by coder-karen — APPROVED** [review]
Nice fix! I left a comment here - https://github.com/Automattic/jetpack/pull/28057#discussion_r1055621348 - but realized it shouldn't stop this going through.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:289]: That's a good question. I'm not sure what the best fix is. Maybe we should be changing the default spacing value to 0?

We can see about fixing this in a follow-up for sure. 👍

Comment (iamtakashi) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:289]: @coder-karen @jeherve Hi! where is this follow up happening? @obenland let me know that some of our patterns look broken because of the not quite 100% width button. 

For example,
* https://dotcompatterns.wordpress.com/2022/10/11/bold-newsletter-signup/
* https://dotcompatterns.wordpress.com/2022/10/11/newsletter-signup-with-media-on-the-left/

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:289]: @iamtakashi We didn't create any other PR as we weren't sure about the best approach to take. Do you have any opinion on the above?
