### PR TITLE
Search: Hide "filters" menu on mobile if there are no filters to display

### LINKED ISSUE #18989: Jetpack Search: "filters" menu is shown on mobile even if there are no filters to display
#### Steps to reproduce the issue

1. Go to a site with Jetpack Instant Search enabled and no filters set up
2. Perform a search on a mobile screen width

#### What I expected
If there are no filters, the filters menu should be hidden.

#### What happened instead
The filters menu was shown but was empty.

**Screenshots**

Screen Shot 2021-03-03 at 14 52 26

Thanks to @gibrown for spotting this.

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #18989.

#### Changes proposed in this Pull Request

In Jetpack Instant Search, hide the "filters" menu on mobile breakpoints when no filters are defined. We currently show the menu even if it doesn't contain anything.

Screen Shot 2021-03-25 at 15 05 11

Implementation notes:

1. Added **hasNonSearchWidgets** to server object and frontend to consume it. There was not enough information from the server object,  which has only hasOverlayWidgets available, to determine whether there are other non-search widgets on the search sidebar. 

2. Fixed a typo to test whether an Array is empty. 

3. Changed the logic to show "Filters" when there are filter options configured or there are non-search widgets existing on the search sidebar

#### Jetpack product discussion
p1616361118002000-slack-jetpack-search-backstage

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
- Go to a site with Jetpack Instant Search enabled, add a search widget to the search sidebar with no filters set up
- Perform a search on a mobile screen width

1. Hide if no widgets in sidebar
    - Test passed if "Filters" menu is hidden

2. Show if there are non-search widgets
    - Add a category widget to Search widget
    - Test passed Filters if menu is shown regardless

3. Hide if no widgets configured
    - Remove all widgets from search sidebar
    - Test passed if "Filters" menu is hidden

### CODE REVIEW

File: projects/plugins/jetpack/changelog/fix-hide-filter-widget-on-empty [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: bugfix
+
+Search: fixed "filters" menu is shown on mobile even if there are no filters to display #18989
```
Comment (bluefuton) [inline projects/plugins/jetpack/changelog/fix-hide-filter-widget-on-empty:4]:
```suggestion
Search: hide "filters" menu on mobile if there are no filters to display
```

This is a user-facing changelog so we don't usually mention the Github PR number in it :)

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php [hunk 2]
```diff
@@ -191,6 +199,7 @@ protected function inject_javascript_options() {
 			'hasOverlayWidgets'     => count( $overlay_widget_ids ) > 0,
 			'widgets'               => array_values( $widgets ),
 			'widgetsOutsideOverlay' => array_values( $widgets_outside_overlay ),
+			'hasOtherWidgets'       => $has_other_widgets,
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:202]: When we say "other widgets", what counts as "normal" and what counts as "other"?

I wonder if there's a more descriptive name we can use (or if not, we could add some comments to explain what the "other widgets" includes).

**Review by bluefuton — COMMENTED** [review]
Testing instructions are great and the changes work well 🙂

Left some minor feedback about naming and changelog.

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php (hunk 2 above)
Comment (kangzj) [reply projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:202]: You are right. The name is a bit ambiguous. I'll give it a better name.

**Review by bluefuton — DISMISSED** [review]
New variable name is clearer, and I have committed the changelog fix. Looks good now! ✅

No filters:

Screen Shot 2021-03-25 at 15 04 29


With filters: 

Screen Shot 2021-03-25 at 15 05 11

**Review by jeherve — DISMISSED** [review]
This tests well for me. 👍

**Comment by kangzj** [comment]
rebased to resolve conflicts

**Comment by bluefuton** [comment]
@jeherve we've had to rebase - would you mind giving it the 🆗 again please? I've set the PR to auto-merge when you approve it 🙂

**Comment by bluefuton** [comment]
🚢 Deployed in r223393-wpcom.

**Review by jeherve — APPROVED** [review]
