### PR TITLE
Contact Info & Map Widget: Remove Geocoding and add map to form

### LINKED ISSUE #10355: Contact Info/Map Widget: Better Error Messaging
## Summary
On **self-hosted sites** (doesn't seem to impact WPcom `*`) the Contact Info/Map widget is not accepting **any** address. This includes the default address shipped with the plugin:

Image Link: http://cld.wthms.co/z2lJQW
 
Tested using an **unrestricted** API key with access to the _Maps Embed API:_

Image Link: http://cld.wthms.co/2xRH1O

**NOTE:** Since I'm posting this in the public repo, I've regenerated both API keys. They're no longer valid.

Bug replicated across different platforms:

- Pressable
- Atomic
- Self-hosted (Google Cloud Platform)
- A user's site

Unclear if this has an impact on _existing_ widgets that already saved the address. Didn't have any to check on. 

`*` **WPcom-specific stuff; check here, there's another oddity:**

- p1539903252000100-slack-jpop-support

Internal ref:
1494815-zen

### LINKED ISSUE #12913: Contact Info Widget: PHP Notice on adding to footer
#### Steps to reproduce the issue

1. Go to `/wp-admin/widgets.php`
2. Add a contact info widget to the footer
3. See notices in debug.log

```
[01-Jul-2019 17:41:54 UTC] PHP Notice:  Undefined offset: 0 in /home4/lrmyrnmy/public_html/jptest/wp-content/plugins/jetpack/modules/widgets/contact-info.php on line 217
[01-Jul-2019 17:41:54 UTC] PHP Notice:  Trying to get property of non-object in /home4/lrmyrnmy/public_html/jptest/wp-content/plugins/jetpack/modules/widgets/contact-info.php on line 217
[01-Jul-2019 17:41:54 UTC] PHP Notice:  Trying to get property of non-object in /home4/lrmyrnmy/public_html/jptest/wp-content/plugins/jetpack/modules/widgets/contact-info.php on line 217
[01-Jul-2019 17:41:54 UTC] PHP Notice:  Trying to get property of non-object in /home4/lrmyrnmy/public_html/jptest/wp-content/plugins/jetpack/modules/widgets/contact-info.php on line 219
[01-Jul-2019 17:41:54 UTC] PHP Notice:  Trying to get property of non-object in /home4/lrmyrnmy/public_html/jptest/wp-content/plugins/jetpack/modules/widgets/contact-info.php on line 220

```

### PR DESCRIPTION
**Pull request by kbrown9**
Fixes #10355
Fixes #12925 
Fixes #12913 

#### Changes proposed in this Pull Request:
* Remove the use of the Google Maps Geocoding API. The Geocoding API is only used to verify that the address is valid. After these changes are made, users will need to enable only one Google Maps API (Maps Embed API).

* Add the Google Maps embedded map to the widget's admin form. This change will allow users to view the maps that will be shown on their site in the admin form. The users will be able to verify that the maps are correct and receive a useful error if the API key is invalid.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* This change adds a feature to the existing Contact Info & Map widget.

#### Testing instructions:
1) Add a new Contact Info & Maps widget (Appearance -> Widgets -> Contact Info & Map), or access an existing Contact Info & Maps widget.

2) Check the Show Map checkbox to show the API key box and the embedded map.

3) The embedded map iframe will show this error when an API key is not entered:
     > Google Maps Platform rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account

4) Enter an invalid API key. The embedded map iframe will show this error when an invalid API key is entered:
     > Google Maps Platform rejected your request. The provided API key is invalid.

5) Enter a valid Google Maps API key. (The Embed Maps API must be enabled for the API key.) Save the widget, and the embedded map will be shown in the admin form.

#### Proposed changelog entry for your changes:
Contact Info Widget: Remove use of the Geocoding API and add an embedded map to the admin form

### CODE REVIEW

**Comment by kbrown9** [comment]
I just noticed that the Customize page will show inconsistent maps when an address is changed. The preview page will show the map for the new address. However, the map in the widget's admin form doesn't update, so it shows the map for the old address. 

I'll try to think of a solution for this.

**Comment by kbrown9** [comment]
Following-up on my last comment - I addressed the issue with inconsistent maps on the Customizer page in the latest commit. In this commit, the embedded map is not displayed in the widget admin form on the Customizer page. Since the Customizer preview displays the embedded map, it's not necessary to display the map in the widget admin form. 

I used the `is_customize_preview()` function ([code reference](https://developer.wordpress.org/reference/functions/is_customize_preview/)) to detect whether the widget admin form is being displayed on the Customizer page.

**Review by jeherve — CHANGES_REQUESTED** [review]
Excellent work! I'd like to suggest a few changes, and to make things easier I've just submitted this PR to your branch:
https://github.com/kbrown9/jetpack/pull/1

If you are happy with those changes, you can merge the PR and my changes will be automatically added to your PR here.

Beyond those changes, I think we should take that opportunity to better display error messages in the customizer when something is wrong. 
Those could be displayed in the widget settings directly, just like on the old settings screen. They could also be displayed in the widget preview directly, since that's where site owners will check what the map will look like.

Let me know what you think.

**Comment by kbrown9** [comment]
> 
> 
> Excellent work! I'd like to suggest a few changes, and to make things easier I've just submitted this PR to your branch:
> [kbrown9#1](https://github.com/kbrown9/jetpack/pull/1)
> 
> If you are happy with those changes, you can merge the PR and my changes will be automatically added to your PR here.
> 
> Beyond those changes, I think we should take that opportunity to better display error messages in the customizer when something is wrong.
> Those could be displayed in the widget settings directly, just like on the old settings screen. They could also be displayed in the widget preview directly, since that's where site owners will check what the map will look like.
> 
> Let me know what you think.

Thank you for this review! I think all of these changes look great.

I'll work on displaying the error message in the customizer!

**Comment by jeherve** [comment]
@kbrown9 Is this ready for another review?

**Comment by kbrown9** [comment]
> 
> 
> @kbrown9 Is this ready for another review?

Yes, it's ready now! I just pushed my last commit. So, I've added three new commits on top of your changes:

commit [7f4b2e09](https://github.com/Automattic/jetpack/pull/12474/commits/7f4b2e09a0be61cd61344dcb2bbe29627438fa1b): This commit includes changes that I think improve readability.

commit [43cb2133](https://github.com/Automattic/jetpack/pull/12474/commits/43cb2133c55ed71d9240c317eec4fe5b63b070b8): This commit displays API key errors in the Contact Info widgets on the Customizer preview page.

commit [15910c91](https://github.com/Automattic/jetpack/pull/12474/commits/15910c911c7495a99dd587b6ee89ee1f71724cbd): This commit displays API key errors in the Contact Info admin forms on the Customizer preview page.

Please let me know if you'd prefer a different approach for these error messages!

Finally, what's the workflow for handling the commits that are improvements to previous commits? After the review is complete, should the commits be squashed together?

**Comment by jeherve** [comment]
> Yes, it's ready now!

Excellent, I'll take a look when I can.

> what's the workflow for handling the commits that are improvements to previous commits? After the review is complete, should the commits be squashed together?

Don't worry about it :) I'll squash all the commits when I merge to `master`.

**Review by jeherve — CHANGES_REQUESTED** [review]
It looks like Unit Tests are failing right now:

```
modules/widgets/contact-info/contact-info-admin.js
  line 23  col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 29  col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 30  col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
  line 25  col 17  'ajaxurl' is not defined.
  ⚠  4 warnings
```

The first 3 warnings are an annoying consequence of us still using jshint (see #11915), but I'm afraid we won't be able to merge as long as the tests are failing.

**Comment by kbrown9** [comment]
> 
> 
> It looks like Unit Tests are failing right now:
> 
> ```
> modules/widgets/contact-info/contact-info-admin.js
>   line 23  col 9   'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
>   line 29  col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
>   line 30  col 13  'const' is available in ES6 (use 'esversion: 6') or Mozilla JS extensions (use moz).
>   line 25  col 17  'ajaxurl' is not defined.
>   ⚠  4 warnings
> ```
> 
> The first 3 warnings are an annoying consequence of us still using jshint (see #11915), but I'm afraid we won't be able to merge as long as the tests are failing.

Thanks for the info! I'll get these fixed up.

**Comment by kbrown9** [comment]
@jeherve - I amended the commit that caused the jshint test failures. The commit passes the tests now!

**Review by jeherve — DISMISSED** [review]
I rebased to fix the last linting errors now that we got rid of jshint. It tests well, and I think this would be ready to merge. 

Leaving it to another Crew member to do a final review on this, and then we can merge!

**Review by brbrr — DISMISSED** [review]
It works well in my tests. Thank you!

I noticed a few minor issues, but I don't think they should block merging of this one:

- Empty "warning" formatting is shown once "Show map" is checked (in both custumizer & `wp-admin/widgets.php`)
Widgets ‹ HelloWord — WordPress 2019-07-26 11-59-22
 
- Map width is way bigger than widget box in `wp-admin/widgets.php`
Widgets ‹ HelloWord — WordPress 2019-07-26 12-07-12

**Comment by jeherve** [comment]
@brbrr I just pushed some changes that should solve those issues; do you think you could test again when you get the chance?

File: modules/widgets/contact-info.php [hunk 1]
```diff
@@ -379,16 +349,85 @@ function urlencode_address( $address ) {
...
+
+			return __( 'Please enter a valid Google API Key.', 'jetpack' );
+		}
+
+		/**
+		 * Check the Google Maps API key after an Ajax call from the widget's admin form in
+		 * the Customizer preview.
+		 */
+		function ajax_check_api_key() {
+			if ( isset( $_POST['apikey'] ) ) {
```
Comment (jeherve) [inline modules/widgets/contact-info.php]: Coming back to this, I think we should create a nonce, use it with our requests, check against them with `check_ajax_referer`, and check for `current_user_can( 'customize' )` as well.

If we don't protect access to those requests, we'll run the risk of having non logged-in users making requests instead of the admin.

**Review by jeherve — CHANGES_REQUESTED** [review]
I think we'll need to review the requests we make and make sure they are well protected and can't be abused by non-logged in users.

File: modules/widgets/contact-info.php (hunk 1 above)
Comment (kbrown9) [reply modules/widgets/contact-info.php]: Good point. I'll add these checks.

**Review by jeherve — DISMISSED** [review]
Everything seems to work well for me now. 🚢 👍

**Comment by mdawaffe** [comment]
I still see the too-wide map sometimes:

1. Add the widget.
2. Enter an invalid API key.
3. Save.
4. Do a full page refresh.
5. Enter a valid API key.
6. Save.
7. See the too-wide map.

Screen Shot 2019-08-15 at 4 08 57 PM

**Comment by kbrown9** [comment]
> I still see the too-wide map sometimes:
> 

Thanks - I was able to reproduce the too-wide map with your instructions. I'll look into this.

**Comment by kbrown9** [comment]
Commit c8544a7 fixes the too-wide map problem by using the `admin_enqueue_scripts` hook to enqueue the stylesheet on widgets.php.

**Comment by mdawaffe** [comment]
Nice! @kbrown9, could you please rebase this PR on top of the latest master? That will get those failing Travis CI tests to pass.

**Review by jeherve — APPROVED** [review]
