### PR TITLE
Social: Fix register_settings namespace php error

### LINKED ISSUE #34627: Critical error when using jetpack/13.0-a.1
### Impacted plugin

Jetpack

### Quick summary

Jetpack was automatically updated and when the user deactivated Classic Editor plugin, the critical error appeared on the site.

We found a temporary workaround by changing the PHP version to 7.4. 

### Steps to reproduce

1. Jetpack was automatically updated to 13.0-a.1
2. When the user deactivated the Classic Editor plugin, a critical error appeared on the site.
3. To see the error, we had to go to the pages and click on editing a page
4. Screenshot 2023-12-13 at 9 46 46 AM

### A clear and concise description of what you expected to happen.

Be able to edit the page without the error appearing. 

### What actually happened

We don't have access to edit the page. 

### Impact

One

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes
CLI error: 
```
[13-Dec-2023 17:48:19 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /wordpress/plugins/jetpack/13.0-a.1/jetpack_vendor/automattic/jetpack-publicize/src/jetpack-social-settings/class-settings.php:155
Stack trace:
#0 /wordpress/plugins/jetpack/13.0-a.1/class.jetpack-gutenberg.php(743): Automattic\Jetpack\Publicize\Jetpack_Social_Settings\Settings->get_settings(true)
#1 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(324): Jetpack_Gutenberg::enqueue_block_editor_assets('')
#2 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#3 /wordpress/core/6.4.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#4 /wordpress/core/6.4.2/wp-includes/script-loader.php(2446): do_action('enqueue_block_a...')
#5 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(324): wp_common_block_scripts_and_styles('post.php')
#6 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.4.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/core/6.4.2/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'post.php')
#9 /wordpress/core/6.4.2/wp-admin/edit-form-blocks.php(309): require_once('/wordpress/core...')
#10 /wordpress/core/6.4.2/wp-admin/post.php(187): require('/wordpress/core...')
#11 {main}
  thrown in /wordpress/plugins/jetpack/13.0-a.1/jetpack_vendor/automattic/jetpack-publicize/src/jetpack-social-settings/class-settings.php on line 155
```

### PR DESCRIPTION
**Pull request by gmjuhasz**
With the Social store refactor we introduced new registered settings, where to be able to use core API endpoints. That change caused some issues on Atomic sites, this change fixes that.

With a lot of debugging @pablinos found out that the namespace of the settings was set to `general` which is a problem in this case, as any change on `wp-admin/options-general.php` will set our `jetpack_social_autoconvert_images` option to an empty string.

## Proposed changes:

* Updated the namespace of the options
* Fixed a possible bug where the type was set incorrectly
* Added a guard clause so the currently messed up options get restored to the defaults

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #34627
## Does this pull request change what data or activity we track or use?

No.
## Testing instructions:

* On trunk Go to your local site on `wp-admin/options-general.php` and click on Save. It should set the option to empty string. Loading the editor will cause the issue.
* Apply this patch. Loading the editor should be fine, as the option should get reset to the defaults.
* Do the first step again on this branch, and confirm that it still works

### CODE REVIEW

File: projects/packages/publicize/src/jetpack-social-settings/class-settings.php [hunk 1]
```diff
@@ -46,15 +46,26 @@ class Settings {
...
+		// Migrating from the old option.
+		$old_auto_conversion_settings = get_option( 'jetpack_social_settings' );
+		if ( ! empty( $old_auto_conversion_settings ) ) {
+			update_option( self::OPTION_PREFIX . self::AUTOCONVERT_IMAGES, array( 'enabled' => ! empty( $old_auto_conversion_settings['image'] ) ) );
 			delete_option( 'jetpack_social_settings' );
 		}
+		// Checking if the new option is valid.
+		$auto_conversion_settings = get_option( self::OPTION_PREFIX . self::AUTOCONVERT_IMAGES );
+		if ( ! is_array( $auto_conversion_settings ) || ! isset( $auto_conversion_settings['enabled'] ) ) {
+			update_option( self::OPTION_PREFIX . self::AUTOCONVERT_IMAGES, self::DEFAULT_AUTOCONVERT_IMAGES_SETTINGS );
```
Comment (pablinos) [inline projects/packages/publicize/src/jetpack-social-settings/class-settings.php]: Should we actually delete it instead? We'll start using the defaults everywhere and it stops anyone that has the option set from this bug having it stored in their database.

Comment (gmjuhasz) [reply projects/packages/publicize/src/jetpack-social-settings/class-settings.php]: Good idea, I'll move to that

**Review by pablinos — APPROVED** [review]
This works well for me! It also fixes things if the corrupted option is found.

**Review by spsiddarthan — APPROVED** [review]
