### PR TITLE
Fix forms input placeholder displaying when its value is "0"

### LINKED ISSUE #41725: Forms: if placeholder is set to 0 then it doesn't render as expected
### Impacted plugin

Jetpack

### Quick summary

If you add the placeholder as 0 to a text field it doesn't render as expected. Since when we are checking and applying classes we assume that the value is "empty". 

### Steps to reproduce

On a page add the form block. Add the placeholder of "0". 

Notice that the form has the animated style. The placeholder is displayed under the label. 

See

Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

Individual site owner revenue

### If a workaround is available, please outline it here.

Instead of using 0. the user can type 0.00

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### PR DESCRIPTION
**Pull request by tellthemachines**
Fixes #41725

## Proposed changes:

* If an input placeholder has any value at all in it, it should display. This changes the check from `empty()` to explicitly check if the string value is empty instead.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Add a contact form to a post or page.
* Set the placeholder on one of the inputs to "0".
* Save and check that the value "0" displays on the front end.

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 1]
```diff
@@ -1066,14 +1066,14 @@ public function render_field( $type, $id, $label, $value, $class, $placeholder,
 
 		$form_style = $this->get_form_style();
 		if ( ! empty( $form_style ) && $form_style !== 'default' ) {
-			if ( empty( $placeholder ) ) {
+			if ( '' === $placeholder ) {
```
Comment (andrewserong) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php]: Tiny nit: I'm not very familiar with this code, but from the looks of it, it might be technically possible for `$placeholder` to be `null`.

I.e. it looks like the placeholder [is set here](https://github.com/Automattic/jetpack/blob/e0b2fdaf91f158a5f882a820a65da60b2bb62601/projects/packages/forms/src/contact-form/class-contact-form-field.php#L299), which gets retrieved from the shortcode via [get_attribute](https://github.com/Automattic/jetpack/blob/653476e520d896d175fe995e8f190d8403795a83/projects/packages/forms/src/contact-form/class-contact-form-shortcode.php#L103), which falls back to `null`.

In that case, would it be safer to check for `! isset( $placeholder ) || '' === $placeholder`? Though in practice, I haven't been able to break this in manual testing, so I might very well be overthinking it!

**Review by andrewserong — DISMISSED** [review]
Good catch, this is testing well for me! Supports a `0` placeholder now (tested with the Animated style of the form):

image

Just left a comment about potentially checking for `null` values just in case, but in practice I wasn't able to run into any issues with the current state of things.

LGTM!

File: projects/packages/forms/src/contact-form/class-contact-form-field.php (hunk 1 above)
Comment (tellthemachines) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php]: Oh good point, maybe it would be safer to do that. What I don't get is the reason for this condition, as it seems we're just adding a space to `$placeholder` if it's empty 🤔

Comment (tellthemachines) [reply projects/packages/forms/src/contact-form/class-contact-form-field.php]: Just confirmed and it's super weird that adding styles to the form to trigger that condition means any field without a placeholder suddenly acquires `placeholder=" "`:

Screenshot 2025-03-06 at 10 51 16 am

This feels like a mistake. CC @simison in case you have any context on this?
