### PR TITLE
Forms: Fix WordPress 6.8 useSelect notice

### LINKED ISSUE #42673: Forms: Fix WordPress 6.8 useSelect warning
### Impacted plugin

Jetpack

### Quick summary

WordPress 6.8 will start returning a console warning if a useSelect call manipulates retrieved data and returns a new object/array reference. The useSelect in the PluginIntegrationPanel is doing this, and should be fixed before WordPress 6.8 is released. 

See this issue: https://github.com/Automattic/jetpack/issues/42421
See this post: https://make.wordpress.org/core/2025/03/12/data-a-helpful-performance-warning-for-developers-in-the-useselect-hook/

### Steps to reproduce

1. Update WordPress to 6.8
2. Go to a page or post and add a form block
3. Open the Akismet panel in the block sidebar, which uses the PluginIntegrationPanel component

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### PR DESCRIPTION
**Pull request by edanzer**
Fixes #42673

## Proposed changes:

WordPress 6.8 will start returning a console warning if a useSelect call manipulates retrieved data to return a new object/array reference. The useSelect in the PluginIntegrationPanel is doing this, and should be fixed before WordPress 6.8 is released.

This PR fixes it by only returning the raw data from the useSelect call, and then handling filtering / manipulation outside of the useSelect.

For more context, see: 
- https://github.com/Automattic/jetpack/issues/42421
- https://make.wordpress.org/core/2025/03/12/data-a-helpful-performance-warning-for-developers-in-the-useselect-hook/

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

Review issue and code to confirm underlying issue is resolved. 

Test that the panel still works as expected.
- Deactivate or delete Akismet on your site if needed.
- Add a form block to a page or post. 
- In the form block sidebar, open the Akismet panel and install or activate Akismet. Confirm state updates once plugin is installed or activated.

### CODE REVIEW

File: projects/packages/forms/src/blocks/contact-form/components/shared/plugin-integration-panel/index.js [hunk 1]
```diff
@@ -25,26 +25,21 @@ const PluginIntegrationPanel = ( {
...
-		},
-		[ pluginPath ]
-	);
+	const { plugins, isLoading } = useSelect( select => {
+		const installedPlugins = select( coreStore ).getPlugins();
+		return {
+			isLoading: ! installedPlugins,
+			plugins: installedPlugins || [],
+		};
+	}, [] );
```
Comment (edanzer) [inline projects/packages/forms/src/blocks/contact-form/components/shared/plugin-integration-panel/index.js]: Main change in the useSelect above is that we're just returning installedPlugins - the raw data from the useSelect call - plus a simple boolean. In old code, we were filtering, manipulating, and returning a new object for pluginStatus. 

Now, we do the filtering and status check below this comment and outside of the useSelect.

**Review by simison — DISMISSED** [review]
Tests well and looks good, thanks for handling this!

**Review by coder-karen — CHANGES_REQUESTED** [review]
If I leave Akismet active on my site, the `useSelect` warning changes when simply adding a form to a post to reference non-equal value keys of `plugins`. I could replicate on a Jurassic Ninja site as well as locally - that's just by testing the changes in Jetpack (not using the Social plugin). The error component stack still references the `PluginIntegrationPanel` - the beginning of the stack is:
```
 Error Component Stack
    at PluginIntegrationPanel (index.js:12:2)
    at AkismetPanel (<anonymous>)
    at RegisterResetAll (block-editor.js?ver=edaac4395145c609e6ba:21955:3)
    at ToolsPanelInspectorControl (block-editor.js?ver=edaac4395145c609e6ba:21973:3)
```
I tried making a change, which removed the console warnings for me:
```
	const { plugin, isLoading } = useSelect(
		select => {
			const installedPlugins = select( coreStore ).getPlugins();

			if ( ! installedPlugins ) {
				return {
					isLoading: true,
					plugin: null,
				};
			}

			return {
				isLoading: false,
				plugin: installedPlugins.find( p => p.plugin === pluginPath ) || null,
			};
		},
		[ pluginPath ]
	);
```
The main change here: instead of returning an array that needs further processing, we return a single plugin object. When `installedPlugins` hasn't changed, the same plugin object reference is returned. But, I'm not sure if this is still the best approach within the context of the forms package, I just observed that it did resolve console warnings for me.

**Comment by edanzer** [comment]
@coder-karen - Thanks for the extra testing. Sorry to miss that. I tested your suggestion, which still had some issues, but after playing with the code a bit, I found a solution that both simplifies the code and resolves any errors. 

I do the manipulation in the in the useSelect call, but now return only the boolean values I actually need (isloading, isInstalled, isActive). This also simplified the available plugin states and allowed me remove one conditional return block that's no longer needed. 

You don't need to test the logic - I did that plenty. But feel free to confirm you can't generate that console warning now.

**Review by coder-karen — APPROVED** [review]
Oh yes, this tests well - no console warning now, and the changes make sense. Thanks!
