### PR TITLE
Publicize: fix refreshing social media connections

### LINKED ISSUE #21093: Publicize: refresh the connections list properly
The connections list is not refreshed properly when changing them from dotcom page. Let's figure out why it's happening and try to fix it.

* Start to create a new post
* Open the Jetpack sidebar
* Click on the `Connect an account` external link 

* Change the connections in the dotcom connections page

* Close the tab
* Confirm that the connection list doesn't get updated.
* Hard refresh
* Now, it should be updated.

**We'd like to see the connections list updated once the tab is closed**

### PR DESCRIPTION
**Pull request by retrofox**
### Branched off from https://github.com/Automattic/jetpack/pull/21090

This PR fixes the issue when the user changes the social media connections from the dotcom admin page. The issue is described [here](https://github.com/Automattic/jetpack/issues/21093), but in short, it doesn't refresh the connections list once the user edits them.

Fixes https://github.com/Automattic/jetpack/issues/21093 

### About the approach

It consumes the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API), through the [react-page-visibility](https://github.com/pgilad/react-page-visibility) React lib. It's pretty light and simplifies the implementation.

#### Changes proposed in this Pull Request:

* Publicize: fix refreshing social media connections

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Create a new post / Edit a post.
* Open the Jetpack sidebar.
* Click on the `Connect an account` external link.
* Edit the social media connections.
* Confirm the connections list is automatically updated once you go back to the block editor (it performs a request to the API, hitting the `wpcom/v2/publicize/connection-test-results` endpoint).
* Close the sidebar
* Change again the connections
* Confirm the browser doesn't hit the API
* Open the sidebar again
* Confirm the client hits the API
* Confirm the connections list is updated

The video below shows all these testing steps:

https://user-images.githubusercontent.com/77539/133631969-3d77b329-83fb-4f90-a41c-46d2df9ab149.mov

### CODE REVIEW

**Comment by DustyReagan** [comment]
I tested and it's working great, but I noticed 2 things.

1. If no accounts are linked we're missing the "Connect an account" link. The pic below is this branch on the left and production on the right.

missing-connect-acct

2. If you remove all of your accounts, look at your post, and then add a new one account, connection-test-results doesn't get called anymore. Video below.

https://user-images.githubusercontent.com/140841/133696913-57c9ee09-d718-4207-8ea8-f1360f90da09.mp4

**Comment by retrofox** [comment]
> I tested and it's working great, but I noticed 2 things.
> 
> 1. If no accounts are linked we're missing the "Connect an account" link. The pic below is this branch on the left and production on the right.


> 1. If you remove all of your accounts, look at your post, and then add a new account, connection-test-results doesn't get called anymore. Video below.

Fixed, Dusty. Thanks for your review, very nice catches!

**Review by allilevine — CHANGES_REQUESTED** [review]
This works well but I'm seeing a refresh on the Publish sidebar, even when no connection changes have been made. To reproduce:
1. Publish a post with sharing enabled
2. Navigate away from the editor to another tab/window
3. Return to the editor

https://user-images.githubusercontent.com/1689238/134232856-30d89841-5674-4a40-8841-7f1ac4d97bc1.mov

File: projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js [hunk 1]
```diff
@@ -2,64 +2,60 @@
...
-			return `https://wordpress.com/marketing/connections/${ siteFragment }`;
-		}
+export default function PublicizeSettingsButton() {
+	const { refresh } = useSelectSocialMediaConnections();
+	const siteFragment = getSiteFragment();
 
-		// If running in WordPress.org wp-admin we redirect to Sharing settings in wp-admin.
-		return 'options-general.php?page=sharing&publicize_popup=true';
-	}
+	const debRefresh = debounce( function ( isVisible ) {
```
[the remark this answers is not in the document]
Comment (retrofox) [reply projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js]: renamed with `debouncedRefresh` here https://github.com/Automattic/jetpack/pull/21107/commits/c83f3a16ea3e4dd8beaff4d024b48c6feda71bbd Let me know whether we should use another name 👍

[the remark this answers is not in the document]
Comment (allilevine) [reply projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js]: Sounds good, thanks!

**Comment by retrofox** [comment]
> This works well but I'm seeing a refresh on the Publish sidebar, even when no connection changes have been made. To reproduce:

Nice catch. It's a side effect of saving the posts in order to propagate the metadata :-(

**Review by allilevine — DISMISSED** [review]
> Nice catch. It's a side effect of saving the posts in order to propagate the metadata :-(

Looks like https://github.com/Automattic/jetpack/pull/21107/commits/849aeaf697e88dfd3cfbe0f8df0a5bf991fab504 fixed it 👍

**Comment by retrofox** [comment]
> > Nice catch. It's a side effect of saving the posts in order to propagate the metadata :-(
> 
> Looks like [849aeaf](https://github.com/Automattic/jetpack/commit/849aeaf697e88dfd3cfbe0f8df0a5bf991fab504) fixed it 👍

Anyway, let's avoid saving the posts. Removed here https://github.com/Automattic/jetpack/pull/21107/commits/bb724a18b94c1e2f05167fbb057ad7f7d84702c1 We can rely on the jetpack/publicize store instead.

File: projects/plugins/jetpack/extensions/plugins/publicize/store/reducer.js [hunk 2]
```diff
@@ -13,15 +13,57 @@ export const DEFAULT_STATE = {
...
+
+			const connections = [];
+			for ( const freshConnection of freshConnections ) {
+				let connection;
+				if ( prevConnectionIds.includes( freshConnection.id ) ) {
+					/*
+					 * The connection is already defined.
+					 * Do not overwrite the existing connection.
+					 */
+					connection = prevConnections.filter(
```
Comment (pablinos) [inline projects/plugins/jetpack/extensions/plugins/publicize/store/reducer.js:31]: This probably doesn't matter as there's only ever a few connections, but I think something that doesn't involve a full scan of the array would be better here, like `findIndex`. We could also remove the need for `prevConnectionIds`

File: projects/plugins/jetpack/extensions/plugins/publicize/store/reducer.js [hunk 3]
```diff
@@ -13,15 +13,57 @@ export const DEFAULT_STATE = {
...
-		case 'SET_CONNECTION_TEST_RESULTS':
+		case 'SET_CONNECTION_TEST_RESULTS': {
+			// Combine current connections with new connections.
+			const { connections: prevConnections } = state;
+			const prevConnectionIds = prevConnections.map( connection => connection.id );
+
+			const { results: freshConnections } = action;
+
+			const connections = [];
+			for ( const freshConnection of freshConnections ) {
```
Comment (pablinos) [inline projects/plugins/jetpack/extensions/plugins/publicize/store/reducer.js:24]: Maybe we could use `reduce` here to transform the shape of the array?

**Review by pablinos — COMMENTED** [review]
With an unpublished post, if I add a new connection, then swap tab and swap back, the connections briefly reset to those available as the editor was loaded, and then refreshes again.

https://user-images.githubusercontent.com/96462/134301062-82911b27-6751-4f91-9c7c-6103e269e131.mov

I don't like the use of post meta and the other store, but I think that's something we need to live with for now.

File: projects/plugins/jetpack/extensions/plugins/publicize/hooks/use-social-media-connections/index.js [hunk 4]
```diff
@@ -29,5 +28,13 @@ export default function useSocialMediaConnections() {
 				jetpack_publicize_connections: filteredConnections,
 			} );
 		},
+
+		refreshConnectionTestResults,
+
+		// To refresh the connections, we need to save the post.
+		refresh: function () {
+			refreshConnectionTestResults(); // refresh the jetpack/publicize connections.
+			savePost(); // refresh the `jetpack_publicize_connections` metadata.
```
[the remark this answers is not in the document]
Comment (pablinos) [reply projects/plugins/jetpack/extensions/plugins/publicize/hooks/use-social-media-connections/index.js]: This was an old comment!

**Comment by retrofox** [comment]
> With an unpublished post, if I add a new connection, then swap tab and swap back,...

That's correct. 

> ...the connections briefly reset to those available as the editor was loaded, and then refreshes again.

That too.

> I don't like the use of post meta and the other store, ...

I don't neither.

> but I think that's something we need to live with for now.

Exactly. Because initially, the connections list provided by the jetpack/publicize store is an empty array, meaning that it won't show any connection and then, after requesting them, will show all connections.
Picking the connections from the post meta will provide a more accurate list.
Also, it happens for new posts, because when it's editing, the metadata is also updated when the connections list changes.

Something that we can keep polishing.

File: projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js [hunk 5]
```diff
@@ -2,64 +2,62 @@
...
-			return `https://wordpress.com/marketing/connections/${ siteFragment }`;
-		}
+export default function PublicizeSettingsButton() {
+	const { refresh } = useSelectSocialMediaConnections();
+	const siteFragment = getSiteFragment();
+
+	// Refresh connections when mounted.
+	useEffect( () => {
+		refresh();
+	}, [ refresh ] );
```
Comment (pablinos) [inline projects/plugins/jetpack/extensions/plugins/publicize/components/settings-button/index.js:34]: What does this fix? The connections should be in sync as the editor loads, so we shouldn't need to refresh them again.

**Review by pablinos — DISMISSED** [review]
I think there are some bits that we could iterate on here, but it's working and this PR is getting big, so let's merge it and we can carry on fixing bits and pieces.

**Review by sdixon194 — DISMISSED** [review]

File: projects/plugins/jetpack/extensions/plugins/publicize/store/effects.js [hunk 6]
```diff
@@ -19,12 +20,71 @@ import { SUPPORTED_CONTAINER_BLOCKS } from '../components/twitter';
...
+		const prevConnections = select( 'jetpack/publicize' ).getConnections();
+		const prevConnectionIds = prevConnections.map( connection => connection.id );
+		const freshConnections = results;
+		const connections = [];
+
+		/*
+		 * Iterate connection by connection,
+		 * in order to refresh or update current connections.
+		 */
+		for ( const freshConnection of freshConnections ) {
```
[the remark this answers is not in the document]
Comment (retrofox) [reply projects/plugins/jetpack/extensions/plugins/publicize/store/effects.js:34]: ok, sounds good to me.

**Review by sdixon194 — DISMISSED** [review]

File: projects/plugins/jetpack/extensions/plugins/publicize/components/panel/index.js [hunk 7]
```diff
@@ -10,44 +10,29 @@
...
  * Internal dependencies
  */
 import PublicizeConnectionVerify from '../connection-verify';
 import PublicizeForm from '../form';
-import PublicizeSettingsButton from '../settings-button';
 import PublicizeTwitterOptions from '../twitter/options';
 
-const PublicizePanel = ( { connections, refreshConnections, prePublish } ) => (
-	<Fragment>
-		{ connections && connections.some( connection => connection.enabled ) && (
```
Comment (pablinos) [inline projects/plugins/jetpack/extensions/plugins/publicize/components/panel/index.js:27]: Yep this makes sense, we want to refresh the connections whether we have some currently enabled or not.

**Review by pablinos — DISMISSED** [review]
That's a good extra tweak. I tried to send loads of requests and it's not possible to do fast enough.

**Review by sdixon194 — DISMISSED** [review]

File: projects/plugins/jetpack/extensions/plugins/publicize/components/panel/index.js (hunk 7 above)
Comment (retrofox) [reply projects/plugins/jetpack/extensions/plugins/publicize/components/panel/index.js:27]: thanks!

**Review by jeherve — APPROVED** [review]

**Comment by retrofox** [comment]
> Great news! One last step: head over to your WordPress.com diff, D67237-code, and commit it.
> Once you've done so, come back to this PR and add a comment with your changeset ID.

r232200-wpcom
