### PR TITLE
Simple Payments: PayPal script execution error on Gutenberg

### LINKED ISSUE #10481: Simple Payments: shortcode in Gutenberg fails PayPal script
Simple payments shortcode throws fatals in Gutenberg editor.

#### Steps to reproduce the issue

1. Have Simple Payments enabled Jetpack (premium or business plan)
2. In Calypso, insert simple payments button and save the post
3. In wp-admin Gutenberg, open the same post
4. See error:
image

Basically simple payment + PayPal scripts get enqueued because of the shortcode, but in Gutenberg the markup is missing.

https://github.com/Automattic/jetpack/blob/d9108e166418cbe2517187c82798b7ace7086543/modules/simple-payments/simple-payments.php#L143

### PR DESCRIPTION
**Pull request by rodrigoi**
PayPal scripts are registered only for the site's Frontend to prevent execution errors when loading Gutenberg on WP-Admin.

Fixes #10481

#### Changes proposed in this Pull Request:

* Prevent registering PayPal Express Checkout scripts on the Admin Page.

#### Testing instructions:

* Jurassic Ninja: https://jurassic.ninja/create?jetpack-beta&branch=fix/simple-payments-frontend-only-register-scripts&gutenpack&gutenberg&calypsobranch=add/gutenpack-simplepayments-ui
* Connect Jetpack, purchase "premium" or "business" plan.
* Create new post in Gutenberg and add "Payment button" block.
* Open your browser's developer tools on the _Console_ tab.
* Save the product, publish the post and then refresh the editor.
* These errors should no longer appear:

screen shot 2018-11-02 at 18 04 40

* Navigate to the published post and verify that there are no regressions on the site's frontend.

### CODE REVIEW

File: modules/simple-payments/simple-payments.php [hunk 1]
```diff
@@ -49,7 +49,9 @@ private function register_shortcode() {
 	public function init_hook_action() {
 		add_filter( 'rest_api_allowed_post_types', array( $this, 'allow_rest_api_types' ) );
 		add_filter( 'jetpack_sync_post_meta_whitelist', array( $this, 'allow_sync_post_meta' ) );
-		$this->register_scripts_and_styles();
+		if ( ! is_admin() ) {
```
Comment (simison) [inline modules/simple-payments/simple-payments.php]: These scripts are not useful even if we're on wp-admin without Gutenberg? I.e. classic editor won't be missing them?

Comment (rodrigoi) [reply modules/simple-payments/simple-payments.php]: The classic editor doesn't need them. These are just for the frontend to wire the actual pay button.

**Review by sirreal — APPROVED** [review]
I tested this following the steps here and those described in #10481. Everything seems to be working well.

- No errors in WP Admin Gutenberg editor.
- Calypso editor continues to work fine.
- Payment button is functional on the frontend of the site.

Thanks, 🚢 !

**Review by tyxla — APPROVED** [review]
I've also verified this fixes the issue, thanks 👍

**Review by jeherve — APPROVED** [review]
LGTM. Merge when ready! 🚢

**Comment by jeherve** [comment]
Cherry-picked to `branch-6.7` in 1b58e69d41391eb5ed89950964ebe4b636bf1bce
