### PR TITLE
Search: mark new pricing as complete

### LINKED ISSUE #26899: Search: Free tier allows the user to turn off the "Powered by" message.
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

- Configure a site with a Free Search plan.
- Go to the customize page, turn off the "Show "Powered by Jetpack"" toggle, and save the settings.
- Go to the front end and do a search. The "Search powered by Jetpack Search" link will not be displayed.

### A clear and concise description of what you expected to happen.

The user should not be able to disable the CTA when on the Free plan. The toggle should be grayed out with a link to upgrade (maybe just an info icon?).

### What actually happened

_No response_

### Browser

_No response_

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes: #26899

#### Changes proposed in this Pull Request:
The PR proposes to enable the feature when `pricing_version` is set to '202208' from the pricing API. The WPCOM change is `D90075-code`. They could be merged regardless of order.

It also forces free plan user to show powered by.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
pcNPJE-145#comment-1819-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Apply `D90075-code` to your sandbox
- Sandbox your Jetpack test site
- Ensure new pricing is showing and purchase flow etc work
- Unsandbox the test site
- Ensure old pricing works

NOTE: please do test on WPCOM simple and ensure it doesn't break anything.

### CODE REVIEW

File: projects/packages/search/src/class-rest-controller.php [hunk 1]
```diff
@@ -422,11 +422,7 @@ public function get_local_stats() {
 	 */
 	public function product_pricing() {
 		$tier_pricing = Search_Product::get_pricing_for_ui();
-		// We don't want to show the half finished new pricing, even when it's set to open from the API.
-		if ( ! Helper::is_new_pricing_202208_ready() ) {
-			unset( $tier_pricing['pricing_version'] );
-		}
-		// Unless we are testing.
+		// we can force the plugin to use the new pricing by appending `pricing_version=202208` to URL.
```
Comment (trakos) [inline projects/packages/search/src/class-rest-controller.php]: Just a nitpick to this comment, but forcing a new pricing is done by adding `new_pricing_202208=1` instead of `pricing_version=202208`. Unless there's a separate argument somewhere, but I couldn't get it work with `pricing_version=202208`.

**Review by trakos — DISMISSED** [review]
Thanks a ton @kangzj, works as expected. I've deployed the related diff D90075-code, so this should be good to go as well once someone from Jetpack Search reviews it.

**Comment by trakos** [comment]
By the way, I've noticed that while we ignore value for `Show "Powered by Jetpack"` option, we still allow changing it:

image

Since it does nothing, I kind of expected it to be hidden or disabled.

Just noting it here, not a blocker for this PR.

File: projects/packages/search/src/class-rest-controller.php (hunk 1 above)
Comment (kangzj) [reply projects/packages/search/src/class-rest-controller.php]: ops that was a typo

Comment (kangzj) [reply projects/packages/search/src/class-rest-controller.php]: fixed

**Comment by kangzj** [comment]
Opened [an issue](https://github.com/Automattic/jetpack/issues/26901) for what @trakos pointed out.

> Since it does nothing, I kind of expected it to be hidden or disabled.

**Review by trakos — APPROVED** [review]

**Comment by gibrown** [comment]
Can we remove the need for new_pricing_202208=1 in the query string in this PR also? (assuming we don't already have another PR).

**Comment by trakos** [comment]
> Can we remove the need for new_pricing_202208=1 in the query string in this PR also? (assuming we don't already have another PR).

@gibrown that's more or less what it does. Once API returns new pricing, both the new pricing page (with free plan) and new dashboard is used. It's not required to use the `new_pricing_202208=1` string then, once you're using the sandboxed store.

Admittedly, it assumes switching all three things (new pricing, free option and new dashboard look) at the same time, but that should be OK? We could probably later separate new pricing with some backend changes.

**Review by dognose24 — APPROVED** [review]
Works as described! 🚀
