### PR TITLE
Instant Search: don't photon-ize SVG images

### LINKED ISSUE #19925: Search: SVG images being served using Photon URL despite being unsupported and displaying as broken links
#### Steps to reproduce the issue

1. Add a new page and put an SVG image as the first image
2. Publish page
3. Navigate to Jetpack Search and search for this new page
4. See SVG image is being displayed as a broken link

Example: https://eoinbusinesstestsite.com/?s=svg

#### What I expected
The SVG image should not be displayed using a Photon URL since Photon does not support SVG images

#### What happened instead
The SVG image is being served through Photon, which is not supported and therefore displays a broken link

**Screenshots**

Screenshot on 2021-05-24 at 09-54-33

Markup 2021-05-24 at 09 54 11

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes https://github.com/Automattic/jetpack/issues/19925.

#### Changes proposed in this Pull Request:
SVG images aren't supported by Photon. This PR skips Photon if the image is SVG.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

1. Make sure Site Accelerator for images is enabled in `/wp-admin/admin.php?page=jetpack#/performance` and that Jetpack Search has either the 'Expanded' or 'Product' result format selected.
1. Add a new page and put an SVG image as the first image
2. Publish page
3. Navigate to Jetpack Search and search for this new page
4. See if SVG image is being displayed correctly

Screen Shot 2021-05-25 at 14 28 05

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js [hunk 1]
```diff
@@ -27,17 +27,21 @@ function stripQueryString( url ) {
  */
 export function usePhoton( initialSrc, width, height, isPhotonEnabled = true ) {
 	const [ src, setSrc ] = useState( null );
+	const initialSrcWithoutQueryString = stripQueryString( initialSrc );
+
+	// Photon does not support SVGs
+	const isSVG = initialSrcWithoutQueryString?.substr( -4 ).toLowerCase() === '.svg';
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:33]: > We only fetch, resize, and serve gif, png, and jpg images from servers that listen on port 80 for HTTP and port 443 for HTTPS. This is about 99.99% of the web servers in the world. 

@see limitations https://developer.wordpress.com/docs/photon/

Could we maybe white list the extension rather than testing only for SVG?

Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:33]: That's a good idea 👍 We might run into the same thing with other formats otherwise. I don't think `.webp` is supported either.

Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js]: Fixed in 09f51ff 👍

**Review by kangzj — DISMISSED** [review]
Tested working and LGTM. Hooray for the test! 👍

File: projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js [hunk 2]
```diff
@@ -27,17 +27,31 @@ function stripQueryString( url ) {
  */
 export function usePhoton( initialSrc, width, height, isPhotonEnabled = true ) {
 	const [ src, setSrc ] = useState( null );
+	const initialSrcWithoutQueryString = stripQueryString( initialSrc );
+
+	// Photon only supports GIF, JPG and PNG
+	// @see https://developer.wordpress.com/docs/photon/
+	const supportedImageTypes = [ 'gif', 'jpg', 'png' ];
```
Comment (leogermani) [inline projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:34]: should we worry about `.jpeg` extensions?

Comment (leogermani) [reply projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:34]: example: https://i0.wp.com/filesamples.com/samples/image/jpeg/sample_640%C3%97426.jpeg

Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:34]: Good catch @leogermani 👍 I'll add it. 

I don't think there are any extension variations on PNG or GIF.

Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/lib/hooks/use-photon.js:34]: Screen Shot 2021-05-26 at 10 58 11

Now Photon-ized 👍

**Review by jeherve — DISMISSED** [review]

**Comment by bluefuton** [comment]
🚢 Shipped in r226345-wpcom.

**Comment by bluefuton** [comment]
@jeherve would you mind pressing the big merge button for me please? I had to rebase and that seems to have dismissed your review unfortunately.

Also - is there any possibility of having this one cherry-picked across to v9.8? It's affecting a Team 51 site (see p4Kr4c-4gB-p2#comment-18288). Thanks :)

**Review by jsnmoon — APPROVED** [review]
Resident Jetpack approver to the rescue!

**Comment by bluefuton** [comment]
Thank you @jsnmoon :)

**Comment by mdrovdahl** [comment]
@jeherve just echoing the request from [above](https://github.com/Automattic/jetpack/pull/19927#issuecomment-849197730)...any chance this can make tomorrow's release?

**Comment by jeherve** [comment]
Sorry, I had missed that one for some reason. I cherry-picked this to `jetpack/branch-9.8` in d900255c5c5fefa978cc1c50e622ba2fc06d7333
