### PR TITLE
Image Guide: Update tiny image check to treat all images as small if there's an error

### LINKED ISSUE #32037: Boost: Image Guide (free) showing up on adminbar avatar
### Impacted plugin

Boost

### Quick summary

CleanShot 2023-07-24 at 18 08 22@2x

### Steps to reproduce

1. Setup latest (2.0.0) Boost;
2. Enable Image Guide;
3. Check any page in the front-end.

### A clear and concise description of what you expected to happen.

Bubble shouldn't show up for avatars.

### What actually happened

_No response_

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by dilirity**
Probably fixes https://github.com/Automattic/jetpack/issues/32037

## Proposed changes:

* Update "is tiny image" check, to treat images who's dimensions couldn't be fetched as tiny.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

I didn't find a consistent way of testing this. I threw an Error inside the [try block](https://github.com/Automattic/jetpack/blob/6855c6f46cfe9ff409a0c3ec54270c8a964666ed/projects/js-packages/image-guide/src/MeasurableImage.ts#L132-L138) to simulate a "unable to fetch dimensions" case.

### CODE REVIEW

File: projects/js-packages/image-guide/src/MeasurableImage.ts [hunk 1]
```diff
@@ -134,7 +134,7 @@ export class MeasurableImage {
 			const dimensions = await this.fetchFileDimensions( this.getURL() );
 			return dimensions.width < minSize || dimensions.height < minSize;
 		} catch ( err ) {
-			return false;
+			return true;
```
Comment (thingalon) [inline projects/js-packages/image-guide/src/MeasurableImage.ts:137]: This function has a comment on it that says what it returns when an image fails to load. If we're changing the behaviour we should update the comment too.

**Review by thingalon — CHANGES_REQUESTED** [review]
Comment needs updating.

However I think this fix is fine. `fetchFileDimensions` uses an `img` tag to load the image and report on its dimensions (width, height). If it fails to load in an `img` tag, we likely shouldn't be showing it as an issue in the image guide.

File: projects/js-packages/image-guide/src/MeasurableImage.ts (hunk 1 above)
Comment (dilirity) [reply projects/js-packages/image-guide/src/MeasurableImage.ts:137]: Done in 99ca2a5.

**Review by thingalon — APPROVED** [review]
🚢  :)
