### PR TITLE
Connect button: Carry the "from" param when redirecting.

### LINKED ISSUE #17344: Jetpack Connection Button Source Tracking Broken
Seems pretty high priority. Let's try to get this into 9.0 if at all possible. 

#### Steps to reproduce the issue

Detailed report can be found in pbtFPC-PY-p2

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #17344

#### Changes proposed in this Pull Request:

This change adds some logic that will manually carry over the `from` parameter from the original request, for cases such as #17344 where the flow starts in the wp-admin dashboard or plugins screen banner. 

One side effect of this approach is that the query parameter remains in the URL after the redirect happens `/wp-admin/admin.php?page=jetpack#/setup&from=connect-banner-72-dashboard`. 

#### Jetpack product discussion

pbtFPC-PY-p2

#### Does this pull request change what data or activity we track or use?

Yes, we should be properly tracking the `from` if it's set in any connection flow. 

#### Testing instructions:

- Disconnect Jetpack
- From `/wp-admin/index.php`, click the "Set Up Jetpack" button in the banner at the top
- You should be redirected to the Jetpack dashboard as normal
- The registration step should still be done automatically
- You should end up landing on the user auth step
- When in the auth step, check the iframe source in the inspector, ensure that the `src` in the `<iframe class="jp-jetpack-connect__iframe"` element does not have an empty `from` parameter. 

- To verify the tracks was correctly recorded, visit the live view in MC, search for your wpcom username and the `wpcom_jpc_authorize_begin` event name. Expand that, and you should see the `from` param recorded correctly.

- Test with all other connection flows. 

#### Proposed changelog entry for your changes:

N/A

### CODE REVIEW

File: _inc/connect-button.js [hunk 1]
```diff
@@ -146,24 +147,24 @@ jQuery( document ).ready( function ( $ ) {
 
 			// Fetch plan type late to make sure any stored license keys have been
 			// attached to the site during the connection.
-			jetpackConnectButton.fetchPlanType()
```
Comment (dereksmart) [inline _inc/connect-button.js:149]: This whole chunk is automated whitespace?

File: _inc/connect-button.js [hunk 2]
```diff
@@ -172,7 +173,11 @@ jQuery( document ).ready( function ( $ ) {
 	};
 
 	// When we visit /wp-admin/admin.php?page=jetpack#/setup, immediately start the connection flow.
-	var hash = location.hash.replace( /#\//, '' );
+	var hash = location.hash.replace( /(#\/setup).*/, 'setup' );
```
Comment (dereksmart) [inline _inc/connect-button.js:176]: I did this to clean out the variable for the comparison below. I don't think we use it for anything other than `setup`, but correct me if I'm wrong.

File: _inc/connect-button.js [hunk 3]
```diff
@@ -52,7 +52,8 @@ jQuery( document ).ready( function ( $ ) {
 		handleConnectInPlaceFlow: function () {
 			// Alternative connection buttons should redirect to the main one for the "connect in place" flow.
 			if ( connectButton.hasClass( 'jp-banner__alt-connect-button' ) ) {
-				window.location = jpConnect.connectInPlaceUrl;
```
Comment (dereksmart) [inline _inc/connect-button.js:55]: This is where it was getting lost before

File: _inc/connect-button.js [hunk 4]
```diff
@@ -52,7 +52,8 @@ jQuery( document ).ready( function ( $ ) {
...
+				// Make sure we don't lose the `from` parameter.
+				window.location = jpConnect.connectInPlaceUrl + '&from=' + connectButtonFrom;
```
Comment (kraftbj) [inline _inc/connect-button.js:56]: Is there ever a situation where there won't be parameters on the URL? Should we transform to an URL and use URLSearchParams to append it?

Comment (dereksmart) [reply _inc/connect-button.js:56]: When I was playing with `URLSearchParams`, I noticed it didn't handle params within hashes, as it treats everything after the hash to be a... hash. 

That's a good point though, there is no reason to append anything at all if `connectButtonFrom` is empty at this point.

**Review by kbrown9 — DISMISSED** [review]
I tested this with the dashboard, plugins, and Jetpack dashboard connection banners. Everything worked as expected.

I think it would be nice to transform the URLs to URL objects and then use those objects to append and obtain the query parameters and hash. However, I don't think that's a blocker.

There are failing unit tests, but they don't appear to be related to the changes in this PR.

File: _inc/connect-button.js (hunk 4 above)
Comment (dereksmart) [reply _inc/connect-button.js]: @kraftbj @kbrown9 I took another stab at it with URLSearchParams, but it's not working for me. I think because `.append()` doesn't actually return anything? I assume the `undefined` check that's used elsewhere in the file is for graceful fallback for IE, so I left it in there. I probably won't have much time to re-visit this today, but please feel free to add it if you think it's worth it. Also I'd be curious to see what you had in mind. 

`if ( connectButton.hasClass( 'jp-banner__alt-connect-button' ) ) {
				// Make sure we don't lose the `from` parameter, if set.
				if ( 'undefined' === typeof URLSearchParams ) {
					var fromParam = ( connectButtonFrom && '&from=' + connectButtonFrom ) || '';
					window.location = jpConnect.connectInPlaceUrl + fromParam;
				} else {
					var searchParams = new URLSearchParams( jpConnect.connectInPlaceUrl );
					window.location = searchParams && searchParams.append( 'from', connectButtonFrom );
				}
				return;
			}`

And the `URLSearchParams` snippet to re-fetch the URL in the diff below (works): 

`if ( 'undefined' === typeof URLSearchParams ) {
		connectButtonFrom = location.hash.split( '&from=' )[ 1 ];
	} else {
		var searchParams = new URLSearchParams( location.hash.replace( /#\//, '' ) );
		connectButtonFrom = searchParams && searchParams.get( 'from' );
	}`

Comment (kraftbj) [reply _inc/connect-button.js]: Since we want this to land in 9.0, I am okay just landing this and following up. I need to check it out, but my understanding is `append` doesn't return, just adds to the object. You'll need to specifically ask for the object to be stringed for use again.

**Review by kbrown9 — APPROVED** [review]
This looks good to me!

**Comment by jeherve** [comment]
Cherry-picked to `branch-9.0` in 1412f07d3731a09ab3501c0704e142b10455c338
