### PR TITLE
Fix/top posts widget

### LINKED ISSUE #15104: Top posts widget not handling post types well
When Top Posts & Pages widget is configured to fetch only one or few post types, it may not behave as expected.

If a site has a large number of posts of a certain post type, and you add a widget to show the Top Posts of another post type, it may not find any.

That's because WordPress.com API doesn't allow you to fetch the top posts filtered by a post type. This filter has to be done later on the client side. So if a site has a large number of popular posts of a post type, the widget might never find the post type it is looking for.

Also, when no posts are found, it displays only one post for the visitor and ignores the post type configuration.

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #15104, 
See #2369
Addresses 4794-jpop-issues, 4988-jpop-issues

#### Changes proposed in this Pull Request:

This PR improves the way the Top Posts & Pages Widget fetches posts to be displayed.

##### How it worked before this PR:

* Widget makes a request to the wp.com API to fetch the top posts (of all post types)
* Since it makes a request with `summarize=1`, it receives up to 500 posts in the response
* It filters out only the number of posts the widget is configured to be displayed
* From this few posts, it filters out only posts of the post types configured to be displayed
* If it results in zero posts, it falls back fetching only one post or page, no matter what the post types configured in the widget are

The problem here is that if there were 10 posts in the top 10 positions, and you queried for pages, you would get no results.

##### This PR proposes two changes:

1. It filters out the posts by post type at the same time it's iterating over all the posts returned by the API, till it reaches the number of posts configured in the widget. 
2. If no posts are found, it respects the post type and number of posts configurations

**Limitations:** This PR does not completely solve the problem. There is no way to query the wp.com API for post types filtering for a specific post type. So the same problem still persists, the only difference is that it now looks in all 500 retrieved posts, and not only on the first 10.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* It fixes an existing feature

#### Testing instructions:

It's very difficult to test the edge cases that this PR fixes, but I'll give some basic testing instructions and describe the edge case afterward.

Run these tests both on a wp.com site and on a JP site. 

**On an existing site with some stats.**
2. in Jetpack settings, activate `Make extra widgets available for use on your site including subscription forms and Twitter streams`
3. Go to Appearance > Widgets and add two "Top Posts & Pages" Widget
4. Configure one of the widgets to display only posts, and the other one to display only pages
5. Visit the site both logged in and logged out and check if the widgets are working as expected

**On a brand new site**
1. Follow the same instructions, 1 to 4
2. Visit the site, logged in, and see the message "There are no posts to display"
3. Visit the site, logged out, and see that the posts displayed in both widget respect the configured post type and count.

**The Edge case**

The Edge case is a site that has many posts of a certain post type and, when you add a widget to display posts of another post type, this widget would not find any post.

* Considering a site that has many posts of the post type `post` as its top rankings posts, and few pages with few visits
1. Follow the same instructions 1 to 4
2. Check the site front end, bot logged in and logged out. Check that the widget that should display pages finds the most viewed pages.

#### Proposed changelog entry for your changes:

* Fixes Top Posts & Pages Widget handling with different post types

### CODE REVIEW

**Comment by sergeymitr** [comment]
Hi @leogermani.
For some reason the _"Top Posts & Pages"_ widget doesn't display any posts or pages when I'm logged in as an admin:
top-pages-posts

Everything works correctly when I'm viewing the website as a guest though.
Let me know if you need help debugging it.

File: modules/widgets/top-posts.php [hunk 1]
```diff
@@ -570,37 +573,59 @@ function get_by_views( $count, $args ) {
...
-	function get_posts( $post_ids, $count ) {
+	/**
+	 * Get posts from an array of IDs
+	 *
+	 * @param array $post_ids The post IDs.
+	 * @param int   $count The maximum number of posts to return.
+	 * @param array $types The post types that should be returned.
+	 * @return array
+	 */
+	public function get_posts( $post_ids, $count, $types ) {
```
Comment (kraftbj) [inline modules/widgets/top-posts.php]: Should we set `$types = array( 'post', 'page' )` to make it an optional parameter?

File: modules/widgets/top-posts.php [hunk 2]
```diff
@@ -570,37 +573,59 @@ function get_by_views( $count, $args ) {
...
-		$post = array_pop( $posts );
-
-		return $this->get_posts( $post->ID, 1 );
+		return $this->get_posts( $posts, $count, $types );
 	}
 
-	function get_posts( $post_ids, $count ) {
+	/**
+	 * Get posts from an array of IDs
+	 *
```
Comment (kraftbj) [inline modules/widgets/top-posts.php]: Could we add a `@since 8.4.0 Added $types`?

**Review by kraftbj — CHANGES_REQUESTED** [review]
Very minor things. (and the updated commit may retrigger Travis)

**Comment by leogermani** [comment]
> Hi @leogermani.
> For some reason the _"Top Posts & Pages"_ widget doesn't display any posts or pages when I'm logged in as an admin:

That's expected with a brand new site.

When you have an anonymous visitor, it falls back and make a simple query for posts (the second fix on this PR). Before this PR. it would display only one post, no matter how many you configured to be displayed in the widget, and also ignore the post type.

File: modules/widgets/top-posts.php (hunk 1 above)
Comment (leogermani) [reply modules/widgets/top-posts.php]: we could. I didn't because this variable is treated here:

https://github.com/Automattic/jetpack/blob/218e6fbe5cf31b212487eae692038cf7125c47b0/modules/widgets/top-posts.php#L244

But no harm doing that

File: modules/widgets/top-posts.php (hunk 2 above)
Comment (leogermani) [reply modules/widgets/top-posts.php]: sure

Comment (leogermani) [reply modules/widgets/top-posts.php]: Done in https://github.com/Automattic/jetpack/pull/15109/commits/97d3618e743e66746a4f38fb28fef1a9f5b4b93c

File: modules/widgets/top-posts.php (hunk 1 above)
Comment (leogermani) [reply modules/widgets/top-posts.php]: I'm reconsidering this.

This method is not called directly by the main widget method, it is passed through `get_by_likes`, `get_by_views` and `get_fallback_posts`. So this would require a chain of optional and useless arguments... 

Both `$count` and `$types` are present in the widgets `$instance`, so a nice refactor would be to use it instead. Not sure if we should do it now... Also, these methods could/should be private (or live somewhere else in jetpack codebase)

I'm always afraid with backward compatibility but this is a widget and the code, I beleive, is self contained and shouldn't be called from outside...

What do you think? quick refactor?

Comment (kraftbj) [reply modules/widgets/top-posts.php]: I'm okay covering that in a later PR. Could you either open an issue (if you don't have bandwidth) or open a new PR for it?

**Review by kraftbj — DISMISSED** [review]

**Comment by kraftbj** [comment]
r204992-wpcom

**Comment by kraftbj** [comment]
https://code.a8c.com/D41022 for the clean-up of the defaults.

**Review by kraftbj — APPROVED** [review]

File: modules/widgets/top-posts.php [hunk 3]
```diff
@@ -619,7 +619,7 @@ public function get_fallback_posts( $count = 10, $types = array( 'post', 'page'
 	/**
 	 * Get posts from an array of IDs
 	 *
-	 * @since 8.4.0 Added $count and $types parameters
+	 * @since 8.4.0 Added $types parameters
```
Comment (leogermani) [inline modules/widgets/top-posts.php]: ah yes, the parameter existed, but it was ignored
