### PR TITLE
Related Posts: ensure authors+ have access to the block

### LINKED ISSUE #42966: Related Posts: block cannot be added by authors and editors
### Steps to reproduce

1. Start with a site that's connected to WordPress.com.
1. Go to Posts > Add New
2. Insert a Related Posts block
3. Activate the feature if you receive the placeholder inviting you to do so.
4. Go to Users > Add New
5. Create a new author or editor user
6. In a new browser, log in with that user
7. Go to Posts > Add New
8. Insert a Related Posts block

You'll get the placeholder inviting you to activate the module, even though it's already enabled.

********

This was originally reported here:
https://github.com/Automattic/jetpack/pull/40209#pullrequestreview-2668080904

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #42966

## Proposed changes:

By opening up this endpoint to authors, we'll be able to check that the related posts feature is available, even for folks who are not admins.

This of course means authors will have access to related posts options. I think this is okay, the options that can be returned are not necessarily problematic. For reference, this is information that could be visible:

- enabled
- show_headline
- headline
- show_thumbnails
- show_date
- show_context
- layout

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

1. Start with a site that's connected to WordPress.com.
1. Go to Posts > Add New
2. Insert a Related Posts block
3. Activate the feature if you receive the placeholder inviting you to do so.
4. Go to Users > Add New
5. Create a new author or editor user
6. In a new browser, log in with that user
7. Go to Posts > Add New
8. Insert a Related Posts block
    * You should see the default related posts output.

### CODE REVIEW

File: projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-related-posts.php [hunk 1]
```diff
@@ -34,7 +34,7 @@ public function register_routes() {
 				'methods'             => WP_REST_Server::READABLE,
 				'callback'            => array( $this, 'get_options' ),
```
Comment (simison) [inline projects/plugins/jetpack/_inc/lib/core-api/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-related-posts.php:35]: I can see why someone used `manage_option` cap since in callback we `get_options`. Assuming this will continue work regardless with the `edit_posts` cap, tho!

**Review by coder-karen — APPROVED** [review]
This works given the testing instructions.

I did need to merge with trunk locally to ensure that non-admins didn't get the block placeholder with the button to activate RP (from the change in #40209), which wouldn't work in that case, but after doing so everything works as I expected 👍
