### PR TITLE
Forms: Prevent Google Drive connection attempt without Jetpack user account connection

### LINKED ISSUE #42915: Forms: Google connection fails if user isn't connected
When going to form submissions and "export", there's a way to connect Google Drive:

Image

Google Connection currently happens in Calypso, and you get dropped at "connections" page with site selected.

However, if you haven't connected your user in Jetpack (i.e. just have done "site connection"), you just land at site-selector in WordPress.com without way forward, since WP.com doesn't know that you own the site. In latest version of Jetpack site and user connection happen to all new Jetpack sites, but there are old sites without user connection. Same bug could show up also when different user than the one who connected jetpack is connecting Google.

Fix is to route to Jetpack user connection first (there's an existing flow for that), and then continue with the setup flow.

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #42915

## Proposed changes:

* Checks if the user is connected before attempting to connect the user's Google Drive account, as that would fail without the Jetpack connection
* Changes the button to connect the user account to Jetpack instead, redirecting back to the same URL, where the user can proceed with the Google connection

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Get to a state where your site is connected to Jetpack, but your user is not
* Click on "Feedback" on the admin sidebar
* Click on Export
* Check that the button on the Google Drive card is set to connect the user account instead
* Click it
* Check that you can connect your user
* Check that you are redirected back to the Feedback page
* With the user connected, check that the Google connection works as expected

| Before | After |
| - | - |
|drawing | drawing

### CODE REVIEW

File: projects/packages/forms/src/dashboard/inbox/export-responses/google-drive.js [hunk 1]
```diff
@@ -16,6 +17,10 @@ const GoogleDriveExport = ( { onExport } ) => {
 	const [ isConnected, setIsConnected ] = useState( config( 'gdriveConnection' ) );
 	const { tracks } = useAnalytics();
 
+	const { isUserConnected, handleConnectUser, userIsConnecting, isOfflineMode } = useConnection( {
```
Comment (enejb) [inline projects/packages/forms/src/dashboard/inbox/export-responses/google-drive.js:20]: I wasn't able to test this redirect. Mostly because it asked me to use the magic link. And when I used it it didn't return me back to the wp-admin as expected.

**Review by enejb — APPROVED** [review]
The changes make sense and they work as expected.

File: projects/packages/forms/src/dashboard/inbox/export-responses/google-drive.js (hunk 1 above)
Comment (simison) [reply projects/packages/forms/src/dashboard/inbox/export-responses/google-drive.js:20]: Magic links wouldn't work with a8c accounts, or did you test with non-a8c account?

**Comment by simison** [comment]
This works as v1 but can the "Connect to Google Drive" redirect to user connection first -> then continue to Google connection? That way they don't need to click twice anything.

We might need to add some copy in/around the Button to set expetations of creating an account first in that case. @ilonagl  can help there.

**Comment by dhasilva** [comment]
> can the "Connect to Google Drive" redirect to user connection first -> then continue to Google connection?

I'm looking for a way to open the connection screen on a new tab. Other than that, I also tried redirecting to the Google Drive connection screen after the Jetpack connection, but the `redirectUri` param is concatenated to the wp-admin address, making it useless for URLs that are unrelated to the admin area. There is a `redirectFunc` that could be used for that, but it did not work.
So if there is a way to open the connection screen in a new tab and redirect it properly after (may need some tweaks on the connection package), it should be possible, though the polling needs to be updated as well to account for the first step.
I'll merge it as is now and get back to it when I find a way to solve the connection screen tab issue.
