### PR TITLE
Fix sonar qube issues

### LINKED ISSUE #31683: [Flagship plugin]: Sonar Qube: Refactor suggested issues

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Fixes #31683

## Proposed changes:

* I did run a [Sonar Qube](https://docs.sonarqube.org/latest/) over Jetpack plugin's related packages in the Monorepo and fixed most important in my opinion. Many issues are non relative, or very low significance, which made fixing them not worth the risk in my opinion.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to '..'
*

### CODE REVIEW

File: projects/js-packages/components/components/boost-score-bar/index.tsx [hunk 1]
```diff
@@ -81,7 +81,7 @@ export const BoostScoreBar: FunctionComponent< BoostScoreBarProps > = ( {
 						<div className="jb-score-bar__score">{ score }</div>
 					) }
 
-					{ showPrevScores && prevScore && prevScore < score && (
+					{ showPrevScores && !! prevScore && prevScore < score && (
```
Comment (andrii-lysenko) [inline projects/js-packages/components/components/boost-score-bar/index.tsx:84]: In rare occasion, it could render 0.

File: projects/js-packages/components/tools/jp-redirect/index.ts [hunk 2]
```diff
@@ -38,7 +38,7 @@ export default function getRedirectUrl( source: string, args: GetRedirectUrlArgs
 		queryVars.source = encodeURIComponent( source );
 	}
 
-	Object.keys( args ).map( argName => {
+	Object.keys( args ).forEach( argName => {
```
Comment (andrii-lysenko) [inline projects/js-packages/components/tools/jp-redirect/index.ts]: There's no need for `map` as it will create new array, while we don't need it.

File: projects/js-packages/connection/components/disconnect-survey/index.jsx [hunk 3]
```diff
@@ -129,6 +129,7 @@ const DisconnectSurvey = props => {
 		return (
 			<SurveyChoice
 				id={ customOption.id }
+				key={ customOption.id }
```
Comment (andrii-lysenko) [inline projects/js-packages/connection/components/disconnect-survey/index.jsx:132]: `key` helps React with better rendering preformance

File: projects/packages/videopress/src/client/hooks/use-uploader.js [hunk 4]
```diff
@@ -95,7 +95,7 @@ export const uploadVideo = ( { file, onProgress, onSuccess, onError, data } ) =>
 
 			req._xhr.open( req._method, req._url, true );
 			// Set the headers again, reopening the xhr resets them.
-			Object.keys( req._headers ).map( function ( headerName ) {
+			Object.keys( req._headers ).forEach( function ( headerName ) {
```
Comment (andrii-lysenko) [inline projects/packages/videopress/src/client/hooks/use-uploader.js]: There's no need for map as it will create new array, while we don't need it.

File: projects/packages/videopress/src/client/hooks/use-uploader.js [hunk 5]
```diff
@@ -116,7 +116,7 @@ export const uploadVideo = ( { file, onProgress, onSuccess, onError, data } ) =>
 				if ( jwtsForKeys[ maybeUploadkey ] ) {
 					req.setHeader( 'x-videopress-upload-token', jwtsForKeys[ maybeUploadkey ] );
 				} else if ( 'HEAD' === method ) {
-					return getJWT( maybeUploadkey ).then( responseData => {
+					return getJWT().then( responseData => {
```
Comment (andrii-lysenko) [inline projects/packages/videopress/src/client/hooks/use-uploader.js:119]: `getJWT` doesn't accept attributes.

File: projects/packages/waf/src/class-waf-runtime.php [hunk 6]
```diff
@@ -222,7 +222,7 @@ public function match_targets( $transforms, $targets, $match_operator, $match_va
 				$v['value'] = $this->transforms->$t( $v['value'] );
 			}
 		}
-
+		unset( $v );
```
Comment (andrii-lysenko) [inline projects/packages/waf/src/class-waf-runtime.php:225]: Not an expert, but suggested unset value after `foreach ( $values as &$v )`

File: projects/js-packages/components/tools/jp-redirect/index.ts (hunk 2 above)
Comment (anomiex) [reply projects/js-packages/components/tools/jp-redirect/index.ts]: You could go a step further and turn it into `for ( const argName of Object.keys( args ) ) {`.

**Review by monsieur-z — DISMISSED** [review]
Code changes look sensible 👍

**Comment by bindlegirl** [comment]
LGTM but pinging @anomiex for a second opinion.

**Review by anomiex — DISMISSED** [review]
LGTM

**Review by samiff — APPROVED** [review]
