### PR TITLE
Search: Fix irrelevant widgets in overlay sidebar on auto config

### LINKED ISSUE #24402: Search: Auto-configuration incorrectly migrates irrelevant widgets into the search sidebar
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

Note: This issue is not consistently reproducible.

1. Purchase a Jetpack Search subscription.
2. Navigate to the block-based widget editor (`/wp-admin/widgets.php`).

### A clear and concise description of what you expected to happen.

There should be an auto-configured Jetpack Search widget in the Jetpack Search sidebar. There should be no other widgets.

### What actually happened

In addition to the Jetpack Search widget, the following were added:

- A search block
- A grouping for "Recent Posts"
- A grouping for "Recent Comments"

image

### Other information

Full-site editing themes may be a factor here.

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #24402 

#### Changes proposed in this Pull Request:
Changes the name of the overlay sidebar to walk around the WP widget auto-adding mechanism  - WP migrates/adds some default widgets to sidebars with keyword `sidebar` in it. To walk around that, we changed `jetpack-instant-search-sidebar` to `jetpack-instant-search-side-bar`. In order to maintain the compatibility for old search sidebar, we hooks the option value and does a mapping.

It also removes some hacky code to stop these widgets to be added when switching themes.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* Create a JN site from [this link](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack-search=master&nojetpack) with only Jetpack Beta Tester plugin and Search plugin on bleeding edge
* Purchase a search subscription
* Ensure Jetpack Search sidebar is auto configured with categories and tags filter (and some irrelevant widgets)
* Switch Search to branch `fix/irrelevant-widgets-in-overlay-sidebar`
* Ensure Jetpack Search sidebar still works
* Ensure you could edit the content of the sidebar
-------

* Create another JN site from [this link](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack-search=fix/irrelevant-widgets-in-overlay-sidebar&nojetpack) with only Jetpack Beta Tester plugin and Search plugin on branch `fix/irrelevant-widgets-in-overlay-sidebar`
* Purchase a search subscription
* Ensure only Jetpack Search widget is added to overlay sidebar with only categories and tags filter (no irrelevant widgets)

### CODE REVIEW

File: projects/packages/search/src/instant-search/class-instant-search.php [hunk 1]
```diff
@@ -18,12 +18,15 @@
  */
 class Instant_Search extends Classic_Search {
 	/**
-	 * The name of instant search sidebar
+	 * The name of instant search sidebar.
+	 *
+	 * 'sidbar' is broken to 'side-bar' on purpose to walk around the mechanism that WP automatically adds widgets to it.
```
Comment (bluefuton) [inline projects/packages/search/src/instant-search/class-instant-search.php]:
```suggestion
	 * 'sidebar' is broken to 'side-bar' on purpose to walk around the mechanism that WP automatically adds widgets to it.
```

**Review by bluefuton — APPROVED** [review]
✅ First test: sidebar migration worked (no widgets removed)
✅ Second test: new site did not have any unnecessary widgets

🚢 Looks good to me!
