### PR TITLE
Search: Fix overlay not scrolled to top on mobile

### LINKED ISSUE #19882: Instant Search: when mobile keyboard is active, modal search input and results are not fully visible
#### Steps to reproduce the issue

1. On an iPad (or simulated iPad via Xcode Simulator) start filling out a search input on a site with Jetpack Instant Search enabled

#### What I expected
When I have the keyboard open, the modal opens scrolled to the top so I can see some results.

#### What happened instead
When I have the keyboard open, only the lower part of the modal is visible so I can't see the modal search input or the first few results.

(Works fine in portrait mode.)

**Screenshots**

Screen Shot 2021-05-19 at 15 26 28

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #19882 

#### Changes proposed in this Pull Request:
Scroll window to the top for the for the visibility of the search input. I guess the problem is the browser tries still to focus on the search input in the body (on the page), and when the search input is on the lower position, the search input on the overlay would be scrolled away. When the search input is on top of the page, it actually works fine.

So this PR basically brings back the scrollTo functionality but with different propertyName to listen on which based on what the overlay animation uses.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Go to a site with Jetpack Search on iPad or iPhone and perform a search
* Ensure the search input of the overlay is visible

Like this,
Simulator Screen Shot - iPad (8th generation) - 2021-08-13 at 13 44 21

NOT like this,
Simulator Screen Shot - iPad (8th generation) - 2021-08-13 at 13 45 32

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/components/dom-event-handler.jsx [hunk 1]
```diff
@@ -169,6 +182,20 @@ export default class DomEventHandler extends Component {
 		}
 	};
 
+	scrollOverlayToTop = event => {
+		// NOTE: the propertyName need to be aligned with the animation
+		if ( event?.propertyName !== 'opacity' ) {
+			return;
+		}
+		// NOTE: IE11 doesn't support scrollTo. Manually set overlay element's scrollTop.
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/dom-event-handler.jsx:190]: We could potentially drop this (IE11 polyfill is being removed in https://github.com/Automattic/jetpack/pull/20499).

**Review by bluefuton — DISMISSED** [review]
✅ Tests out well on iPhone Safari.

File: projects/plugins/jetpack/modules/search/instant-search/components/dom-event-handler.jsx (hunk 1 above)
Comment (kangzj) [reply projects/plugins/jetpack/modules/search/instant-search/components/dom-event-handler.jsx]: removed in 0804f0234b

**Review by jeherve — DISMISSED** [review]

**Comment by kangzj** [comment]
Hi @jeherve, sorry had to do a rebase, could you please have another look? Thanks.

**Review by jeherve — APPROVED** [review]

**Comment by kangzj** [comment]
🚢 shipped in r230296-wpcom
