### PR TITLE
Subscriptions: stop loading subscribe block and panels when module disabled

### LINKED ISSUE #39800: Hide the Newsletter plugin icon when newsletter isn't enabled
Today, even if Jetpack Newsletter isn't enabled, we show the `send` icon in Gutenberg. We should only show it **if** Jetpack Newsletter is enabled.

Image

Image

### LINKED ISSUE #40230: Newsletter: Disabling Newsletter Doesn't Remove It from Post Editing
### Impacted plugin

Jetpack

### Quick summary

When you disable Newsletter in the Jetpack Settings, it still displays in the post editing and publishing UI

### Steps to reproduce

1. Disable Newsletter in settings
2. Add a new post and see that the newsletter preview still displays

### A clear and concise description of what you expected to happen.

If I elect to disable Newsletter, I expect the elements to be removed from the UI.

### What actually happened

Image

Image

### Impact

One

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Tested in Jetpack v14

### PR DESCRIPTION
**Pull request by simison**
Subscriptions: stops loading editor functionality (i.e. the block and panels) when subscriptions module is disabled.

Resolves https://github.com/Automattic/jetpack/issues/39800
Resolves https://github.com/Automattic/jetpack/issues/40230

## Proposed changes:

* Dont'load the JS code at all when module is disabled
* Remove "enable module" nudges from JS since those aren't loaded anymore

Newsletter in the header icon will be no more, and the subscribe block won't show up in block pickers:

Screenshot 2024-11-22 at 15 51 38

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Block and panels work when subscriptions module is enabled from "Jetpack -> Settings -> Newsletter"
* You won't find any functionality in the editor when module is disabled:

     image

### CODE REVIEW

**Comment by crisbusquets** [comment]
Works for me. I tested this on a JN site. Thanks for working on this! 🙏 

**Jetpack connected**
Screenshot 2024-10-17 at 12 00 51


**WordPress.com account connected, Newsletter disabled**
Screenshot 2024-10-17 at 12 01 40


**WordPress.com account connected, Newsletter enabled**
Screenshot 2024-10-17 at 12 02 08

**Comment by crisbusquets** [comment]
This is also nice, @simison 🚀 

Screenshot 2024-10-17 at 12 03 55

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 1]
```diff
@@ -61,22 +68,6 @@ function register_block() {
...
-	 */
-	if ( ! Jetpack::is_module_active( 'subscriptions' ) ) {
-		return;
-	}
-
-	/**
-	 * Do not proceed if the newsletter feature is not enabled
-	 * or if the 'Jetpack_Memberships' class does not exists.
-	 */
-	if ( ! class_exists( '\Jetpack_Memberships' ) ) {
```
Comment (simison) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:76]: It was a bit weird to see this class check here since we just import the file a few lines above:

https://github.com/Automattic/jetpack/blob/adb410b4b4bd9c8298f726b2d79889a70388177a/projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php#L46

So I removed the check as a redundant.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 2]
```diff
@@ -43,9 +43,16 @@ function register_block() {
...
+	 * Do not proceed if the newsletter feature (Subscriptions module) is not enabled
+	 */
+	if ( ! Jetpack::is_module_active( 'subscriptions' ) ) {
+		return;
+	}
+
 	require_once JETPACK__PLUGIN_DIR . '/modules/memberships/class-jetpack-memberships.php';
-	if ( \Jetpack_Memberships::should_enable_monetize_blocks_in_editor() ) {
 
+	if ( \Jetpack_Memberships::should_enable_monetize_blocks_in_editor() ) {
```
Comment (simison) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:55]: Function name could be improved but works for now.

**Review by jeherve — COMMENTED** [review]
This essentially removes the work we had done in #29044. This introduces a discrepancy with the other blocks that rely on a module, and that will remain always available. is that okay? 

Could we instead hide the newsletter icon, but keep the placeholders to invite folks to turn the feature on?

**Comment by simison** [comment]
> Could we instead hide the newsletter icon, but keep the placeholders to invite folks to turn the feature on?

It's an option, yes. I'm little less worried about undoing work (although it's a bummer) and more interested in finding best possible UX. :-) 

Happy to have the product convo in a P2 regarding other blocks, before committing to this!

**Comment by jeherve** [comment]
> Happy to have the product convo in a P2 regarding other blocks, before committing to this!

It may be worth a discussion on +jpopdesignp2 I think. I don't have a strong opinion on the matter personally, but I think it would make sense to have a consistent approach. If we were to remove the placeholders for one block, we should probably do it for all. I think there are arguments for it, performance could be one of them.

**Comment by crisbusquets** [comment]
> > Happy to have the product convo in a P2 regarding other blocks, before committing to this!
> 
> It may be worth a discussion on +jpopdesignp2 I think. I don't have a strong opinion on the matter personally, but I think it would make sense to have a consistent approach. If we were to remove the placeholders for one block, we should probably do it for all. I think there are arguments for it, performance could be one of them.

My thoughts: When a user opens Gutenberg, they're usually focused on writing content for their site, not exploring new features. Sure, they could come across new features, but that's not the main goal for this UI.

I think we can find better opportunities to introduce features within the WP Admin or Jetpack, rather than adding more icons to Gutenberg that users may not need right away (or maybe never).

I'm not entirely sure we have a one-size-fits-all approach, it probably depends on the feature. AI, for example, directly helps with writing, so that one makes sense to keep.

**Review by lezama — DISMISSED** [review]

**Comment by simison** [comment]
@jeherve I was reviewing a bit placehodler status for other features:

While Newsletters feature has a clear'ish "on/off" toggle (it could be better discoverable but that's separate issue), not all features do have it:

Screenshot 2024-11-26 at 13 56 55

For example Related posts has a toggle which adds classic related posts to posts:

Screenshot 2024-11-26 at 13 56 43

Having that toggle control the block is kinda meaningless since related posts would just appear in your posts, you don't need to deal with the block anymore. Once related posts is updated to use block hooks, hiding the block when module is disabled is more meaningful.

Screenshot 2024-11-26 at 13 55 17

There are likely similar UX issues with other blocks, and placeholders are kinda "hack" to improve otherwise poor UX for enabling and discovering features, but have a tradeoff of contributing to the bloated feeling of Jetpack.

**Comment by jeherve** [comment]
> There are likely similar UX issues with other blocks, and placeholders are kinda "hack" to improve otherwise poor UX for enabling and discovering features, but have a tradeoff of contributing to the bloated feeling of Jetpack.

Yup, that's very true. 

Interestingly, the concept of modules also contributed to fight the idea of bloat since when a module is inactive, code for that feature didn't run on the site. 
If we were to do away with that, and for example always load the related posts codebase so the block is available without having to activate a module, we would do away with that concept. I'm honestly not quite sure how to best address this.
