### PR TITLE
Premium Content Block: Move the product management system into a shared component

### LINKED ISSUE #23412: Premium Content Block: Move the product management system into a shared component
### Impacted plugin

Jetpack

### What

First step in making all payment blocks use the same product management components.

### How

All payment blocks use a different product management system, each with different features.
Premium Content's system is the most feature-complete of the lot, and also has the best UX.
Let's move it into a shared component so that it could be reused by the other payment blocks.

The system consists of a toolbar and a sidebar part. We'll need to move them both:

- https://github.com/Automattic/jetpack/blob/6a0324ba5746a289d6b15e03845ec3019f5b913c/projects/plugins/jetpack/extensions/blocks/premium-content/_inc/controls.js
- https://github.com/Automattic/jetpack/blob/6a0324ba5746a289d6b15e03845ec3019f5b913c/projects/plugins/jetpack/extensions/blocks/premium-content/_inc/inspector.js

It could also be useful to create a Redux store to share products data across multiple payment blocks.

### LINKED ISSUE #23444: Premium Content Block: Add new subscription doesn't allow one-time payments
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Add a new Premium content block
2. Click on the Add new subscription from Gutenberg block
3. Notice that in the sidebar form the "Interval" dropdown doesn't contain "One-time" subscription type.
4. Go to https://wordpress.com/earn/payments-plans/{your-site} and add a new subscription.
5. Select the "One time purchase" in the Select renewal frequency option
6. Go back to the editor and you'll see that the One-time subscription you've just created can be selected.

### A clear and concise description of what you expected to happen.

We should be able to create one-time subscriptions from inside Gutenberg for Premium content blocks

### What actually happened

A user can only create a Monthly and Yearly subscription

### Other information

Screenshot 2022-03-15 at 14 27 16

### Operating System

_No response_

### OS Version

_No response_

### Browser

Other / Not applicable

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by Copons**
Fixes #23412
Fixes #23444

#### Changes proposed in this Pull Request:

* Premium Content Block: Move the product management system into a shared component.

This PR moves the Premium Content block's product-related toolbar and sidebar controls.
The plan is to eventually reuse it on several payment blocks (Premium Content and Payment Button), and to enhance it with more features.

The PR also moves the products into a Redux state, so that we'll be able to share them across several blocks, instead of fetching them every time.

The PR doesn't introduce any visual changes.
I've avoided attempting other improvements to avoid bloating this PR size.
Anything that we'll need to make this work on the Payment Button block (e.g. editorial changes), we'll do in a follow-up.

Note:
This could also include https://github.com/Automattic/jetpack/pull/23352.
I've chosen to not add it here as that introduces a new event that is a bit time-sensitive.
We can refactor the shared Stripe Connect button into this new component at a later time.

#### Jetpack product discussion

paYJgx-1SL-p2

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Sync these changes to WordPress.com, and test the Premium Content block with both free and business sites.
* On the free site: make sure the block displays the upgrade nudge and doesn't show any product-related UI.
* On the business site...
  * Stripe not connected?
    * Only the "Connect Stripe" control, no product-related UI.
  * No products (check `https://wordpress.com/earn/payments-plans/`)?
    * The block is automatically created with a $5/month subscription called "Monthly Subscription".
  * Click on the toolbar control:
    * Changing the selected product updates the `selectedPlanId` attribute of the block.
    * Clicking on "Add a new subscription" opens the block sidebar and focus on the name field.
  * From the sidebar:
    * Try inserting various subscriptions and make sure they get selected once inserted.

### CODE REVIEW

**Review by dsas — APPROVED** [review]
Works well for me. I've left some comments none of them are blockers though, so feel free to do with them as you wish :).

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+ * WordPress dependencies
+ */
+import { useSelect } from '@wordpress/data';
+import { useEffect } from '@wordpress/element';
+
+/**
+ * Internal dependencies
+ */
+// eslint-disable-next-line no-unused-vars
+import store, { jetpackMembershipProductsStore } from './store';
```
[the remark this answers is not in the document]
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js]: Typically stores are imported as `import './store'`, but in this case I also wanted `jetpackMembershipProductsStore`, which is the store name, to use in the selector.
Two separate imports is a lint error as much as this one, but this at least is a one-liner. 😄 

This said, I tried removing the `store,` part, and the store is registered correctly anyway.
I think the `registerStore` gets called regardless once anything in the `store.js` file is imported somewhere. 🤔

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js [hunk 2]
```diff
@@ -0,0 +1,139 @@
...
+	const isEditorSidebarOpened = useSelect( select =>
+		select( editPostStore ).isEditorSidebarOpened()
+	);
+	const { openGeneralSidebar } = useDispatch( editPostStore );
+
+	const handleClick = event => {
+		event.preventDefault();
+		// Open the sidebar if not open
+		if ( ! isEditorSidebarOpened ) {
+			openGeneralSidebar( 'edit-post/block' );
```
[the remark this answers is not in the document]
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js:77]: Ooh, excellent catch!
All different editor variations have their own sidebar name.

- Post: `edit-post/block`
- Site: `edit-site/block-inspector`
- Widget: `edit-widgets/block-inspector`

The tricky part is that IIRC there's no unified way to know that: `isEditorSidebarOpened` only exists on the post editor, site and widget editors have to come up with their own creative ways.

I'll open a follow-up issue to this because it's not worth it to investigate it here.

[the remark this answers is not in the document]
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/toolbar-control.js:77]: https://github.com/Automattic/jetpack/issues/23443

**Comment by BogdanUngureanu** [comment]
Works for me too. I did find a small issue (more like inconsistency), but it's unrelated to these changes. I've [opened a new issue for it](https://github.com/Automattic/jetpack/issues/23444).

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js [hunk 3]
```diff
@@ -0,0 +1,67 @@
...
+	setSelectedProductId = () => {},
+} ) {
+	const products = useSelect(
+		select =>
+			select( jetpackMembershipProductsStore ).getProducts(
+				selectedProductId,
+				setSelectedProductId
+			),
+		[]
+	);
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:31]: This selector only fetches data on mount, which is the same behaviour as before.

File: projects/plugins/jetpack/extensions/blocks/premium-content/edit.js [hunk 4]
```diff
@@ -82,148 +57,21 @@ const defaultString = null;
...
-	const wrapperRef = useRef( null );
-	useOutsideAlerter( wrapperRef, hasSelectedInnerBlock );
-
-	const { isSelected, className } = props;
+	const setSelectedProductId = productId => setAttributes( { selectedPlanId: productId } );
+	const { apiState } = useProducts( {
+		selectedProductId: selectedPlanId,
+		setSelectedProductId,
+		shouldSkipResolver: isPreview,
+	} );
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/premium-content/edit.js:74]: When the block is rendered in preview context (e.g. in the inserter or transform popup), we skip the `getProducts` resolver, to avoid fetching plans while not needed.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/selectors.js [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+	siteSlug: state.siteSlug,
+} );
+
+export const getApiState = state => state.apiState;
+
+export const getConnectUrl = state => state.connectUrl;
+
+export const getProducts = state => state.products;
+
+export const getProductsNoResolver = state => getProducts( state );
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/selectors.js:14]: Just in the off-chance this is not clear:

The `getProducts` selector, when called through Redux, is passed through the `getProducts` resolver that fetches the products from the backend and add them to the state.

`getProductsNoResolver` (the name is consistent with [Core Gutenberg](https://github.com/WordPress/gutenberg/blob/00a7f89f80cea844e363bbe7789fde1d574ae8ad/packages/core-data/src/selectors.js#L238)) bypasses the resolver calling `getProducts` directly, which means we get to save an API call if not needed.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+		);
+		return {
+			apiState: getApiState(),
+			connectUrl: getConnectUrl(),
+			shouldUpgrade: getShouldUpgrade(),
+		};
+	} );
+
+	return { apiState, connectUrl, products, shouldUpgrade };
+}
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js:37]: With the latest Redux refactor, this hook has basically become a simple helper if consumers need some of the data provided by the product management component.

All of this can be done directly with Redux if needed, but I think this is a slightly nicer, more controlled way of exposing a whole lot of complexity.

In my opinion, blocks shouldn't need to use this, but simply rely on the component itself.
Though, Premium Content is _complicated_ and has some logic relying on `apiState`, so I think this hook comes in handy for edge cases.

File: projects/plugins/jetpack/extensions/blocks/premium-content/edit.js [hunk 7]
```diff
@@ -82,148 +57,21 @@ const defaultString = null;
...
-	}
-	//We would like to hide the tabs and controls when user clicks outside the premium content block
-	/**
-	 * @type { ContainerRef }
-	 */
-	const wrapperRef = useRef( null );
-	useOutsideAlerter( wrapperRef, hasSelectedInnerBlock );
-
-	const { isSelected, className } = props;
+	const setSelectedProductId = productId => setAttributes( { selectedPlanId: productId } );
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/premium-content/edit.js:69]: I'm not a fan of passing this function around, but I couldn't come up with a better way of sharing `setAttributes` (with a variable attribute name — all payment blocks use a different name...) with the product management component and its state. 🤔

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+/**
+ * Internal dependencies
+ */
+import { jetpackMembershipProductsStore } from './store';
+
+export default function useProducts( {
+	selectedProductId = 0,
+	setSelectedProductId = () => {},
+	shouldSkipResolver = false,
+} ) {
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js:15]: What's the benefit of using an object as an argument instead of actually using a list of arguments?

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js [hunk 9]
```diff
@@ -0,0 +1,37 @@
...
+	const { apiState, connectUrl, shouldUpgrade } = useSelect( select => {
+		const { getApiState, getConnectUrl, getShouldUpgrade } = select(
+			jetpackMembershipProductsStore
+		);
+		return {
+			apiState: getApiState(),
+			connectUrl: getConnectUrl(),
+			shouldUpgrade: getShouldUpgrade(),
+		};
+	} );
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js:34]: Should we add deps to this useSelect?

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js [hunk 10]
```diff
@@ -0,0 +1,23 @@
...
+ * Internal dependencies
+ */
+import * as actions from './actions';
+import reducer from './reducer';
+import * as resolvers from './resolvers';
+import * as selectors from './selectors';
+
+export const jetpackMembershipProductsStore = 'jetpack/membership-products';
+
+const store = registerStore( jetpackMembershipProductsStore, {
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js:16]: Register store is deprecated, I think we need to use register instead. [Github link](https://github.com/WordPress/gutenberg/blob/9d0689b7bf83688d02ede386e3d2e7d308de8d29/packages/data/src/index.js#L180)

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js [hunk 11]
```diff
@@ -0,0 +1,23 @@
+/**
+ * External dependencies
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js:2]: Typo: WordPress dependencies.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js (hunk 8 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/use-products.js:15]: Mostly personal preference, as I find it more readable and predictable.
I'm definitely not a fan of having flags (such as `shouldSkipResolver`) as regular arguments, as they become easily confusing.

For example, here it would be used like this:
```js
useProducts( selectedPlanId, setSelectedProductId, isPreview )
```
That `isPreview` is not immediately clear what it means, if it comes from the hook or from the consumer.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js (hunk 11 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js:2]: 💥

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/resolvers.js [hunk 12]
```diff
@@ -0,0 +1,87 @@
...
+	const path = addQueryArgs( '/wpcom/v2/memberships/status', {
+		source: origin === 'https://wordpress.com' ? 'gutenberg-wpcom' : 'gutenberg',
+	} );
+
+	try {
+		const response = await apiFetch( { path, method: 'GET' } );
+		if ( ! response && typeof response !== 'object' ) {
+			return;
+		}
+		const wpError = response?.errors && Object.values( response?.errors )?.[ 0 ]?.[ 0 ];
```
[the remark this answers is not in the document]
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/resolvers.js:38]: Good point, this probably requires an explanation and I'll add a comment to the code.

The error response is a [WP_Error](https://developer.wordpress.org/reference/classes/wp_error/) which looks something like this:
```
{
  errors: {
    foo: [
      'error message',
      'another error message',
    ],
    bar: [
      'error message'.
    ],
  },
}
```
As you can imagine, the tricky part is getting to those `foo` and `bar`, which are not fixed values, and are unknown.

I've skimmed the endpoint code, and there are _many_ uses of WP_Error, with different error names.

What the code does there is: convert the `errors` object into an array of its properties values (basically to remove the unknown property name); then pick the first message of the first error.

It's worth noting that I just copied the approach from before, I've just cleaned it up a little bit with the optional chaining (and you're correct, I've added one `?` too many). 🙂

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js (hunk 10 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/store/index.js]: I've updated this, and actually took the chance of moving the store to a shared, centralized location, along with `jetpack/media-source`.

Now the store is actually only registered once (it wasn't a big deal, but still), and the overall implementation is consistent with Core Gutenberg (using the actual store as `StoreDescriptor` for selectors and dispatchers).

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js [hunk 13]
```diff
@@ -0,0 +1,69 @@
...
+
+	if ( shouldUpgrade ) {
+		return null;
+	}
+
+	return (
+		<>
+			{ ! isApiConnected && !! connectUrl && (
+				<BlockControls group="block">
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:49]: Maybe we could add the `__experimentalShareWithChildBlocks` property here so that we can show the connect button when clicking on children of the block that uses this component (if they are using the supports __experimentalExposeControlsToChildren), WDYT?

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:49]: In line with my previous comment, I've seen that we are adding the ability to manage subscriptions but not to select subscriptions. Maybe we could also generalize (or merge with the manage component) this by using the controls we have in the Payments block:

Captura de pantalla 2022-03-18 a las 12 39 59

WDYT?

File: projects/plugins/jetpack/extensions/blocks/premium-content/edit.js (hunk 4 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/blocks/premium-content/edit.js]: Good point.

The problem I had was that the block only rendered the control once the API was connected.
But it was the control itself that was connecting the API!

In 5fced84, I've refactored the block renderer so that now it's more predictable, and the control component is always rendered (it determines internally if its UI needs to be displayed)
This removes a whole lot of awkwardness, making the block more readable IMHO.

As a side effect, we also don't need the `useProducts` hook anymore, so I've deleted it.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js (hunk 13 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:49]: > add the __experimentalShareWithChildBlocks property

@rcrdortiz I've tried it but it wasn't working immediately, and I've ignored it for now.
We should definitely try to share the controls with children blocks, I agree, but given that's not a regression, we can work on it separately.
Feel free to add a follow-up issue for it, earmarked for the next iteration. 🙂 

> adding the ability to manage subscriptions but not to select subscriptions

That's because the Premium Content approach has the selection integrated with the toolbar, which is arguably the better UX.
I'm ok with having the selection in the sidebar too, but I'd say it's a low priority for now.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js [hunk 14]
```diff
@@ -0,0 +1,69 @@
...
+					<StripeConnectToolbarButton blockName="premium-content" connectUrl={ connectUrl } />
```
Comment (BogdanUngureanu) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:50]: Was the blockName left hardcoded on purpose to "premium-content"?

Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:50]: Nope, not on purpose. 😢

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js [hunk 15]
```diff
@@ -0,0 +1,126 @@
...
+	const [ currency, setCurrency ] = useState( 'USD' );
+	const [ price, setPrice ] = useState( 5 );
+	const [ interval, setInterval ] = useState( '1 month' );
+
+	const intervalOptions = [
+		{ label: __( 'Month', 'jetpack' ), value: '1 month' },
+		{ label: __( 'Year', 'jetpack' ), value: '1 year' },
+	];
+	if ( allowCreateOneTimeInterval ) {
+		intervalOptions.concat( [ { label: __( 'One-Time Payment', 'jetpack' ), value: 'one-time' } ] );
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:45]: We should update the array, the concat method returns a new array that is the combination of both. Since we aren't storing the new array we can never create "One-time Payments".

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js [hunk 16]
```diff
@@ -0,0 +1,126 @@
...
+			{ siteSlug && (
+				<ExternalLink
+					href={ `https://wordpress.com/earn/payments/${ siteSlug }` }
+					className={ 'product-management-control-inspector__link-to-earn' }
+				>
+					{ __( 'Manage your subscriptions.', 'jetpack' ) }
+				</ExternalLink>
+			) }
+			<PanelBody
+				title={ __( 'Add a new subscription', 'jetpack' ) }
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:71]: Maybe we could change this text for:
`Add this payment plan`
Not all the plans we can configure are subscriptions, it's strange to add a one-time payment and then click on "Add a new subscription".

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js [hunk 17]
```diff
@@ -0,0 +1,70 @@
...
+	return (
+		<>
+			{ ! isApiConnected && !! connectUrl && (
+				<BlockControls group="block">
+					<StripeConnectToolbarButton blockName={ blockName } connectUrl={ connectUrl } />
+				</BlockControls>
+			) }
+			{ isApiConnected && (
+				<>
+					<ProductManagementInspectorControl
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/index.js:56]: I think we have a problem with the current approach. This approach doesn't play well with blocks that have their own InspectorControls.  We end up with more than one InspectorControls declaration. I don't think there is an easy solution to this problem, but maybe we could export each individual control type (ProductManagementInspectorControl and ProductManagementToolbarControl), and just have them return the PanelBody so that we can compose the controls as needed.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js [hunk 18]
```diff
@@ -0,0 +1,126 @@
...
+	return (
+		<InspectorControls>
+			{ siteSlug && (
+				<ExternalLink
+					href={ `https://wordpress.com/earn/payments/${ siteSlug }` }
+					className={ 'product-management-control-inspector__link-to-earn' }
+				>
+					{ __( 'Manage your subscriptions.', 'jetpack' ) }
+				</ExternalLink>
+			) }
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:69]: Could we add this external link inside the "Add a new subscription" or create a "Management" panel.? It looks a bit odd to just have a link floating in the middle of the controls.
Captura de pantalla 2022-03-19 a las 1 22 55

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js [hunk 19]
```diff
@@ -0,0 +1,126 @@
...
+								onChange={ value => setInterval( value ) }
+								options={ intervalOptions }
+								value={ interval }
+							/>
+						</PanelRow>
+						<PanelRow>
+							<Button onClick={ handleSubmit } variant="secondary">
+								{ __( 'Add subscription', 'jetpack' ) }
+							</Button>
+						</PanelRow>
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:120]: In the Payments block, we are showing a link to the fees associated with our service. I think it would be a good idea to add it inside the controls so that we have a heterogeneous way of showing this information and therefore we wouldn't need to implement this link in each individual block that uses these controls.

The end result would look like this:
Captura de pantalla 2022-03-19 a las 10 10 01
These would be the changes needed:
```suggestion
						<PanelRow>
							<Button onClick={ handleSubmit } variant="secondary">
								{ __( 'Add subscription', 'jetpack' ) }
							</Button>
						</PanelRow>
						<PanelRow>
							<ExternalLink href="https://wordpress.com/support/wordpress-editor/blocks/payments/#related-fees">
								{ __( 'Read more about Payments and related fees.', 'jetpack' ) }
							</ExternalLink>
						</PanelRow>
```
WDYT?

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js (hunk 16 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:71]: I have intentionally not done any copy changes, as that will require some specific handling that I'd rather do in a follow up.

**Review by rcrdortiz — DISMISSED** [review]

**Comment by rcrdortiz** [comment]
Tests well for me, great job!!

File: projects/plugins/jetpack/extensions/store/membership-products/resolvers.js [hunk 20]
```diff
@@ -0,0 +1,96 @@
...
+			onError( wpError, registry );
+			return;
+		}
+
+		const postId = registry.select( editorStore ).getCurrentPostId();
+
+		dispatch( setConnectUrl( getConnectUrl( postId, response.connect_url ) ) );
+		dispatch( setShouldUpgrade( response.should_upgrade_to_access_memberships ) );
+		dispatch( setSiteSlug( response.site_slug ) );
+
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/store/membership-products/resolvers.js:59]: Here we are missing the upgrade_url value from the response. We use this value to redirect the user to this URL if he doesn't have a valid Jetpack plan. 
I can add this functionality in the Payment button block issue if you prefer.

**Review by jeherve — DISMISSED** [review]
This seems to test well! 🚢

**Comment by Copons** [comment]
Whoopsie, my last commit https://github.com/Automattic/jetpack/pull/23427/commits/4a100cb142cefbdce120294e1ad69750697c3c1b dismissed the approvals.
It's not a functional change (it simply adds a new property to the new store which will be used by future PRs) so I'm gonna re-approve and merge this as soon as tests are green. 🙂

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js (hunk 18 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:69]: Added to our backlog.

File: projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js (hunk 19 above)
Comment (Copons) [reply projects/plugins/jetpack/extensions/shared/components/product-management-controls/inspector-control.js:120]: Added to our backlog.

**Review by mdbitz — APPROVED** [review]
Verified changes was the addition of setUpgradeUrl , no functional change.

Re-Approved
