### PR TITLE
My Jetpack: Stats product card - various improvements

### LINKED ISSUE #35035: My Jetpack: Stats Module Shows as Inactive without Plan
### Impacted plugin

Jetpack

### Quick summary

When Jetpack is initially installed and/or hasn't yet added a free or paid stats plan, "My Jetpack" reports that the module is inactive even though stats are being collected

### Steps to reproduce

1. On a new site, connect site to Jetpack
2. Navigate to "My Jetpack"
3. See that the stats module says it is "inactive" even though it has been activated and is collecting information

### A clear and concise description of what you expected to happen.

The stats screen shouldn't show the "Inactive" status since stats are actually working. Perhaps it could say "Choose a plan" or something else to indication the user needs to pick a stats plan.

### What actually happened

My Jetpack view:

Annotation on 2024-01-15 at 08-44-19

View in Stats (shows upgrade prompt):

Annotation on 2024-01-15 at 08-47-41

View in "My Jetpack" once plan (free or paid) is added:

Annotation on 2024-01-15 at 08-44-52

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by elliottprogrammer**
This PR makes various improvements to the My Jetpack "Stats" product card.  See 'Proposed changes' below:
and see project task: https://github.com/Automattic/jetpack-marketing/issues/505

## Proposed changes:

* Make large Stats card show by default (if Jetpack plugin activated) & remove small stats card.
* When site hasn't established first site connection, show "Learn more" CTA.
* When connected, allow user to view detailed stats, as well as upgrade/purchase a Stats plan. (two buttons)
* Display either "commmercial" interstitial or "pwyw" interstitial depending on if site "is commercial" and/or if site has a purchased Stats plan.

**Still TODO: (in a separate follow-up PR)**
- Show Stats card when stand-alone plugin(s) activated (Jetpack plugin not installed), and add relevant action button labels/behaviors

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes: https://github.com/Automattic/jetpack/issues/35035
Related to: https://github.com/Automattic/jetpack-marketing/issues/505

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

- Spin up a jurassic.ninja site with Jetpack Beta plugin pointing to this branch (`update/my-jetpack-stats-section`).
- While Jetpack not connected yet, go to My Jetpack page.
- Verify you see the large Stats card at the top. Status: "inactive", CTA button label: "Learn more".  CTA action: `admin.php?page=my-jetpack#/add-stats`
- Click the "Learn more" button. Verify the Stats interstitial CTA reads, "Get Stats" (not "Install Stats").
- Click the ⬅️ Back button, to go back to My Jetpack.
- Next, connect Jetpack, but do not "Authorize".  (Site-only connection)
- Go back to the My Jetpack page.
- Examine the large Stats card. Verify the Stats card status is now "Active" and the primary action button reads, "Upgrade", and secondary button reads, "See detailed stats".
- Verify the "Upgrade button points to `?page=stats#!/stats/purchase/:blogId` and verify "See detailed stats" points to `?page=stats`.
- Next connect user account (Establish user-connection).
- Go back to the My Jetpack page. Verify the Stats card status is "Active" and the primary action button reads, "Upgrade", and secondary button reads, "See detailed stats".
- Go to Jetpack --> Settings, scroll down to footer, click the "Modules" link.
- Search "Stats", then click the "Deactivate" button for Jetpack Stats.
- Navigate back to My Jetpack page, and verify the Stats action button reads "Activate" and the Status is "Module disabled"
- In the Stats card, click the "Activate" button and verify the Stats module gets activated and the Stats card status changes to "Active".
    - Note: I think there is a bug on the Activate button where, on click of the button we should be preventing the browser click event default action, ie.- `event.preventDefault()`.  Will tackle this in a separate PR.
    (You may need to refresh/reload the page, maybe not).
- Now disconnect Jetpack (from the "Manage connection" button, either on Jetpack Dashboard or My Jetpack).
- Go to My Jetpack page. Verify the Stats CTA reads, "Connect Jetpack to use Stats" and the status is "Needs connection".
- Click the Connect button. Connect Jetpack (user connection).
- Click the "Upgrade" button and purchase the Stats PWYW plan.
- After purchased, verify the "Upgrade" button is no longer available.
- In Sore Admin, remove the PWYW plan you just purchased.
- Next, purchase Stats Commercial (any tier..., except **_not_** the highest tier (more than 1m views))
- The "Upgrade" button should still be visible.
- Now purchase the Stats commercial, the highest tier (more than 1m views).
- Verify the "Upgrade" button is no longer available when you own the highest tier of Stats commercial.

### CODE REVIEW

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx [hunk 1]
```diff
@@ -244,6 +244,15 @@ const ProductCard = props => {
 		onDeactivateStandalone();
 	}, [ slug, onDeactivateStandalone, recordEvent ] );
 
+	/**
+	 * Called when "See detailed stats" button is clicked.
+	 */
+	const onDetsailedStatsClick = useCallback( () => {
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Looks like there is a typo here :)

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx [hunk 2]
```diff
@@ -244,6 +244,15 @@ const ProductCard = props => {
...
+		recordEvent( `jetpack_myjetpack_stats_card_seedetailedstats_click`, {
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Nitpick, could this match with the button wording as `jetpack_myjetpack_stats_card_view_detailed_stats_click`?

Also, should these be single quotes instead of backticks?

File: projects/packages/my-jetpack/_inc/components/product-cards-section/index.jsx [hunk 3]
```diff
@@ -29,7 +25,7 @@ const ProductCardsSection = () => {
 		boost: BoostCard,
 		search: SearchCard,
 		videopress: VideopressCard,
-		stats: showJetpackStatsCard ? StatsCard : null,
+		// Stats card is shown in the <StatsSection/> component.
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/product-cards-section/index.jsx:28]: thanks for this comment

File: projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx [hunk 4]
```diff
@@ -103,7 +103,9 @@ const ActionButton = ( {
 					onClick: onAdd,
 				};
 			case PRODUCT_STATUSES.ACTIVE: {
-				const buttonText = __( 'View', 'jetpack-my-jetpack' );
+				const defaultButtonText = __( 'View', 'jetpack-my-jetpack' );
+				const statsButtonText = __( 'View detailed stats', 'jetpack-my-jetpack' );
+				const buttonText = slug === 'stats' ? statsButtonText : defaultButtonText;
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: Hmmm. I think I'd be OK just leaving this as "View" for now to avoid the conditional statement here. 
What do you think?

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx [hunk 5]
```diff
@@ -271,16 +280,30 @@ const ProductCard = props => {
...
+							<Button
+								size="small"
+								weight="regular"
+								variant={ 'secondary' }
+								href={ 'admin.php?page=stats' }
+								onClick={ onDetsailedStatsClick }
+							>
+								{ __( 'See detailed stats', 'jetpack-my-jetpack' ) }
+							</Button>
+						) }
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: I think we should avoid this conditional rendering here if possible. If we wanted to do something similar for other cards, this pattern would become difficult to manage 🤔 

I am noticing the `additionalActions` prop on the `ActionButtons` component - maybe we use that for now since that pattern exists? I think it creates a small drop-down on the button. The backup card has a working example of this.

File: projects/packages/my-jetpack/_inc/components/stats-section/index.jsx [hunk 6]
```diff
@@ -1,16 +1,21 @@
...
- */
+
 const StatsSection = () => {
 	const { statsCounts } = useStatsCounts();
 	const counts = statsCounts?.past_seven_days || {};
 	const previousCounts = statsCounts?.between_past_eight_and_fifteen_days || {};
+	return (
+		<ProductCard admin={ !! window?.myJetpackInitialState?.userIsAdmin } slug="stats" showMenu>
+			<StatsCards counts={ counts } previousCounts={ previousCounts } />
+		</ProductCard>
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/stats-section/index.jsx]: It's nice that we can re-use the `<ProductCard>` here as well!

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 7]
```diff
@@ -169,40 +175,30 @@ public static function has_required_plan() {
 	 * @return boolean
 	 */
 	public static function is_upgradable() {
-		$purchases_data = Wpcom_Products::get_site_current_purchases();
-		if ( is_wp_error( $purchases_data ) ) {
+		$connection = new Connection_Manager();
+		if ( ! $connection->is_connected() || ! $connection->is_user_connected() ) {
```
Comment (jboland88) [inline projects/packages/my-jetpack/src/products/class-stats.php]: Stats should not need a user connected, so I think we can just check the site connection here

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 8]
```diff
@@ -145,21 +160,12 @@ public static function get_wpcom_free_product_slug() {
 	 * @return boolean
 	 */
 	public static function has_required_plan() {
-		$purchases_data = Wpcom_Products::get_site_current_purchases();
-		if ( is_wp_error( $purchases_data ) ) {
+		// The only requirement for Stats is a connection.
+		$connection = new Connection_Manager();
+		if ( ! $connection->is_connected() || ! $connection->is_user_connected() ) {
```
Comment (jboland88) [inline projects/packages/my-jetpack/src/products/class-stats.php]: Hmmm, this connection check seems out of place in the `has_required_plan` function 🤔 

I wonder if we should add another static property on the product class called `requires_site_connection`. If the product requires a site connection and the site is not connected, I think we could have the `get_status` function return "inactive".

We could probably remove this function with a change like that.

What do you think?

**Review by jboland88 — CHANGES_REQUESTED** [review]
I have not had a chance to do the functional testing yet, wanted to go ahead and submit some code comments.

I think there are a few things we can do to make the changes contain fewer "stats only" conditionals in the code and rely on or create some patterns that we can use elsewhere

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 5 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Yes good point @jboland88 , I agree we should avoid the conditional rendering. Yes sounds good, I'll pass the additional action in as a prop. Thanks!👍
However do we really want the "See your stats" and "Upgrade" button together in a dropdown? If so, which button is showing by default, the "Upgrade" or "View your stats"?
Another idea is I could add in the ability to _also_ show a secondary button via an additional prop (in ActionButton component), ie.- prop '`secondaryAction`'. (in which case, I could then maybe rename the `additionalActions` prop to `dropdownActions` or something like that, just for more clarity)
I kinda like the appearance of the 2 buttons on the Stats card (both visible at the same time without having to click a dropdown). But I don't feel strongly either way, I just thought I'd mention the idea and let you and @augurlu decide which you like best.  Let me know which way sounds best to you. 🙂

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 2 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Yeah, I was just matching the event that is already previously in use for the "View your stats" button. If I change it, we will have a break in data, where the previous tracking data on the button is recorded with the event name `jetpack_myjetpack_stats_card_seedetailedstats_click` and then all new clicks on the button from this point forward will be recorded on a new, different event name (`jetpack_myjetpack_stats_card_view_detailed_stats_click`). I think ideally we want to avoid breaking up the data, right?

Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Ahh yes, single quotes instead of backticks. I just copied it over like that, so it was already like that previously, but I agree, single quotes is most commonly what we use when defining tracking events. 👍

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 1 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: Good catch, thank you! 😊

File: projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx (hunk 4 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: The button has always previously read "View detailed stats" so I think it would be more ideal not to change it, however if I pass the button in as prop, as you mention in your feedback below, I can avoid/remove the conditional statement here, but still render the button the same as it was displayed previously. 😉

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 8 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php]: Yes that sounds like a good solution, thanks @jboland88!  Although the 'detailed' Stats page currently will not show/render (is blocked) for users without a user-connection. So I'll need to make sure we can open it to users without a user-connection. I'll check if I can accomplished this fairly easily. 👍

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 7 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php]: My same comment above (about the 'detailed' Stats page being blocked to users without a user-connection) applies here too.

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 2 above)
Comment (jboland88) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: > Yeah, I was just matching the event that is already previously in use for the "View your stats" button. If I change it, we will have a break in data, where the previous tracking data on the button is recorded with the event name jetpack_myjetpack_stats_card_seedetailedstats_click and then all new clicks on the button from this point forward will be recorded on a new, different event name

Aha, that makes sense - I think it's good to leave it then!

File: projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx (hunk 4 above)
Comment (jboland88) [reply projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: Ah yes - I think my main concern was adding an extra conditional. If we can avoid the stats-specific code here then I think the wording "View detailed stats" is great

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 5 above)
Comment (jboland88) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: > Another idea is I could add in the ability to also show a secondary button via an additional prop (in ActionButton component), ie.- prop 'secondaryAction'. (in which case, I could then maybe rename the additionalActions prop to dropdownActions or something like that, just for more clarity)

Hmm, I do like this idea as it establishes a re-usable pattern. I also like the appearance of the two buttons here when the user has working stats but can also upgrade.

Let's move in this direction of showing a secondary button based on the props passed in from the individual product card component.

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 7 above)
Comment (jboland88) [reply projects/packages/my-jetpack/src/products/class-stats.php]: Aha - gotcha. I was not aware that the detailed stats page was currently requiring a user connection.

I think changing the detailed stats page to use only a site connection will be out of scope for this PR. Does the detailed stats page prompt for a user connection if there is not one? Perhaps we can still link there and then the user can complete the connection flow at that point?

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 8 above)
Comment (jboland88) [reply projects/packages/my-jetpack/src/products/class-stats.php]: > Stats page currently will not show/render (is blocked) for users without a user-connection. So I'll need to make sure we can open it to users without a user-connection. I'll check if I can accomplished this fairly easily. 👍

Maybe we can still link there with the "Show detailed stats" CTA for now and allow the user to connect from that page if they are not currently connected? I think changing the connection required for that page is out of scope for this PR.

**Comment by kangzj** [comment]
Thanks for working on this @elliottprogrammer 👍 

I have the same feeling as @jboland88 - it might be worth to make some of the code more general for the future.

I also want to add that, IMHO, the root of the problem is that the status of a module is tied to the requirements of the product, which doesn't really make a lot of sense. The module status should be an independent status which we toggle on / off based on the purchase and the requirements of the product or by users. It'll be awesome to see them untangled in the future. Similar applies to the action button too - the abstraction doesn't satisfy the business scenarios.

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 8 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php]: @jboland88, Yes I agree changing the connection required for Stats is out of scope for this PR.
The way I made it work now is: If there is no connection, the card shows 'Inactive' with a "Learn more" button which points to the Stats product interstitial (Same behavior as the other products), which when clicked will lead to the "connect after checkout" flow with Stats commercial in the cart.
As for the `has_required_plan()` function, I removed the connection check, but instead simply just return `true` because a purchased plan is not currently a requirement for Stats. Stats functionality works right out of the box.
What do you think?

File: projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx (hunk 4 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: @jboland88, For when the primary "Upgrade" button is not available/showing to the user (in the Stats card), I created a prop, `primaryActionOverride` which allows any product (in this case, Stats), to override/customize the display and behavior of any primary action button, different than the default way it is defined in `action-button.jsx`.  For Stats, we want to change the "View" button to instead display "View detailed stats". This is one way, a small refactor that works for now... 
Although I think ideally each product should define and pass it's own action buttons it wants to display, rather than having them all strictly defined one way for all products in `action-button.jsx`. Although this would be quite a larger refactor, so I thought I would mention it here, so we can plan it for a followup PR.  Your thoughts?

File: projects/packages/my-jetpack/_inc/components/product-card/index.jsx (hunk 5 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/product-card/index.jsx]: I created a (optional) `secondaryAction` prop that allows any product to display a secondary action button, if desired. 👍

File: projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx (hunk 4 above)
Comment (jboland88) [reply projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: >  created a prop, primaryActionOverride which allows any product (in this case, Stats), to override/customize the display and behavior of any primary action button

Yes, I think this is a good solution for where we are now - nice one 👍 

>  ideally each product should define and pass it's own action buttons it wants to display, rather than having them all strictly defined one way for all products in action-button.jsx. Although this would be quite a larger refactor, so I thought I would mention it here, so we can plan it for a followup PR

This would be interesting yes - I do think we'd want to customize the text showing on different buttons at different times. I think that would be good to follow up on as we are iterating on the product cards

Comment (jboland88) [reply projects/packages/my-jetpack/_inc/components/product-card/action-button.jsx]: It does look like the conditional statement is still there and we should be able to remove that now :)

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 9]
```diff
@@ -145,21 +160,46 @@ public static function get_wpcom_free_product_slug() {
...
-			return false;
-		}
-		if ( is_array( $purchases_data ) && ! empty( $purchases_data ) ) {
-			foreach ( $purchases_data as $purchase ) {
-				if ( str_starts_with( $purchase->product_slug, 'jetpack_stats' ) ) {
-					return true;
-				}
-				if ( str_starts_with( $purchase->product_slug, 'jetpack_complete' ) ) {
-					return true;
+		return true;
```
Comment (jboland88) [inline projects/packages/my-jetpack/src/products/class-stats.php]: IIRC the parent class function `has_required_plan` returns true by default, so we can probably remove this function from the stats child class.

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 10]
```diff
@@ -145,21 +160,46 @@ public static function get_wpcom_free_product_slug() {
...
+	}
+
+	/**
+	 * Gets the 'status' of the Stats product
+	 *
+	 * @return string
+	 */
+	public static function get_status() {
```
Comment (jboland88) [inline projects/packages/my-jetpack/src/products/class-stats.php:162]: Hmmm, It feels a bit strange to duplicate the `get_status` function here in the child class 🤔 

Is this replicated here to handle the user connection condition differently?

What happens if we remove this and set `$requires_user_connection` back to false? If the user goes to "view detailed stats" and are not connected, could they complete the connection from the detailed stats page?

FWIW, I am able to access the detailed stats page with just a site connection while testing?

File: projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx [hunk 11]
```diff
@@ -150,7 +150,7 @@ export default function MyJetpackScreen() {
 							<GlobalNotice message={ message } options={ options } clean={ clean } />
 						</Col>
 					) }
-					{ isStatsModuleActive && (
+					{ showJetpackStatsCard && (
```
Comment (jboland88) [inline projects/packages/my-jetpack/_inc/components/my-jetpack-screen/index.jsx:153]: In theory, we'd like to show the stats card all the time, even if the main Jetpack plugin is not installed (like we do with all the other cards)

However, after tinkering with this a bit, I am realizing that there a some other implications that we'd need to work out in doing this. For example, what to show on the card CTA when there is no site connection? "Learn more"? "Fix site connection"?

I think we can leave this as-is in this PR and work on having the stats card show up for other standalone plugins in another PR

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 12]
```diff
@@ -43,6 +44,20 @@ class Stats extends Module_Product {
 	 */
 	public static $plugin_filename = self::JETPACK_PLUGIN_FILENAME;
 
+	/**
+	 * Stats only requires site connection, not user connection
+	 *
+	 * @var boolean
+	 */
+	public static $requires_user_connection = true;
```
Comment (jboland88) [inline projects/packages/my-jetpack/src/products/class-stats.php]: Wasn't this set to `false` in the first revision? Curious why it is `true` now?

**Review by jboland88 — DISMISSED** [review]
This looks pretty close - I think the only blocker is replicating the `get_status` function in the stats class. I think we can avoid this by just setting `$requires_user_connection` to `false` for the stats class.

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 10 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php:162]: > FWIW, I am able to access the detailed stats page with just a site connection while testing?

Hmm, on my local Jetpack dev env as well as a Jurassic Ninja site, starting off as connected, if I click the "manage connection" link from either the Jetpack Dashboard or from the bottom of My Jetpack, then click "Disconnect". Now (while not connected) if I try to load page: `/wp-admin/admin.php?page=stats`, I get a page that says, "Sorry, you are not allowed to access this page." (See screenshot) ⤵️

Markup 2024-02-05 at 17 28 23

JN site
Markup 2024-02-05 at 18 18 40

Maybe I'm misunderstanding the meaning of "site connection"?  What Steps are you taking to establish only a "site connection"?

Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php:162]: > Hmmm, It feels a bit strange to duplicate the get_status function here in the child class 🤔
>
> Is this replicated here to handle the user connection condition differently?
>
> What happens if we remove this and set $requires_user_connection back to false? If the user goes to "view detailed stats" and are not connected, could they complete the connection from the detailed stats page?

Yes, with the goal of making the "Learn more" button show when there is no connection (just like the other product cards), the way the `get_status()` function works is, when `$requires_user_connection` is `false` then `get_status()` will check `has_required_plan()` and if it's `false`, the "Learn more" button shows.  This works for all the other cards because `has_required_plan()` returns `false` for the other products, I believe, because they all require a plan to work.  Stats is different because the only thing required for Stats to work (currently) is a connection (not a plan).  That being said, for Stats to show the "Learn more" button when there's no connection, we either have to, 1: Set `$requires_user_connection` to `false` and then return false in `has_required_plan()` when there is no connection (what I did previously, in the first revision). OR 2: We set `$requires_user_connection` to `true` but then have `get_status()` return '`needs_purchase_or_free`' instead of '`error`' when there is no connection (what I did in this revision). Which incidentally, I found a cleaner way to do this, rather than replicating (with a minor change) the whole contents of the `get_status()` function, which is:
```
public static function get_status() {
	$status = parent::get_status();
	if ( $status === 'error' ) {
		$status = 'needs_purchase_or_free';
	}
	return $status;
}
```

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 12 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php]: I answered this in https://github.com/Automattic/jetpack/pull/35355#discussion_r1479115067 I left above.

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 10 above)
Comment (jboland88) [reply projects/packages/my-jetpack/src/products/class-stats.php:162]: > Maybe I'm misunderstanding the meaning of "site connection"? What Steps are you taking to establish only a "site connection"?

Good question. So, to get a site-only connection is a bit of a workaround at the moment.

Start on the connection screen like normal and click the button to connect.
Screenshot 2024-02-06 at 8 37 13 AM

Wait until you see the user connect screen, but do not authorize the user connection. Navigate back to the site instead. Now, at the bottom of My Jetpack, you should see that the site is connected, but the user is not.
Screenshot 2024-02-06 at 8 39 51 AM

The site is now "site connected" and has access to some Jetpack features, which should include the stats page.

File: projects/packages/my-jetpack/src/products/class-module-product.php [hunk 13]
```diff
@@ -86,7 +86,7 @@ public static function is_module_active() {
 	 */
 	public static function get_status() {
 		$status = parent::get_status();
-		if ( 'active' === $status && ! static::is_module_active() ) {
+		if ( 'inactive' === $status && ! static::is_module_active() ) {
```
Comment (elliottprogrammer) [inline projects/packages/my-jetpack/src/products/class-module-product.php:89]: `'active' === $status` does not seem correct here, and it doesn't work properly that way. I don't see how the status could be 'active' and the module be **not** active.
Anyway, I corrected this to `'inactive' === $status` which makes more sense and it works correctly, as expected now.

File: projects/packages/my-jetpack/_inc/components/stats-section/index.jsx [hunk 14]
```diff
@@ -1,16 +1,64 @@
...
+		[ PRODUCT_STATUSES.ERROR ]: {
+			label: __( 'Connect Jetpack to use Stats', 'jetpack-my-jetpack' ),
+		},
+	};
 
-	return <StatsCards counts={ counts } previousCounts={ previousCounts } />;
+	return (
+		<ProductCard
+			admin={ userIsAdmin }
+			slug={ 'stats' }
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/stats-section/index.jsx:54]: Very small nitpick, I see this is used here and in the tracks event call, could be slightly better to move this to a top level variable

Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/_inc/components/stats-section/index.jsx]: Very small nitpick, I see this is used here and in the tracks event call, could be slightly better to move this to a top level variable

File: projects/packages/my-jetpack/src/products/class-stats.php [hunk 15]
```diff
@@ -43,6 +44,20 @@ class Stats extends Module_Product {
...
+	 * Stats only requires site connection, not user connection
+	 *
+	 * @var boolean
+	 */
+	public static $requires_user_connection = false;
+
+	/**
+	 * Stats does not have a standalone plugin (yet?)
+	 *
+	 * @var bool
```
Comment (CodeyGuyDylan) [inline projects/packages/my-jetpack/src/products/class-stats.php:57]: Another nitpick, above says `@var boolean` but here it says `@var bool`. These should be the same

**Review by CodeyGuyDylan — DISMISSED** [review]
Just a couple nitpicks but it all tested well and looks good to me, nice job working through all possible states!

File: projects/packages/my-jetpack/_inc/components/stats-section/index.jsx (hunk 14 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/_inc/components/stats-section/index.jsx]: Ahh yeah, makes sense. It's used in 3 different places.
Ok, I created a top-level var for the slug. 👍

File: projects/packages/my-jetpack/src/products/class-stats.php (hunk 15 above)
Comment (elliottprogrammer) [reply projects/packages/my-jetpack/src/products/class-stats.php:57]: Good catch, thanks!
Yeah, the real PHP type is "bool", so I made them both bool. 👍

**Review by IanRamosC — APPROVED** [review]
Tests as expected and feedback has been addressed! 👍🏾 :shipit:
