### PR TITLE
Widgets: shows a warning for Admin users when Simple Payments is not enabled.

### LINKED ISSUE #9777: Customizer: add WP-Admin/Admin user only warnings for Simple Payments
After the changes on #9650, the Simple Payments product no longer show on downgraded sites, neither on the post and pages, nor in the upcoming Widget. There's an opportunity to warn the user on the WP-Admin interface if there are active products. Also, on the site post or page where the product is published.

#### Steps to reproduce the issue

1. Add a Simple Payments Button to a post or page on a Business Site
2. Downgrade the site to Free.
3. Navigate to the post or page where the SP button was added.

#### What I expected

As a site administrator, to see a warning about why the product is no longer showing.

#### What happened instead

The page does not show the SP button.

### PR DESCRIPTION
**Pull request by rodrigoi**
Fixes #9777

#### Changes proposed in this Pull Request:

Adds a warning for admin users when there are Simple Payments products published on pages/posts or as a Widget and Simple Payments is disabled.

| Admins | Non-Admins |
| - | - |
| screen shot 2018-07-01 at 11 56 26 | screen shot 2018-07-01 at 11 57 05 |

The same warning appears on the Customizer when the user wants to add or edit a Simple Payments Widget. The user is not allowed to edit or add new products, but the Widget itself can be removed.

screen shot 2018-07-01 at 11 58 01

If for some reason the user bypasses this restrictions to show the product, it will still fail due to WordPress.com backend checks.

screen shot 2018-07-01 at 12 15 09

#### Testing instructions:

* Get a Professional Subscription on a Jetpack site.
* Add a Simple Payment Product to a Page/Post and as a Widget, and publish the changes.
* Navigate to the page/post: the site should show the product and the widget for both admin, non-admins and logged out users.
* Cancel the Professional Subscription
* Navigate to the page/post: the site should show the warning for admin users, and for non-admin and anonymous users it shouldn't show a warning nor the product.

Also, some scripts should not load when the warning is shown.

#### Proposed changelog entry for your changes:

* Adds a Admin only warning when Simple Payments is disabled, but there are products published.

### CODE REVIEW

File: modules/simple-payments/simple-payments.php [hunk 1]
```diff
@@ -155,7 +154,28 @@ function parse_shortcode( $attrs, $content = false ) {
...
+		}
+		$css_prefix = self::$css_classname_prefix;
+
+		return "
+<div class='{$data['class']} ${css_prefix}-wrapper'>
+	<div class='${css_prefix}-product'>
+		<div class='${css_prefix}-details'>
+			<div class='${css_prefix}-purchase-message show error' id='{$data['dom_id']}-message-container'>
+				<p>" . sprintf(
+					__( 'Simple Payments is not supported by your Jetpack Plan. To learn more, and to upgrade to a supported plan, visit <a href="%s" target="_blank">these resources</a>.', 'jetpack' ),
```
Comment (dmsnell) [inline modules/simple-payments/simple-payments.php]: is a missing plan the only reason this could be `! $this->is_enbaled…`? the `output_admin_warning()` remains somewhat unspecific in its name but this string is very specific.

File: modules/widgets/simple-payments.php [hunk 2]
```diff
@@ -463,24 +464,24 @@ function update( $new_instance, $old_instance ) {
...
+					'orderby' => 'date',
+					'post_type' => Jetpack_Simple_Payments::$post_type_product,
+					'post_status' => 'publish',
+				) );
 
-			require( dirname( __FILE__ ) . '/simple-payments/form.php' );
+				require( dirname( __FILE__ ) . '/simple-payments/form.php' );
+			} else {
+				require( dirname( __FILE__ ) . '/simple-payments/admin-warning.php' );
+			}
```
Comment (dmsnell) [inline modules/widgets/simple-payments.php]: maybe an early-abort here would be nice?

```php
if ( ! $jetpack_simple_payments->is_enabled_jetpack_simple_payments() ) {
	require( dirname( __FILE__ ) . '/simple-payments/admin-warning.php' );
	return;
}

$product_posts = …
```

would at least make the differ simpler I think.

File: modules/simple-payments/simple-payments.php (hunk 1 above)
Comment (Copons) [reply modules/simple-payments/simple-payments.php]: `Simple Payments is not supported by your Jetpack Plan.`
Though, this can be output on WPCOM as well? I'd probably lose "Jetpack" for a more generic "plan".

File: modules/widgets/simple-payments/admin-warning.php [hunk 3]
```diff
@@ -0,0 +1,6 @@
+<div class='error'>
+	<p><?php echo sprintf(
+		__( 'Simple Payments is not supported by your Jetpack Plan. To learn more, and to upgrade to a supported plan, visit <a href="%s" target="_blank">these resources</a>.', 'jetpack' ),
```
Comment (Copons) [inline modules/widgets/simple-payments/admin-warning.php]: Same as https://github.com/Automattic/jetpack/pull/9842/files#r199438054

**Comment by gwwar** [comment]
Could we update the resources link to https://jetpack.com/support/simple-payment-button/#privacy ?

✅ Simple Payments still render with the correct plan:
screen shot 2018-07-13 at 2 15 06 pm
✅ Non-Admins still don't see payments. (Though titles will show up)
screen shot 2018-07-13 at 2 21 57 pm
✅ We see a warning in the customizer + published page as admins
screen shot 2018-07-13 at 2 22 01 pm
screen shot 2018-07-13 at 2 22 19 pm
✅ Warning notice on the left side as admin
screen shot 2018-07-13 at 2 39 42 pm
❌ Multiple nondismissible notices for widgets.php
screen shot 2018-07-13 at 2 31 14 pm
❌ Missing the edit warning notice widgets.php?
screen shot 2018-07-13 at 2 34 16 pm

**Comment by codebykat** [comment]
Code looks good and this tests out for me. I also got the duplicate wp-admin notices:

screen shot 2018-07-13 at 19 06 00

Weirdly, I managed to lose my post content somehow when it contained only the shortcode. I thought the Calypso editor had deleted it, but now I can't reproduce. 😠 

Anyhow, I went back and added content before the shortcode; in that case, it seems to be preserved, and is showing the embed preview as if nothing is wrong.

screen shot 2018-07-13 at 19 14 21

Should there be a notice in the post editor as well, for posts that contain a shortcode?

File: modules/widgets/simple-payments/customizer.css [hunk 4]
```diff
@@ -3,6 +3,10 @@
 	clear: both;
 }
 
+.widget-content .jetpack-simple-payments.error p {
+	color: initial;
```
[the remark this answers is not in the document]
Comment (rodrigoi) [reply modules/widgets/simple-payments/customizer.css]: This was for the benefit of WordPress.com, that has some style overrides on the customizer and show the text white, effectively hiding it. It is no longer needed with the changes on 967611d2ad7cf2e21674805a402cd191a38baab1.

**Comment by rodrigoi** [comment]
@gwwar @codebykat I've fixed the multiple warnings on 967611d2ad7cf2e21674805a402cd191a38baab1. The widget page does some magic and extract everything with a `class="error"` from the widgets `form` html returned code and puts it into the body of the page.
D16068-code has been updated as well.

I'll look into what Calypso is doing on the editor, which most likely will be fixed on a different PR.

**Comment by Copons** [comment]
I've updated the copy of the message with the Editorial's suggestions.
Now it's shorter and identical for both JP and WPCOM (except the link).

> Your plan doesn't include Simple Payments. Learn more and upgrade.

**Comment by gwwar** [comment]
✅ for widgets screen shot 2018-07-18 at 1 32 02 pm

I'm not seeing the top level wp-admin notice, but I assume that was autogenerated from Rodrigo's notes:
> The widget page does some magic and extract everything with a class="error" from the widgets form html returned

**Review by gwwar — APPROVED** [review]
Tests well for me, thanks @rodrigoi and @Copons !

**Comment by Copons** [comment]
> I'm not seeing the top level wp-admin notice

@gwwar Apparently, the magic mentioned by Rodrigo is that `widgets.php` moves all `.error` elements away from their own widgets and into the top level wp-admin notice area.

To fix this, in 967611d, the warning class changed from `jetpack-simple-payments error` (notice the space) to `jetpack-simple-payments-error` (notice the dash).

File: modules/simple-payments/simple-payments.php [hunk 5]
```diff
@@ -155,7 +154,37 @@ function parse_shortcode( $attrs, $content = false ) {
...
+			return;
+		}
+		$css_prefix = self::$css_classname_prefix;
+
+		$support_url = ( defined( 'IS_WPCOM' ) && IS_WPCOM )
+			? 'https://support.wordpress.com/simple-payments/'
+			: 'https://jetpack.com/support/simple-payment-button/';
+
+		$warning = sprintf(
+			wp_kses(
```
Comment (vindl) [inline modules/simple-payments/simple-payments.php]: Why do we need `wp_kses` here? The only variable that we pass to the string is `$support_url`, and it's already sanitized with `esc_url`. All of the other tags are hard-coded and completely controlled by us.

File: modules/widgets/simple-payments.php [hunk 6]
```diff
@@ -56,8 +56,11 @@ function __construct() {
 				)
 			);
 
-			if ( is_customize_preview() ) {
```
Comment (vindl) [inline modules/widgets/simple-payments.php]: Why did we move this check further down? Do we need to enqueue these styles for each section, or could we limit that just to customizer and posts/pages?

Comment (Copons) [reply modules/widgets/simple-payments.php]: Indeed we do need the styles for the `widgets.php` page as well.
Although, you're right, we shouldn't show it everywhere, but only in Customizer and Widgets.

File: modules/simple-payments/simple-payments.php (hunk 5 above)
Comment (Copons) [reply modules/simple-payments/simple-payments.php]: I'm not sure the localized strings are completely controlled by us.
What if a third party translator (can be an OSS contributor, an external localization company, a disgruntled a11n 😄, etc.) sneaked in some unexpected attributes to our link, and we didn't check the .po file because 🤷‍♂️ ?

File: modules/widgets/simple-payments.php (hunk 6 above)
Comment (Copons) [reply modules/widgets/simple-payments.php]: See c4a85f2

File: modules/simple-payments/simple-payments.php (hunk 5 above)
Comment (vindl) [reply modules/simple-payments/simple-payments.php]: I completely missed the translation part while reading. You are right, we need to keep `wp_kses` here. :)

Comment (vindl) [reply modules/simple-payments/simple-payments.php]: Another option would be to treat this as two separate strings for translation, since I think they could be translated independently. That way we could use `esc_html__` and move the `a` tag part outside of the translation parameter.

**Review by vindl — APPROVED** [review]
