### PR TITLE
BlogRoll: Add image fallback

### LINKED ISSUE #81952: Better handling for broken images
Images that can't load should be replaced with our placeholder

https://github.com/Automattic/wp-calypso/assets/7000684/fad55db1-471d-4aa6-afa4-b5606d24044f

### PR DESCRIPTION
**Pull request by renancarvalho**
Fixes https://github.com/Automattic/wp-calypso/issues/81952

## Proposed changes:
Add a fallback image when for any reason the blogroll item image fails to load.

## Does this pull request change what data or activity we track or use?

This PR loads an image on blogroll-item in case of failure

## Testing instructions:

* Open the editor in your jetpack site
* Make sure you have the blogroll block
* To simulate a broken image, I did:
	- Open the code editor
	- Found a blogroll item and changed the image URL to break it. ( like in this video https://github.com/Automattic/wp-calypso/issues/81952 )

* After that you should see the "wordpress" fallback image

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/blogroll/blogroll-item/edit.js [hunk 1]
```diff
@@ -17,7 +17,14 @@ function BlogrollItemEdit( { className, attributes, setAttributes } ) {
 				render={ ( { open } ) => (
 					<Button variant="link" onClick={ open } style={ { padding: 0 } }>
 						<figure>
-							<img src={ icon } alt={ name } />
+							<img
+								onError={ event => {
+									event.target.src = 'https://s0.wp.com/i/webclip.png';
+									event.onerror = null;
```
Comment (alshakero) [inline projects/plugins/jetpack/extensions/blocks/blogroll/blogroll-item/edit.js]: This seems like a mistake? `event` has no `onerror` prop. To prevent an infinite loop, I would do this:

```suggestion
									if ( event.target.src !== 'https://s0.wp.com/i/webclip.png' ) {
									     event.target.src = 'https://s0.wp.com/i/webclip.png';
									}
```

**Review by alshakero — CHANGES_REQUESTED** [review]
Tiny issue.

File: projects/plugins/jetpack/extensions/blocks/blogroll/blogroll-item/edit.js (hunk 1 above)
Comment (renancarvalho) [reply projects/plugins/jetpack/extensions/blocks/blogroll/blogroll-item/edit.js]: That makes sense @alshakero, great catch! Addressed 👍

**Review by alshakero — APPROVED** [review]
Looks great!
