### PR TITLE
AI Excerpt: avoid errors on post types that do not support excerpts

### LINKED ISSUE #33438: AI Excerpt: undefined excerpt cause wordcount to throw fatal
### Impacted plugin

Jetpack

### Quick summary

When drafting a new post from a post type that doesn't support excerpts, the excerpt is `undefined`, which causes `count()` from `@wordpress/wordcount` to throw a fatal:

https://github.com/Automattic/jetpack/blob/b3950e3eb690adb8b7e8593285825a23c057dfb9/projects/plugins/jetpack/extensions/plugins/ai-content-lens/extend/ai-post-excerpt/index.tsx#L93

```
    TypeError: Cannot read properties of undefined (reading 'replace')
    at t (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/wordcount.min.js:2:896)
    at https://c0.wp.com/c/6.3.1/wp-includes/js/dist/wordcount.min.js:2:2177
    at Array.reduce (<anonymous>)
    at https://c0.wp.com/c/6.3.1/wp-includes/js/dist/wordcount.min.js:2:2162
    at d (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/wordcount.min.js:2:2240)
    at h (https://agreed-jacket.jurassic.ninja/wp-content/plugins/jetpack/_inc/blocks/editor.js?minify=false&ver=b4bf07040c8dde718816:62:8679)
    at wt (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/vendor/react-dom.min.js:10:47637)
    at js (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/vendor/react-dom.min.js:10:120584)
    at wl (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/vendor/react-dom.min.js:10:88659)
    at bl (https://c0.wp.com/c/6.3.1/wp-includes/js/dist/vendor/react-dom.min.js:10:88587)
```

### Steps to reproduce

1. Make sure you are connected to JP and have Jetpack Blocks enabled
2. Draft a new post on a post type that doesn't support excerpts:
```php
add_action(
	'init',
	function() {
		register_post_type( 'test_cpt', [ 'public' => true, 'supports' => [ 'title', 'editor' ], 'show_in_rest' => true ] );
	}
);
```

3. Confirm the editor breaks:

image

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #33438

## Proposed changes:

Avoid issues when trying to use the excerpt feature on post types that do not support excerpts. On such posts, we should not even display the excerpt box.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1696256126106919-slack-CDLH4C1UZ

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

* Create a CPT:

```php
add_action(
	'init',
	function() {
		register_post_type( 'test_cpt', [ 'public' => true, 'supports' => [ 'title', 'editor' ], 'show_in_rest' => true ] );
	}
);
```

* Go to the block editor for that post type.
* Open the post side panel
* You should not see an excerpt panel.
* You shoulod not see any fatal error.
* Go to Posts > Add New
* Open the post side panel
* You should see an excerpt panel
* The AI excerpt features should work.

### CODE REVIEW

**Review by sdixon194 — APPROVED** [review]
Can't speak to the code itself, but the PR fixes the issue for me with no regressions.

File: projects/plugins/jetpack/extensions/plugins/ai-content-lens/extend/ai-post-excerpt/index.tsx [hunk 1]
```diff
@@ -245,11 +249,13 @@ ${ postContent }
...
 
 export const PluginDocumentSettingPanelAiExcerpt = () => (
-	<PluginDocumentSettingPanel
-		className={ isBetaExtension( 'ai-content-lens' ) ? 'is-beta-extension inset-shadow' : '' }
-		name="ai-content-lens-plugin"
-		title={ __( 'Excerpt', 'jetpack' ) }
-	>
-		<AiPostExcerpt />
-	</PluginDocumentSettingPanel>
+	<PostTypeSupportCheck supportKeys="excerpt">
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/plugins/ai-content-lens/extend/ai-post-excerpt/index.tsx:252]: :til: about `<PostTypeSupportCheck />` 👏

**Review by retrofox — COMMENTED** [review]
Should we handle extending the plugin at a different level?

Because, on this approach, the AI Excertpt panel will be rendered but nothing? I suppose `< PostTypeSupportCheck />` will rendered null for those posts that don't support `excerpt`

Maybe it should be addressed in the [extendAiContentLensFeatures()](https://github.com/Automattic/jetpack/blob/1ff79031d0b3499706fb8ad9a9e2b7423e70d965/projects/plugins/jetpack/extensions/plugins/ai-content-lens/editor.js#L26) function.

**Review by kraftbj — APPROVED** [review]
Confirmed problem state and confirmed this PR resolves.

**Comment by kraftbj** [comment]
> Should we handle extending the plugin at a different level?
>
>Because, on this approach, the AI Excertpt panel will be rendered but nothing? I suppose < PostTypeSupportCheck /> will rendered null for those posts that don't support excerpt
>
>Maybe it should be addressed in the [extendAiContentLensFeatures()](https://github.com/Automattic/jetpack/blob/1ff79031d0b3499706fb8ad9a9e2b7423e70d965/projects/plugins/jetpack/extensions/plugins/ai-content-lens/editor.js#L26) function.

I don't have an opinion on this, but going to merge this and let the discussion continue in a future PR so we don't leave things in the broken state.

**Comment by jeherve** [comment]
> Should we handle extending the plugin at a different level?
> 
> Because, on this approach, the AI Excertpt panel will be rendered but nothing? I suppose `< PostTypeSupportCheck />` will rendered null for those posts that don't support `excerpt`
> 
> Maybe it should be addressed in the [extendAiContentLensFeatures()](https://github.com/Automattic/jetpack/blob/1ff79031d0b3499706fb8ad9a9e2b7423e70d965/projects/plugins/jetpack/extensions/plugins/ai-content-lens/editor.js#L26) function.

I don't see why not, that seems like a good idea if it allows us to shortcircuit earlier in the process. 👍

**Comment by mgozdis** [comment]
Is this still planned to be released in about a week? Getting user reports of this affecting custom post types used by Sensei and various other plugins. Disabling Jetpack Blocks is a workaround.

**Comment by sdixon194** [comment]
@mgozdis Yup, this is going to be included in the upcoming Jetpack 12.7 release on Tuesday.
