### PR TITLE
Make VaultPress notice dismissable

### LINKED ISSUE #13866: No close button and other style inconsistencies in Jetpack backup notice
#### Steps to reproduce the issue

1. Activate Jetpack premium on a site with VaultPress (e.g. Pressable)
2. You will see this notice:

jetpack-handling-backups-note

3. It doesn't have a close button (though it does disappear on reload)
4. It also has a large font for the title, inconsistent with other notices.

#### What I expected

A less obtrusive, closeable notice

#### What happened instead

No close icon, obtrusive font style

**Screenshots**

jetpack-handling-backups

### PR DESCRIPTION
**Pull request by gravityrail**
Fixes #13866

#### Changes proposed in this Pull Request:

* Make VaultPress upgrade notice dismissable, and style more consistent with other notices
* Also updates usage of `_e` to `esc_html_e`

Before:

jetpack-vp-before

After:

backups-activity

After, in Jetpack dash:

backups-activity-dash

#### Testing instructions:

* On a site with VaultPress enabled and Rewind available, e.g. on Pressable
* Upgrade to a Premium plan that includes backups
* Visit wp-admin
* VP notice should be dismissable, and should not have a large h2 heading

Alternatively, you can create a micro-plugin which includes just this line of code:

```php
add_action( 'admin_notices', 'jetpack_vaultpress_rewind_enabled_notice' );
```

#### Proposed changelog entry for your changes:

*

### CODE REVIEW

**Review by jeherve — CHANGES_REQUESTED** [review]
From the issue:
> Can you replace that notice with something that resembles the Akismet one? But with a green border-left and the following message that lets users know where to access their backups:
>> Jetpack is now handling your backups.
>> Vaultpress is no longer needed and has been deactivated. You can access your backups on your site's Activity page.
> ^ where "Activity" links to the Activity page in Calypso.
-- https://github.com/Automattic/jetpack/issues/13866#issuecomment-547141142

**Comment by gravityrail** [comment]
@jeherve I updated the PR to include the suggested changes.

File: 3rd-party/vaultpress.php [hunk 1]
```diff
@@ -29,6 +46,7 @@ function jetpack_vaultpress_rewind_enabled_notice() {
  * @since 5.8
  */
 function jetpack_vaultpress_rewind_check() {
+	add_action( 'admin_notices', 'jetpack_vaultpress_rewind_enabled_notice' );
```
Comment (kraftbj) [inline 3rd-party/vaultpress.php]: I haven't tested, but I think this line needs to be removed before merging.

Comment (jeherve) [reply 3rd-party/vaultpress.php]: Took care of that in fc630c4156bac7c907ad999e5b90ee59c6e76f0d

**Review by jeherve — APPROVED** [review]
I added a `rel` to the link just to be safe. Everything else looks good to me. This should be good to merge once we get the okay from Design.

**Comment by joanrho** [comment]
From the design side, LGTM.

Screen Shot 2019-10-28 at 3 43 12 PM
