### PR TITLE
Contact Form: check if checkbox-multiple has at least one selection, fixes #3131

### LINKED ISSUE #3131: Contact Form: checkbox-multiple and required option for field don't jibe
If you assign a `checkbox-multiple` field in a contact form as a required element, any answer to that field will not register as completed and the form will never submit.

To reproduce:

1. make contact form
2. create a `checkbox-multiple` field
3. make it required
4. save contact form
5. try to fill it out and submit
6. you can't :)

### PR DESCRIPTION
**Pull request by eliorivero**
References #3131

### CODE REVIEW

File: modules/contact-form/grunion-contact-form.php [hunk 1]
```diff
@@ -1878,7 +1878,15 @@ function validate() {
 		$field_type  = $this->get_attribute( 'type' );
 		$field_label = $this->get_attribute( 'label' );
 
-		$field_value = isset( $_POST[$field_id] ) ? stripslashes( $_POST[$field_id] ) : '';
+		if ( isset( $_POST[$field_id] ) ) {
```
Comment (dereksmart) [inline modules/contact-form/grunion-contact-form.php]: plz add whitespace in brackets

(2 more below)
