### PR TITLE
Cover: Only add filter if needed

### LINKED ISSUE #16233: Blocks: broken with WP 5.3
#16107 may have broken our blocks in older versions of WordPress.

If you test a WordPress 5.3.4 site with Jetpack Master today, you'll run into the following error when trying to insert an Image Compare block for example:

```
TypeError: Object(...) is not a function
    at eval (cover-media-placeholder.js:75)
```

image

@retrofox Do you think you could take a look?

### PR DESCRIPTION
**Pull request by obenland**
Suggestion to fix the `useBlockEditContext` regression for WordPress 5.3.

This emulates the way the VideoPress block is using `useBlockEditContext`, hidden behind an `isSimpleSite` and plan check.

Fixes #16233.

#### Changes proposed in this Pull Request:

* Moves environment checks into `index.js` to only filter the media placeholder when necessary.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Set up a test environment that runs WordPress 5.3.4 with Jetpack master
* Open the editor and try inserting an Image Compare block 
* Make sure the block displays without error

#### Proposed changelog entry for your changes:

* Not needed.

### CODE REVIEW

**Comment by obenland** [comment]
@retrofox Do we have different Jetpack setups? It auto-adjusted a few things for me when I pushed my changes

**Comment by retrofox** [comment]
> @retrofox Do we have different Jetpack setups? It auto-adjusted a few things for me when I pushed my changes

I don't, @obenland.  🤷

File: extensions/shared/blocks/cover/cover-media-placeholder.js [hunk 1]
```diff
@@ -9,13 +8,13 @@ import { useContext, useCallback } from '@wordpress/element';
...
+import { isVideoFile } from './utils';
 import { CoverMediaContext } from './components';
 
 export default createHigherOrderComponent(
 	CoreMediaPlaceholder => props => {
 		const { name } = useBlockEditContext();
-		if ( ! name || ! isUpgradable( name ) ) {
+		if ( 'core/cover' !== name ) {
 			return <CoreMediaPlaceholder { ...props } />;
 		}
```
Comment (retrofox) [inline extensions/shared/blocks/cover/cover-media-placeholder.js:19]: This checking is redundant since it's begin controlled by _isUpgradable()_, in the **addVideoUploadPlanCheck** function.

I see it's k removing it.

Comment (obenland) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: From what I understand, adding a filter to `editor.MediaPlaceholder` adds it to all instances, even when the current block is not `core/cover`. Is that not the case?

Comment (retrofox) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: yeah, it's added to all blocks but the block type control is handled by the `isUpgradable()` function too. So, in theory, the media placeholder will be extended only for core/cover beyond of this control.

Comment (retrofox) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: [here](https://github.com/Automattic/jetpack/blob/6572c94e3f07c30a57cc522a405f745663be1e50/extensions/shared/blocks/cover/utils.js#L58)

File: extensions/shared/blocks/cover/index.js [hunk 2]
```diff
@@ -11,15 +11,23 @@ import { addFilter } from '@wordpress/hooks';
  * Internal dependencies
  */
 import coverEditMediaPlaceholder from './cover-media-placeholder';
-import isCurrentUserConnected from '../../is-current-user-connected';
 import jetpackCoverBlockEdit from './edit';
-
+import { isUpgradable } from './utils';
 import './editor.scss';
 
-if ( isCurrentUserConnected() ) {
```
Comment (retrofox) [inline extensions/shared/blocks/cover/index.js:19]: I see you remove this checking. Isn't needed? Maybe we can add it to  the `isUpgradable()` function.

File: extensions/shared/blocks/cover/utils.js [hunk 3]
```diff
@@ -53,7 +53,10 @@ export function isVideoFile( file ) {
 export function isUpgradable( name ) {
 	const { unavailableReason } = getJetpackExtensionAvailability( 'videopress' );
 
-	return name && name === 'core/cover' && // upgrade only for cover block
+	return (
+		name &&
+		name === 'core/cover' && // upgrade only for cover block
```
Comment (retrofox) [inline extensions/shared/blocks/cover/utils.js:58]: should we add `isCurrentUserConnected()` here?

File: extensions/shared/blocks/cover/cover-media-placeholder.js (hunk 1 above)
Comment (obenland) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: I `console.log`'d the name variable on my sandbox and it *does* add the filter to all instances of `editor.MediaPlaceholder`. I'm afraid we'll still need that check

File: extensions/shared/blocks/cover/index.js (hunk 2 above)
Comment (obenland) [reply extensions/shared/blocks/cover/index.js:19]: Since we're only interested in simple sites, I think we can omit that check

File: extensions/shared/blocks/cover/utils.js (hunk 3 above)
Comment (obenland) [reply extensions/shared/blocks/cover/utils.js:58]: Since we're only interested in simple sites I think we can omit that check

File: extensions/shared/blocks/cover/cover-media-placeholder.js (hunk 1 above)
Comment (retrofox) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: I see, the block type checking in the _isUpgradable()_ function doesn't make sense, because once the function is bound to the hook, it executes for all blocks.

Comment (obenland) [reply extensions/shared/blocks/cover/cover-media-placeholder.js:19]: I think does make sense there because we only want to add the filter if `core/cover` gets registered. If it never gets registered we don't need to add the notice.

**Comment by obenland** [comment]
r209538-wpcom
