### PR TITLE
Carousel: Check if image parent is not a link

### LINKED ISSUE #6638: Carousel: JavaScript in some gallery settings
In #6306, we made some changes to the way carousels are loaded. Unfortunately, in some situations it now creates the following JavaScript error:
`Uncaught TypeError: Cannot read property 'split' of undefined`
On line 451 of `modules/carousel/jetpack-carousel.js`

You can reproduce the issue [here](http://temp.tilestonesource.com/century-wood-series/). I unfortunately haven't been able to reproduce the issue on my end. It seems to happen in some cases in in-page galleries, sometimes in slideshows.

Reported here:
- https://wordpress.org/support/topic/installing-jetpack-4-7-breaks-some-tiled-galleries/
- https://wordpress.org/support/topic/4-7-update-breaks-slideshow-on-pages/

### PR DESCRIPTION
**Pull request by Stoyan0v**
Fixes #6638

#### Changes proposed in this Pull Request:

* Add additional condition to check if the parent is not a link, to prevent javascript errors.

#### Testing instructions:

* Enable Carousel 
* Disable html5 support for captions
* Create new page and add a sample gallery
* Add two or more caption shortcodes wrapped in a custom `a` tag (you can use [the following code](https://gist.github.com/Stoyan0v/caa692e5e60149d27e3f4d40105068f3) )
* Open the page and make sure that there is no javascript error like the following :
`Uncaught TypeError: Cannot read property 'split' of undefined`
On line 451 of `modules/carousel/jetpack-carousel.js`

cc @jeherve

### CODE REVIEW

File: modules/carousel/jetpack-carousel.js [hunk 1]
```diff
@@ -445,6 +445,11 @@ jQuery(document).ready(function($) {
 				return;
 			}
 
+			// skip if the parent is not a link
```
Comment (zinigor) [inline modules/carousel/jetpack-carousel.js]: Looks good, but one tiny nitpick. We're not talking about the parent here, but about the container, right?

Comment (Stoyan0v) [inline modules/carousel/jetpack-carousel.js]: Yes and no 😄 . The container is actually the [parent](https://github.com/Automattic/jetpack/blob/master/modules/carousel/jetpack-carousel.js#L441), but I will change this if you want.

**Comment by zinigor** [comment]
OK, so I guess the `container.parent` above was the grandparent :) Thanks, looks good!

**Comment by dereksmart** [comment]
merged to 4.7 eae9b8f
