### PR TITLE
Search: Fix no search results in customizer

### LINKED ISSUE #25000: Search: no search results shown in Customizer on load
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

On a site with Jetpack Search enabled, go to `/wp-admin/customize.php`.

### A clear and concise description of what you expected to happen.

Search results should load in the Customizer.

### What actually happened

Search results only load after interacting with the modal (e.g. changing the sort order).

### Other information

I suspect this may have been caused by https://github.com/Automattic/jetpack/pull/24609.

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

Use Customberg instead: `/wp-admin/admin.php?page=jetpack-search-configure`.

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #25000

#### Changes proposed in this Pull Request:
The PR proposes to load search results for customizer when `isInCustomizer` is true for component `SearchApp`, so that user could preview the overlay properly.

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Create a JN site by click [here](https://jurassic.ninja/create/?jetpack-beta&branches.jetpack-search=fix/no-search-results-in-customizer&nojetpack)
- Open cutomizer ( `/wp-admin/customize.php?return=%2Fwp-admin%2Fwidgets.php` ) and click Jetpack Search section

image

- Ensure the search results is loaded

image

### CODE REVIEW

File: projects/packages/search/src/instant-search/components/search-app.jsx [hunk 1]
```diff
@@ -80,7 +80,10 @@ class SearchApp extends Component {
 
 	componentDidMount() {
 		// The condition can only occur in the Customberg preview context.
```
Comment (jsnmoon) [inline projects/packages/search/src/instant-search/components/search-app.jsx]:
```suggestion
		// This condition can only occur within Customberg or the Customizer.
```

**Review by jsnmoon — DISMISSED** [review]
Works as described. I added a code comment tweak suggestion below 👍

**Review by jsnmoon — APPROVED** [review]
