### PR TITLE
SSO: consider filters and constant when rendering the checkboxes in admin page

### LINKED ISSUE #3526: Disable SSO options when code overrides them
#### What I expected

Upon adding the following hooks:

```php
add_filter( 'jetpack_sso_require_two_step', '__return_true' );
add_filter( 'jetpack_sso_match_by_email', '__return_true' );
```

I would expect the SSO options page (/wp-admin/admin.php?page=jetpack&configure=sso) to show the checkboxes checked and disabled. Same goes for the "Match by email" option when using the `WPCC_MATCH_BY_EMAIL` constant.

#### What happened instead

The boxes are not checked. Checking or unchecking has no effect.

#### Steps to reproduce the issue

See above code snippet.

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #3526.

#### Changes proposed in this Pull Request:
Considers `jetpack_sso_require_two_step` and `jetpack_sso_match_by_email` filters when rendering the 	_Require Two-Step Authentication_ and _Match by Email_ checkboxes in SSO admin page. If the filters return true, they will be always checked and disabled.

If `WPCC_MATCH_BY_EMAIL` constant is defined, the _Match by Mail_ will always be checked and disabled.

### CODE REVIEW

File: modules/sso.php [hunk 1]
```diff
@@ -219,8 +219,10 @@ public function register_settings() {
 	 * @since 2.7
 	 **/
 	public function render_require_two_step() {
+		$require_two_step = 1 == apply_filters( 'jetpack_sso_require_two_step', get_option( 'jetpack_sso_require_two_step' ) );
```
Comment (jeherve) [inline modules/sso.php]: Could you add inline doc here, mentioning that the filter is documented in modules/sso.php?

Thanks!

Comment (eliorivero) [inline modules/sso.php]: Done! thanks for the heads up.
