### PR TITLE
Jetpack AI: do not extend form if module isn't available

### LINKED ISSUE #40332: Form Block: AI input field appears when Contact Form module is inactive
### Impacted plugin

Jetpack

### Quick summary

When the Contact Form module is not active, we display a placeholder instead of the block controls in the block editor. Jetpack's AI Assistant input field is displayed below that placeholder, even though the AI Assistant cannot help you with the feature when the module is not active.

### Steps to reproduce

1. Go to Jetpack > Settings > Modules
2. Deactivate the Contact Form feature
3. Go to Posts > Add New
4. Type `/contact` and insert a contact form block

### A clear and concise description of what you expected to happen.

At this point I would expect to see the invitation to activate the form feature, and nothing else.

### What actually happened

Instead I see the placeholder, as well as the AI assistant input field:

Image

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

You can solve the issue by activating the contact form module.

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by CGastrell**
`contact-form` extension should only happen if `contact-form` module is enabled.

Fixes #40332

## Proposed changes:
Add a store check for module availability on our lib responsible for allowing the extension.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
https://github.com/Automattic/jetpack/issues/40332#issuecomment-2499028060

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
- Go to Posts > Add New
- Type /contact and insert a contact form block
- [ ] See the AI assistant input shows under the variation selector

- Go to Jetpack > Settings > Modules
- Deactivate the Contact Form feature
- Go to Posts > Add New
- Type /contact and insert a contact form block
- [ ] See the AI assistant input is NOT present
- [ ] Confirm other AI assistant features remain available

### CODE REVIEW

**Review by jeherve — COMMENTED** [review]
Thanks for tackling this so quickly! Looks like there is an error in the JS tests:

```
error TS2339: Property 'isModuleActive' does not exist on type '{}'.
```

When testing, I noticed that the contact form AI assistant does not appear after I activate the Contact form module via the button in the block placeholder. I have to do a full page refresh for the AI assistant to start appearing.
I would expect it to be displayed as soon as the module is activated.

**Comment by CGastrell** [comment]
> Thanks for tackling this so quickly! Looks like there is an error in the JS tests:
> 
> ```
> error TS2339: Property 'isModuleActive' does not exist on type '{}'.
> ```

I'll see how to deal with this.

> When testing, I noticed that the contact form AI assistant does not appear after I activate the Contact form module via the button in the block placeholder. I have to do a full page refresh for the AI assistant to start appearing. I would expect it to be displayed as soon as the module is activated.

Good catch, sadly that means we cannot use the current approach, we'll need to use the hook `useModuleStatus` which means we need to make the call from the component (the current approach was skip the block extension entirely). I'll look for a different solution.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/jetpack-form/index.tsx [hunk 1]
```diff
@@ -1,8 +1,7 @@
 /**
  * External
  */
-import { parse, serialize } from '@wordpress/blocks';
-import { createBlock } from '@wordpress/blocks';
+import { parse, serialize, createBlock } from '@wordpress/blocks';
```
Comment (dhasilva) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/jetpack-form/index.tsx:4]: Good catch

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/lib/utils/get-feature-availability.ts [hunk 2]
```diff
@@ -1,3 +1,8 @@
+/*
+ * External dependencies
+ */
+import { getJetpackExtensionAvailability } from '@automattic/jetpack-shared-extension-utils';
+
 export function getFeatureAvailability( feature: string ): boolean {
-	return window?.Jetpack_Editor_Initial_State?.available_blocks?.[ feature ]?.available === true;
+	return getJetpackExtensionAvailability( feature ).available === true;
```
Comment (dhasilva) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/lib/utils/get-feature-availability.ts:7]: Nice!

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/lib/is-possible-to-extend-block.ts [hunk 3]
```diff
@@ -24,3 +33,17 @@ export function isPossibleToExtendBlock( blockName: string ): boolean {
 
 	return true;
 }
+
+/**
+ * Hook that checks if a block can be extended with AI Assistant capabilities.
+ * @param {string} blockName - The block name.
+ * @return {boolean} Whether the block can be extended.
+ */
+export function useIsPossibleToExtendBlock( blockName: string ): boolean {
```
Comment (dhasilva) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/lib/is-possible-to-extend-block.ts]: I'd say the naming is a bit confusing. `isPossibleToExtendBlock` is already used to extend the block or not and I think it should be used only for that, as when this is called, the block is already extended.
This could be something like `useIsBlockExtensionEnabled`, so we can be in a state where extending the block is _possible_, but it is not _currently enabled_ for whatever reason, and this can change at any time.

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/with-ai-extension.tsx [hunk 4]
```diff
@@ -498,7 +504,7 @@ const blockEditWithAiComponents = createHigherOrderComponent( BlockEdit => {
 			<>
 				<BlockEdit { ...props } />
 
-				{ showAiControl && (
+				{ showAiControl && canExtendBlock && (
```
Comment (dhasilva) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/with-ai-extension.tsx]: The Input is not the only component, there is also the `AiAssistantExtensionToolbarDropdown`:



That said, I think the best way here may be to do an early return to bypass all those hook calls. When the module is disabled, there should be no performance penalty.

To avoid the React error with early returns, maybe we can do something like what is done [here](https://stackoverflow.com/a/56976469/4301486) with the `AfterEarlyReturn` component. 
If `isBlockExtensionEnabled` is false, return the original block, otherwise return the extended component. Makes sense?

**Review by dhasilva — CHANGES_REQUESTED** [review]
The toolbar needs to be hidden as well (see screenshot in one of the comments).

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/lib/is-possible-to-extend-block.ts (hunk 3 above)
Comment (CGastrell) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/lib/is-possible-to-extend-block.ts]: True true. Maybe the hook should make some reference to “module”, as it is what it’s really checking. Different from other extensions, this check is for “module dependency”. 
but overall agree it needs a name change and split it from isPossibleToExtendBlock

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/with-ai-extension.tsx (hunk 4 above)
Comment (CGastrell) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/with-ai-extension.tsx]: Good point! 
i did try making an early return, but that got me into this “page reload” scenario. I can show you, maybe you can spot something

**Review by dhasilva — COMMENTED** [review]
Trying to dismiss my change request without approving since I added a commit.

**Review by dhasilva — APPROVED** [review]
Commenting does not work, I have to approve, but let's get other approvals here.

**Review by mwatson — APPROVED** [review]
Works as described in the test instructions! :shipit:

**Review by jeherve — APPROVED** [review]
This tests well for me too. 🚢
