### PR TITLE
Sitemaps: Add thumbnails to video sitemaps

### LINKED ISSUE #9539: Video Sitemap does not include thumbnails
#### Steps to reproduce the issue

Upload a video to the Media Library

#### What I expected

The video sitemap should include the video's featured image as the thumbnail

#### What happened instead

The thumbnail `<video:thumbnail_loc>` is empty

_Update:_ Ref: 1148771-zen

### PR DESCRIPTION
**Pull request by aheckler**
Uses thumbnails from processed VideoPress videos where possible, otherwise falls back to a (filterable) blank image. This will avoid Google Search Console (fka Google Webmaster Tools) from complaining about invalid URLs in video sitemaps.

Fixes #9539.

#### Testing instructions:

1. Start with a properly connected, self-hosted site with a Premium or Professional plan.
2. Enable Jetpack's video hosting feature under Jetpack > Settings > Performance > Media section.
3. Upload a video to the site via `wordpress.com/media`.
4. Wait for VideoPress to finish processing the video.
5. Rebuild sitemaps with `wp jetpack sitemap rebuild --purge`.
6. View the view sitemap at `www.example.com/video-sitemap-1.xml`.

Videos processed with VideoPress will show an actual thumbnail. Videos not processed with VideoPress will have a blank image as the thumbnail, which is better than nothing.

screen shot 2019-03-01 at 7 04 58 am

#### Proposed changelog entry for your changes:

Added thumbnails to video sitemaps as required by Google Search Console

### CODE REVIEW

**Comment by kraftbj** [comment]
Works as advertised for me, but I need to test it again not on JN. The way JN defines the URL breaks sitemaps, which is outside the scope of this PR, but want to see it live. Also would need to run a non-JN sitemap through a validator to confirm.

File: modules/sitemaps/sitemap-builder.php [hunk 1]
```diff
@@ -1319,6 +1319,20 @@ private function video_post_to_sitemap_item( $post ) {
...
+			$video_thumbnail_url = get_the_post_thumbnail_url( $post );
+		} else {
+			/**
+			 * Filter the thumbnail image used in the video sitemap for non-VideoPress videos.
+			 *
+			 * @since 7.2.0
+			 *
+			 * @param string $str Image URL.
+			 */
+			$video_thumbnail_url = apply_filters( 'jetpack_video_sitemap_default_thumbnail', 'https://s0.wp.com/i/blank.jpg' );
```
Comment (kraftbj) [inline modules/sitemaps/sitemap-builder.php]: Any thought on using the video default image that ships with core, e.g. https://kraftbj.wpsandbox.me/wp-includes/images/media/video.png

Any pros or cons from your POV?

**Comment by kraftbj** [comment]
Tested it and looked good. Images populated as expected and passed validation. Pending the question about the default image, 🚢

File: modules/sitemaps/sitemap-builder.php (hunk 1 above)
Comment (aheckler) [reply modules/sitemaps/sitemap-builder.php]: The core image is better than the blank one, as far as imparting the nature of the file goes (i.e. that it's a video).

However, Google suggests a minimum thumbnail size of 160x90:

https://support.google.com/webmasters/answer/156442#thumbnails

... which makes the core image too small.

I did not actually test to see if Search Console would complain about a too-small image though.

Comment (kraftbj) [reply modules/sitemaps/sitemap-builder.php]: I would be fine assuming it would complain. So, let's roll with blank for now and we can accept a future PR to provide a better default image.

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
r188792-wpcom
