### PR TITLE
Open sharing in same window

### LINKED ISSUE #1288: Sharing: "Open in the same window" option doesn't work
Steps to reproduce:

1. Enable the Sharing module
2. Go to Settings > Sharing, set up some non-official buttons
3. Choose to open the links in the same window
4. Save your changes
5. Visit a post, click on a sharing button
    - The sharing form opens in a new window

Since we use `js_dialog` ([ref](https://github.com/Automattic/jetpack/blob/3.2/modules/sharedaddy/sharing-sources.php#L164)) to overwrite the default link behaviour for each one of the buttons, it doesn't matter whether `target="_blank"` is set in the link ([ref](https://github.com/Automattic/jetpack/blob/3.2/modules/sharedaddy/sharing-sources.php#L1092)).

Should we add a "target" option to `js_dialog` to allow links to open in the same window?

Reported here:
- https://wordpress.org/support/topic/open-sharing-buttons-in-a-new-window-not-tab?replies=1

### PR DESCRIPTION
**Pull request by dereksmart**
fixes #1288 

We were always opening the sharing window in a new window.  This puts a stop to it if "same window" is selected.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
This looks like it should fix #1288, @jeherve can you please confirm that this is the expected action?

**Comment by jeherve** [comment]
It works for me and that's what I'd expect, but George had a good question about the expected behaviour in #1288.

File: modules/sharedaddy/sharing-sources.php [hunk 1]
```diff
@@ -76,7 +74,7 @@ public function get_link( $url, $text, $title, $query = '', $id = false ) {
 			( $id ? esc_attr( $id ) : '' ),
 			implode( ' ', $klasses ),
 			$url,
-			( $this->open_links == 'new' ) ? ' target="_blank"' : '',
+			( $this->open_link_in_new == true ) ? ' target="_blank"' : '',
```
Comment (samhotchkiss) [inline modules/sharedaddy/sharing-sources.php]: As much as I hate them, I believe our code style is to use yoda conditionals ( @georgestephanis can you confirm? )

File: modules/sharedaddy/sharing-sources.php [hunk 2]
```diff
@@ -3,18 +3,16 @@
 abstract class Sharing_Source {
 	public    $button_style;
 	public    $smart;
-	protected $open_links;
+	protected $open_link_in_new;
 	protected $id;
 
 	public function __construct( $id, array $settings ) {
 		$this->id = $id;
+		$this->open_link_in_new = apply_filters( 'open_sharing_in_new_window', true );
```
Comment (samhotchkiss) [inline modules/sharedaddy/sharing-sources.php]: @dereksmart: This should be namespaced (`jetpack_open_sharing_in_new_window`)
