### PR TITLE
Boost: Refactor the pre-WordPress part of the Page Cache

### LINKED ISSUE #41983: Boost: if there are too many files in the boost-cache directory, uninstall "fails"
Uninstalling Boost Cache by deleting it from plugins.php appears to fail in the "deleting..." phase if there are too many cache files to delete quickly.

I observed this happening when my boost-cache directory was over 400MB in size.

Other potential causes for failed uninstall: Timeout during transient cleanup.

9568961-zd-a8c

### PR DESCRIPTION
**Pull request by donnchawp**
This PR started out by removing the 0 byte index.html files left by garbage collection, but is now a refactor of the Page Cache storage system.
It uses "path actions" to handle the different actions we perform on files and directories, such as deleting and rebuilding, and filtering out expired files.

Tests were added to cover most of the changes.

Fixes HOG-23
And probably will fix HOG-22 too as the number of cached files and directories is reduced.

## Proposed changes:

* Fix the $iterator in the cache cleanup so it returns directories as well as files.
* Remove the REBUILD check when doing GC so directories can be cleaned up.
* 

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply PR
* Enable Page Cache and make sure some pages are cached.
* Clear cache from the settings page and confirm that the blog's directory in boost-cache/cache/ is gone, empty, or almost empty. (random requests from the internet may populate pages)
* Set the cache TTL to 600 seconds by adding `define( 'JETPACK_BOOST_CACHE_DURATION', 600 );` to your wp-config.php
* Wait for an hour for garbage collection or run the "jetpack_boost_cache_garbage_collection" through the wp-crontrol plugin. Confirm that any cache file older than an the TTL is gone. Old index.html files may still exist if there are newer cache files in that directory or sub directories.
* Make sure garbage collection works and removes old files. Set the TTL to 10 seconds. Run the scheduled job manually.
* Use the jetpack_boost_clear_page_cache_url action to try to get out of boost-cache/cache/ by using URLs with ../../ in them.
* Unpublish a post and confirm it doesn't delete the entire cache.
* Tail the error log and make sure no file operation warnings appear.

### CODE REVIEW

**Review by haqadn — DISMISSED** [review]
Nothing to change. Just testing.

**Review by haqadn — COMMENTED** [review]
The change makes sense but I faced an issue which I am not sure how it's happening.

When I click clear cache button, it still leaves the index.html files. However, Deactivating and then reactivating the cache module clears the cache nicely.

I am confused because the code path is almost identical for both.

**Comment by donnchawp** [comment]
It was [this line](https://github.com/Automattic/jetpack/pull/42789/files#diff-8622fc9f8fd99d72c80dd909f33ff702982db2cba210df1ae403052d0d39f35eL47) that excluded index.html. When I was testing it on my server I had removed that check. I could have sworn I removed it locally too before checking in my code but I didn't.
Clearing the cache will now delete the entire directory for your hostname.

**Comment by donnchawp** [comment]
I was able to clear the cache on a site with over 200MB of files in about 11 seconds. Another site with 64MB of files was cleared in about 2 seconds.

**Review by LiamSarsfield — DISMISSED** [review]
LGTM, works as expected!
I noticed the log files for boost-cache still exist after uninstalling the plugin `boost-cache/logs`, though this is most likely out of scope for this for this PR.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php [hunk 1]
```diff
@@ -198,10 +201,6 @@ public static function gc_expired_files( $directory, $file_ttl, $action = self::
 		}
 		closedir( $handle );
 
-		if ( $action === self::REBUILD ) {
-			return $count;
-		}
-
 		// If the directory is empty after processing its files, delete it.
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php]: Seems like we are handling index.html in a special way and only deleting it when deleting the directory. Check the definition of `is_dir_empty`:

https://github.com/Automattic/jetpack/blob/dc83c8e07bc72912269718224c70ace6f8bfd2e9/projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php#L314C2-L321C3

For some reason that approach is not working. I think we should fix that instead.

**Review by haqadn — DISMISSED** [review]

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php [hunk 2]
```diff
@@ -329,12 +313,12 @@ public function rebuild_on_comment_post( $comment_id, $comment_approved, $commen
 			 */
 			if ( isset( $parameters['cookies'] ) && ! empty( $parameters['cookies'] ) ) {
 				$filename = trailingslashit( get_permalink( $post->ID ) ) . Filesystem_Utils::get_request_filename( $parameters );
-				$this->storage->invalidate( $filename, Filesystem_Utils::DELETE_FILE );
+				$this->rebuild_page( $filename );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php]: This is broken atm. It should delete the specific file with specific parameters. This need to be addressed before the PR is merged.

Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php]: PR has been updated. This `rebuild_page` should have been `delete_page` too. It's because the cached page was generated by a visitor with cookies who just left a comment. The cookies will be unique to that visitor.

**Comment by haqadn** [comment]
Tests are failing at the moment.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php [hunk 3]
```diff
@@ -44,15 +45,15 @@
...
+	$boost_cache->delete_recursive( home_url() );
 }
 
 /**
  * Delete cache for homepage and paged archives.
  */
 function jetpack_boost_delete_cache_for_home() {
 	$boost_cache = new Boost_Cache();
-	$boost_cache->invalidate_cache_for_front_page( Filesystem_Utils::DELETE_ALL );
+	$boost_cache->delete_page( home_url() );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php:55]: I was trying to make sense of the action and function name and decided it should only delete the homepage. But, the previous implementation was deleting the whole cache.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php [hunk 4]
```diff
@@ -62,7 +63,7 @@ function jetpack_boost_delete_cache_for_home() {
  */
 function jetpack_boost_delete_cache_for_url( $url ) {
 	$boost_cache = new Boost_Cache();
-	$boost_cache->invalidate_cache_for_url( $url, Filesystem_Utils::DELETE_ALL );
+	$boost_cache->delete_page( $url );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php]: Does this make sense to be `delete_recursive`? I am unsure, asking based on old implementation.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php [hunk 5]
```diff
@@ -71,6 +72,32 @@ function jetpack_boost_delete_cache_for_url( $url ) {
...
+	 * If a post is unpublished, the permalink will be deleted. In that case,
+	 * get_sample_permalink() will return a permalink with ?p=123 instead of
+	 * the post name. We need to get the post name from the post object.
+	 */
+	$permalink = get_permalink( $post->ID );
+	Logger::debug( "invalidate_cache_for_post: $permalink" );
+
 	$boost_cache = new Boost_Cache();
-	$boost_cache->invalidate_cache_by_post_id( (int) $post_id, Filesystem_Utils::DELETE_ALL );
+	$boost_cache->delete_page( $permalink );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php]: I guess this should be `delete_recursive` as well.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php [hunk 6]
```diff
@@ -45,6 +45,8 @@ public static function iterate_directory( $path, Path_Action $action ) {
 			$count += $action->apply_to_path( $file );
 		}
 
+		$count += $action->apply_to_path( new SplFileInfo( $path ) );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:46]: I tried this and found it may produce errors in GC due to the directory not existing. I think we can either leave the directory alone or check for directory exists in the delete action.

Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:46]: I tested this by deleting the base hostname directory and triggering a GC and I didn't see any errors, so the extra checks we've added since, have fixed this.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 3 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php:55]: This needs to replicate what the original `invalidate_cache_for_front_page` did. If the homepage shows a static page it needs to delete the "posts" page too. The stable version of the plugin deletes the "homepage" post too, but it might be enough to delete home_url() for that. I'll fix this.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 4 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php]: Yes, it should be recursive. Before it was modified recently, in version 3.12.1 it did a DELETE_ALL by default. Also, it would allow you to delete or rebuild specific cache files, but I doubt anyone used that functionality.

This function is used by the `jetpack_boost_clear_page_cache_url` hook to allow developers to delete pages. However, [the example given](https://github.com/Automattic/jetpack/blob/update/boost/fix-deleting-directories/projects/plugins/boost/docs/Cache_API.md#delete-the-cache-for-a-specific-url) uses https://example.com/ so a recursive delete would clear the entire cache. I need to update those docs to show a post or page, and not the homepage.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 5 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php]: Yeah. A post may have paged comments, so yeah. This is now using delete_post_cache which does a recursive delete.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 4 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php]: I updated the docs and changed this to `delete_recursive`.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 3 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php:55]: I just updated the PR to delete the posts page too.

File: projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php [hunk 7]
```diff
@@ -205,17 +204,20 @@ public function handle_post_update( int $post_id ) {
...
 	 * @param string $path The path that was invalidated.
-	 * @param string $type The type of invalidation that occurred (e.g., Filesystem_Utils::DELETE_ALL).
+	 * @param string $type The type of invalidation that occurred (rebuild or delete).
+	 * @param string $scope The scope of the invalidation (page or recursive).
 	 * @return void
 	 */
-	public function handle_cache_invalidation( string $path, string $type ) {
-		if ( $type === Filesystem_Utils::DELETE_ALL ) {
+	public function handle_cache_invalidation( string $path, string $type, string $scope ) {
+		if ( $path === home_url() && $scope === 'recursive' ) {
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php:212]: I'm curious why do we check if the path is the home url?

Do we make the assumption that if it's the home page that we're invalidating for (and we're doing it recursively), the whole cache was invalidated?

I think I get it but I'm not a 100% sure. Would a comment make sense here?

Comment (dilirity) [reply projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php:212]: Do we need to worry if slashes are present or not in `$path` or is the path always sanitized?

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php [hunk 8]
```diff
@@ -44,15 +44,23 @@
...
  */
 function jetpack_boost_delete_cache_for_home() {
 	$boost_cache = new Boost_Cache();
-	$boost_cache->invalidate_cache_for_front_page( Filesystem_Utils::DELETE_ALL );
+	$boost_cache->delete_page( home_url() );
+	Logger::debug( 'jetpack_boost_delete_cache_for_home: deleting front page cache' );
+	if ( get_option( 'show_on_front' ) === 'page' ) {
+		$posts_page_id = get_option( 'page_for_posts' ); // posts page
+		if ( $posts_page_id ) {
+			$boost_cache->delete_recursive( get_permalink( $posts_page_id ) );
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php:60]: Having an id for the option, doesn't mean the page actually exists.

I know it's an edge case, but if the blog page gets deleted there's no permalink.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php [hunk 9]
```diff
@@ -231,40 +231,25 @@ public function ob_callback( $buffer ) {
...
 	 */
-	public function invalidate_cache_for_front_page( $action = Filesystem_Utils::REBUILD_FILES ) {
+	public function rebuild_front_page() {
 		if ( get_option( 'show_on_front' ) === 'page' ) {
 			$front_page_id = get_option( 'page_on_front' ); // static page
 			if ( $front_page_id ) {
-				Logger::debug( 'invalidate_cache_for_front_page: deleting front page cache' );
-				$this->invalidate_cache_for_post( get_post( $front_page_id ), $action );
+				Logger::debug( 'rebuild_front_page: deleting front page cache' );
+				$this->rebuild_post_cache( get_post( $front_page_id ) );
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php]: Can this check if what we're sending is an actual post? `get_post` might return `null` if the post has been deleted.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php [hunk 10]
```diff
@@ -231,40 +231,25 @@ public function ob_callback( $buffer ) {
...
 			}
 			$posts_page_id = get_option( 'page_for_posts' ); // posts page
 			if ( $posts_page_id ) {
-				Logger::debug( 'invalidate_cache_for_front_page: deleting posts page cache' );
-				$this->invalidate_cache_for_post( get_post( $posts_page_id ), $action );
+				Logger::debug( 'rebuild_front_page: deleting posts page cache' );
+				$this->rebuild_post_cache( get_post( $posts_page_id ) );
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php:241]: Same as the comment above about the post being deleted.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php [hunk 11]
```diff
@@ -13,14 +16,67 @@ class Filesystem_Utils {
 	const REBUILD                = 'rebuild'; // rebuild mode for managing expired files
 	const DELETE                 = 'delete'; // delete mode for managing expired files
 	const REBUILD_FILE_EXTENSION = '.rebuild.html'; // The extension used for rebuilt files.
+
+	/**
+	 * Iterate over a directory and apply an action to each file.
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:21]: Nitpick: I think using file when it refers to a file path is a bit confusing. The code refers paths everywhere, but then it passes files instead of file paths.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php [hunk 12]
```diff
@@ -13,14 +16,67 @@ class Filesystem_Utils {
...
+	 *
+	 * This applies the action to all files and subdirectories in the given directory.
+	 *
+	 * @param string      $path - The directory to iterate over.
+	 * @param Path_Action $action - The action to apply to each file.
+	 * @return int|Boost_Cache_Error - The number of files processed, or Boost_Cache_Error on failure.
+	 */
+	public static function iterate_directory( $path, Path_Action $action ) {
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:29]: Nitpick: The name `iterate_directory` doesn't sit right with me for some reason. It's a given that it iterates, but the most important part is applying the action.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php [hunk 13]
```diff
@@ -13,14 +16,67 @@ class Filesystem_Utils {
...
-	 * @param bool   $type - The type of action to take, see constants above.
-	 * @return bool|Boost_Cache_Error
+	 * This applies the action to all files in the directory, except index.html. And doesn't go into subdirectories.
+	 *
+	 * @param string      $path - The directory to iterate over.
+	 * @param Path_Action $action - The action to apply to each file.
+	 * @return int|Boost_Cache_Error - The number of files processed, or Boost_Cache_Error on failure.
 	 */
-	public static function walk_directory( $path, $type ) {
+	public static function iterate_files( $path, Path_Action $action ) {
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:60]: The initial description of this method overlaps with `iterate_directory`.

I have the same nitpick for the name.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php [hunk 14]
```diff
@@ -0,0 +1,35 @@
+<?php
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php:1]: Nitpick: I really liked the comments on everything else in page cache 😅

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php [hunk 15]
```diff
@@ -0,0 +1,35 @@
...
+
+namespace Automattic\Jetpack_Boost\Modules\Optimizations\Page_Cache\Pre_WordPress\Path_Actions;
+
+use SplFileInfo;
+
+class Filter_Older implements Path_Action {
+	private $timestamp;
+	private $sub_action;
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php:12]: Curious: Why is this `$sub_action` instead of `$action`?

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php [hunk 16]
```diff
@@ -0,0 +1,46 @@
...
+use Automattic\Jetpack_Boost\Modules\Optimizations\Page_Cache\Pre_WordPress\Filesystem_Utils;
+use Automattic\Jetpack_Boost\Modules\Optimizations\Page_Cache\Pre_WordPress\Logger;
+use SplFileInfo;
+
+class Simple_Delete implements Path_Action {
+	/**
+	 * Delete a file or directory.
+	 *
+	 * @param SplFileInfo $file The file or directory to delete.
+	 * @return int The number of files or directories deleted.
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php:17]: This mentions returning `int`, but `delete_file` returns a boolean.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php [hunk 17]
```diff
@@ -0,0 +1,46 @@
...
+	 */
+	public function apply_to_path( SplFileInfo $file ) {
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php:19]: I think this can also return `null` if the directory isn't empty.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/storage/class-file-storage.php [hunk 18]
```diff
@@ -152,33 +163,39 @@ private function sanitize_path( $path ) {
...
+	public function clear( $path, $args = array() ) {
+		$normalized_path = Boost_Cache_Utils::trailingslashit( $this->root_path . Boost_Cache_Utils::normalize_request_uri( $path ) );
+
+		$recursive  = $args['recursive'] ?? false;
+		$rebuild    = $args['rebuild'] ?? true;
+		$parameters = $args['parameters'] ?? false;
 
-		if ( $response === null ) {
-			return new Boost_Cache_Error( 'no-cache-files-to-delete', 'No cache files to delete.' );
+		$action = new Simple_Delete();
```
Comment (dilirity) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/storage/class-file-storage.php]: Nitpick: I know it's a little thing, but if we put this in the `else` we wouldn't always have to create an instance and then sometimes override it.

**Review by dilirity — CHANGES_REQUESTED** [review]
Great work on this! I couldn't find any issues while testing.

I have a few notes/nitpicks and we can merge after that.

File: projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php (hunk 7 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php:212]: The `handle_cache_invalidation` function is used by the `jetpack_boost_invalidate_cache_success` action which is executed by the `invalidate_cache_success` function.
The function is used by the various delete/rebuild functions in Boost_Cache, which are called with home_url() or permalinks, although jetpack_boost_delete_cache_for_url() does call it with $url.
That is fired by an action, `jetpack_boost_clear_page_cache_url`, so $url could be anything. For `handle_cache_invalidation`, that doesn't matter because it's only used for comparison, but I need to check where that's sanitized before deleting.

Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/class-cache-preload.php:212]: > I'm curious why do we check if the path is the home url?

Yeah, there is a comment a few lines down saying "If the cache is invalidated for all files, schedule preload for all Cornerstone Pages."

> Do we need to worry if slashes are present or not in $path or is the path always sanitized?
I was going to remove any "//" but that might introduce security issues. If someone passes through a url with "//" separating items in the URL, then it won't match and in this case, if they clear "http://example.com//" then it won't schedule a cornerstone refresh.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php (hunk 8 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/boost-cache-actions.php:60]: I just tested that. If the page is deleted, then show_on_front won't be "page" any more, so this is ok.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php (hunk 9 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php]: I think it's safe enough to do this as WordPress takes care of the setting if the page is deleted.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php (hunk 10 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php:241]: WordPress takes care of it, so this seems to be safe.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php (hunk 11 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:21]: It just means the files in the directory, although I see what you mean. The actions take `SplFileInfo` objects where everywhere else it's a string.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php (hunk 12 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:29]: `process_directory_recursively` perhaps? Or `apply_directory_action` ?

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php (hunk 13 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:60]: Both functions do something similar, but maybe `process_single_directory` ? Or `process_files` ?

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php (hunk 14 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php:1]: Ha, I'll add them to these actions then. :)

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php (hunk 15 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-filter-older.php:12]: Adnan wrote this, but maybe because this filter is an action itself, so $sub_action clearly separates the action to perform from the filter.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php (hunk 16 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php:17]: Good catch, I'll make apply_to_path return 1 after deleting.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php (hunk 17 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/path-actions/class-simple-delete.php:19]: I'll make it return 0. Other bits of code count the number of files affected.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/storage/class-file-storage.php (hunk 18 above)
Comment (donnchawp) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/storage/class-file-storage.php]: I was thinking of doing that, but forgot to change that. Thanks for the reminder. :)

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php (hunk 12 above)
Comment (dilirity) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:29]: I think we can ignore this. Let's not make this take any longer than necessary 😅

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php (hunk 13 above)
Comment (dilirity) [reply projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-filesystem-utils.php:60]: Let's ignore this for now.

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php [hunk 19]
```diff
@@ -466,15 +473,27 @@ public function rebuild_all() {
...
 		$post_path = $this->get_post_path_for_invalidation( $post );
-		if ( $post_path ) {
+		if ( null === $post_path ) {
+			return;
+		}
+
+		if ( Boost_Cache_Utils::trailingslashit( $post_path ) !== Boost_Cache_Utils::trailingslashit( home_url() ) ) {
 			$this->delete_recursive( $post_path );
+		} else {
+			$this->delete_page( $post_path );
```
Comment (haqadn) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/class-boost-cache.php:483]: 👍🏼

**Review by dilirity — APPROVED** [review]
