### PR TITLE
Search: Adds text description for post type icons

### LINKED ISSUE #25138: Instant Search: text description missing for post type icons
### Impacted plugin

Jetpack, Search

### Steps to Reproduce

1. On a site with Jetpack Instant Search enabled, perform a search with `/?s=&result_format=minimal`.
2. Inspect the post type icons with your browser a11y tools.

### A clear and concise description of what you expected to happen.

All icons should have a text description available.

### What actually happened

The page icon in my results did not have a text alternative.

### Browser

Mozilla Firefox

### Other information

Screen Shot 2022-07-20 at 15 14 09
Screen Shot 2022-07-20 at 15 48 32

### Platform (Simple, Atomic, or both?)

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by annacmc**
This PR adds a text description for the post-type icons displayed on the instant search overlay. 

Fixes #25138

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:

* On a site with Jetpack Instant Search enabled, perform a search with /?s=&result_format=minimal.
* Inspect the post-type icons with your browser a11y tools.
* Confirm that all icons have a text description available.

| Before  | After |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

File: projects/packages/search/src/instant-search/components/post-type-icon.jsx [hunk 1]
```diff
@@ -47,10 +48,22 @@ const PostTypeIcon = ( { postType, shortcodeTypes, iconSize = 18 } ) => {
 
 	switch ( postType ) {
 		case 'page':
-			return <Gridicon icon="pages" size={ iconSize } />;
+			return (
+				<Gridicon
+					icon="pages"
+					size={ iconSize }
+					description={ __( 'Page icon', 'jetpack-search-pkg' ) }
```
Comment (bluefuton) [inline projects/packages/search/src/instant-search/components/post-type-icon.jsx]: Having looked at a few examples, I reckon we should omit "icon" here.
```suggestion
					description={ __( 'Page', 'jetpack-search-pkg' ) }
```

Here's one: 

https://www.unimelb.edu.au/accessibility/techniques/accessible-svgs

...the last example is for a home icon, labelled "Home".

File: projects/packages/search/src/instant-search/components/post-type-icon.jsx [hunk 2]
```diff
@@ -47,10 +48,22 @@ const PostTypeIcon = ( { postType, shortcodeTypes, iconSize = 18 } ) => {
...
+				/>
+			);
 		default:
 			if ( hasGallery ) {
-				return <Gridicon icon="image-multiple" size={ iconSize } />;
+				return (
+					<Gridicon
+						icon="image-multiple"
+						size={ iconSize }
+						description={ __( 'Image icon', 'jetpack-search-pkg' ) }
```
Comment (bluefuton) [inline projects/packages/search/src/instant-search/components/post-type-icon.jsx]:
```suggestion
						description={ __( 'Image', 'jetpack-search-pkg' ) }
```

File: projects/packages/search/src/instant-search/components/gridicon/index.jsx [hunk 3]
```diff
@@ -228,6 +228,7 @@ class Gridicon extends Component {
 
 		return (
 			<svg
+				aria-label={ this.props?.description }
```
Comment (bluefuton) [inline projects/packages/search/src/instant-search/components/gridicon/index.jsx]: I think we can safely assume a React component will have a `this.props` so probably don't need the optional chaining here (I notice we access this.props a few lines below for focusable).
```suggestion
				aria-label={ this.props.description }
```

File: projects/packages/search/src/instant-search/components/post-type-icon.jsx (hunk 2 above)
Comment (bluefuton) [reply projects/packages/search/src/instant-search/components/post-type-icon.jsx]: Looking at the code, does the icon actually represent 'Gallery'?

**Review by kangzj — APPROVED** [review]
It works as described 👍
