### PR TITLE
Widgets: fix linting errors, part 2

### LINKED ISSUE #21993: PHPCS: Widgets 2
### Impacted plugin

Jetpack

### What

PHPCS

### How

```	
	"projects/plugins/jetpack/modules/widgets/mailchimp.php",
	"projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php",
	"projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php",
	"projects/plugins/jetpack/modules/widgets/my-community.php",
	"projects/plugins/jetpack/modules/widgets/rsslinks-widget.php",
	"projects/plugins/jetpack/modules/widgets/search.php",
	"projects/plugins/jetpack/modules/widgets/social-media-icons.php",
	"projects/plugins/jetpack/modules/widgets/top-posts.php",
	"projects/plugins/jetpack/modules/widgets/twitter-timeline.php",
	"projects/plugins/jetpack/modules/widgets/upcoming-events.php",
```

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #21993

#### Changes proposed in this Pull Request:

* Widgets: fix linting errors in Mailchimp popup widget.
* Widgets: fix linting errors in gallery widget.
* Widgets: fix linting errors in image widget
* Fix linting errors in community widget
* Fix linting errors in RSS widget
* Fix linting errors in Search widget
* Fix linting errors for old Social Icons widget
* Fix linting errors with the Top Posts widget
* Fix linting errors in Twitter Timeline widget
* fix linting errors in Upcoming Events widget

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* On a new site, go to Jetpack > Settings, search for widgets, and enable the feature.
* On the same screen, enable the Stats feature if it's not already enabled.
* Go to Plugins > Add New, install and activate the Classic Widgets plugin.
* Go to Appearance > Widgets, and try setting up those widgets.
    * You can use this URL to test the Upcoming Events widget: `https://calendar.google.com/calendar/ical/c_c8svl8hfcru362iflfq1ebnq78%40group.calendar.google.com/public/basic.ics`
* Test in Apperance > Customize and on the frontend as well.

### CODE REVIEW

File: projects/plugins/jetpack/modules/widgets/rsslinks-widget.php [hunk 1]
```diff
@@ -169,32 +200,35 @@ function form( $instance ) {
...
-		} elseif ( 'comments' == $type ) {
-			$type_text = __( 'Comments', 'jetpack' );
-			$rss_type  = 'comments_rss2_url';
+	/**
+	 * Output a link with a link to the feed.
+	 *
+	 * @param string $type Widget type (posts or comments).
+	 * @param array  $args Widget arguments.
+	 */
+	private function rss_link( $type, $args ) {
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/widgets/rsslinks-widget.php:221]: I refactored that method entirely, to make it easier to translate and somehow easier to parse. The current version was very hard to translate as we had translations split in different strings.

File: projects/plugins/jetpack/modules/widgets/social-media-icons.php [hunk 2]
```diff
@@ -1,23 +1,24 @@
...
 /**
  * WPCOM_social_media_icons_widget class.
  *
  * @extends WP_Widget
+ *
+ * phpcs:disable PEAR.NamingConventions.ValidClassName.Invalid
  */
 class WPCOM_social_media_icons_widget extends WP_Widget {
-
+	// phpcs:enable PEAR.NamingConventions.ValidClassName.Invalid
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/widgets/social-media-icons.php:21]: This had to be split instead of just a single `// phpcs:ignore` because otherwise it triggers another phpcs linting error.

File: projects/plugins/jetpack/modules/widgets/upcoming-events.php [hunk 3]
```diff
@@ -1,7 +1,28 @@
...
+ * @package automattic/jetpack
+ */
+
+/**
+ * Register the widget.
+ */
+function upcoming_events_register_widgets() {
+	register_widget( 'Jetpack_Upcoming_Events_Widget' );
+}
+add_action( 'widgets_init', 'upcoming_events_register_widgets' );
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/widgets/upcoming-events.php:16]: I moved this to the top of the file to be consistent with the other files.

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 4]
```diff
@@ -246,15 +302,20 @@ function widget( $args, $instance ) {
 		$types = isset( $instance['types'] ) ? (array) $instance['types'] : array( 'post', 'page' );
 
 		// 'likes' are not available in Jetpack
-		$ordering = isset( $instance['ordering'] ) && 'likes' == $instance['ordering'] ? 'likes' : 'views';
-
-		if ( isset( $instance['display'] ) && in_array( $instance['display'], array( 'grid', 'list', 'text' ) ) ) {
+		$ordering = isset( $instance['ordering'] ) && 'likes' === $instance['ordering'] ?
+			'likes'
+			: 'views';
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php:307]: I like better how you did this just above.
```suggestion
		$ordering = isset( $instance['ordering'] ) && 'likes' === $instance['ordering']
			? 'likes'
			: 'views';
```

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 5]
```diff
@@ -295,9 +356,9 @@ function widget( $args, $instance ) {
 			$posts = $this->get_fallback_posts( $count, $types );
 		}
 
-		echo $args['before_widget'];
+		echo $args['before_widget']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
 		if ( ! empty( $title ) ) {
-			echo $args['before_title'] . $title . $args['after_title'];
+			echo $args['before_title'] . esc_html( $title ) . $args['after_title']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php:361]: (same as above re escaping $title)

File: projects/plugins/jetpack/modules/widgets/top-posts.php [hunk 6]
```diff
@@ -681,8 +765,8 @@ public function get_posts( $post_ids, $count, $types = array( 'post', 'page' ) )
 			$posts[] = compact( 'title', 'permalink', 'post_id', 'post_type' );
 			$counter++;
 
-			if ( $counter == $count ) {
-				break; // only need to load and show x number of likes
+			if ( $counter == $count ) { // phpcs:ignore WordPress.PHP.StrictComparisons.LooseComparison
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/top-posts.php:768]: I wonder if we should just cast `$count` to an integer at the top of the function and make this strict.

Although I see the filter just below for some reason claims `$count` will be a string. Weird.

File: projects/plugins/jetpack/modules/widgets/upcoming-events.php [hunk 7]
```diff
@@ -1,7 +1,28 @@
...
+ * It relies on the icalendar-reader library.
+ *
+ * @package automattic/jetpack
+ */
+
+/**
+ * Register the widget.
+ */
+function upcoming_events_register_widgets() {
+	register_widget( 'Jetpack_Upcoming_Events_Widget' );
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/upcoming-events.php:14]: This nitpick again.
```suggestion
	register_widget( Jetpack_Upcoming_Events_Widget::class );
```

File: projects/plugins/jetpack/modules/widgets/upcoming-events.php [hunk 8]
```diff
@@ -26,106 +50,140 @@ function css() {
...
+		<label for="<?php echo esc_attr( $this->get_field_id( 'count' ) ); ?>"><?php esc_html_e( 'Items to show:', 'jetpack' ); ?></label>
+		<select id="<?php echo esc_attr( $this->get_field_id( 'count' ) ); ?>" name="<?php echo esc_attr( $this->get_field_name( 'count' ) ); ?>">
 			<?php
 			$i = 1;
 			while ( $i <= 10 ) {
-			?>
-				<option <?php selected( $instance['count'], $i ); ?>><?php echo $i; ?></option>
+				?>
+				<option <?php selected( $instance['count'], $i ); ?>><?php echo (int) $i; ?></option>
 			<?php $i++; } ?>
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/upcoming-events.php:90]: Seems weird that this isn't a for loop.
```suggestion
			<?php for ( $i = 1; $i <= 10; $i++ ) { ?>
				<option <?php selected( $instance['count'], $i ); ?>><?php echo (int) $i; ?></option>
			<?php } ?>
```

**Review by anomiex — COMMENTED** [review]
Did some static analysis, but didn't test it myself. Feel free to answer "no" to any of the questions, or otherwise disagree. The only thing that seems like an actual error is the lost handling of `$widgets` being a non-array in two places.

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php [hunk 9]
```diff
@@ -30,10 +31,13 @@ function jetpack_migrate_gallery_widget() {
...
-		// Try to get an unique id for the new type of widget.
-		// It may be the case that the user has already created a core Gallery Widget
-		// before the migration begins. (Maybe Jetpack was deactivated during core's upgrade).
-		for( $i = 0; $i < 10 && in_array( $new_id, array_keys( $media_gallery ) ); $i++, $new_id++ );
+
+		/*
+		 * Try to get an unique id for the new type of widget.
+		 * It may be the case that the user has already created a core Gallery Widget
+		 * before the migration begins. (Maybe Jetpack was deactivated during core's upgrade).
+		 */
```
[the remark this answers is not in the document]
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php:39]: No, that was me, I personally find this more readable that way, but I realize that's very much a personal thing. :)

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php [hunk 10]
```diff
@@ -176,9 +185,11 @@ function jetpack_migrate_image_widget() {
 		}
 
 		foreach ( $sidebars_widgets as $sidebar => $widgets ) {
+			$key = array_search( "image-{$id}", $widgets, true );
```
[the remark this answers is not in the document]
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php]: 👍 db601e7528d102ac5aef407efc877a00d2c9d2f0

File: projects/plugins/jetpack/modules/widgets/my-community.php [hunk 11]
```diff
@@ -68,14 +68,14 @@ function enqueue_style() {
...
-	function form( $instance ) {
+	public function form( $instance ) {
 		$title = isset( $instance['title'] ) ? $instance['title'] : false;
 		if ( false === $title ) {
 			$title = $this->default_title;
 		}
 
 		$number = isset( $instance['number'] ) ? $instance['number'] : 10;
-		if ( ! in_array( $number, array( 10, 50 ) ) ) {
+		if ( ! in_array( $number, array( 10, 50 ) ) ) { // phpcs:ignore WordPress.PHP.StrictInArray.MissingTrueStrict
```
[the remark this answers is not in the document]
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/my-community.php]: 👍 0d453bd02ab96c1713664f3315745bbf430ae7d2

File: projects/plugins/jetpack/modules/widgets/my-community.php [hunk 12]
```diff
@@ -131,15 +131,15 @@ function form( $instance ) {
...
 		$instance          = array();
 		$instance['title'] = wp_kses( $new_instance['title'], array() );
 		if ( $instance['title'] === $this->default_title ) {
-			$instance['title'] = false; // Store as false in case of language change
+			$instance['title'] = false; // Store as false in case of language change.
 		}
 
 		$instance['number'] = (int) $new_instance['number'];
-		if ( ! in_array( $instance['number'], array( 10, 50 ) ) ) {
+		if ( ! in_array( $instance['number'], array( 10, 50 ) ) ) { // phpcs:ignore WordPress.PHP.StrictInArray.MissingTrueStrict
```
[the remark this answers is not in the document]
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/my-community.php]: 👍 977b3ccaa8cb5e555d388f6d3b77efb81644f08f

File: projects/plugins/jetpack/modules/widgets/my-community.php [hunk 13]
```diff
@@ -180,10 +181,10 @@ function widget( $args, $instance ) {
 		/** This filter is documented in wp-includes/widgets/class-wp-widget-pages.php */
 		$title = apply_filters( 'widget_title', $title );
 
-		echo $args['before_widget'];
+		echo $args['before_widget']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
 
 		if ( ! empty( $title ) ) {
-			echo $args['before_title'] . $title . $args['after_title'];
+			echo $args['before_title'] . esc_html( $title ) . $args['after_title']; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
[the remark this answers is not in the document]
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/my-community.php]: I'm not too sure what to make of this. We do escape the title in some of our widgets already, but not all. In core, they don't escape them indeed, but they do run them through `sanitize_text_field` on save. 

Maybe we shouldn't escape them, and assume folks using the `widget_title` filter may use the filter to add HTML to all widget titles.

I'll remove it from this one, and all others while I'm at it.
10edd7b10145c90eb33bcf0d6faccaa3301376f0

File: projects/plugins/jetpack/modules/widgets/top-posts.php (hunk 4 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/top-posts.php:307]: Yep, that was an oversight from me. Committing.

File: projects/plugins/jetpack/modules/widgets/top-posts.php (hunk 6 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/top-posts.php:768]: This was one of those cases where I prefer to leave it as it is to avoid breaking something that doesn't immediately seem obvious to me. I think I'll leave it like that for now. :)

File: projects/plugins/jetpack/modules/widgets/upcoming-events.php (hunk 8 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/upcoming-events.php]: 👍 75bdcd8c991a1da7e475fe980f62c24cdcae3652

**Comment by jeherve** [comment]
Thanks for the review. I think I've addressed all your comments, it should be ready for another go!

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php [hunk 14]
```diff
@@ -92,81 +107,93 @@ function jetpack_migrate_gallery_widget_is_importable( $widget ) {
...
  */
 function jetpack_migrate_gallery_widget_update_sidebars( $sidebars_widgets, $id, $new_id ) {
 	foreach ( $sidebars_widgets as $sidebar => $widgets ) {
+		$key = is_array( $widgets ) ? array_search( "gallery-{$id}", $widgets, true ) : false;
+
 		if (
 			is_array( $widgets )
-			&& false !== ( $key = array_search( "gallery-{$id}", $widgets, true ) )
+			&& false !== $key
 		) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php:190]: No need to check `is_array()` again now.
```suggestion
		if ( false !== $key ) {
```

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php [hunk 15]
```diff
@@ -176,9 +185,11 @@ function jetpack_migrate_image_widget() {
 		}
 
 		foreach ( $sidebars_widgets as $sidebar => $widgets ) {
+			$key = is_array( $widgets ) ? array_search( "image-{$id}", $widgets, true ) : false;
+
 			if (
 				is_array( $widgets )
-				&& false !== ( $key = array_search( "image-{$id}", $widgets, true ) )
+				&& false !== $key
 			) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php:193]: No need to check `is_array()` again now.
```suggestion
		if ( false !== $key ) {
```

**Review by anomiex — COMMENTED** [review]
Two minor suggestions, otherwise looks good

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php (hunk 14 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/migrate-to-core/gallery-widget.php]: 👍 b7c781e90394caa4c851f6a770e99d7648721e90

File: projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php (hunk 15 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/migrate-to-core/image-widget.php]: 👍 b7c781e90394caa4c851f6a770e99d7648721e90

**Review by anomiex — DISMISSED** [review]

**Comment by jeherve** [comment]
I'm afraid this is going to need one last review, I had to bump a package's version.

**Comment by jeherve** [comment]
r236617-wpcom

**Review by anomiex — APPROVED** [review]
