### PR TITLE
Jetpack: WordPress 6.8 Compatibility - Fix data manipulation within useSelect in core features

### LINKED ISSUE #42434: Jetpack: WordPress 6.8 Compatibility - Fix data manipulation within useSelect in core features
### Issue

This is a sub-issue of https://github.com/Automattic/jetpack/issues/42421

Within the Jetpack plugin, there are various instances where the usage of `useSelect` will result in fairly bulky console warnings in WordPress 6.8, if script debug is enabled on a site:

* Blogging Prompt - `usePromptTags`
* Donations block - `selectedProducts`
* Button block - `attributesToSync`
* Slideshow block - `slideshowEdit`

These instances should be fixed.

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes https://github.com/Automattic/jetpack/issues/42434

## Proposed changes:

* This PR modifies how data is manipulated in several instances where they are included within `useSelect` calls. This prevents console warnings in the upcoming WordPress 6.8 release, if script debug is enabled. 
* More information in the parent issue: https://github.com/Automattic/jetpack/issues/42421
* The affected features / blocks:
  * Blogging Prompt
  * Button block
  * Payment buttons
  * Slideshow block
* The changes include:
  *  Only the items that actually change get new references
  * `useMemo` prevents unnecessary object creation, and only recalculates when dependencies actually change (`usePassthroughAttributes`)
  * `ProductManagementToolbarControl` returns the selector's value directly without wrapping it in an object and only changes when `getSelectedProducts` returns a new object.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

On a self-hosted test site, to reproduce the issues on trunk:

* Make sure script debug is enabled for your site: `define( 'SCRIPT_DEBUG', true );` in `wp-config.php`.
* Install the WordPress Beta Tester plugin
* Go to Tools > Beta Testing, and set the plugin to use Beta/RC Only (in order to upgrade to WP 6.8-beta3)
* Go to Dashboard > Updates, and update to WP 6.8-beta3.
* Open up a new post. You will likely see other similar console warnings that will be addressed separately. However to replicate the warnings relevant to this PR:
  * Add a Writing Prompt block, then check console errors. See below for what to look for.
  * Clear the console and add a Slideshow block. As before, see below for what to look for in the console.
  * Clear the console and add a Payments Button block. You may also need to add a new payment plan as well (which will involve connecting Stripe - there may be accounts in the SS that could be used for that)
* In all cases you'll see a console warning similar to this: `The useSelect hook returns different values when called with the same state and parameters. This can lead to unnecessary re-renders and performance issues if not fixed.`
* The writing prompt non-equal value key relates to `tags`, and the Error Component Stack begins with `BloggingPromptEdit` (note - the red tags post request console warning occurs on trunk as well, unrelated)
* The Payments button block non-equal value key relates to `selectedProducts`, and the Error Component Stack begins with `ProductManagementToolbarControl`. The button block issue also visible with the Payments button block, has a non-equal value key of `attributesToSync`.
* The Slideshow blocknon-equal value key relates to `resizedImages`.

To test the fix:
* Apply this PR if testing locally (if using Jurassic Ninja or another test site, use the Jetpack Beta Tester plugin) and refresh the post after clearing the console. Those warnings should not appear. Ensure the block functionality is as expected.

You can also test on WoA and Simple (without testing WP 6.8) to ensure no issues with the blocks.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/blogging-prompt/use-prompt-tags.js [hunk 1]
```diff
@@ -31,30 +31,59 @@ export function usePromptTags( promptId, tagsAdded, setTagsAdded ) {
...
-			tagsHaveResolved:
-				_termIds && _termIds.length
-					? hasFinishedResolution( 'getEntityRecords', [ 'taxonomy', 'post_tag', query ] )
-					: true,
-		};
-	}, [] );
+	// Get tags with memoized query
+	const tags = useSelect(
+		select => {
+			if ( tagIds.length === 0 ) {
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/blogging-prompt/use-prompt-tags.js:69]: Could that condition be moved out of the function passed to `useSelect`? Or would that create an issue?

File: projects/plugins/jetpack/extensions/blocks/slideshow/edit.js [hunk 2]
```diff
@@ -192,14 +192,35 @@ export const SlideshowEdit = ( {
 	);
 };
 
+const memoCache = new Map();
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/slideshow/edit.js:195]: I'm wondering whether we should clear the map somewhere, maybe when `SlideshowEdit` unmounts. But that may be overkill.

File: projects/plugins/jetpack/extensions/blocks/blogging-prompt/use-prompt-tags.js (hunk 1 above)
Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/blogging-prompt/use-prompt-tags.js:69]: So, `useSelect` itself can't be called conditionally. I believe we could miss important store updates when switching between states as well if we were able to use it conditionally.

File: projects/plugins/jetpack/extensions/blocks/slideshow/edit.js (hunk 2 above)
Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/slideshow/edit.js:195]: Good thought, thank you. I looked into this more, and from what I understand it would be overkill based on page refresh that should clean this up so the cache is per session, and that the data is lightweight (only image id and size information, not remaining image information). And lastly in attempting to add this it was turning into a complex operation as well.
As for page refresh cleaning the data up, I could confirm this by adding `window.debugMemoCache = memoCache;` to the code, then logging this in the browser console before adding a block with images, and then after a page refresh. After the page refresh it defaults back to a size of 1. And if I remove the Slideshow ad refresh, the cache is gone.
So based on that I think most likely overkill here, would you agree?

**Comment by coder-karen** [comment]
Thanks for the reviews @monsieur-z ! Separately I realized there were a couple of other small improvements I could make, explained in the additional commit messages, so I've just pushed those changes now too.

File: projects/plugins/jetpack/extensions/blocks/slideshow/edit.js (hunk 2 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/extensions/blocks/slideshow/edit.js:195]: Absolutely! Thanks for looking it up.

**Review by monsieur-z — APPROVED** [review]
LGTM! The code changes seem appropriate and the PR tested as expected (tested on a self-hosted site). I could no longer see the warnings except for that one.
Screenshot 2025-03-20 at 10 35 00 AM

**Comment by coder-karen** [comment]
Thanks @monsieur-z ! Yes that one is dealt with in a separate PR here: https://github.com/Automattic/jetpack/pull/42536

**Comment by ellatrix** [comment]
I'm seeing these warnings in the console on Dotcom:

```
index.js:33 The `useSelect` hook returns different values when called with the same state and parameters.
This can lead to unnecessary re-renders and performance issues if not fixed.

Non-equal value keys: attributesToSync
```

Could it be related to this PR?

**Comment by ellatrix** [comment]
Or, maybe you just fixed that haha :D
