### PR TITLE
Copy Post: Fix content for non-standard post formats.

### LINKED ISSUE #11256: Copy a post: Content not copied when using Block editor and default post format set in Settings > Writing
#### Steps to reproduce the issue

0. Make sure your theme supports post types (such as `Twenty Seventeen`)
0. Under Settings > Writing, set a default post format other than "Standard"
1. Go to `wp-admin/post-new.php`
2. Set 'Gallery' or 'Image' post format
3. Add a paragraph and gallery blocks as a content
4. Publish and try to copy the post.
5. Post copied without content

#### What I expected

post content is copied no matter what post format I used

#### What happened instead

See reproduction steps

screencast 2019-02-04 16-09-44

### PR DESCRIPTION
**Pull request by kwight**
When the new post screen is loading, it believes it is loading a newly-created post with default content, and attempts to set the post format to the default selected in `Settings > Writing`. Since Copy Post has already taken care of assigning the proper post format, we can take advantage of `set_post_format`'s shortcircuit to stop core from making any changes.

Fixes #11256 .

#### Testing instructions:
* Apply this PR.
* Set the default post format to something other than standard, in `Settings > Writing`.
* Set up a test post that has a post format other than standard, and different from the default.
* Copy the test post.
* Verify that content is correct, and that the post format of the source post is preserved in the newly-created post.

#### Proposed changelog entry for your changes:
* Fixed a bug with Copy Post and its handling of non-standard post formats.

### CODE REVIEW

**Comment by kwight** [comment]
This is the first step; the block editor will no longer modify content for post formats. However, the post format itself is still incorrectly set by the block editor to whatever the default is in `Settings > Writing > Default Post Format`.

File: modules/copy-post.php [hunk 1]
```diff
@@ -32,6 +32,7 @@ public function __construct() {
 
 		if ( ! empty( $_GET['jetpack-copy'] ) && 'post-new.php' === $GLOBALS['pagenow'] ) {
 			add_action( 'wp_insert_post', array( $this, 'update_post_data' ), 10, 3 );
+			add_filter( 'pre_option_default_post_format', array( $this, 'shortcircuit_default_post_format' ) );
```
Comment (jeherve) [inline modules/copy-post.php]: Could we use `__return_empty_string` here instead of creating an extra function?

**Review by jeherve — CHANGES_REQUESTED** [review]
It works well for me. I only have one small remark.

**Review by mmtr — COMMENTED** [review]
Tested manually and it worked as expected :)

File: modules/copy-post.php (hunk 1 above)
Comment (kwight) [reply modules/copy-post.php]: Ha! Well spotted, I had no idea we had that. I was even thinking, "gee, too bad I can't return false, I could have just used `__return_false`" 😜Will do!

**Review by jeherve — APPROVED** [review]
This is looking good. Merge when ready.
