### PR TITLE
Pay with PayPal: Save product in Customize > Widgets

### LINKED ISSUE #61319: [Bug]: Pay with Paypal block: Block not saved in Widgets in Customizer
### Quick summary

When adding a new Pay with Paypal block in the Site Editor and in Widgets page, the block does not appear after the user updates the page.

### Steps to reproduce

1. Go to Appearance > Customizer > Widgets
2. Add a new Pay with Paypal block and press Save
3. Go to the front-end and notice that the block is not displayed
4. Go to the editor and refresh the page. The block appears in the editor.
5. Go back to the front-end and notice that block is being displayed on the front-end (after the refresh).

### What you expected to happen

The block to be displayed when the user clicks on the save/update button.

### What actually happened

The block is not visible on the front-end even though it's displayed in the editor.

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

Simple, Atomic

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

The user will need to refresh the editor page in order for the block to be displayed on the front-end.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/61319

#### Changes proposed in this Pull Request:
Ensures that Simple Payment products created via the Pay with PayPal blocks inside Customize > Widgets are saved after changing the widgets, so the block is displayed in both the preview and frontend after doing any change to the block.

The only problem is that since changes need to be reflected in real time the Customizer preview, I needed to validate the attributes after every change (as opposed to the behavior in a normal post editor where attributes are only validated after deselecting the block), so users will get validation errors as soon as they start filling the block.

#### Jetpack product discussion
N/A

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
- Apply these changes to a Jetpack site, WP.com Simple site, or WP.com Atomic site.
- Switch to a non-FSE theme like Twenty Twenty-One.
- Go to Appearance > Customize > Widgets.
- Insert a Pay with PayPal block.
- Select a widget area.
- Make sure the block shows up in the preview after entering correct values.
- Save the changes.
- Visit the frontend.
- Make sure the block shows up in the frontend.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js [hunk 1]
```diff
@@ -76,6 +77,24 @@ export class SimplePaymentsEdit extends Component {
 				} ),
 			} );
 		}
+
+		window.wp?.customize?.bind( 'change', setting => {
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js:81]: Do you think it would be useful to add a check for the customizer before doing this bind?

Richard is working on a `getEditorType` function used to target every known editor type (post, site, etc. including the customizer): https://github.com/Automattic/jetpack/pull/23828

**Review by Copons — APPROVED** [review]
This works well for me!
The comment I left is minor and it shouldn't really change the behaviour anyway.

I'm approving but let's wait to double-check with @Automattic/jetpack-crew about the new `@wordpress/widgets` package.

File: projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js:81]: > Richard is working on a getEditorType function used to target every known editor type (post, site, etc. including the customizer):

This is going to be handy! 🙏

**Review by jeherve — APPROVED** [review]
Looks good to me. 🚢

File: projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js (hunk 1 above)
Comment (mmtr) [reply projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js:81]: > Do you think it would be useful to add a check for the customizer before doing this bind?

I think I'm already doing that with `window.wp?.customize?`? AFAIK the `window.wp.customize` global is only defined in the customizer.

I'm happy to use the new `getEditorType` function though for consistency with the rest of the code, so I can wait for https://github.com/Automattic/jetpack/pull/23828 to land first.

Comment (Copons) [reply projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js:81]: In this specific case we can go ahead without the `getEditorType` since we are forced to test for `wp.customize` anyway. 👍

**Comment by mmtr** [comment]
r243396-wpcom
