### PR TITLE
Sharing: force get sharing options when saved options are incorrect

### LINKED ISSUE #6121: Sharing: Catchable fatal error
In some specific configurations, one gets the following error when the Sharing module is active:

```
Catchable fatal error: Argument 2 passed to Share_Facebook::__construct() must be of the type array, null given, called in wp-content/plugins/jetpack/modules/sharedaddy/sharing-service.php on line 207 and defined in wp-content/plugins/jetpack/modules/sharedaddy/sharing-sources.php on line 871
```

Digging into this right now to find out more.

Reported here:
- 2996281-t ( cc @rachelsquirrel)

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #6121

When testing on one of the sites mentioned in #6121, `get_option( 'sharing-options' );` would return data saved from another plugin, Yoast SEO. On a regular site, Yoast SEO saves that data in `get_option( 'wpseo_social' );`, but on that particular site, `get_option( 'sharing-options' );` always returned data from the `wpseo_social` option.

One way to work around this was to add an additional check when checking for the integrity of the data we got from `get_option( 'sharing-options' );`.

That's what I came up with, but I'd be happy to consider other alternatives, though :)

Since Yoast SEO wasn't even installed on the other site, I guess the original problem may be linked to database configuration or caching issues.

#### Proposed changelog entry for your changes:

* Sharing: force get sharing options when saved options are incorrect due to site configuration issues. Avoids potential fatal errors.

### CODE REVIEW

**Comment by samhotchkiss** [comment]
Seems like a reasonable fix, however, it'd be nice to have a comment on it in the code so that when our future selves look at it, we don't think "why did we do that?  that's not needed!  let's take it out!"

File: modules/sharedaddy/sharing-service.php [hunk 1]
```diff
@@ -170,8 +170,14 @@ public function get_blog_services() {
 		$enabled  = get_option( 'sharing-services' );
 		$services = $this->get_all_services();
 
-		if ( !is_array( $options ) )
+		/**
+		 * Check if options exist and are well formatted.
+		 * This avoids issues on sites with corrupted options.
+		 * @see https://github.com/Automattic/jetpack/issues/6121
+		 */
+		if ( ! is_array( $options ) || ! isset( $options['button_style'] ) ) {
```
Comment (georgestephanis) [inline modules/sharedaddy/sharing-service.php]: Should this do `isset( $options['button_style'],  $options['global'] )` to test for `global` as well?  Just as we're about to use it in the subsequent line after the conditional.

Comment (jeherve) [inline modules/sharedaddy/sharing-service.php]: Good call. 4f0e8029e1cf78004bc73ea2fdc4e0fbcf0d6875
