### PR TITLE
Fix PHP warnings when user subscribes to comments

### LINKED ISSUE #3339: "Notify me of follow-up comments by email" produces PHP Warning
Checking the "Notify me of follow-up comments by email" checkbox when commenting produces a PHP Warning on the next pageload:

```Notice: Trying to get property of non-object in [...]/wp-content/plugins/jetpack/modules/subscriptions.php on line 730```

Running Jetpack 3.9.1, WP 4.4.1. Happy to provide any additional debugging information that you need.

### PR DESCRIPTION
**Pull request by cfinke**
Fixes #3339. 

#### Changes proposed in this Pull Request:

Reported in #3339, PHP warnings are generated when a user subscribes to comments, and the cookie is set with a null value instead of the expected post ID, making the cookie useless since the check in `comment_subscribe_init()` will never pass.

This patch fixes the reference to the post ID, and it saves the "Subscribe to all comments" value for each post separately. Previously, if a user subscribed to comments on post 1, then commented on post 2 and did not subscribe to comments on it, the checkbox on post 1 would remain unchecked. Now, both checkboxes will have the appropriate state.

This will increase the number of cookies set for users that subscribe to comments on many individual posts. We may wish to revisit the ~1-year cookie expiration limit.

#### Testing instructions:
1. Comment on a post. Leave both subscription checkboxes unchecked. Observe no PHP warnings, and both boxes remain unchecked.
1. Comment on a post. Check only the comments subscription checkbox. Observe no PHP warnings, and only the comment checkbox is checked. Visit another post. Observe that the comment checkbox is not checked.
1. Comment on a different post. Check both subscription checkboxes. Observe no PHP warnings, and both checkboxes should remain checked. Visit the post commented on in the previous step. Observe both checkboxes are now checked.
1. Re-comment on the first post, and uncheck both subscription checkboxes. Observe no PHP warnings, and both checkboxes should now be unchecked. Visit the second post commented on above, and observe that the comment subscription box is checked.

### CODE REVIEW

**Comment by cfinke** [comment]
This change would also ignore any cookies previously set for single-post comment subscriptions. How important is that?  Backwards compatibility could be added by restoring the deleted part of the check on line 579.

**Comment by cfinke** [comment]
One of the checks failed, but it looks unrelated to this changeset.

File: modules/subscriptions.php [hunk 1]
```diff
@@ -708,12 +715,12 @@ function set_cookies( $comments = true, $posts = true ) {
 		 */
 		$cookie_domain   = apply_filters( 'jetpack_comment_cookie_domain', COOKIE_DOMAIN );
 
-		if ( $comments )
-			setcookie( 'jetpack_comments_subscribe_' . self::$hash, $post->ID, time() + $cookie_lifetime, $cookie_path, $cookie_domain );
+		if ( $subscribe_to_post && $post_id >= 0 )
```
Comment (kraftbj) [inline modules/subscriptions.php]: While we're touching these lines, would be nice to upgrade them to WP coding standards (adding braces), but not a blocker.

Comment (cfinke) [inline modules/subscriptions.php]: I actually had done that and reverted it to make the diff cleaner. ¯\_(ツ)_/¯

**Comment by kraftbj** [comment]
Reran tests so all's green now. I haven't manually tested the PR yet though (thus still needs review before merge).

**Comment by rcoll** [comment]
Added some braces, rebased, and tested. Everything looks good for a merge :smile:

**Comment by zinigor** [comment]
Thanks, this works great!
