### PR TITLE
VideoPress: Add original core/video attributes to extended attributes definition for v5

### LINKED ISSUE #30571: Adding Subtitles to a 'regular' video block causes Block Recovery
### Impacted plugin

Jetpack

### Quick summary

With https://jetpack.com/support/jetpack-blocks/ activated, I can no longer include subtitles

### Steps to reproduce

1. Create a post with a video (remote or local, doesn't matter)
2. Upload VTT file to WordPress
3. Edit the block to add text tracks 
4. Save the post
5. Refresh the editor

### A clear and concise description of what you expected to happen.

Video should have subtitles. Yay!

### What actually happened

Block Validation Fails :( 

Screenshot 2023-05-09 at 3 41 06 PM

```
Block validation: Block validation failed for `core/video` (Object).

Content generated by `save` function:

<figure class="wp-block-video"><video controls src="https://example.com/video.mp4"></video></figure>

Content retrieved from post body:

<figure class="wp-block-video"><video controls src="https://example.com/video.mp4"><track src="https://example.local/wp-content/uploads/2023/05/video.vtt" label="English" srclang="en" kind="subtitles"/></video></figure>
```

I reproduced this on a clean site without any plugin except Jetpack, as well as with a bunch more plugins, different themes, ec.

The only fix is to disable the blocks. :( 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #30571

## Proposed changes:

* Adds the original `core/video` attributes (this issue particularly needs the `tracks` attribute) to the blocks attributes so the saved content matches the save function

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Do NOT install Jetpack
* Go to the block editor and add a `core/video` block
* Upload subtitles to the videos tracks and save the post
* Hard refresh
* Check that the block is rendered as normal
* Install and activate Jetpack
* Go back to the post in the block editor
* Hard refresh
* Check that the block is rendered as normal, without invalid content
* Check that the subtitles work as expected

Before | After
-|-
 |

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/videopress/editor.js [hunk 1]
```diff
@@ -292,6 +292,13 @@ const addVideoPressSupport = ( settings, name ) => {
 				},
 				default: [],
 			},
+			tracks: {
```
Comment (retrofox) [inline projects/plugins/jetpack/extensions/blocks/videopress/editor.js]: we should map this attribute with [videoPressTracks](https://github.com/Automattic/jetpack/blob/99937fb86a9287312c5df88dcf9eb4f64184fdc4/projects/plugins/jetpack/extensions/blocks/videopress/editor.js#LL288C4-L288C20) instead of adding a new one.

Comment (dhasilva) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js]: The thing is, they are not related to VideoPress at all. They are listed as `tracks` originally, before the extension from `core/video`, and since `tracks` is not in the attributes list, the attribute is removed and we end with a `<track ...` tag without the attribute.

Comment (dhasilva) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js]:
```
		const attributesDefinition = {
			...settings.attributes,
```
also works, but there may be unintended side effects doing this?

Comment (dhasilva) [reply projects/plugins/jetpack/extensions/blocks/videopress/editor.js]: The issue here is that the block is registered in general, irrespective of a particular block's data, but overwriting the attributes and removing some of the original ones. When a block does not use a VideoPress video, but a local one, this causes the rendering problem.

I updated the PR to add the original attributes before the new ones, so if an attribute is not used by v5 they are simply ignored, but normal videos do not break.

**Review by retrofox — APPROVED** [review]
