### PR TITLE
Facebook Widget parse args to prevent undefined warnings

### LINKED ISSUE #2844: Widgets: Facebook Page Plugin PHP notice
Steps to reproduce:

1. Drag a new Facebook Like Box widget to your sidebar
2. Enter a Facebook Page URL, but not touch any other setting,
3. Save your widget settings.

```
[13-Oct-2015 18:13:03 UTC] PHP Notice:  Undefined index: stream in /wp-content/plugins/jetpack/modules/widgets/facebook-likebox.php on line 107
```

### PR DESCRIPTION
**Pull request by chaselivingston**
Fixes #2844

### CODE REVIEW

File: modules/widgets/facebook-likebox.php [hunk 1]
```diff
@@ -104,7 +104,7 @@ function update( $new_instance, $old_instance ) {
 			'href'        => trim( strip_tags( stripslashes( $new_instance['href'] ) ) ),
 			'height'      => (int) $new_instance['height'],
 			'show_faces'  => (bool) $new_instance['show_faces'],
-			'stream'      => (bool) $new_instance['stream'],
+			'stream'      => (bool) $new_instance['stream'] = false,
```
Comment (dereksmart) [inline modules/widgets/facebook-likebox.php]: This will overwrite the option always. We should be checking if there is a new instance of it before we write it.

something like `isset( $new_instance['stream'] ) ? (bool) $new_instance['stream'] : false,`
