### PR TITLE
SEO tools suite loading even if the site is not active and not in development mode.

### LINKED ISSUE #7898: Jetpack SEO throws fatal error on multisite
Happens only on multisite, tested with unconnected site.
On front end, I'm getting
```
Fatal error: Uncaught Error: Class 'Jetpack_SEO_Utils' not found in /wp-content/plugins/jetpack/modules/seo-tools/jetpack-seo.php on line 108
```

```
Error: Class 'Jetpack_SEO_Utils' not found in /wp-content/plugins/jetpack/modules/seo-tools/jetpack-seo.php on line 108```
```

### PR DESCRIPTION
**Pull request by zinigor**
This is required because with some recent changes in the code SEO tool class constants are required by the code even when Jetpack is not active, for example in multisite environment.

Fixes #7898.

### CODE REVIEW

File: modules/module-extras.php [hunk 1]
```diff
@@ -27,10 +27,20 @@
...
+		'seo-tools/jetpack-seo-titles.php',
+		'seo-tools/jetpack-seo-posts.php',
+	);
+}
+
 /**
  * Filter extra tools (not modules) to include.
  *
  * @since 2.4.0
+ * @since 5.4.0 can be used when Jetpack is not connected to WordPress.com and not in development mode.
```
Comment (dereksmart) [inline modules/module-extras.php]: Only in multisite though, otherwise this file will never be loaded as it's blocked [here](https://github.com/Automattic/jetpack/pull/7900/files#diff-9ba9fa5bb52bd6cf36c6c0bdd5ed4830R1657)

**Comment by dereksmart** [comment]
merged to 5.4 0cc6b97d1
