### PR TITLE
Widget Visibility - Fix broken dropdowns after updating to 4.7

### LINKED ISSUE #6596: Widget Visibility: rules disappear when updating from 4.6 to 4.7.
I haven't been able to reproduce on my own sites just yet, but this appears to be an issue for multiple users after updating from Jetpack 4.6 to Jetpack 4.7.

#### Steps to reproduce the issue

1. Start from a site running Jetpack 4.6.
2. Go to Appearance > Widgets and set up some widgets with custom visibility rules.

screen shot 2017-03-07 at 22 27 21

4. Update to Jetpack 4.7.
5. The rules don't appear anymore in the widget settings, but are still applied on the front end.

This was most likely introduced in ##6333.

To figure this out **we'll need to know the exact set of rules that disappeared upon update. It may be limited to specific rules (e.g. #6595).**

----
Reported here:
- 3096698-t
- https://wordpress.org/support/topic/jetpack-4-7-upgrade-removes-widget-visibilitys-original-settings/

### PR DESCRIPTION
**Pull request by Stoyan0v**
Fixes #6596 #6595

#### Changes proposed in this Pull Request:

* Fix broken dropdowns after updating to 4.7

Since "Post Type" option has been removed in 4.7, there is an js error when you open the widget visibility after updating from 4.6 to 4.7. The `majorData` variable is empty and it prevents other conditions to be shown. This PR adds a check that the `major` rule is not `post_type` and additional check that `widget_conditions_data` has the property, before we make anything.

visibility-options-error

#### Testing instructions:

* Install Jetpack 4.6
* Add a widget to any sidebar
* Add a Post Type rule in the beginning 
* Add other rule/rules ( it doesn't matter which one )
* Update to Jetpack 4.7
* Check that all other rules except the "Post type" one are displayed ( similar to the following image )
visibility-options

### CODE REVIEW

File: modules/widget-visibility/widget-conditions/widget-conditions.js [hunk 1]
```diff
@@ -200,32 +200,36 @@ jQuery( function( $ ) {
 			select = condition.find( '.conditions-rule-minor' ).html( '' ),
 			major = condition.data( 'rule-major' );
 
-		if ( ! major ) {
+		if ( ! major || major === 'post_type' ) {
```
Comment (zinigor) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: Can you please modify the condition to be Yoda-style `'post_type' ===`. Also, let's add a comment before this condition that it's done for backwards compatibility in order to avoid errors when people have "Post Type" selected?

File: modules/widget-visibility/widget-conditions/widget-conditions.js [hunk 2]
```diff
@@ -200,32 +200,36 @@ jQuery( function( $ ) {
...
 		}
 
 		minor = condition.data( 'rule-minor' );
 		hasChildren = condition.data( 'rule-has-children' );
-		majorData = widget_conditions_data[ major ];
 
-		for ( i = 0, _len = majorData.length; i < _len; i++ ) {
-			key = majorData[i][0];
-			val = majorData[i][1];
+		if ( widget_conditions_data.hasOwnProperty(major) ) {
```
Comment (zinigor) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: I'd say that the change below is not needed because this can only be false when `major` is `post_type`, and we have already cut that flow out with the previous condition. Let me know if I'm not seeing something.

Comment (Stoyan0v) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: Do you think it will be better if we remove the first condition and leave this one? It may prevent similar issues in the future if there are such, while the first one will handle `post_type` only. I wasn't sure which one is better that's why added both.

Comment (zinigor) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: Yeah, makes sense, but I'd rather not have a huge wrapping condition like this, because we don't remove major rules that often. It has only happened once so far afaik.

Comment (Stoyan0v) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: Makes sense, thanks for clarification 😄

File: modules/widget-visibility/widget-conditions/widget-conditions.js (hunk 1 above)
Comment (Stoyan0v) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: I've added a comment and changed the condition to Yoda-style. Thank you!

**Comment by dereksmart** [comment]
👍  thanks!

**Comment by dereksmart** [comment]
branch-4.7 175c260
