### PR TITLE
Sharing: do not record stats if the stats module is disabled.

### LINKED ISSUE #9678: Sharing: do not track stats when the Stats feature is disabled #9183
Follow-up to #9183 

We currently add a tracking pixel  when Jetpack is active but we should check if the Stats module is active too:

https://github.com/Automattic/jetpack/blob/6.1/modules/sharedaddy/sharing.js#L102

#### Steps to reproduce the issue
_Will add later_
#### What I expected
_Will add later_
#### What happened instead
_Will add later_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #9678

#### Changes proposed in this Pull Request:

When the Stats module is disabled, do not use any tracking pixel on pages using sharing buttons.

#### Testing instructions:

1. Enable Sharing and Stats.
2. Add a Facebook button to your posts.
3. Load a post and check requests in the network tab; you will see 2 requests to `pixel.wp.com`; one for regular stats and one for sharing.
4. Disable the Stats module (under the old Module settings screen)
5. Reload the post's page; you should see no `pixel.wp.com` request.

#### Proposed changelog entry for your changes:

- Sharing: do not record stats if the stats module is disabled.

### CODE REVIEW

File: modules/sharedaddy/sharing-service.php [hunk 1]
```diff
@@ -613,9 +613,10 @@ function sharing_add_footer() {
 
 		wp_enqueue_script( 'sharing-js' );
 		$sharing_js_options = array(
-			'lang'   => get_base_recaptcha_lang_code(),
+			'lang'            => get_base_recaptcha_lang_code(),
 			/** This filter is documented in modules/sharedaddy/sharing-service.php */
-			'counts' => apply_filters( 'jetpack_sharing_counts', true ),
+			'counts'          => apply_filters( 'jetpack_sharing_counts', true ),
+			'is_stats_active' => Jetpack::is_module_active( 'stats' ),
```
Comment (dereksmart) [inline modules/sharedaddy/sharing-service.php]: This method does not exist in wpcom, so this change cannot be synced back as-is.
