### PR TITLE
MU WPCOM: don't enqueue block scripts in the canvas iframe!

### LINKED ISSUE #98447: Odd scrolling behaviour in the post editor
### Context and steps to reproduce

When the user clicks on the scroll bar in the post editor, the page scrolls down to the bottom of the editor.

1. Start from this draft post: https://wordpress.com/post/monkeystale.ca/79017
2. Click on the scroll bar on the right

### Expected behaviour

The cursor should remain where the user scrolls to.

### What's happening

The cursor moves to the bottom of the editor.

### Video of the problem

https://github.com/user-attachments/assets/97209a45-01f4-4eab-a393-801dd81066ed

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

Use the List View to navigate through blocks.

### Platform

Simple

### PR DESCRIPTION
**Pull request by ellatrix**
Fixes: https://github.com/Automattic/wp-calypso/issues/98447

## Problem:

React and most block editor packages are currently loaded in _both_ the main window _and_ the editor canvas iframe. This should not happen. (Note that you don't need any blocks inserted.)

image

Additionally there's an error message from one of the scripts that's added in the iframe:

image

## Proposed changes:

* The problem is that 4 blocks are currently enqueueing their editor scripts with `enqueue_block_assets` for some reason. This is wrong, since that hook is meant for assets to the block itself rather than assets to register the blocks. Instead, `enqueue_block_editor_assets` should be used.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* On a simple site, just visit the post editor and check the `<head>` of the canvas.
* Try adding a timeline block for example and check that it still works in the editor.

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php [hunk 1]
```diff
@@ -86,7 +86,7 @@ function () {
 	);
 
 	add_action(
-		is_admin() ? 'enqueue_block_assets' : 'enqueue_block_editor_assets',
```
Comment (youknowriad) [inline projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: I wonder what's the historic reason for this.

**Review by youknowriad — APPROVED** [review]
This makes sense.

File: projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php (hunk 1 above)
Comment (ellatrix) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: Yes, I asked in https://github.com/Automattic/jetpack/pull/38724 and https://github.com/Automattic/jetpack/pull/38298 🤔

Comment (ellatrix) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: Also no other blocks are doing this (otherwise this PR wouldn't entirely remove the packages enqueued).

Comment (arthur791004) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: Yes, I just migrated the code to this repo, and kept everything the same as before to avoid any regressions

**Review by arthur791004 — APPROVED** [review]
Thanks for addressing this 🙂

File: projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php (hunk 1 above)
Comment (arthur791004) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: Oops...my memory was wrong, and I just followed the comment below. It seemed something was wrong but I forgot the reason.

https://github.com/Automattic/jetpack/blob/50429029a891294dcec02a3d3e47a4ec4af3f88a/projects/plugins/jetpack/class.jetpack.php#L632-L641

Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: We need to enqueue it outside of the admin for sites that use the editor outside of WP-Admin. For example P2s (the comments box) uses it. The problem was that **only** enqueue_block_editor_assets was triggered for P2s, so we had to use this workaround.

Comment (p-jackson) [reply projects/packages/jetpack-mu-wpcom/src/features/newspack-blocks/index.php:89]: Is this going to cause a breakage on P2 @BogdanUngureanu? I just tried adding a timeline and event countdown block in a P2 comment and it worked fine.
