### PR TITLE
Fix sharing buttons and like buttons when copying a post

### LINKED ISSUE #14117: Copy Post: Sharing buttons don't appear if post is copied using block editor
#### Steps to reproduce the issue

1. Make sure the Copy Post module in Jetpack is activated, and that the Classic Editor plugin is not active.
2. At WP-Admin ->Posts, make sure you have a post with sharing and Like buttons enabled, and check the buttons are visible in the published post on the front end
3. Use the Copy Post feature to create a new post
4. Before publishing, check the Jetpack sidebar and make sure sharing and Like buttons are enabled
5. Publish the copied post

#### What I expected

For the sharing and Like buttons to appear below the post content same as on the original post

#### What happened instead
Only the Like button appears. The sharing buttons don't appear.

The only way to get the sharing buttons to appear is to edit the post again, disable sharing buttons and update, enable sharing buttons and update again.

This happens when copying posts using the block editor from both the post lists in WP-Admin and Calypso. If the Classic Editor plugin is installed and the classic editor set as default so it's used to publish the copied post, the sharing buttons appear as they're supposed to.

Reported in the forums at https://wordpress.org/support/topic/share-buttons-dont-show-with-copy-post/

### PR DESCRIPTION
**Pull request by scottsweb**
Looks like we are explicitly setting `sharing_disabled` and `switch_like_status` meta despite the original post relying on the global setting for these to show. It is creating some inconsistencies as per: https://github.com/Automattic/jetpack/issues/14117

Fixes #14117 

#### Changes proposed in this Pull Request:

* This PR attempts to better handle missing meta values on the post being copied

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Bug fix

#### Testing instructions:

From the issue:

* Make sure the Copy Post module in Jetpack is activated, and that the Classic Editor plugin is not active.
* At WP-Admin ->Posts, make sure you have a post with sharing and Like buttons enabled, and check the buttons are visible in the published post on the front end
* Use the Copy Post feature to create a new post
* Before publishing, check the Jetpack sidebar and make sure sharing and Like buttons are enabled
* Publish the copied post
* Verify if the sharing and like buttons respect those of the original post and are output on the front end

**Note: Even if wp-admin is showing the correct values for these toggles, we have been seeing different results in the theme on the front end, so check both places.**

Digging deeper. The meta data before the fix is applied:

Original post:

Screenshot 2020-01-02 at 16 41 57

Copied post:

Screenshot 2020-01-02 at 16 45 16

The meta data after the fix is applied:

Original post:

Screenshot 2020-01-02 at 17 03 41

Copied post:

Screenshot 2020-01-02 at 17 04 50

Ideally `switch_like_status` would not have been set at all in this scenario - but it does seem to work. I think we might need something better than the `isset` check.

#### Proposed changelog entry for your changes:

* Bug fix: Ensure correct sharing and like settings are copied when posts are duplicated

### CODE REVIEW

File: modules/copy-post.php [hunk 1]
```diff
@@ -200,10 +200,21 @@ public function remove_post_format_template( $settings ) {
...
 	 */
 	protected function update_likes_sharing( $source_post, $target_post_id ) {
-		$likes          = get_post_meta( $source_post->ID, 'switch_like_status', true );
-		$sharing        = get_post_meta( $source_post->ID, 'sharing_disabled', false );
-		$likes_result   = update_post_meta( $target_post_id, 'switch_like_status', $likes );
-		$sharing_result = update_post_meta( $target_post_id, 'sharing_disabled', $sharing );
+		$likes   = get_post_meta( $source_post->ID, 'switch_like_status', true );
+		$sharing = get_post_meta( $source_post->ID, 'sharing_disabled', false );
+
+		if ( isset( $likes ) ) {
```
Comment (kraftbj) [inline modules/copy-post.php]: I think `'' !== $test` would be better here. `get_post_meta` would return `''` if not present, and so `isset` is true for `$likes`. Reviewing the codebase, looks like `switch_like_status` should be either `0` or `1`, so need to be more exact. I wish we could use `empty` like the `sharing_disabled` option, but the `0` breaks that.

**Review by kraftbj — DISMISSED** [review]

File: modules/copy-post.php (hunk 1 above)
Comment (scottsweb) [reply modules/copy-post.php]: Updated the check but still have a couple of potential concerns, more in the comment below.

**Comment by scottsweb** [comment]
I just pushed a fix, thanks for your suggest @kraftbj - it looks to have worked. 

Before:

Screenshot 2020-01-03 at 09 35 49

After:

Screenshot 2020-01-03 at 09 36 23

So I think the original issue can me marked as resolved. 

I do however have a lingering concern, when the settings for sharing and likes are set to 'on' for all new posts and pages, I went into a specific post and turned them off. This gave me the following meta:

Screenshot 2020-01-03 at 09 39 53-bugs

It is a shame that `sharing_disabled` and `switch_like_meta` are the inverse of each other (both 0 an 1 meaning the option is turned off). It does work as expected though. 

When copying in this state though, the meta on the copied post is very different:

Screenshot 2020-01-03 at 09 39 38-bugs

`sharing_disabled` becomes a serialised value, which also seems like a possible bug. 

```
		$sharing = get_post_meta( $source_post->ID, 'sharing_disabled', false );
```

Should probably become:

```
		$sharing = get_post_meta( $source_post->ID, 'sharing_disabled', true );
```

and then we can perform the same check for sharing ` '' !== $sharing`

**Comment by jeherve** [comment]
> `sharing_disabled` becomes a serialised value, which also seems like a possible bug.

It does indeed seem like a bug, and I like your suggestion for a fix.

**Comment by scottsweb** [comment]
@jeherve fix has been pushed:

Original:

Screenshot 2020-01-08 at 16 17 50

Copy:

Screenshot 2020-01-08 at 16 18 28

Values stay as boolean.

**Review by jeherve — APPROVED** [review]
This seems to work well in my tests. Should be good to merge.

**Comment by scottsweb** [comment]
r201430-wpcom
