### PR TITLE
Sitemaps: Various improvements

### LINKED ISSUE #7992: Sitemaps: Updating Jetpack breaks sitemap
After updating Jetpack, visiting the 'sitemap.xml' URL gives the error "No sitemap found. Maybe it's being generated. Please try again later."

If you toggle the sitemap feature on and off it will start working again. 

Steps to reproduce: 

* Set up a site running JP 5.3
* Check sitemap (Screenshot of sitemap page from 5.3: http://cld.wthms.co/6yRXUz) 
* Update to 5.4
* Check Sitemap again (Screenshot: http://cld.wthms.co/ABj0ne)
* Go to Jetpack → Settings → Traffic and toggle on and off Sitemaps
* Check sitemap again, it works now. 

Originally reported in 732886-zen, I tested as well updating from 5.3 to 5.4 and experienced the same issue.

### PR DESCRIPTION
**Pull request by kraftbj**
After digging in to figure out the initial creation issue ( #10274 ), I made a pass at the other pending issues.
Fixes #7992 #8549 #9159 #9363

#### Changes proposed in this Pull Request:

* Updates a concatenated string to a single string.
* Checks if the home_url is a static page and if so, do not include it in the sitemap (as it would already be included when pages are added to the sitemap)
* Modifies the "no sitemap" error when visiting sitemap.xml for logged-in admins to display the next cron run time.
* When the sitemap data is reset following a Jetpack upgrade, schedule a new generation task one minute in the future. Before, it would wait until the next scheduled attempt, which could be up to 12 hours under default settings.

#### Testing instructions:

* Site with Sitemaps already active.
* Set the home page as a static page.
* Bump the version within JP (or set the Jetpack_Options value for `version` down so `plugin_upgrade` fires.
* Immediately check sitemap.xml. If it was within the first minute, see the new error message displayed for admins. Notice the time should be within a minute.
* After 1 minute, confirm the new sitemap is generated.
* Using a plugin like WPCrontrol, confirm the sitemap cron job is still on a regular `sitemap interval` schedule.
* Confirm the home page URL (set in step 2 above) only displays one.

#### Proposed changelog entry for your changes:
* Sitemaps: Ensure homepage is only included once.
* Sitemaps: Provide richer "not found" message to site admins.
* Sitemaps: Ensure sitemap is refreshed faster after upgrading Jetpack.

### CODE REVIEW

File: modules/sitemaps/sitemaps.php [hunk 1]
```diff
@@ -451,10 +458,12 @@ public function callback_action_flush_news_sitemap_cache() {
 	 *
 	 * @access public
 	 * @since 5.3.0
+	 * @since 6.7.0 Schedules a regeneration after 60 seconds.
 	 */
 	public function callback_action_purge_data() {
 		$this->callback_action_flush_news_sitemap_cache();
 		$this->librarian->delete_all_stored_sitemap_data();
+		wp_schedule_single_event( time() + 60, 'jp_sitemap_cron_hook' );
```
Comment (simison) [inline modules/sitemaps/sitemaps.php]: Should we randomly spread this across 5mins or so to avoid heavy server load in situations where Jetpack is upgraded for multiple sites on same server?

Comment (kraftbj) [reply modules/sitemaps/sitemaps.php]: You're absolutely right. I'll update that in my morning.

Comment (gravityrail) [reply modules/sitemaps/sitemaps.php]: Can we make the random distribution configurable? I'm sure that some hosts that upgrade Jetpack centrally would appreciate being able to spread the load over, say, an hour.

Comment (kraftbj) [reply modules/sitemaps/sitemaps.php]: How about like this? https://github.com/Automattic/jetpack/pull/10274/commits/44f86066e2d7787cce364480fd042fecfa2cea0b

(I'll introduce the same thing here too)

**Comment by kraftbj** [comment]
Waiting on WP.com since I'd want to rebase this PR for Fusion's sake and rerun it after #10274 lands.

**Comment by kraftbj** [comment]
Ready for this to be reviewed and merged whenever makes sense. There are PHPCS issues to address, but I'll roll those into a separate PR to merge into this one to make the review easier.

**Comment by kraftbj** [comment]
#10291 can be merged into this PR once we have this one reviewed.

File: modules/sitemaps/sitemaps.php [hunk 2]
```diff
@@ -149,8 +149,15 @@ private function serve_raw_and_die( $the_content_type, $the_content ) {
 		set_query_var( 'feed', 'sitemap' );
 
 		if ( '' === $the_content ) {
+			$error = __( 'No sitemap found. Please try again later.', 'jetpack' );
+			if ( current_user_can( 'manage_options' ) ) {
+				$next = date_i18n( 'F j, Y g:i a', wp_next_scheduled( 'jp_sitemap_cron_hook' ) );
```
Comment (jeherve) [inline modules/sitemaps/sitemaps.php]: This date format does not seem ideal.

screenshot 2018-10-11 at 14 53 41

What if we used something like "in x hours" instead, with `human_time_diff` for example?

File: modules/sitemaps/sitemaps.php [hunk 3]
```diff
@@ -149,8 +149,15 @@ private function serve_raw_and_die( $the_content_type, $the_content ) {
 		set_query_var( 'feed', 'sitemap' );
 
 		if ( '' === $the_content ) {
+			$error = __( 'No sitemap found. Please try again later.', 'jetpack' );
```
[the remark this answers is not in the document]
Comment (kraftbj) [reply modules/sitemaps/sitemaps.php]: I separated it out since we want to escape late. The line is still escaped before output.

File: modules/sitemaps/sitemaps.php (hunk 2 above)
Comment (kraftbj) [reply modules/sitemaps/sitemaps.php]: Great idea. 5b02925faa45fa4c24eb99aaf2d459b82cb0ad26

**Comment by kraftbj** [comment]
2018-10-11 at 12 16

**Comment by kraftbj** [comment]
Synced with wp.com via r181829-wpcom.
