### PR TITLE
Fix/fontfamily attribute

### LINKED ISSUE #38311: Google Fonts: formating the fontFamily block attribute fails if it's not a string
### Impacted plugin

Jetpack

### Quick summary

Any block can add the attribute `fontFamily` as something other than a string. 
However, `format_font()` method assumes the attribute is a string https://github.com/Automattic/jetpack/blame/trunk/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php#L149

This can cause issues when trying to render a block which can in turn prevent updating a post.

This was found while trying to solve an issue where a widget contained a block that used `fontFamily` object attribute. 
The specific block attribute can be seen here https://plugins.trac.wordpress.org/browser/easy-quotes/trunk/build/block.json#L93

Trying to remove that block from a widget results in the error 
``` PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /wordpress/plugins/jetpack/13.7-a.1/modules/google-fonts/current/class-jetpack-google-font-face.php:149 ```

### Steps to reproduce

Steps
1. Install a plugin that has adds a block which defines a `fontFamily` that is not a string ( https://wordpress.org/plugins/easy-quotes/ for example )
2. Add the block to a page of a WordPress.com site 
3. Try saving the page

### A clear and concise description of what you expected to happen.

The page should be saved

### What actually happened

The API returns an error and the post is not saved.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Probably just need to do a string check here https://github.com/Automattic/jetpack/blame/trunk/projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php#L124

### PR DESCRIPTION
**Pull request by jhnstn**
Fixes #38311

## Proposed changes:

* Check if the block attribute `fontFamily` is a string before setting the font family.

### Other information:
This change allows other blocks to use a different data type as a `fontFamily`. 

- [x] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Install a block that uses a `fontFamily` attribute that is not a string. see https://wordpress.org/plugins/easy-quotes/ as an example
* Add the block to a post
* Note that the post cannot be saved.

### CODE REVIEW

File: projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php [hunk 1]
```diff
@@ -122,7 +122,9 @@ public function collect_global_styles_fonts() {
 	public function collect_block_fonts( $content, $parsed_block ) {
 		if ( ! is_admin() && isset( $parsed_block['attrs']['fontFamily'] ) ) {
 			$block_font_family = $parsed_block['attrs']['fontFamily'];
-			$this->add_font( $block_font_family );
+			if ( is_string( $block_font_family ) ) {
+				$this->add_font( $block_font_family );
```
Comment (arthur791004) [inline projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php]: How about checking the value inside the `add_font` function? I think it's safer

**Review by arthur791004 — DISMISSED** [review]
Nice job! Thanks for fixing the issue 👍

File: projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php (hunk 1 above)
Comment (fushar) [reply projects/plugins/jetpack/modules/google-fonts/current/class-jetpack-google-font-face.php]: Done!

**Review by arthur791004 — APPROVED** [review]
