### PR TITLE
Nav Unification: Store the correct preferred view when it is selected.

### LINKED ISSUE #49486: Clicking All Posts goes to WP-Admin posts instead of Calypso posts page
### Steps to reproduce the behavior

1. On Atomic site, start writing a new post
2. Click the "W" on the top 
3. Click "< All Posts"
4. You're taken to Wp-admin posts page, not the calypso posts page

#### What I expected to happen
I expected to see Calypso posts page

#### What actually happened
I saw the wp-admin posts page

### Context
I was doing testing 

#### Browser / OS version
Chrome 88 MacOS

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
Simple

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
minor

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See Video on my comment on pciE2j-bv-p2 (to be posted)
Screen Shot 2021-01-29 at 1 20 17 PM

### PR DESCRIPTION
**Pull request by vykes-mac**
Fixes https://github.com/Automattic/wp-calypso/issues/49486

#### Changes proposed in this Pull Request:
 
* This PR prevents preferred views for the same page being stored twice, without the query params and with the query params. This caused navigation from post to go to classic view when the user is expecting the new default/calypso view.
This is accomplished by removing the query args before saving the view. 

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

* Repro the issue: 
          1. Go to post and change view to classic view
          2. View post in the editor then use the W > View all posts to navigate back
          3. Change the view to default view then open the post editor
          4. Again navigate back, notice it's now showing the classic view when it should be showing the default view.

* Sandbox the generated diff D84120-code
* Perform the steps above and verify the correct view is being displayed.

For regression see here to test other screens 715-gh-Automattic/wpcomsh

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 1]
```diff
@@ -614,6 +614,7 @@ public function dashboard_switcher_scripts() {
 	 */
 	public function set_preferred_view( $screen, $view ) {
 		$preferred_views            = $this->get_preferred_views();
+		$screen                     = remove_query_arg( array( 'post_type', 'page', 'taxonomy' ), $screen );
```
Comment (danielbachhuber) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: Because the scope of the problem seems limited to `?post_type=post`, I think we should only remove `?post_type=post` from the URL when present (see [extended review note](https://github.com/Automattic/jetpack/pull/25074#pullrequestreview-1036586226)). I don't even think we need to do any argument parsing:

```php
$screen = str_replace( '?post_type=post', '', $screen );
```

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
Because I was curious how this worked, I did some debugging to explore further.

## Posts

On a Simple site without the patch, when you switch from Default view to Classic view, here's what's saved:

```
[12-Jul-2022 22:32:57 UTC] array (
  'edit.php' => 'classic',
)
```

image

Then, when you edit a post and then navigate back with `W > View all posts`, the `?post_type=post` query param ends up in the URL:

image

Thus, what's saved when you switch back to Default view is:

```
[12-Jul-2022 22:37:29 UTC] array (
  'edit.php' => 'classic',
  'edit.php?post_type=post' => 'default',
)
```

The patch rectifies this problem by removing `?post_type=post` from `$screen`, and storing the key in a manner that matches how the menu is identified.

## Tags

I was curious about the impact of removing `?taxonomy=post_tag` from `$screen` too.

Without the patch applied, I can navigate to 'Tags', switch to 'Classic view', navigate to 'Media', and return to Tags 'Classic view' when I navigate back:

https://user-images.githubusercontent.com/36432/178612256-bfb93acf-c030-4e05-bc7e-5af3e8b4f14c.mp4

(Note: you do have to wait a moment for `wpcom/v2/admin-menu` to return the site's menu links)

With the patch applied however, the buggy behavior in https://github.com/Automattic/wp-calypso/issues/49486 happens to taxonomy pages:

https://user-images.githubusercontent.com/36432/178613733-379318bb-e1a0-441e-be7d-ad6161df049b.mp4

Before the patch, here's what's stored:

```
[12-Jul-2022 22:55:49 UTC] array (
  'edit-tags.php?taxonomy=post_tag' => 'classic',
)
```

After the patch, it becomes:

```
[12-Jul-2022 23:04:04 UTC] array (
  'edit-tags.php' => 'classic',
)
```

There are additional views you could test with in https://github.com/Automattic/jetpack/pull/20228

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 1 above)
Comment (vykes-mac) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: Thank you for the detail test. I know there are a bunch of other screens involve but we seem to only be adding query params for `post_type, taxonomy and page`

Comment (vykes-mac) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:617]: The issue also happens with pages

Comment (vykes-mac) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: > Because the scope of the problem seems limited to `?post_type=post`, I think we should only remove `?post_type=post` from the URL when present (see extended review note)

👍

Comment (danielbachhuber) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: @vykes-mac Sorry, I should've been more clear 😦 

With 1852efc160188bfe01062694ebc51c4af88ecf95, the `post_type=page` is _incorrectly_ removed from `edit.php?post_type=page`, which means the bug is introduced in the "All Pages" context:

1. Navigate to "All Pages".
2. Switch to the "Classic view"

image

3. Observe the "Classic view" load as expected:

image

4. Navigate to "Media".
5. After waiting a moment for the nav menu to fully load, hover over "Pages" to observe "Default view" to unexpectedly appear as the URL:

image

The expected URL is `/wp-admin/edit.php?post_type=page`.

What's happening under the hood is that the previewed view is saved to the `edit.php` key, which corresponds to Posts:

```
array (
  'edit.php' => 'classic',
)
```

For Pages, the preferred view needs to be stored to `edit.php?post_type=page`.

As such, I _think_ I'd recommend a simple:

```
$screen = str_replace( '?post_type=post', '', $screen );
```

`post_type=post` is the special edge case we need to accommodate.

Comment (vykes-mac) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: Ah I see, I was under the impression that setting pages to classic view would also maintain classic view for posts. It feels a little bit weird that one section of the app is classic view and another section is default view, I think that experience can be jarring but that's current implementation.

**Review by danielbachhuber — APPROVED** [review]
👍 Works great in my testing!

**Review by coder-karen — APPROVED** [review]

**Comment by coder-karen** [comment]
r249153-wpcom
