### PR TITLE
Tonesque: Use `imagecreatefromstring()` rather than attempting to detect file type manually

### LINKED ISSUE #3741: Tonesque: Avoid detecting filetype by filename
While using Tonesque on WordPress.org, I'm seeing a lot of PHP warnings which are caused by files which claim to be one filetype, but are actually another - for example, `banner.jpg` which is actually a `png`.

PHP offers an alternative function which can auto-detect gif/png/jpg/bmp & gd2 files, however it only accepts a string (rather than `imagecreatefromjpg()` and friends which accept a filename/filewrapper).

#### What I expected
 - Tonesque to operate on the valid Image content provided

#### What happened instead
 - Tonesque produced warnings and failed to return the expected result
 - `Warning: imagecreatefromjpeg(): '../banner-1544x500.jpg' is not a valid JPEG file`

#### Steps to reproduce the issue
 - Upload a `png` image as a `jpeg` filename and attempt to run Tonesque on it.

### PR DESCRIPTION
**Pull request by dd32**
Fixes #3741.

#### Changes proposed in this Pull Request:
- Uses `imagecreatefromstring()` rather than calling individual PHP functions directly, allowing PHP to do the detection using the file contents (and each image types bytemark) instead of based on the filename.

### CODE REVIEW

File: _inc/lib/tonesque.php [hunk 1]
```diff
@@ -37,27 +37,7 @@ function __construct( $image_url ) {
...
-			case 'jpg' :
-			case 'jpeg' :
-				$image_obj = imagecreatefromjpeg( $image_url );
-				break;
-			default:
-				return false;
-		}
-
-		return $image_obj;
+		return imagecreatefromstring( file_get_contents( $image_url ) );
```
Comment (jeherve) [inline _inc/lib/tonesque.php]: Would it make sense to use `wp_remote_get()` instead of `file_get_contents()`?

Comment (dd32) [inline _inc/lib/tonesque.php]: I didn't want to introduce an external dependency into the library, and using `file_get_contents()` was exactly what PHP was internally doing anyway.
Right now someone could be using Tonesque + `Jetpack_Color` stand-alone without issue, as far as I could see.

We could use `wp_remote_get()` if the `$image_url` is prefixed by `http://` or `https://` however would need to use `file_get_contents()` for all other protocols and image paths anyway (ie. `/home/.../image.jpg` or `custom-file-wrapper://path/image.jpg`)

Comment (dd32) [inline _inc/lib/tonesque.php]: Something I've since noticed in testing
 * Warnings will be thrown by `file_get_contents()` when the request fails
 * Warnings will be thrown by `imagecreatefromstring()` when the input is empty (`Empty string or invalid image`), or a non-image data (`Data is not in a recognized format `)

Should be noted though, that the functions being replaced would also throw PHP warnings when invalid URLs or images were passed, so nothing has changed there.

**Comment by jeherve** [comment]
This seems to work well in my tests. 🚢
