### PR TITLE
Fix missing search overlay in some themes like Rebalance

### LINKED ISSUE #7440: Rebalance: Jetpack Search results modal doesn't load
### Quick summary

I was able to reproduce the user's issue with their theme, Rebalance, the Jetpack Search results modal doesn't load with it.  It worked fine when I tried Twenty Twenty Three.

I'm not sure if it's for the Theme team to handle, please transfer to https://github.com/Automattic/wp-calypso/ as needed. Sorry!

### Steps to reproduce

1. Create a Simple site
2. Select the theme Rebalance
3. Go to Jetpack > Search, then get the Free license
4. Still under Jetpack > Search, check that `Enable Jetpack Search` is enabled
5. Add a Search block anywhere
6. Test Search on the live site

### What you expected to happen

Search results modal should display.

### What actually happened

- Entirely blank page displays.
- It order for the results modal to show, I need to manually reload the page, or load the search URL directly (for example: `https://url-example.wordpress.com/?s=love`)

### Browser

_No response_

### Context

Customer report: 7181532-zd-a8c

### Platform (Simple, Atomic, or both?)

Only tested Simple.

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

User another theme.  I tested with Twenty Twenty Three, and Jetpack Search worked fine.

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/themes/issues/7440

## Proposed changes:

Themes like Rebalance play with body opacity, e.g., they set it initially to 0 and use JS to set it to 1 when it's ready. It prevents the Jetpack instant search dialog from being displayed.

I propose to fix the body opacity if it's incorrect when the instant search dialog is updated.

### Other information:

This is the CSS code used in the mentioned theme:

```
/* Fade in page after js loads */
.js body {
	opacity: 0;
}
```

And JS code:

```
/*
 * Fade in page
 * - only if js is enabled
 */
$wrapper.animate({
	opacity: 1,
}, 30);
```

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

None

## Does this pull request change what data or activity we track or use?

No

### WoA

1. Create a WoA site
2. Install the Jetpack Beta plugin
3. Using the Jetpack Beta plugin management UI, enable this branch for the Jetpack plugin
4. Switch to Rebalance theme
5. Enable Jetpack Search
6. Open the page in frontend
7. Enter any text in the search field and press Enter
8. Confirm that the overlay is displayed

### Simple site

1. To test on Simple, run the following command on your sandbox:
```
bin/jetpack-downloader test jetpack fix/missing-search-overlay-in-some-themes
```
2. Create a Simple site
3. Follow steps 4-8 from the previous section

### CODE REVIEW

File: projects/packages/search/src/instant-search/components/dom-event-handler.jsx [hunk 1]
```diff
@@ -190,6 +191,14 @@ export default class DomEventHandler extends Component {
 		}
 	};
 
+	fixBodyOpacity = () => {
+		if ( '1' !== document.body.style.opacity ) {
```
Comment (okmttdhr) [inline projects/packages/search/src/instant-search/components/dom-event-handler.jsx:195]: badge

Would it be possible to change this to the following?

```suggestion
		if ( '0' === document.body.style.opacity ) {
```

I am a bit concerned that this executes unnecessarily, such as when `document.body.style.opacity` is unset.

**Review by okmttdhr — DISMISSED** [review]
✅

File: projects/packages/search/src/instant-search/components/dom-event-handler.jsx (hunk 1 above)
Comment (wojtekn) [reply projects/packages/search/src/instant-search/components/dom-event-handler.jsx:195]: Changed https://github.com/Automattic/jetpack/pull/40472/commits/b923e01376b90b0c764984b6f21027d6c3c8badd

**Review by okmttdhr — DISMISSED** [review]

**Review by tbradsha — DISMISSED** [review]
Works for me!

File: projects/packages/search/src/instant-search/components/dom-event-handler.jsx [hunk 2]
```diff
@@ -190,6 +191,14 @@ export default class DomEventHandler extends Component {
 		}
 	};
 
+	fixBodyOpacity = () => {
+		if ( '0' === document.body.style.opacity ) {
```
Comment (tbradsha) [inline projects/packages/search/src/instant-search/components/dom-event-handler.jsx]: I'll note that if the body opacity is set to `0` by CSS alone (as per the PR description), `document.body.style.opacity` will be empty, and this won't trigger, so I suspect there's some JS or inline CSS in the theme that's setting the opacity as well.

It might be worth always setting the opacity to `1`, or at least doing so if the string is empty.

**Comment by kraftbj** [comment]
Marked both needs author reply and ready to merge since it has been approved for merge, but with a comment for the author. Good to merge :)

File: projects/packages/search/src/instant-search/components/dom-event-handler.jsx (hunk 2 above)
Comment (wojtekn) [reply projects/packages/search/src/instant-search/components/dom-event-handler.jsx]: Thanks, I've changed it back to the initial implementation.
