### PR TITLE
Mailchimp: Hide Block If No Connection

### LINKED ISSUE #11290: Mailchimp block: View form is rendered when connection is broken
#### Steps to reproduce the issue

1. Follow the steps to produce a new mailchimp block
2. Add the block
3. View it on the frontend
4. Disconnect MailChimp from your account
5. The editor will show a placeholder, but the block is still rendered view-side.

#### What I expected
Remove the block and/or show some error messaging.

#### What happened instead

The block is still rendered.

cc: @artpi / @jeffersonrabb

### PR DESCRIPTION
**Pull request by jeffersonrabb**
This PR will not render the Mailchimp block if the site doesn't have a Mailchimp connection and list selected. 

Fixes https://github.com/Automattic/jetpack/issues/11290

#### Testing instructions:

- https://jurassic.ninja/create/?gutenpack&calypsobranch=master&branch=fix/mailchimp-hide-block-if-no-connection
- Connect Jetpack
- In `Settings->Jetpack Constants` enable `JETPACK_BETA_BLOCKS`
- Add Mailchimp block to a post
- Click through to WP.com Sharing page, link to Mailchimp account and select list
- Publish the post and view the published page. Mailchimp block should be visible.
- In WP.com sharing page, set list to `Do not save...`
- Refresh published page. Block should be hidden.
- In WP.com sharing page, choose a list again. Refresh published page and see Block visible again.
- In Wp.com sharing page, Disconnect Mailchimp.
- Refresh published page. Block should again be hidden.

### CODE REVIEW

**Review by artpi — APPROVED** [review]
Works nicely!

**Comment by jeherve** [comment]
I get the following error when trying to add the block to a brand new site, for some reason:

image

File: extensions/blocks/mailchimp/mailchimp.php [hunk 1]
```diff
@@ -86,3 +89,20 @@ function jetpack_mailchimp_block_load_assets( $attr ) {
...
 	return $html;
 }
+
+/**
+ * Mailchimp connection/list selection verification.
+ *
+ * @return boolean
+ */
+function jetpack_mailchimp_verify_connection() {
+	$option = get_option( 'jetpack_mailchimp' );
```
Comment (sirreal) [inline extensions/blocks/mailchimp/mailchimp.php]: Should we use the `Jetpack_Options` class here?

```suggestion
	$option = Jetpack_Options::get_option( 'mailchimp' );
```

File: extensions/blocks/mailchimp/mailchimp.php [hunk 2]
```diff
@@ -24,6 +24,9 @@
  * @return string
  */
 function jetpack_mailchimp_block_load_assets( $attr ) {
+	if ( ! jetpack_mailchimp_verify_connection() ) {
+		return null;
```
Comment (sirreal) [inline extensions/blocks/mailchimp/mailchimp.php]: If we wanted to get fancy, we could render a notice for some set of site users.

**Review by sirreal — APPROVED** [review]
Works well, thanks! I like not rendering a broken block 🙂 

I left a suggestion for consistency and an enhancement idea, neither are blockers.

**Review by jeherve — APPROVED** [review]
This works nicely on my end. 👍
