### PR TITLE
Admin Page: Make the Module Settings save button be disabled while saving options

### LINKED ISSUE #4430: Notices: Admin Page - Feature Settings - After I click the "Save" button and the saving ends nothing shows that saving succeeded
#### Steps to reproduce the issue

1. Get to the Admin Page, and under the **Engagement** tab,  update one of the **Subscription** module settings (checkboxes).
2. Press **Save**.
3. See how you don't get any feedback about the settings being successfully saved

#### What I expected

Some feedback, maybe the **Save** button turning disabled again (as @eliorivero [proposed here](https://github.com/Automattic/jetpack/pull/4411#issuecomment-233369079)).

#### What happened instead

Only the checkboxes get disabled while the saving is being done, but they switch to their prior enabled state when it's done.

### PR DESCRIPTION
**Pull request by oskosk**
Fixes #4430  .

#### Changes proposed in this Pull Request:

- Makes the save button on feature settings forms disable when saving and re-enable when the API requests ends.
- Makes the save button read "Saving..." while the options are being saved.
- Moves every save button to be inside a `<FormFieldSet />` for appropriate positioning.
- Changes the save buttons to have the `.is-primary` class applied

#### Before

beforesavebutton

#### After

savebutton

#### Testing instructions:
- Get to the **Stats** settings under the **Engagement** module
- Update one of the options for the Roles Permissions
- Save the change
- Watch the save button be disabled when the change is still being saved. It's label switched to "Saving..."
- Watch the save button remain disabled when the option has been saved. It's label switched to "Save settings".
- Watch the save button be re-enabled if you alter one of the options again

### CODE REVIEW

**Comment by oskosk** [comment]
cc @eliorivero as you mentioned the previous behaviour.
cc @MichaelArestad . This also solves a few positinioning ( which you may have seen ) because some buttons were outside fieldsets.

File: _inc/client/components/module-settings/module-settings-form.jsx [hunk 1]
```diff
@@ -48,25 +48,43 @@ export function ModuleSettingsForm( InnerComponent ) {
...
+			shouldItBeEnabled = ! this.isSavingAnyOption() && this.isDirty();
+			return ! shouldItBeEnabled;
+		},
 		isDirty() {
 			return !! Object.keys( this.state.options ).length;
 		},
+		isSavingAnyOption() {
+			let isSaving = false;
+			// Check if any of the updated options is still saving
+			Object.keys( this.state.options ).forEach( option_name => {
```
Comment (eliorivero) [inline _inc/client/components/module-settings/module-settings-form.jsx]: @oskosk maybe this can be replaced with
```js
isSaving = Object.keys( this.state.options ).some( option_name => this.props.isUpdating( option_name ) );
```
It has better performance since it will return as soon as the condition is true and won't go through the other options. I've tested this in this branch and seems to work fine.

**Comment by oskosk** [comment]
you're right thanks

File: _inc/client/components/module-settings/module-settings-form.jsx (hunk 1 above)
Comment (eliorivero) [inline _inc/client/components/module-settings/module-settings-form.jsx]: @oskosk actually the entire method can simply be
```js
isSavingAnyOption() {
	// Check if any of the updated options is still saving
	return Object.keys( this.state.options ).some( option_name => this.props.isUpdating( option_name ) );
},
```

Comment (oskosk) [inline _inc/client/components/module-settings/module-settings-form.jsx]: yeah probably. I'll update it in a few mins, thanks!

**Comment by oskosk** [comment]
@eliorivero I've just updated the code to introduce your recommendation, thx!

**Comment by eliorivero** [comment]
LGTM! 🐑 it
