### PR TITLE
Boost: Various ISA UI tweaks

### LINKED ISSUE #31772: Boost: ISA - main groups UI is broken on smaller screens
The settings page isn't responsive, unfortunately. On my phone the green status images are all cluttered together.

p1688983236272389/1688978711.793359-slack-C0232B8CUHG

Screenshot_20230710_105807_Firefox

_Originally posted by @donnchawp in https://github.com/Automattic/jetpack/issues/31771#issuecomment-1628636689_

### PR DESCRIPTION
**Pull request by dilirity**
Fixes #31772 and #31773.

## Proposed changes:

* Update groups UI, to look better on smaller screens (#31772);
  * <details>
     <summary>screenshot</summary>
      CleanShot 2023-07-10 at 18 26 31@2x

      </details>
   * <details>
     <summary>max-width: 600px</summary>
     CleanShot 2023-07-10 at 18 18 16@2x

      </details>

* Fix discrepancies between UI and designs (#31773):
  * "has issues" label now has an icon and is colored red;
  * The arrow in front of "Analyze again" is now green;
  * There is now an info box next to "Other", that shows a tooltip when hovered over. **Note, that the list of post types is hard-coded. We should either add an endpoint that returns the custom post types analyzed in a report, or remove this for now**;
  * The "No issues" label has been updated to use a gray color, that matches the original design.
  * <details>
     <summary>screenshot before</summary>
     image
     </details>
  * <details>
     <summary>screenshot after</summary>
     image
     </details>

* Additional tweaks include:
  * Removed underline from page name on "latest report page" listing;
  * spacing adjustments in header of "latest report page";
  * Updated 'Beta' pill colors to be green instead of gray (visible on first screenshot).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Setup Boost with Image Size Analysis;
* Go over list of changes and make sure everything looks okay.

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/elements/OtherGroupContext.svelte [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+		<p>
+			{__(
+				'In addition to the Homepage, Pages and Posts, Boost will also analyze the following custom post types found on your site:',
+				'jetpack-boost'
+			)}
+		</p>
+		<ul>
+			<li>Testimonials</li>
+			<li>Portfolio</li>
+			<li>Projects</li>
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/elements/OtherGroupContext.svelte:17]: This list should show the kinds of "other" content on the site. However, I will merge this PR as it's a _huge_ improvement - and we can make it show the real post types in a follow-up PR.

https://github.com/Automattic/boost-cloud/issues/296

**Review by thingalon — APPROVED** [review]
❤️ Nice work, Peter; this is a huge improvement.

I've noted that the hard-coded list of Post Types is likely to be wrong on many sites. I've created a separate Issue to fix that in a follow-up PR; the changes in this PR are otherwise great and a huge improvement.
