### PR TITLE
Fix/inacurate pro dashboard card buttons

### LINKED ISSUE #4540: Admin: AAG dashboard action inconsistencies with plan type
**Akismet**

While testing https://github.com/Automattic/jetpack/pull/4500 I discovered that if I have a pro plan and I uninstall akismet, I'm prompted to upgrade via the anti-spam card on the AAG dashboard. 

screen shot 2016-07-25 at 2 34 29 pm

This should say "install" instead of "upgrade" since the plan is already purchased. 

**VaultPress:**

Secondly, if I have the pro plan and _delete_ VP, on the dashboard the VP cards prompt me to "activate" backups and security scan, rather than "install"

screen shot 2016-07-25 at 5 08 34 pm

(possibly issue for premium plan too)

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #4540

This fixes the remaining inconsistencies in the DashItem CTA buttons for the pro cards (akismet/vaultpress). 

Changes made: 
- More accurate links (now points directly to the Calypso plugin page _for your site_)
- New DashItem status `no-pro-inactive-or-uninstalled`, which will show `upgrade` button with link to plans.  
- Now correctly identifying whether pro plugins are installed or just inactive. 

To test: 
- Have an active plan for the site
- Uninstall VaultPress & Akismet.  You should see the button as `Install`, and it should link directly to the plugin for your site with the ability to install.  
- Deactivate VaultPress & Akismet (but leave it installed).  The button should read `activate`, and it should take you to the same calypso plugin page for your site.  
- On a site with no plan, the buttons should read `upgrade` if the plugins are either uninstalled or inactive.

### CODE REVIEW

File: _inc/client/at-a-glance/scan.jsx [hunk 1]
```diff
@@ -16,6 +16,8 @@ import {
 	isFetchingModulesList as _isFetchingModulesList
 } from 'state/modules';
 import { getSitePlan } from 'state/site';
+import { SecurityModulesSettings } from 'components/module-settings/modules-per-tab-page';
```
Comment (oskosk) [inline _inc/client/at-a-glance/scan.jsx]: Looks like `SecurityModulesSettings` is not used anywhere

File: _inc/client/components/dash-item/index.jsx [hunk 2]
```diff
@@ -57,11 +63,20 @@ const DashItem = React.createClass( {
...
+					compact={ true }
+					primary={ true }
+					href={ 'https://wordpress.com/plugins/' + this.props.module + '/' + window.Initial_State.rawUrl }
+				>
+					{ __( 'Install' ) }
+				</Button>;
+				break;
 			case 'pro-inactive':
 				status = <Button
 					compact={ true }
```
Comment (oskosk) [inline _inc/client/components/dash-item/index.jsx]: props for `<Button>` seem one level out of indentation.

**Comment by oskosk** [comment]
works as expected. Left a few comments in the code. Otherwise LGTM. After tackling this observation, I'd say is good to 🚢

File: _inc/client/components/dash-item/index.jsx (hunk 2 above)
Comment (dereksmart) [inline _inc/client/components/dash-item/index.jsx]: They are all aligned the same as of now.  Do you think they should be moved one way or another?

File: _inc/client/at-a-glance/akismet.jsx [hunk 3]
```diff
@@ -28,9 +29,10 @@ const DashAkismet = React.createClass( {
 	},
 
 	getContent: function() {
-		const akismetData = this.props.getAkismetData();
-		const akismetSettingsUrl = window.Initial_State.adminUrl + 'admin.php?page=akismet-key-config';
-		const labelName = __( 'Anti-spam', { args: { akismet: '(Akismet)' } } );
+		const akismetData = this.props.getAkismetData(),
+			akismetSettingsUrl = window.Initial_State.adminUrl + 'admin.php?page=akismet-key-config',
+			labelName = __( 'Anti-spam', { args: { akismet: '(Akismet)' } }),
```
Comment (eliorivero) [inline _inc/client/at-a-glance/akismet.jsx]: Maybe this could be just `__( 'Anti-spam' )`?

**Comment by eliorivero** [comment]
Is it ok that these display Upgrade in Dev Mode? The link goes nowhere.

devmode-vp-ak

File: _inc/client/at-a-glance/akismet.jsx (hunk 3 above)
Comment (dereksmart) [inline _inc/client/at-a-glance/akismet.jsx]: Good catch

**Comment by dereksmart** [comment]
@eliorivero good point, we should hide the button if in dev mode.

**Comment by dereksmart** [comment]
@eliorivero updated with both of your suggestions.

**Comment by eliorivero** [comment]
LGTM! 🐑
