### PR TITLE
Fix Paypal block when duplicating

### LINKED ISSUE #12801: Simple Payments / Pay with PayPal : Duplicated payment blocks affect original block on save
When duplicating a Simple Payments block on a page, editing the duplicated block changes the data of the first block when you make changes and save.

#### Steps to reproduce
1. On a test site (tested on Simple and AT) add a Simple Payments block, add content
2. Duplicate the Block, change information in the block (title, price, etc)
3. Save changes to the page and refresh the page (in editor or front end)

#### What I expected

Both blocks should have different content.

#### What happened instead

The original block updates with the changes you made to the second product block.

#### Browser / OS version

Don't think this is browser related.

#### Screenshots

before
after

Video: https://cld.wthms.co/I5GBRA

#### Context / Source

Noticed this when debugging an issue on a site where a customer duplicated pages which had Simple Payment blocks to quickly create additional product pages.

13544091-hc

### PR DESCRIPTION
**Pull request by millerf**
Fixes #12801

## Proposed changes:

* Remove the Product Id linked to the block when copying

### Other information:

I am not sure whether this is the best approach. Also copying a page should be tested. It probably won't fix it there.

## Testing instructions:

* Spin up a new JN instance or use this branch on WPCOM 
* Create a page with one paypal block (pay with paypal) instance. Save it.
* Duplicate the block and change the price / title or description and save the page
* Open the page, or reload the editor, the 2 blocks should be distinct

* Duplicate the whole page from the admin 
* Edit the new page and modify the blocks, save
* Make sure the blocks from the original page were not modified

### CODE REVIEW

**Comment by n3f** [comment]
I spent more than an hour fiddling with this but didn't make any progress:

* I tried the `from` transform instead of the `to` with similar code.
* I found the code I was looking for in the [pastehandler](https://github.com/WordPress/gutenberg/blob/trunk/packages/blocks/src/api/raw-handling/paste-handler.js#L79), but I couldn't figure out how to hook into it. _It looks like it calls the transforms, so maybe we're missing something simple._
* I think @ellatrix might be the best resource to ask if it's even possible.

```jsx
from: [
	{
		type: 'block',
		blocks: [ 'jetpack/simple-payments' ],
		transform: attributes => {
			// Create a new attributes object without the productId
			const { productId, ...newAttributes } = attributes;
			return createBlock( 'jetpack/simple-payments', newAttributes );
		},
	},
],
```

**Comment by ellatrix** [comment]
I'm not sure if it's possible. When pasting blocks, the blocks are not transformed from raw content because they're already blocks. And when copying, I don't think there's any filter that runs. There's some blocks that deal with stuff like this with a mount effect, but that's a really dirty way of dealing with it. Ideally there should be some kind of filter that runs every time a block is created?

**Comment by millerf** [comment]
Thanks @n3f and @ellatrix,

I think we will have to take another approach here. We need to lean int this and think it as a "feature" :)
Ultimately, we can also make the product object immutable and create a new object at each change. That should amke it behave as expected pretty seamlessly.

**Comment by millerf** [comment]
Trying to get around some issue when testing JP on sandbox: p1741184360480319-slack-CDLH4C1UZ

File: projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ export const SimplePaymentsEdit = ( {
 		setIsSavingProduct( true );
 
 		saveEntityRecord( 'postType', SIMPLE_PAYMENTS_PRODUCT_POST_TYPE, {
-			id: productId,
+			id: null, // This insures that a new product is created every time a change is made
```
Comment (n3f) [inline projects/plugins/jetpack/extensions/blocks/simple-payments/edit.js:112]: nice.

**Review by n3f — APPROVED** [review]
Works for me:

image

image
