### PR TITLE
Business Hours: fix time formatting in preview mode

### LINKED ISSUE #36647: Business Hours: in the editor previewed hours are incorrect
### Impacted plugin

Jetpack

### Quick summary

In the editor, the Business Hours block shows different hours in preview and edit mode.

_Edit mode_
Screenshot 2024-03-28 at 1 38 52 PM

_Preview mode_
Screenshot 2024-03-28 at 1 38 57 PM

### Steps to reproduce

- Choose a self-hosted test site connected to Jetpack
- Create a new post or page
- Add the _Business Hours_ block
- Notice the difference in preview and edit mode

### A clear and concise description of what you expected to happen.

In preview mode, hours should be the same as in edit mode.

### What actually happened

It seems that in preview mode, the timezone is not accounted for.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/36647

## Proposed changes:

In the editor, the Business Hours block shows different hours in preview and edit mode (see linked issue). The code hasn't changed in years and this might be due to a version bump of the `wordpress/data` package.

This PR fixes this by rendering the time with the same approach in both the `DayPreview` and `DayEdit` components.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Spin up a test site with this branch
- If you run it locally, make sure to run `cd projects/plugins/jetpack && pnpm run build-extensions`
- Create a post
- Add the _Business Hours_ block
- Make sure the hours are the same in edit and preview mode

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/business-hours/components/day-preview.js [hunk 1]
```diff
@@ -1,19 +1,14 @@
...
-		const { timeFormat } = this.props;
 		const [ hours, minutes ] = time.split( ':' );
-		const _date = new Date();
 		if ( ! hours || ! minutes ) {
 			return false;
 		}
-		_date.setHours( hours );
-		_date.setMinutes( minutes );
-		return date( timeFormat, _date );
+		return time;
```
Comment (monsieur-z) [inline projects/plugins/jetpack/extensions/blocks/business-hours/components/day-preview.js]: Time is rendered as is in `DayEdit` too.

**Review by jeherve — DISMISSED** [review]

**Comment by jeherve** [comment]
Ah, I had missed that the tests were failing because of the change. You'll need to update the tests I'm afraid.

**Review by jeherve — APPROVED** [review]
