### PR TITLE
Admin Menu: Fix invalid menu item ID attributes

### LINKED ISSUE #19625: WooCommerce Upsell Icon - No Logo Appearing
#### Steps to reproduce the issue

1. Install Jetpack beta on an Atomic site where WooCommerce is not installed/deactivated
2. Activate the master branch ("Bleeding Edge")
3. See the WooCommerce upsell icon appear as a white square
4. If you see the WooCommerce logo, try making sure the plugin is deactivated.

Screen Shot 2021-04-22 at 09 33 25

possibly related since it was also reported here: https://github.com/Automattic/jetpack/pull/19364

### PR DESCRIPTION
**Pull request by pablinos**
Some menu items are pointing to full URLs. It turns out these have a
number of invalid characters that aren't getting stripped out by the
core WordPress functions. This meant that invalid ID attributes were
being set and that in turn broke the SVG styling introduced in #19364.

Fixes #19625

#### Changes proposed in this Pull Request:

This PR fixes the ID, by filtering out invalid characters, allowing the icon to be properly displayed.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Using an Atomic site install Woocommerce
* Run the current master branch using the Jetpack Beta plugin
* Without Woocommerce activated, note that the icon is not displayed in the menu
* Swap to this branch and the icon should be displayed correctly.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 1]
```diff
@@ -389,16 +389,25 @@ public function override_svg_icons() {
...
 		foreach ( $menu as $idx => $menu_item ) {
-			if ( count( $menu_item ) > 6 && 0 === strpos( $menu_item[6], 'data:image/svg+xml' ) && 'site-card' !== $menu_item[3] ) {
-				$svg_items[] = array(
-					'icon' => $menu[ $idx ][6],
-					'id'   => $menu[ $idx ][5],
+			if ( count( $menu_item ) < 7 ) {
+				continue;
+			}
+
+			// If the hookname looks to contain a URL than sanitize it by remplacing invalid characters.
```
Comment (allilevine) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:396]: Should this be "If the hookname contains a URL then sanitize it by replacing invalid characters"?

**Review by allilevine — APPROVED** [review]
Works great! ✅ 
Screen Shot 2021-04-23 at 9 14 12 AM

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 1 above)
Comment (pablinos) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:396]: Yes, that's better! I think it was because the check is for `://` so it's a URL-like string, rather than being sure we've got a URL. Your version is simpler though

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 2]
```diff
@@ -389,16 +389,25 @@ public function override_svg_icons() {
 
 		$svg_items = array();
 		foreach ( $menu as $idx => $menu_item ) {
-			if ( count( $menu_item ) > 6 && 0 === strpos( $menu_item[6], 'data:image/svg+xml' ) && 'site-card' !== $menu_item[3] ) {
-				$svg_items[] = array(
-					'icon' => $menu[ $idx ][6],
-					'id'   => $menu[ $idx ][5],
+			if ( count( $menu_item ) < 7 ) {
```
Comment (retrofox) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:392]: minor one, can you add a comment on why the `$menu_item` number needs to be greater than `6`?

Comment (pablinos) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:395]: Yeah, good idea. It's obviously a legacy thing as it would be better to have those as named keys.

Comment (retrofox) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:395]: thanks, Paul.

**Review by retrofox — APPROVED** [review]
LGTM

#### Without WooCommerce installed or deactivated
The WooCommerce link points to `https://wordpress.com/woocommerce-installation/<blog-id>`

before (bleeding Edge) | after (this branch)
------|-------
image | image

When the plugin is activated, the visual issue doesn't happen.
