### PR TITLE
VideoPress: Fix token bridge issue in development environment

### LINKED ISSUE #28785: VideoPress: Video stuck on loading in development mode without HTTPS
Steps to reproduce:

1 - Run VideoPress locally
2 - In the block editor, add a VideoPress block
3 - Select a video from the media library. This step may be enough to trigger the exception
4 - Set the video to private
5 - Toggle some parameter, like `loop`, to force a token request
6 - Check that the video may be stuck on `Loading` with an error in the console about `ServiceWorker` being undefined:

Image

Edit: @renatoagds pointed out that `ServiceWorker` is available over HTTPS, so this is only an issue over HTTP.

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #28785

## Proposed changes:

* Checks if `ServiceWorker` is defined before checking against its type
* Also changes the calls to `postMessage` making the `targetOrigin` explicit to avoid Typescript warnings

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Test locally
* Go to the block editor
* Add a VideoPress block
* Set the video's privacy level to `private`
* Change some other property, like `loop` to force a token request
* Check that the video is loaded correctly and there is no error in the dev console

### CODE REVIEW

File: projects/packages/videopress/src/client/lib/token-bridge/index.ts [hunk 1]
```diff
@@ -88,7 +91,7 @@ export async function tokenBridgeHandler(
 			guid,
 			requestId,
 		},
-		'*'
+		{ targetOrigin: '*' }
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/lib/token-bridge/index.ts:94]: Reason:


`'*'` does work in the first signature, but TS shows an error anyway:

Comment (lhkowalski) [reply projects/packages/videopress/src/client/lib/token-bridge/index.ts:94]: So the change is to use another signature for the same function, using the `options` object instead of the straight string `targetOrigin`?

**Comment by lhkowalski** [comment]
Tested on my local env. Can confirm that I am not seeing the `ServiceWorker` error message:

Screen Shot 2023-02-06 at 18 05 07

File: projects/packages/videopress/src/client/lib/token-bridge/index.ts (hunk 1 above)
Comment (dhasilva) [reply projects/packages/videopress/src/client/lib/token-bridge/index.ts:94]: Yes. It should not change the functionality, just get rid of the "error".

**Review by lhkowalski — APPROVED** [review]
Code changes are good, and the tests showed that the error message is gone.

**Review by renatoagds — APPROVED** [review]
