### PR TITLE
Subscribe block: do not show in page editor and for private sites

### LINKED ISSUE #23688: Jetpack Subscriptions shows that Pages and Private Posts notify readers upon publications
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Navigate to Pages > Add a page, then click Publish
2. During the pre-publish check displays that the Page will be sent out to the site's readers.

*The same behavior occurs with Private Posts as well

### A clear and concise description of what you expected to happen.

The article for [Jetpack Subscriptions](https://jetpack.com/support/subscriptions/) explicitly states that notifications will not be sent for Pages. I assume this would apply to Private Posts:

> Jetpack Subscriptions will only send out notifications for new posts. Publishing other post types (like pages or a custom post type) or making updates to an already published post will not send a notification e-mail.

### What actually happened

Although it does display that readers will be notified of the Page and Private Post publication, and then subsequently states the Page/Post has been sent out to the subscribers, this appears to be merely a visual discrepancy, as subscribers are not notified of a Page, nor Private Post publication. 

### Other information

image

image

image

### Operating System

macOS

### OS Version

12.2.1

### Browser

Chrome/Chromium

### Browser Version(s)

Version 99.0.4844.84 (Official Build) (x86_64)

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #23688

#### Changes proposed in this Pull Request:

* Subscriptions are only available for posts, and not for private sites on WoA, so let's add some conditions to the display of subscription panels in the block editor.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Test on a WoA site, connected to WordPress.com, still private (not launched).
* Go to Jetpack > Settings and enable the Subscriptions feature.
* Go to Pages > Add New, type some content.
* Save your draft, and hit the Publish button; you should not see the Subscriptions panel in the Pre-publish panel.
* Now repeat the same thing when creating a post.
* Now repeat the same thing after setting the site to public; you should see the Subscriptions panel now.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js [hunk 1]
```diff
@@ -18,7 +21,23 @@ export default function SubscribePanels() {
...
 
-	return ! Number.isFinite( subscriberCount ) || subscriberCount <= 0 ? null : (
+	// Only show this for posts for now (subscriptions are only available on posts).
+	const postType = useSelect( select => select( editorStore ).getCurrentPostType(), [] );
+	if ( 'post' !== postType ) {
+		return null;
+	}
+
+	// Subscriptions will not be triggered on WoA's private sites.
+	if ( isAtomicSite() && isPrivateSite() ) {
```
Comment (mtias) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: Can private sites have subscribers / collaborators?

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: They can have subscribers, yes, if they were public at one point and then switched to private, but subscription emails are not being sent once the site is private.

Comment (mtias) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: But they might be getting notifications? What about members of the site that are following / getting emails for the site?

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: No emails will be sent to anyone, and no post will appear in the Reader, whether you're a member of the site or not.

Comment (ivan-ottinger) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: Turns out that `isPrivateSite()` returns `false` when the site hasn't been launched. 🤔 

As a result, the text still displays in the sidebar.

**Review by sdixon194 — APPROVED** [review]
Does the job for me 👍

**Review by ivan-ottinger — CHANGES_REQUESTED** [review]
The text doesn't display when publishing a page anymore 👍🏼 

Markup on 2022-03-30 at 16:07:44

but I can still see it when the site hasn't been launched.

File: projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js (hunk 1 above)
Comment (ivan-ottinger) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: On the PHP side we have `is_coming_soon()` and `get_launch_status()` available, but I haven't found an equivalent on the JS/React side yet.

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: Ah, I guess I'm not testing "not launched" properly then; I was just making my site private under Settings > General, but that's different from "not launched" I see. I'll come up with something to fix not launched sites as well.

Comment (sdixon194) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js:31]: Yeah I had tested it by setting my site to private. Strange that I'd expect isPrivateSite() to return true. I see we have an endpoint for the launch status - maybe helpful?  https://github.com/Automattic/jetpack/blob/master/projects/plugins/jetpack/sal/class.json-api-site-jetpack.php#L185

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Just pushed f502a5423a9a2c1548e9a1b6b9d77dce4c7d5c81 to try to address this situation.

Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: I just spent some time testing this now using a non-launched WoA site, using this feature branch with the beta plugin. The subscription panel does show for posts only, in the pre-publish panel.
Screenshot 2022-03-31 at 11 11 20

That was my first time setting up a WoA dev blog so it's possible I've missed something, but everything seems to be in place from what I can see.

Comment (jeherve) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: I've just pushed 6e1fcf5a2c1c6cb49f2d314973767c6ab70d42cd to try a fix, I had missed that export so my last changes were not building properly, sorry!

Comment (ivan-ottinger) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Works as expected now. 😊👍🏼 

When the site hasn't been launched, the "Subscribe" panel doesn't load (it doesn't load when publishing a _page_ either):
Markup on 2022-03-31 at 12:54:13

As soon as the site is launched and _public_, the "Subscribe" panel loads when publishing a _post_:
Markup on 2022-03-31 at 12:56:16

Tested the changes when the site was in the _coming soon_ and _private_ mode as well. The "Subscribe" panel doesn't load - as expected.

Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: That works for me now too. However after launching the site, with the PR being tested there is no subscriber panel pre-publish with posts, and when I remove the beta plugin there is a subscriber panel showing.
It may just be this WoA site though - despite being public now every WordPress.com dashboard load shows it momentarily as being in 'Coming Soon' mode, then that disappears.

Comment (ivan-ottinger) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: > [...] despite being public now every WordPress.com dashboard load shows it momentarily as being in 'Coming Soon' mode, then that disappears.

Interesting. Does it appear and disappear for you in the "pre-publish" panel? 🤔

Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/subscriptions/panel.js]: Ah no, sorry. I meant the 'coming soon' banner showing under the site URL (under 'My Sites') in the WordPress.com dashboard appears and then disappears. However I just changed it back to private then back to public again, and now everything works perfectly 🤷

**Review by coder-karen — APPROVED** [review]

**Comment by samiff** [comment]
r242922-wpcom

cherry-picked to `jetpack/branch-10.8` in 76715b8c4dbd6f097fd2865c1c4db62ed987b033
