### PR TITLE
Fix Pay via Paypal block: currency symbol appears after the price in editor

### LINKED ISSUE #11897: Simple Payments Gutenberg block: currency symbol appears after the price in editor
#### Steps to reproduce
1. Starting from a Jetpack site running WP 5.0 Beta 5 and JP 6.8 Beta 3, with a Premium plan.
2. Go to Posts > Add New, and create a new simple payment button
3. The price looks ok on the frontend, but on the block preview in wp-admin, the dollar sign comes after the price:

screen-shot-2018-11-22-at-16-10-51

### PR DESCRIPTION
**Pull request by mreishus**
fixes #11897

#### Changes proposed in this Pull Request:

* Simple payments block now uses `Intl.NumberFormat()` to format currency display, if available

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* On master branch, create a new post.
* Add a 'Pay via Paypal' block and fill out the information.  Save as draft.
* Unfocus the block.  In preview mode, instead of "$5.00", it will say "5.00 $".
* Switch to this branch and reload the post.
* The block should upgrade correctly and now display $5.00.
* Other currencies and locales should be supported as well.

( To test on my sandbox, I used `yarn build-extensions --watch` and then rsynced the `./_inc/blocks` folder over).

#### Proposed changelog entry for your changes:

* Simple payments block now uses `Intl.NumberFormat()` to format currency display, if available

### CODE REVIEW

File: extensions/blocks/simple-payments/utils.js [hunk 1]
```diff
@@ -21,9 +22,50 @@ export const decimalPlaces = number => {
 	return Math.max( 0, ( match[ 1 ] ? match[ 1 ].length : 0 ) - ( match[ 2 ] ? +match[ 2 ] : 0 ) );
 };
 
-export const formatPrice = ( price, currency, withSymbol = true ) => {
+const getNavigatorLanguage = () => {
+	if ( navigator.languages && navigator.languages.length ) {
+		return navigator.languages[ 0 ];
+	}
+	return navigator.userLanguage || navigator.language || navigator.browserLanguage || 'en';
+};
```
Comment (mreishus) [inline extensions/blocks/simple-payments/utils.js:30]: I grabbed this after looking through https://stackoverflow.com/questions/673905/best-way-to-determine-users-locale-within-browser .

File: extensions/blocks/simple-payments/depecrated/v2/save.js [hunk 2]
```diff
@@ -0,0 +1,61 @@
+/**
+ * WordPress dependencies
+ */
+import { __ } from '@wordpress/i18n';
+
+/**
+ * Internal dependencies
+ */
+import { formatPriceFallback } from '../..//utils';
```
Comment (obenland) [inline extensions/blocks/simple-payments/depecrated/v2/save.js:9]: Found a double slash in case that matters. It probably doesn't

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Thanks @mreishus for working on this!
Indeed by applying the patch the euro / dollar sign moved to the left both in editor and the frontend


It seems though, that language discovered is the interface language and not the site language (left inline comment).

Also, have you considered updating this package
https://github.com/Automattic/wp-calypso/blob/2eff0c49dfee1fb27461bd1e11ee4e93d2d83e6e/packages/format-currency/src/index.js#L27

instead of introducing changes that are scoped to only that block?

File: extensions/blocks/simple-payments/utils.js [hunk 3]
```diff
@@ -21,9 +22,50 @@ export const decimalPlaces = number => {
...
+export const formatPriceFallback = ( price, currency, withSymbol = true ) => {
 	const { precision, symbol } = getCurrencyDefaults( currency );
 	const value = price.toFixed( precision );
 	// Trim the dot at the end of symbol, e.g., 'kr.' becomes 'kr'
 	return withSymbol ? `${ value } ${ trimEnd( symbol, '.' ) }` : value;
 };
+
+// Display prices using Intl.NumberFormat - supported in 95.75% of browsers as of Oct 2020.
+const formatPriceIntlNumberFormat = ( price, currency, withSymbol = true ) => {
+	const { siteLocale } = select( 'core/block-editor' ).getSettings();
```
Comment (cpapazoglou) [inline extensions/blocks/simple-payments/utils.js:42]: `const { siteLocale } = select( 'core/block-editor' ).getSettings();` will return the current user interface language and not the current site language. So, when a user (me) has `en` as interface language (very common) but `greek` as site language then the symbol appears on the left whereas it should appear in the right.



I searched it a bit, I am not sure if `getLocaleSlug` from `i18n-calypso` will return the correct locale
https://github.com/Automattic/wp-calypso/blob/aa011d0e42b1190ead34a407538d21e7e8fe2186/packages/i18n-calypso/src/i18n.js#L314

File: extensions/blocks/simple-payments/utils.js [hunk 4]
```diff
@@ -21,9 +22,50 @@ export const decimalPlaces = number => {
...
+	// "Shouldn't" reach here - maybe Intl.Numberformat rejected the currency. Fallback.
+	return formatPriceFallback( price, currency, withSymbol );
+};
+
+// Format a price with Intl.NumberFormat if available, but fall back to old method if not.
+export const formatPrice = ( price, currency, withSymbol = true ) => {
+	if ( window.Intl && 'function' === typeof Intl.NumberFormat ) {
+		return formatPriceIntlNumberFormat( price, currency, withSymbol );
+	}
+	return formatPriceFallback( price, currency, withSymbol );
```
Comment (cpapazoglou) [inline extensions/blocks/simple-payments/utils.js:70]: Can't this be part of a generic `formatPriceIntlNumberFormat` which will return `formatPriceFallback( price, currency, withSymbol );` if not `window.Intl && 'function' === typeof Intl.NumberFormat`?

**Review by cpapazoglou — CHANGES_REQUESTED** [review]

**Comment by mreishus** [comment]
> Also, have you considered updating this package
> https://github.com/Automattic/wp-calypso/blob/2eff0c49dfee1fb27461bd1e11ee4e93d2d83e6e/packages/format-currency/src/index.js#L27
> 
> instead of introducing changes that are scoped to only that block?

If we're going to use locale, I don't think `formatCurrency` from `@automattic/format-currency` is a good fit.  It doesn't expect a locale in its API, and I don't think it will be able to pull one from say, calypso state because it's a separate package (would need to be usable by outside consumers).

That said, I'm not sure if we can get the correct locale either, looking into that next..

**Comment by mreishus** [comment]
Found an interesting example while testing, in the German locale the Euro sign goes on the right, in English, it goes on the left:

```
console.log(new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(12345.67));
12.345,67 €
console.log(new Intl.NumberFormat('en-US', { style: 'currency', currency: 'EUR' }).format(12345.67));
€12,345.67
```

File: extensions/blocks/simple-payments/utils.js (hunk 3 above)
Comment (mreishus) [reply extensions/blocks/simple-payments/utils.js:43]: Good catch! I pushed an update that uses getLocalSlug, can you try it out and let me know if it works? I tried updating both my site and wordpress user language to Greek, and it didn't seem to work.  Maybe it's because I'm using the wp-admin edit to test?  This may be difficult..

File: extensions/blocks/simple-payments/utils.js (hunk 4 above)
Comment (mreishus) [reply extensions/blocks/simple-payments/utils.js]: I'm not sure what you're referring to - is it this? 
* [fix/currency-display c9aa474b6] Inline formatPrice selector function
Personally, I prefer the previous version that has a slightly simpler function at the trade-off of adding one more function.

File: extensions/blocks/simple-payments/utils.js (hunk 3 above)
Comment (cpapazoglou) [reply extensions/blocks/simple-payments/utils.js:47]: It still returns the `en` version for me too. Seems like 
https://github.com/Automattic/wp-calypso/blob/aa011d0e42b1190ead34a407538d21e7e8fe2186/packages/i18n-calypso/src/i18n.js#L256-L259
it returns the `defaultLocaleSlug`.... That said, I am not sure how we can fix this.

**Comment by mreishus** [comment]
It looks like jetpack removed all references to `i18n-calypso` and uses `@wordpress/i18n` for everything. (See: https://github.com/Automattic/jetpack/issues/16481)

Since `@wordpress/i18n` knows how to translate into the user language ( `__("This is a test")` ), it has to know the user language.  So, can we get the current user language from it?  I see a `setLocaleData` but not a `getLocale` from https://github.com/WordPress/gutenberg/tree/master/packages/i18n.

**Comment by mreishus** [comment]
We might be able to get it by translating `html_lang_attribute` with `__()`.  I found this in some translation files.

**Comment by mreishus** [comment]
Not having much luck with `__`.  I'm not able to get it to translate anything at all; even after changing my wordpress interface language, site language in wp-admin, and browser language to French, I can't get a translation that's elsewhere in the code to work:

```
	const backup = __( 'Daily Backups', 'jetpack' );
	console.log( backup );
```

**Comment by mreishus** [comment]
I removed all of the locale detection code, since it wasn't working.  The function that gets it from the browser settings is there and seems to work.  That might be good?




Next steps(?):
* Ask Jetpack crew if there's a way to get the current locale
* If not, reconsider adding this code to the '@automattic/format-currency' package

File: extensions/blocks/simple-payments/index.js [hunk 5]
```diff
@@ -189,5 +190,5 @@ export const settings = {
 		reusable: false,
 	},
 
-	deprecated: [ deprecatedV1 ],
+	deprecated: [ deprecatedV1, deprecatedV2 ],
```
Comment (simison) [inline extensions/blocks/simple-payments/index.js:193]: Not blocking this PR or anything, but I was always wondering if it would work to async-load these deprecations. They're basically doubling/tripling the block JS+CSS size each time.

cc @sgomes for thoughts

File: extensions/blocks/simple-payments/utils.js (hunk 1 above)
Comment (simison) [reply extensions/blocks/simple-payments/utils.js:30]: Wouldn't you need it in site's locale, rather than user's browser? 🤔 I might be missing some context here tho. :-)

File: extensions/blocks/simple-payments/utils.js (hunk 4 above)
Comment (cpapazoglou) [reply extensions/blocks/simple-payments/utils.js]: Yes, that is exactly what I meant. 

> Personally, I prefer the previous version that has a slightly simpler function at the trade-off of adding one more function.

From a reading point (while reviewing), I felt it weird but feel free to revert using your version in that case!

**Comment by cpapazoglou** [comment]
> I removed all of the locale detection code, since it wasn't working. The function that gets it from the browser settings is there and seems to work. That might be good?
> 
> 
> 
> 
> Next steps(?):
> 
> * Ask Jetpack crew if there's a way to get the current locale
> * If not, reconsider adding this code to the '@automattic/format-currency' package

If getting the current site locale seems impossible, lets go with the browser locale which shouldn't be that bad from a visitor perspective and we can iterate later.

It seems also that we should have a holistic solution for currency symbols across all blocks that show prices.

File: extensions/blocks/simple-payments/index.js (hunk 5 above)
Comment (sgomes) [reply extensions/blocks/simple-payments/index.js:193]: If at all possible, I would heartily recommend that, yes. Looking at the code, however, it's not immediately obvious how to do that easily.

Perhaps making `deprecated` an async function to an array, rather than a simple array?

```js
{
  deprecated: async () => {
    const deprecatedV1 = await import( './depecrated/v1' );
    const deprecatedV2 = await import( './depecrated/v2' );
    return [ deprecatedV1, deprecatedV2 ];
  },
}
```

Other code that makes use of these properties would then have to be updated accordingly, and made to be async-safe.

Fixing the `depecrated` typo would also be nice 😄

Comment (simison) [reply extensions/blocks/simple-payments/index.js:193]: Yeah, so maybe this is something to add support for in core first. cc @mtias @youknowriad

File: extensions/blocks/simple-payments/utils.js (hunk 1 above)
Comment (mreishus) [reply extensions/blocks/simple-payments/utils.js:30]: Yeah.. we're trying to find the best way to get the site's locale.  I've removed a couple of methods that don't work and the navigator locale is all that's left right now.  I'll add `[WIP]` to the PR to be a bit clearer

**Comment by mreishus** [comment]
@cpapazoglou : Do you have an opinion on using the browser language vs `const { siteLocale } = select( 'core/block-editor' ).getSettings();` which gets the wp.com interface language?  Which is better?

**Comment by cpapazoglou** [comment]
> @cpapazoglou : Do you have an opinion on using the browser language vs `const { siteLocale } = select( 'core/block-editor' ).getSettings();` which gets the wp.com interface language? Which is better?

I would go with `const { siteLocale } = select( 'core/block-editor' ).getSettings();` which is something users can set to our application and we don't rely to browser settings (which in some cases users may not have access to also).

**Comment by mreishus** [comment]
Ok, summarizing the issues from reviews so far:

- **How to load the WordPress site's locale?**
After searching around, we couldn't find a way to do it.  The code currently uses the Wordpress interface locale, and if that isn't valid, then falls back to the browser's locale.
- **Async load deprecations**
I split this off into its own issue: https://github.com/Automattic/jetpack/issues/17467
- **Apply the fix to all blocks that show currencies?**
Calypso does have an `@automattic/format-currency` package, which contains a `formatCurrency()` function.  That function doesn't expect its callers to pass in a locale.  If we were to modify `formatCurrency()` to use `Intl.NumberFormat()`, all of its call sites would have to be modified to find a locale to pass, and the scope of this change would increase considerably.  
Given the number of user issues inside the parent issue, I propose moving forward with the limited scope fix and put modifying `@automattic/format-currency` into another issue.

File: extensions/blocks/simple-payments/index.js (hunk 5 above)
Comment (jeherve) [reply extensions/blocks/simple-payments/index.js:193]: Conversation to be continued in #17467.

**Comment by cpapazoglou** [comment]
> Given the number of user issues inside the parent issue, I propose moving forward with the limited scope fix and put modifying @automattic/format-currency into another issue.

Sounds good!

**Review by cpapazoglou — APPROVED** [review]
Looks and works great! Thanks for making the changes!

File: extensions/blocks/simple-payments/index.js [hunk 6]
```diff
@@ -14,6 +14,7 @@ import { getIconColor } from '../../shared/block-icons';
 import edit from './edit';
 import save from './save';
 import deprecatedV1 from './depecrated/v1';
+import deprecatedV2 from './depecrated/v2';
```
Comment (jeherve) [inline extensions/blocks/simple-payments/index.js:17]: Maybe we can take this opportunity to:

1. Rename `depecrated/` into `deprecated` to fix this typo.
2. Have a `deprecated/index.js` where we collect all deprecations, a bit like here:
https://github.com/Automattic/jetpack/blob/c3774de77e1c255b7e5e447cbc246dc21daca7e4/extensions/blocks/eventbrite/deprecated/index.js#L2-L7

**Review by jeherve — APPROVED** [review]
This looks good to me. I have some feedback below, but that's a minor nitpick, can be done in another PR.

**Comment by mreishus** [comment]
Github lists one of the required checks as failing: "wpcom — Tests failed: D50729-code".  However, looking over at D50729-code, it shows all the checks in the buildable passing.  Any insight into this @jeherve ?

**Review by jeherve — APPROVED** [review]

**Comment by AtrumGeost** [comment]
Hi folks!

Thanks for working on this :) Do you know when these changes will be reflected on WordPress.com?

**Comment by mreishus** [comment]
Hi @AtrumGeost

> Thanks for working on this :) Do you know when these changes will be reflected on WordPress.com?

Jetpack is released on the first Tuesday of each month, so it should be November 3rd (someone please correct me if I'm wrong).

**Comment by simison** [comment]
@mreishus are you waiting for the release day to ship .com side? D50729-code

**Comment by mreishus** [comment]
> @mreishus are you waiting for the release day to ship .com side? [D50729-code](https://href.li/?D50729-code)

That does work, but I was a bit worried about Simple -> Atomic transfers occurring after that was pushed.  There are invisible block validation errors, which might not matter?  But I was thinking about the case where someone pays extra to get a business or ecommerce plan, finds their paypal block is degraded as a part of the transfer, and then there's nothing we can do about it.  Any thoughts on that?

**Comment by jeherve** [comment]
> Jetpack is released on the first Tuesday of each month, so it should be November 3rd

That would normally be the case, but we're exceptionally releasing a week later this month, to avoid releasing on Election Day in the US.

> I was thinking about the case where someone pays extra to get a business or ecommerce plan, finds their paypal block is degraded as a part of the transfer, and then there's nothing we can do about it.

Yes, I think it's fine to wait until release day to push that commit. That's what we've been doing so far for all commits that change the way blocks are saved, to avoid the problems you highlighted.

**Comment by jeherve** [comment]
r216551-wpcom
