### PR TITLE
Fix: newsletter toggle in editor sidebar has a visually broken active state

### LINKED ISSUE #97139: Newsletter toggle in editor sidebar has a visually broken active state
### Quick summary

Image

Image

### Steps to reproduce

1. Write a post in the post editor
2. Click Publish (the publish confirmation sidebar opens)
3. Scroll down to the **Newsletter** area
4. Toggle to **Post only**

### What you expected to happen

The **Post only** option should look selected, with a black background

### What actually happened

The **Post only** button looks like it's disappearing

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

It still publishes without sending an email. The component just looks broken.

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by zaerl**
Fixes https://github.com/Automattic/wp-calypso/issues/97139

The [ToggleGroupControl](https://developer.wordpress.org/block-editor/reference-guides/components/toggle-group-control/) component seems unhappy with a `false` value set in a `ToggleGroupControlOption` child component. Despite the value **is** false (and so the right value), the `useAnimatedOffsetRect` component does not calculate valid CSS variables used for animation but instead generates a:

```
--selected-top: 0;
--selected-right: 0;
--selected-bottom: 0;
--selected-left: 0;
--selected-width: 0;
--selected-height: 0;
```

They should be similar to:

```
--selected-top: 4;
--selected-right: 4;
--selected-bottom: 4;
--selected-left: 124;
--selected-width: 120;
--selected-height: 32;
```

Once changed to two strings, it is working. I checked other places where the component is used, and it is working in the same way.

I don't consider this a Gutenberg bug but simply the component that does not accept falsy booleans, and I vote not to open a Gutenberg issue.

https://github.com/user-attachments/assets/6c9e72ae-167e-403e-9865-4cc018a82447

## Proposed changes:

* Replace `true/false` values with `"post-and-email"/"post-only"` strings
* Change `toggleSendEmail` and `isSendEmailEnabled` to accept the new values

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* You need a Jetpack plan with included the newletter
* If the newsletter is not active, go to `/wp-admin/admin.php?page=jetpack#newsletter` and switch on "Let visitors subscribe to this site and receive emails when you publish a post"
* If you don't have active subscribers, go to https://cloud.jetpack.com/subscribers, select the site, and import one of your emails used for testing.

Then you'll need to do two examples.

* Create a new post, add a title and some content
* Click "Publish" on top right
* Make sure that you can click the "Post & email / Post only" component

Submit the post with the selected "Post & email" and be sure to receive an email with the new post. Create another post with "Post only" selected, submit it, and be sure **not** to receive any email.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/shared/memberships/settings.js [hunk 1]
```diff
@@ -315,7 +315,7 @@ export function NewsletterEmailDocumentSettings() {
 	const isSendEmailEnabled = useSelect( select => {
 		const meta = select( editorStore ).getEditedPostAttribute( 'meta' );
 		// Meta value is negated, "don't send", but toggle is truthy when enabled "send"
```
Comment (p-jackson) [inline projects/plugins/jetpack/extensions/shared/memberships/settings.js:317]: I'm not sure whether this comment is still necessary. Now that the toggle control value is a string, the code is more self-documenting IMO.

**Review by p-jackson — APPROVED** [review]
LGTM
