### PR TITLE
Fix gallery click behaviour for when image has rounded corners

### LINKED ISSUE #65350: Jetpack Carousel: Space Around Rounded Images Open Carousel Even If Image Has a Custom Link
### Quick summary

When Jetpack Carousel feature is enabled, the space around rounded images open the image in the carousel. This happens when the image style is set to rounded.

### Steps to reproduce

1. Make sure Image Gallery Carousel option is enabled. For simple sites this is in: Settings > Media. For atomic sites this is at the top: Jetpack > Settings > Writing.
2. Add a Gallery block and some images to a page
3. Set the image style to be rounded.
4. Add a custom link to the images.
5. Update page to save changes.
6. View the live version of the page and click the white space between the images. It opens a carousel view instead of going to the link in the image.

Here is an example of where to click in the white space:

Markup 2022-07-07 at 07 41 13

### What you expected to happen

That clicking the white space would either not link anywhere OR that it would link to the same link set for the image.

### What actually happened

The image is opened in carousel view.

### Context

HC-35866904

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

I found two options:

1. Disabled the carousel feature. 

- For simple sites - this can be done in Settings > Media > uncheck "Display images in full-size carousel slideshow".
- For atomic sites - this can be done in Jetpack > Settings > Writing > toggle off "Display images in a full-screen carousel gallery"

2. Use combination of Column blocks and Image blocks for content. Images set to rounded that have a link added function as expected.

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes https://github.com/Automattic/wp-calypso/issues/65350

#### Changes proposed in this Pull Request:
When clicking into part of an image that has been removed due to the rounded style, the click handling logic will now navigate to the image's custom URL, if there is one, instead of opening the carousel view. If no custom URL exists, the default behaviour of opening the carousel remains. 

image

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
Test this on a site with Jetpack Beta installed, e.g. an Ephemeral Site. 

1. Navigate to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack`
2. Enable this branch
3. Then follow the [Steps to reproduce in the original issue. ](https://github.com/Automattic/wp-calypso/issues/65350) and verify that the click behaviour has changed and that you are navigated to the custom URL you set.

### CODE REVIEW

**Comment by mpkelly** [comment]
@daledupreez this is a remake of the old PR. It uses your proposed change. I've just tested it and it seems to be working ok. Can you review it when you get time.

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js [hunk 1]
```diff
@@ -1606,45 +1606,54 @@
...
+				// a custom link so don't load the carousel.
+				if (
+					parentHref &&
+					parentHref.split( '?' )[ 0 ] !==
+						target.getAttribute( 'data-orig-file' ).split( '?' )[ 0 ] &&
+					parentHref !== target.getAttribute( 'data-permalink' )
+				) {
 					return;
 				}
+			}
```
Comment (daledupreez) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.js]: This closing bracket looks like it is in the wrong place. It looks like the following two lines need to be inside this `if ( gallery )` code block, but you've shifted them out of the block:
```js
			var index = Array.prototype.indexOf.call( gallery.querySelectorAll( itemSelector ), item );
			loadSwiper( gallery, { startIndex: index } );
```

We can either move the closing bracket further down, or we can simply flip the opening condition so we have another early return instead of an indent:
```js
			if ( ! gallery ) {
				return;
			}

			if ( ! testForData( gallery ) ) {
				return;
			}
			// etc...
```

**Review by daledupreez — CHANGES_REQUESTED** [review]

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js (hunk 1 above)
Comment (mpkelly) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js]: Thanks, @daledupreez! That's been fixed [here](https://github.com/Automattic/jetpack/pull/25410/commits/1c7c315c8d381237fde700bcb8e4136a013a47e1).

File: projects/plugins/jetpack/changelog/fix-gallery-image-with-link [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: bugfix
+
+Gallery: ensure clicks will navigate to custom URL when image has rounded corners.
```
Comment (daledupreez) [inline projects/plugins/jetpack/changelog/fix-gallery-image-with-link]: Nit: I think this is technically a fix to the Carousel feature rather than the Gallery code. It may be worth rephrasing this to represent that more accurately.
```suggestion
Carousel: ensure that clicks on rounded images in galleries will load a custom URL when it is specified.
```

**Review by daledupreez — DISMISSED** [review]
Other than clarifying the changelog entry, this LGTM!

Thanks for sticking with this one through multiple PRs! Also, apologies for not getting this tested yesterday.

File: projects/plugins/jetpack/changelog/fix-gallery-image-with-link (hunk 2 above)
Comment (mpkelly) [reply projects/plugins/jetpack/changelog/fix-gallery-image-with-link]: Ok, I've accepted this version.

**Review by daledupreez — APPROVED** [review]
Re-approving after the changelog update

**Review by sdixon194 — APPROVED** [review]
This works great for me, thanks for the fix!

**Comment by daledupreez** [comment]
I deployed this in r251016-wpcom while pairing with @mpkelly.
