### PR TITLE
Instant Search: Fix taxonomy name compilation bug

### LINKED ISSUE #14377: Instant Search: taxonomy filters not being applied to results
#### Steps to reproduce the issue

1. Follow the [newly updated testing instructions](https://github.com/Automattic/jetpack/blob/add/instant-search-filter-injection/modules/search/instant-search/README.md#testing-instructions) which requires adding a Jetpack Search widget into the overlay widget area (named `Jetpack Search Sidebar`). Please make sure to configure some search filters for this widget, including a taxonomy filter: Tag, Category or Post Type.
2. Perform a site search to trigger the Jetpack Search overlay.
3. Check a Tag, Category or Post Type filter.

#### What I expected
Checking a Tag, Category or Post Type filters the search results by the selected option.

#### What happened instead
Checking a Tag, Category or Post Type filter changes the query string, but does not alter the results.

Screen Shot 2020-01-17 at 15 08 28

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #14377.

#### Changes proposed in this Pull Request:

* Fixes logic in `getFilterKeys` function to account for all widget configurations instead of just the first widget when compiling an array of viable taxonomy names.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
1. Follow the [newly updated testing instructions](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions) which requires adding a Jetpack Search widget into the overlay widget area (named `Jetpack Search Sidebar`). Do not configure a taxonomy filter for the widget in the overlay.
2. Add a Jetpack Search widget to either your footer or site sidebar. Configure a taxonomy filter for this widget.
3. Trigger the search overlay by clicking on a taxonomy filter selected in step 2.
4. Ensure that the search results in the overlay have been filtered as expected. 

#### Proposed changelog entry for your changes:
* None.

### CODE REVIEW

File: modules/search/instant-search/lib/query-string.js [hunk 1]
```diff
@@ -3,10 +3,6 @@
  */
 import 'url-polyfill';
 import { decode, encode } from 'qss';
-// NOTE: We only import the get package here for to reduced bundle size.
-//       Do not import the entire lodash library!
-// eslint-disable-next-line lodash/import-scope
-import get from 'lodash/get';
```
Comment (bluefuton) [inline modules/search/instant-search/lib/query-string.js]: 🎉

**Review by bluefuton — APPROVED** [review]
Works well in my testing 🚢
