### PR TITLE
Publicize / Subs: do not show pushed message for private posts

### LINKED ISSUE #11109: Wrong message on publishing private posts about emails being sent
#### Steps to reproduce the issue

1. Activate subscriptions (and provide your own alternative email addresses if doing it fresh, so that you have subscribers)
2. Add a new post
3. Make it private with options on the right
4. Publish
5. Message saying email sent to subscribers

#### What I expected
(maybe a message saying that no email is sent since the post is private)

#### What happened instead
Message saying email sent.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #11109 

#### Changes proposed in this Pull Request:

In the old editor, we display messages at the top of the editor when a post has been published and sent to subscribers and / or posted to linked Social Media sites.

image

Since our Subscriptions and Publicize modules are not triggered for private posts, let's not show that message when a private post is created.

#### Testing instructions:

* Start on a site with Publicize and Subs active and configured (at least one Social Media profile connected).
* Install the classic editor plugin on your site.
* Write a new post.
* Change its status to Private in the options above the Publish button.
* click update.
* Make sure no message appears at the top of the page about Publicize or Subscriptions.
* Repeat with only Publicize active, and only Subscriptions.
* Repeat with a public post; the message should appear.
* Repeat with a scheduled post; the message should appear.

#### Proposed changelog entry for your changes:

* Publicize / Subscriptions: do not show message at the top of the editor when creating a private post.

### CODE REVIEW

File: modules/publicize/publicize.php [hunk 1]
```diff
@@ -1038,6 +1038,12 @@ public function update_published_message( $messages ) {
 		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
 			return $messages;
 		}
+
+		// Bail early if the post is private.
+		if ( 'private' === $post->post_status ) {
```
Comment (mdawaffe) [inline modules/publicize/publicize.php]: It's probably slightly more correct to look at the return value of `get_post_status_object()`:

```php
$post_status_object = get_post_status_object( $post->post_status );
if ( $post_status_object->private ) {
  return $messages;
}
```

Or maybe
```php
if ( ! $post_status_object->public ) {
  return $messages;
}
```

I'm not sure.

That said, none of the other Publicize code does that :) Instead, we only Publicize posts that have `post_status=publish`, which suggests to me that we shouldn't bother with the post_status_object at all, but that we should change the conditional to:

```php
if ( 'publish' !== $post->post_status ) {
  return $messages;
}
```

What do you think?

File: modules/subscriptions.php [hunk 2]
```diff
@@ -211,6 +211,11 @@ public function should_email_post_to_subscribers( $post ) {
 			return false;
 		}
 
+		// Private posts are not sent to subscribers.
+		if ( 'private' === $post->post_status ) {
```
Comment (mdawaffe) [inline modules/subscriptions.php]: I'm not sure where we decide what posts are sent out to subscribers. Not `post_status=private` ones? Only `post_status=publish` ones?

**Review by mdawaffe — COMMENTED** [review]
> Repeat with a scheduled post; the message should appear.
 
I'm not sure what I'm looking for here. For both master and this branch, I see:

> Post scheduled for: Jan 10, 2020 @ 06:01. Preview post

That is, there's no mention of subscribers/publicize, but that is not a change between master and here.

File: modules/publicize/publicize.php (hunk 1 above)
Comment (jeherve) [reply modules/publicize/publicize.php]: That's true. Updated in 6d1cefa4e4d6efdb02daf630867b02763088835b

File: modules/subscriptions.php (hunk 2 above)
Comment (jeherve) [reply modules/subscriptions.php]: I believe that is done on WordPress.com after the sync, but @enejb would know better.

**Review by brbrr — APPROVED** [review]
It works well in my tests! :shipit:
