### PR TITLE
Search: Improve a11y via headings hierarchy and aria roles

### LINKED ISSUE #22156: Instant Search: Heading hierarchy for accessibility
### Impacted plugin

Jetpack

### Steps to Reproduce

Screenshot below in 'What actually happened' or

1. Open Instant Search modal
2. Add search query
2. Note the nested headings of filter types and skipped heading levels 

### A clear and concise description of what you expected to happen.

Ideally, there should be a heading level 1 for the full search dialog box which can be hidden with the `.screen-reader-text` class with results and filters separated by heading level 2.

The current heading level 1, 'Search Results', should be heading level 2 as each subsequent result is a heading level 3. 

'Filter Options' should be heading level 2 with subsequent filters heading level 3.

e.g.
image

### What actually happened

Please see below screenshot. The heading structure between results and filters are incorrect with no heading level 2 to separate results and filters.

Filters are nested under the last search result.

The 'Filter Options' section has no heading at all and immediately skips to heading level 4. Therefore, filter headings are nested under the last search result. 

e.g.
image

### Operating System

Windows

### OS Version

Any OS

### Browser

Firefox

### Browser Version(s)

Any browser

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #22156. cc @jpumfreyamergin, who first reported this issue.

#### Changes proposed in this Pull Request:
* Reorganizes the headings hierarchy for improved accessibility.
* Reorganizes and adds aria roles for improved accessibility. 

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your site with a Jetpack Search subscription.
* Perform a site search.
* Ensure that the elements have reasonable aria roles and heading hierarchies.

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const Overlay = props => {
 			role="dialog"
 		>
 			<h1 id="jetpack-instant-search__overlay-title" className="screen-reader-text">
-				{ __( 'Search results', 'jetpack' ) }
+				{ __( 'Jetpack Search Results', 'jetpack' ) }
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx:47]: Is it relevant to the user that Jetpack Search produced the results?

I think I'd be tempted to stick with the original text.

File: projects/plugins/jetpack/modules/search/instant-search/components/search-filters.jsx [hunk 2]
```diff
@@ -88,9 +88,9 @@ class SearchFilters extends Component {
 		return (
 			<div className="jetpack-instant-search__search-filters">
 				{ this.props.showTitle && (
-					<div className="jetpack-instant-search__search-filters-title">
+					<h2 className="jetpack-instant-search__search-filters-title">
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-filters.jsx:91]: Nice 👍

File: projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx [hunk 3]
```diff
@@ -56,7 +56,7 @@ class Gridicon extends Component {
 			case 'gridicons-comment':
 				return <title>{ __( 'Matching comment.', 'jetpack' ) }</title>;
 			case 'gridicons-cross':
-				return <title>{ __( 'Close search results', 'jetpack' ) }</title>;
+				return <title>{ __( 'Close search interface', 'jetpack' ) }</title>;
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx:59]: "interface" is pretty technical language - shall we stick with "results"?

File: projects/plugins/jetpack/modules/search/instant-search/components/search-results.jsx [hunk 4]
```diff
@@ -229,7 +227,7 @@ class SearchResults extends Component {
 						onClick={ this.closeOverlay }
 						onKeyPress={ this.onKeyPressHandler }
 						tabIndex="0"
-						aria-label={ __( 'Close search results', 'jetpack' ) }
+						aria-label={ __( 'Close search interface', 'jetpack' ) }
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-results.jsx:230]: "interface" is pretty technical language - shall we stick with "results"?

File: projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx (hunk 1 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx:47]: Do you see any value in giving the user additional branding context here? Visually, it's easy to tell that Jetpack Search produced the overlay. Using a screen reader, however, you'd need to drill all the way down to the bottom of the sidebar, like so:

Screen Shot 2022-01-10 at 3 42 02 PM

File: projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx (hunk 3 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx:59]: I agree that "interface" is too technical to be used here. The original intent of my change was to make the cross more explicitly indicate overlay closure. In this case, we're not merely closing "search results", but the entire overlay including various search controls that would be reset in such a closure.

Maybe "window" or "screen" would be better?

File: projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx (hunk 1 above)
Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/components/overlay.jsx]: I reckon keeping the title brief outweighs branding in this case 👍

File: projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx (hunk 3 above)
Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/components/gridicon/index.jsx]: I think "window" is better but would still lean towards describing the content with "search results".

**Review by bluefuton — DISMISSED** [review]
Looks good 👍 Thanks for improving this @jsnmoon!

**Review by jeherve — DISMISSED** [review]

**Comment by kraftbj** [comment]
There are various conflicts with other `instant-search` files. @jsnmoon could you take a look at that and feel free to ping me (or anyone in Crew) for a quick review once that's done so we can merge this before anything else conflicts.

**Comment by jsnmoon** [comment]
@kraftbj: Will do, thanks for the ping!

**Comment by jsnmoon** [comment]
The latest master merge brought in some prettier changes which shouldn't affect product behavior.

File: projects/packages/search/src/customberg/components/sidebar/tabs.jsx [hunk 5]
```diff
@@ -57,7 +57,9 @@ export default function Tabs( { enabledSidebarName, enableSidebar } ) {
  */
 function Tab( { enableSidebar, identifier, label, isActive } ) {
 	// translators: %s: sidebar label e.g: "Options".
-	const ariaLabel = isActive ? sprintf( __( '%s (selected)', 'jetpack-search-pkg' ), label ) : label;
+	const ariaLabel = isActive
+		? sprintf( __( '%s (selected)', 'jetpack-search-pkg' ), label )
```
Comment (jeherve) [inline projects/packages/search/src/customberg/components/sidebar/tabs.jsx:61]: Looks like you'll need to move the translator comment from above the const declaration to right before `__`, so the linter is happy and the extractor picks up the comment.

**Review by jeherve — DISMISSED** [review]

File: projects/packages/search/src/customberg/components/sidebar/tabs.jsx (hunk 5 above)
Comment (jsnmoon) [reply projects/packages/search/src/customberg/components/sidebar/tabs.jsx]: Tried moving the comment below line 60, but the linter was still complaining. So instead, I went ahead and reverted this change since it's irrelevant to this PR.

**Review by kraftbj — APPROVED** [review]
