### PR TITLE
[Boost] Fix Defer JS on short pages

### LINKED ISSUE #30008: Boost: Blank page when printing ticket in WC Box Office
### Impacted plugin

Boost

### Quick summary

WC Box Office makes a call to `exit` after including the template for printing tickets. This causes the page to be blank probably because of a buffer that is opened by Jetpack Boost which never gets outputted.

Here is the "offending" `exit`: https://github.com/woocommerce/woocommerce-box-office/blob/4b9993aa9c563c3df49b8c6a87f7cc0cd05bd8e4/includes/class-wc-box-office-ticket-frontend.php#L145

### Steps to reproduce

1. Install, activate, and configure Jetpack Boost
2. Install, activate, and configure WC Box Office
3. Purchase a ticket powered by WC Box Office
4. Try to print the said ticket (URL should look like `<domain>/my-ticket/?token=<token>&print=true`)
5. The page will now be blank instead of the ticket showing up

### A clear and concise description of what you expected to happen.

The ticket contents should show up ready for printing instead of a blank page.

### What actually happened

A blank page showed up.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by thingalon**
Fixes #30008

The Defer JS feature uses output filtering to shift scripts to the bottom of the page. PHP output buffering is handled in "chunks" - page renders typically have multiple chunks to process.

However, when a page is extremely tiny - such as when printing a ticket in Woocommerce Box Office - only one chunk gets filtered. This PR implements fixes for the output filtering code to ensure it works whether there is one chunk, or more.

## Proposed changes:
* Fix output filtering to ensure single-chunk pages get output properly.

### Other information:
- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
n/a

## Does this pull request change what data or activity we track or use?
no

## Testing instructions:
* Follow the testing instructions on https://github.com/Automattic/jetpack/issues/30008

### CODE REVIEW

File: projects/plugins/boost/app/lib/class-output-filter.php [hunk 1]
```diff
@@ -91,11 +91,18 @@ public function add_callback( $callback ) {
...
 		if ( ! $this->is_filtering ) {
 			return $buffer;
 		}
 
+		// Special case: If this is the first, last and only chunk, fake an empty 'previous' chunk to keep processing simple.
+		$is_last_chunk = ( $phase & PHP_OUTPUT_HANDLER_END ) > 0;
+		if ( $is_last_chunk && ! isset( $this->buffered_chunk ) ) {
+			$this->buffered_chunk = '';
+		}
+
```
Comment (pyronaur) [inline projects/plugins/boost/app/lib/class-output-filter.php]: How about instead always setting the `buffered_chunk` to string on class initialization?

**Review by pyronaur — COMMENTED** [review]
I'm not sure I understand how this works, perhaps a comment explaining what's going on with the special case? What exactly is bitwise doing here`($phase & PHP_OUTPUT_HANDLER_END ) > 0` ?

File: projects/plugins/boost/app/lib/class-output-filter.php (hunk 1 above)
Comment (thingalon) [reply projects/plugins/boost/app/lib/class-output-filter.php]: > What exactly is bitwise doing here `($phase & PHP_OUTPUT_HANDLER_END ) > 0` ?

I added some comments explaining, but that is the callback for PHP's output buffer. The second param ($phase) is a bitmask. I've tried to make the code clearer.

I also simplified the logic in 0953bf9562.

Comment (pyronaur) [reply projects/plugins/boost/app/lib/class-output-filter.php]: Nice! This looks much cleaner. I would still add a comment mentioning why/how the bitwise operator works and interacts with the constants, it's not every day you see those in PHP :)

Comment (thingalon) [reply projects/plugins/boost/app/lib/class-output-filter.php]: I grew up on a diet of C. I had no idea that bitwise `&` needed further explanation.

I've added a comment that explains how `$phase` works and why bitwise `&` is used. Does that cover the understanding gap?

Comment (pyronaur) [reply projects/plugins/boost/app/lib/class-output-filter.php]: 💘 Wonderful. I had my suspicion that this is something so obvious to you that you paid no attention to it at all 😄

**Review by pyronaur — APPROVED** [review]

**Comment by thingalon** [comment]
Cherry picked to 1.8.0 in [e9bd9ba](https://github.com/Automattic/jetpack/commit/e9bd9ba863a07149e13fb5120f26f02f4f03b279).

**Comment by jeherve** [comment]
Noting that this also impacts the ActivityPub plugin, as per the thread [here](https://wordpress.org/support/topic/conflict-activitypub-jetpack/). I tested and can confirm that this PR fixes the issue.

cc @pfefferle
