### PR TITLE
Premium Content Block: Added a "Remove block and keep content" and fixed to group transformation

### LINKED ISSUE #22424: Premium Content Block: Remove and Keep the Content
### Impacted plugin

Jetpack

### What

Improve the Premium Content block removal action

### How

Screenshot 2022-01-20 at 11 11 23

When removing a Premium Content block, all its content gets deleted as well.

Some users might want to only remove the "premium wrapper", for example, to give all users access to some previously paywalled content.

Let's explore if there's a way to hook into the remove/delete block function in order to perform a block transformation.

#### Note

There are probably two well defined and different user intents when _deleting_ a block (e.g. by backspacing while the block is selected), and when _removing_ it (e.g. by clicking on "remove block" from the toolbar's more menu).

My hunch would be that the former implies deleting the entire block, while the latter (especially when labelled "Remove Premium Content" as in the screenshot) could mean only removing the premium wrapper.

While working on this, let's reach out to previous owners and designers for advice.

---

This might require a Core Gutenberg change.
Let's determine how time intensive it would be before committing to it.

See: p58i-bIN-p2 (relevant part starts at around minute 10)

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
In order to avoid cases where users might want to remove the block but keep the content, we've introduced an alias block settings menu item that acts like an alias for `to core/group` transform.  Furthermore, the PR also contains a fix for `to core/group` transforms that will only move the Subscriber view content into the new group block.

Fixes #22424

#### Changes proposed in this Pull Request:

* Fixed transformation to group
* Added a new menu item only for Premium content Block called "Remove block and keep content" that, when pressed, will transform the block into a core/group. Basically, it's just an alias for to group transforms

#### Does this pull request change what data or activity we track or use?

no
#### Testing instructions:

* For Simple, apply D74487-code on your sandbox
* For Atomic, use Jetpack Beta to switch to this branch
* Go to the editor and insert a new Premium content block (an existing one would also work).
* Click block three-dot setting menu (make sure the Premium content block container is selected, it should have the Subscriber and plan information controls).
* Click on the "Remove block and keep content" menu item
* You should be able to see now that the block has been converted to a group block containing only the content from the subscriber view.
* To test the transform, revert your block back to Premium content (or add another one)
* Click on the transforms menu and select "Group"
* Notice that the block has been converted to a group with the content only from the "Subscriber view".

**Video:**

https://user-images.githubusercontent.com/995955/152653803-f38a592e-5364-432c-9a48-b236ab477578.mov

### CODE REVIEW

**Review by rcrdortiz — APPROVED** [review]

**Comment by rcrdortiz** [comment]
Tests well for me.

File: projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+ * Internal dependencies
+ */
+import { transformToCoreGroup } from './transform-to-core-group';
+import { name } from '../index';
+
+function replaceBlockAndKeepContent() {
+	const block = select( 'core/editor' ).getSelectedBlock();
+	dispatch( 'core/block-editor' ).replaceBlock(
+		block.clientId,
+		transformToCoreGroup( block.innerBlocks )
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: What do you think of not wrapping the inner blocks into a Group, but instead just spreading them into the content?
`replaceBlock` accepts an array of replacement blocks as well, so it might be as easy as:
```js
// untested code
replaceBlock( block.clientId, block.innerBlocks );
```

As the block is right now, I don't see an actual need for the Group, which might just end up complicating the UX.
Although playing devil's advocate, I guess that if we eventually add style options to the Premium Content's views, we would then need the Group in order to keep them after the removal. 🤔 

Then again, it might not be very useful? The PC views are intentionally very light, and encourage doing any stylings directly in the inner blocks.

I'm probably overthinking, but I'd love your opinion! 😄 

---

To clarify: this proposal would only affect when using the "remove and keep content" menu item; the transform to Group would obviously keep wrapping into a Group. 🙂

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: I've initially thought of this while testing. My main argument against your approach would be that if we extract the premium content and don't move it to a group block, we could not re-convert it to premium content again, or would require some work on the user's side.

Comment (dsas) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: > if we extract the premium content and don't move it to a group block, we could not re-convert it to premium content again, or would require some work on the user's side.

It's far from obvious but if you shift and click you can select multiple blocks, then choose transform to premium-content and it will wrap all selected blocks in a single premium content block.

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: > It's far from obvious but if you shift and click you can select multiple blocks, then choose transform to premium-content and it will wrap all selected blocks in a single premium content block.

That's what I meant by "would require some work on the user's side" 😄

Comment (Copons) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: I like the point that with a Group it would be trivial to transform back to PC, so let's keep the approach proposed here! 👍 

> That's what I've also observed, but it's actually a result of the group to PC transform, which is unrelated to this. I was planning to discuss it with the team before opening an issue on GH.

Feel free to open it to kickstart a conversation. ✨

Comment (BogdanUngureanu) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:17]: Actually, I just realised where the problem comes from and pushed a change that fixes it :D

File: projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+ */
+export default () => {
+	return (
+		<PluginBlockSettingsMenuItem
+			allowedBlocks={ [ name ] }
+			label="Remove block and keep content"
+			onClick={ replaceBlockAndKeepContent }
+		/>
+	);
+};
```
Comment (Copons) [inline projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:34]: We could shorten this by returning the component directly:

```es6
export default () => <PluginBlockSettingsMenuItem /* ... */ />;
```

**Review by Copons — APPROVED** [review]
LGTM!

I've left a couple of minor, non-blocking comments.
I'll pre-approve the PR, even though I'm aware the review will be dismissed when you'll push new changes. 🙂

**Review by Copons — APPROVED** [review]

File: projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+/**
+ * Register a Menu item for Removing the block and keeping the content.
+ *
+ * @returns {Element} Remove block and keep content menu item.
+ */
+export default () => (
+	<PluginBlockSettingsMenuItem
+		allowedBlocks={ [ name ] }
+		label="Remove block and keep content"
```
Comment (sdixon194) [inline projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js:29]: I could see "Remove block and keep content" seeming a bit contradictory for the average user, but I can't think of anything much more concise than that ("Change premium content to free content" or "Remove content restriction"  or something). 

I don't have a full grasp on block development, but does this section need to be flagged for translation as well?

Comment (sdixon194) [reply projects/plugins/jetpack/extensions/blocks/premium-content/_inc/remove-block-keep-content.js]: Yeah I think it's fine for now. We'll make sure to flag JPOP Quill to update docs and if we get any feedback, could always update the copy!

**Review by jeherve — APPROVED** [review]
This tests well for me. 🚢

**Comment by BogdanUngureanu** [comment]
Deployed on WPCOM with r239921-wpcom
