### PR TITLE
Search: Fix infinite scroll in Customberg

### LINKED ISSUE #20970: Search: Infinite Scroll Not Working in Preview
### Impacted plugin

Jetpack

### Steps to Reproduce

When going to edit the Jetpack Search using the Gutenberg customization, there's an option to enable infinite scroll. However this doesn't change anything in the preview.

Further digging revealed it didn't seem to work whether it was enabled or disabled, nor did it just work for the theme either (Twenty-Twenty One). Is infinite scroll behavior dependent on theme support? 

### A clear and concise description of what you expected to happen.

Infinite scroll to work, or if it's dependent on theme support, an indication that it will only work if the theme supports it.

### What actually happened

No infinite scroll behavior or notice about when that condition is supported.

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #20970.

#### Changes proposed in this Pull Request:
* Changes nesting of elements to enable infinite scrolling within Customberg.
* Begins deprecating styles copied over from the `@wordpress/interface` package.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
* Apply this change to your site with a Jetpack Search subscription.
* Navigate to Customberg (`/wp-admin/admin.php?page=jetpack-search-configure`) and try interacting with the infinite scroll functionality in the preview.
* Ensure that the infinite scroll functionality works as expected in Customberg.
* Ensure that the mobile-friendly breakpoints work as expected in the Instant Search preview within Customberg.
* Ensure that the infinite scroll functionality continues to work as expected for the site (`?s=some search`).

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/components/scroll-button.jsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ class ScrollButton extends Component {
 	checkScroll = debounce( () => {
 		if (
 			this.props.enableLoadOnScroll &&
-			window.innerHeight + this.overlayElement.scrollTop === this.overlayElement.scrollHeight
+			window.innerHeight + this.overlayElement.scrollTop >= this.overlayElement.scrollHeight
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/instant-search/components/scroll-button.jsx:29]: 👍

File: projects/plugins/jetpack/modules/search/customberg/components/app-wrapper/index.jsx [hunk 2]
```diff
@@ -74,7 +74,14 @@ export default function AppWrapper() {
 	const { isLoading } = useSiteLoadingState();
 
 	return (
-		<div className="jp-search-configure-app-wrapper">
+		<div
+			/* translators: accessibility text for the widgets screen content landmark region. */
+			aria-label={ __( 'Jetpack Search customization preview', 'jetpack' ) }
+			className="jp-search-configure-app-wrapper"
+			// className="interface-interface-skeleton__content"
```
Comment (kangzj) [inline projects/plugins/jetpack/modules/search/customberg/components/app-wrapper/index.jsx:81]: probably we'd want to remove the commented line.

**Review by kangzj — DISMISSED** [review]
Well done. This works well and looks good to me 👍

File: projects/plugins/jetpack/modules/search/customberg/components/app-wrapper/index.jsx (hunk 2 above)
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/customberg/components/app-wrapper/index.jsx:81]: Ah, good catch!

**Review by jeherve — APPROVED** [review]

**Comment by jsnmoon** [comment]
🚢 r232814-wpcom
