### PR TITLE
Fix: Removal of widget DOM element following acceptance of cookie policy

### LINKED ISSUE #11311: Cookie widget container blocks underlying elements after being dismissed
#### Steps to reproduce the issue

1. Open https://2019.laspalmasgc.wordcamp.org/programa-schedule/
2. Dismiss the cookie banner
1. Find the `.show-email-form` element in your browser's element inspector (under `.entry-content`), and disable the `z-index: 50002;` rule. I added that rule to work around this bug, so you'll need to disable it in order to reproduce the bug.
3. Click on one of the ⭐️ icons in the schedule. A new fixed-position element will appear in the bottom-right hand corner of the screen, containing ⭐️ and ✉️ icons.
4. Try to click on that new element, nothing will happen.
5. Right-click on the element and inspect it, you'll see that `.widget_eu_cookie_law_widget` is sitting on top of it.

x-ref: https://wordpress.slack.com/archives/C08M59V3P/p1549564933216200

#### What I expected

When a user clicks the button to dismiss the widget, all of its DOM elements should be removed.

#### What happened instead

`#eu-cookie-law` is removed, but the `.widget_eu_cookie_law_widget` container remains, with `display: block`, `position: fixed`, etc. 

If Another element is also fixed to a similar position, then it can become inaccessible, with an invisible element sitting on top of it. The user won't know why they can't click on it, only that nothing happens when they try.

**Screenshots**

screen shot 2019-02-08 at 10 39 54 am 2

### PR DESCRIPTION
**Pull request by tonytettinger**
Fixes #11311

#### Changes proposed in this Pull Request:
* The described expected behavior is the removal of the invisible element from the DOM that stays behind after the users click on the accept button. To achieve this, I have added code responsible for removing this element in the accept function of the widget. I've placed it under the function that is responsible to fade out the element gradually to keep the smooth transition.

#### Testing instructions:

* Add the Cookies & Consents Banner (Jetpack) widget to the site.
* Click on the Accept button and observe the gradual disappearance of the widget wrapper.
* Check that the site functions as expected and inspect the DOM to verify that the invisible wrapper (.widget_eu_cookie_law_widget) is removed.

eucookie1
eucookie2

#### Proposed changelog entry for your changes:
* None required

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]
Nice. I appreciate this update.

File: modules/widgets/eu-cookie-law/eu-cookie-law.js [hunk 1]
```diff
@@ -58,6 +58,8 @@
 
 		overlay.fadeOut( 400, function() {
 			overlay.remove();
+			var widgetSection = document.querySelector(".widget.widget_eu_cookie_law_widget");
+			widgetSection.parentNode.removeChild(widgetSection);
```
Comment (simison) [inline modules/widgets/eu-cookie-law/eu-cookie-law.js]: A minor nitpick but just noting that since this file uses jQuery, this would've been enough. 🙃 

```js
$( '.widget.widget_eu_cookie_law_widget' ).remove();
```
