### PR TITLE
Form block: fix 0 value options

### LINKED ISSUE #17866: Form Block: Select elements with option value 0 do not render
#### Steps to reproduce the issue

1. Create a new page
2. Add a form block
3. Insert a Select element to the form
4. Enter a few options with values 0, 1, 2
5. Publish page
6. View page and see the option with value 0 does not appear

#### What I expected
I would expect the 0 option to appear in the list as well

#### What happened instead
All other options render in the select element but the 0 option does not.

**Screenshots**

### LINKED ISSUE #24885: Form block: checkbox group doesn't display item with option set to 0
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Create a new post and add a form to it.
2. Add a checkbox group with several options.
3. View the post. 

### A clear and concise description of what you expected to happen.

Option with value 0 should show up.

### What actually happened

The option is missing.

### Other information

When adding the single checkbox, the problem doesn't appear.
Screen Shot on 2022-06-29 at 14-06-52
Screen Shot on 2022-06-29 at 14-01-11

### Reproducibility

Consistent

### Severity

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by bindlegirl**
Fixes #24885
Fixes #17866

Options with value set to 0 in radio, select, and multiple checkbox fields don't show up as PHP interprets it as falsey value. I changed the condition to use the is_string instead so 0 and blank values can be displayed.

#### Changes proposed in this Pull Request:

* Changed `if ( $option )` to ` is_string( $option )`. 
* I was thinking if maybe we should prevent options with blank value to show up but if we want to do that, I think we should fix it from saving side instead.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

no

#### Testing instructions:

* Create a post and add a form block.
* Add some select, radio and multiple checkbox fields and add 0 as an option.
* Before this patch is applied, 0 options won't show up. After it's applied it should.

### CODE REVIEW

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php [hunk 1]
```diff
@@ -4294,7 +4294,7 @@ public function render_radio_field( $id, $label, $value, $class, $required, $req
 		$field = $this->render_label( '', $id, $label, $required, $required_field_text );
 		foreach ( (array) $this->get_attribute( 'options' ) as $option_index => $option ) {
 			$option = Grunion_Contact_Form_Plugin::strip_tags( $option );
-			if ( $option ) {
+			if ( is_string( $option ) ) {
```
Comment (anomiex) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: I wonder if we should add a `&& $option !== ''` in here (and below). Do we want to start allowing empty-string as an option too, or just zero?

Comment (bindlegirl) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: I was thinking about that. The reason I didn't add that is that I think we shouldn't allow saving options like that if we don't want to render them. Right now nothing seems to stop users from saving stuff like this:
Screen Shot on 2022-07-01 at 14-32-11

Comment (bindlegirl) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: Then again, maybe some users are already counting on blank entries not showing up so making sure they don't would be a good idea.

Comment (bindlegirl) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: Changed in https://github.com/Automattic/jetpack/pull/24926/commits/d178061864752a18fdd136e55c85b2851cfca5ba

**Review by anomiex — APPROVED** [review]
Let's do it!

**Comment by bindlegirl** [comment]
r248355-wpcom

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-11.1` in 2e4905ab7eee63dbc3268f216b3a234db4026df2
