### PR TITLE
VideoPress: Fix app breaking when deleting last page video.

### LINKED ISSUE #27772: VideoPress: Library breaks when deleting a video on a page other than the first
Steps to reproduce:
1 - Add enough videos to have at least 2 pages
2 - Go to the 2nd page
3 - Delete all videos from the page

When deleting the last video of the page, the current page should be decreased by one, instead it is not and an error is thrown:

https://user-images.githubusercontent.com/8486249/205940468-05c49166-750b-48ca-8b86-5360e5715a4c.mp4

### PR DESCRIPTION
**Pull request by renatoagds**
Closes #27772 

## Proposed changes:

* Allow pushing `page` changes into store without pushing back to URL page.
* Reduce the page on `REMOVE_VIDEO` action if needed.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Spawn a JN site with `VideoPress`.
* Upload 7 videos to have a second page.
* Delete the second-page video.
* You should be redirected to the first page.
* _Try the same with more pages_

### CODE REVIEW

File: projects/packages/videopress/src/client/admin/components/admin-page/index.tsx [hunk 1]
```diff
@@ -82,9 +86,18 @@ const useDashboardVideos = () => {
...
+			if ( page !== tempPage.current ) {
+				tempPage.current = page;
+				searchParams.setParam( 'page', page );
+				searchParams.update();
+			} else {
+				tempPage.current = pageFromSearchParam;
+				setVideosQuery( {
+					page: pageFromSearchParam,
+				} );
+			}
```
Comment (renatoagds) [inline projects/packages/videopress/src/client/admin/components/admin-page/index.tsx:100]: About this one, we need to be aware of the same thing at https://github.com/Automattic/jetpack/issues/26720 to allow updating the field from the store and getting it reflected in the URL.

cc/ @lhkowalski

File: projects/packages/videopress/src/client/state/reducers.js [hunk 2]
```diff
@@ -243,8 +243,18 @@ const videos = ( state, action ) => {
...
+			const lastVideo = items?.length === 1;
+			const currentPage = query?.page ?? 1;
+			const page = lastVideo && currentPage > 1 ? currentPage - 1 : currentPage;
+
 			return {
 				...state,
+				query: {
+					...query,
+					page,
+				},
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/state/reducers.js]: The total pages could be decreased by one as well, to adjust the paginator.

**Review by dhasilva — APPROVED** [review]
LGTM!
