### PR TITLE
Contact Form Block: Displays expected success message when used in FSE template, FSE template part, or widget block

### LINKED ISSUE #24519: Contact Form Block: No Confirmation on Sidebar/FSE
### Impacted plugin

Jetpack

### Steps to Reproduce

- Add a contact form block to a sidebar, or anywhere on a FSE theme
- Submit the form
- See the page refresh, but no confirmation message that the form was sent successfully. 

Note that the form does indeed send and appears in Feedback

### A clear and concise description of what you expected to happen.

A success message upon submitting the form.			

### What actually happened

The page just refreshed.

### Other information

_No response_

### Operating System

macOS

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by danielbachhuber**
Refactors Contact Form Block generation and processing so that the expected success message displays when the block is used in a FSE template, FSE template part, or block widget.

See https://github.com/Automattic/wp-calypso/issues/60774
See https://github.com/Automattic/wp-calypso/issues/62431

### Proposed changes

The refactor follows a pattern similar to how the Contact Form Widget special-case is handled.

For block templates:
1. `$_wp_current_template_content` is filtered on `template_include` to add a `block_template=canvas` attribute to all contact form blocks in the block template.
2. The `Grunion_Contact_Form` class interprets the `block_template` attribute accordingly when present.
3. The `::process_form_submission()` method properly interprets `contact-form-id=canvas`. It has to hackily reproduce part of `wp-includes/template-loader.php` in order to hydrate `$_wp_current_template_content`(because `$_wp_current_template_content` needs to be rendered in order to populate `Grunion_Contact_Form::$last`.

For block template parts:
1. The `$GLOBALS['grunion_block_template_part_id']` global variable is set when the `wp:core/template-part` block is rendered.
4. If the `$GLOBALS['grunion_block_template_part_id']` is set when the contact form block is rendered, a `block_template_part=<part-id>` attribute is added to the block attributes.
5. The `Grunion_Contact_Form` class interprets the `block_template_part` attribute accordingly when present.
6. The `::process_form_submission()` method properly interprets `contact-form-id=block-template-part-<part-id>`.

For block widgets:
1. `widget_block_content` is filtered to apply `widget=<widget-id>` as an attribute to each block within the block widget.
2. The rest of the existing logic for widgets is reused.

### Does this pull request change what data or activity we track or use?

No.

### Testing instructions

To test the block _template_ integration:

1. Activate a FSE theme (Twenty Twenty-Two is a good one).
2. Add a Contact Form Block to the Single Template.
3. Change "On Submission" to "Show a custom text message". Write a custom text message.
4. Navigate to an individual blog post.
5. Submit the Contact Form Block.
6. Observe your custom success message in the Contact Form Block.
7. Return to Full Site Editor and change your Contact Form Block to use "Show a summary of submitted fields".
8. Navigate to an individual blog post.
9. Submit the Contact Form Block.
10. Observe your submitted fields in the Contact Form block.

image

image

To test the block _template part_ integration:

1. Activate a FSE theme (Twenty Twenty-Two is a good one).
2. Add a Contact Form Block to the Footer template part.
3. Change "On Submission" to "Show a custom text message". Write a custom text message.
4. Navigate to the footer on the frontend.
5. Submit the Contact Form Block.
6. Observe your custom success message in the Contact Form Block.
7. Return to Full Site Editor and change your Contact Form Block to use "Show a summary of submitted fields".
8. Navigate to the footer on the frontend.
9. Submit the Contact Form Block.
10. Observe your submitted fields in the Contact Form block.

image

image

To test the _widget block_ integration:

1. Activate a legacy theme (Twenty Twenty is a good one).
2. Add a Contact Form Block to a block editor-enabled sidebar.
3. Change "On Submission" to "Show a custom text message". Write a custom text message.
4. Navigate to the sidebar on the frontend.
5. Submit the Contact Form Block.
6. Observe your custom success message in the Contact Form Block.
7. Return to widgets in the backend and change your Contact Form Block to use "Show a summary of submitted fields".
8. Navigate to the sidebar on the frontend.
9. Submit the Contact Form Block.
10. Observe your submitted fields in the Contact Form block.

image

image

### CODE REVIEW

**Comment by wojtekn** [comment]
@danielbachhuber I tested it on my sandbox after synchronizing the `grunion-contact-form.php` file from the Jetpack repository to my sandbox. I couldn’t make it work and was still reproducing the bug. In my case, `contact-form-id` is set to an integer each time. I found out that `render_block_core_template_part_post` is never triggered. I was adding a form as a block to one of the widget areas. I was using the Blask theme.

Then I reread the testing instructions and realized I should use FSE to place the form in the footer. I changed the theme to Twenty Twenty Two and used FSE to add a form as a block into the home page footer, and I still couldn’t make it work. It seems that `grunion_contact_form_set_block_template_part_id_global` is still not executed.

Any idea what I’m doing wrong here? I understand how you approach that. However, I still miss some context on how to run this particular use case.

**Comment by sejas** [comment]
@wojtekn @danielbachhuber here is the diff related to this PR: D82492-code , I've also tested it using the sandbox, and I can confirm that the issue is still there for simple sites.

I think #62431 is a dup of #60774, we should close one of them.

**Comment by sejas** [comment]
I've tested it on an external jetpack site, and it works for `template parts` such as the _header_ and _footer_. But it doesn't work in `templates` like _single_ or _home_.

Maybe the issues are very similar but not the same after all.

Screenshot of templates vs template parts.
Screenshot 2022-06-14 at 15 43 44

**Comment by danielbachhuber** [comment]
@wojtekn @sejas Thanks for your testing! I addressed FSE templates with e694eb3e0bc7c858c84487a56f291efba4c3c565 and block widgets with 4566a763e196b37eee21fab5ac8cc90fda31ab45

Still need to test the wpcom diff. I'll re-flag for review after I've done so.

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php [hunk 1]
```diff
@@ -27,6 +27,115 @@ function grunion_contact_form_require_endpoint() {
 	require_once GRUNION_PLUGIN_DIR . 'class-grunion-contact-form-endpoint.php';
 }
 
+/**
+ * Sets the 'block_template' attribute on all instances of wp:jetpack/contact-form in
```
Comment (wojtekn) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:31]: Would it make sense to add a comment to each block to say which way of adding a form it fixes clearly?

**Review by wojtekn — COMMENTED** [review]
@danielbachhuber I've checked the diff on my wpcom sandbox and it looks as follows:

* FSE, Site: works fine
* FSE, Templates (used Single Post template): works fine
* FSE, Template Parts (used Footer part): doesn't work 
* widget on the classic theme (used Blask theme): works fine

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php (hunk 1 above)
Comment (danielbachhuber) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:31]: > Would it make sense to add a comment to each block to say which way of adding a form it fixes clearly?

I think so! Great suggestion 😄 Added with 0434b8c6f01a412445779e86aeef0422c2f83f0b

**Comment by danielbachhuber** [comment]
@wojtekn @sejas Fortunately, a simple solution for dotcom (and Gutenberg plugin) compatibility: d247ddadc36371a1ff2583269fea371355839b2d

😅

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php [hunk 2]
```diff
@@ -2239,6 +2422,16 @@ public function __construct( $attributes, $content = null ) {
...
+		} elseif ( ! empty( $attributes['block_template'] ) && $attributes['block_template'] ) {
+			$default_to      .= get_option( 'admin_email' );
+			$attributes['id'] = 'block-template-' . $attributes['block_template'];
+			// translators: the blog name.
+			$default_subject = sprintf( _x( '%1$s Block Template', '%1$s = blog name', 'jetpack' ), $default_subject );
+		} elseif ( ! empty( $attributes['block_template_part'] ) && $attributes['block_template_part'] ) {
+			$default_to      .= get_option( 'admin_email' );
+			$attributes['id'] = 'block-template-part-' . $attributes['block_template_part'];
+			// translators: the blog name.
+			$default_subject = sprintf( _x( '%1$s Block Template Part', '%1$s = blog name', 'jetpack' ), $default_subject );
```
Comment (sejas) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2434]: It would be great if we can modify the title a little bit to keep the old context.

I can see that the user loses context from which page was sent the message.

`/wp-admin/edit.php?post_type=feedback`

In my example, it was saying: `Site Title] Hello World!` before the fix.
After the fix it says: `[Site Title] Block Template` or `[Site Title] Block Template Part`

Screenshot 2022-06-15 at 15 49 24

**Review by sejas — DISMISSED** [review]
@danielbachhuber The PR looks great.
I've tested it and it's working in every case: on simple sites, atomic sites, jetpack sites with the form inside the templates and also in template parts.

Great work!!

I've added a suggestion about showing a different title on the Form Responses page.

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php (hunk 2 above)
Comment (danielbachhuber) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2434]: > It would be great if we can modify the saved title to keep the context.

That would be a great improvement 😄 

Unfortunately, I don't know of a good way to identify a _name_ for the context (aside from inventing our own system). Do you know of any ways? Alternatively, maybe there's a more generic title we could use?

Comment (danielbachhuber) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2434]: > What if we remove `$default_subject` from all those conditions and then use this below?

While we'd have a blog post title, it may or may not be accurate:
* On the homepage, `$post` would be the last post in the main query, unless...
* Anywhere there's a `WP_Query` immediately before the contact form, `$post` would be the last post in that query.

Comment (wojtekn) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2434]: @danielbachhuber isn't it how it worked before the change? I've roughly tested that case and it was not using the last post, but the homepage's main $post.

Comment (danielbachhuber) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: > isn't it how it worked before the change? I've roughly tested that case and it was not using the last post, but the homepage's main `$post`.

@wojtekn Oh, fair enough. I've restored the prior (somewhat inaccurate) behavior for all contexts with 888a8ad8fd. Here's what it looks like:

image

**Review by sdixon194 — APPROVED** [review]
Did some extensive testing on this one and everything worked well! Noting that this fixes https://github.com/Automattic/jetpack/issues/24519

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php (hunk 2 above)
Comment (wojtekn) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: @danielbachhuber it looks solid and works well for me in all cases now.

**Review by wojtekn — APPROVED** [review]

**Review by sejas — APPROVED** [review]

**Comment by sejas** [comment]
r247680-wpcom

**Comment by jeherve** [comment]
Nice work! I was hoping this would also fix https://github.com/Automattic/jetpack/issues/22749 so we wouldn't need something like #24701, but I still see the problem on `trunk` right now. Do you think you could take a look at it?

Thanks!

**Comment by danielbachhuber** [comment]
@jeherve I've assigned myself #22749 to take a look.
