### PR TITLE
VideoPress: Replace video uploads in Gutenberg

### LINKED ISSUE #11194: VideoPress: allow users to upload videos from Gutenberg [2]
#### Steps to reproduce the issue

0. Start from a Jetpack site with an active Professional upgrade.
1. Go to Jetpack > Settings, and enable the VideoPress feature.
2. Go to Post > Add new.
3. Insert a video block.
4. Upload a video using the "Upload" button.
5. Save / publish / discard the post.
6. Go to Media > Library and check the video previously uploaded.

#### What I expected
The video is processed by VideoPress.
screen shot 2019-01-24 at 15 42 33

#### What happened instead
The video has not been processed by VideoPress.
screen shot 2019-01-24 at 15 42 13

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/jetpack/issues/11194

#### Changes proposed in this Pull Request:
Load an API fetch middleware in the block editor that overrides the video uploads in Gutenberg so they are uploaded against the WP.com API media endpoint and thus transcoded by VideoPress.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
Improve VideoPress (paYKcK-f0-p2, p9dueE-xm-p2).

#### Testing instructions:
- Apply D33658-code and sandbox the API.
- Apply this branch to your JP dev environment.
- Start from a Jetpack site with an active Professional upgrade.
- Go to Jetpack > Settings in your dashboard, and enable the VideoPress feature.
- Load the block editor.
- Insert a video block.
- Upload a video using the "Upload" button (not the "Media Library" one).
- Check the VideoPress player is rendered on the editor.
- Publish the post.
- Check the VideoPress player is rendered on the published view.
- Deactivate VideoPress.
- Load the block editor again.
- Make sure the `gutenberg-video-upload.js` script is not enqueued.
- Sandbox a WP.com site and load the block editor.
- Make sure the `gutenberg-video-upload.js` script is not enqueued on the WP.com site.

#### Proposed changelog entry for your changes:
VideoPress: Replace video uploads in Gutenberg

### CODE REVIEW

**Comment by mmtr** [comment]
This is not working currently due to a CORS error when making the request to the WP.com media endpoint:

```
Access to fetch at 'https://public-api.wordpress.com/rest/v1.1/sites/<SITE_ID>/media/new?_locale=user' from origin '<JP_SITE>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is 'false' which must be 'true' when the request's credentials mode is 'include'.
```

**Comment by mmtr** [comment]
> ```
> Access to fetch at 'https://public-api.wordpress.com/rest/v1.1/sites/<SITE_ID>/media/new?_locale=user' from origin '<JP_SITE>' has been blocked by CORS policy: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
> ```

This has been solved in D33658-code by allowing the `X-WP-Nonce` header in the CORS requests.

**Comment by mmtr** [comment]
The request is returning now a 400 error because the endpoint [expects the data in a different format](https://github.com/Automattic/jetpack/blob/170f4992fd830ea00f6ab4733ac637c1fb7440fc/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php#L59-L63), so the middleware should change how the file is included in the payload.
Gutenberg also expects the returned data by the endpoint in a [different format](https://github.com/WordPress/gutenberg/blob/d9b232d1d15db418d22db89c53626542a8efd654/packages/editor/src/utils/media-upload/media-upload.js#L173-L178) so the middleware should parse and format the response.

**Comment by kwight** [comment]
FWIW, yep, this is what I get (with all of the expected pieces already in place 👍

File: modules/videopress/class.videopress-gutenberg.php [hunk 1]
```diff
@@ -164,6 +165,28 @@ public function render_video_block_with_videopress( $attributes, $content ) {
...
 	}
+
+	/**
+	 * Replaces the video uploaded in the block editor.
+	 *
+	 * Enqueues a script that registers an API fetch middleware replacing the video uploads in Gutenberg so they are
+	 * uploaded against the WP.com API media endpoint and thus transcoded by VideoPress.
+	 */
+	public function override_video_upload() {
+		if (
```
Comment (kwight) [inline modules/videopress/class.videopress-gutenberg.php]: Can we also make this conditional on it being a REST API request, and bail early on the failure instead? I think we can use `REST_REQUEST` here. That way, the script isn't unnecessarily loaded in other contexts.

File: modules/videopress/class.videopress-gutenberg.php [hunk 2]
```diff
@@ -164,6 +165,28 @@ public function render_video_block_with_videopress( $attributes, $content ) {
...
+			method_exists( 'Jetpack', 'is_active' ) && Jetpack::is_active()
```
Comment (kwight) [inline modules/videopress/class.videopress-gutenberg.php]: Is this line necessary? Wouldn't the `is_module_active` check be enough?

File: modules/videopress/class.videopress-gutenberg.php (hunk 1 above)
Comment (mmtr) [reply modules/videopress/class.videopress-gutenberg.php]: Uhm, we need to load this script on the WP Admin editor, not on an API context. This is a JS file that will intercept any `wp.apiFetch` call to `/wp/v2/media` and swap it out to `public-api.wordpress.com/rest/v1.1/media/new`.

File: modules/videopress/class.videopress-gutenberg.php (hunk 2 above)
Comment (mmtr) [reply modules/videopress/class.videopress-gutenberg.php]: You're right! I simplified the checks in 9d75857

**Comment by mmtr** [comment]
> The request is returning now a 400 error because the endpoint [expects the data in a different format](https://github.com/Automattic/jetpack/blob/170f4992fd830ea00f6ab4733ac637c1fb7440fc/json-endpoints/class.wpcom-json-api-upload-media-v1-1-endpoint.php#L59-L63), so the middleware should change how the file is included in the payload.
> Gutenberg also expects the returned data by the endpoint in a [different format](https://github.com/WordPress/gutenberg/blob/d9b232d1d15db418d22db89c53626542a8efd654/packages/editor/src/utils/media-upload/media-upload.js#L173-L178) so the middleware should parse and format the response.

Solved both problems in 7682948 and ff0194b, so this is now ready to review.

**Review by jeherve — COMMENTED** [review]
**Edit: my bad, I forgot to apply the related diff. I'll try again, but I'll read the instructions this time, sorry!**

I get this error when I try to upload a video:

```
Access to fetch at 'https://public-api.wordpress.com/rest/v1.1/sites/164776955/media/new?_locale=user' from origin 'http://my.localsite' has been blocked by CORS policy: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
Uncaught (in promise) TypeError: Cannot read property 'code' of undefined
    at http://my.localsite/wp-content/plugins/gutenberg/build/api-fetch/index.js?ver=e20b1c8bba67f2198e1cfae53eac80c5:formatted:365
```

I don't get any feedback in the editor though; everything happens in the console and the editor seems to be stuck on uploading:
image

File: modules/videopress/class.videopress-gutenberg.php [hunk 3]
```diff
@@ -164,6 +165,32 @@ public function render_video_block_with_videopress( $attributes, $content ) {
...
+		}
+
+		// Bail if Jetpack or VideoPress is not active.
+		if ( ! Jetpack::is_active() || ! Jetpack::is_module_active( 'videopress' ) ) {
+			return;
+		}
+
+		wp_enqueue_script(
+			'jetpack-videopress-gutenberg-override-video-upload',
+			plugin_dir_url( __FILE__ ) . 'js/gutenberg-video-upload.js',
```
Comment (jeherve) [inline modules/videopress/class.videopress-gutenberg.php]: I think you could enqueue the minified version in prod environments, like so:

```diff
diff --git a/modules/videopress/class.videopress-gutenberg.php b/modules/videopress/class.videopress-gutenberg.php
index 156945c69..0b325b35e 100644
--- a/modules/videopress/class.videopress-gutenberg.php
+++ b/modules/videopress/class.videopress-gutenberg.php
@@ -5,6 +5,8 @@
  * @package Jetpack
  */
 
+use Automattic\Jetpack\Assets;
+
 /**
  * Register a VideoPress extension to replace the default Core Video block.
  */
@@ -185,7 +187,10 @@ class VideoPress_Gutenberg {
 
 		wp_enqueue_script(
 			'jetpack-videopress-gutenberg-override-video-upload',
-			plugin_dir_url( __FILE__ ) . 'js/gutenberg-video-upload.js',
+			Assets::get_file_url_for_environment(
+				'_inc/build/videopress/js/gutenberg-video-upload.min.js',
+				plugin_dir_url( __FILE__ ) . 'js/gutenberg-video-upload.js'
+			),
 			array( 'wp-api-fetch', 'wp-polyfill', 'lodash' ),
 			JETPACK__VERSION,
 			false

```

**Review by jeherve — CHANGES_REQUESTED** [review]
This works a lot better when I follow instructions! :)

I would have a remark to load a minified file when possible.

File: modules/videopress/class.videopress-gutenberg.php [hunk 4]
```diff
@@ -164,6 +165,32 @@ public function render_video_block_with_videopress( $attributes, $content ) {
...
+
+	/**
+	 * Replaces the video uploaded in the block editor.
+	 *
+	 * Enqueues a script that registers an API fetch middleware replacing the video uploads in Gutenberg so they are
+	 * uploaded against the WP.com API media endpoint and thus transcoded by VideoPress.
+	 */
+	public function override_video_upload() {
+		// Bail if WP.com site.
+		if ( defined( 'IS_WPCOM' ) && IS_WPCOM ) {
```
Comment (kwight) [inline modules/videopress/class.videopress-gutenberg.php]: @jeherve do we still do this? It's to be avoided at all costs in my mind (but I don't remember why).

Comment (jeherve) [reply modules/videopress/class.videopress-gutenberg.php]: Yeah, that's okay. When possible we try to skip it (by using filters for example), but we still use this constant quite a bit in Jetpack.

File: modules/videopress/class.videopress-gutenberg.php (hunk 3 above)
Comment (mmtr) [reply modules/videopress/class.videopress-gutenberg.php]: Changed in fbbfb53

File: modules/videopress/class.videopress-gutenberg.php (hunk 4 above)
Comment (mmtr) [reply modules/videopress/class.videopress-gutenberg.php]: > When possible we try to skip it 

In that case, let's avoid it :) I added to D33658-code the filter removal @kwight developed in D33744-code?id=123028, and removed the WP.com bail in 813a173

**Review by jeherve — APPROVED** [review]
This looks good to me, it tests well. That's improving the VideoPress experience so much, too ❤️

**Review by gwwar — APPROVED** [review]
Nice work @mmtr! This tests well with both the upload button and drag-and-drop uploads. I also verified that the script was not loaded when VideoPress was disabled in settings.

Oct-10-2019 15-55-37
