### PR TITLE
Forms: Fix redirect field styles

### LINKED ISSUE #41022: Forms: URL redirect field too large
URL redirect field makes sidebar scroll horizontally:

Image

It should instead fit within the sidebar.

### PR DESCRIPTION
**Pull request by ntsekouras**
Fixes: https://github.com/Automattic/jetpack/issues/41022

This PR fixes some styles with the redirect address field. Additionally I updated a bit the styles for the suggestions to have smaller width.

## Testing instructions:
1. insert a contact form
2. in Inspector controls under `Submission settings`, go to `on submission` and select `Redirect to another webpage`.
3. Observe that the input width is correct
4. Type something for some suggestions to show
5. Observe the smaller width of the dialog.

Before     | After
:-------------------------:|:-------------------------:
before | after

### CODE REVIEW

File: projects/packages/forms/src/blocks/contact-form/edit.js [hunk 1]
```diff
@@ -198,18 +197,14 @@ export const JetpackContactFormEdit = forwardRef(
 					) }
 
 					{ 'redirect' === customThankyou && (
-						<BaseControl
```
Comment (ntsekouras) [inline projects/packages/forms/src/blocks/contact-form/edit.js:201]: `URLInput` is already wrapped with [BaseControl](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-input/index.js#L475). Unfortunately the `div` wrapper is still needed because we can't pass a `ref` to `URLInput`'s Popover` to anchor properly.

File: projects/packages/forms/src/blocks/contact-form/editor.scss [hunk 2]
```diff
@@ -240,12 +240,16 @@
...
+	min-width: auto;
+}
+
 .jetpack-contact-form__thankyou-redirect-url input[type='text'] {
 	width: 100%;
 }
 
 .jetpack-contact-form__thankyou-redirect-url__suggestions {
-	width: 260px;
+	width: 230px;
```
Comment (simison) [inline projects/packages/forms/src/blocks/contact-form/editor.scss:252]: I'm always little nervous about fixed widths — the previous version with 260px already broke. Fine by me if `width: auto`, `max-width: 230px` etc didn't help here.

**Review by simison — APPROVED** [review]
I have not tested but code looks good. Can you also double check mobile-web version to ensure all is good there too?

File: projects/packages/forms/src/blocks/contact-form/editor.scss [hunk 3]
```diff
@@ -240,12 +240,16 @@
 	width: 100%;
 }
 
+.jetpack-contact-form__thankyou-redirect-url {
+	min-width: auto;
```
Comment (ntsekouras) [inline projects/packages/forms/src/blocks/contact-form/editor.scss:244]: This overrides core styles: https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-input/style.scss#L13. This should be handled in GB because it seems we cannot use `URLInput` in Inspector controls properly.

Comment (simison) [reply projects/packages/forms/src/blocks/contact-form/editor.scss:244]: Worth opening a github issue describing what is needed?

File: projects/packages/forms/src/blocks/contact-form/editor.scss (hunk 2 above)
Comment (ntsekouras) [reply projects/packages/forms/src/blocks/contact-form/editor.scss:252]: > Can you also double check mobile-web version to ensure all is good there too?

It is still a bit problematic, but as I [mentioned below](https://github.com/Automattic/jetpack/pull/41030#discussion_r1914718382):
>it seems we cannot use URLInput in Inspector controls properly.

That component actually hides the [suggestions on mobile](https://github.com/WordPress/gutenberg/blob/trunk/packages/block-editor/src/components/url-input/style.scss#L44).

File: projects/packages/forms/src/blocks/contact-form/editor.scss (hunk 3 above)
Comment (ntsekouras) [reply projects/packages/forms/src/blocks/contact-form/editor.scss:244]: Done: https://github.com/WordPress/gutenberg/issues/68659.
