### PR TITLE
Fix Launchpad copy typo for Adding subscribers

### LINKED ISSUE #99816: Task: Address feedback from the demo call
### Standardize the CTAs for domain Upsell

Image

### “Skip to dashboard” is a link, but it doesn’t look like one

Image

### Related

_No response_

### PR DESCRIPTION
**Pull request by paulopmt1**
Task-related: https://github.com/Automattic/wp-calypso/issues/99816

## Proposed changes:

* Fixing typo `Add your first subscribers` and updating it to `Add subscribers` as it is more used across the interfaces

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

This came from today-s Self-serve demo call

## Does this pull request change what data or activity we track or use?
no

## Testing instructions:

* Apply this code to your sandbox
* Go to /setup/onboarding and create a site with a `Blog` intent
* On Launchpad, ensure you're seeing the new copy:

| Before | After |
|--------|--------|
|image | image| 

Note that it's similar to the copy we have when clicking on that step:

image

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php [hunk 1]
```diff
@@ -676,7 +676,7 @@ function wpcom_launchpad_get_task_definitions() {
 			// We do not want this mapped to the 'subscribers_added' task, since this task supports
 			// being marked as complete in situations where subscribers are not added.
 			'get_title'            => function () {
-				return __( 'Add your first subscribers', 'jetpack-mu-wpcom' );
+				return __( 'Add subscribers', 'jetpack-mu-wpcom' );
```
Comment (paulopmt1) [inline projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php:679]: We already have [a translation for Add subscribers](https://translate.wordpress.com/projects/wpcom/es/default?filters%5Bterm%5D=Add+subscribers&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc).

**Review by zaguiini — APPROVED** [review]
