### PR TITLE
Instagram oEmbed: Simplify

### LINKED ISSUE #12918: Unit-tests: Instagram tests are failing on WP master
Build example: https://travis-ci.org/Automattic/jetpack/jobs/553243484

These failures seem like related to the recent changes in core. we should investigate these, and update our code/tests

We also should enable these tests too (revert https://github.com/Automattic/jetpack/pull/12919)

#### Steps to reproduce the issue

1. Run `test-class.instagram.php` in CI. see WP Master job is failing

### PR DESCRIPTION
**Pull request by ockham**
Rely on Core's `oEmbed` mechanisms, rather than adding our own embed handler.

Supersedes #11063.
Fixes #12918.
_Possibly_ fixes some other Instagram embed related issues (since this removes our custom embed handler in favor of Core tooling)? Like maybe #16752, #16753, #9331? 

#### Changes proposed in this Pull Request:
- Implement the first (and most crucial) part of pc9Uba-6d-p2: Remove `jetpack_instagram_handler` in favor of Core's own oEmbed system (which, among other things, gives us embed caching for free), while adding
  - a new `jetpack_instagram_oembed_oembed_fetch_url` filter (hooked into `oembed_fetch_url`) to
    - remove any query args from the embed URL (see #17428) and
    - add the now-required auth token for Instagram's oEmbed REST API if present, or redirect the request to WP.com's IG oEmbed proxy instead
  - and a `jetpack_instagram_oembed_remote_get_args` filter (hooked into `oembed_remote_get_args`) to add the required authorization for the WP.com proxy.
- Extract a `build_signed_request` helper method for the latter (in `packages/connection/src/class-client.php`).
- Remove the `instagram_cache_oembed_api_response_body` filter. This allowed returning a boolean value indicating whether to cache or not; if set to true, it would cache for a random amount of time [between one hour and two](https://github.com/Automattic/jetpack/blob/fe6303930772e4b3b276cfba94f651346b6f012d/modules/shortcodes/instagram.php#L185). Core's oEmbeds are cached [for a day](https://github.com/WordPress/WordPress/blob/aef2b539cd665007d3847e27c5e5a3c40afc481c/wp-includes/class-wp-embed.php#L245) by default; caching time can be customized through the `oembed_ttl` filter. _(This is a slight derivation from the original project proposal in `pc9Uba-6d-p2`, but it seemed reasonable to me.)_
- Reenable a number of IG embed unit tests against WP `master`, thus fixing #12918.
- Remove the code that [removes an IG oEmbed handler for an older URL format](https://github.com/Automattic/jetpack/blob/fe6303930772e4b3b276cfba94f651346b6f012d/modules/shortcodes/instagram.php#L87) ([no longer present in Core](https://core.trac.wordpress.org/changeset/44486)), and update a related comment to say that we can also remove the removal of the current IG oEmbed handler [once Core drops it](https://core.trac.wordpress.org/ticket/50861).

#### Jetpack product discussion
pc9Uba-6d-p2

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

We first test "classic" embeds/shortcodes handling (that doesn't involve Core's oEmbed endpoint that's used by the GB embed block).

- Start a new post, and insert a Classic block.
- Insert the URL of an Instagram post into that block.
- Verify that it expands into the corresponding embed.
- Publish the post, note its ID somewhere, and view it.
- Verify that the embed works there, too.
- To be on the safe side, clear the embed cache by running `yarn docker:wp post meta delete YOUR_POST_ID --all` (using the post ID you noted earlier).
- Reload the post, and verify that the embed still works.

Next, repeat the same without the Classic block by directly pasting the IG post URL into a post. Don't forget to clear oEmbed cache! You should see the embed expand into the embed block, with a preview of the IG post. Once again save, view, clear cache, and reload the post on the frontend.

There's also some good coverage of IG embeds and shortcodes in `tests/php/modules/shortcodes/test-class.instagram.php`, so verify that Travis is green. To run them manually, use

```bash
yarn docker:phpunit --filter=WP_Test_Jetpack_Shortcodes_Instagram
```

#### Proposed changelog entry for your changes:
Instagram embed: Use Core's oEmbed handling, drop custom Jetpack handler.

---

_Big props to @jeherve for his previous work in #11063 and p9GBOq-BC-p2, and to @ebinnion for his work on adding the auth token to requests to IG's oEmbed REST API._

### CODE REVIEW

**Review by WunderBart — DISMISSED** [review]
This works well for me! 🎉  I followed the testing instructions and here's what I see:

Oct-12-2020 18-13-39

~I couldn't run the mentioned specs due to some problems with my local setup. I can try again tomorrow unless JP folks beat me up to it 😄~

Scratch that - all good there as well! (Thanks, @jeherve!)

```
 1. 674ms to run WP_Test_Jetpack_Shortcodes_Instagram:test_shortcodes_instagram_non_amp with data set "non_instagram_url"

Time: 10.64 seconds, Memory: 88.50 MB

OK (22 tests, 22 assertions)
✨  Done in 13.38s.
```

File: modules/shortcodes/instagram.php [hunk 1]
```diff
@@ -206,154 +185,6 @@ function jetpack_instagram_get_access_token() {
...
-		 * Fires after making a request for an Instagram embed.
-		 *
-		 * @module shortcodes
-		 *
-		 * @since  9.1.0
-		 *
-		 * @param array $response The response from the embed request.
-		 * @param array $url      The arguments sent with the request.
-		 */
-		do_action( 'jetpack_instagram_embed_request', $response, $args );
```
Comment (jeherve) [inline modules/shortcodes/instagram.php:294]: With this change and the removal of the action, we lose a way to keep track of the requests. Is that alright?

If it is, we should add that action to the list of deprecated hooks alongside `instagram_cache_oembed_api_response_body `.

File: modules/shortcodes/instagram.php [hunk 2]
```diff
@@ -78,112 +78,91 @@ function jetpack_instagram_embed_reversal( $content ) {
...
-	if ( $atts['width'] > $max_width ) {
-		$atts['width'] = $max_width;
-	} elseif ( $atts['width'] < $min_width ) {
-		$atts['width'] = $min_width;
+	// Attempt to clean query params from the URL since Facebook's new API for Instagram
+	// embeds does not like query parameters. See p7H4VZ-2DU-p2.
+	$parsed_url = wp_parse_url( $url );
+	if ( $parsed_url ) {
+		$clean_url = 'https://www.instagram.com' . $parsed_url['path'];
+		$provider  = add_query_arg( 'url', rawurlencode( $clean_url ), remove_query_arg( 'url', $provider ) );
```
Comment (jeherve) [inline modules/shortcodes/instagram.php:123]: This `remove_query_arg` inside `add_query_arg` made me do a double take when I first read it :)

**Review by jeherve — DISMISSED** [review]
This tests well for me, and looks good, thanks for your work on this!

@emrikol Would you like to give this a look as well, given that it removes the `instagram_cache_oembed_api_response_body` filter currently in use on VIP Go?
This would mean you'd most likely have to switch to using the `oembed_ttl` filter to control caching of those embeds on the platform, and this would have to happen in coordination with the 9.1 release there.

File: modules/shortcodes/instagram.php (hunk 2 above)
Comment (ockham) [reply modules/shortcodes/instagram.php:123]: I can spread it over two lines (with an intermediate `$provider_without_url` or `$provider_without_emned_url` var), and/or add a comment :slightly_smiling_face:

File: modules/shortcodes/instagram.php (hunk 1 above)
Comment (ockham) [reply modules/shortcodes/instagram.php:294]: Ohh, I think I missed that when rebasing. Thanks for raising this! I think we want to keep it. I'll add it back.

Comment (ockham) [reply modules/shortcodes/instagram.php:294]: Took me a bit to find an action that we can tap into. The best I could find is fairly generic and bit ugly (`http_api_debug`) -- I couldn't find anything more oEmbed specific that retained the errors (they are almost always discarded, and `false` is returned instead).

I think we have two options:
1. Do nothing here; instead, change the action added in D50894-code to hook into `http_api_debug` (and bail early if the `$url` doesn't start with `https://graph.facebook.com/v5.0/instagram_oembed/`) instead of `jetpack_instagram_embed_request`, and discard the latter (which conveniently hasn't been part of any public JP release yet).
2. Call the `jetpack_instagram_embed_request` action from the `http_api_debug` action:

```diff
diff --git a/modules/shortcodes/instagram.php b/modules/shortcodes/instagram.php
index 8b2ba5cfc..973057c11 100644
--- a/modules/shortcodes/instagram.php
+++ b/modules/shortcodes/instagram.php
@@ -164,6 +164,37 @@ function jetpack_instagram_oembed_remote_get_args( $args, $url ) {
 }
 add_filter( 'oembed_remote_get_args', 'jetpack_instagram_oembed_remote_get_args', 10, 2 );
 
+/**
+ * Call the `jetpack_instagram_embed_request` action upon HTTP response from the IG oEmbed API.
+ *
+ * @param array|WP_Error $response    HTTP response or WP_Error object.
+ * @param string         $context     Context under which the hook is fired.
+ * @param string         $class       HTTP transport used.
+ * @param array          $args        HTTP request arguments.
+ * @param string         $url         The request URL.
+ */
+function jetpack_instagram_http_api_debug( $response, $context, $class, $args, $url ) {
+	if ( ! wp_startswith( $url, 'https://graph.facebook.com/v5.0/instagram_oembed/' ) ) {
+		return;
+	}
+
+	// Unset before calling the action below.
+	unset( $args['access_token'] );
+
+	/**
+	 * Fires after making a request for an Instagram embed.
+	 *
+	 * @module shortcodes
+	 *
+	 * @since  9.1.0
+	 *
+	 * @param array $response The response from the embed request.
+	 * @param array $args     The arguments sent with the request.
+	 */
+	do_action( 'jetpack_instagram_embed_request', $response, $args );
+}
+add_action( 'http_api_debug', 'jetpack_instagram_http_api_debug', 10, 5 );
+
 /**
  * Fetches a Facebook API access token used for query for Instagram embed information, if one is set.
  *
```

Any preference? :thinking:

File: modules/shortcodes/instagram.php (hunk 2 above)
Comment (ockham) [reply modules/shortcodes/instagram.php]: d117c6571

**Comment by ockham** [comment]
Tangential question: How do we apply this to WP.com in a post-JP DNA world? E.g. the `class-client.php` file seems to live in a `vendor/` dir now, and hasn't got the latest [fix](https://github.com/Automattic/jetpack/pull/17429) applied yet. What's the procedure here?

File: modules/shortcodes/instagram.php (hunk 1 above)
Comment (jeherve) [reply modules/shortcodes/instagram.php:294]: I'd personally vote for option 1.

File: modules/shortcodes/instagram.php (hunk 2 above)
Comment (jeherve) [reply modules/shortcodes/instagram.php]: Thank you!

**Comment by jeherve** [comment]
> How do we apply this to WP.com in a post-JP DNA world?

We'll need to update the packages' version numbers on WordPress.com to use the latest version of the connection package. I'll take care of this today.

File: modules/shortcodes/instagram.php (hunk 1 above)
Comment (ockham) [reply modules/shortcodes/instagram.php:294]: Thanks! I'll file a diff.

Comment (ockham) [reply modules/shortcodes/instagram.php:294]: D51050-code

**Comment by jeherve** [comment]
> We'll need to update the packages' version numbers on WordPress.com to use the latest version of the connection package. I'll take care of this today.

Done in r215115-wpcom

**Review by jeherve — APPROVED** [review]

**Comment by ockham** [comment]
Thanks a lot, Jeremy! :heart:
