### PR TITLE
Podcast Player: Fix missing replace button

### LINKED ISSUE #15459: (3P) Podcast Player: "Replace" button is empty
Gutenberg 7.9 seems to introduce yet another class/markup change for the toolbar, rendering the button that lets users replace RSS urls empty.

#### Steps to reproduce the issue

1. Enable gutenberg-edge on your test site
2. Apply D41939-code to your sandbox
3. Set the feed URL and then attempt to replace it

#### Screenshots

image

### PR DESCRIPTION
**Pull request by frontdevde**
#### Changes proposed in this Pull Request:

As reported in https://github.com/Automattic/jetpack/issues/15459 with Gutenberg 7.9 the `Replace` button in the podcast player block is not visible anymore. The source of the change could be traced down to [this commit](https://github.com/WordPress/gutenberg/pull/21252/files#diff-79abb3d6d15fcdde19979cde85e9d2ac).

This PR suggests changing our implementation to be in line with how the same button is handled in `MediaReplaceFlow` which is used in the `image` block.

Fixes https://github.com/Automattic/jetpack/issues/15459

#### Testing instructions:

* Create a new post and add the `Podcast player (beta)` block
* Add a podcast URL
* See if the replace button is visible
* Try to replace the podcast URL

| Before  | After |
| ------------- | ------------- |
| Screenshot 2020-04-21 at 15 58 00 | Screenshot 2020-04-21 at 15 58 14 |

### CODE REVIEW

**Review by obenland — DISMISSED** [review]
Tested with Gutenberg 7.9.1 and with vanilla Core trunk, both work as expected. Nice!

**Review by jeherve — CHANGES_REQUESTED** [review]
I'm afraid we can't use `ToolbarGroup` just yet. It wasn't part of WordPress 5.3.2, it was only added in 5.4. It consequently causes the block to error out in WP 5.3.2.

File: extensions/blocks/podcast-player/edit.js [hunk 1]
```diff
@@ -256,14 +257,29 @@ const PodcastPlayerEdit = ( {
...
+							onClick={ () => setIsEditing( true ) }
+						>
+							{ __( 'Replace', 'jetpack' ) }
+						</Button>
+					</ToolbarGroup>
+				) : (
+					<Toolbar
+						controls={ [
+							{
+								title: __( 'Edit Podcast Feed URL', 'jetpack' ),
```
Comment (WunderBart) [inline extensions/blocks/podcast-player/edit.js:274]: Will this and the `Replace` strings be required for translation twice if we call it twice? Or are they _merged_ somehow and then translated as one?

File: extensions/blocks/podcast-player/edit.js [hunk 2]
```diff
@@ -266,7 +257,29 @@ const PodcastPlayerEdit = ( {
 	return (
 		<>
 			<BlockControls>
-				<Toolbar controls={ toolbarControls } />
+				{ /* @todo Fallback can be removed when WP 5.4 is the minimum supported version. */ }
```
Comment (retrofox) [inline extensions/blocks/podcast-player/edit.js:260]: minor suggestion: make it sense moving all logic into a variable or a component?

```es6
<PodcatsPlayerToolbar />
```

and deal with this there. Please feel free to ignore it.

File: extensions/blocks/podcast-player/edit.js (hunk 1 above)
Comment (marekhrabe) [reply extensions/blocks/podcast-player/edit.js:274]: It shouldn't be a problem as same strings are consolidated from the whole Jetpack codebase, backend and frontend. We have scripts in place that extract all strings from codebase and unique ones will be uploaded to GlotPress for translation.

File: extensions/blocks/podcast-player/edit.js (hunk 2 above)
Comment (obenland) [reply extensions/blocks/podcast-player/edit.js:260]: I'd rather keep it modular so it can be cleaned up once WordPress 5.5 was released.

**Review by marekhrabe — APPROVED** [review]
I have tested in WP 5.3.2 with and without the Gutenberg plugin. Works as expected in both cases.

**Review by jeherve — APPROVED** [review]

**Comment by frontdevde** [comment]
r206327-wpcom
