### PR TITLE
Post List: Fix the response after saving a Quick Edit.

### LINKED ISSUE #21671: Post-list enhancement: thumbnails fail during "quick edit".
### Impacted plugin
Post-list enhancement package.

### Steps to Reproduce

1. The "post list enhancement" is currently behind a blog sticker. Enable the wpcom-post-list-enhancements sticker from the site's report card to enable it.
2. Go to the Posts page in wp-admin.
3. Click on a post's "Quick Edit".
4. Once inside "Quick Edit" click "Update"
4. Note how the thumbnail disappears, and the post's row layout is malformed.

### A clear and concise description of what you expected to happen.

The thumbnail should not disappear after a "quick edit" "update" and the post's row should not be malformed.

### What actually happened

After "updating" from a "quick edit" the posts thumbnail should still be visible and the row layout should not be messed up.

### Other information

https://user-images.githubusercontent.com/140841/140808860-7fcb8679-cd47-45aa-9327-414c923b8d07.mp4

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium, Firefox, Safari

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by pablinos**
The customizations that to the post list screen were being made on hooks
that only ran as the page/screen loaded. If a quick edit was made, the
table row returned in the result didn't include the necessary
customizations and would break the table.

There appears to be a WordPress bug where the post actions are not
hidden after a quick edit too. I also noticed the Copy post action was
missing, which might be another issue in Jetpack.

Fixes #21671

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Enable the post list package
* Perform a quick edit on a post or page
* Without this PR, the row will be missing the thumbnail and the table will look broken
* With this PR, it should render correctly

### CODE REVIEW

File: projects/packages/post-list/src/class-post-list.php [hunk 1]
```diff
@@ -37,9 +37,13 @@ public static function get_instance() {
 	public function register() {
 		if ( ! did_action( 'jetpack_on_posts_list_init' ) ) {
 			add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_scripts' ) );
-			add_action( 'current_screen', array( $this, 'add_filters_and_actions' ) );
+			add_action( 'current_screen', array( $this, 'add_filters_and_actions_for_screen' ) );
 			add_filter( 'default_hidden_columns', array( $this, 'adjust_default_columns' ), 10, 2 );
 
+			if ( wp_doing_ajax() && ! empty( $_POST['action'] ) && 'inline-save' === $_POST['action'] && wp_verify_nonce( 'inlineeditnonce', '_inline_edit' ) ) {
+				add_action( 'admin_init', array( $this, 'add_filters_and_actions_quick_edit' ) );
```
Comment (dsas) [inline projects/packages/post-list/src/class-post-list.php:44]: This register method is already being executed via the `admin_init` action, so I don't _think_ this will run

File: projects/packages/post-list/src/class-post-list.php [hunk 2]
```diff
@@ -104,14 +113,44 @@ public function add_filters_and_actions( $current_screen ) {
 			 * @param boolean Whether we should show the share action for this post type.
 			 * @param string  The current post type.
 			 */
-			apply_filters( 'jetpack_post_list_display_share_action', false, $current_screen->post_type )
+			apply_filters( 'jetpack_post_list_display_share_action', false, $post_type )
```
Comment (Copons) [inline projects/packages/post-list/src/class-post-list.php:116]: I've noticed that after a quick edit, the Share action disappears from the quick actions row.

It seems this is caused by this filter returning false — which should not happen on WPCOM (see the `wpcom-jetpack-loader`).
I've poked around a little bit, but I couldn't find a good solution. 🤔 

Either case, I think this could be filed as a minor bug, and IMHO shouldn't block the merge of this PR which address a much more serious issue.
@dsas feel free to take a look yourself, in the off-chance my PHP skills are so rusty I'm overlooking something simple.

Comment (dsas) [reply projects/packages/post-list/src/class-post-list.php:116]: `wpcom_configure_post_list` in wp-content/mu-plugins/0-wpcom-jetpack-loader.php hooks the filter to return true. That happens *after* Post_List::register is ran. On a page request Post_List::register will set-up the quick actions later, on an ajax request it sets them up immediately - which in this case will fail as the filter hasn't been registered yet.

Ideally the fix might  be to identify a better hook to use for ajax requests in Post_List::register so it acts more similarly to a page load. The quick fix however is to register the filter in `wpcom_configure_post_list`  before the config object makes `Post_List::register` run.

Comment (dsas) [reply projects/packages/post-list/src/class-post-list.php:116]: Couldn't see a better action being ran, so I rearranged the code in `0-wpcom-jetpack-loader.php` in D70220-code

Comment (mmtr) [reply projects/packages/post-list/src/class-post-list.php:116]: It's also happening on Atomic sites, so I guess we need a similar fix on `wpcomsh`?

**Review by mmtr — DISMISSED** [review]
LGTM 🚀 

The small issue noted by Jacopo will be handled separately for both WP.com and Atomic, so it shouldn't block the merge of this PR.

**Review by mmtr — APPROVED** [review]

File: projects/packages/post-list/src/class-post-list.php (hunk 2 above)
Comment (dsas) [reply projects/packages/post-list/src/class-post-list.php:116]: I've opened 787-gh-Automattic/wpcomsh for that
