### PR TITLE
Contact Form Block: Prevent removal of the submit button

### LINKED ISSUE #16303: Contact Form Block: Disallow removing Submit/Contact Us Button (or add a way to add it back if removed)
It's possible to remove the `Submit/Contact Us` Button inside the Contact form Block. And once that is done, there is no way to add it back as it's not part of the Blocks the Form can have. 

I noticed this after https://github.com/Automattic/jetpack/issues/15286 was implemented, so pinging @apeatling in case it's something that can be fixed.

#### Steps to reproduce the issue

1. Add Contact Form Block
2. Click on `Submit/Contact Us` button to select it and then three-dots and `Remove`
3. Try to click + and see no Button Block in the list of items that can be added

#### What I expected
- No way to remove the `Submit/Contact Us` button (maybe remove the entry `Remove` in the three-dots menu)

_Link: https://d.pr/i/opYVpC_

OR

- Add specifically `Submit/Contact Us` button to the list of Blocks that can be added inside the Contact Form block.

_Link: https://d.pr/i/PBMchY_

#### What happened instead

`Submit/Contact Us` Button Block can be removed as any other block but with no possibility to add it back (unless you edit the code directly by adding `<!-- wp:jetpack/button {"element":"button","text":"Contact Us"} /-->` within `<!-- wp:jetpack/contact-form --> <!-- /wp:jetpack/contact-form -->`)

#user-report https://wordpress.com/it/forums/topic/testo-pulsante-invia/

### PR DESCRIPTION
**Pull request by vykes-mac**
Fixes #16303

#### Changes proposed in this Pull Request:

This PR aims to make the user experience better when using contact form blocks by removing the ability remove the submit button, since the button naturally is a required component of a contact form for this we: 
* add the attribute `lock { remove:  true}` to the submit button on each variation of a form. This makes it unable to remove the button for newly added forms.
* programatically find existing forms on a page and update the submit button attributes to prevent removal. This handles the case for users with existing forms.

#### Limitations:
The user can unlock the button and uncheck `prevent removal` and remove the button, but I think this might serve as an indicator to the user that this button shouldn't be removed. If they do remove the button they will find there's no other way to added it back and recreate the form at which point the button will be locked from removal again.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Testing instructions:

1. Set up a Jurassic Ninja site.
2. Connect it to WP.com.
3. First create/save a post with a form block without these changes.
4. Apply changes then visit the post and verify that the option to remove the form button is no longer present.
5. Add a new form to the post and verify that the option to remove the button is no present.

**Before**
Screenshot 2022-06-24 at 12 34 35 PM
**After**
Screenshot 2022-06-24 at 12 36 12 PM

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
In testing (on a JN site and locally) I found that a form block added before the feature branch was enabled still allowed me to remove the button.

The option [suggested in this comment](https://github.com/Automattic/jetpack/issues/16303#issuecomment-1163648553) looks like it just prevents the remove button link from working. I experimented with this a bit but couldn't actually get the functionality to work either - I'm wondering if that's why the lock option was chosen? I did find the UI for the lock / unlock option a little confusing, though it does make it that little bit harder to accidentally remove the button which is helpful.

**Comment by vykes-mac** [comment]
@coder-karen 

> In testing (on a JN site and locally) I found that a form block added before the feature branch was enabled still allowed me to remove the button.

Can you test this again? I wasn't checking that an actual form exists before unsubscribing so the logic to update the button didn't got executed.

> I'm wondering if that's why the lock option was chosen? I did find the UI for the lock / unlock option a little confusing, though it does make it that little bit harder to accidentally remove the button which is helpful.

Yes, I played around with the the reseting the blocks to previous state if remove button was click but as you said it only disable the button and not remove it, which might be more confusing to users. I think the lock feature is less destructive or hacky as it's a provide block api feature. Also we could set `lock:true` on the global parameters for the jetpack button which would remove the lock icon from the block options, this means users wouldn't be able to unlock the button. The downside to that is all jetpack button added would be locked and cannot be unlocked which might spell problems even though it seems those buttons are not insertable blocks but has to be added programatically.

File: projects/plugins/jetpack/extensions/blocks/contact-form/index.js [hunk 1]
```diff
@@ -16,6 +16,7 @@ import deprecated from './deprecated';
 import edit from './edit';
 import transforms from './transforms';
 import variations from './variations';
+import './view';
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/contact-form/index.js]: If you'd like to start loading js on the frontend whenever the form block is added to a post / page, you would need to also rely on `Jetpack_Gutenberg::load_assets_as_required()` in PHP to ensure the js gets loaded on the frontend.

That said, I'm thinking we may not need to add this to the frontend, right? It should be enough to load this in the editor.
In this case, I would recommend that you move the code from `view.js` to `edit.js`.
This will have the added bonus of not having to load `@wordpress/data` on the frontend.

**Review by jeherve — DISMISSED** [review]

File: projects/plugins/jetpack/extensions/blocks/contact-form/index.js (hunk 1 above)
Comment (vykes-mac) [reply projects/plugins/jetpack/extensions/blocks/contact-form/index.js]: > That said, I'm thinking we may not need to add this to the frontend, right?

Yes this is not needed in the front-end only the editor. It's purpose is to update existing form blocks to remove the delete option for the submit button.

> In this case, I would recommend that you move the code from view.js to edit.js.
> This will have the added bonus of not having to load @wordpress/data on the frontend.

Thank you for the suggestion, this make sense since this piece of code is not needed in the front-end. I will update accordingly.

**Review by coder-karen — APPROVED** [review]
Tested again after those changes and I notice the lock option is now showing for form buttons added prior to this PR.

I notice you have a 'needs team review' label this time rather than 'needs review' so I've left that in case you are looking for a review from your team too.

**Comment by coder-karen** [comment]
r248397-wpcom
