### PR TITLE
CXN Tests: Better unexpected state handling in wpcom connection test

### LINKED ISSUE #12325: Site Health: The WP.com endpoint can 404
captura_de_pantalla_2019-05-08_a_la_s__22 55 03

This is the `test__wpcom_connection_test` failing to get a response (a 404) from the WP.com endpoint. My guess is this check:
```
		if ( ! Jetpack::is_active() || Jetpack::is_development_mode() || Jetpack::is_staging_site() || ! $this->pass ) {
			return self::skipped_test( $name );
		}
```
isn't stopping the test, perhaps the `!$this->pass` with the decoupling of the tests for the Site Health section. I believe investigating on a never-connected site would be the first thing to try.

#### Steps to reproduce the issue

1. Unsure right now.

#### What I expected
No PHP errors and results from the Site Health are all complete.

#### What happened instead
See screenshot.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #12325

#### Changes proposed in this Pull Request:
* Handle cases where the Jetpack ID is non-standard and if WP.com 404s.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* No.

#### Testing instructions:
* @eliorivero running it on his site.
* Manually set your Jetpack ID option to a random string.
* Run Site Health.

#### Proposed changelog entry for your changes:
* Site Health: Improve error messaging.

### CODE REVIEW

File: _inc/lib/debugger/class-jetpack-cxn-tests.php [hunk 1]
```diff
@@ -225,6 +225,12 @@ protected function test__wpcom_connection_test() {
 			return self::skipped_test( $name );
 		}
 
+		$id = Jetpack_Options::get_option( 'id' );
+
+		if ( ! is_int( $id ) ) {
```
Comment (zinigor) [inline _inc/lib/debugger/class-jetpack-cxn-tests.php]: Do we have a legitimate reason why this could be happening? `is_int` will return `FALSE` if the returned value is not coerced to an integer, for example: `"42"`. I'm pretty sure we won't be storing the ID as a string anywhere, but I'm still worried that this might cause some false positives.

Comment (kraftbj) [reply _inc/lib/debugger/class-jetpack-cxn-tests.php]: That's fair. I don't know why it wouldn't be a number. @eliorivero any ideas since it was occurring on your site?

Comment (mdawaffe) [reply _inc/lib/debugger/class-jetpack-cxn-tests.php]: I have definitely seen the ID stored as a string recently. I have also seen it stored as an integer recently.

:(

Comment (kraftbj) [reply _inc/lib/debugger/class-jetpack-cxn-tests.php]: Alrighty, I'm going to account for the 404 then and not worry about the type for now.

Comment (kraftbj) [reply _inc/lib/debugger/class-jetpack-cxn-tests.php]: 48029775f

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
Leaving it for @eliorivero to give it a try as well!
