### PR TITLE
My Jetpack: Keep product card action button disabled while installing standalone plugin

### LINKED ISSUE #30223: My Jetpack: Keep action button disabled until refresh after installing or activating plugin through My Jetpack card
There is a small gap between the time the manage button is re-enabled and the page refresh where the user could press it and be redirected to the wrong page:

Clicking before refresh:

https://user-images.githubusercontent.com/8486249/233451040-ef779f35-77ce-4287-98a0-5e0a97e5bd8a.mp4

Waiting for refresh:

https://user-images.githubusercontent.com/8486249/233451510-72a9f856-2cf2-4184-86b8-c89d8e7ff328.mp4

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #30223

## Proposed changes:

* Adds a local state flag to know when a standalone plugin is installing to keep the button disabled

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to My Jetpack
* In any card representing a plugin that is not installed and has the actions menu, use it to install the plugin:

* Check that the `Manage` button is disabled until the page refresh

Before: https://github.com/Automattic/jetpack/issues/30223
After:

https://user-images.githubusercontent.com/8486249/234987296-5d379c6d-72ad-47b0-8cb3-70a8a15d1f2b.mp4

### CODE REVIEW

File: projects/packages/my-jetpack/_inc/components/connected-product-card/index.jsx [hunk 1]
```diff
@@ -62,9 +69,15 @@ const ConnectedProductCard = ( { admin, slug, children, showMenu = false, menuIt
...
 	const handleInstallStandalone = useCallback( () => {
-		installStandalonePlugin().then( () => {
-			window?.location?.reload();
-		} );
+		setInstallingStandalone( true );
+
+		installStandalonePlugin()
+			.then( () => {
+				window?.location?.reload();
+			} )
```
Comment (retrofox) [inline projects/packages/my-jetpack/_inc/components/connected-product-card/index.jsx:77]: Minor suggestion. Not tested.
```suggestion
			.then( window?.location?.reload )
```

**Review by retrofox — DISMISSED** [review]
LGTM!

We should tweak the disabled state of the button:

https://user-images.githubusercontent.com/77539/235005733-1d775a09-2665-49aa-a158-dd11e0cdd160.mov

But that's another story. 🚢

**Review by retrofox — DISMISSED** [review]

File: projects/packages/my-jetpack/_inc/components/connected-product-card/index.jsx (hunk 1 above)
Comment (dhasilva) [reply projects/packages/my-jetpack/_inc/components/connected-product-card/index.jsx:77]: Did not work

**Review by retrofox — APPROVED** [review]
