### PR TITLE
Forms: Fix syncing of shared styles for nested fields and related undo issue

### LINKED ISSUE #41704: Forms: Shared field styles break when fields are not immediate children of form
### Impacted plugin

Jetpack

### Quick summary

Only fields that are immediate children of a form will correctly share sync'd style attributes regardless of opt-in to the feature.

https://github.com/user-attachments/assets/d612698f-e847-4fae-9865-fb77d724f0a9

### Steps to reproduce

1. Add a form to a post
2. Add some additional fields and nest them within a container block e.g. Group, Row, Stack, Columns etc.
3. Ensure all the form fields have "Sync fields style" toggled on
4. Try styling one of the nested fields, notw that only the top-level, immediate form child fields, will update. The nested field that has opted into the shared style misses out.
5. Switch to the field that missed out, adjust its styles and note the same result.
6. Adjust styles on a top level form field and note no nested fields get updated.

<details>
<summary>Here's some test block markup</summary>

```html
<!-- wp:jetpack/contact-form {"style":{"spacing":{"padding":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}}} -->
<div class="wp-block-jetpack-contact-form" style="padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px"><!-- wp:jetpack/field-name {"required":true} /-->

<!-- wp:jetpack/field-email {"required":true} /-->

<!-- wp:group {"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group"><!-- wp:jetpack/field-name {"required":true,"width":50} /-->

<!-- wp:jetpack/field-email {"required":true,"width":50} /--></div>
<!-- /wp:group -->

<!-- wp:jetpack/field-textarea {"label":"Message"} /-->

<!-- wp:jetpack/button {"element":"button","text":"Contact Us","lock":{"remove":true}} /--></div>
<!-- /wp:jetpack/contact-form -->
```
</details>

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

The only work around is to manually adjust all the nested fields individually or un-nest them.

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
Fixes #41704

## Proposed changes:

* Updates the `useSharedFieldAttributes` hook to factor in that form fields can be nested within other blocks and may not be immediate children of the primary form block.
* Fixes multiple bugs related to style syncing
    * Prevents fields from using themselves as the source for shared attributes
    * Eliminates duplicate undo stack entries that were causing undo loops
    * Fixes undo when syncing styles on block insertion e.g. dropping field from second form into the current one.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No changes.

## Testing instructions:

1. Test nested field style syncing:
    - Add a form with fields nested in a Group block (example block markup provided below)
    - Enable "sync field styles" on nested fields, if not already set
    - Modify styles on a nested field and verify all opted-in fields update
    - Modify styles on a top-level field and verify nested fields update correctly

2. Test undo functionality:
    - Make style changes to synced fields
    - Verify that undo/redo operations work smoothly without loops
    - Drop a new field into the form and verify undo still works appropriately
        - _Note: this PR doesn't aim to make form and field undos perfect just improve the situation around syncing styles_

3. Test block insertion with synced styles:
    - Ensure some form fields have shared styles set
    - Add a new field to the beginning of the form (either by drag and dropping one or inserter)
    - Verify it correctly inherits the shared styles from existing fields

```html
<!-- wp:jetpack/contact-form {"style":{"spacing":{"padding":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}}} -->
<div class="wp-block-jetpack-contact-form" style="padding-top:16px;padding-right:16px;padding-bottom:16px;padding-left:16px"><!-- wp:jetpack/field-name {"required":true,"placeholder":"Placeholder"} /-->

<!-- wp:jetpack/field-email {"required":true,"placeholder":"Placeholder"} /-->

<!-- wp:group {"style":{"spacing":{"padding":{"top":"var:preset|spacing|30","bottom":"var:preset|spacing|30","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}},"color":{"background":"#eeeeee"}},"layout":{"type":"flex","flexWrap":"nowrap"}} -->
<div class="wp-block-group has-background" style="background-color:#eeeeee;padding-top:var(--wp--preset--spacing--30);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--30);padding-left:var(--wp--preset--spacing--30)"><!-- wp:jetpack/field-name {"label":"Nested Field 1","required":true,"placeholder":"Placeholder","width":50} /-->

<!-- wp:jetpack/field-email {"label":"Nested Field 2","required":true,"placeholder":"Placeholder","width":50} /--></div>
<!-- /wp:group -->

<!-- wp:jetpack/field-textarea {"label":"Message","placeholder":"Placeholder"} /-->

<!-- wp:jetpack/button {"element":"button","text":"Contact Us","lock":{"remove":true}} /--></div>
<!-- /wp:jetpack/contact-form -->
```

#### Nested Field Syncing

| Before | After |
|---|---|
| <video src="https://github.com/user-attachments/assets/5567f58f-86a0-43c1-9987-5bf4427a8db3" /> | <video src="https://github.com/user-attachments/assets/955864e0-0478-4f9d-890e-27b1b13b26ad" /> |

#### Undo fix for general style sync

| Before | After |
|---|---|
| <video src="https://github.com/user-attachments/assets/61dd99b1-de57-45c2-9080-725e6ae331ee" /> | <video src="https://github.com/user-attachments/assets/6774a1f8-3d27-4998-9509-892f72f3d0d7" /> |

#### Source of truth and sync on mount fixes

| Before | After |
|---|---|
| <video src="https://github.com/user-attachments/assets/04a4458b-8aa1-4f09-a5ed-b043145e453a" /> | <video src="https://github.com/user-attachments/assets/f116277b-79cf-4648-b760-000038e90edb" /> |

### CODE REVIEW

File: projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js [hunk 1]
```diff
@@ -3,7 +3,7 @@
  */
 import { useDispatch, useSelect } from '@wordpress/data';
 import { useCallback, useEffect } from '@wordpress/element';
-import { isEmpty, filter, first, map, pick, isNil } from 'lodash';
+import { isEmpty, first, map, pick, isNil } from 'lodash';
```
Comment (aaronrobertshaw) [inline projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js:6]: A good followup here would be to switch out the use of lodash functions for vanilla JS.

File: projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js [hunk 2]
```diff
@@ -21,10 +21,18 @@ export const useSharedFieldAttributes = ( {
...
+			}
+
+			const formDescendants = blockEditor.getClientIdsOfDescendants( parentId );
+
+			return blockEditor
+				.getBlocksByClientId( formDescendants )
+				.filter(
+					block =>
+						block?.name?.indexOf( 'jetpack/field' ) > -1 && block?.attributes?.shareFieldAttributes
+				);
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: I read through the syncing code deeply, as I was interested in how it works, and spotted a bug in the logic which I imagine will also be present in trunk.

If you have two forms, set some synced field styles on the first form, but leave the second one unstyled. Then try dragging one of the unstyled fields from the second form to the first, you'll see different results depending on where you drop the field.
- If the field is dropped anywhere other than as the first child in the form, then it'll sync and receive the same styles as the other fields
- If the field is dropped into the first position in the form, then it remains unsynced, and syncing from that point on can be buggy (all the other blocks start syncing to this unstyled first block). 😬 

Also happens when you insert new fields to the first position using the block inserter, though I think drag and drop is a bit easier to repro.

It's because of the way the code later on uses `first( siblings ).attributes` as the source of truth, but `siblings` also includes the current block, so when that new block is added as the first one, it syncs to itself. 😄 

I think a solution is to filter out the `clientId` from siblings. Hopefully doing so won't cause other issues.

Happy to treat is as a different PR and keep things atomic.

**Review by talldan — DISMISSED** [review]
LGTM.

I spotted a bug with the code in trunk (see the review comment), but I think it can be handled separately from this PR. I'll leave it up to you.

NIH, but something else is the `useSelect` will, I think, be pretty inefficient. It'll re-calculate `siblings` constantly, even when the user is only hovering different blocks. It'd be better to calculate `siblings` in the callback IMO.

File: projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js (hunk 2 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: > I think a solution is to filter out the clientId from siblings. Hopefully doing so won't cause other issues.

I don't think it does. 

I actually did [this](https://github.com/Automattic/jetpack/pull/41281/commits/519c5a1c6bff2e4356ffc7ac98def32666015b8f#diff-499e8fa890c3d3d79b8b2a579785c3a69a0517c4a5f02a4eb0cf032d17ec89abR56) in the recent exploration into inner blocks for form fields. That PR evolved from there and I forgot about fixing it there. Appreciate the reminder, I'll address it in this PR 🙇

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: Actually, I'm not sure what the expected behaviour is for this edge case of dropping synced fields in from different forms. It doesn't strike me as a common use case, so we might not have a lot to go on 🤔 

Given that uncertainty, let's leave the existing functionality for now and discuss in a follow-up potential changes to how it should work. Whether that edge case is supported might also impact the other suggestion from your review.

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: This syncing behaviour also leads to getting stuck in an undo loop.

**Comment by aaronrobertshaw** [comment]
Appreciate the speedy review @talldan 👍 

> NIH, but something else is the useSelect will, I think, be pretty inefficient. It'll re-calculate siblings constantly, even when the user is only hovering different blocks. It'd be better to calculate siblings in the callback IMO.

I've pushed a commit I think improves the situation regarding repeatedly collecting siblings but I'll need to give it a proper test and more thought tomorrow.

I'm also not sure about the approach taken, so happy for further feedback to push it in the right direction.

File: projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js [hunk 3]
```diff
@@ -1,7 +1,7 @@
 /**
  * External dependencies
  */
-import { useDispatch, useSelect } from '@wordpress/data';
+import { select, useDispatch } from '@wordpress/data';
```
Comment (talldan) [inline projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: I think you can still stick with `useSelect`, but there's a short form that doesn't have the dependencies or the mapping function:

```js
const { getBlockParentsByBlockName, getClientIdsOfDescendants, getBlocksByClientId } =
		useSelect( 'core/block-editor' );
```

I believe the advantage of `useSelect` over `select` is it'll ensure the correct registry is used.

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: I started there and ended up talking myself out of it. Appreciate the explanation 👍 

I'll revisit this once I sort out a couple of other fixes for undo stack etc.

Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: Done in https://github.com/Automattic/jetpack/pull/41708/commits/115020721fa7d0b121d96c2c57c1ef2b5f8a2efb

File: projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js (hunk 2 above)
Comment (aaronrobertshaw) [reply projects/packages/forms/src/blocks/contact-form/util/with-shared-field-attributes.js]: I've spent some time testing different flows and I think the filtering of the current block out of siblings leads to more expected behaviour. It also highlighted more issues with the syncing of styles breaking the undo stack.

The filtering of the current block from the siblings was done in: https://github.com/Automattic/jetpack/pull/41708/commits/8339bda3625a7a83e2255fd0956ddeaf154c0ba9

I've batched the updates syncing siblings and updating the current block attributes in: https://github.com/Automattic/jetpack/pull/41708/commits/8f2c06319f9966df2e047907009ea79818a1495b

To combat syncing styles breaking undo when dropping a block into a form, I marked that update as not persistent in: https://github.com/Automattic/jetpack/pull/41708/commits/7ac07fd97781a25b54357c16551bfa0aa7dac861

Happy for feedback on better approaches as always. For now though I'll resolve this conversation thread, update the PR title, description, and test instructions for the updated functionality.

**Comment by aaronrobertshaw** [comment]
I've updated this PR to not only fix the syncing of styles for the nested fields but also address some of the secondary issues noted in reviews and testing. These include:

- Ensuring new blocks, whether inserted or dropped into the first position in the form, aren't used as the source of shared style attributes
- Preventing the syncing of style attributes from causing an undo loop both when generally updating field styles and when dropping field blocks into an existing form with shared styles

The PR description and test instructions have been updated to reflect the latest state. Further enhancements or fixes should probably be done via follow-ups.

To that end, I think this is ready for a final review before merging 🙏

**Review by talldan — APPROVED** [review]
Tests well for me, and the code looks good. Thanks @aaronrobertshaw!
