### PR TITLE
Fix JS errors for eu-widget in block widget editor

### LINKED ISSUE #18565: Cookie Widget: JS error thrown when using Gutenberg block-based widgets screen
#### Steps to reproduce the issue

1. On a Jetpack (v9.3.1 used) connected site, make sure extra widgets are turned on in `/wp-admin/admin.php?page=jetpack#/writing`
2. Activate the Gutenberg plugin (v9.8.1 used); block-based widgets screen shipped in Gutenberg [8.9.0](https://github.com/WordPress/gutenberg/releases/tag/v8.9.0)
3. Activate the Twenty Twenty theme (v1.6 used)
4. In WP Admin > Appearance > Widgets, you should see the block-based widgets screen
5. Add the `Jetpack Cookies & Consents Banner` to a widget area and save changes.
6. Refresh the Widgets page.

#### What I expected

* For the block-based widgets screen to display without errors.

#### What happened instead

* A JS error is thrown, and existing widgets show as "This block has encountered an error and cannot be previewed."
* At this point the same widgets can be managed just fine from the Customizer.
* Removing just the `Jetpack Cookies & Consents Banner` widget via Customizer will allow the block-based widgets screen to load as expected again.

**Screenshots**

```
TypeError: Cannot read property 'indexOf' of undefined - /wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js

at HTMLDocument - /wp-content/plugins/jetpack/_inc/build/widgets/eu-cookie-law/eu-cookie-law-admin.min.js?ver=20180417
```

Screen Shot 2021-01-27 at 11 55 07 AM

### PR DESCRIPTION
**Pull request by samiff**
#### Changes proposed in this Pull Request:

Gutenberg 8.9.0 introduced a block-based widget editing screen, and
these changes fix two JS errors that were occuring due to:

1. `eu-cookie-law-admin.js` referencing an id value which when editing
the widget from the block-based screen is no longer present - there is
a legacy widget block wrapper.
2. `eu-cookie-law.js` may not always find the right DOM elements from
the block-based widget screen as the block is rendered or rerendered.

A separate issue has been opened for the `Preview` option not working as expected: #18664

#### Jetpack product discussion

Fixes #18565

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Refer to reproduction steps outlined in #18565
* After pulling/building proposed changes, test that you are able to add & edit a `Jetpack Cookies & Consents Banner` widget from the Gutenberg block-based widgets screen. Refresh the page and make sure no JS errors are thrown.
* Deactivate Gutenberg and make sure the normal WP Admin widget editing screen, and the Widgets item in Customizer work as expected.

#### Proposed changelog entry for your changes:

* Cookie Widget: Fix JS error when editing widget from block-based widget editor

### CODE REVIEW

File: projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law.js [hunk 1]
```diff
@@ -10,6 +10,10 @@
 		initialScrollPosition,
 		scrollFunction;
 
+	if ( null === widget || null === overlay ) {
```
Comment (sdixon194) [inline projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law.js:13]: Was this related to the bug itself, or just a way to shortcircuit if the widget isn't found at all?

**Review by sdixon194 — APPROVED** [review]
Tests well for me, nicely done!

**Review by jeherve — APPROVED** [review]

File: projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law.js (hunk 1 above)
Comment (samiff) [reply projects/plugins/jetpack/modules/widgets/eu-cookie-law/eu-cookie-law.js:13]: A short circuit because the rest of the code assumes those elements are present. Thanks for the review 👍
