### PR TITLE
Product Management Controls: double subscription creation

### LINKED ISSUE #24138: Premium Content: Fix double product creation when no products available caused by the Payment Button resolving the selector at the same time
## Impacted plugin
Jetpack

## Steps to Reproduce
When we have a Post with multiple payment blocks (Premium content and/or payment blocks), and we don't have any default plans/subscriptions, a new default subscription is being created for every payment block.

## A clear and concise description of what you expected to happen.
Only one default subscription/plan should be created.

## What actually happened
N plan/subscriptions are being created, where N is the number of individual payment blocks.

### PR DESCRIPTION
**Pull request by rcrdortiz**
Fixes #24138

#### Changes proposed in this Pull Request:

* Created a lock so that we don't create as many new plan/subscriptions as payment blocks. 

#### Testing instructions:

* Delete all your plan/subscriptions from https://wordpress.com/earn/payments-plans/{yoursitename}
* Create a new Post.
* Open the code editor and paste the following code (it consists of four different payment blocks without any assigned plan ids)
```
<!-- wp:premium-content/container  -->
<div class="wp-block-premium-content-container"><!-- wp:premium-content/subscriber-view -->
    <div class="wp-block-premium-content-subscriber-view entry-content"><!-- wp:heading {"level":3} -->
        <h3>Subscriber Content</h3>
        <!-- /wp:heading -->

        <!-- wp:paragraph -->
        <p>Add content here that will only be visible to your subscribers.</p>
        <!-- /wp:paragraph --></div>
    <!-- /wp:premium-content/subscriber-view -->

    <!-- wp:premium-content/logged-out-view -->
    <div class="wp-block-premium-content-logged-out-view entry-content"><!-- wp:heading {"level":3} -->
        <h3>Subscribe to get access</h3>
        <!-- /wp:heading -->

        <!-- wp:paragraph -->
        <p>Read more of this content when you subscribe today.</p>
        <!-- /wp:paragraph -->

        <!-- wp:premium-content/buttons -->
        <div class="wp-block-premium-content-buttons wp-block-buttons"><!-- wp:jetpack/recurring-payments {"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1568","uniqueId":"recurring-payments-1568"} -->
            <div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-1568","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"text":"Subscribe","url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1568"} /--></div>
            <!-- /wp:jetpack/recurring-payments -->

            <!-- wp:premium-content/login-button -->
            <div class="wp-block-premium-content-login-button wp-block-button"><a class="wp-block-button__link">Log in</a></div>
            <!-- /wp:premium-content/login-button --></div>
        <!-- /wp:premium-content/buttons --></div>
    <!-- /wp:premium-content/logged-out-view --></div>
<!-- /wp:premium-content/container -->

<!-- wp:jetpack/recurring-payments {"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1568","uniqueId":"recurring-payments-1568"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-1568","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1568"} /--></div>
<!-- /wp:jetpack/recurring-payments -->

<!-- wp:jetpack/recurring-payments {"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1569","uniqueId":"recurring-payments-1569"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-1569","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1569"} /--></div>
<!-- /wp:jetpack/recurring-payments -->

<!-- wp:jetpack/recurring-payments {"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1570","uniqueId":"recurring-payments-1570"} -->
<div class="wp-block-jetpack-recurring-payments"><!-- wp:jetpack/button {"element":"a","uniqueId":"recurring-payments-1570","passthroughAttributes":{"uniqueId":"uniqueId","url":"url"},"url":"https://anysite.wordpress.com/2022/04/22/1507/?recurring_payments=1570"} /--></div>
<!-- /wp:jetpack/recurring-payments -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
```
* You should only see one notice indicating that a plan/subscription has been created.
* Check that every payment block ends up having a payment plan assigned.
* Navigate to https://wordpress.com/earn/payments-plans/{yoursitename}, you should only see one subscription.

#### Testing

https://user-images.githubusercontent.com/1989914/165757843-4c19b193-3b54-4753-9b51-7454ee6c6301.mp4

### CODE REVIEW

File: projects/plugins/jetpack/extensions/shared/execution-lock.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+	const [ key, lockedBy ] = lock;
+	if ( isLocked( key ) && lockMap.get( key ) === lockedBy ) {
+		lockMap.delete( key );
+		return true;
+	}
+
+	return false;
+};
+
+export default {
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/execution-lock.js:68]: Key-based lock implementation, the only special feature is the block execution method, which prevents some code from being executed without necessarily blocking the main thread. Implemented as a singleton.

File: projects/plugins/jetpack/extensions/store/membership-products/resolvers.js [hunk 2]
```diff
@@ -22,12 +22,18 @@ import { API_STATE_CONNECTED, API_STATE_NOTCONNECTED } from './constants';
 import getConnectUrl from '../../shared/get-connect-url';
 import { PRODUCT_TYPE_PAYMENT_PLAN } from '../../shared/components/product-management-controls/constants';
 import { getMessageByProductType } from '../../shared/components/product-management-controls/utils';
+import executionLock from '../../shared/execution-lock';
+
+const EXECUTION_KEY = 'membership-products-resolver-getProducts';
 
 export const getProducts = (
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/store/membership-products/resolvers.js:29]: This function is very complicated to test in its current state, that's why I haven't added tests for it.

File: projects/plugins/jetpack/extensions/shared/execution-lock.js [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+/**
+ * Block the execution until the locked key is released without blocking the thread.
+ *
+ * @param {string} key - Key that we will wait for release.
+ * @param {number} timeOffset - Amount of time to wait between lock checks.
+ */
+const blockExecution = async ( key, timeOffset = 10 ) => {
+	if ( isLocked( key ) ) {
+		await new Promise( resolve => setTimeout( resolve, timeOffset ) );
```
Comment (rcrdortiz) [inline projects/plugins/jetpack/extensions/shared/execution-lock.js:32]: Tried an exponential backoff approach at first, but it ended up being considerably slower than necessary so I've reverted to a fixed dt.

File: projects/plugins/jetpack/extensions/shared/execution-lock.js [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+};
+
+/**
+ * Block the execution until the locked key is released without blocking the thread.
+ *
+ * @param {string} key - Key that we will wait for release.
+ * @param {number} timeOffset - Amount of time to wait between lock checks.
+ */
+const blockExecution = async ( key, timeOffset = 10 ) => {
+	if ( isLocked( key ) ) {
```
[the remark this answers is not in the document]
Comment (dsas) [reply projects/plugins/jetpack/extensions/shared/execution-lock.js:31]: This comment would be useful in the code 👍

File: projects/plugins/jetpack/extensions/shared/execution-lock.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
+/**
```
Comment (dsas) [inline projects/plugins/jetpack/extensions/shared/execution-lock.js:1]: Maybe this file/directory could do with some documentation with an example use?

Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/shared/execution-lock.js:1]: Do you need more examples besides the ones in the test file? Could you specify any example that you think could add value? I'll add any example requested as a test.

**Review by dsas — COMMENTED** [review]
Looks good to me, and tests fine 👍

File: projects/plugins/jetpack/extensions/shared/execution-lock.js (hunk 5 above)
Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/shared/execution-lock.js:1]: As spoke in person, added a reference to the test file in this file.

File: projects/plugins/jetpack/extensions/shared/execution-lock.js (hunk 1 above)
Comment (rcrdortiz) [reply projects/plugins/jetpack/extensions/shared/execution-lock.js:73]: > I know that this might a bit too late since we already have an implementation. Since by definition having a lock means having a global state, could we change the implementation to avoid making the additional API requests? Right now, the lock just delays the status requests until the first one is finished.

I've thought of this too, I was going to recap some things I've found in a P2. We can't avoid making those requests (at least without adding yet more code specific to it) because of the way the Store works. If I'm not mistaken, when you invoke the getProducts selector if a resolver with the same name exists, the store will return the current state and call the resolvers method asynchronously to update the data.
[This article](https://unfoldingneurons.com/2020/wordpress-data-store-properties-resolvers) I've found explains how a typical store works.

**Review by BogdanUngureanu — APPROVED** [review]
Tests well on Atomic and Simple! 🚢

**Review by kraftbj — APPROVED** [review]

**Comment by rcrdortiz** [comment]
Deployed r244809-wpcom
