### PR TITLE
Popover: React 19 compatibility - modifying component to use refs instead of findDOMNode

### LINKED ISSUE #37408: React-dom `findDOMNode` is being removed in React 19
### Impacted plugin

Jetpack

### Quick summary

In React 19, the react-dom `findDOMNode()` function is being removed. More details on this are at https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-finddomnode

I've already cleaned up most of the uses of `findDOMNode()` in the monorepo in #37380, but I couldn't figure out how to replace the uses in `projects/plugins/jetpack/_inc/client/components/popover/index.jsx`.
https://github.com/Automattic/jetpack/blob/7d3a11fbc8bee13093ed17a18a8764970390f2f9/projects/plugins/jetpack/_inc/client/components/popover/index.jsx#L80-L85
https://github.com/Automattic/jetpack/blob/7d3a11fbc8bee13093ed17a18a8764970390f2f9/projects/plugins/jetpack/_inc/client/components/popover/index.jsx#L246-L251
https://github.com/Automattic/jetpack/blob/7d3a11fbc8bee13093ed17a18a8764970390f2f9/projects/plugins/jetpack/_inc/client/components/popover/index.jsx#L198-L205
Since these are operating on an arbitrary React element passed in, we may need to change the interface for Popover to require an actual DOM node ref or something instead.

While this isn't a problem yet (React 19 is still in beta), eventually WordPress will start shipping it instead of React 18. At that point Popover will break, possibly breaking entire pages, so if we can clean this up ahead of time that would be useful.

### Steps to reproduce

1. `git grep findDOMNode`

### A clear and concise description of what you expected to happen.

No results calling the react-dom function of that name.

### What actually happened

```
projects/plugins/jetpack/_inc/client/components/popover/index.jsx:                      this.domContext = ReactDom.findDOMNode( nextProps.context );
projects/plugins/jetpack/_inc/client/components/popover/index.jsx:                      const ignoreContext = ReactDom.findDOMNode( this.props.ignoreContext );
projects/plugins/jetpack/_inc/client/components/popover/index.jsx:                      this.domContext = ReactDom.findDOMNode( this.props.context );
```

### Impact

All

### Available workarounds?

There is no user impact (yet)

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes https://github.com/Automattic/jetpack/issues/37408

## Proposed changes:

Popover functionality:

* The expected behaviour of the Popover component is that it would not render it's content if `props.isVisible` is not true, or if `props.context` is not a DOM element. If  `props.ignoreContext` is set, the idea here is that clicking inside a DOM element that is set as the ignoreContext will not close the popover.
* There are three components that use Popover: `InfoPopover` which is the primary component I've been testing with (on the Jetpack dashboard), but also `FormToggle`, primarily used in `CompactFormToggle`, itself used in the Privacy class, used on the Privacy settings page - `/wp-admin/admin.php?page=jetpack#/privacy`. And lastly `Tooltip`, primarily used on the at-a-glance stats chart, also on the Jetpack dashboard.

The changed code:

* In the old code, `this.domContext` was assigned either a DOM element directly or the result of `ReactDom.findDOMNode`. The `findDOMNode` method is now considered unsafe and deprecated in strict mode.
* `this.domContextRef` and `this.domContainerRef` are initialized in the constructor. These refs will be used to store references to the DOM elements that the Popover interacts with.
* Technically `domContainer` does not need to be changed into a reference (it does not affect functionality nor result in any issues not to do it), but it makes sense to keep both dom elements as references in order to future-proof it and avoid more issues such as the findDOMNode issue. 
* The third instance where findDOMNode was used, was for `ignoreContext`. With this we're just checking the current value.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/37408

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

Testing functionality:
* With this PR checked out locally or via the Beta tester plugin, ensure that existing Popover functionality has not been changed. An example of where this Popover is used is on the Jetpack dashboard in wp-admin, - see the small info icons. Clicking them should open the Popover, and clicking them again (or elsewhere on the page) should close it.
* Note that the 'createRoot' console error is related to the RootChild component, which the Popover component uses.

Running tests:
* To actually replicate the issue, within a local development environment and with this PR checked out, replace the `popover/index.jsx` code with the existing code: https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/_inc/client/components/popover/index.jsx
* Navigate to the Jetpack plugin folder, and from there run run the following  test - this will run all test-adminpage tests, including the popover tests: `npm run test-adminpage`. 
* Note the three failed tests - in particular the 'should not show Popover when context is not a DOM element' which mentions the findDOMNode is deprecated. The 'should handle ignoreContext correctly' test will also show this same deprecation notice, if the first two tests are commented out (or preceded by 'x', eg `xit( 'should not show Popover`...).  These three (the first two, and the ignoreContext) tests cover two of the three findDOMNode instances in the old code - I was unable to test the third but the logic is the same as in the first example.
* Then, apply the changes to the `popover/index.jsx` file from this PR and run the tests again. They should all pass.

### CODE REVIEW

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 1]
```diff
@@ -78,10 +81,10 @@ class Popover extends Component {
 
 	UNSAFE_componentWillReceiveProps( nextProps ) {
 		// update context (target) reference into a property
-		if ( ! isDOMElement( nextProps.context ) ) {
-			this.domContext = ReactDom.findDOMNode( nextProps.context );
+		if ( ! isDOMElement( nextProps.context ) && nextProps.context !== null ) {
```
Comment (coder-karen) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Technically the null check isn't needed, (`isDOMElement` is `isElement` in `util.js`, and this will return false for null), but it makes it explicit and makes sure the null check will always be considered.

**Review by monsieur-z — DISMISSED** [review]
LGTM 👍

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 2]
```diff
@@ -78,10 +81,10 @@ class Popover extends Component {
...
+			this.domContextRef.current = nextProps.context.current;
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Is this going to work? Or is it likely that `nextProps.context.current` is undefined because `nextProps.context` is some arbitrary React element without a `.current` property?

Possibly we want to do something more like this, if being able to pass a ref is the intention
```js
if ( isDomNode( nextProps.context ) ) {
    this.domContextRef.current = nextProps.context;
} else if ( isRef( nextProps.context ) ) {
    this.domContextRef.current = nextProps.context.current;
    // Or should it be like this so changes to the ref make it in here? I don't really know React.
    this.domContextRef = nextProps.context;
} else if ( nextProps.context !== null ) {
    console.error( 'Expected a DOM node or a React ref', nextProps.context );
}
```

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 3]
```diff
@@ -193,10 +196,12 @@ class Popover extends Component {
...
 	onClickout( event ) {
 		let shouldClose =
-			this.domContext && this.domContext.contains && ! this.domContext.contains( event.target );
+			this.domContextRef.current &&
+			this.domContextRef.current.contains &&
+			! this.domContextRef.current.contains( event.target );
 
 		if ( this.props.ignoreContext && shouldClose ) {
-			const ignoreContext = ReactDom.findDOMNode( this.props.ignoreContext );
+			const ignoreContext = this.props.ignoreContext.current;
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Same here.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 4]
```diff
@@ -241,16 +246,16 @@ class Popover extends Component {
 		this.bindClickoutHandler( domContainer );
 
 		// store DOM element referencies
-		this.domContainer = domContainer;
-
+		this.domContainerRef.current = domContainer;
 		// store context (target) reference into a property
 		if ( ! isDOMElement( this.props.context ) ) {
-			this.domContext = ReactDom.findDOMNode( this.props.context );
+			this.domContextRef.current = this.props.context.current;
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Same here.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 2 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Thank you, yes you're right - the new code assumes that if nextProps.context is not a DOM element, that it is a ref, but it may be neither. I also think the console.error is a good idea, as previously we were logging an error via isDomElement (isElement) if something was not an HTML element, but we need to check for refs here and also want to show an error otherwise so a custom solution is better.

>   Or should it be like this so changes to the ref make it in here? I don't really know React.
Oh , good question. From my testing it doesn't appear to make a difference.

From what I understand, it should be` this.domContextRef.current = nextProps.context.current` because assigning `this.domContextRef` directly to `nextProps.context` is overwriting the `this.domContextRef` reference, not just it's current property.

**Comment by coder-karen** [comment]
PR ready for review again - updated checks based on code reviews, and updated tests.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 2 above)
Comment (anomiex) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: I don't really know how React works, but my thinking was that if someone passes in a ref then they'd probably expect that changes to the ref affect the popover, rather than it using the value of the ref at initialization and then not checking it again when it's time to use it. But maybe React already handles that somehow?

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 5]
```diff
@@ -79,12 +78,24 @@ class Popover extends Component {
 		bindWindowListeners();
 	}
 
+	isDOMNode( obj ) {
+		return obj && obj instanceof HTMLElement;
+	}
+
+	isRef( obj ) {
+		return obj && typeof obj === 'object' && 'current' in obj;
+	}
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Looks like the `obj &&` is probably redundant here. The `instanceof` and `typeof` checks will both do the right thing if it's null or false or undefined or 0.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 6]
```diff
@@ -79,12 +78,24 @@ class Popover extends Component {
...
-			this.domContextRef.current = nextProps.context.current;
-		} else {
+
+		if ( this.isDOMNode( nextProps.context ) ) {
 			this.domContextRef.current = nextProps.context;
+		} else if ( this.isRef( nextProps.context ) ) {
+			this.domContextRef.current = nextProps.context.current;
+		} else if ( nextProps.context !== null ) {
+			// eslint-disable-next-line no-console
+			console.error( 'Expected a DOM node or a React ref', nextProps.context );
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Maybe we should mention "for props.context" or something like that?

(my bad for not including that in my earlier suggestion)

Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Good point, added in cf0e911

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 5 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Thanks for mentioning that, added here: db9b9d6

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 2 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: That's interesting, good point. Still learning and trying to understand this better too myself. And I realize I'm not thinking about cases when the ref itself would actually change. 

When the context prop changes, the `componentDidUpdate` function should run, and it should be possible to use that to update` this.domContextRef.current`.

Given that componentDidUpdate is [what is called after re-rendering due to a change in props or state](https://reactjs.org/docs/react-component.html#componentdidupdate) - and also given that `UNSAFE_componentWillReceiveProps` is legacy, adding this logic to `componentDidUpdate` should help make this a little more future proof too - and we can assign to .current in that case. And I believe we can remove `UNSAFE_componentWillReceiveProps` too with the snippet added to `componentDidUpdate`.

`setDOMBehaviour` looks like it only runs on construction so I've left that.

That all said and done, I wonder if it's worth bringing an internal React expert in to double check this perhaps 🤔

Comment (anomiex) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: > That all said and done, I wonder if it's worth bringing an internal React expert in to double check this perhaps 🤔

Sounds like a good plan to me!

Or what are the callers of this? Could we have the callers pass `whateverRef.current` so Popover only takes DOM nodes?

Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: > Or what are the callers of this? Could we have the callers pass whateverRef.current so Popover only takes DOM nodes?

Good point.

So as it turns out, all three callers of Popover already pass whateverRef.current. `ModuleChartBar`, used on the at-a-glance stats page, passes context as `this.valueBarRef.current` already. The `FormToggle` passes context as `this.toggleSwitchRef.current`. The `InfoPopover` passes context as `this.infoPopoverRef.curren`t.

The expected behaviour then is to pass in a DOM node, not a ref. So there is no need to create a workaround for refs, and it'd also be good to note that we expect DOM nodes too (perhaps that's clear with the new console.error messages but I added to some other comments with more context).

What I've done now to be safe is go back to using `UNSAFE_componentWillReceiveProps`, and I'll also see if I can 
 find someone with more React knowledge can confirm it really is safe to move the checks from `UNSAFE_componentWillReceiveProps` into `componentDidUpdate`, otherwise will keep it where it now is.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 7]
```diff
@@ -240,17 +258,18 @@ class Popover extends Component {
...
+		if ( this.isDOMNode( this.props.context ) ) {
+			this.domContextRef.current = this.props.context;
+		} else if ( this.props.context !== null ) {
+			// eslint-disable-next-line no-console
+			console.error( 'Expected a DOM node for props.context', this.props.context );
 		}
 
-		this.domContainer.focus();
+		this.domContainerRef.current.focus();
+		//this.domContainer.focus();
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Commented line:
```suggestion
```

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 8]
```diff
@@ -76,12 +80,18 @@ class Popover extends Component {
...
-		// update context (target) reference into a property
-		if ( ! isDOMElement( nextProps.context ) ) {
-			this.domContext = ReactDom.findDOMNode( nextProps.context );
-		} else {
-			this.domContext = nextProps.context;
+		// update context (target - expecting a DOM node not a ref) reference into a property
+
+		if ( this.isDOMNode( nextProps.context ) ) {
+			this.domContextRef.current = nextProps.context;
+		} else if ( nextProps.context !== null ) {
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Could `nextProps.context` be `undefined` (not provided)? It seems like that may be a valid next `context`. Should the error be shown if `context` is not provided?

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 9]
```diff
@@ -76,12 +80,18 @@ class Popover extends Component {
...
+			// eslint-disable-next-line no-console
+			console.error( 'Expected a DOM node for props.context', nextProps.context );
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: I want to confirm it's intentional to introduce a new `console.error` here.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 10]
```diff
@@ -193,15 +203,23 @@ class Popover extends Component {
 
 	onClickout( event ) {
 		let shouldClose =
-			this.domContext && this.domContext.contains && ! this.domContext.contains( event.target );
+			this.domContextRef.current &&
+			this.domContextRef.current.contains &&
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: This can likely be an optional chain:

```suggestion
			this.domContextRef.current?.contains &&
```

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 11]
```diff
@@ -193,15 +203,23 @@ class Popover extends Component {
...
-				shouldClose &&
-				ignoreContext &&
-				ignoreContext.contains &&
-				! ignoreContext.contains( event.target );
+			let ignoreContext;
+			if ( this.isDOMNode( this.props.ignoreContext ) ) {
+				ignoreContext = this.props.ignoreContext;
+			} else {
+				// eslint-disable-next-line no-console
+				console.error( 'Expected a DOM node for ignoreContext', this.props.ignoreContext );
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Confirming whether this new console message is intentional.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 12]
```diff
@@ -240,17 +258,18 @@ class Popover extends Component {
 
 		this.bindClickoutHandler( domContainer );
 
-		// store DOM element referencies
-		this.domContainer = domContainer;
-
+		// store DOM element referencies - note we expect DOM nodes not refs.
```
Comment (sirreal) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Typo (pre-existing)
```suggestion
		// store DOM element references - note we expect DOM nodes not refs.
```

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 13]
```diff
@@ -76,12 +80,18 @@ class Popover extends Component {
...
-		} else {
-			this.domContext = nextProps.context;
+		// update context (target - expecting a DOM node not a ref) reference into a property
+
+		if ( this.isDOMNode( nextProps.context ) ) {
+			this.domContextRef.current = nextProps.context;
+		} else if ( nextProps.context !== null ) {
+			// eslint-disable-next-line no-console
+			console.error( 'Expected a DOM node for props.context', nextProps.context );
 		}
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Looking at this again, we lost assigning the null if it is null. I think I left that out of my original suggestion.

Now that we dropped handling refs, it's easy to fix.

```suggestion
		if ( nextProps.context === null || this.isDOMNode( nextProps.context ) ) {
			this.domContextRef.current = nextProps.context;
		} else {
			// eslint-disable-next-line no-console
			console.error( 'Expected a DOM node for props.context', nextProps.context );
		}
```

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 14]
```diff
@@ -240,17 +258,18 @@ class Popover extends Component {
...
-		if ( ! isDOMElement( this.props.context ) ) {
-			this.domContext = ReactDom.findDOMNode( this.props.context );
-		} else {
-			this.domContext = this.props.context;
+		if ( this.isDOMNode( this.props.context ) ) {
+			this.domContextRef.current = this.props.context;
+		} else if ( this.props.context !== null ) {
+			// eslint-disable-next-line no-console
+			console.error( 'Expected a DOM node for props.context', this.props.context );
 		}
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]:
```suggestion
		if ( this.props.context === null || this.isDOMNode( this.props.context ) ) {
			this.domContextRef.current = this.props.context;
		} else {
			// eslint-disable-next-line no-console
			console.error( 'Expected a DOM node for props.context', this.props.context );
		}
```

**Review by sirreal — COMMENTED** [review]
I've reviewed the component changes and left some notes. There are some plain `console` messages that should probably use `this.debug` like the component uses elsewhere.

Most of the component changes seem reasonable from a React/JS perspective. I have not done any manual testing and I'm not familiar with current development practices of this project.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 13 above)
Comment (anomiex) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Or, as @sirreal mentioned in a comment while I was writing this, maybe we should just check for `! nextProps.context` instead of `nextProps.context === null` to handle undefined too.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 7 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Good catch, thanks. Removed in [fa42b41](https://github.com/Automattic/jetpack/pull/38339/commits/fa42b41d814c6777778c3a6fd3babce182b8d5ed)

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 8 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Yes good point, I've added in the check for that that @anomiex suggested here: https://github.com/Automattic/jetpack/pull/38339#discussion_r1686639992. Added in [6d201aa](https://github.com/Automattic/jetpack/pull/38339/commits/6d201aae0ab20583b2fddcb0be6d7f132e7e99c9) and further cleaned up in [4a6f8ce](https://github.com/Automattic/jetpack/pull/38339/commits/4a6f8ce8817c057ddceca7b3369b5b1fc81358ed)

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 9 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Yes that was intentional, but using debug works just as well now that I've looked into how to test for it as well, thanks! Added in [bdc9a33](https://github.com/Automattic/jetpack/pull/38339/commits/bdc9a33b2cc16693b190d0f528aeb6994274ad90)

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 10 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Nice, added in [e44145f](https://github.com/Automattic/jetpack/pull/38339/commits/e44145f41a553458d5647fc60cd0670e300c00a1)

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 11 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Yes but modified now (see above).

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx (hunk 13 above)
Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Nice catch, thank you.

File: projects/plugins/jetpack/_inc/client/components/popover/index.jsx [hunk 15]
```diff
@@ -53,6 +52,8 @@ class Popover extends Component {
 	constructor( props ) {
 		super( props );
 
+		this.props;
```
Comment (anomiex) [inline projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: What's this for?

Comment (coder-karen) [reply projects/plugins/jetpack/_inc/client/components/popover/index.jsx]: Huh. Looking through the commits, it makes no sense to be added when it was. It looks like - well I'm not sure what it looks like, some kind of odd copy-paste in the wrong place perhaps. Anyway, absolutely no reason for it. Removed in [9261846](https://github.com/Automattic/jetpack/pull/38339/commits/926184627baeb6f37839a85951177aec67f88527)

**Review by anomiex — APPROVED** [review]
Looks reasonable, and seems to work.
