### PR TITLE
Infinite Scroll: Set the number of posts for the 'click' option to the global setting

### LINKED ISSUE #16471: Infinite Scroll: Unprompted changes to number of posts shown per page.
Recent changes to Jetpack's Infinite Scroll seem to have caused some issues with the number of posts appearing on sites. The theme hasn't changed, but with this update, sites went from displaying 12 posts per page, to only showing 8.

#### Steps to reproduce the issue

1. Use Pictorico + Jetpack
2. Choose to show 12 posts per page (this is how the demo is configured)
3. Note with IS on, we only see 8 posts. Or 9. It's a bit random from site to site. If we disable infinite scroll, it works as expected.

#### What I expected
For the number of posts displayed to stay the same even after updating Jetpack.

#### What happened instead
The number of posts on the front page changed. Disabling Infinite Scroll, or disabling Jetpack on my .org test site, seems to address it.

**Screenshots**
Here's a screenshot from our showcase page:
pictorico

Here's a screenshot from the live showcase. Neither Pictorico nor its settings have been updated
screencapture-pictoricodemo-wordpress-2020-07-13-11_50_37
 anytime recently.

### Context
User complaints:
https://wordpress.com/forums/topic/pictorio-theme-grid-on-homepage/
3135164-zen

### PR DESCRIPTION
**Pull request by scruffian**
#9120 made a change to Infinite Scroll which changed the behaviour for the "click" option.

#### Changes proposed in this Pull Request:

This reinstates only behaviour in Infinite Sroll thus:

If infinite scroll is set to `click` and the user has a `posts_per_page` setting which is different from the default (10) then use that instead of the theme value.

cc @mikejolley

Fixes #16471

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:

* Choose a theme that supports infinite scroll (e.g. Pictorico)
* Turn on Infinite Scroll with this setting: "Load more posts in page with a button"
* Change the posts per page setting on wp-admin/options-reading.php to a number that isn't 10
* Check that this number of posts loads on the frontend.

#### Proposed changelog entry for your changes:

* Load the user's setting for posts per page in Infinite Scroll if it's not the default

### CODE REVIEW

File: modules/infinite-scroll/infinity.php [hunk 1]
```diff
@@ -251,7 +251,15 @@ static function get_settings() {
 	static function posts_per_page() {
 		$posts_per_page = self::get_settings()->posts_per_page ? self::get_settings()->posts_per_page : self::wp_query()->get( 'posts_per_page' );
 
-		// Take JS query into consideration here
+		// If Infinite Scroll is set to click, and if the site owner changed posts_per_page, let's use that.
+		if (
+			'click' === self::get_settings()->type
+				&& ( '10' !== get_option( 'posts_per_page' ) )
```
Comment (jeherve) [inline modules/infinite-scroll/infinity.php:257]: Should we use `self::wp_query()->get( 'posts_per_page' )`, or `$posts_per_page` as used above? I'm not super clear on what's the difference here?

Comment (scruffian) [reply modules/infinite-scroll/infinity.php:257]: My understanding is that  `self::get_settings()->posts_per_page` is the setting that gets declared when the theme registers support for infinite scroll, whereas `self::wp_query()->get( 'posts_per_page' )` is the number of posts that the query in the current loop is getting. The idea of this line is to get the setting from `wp-admin/options-reading.php` rather than whatever the theme registered, so that users can change it from the default if they want.

The problem with this approach is that if the theme registers a value which is not the default and the users wants the default, they won't be able to.

Comment (kraftbj) [reply modules/infinite-scroll/infinity.php:257]: We're calling `get_option` twice in short succession for the same option. Could we just put the value in a local var and use that?

Comment (scruffian) [reply modules/infinite-scroll/infinity.php]: Done in 2577ee812

**Review by tjcafferkey — APPROVED** [review]
Tested and LGTM 👍🏻

**Review by kraftbj — APPROVED** [review]

**Comment by kraftbj** [comment]
IS on WP.com is really divergent. Tomorrow, I'll check it out and clear our the wp.com block.

**Comment by kraftbj** [comment]
r215511-wpcom
