### PR TITLE
Hide sharing buttons in Blog Posts block in the editor

### LINKED ISSUE #25329: Sharing buttons: Specific sharing configuration results in misleading page editor display
### Impacted plugin

Jetpack

### Steps to Reproduce

This issue is specific to a particular configuration of sharing settings. While this can be replicated in both beta and previous versions of Jetpack and there are existing, similar issues, this issue is more pronounced as a result of this PR - https://github.com/Automattic/jetpack/pull/24896 - because sharing buttons now shouldn't display at all on pages with the Blog Posts block.

1. On a Jetpack connected site, make sure Sharing and / or Like buttons are enabled via Jetpack > Settings > Sharing.
2. From Settings > Sharing, make sure 'Front Page, Archive Pages, and Search Results' is checked, as well as Posts. 
3. Add and activate the WordPress.com Editing Toolkit plugin.
4. Add a new page, and add a Blog Posts block.
5. In the page editor, you should see some unformatted sharing / like button output. 
6. On the page preview / frontend, you should not see the sharing buttons / likes (if testing with 11.2-beta).
7. From Settings > Sharing, disable 'Front page, Archive Pages, and Search results' and the page editor should go back to it's normal view (no sharing / like button output).

It looks like this might be the case on all themes - all that I've tested so far display this behavior:  Twenty Twenty One, Astra, BlockBase, Twenty Twenty Two, Twenty Twenty, Twenty Nineteen.

This was reported internally here: p8oabR-Uj-p2#comment-6512

### A clear and concise description of what you expected to happen.

No sharing / like button output should show in the page editor at all.

### What actually happened

Sharing / like button output is showing in the page editor.

### Browser

Google Chrome/Chromium

### Other information

The output in the editor looks like this:
Screenshot 2022-07-29 at 12 19 06

There are two other related issues at the moment:
- https://github.com/Automattic/jetpack/issues/24254
- https://github.com/Automattic/jetpack/issues/7361

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by wojtekn**
Fixes https://github.com/Automattic/jetpack/issues/25329

#### Changes proposed in this Pull Request:

* Blog Posts block is rendered in the editor via REST request and still displays sharing buttons. I'm adding additional checks to remove those from the editor, to match frontend behavior.

#### Other information:

- [ ] ~~Have you written new tests for your changes, if applicable?~~
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

1. Start a Jetpack environment
2. Go to WP Admin
3. Install a WordPress.com Editing Toolkit plugin
4. Enable Sharing buttons in Jetpack -> Settings -> Sharing (works in Jetpack's offline mode)
5. Configure sharing buttons to display them on "Front Page, Archive Pages, and Search Results", "Posts", and "Pages"
6. Add a new page with a Blog Posts block (and not Posts Lists)
7. Confirm sharing buttons are not displayed under each post in the list of posts in the block shown in the editor

Screen Shot 2022-08-01 at 12 42 04

Alternatively, use an Atomic site with the Jetpack Beta plugin and use this PR branch there.

### CODE REVIEW

File: projects/plugins/jetpack/modules/sharedaddy/sharing-service.php [hunk 1]
```diff
@@ -942,6 +942,11 @@ function sharing_display( $text = '', $echo = false ) {
 		return $text;
 	}
 
+	// Prevent from rendering sharing buttons in block which is fetched from REST endpoint by editor
+	if ( defined( 'REST_REQUEST' ) && REST_REQUEST ) {
```
Comment (danielbachhuber) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: @coder-karen @jeherve Just to confirm, we'd like to _always_ remove the share buttons in REST API responses?

If we wanted to sometimes include share buttons in the REST API response, an alternative approach might be:
1. Only include share buttons in the REST API response when share buttons are enabled for the post type.
2. Don't ever include share buttons in the REST API response when it's a dynamic block request.

Comment (coder-karen) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: 🤔  I should think we'd not want it in the REST API response, but if we did it would be when they're enabled for the post type.

Comment (samiff) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: Given that the injected sharing buttons require enqueued JS to function further down in the chain, I'm not sure why anyone would want the button content to show up in REST API responses 🤔 

This tested well for me, and I think it'd be safe to ship and observe for any issue requests that pop up.

**Review by samiff — DISMISSED** [review]

File: projects/plugins/jetpack/modules/sharedaddy/sharing-service.php (hunk 1 above)
Comment (wojtekn) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: When the editor requests this block, it appends the `context` GET param set to the `edit` value. I could include it in the condition to address @danielbachhuber concerns. What do you think?

Comment (coder-karen) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: That could work, assuming the main intention is to hide the sharing buttons in the editor. That would tie in with the original linked issue.

Perhaps determining which REST API conditions to include sharing buttons in could be for a separate PR, with this one just removing them from the editor. That said I'll be releasing 11.2 in a few hours so I'm not sure if any of this should be a blocker. Given that the issue itself (share button output in the editor) has been around for quite some time it may be better that I don't try to rush this in to 11.2, then we can make sure all cases are covered.

Comment (coder-karen) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: Or I can just merge as is, like @samiff suggested we can look out for any issues as is, though we could perhaps refine what we do and don't want to include in a further PR. I'll do this then unless anything comes up in the next few hours.

Comment (wojtekn) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: @coder-karen I've just added that additional check and retested it - it still works as expected.

Comment (coder-karen) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-service.php]: Yes it does. I'll merge this as is, then I think we can follow up in another PR should we need to be stricter with the REST API conditions.

**Review by coder-karen — APPROVED** [review]

**Comment by wojtekn** [comment]
r249967-wpcom

**Comment by coder-karen** [comment]
Cherry-picked to release branch in b3b1455cce35a2508a801a3d90bb85b902a5ceba
