### PR TITLE
Search: Fix chosen filter options not visible when no results returned

### LINKED ISSUE #14179: Instant Search: always show filters
#### Steps to reproduce the issue

- In the demo select the filter "Media".
- Search for "css".

#### What I expected

I would expect the filters list to still be visible.

#### What happened instead

The filters are hidden, preventing me from broadening my query.

Also note that the query is `?post_types=attachment&s=css` but the UI doesn't reflect that, showing nothing but an search box with “css”.

image

#### Screen capture

jps-filters-01

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #14179 and partially fixes `pcNPJE-av-p2`

#### Changes proposed in this Pull Request:
The PR proposed a solution where the frontend cache the Aggregations object, and then use it to to still show the filters when there's no result. When the overlay opens, the cache would be cleared.

The patch only works when there's no result and there are filters in the URL, so it wouldn't affect normal search flow.

I considered to put the filter label in the URL, but which could potentially cause XSS issue or show unwanted content on the page.

Another solution would be mapping the filters on the backend, which basically requires a re-write of a few frontend parts in PHP, not very ideal considering the PR is just a workaround.

The ultimate solution would be changes from the Search API side, and return filters including counts on all requests, which would need support from elastic search side.

The PR does NOT fix the issue when empty search results is shared by URL, because I think this situation is relatively rare, because if there's no results, people wouldn't tend to share it.

#### Jetpack product discussion
pcNPJE-av-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to a site with Jetpack subscription
- Search something and then check one/more filter options
- Continue to enter the query until there's no results
- Ensure the filters are still visible for users to uncheck
- Ensure the filters work as expected

Screen Capture on 2021-08-16 at 18-40-54

### CODE REVIEW

**Comment by annacmc** [comment]
I gave this a spin on desktop & mobile and in both cases it worked as expected for me 😄

**Review by samiff — DISMISSED** [review]
This worked well for me 👍 

Looks like there are a couple `modules/search/instant-search/store/test/reducer.test.js` tests failing here though, could you have a look @kangzj thanks!

**Review by jsnmoon — COMMENTED** [review]
This change works exactly as described, enabling users to deselect overly restrictive filters when there are no search results. 

Here's a UX improvement I'd like to propose, which should fully address #14179: What do you think about caching all the aggregations, all the time? Here's an example to illustrate what I mean:

<table>
<tr>
	<td> 
Screen Shot 2021-09-01 at 5 40 51 PM

We start with an empty query, which shows all possible aggregations for the site.

<tr>
	<td>
Screen Shot 2021-09-01 at 5 40 57 PM

I enter a query for "home" and all aggregations that no longer apply are removed from the sidebar.
<tr>
	<td>
Screen Shot 2021-09-01 at 5 40 59 PM

Suggested change: Instead of removing the aggregations, what if we kept them and disabled checkboxes for buckets without any results? In other words, we would always show all aggregations, all the time.
</table>

One potential issue I see with this approach is that it could get unwieldy for month or year date filters. In order to allow site owners to deal with this, we could:

1. Add a class name to the SearchFilter container (e.g. `jetpack-instant-search__search-filter`).
2. Add a class name to individual filter options (e.g. `jetpack-instant-search__search-filter-bucket`).
3. Add an additional class name to individual filter options with 0 results (e.g. `jetpack-instant-search__search-filter-bucket--empty`).

This will enable site owners to manually hide the excess checkboxes via CSS when appropriate.

**Comment by kangzj** [comment]
> Here's a UX improvement I'd like to propose, which should fully address #14179: What do you think about caching all the aggregations, all the time? Here's an example to illustrate what I mean:

Hi @jsnmoon thanks for the suggestions. I tried to cache all the aggregations before, it worked. But we'll have to consider more situations. For example, ordering, say if an option is selected we have to promote it to be visible because there are limitation on number of filter options etc. And also it could end up in a very long empty list which doesn't make a lot of sense. 
I'm sure there are a lot to improve for the current solution, but considering it's a temporary solution, I don't think we'll want to put that much time in, do we?

>  disabled checkboxes for buckets without any results

This is added.

And I had another thought about it, changed the following.
- We don't really need to put the cached aggregations in the state - a local variable works just fine. 
- Unit test added

Let me know what you think, thanks.

File: projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js [hunk 1]
```diff
@@ -63,16 +64,57 @@ export function response( state = {}, action ) {
...
+/**
+ * The function only merge on the top level, it doesn't merge the buckets.
+ * Tried to merge the buckets, but which seems a bit bumpy.
+ * Note: doc_count of cached aggregations is always set to 0.
+ *
+ * @param {object} previousCachedAggregations - Cached aggregations.
+ * @param {object} newAggregations - New aggregations to merge.
+ * @returns {object} Merged aggregations.
+ */
+function mergeCachedAggregations( previousCachedAggregations, newAggregations ) {
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js:105]: Could we add a unit test for this function?

**Review by jsnmoon — COMMENTED** [review]
> I tried to cache all the aggregations before, it worked. But we'll have to consider more situations. For example, ordering, say if an option is selected we have to promote it to be visible because there are limitation on number of filter options etc. And also it could end up in a very long empty list which doesn't make a lot of sense. (@kangzj)

Fair points. In that case, shipping this implementation and continuing to iterate makes a lot of sense. I left a comment inline requesting one small change, but everything else looks good to go with this PR.

**Comment by samiff** [comment]
@kangzj Were you hoping to get this PR into Jetpack 10.2? If so, the code freeze date is: 2021-09-28 Please add the `[Status] Needs review` label once it's ready for Crew to have a look 👍

**Comment by kangzj** [comment]
> @kangzj Were you hoping to get this PR into Jetpack 10.2? If so, the code freeze date is: 2021-09-27

Hi @samiff thanks for the kind reminder. I'll still have to revisit this to make sure it works as expected. Will try to make it in 10.2. Thanks

**Comment by kangzj** [comment]
Added unit test and rebased.

File: projects/plugins/jetpack/modules/search/instant-search/lib/api.js [hunk 2]
```diff
@@ -43,6 +43,28 @@ export function buildFilterAggregations( widgets = [] ) {
...
 }
 
+/**
+ * The function set the aggregation count to zero which is just meant for users to uncheck.
+ * Tried to merge the buckets, but which ended up showing too many filters.
+ *
+ * @param {object} newAggregations - New aggregations to operate on.
+ * @returns {object} - Aggregations with doc_count set to 0.
+ */
+export function setAggregationCountToZero( newAggregations ) {
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/lib/api.js:53]:
```suggestion
export function setDocumentCountsToZero( newAggregations ) {
```

File: projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js [hunk 3]
```diff
@@ -63,13 +69,28 @@ export function response( state = {}, action ) {
...
 
 			// To prevent our interface from erroneously rendering a "no result" search results page when
 			// we actually have results, override the total if the size of our results exceed the `response.total` value.
 			if ( Array.isArray( newState.results ) && newState.results.length > newState.total ) {
 				newState.total = newState.results.length;
 			}
+
+			// If it's a new search - not pagination requests
+			// - we cache the query aggregations if there are results
+			// - we use the cache to show filters if there are not results
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/store/reducer/api.js:83]:
```suggestion
			// For a new search requests (i.e. not pagination requests):
			// - Cache aggregations if query yields results
			// - Show previously cached aggregations if query does not yield any results
```

File: projects/plugins/jetpack/modules/search/instant-search/store/test/reducer.test.js [hunk 4]
```diff
@@ -189,6 +189,31 @@ describe( 'response Reducer', () => {
 		);
 		expect( state ).toEqual( initialState );
 	} );
+	test( 'could replace aggregation with cached aggregation when result is empty', () => {
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/instant-search/store/test/reducer.test.js:192]:
```suggestion
	test( 'returns cached aggregations when no search results are available', () => {
```

**Review by jsnmoon — COMMENTED** [review]
Looks good to me. Feel free to mark for crew review whenever you're ready.

I left some nitpicky suggestions for improving code readability.

File: projects/plugins/jetpack/modules/search/instant-search/lib/api.js (hunk 2 above)
Comment (kangzj) [reply projects/plugins/jetpack/modules/search/instant-search/lib/api.js]: changed in d5c06c86c5

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 🚢

**Comment by kangzj** [comment]
🚢 r232807-wpcom
