### PR TITLE
Social: Hide license link on Social admin page of WoA sites

### LINKED ISSUE #98217: Unable to access "Activate a Plan" link when WordPress.com interface style is enabled General Settings
### Quick summary

Users are unable to access the "Activate a Plan" link in Jetpack → Social when the WordPress.com interface is enabled for their site dashboard. The error displayed is:

> Sorry, you’re not allowed to access this page.

This issue is resolved when the user switches to the classic WP-admin interface.

### Steps to reproduce

1. Enable the WordPress.com interface for the site dashboard (via https://wordpress.com/settings/general/[site-domain] and selecting "WordPress.com" under "Admin interface style").

Image

2. Make sure you have the Jetpack plugin installed and active.
3. Navigate to Jetpack → Social.
4. Attempt to click the "Activate a Plan" link.
Image

4. Observe the error message: "Sorry, you’re not allowed to access this page."

Image

### What you expected to happen

The link to activate the plan should work as expected. 

### What actually happened

The link opens a page showing ""Sorry, you’re not allowed to access this page.""

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes https://github.com/Automattic/wp-calypso/issues/98217

## Proposed changes:

* Adds a `is_woa_site` flag to the `window.JetpackScriptData.social` global
* Hide the `Already have an existing plan or license key?` link on the Social plugin's admin page when the site is hosted on WoA

CleanShot 2025-01-15 at 16 10 30@2x

Hiding the license link in the admin page is the approach that Jetpack Boost took here when it had the equivalent issue here https://github.com/Automattic/jetpack/pull/36434

AFAICT there isn't an existing way to check whether the site is hosted on WoA in the client, so, like Boost, we have to add something to a global. (Boost uses it's own `window.Jetpack_Boost` global which contains this data https://github.com/Automattic/jetpack/blob/ee9ed011674ce216aa9e19dde49e2a1cc3effcfc/projects/plugins/boost/app/assets/src/js/lib/utils/hosting.ts#L16)

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

The issue described in https://github.com/Automattic/wp-calypso/issues/98217 is that the user can end up on an access denied page after clicking the `Add an existing license` link.

image

This is because the `My Jetpack` page is hidden on WoA sometimes; specifically when the admin interface style is set to "Default" (aka use Calypso instead of wp-admin)

There's been discussion here https://github.com/Automattic/wp-calypso/issues/98217#issuecomment-2589328809 and here https://github.com/Automattic/dotcom-forge/issues/5663#issuecomment-1953388803 about whether we should just open up the `My Jetpack` page in all cases. This PR doesn't answer that discussion.

## Does this pull request change what data or activity we track or use?

Nope

## Testing instructions:

* Follow [these instructions](https://github.com/Automattic/jetpack/pull/41076#issuecomment-2591550308) for setting up this diff on your WoA test site
* The standalone Jetpack Social plugin needs to be installed
* Nav to `/wp-admin/admin.php?page=jetpack-social`
* Confirm the `Already have an existing plan or license key?` link is hidden
* Test using `jurassic.ninja`; the link should appear

### CODE REVIEW

File: projects/packages/publicize/src/class-publicize-script-data.php [hunk 1]
```diff
@@ -100,6 +100,7 @@ public static function get_admin_script_data() {
 			'shares_data'          => array(),
 			'urls'                 => array(),
 			'settings'             => self::get_social_settings(),
+			'is_woa_site'          => ( new Host() )->is_woa_site(),
```
Comment (manzoorwanijk) [inline projects/packages/publicize/src/class-publicize-script-data.php]: Instead of adding this boolean flag here, we can add it inside that [`set_admin_script_data` method here](https://github.com/Automattic/jetpack/blob/4f7022d9d796be0ff70c83aaf5ef66dcdfbcc5fc/projects/packages/publicize/src/class-publicize-script-data.php#L74).

```php
if ( ! isset( $data['site']['host'] ) ) {
	$data['site']['host'] = ( new Host() )->get_known_host_guess();
}
```

File: projects/js-packages/publicize-components/src/types.ts [hunk 2]
```diff
@@ -54,4 +54,5 @@ export interface SocialScriptData {
 	store_initial_state: SocialStoreState;
 	supported_services: Array< ConnectionService >;
 	urls: SocialUrls;
+	is_woa_site: boolean;
```
Comment (manzoorwanijk) [inline projects/js-packages/publicize-components/src/types.ts]: After making that host data change below, we can add the `host` property to [`AdminSiteData` interface](https://github.com/Automattic/jetpack/blob/2b94898223dd1a64e0b6d722bcf9b03908f13b8d/projects/js-packages/script-data/src/types.ts#L18). 

```ts
host: 'woa' | 'atomic' | 'newspack' | 'vip' | 'wpcom' | 'unknown';
```

File: projects/plugins/social/src/js/components/admin-page/header/index.jsx [hunk 3]
```diff
@@ -7,14 +7,15 @@ import styles from './styles.module.scss';
...
+	const isWoaSite = Boolean( window.JetpackScriptData?.social?.is_woa_site );
 
 	return (
 		<div className={ styles.header }>
 			<span className={ styles.logo }>
 				<Logo />
 			</span>
 
-			{ ! hasSocialPaidFeatures() && (
+			{ ! hasSocialPaidFeatures() && ! isWoaSite && (
```
Comment (manzoorwanijk) [inline projects/plugins/social/src/js/components/admin-page/header/index.jsx]: Then here we can use `! getScriptData().site.host !== 'woa'` after

`import { getScriptData } from '@automattic/jetpack-script-data';`

**Review by manzoorwanijk — COMMENTED** [review]
This looks good and a reasonable change. Thank you for fixing it.

As you mentioned

> AFAICT there isn't an existing way to check whether the site is hosted on WoA in the client, so, like Boost, we have to add something to a global. (Boost uses it's own window.Jetpack_Boost global which contains this data

There are always multiple versions of the same data passed to the client and for this reason, we decided to consolidate the initial state for Jetpack - pdWQjU-11v-p2.

So, since that flag you added is not specific to social, let us add it to some place where it can be used by other areas of the codebase.

After the suggested changes, we can have this

Screenshot 2025-01-15 at 10 09 26 AM

**Review by agrullon95 — DISMISSED** [review]
I tested on my atomic site and can confirm the link is no longer visible.
The link is a visible and navigating to the correct location when I tested with Jurassic NInja

**Comment by manzoorwanijk** [comment]
@p-jackson Please let me know if I should make those changes for you.

File: projects/packages/publicize/src/class-publicize-script-data.php (hunk 1 above)
Comment (p-jackson) [reply projects/packages/publicize/src/class-publicize-script-data.php]: By extending the `JetpackScriptData` interface to include the `host` value too, is your intention that Boost should move over to using it too? I'd be happy to make that change too, but would that be considered too much of a breaking change? (since the over-the-wire format would be changing).

In which case, would it be better to add the `host` value here?
https://github.com/Automattic/jetpack/blob/ee9ed011674ce216aa9e19dde49e2a1cc3effcfc/projects/packages/assets/src/class-script-data.php#L110

_Or_ (in keeping with the filter documentation that we should only enqueue data we _know_ will be used) should both the Social and Boost plugins both independently add the `host` data in the `jetpack_admin_js_script_data` filter. So that when neither plugin is installed the data won't be present.

Some data is always added, whether it's used or not (like `wp_version`, `is_multisite`), but maybe those are more fundamental than the host.

Comment (manzoorwanijk) [reply projects/packages/publicize/src/class-publicize-script-data.php]: > By extending the `JetpackScriptData` interface to include the `host` value too, is your intention that Boost should move over to using it too? I'd be happy to make that change too, but would that be considered too much of a breaking change? (since the over-the-wire format would be changing).

I don't mean to change anything in Boost right now. I think that has been in Boost for a while. I mean to say that we just don't make that data specific to Social. Boost can later refactor to use that shared value from `JetpackScriptData`

> In which case, would it be better to add the `host` value here?

That will require the `status` package to be a dependency for the `assets` package, which we don't want for this small change. At least not as a part of this PR.

> _Or_ (in keeping with the filter documentation that we should only enqueue data we _know_ will be used) should both the Social and Boost plugins both independently add the `host` data in the `jetpack_admin_js_script_data` filter. So that when neither plugin is installed the data won't be present.

Yes, let the package that needs it, add it to the data.

Comment (p-jackson) [reply projects/packages/publicize/src/class-publicize-script-data.php]: Thanks for the clarification. I'll rein in the scope of where I was starting to go with this PR 😄

File: projects/js-packages/script-data/src/types.ts [hunk 4]
```diff
@@ -18,6 +18,7 @@ export interface PublicSiteData {
 export interface AdminSiteData {
 	admin_url: string;
 	date_format: string;
+	host: 'woa' | 'atomic' | 'newspack' | 'vip' | 'wpcom' | 'unknown';
```
Comment (manzoorwanijk) [inline projects/js-packages/script-data/src/types.ts]: Let us make this optional as it actually is from the backend.

```suggestion
	host?: 'woa' | 'atomic' | 'newspack' | 'vip' | 'wpcom' | 'unknown';
```

**Review by manzoorwanijk — DISMISSED** [review]
This looks good. Thank you for the fix.

I just have another optional suggestion.

Thank you for making the suggested changes.

File: projects/js-packages/script-data/src/types.ts (hunk 4 above)
Comment (p-jackson) [reply projects/js-packages/script-data/src/types.ts]: In practice everything in `AdminSiteData` is optional since it's included in the `JetpackScriptData` interface using `Partial< ... >`.

But perhaps this makes it clearer that this property is even more optional than the other optional properties.

Comment (manzoorwanijk) [reply projects/js-packages/script-data/src/types.ts]: Yeah, thanks. I am fine with both.

**Comment by p-jackson** [comment]
> Thank you for making the suggested changes.

No problem, I like this better

**Review by manzoorwanijk — APPROVED** [review]
This will require an Atomic release, right?

**Comment by p-jackson** [comment]
> This will require an Atomic release, right?

I don't believe so. It's not part of `wpcomsh`. It will just roll out whenever the stand alone Social plugin usually rolls out right? Jetpack Social is not a plugin "managed" by the Atomic platform, so it doesn't have a way of updating this plugin sooner than it coming out in the dotorg repo.

**Comment by manzoorwanijk** [comment]
Yeah, makes sense. Thanks.

**Review by manzoorwanijk — CHANGES_REQUESTED** [review]
Please hold off merging this. We are discussing it in our team call. 

That nudge might be valid. I will get back to you on this.

**Review by manzoorwanijk — APPROVED** [review]
OK, this can be shipped now. We had recently enabling purchasing of Social plans for Atomic sites and were wondering if that nudge is valid, but since they can't access the page, it's better to hide it. Sorry for keeping you waiting.

**Comment by p-jackson** [comment]
Sounds good, thanks for the reviews!
