### PR TITLE
Contact Form: replace jQuery UI select by native element

### LINKED ISSUE #34253: Contact Form: dropdown error message is not accessible
### Impacted plugin

Jetpack

### Quick summary

The error message of the dropdown field in the Form package is not accessible. Screen readers do not read it, nor is the input announced as invalid.

### Steps to reproduce

1. Create a new post.
2. Add a form from the Form block.
3. Add a dropdown and mark it as required.
4. Visit the post preview and open a screen reader.
5. Submit the post. You should get an error message.
6. Tabbing back to the dropdown field, notice the screen reader is not reading any error message.

### A clear and concise description of what you expected to happen.

The screen reader should announce that the input is invalid and say the error message.

### What actually happened

The screen reader doesn't announce that the input is invalid and doesn't say the error message.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

Video comparing how VoiceOver reads a text input (desired behavior) and the dropdown (faulty behavior).

https://github.com/Automattic/jetpack/assets/1620183/bb12c541-7883-4369-9e71-a6aa2634bcf8

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/34253

## Proposed changes:

The _Dropdown_ field of the _Contact Form_ is implemented with jQuery UI Selectmenu. This PR replaces it by a native select. Though we can't style the dropdown menu, this solution is more accessible, performant, and provides a better experience on mobile.

|Before|After|
|-|-|
|screenshot-2023-12-04-at-6 15 48-pm|screenshot-2023-12-04-at-6 16 05-pm|

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

pf5801-je-p2

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

- Spin up a test site with this branch
- Create a new post
- Add the _Contact Form_ block to the page
- Add a Dropdown field and mark it as required
- Open the page preview
- Check that the Dropdown looks the same
- Check that the field is marked as invalid when submitting the form with an empty value
- Select an option
- Submit the form again and check that the results contain the field value

### CODE REVIEW

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 1]
```diff
@@ -781,12 +781,9 @@ public function render_checkbox_multiple_field( $id, $label, $value, $class, $re
 	 * @return string HTML
 	 */
 	public function render_select_field( $id, $label, $value, $class, $required, $required_field_text ) {
-		$label_ns     = 'contact-form-label';
```
Comment (monsieur-z) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php:784]: Remove unnecessary attributes.

File: projects/packages/forms/src/contact-form/class-contact-form-field.php [hunk 2]
```diff
@@ -803,23 +800,7 @@ public function render_select_field( $id, $label, $value, $class, $required, $re
 			}
 		}
 		$field .= "\t</select>\n";
-
-		wp_enqueue_style(
```
Comment (monsieur-z) [inline projects/packages/forms/src/contact-form/class-contact-form-field.php:807]: Remove deprecated deps.

**Review by sergeymitr — APPROVED** [review]
