### PR TITLE
Customizer: Remove Customizer link from admin menu

### LINKED ISSUE #100223: Task: Ensure Appearance > Customize link only appears in the correct circumstances
### Details

The Customizer should not be accessible when a block theme is active. However I noticed a link in the main navigation appears when browsing the theme showcase at the site level.

| Not browsing theme showcase | Browsing theme showcase |
| --- | --- |
| Image | Image |

## To reproduce

1. Enable wp-admin interface in general settings
2. Activate a block theme
3. Navigate to Appearance > Theme Showcase
4. Observe the appearance of the 'Customize' link

### Checklist

- [ ] Ensure 'Customize' link is correctly hidden

### Related

_No response_

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
We are now hooking the logic that removes the customizer depending on the execution context (API vs regular request).

This is needed because  when executed on init, on API requests, the switch to blog is not executed on time, thus `wp_is_block_theme` returns the placeholder theme.

This PR also removes some duplicate code that's no longer necessary.

Fixes https://github.com/Automattic/wp-calypso/issues/100223
Before
Screenshot 2025-03-12 at 19 03 51

After
Screenshot 2025-03-12 at 19 02 50

## Proposed changes:

* Load the function that removes the customizer on a different hook when executed in API contexts
* Remove duplicated code that's no longer necessary

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply the changes on your Atomic and Simple Site
* Go to wp-admin/edit.php, Appearances > Themes (Theme showcase - Calypso)
* Notice that we no longer display the Customizer link

### CODE REVIEW

**Comment by BogdanUngureanu** [comment]
Hey @Automattic/lego team! Since you've worked on this, do you have a bit of free time to review this PR? :)

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-menu/wpcom-admin-menu.php [hunk 1]
```diff
@@ -321,7 +321,9 @@ function wpcom_hide_customizer_submenu_on_block_theme() {
 		remove_action( 'customize_register', array( 'Jetpack_Custom_CSS_Enhancements', 'customize_register' ) );
 	}
 }
-add_action( 'init', 'wpcom_hide_customizer_submenu_on_block_theme' );
+
+$customizer_removal_hook = defined( 'REST_API_REQUEST' ) && REST_API_REQUEST ? 'rest_pre_dispatch' : 'init';
+add_action( $customizer_removal_hook, 'wpcom_hide_customizer_submenu_on_block_theme' );
```
Comment (rcrdortiz) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-menu/wpcom-admin-menu.php:328]: [Personal preference]
I find it easier to read if we have a variable that indicates if we're in a rest request context:
```
$is_rest_request = defined('REST_API_REQUEST') && REST_API_REQUEST;
$hook = $is_rest_request ? 'rest_pre_dispatch' : 'init';

add_action($hook, 'wpcom_hide_customizer_submenu_on_block_theme');
```

**Comment by rcrdortiz** [comment]
Missing before/after or visual indication of the changes.

**Comment by BogdanUngureanu** [comment]
> Missing before/after or visual indication of the changes.

@rcrdortiz done! :)

**Review by rcrdortiz — DISMISSED** [review]
Changes work as expected. You have some errors that seem unrelated to your changes.

**Comment by matiasbenedetto** [comment]
I tried this PR in my sandbox and I can still see the "Customize" option being rendered:

image

**Comment by rcrdortiz** [comment]
> I tried this PR in my sandbox and I can still see the "Customize" option being rendered:
> 
> image

@matiasbenedetto Did you apply to your sandbox both of these commands?
- bin/jetpack-downloader test jetpack fix/remove-customizer-menu-item
- bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/remove-customizer-menu-item

**Comment by matiasbenedetto** [comment]
>@matiasbenedetto Did you apply to your sandbox both of these commands?

    bin/jetpack-downloader test jetpack fix/remove-customizer-menu-item
    bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/remove-customizer-menu-item
 
 
 Yes I did that:
 
 
[Screencast From 2025-03-12 14-18-49.webm](https://github.com/user-attachments/assets/00da3658-a8d7-4a45-b37b-8575e547698c)

**Comment by rcrdortiz** [comment]
> > @matiasbenedetto Did you apply to your sandbox both of these commands?
> 
> ```
> bin/jetpack-downloader test jetpack fix/remove-customizer-menu-item
> bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/remove-customizer-menu-item
> ```
> 
> Yes I did that:
> 
>  Screencast.From.2025-03-12.14-18-49.webm

It seems you have untracked files and changes on your sandbox, could you try on trunk without any changes? For reference this is what I get when I run the commands:
Screenshot 2025-03-12 at 18 24 02

Also check that sun/moon loader is correct.

Here you can see the changes working for me and I'm not the PR author:
Screenshot 2025-03-12 at 18 24 48

**Comment by rcrdortiz** [comment]
> > > @matiasbenedetto Did you apply to your sandbox both of these commands?
> > 
> > 
> > ```
> > bin/jetpack-downloader test jetpack fix/remove-customizer-menu-item
> > bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/remove-customizer-menu-item
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yes I did that:
> > Screencast.From.2025-03-12.14-18-49.webm
> 
> It seems you have untracked files and changes on your sandbox, could you try on trunk without any changes? For reference this is what I get when I run the commands: Screenshot 2025-03-12 at 18 24 02
> 
> Also check that sun/moon loader is correct.
> 
> Here you can see the changes working for me and I'm not the PR author: Screenshot 2025-03-12 at 18 24 48

I just upgraded to a Premium plan and I can reproduce. Removing my approval.

**Comment by matiasbenedetto** [comment]
> I just upgraded to a Premium plan and I can reproduce. Removing my approval.

I think that's because the rendering of the 'Customize' button is not because of the reason stated in this PR:

>This is needed because when executed on init, on API requests, the switch to blog is not executed on time, thus wp_is_block_theme returns the placeholder theme.

but because not all the customizer options provided by jetpack and wpcom are unregistered.
That's what we are doing in this alternative PR: https://github.com/Automattic/jetpack/pull/42035

**Comment by BogdanUngureanu** [comment]
Hi @matiasbenedetto. Looks like the only option that was missing was 
```
		remove_action( 'customize_register', array( 'Jetpack_Custom_CSS_Customizer', 'customize_register' ) );
```
Now it should work. :)

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-menu/wpcom-admin-menu.php [hunk 2]
```diff
@@ -318,10 +318,14 @@ function wpcom_hide_customizer_submenu_on_block_theme() {
 
 		remove_action( 'customize_register', 'Automattic\Jetpack\Masterbar\register_css_nudge_control' );
 
+		remove_action( 'customize_register', array( 'Jetpack_Custom_CSS_Customizer', 'customize_register' ) );
+
```
Comment (BogdanUngureanu) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-menu/wpcom-admin-menu.php:322]: I need to update the stubs in WPCOM.

**Review by matiasbenedetto — DISMISSED** [review]
>Now it should work. :)

Still not working on my end.
image

**Comment by BogdanUngureanu** [comment]
@matiasbenedetto that's strange. Can you pull the changes again on your sandbox? Sometimes, the artifact takes a while until it's finished.

I've tried again on my sandbox by applying 
```
bin/jetpack-downloader test jetpack fix/remove-customizer-menu-item
bin/jetpack-downloader test jetpack-mu-wpcom-plugin fix/remove-customizer-menu-item
```

And it worked for me. Sorry for the back and forth!

**Review by matiasbenedetto — COMMENTED** [review]
It's working as expected on my latest test :+1:

**Review by rcrdortiz — APPROVED** [review]
Works as expected
