### PR TITLE
Widget Visibility: Fix select option in Customizer

### LINKED ISSUE #6574: Widget Visibility: can't select any option
#### Steps to reproduce the issue

1. Install Jetpack 4.7 Beta.
2. Go to Appearance > Customize > Widgets
3. Select a Widget.
4. Try to apply the following rules:

screen shot 2017-03-06 at 23 13 53

The Front Page rule will disappear as the customizer refreshes.

This happens wither other options as well.

This doesn't happen with Jetpack 4.6.

Possibly caused by #6333, #6327, #3406, or #6326

### PR DESCRIPTION
**Pull request by Stoyan0v**
Fixes #6574

#### Changes proposed in this Pull Request:

* Change the `.condition` holder `data-rule-minor` attribute when the minor select is changed.

It appears that `.condition` data attribute is not updated when minor rules select is changed. Then when `buildMinorConditions` function is called the `minor` data is empty and the select looks broken.

#### Testing instructions:

* Install Jetpack 4.7 Beta.
* Go to Appearance > Customize > Widgets
* Select a Widget.
* Try to apply any option
* Make sure that the minor option doesn't disappear

### CODE REVIEW

File: modules/widget-visibility/widget-conditions/widget-conditions.js [hunk 1]
```diff
@@ -163,6 +163,9 @@ jQuery( function( $ ) {
 		var $conditionsRuleMinor = $( this ),
 			$conditionsRuleMajor = $conditionsRuleMinor.siblings( 'select.conditions-rule-major' ),
 			$conditionsRuleHasChildren = $conditionsRuleMinor.siblings( 'span.conditions-rule-has-children' );
+			$condition = $conditionsRuleMinor.closest( '.condition' );
```
Comment (zinigor) [inline modules/widget-visibility/widget-conditions/widget-conditions.js]: Actually, wait a second. You need to change the previous line to end with a comma, not with a semicolon. Can you please fix that?

**Comment by dereksmart** [comment]
Thank you, works well 👍

**Comment by dereksmart** [comment]
branch 4.7- c19e1e4
