### PR TITLE
Publicize: Fix the default connection state filter

### LINKED ISSUE #24059: Publicize: `publicize_checkbox_default` removes checkboxes but sharing still happens. Doc update needed?
### Impacted plugin

Jetpack

### Steps to Reproduce

To prevent automatic sharing, I've added this to my theme's functions.php file:

```
if ( class_exists( 'Jetpack' ) && Jetpack::is_module_active( 'publicize' ) ) {
  add_filter( 'publicize_checkbox_default', '__return_false' );
}
```

It removes the checkboxes beside the connected Twitter account(s), but Publicize still fires and the tweet is published.

Screen Shot 2022-04-22 at 12 31 06 PM

### A clear and concise description of what you expected to happen.

The `publicize_checkbox_default` documentation on https://developer.jetpack.com/hooks/publicize_checkbox_default/ contains a note that says `Important: there are currently some issues with this filter. It is recommended not to use until [this issue](https://github.com/Automattic/jetpack/issues/1550) is solved.`

That [issue](https://github.com/Automattic/jetpack/issues/1550) is solved, however this filter is not currently working as expected.

### What actually happened

It removes the checkboxes beside the connected Twitter account(s), but Publicize still fires.

Without this filter in place, if I manually uncheck the checkmark beside my connected Twitter account, the post is *not* shared on Twitter when published.

### Other information

An example post where I tested this: 
blog_id=106565671
post_id=9022

This happens with the Block editor.

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by pablinos**
Fixes #24059

#### Changes proposed in this Pull Request:
The REST post field assumes that the default value for connections is to be enabled. If the `publicize_checkbox_default` filter is used to make it `false` then it breaks this logic and meta isn't stored against the post to skip the connections when Publicize runs.

This PR removes the checks for `jetpack_publicize_connections` being empty as the post is saved, and ensures that the appropriate meta is stored against the post.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Setup Publicize on a site
* Add `add_filter( 'publicize_checkbox_default', '__return_false' );` somewhere that will be loaded.
* Without this PR when a post is published it will still be shared to any connections
* With it, the connection state should be respected.

Run the automated tests:

In the `packages/publicize` directory, run:

```
composer phpunit -- --filter=Test_Connections_Post_Field
```

### CODE REVIEW

File: projects/packages/publicize/tests/php/test-connections-post-field.php [hunk 1]
```diff
@@ -336,4 +336,25 @@ public function test_update_connections_by_service_name() {
...
+		add_filter( 'publicize_checkbox_default', $filter_func );
+		$request = new WP_REST_Request( 'POST', sprintf( '/wp/v2/posts/%d', $this->draft_id ) );
+		$this->server->dispatch( $request );
+
+		foreach ( self::$connection_ids as $unique_id ) {
+			$skip_key = $this->publicize->POST_SKIP . $unique_id;
+			$this->assertNotEmpty( get_post_meta( $this->draft_id, $skip_key, true ) );
+		}
+
+		remove_filter( 'publicize_checkbox_default', $filter_func );
```
Comment (danielpost) [inline projects/packages/publicize/tests/php/test-connections-post-field.php:371]: Does it make sense to add an extra test testing the opposite (if default filter is not used, connections are enabled by default)?

**Review by danielpost — DISMISSED** [review]

File: projects/packages/publicize/tests/php/test-connections-post-field.php (hunk 1 above)
Comment (pablinos) [reply projects/packages/publicize/tests/php/test-connections-post-field.php:371]: Good idea. Added in 0728743435

**Review by danielpost — APPROVED** [review]
