### PR TITLE
RDV: Fix the performance issue on AT sites

### LINKED ISSUE #98603: Jetpack: Test assignments slowing page generation time for Atomic sites
### Context and steps to reproduce

When I load wp-admin, while proxied so that debug bar shows, for my atomic site, I see that there are two requests for assignments that are adding 320+ ms to the page generation time. 

Image

Naively, I assume that we're making these requests to get the bucket that this site/user has been assigned to. And I also assume that we need that bucket during page generation.

But, the issue is that it seems like we're making the same network requests with every page load. We should probably be caching the results of these calls in an option or transient.

### Site owner impact

More than 60% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### Platform

Atomic

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Fixes https://github.com/Automattic/wp-calypso/issues/98603

When the ExPlat API returns a null assignment value we don't cache the result, thus making an API request on every page load.

Since only a12s should be un-assigned to a variation, this PR adds "treatment" variation as a fallback value.

## Proposed changes:

* Default to treatment for users that don't have an assignment returned

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Install the change on your Atomic site
* Make sure you get treatment
* Make sure that we don't make an API request on each page load (using the debug tool)

### CODE REVIEW

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 1]
```diff
@@ -448,6 +448,17 @@ function wpcom_is_duplicate_views_experiment_enabled() {
 
 	if ( isset( $data['variations'] ) && isset( $data['variations'][ $experiment_name ] ) ) {
```
Comment (rcrdortiz) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php]: When the experiment_name's value is NULL we don't go inside this branch.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php [hunk 2]
```diff
@@ -451,11 +451,19 @@ function wpcom_is_duplicate_views_experiment_enabled() {
 		update_user_option( get_current_user_id(), $option_name, $variation, true );
 
 		$is_enabled = 'treatment' === $variation;
-		return $is_enabled;
+	} elseif ( isset( $data['variations'] ) && ! isset( $data['variations'][ $experiment_name ] ) ) {
```
Comment (rcrdortiz) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php]: We can improve/simplify the checks by:
````
if ( isset( $data['variations'][ $experiment_name ] ) ) {
    $variation = $data['variations'][ $experiment_name ];
    update_user_option( get_current_user_id(), $option_name, $variation, true );
    $is_enabled = 'treatment' === $variation;
} elseif ( isset( $data['variations'] ) ) {
  /**
   * If the variations array is set but the variation value is null chances are this is an a11n (since ExPlat returns null for a12s).
   * 
   * We want to set the treatment for all a12s.
   */
    update_user_option( get_current_user_id(), $option_name, 'treatment', true );
    $is_enabled = true;
} else {
    $is_enabled = false;
}
````

Comment (BogdanUngureanu) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php]: Yeah, that could work too.

**Review by rcrdortiz — DISMISSED** [review]
Besides the nit I left, everything works as expected now.

**Review by rcrdortiz — DISMISSED** [review]

**Review by rcrdortiz — APPROVED** [review]
