### PR TITLE
tools: Check that `pnpm` works before piping output

### LINKED ISSUE #37523: Tools: Changelogger Release fails with cryptic message when pnpm's version is wrong
`tools/changelogger-release.sh` fails when pnpm's version is wrong with the following message:
 
```
> tools/changelogger-release.sh -p -r 6.4.3 plugins/crm
jq: parse error: Invalid numeric literal at line 1, column 34
```

By using some debug lines we are able to find the following error:

```
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version) Your pnpm version is incompatible with "/home/gogdzl/dsk/git/avengers/jetpack". Expected version: ^8.6.2 Got: 9.1.1 This is happening because the package's manifest has an engines.pnpm field specified. To fix this issue, install the required pnpm version globally. To install the latest version of pnpm, run "pnpm i -g pnpm". To check your pnpm version, run "pnpm -v".
```

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

If the `engines` in `package.json` aren't satisfied, `pnpm run` (among other `pnpm` commands, but not all of them) will print an error message to standard output and exit with a non-zero status. When the first use of `pnpm` in a script is doing like `pnpm jetpack dependencies | jq`, the script winds up exiting with an unhelpful error like
```
jq: parse error: Invalid numeric literal at line 1, column 34
```

To avoid this, lets run some other `pnpm jetpack` command earlier in the affected scripts. And to avoid useless or confusing output for the more common case that things work properly, let's introduce a `jetpack noop` command that does nothing beyond the normal startup stuff to use for this.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #37523

## Testing instructions:

* Adjust the version numbers in `engines` in `package.json` so the installed version of node or pnpm doesn't pass. Then try running the modified scripts.

### CODE REVIEW

File: tools/cli/commands/noop.js [hunk 1]
```diff
@@ -0,0 +1,17 @@
+export const command = 'noop';
+export const describe = false;
+
+/**
+ * Options definition for the phan subcommand.
```
Comment (tbradsha) [inline tools/cli/commands/noop.js]:
```suggestion
 * Options definition for the noop subcommand.
```

**Review by tbradsha — APPROVED** [review]
Works as stated.
