### PR TITLE
Search: ensure translations are available for lazy-loaded payloads

### LINKED ISSUE #19752: Instant Search: Builds probably shouldn't include cachebusters in the file names.
#### Steps to reproduce the issue

1. Have a full page caching system
2. Update Jetpack
3. Previously cached pages still enqueue old filenames, which now 404.
4. Sad christmas.

#### What I expected
Bundle filenames to be consistent across versions -- using cachebusters in the query string instead as per standard WordPress practice.

#### What happened instead
The filenames changed, resulting in 404s.

### LINKED ISSUE #20520: Jetpack Search: some interface strings are not being localized
#### Steps to reproduce the issue

1. On your test site with Instant Search enabled, set the site language to 'Français'.
2. Return to the front end of your site and perform a search.

#### What I expected
If the site language is French, all of the interface language in the Instant Search modal should also be in French.

#### What happened instead
The modal shows English strings for "Showing popular results", "Sort" and "clear". Interestingly the sort options themselves are correctly translated (e.g. "Pertinence") so some translations are working as expected.

For example: https://lapidoule.com/?s=bebe

Discovered via 4190269-zen.

**Screenshots**

Screen Shot 2021-08-02 at 15 03 22

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #20520 This should also fix #19752.

#### Changes proposed in this Pull Request:
Inline translations before enqueuing the main payload to make sure translations for lazy-loaded payloads are available. And also to avoid directory scanning and to make it work for WPCOM as well, the PR proposed to replace the `hash` from the main chunk file name with a query string based cache buster.

#### Jetpack product discussion
pcNPJE-gU-p2

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Open your local site with Jetpack Search subscription
* Navigate to the WP language folder `tools/docker/wordpress/wp-content/languages/plugins`
* Change the translation file name from `jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json` to `jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json`. The example is done for French language, and other languages are similar.
 * Ensure everything is translated on search interface, especially the marked ones.
 
image

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php [hunk 1]
```diff
@@ -140,6 +140,35 @@ public function load_assets_with_parameters( $path_prefix, $plugin_base_path ) {
...
+		// Then register it, which is required for the next steps.
+		wp_register_script( $handle, $payload_url, array(), $wp_version, false );
+		// Set translation domain to `jetpack`, and we need to explicitly set the `path` to load translations files for WPCOM.
+		// Otherwise WPCOM would try to load from `WP_LANG_DIR . '/mu-plugins'` and fails.
+		wp_set_script_translations( $handle, 'jetpack', WP_LANG_DIR . '/plugins' );
+		// Inline the translations before `$before_handle` handle.
+		wp_add_inline_script( $before_handle, wp_scripts()->print_translations( $handle, false ), 'before' );
+		// Deregister the script as we don't really enqueue it from PHP side.
+		wp_deregister_script( $handle );
 	}
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:172]: Manually inspecting `script#jetpack-instant-search-js-before` in the document body yields a blank translation payload:

Screen Shot 2021-09-07 at 6 33 10 PM

Is this expected?

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php [hunk 2]
```diff
@@ -140,6 +140,35 @@ public function load_assets_with_parameters( $path_prefix, $plugin_base_path ) {
...
+	}
+
+	/**
+	 * Add inline translations for script `$payload_url` before loading `$before_handle` script.
+	 *
+	 * @param string $payload_url - The payload url for which we load the translations.
+	 * @param string $before_handle - Inline the translations before this handle.
+	 */
+	protected function inject_translation_for_script( $payload_url, $before_handle = 'jetpack-instant-search' ) {
+		global $wp_version;
```
Comment (jsnmoon) [inline projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:160]: Is `$wp_version` a reliable cache-buster in our use case? Wouldn't this value remain unchanged across multiple Jetpack releases?

File: projects/plugins/jetpack/tools/webpack.config.search.js [hunk 3]
```diff
@@ -33,7 +33,7 @@ const baseWebpackConfig = getBaseWebpackConfig(
 				require.resolve( 'abortcontroller-polyfill/dist/polyfill-patch-fetch' ),
 			],
 		},
-		'output-chunk-filename': 'jp-search.chunk-[name]-[hash].min.js',
+		'output-chunk-filename': 'jp-search.chunk-[name].min.js?ver=[hash]',
```
Comment (jsnmoon) [inline projects/plugins/jetpack/tools/webpack.config.search.js:36]: Does Webpack's configuration file allow for query string values like this?

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php (hunk 2 above)
Comment (kangzj) [reply projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:160]: Good catch. We don't really need a version here, the `$wp_version` is only to eliminate the warnings. Changed the value  to `false` and disabled the check.

File: projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php (hunk 1 above)
Comment (kangzj) [reply projects/plugins/jetpack/modules/search/class-jetpack-instant-search.php:172]: Yes this is expected. As there's no translation available for now. To simulate the situation, you'd need to 
- Change the translation file name from `jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json` to `jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json`. The example is done for French language, and other languages are similar, just change the hash.

File: projects/plugins/jetpack/tools/webpack.config.search.js (hunk 3 above)
Comment (kangzj) [reply projects/plugins/jetpack/tools/webpack.config.search.js:36]: Yes it supports so, but is not documented. I guess it's because it's not the recommended way. 
Here's [what I found](https://github.com/webpack/webpack/issues/2329), a author of Webpack confirmed this approach. I don't see any resource indicating this would be deprecated, so I think we're good. But if it does get deprecated, we would need to implement our own plugin or loader I guess.

Comment (kangzj) [reply projects/plugins/jetpack/tools/webpack.config.search.js:36]: PS: the file name would just be `jp-search.chunk-[name].min.js` while loading as `https://xxxx/path/jp-search.chunk-[name].min.js?ver=hash`

Comment (jsnmoon) [reply projects/plugins/jetpack/tools/webpack.config.search.js:40]: What do you think of the failure scenario the author penned [here](https://github.com/webpack/webpack/issues/2329#issuecomment-210433116)? Do you think it could cause failures in any of our environments (e.g. simple, atomic, and Jetpack)?

Comment (kangzj) [reply projects/plugins/jetpack/tools/webpack.config.search.js:40]: Yep we talked about this before (pcNPJE-9r-p2), query based cache buster could cause inconsistency. But it wouldn't in our case.

- It only would happen when user has loaded one chunk, and we updated assets, and user loads another chunk and unluckily enough, the chunk would break the app. In our case, this will NOT happen because we have ONLY one lazy-loaded chunk, at least for now.
- Even it happens, it's recoverable - a refresh would do.
- Hashed file name has its problem too, like what happened [here](https://github.com/Automattic/jetpack/issues/19752)

So I don't think the approach would cause issues for Simple, Atomic or Jetpack sites theoretically. But of course we'll need to watch the environments carefully after delivering the changes.

Comment (kangzj) [reply projects/plugins/jetpack/tools/webpack.config.search.js:40]: For wpcom it seems there are more than one chunks, but the conclusion still stands I guess.

**Review by jsnmoon — DISMISSED** [review]
👍 Let's give this a shot for the 10.2 release.

**Comment by sdixon194** [comment]
@kangzj Wanted to give this one a try, but having some trouble with finding `tools/docker/wordpress/wp-content/languages/plugins` - I have a `themes` folder, but nothing for plugins. Am I missing something that will generate that folder so I can replace the file?

**Comment by kangzj** [comment]
> @kangzj Wanted to give this one a try, but having some trouble with finding `tools/docker/wordpress/wp-content/languages/plugins` - I have a `themes` folder, but nothing for plugins. Am I missing something that will generate that folder so I can replace the file?

Hi @sdixon194 thanks for looking at this.

So you'll need to switch WP to a language other than English and then go to Updates -> Update translations. You'll then find the plugins folder.

**Comment by sdixon194** [comment]
Per a conversation with @kangzj, it seems like there might be a larger issue with translations, since our Dashboard is not translated either, will need more investigation.

**Comment by samiff** [comment]
Just noting https://github.com/Automattic/jetpack/issues/21204 which could be related to the issues seen testing here.

**Comment by samiff** [comment]
@kangzj Now that https://github.com/Automattic/jetpack/issues/21204 is closed I was wanting to give this another test, though I'm not sure about this instruction:

> Change the translation file name from jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json to jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json. The example is done for French language, and other languages are similar.

I don't see `jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json` on my end, could you explain a bit more what's going on here, thanks.

**Comment by kangzj** [comment]
> I don't see `jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json` on my end, could you explain a bit more what's going on here, thanks.

Hi @samiff thanks for coming back for this. Sorry I should have put more information about it. `jetpack-fr_FR-8df5774da753f9be21ced70eecc80000.json` is the translations for `_inc/build/instant-search/jp-search.chunk-main-payload-7757c96a0cd36029a41d.min.js` from ver `10.0` I believe, which we wanted to load before  enqueuing instant search payloads.

As the translation file name is basically a hash from the JS file name. Whenever the js file name changes, the translation file name changes as well. So we moved the hash to a query parameter to make the file name stays the same between versions - you see from the new webpack config. `jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json` -  the hash is manually calculated and would match `_inc/build/instant-search/jp-search.chunk-main-payload.min.js`, and will stay the same for future versions.

I don't think the translations are ready yet. I mocked a translation file here, with only one string translated ( `Showing popular results`  => `In French: Showing popular results` ): [jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json.zip](https://github.com/Automattic/jetpack/files/7262897/jetpack-fr_FR-0e17ef273599d7b1004fc0c6aacf4f5e.json.zip)

Could you unzip the file to `tools/docker/wordpress/wp-content/languages/plugins` and then switch your WP language to French and open the search overlay, and ensure you see `In French: Showing popular results` like the screenshot below.

image

**Comment by kangzj** [comment]
I know it's pretty hard to test as it's basically relies on the translation mechanism of WP. And to some extend, I think this is not even needed to be tested for translations. As we didn't change anything about translations, we changed a target file name and we just need to verify if Search works - the translations should just work, right?

**Review by jeherve — APPROVED** [review]
Using the provided file, this seems to work. Let's give it a try!

**Comment by samiff** [comment]
cherry-picked to jetpack/branch-10.2 in e86e886c0e7889baf95046057c7d33063f863c7c

**Comment by samiff** [comment]
@kangzj Doing some diff cleanup, does D66256-code need attention?

**Comment by kangzj** [comment]
Hi @samiff thanks for the reminder 😄 . It's now shipped.
🚢 r232895-wpcom
