### PR TITLE
Subscription: Add Filter to Allow Capability to be changed

### LINKED ISSUE #36908: Supscriptions: Add Filter to Customize Subscription Meta Capability
### Impacted plugin

Jetpack

### What

Add a Filter to allow Subscription Meta Cap to be Editied

### How

If users don't have the `publish_post` capability they will get the following error during post meta save for the Newsletter meta 
> "Updating failed. Sorry, you are not allowed to edit the jetpack_post_was_ever_published custom field."

https://github.com/Automattic/jetpack/blob/3c0ef60252d2e09e837e8a7d8bfd547ff20be316/projects/plugins/jetpack/modules/subscriptions.php#L957-L966

This request is to add a filter to allow this capability to be customized.

### PR DESCRIPTION
**Pull request by BrookeDot**
Fixes #36908

## Proposed changes:
* The `first_published_status_meta_auth_callback` defaults to `publish_post` this PR adds the new `jetpack_subscriber_was_published_capability` filter to allow this to be changed. This was requested by a VIP customer who would like to change the filter to `edit_post`

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Have an admin user who can `edit_posts` but not `publish_posts` 
* Visit a post in the admin
* Try to edit post-meta and see "Updating failed. Sorry, you are not allowed to edit the jetpack_post_was_ever_published custom field."
* Add the `jetpack_subscriber_was_published_capability` filter to a cap your user has (ie `edit_post`)
* The error will go away and the content will load.

## Does this pull request change what data or activity we track or use?

This PR does not update any tracking data

### CODE REVIEW

File: projects/plugins/jetpack/modules/subscriptions.php [hunk 1]
```diff
@@ -960,7 +960,9 @@ public function maybe_set_first_published_status( $new_status, $old_status, $pos
 	 * @return bool
 	 */
 	public function first_published_status_meta_auth_callback() {
-		if ( current_user_can( 'publish_posts' ) ) {
+		$capability = apply_filters( 'jetpack_subscriber_was_published_capability', 'publish_posts' );
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/subscriptions.php]: I'd suggest adding a docblock, so our Codex can be automatically updated with the new filter on the next release. You can check other filters in that file for the expected format:
https://github.com/Automattic/jetpack/blob/b77b183164ca8f0d71a0bd0bb8fb4079c7c3dec0/projects/plugins/jetpack/modules/subscriptions.php#L173-L181

You can use `@since $$next-version$$` as the since version number; it will be automatically replaced on release day.

Comment (jeherve) [inline projects/plugins/jetpack/modules/subscriptions.php]: What do you think about making the filter a bit more specific, since it will only apply to that specific use check? Maybe something like `jetpack_subscriptions_post_was_ever_published_capability`? It's a mouthful, but it will avoid confusion for folks seeing that filter in the wild in the future.

**Review by jeherve — DISMISSED** [review]
This looks good to me. I only have a few minor suggestions. 

Looks like you'll also need to update your branch with the latest `trunk` to avoid the warnings in CI.

File: projects/plugins/jetpack/modules/subscriptions.php (hunk 1 above)
Comment (BrookeDot) [reply projects/plugins/jetpack/modules/subscriptions.php]: Agree, I was trying to figure out how to name a filter in a manner that was descriptive but also balanced the length. I'm fine with your suggestion.

**Review by jeherve — APPROVED** [review]
