### PR TITLE
Boost: Add health checks for cache loading

### LINKED ISSUE #36331: Boost: Re-run setup to detect if something's broken
We should probably re-run setup when opening the Boost UI to tell the user if somethings wrong with caching.

### PR DESCRIPTION
**Pull request by haqadn**
Fixes #36331

## Proposed changes:
* Run cache setup on every dashboard page load to self heal any issues
* Add a to site health if page cache is active but not loading
* Show a notice in boost settings, if page cache is active but not loading.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
None

## Does this pull request change what data or activity we track or use?
None

## Testing instructions:
* Enable boost cache
* Mutilate the caching system, i.e. Set `WP_CACHE` to `false` or delete the `advanced-cache.php` file.
* After loading boost settings, it should auto-fix the issues
* Now, try modifying the advanced-cache.php file slightly so that the cache cannot load. Example: Add a `return;` immidiately after the `<?php` line.
* Load boost dashboard.

image

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/lib/stores/page-cache.ts [hunk 1]
```diff
@@ -69,6 +69,41 @@ export function usePageCacheSetup() {
...
+				setError( {
+					code: 'unknown_error',
+					message: standardizedError.message || __( 'Unknown error occurred.', 'jetpack-boost' ),
+				} );
+			},
+			onSuccess: () => {
+				setError( null );
+			},
+		},
+	} );
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/lib/stores/page-cache.ts]: This is a whole lot of repeat code from the function above it. Can these be combined?

File: projects/plugins/boost/app/modules/optimizations/page-cache/data-sync-actions/check-setup.php [hunk 2]
```diff
@@ -0,0 +1,28 @@
+<?php
+
+namespace Automattic\Jetpack_Boost\Modules\Optimizations\Page_Cache\Data_Sync_Actions;
+
+use Automattic\Jetpack\WP_JS_Data_Sync\Contracts\Data_Sync_Action;
+use Automattic\Jetpack_Boost\Modules\Optimizations\Page_Cache\Page_Cache_Setup;
+
+/**
+ * Critical CSS Action: request regeneration.
+ */
```
Comment (thingalon) [inline projects/plugins/boost/app/modules/optimizations/page-cache/data-sync-actions/check-setup.php]: Is this a critical css action?

**Review by thingalon — CHANGES_REQUESTED** [review]
Interesting approach checking if the cache ::serve has been called when running the ajax call to check the setup. I do like the "test if it's really calling our code" test, that's nice. 

But there's some code duplication here that I think will get messy if we don't tidy it up.

**Comment by thingalon** [comment]
If you freshly load the Boost dashboard with caching off, then turn caching on, you see the cache system error message pop up briefly before disappearing:

https://github.com/Automattic/jetpack/assets/1369626/3d9103b0-504d-42a8-928c-1f80561168c9

File: projects/plugins/boost/app/assets/src/js/pages/index/index.tsx [hunk 3]
```diff
@@ -39,12 +40,18 @@ const Index = () => {
...
+	);
 
 	const [ removePageCacheNotice ] = useMutationNotice(
 		'page-cache-setup',
 		{
 			...pageCacheSetup,
-			isPending: isPageCacheSettingUp || pageCacheSetup.isPending,
+			isSuccess: runningFreshSetup && pageCacheSetup.isSuccess,
+			isPending: runningFreshSetup && ( isPageCacheSettingUp || pageCacheSetup.isPending ),
+			isIdle: runningFreshSetup && pageCacheSetup.isIdle,
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/pages/index/index.tsx]: This is a really complex knot of logic right in `index.tsx`. I can't understand what is going on here.

At a minimum it needs comments explaining what is going on. What is the difference between `runningFreshSetup` and `isPageCacheSettingUp`? Why is it only pending if both "fresh" and "setting up" or "pending"?

My gut feeling is that this code doesn't belong here in this form, but I can't say that for sure because I don't understand it.

File: projects/plugins/boost/app/modules/optimizations/page-cache/Page_Cache_Setup.php [hunk 4]
```diff
@@ -14,41 +15,87 @@ class Page_Cache_Setup {
...
 			'verify_permalink_setting',
+		);
+
+		foreach ( $verification_steps as $step ) {
+			$result = self::run_step( $step );
+
+			if ( is_wp_error( $result ) ) {
+				return $result;
+			}
+		}
```
Comment (thingalon) [inline projects/plugins/boost/app/modules/optimizations/page-cache/Page_Cache_Setup.php:30]: 🤔 This isn't a blocker, so if you really prefer it like this it doesn't have to change, but:

Wouldn't it be simpler to have all setup steps -- whether verification or setup -- always return the same things, so we only need one loop?

File: projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/Boost_Cache.php [hunk 5]
```diff
@@ -76,6 +88,15 @@ public function serve() {
 		}
 	}
 
+	/**
+	 * Check if the cache engine has been loaded.
+	 *
+	 * @return bool - True if the cache engine has been loaded, false otherwise.
+	 */
+	public static function is_loading() {
```
Comment (thingalon) [inline projects/plugins/boost/app/modules/optimizations/page-cache/pre-wordpress/Boost_Cache.php]: `is_loading` makes it sound like an ongoing process. Perhaps just `is_loaded` or `has_loaded`?

**Review by thingalon — CHANGES_REQUESTED** [review]
I've noticed a bug (in a comment above), and have a concern at a complex knot of code I don't understand.

File: projects/plugins/boost/app/assets/src/js/pages/index/index.tsx (hunk 3 above)
Comment (haqadn) [reply projects/plugins/boost/app/assets/src/js/pages/index/index.tsx]: I'll improve `runningFreshSetup`. I didn't quite understand `isPageCacheSettingUp` and didn't want to break any functionality. @pyronaur can you help me understand it?

File: projects/plugins/boost/app/modules/optimizations/page-cache/Page_Cache_Setup.php (hunk 4 above)
Comment (haqadn) [reply projects/plugins/boost/app/modules/optimizations/page-cache/Page_Cache_Setup.php:30]: I am on the fence about it, but leaning towards having them separate. This is because for the steps that can mutate something their return values can be:
- `true` - when something changed
- `false` - nothing changed but no issues
- `WP_Error` - if it failed

If we apply this same format for the verification steps, it would return `false|WP_Error`. It kind of looks weird to return `false` for success while returning true for nothing.

For mutable steps, I think it makes sense to return `bool|WP_Error` because we are checking the return value to check anything changed. Let me know what you think.

Comment (pyronaur) [reply projects/plugins/boost/app/modules/optimizations/page-cache/Page_Cache_Setup.php:30]: I agree that two loops look a bit messy, but because they have a clear distinction between, I actually think keeping them separate is a step in the right direction. I'm not reviewing anything here, just leaving my vote for doing the 2 loop approach.

**Review by thingalon — DISMISSED** [review]

**Review by thingalon — APPROVED** [review]
