### PR TITLE
Donations block: prevent crash on currency change

### LINKED ISSUE #30299: Payments block: cannot change currency
### Impacted plugin

Jetpack

### Quick summary

When using the payments block, changing currency breaks the block.

### Steps to reproduce

1. On Simple site (didn't check Atomic/Jetpack sites)
2. In the page editor (could happen also in other editors)
3. Add payments block
4. Pick donations
5. In the block toolbar, change currency to any other from the default USD
    Screenshot 2023-04-26 at 11 40 49
6. Observe crash and error in console

Screenshot 2023-04-26 at 11 40 39

https://user-images.githubusercontent.com/87168/234521391-a9098b08-c2d2-490a-90f1-60a099d0891f.mov

image

Not sure if this warning is related, but its in the console:

image

### A clear and concise description of what you expected to happen.

Should be able to change currency.

In fact, since I'm in Lithuania, I expected the default pre-selected currency to be Euros.They should

### What actually happened

Block crashed.

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- Chrome browser

### PR DESCRIPTION
**Pull request by n3f**
Fixes #30299 (donation block currency changes crashed the block)

## Proposed changes:

* Adds `removeEventListener` to Amount blur.
* Updates the default amounts when the change occurs.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* On sandbox run `bin/jetpack-downloader test jetpack earn/fix/change-donation-block-currency`
* Sandbox the site you want to check on and load the donations block.  Change the currency.  The block should not crash.
* There exist some other issues with the amount component, but these will be addressed in other patches.

### CODE REVIEW

**Comment by n3f** [comment]
@millerf, I think that I found the root cause (there was a useEffect that was adding an event handler but never removing it -- I think this handler was firing (it was on blur). But it seems that it "works" now. With it working though I can see an issue with the isInvalid check that will need some attention.  I'll file that issue next.

File: projects/plugins/jetpack/extensions/shared/currencies.js [hunk 1]
```diff
@@ -60,6 +60,21 @@ export function minimumTransactionAmountForCurrency( currency_code ) {
 	return SUPPORTED_CURRENCIES[ currency_code ];
 }
 
+/**
+ * Returns the default amounts for the given currency.
+ *
+ * @param {string} currency_code - three character currency code to get default amounts for
+ * @returns {number[]} Default amounts for the given currency_code
+ */
+export function getDefaultAmountsForCurrency( currency_code ) {
```
Comment (n3f) [inline projects/plugins/jetpack/extensions/shared/currencies.js]: Should we rename this to `getDefaultDonationAmountsForCurrency()`?

File: projects/plugins/jetpack/extensions/blocks/donations/controls.js [hunk 2]
```diff
@@ -75,7 +76,14 @@ const Controls = props => {
 											<MenuItem
 												isSelected={ ccy === currency }
 												onClick={ () => {
-													setAttributes( { currency: ccy } );
+													const defaultAmounts = getDefaultAmountsForCurrency( ccy );
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/donations/controls.js]: We should move that to its own callback for clarity

File: projects/plugins/jetpack/extensions/blocks/donations/tabs.js [hunk 3]
```diff
@@ -39,7 +39,7 @@ const Tabs = props => {
 				annualDonation: { ...annualDonation, planId: products[ '1 year' ] },
 			} ),
 		} );
-	}, [ oneTimeDonation, monthlyDonation, annualDonation, setAttributes, products ] );
+	}, [ oneTimeDonation, monthlyDonation, annualDonation, products, setAttributes ] );
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/donations/tabs.js]: Do we have to include setAttributes here?! Also this change is quite uneneeded :)

File: projects/plugins/jetpack/extensions/shared/currencies.js (hunk 1 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/shared/currencies.js]: Go ahead 👍

File: projects/plugins/jetpack/extensions/blocks/donations/amount.js [hunk 4]
```diff
@@ -54,17 +55,21 @@ const Amount = ( {
...
+				setAmount( formatCurrency( defaultValue, currency, { symbol: '' } ) );
+			}
+		};
+
+		_ref.addEventListener( 'blur', onBlur );
 
-		setAmount( formatCurrency( defaultValue, currency, { symbol: '' } ) );
-	}, [ currency, defaultValue, editedValue, isFocused, setAmount ] );
+		return () => {
+			_ref.removeEventListener( 'blur', onBlur );
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/donations/amount.js:69]: Nice catch

Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/donations/amount.js:69]: I wonder if  `_ref` is properly referenced in the clean up 🤔

File: projects/plugins/jetpack/extensions/blocks/donations/tabs.js (hunk 3 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/donations/tabs.js]: Ha! I didn't notice that.  But yeah, your PR removed it and the linter wanted it back, so I re-added it.  I'll get this fixed.

File: projects/plugins/jetpack/extensions/blocks/donations/amount.js (hunk 4 above)
Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/donations/amount.js:69]: This was actually another catch from the linter.  Originally I just used the `.current` reference, but the linter correctly pointed out that it could be removed from the scope, but creating  a local const preserves it in this closure.

File: projects/plugins/jetpack/extensions/blocks/donations/tabs.js (hunk 3 above)
Comment (millerf) [reply projects/plugins/jetpack/extensions/blocks/donations/tabs.js]: Yeah, this linter rule kind of unsettles me...

Comment (n3f) [reply projects/plugins/jetpack/extensions/blocks/donations/tabs.js]: Same, I'm not a big fan of it.

**Comment by millerf** [comment]
@n3f Can you remove the draft status when you are done?

File: projects/plugins/jetpack/extensions/blocks/donations/amount.js [hunk 5]
```diff
@@ -16,6 +16,7 @@ const Amount = ( {
 	const [ editedValue, setEditedValue ] = useState(
 		formatCurrency( value, currency, { symbol: '' } )
 	);
+	// const [ previousCurrency, setPreviousCurrency ] = useState( currency );
```
Comment (millerf) [inline projects/plugins/jetpack/extensions/blocks/donations/amount.js]: Needs removing

**Review by millerf — APPROVED** [review]
Works for me 👍

**Review by samiff — APPROVED** [review]
Tested well on my WoA site.
