### PR TITLE
Search: further layout and accessibility improvements for wp-admin page

### LINKED ISSUE #20734: Instant Search: improve accessibility of wp-admin section
Potential a11y improvements to the new wp-admin section at `/wp-admin/admin.php?page=jetpack-search`:

* [x] Use aria-hidden to hide mocked search interface or replace with an image
* [x] Add `label`s for form toggles
* [x] Make sure Jetpack logo in header and footer and 'An Automattic Airline' are appropriately labelled, perhaps with aria-labelledby (https://www.sarasoueidan.com/blog/accessible-icon-buttons/)

You can verify your changes with the Firefox Accessibility tab in Developer Tools and by testing with VoiceOver (https://webaim.org/articles/voiceover/).

### LINKED ISSUE #20757: Instant Search: wp-admin section does not appear in my selected language
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Set your WP interface language to something other than English.
2. Load the beta Jetpack Search wp-admin section at `/wp-admin/admin.php?page=jetpack-search`.

### A clear and concise description of what you expected to happen.

If my language is set to French, the wp-admin UI should appear in French.

### What actually happened

The menus are in French but the wp-admin section is all in English.

### Other information

Not sure if this is because the translations aren't back yet, or because we're not selecting the right translations.

The sort options (like 'Relevance') are definitely translated for the main Instant Search UI, so it's possibly the latter.

### Operating System

_No response_

### OS Version

_No response_

### Browser

Firefox

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by kangzj**
#### Changes proposed in this Pull Request:
This PR is a follow up PR for #20399, including some layout and accessibility improvements. Also partially fixes #20734 and fixes #20757 (translation issue). Also the PR added a submenu for search under Jetpack menu.

- Changed buttons to use grid layout
- Adjusted spacing
- `aria-hidden` mocked elements
- Some code quality improvements

#### Jetpack product discussion
pcNPJE-7J-p2#comment-161

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- Go to a site with Jetpack subscription
- Ensure you can find `Search` under `Jetpack` menu
- And then click `Search`
- Ensure the page looks and feels okay under different resolutions
- Ensure a11y is working okay

### CODE REVIEW

**Comment by bluefuton** [comment]
Maybe one tiny fix we could add here - on the main Instant Search UI the sidebar heading is "Filter options" whereas in the mocked search UI here it is "Filter Options":

Screen Shot 2021-08-19 at 15 25 48

**Comment by kangzj** [comment]
Hi @bluefuton do you reckon we should replace the mocked interface with jpegs since Philip is back from AFK?

**Comment by bluefuton** [comment]
> do you reckon we should replace the mocked interface with jpegs since Filipe is back from AFK?

I actually think the mocked search interface has one big positive - it's translatable. If we can get the translations working correctly (see https://github.com/Automattic/jetpack/issues/20520) and the layout works across languages, I reckon we could leave it in.

**Comment by kangzj** [comment]
> I actually think the mocked search interface has one big positive - it's translatable. If we can get the translations working correctly (see #20520) and the layout works across languages, I reckon we could leave it in.

Sweet. Actually the search admin page is built separately and is not lazy-loaded. So I guess it should be fine?


> We should `aria-hidden` the whole block or provide an alternative for screen readers if we haven't already though - I can imagine it'd be super confusing otherwise.

Yep the whole block is now marked with `aria-hidden`.

**Comment by bluefuton** [comment]
> Actually the search admin page is built separately and is not lazy-loaded. So I guess it should be fine?

Sorry - the issue should have been https://github.com/Automattic/jetpack/issues/20757.

Try switching your WP interface language - nothing is translated at the moment. We know, for example, that the sort order strings (like "Relevance") definitely have translations available, because they appear in the main search UI.

**Comment by kangzj** [comment]
> the issue should have been #20757.
> 
> Try switching your WP interface language - nothing is translated at the moment. We know, for example, that the sort order strings (like "Relevance") definitely have translations available, because they appear in the main search UI.

Ah sure of course you mentioned me on that issue. I'll have a look and see why.

**Comment by kangzj** [comment]
#20757 is now fix by specify the translation domain by 
```PHP
wp_set_script_translations( 'jp-search-dashboard', 'jetpack' );
```
Customburg could do similar to load the translations.

cc @bluefuton @jsnmoon

**Comment by kangzj** [comment]
I can see Customburg has added the line to set translations, but still some of the translations not loading. Looking...

**Comment by kangzj** [comment]
Hi @Automattic/jetpack-search team, the final tuning PR is now ready for review. Very much appreciate it if you folks could have a look. Thanks.

File: projects/plugins/jetpack/_inc/client/search/dashboard/mocked-instant-search.jsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function MockedInstantSearch() {
 				style={ {
 					height: '2.5em',
```
Comment (bluefuton) [inline projects/plugins/jetpack/_inc/client/search/dashboard/mocked-instant-search.jsx:33]: Is it essential for these styles to be inline or could we attach them to a CSS class instead?

File: projects/plugins/jetpack/_inc/client/search/dashboard/module-control.scss [hunk 2]
```diff
@@ -117,3 +131,47 @@ p.jp-form-search-settings-group__toggle-explanation {
...
+		display: block;
+
+		&:last-of-type {
+			font-weight: 600;
+		}
+	}
+
+	&:hover,
+	&:focus {
+		//box-shadow: 0px 0px 40px rgba( 0, 0, 0, 0.08 );
```
Comment (bluefuton) [inline projects/plugins/jetpack/_inc/client/search/dashboard/module-control.scss:154]: Can we remove this?

Comment (kangzj) [reply projects/plugins/jetpack/_inc/client/search/dashboard/module-control.scss:154]: removed in 9be6c1430c

File: projects/plugins/jetpack/_inc/client/search/dashboard/mocked-instant-search.jsx (hunk 1 above)
Comment (kangzj) [reply projects/plugins/jetpack/_inc/client/search/dashboard/mocked-instant-search.jsx:33]: The placeholder is kinda like a function where the styles are like parameters. I think in this way, we could keep it simple and stupid component, which doesn't rely on CSS  :-) Let me know if you think otherwise

**Comment by bluefuton** [comment]
This is looking really good @kangzj!

- [ ] On the smallest breakpoint, there's an unexpected gap above the Jetpack logo banner in Firefox:

Screen Shot 2021-08-25 at 16 19 02

- [ ] On the largest breakpoint, the second button wraps to two lines in French. Can we let the buttons expand to the full width of the container?

Screen Shot 2021-08-25 at 16 18 20

**Comment by annacmc** [comment]
Very nice! 

I noticed that on mobile (tested on iPhone 11) it looks like the toggles are lined up with the centre of the headline text when it overflows into two lines, rather than the top _(as it is on other Jetpack pages which use toggles and on this page when it spans only one line)_

image

Also, this is likely related to the transition questions above: When the site is set to US, or NZ English _(potentially others, too)_ **customize** should become **customise**. Likely this will resolve along with the other translation related discussion though 😃

**Review by jsnmoon — DISMISSED** [review]
Looks good to me, 🚢 it! 

EDIT: It looks like `pnpm run test-adminpage` is failing for this PR for some reason.

**Review by jeherve — APPROVED** [review]
LGTM!
