### PR TITLE
Fix: Customiser color settings affect block editor UI.

### LINKED ISSUE #7818: Colinear: Customizer colors affect post/page editor element styles on Atomic sites
### Quick summary

If you change any color in the Customizer (_Appearance > Customize > Colors & Backgrounds_), some new CSS takes effect in the editor which overrides the styles used for editor elements (including hover styles), which can make them difficult or impossible to read. This affects tabs (e.g. "Page/Post," "Block," "List View," "Outline," "Patterns," "Media") and settings headings (e.g. "Summary", "Styles," "Advanced").

### Steps to reproduce

1. Activate the Colinear theme.
2. Open a post or page in the editor. Check that the various tabs and headings in the side panels (insert block, list view, settings, Jetpack settings, kebab menu) are all legible as black text on white backgrounds with appropriate hover effects.
3. Navigate to _Appearance > Customize > Colors & Backgrounds_. Change any of the four colors and save changes.
4. Navigate back to the post/page editor (or refresh the page). Compare the various editor elements' styles with what was seen in step 2.

### What you expected to happen

Theme color styles should not affect editor elements.

### What actually happened

The theme color styles add some additional inline CSS (`custom-colors-editor-css-inline-css`), which is loaded _after_ the editor style CSS file, and therefore takes precedence. In many cases, this causes editor elements to become difficult or impossible to read when not hovered over (or when being hovered over), depending on the colors set.

Screenshot below is an example with only the "Links" color changed to a light pink. ("Block" tab in the right settings sidebar is being hovered over.)

### Browser

_No response_

### Context

Initial report in 8219316-zd-a8c. Similar to https://github.com/Automattic/themes/issues/6955 (Illustratr theme).

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

Only tested on Atomic so far. 

Initial customer reported that this affected the help center window as well, though I haven't been able to replicate that yet. Asking them for more information or screenshots – if this affects the help center, I'd imagine that will affect the priority of this issue.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
Currently when colors are choosen on "Colors & Backgrounds" section of the customizer, the styles on the editor are not enqued as block editor styles and affect/break the block editor UI.

Fixes https://github.com/Automattic/themes/issues/7818.

## Proposed changes:
This PR instead of printing the styles directly on the block editor, uses the filter block_editor_settings_all and adds the styles in the styles sections. This change ensures that the styles are wrapped with the editor's content container and don't break the editor UI. It also makes the content of the post editor reflect the chosen styles.

This is an issue that affects all sites with a theme using customiser, when colors are choose the editor UI gets broken, creating a bad experience for the users.

### Colinear

Screenshot 2025-01-14 at 23 52 06
Screenshot 2025-01-14 at 23 51 56

### Cubic
Screenshot 2025-01-14 at 23 59 36

## After

Screenshot 2025-01-14 at 23 51 09
Screenshot 2025-01-14 at 23 50 53

### Cubic
Screenshot 2025-01-14 at 23 58 28

## Testing instructions:
Enable the "Colinear" theme (other themes with customizer have similar issues or even worse problems).
Go to the customizer, open "Colors & Backgrounds" make the link color green (second color).
Create a new post and add a link in a pagraph verify the link is green (on trunk it is not).
Hoover around the editor UI on sections like "Excerpt" "Categories" etc, verify the UI looks ok (on trunk the elements become green on hoover).

Repeats the steps with the Cubic theme, verify the background color is reflected on the editor on this branch but not on trunk.

## Does this pull request change what data or activity we track or use?

No.

### CODE REVIEW

File: projects/plugins/wpcomsh/custom-colors/colors.php [hunk 1]
```diff
@@ -1483,17 +1483,33 @@ public static function print_theme_css() {
...
-			return;
+			return $editor_settings;
 		}
+
 		$css = self::get_theme_css();
 
-		wp_register_style( 'custom-colors-editor-css', false, array(), '20210311' ); // Register an empty stylesheet to append custom CSS to.
-		wp_enqueue_style( 'custom-colors-editor-css' );
-		wp_add_inline_style( 'custom-colors-editor-css', $css ); // Append inline style to our new stylesheet
+		if ( is_array( $editor_settings['styles'] ) ) {
```
Comment (youknowriad) [inline projects/plugins/wpcomsh/custom-colors/colors.php]: I think the code here can be simplified by initializing the array to avoid duplication:

 ```
if ( is_array( $editor_settings['styles'] ) ) {
   $editor_settings['styles'] = array();
}
```

File: projects/plugins/wpcomsh/custom-colors/colors.php [hunk 2]
```diff
@@ -1483,17 +1483,33 @@ public static function print_theme_css() {
...
+		} else {
+			$editor_settings['styles'] = array(
+				array(
+					'css'            => $css,
+					'__unstableType' => 'theme',
+					'isGlobalStyles' => false,
+				),
+			);
+		}
+		return $editor_settings;
```
Comment (youknowriad) [inline projects/plugins/wpcomsh/custom-colors/colors.php:1507]: Reading this code, it seems what we want is to "add an editor style". But we want that style to be dynamic (generated in the server). 

Unfortunately `add_editor_style`'s WP function doesn't support adding inline styles (it only sources from files and urls). So I think personally if a ticket or issue doesn't exist on WordPress Core, it's worth creating. (A dedicated function to add an inline editor style).

I know the code here does the same, but for me that's a bit too low level.

**Review by youknowriad — DISMISSED** [review]
It fixes the issue in my testing.

One interesting potential side effect is that some of these classic themes have a background style but also a "content background style", what happens now is that the background style is applied to the editor but not the "content background style" which means you might have weird results. 

That said, I believe that's out of scope here and hard to fix.

File: projects/plugins/wpcomsh/custom-colors/colors.php (hunk 2 above)
Comment (jorgefilipecosta) [reply projects/plugins/wpcomsh/custom-colors/colors.php:1507]: Yes, I think an add_editor_styles function which receives dynamic styles instead of a file or URL may make sense. I will create an issue.
