### PR TITLE
Site Editor Compatibility: Podcast Player block issues in editor and front end views

### LINKED ISSUE #19483: Site Editor Compatibility: Podcast Player block issues in editor and front end views
In the new site editor in Gutenberg (`/wp-admin/admin.php?page=gutenberg-edit-site`), there are some issues with the Podcast Player block within the editor and on the front end of the site. The issues include:

* Within the editor, the styling and behaviour for the player doesn't appear to be rendering (perhaps an issue with how the block works with the site editor iframe?)
* On the front end of the site, the player itself isn't being rendered / loaded

#### Steps to reproduce the issue

1. Grab an RSS feed from your favourite podcast (here's one for Distributed.blog: https://distributed.blog/category/podcast/feed/)
2. With the Gutenberg plugin active (>=10.4.0-rc1), activate a block-ready theme (like tt1-blocks)
3. In the site editor, insert a Podcast Player block into the Footer template part
4. Add the feed URL from your favourite podcast and click embed
5. Observe that the player isn't rendered correctly.
6. Save the template part and view the front end of your site
7. Observe that the podcast player interface isn't loaded / rendered

#### What I expected
* The player to be available within the editor canvas and to be styled correctly.
* The player to be available on the front end of the site

| Editor view | Front end view |
| --- | --- |
| image | image |

#### What happened instead
* The player is not available within the editor canvas
* The player was not rendered on the front end of the site

| Editor view | Front end view (note missing player) |
| --- | --- |
| image | image |

### PR DESCRIPTION
**Pull request by ramonjd**
This PR addresses Podcast Player block compatibility issues in the site editor, and on the frontend in block-based themes.

Fixes #19483

#### Changes proposed in this Pull Request:

1. Adds a check to see if the DOM is loaded before initializing the block on the frontend.
2. Adds a temporary workaround to inject required assets into the Site Editor iframe.

Screen Shot 2021-04-21 at 3 13 14 pm

#### Jetpack product discussion
Related to Automattic/jetpack#19504

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
1. Using a block-based theme, e.g., TT1 add a Podcast block to the site editor. Here's an RSS feed link: https://distributed.blog/category/podcast/feed/ 😄 
2. Once loaded, you should be able to interact with the player as expected.
3. Add another one.
4. Both should work 
5. Check that, for every podcast block you add, we're not duplicating the mediaelement-css assets.
6. Take a look at the frontend. The player(s) should both load.
7. Check a few other themes for regressions.
8. Sync the changes to WPCOM and ensure that both the block and site editors work as expected.

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js [hunk 1]
```diff
@@ -123,3 +123,26 @@ export const getColorsObject = memoize( generateColorsObject, config => {
...
+ */
+export function __maybeInjectStylesIntoSiteEditor() {
+	// Check to see if we're in the site editor.
+	const iframe = document.querySelector( 'iframe[name="editor-canvas"]' );
+
+	if ( iframe ) {
+		const mediaElementCSS = document.querySelector( 'link#mediaelement-css' );
+		const wpMediaElementCSS = document.querySelector( 'link#wp-mediaelement-css' );
+
+		if ( ! iframe.contentDocument.querySelector( 'link#mediaelement-css' ) ) {
```
Comment (andrewserong) [inline projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js:138]: Do we need to check that `mediaElementCSS` is not `null`, too, just in case for some reason the above querySelector on the parent document doesn't match against anything?

File: projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js [hunk 2]
```diff
@@ -123,3 +123,26 @@ export const getColorsObject = memoize( generateColorsObject, config => {
...
+			iframe.contentDocument.head.appendChild( mediaElementCSS.cloneNode() );
+			mediaElementCSS.remove();
+		}
+
+		if ( ! iframe.contentDocument.querySelector( 'link#wp-mediaelement-css' ) ) {
```
Comment (andrewserong) [inline projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js:143]: Similar to above, do we need to check that `weMediaElementCSS` is not `null`, too, just in case for some reason the above querySelector on the parent document doesn't match against anything?

**Review by andrewserong — COMMENTED** [review]
Thanks for investigating this one @ramonjd. I think this looks like a reasonable temporary workaround. I haven't tested it yet, but just wondered if we should add a couple of extra checks just in case (for some reason?) the expected CSS hasn't been enqueued in the parent document?

**Comment by andrewserong** [comment]
Oh, it's complaining about a missing changelog entry too 🙂

File: projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js (hunk 1 above)
Comment (ramonjd) [reply projects/plugins/jetpack/extensions/blocks/podcast-player/utils.js:138]: We probably should do that. Thanks!

**Comment by glendaviesnz** [comment]
@ramon it looks like there might be some funny race condition as it doesn't work for me locally as he useEffect never gets fired with a podcastPlayerRef.current defined.

TIL - it seems like you can't rely on ref to cause a rerender when it the dom node is assigned/changed and should use a callback ref instead. I switched it to the following locally and that seemed to fix it for me:
```js
	const podCastPlayerRef = useCallback(
		node => {
			if ( node !== null && ! hasMigratedStyles ) {
				maybeCopyElementsToSiteEditorContext(
					[ 'link#mediaelement-css', 'link#wp-mediaelement-css' ],
					node
				);
				setHasMigratedStyles( true );
			}
		},
		[ hasMigratedStyles ]
	);
```

File: projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+	const parentDoc = currentWindow?.parent?.document;
+	let results = [];
+
+	if ( currentDoc && parentDoc ) {
+		results = elementSelectors.filter( selector => {
+			const parentElementToCopy = parentDoc.querySelector( selector );
+			const isElementAlreadyPresentInCurrentWindow = !! currentDoc.querySelector( selector );
+			if ( parentElementToCopy && ! isElementAlreadyPresentInCurrentWindow ) {
+				currentDoc.head.appendChild( parentElementToCopy.cloneNode() );
+				parentElementToCopy.remove();
```
Comment (andrewserong) [inline projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js:56]: Do we need to remove the element from the parent document? I don't have a practical example of this, but just imagining if for some reason a plugin were to enqueue the mediaelement for use in the sidebar inspector, which is rendered outside of the site editor iframe context?

Comment (ramonjd) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js:56]: No, there was no pressing need. It was more of a OCD clean up manoeuvre.

You have a make a good hypothetical point though and there's no real harm in leaving it in there. I'll remove it. 👍

Comment (ramonjd) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js]: I made it optional. For generic purposes, there might be a use case for removing it, maybe if the source element has styles/js that bork if their corresponding HTML isn't there or some other completely made up scenario.

Comment (andrewserong) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js]: Oh, good thinking!

**Comment by andrewserong** [comment]
This is testing well in FSE across Safari, FF, Chrome, and Edge. Unfortunately, I think this approach introduces a regression in a non-FSE theme in wpcom. Because in that context we are rendering Gutenberg within an iframe from wordpress.com, it looks like it's attempting to access the wrong parent document (e.g. the `ref` is not within the site editor iframe, but _is_ within the iframe rendered within wordpress.com, so it's now trying to break out of Gutenberg). Here's the error after entering a podcast feed URL in the placeholder:

image

File: projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js [hunk 4]
```diff
@@ -0,0 +1,67 @@
...
+/**
+ * Returns whether a given element is contained within an iframe.
+ * Useful to check if a block sits inside the Site Editor.
+ *
+ * @param   {HTMLElement} elementRef - The element whose context we want to return.
+ * @returns {boolean}                - Whether `elementRef` is contained within an iframe.
+ */
+export function isElementInIframe( elementRef ) {
+	const { currentWindow } = getLoadContext( elementRef );
+	return currentWindow.self !== currentWindow.top;
```
Comment (andrewserong) [inline projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js:24]: We might need to add an additional check either here or within `getLoadContext` that we're in the _correct_ iframe (the site editor) and not within another version of an iframed editor (e.g. the post/page editor iframed within `wordpress.com/post/<blog_name>/<post_id>`).

Comment (ramonjd) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js:24]: Oh wow, thanks for double checking that. 🤕 

I did check in WPCOM when I was initially targeting `'iframe[name="editor-canvas"]'` 

I'll try to reinstate that test. 

THANK YOU

Comment (ramonjd) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js]: I re-added an iframe name check. Not ideal, but the whole thing is (theoretically) transitory.

I could try to check in the back end and add a global JS variable if it might help future endeavours.

Comment (ramonjd) [reply projects/plugins/jetpack/extensions/shared/block-editor-asset-loader.js]: We could also add to test that the iframe passes the same-origin-policy before we try to start injecting things into the header and bork it all again. :D

**Review by andrewserong — DISMISSED** [review]
Thanks for implementing all those changes @ramonjd! This is testing nicely for me now. I re-tested in FSE across Safari, FF, Edge, and Chrome, via wordpress.com/site-editor and directly from the the site, and double-checked that the addition of checking for the iframe name resolves the regression 👍

LGTM!

**Comment by ramonjd** [comment]
>  I re-tested in FSE across Safari, FF, Edge, and Chrome, via wordpress.com/site-editor and directly from the the site

Thanks for testing so thoroughly! I added another, small condition to see if the child iframe has access to its parent (same origin). Hopefully will prevent borks if the editor iframe name ever changes.

**Review by andrewserong — APPROVED** [review]
Thanks for adding the additional check @ramonjd 👍 that looks safer. Just gave this another quick smoke test in the post/page editor (via wordpress.com iframe and via wp-admin) and the site editor (again via wordpress.com/site-editor and the direct /wp-admin url). LGTM! 🎉

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍

**Comment by ramonjd** [comment]
r224746-wpcom

**Comment by ramonjd** [comment]
An api is being added to core Gutenberg that we may be able to use instead of the CSS shuffling: WordPress/gutenberg#31873
