### PR TITLE
Related Posts: allow author to set headline level

### LINKED ISSUE #34973: Related Posts: Headline conflicts with page outline
### Impacted plugin

Jetpack

### Quick summary

The _Related Posts_ block has an optional _Headline_ setting, which is rendered as a `h3` heading in the site.

A clear document outline is essential to communicate the organization of the content on a page. Heading levels shouldn't be skipped, and the behavior described above assumes that a page has `h1` and `h2` headings.

If set, the headline should respect the page heading structure instead of choosing a level arbitrarily.

Screenshot 2024-01-11 at 2 58 20 PM

### Steps to reproduce

1. Create a new post
2. Add a _Related Posts_ block
3. In the settings panel, add a headline
4. Open the preview
5. Notice the headline is rendered in a `h3`

### A clear and concise description of what you expected to happen.

A straightforward solution is to let the user set the heading level. Maybe the most "Gutenberg-like" way of doing this is to remove the headline from the settings panel and add a `core/heading` as a child block instead.

A more involved option is automatically setting the heading level based on the current page structure, on updating the page.

### What actually happened

The headline is rendered in a `h3`.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/34973

## Proposed changes:

The _Related Posts_ block can have a headline. Until now, this headline was an attribute that authors could edit in the settings panel. It was rendered inside an `h3` tag on the front end, regardless of the other page headings. This behavior could break the outline of the page and confuse some users, such as screen reader users.

This PR solves this issue by removing the headline from the settings and adding it as a child block instead. This way, the authors can choose the heading level and provide a consistent page outline to their site visitors.

| Before | After |
| - | - |
|Screenshot 2024-01-31 at 10 55 42 AM|Screenshot 2024-01-31 at 11 58 44 AM|

In more details, the PR:
- creates a deprecated version of the block to which current pages can fall back without breaking
- removes the `headline` and `displayHeadline` attributes
- adds a `core/heading` child block to the _Related Posts_ block
- ensures the block navigation has a consistent label

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

WARNING: before spinning up a site with this branch, check the _Prerequisites_ section.

### Prerequisites

- Spin up a test site that doesn't run this branch
- Create two posts: one with a _Related Posts_ block that has a heading and another one that has not
Screenshot 2024-01-31 at 10 55 42 AM

- Keep these posts open in your browser tabs
- For each post, open the preview in a new tab

### Testing

- Switch the Jetpack version of your test site to this branch
- For each of the two posts and their preview
  - open the dev console
  - reload the page and check that everything looks okay
  - check there's no error in the console
- Create a new post
- Add a _Related Posts_ block
- Notice that you can add a heading from inside the block
Screenshot 2024-01-31 at 11 58 44 AM

- Enter a heading and choose a level
- Check it renders as expected on the front end

### CODE REVIEW

**Review by andrii-lysenko — DISMISSED** [review]
This tests well for me and looks good codewise.

Due to being a breaking change I'd suggest having additional approval review on this.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 1]
```diff
@@ -492,27 +493,35 @@ public function render_block( $attributes, $content ) {
...
 		}
 
-		$headline_id     = 'relatedposts-headline-' . uniqid();
 		$headline_markup = '';
 
-		if ( $block_attributes['show_headline'] === true ) {
+		if ( isset( $block ) ) {
+			foreach ( $block->inner_blocks as $inner_block ) {
+				if ( 'core/heading' === $inner_block->name && ! empty( trim( wp_strip_all_tags( $inner_block->inner_html ) ) ) ) {
+					$headline_markup = $inner_block->inner_html;
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php]: Should we add the escaping here instead of in the check above?

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 2]
```diff
@@ -492,27 +493,35 @@ public function render_block( $attributes, $content ) {
...
 		$display_markup = sprintf(
-			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" %6$s>%4$s%5$s</nav>',
+			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" aria-label="%6$s">%4$s%5$s</nav>',
 			! empty( $wrapper_attributes['class'] ) ? ' ' . esc_attr( $wrapper_attributes['class'] ) : '',
 			! empty( $wrapper_attributes['style'] ) ? ' style="' . esc_attr( $wrapper_attributes['style'] ) . '"' : '',
 			esc_attr( $block_attributes['layout'] ),
 			$headline_markup,
 			$list_markup,
-			empty( $headline_markup ) ? 'aria-label="' . esc_attr( __( 'Related Posts', 'jetpack' ) ) . '"' : 'aria-labelledby="' . esc_attr( $headline_id ) . '"'
+			empty( $headline_markup ) ? esc_attr( __( 'Related Posts', 'jetpack' ) ) : esc_attr( wp_strip_all_tags( $headline_markup ) )
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php]:
```suggestion
			empty( $headline_markup ) ? esc_attr__( 'Related Posts', 'jetpack' ) : esc_attr( wp_strip_all_tags( $headline_markup ) )
```

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 3]
```diff
@@ -492,27 +493,35 @@ public function render_block( $attributes, $content ) {
...
+
 		$display_markup = sprintf(
-			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" %6$s>%4$s%5$s</nav>',
+			'<nav class="jp-relatedposts-i2%1$s"%2$s data-layout="%3$s" aria-label="%6$s">%4$s%5$s</nav>',
 			! empty( $wrapper_attributes['class'] ) ? ' ' . esc_attr( $wrapper_attributes['class'] ) : '',
 			! empty( $wrapper_attributes['style'] ) ? ' style="' . esc_attr( $wrapper_attributes['style'] ) . '"' : '',
 			esc_attr( $block_attributes['layout'] ),
 			$headline_markup,
 			$list_markup,
-			empty( $headline_markup ) ? 'aria-label="' . esc_attr( __( 'Related Posts', 'jetpack' ) ) . '"' : 'aria-labelledby="' . esc_attr( $headline_id ) . '"'
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:515]: Is it okay that we're losing the `aria-labelledby` markup in this case?

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php [hunk 4]
```diff
@@ -492,27 +493,35 @@ public function render_block( $attributes, $content ) {
...
+			}
+		}
+
+		if ( empty( $headline_markup ) && $block_attributes['show_headline'] === true ) {
 			$headline = $block_attributes['headline'];
 			if ( strlen( trim( $headline ) ) !== 0 ) {
 				$headline_markup = sprintf(
-					'<h3 id="%2$s" class="jp-relatedposts-headline">%1$s</h3>',
-					esc_html( $headline ),
-					esc_attr( $headline_id )
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:504]: I take it the `$headline_id` wasn't necessary anymore? Could this be an issue if folks had added links to that anchor somehow?

**Review by jeherve — COMMENTED** [review]
It tests well for me, nice work! I only have a few questions on the implementation details, below.

**Comment by Aurorum** [comment]
This is primarily because I'm wondering if the Top Posts and Pages block should include something similar, but may I ask what the advantages are to including a headline to the block at all? Why can't a user just insert a normal Heading block above the Related Posts block?

**Comment by monsieur-z** [comment]
> This is primarily because I'm wondering if the Top Posts and Pages block should include something similar, but may I ask what the advantages are to including a headline to the block at all? Why can't a user just insert a normal Heading block above the Related Posts block?

@Aurorum, good point. It's for a backward compatibility reason. Had we created the block from scratch, we probably wouldn't have added a headline in the block.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php (hunk 2 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php]: Forgot about this one, thanks!

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php (hunk 1 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php]: Makes sense!

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php (hunk 3 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:515]: Yes, I should have added a note about it. My initial approach was to add an id to the heading tag and use `aria-labelledby` to reference it in the nav label. However, I only managed to get the headline markup and content as a string (with `$inner_block->inner_html`), and parsing it to add an attribute and reconstruct the string seemed overkill compared to using `aria-label` with the heading text content.

File: projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php (hunk 4 above)
Comment (monsieur-z) [reply projects/plugins/jetpack/modules/related-posts/jetpack-related-posts.php:504]: I should have added a note here, too. See the previous comment for why I removed it. It's not an issue since the id was hardcoded: it's not user-populated.

**Review by andrii-lysenko — APPROVED** [review]
Looks good 👍
