### PR TITLE
Shortcode: Get rid of custom shortcodes for YouTube and Vimeo in favor of Core

### LINKED ISSUE #7370: Shortcode Embeds: should include title attribute on iframe output to meet accessibility standards
#### Steps to reproduce the issue
The use of oEmbed with Shortcode Embeds enabled or using the embed shortcodes directly have iframe code which then lacks a title attribute.

#### What I expected
Section 508 and WCAG 2.0 accessibility standards request/require title attributes to be included on iframe elements which describes the content of the iframe for screen readers, etc.

#### What happened instead
Iframes output by the current version of the Shortcode Embeds module are missing the title attribute.

As an aside, it seems like previous versions of some iframe templates had the title attribute, and the removal of this seems to be odd (don't know why it would've been removed) considering the removal of the title attribute causes the resulting code to fail accessibility standards.

I had originally posted this on the WordPress.org support forum here: https://wordpress.org/support/topic/shortcode-embeds-module-should-include-title-attribute-on-iframe-output/

### LINKED ISSUE #91098: Embed: Missing title in iFrame markup for oEmbed videos
### Quick summary

The Embed block is not fetching and/or inserting the title response in the iFrame markup for oEmbeds. This seems isolated to the WordPress.com platform, as it works as expected on self-hosted sites. 

Confirming that the videos used for testing return titles:
https://debug.iframely.com/?uri=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Daqz-KE-bpKQ
https://debug.iframely.com/?uri=https%3A%2F%2Fvimeo.com%2F1084537

### Steps to reproduce

1. Embed a YouTube or Vimeo link on a page (for example, https://www.youtube.com/watch?v=aqz-KE-bpKQ or https://vimeo.com/1084537)
2. Inspect the rendered HTML and there is no title on the iFrame. 

### What you expected to happen

There should be a `title=""` attribute grabbed from the oEmbed response. 

### What actually happened

No `title` attribute

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

During testing, I'm seeing different results on Simple and Atomic for Vimeo and YouTube:

Simple: Title shows for Vimeo but not for YouTube
Atomic: Title shows for neither

Simple site rendered HTML:

```
<figure class="wp-block-embed is-type-video is-provider-vimeo wp-block-embed-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<div class="embed-vimeo"><iframe title="Big Buck Bunny" src="https://player.vimeo.com/video/1084537?dnt=1&amp;app_id=122963" width="500" height="281" frameborder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write"></iframe></div>
</div></figure>

<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<span class="embed-youtube" style="text-align:center; display: block;"><iframe class="youtube-player" width="640" height="360" src="https://www.youtube.com/embed/aqz-KE-bpKQ?version=3&amp;rel=1&amp;showsearch=0&amp;showinfo=1&amp;iv_load_policy=1&amp;fs=1&amp;hl=en&amp;autohide=2&amp;wmode=transparent" allowfullscreen="true" style="border:0;" sandbox="allow-scripts allow-same-origin allow-popups allow-presentation allow-popups-to-escape-sandbox"></iframe></span>
</div></figure>
```

Atomic rendered HTML:

```
<figure class="wp-block-embed is-type-video is-provider-vimeo wp-block-embed-vimeo wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<div class="embed-vimeo" style="text-align: center;"><iframe loading="lazy" src="https://player.vimeo.com/video/1084537" width="600" height="338" frameborder="0" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen=""></iframe></div>
</div></figure>

<figure class="wp-block-embed is-type-video is-provider-youtube wp-block-embed-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper">
<span class="embed-youtube" style="text-align:center; display: block;"><iframe loading="lazy" class="youtube-player" width="640" height="360" src="https://www.youtube.com/embed/aqz-KE-bpKQ?version=3&amp;rel=1&amp;showsearch=0&amp;showinfo=1&amp;iv_load_policy=1&amp;fs=1&amp;hl=en-US&amp;autohide=2&amp;wmode=transparent" allowfullscreen="true" style="border:0;" sandbox="allow-scripts allow-same-origin allow-popups allow-presentation allow-popups-to-escape-sandbox"></iframe></span>
</div></figure>

```

### PR DESCRIPTION
**Pull request by arthur791004**
Fixes https://github.com/Automattic/wp-calypso/issues/91098
Fixes #7370

## Proposed changes:

* The custom embed handler for both YouTube & Vimeo cannot get the title of the video resources so this PR aims to remove them in favor of Core's one.
  * For YouTube, [the playlist and watch are supported by Core](https://github.com/WordPress/wordpress-develop/blob/f4761a3f8c5aa6920d4407e3af271ef70db5f305/src/wp-includes/class-wp-oembed.php#L54-L57) so it seems okay to remove the custom one
  * For Vimeo, we never enable the custom one on wpcom so I think it's okay to remove the it as well

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Apply changes to your site
* Create a new post/page
* Insert the YouTube Embed blocks
  * https://www.youtube.com/watch?v=o_nxIQTM_B0
  * https://www.youtube.com/playlist?list=PL5AdamETFtKQEHSpJ-4jrkOOv_3e2z9av
  * https://www.youtube.com/shorts/zwP6Cz3Z9Uc
* Insert the Vimeo Embed blocks
  * https://player.vimeo.com/video/661136107
  * https://vimeo.com/661136107
  * https://vimeo.com/groups/758728/videos/897094040
  * https://vimeo.com/album/2838732/video/6342264
  * https://vimeo.com/555942796/e712a2e45d (Need to purchase)
  * https://vimeo.com/1003283038 (Live)
* Save & Preview your post/page
* Make sure the embed block is rendered correctly
* Make sure the iframe element has the correct title

### CODE REVIEW

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php [hunk 1]
```diff
@@ -246,53 +246,6 @@ class_exists( 'Jetpack_AMP_Support' )
...
-	}
-
-	return vimeo_shortcode( $vimeo_info );
-}
-
-/**
- * For bare URLs on their own line of the form.
- *
- * Accepted formats:
- * https://vimeo.com/289091934/cd1f466bcc
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php]: It would be worth making sure that Core handles this format as well. Those are private videos, iirc. See this issue for more information:
https://github.com/Automattic/wp-calypso/issues/57257

Comment (arthur791004) [reply projects/plugins/jetpack/modules/shortcodes/vimeo.php]: Will check! I thought it's not supported by Vimeo now 😂

Comment (arthur791004) [reply projects/plugins/jetpack/modules/shortcodes/vimeo.php]: > An example of a live video would be https://vimeo.com/635643256/b6a59a4d1e
> An example of a video to purchase would be https://vimeo.com/555942796/e712a2e45d

I tested the video that needs to purchase, and it works well. However, the above live video is outdated so I cannot check whether the live video with the above format works or not. But I tested another live video, https://vimeo.com/1003283038, and it works!

In short, I assume Core supports the vimeo video with the above format, e.g.: https://vimeo.com/555942796/e712a2e45d

Comment (arthur791004) [reply projects/plugins/jetpack/modules/shortcodes/vimeo.php]: I think it supports all format as the Core uses `http://vimeo.com/api/oembed.json` endpoint to ask the information about the url, e.g. `http://vimeo.com/api/oembed.json?url=http://vimeo.com/76979871`

See http://developer.vimeo.com/apis/oembed

**Comment by arthur791004** [comment]
The failing `WordPress.com Tests` is expected as we remove the `wpcom_youtube_embed_crazy_url`. So, we have to update the wpcom tests when deploying.

File: projects/plugins/jetpack/changelog/feat-remove-custom-embed [hunk 2]
```diff
@@ -0,0 +1,4 @@
+Significance: patch
+Type: bugfix
+
+Shortcode: Get rid of custom shortcodes for Youtube and Vimeo in favor of Core
```
Comment (jeherve) [inline projects/plugins/jetpack/changelog/feat-remove-custom-embed]: I would recommend updating this a bit:

```suggestion
Type: compat

Embeds: prioritize YouTube and Vimeo embeds provided by WordPress itself, over Jetpack's embedding solution.
```

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php [hunk 3]
```diff
@@ -246,53 +255,6 @@ class_exists( 'Jetpack_AMP_Support' )
...
- *
- * @since 3.9
- *
- * @param array $matches Regex partial matches against the URL passed.
- * @param array $attr    Attributes received in embed response.
- * @param array $url     Requested URL to be embedded.
- *
- * @return string Return output of Vimeo shortcode with the proper markup.
- */
-function wpcom_vimeo_embed_url( $matches, $attr, $url ) {
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php:260]: Instead of just removing the function, I would recommend marking it as deprecated first, and only remove it in a few releases. Since Vimeo embeds have been around for a long time, it's possible that third-parties currently do something with those functions.

Same for other functions in this PR.

File: projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.vimeo.php [hunk 4]
```diff
@@ -186,7 +186,7 @@ public function test_replace_url_with_iframe_in_the_content( $url, $video_id ) {
 
 		global $post;
 
-		$post = self::factory()->post->create_and_get( array( 'post_content' => $url ) );
+		$post = self::factory()->post->create_and_get( array( 'post_content' => "[vimeo $url]" ) );
```
Comment (jeherve) [inline projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.vimeo.php:189]: Since the content goes from just a URL to a shortcode with a URL, should the function name be updated accordingly?

**Review by jeherve — COMMENTED** [review]
This is looking good. I have some minor remarks on actually releasing this, below.

File: projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.vimeo.php (hunk 4 above)
Comment (arthur791004) [reply projects/plugins/jetpack/tests/php/modules/shortcodes/test-class.vimeo.php:189]: Renamed to `test_shortcodes_vimeo_replace_url_with_iframe_in_the_content`

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php (hunk 3 above)
Comment (arthur791004) [reply projects/plugins/jetpack/modules/shortcodes/vimeo.php:260]: Updated!

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php [hunk 5]
```diff
@@ -250,6 +259,7 @@ class_exists( 'Jetpack_AMP_Support' )
  * Callback to modify output of embedded Vimeo video using Jetpack's shortcode.
  *
  * @since 3.9
+ * @deprecated since x.x.x
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php]: You can use the `$$next-version$$` placeholder; it will be automatically replaced on release.

https://github.com/Automattic/jetpack/blob/d3f58235992e84fcc8a4b1bc191c56ba6edf213a/projects/packages/README.md#L116-L123

```suggestion
 * @deprecated since $$next-version$$
```

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php [hunk 6]
```diff
@@ -278,21 +288,14 @@ function wpcom_vimeo_embed_url( $matches, $attr, $url ) {
  * http://player.vimeo.com/video/18427511
  *
  * @since 3.9
+ * @deprecated since x.x.x
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php]:
```suggestion
 * @deprecated since $$next-version$$
```

File: projects/plugins/jetpack/modules/shortcodes/youtube.php [hunk 7]
```diff
@@ -527,21 +527,24 @@ function jetpack_shortcode_youtube_dimensions( $query_args ) {
...
+ * @param string $url     Requested URL to be embedded.
  */
 function wpcom_youtube_embed_crazy_url( $matches, $attr, $url ) {
 	return youtube_id( $url );
 }
 
 /**
  * Add a new handler to automatically transform custom Youtube URLs (like playlists) into embeds.
+ *
+ * @deprecated since x.x.x
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/youtube.php]:
```suggestion
 * @deprecated since $$next-version$$
```

File: projects/plugins/jetpack/modules/shortcodes/vimeo.php (hunk 5 above)
Comment (jeherve) [inline projects/plugins/jetpack/modules/shortcodes/vimeo.php]: On top of that deprecation warning, I think you could add a warning to developers via `_deprecated_function`:
https://developer.wordpress.org/reference/functions/_deprecated_function/

https://github.com/Automattic/jetpack/blob/f0fa2c82dce0cb507b892645e27a9fafd8ab87e0/docs/coding-guidelines.md#L54-L55

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
8676719-zen seems to report issues when trying to embed a private YouTube video. @arthur791004 Do you think you could take a look at that?

**Comment by arthur791004** [comment]
I tested a scheduled video, and
* In the editor, it doesn't work and I don't think it's related to this change. But as 8676719-zd-a8c mentioned, it seemed to work in the editor before 🤔
* In the frontend, it worked before as the `wpcom_youtube_embed_crazy_url` would convert the YouTube URL to the embed block. However, it doesn't work after this PR as the Core won't convert it to the embed block on the server side. Instead, you have to use the shortcode to display it

Now the current experience on both editor and frontend is the same, it would be better to propose changes to Gutenberg to support it in the editor. Does it make sense?

---

> YouTube – only public and “unlisted” videos and playlists can be embedded. “private” videos cannot be embedded.

BTW referring to https://wordpress.org/documentation/article/embeds/, it seems the “private” video is not supported by Core, and the scheduled video is a private video before the scheduled time.

**Comment by jeherve** [comment]
> it would be better to propose changes to Gutenberg to support it in the editor. Does it make sense?

Yes, that would be a nice improvement.

**Comment by arthur791004** [comment]
But the problem seems that the current YouTube oembed endpoint won't return the information of the private video 🥲

Here is the endpoint: `https://www.youtube.com/oembed?format=json&url=<youtube_url>`
