### PR TITLE
VideoPress: Fix image URLs in the block editor

### LINKED ISSUE #28779: VideoPress: get 404 error on Dynamic colors example
I get 404 error on Dynamic colors example from Block settings > Color

Simple | Jetpack
-----|-----
Image| Image

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #28779

## Proposed changes:

* Adds a helper function that uses the `plugin_dir_url` function to determine the right URL for images added in the block editor.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

On simple site, where the problem is happening:
* Apply this branch to your simple site sandbox
* In the block inserter, click "Browse all"
* Search for VideoPress
* Hover over the VideoPress icon
* Check that the example image loads
* Add a VideoPress block and upload a video
* Select the block and go to the Color panel
* Check that the image loads correctly
* Copy the image URL
* Reset your sandbox back to production and disconnect from it
* Hard reload
* Go to the Color panel again and find the broken image
* Manually change its `src` to the previously copied value
* Check that the image loads correctly
* Check the images on JN and WoA as well, they should keep loading normally

Before | After
-|-
 | 

Before | After
-|-
 |

### CODE REVIEW

File: projects/packages/videopress/src/class-block-editor-extensions.php [hunk 1]
```diff
@@ -159,6 +159,7 @@ public static function enqueue_extensions() {
 			'jetpackVideoPressSettingUrl' => admin_url( 'admin.php?page=jetpack#/settings?term=videopress' ),
 			'isVideoPressModuleActive'    => Status::is_jetpack_plugin_and_videopress_module_active(),
 			'isStandaloneActive'          => Status::is_standalone_plugin_active(),
+			'imageURLBase'                => plugin_dir_url( __DIR__ ) . 'build/images/',
```
Comment (retrofox) [inline projects/packages/videopress/src/class-block-editor-extensions.php]: really minor one:

```suggestion
			'imagesURLBase'               => plugin_dir_url( __DIR__ ) . 'build/images/',
```

if we commit this change, we'll have to update the client-side part.

**Comment by lhkowalski** [comment]
Confirmed that the block preview image and the Colors panel image are loading as expected on Simple sites:

Screen Shot 2023-02-10 at 10 44 21

Screen Shot 2023-02-10 at 10 45 08

---

Jetpack site is working as expected:

Screen Shot 2023-02-10 at 10 52 38

Screen Shot 2023-02-10 at 10 53 02

---

Atomic site is working as expected as well:

Screen Shot 2023-02-10 at 10 59 30

Screen Shot 2023-02-10 at 10 59 57

**Review by lhkowalski — APPROVED** [review]
Code changes are looking good and the fix is working as expected 🚀
