### PR TITLE
Remove Settings links and buttons from disconnected views.

### LINKED ISSUE #6461: Settings UI: settings button should not be visible if site is disconnected
#### Steps to reproduce the issue
Make sure the site is disconnected

#### What I expected
Settings split button and link in admin menu to be hidden. Additionally since user can't switch to Settings, the Dashboard button and link should also be hidden

#### What happened instead
captura de pantalla 2017-02-21 a las 11 51 13

### PR DESCRIPTION
**Pull request by zinigor**
Fixes #6461 

#### Changes proposed in this Pull Request:
* Removes the navigation button group from static loading placeholders.
* Removes the navigation button group from disconnected sites that are not in dev mode.
* Adds a page reload on site disconnection to refresh the sidebar navigation.

#### Testing instructions:
* Reload the admin page, observe the Masthead element. There should be no button group in loading state.
* Disconnect the site from the dashboard, you should observe a page being reloaded and scrolled back to top. Settings link shouldn't be there in the left sidebar.
* In disconnected mode observe that there are no buttons in the Masthead.
* Turn development mode on, observe the button group in the Masthead.

### CODE REVIEW

**Comment by eliorivero** [comment]
Build isn't passing ESLint due to 
```
jetpack/_inc/client/state/connection/actions.js
 20:2  error  'DISCONNECT_SITE_SUCCESS' is defined but never used  no-unused-vars
```

**Comment by zinigor** [comment]
Whoops, pushed a fix.

File: _inc/client/state/connection/actions.js [hunk 1]
```diff
@@ -79,12 +78,13 @@ export const disconnectSite = () => {
...
-				type: DISCONNECT_SITE_SUCCESS,
-				disconnectingSite: disconnectingSite
-			} );
-			dispatch( removeNotice( 'disconnect-jetpack' ) );
+		return restApi.disconnectSite().then( () => {
+
+			// Because the sidebar navigation is not connected to Jetpack state tree
+			// it is easiest to just reload the page on disconnection to remove all
+			// unneeded navigation items, like Settings.
+			window.scrollTo( 0, 0 );
```
Comment (oskosk) [inline _inc/client/state/connection/actions.js]: These two lines (`window.something`), could be moved to a Component, reacting to a props change, as we talked on Slack regarding where to put jQuery calls. 
Maybe in `Main` or `Masthead`'s `componentDidUpdate` and checking connection status in  old props vs current props

**Comment by eliorivero** [comment]
Needs rebasing.

**Comment by zinigor** [comment]
Rebased!

**Comment by eliorivero** [comment]
* While the app is loading, I can see the buttons like this once it's fully loaded, they jump in their correct position. I tried doing a `distclean` and `build`, and clearing the cache, but it's the same.

captura de pantalla 2017-03-07 a las 12 26 48

* A similar thing happens when I disconnect the site. The buttons are shown like above while the app is loading, and once it's loaded, they're removed.

**Comment by zinigor** [comment]
I can't reproduce that problem, are you sure you have updated the static files on your test server? @oskosk can you please test as well?

File: _inc/client/main.jsx [hunk 2]
```diff
@@ -121,6 +121,23 @@ const Main = React.createClass( {
...
+		// status without reloading is possible only by disconnecting a live site not
+		// in development mode.
+		if ( prevProps.siteConnectionStatus !== this.props.siteConnectionStatus ) {
+			jQuery( '#toplevel_page_jetpack ul.wp-submenu li' )
+				.filter( function() {
+					const anchor = jQuery( this ).find( 'a' );
+					if ( ! anchor.length ) {
+						return false;
+					}
+					return -1 !== anchor.attr( 'href' ).indexOf( '#/settings' );
```
Comment (dereksmart) [inline _inc/client/main.jsx]: If we're hiding this, might as well also hide the Site Stats link, right?

**Comment by dereksmart** [comment]
Tests well, just left one suggestion that's not a blocker

**Comment by eliorivero** [comment]
I added a commit that is a bit faster for jQuery and hides the Site Stats.

**Comment by eliorivero** [comment]
Can be merged after rebasing.

**Comment by zinigor** [comment]
Thanks @eliorivero ! Will merge as soon as Travis is done.
