### PR TITLE
Admin Page: better handle i18n for disconnection warnings

### LINKED ISSUE #18391: Admin Page: i18n error, strings in _n() must include a number
While checking pending translations, I stumbled upon a place in Jetpack where _n() is used incorrectly. The platform translate.wordpress.org links to https://plugins.trac.wordpress.org/browser/jetpack/tags/9.3.1/_inc/build/admin.js#L59 but right now plugin trac seems a bit slow and I get timeout when I want to grab a code sample.

The problematic string is like this:

Singular:
The Jetpack Connection is also used by another plugin, and it will lose connection.
Plural:
The Jetpack Connection is also used by other plugins, and they will lose connection.

_n() is the wrong tool to distinguish between singular and plural. It should ONLY be used when the "steering" number is included in the string.
Although it nicely takes a singular and a plural string as arguments, various languages may actually need to provide a different number of translated strings. For instance, there are languages that CAN translate singular and plural differently, but where the word forms won't change at all for various numbers in the string – so they'll provide only one translated string for a _n().

Russian translations provide at least three translations on a _n(). The singular form is used wherever the word "one" is pronounced at the end of the number (1, 21, 31, 41, 51..., 101, 121, 131...). Then they use a special form of word ("dual") for numbers that end in a pronounced 2, 3, or 4 (2, 3, 4, 22, 23, 24, 32, 33, 34...). 

You can fix this in two ways.
1. If you know the number of conflicting plugins, just include it in the string:
The Jetpack Connection is also used by &d other plugin, and it will lose connection./The Jetpack Connection is also used by &d other plugins, and they will lose connection.
2. if you don't want/or can't show the specific number, use normal logic to distinguish between "1" and ">1" and use two discrete strings instead.

You may have the same problem in more places. I just found this occurrence and decided to let you know.
If you have any additional questions, feel free to contact me via Slack "Making WordPress", either in channel "polyglots" or me directly, my username is tobifjellner there, as well.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #18391

#### Changes proposed in this Pull Request:

* Let's ensure that we display the right string regardless of the language and the number of connected plugins.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* Start from a site connected to WordPress.com and running this branch.
* Add and activate a test plugin like this one:

```php
<?php
/** Plugin Name: Jetpack Connection Test Plugin (1) */
add_action( 'plugins_loaded', function() {
        ( new Automattic\Jetpack\Config() )->ensure(
                'connection',
                array(
                      	'slug' => 'jetpack-connection-test-1',
                        'name' => 'Jetpack Connection Test Plugin (1)'
                )
        );
}, 1 );
```

* Go to Jetpack > Dashboard, and click on the Manage connection link towards the end of the page.
* You should see this:
image

* Now add and activate a second plugin:

```php
<?php
/** Plugin Name: Jetpack Connection Test Plugin (2) */
add_action( 'plugins_loaded', function() {
        ( new Automattic\Jetpack\Config() )->ensure(
                'connection',
                array(
                      	'slug' => 'jetpack-connection-test-2',
                        'name' => 'Jetpack Connection Test Plugin (2)'
                )
        );
}, 1 );
```
* You should now see this:
image

#### Proposed changelog entry for your changes:

* N/A

### CODE REVIEW

File: projects/plugins/jetpack/_inc/client/components/jetpack-termination-dialog/features.jsx [hunk 1]
```diff
@@ -110,11 +110,26 @@ class JetpackTerminationDialogFeatures extends Component {
...
+		const connectedPluginsTitle =
+			1 === connectedPlugins.length
+				? __(
+						'The Jetpack Connection is also used by another plugin, and it will lose connection.',
+						'jetpack'
+				  )
+				: sprintf(
+						/* translators: placeholder is a number. */
+						_n(
+							'The Jetpack Connection is also used by %d other plugin, and it will lose connection.',
```
Comment (kraftbj) [inline projects/plugins/jetpack/_inc/client/components/jetpack-termination-dialog/features.jsx:125]: what's the use case for this line? If it is singular, I'd expect the string above to fire.

**Review by kraftbj — CHANGES_REQUESTED** [review]

File: projects/plugins/jetpack/_inc/client/components/jetpack-termination-dialog/features.jsx (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/_inc/client/components/jetpack-termination-dialog/features.jsx:125]: This is mostly to cover for languages that have complex plural systems. There is some more info about this here:
https://developer.wordpress.org/reference/functions/_n/#comment-2397

**Review by kraftbj — APPROVED** [review]
