### PR TITLE
Stats: Fix top post card on the Insight page

### LINKED ISSUE #88005: Stats: Most popular post is not available for Odyssey Stats
Image

It seems to be working on some sites while not on others. We'd like to look into it and see what we can find.

### PR DESCRIPTION
**Pull request by kangzj**
Fixes https://github.com/Automattic/wp-calypso/issues/88005

## Proposed changes:

* Adding missing fields to the single post endpoint

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
n/a

## Does this pull request change what data or activity we track or use?
no

## Testing instructions:

* Build Odyssey Stats and Jetpack locally
* Open `/wp-admin/admin.php?page=stats#!/stats/insights/:siteSlug`
* Ensure Top post is showing up

image

Note: likes is not working and will be fixed with another PR

### CODE REVIEW

File: projects/packages/stats-admin/src/class-rest-controller.php [hunk 1]
```diff
@@ -606,9 +606,15 @@ public function get_single_post( $req ) {
 
 		// It shouldn't be a problem because only title and ID are exposed.
```
Comment (annacmc) [inline projects/packages/stats-admin/src/class-rest-controller.php]: I'm curious about this comment. Do you know what it's referring to? We are no longer only exposing the title and ID here, and have added additional information. I've read through the code and can't see what "It shouldn't be a problem" might mean in this context, or how exposing additional data could affect that?

**Review by annacmc — DISMISSED** [review]
LGTM and works as expected. Just left one non blocking comment, more out of curiosity than anything

File: projects/packages/stats-admin/src/class-rest-controller.php (hunk 1 above)
Comment (kangzj) [reply projects/packages/stats-admin/src/class-rest-controller.php]: Good catch @annacmc! The comment here is out dated. Addressed in 79d2478c97
