### PR TITLE
AMP: move checks for AMP requests later, inside modules.

### LINKED ISSUE #11123: AMP: last AMP compatibility changes impact CSS concatenation
In #10945, we made changes to our AMP compatibility file that impact the way we load CSS. Unfortunately, this change impacts all site owners currently using the `jetpack_implode_frontend_css` filter

#### Steps to reproduce the issue

1. Start from a site using Jetpack 6.8.1 and with the following code snippet: `add_filter( 'jetpack_implode_frontend_css', '__return_false' );`
2. Separate CSS files are loaded by Jetpack on the frontend.
3. Update to Jetpack 6.9
4. Your code snippet does not have any impact anymore, the concatenated `jetpack.css` is loaded instead. You have to change the priority for it to start working again, like `add_filter( 'jetpack_implode_frontend_css', '__return_false', 99 );`.

I have not tested, but I suspect this also impacts the other filters in use by the AMP compatibility file.

Reported here:
https://jetpack.com/2019/01/10/jetpack-6-9-introducing-more-tools-for-the-new-block-editor/#comment-193496

### LINKED ISSUE #11148: Carousel: 400 errors on Ajax requests to get comments for each image
#### Steps to reproduce the issue

1. Start on a post with a gallery, Carousel active, and 6.9 installed. The problem did not exist in 6.8.1. The gallery can be a classic one, or a gallery block.
2. Click on the gallery to open the carousel modal.
3. As you move through the images in the gallery, you will notice 400 errors on all the Ajax calls that are made to retrieve comments for each image.

```
wp-admin/admin-ajax.php?action=get_attachment_comments&nonce=dc6aed47f7&id=13568&offset=0
Status Code: 400 Bad Request
Response: 0
```

The problem appears to be caused by #10945.
https://github.com/Automattic/jetpack/pull/10945/files#diff-3cfca2b828797ec0937ace907f546d80R32

### LINKED ISSUE #11151: Carousel: image meta data not added to image when image is loaded via AJAX
[This filter](https://github.com/Automattic/jetpack/blob/6.8.1/modules/carousel/jetpack-carousel.php#L79) not working on ajax call. It's perfectly working on page load and carousel also working fine.  

I have `Load more` button to load images, on click of that button I am fetching images using ajax call. But during this ajax call [the filter](https://github.com/Automattic/jetpack/blob/6.8.1/modules/carousel/jetpack-carousel.php#L79) doesn't get called and the image data attribute doesn't load. 

Because data attribute doesn't load for all newly added images the carousel doesn't work for those images.

### LINKED ISSUE #11169: AMP: load order issues
Opening this to track the different issues that were caused by #10945 in Jetpack 6.9. We'll need to find a different solution to address the solution proposed in this PR, as it caused problems with different modules:

- [ ] #11151 Carousel: image meta data not added to image.
- [ ] #11148 Carousel: cannot get comments for each image.
- [ ] #11123 Sharing / Multiple modules: filters are not effective anymore.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #11151
Fixes #11148
Fixes #11123 
Fixes #11169

#### Changes proposed in this Pull Request:

Internal discussion: p1HpG7-6cV-p2

See https://github.com/Automattic/jetpack/issues/11169#issuecomment-456875877

> the AMP checks should be deferred to as late as possible.

#### Testing instructions:

* Install the AMP plugin.
* Switch AMP mode (AMP > General) to `Paired` or `Classic`.
* Activate the Carousel module, the sharing module, and ensure that `SCRIPT_DEBUG` is set to `false` on your install.
* Create a post with a gallery
* Add a Facebook sharing button to that post.
* Share that post on Facebook once.
* Comment on one of the images in the gallery.
* Load the post in a non-AMP view, and in the 3 modes available in the AMP options screen: Native, Paired, Classic. (`Native` mode -  all views are AMP views; `Paired` mode - add `?amp` to get to the AMP view; `Classic` mode - add `/amp` to get to the AMP view)
    -  **In non-AMP views:** Does the Carousel modal work? Do you see the comment in the Carousel modal? Do you see the sharing buttons? Do you see the counter next to the sharing button? Do you see the `jetpack.css` file when viewing source?
    - **In AMP views:** you should not see the Carousel. You should see a special styling of the sharing buttons. If you check the network tab in your browser tools, you should see a request to pixel.wp.com when logged out. You should not see a `jetpack.css` file in the source.

In all cases:
- You should not see any js errors in the browser console.
- You should not get any PHP notices in your debug log.

Now try adding the following to a functionality plugin on your site:

```php
add_filter( 'jetpack_implode_frontend_css', '__return_false' );
add_filter( 'jetpack_sharing_counts', '__return_false' );
```

Once you've done so, check the non-AMP view again: 
- you should not see the sharing counter on the Facebook button.
- you should not see the `jetpack.css` file in your source. 

#### Proposed changelog entry for your changes:

* Carousel: avoid errors when fetching comments in the Carousel modal.
* CSS: fix the behaviour of the CSS concatenation filter.

### CODE REVIEW

**Comment by westonruter** [comment]
Yes. I will try to do so later today or tomorrow.

File: modules/sharedaddy/sharing-service.php [hunk 1]
```diff
@@ -577,6 +577,10 @@ function sharing_maybe_enqueue_scripts() {
 }
 
 function sharing_add_footer() {
+	if ( Jetpack_AMP_Support::is_amp_request() ) {
+		return;
+	}
```
Comment (westonruter) [inline modules/sharedaddy/sharing-service.php]: 👍 This will work fine because it will run at the `wp_footer` action, which happens after `wp`.

File: class.jetpack.php [hunk 2]
```diff
@@ -6873,6 +6873,11 @@ public function implode_frontend_css( $travis_test = false ) {
 			$do_implode = false;
 		}
 
+		// Do not implode CSS when the page loads via the AMP plugin.
+		if ( Jetpack_AMP_Support::is_amp_request() ) {
```
Comment (westonruter) [inline class.jetpack.php]: 👍 This call is made during `wp_print_scripts` so it will work well.

File: 3rd-party/class.jetpack-amp-support.php [hunk 3]
```diff
@@ -14,21 +14,9 @@ static function init() {
...
-		add_filter( 'sharing_js', array( __CLASS__, 'is_not_amp_request' ) );
+		// Sharing.
 		add_filter( 'jetpack_sharing_display_markup', array( 'Jetpack_AMP_Support', 'render_sharing_html' ), 10, 2 );
 
-		// disable lazy images
-		add_filter( 'lazyload_is_enabled', array( __CLASS__, 'is_not_amp_request' ) );
-
-		// disable imploding CSS
-		add_filter( 'jetpack_implode_frontend_css', array( __CLASS__, 'is_not_amp_request' ) );
-
```
Comment (westonruter) [inline 3rd-party/class.jetpack-amp-support.php]: Good that these are integrated with the modules they relate to.

**Review by westonruter — COMMENTED** [review]
I examined the changes and they all seem valid.

**Review by brbrr — COMMENTED** [review]
FWIW: When testing on JN site - I see this error on `jetpack_modules` page: `Notice: Undefined index: copy-post in /srv/users/user3bb07467/apps/user3bb07467/public/wp-content/plugins/jetpack-dev/modules/module-headings.php on line 248`

**Comment by jeherve** [comment]
> I see this error on jetpack_modules page

This seems unrelated to this PR, and should disappear if you run `yarn build`.

**Review by brbrr — APPROVED** [review]
Tests well. Thanks!
