### PR TITLE
Instant Search: Add a button to clear applied filters

### LINKED ISSUE #14181: Instant search: add option to clear out search
#### Steps to reproduce the issue

- Enter any search term; e.g.: "maintenance".

or

- Filter content using any of the filters available; e.g.: "Year: 2019".

#### What I expected

- To have an option to clear out my search query and/or filters.
- This could be as simple as a cross, or it could be a link.
- It would clear out the search box, toggle all filters back off, and rewrite a clean URL.

image

#### What happened instead

- I'm left with clicking back in my browser (see https://github.com/Automattic/jetpack/issues/14180 for related issue) or clicking the navigation menu to go to another page.

Related: https://github.com/Automattic/jetpack/issues/13814

### PR DESCRIPTION
**Pull request by jsnmoon**
Partially fixes #14181.

#### Changes proposed in this Pull Request:
* Adds a button to clear applied filters in the overlay sidebar.

Screen Shot 2020-01-10 at 4 00 00 PM

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Yes, this adds a new feature to Jetpack Instant Search, which has not yet been launched to the public.

#### Testing instructions:
1. If you haven't already, set up Instant Search following the instructions in the [readme](https://github.com/Automattic/jetpack/blob/instant-search-master/modules/search/instant-search/README.md#testing-instructions). Ensure that you've configured filters for your Jetpack Search widget.
2. Navigate to your WordPress site and submit a query into the search widget.
3. Ensure that the search overlay appears along with the search filters on the right side. 
4. Select a search filter of choice. Ensure that your results have been filtered as expected. Ensure that a "Clear Filters" button has appeared above your filters.

#### Proposed changelog entry for your changes:

* None.

### CODE REVIEW

File: modules/search/instant-search/components/search-filter.jsx [hunk 1]
```diff
@@ -136,11 +136,11 @@ export default class SearchFilter extends Component {
 	render() {
 		return (
 			<div>
-				<h4 className="jetpack-search-filters-widget__sub-heading">
+				<h4 className="jetpack-instant-search__filter-sub-heading">
```
Comment (bluefuton) [inline modules/search/instant-search/components/search-filter.jsx]: 👍

**Review by bluefuton — APPROVED** [review]
Works a treat! 

The button is very prominent on my Twenty Sixteen test site:

Screen Shot 2020-01-13 at 14 47 54

Not sure how we work around that on a cross-theme way. Maybe use another element with `role="button"`, or just reducing font size slightly?

Happier to address that in the future and 🚢 this, though.
