### PR TITLE
Widget: remove Pay with PayPal widget from Legacy Widget block

### LINKED ISSUE #57838: Pay with PayPal Legacy Widget - Create new product within widget area
### Quick summary

When trying to add a Pay with PayPal Legacy Widget in the sidebar, it was not possible to create the new product directly, but only possible to select already created products from a dropdown.

User has to create the Pay with PayPal Block within a page to be able to then add it as a widget.

### Steps to reproduce

1. Create a Pay with PayPal Block within a page - save
2. Go to widgets and add a Pay with PayPal Legacy Widget
3. From the Pay with PayPal Legacy Widget you are able to select the payment block you made within the page in step one - but there is no way to edit or add a new Pay with PayPal Block from the widget area.
4. There is an option to direct you to the Customizer to make changes, but it is not possible to make the change from the customizer.
Annotation on 2021-11-09 at 17-53-08

Annotation on 2021-11-09 at 17-31-53

### What you expected to happen

I expect to be able to add/edit a new Pay with PayPal product from within the widget area, not have to make it within a page beforehand.

### What actually happened

From the widget area it is not possible to add a Pay with PayPal button directly, the legacy widget needs to be used, and the Pay with PayPal block needs to be created before entering the widget area.

### Context

#4441294-zen

### Operating System

_No response_

### Browser

_No response_

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Other notes

_No response_

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
#### Summary
The Pay with PayPal widget is not functioning properly inside of the Legacy Widget block. Since this functionality is available with the Pay with PayPal block we should hide the widget in favor of the block.

Fixes Automattic/wp-calypso#57838

#### Changes proposed in this Pull Request:
* Add widget to the `widget_types_to_hide_from_legacy_widget_block` filter.

#### Jetpack product discussion
#21069

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:
* Make sure you have a paid Jetpack plan to see the widget
* Go to Appearance ⇢ Customizer ⇢ Widgets
* Add the Legacy Widget block and check the drop-down for `Pay with PayPal`.

#### Screenshots
Markup 2021-11-30 at 18 54 25

Markup 2021-11-30 at 18 54 11

### CODE REVIEW

**Comment by arcangelini** [comment]
The `wpcom` test is failing due to a check against the `$widget_types` array. This test will be updated in the diff patch prior to merging.

File: projects/plugins/jetpack/changelog/update-remove-pay-with-paypal-widget-from-blocks [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Significance: minor
+Type: compat
+
+Pay with PayPal Widget - hide widget from Legacy Widget block
```
Comment (ivan-ottinger) [inline projects/plugins/jetpack/changelog/update-remove-pay-with-paypal-widget-from-blocks:4]: This is a tiny thing.

I think we generally try to use `:` instead of `-` in the Jetpack changelog file.

```suggestion
Pay with PayPal Widget: hide widget from Legacy Widget block
```

File: projects/plugins/jetpack/modules/widgets/simple-payments.php [hunk 2]
```diff
@@ -66,6 +66,7 @@ function __construct() {
 				array(
 					'classname'                   => 'jetpack-simple-payments',
 					'description'                 => __( 'Add a Pay with PayPal button as a Widget.', 'jetpack' ),
+					'show_instance_in_rest'       => true,
```
Comment (ivan-ottinger) [inline projects/plugins/jetpack/modules/widgets/simple-payments.php:69]: I _think_ that unless we are planning to add a transform from the "Pay with PayPal" widget into the "Pay with PayPal" block, this line isn't necessary.

But maybe you are planning to add that transform or I am missing something. 🤔

**Review by ivan-ottinger — COMMENTED** [review]
Works as expected 👍🏼👍🏼 , the "Pay with PayPal" widget doesn't show up (screenshots below).

I also left two comments directly in the code.

One additional thing: I think that once we deploy the change to WPCOM, it would be worth:
- reopening the docs thread (1273-gh-Automattic/en.support-docs-content) and adding a comment there - so folks can update the relevant docs (e.g. https://wordpress.com/support/pay-with-paypal/#pay-with-pay-pal-widget-footer-sidebar-etc)
- letting Happiness know about the change (similarly as we did here for example: p1636129680147500-slack-CB0B2G43X)

Markup on 2021-12-01 at 10:13:20
Markup on 2021-12-01 at 10:37:30

File: projects/plugins/jetpack/modules/widgets/simple-payments.php (hunk 2 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/simple-payments.php:69]: > maybe you are planning to add that transform 

I think that would be nice, in that PR or in a follow-up one!

**Review by jeherve — DISMISSED** [review]

**Comment by jeherve** [comment]
Setting this as "Ready To Merge"; I'll let you decide about the transform! :)

**Comment by arcangelini** [comment]
I tried to work out a `transform` but it seems that the current block is already broken. When I create a Pay with PayPal widget in classic widget it does not show on the front-end of the site.

### Homepage
Markup 2021-12-02 at 17 09 17

### Customizer
Markup 2021-12-02 at 17 09 56

For some reason the widget instance is turning up completely empty. This means that there are no data available to be transformed `from ⇢ to`. Should we merge this now and open a separate GH issue for the widget? or do you think this would not be time well spent since the widget is a thing of the past? @jeherve @ivan-ottinger

**Comment by ivan-ottinger** [comment]
> [...] or do you think this would not be time well spent since the widget is a thing of the past?

I would personally vote for moving forward without the transform in this case.

**Comment by jeherve** [comment]
> it seems that the current block is already broken. When I create a Pay with PayPal widget in classic widget it does not show on the front-end of the site.

Yes, I think it's a bit broken with the block-based widget editor.

- I can create a widget with the classic widget interface (either via the Classic Widgets plugin or an old version of WP
Screenshot 2021-12-02 at 18 33 27
)
- That widget is displayed on the front end of the site with no issues:
image

- Once I update to the most recent version of WP or deactivate the Classic Widgets plugin, I can still see the widget in the editor, but since it can only be edited in the old customizer, I cannot edit it anymore:
Screenshot 2021-12-02 at 18 34 05
Screenshot 2021-12-02 at 18 34 25

So I think a transform makes even more sense at this point, since we need people to move away from the old widget even more.
But we can definitely do that in a follow-up PR.

**Comment by arcangelini** [comment]
Sorry I should have clarified @jeherve this applied to products created from the widget itself. I ran into the issue on AT and Jetpack only sure.

**Comment by jeherve** [comment]
> this applied to products created from the widget itself. I ran into the issue on AT and Jetpack only sure.

Do you think you could add the steps you followed in your tests? I must be doing something different, as I'm not running into the same issue, and I created the product from the customizer view as well.

**Comment by arcangelini** [comment]
OK it looks like you were right for Jetpack only sites. This is all working properly. The issue appears to be isolated to WordPress.com ATOMIC sites. And also when I try to edit the existing PayPal item it clears out the form in the customizer. Here are the steps I am following:

1. On AT or JPOP site activate the Classic Widget plugin.
2. Go to the Widgets section of Customizer and add the Pay with PayPal widget.
3. Click the ADD NEW button and fill out all the details.
4. Save the widget and publish your changes.
5. Notice the customizer will show all the details correctly, but the widget is not being populated on the front-end.

### ATOMIC
[Screenshot](https://d.pr/i/htrxVA)

[Screenshot](https://d.pr/i/3sZ7rv)

#### Moving forward...
I would like to retire the widget first with this current PR and then work on resolving the other issue with the widget on Atomic sites in another GH issue and PR and maybe have a separate PR after that to create a transform. That way we can be sure the widget is working properly before adding the transform and potentially causing users to lose data if they switch over while its broken on Atomic.

The retire won't affect anyone with the widget currently only prevent future instances from being created. Thoughts @jeherve

**Comment by jeherve** [comment]
> I would like to retire the widget first with this current PR and then work on resolving the other issue with the widget on Atomic sites in another GH issue and PR and maybe have a separate PR after that to create a transform. That way we can be sure the widget is working properly before adding the transform and potentially causing users to lose data if they switch over while its broken on Atomic.

Yep, that sounds great!

**Review by samiff — APPROVED** [review]
