### PR TITLE
Subscribe button: fix width in editor

### LINKED ISSUE #41700: Subscribe Block: Subscribe button too wide
### Impacted plugin

Jetpack

### Quick summary

Visual defect. "Type you email..." field it to small compared to the "Subscibe" button that takes most of the horizontal space.

Image

The block appear OK in the preview.

Image

### Steps to reproduce

Firefox, Safari

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### PR DESCRIPTION
**Pull request by eoigal**
Fixes https://github.com/Automattic/jetpack/issues/41700

This PR improve the handling of button width attributes in both JavaScript and PHP files in the subscribe block.

## Proposed changes:

**edit.js**
Updated the button width logic:
- If buttonWidth has a length greater than 0, use buttonWidth.
- Otherwise, set the width to 'auto'.

**subscriptions.php**
Removed duplicate retrieval of button_spacing attribute.
Enhanced the button width handling:
- Retrieved buttonWidth attribute.
- If buttonWidth is empty, set it to 'auto'.
- Added max-width: 100%; to the button wrapper styles.

## Before

Screenshot 2025-02-25 at 10 35 06

## After

Screenshot 2025-02-25 at 10 34 10

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Sandbox public-api.wordpress.com and your test WPCOM site
* Apply this PR to your WPCOM sandbox
* Create a new post with the subscribe block
* Confirm the button width is as expected

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php [hunk 1]
```diff
@@ -499,7 +503,6 @@ function get_element_styles_from_attributes( $attributes ) {
 	$submit_button_styles .= $style;
 	$email_field_styles   .= $style;
 
-	$button_spacing = get_attribute( $attributes, 'spacing', DEFAULT_SPACING_VALUE );
```
Comment (eoigal) [inline projects/plugins/jetpack/extensions/blocks/subscriptions/subscriptions.php:502]: This is redundant - just cleaning it up.

**Review by arcangelini — COMMENTED** [review]
Everything is working correctly 👍👍

One question I have is if your solution better than setting the default width to ["auto" in the block.json](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/block.json#L50). It seems like it could work the same, but I could be missing some nuances here.

**Comment by eoigal** [comment]
> One question I have is if your solution better than setting the default width to ["auto" in the block.json](https://github.com/Automattic/jetpack/blob/trunk/projects/plugins/jetpack/extensions/blocks/subscriptions/block.json#L50). 

I had another look and decided to go with defining a `const` for the default value as this appears to be how other attributes do it in the same subscriptions file.

**Review by arcangelini — APPROVED** [review]
🚀🚀
