### PR TITLE
Masterbar: Async the admin menu upsell nudge - take 2

### LINKED ISSUE #23519: nav-unification: JITM request performance issues
#### Steps to reproduce

1. Start with a WoA site, connected to WordPress.com
2. Access `site.com/wp-admin/edit.php`
    * Ensure you see the nav-unification sidebar; it will only appear if the Masterbar module is active (it should be active by default), and if your user is connected to WordPress.com.
3. Examine network requests; the debug panel should highlight one specific request as being slow (**sometimes more than 5 seconds to complete**):
    * `https://public-api.wordpress.com/wpcom/v2/sites/BLOG_ID/jitm/calypso:sites:sidebar_notice?`

That request comes from here:
https://github.com/Automattic/jetpack/blob/921b5c74adace486a1edf3c0c67d20f18d3b1fd1/projects/packages/jitm/src/class-post-connection-jitm.php#L494-L495
https://github.com/Automattic/jetpack/blob/862a3f107ad02346a4571b78f8aea3b9e066f744/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L268-L270

It was added in #19773. 

It would be nice to figure what is causing that request to be so slow; I would assume that one of the JITM rules is taking a bit longer than the others. @Automattic/dinobots Is that something you could look at?

Thank you!

*******

Internal references:

- 7301-gh-jpop-issues
- 4824430-zen

### PR DESCRIPTION
**Pull request by tyxla**
Currently, the admin menu upsell nudge in the admin menu can take between 200 and 300 milliseconds (and it takes around a second on one of my atomic sites), and that's quite a solid portion of the admin TTFB, and the editor in particular.

This diff is an experiment to make an async version of it. Instead of querying JITM on page load, we do it asynchronously after page load.

It only makes sense for this to be async, because it's non-critical functionality.

This is part of the effort to improve the performance of the editor.

See D79729-code for a working implementation of this for WP.com simple sites.

See #24222 for the earlier version.

Fixes #23519

#### Changes proposed in this Pull Request:
* Masterbar: Async the admin menu upsell nudge

#### Jetpack product discussion
No related product discussion.

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
* Get an Atomic site that currently displays a nudge below the site card in the sidebar.
* Install Jetpack Beta on that site.
* Use Jetpack Beta to apply this branch on your site.
* Verify that on the following pages, the nudge loads correctly and appears well:
  * `/wp-admin/post-new.php`
  * `/wp-admin/post.php?....` - the page to edit an existing post
  * `/wp-admin/edit.php`
* Verify that dismissing the nudge works well. 
* Apply D80398-code on your WP.com sandbox.
* Sandbox a WP.com simple site that currently displays a nudge below the site card in the sidebar.
* Verify that on the following pages, the nudge loads correctly and appears well:
  * `/wp-admin/post-new.php`
  * `/wp-admin/post.php?....` - the page to edit an existing post
  * `/wp-admin/edit.php`
* Verify that dismissing the nudge works well.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 1]
```diff
@@ -81,8 +82,31 @@
...
+							adminMenu
+								.querySelector( '#toplevel_page_site_card' )
+								.insertAdjacentHTML( 'afterend', xhr.responseText );
+						}
+					}
+				} catch ( error ) {
+					// On failure, we just won't display an upsell nudge
+				}
+			};
+			xhr.send();
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js:109]: Minor and non-blocking: if you update the `makeAjaxRequest` function to accept an optional callback, you could remove some code here.

```diff
diff --git a/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js b/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
index ce3859138d..261c4ab150 100644
--- a/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
+++ b/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
@@ -86,7 +86,7 @@
                }
        }
 
-       function makeAjaxRequest( method, url, contentType, body ) {
+       function makeAjaxRequest( method, url, contentType, body, callback ) {
                var xhr = new XMLHttpRequest();
                xhr.open( method, url, true );
                xhr.setRequestHeader( 'X-Requested-With', 'XMLHttpRequest' );
@@ -94,6 +94,11 @@
                        xhr.setRequestHeader( 'Content-Type', contentType );
                }
                xhr.withCredentials = true;
+               if ( callback ) {
+                       xhr.onreadystatechange = function() {
+                               callback( xhr );
+                       }
+               }
                xhr.send( body );
        }
```

```suggestion
			makeAjaxRequest(
				'GET',
				ajaxurl + '?action=upsell_nudge_jitm&_ajax_nonce=' + jetpackAdminMenu.upsellNudgeJitm,
				null,
				null,
				function ( xhr ) {
					try {
						if ( xhr.readyState === XMLHttpRequest.DONE ) {
							if ( xhr.status === 200 ) {
								adminMenu
									.querySelector( '#toplevel_page_site_card' )
									.insertAdjacentHTML( 'afterend', xhr.responseText );
							}
						}
					} catch ( error ) {
						// On failure, we just won't display an upsell nudge
					}
				};
			);
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php [hunk 2]
```diff
@@ -747,6 +750,15 @@ public function should_link_to_wp_admin() {
...
 
+	/**
+	 * Returns the first available upsell nudge.
+	 *
+	 * @return array
+	 */
+	public function get_upsell_nudge() {
+		return array();
+	}
+
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php:761]: Can we keep this in the `Admin_Menu` class since this method is only needed in there? I'd also add a comment explaining the method returns nothing because it should be implemented in the child classes.

**Review by mmtr — COMMENTED** [review]
Thanks for preparing this alternative approach! It looks much more robust now 🙂 

I think there is a bug when there are no upsell nudges to render. In this case, looks like a `0` is displayed:

Screen Shot 2022-05-11 at 10 13 22

**Review by jeherve — COMMENTED** [review]
this looks good to me. The nudges are not dismissible though, so couldn't test that :)

**Comment by tyxla** [comment]
> this looks good to me. The nudges are not dismissible though, so couldn't test that :)

I've been testing the "domain_upsell_nudge" JITMs that are dismissible. To get such a JITM to appear, after sandboxing the API, in the JITM engine, you can remove some of the conditions (removing the `registered_domain_before` line worked for me).

**Comment by tyxla** [comment]
> I think there is a bug when there are no upsell nudges to render. In this case, looks like a `0` is displayed:

I think this should be fixed with https://github.com/Automattic/jetpack/pull/24304/commits/7493b88e7d3c68496afeaa410252b30f2f53ec78

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php (hunk 2 above)
Comment (tyxla) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php]: Sure! Done in https://github.com/Automattic/jetpack/pull/24304/commits/61f2ef9fc895b4117947516b29760d92c346ebd3

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 1 above)
Comment (tyxla) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Addressed in https://github.com/Automattic/jetpack/pull/24304/commits/3a64f82b16e2aa793fb1976c4b9f806ad5f8847b. LoC-wise, things aren't much different, but at least we're reusing an existing function 😉

**Comment by tyxla** [comment]
Thanks everyone for the feedback 🙌 

I've addressed @mmtr's feedback. This is ready for a final look. 👀

**Comment by tyxla** [comment]
> I still see it after making sure Jetpack Beta has applied the lasted build:
> 
> Loos like the AJAX response includes a `0`, so maybe you need to control that server-side and ensure that the response is empty?

Thanks - yes, I keep forgetting that the `wp_ajax_*` API is very old-school and doesn't really work as REST API does 😅 . I've updated it again, right now we'll bail early with an empty response in https://github.com/Automattic/jetpack/pull/24304/commits/7d9088ea25712501849259b16f0a5a3a075ae986 - I believe this should solve it. Let me know once you give it a spin.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 3]
```diff
@@ -59,16 +59,17 @@
 				} );
 			}
 
-			const jitmDismissButton = adminMenu.querySelector( '.dismissible-card__close-icon' );
-			if ( jitmDismissButton ) {
-				jitmDismissButton.addEventListener( 'click', function ( event ) {
+			adminMenu.addEventListener( 'click', function ( event ) {
+				if ( event.target.classList.contains( 'dismissible-card__close-icon' ) ) {
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js:63]: I think this is not capturing correctly clicks on the close icon. I tried dismissing an upsell nudge on a Simple site with these changes applied, and I got redirected to the upsell nudge link:

https://user-images.githubusercontent.com/1233880/167865813-42ea7e06-f38e-42c5-8864-5bc8ec9985a1.mov

**Review by mmtr — COMMENTED** [review]
Great, lack of nudges is no longer displayed with a `0`. But I think I found another bug related to the nudges dismissals.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 3 above)
Comment (tyxla) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Bummer! You must have been precise enough to click on the X, which isn't an SVG but is rather a `path` element. Fixed in the last commit. Mind giving it another spin?

Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Maybe we can move this logic to the callback that renders the upsell? That way we can bind the click listener to the `.dismissible-card__close-icon` element as before, since it'd be already rendered.

**Review by jeherve — APPROVED** [review]
This tests well for me now.

**Comment by tyxla** [comment]
Thanks for the reviews @jeherve and @mmtr! 🙌

**Comment by tyxla** [comment]
r245688-wpcom
