### PR TITLE
VideoPress: add plan support checks for all plans.

### LINKED ISSUE #10085: VideoPress: AT Sites on Two-Year Business Plan are asked to Upgrade to Activate VideoPress
Atomic sites on a two-year Business Plan are asked to upgrade to be able to host videos on the VideoPress service.  This looks similar to #9949 where the Simple Payments Button wasn't working on the same plan.

#### Steps to reproduce the issue

1. Visit the wp-admin panel of an AT site with a one-year Business Plan
2. Go to Jetpack > Settings
3. Under Media > Video, you should be able to see a tab with the text `Enable high-speed, ad-free video player` to activate or deactivate VideoPress.
4. Replace the site's Business Plan to a two-year one in Store Admin
5. Go back to Jetpack > Settings
6. Under Media, VideoPress seems to be unavailable, and the tab to turn it on or off is missing.  Instead, there is a blue "Upgrade" button next to the text `Host fast, high-quality, ad-free video.`

#### What I expected

I expected to see the toggle button to activate VideoPress after switching to a two-year Business plan.

#### What happened instead

I see this option missing, and I'm being asked to click on a blue button to upgrade.  It is worth noting that I'm still able to upload videos normally to VideoPress, but this can be really confusing to users who either want to use VideoPress or not.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #10085

#### Changes proposed in this Pull Request:

Make sure that all users of a Premium or Business plan, whether it's a one-year or 2-year plan, can use the VideoPress feature.

#### Testing instructions:

1. Visit the wp-admin panel of an AT site with a one-year Business Plan
2. Go to Jetpack > Settings
3. Under Media > Video, you should be able to see a tab with the text `Enable high-speed, ad-free video player` to activate or deactivate VideoPress.
4. Replace the site's Business Plan to a two-year one in Store Admin
5. Go back to Jetpack > Settings
6. Under Media, VideoPress seems to be unavailable, and the tab to turn it on or off is missing.  Instead, there is a blue "Upgrade" button next to the text `Host fast, high-quality, ad-free video.`
7. Install the [Jetpack beta plugin](https://jetpack.com/download-jetpack-beta/)
8. Visit /wp-admin/admin.php?page=jetpack-beta and activate the `fix/videopress-plans` branch.
9. Go back to Jetpack settings and make sure you can now activate the VideoPress feature.

#### Proposed changelog entry for your changes:
- VideoPress: do not block access to the Video settings for 2-year plans.

### CODE REVIEW

File: modules/videopress/class.videopress-options.php [hunk 1]
```diff
@@ -5,9 +5,6 @@ class VideoPress_Options {
 	/** @var string */
 	public static $option_name = 'videopress';
 
-	/** @var array */
-	public static $jetpack_plans_with_videopress = array( 'jetpack_premium', 'jetpack_business' );
```
Comment (jeherve) [inline modules/videopress/class.videopress-options.php]: Noting that this wasn't used anymore, since a714b0b8e568c8bd552e65072bb942c504b43748, so I removed it to avoid confusions.
