### PR TITLE
Gutenframe: Show message if user is logged out

### LINKED ISSUE #32046: Gutenframe: Add UI explaining failure when the user is not logged in on the Jetpack side.
Display a “to use the block editor on this Jetpack site, you’ll need to log into that site”-type screen if the user is not logged in on the JP side. When the user is not logged in, the XML-RPC verification will fail, and the `sameorigin` error screen will be shown, which doesn't help a confused user at all.

Background: p3fqKv-6Hh-p2

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/32046.
Background: p3fqKv-6Hh-p2.

### Changes proposed in this Pull Request:

When the user is not logged into the Jetpack site, the WordPress.com iframed block editor won't load because the iframe redirects to the login URL which cannot be embedded in an iframe (since it causes a `sameorigin` error screen). 

Screen Shot 2019-04-23 at 11 25 44 AM

This PR aborts the default workflow with a `wp_die` command that displays a help message to the user explaining we need them to be logged in. The message is only displayed in a iframed block editor context (current page is `post.php` or `post-new.php` and the param `frame-nonce` is present).

Screen Shot 2019-04-24 at 15 47 30

#### Testing instructions:
* Make sure you're logged out the Jetpack site.
* Start Calypso locally using the `update/me-sites-version` branch (https://github.com/Automattic/wp-calypso/pull/32527).
* Load `/block-editor/post/:yourJetpackDomain`.
* Verify you see the custom error message.
* Load any other page of the Jetpack site (i.e. `://yourJetpackDomain/wp-admin`) and confirm you don't see that message and you're redirected to the login page.
* Login into the Jetpack site.
* Reload `/block-editor/post/:yourJetpackDomain`.
* Check the iframed block editor loads successfully now.

#### Proposed changelog entry for your changes:
I guess it's not needed?

### CODE REVIEW

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 1]
```diff
@@ -68,17 +106,13 @@ public function add_iframed_body_class( $classes ) {
...
-		}
-
 		$verified = $this->verify_frame_nonce(
 			$_GET['frame-nonce'],  // phpcs:ignore WordPress.Security.NonceVerification
 			'frame-' . Jetpack_Options::get_option( 'id' )
 		);
 
 		if ( is_wp_error( $verified ) ) {
-			wp_die( $verified );
+			wp_die( esc_html( $verified ) );
```
Comment (jeherve) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: since we are changing this, how about adding an argument to specify a custom response code to replace the default `500`?

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 2]
```diff
@@ -35,8 +35,45 @@ public static function init() {
...
+	 * The iframed block editor can be only embedded in WordPress.com if the user is logged
+	 * into the Jetpack site. So we abort the default redirection to the login page (which
+	 * cannot be embedded in a iframe) and instead we explain that we need the user to log
+	 * into Jetpack.
+	 */
+	public function show_error_if_logged_out() {
+		if ( ! get_current_user_id() ) {
+			$login_url = wp_login_url();
+			/* translators: %s: Login URL */
+			wp_die( sprintf( __( 'In order to use the block editor of this Jetpack site in WordPress.com, you need to <a href="%s" target="_blank">log into</a> the Jetpack site.', 'jetpack' ), $login_url ) ); // // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (jeherve) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]:
```suggestion
			wp_die( sprintf( __( 'In order to use the block editor of this Jetpack site in WordPress.com, you need to <a href="%s" target="_blank" rel="noopener noreferrer">log into</a> the Jetpack site.', 'jetpack' ), $login_url ) ); // // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```

**Review by jeherve — CHANGES_REQUESTED** [review]
Just some minor comments.

**Review by dmsnell — COMMENTED** [review]
This is a good approach @mmtr and I wish I had thought of something so simple.

Do you have any initial thoughts on what to do after someone logs in inside another tab or window? Something which could bring them back or close that tab?

**Comment by kwight** [comment]
Hm, this isn't working for me. Logged out from the Jetpack site, I still get access to the block editor (instead of a fail with the `wp_die()` message). This is with the API sandboxed using D27129-code, and on local Calypso with https://github.com/Automattic/wp-calypso/pull/32527.

I'll keep digging, might be me.

**Comment by codebykat** [comment]
This seems to work for me for the first load. Sandboxed D27129-code, this branch on Jetpack/ngrok, and Calypso on master.

It does not detect if I log out of the Jetpack site after the editor is loaded:

Screen Shot 2019-04-24 at 2 00 26 PM

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php (hunk 1 above)
Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Resolved in https://github.com/Automattic/jetpack/pull/11354

**Comment by obenland** [comment]
> It does not detect if I log out of the Jetpack site after the editor is loaded

Good find! I think it would be okay to leave that for a v2

**Comment by mmtr** [comment]
> This is a good approach @mmtr and I wish I had thought of something so simple.

Props to @mdawaffe! 
 
> Do you have any initial thoughts on what to do after someone logs in inside another tab or window? Something which could bring them back or close that tab?

I tried to use the `redirect` argument of the [`wp_login_url` function](https://codex.wordpress.org/Function_Reference/wp_login_url) and make sure that the login page is opened on the same tab. So when a user logs in, it is redirected back to Calypso.

But it didn't work to me and I was always redirected to `/wp-admin`. I guessed it was caused by WordPress not allowing external redirections.

I didn't think in any other alternative yet, so I left this at it is right now.

**Comment by obenland** [comment]
Yeah, in Jetpack we're not aware of the URL outside the iframe. I wonder if ending up in wp-admin would still be the better experience. In my test, Calypsoify linked the editor's Back button to Calypso, so we're not too far away from that experience.

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 3]
```diff
@@ -147,8 +182,9 @@ public function verify_frame_nonce( $nonce, $action ) {
 	/**
 	 * Filters the WordPress salt.
 	 *
-	 * @param string $salt   Salt for the given scheme.
+	 * @param string $salt Salt for the given scheme.
 	 * @param string $scheme Authentication scheme.
+	 *
```
Comment (obenland) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: @mmtr Are these whitespace changes prompted by phpcs?

Comment (mmtr) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Oops, I didn't notice this. Yes, I performed an automatic reformat code on the file while I wanted to run in only in a specific piece of code and it seems that this space was added automatically because my IDE thinks that it should be a new line before the `@return` description. 

I don't see that's required on https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/ so I'm happy to revert that change back.

Comment (mmtr) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Actually, it seems like we use this pattern (separate `@return` from `@param`) in many Jetpack functions, so probably it is ok to leave it as it is?

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: I'd bet the separation stems from IDE's default settings. Core groups `@param` and `@return` notations and aligns `@param` descriptions.
It's not terribly important in the scheme of things, and I'm not sure if Jetpack has diverging coding standards from Core's that would support it, but we get around to it I think it would be worth not changing.

**Review by jeherve — DISMISSED** [review]
This works well in my tests. 👍

**Comment by mmtr** [comment]
> This works well in my tests. 👍

Thanks @jeherve! This needs again an approval after having rebased to include changes from https://github.com/Automattic/jetpack/pull/12070

**Review by jeherve — APPROVED** [review]

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 4]
```diff
@@ -55,6 +56,22 @@ public function is_iframed_block_editor() {
...
+	 * The iframed block editor can be only embedded in WordPress.com if the user is logged
+	 * into the Jetpack site. So we abort the default redirection to the login page (which
+	 * cannot be embedded in a iframe) and instead we explain that we need the user to log
+	 * into Jetpack.
+	 */
+	public function show_error_if_logged_out() {
+		if ( ! get_current_user_id() ) {
+			$login_url = wp_login_url();
+			/* translators: %s: Login URL */
+			wp_die( sprintf( __( 'In order to use the block editor of this Jetpack site in WordPress.com, you need to <a href="%s" target="_blank" rel="noopener noreferrer">log into</a> the Jetpack site.', 'jetpack' ), $login_url ) ); // // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
```
Comment (simison) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: I think by default `wp_die` returns HTTP status code [`500 Internal Server Error`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500) — tho I didn't check if this is still the case.

I don't know if that can affect how we collect stats in different layers.

Something like [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) or [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) would prolly be better here.

https://developer.wordpress.org/reference/functions/wp_die/

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Good catch, I'll spin up a PR for it

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: See https://github.com/Automattic/jetpack/pull/12162
