### PR TITLE
Stats: Return error for API requests

### LINKED ISSUE #11513: Blank dashboard from handling of views_today
#### Steps to reproduce the issue

1. Go to /wp-admin/admin.php?page=jetpack#/dashboard, specifically on a site with a new Jetpack connection
2. In some cases when views_today returns bad data the Dashboard will be inaccessible
3. Console shows the following error:

views_today console error

#### What I expected
The Jetpack Dashboard to load normally

#### What happened instead
It loads for a second, then disappears. Once good data loads (usually within a few minutes) the Dashboard loads normally.

From @kraftbj:

> the one thing that was recently added and related to stats
> 
> before: if the wp.com API didn't return good data for stats, it wouldn't cache the response and keep trying on every page load
> 
> now: it'll cache a blank response for 5 minutes (what a successful call does)
> 
> i bet this probably happened since always
> but the 5-minute caching is making it persist after a refresh, so folks are thinking something's actually wrong instead of folks' usual "oh well, a refresh worked"

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #11513

Handles cases where the WP.com API fails when loading the JP dashboard after #11489

#### Changes proposed in this Pull Request:
* Passes through error message.

#### Testing instructions:
* Set up your site's hosts file to blackhole `JETPACK__WPCOM_JSON_API_HOST` or set it to your sandbox and intentionally 500 any response.
* Open the Jetpack dashboard.
* Confirm the error is handled gracefully like so:
2019-03-07 at 11 17

#### Proposed changelog entry for your changes:
* Stats Dashboard: Properly handle an error from the REST API

### CODE REVIEW

**Review by jmdodd — APPROVED** [review]

**Review by jeherve — APPROVED** [review]
This should work. 🚢

File: modules/stats.php [hunk 1]
```diff
@@ -1754,7 +1757,7 @@ function stats_get_from_restapi( $args = array(), $resource = '' ) {
 	// Do the dirty work.
 	$response = Jetpack_Client::wpcom_json_api_request_as_blog( $endpoint, $api_version, $args );
 	if ( 200 !== wp_remote_retrieve_response_code( $response ) ) {
-		$data = array();
+		$data = $response;
```
Comment (mdawaffe) [inline modules/stats.php]: `$response` does not have to be a `WP_Error` for every non-200 response.

I think we should do something like:
```
$data = is_wp_error( $response ) ? $response : new WP_Error( 'stats_error' );
```

Comment (kraftbj) [reply modules/stats.php]: That makes sense. Before 7.1, we just returned the response, but there could be unexpected cases so we should force the error. 👍 

https://github.com/Automattic/jetpack/pull/11582
