### PR TITLE
Infinite Scroll: Prevent first page duplication, and fix main query detection

### LINKED ISSUE #1135: Different orderby causes double load in Infinite Scroll
Hi,

When loop's **orderby** is different then "modified" or "date", `get_last_post_date` and `get_query_sort_field`  functions returns false and that causes double load first posts. 

(Edit: talking about Infinite Scroll)

### PR DESCRIPTION
**Pull request by mikejolley**
I believe this fixes #1135 but we have slightly different reproduction steps in that we're simply running this on a custom post type archive. I found issues in the way pagination works which I'll do my best to explain below.

There are 2 main issues this PR aims to resolve;

1. Page "1" being loaded when you're already viewing page 1.
2. Queries from other plugins failing because the Infinite scroll query is not the "main query".

#### Changes proposed in this Pull Request:

**Globals**

This PR adjusts the order in which the globals `wp_the_query` and `wp_query`  are set so that `is_main_query` is accurate when ran on the `pre_get_posts` hook.

Looking at the code where it set `wp_the_query` and `wp_query` it looks like the intention here was to be the 'main query' but because the query is RAN before these globals are set, any functions hooking into `pre_get_posts` will not see correct results.

Before:

- Query is ran in the constructor of `WP_Query`
- `pre_get_posts` fires during the query. 
- At this point `wp_the_query` and `wp_query` have the original values. This means `is_main_query` will return false.

After:

- New `WP_Query` is constructed.
- `wp_the_query` and `wp_query` are set to this new `WP_Query` object.
- query is ran.
- `pre_get_posts` fires during the query. 
- At this point `wp_the_query` and `wp_query` contain the current query object, so `is_main_query` will return true.

This fixes a conflict with WooCommerce which only adjusts the main query.

**Pagination JavaScript**

When viewing the first page and scrolling, IS loads page 1 again. The adjustment in the script I made makes it load page 1 plus the current page (offset).

So example, WooCommerce shop page at `local.wordpress.test/shop/` is showing page 1 already. When you scroll it loads page 1 + offset 1 = page 2.

If you start at `local.wordpress.test/shop/page/2` it loads page 1 + offset 2 + page 3.

Both the results are correct, and the address bar is updated accordingly.

I'm not sure how or if it actually worked before :)

#### Testing instructions:

So these are the testing instructions for our WooCommerce use case. @tiagonoronha May comment for general blog testing instructions but basically.

- Checkout this branch
- Checkout this branch of WooCommerce https://github.com/woocommerce/woocommerce/pull/19477
- In customizer > woocommerce > product catalog, set orderby to title, and show 3 products per row and 1 row per page.
- View the shop page. 
- Scroll/load more, and you'll see another row of products added until complete.

Before the patch you'd see random number of products, in random order, with missing items in the grid. Page 1 would also be duplicated.

#### Proposed changelog entry for your changes:

* Fixes `is_main_query` detection within infinite scroll's WP_Query object.
* Fixes first page pagination to prevent duplicate pages being returned.

### CODE REVIEW

**Comment by danieldudzic** [comment]
I have tested this with Storefront (and few other themes), but I'm still experiencing an issue:

* Jetpack and WooCommerce branches checked out: https://cldup.com/vicAWyRaWq.png
* 18 published products: https://cldup.com/HUppNjd6dC.png (products .csv: https://cloudup.com/cLnPPDZgKus)
* With IS enabled: Shop page displays only 14 products (after scrolling to the bottom): https://cldup.com/-nupQRnSj1.png
* With IS disabled: Shop page displays 17 products: https://cldup.com/nKA4tiWVs0.png / https://cldup.com/ynGv6OuweR.png

**Comment by tiagonoronha** [comment]
@danieldudzic  Thanks for testing.

Please test with https://github.com/Automattic/jetpack/pull/9120 instead. Also make sure that none of the themes has any custom code to alter the IS query. You can test with https://github.com/woocommerce/storefront/pull/788.

File: modules/infinite-scroll/infinity.php [hunk 1]
```diff
@@ -1243,7 +1243,9 @@ function query() {
 		// Add query filter that checks for posts below the date
 		add_filter( 'posts_where', array( $this, 'query_time_filter' ), 10, 2 );
 
-		$GLOBALS['wp_the_query'] = $GLOBALS['wp_query'] = new WP_Query( $query_args );
+		$GLOBALS['wp_the_query'] = $GLOBALS['wp_query'] = $infinite_scroll_query = new WP_Query();
+
+		$infinite_scroll_query->query( $query_args );
```
Comment (zinigor) [inline modules/infinite-scroll/infinity.php]: According to the PRs description, there's a pretty big change implied in this simple diff here. Do you think we should add a comment so that no one would have a desire to roll the thing back and avoid using an additional variable? :)

Or maybe we can even get rid of the variable, and just call the `query` method on one of the globals after they are set?

**Comment by zinigor** [comment]
After testing together with #9120 I can say that the problem is gone, well done, thank you!
