### PR TITLE
REST requests: avoid PHP warnings with custom post objects

### LINKED ISSUE #33728: Sharing: Undefined array key "id" warning
### Impacted plugin

Jetpack

### Quick summary

I have been getting multiple errors in the error log for the error below

```
PHP Warning:  Undefined array key "id" in /public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php on line 41
```

### Steps to reproduce

This is triggered when checking if sharing is enabled for a post when making an API request.

### A clear and concise description of what you expected to happen.

_No response_

### What actually happened

_No response_

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### LINKED ISSUE #36306: Warning: Undefined array key "id" in jetpack/modules/sharedaddy/sharing.php on line 789 when invoking site editor
### Impacted plugin

Jetpack

### Quick summary

When invoking the site editor with Jetpack activated a Warning message is produced from the sharedaddy module.

### Steps to reproduce

With WP_DEBUG true.

1. Activate Jetpack
2. Invoke the Site Editor - Dashboard > Appearance > Editor
3. Warning message is displayed before the Site Editor appears

```
<br />
<b>Warning</b>:  Undefined array key "id" in <b>/home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php</b> on line <b>41</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php:41) in <b>/home/customer/www/seriouslybonkers.com/public_html/wp-admin/admin-header.php</b> on line <b>9</b><br />
<!DOCTYPE html>
```
Code in error is from this function
```
function jetpack_post_sharing_get_value( array $post ) {
	// if sharing IS disabled on this post, enabled=false, so negate the meta
	return (bool) ! get_post_meta( $post['id'], 'sharing_disabled', true );
}
```

### A clear and concise description of what you expected to happen.

No Warning messages regardless of the setting of WP_DEBUG

### What actually happened

Unwanted Warning messages

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Warnings are produced from other places in the code.

/home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php(286:2) bw_trace_error_handler(1) 129 1 2024-03-10T18:26:43+00:00 0.386591 0.002480 cf! 40638 136 0 94371840/94371840 768M F=1908 err Array

    [0] => (integer) 2
    [1] => (string) "Warning: Undefined array key "id""
    [2] => (string) "/home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php"
    [3] => (integer) 41

0. bw_lazy_backtrace /home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/oik-bwtrace/libs/bwtrace.php:108 0
1. bw_backtrace /home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/oik-bwtrace/includes/bwtrace-actions.php:293 0
2. bw_trace_error_handler(2,Undefined array key "id",/home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php,41) /home/customer/www/seriouslybonkers.com/public_html/wp-content/plugins/jetpack/extensions/plugins/sharing/sharing.php:41 4
3. Automattic\Jetpack\Extensions\Sharing\{closure}(array,jetpack_sharing_enabled,object,wp_global_styles) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api/endpoints/class-wp-rest-controller.php:439 4
4. add_additional_fields_to_object(array,object) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api/endpoints/class-wp-rest-global-styles-controller.php:619 2
5. get_theme_item(object) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api/class-wp-rest-server.php:1193 1
6. respond_to_request(object,/wp/v2/global-styles/themes/(?P<stylesheet>[^\/:<>\*\?"\|]+(?:\/[^\/:<>\*\?"\|]+)?),array,null) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api/class-wp-rest-server.php:1041 4
7. dispatch(object) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api.php:551 1
8. rest_do_request(object) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api.php:2918 1
9. rest_preload_api_request(array,/wp/v2/global-styles/themes/sb) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/rest-api.php:0 2
10. array_reduce(array,rest_preload_api_request,array) /home/customer/www/seriouslybonkers.com/public_html/wp-includes/block-editor.php:753 3
11. block_editor_rest_api_preload(array,object) /home/customer/www/seriouslybonkers.com/public_html/wp-admin/site-editor.php:116 2

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #33728
Fixes #36306

## Proposed changes:

In some scenarios, the object data passed to the callback function used with `register_rest_field` is not the standard `WP_Post` post data we can expect. In order to avoid PHP warnings like the ones listed in the issues above, let's be more defensive everywhere where we use `register_rest_field`, and bail early when we do not have the expected data. 
### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

I'm not exactly sure what's the best way to reproduce the warnings above, since it depends on specific third-party plugins. I think we can test things out by ensuring that the different requests still work for a regular setup.

* Go to Jetpack > Settings > Sharing
* Enable sharing buttons and Publicize
* Go to Posts > Add New
* Publish a post
    * On the frontend, ensure you can see sharing buttons.
* Go back to the post editor, and in the Jetpack sidebar disable sharing.
* Save your changes
    * On the frontend, ensure the buttons are now gone.
* Go to Posts > Add New
* Connect a few social networks.
* Write a post
* Unselect some of the social networks you've connected in the Jetpack sidebar
* Publish your post
    * Ensure the posts are only sent to the selected social networks.
* Go to Jetpack > Settings > Performance
* Turn on VideoPress
* Go to Posts > Add New
* Add a VideoPress block and upload a video.
* Make sure the video can be uploaded, and its details changed.

### CODE REVIEW

File: projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php [hunk 1]
```diff
@@ -91,15 +93,12 @@ public function get_schema() {
...
-		} else {
-			$blog_id = \Jetpack_Options::get_option( 'id' );
+		if ( ! isset( $attachment['id'] ) ) {
+			return array();
 		}
 
-		$post_id = absint( $attachment['id'] );
-
-		$videopress_guid = $this->get_videopress_guid( $post_id, $blog_id );
+		$blog_id         = Jetpack_Connection::get_site_id();
```
Comment (jeherve) [inline projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php]: I took this opportunity to simplify how we get the blog ID here, since we already have an extracted method to do just that in the Connection package.

Comment (sergeymitr) [reply projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php]: Do you think we should check for `WP_Error` here to properly handle connection errors?
https://github.com/Automattic/jetpack/blob/f00a638a9b881f9c648b70df94a0bf9006b49de7/projects/packages/connection/src/class-manager.php#L2572

Comment (jeherve) [reply projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php]: That makes sense. What do you think of 3b790e5ab0223c6fcce73d80c96bfdee3e704367?

**Comment by sergeymitr** [comment]
Hi @jeherve, looks like unit tests are failing now.

File: projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php (hunk 1 above)
Comment (sergeymitr) [reply projects/packages/videopress/src/class-wpcom-rest-api-v2-attachment-field-videopress.php]: That should work, thanks for taking care of it!

**Comment by jeherve** [comment]
Thank you! I updated the tests, it should be good for another review.

**Review by sergeymitr — APPROVED** [review]
I wasn't able to test the social network posting because I had issues connecting an account, but everything else appears to be working great.
So if tested the posting, I think it's good to go.
