### PR TITLE
Fix/9754 seo verbiage copy sprint

### LINKED ISSUE #9754: SEO settings: Verbiage enhancements
**Current:**

**free, personal plans:**
screen shot 2018-06-13 at 4 42 31 pm

**premium, pro plans:**
screen shot 2018-06-13 at 4 18 21 pm

**Proposed:**

**free, personal plans:**
screen shot 2018-06-13 at 4 14 46 pm

upgrade prompt description:
> Give your ranking a boost with SEO tools in Jetpack Premium or Professional. Learn more.

**premium, pro plans:**
screen shot 2018-06-13 at 4 38 01 pm

CTA description: 
> Configure your SEO settings in your WordPress.com dashboard

description for all plan levels:

> Jetpack SEO tools will give you live previews of what your site homepage and posts look like in popular search engines. Reorder items such as 'Site Name’' and 'Tagline' without having to touch any code.

cc @benhuberman since I kind of just pieced a few sentences together. could use some refinement!

### PR DESCRIPTION
**Pull request by eeeeevon13**
Updating copy on the SEO banner as well as changing the copy on the feature description for upgraded users. 

Partially Fixes #9754 

#### Changes proposed in this Pull Request:
* updated copy on SEO banner
* updated feature description for upgraded users

before-after1
copy2-updated

### Changes still needed (need dev help)
We want to show this paragraph to non-upraded users as well as upgraded.
```"Jetpack SEO tools will give you live previews of what your site homepage and posts look like in popular search engines. Reorder items such as 'Site Name’' and 'Tagline' without having to touch any code."```

I found where to change it in the current code, but not how to make it show for all users

still-needs-to-happen

#### Testing instructions:
* Go to /wp-admin/admin.php?page=jetpack#/traffic
* View as non-upgraded
* View as upgraded

#### Proposed changelog entry for your changes:

*none

@scottsweb

### CODE REVIEW

File: _inc/client/components/settings-card/index.jsx [hunk 1]
```diff
@@ -165,7 +167,9 @@ export const SettingsCard = props => {
 				return (
 					<JetpackBanner
 						callToAction={ upgradeLabel }
-						title={ __( 'Help your content get found and shared with SEO tools.' ) }
+						title={ __(
+							'Boost your search engine ranking with the powerful SEO tools in Jetpack Premium.'
```
Comment (jeherve) [inline _inc/client/components/settings-card/index.jsx]: Should it also say "or Professional"?

image

**Review by jeherve — DISMISSED** [review]
This worked well. I only have one small remark.

File: _inc/client/components/settings-card/index.jsx (hunk 1 above)
Comment (scottsweb) [reply _inc/client/components/settings-card/index.jsx]: Sound sensible, I will get this updated.

```suggestion
							'Boost your search engine ranking with the powerful SEO tools in Jetpack Premium or Professional.'
```

**Review by scottsweb — APPROVED** [review]

**Comment by scottsweb** [comment]
Confused by these failing tests :/

**Review by scottsweb — APPROVED** [review]

**Comment by scottsweb** [comment]
@jeherve this should be good now, I think you may need to give it another 👍 so we can merge.

**Review by mdawaffe — APPROVED** [review]
Because of the "Partially **Fixes #9754**" (emphasis mine) in the description of this PR, merging this may close that issue, even though this PR doesn't completely fix that issue. I'm not sure what will happen :)

Just be ready for that when this is merged.

**Comment by scottsweb** [comment]
Thanks @mdawaffe - I am happy for #9754 to be closed, it is an old issue and this overlaps quite a bit.
