### PR TITLE
Carousel: Add JS-based smooth scrolling on footer area open/hide

### LINKED ISSUE #20251: Carousel: Add support for smooth scrollTo on mobile when opening/closing comments section
On mobile we currently don't have support for `behavior: 'smooth'` for [Element.scrollTo](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo), which means that when we open/close the comments of info sections at the bottom of the carousel they snap open / closed instead of smoothly scrolling the viewport to that section of the page.

Let's investigate adding in a JavaScript approach to smooth scroll those sections into view.

#### Steps to reproduce the issue

1. With the Carousel module in Jetpack enabled, go to a post containing an image gallery, using a mobile device
2. Tap on an image to open up the Carousel on mobile
3. Tap on the comments or info icons in the footer

#### What I expected

The viewport to smooth scroll down to the comments area

#### What happened instead
The viewport snaps down to the position of the comments area

**Screenshots**

https://user-images.githubusercontent.com/14988353/124200821-9d05cb00-db19-11eb-8d65-21e4733e4547.MP4

### PR DESCRIPTION
**Pull request by andrewserong**
Fixes: https://github.com/Automattic/jetpack/issues/20251

#### Changes proposed in this Pull Request:

* The objective is to add JS-based smooth scroll for the icon buttons in the footer of the Carousel. This needs to be done in JS so that devices that don't support smooth scroll behaviour can still have it (e.g. iOS Safari), and so that on all devices (including desktop) we can scroll to top _before_ hiding the comments area, otherwise we effectively snap scroll to the top when the comments area is hidden.
* The scroll duration is currently set to 300ms.
* For the easing algorithm, I used the `easeInOutQuad` from https://easings.net/#easeInOutQuad — also happy to try one of the other easings if folks prefer an alternative.

#### Screenshots

Desktop:

https://user-images.githubusercontent.com/14988353/125039351-bb4f6600-e0d9-11eb-90ed-ce257d8d4a18.mp4

Mobile:

https://user-images.githubusercontent.com/14988353/125221207-3ea3ce00-e30b-11eb-882f-3d63b7e6e539.mov

#### Jetpack product discussion

There are much more complex polyfills and libraries we could use instead of this added function (e.g. https://github.com/iamdustan/smoothscroll), however to try to keep this lightweight, I thought I'd see if we can keep the function as simple as possible rather than pulling in anything extra.

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* With the Jetpack Carousel module switched on, add an image gallery to a post and view it on the front end of the site
* Open up the carousel.
* Click or tap on the buttons in the footer to slide out the extra footer area
* (NEW) On desktop, clicking the button again should smooth scroll the viewport back to the top and then hide the extra footer area
* On mobile (e.g. iOS Safari) there should now be smooth scrolling when showing/hiding the extra footer area where there was none before

I have tested this on desktop Safari, FF, Chrome, and Edge (on Mac), and on a real iOS device (iPhone 8, Safari + Chrome).

I'm curious if someone can test this on a real android device, and on any device see if we run into any edge cases or issues with this JS-based approach.

### CODE REVIEW

**Comment by ramonjd** [comment]
Great work @andrewserong !

I was doing some browser testing and it's very smooth. Here's iOS Safari:


https://user-images.githubusercontent.com/6458278/125236703-c8fa2b00-e327-11eb-894b-1ada003d208b.MP4

Tests well in all desktop/mobile browsers I have access to. If you can, it would be neat to sanity check something for me so as to rule out user error :D I was testing Edge desktop using Browserstack and none of the mouse interactions work for me. 

Also, do you think we should animate scrolling when we switch between info/comments panels? See the end of the video for how it snaps.

Not a biggie.

**Comment by ramonjd** [comment]
Also not a huge deal, but I noticed that, if I've already opened an image's comments, a sibling image's comments will scroll to the last known Y position. This is evident for images with numerous comments that take up the page.


https://user-images.githubusercontent.com/6458278/125237408-feebdf00-e328-11eb-8dce-b288cdc4e087.mp4

**Comment by andrewserong** [comment]
Oh, thanks for the feedback and the detailed testing, Ramon! I'll try out Edge in Browserstack and see if I can reproduce the issue.

> Also, do you think we should animate scrolling when we switch between info/comments panels? See the end of the video for how it snaps.

It would be nice if we can do that — unfortunately I couldn't quite think of an easy way to do it without artificially extending the minimum height of the info area to the current scroll height (It snaps the viewport up as soon as the comments area is no longer displayed). But maybe we can do that just during the transition so that we don't keep an excessive amount of empty space around in the page 🤔

> Also not a huge deal, but I noticed that, if I've already opened an image's comments, a sibling image's comments will scroll to the last known Y position. This is evident for images with numerous comments that take up the page.

Oh, good catch! I'll take a look at that too.

**Comment by ramonjd** [comment]
> I'll try out Edge in Browserstack and see if I can reproduce the issue.

I've been testing in various Browserstack browsers (Edge, Firefox and Opera) and I'm starting to think it's a Browserstack peculiarity. 

I was testing on the master branch.

I _think_ [finished()](https://github.com/Automattic/jetpack/blob/95a7b30c34fcb57eadc352e03b4b21ab49af5446/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L125) isn't being called on `transitionend` and `transitioncancel`. 

This removes `pointer-events: none` from the carousel:

Screen Shot 2021-07-12 at 8 53 31 pm

Maybe some `requestAnimationFrame` funkiness.

**Comment by andrewserong** [comment]
> I've been testing in various Browserstack browsers (Edge, Firefox and Opera) and I'm starting to think it's a Browserstack peculiarity.

Hrm, that's very strange! This unfortunately doesn't help diagnose it, but I tried testing in Browserstack this morning using Windows 10 + Edge, Firefox, and Opera, and it worked correctly on each. Any tips on reproducing it? Maybe there's something different about the content in your image gallery than in my image gallery?

**Comment by andrewserong** [comment]
(Also, I got a bit sidetracked by other tasks this morning, but I'll take a look at the other feedback this afternoon, too!)

**Comment by ramonjd** [comment]
> This unfortunately doesn't help diagnose it, but I tried testing in Browserstack this morning using Windows 10 + Edge, Firefox, and Opera, and it worked correctly on each. Any tips on reproducing it? Maybe there's something different about the content in your image gallery than in my image gallery?

Sorry to waste your time on that. Thanks for testing. 

If it works for you, it's good enough for me. As I said, it's working well on all my native browsers.

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js [hunk 1]
```diff
@@ -174,16 +174,66 @@
...
+				extraInfoArea.style.minHeight = window.innerHeight - 64 + 'px';
+			}
+			var extraInfoContentArea = container.querySelector( '.jp-carousel-info-content-wrapper' );
+			var extraInfoContentAreaHeight = extraInfoContentArea
+				? extraInfoContentArea.offsetHeight
+				: window.innerHeight;
+
+			var isScrolling = true;
+			var startTime = Date.now();
+			var duration = 500;
```
Comment (apeatling) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.js:202]: 500ms feels a bit slow to me, I think 300ms is better and feels snappier, especially in places where the height of the toggled area is smaller.

**Review by apeatling — CHANGES_REQUESTED** [review]

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js (hunk 1 above)
Comment (andrewserong) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js:202]: Oh, good feedback, I was wondering how folks might feel about the duration. I'll update to 300ms. Thanks!

Comment (andrewserong) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js]: Updated to 300ms 👍

**Review by ramonjd — DISMISSED** [review]
This works well for me on desktop and mobile. Nice!

LGTM if other folks are happy with it.

Here's mobile iOS Safari with the latest changes from this PR. 

What you're looking at are hinges. Excitement plus.


https://user-images.githubusercontent.com/6458278/125714106-ba39c389-7c9e-401c-a2db-e889dc12ffe1.MP4

**Comment by andrewserong** [comment]
Fantastic, thanks for testing @ramonjd! I just had another idea that I'd like to try after lunch — I thought I might see about adding the min-height only _during_ the transition, so that once the transition finishes, we remove the excess whitespace. It may or may not work / look good on browsers that show a scrollbar, but I thought it worth trying before we land it.

**Comment by andrewserong** [comment]
In https://github.com/Automattic/jetpack/pull/20318/commits/5817299738ee01f647f80ba209ea84485cb28394 I've added a call to remove the minHeight again once the transition is complete. It appears to be working well for me in my testing. 

However, separately, today I've been able to reproduce the issue in Browserstack where click events don't appear to be working correctly. I don't _think_ it's related to this PR, but it's still a little troubling...

> I think finished() isn't being called on transitionend and transitioncancel.

I tried commenting out the `pointerevents` line, and that improves things a bit, but then I still notice two other issues:

* After closing the carousel, clicking on an image in the page doesn't open the carousel again
* The back and forward buttons don't appear to be clickable

I'll continue doing a little digging, but 🤞 it's just a Browserstack issue. Either way, I don't think it'd be affected by this PR 🤔

**Comment by andrewserong** [comment]
Update: in Browserstack, I actually think `transitionend` doesn't appear to be firing sometimes. There's a bit more context in https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontransitionend of when it might not fire. I'll do a bit more testing tomorrow (separately to this PR), but I'm wondering if it might be a bit more reliable to use a setTimeout for the `fade` function. In the meantime, I don't _think_ that should hold up this PR, but good to get to the bottom of it 🙂

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js [hunk 2]
```diff
@@ -201,7 +201,7 @@
 			var targetPosition = Math.max(
 				0,
 				el.offsetTop -
-					Math.max( 0, window.innerHeight - ( extraInfoContentAreaHeight + 64 + 15 + 35 ) ) // Subtract footer height plus content area padding.
+					Math.max( 0, window.innerHeight - ( extraInfoContentAreaHeight + 64 + 35 + 35 ) ) // Subtract footer height plus content area padding.
```
Comment (apeatling) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.js:204]: Could we programatically grab the footer height and content area padding here? This will almost certainly get missed if this is changed in the CSS in the future.

Comment (andrewserong) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js:204]: Oh, yes, thanks for the note. I'd been trying to avoid the function from getting too long, but agreed, it's much better to calculate based on the real positions 👍

Comment (andrewserong) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js]: I've updated this to get the real values from the DOM when we begin the scroll, and have moved the calculations to a separate function to try to tidy things up a little bit.

**Comment by andrewserong** [comment]
I've updated this PR with the additional calculation of the footer clearance, and tidied it up a little. I did a bit more exploration into the Browserstack issue we ran into (where the Carousel became unresponsive), and started a draft PR in https://github.com/Automattic/jetpack/pull/20380 — it appears to be unrelated to this PR, so we can continue exploring over there.

I'm AFK now for the next week and a half, but feel free if anyone would like to jump in and take over this PR or the other one. I _think_ this one is pretty close to ready, it will need a bit of extra testing, and it'd be great if someone with a real Android device could give it a test to make sure the scrolling feels good over there, too. Thanks!

**Comment by ramonjd** [comment]
This is working excellently on my iOS in Safari and Chrome.

I also tested on several Android devices on Browserstack (my Android device is completely dead).

It's working well given the expected lag:

https://user-images.githubusercontent.com/6458278/126094220-f43e0391-907a-4bde-b380-b46da38397b5.mp4

**Comment by ramonjd** [comment]
Also rebased and added a comment where we are setting the height of the info area

```js
// 64px is the same height as `.jp-carousel-info-footer` in the CSS.
infoArea.style.minHeight = window.innerHeight - 64 + 'px';
```

**Review by ramonjd — DISMISSED** [review]
I've tested this in the usual suspects, including mobile devices.

Unfortunately I only had access to Android using Browserstack, but they're devices are real and not simulated (according to themselves 😄 )

This is testing well for me. 

As we add code like this, we might like to think towards modularization (https://github.com/Automattic/jetpack/pull/20131) as it will make future maintenance easier for developers in my opinion.

**Comment by ramonjd** [comment]
Update: I found an old Samsung Galaxy at the bottom of the drawer. Fired it up and tested this branch on Chrome and Brave browsers. 

Works as expected 🚀

**Review by apeatling — DISMISSED** [review]
Working great, LGTM!

**Review by apeatling — APPROVED** [review]

**Review by sdixon194 — APPROVED** [review]
This is slick and works super well for me 👍 Tested on an actual android device and didn't have any issues 🎉

**Comment by andrewserong** [comment]
r229204-wpcom
