### PR TITLE
[RNMobile] Implement useSyncMedia hook on native

### LINKED ISSUE #5611: Implement `useSyncMedia` hook to synchronize VideoPress metadata
## Description

This hook handles all the metadata synchronization between the VideoPress service and the block attributes. The logic can be broken down into the following sections:

### 1 - Fetch metadata from VideoPress (VideoPress => block settings)

Using the hook [`useVideoData`](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/block-editor/hooks/use-video-data/index.ts), it makes a request to [`/videos/$guid` endpoint](https://developer.wordpress.com/docs/api/1.1/get/videos/%24guid/). if the site is private, it tries to fetch the token for the request, however, this is only needed for self-hosted sites which aren't supported yet in native.

With the metadata, it updates an internal initial state, which is used later on, and the block attributes.

### 2 - Check if the chapters file can be auto-generated

It tries to fetch the current tracks file and check if it was autogenerated. The result of this check is used later on when updating the metadata in VideoPress.

### 3 - Request video frame poster

When the post is saved, it checks if the poster is a video frame and in case the time changed, it requests a new one.

### 4 - Update metadata (Block settings => VideoPress)

When saving the post, it compares the attributes changed with the initial state and makes a POST request to VideoPress (`wpcom/v2/videopress/meta`).

The request response is used for:
- Update the initial state.
- Set the `isPrivate` attribute.
- Based on the result from point 2, generate and upload the chapters file.
- Invalidate `getEmbedPreview` resolutions based on the attributes changed. This will enforce the preview used in the player to be updated.

## Differences in the native version
- **Related to metadata update in VideoPress:** On the native version, we can't rely on the post saving to update the metadata because the editor would be closed. We'd need to use a different behavior.
- **Related to the video frame poster request:** The endpoint used is different for simple sites and other types of sites. Currently, in the native version, we don't provide information about the type of site. Hence, if we want to support this functionality we'd need to provide a workaround.
- **Related to chapter file generation:** Not sure how feasible would be to generate the file on native, it's likely that we need to delegate this to the main apps.

## Notes

- The hook can be divided into smaller hooks, we might consider this before implementing the native version.
- The WPCOM endpoints used by the hook should work in the native version for simple sites. However, for self-hosted sites, we'd need to investigate further if we need to tweak the network logic.

## Subtasks
- [ ] Divide hook into smaller hooks
- [ ] Fetch VideoPress metadata
    - [ ] Implement [`fetchVideoItem` function](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/lib/fetch-video-item/index.ts)
    - [ ] Implement [`useVideoData` hook](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/videopress/src/client/block-editor/hooks/use-video-data)
- [ ] Extract and implement [`useMediaDataUpdate` hook](https://github.com/Automattic/jetpack/blob/76104bdebaafa1a976447dd2991b1654eeb1d713/projects/packages/videopress/src/client/block-editor/hooks/use-video-data-update/index.ts#L48-L67)
- [ ] Implement [logic to update metadata VideoPress](https://github.com/Automattic/jetpack/blob/76104bdebaafa1a976447dd2991b1654eeb1d713/projects/packages/videopress/src/client/block-editor/hooks/use-video-data-update/index.ts#L370-L509) and potentially extract it to a separate hook
- [ ] Integrate hooks and the rest of the logic into the `useSyncMedia` hook

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes https://github.com/wordpress-mobile/gutenberg-mobile/issues/5611

## Proposed changes:

* The `useSyncMedia` hook has been called from [the `edit.native.js` file](https://github.com/Automattic/jetpack/pull/29996/files#diff-80669e45a350ffdb93b81e6ca442d6faaa68f0d2d7e34298862893d61f73ff50), so that the block's settings are synced across web and the app.
* https://github.com/Automattic/jetpack/pull/29996/commits/6b2e83630e1ed4c8c56527ececfb9af52cdbae89: A temporary "Save Settings" button has been introduced. **Note, this is temporary and will not be shipped to users. We aim to remove this hack from the code within a week.** The purpose of this button is to enable us to more easily test the sync functionality internally.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p9ugOq-3mV-p2 

## Does this pull request change what data or activity we track or use?

No, it does not.

## Testing instructions:

* With the changes from this PR applied, first navigate to the post editor on the web.
* Either add a new VideoPress block or use an existing one, and make sure to tweak its settings. It's particularly important to tweak the settings in the **Details** and **Privacy and rating** panels, as these are the settings that are not currently being synced.
* Save your changes on the web and then navigate to the post in the native app.
* Verify that the block's settings have been correctly fetched from the web.
* Next, update the block's settings in the app itself. 
* Tap the temporary **Save Settings** button from the settings panel. 
* Verify that these changes have been synced to the web.
* Go through a few tries of editing the block on the web then returning the app, and vice versa, to ensure syncing is working as expected.

**Screen recording:**

https://user-images.githubusercontent.com/2998162/231724361-a4850ce7-8413-4b29-943a-d74804feab32.mov

### CODE REVIEW

**Review by fluiddot — COMMENTED** [review]
Great work @SiobhyB 🏅 ! 

I checked the changes and noticed the following issues:
* When changing the rating to `R` and saving the settings, the insert your DOB message is not shown in the video. However, I checked the web version and this issue can also be reproduced so I wouldn't block the PR due to this. As a workaround, we could figure out a way to force the preview to be reloaded. 
* The privacy option `Site Default` of the `Privacy and Rating` settings section doesn't reflect the privacy of the site. It always shows the `Public` value (e.g. `Site Default (Public)`). I checked the code of the web version and seems we need to pass the `privateEnabledForSite` prop to the `PrivacyAndRatingPanel` which is included in the video data returned by the `useSyncMedia` hook:
```
	const { videoData } = useSyncMedia(
		attributes,
		setAttributes,
		blockSettingsSaved,
		setBlockSettingsSaved
	);
	const { private_enabled_for_site: privateEnabledForSite } = videoData;
```

File: projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
Comment (fluiddot) [inline projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts:1]: There's a localized string in this file ([reference](https://github.com/Automattic/jetpack/blob/125163a2575cec14371c30294dad657313cf9e1a/projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts#L373)), although I'm not sure if we'll need it in the native version, @SiobhyB WDYT?

If so, since in GB-mobile the translation pipeline can't process TypeScript files, we might consider duplicating this file and removing all TypeScript code. I wouldn't block the PR due to this as we can do this in a separate PR if needed.

Comment (SiobhyB) [reply projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts:1]: @fluiddot, I don't think this is needed in the native version at the moment, either. If we add support for tracks in the future, we should then probably split the code, but I'm not sure if it's warranted at the moment. Do you think it seems sound to leave it as-is for now?

**Comment by SiobhyB** [comment]
@fluiddot, thank you for being so diligent in your reviews as always 🙇‍♀️  I added the fix for the privacy issue in https://github.com/Automattic/jetpack/pull/29996/commits/1bdc0572ea89ad818574f42c7ede5d2b71ccbdb3 and confirmed it works in my testing now. I can also follow up separately on the rating UI issue.

File: projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
Comment (fluiddot) [reply projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts:1]: Good point. Although I noticed that chapters are also autogenerated in the native version. You can try by pasting the following text into the description field and saving the settings:
```
00:00 Intro
00:24 Mountains arise
02:38 Coming back home
03:04 Credits
```

The editor tries to upload the chapters but fails with the following error. Probably we should disable this functionality in the native version to avoid the warning.
```
Possible Unhandled Promise Rejection (id: 0):
"\"upload\" scope is not supported."
```

In any case, I agree that at this point it's not needed to migrate the file 👍 .

Comment (SiobhyB) [reply projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts:1]: I attempted to auto generate the chapters, but wasn't able to get it working. 🤔 However, I have prevented that code from running for native in https://github.com/Automattic/jetpack/pull/29996/commits/b5202e7374e13a9cdc9954f4aa21dd32d9dc163f. @fluiddot, would you be able to confirm whether it fixes what you're seeing? Thank you! 🙇‍♀️

**Review by fluiddot — DISMISSED** [review]
LGTM 🎊 !

## Native version
I followed the testing instructions from the PR and confirm that the changes work as expected:
* Metadata is updated when changing block settings and saving via the temporary save button. ✅ 
* Chapters are not auto-generated after saving settings. ✅

## Web version
I tested the following flows in the web version to confirm that no regressions were introduced:
* Check that metadata is updated when changing block settings and saving the post. ✅ 
* Check that chapters are auto-generated after saving the post. ✅

File: projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts
Comment (fluiddot) [reply projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts:1]: I confirm that https://github.com/Automattic/jetpack/commit/b5202e7374e13a9cdc9954f4aa21dd32d9dc163f fixed the issue, thanks!

File: projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts [hunk 1]
```diff
@@ -145,11 +147,15 @@ function arrangeTracksAttributes(
...
+ * @param {boolean} blockSettingsSaved  - Temporary attribute to track when block settings have been saved on native.
+ * @param {Function} setBlockSettingsSaved  - Temporary attribute to track manually control when settings are synchronised on native.
  * @returns {UseSyncMedia}      Hook API object.
  */
 export function useSyncMedia(
 	attributes: VideoBlockAttributes,
-	setAttributes: VideoBlockSetAttributesProps
+	setAttributes: VideoBlockSetAttributesProps,
+	blockSettingsSaved = false,
+	setBlockSettingsSaved = undefined
```
Comment (fluiddot) [inline projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts]: Nitpick: The default value for `setBlockSettingsSaved` should be `undefined` when the prop is not passed, hence we could avoid setting the default value here.

Comment (SiobhyB) [reply projects/packages/videopress/src/client/block-editor/hooks/use-sync-media/index.ts]: Thank you, changed in https://github.com/Automattic/jetpack/pull/29996/commits/dcd27ca81d52dc3ed76f27322fcdd83e88d49de0 🙇‍♀️

**Comment by dhasilva** [comment]
About the DOB message when the video rating is `R`, it is a known problem. I opened [this issue](https://github.com/WordPress/gutenberg/issues/48942) on the Gutenberg repo, so for now it is blocked for us.

**Review by dhasilva — APPROVED** [review]
No regressions on the web version. I did not test the mobile version, but since @fluiddot did we are good to go.

**Review by fluiddot — APPROVED** [review]
Re-approving the PR after the last change and following my previous review https://github.com/Automattic/jetpack/pull/29996#pullrequestreview-1383757144.
