### PR TITLE
Sitemaps: when module is activated, schedule generation once

### LINKED ISSUE #6854: Sitemaps fail to activate properly on sites with many posts.
When you have a site with lots of posts (I tried around 1600), sitemaps fails to activate from the settings. It gets a timeout from the server and displays an `Invalid JSON` error in the notice. When I tried to generate them using cron, it ran for 20 minutes, got the load average to about 11, I had to kill it.

#### Steps to reproduce the issue
* Create a ton of posts, maybe even two tons.
* Activate the sitemaps feature.

#### What I expected
* Sitemaps to be activated.
* Message about the sitemaps being generated to disappear.

#### What happened instead
* I saw an error message, sitemaps did not activate until page reload.

cc @eliorivero @dereksmart

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6854

#### Changes proposed in this Pull Request:

* when module is activated, don't generate immediately. Instead, defer it to a cron job to be run once.
* removes message about sitemap being generated

#### Testing instructions:

* make sure the sitemap is generated asap. It won't be generated immediately. Make sure the UI doesn't hang.

### CODE REVIEW

File: modules/sitemaps.php [hunk 1]
```diff
@@ -23,8 +37,11 @@ function jetpack_sitemap_generate_on_activate() {
 	require_once dirname( __FILE__ ) . '/sitemaps/sitemap-builder.php';
 
 	wp_clear_scheduled_hook( 'jp_sitemap_cron_hook' );
-	// Tell build that it's true we're activating this module.
+	wp_clear_scheduled_hook( 'jetpack_sitemap_generate_on_activate' );
+
+	// Tell builder that it's true we're activating this module.
 	$sitemap_builder = new Jetpack_Sitemap_Builder( true );
```
Comment (zinigor) [inline modules/sitemaps.php]: Since we're always running sitemap generation asynchronously, do we even need a constructor parameter here? Otherwise everything's great!

Comment (eliorivero) [inline modules/sitemaps.php]: You're right. Will remove it and its ramifications.

**Comment by eliorivero** [comment]
Updated to remove flag that indicated that the module was being activated since it's no longer necessary now that we're scheduling as if the module was working normally.

**Comment by zinigor** [comment]
Tests well after latest changes!

**Comment by dereksmart** [comment]
merged to 4.8 401157c85
