### PR TITLE
Search: Fix modal intermittently scrolls to wrong position in Firefox

### LINKED ISSUE #19480: Search: modal intermittently scrolls to wrong position in Firefox
This has been happening since the modal changes introduced in Jetpack 9.6.

#### Steps to reproduce the issue

1. In Firefox, go to a page with search enabled and open the modal.

Note: this never seems to happen when the search page is loaded with a query (like example.com/?s=dog). It only occurs when opening the modal manually. I've been using the Twenty Twenty theme and its 'Search' button to test this.

I couldn't reproduce it in Safari, IE11, Edge or Chrome.

#### What I expected
The search modal always opens with the search input visible.

#### What happened instead
Sometimes, at certain window sizes, Firefox does not scroll to the top of the modal and the the search input is not visible. 

**Screenshots**

Screen Shot 2021-04-09 at 11 16 46
Screen Shot 2021-04-09 at 11 14 44

### PR DESCRIPTION
**Pull request by kangzj**
Fixes #19480 

#### Changes proposed in this Pull Request:
The overlay will not automatically be scrolled to the top  when used in conjuction with slideInUp animation. A timeout to trigger `scrollOverlayToTop` was used to correct it, but under some circumstances in Firefox, the function is called before the animation, which makes the overlay still not scrolled to the top sometimes.

The PR changed the scroll trigger from timeout to listening to `transitionend` event, by which we could wait till the animation is complete and then we could scroll the overlay to the top.

The issue that the overlay is not scrolled to the top after animation is not in the scope of this pull request, and will need further investigation.

#### Jetpack product discussion
n/a

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
- In Firefox/Chrome/Safari/IE11/Edge, go to a page with search enabled and open the modal
- Ensure the search input of the overlay is visible without scrolling
image

### CODE REVIEW

File: projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx [hunk 1]
```diff
@@ -144,11 +155,15 @@ class SearchApp extends Component {
...
+	scrollOverlayToTop( event ) {
+		if ( event?.propertyName !== 'transform' ) {
+			return;
+		}
+		const overlay = event.target;
 		// NOTE: IE11 doesn't support scrollTo. Manually set overlay element's scrollTop.
 		if ( overlay.scrollTo ) {
-			overlay.scrollTo( 0, 0, { smooth: true } );
+			// @see https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo
+			overlay.scrollTo( 0, 0 );
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:166]: Is `{ smooth: true }` no longer required? Can we use the options syntax instead, like:

```
element.scrollTo({
  top: 100,
  left: 100,
  behavior: 'smooth'
});
```

Comment (kangzj) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:166]: Safari does not support scrollTo options, so I  don't think we'd use options - and I don't see any difference whether I add smooth or not.  https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo#browser_compatibility

Comment (kangzj) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:166]: hmmm I tested on latest Safari, it actually supports scrollTo options.

Comment (bluefuton) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:166]: I wonder how it'd fare on older versions of Safari 🤔 Could be worth a go on Browserstack?

Also happy to omit it if it makes no visual difference :)

Comment (kangzj) [reply projects/plugins/jetpack/modules/search/instant-search/components/search-app.jsx:166]: I reckon we use scrollTo without options, which has better compatibility and has no virtual difference via behaviour `smooth` parameter. 😄

**Review by bluefuton — DISMISSED** [review]
✅ Tests out well for me across browsers. Can no longer repro the original issue in Firefox.

**Review by jsnmoon — DISMISSED** [review]
Excellent fix! Needs a rebase before merging, it looks like.

**Comment by kangzj** [comment]
> Excellent fix! Needs a rebase before merging, it looks like.

Hi @jsnmoon Thanks for the review. Just rebased, could you please have another look, thanks.

**Review by jsnmoon — APPROVED** [review]
