### PR TITLE
Boost: Improve critical css generation process

### LINKED ISSUE #41391: [Critical CSS Gen] Prevent bad URLs from breaking Critical CSS Generator
Related: https://github.com/Automattic/jetpack/pull/35561

If a bad URL gets fed into one Critical CSS provider, the whole process fails with a meaningless error:
```
Failed to construct 'URL': Invalid URL
```

If parsing a URL fails, it should throw a provider-specific error message, and specify what URL was invalid.

### PR DESCRIPTION
**Pull request by dilirity**
This PR fixes the C.CSS generation process breaking when an invalid URL was passed to the critical CSS gen library.

Recommendations will also now be more unique instead of bunched together under one entry on the advanced recommendations page. Previously, if a provider failed and had URLs with a 301, 404 and 500 error, items would be listed under the 500 error (or the most frequent one). Now they all have separate recommendations and can be dismissed individually. In other words, the `error_status` for providers has been replaced with `dismissed_errors` and now holds all error types that were dismissed via the UI.

Fixes #41391

## Proposed changes:

* Fix invalid URLs passed to critical CSS gen library, resulting in the whole process being broken;
* Add `InvalidURLError` recommendation and steps on how to address it;
* Add watch command to CSS gen package;
* Fix not reporting non-200 HTTP errors to the user. This means, 404 pages will no longer be used to generate critical css for a group;
* Update advanced recommendations listing, to list recommendations based on provider-error type, instead of just provider.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

```
All tests should be run with Boost free,
as these changes affect the css gen package used in the free version.
```

### Test that it breaks (old/production behavior)

<details>
<summary>Instructions</summary>

```
Add this snippet to your website.
It changes the providers list to two groups and adds an invalid URL to the posts group:
```

```php
add_filter( 'jetpack_boost_critical_css_providers', 'jb_critical_css_providers', 15 );
function jb_critical_css_providers( $providers ) {
	$new_providers = [];
	foreach ( $providers as &$provider ) {
		if ( $provider['key'] === 'core_posts_page' ) {
			$new_providers[] = $provider;
		} else if ( $provider['key'] === 'singular_post' ) {
			// Add the bad URL to the front so we don't wait for the whole process.
			$provider['urls'] = array_merge( [ 'oh-hi-bad-url' ], $provider['urls'] );
			$new_providers[] = $provider;
		}
	}
	return $new_providers;
}
```

- Setup Boost from trunk or production;
- Generate Critical CSS;
- You should get the same error as mentioned in the related ticket:

CleanShot 2025-02-24 at 18 05 07

</details>

### Test that 404 pages are used in CSS generation (old/production behavior)

<details>
<summary>Instructions</summary>

```
Replace the old snippet with this one.
It will replace the posts group URLs with 404 URLs:
```

```php
add_filter( 'jetpack_boost_critical_css_providers', 'jb_critical_css_providers', 15 );
function jb_critical_css_providers( $providers ) {
	$new_providers = [];
	foreach ( $providers as &$provider ) {
		if ( $provider['key'] === 'core_posts_page' ) {
			$new_providers[] = $provider;
		} else if ( $provider['key'] === 'singular_post' ) {
			$provider['urls'] = [
				home_url( 'non-existent-url' ),
				home_url( 'non-existent-url-2' ),
				home_url( 'non-existent-url-3' ),
			];
			$new_providers[] = $provider;
		}
	}
	return $new_providers;
}
```

- Switch to trunk/production version of Boost (if not already);
- Generate critical css;
- The process should complete with 2 files generated.

</details>

### Test that the process doesn't break if there's an invalid URL in the list (new behavior)

<details>
<summary>Instructions</summary>

```
Replace the existing snippet with this one (same as the first test):
```

```php
add_filter( 'jetpack_boost_critical_css_providers', 'jb_critical_css_providers', 15 );
function jb_critical_css_providers( $providers ) {
	$new_providers = [];
	foreach ( $providers as &$provider ) {
		if ( $provider['key'] === 'core_posts_page' ) {
			$new_providers[] = $provider;
		} else if ( $provider['key'] === 'singular_post' ) {
			// Add the bad URL to the front so we don't wait for the whole process.
			$provider['urls'] = array_merge( [ 'oh-hi-bad-url' ], $provider['urls'] );
			$new_providers[] = $provider;
		}
	}
	return $new_providers;
}
```

- Switch to `fix/critical-css-gen/invalid-url-breaking-whole-process`;
- Generate critical css;
- The generation should succeed. Despite there being an invalid URL in the list, the generation process was successful and recommendations won't be shown to the user (this is old behavior). The single posts group needs 50% of posts to be successful. By default, new sites have only 1 post so having the bad URL guarantees a 50% success rate.

</details>

### Test that it gives individual recommendations about errors

<details>
<summary>Instructions</summary>

```
Make sure to replace the old snippet with the one below.
It will add an invalid URL in the posts provider and several 404 URLs:
```

```php
add_filter( 'jetpack_boost_critical_css_providers', 'jb_critical_css_providers', 15 );
function jb_critical_css_providers( $providers ) {
	$new_providers = [];
	foreach ( $providers as &$provider ) {
		if ( $provider['key'] === 'core_posts_page' ) {
			$new_providers[] = $provider;
		} else if ( $provider['key'] === 'singular_post' ) {
			$provider['urls'] = [
				'oh-hi-bad-url',
				home_url( 'non-existent-url' ),
				home_url( 'non-existent-url-2' ),
				home_url( 'non-existent-url-3' ),
			];
			$new_providers[] = $provider;
		}
	}
	return $new_providers;
}
```

- Switch to this branch (if you're not on it already);
- Generate critical css;
- You should see 1 successful file and 1 recommendation:

CleanShot 2025-02-24 at 18 09 42

- Click the `advanced recommendations page` link to go to the recommendations page;
- You should see two items - one for the invalid URL and another for the 404. You can dismiss them individually. Make sure that you can dismiss them and un-dismiss them using the `Show X hidden recommendation.` link.

</details>

### CODE REVIEW

File: projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts [hunk 1]
```diff
@@ -140,7 +149,18 @@ export class BrowserInterfaceIframe extends BrowserInterface {
...
-		const fullUrl = this.addGetParameters( rawUrl );
+		// Make sure URL is valid.
+		let url;
+		try {
+			url = new URL( rawUrl );
+		} catch ( err ) {
+			return new Promise( ( resolve, reject ) => {
+				this.trackUrlError( rawUrl, err );
+				reject( new InvalidURLError( { url: rawUrl } ) );
+			} );
```
Comment (LiamSarsfield) [inline projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: Nit: We could use the below instead here, since `loadPage` is async, it's the same as rejecting the promise, but [minimises callback hell](http://callbackhell.com/)
```suggestion
			this.trackUrlError( rawUrl, err );
			throw new InvalidURLError( { url: rawUrl } );
```

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts [hunk 2]
```diff
@@ -140,3 +141,51 @@ export function groupKey( error: CriticalCssErrorDetails ) {
...
+
+export function groupRecommendationsByStatus(
+	providersWithIssues: Provider[]
+): RecommendationsResult {
+	const activeRecommendations: ProviderRecommendation[] = [];
+	const dismissedRecommendations: ProviderRecommendation[] = [];
+
+	providersWithIssues.forEach( provider => {
+		// Group errors by type first
+		const errorsByType = ( provider.errors || [] ).reduce<
```
Comment (LiamSarsfield) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts]: Nit: It feels like we're not really using TypeScript's type inference here but instead sacrificing readability for overly explicit typing, which might be a code smell.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts [hunk 3]
```diff
@@ -140,3 +141,51 @@ export function groupKey( error: CriticalCssErrorDetails ) {
...
+			if ( ! acc[ error.type ] ) {
+				acc[ error.type ] = [];
+			}
+			acc[ error.type ].push( error );
+			return acc;
+		}, {} );
+
+		// For each error type group, check if it's dismissed
+		(
+			Object.entries( errorsByType ) as [ Critical_CSS_Error_Type, CriticalCssErrorDetails[] ][]
```
Comment (LiamSarsfield) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts]: Nit: Same concern here regarding TypeScript type inference, could this be within `projects/plugins/boost/app/assets/src/js/features/critical-css/lib/stores/critical-css-state-types.ts` as a specific type?

File: projects/plugins/boost/app/assets/src/js/pages/critical-css-advanced/critical-css-advanced.tsx [hunk 4]
```diff
@@ -136,25 +154,55 @@ const HeadingMeta = ( { dismissedIssues, showDismissedIssues }: HeadingMetaProps
...
+			{ errorSets.map( ( errorSet, _index ) => (
+				<SingleRecommendation
+					key={ `${ recommendation.key }-${ errorSet.type }` }
+					recommendation={ recommendation }
+					errorSet={ errorSet }
+					setDismissed={ setDismissed }
+				/>
+			) ) }
+		</>
+	);
```
Comment (LiamSarsfield) [inline projects/plugins/boost/app/assets/src/js/pages/critical-css-advanced/critical-css-advanced.tsx]: This could be simplified to the below:
```suggestion
	return errorSets.map( ( errorSet, _index ) => (
		<SingleRecommendation
			key={ `${ recommendation.key }-${ errorSet.type }` }
			recommendation={ recommendation }
			errorSet={ errorSet }
			setDismissed={ setDismissed }
		/>
	) );
```

**Comment by LiamSarsfield** [comment]
Looks good to me! Works as expected and I can't see any major issues besides nitpicks. 
I think we discussed this offline but for a future initiative I think we should adjust the wording. Particularly the "file" and "recommendation" meaning in this context, I don't think it's entirely accurate.

Screenshot 2025-03-03 at 13 46 40

**Review by LiamSarsfield — DISMISSED** [review]
Looks good to me! Works as expected and I can't see any major issues besides nitpicks. 
I think we discussed this offline but for a future initiative I think we should adjust the wording. Particularly the "file" and "recommendation" meaning in this context, I don't think it's entirely accurate.

Screenshot 2025-03-03 at 13 46 40

File: projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts (hunk 1 above)
Comment (haqadn) [reply projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: I've updated Liam's suggestion to fix the whitespace (spaces to tabs).

File: projects/js-packages/critical-css-gen/tests/unit/browser-interface-iframe.test.js [hunk 5]
```diff
@@ -173,8 +173,8 @@ describe( 'Iframe interface', () => {
 		const page = await browser.newPage();
 		await page.goto( testServer.getUrl() );
 
-		const pageA = path.join( testServer.getUrl(), 'page-a' );
-		const pageB = path.join( testServer.getUrl(), 'page-b' );
+		const pageA = path.join( testServer.getUrl(), 'page-a/' );
+		const pageB = path.join( testServer.getUrl(), 'page-b/' );
 
 		const result = await page.evaluate(
```
Comment (haqadn) [inline projects/js-packages/critical-css-gen/tests/unit/browser-interface-iframe.test.js]: I am curious if the slashes change anything behavior-wise for the tests.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts [hunk 6]
```diff
@@ -464,6 +464,45 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+		describeSet: set =>
+			_n(
+				'Jetpack Boost found an invalid URL:',
+				'Jetpack Boost found invalid URLs:',
+				urlCount( set ),
+				'jetpack-boost'
+			),
+		suggestion: _set => ( {
+			paragraph: __(
+				'Jetpack Boost needs valid URLs from the current site in order to generate Critical CSS. It seems that one or more of the URLs you provided are invalid.',
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: Nitpick: I don't think we need to mention "current site". Though you probably have some context in mind, this might leave the user wondering what current site is.
```suggestion
				'Jetpack Boost needs valid URLs in order to generate Critical CSS. It seems that one or more of the URLs you provided are invalid.',
```

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts [hunk 7]
```diff
@@ -464,6 +464,45 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+					'jetpack-boost'
+				),
+				__(
+					'Verify your WordPress permalink settings are configured correctly in Settings → Permalinks.',
+					'jetpack-boost'
+				),
+				__(
+					'If you use custom post types, ensure they are properly registered and their permalinks are working.',
+					'jetpack-boost'
+				),
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts:494]: Do you think we need to mention, "it is ok to ignore custom post type URLs that aren't meant to show publicly"? 🤔

**Review by haqadn — APPROVED** [review]
Changes look good and works as expected. Thank you for the very helpful and detailed testing instructions.

**Review by haqadn — DISMISSED** [review]
Changes look good and works as expected. Thank you for the very helpful and detailed testing instructions.

File: projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts (hunk 1 above)
Comment (dilirity) [reply projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: @LiamSarsfield I had no idea this is what's making me not like JS. WOW - nice read. Thank you!

File: projects/plugins/boost/app/assets/src/js/pages/critical-css-advanced/critical-css-advanced.tsx (hunk 4 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/pages/critical-css-advanced/critical-css-advanced.tsx]: Oops. Nice catch 😅

**Comment by dilirity** [comment]
~This needs a fix as there's a bug. If you multiple status code errors for an HttpError, dismissing one, dismisses all of them.~

~You also get this nice error in there:~

```
react-dom.js?ver=18.3.1.1:73 Warning: Encountered two children with the same key, `singular_post-HttpError`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Moved to its own issue https://github.com/Automattic/jetpack/issues/42206

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts (hunk 6 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: I think you're right. No need to be overly technical.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts (hunk 7 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts:494]: Makes sense. I've included that step and updated the second.

CleanShot 2025-03-04 at 17 49 50

File: projects/js-packages/critical-css-gen/tests/unit/browser-interface-iframe.test.js (hunk 5 above)
Comment (dilirity) [reply projects/js-packages/critical-css-gen/tests/unit/browser-interface-iframe.test.js:179]: I think because of the missing slash, loading the page did a redirect. There was no check for that before, so the process continued. However, I'm not sure why there was no redirect error in the tests then.

With the check I added, if the request isn't 200, it will be declined with an HttpError.

Now this makes me wonder - did generation work for pages with a redirect?

Comment (dilirity) [reply projects/js-packages/critical-css-gen/tests/unit/browser-interface-iframe.test.js]: I added the slashes to fix the tests, but didn't realize what the actual reason for them breaking was.

I [introduced](https://github.com/Automattic/jetpack/pull/41946/commits/f7f9078763051dc7dde6989d404c6ac0892bc6ee) (and [here](https://github.com/Automattic/jetpack/pull/41946/commits/c2de569460065008fd54e4ee78a2bd797b2a89c0)) an http status code check, to prevent CSS gen from processing non-200 pages (in other words - catch 404 pages during generation). What I didn't realize is that there's a [opaqueredirect](https://developer.mozilla.org/en-US/docs/Web/API/Response/type#:~:text=opaqueredirect%3A%20The%20fetch%20request%20was%20made%20with%20redirect%3A%20%22manual%22.%20The%20Response%27s%20status%20is%200%2C%20headers%20are%20empty%2C%20body%20is%20null%20and%20trailer%20is%20empty.) happening (because of the redirect from `page-a` to `page-a/`). That opaqueredirect wasn't a problem before, as it was just redirecting the iframe to the correct page and the css gen library was processing the pages.

Because the opaqueredirect returns a status 0, my change ended up preventing CSS generation for working on such pages.

I've [updated](https://github.com/Automattic/jetpack/pull/41946/commits/cb976c4acf9bdcbcc5abc9105878c73533dad789) the check to only handle 404 pages, to allow the opaqueredirect to work again. I've also [removed](https://github.com/Automattic/jetpack/pull/41946/commits/9a48e19d6690a3375965949debfc4bfd320e34e9) the slashes.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts (hunk 2 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts]: This was [updated](https://github.com/Automattic/jetpack/pull/41946/commits/b80ebf1d4335b374b0ee3d3aaef57f7a552cc70a) during a sync call in Slack.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts (hunk 3 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/critical-css-errors.ts]: This was [updated](https://github.com/Automattic/jetpack/pull/41946/commits/b80ebf1d4335b374b0ee3d3aaef57f7a552cc70a) during a sync call in Slack.

File: projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts [hunk 8]
```diff
@@ -131,13 +131,13 @@ export class BrowserInterfaceIframe extends BrowserInterface {
 		}
 	}
 
-	async hasValidHttpStatus( url: string ): Promise< UrlError | null > {
+	async is404Page( url: string ): Promise< UrlError | null > {
```
Comment (LiamSarsfield) [inline projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: Nitpick: When I see a function called `is404Page` usually I assume it'll return a Boolean, I wonder could we return a `true`/`false` here instead? Or rename the function to something that might indicate it might return a URL error?

Comment (haqadn) [reply projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: +1

**Review by LiamSarsfield — DISMISSED** [review]
Looks good to me! Tested with new changes as works as expected.

File: projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts (hunk 8 above)
Comment (dilirity) [reply projects/js-packages/critical-css-gen/src/browser-interface-iframe.ts]: Thanks for the nit!

Fixed in 8256a14.

**Review by LiamSarsfield — APPROVED** [review]
LGTM! 🙌
