### PR TITLE
Boost: detect xframe options

### LINKED ISSUE #21023: Detect X-Frame-Options DENY
Jetpack Boost uses iframes to generate Critical CSS. Some customers have run into an issue when they use the `X-Frame-Options: DENY` header to disallow their site loading inside an iframe.

Unfortunately, Jetpack Boost doesn't detect cases like these, and gives users a really unhelpful error message when this occurs: "It looks like this URL doesn't match: <URL>".

When loading content in an iframe fails, the Critical CSS generator library uses `diagnoseUrlError` (in browser-interface-iframe.js`) to load the same URL with `fetch` to diagnose what went wrong. That way, it can detect HTTP errors, redirects, etc - which aren't really detectable when an iframe load fails.

That method could be updated to check the response headers for `X-Frame-Options` deny, and throw an error which explains the sitaution.

Jetpack Boost's Critical CSS error handling code will also need to be updated to handle this error message, and show it in a user-friendly manner.

### PR DESCRIPTION
**Pull request by amustaque97**
Fixes #21023

#### Changes proposed in this Pull Request:

* This PR is few changes are done in other PR link: https://github.com/Automattic/jetpack-boost-critical-css-gen/pull/20
* In the Jetpack repo I have added recommendations for `XFrameDenyError`

#### Testing instructions:

* Testing instructions are same as of the other PR https://github.com/Automattic/jetpack-boost-critical-css-gen/pull/20

#### Screenshot:
Screenshot from 2021-09-10 23-21-13

cc @thingalon

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts [hunk 1]
```diff
@@ -435,6 +435,33 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
 			],
 		} ),
 	},
+
+	XFrameDenyError: {
+		describeSet: set =>
+			_n(
+				"Jetpack Boost couldn't proceed because of x-frame-deny configuration",
+				"Jetpack Boost couldn't proceed because of x-frame-deny configuration",
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts:443]:
```suggestion
				"Jetpack Boost couldn't load the following page due to its X-Frame-Options configuration:",
				"Jetpack Boost couldn't load the following pages due to their X-Frame-Options configuration:",
```

File: projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts [hunk 2]
```diff
@@ -435,6 +435,33 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+				'jetpack-boost'
+			),
+		rawError: set => Object.values( set.byUrl )[ 0 ].message,
+		suggestion: set => ( {
+			paragraph: _n(
+				'Please follow the troubleshooting steps below for the page.',
+				'Please follow the troubleshooting steps below for each of the pages.',
+				urlCount( set ),
+				'jetpack-boost'
+			),
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts:454]: The suggestion should give a user-friendly idea of what the error means.

```suggestion
			paragraph: __(
				'Jetpack Boost uses iframes while generating your Critical CSS. Unfortunately, your site has a special configuration header which prevents it from loading inside an iframe. The header is called "X-Frame-Options: DENY". This can be added to a WordPress site either by using a plugin, or by server configuration.',
				'jetpack-boost'
			),
```

File: projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts [hunk 3]
```diff
@@ -435,6 +435,33 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+			list: [
+				__( 'Verify that x-frame-options header value is not set to deny', 'jetpack-boost' ),
+				__( 'If it does, <retry>try again</retry> to generate the Critical CSS.', 'jetpack-boost' ),
+				__(
+					'If the error still persist please contact <support>Jetpack Boost Support</support> with a copy of your error message.',
+					'jetpack-boost'
+				),
```
Comment (thingalon) [inline projects/plugins/boost/app/assets/src/js/utils/describe-critical-css-recommendations.ts:461]:
```suggestion
				__( 'Check that you are not using any plugins which add extra HTTP headers to your WordPress site, and deactivate them if you are.', 'jetpack-boost' ),
				__( 'If you are unsure of what these headers are, or where they come from please contact your hosting provider and ask them to remove the "X-Frame-Options" header from your site', 'jetpack-boost' ),
				__( '<retry>Try again</retry> to generate the Critical CSS.', 'jetpack-boost' ),
```

**Review by thingalon — CHANGES_REQUESTED** [review]
Thank you for this fix; your implementation is good.

I've supplied some clearer wording for the error messages, and some suggestions which novice users will hopefully find easier to follow when facing this error. :)

**Comment by amustaque97** [comment]
Hi @thingalon, I have addressed the review comments, please take a look at PR once again. I'm attaching a screenshot after making changes.
Screenshot 2021-09-13 21:41:21

**Review by thingalon — APPROVED** [review]
👍  Looks great! Thank you for your contribution! :)

**Comment by thingalon** [comment]
@amustaque97 would you mind merging or rebasing from `master`? Our pre-merge checklist won't let me merge if it's a little out of date. :)

**Comment by amustaque97** [comment]
@thingalon, I have taken a merge from master and PR is up to date. :)

**Review by thingalon — APPROVED** [review]
👍  Thanks!
