### PR TITLE
Admin Menu / WooCommerce: Fix product redirect

### LINKED ISSUE #72429: On a self-hosted site with WooCommerce and Jetpack connection, Products tab does not work as expected when Secure Sign On is enabled
### Quick summary

On a self-hosted site with WooCommerce and Jetpack connection, Products tab in the menu area redirects to the **Products** page in WP-Admin (`/wp-admin/edit.php?post_type=product`). 
However, when Secure Sign On is enabled, this is no longer the case. The `Products` tab points to `https://wordpress.com/types/product/{site}` page that displays the _You need permission to manage this post type
Ask your site administrator to grant you access_ notice.

### Steps to reproduce

1. Set up a self-hosted site with Jetpack connection and WooCommerce installed
2. Visit the site in Calypso
3. Try to access **Products** from the main menu (left sidebar)
4. You will be redirected to your site's WP Admin > Products (`/wp-admin/edit.php?post_type=product`)
Markup 2023-01-23 at 13 38 34

5. Now, activate Secure Sign On (In your WP dashboard in **Jetpack > Settings > Security > WordPress.com Login** or in Calypso **Settings > Security > WordPress.com log in**
6. Reload the browser in Calypso
7. You will notice that the `gridicons-external` icon disappeared
8. When you click the **Products** you will be pointed to `https://wordpress.com/types/product/{site}` page that displays _You need permission to manage this post type Ask your site administrator to grant you access_
Markup 2023-01-23 at 13 40 55

### What you expected to happen

The icon does not disappear and the user is redirected to their WP Admin > Products.
In other words, I would expect that the experience does not change whether SSO is enabled or not.
The notice is also confusing, it's displayed regardless if there are only one or multiple admins on the site.

### What actually happened

User is confused. They are admin but don't have permission to edit/see products.

### Context

Reported in 5863777-zd-woothemes

### Platform (Simple, Atomic, or both?)

Self-hosted

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

- Clarify to the user that they should always log in to their WP admin in order to edit Products. 
- Disable SSO to remove the confusion

### PR DESCRIPTION
**Pull request by valterlorran**
Fixes https://github.com/Automattic/wp-calypso/issues/72429

## Proposed changes:

* We noticed that the "Products" button was not working on self-hosted sites connected with Jetpack and had the SSO enabled. The problem was the user was being redirected to `https://wordpress.com/types/product/{site}` as opposed to `/wp-admin/edit.php?post_type=product`.
* I updated the check on the `class-jetpack-admin-menu.php` file, which is responsible for generating the link we use in Calypso.
* I'm not convinced that this is the best approach, but I believe we shouldn't disable the `show_in_rest` prop on the Product type.

For more context, please visit https://github.com/Automattic/wp-calypso/issues/72429

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* We need a self-hosted site to test this. I used a Jurassic Ninja site for that and applied the changes manually. 
* Install WooCommerce on your self-hosted site and connect Jetpack.
* Don't enable the SSO just yet.
* Now access your site on WordPress.com
* Click on the Products link, and you should be redirected to the WP Admin page of your site.
* Now enable the SSO, and go back to WordPress.com
* Click again on the Products link and you should be redirected to the WP Admin page again.
* You can also remove the changes and test the wrong behavior.

### CODE REVIEW

File: projects/packages/masterbar/src/admin-menu/class-jetpack-admin-menu.php [hunk 1]
```diff
@@ -61,6 +61,20 @@ public function get_preferred_view( $screen, $fallback_global_preference = true
 		return self::DEFAULT_VIEW;
 	}
 
+	/**
+	 * Check if the current site is a self-hosted site.
+	 *
+	 * @return bool Whether the site is a self-hosted site.
+	 */
+	private function is_self_hosted_site() {
```
Comment (myhro) [inline projects/packages/masterbar/src/admin-menu/class-jetpack-admin-menu.php]: There's [a similar check][1] in the `comments` module, where we basically check if the `Host.is_wpcom_platform()` method returns `false`:

```php
// Not allow it to run on self-hosted or simple sites
if ( ! ( new Host() )->is_wpcom_platform() || ( new Host() )->is_wpcom_simple() ) {
	$tracking_event = 'hidden_self_hosted';
}
```

I'm not sure if it works perfectly in this case, given it checks [if the site is either a Simple Site or Atomic][2], but maybe we can use a similar check? This way we may not need to add a new method with a different logic.

[1]: https://github.com/Automattic/jetpack/blob/0655fb30d3cd2173ad94ed13726c56cf139fd440/projects/plugins/jetpack/modules/comments/comments.php#L827-L830
[2]: https://github.com/Automattic/jetpack/blob/681e85c06f8b28b948fff347982a63cc58abf9da/projects/packages/status/src/class-host.php#L70-L79

**Review by myhro — DISMISSED** [review]
I wasn't able to use the updated branch directly into Jurassic Ninja, as the Jetpack Beta is apparently caching an out-of-date version of it. Still, I manually applied the last commit 0e029d9 and could confirm that the `Products` link in the sidebar points to the same target before and after enabling the Jetpack SSO:

## Before

`https://keen-blackbird.jurassic.ninja/wp-admin/edit.php?post_type=product`

## After

`https://keen-blackbird.jurassic.ninja/wp-admin/edit.php?post_type=product`

---

LGTM. Thanks for the PR, @valterlorran!

File: projects/packages/masterbar/src/admin-menu/class-jetpack-admin-menu.php [hunk 2]
```diff
@@ -70,9 +71,11 @@ public function get_preferred_view( $screen, $fallback_global_preference = true
 	 */
 	public function get_cpt_menu_link( $ptype_obj ) {
 
-		$post_type = $ptype_obj->name;
+		$post_type                          = $ptype_obj->name;
+		$is_self_hosted_site                = ! ( new Host() )->is_wpcom_platform();
```
Comment (jeherve) [inline projects/packages/masterbar/src/admin-menu/class-jetpack-admin-menu.php]: Do we need that added check here? Looking at the code, `Jetpack_Admin_Menu` should only be loaded on self-hosted sites already:

https://github.com/Automattic/jetpack/blob/15de818749232d2c11e2cf9b7650c558119528ed/projects/packages/masterbar/src/admin-menu/load.php#L130-L132

Comment (valterlorran) [reply projects/packages/masterbar/src/admin-menu/class-jetpack-admin-menu.php]: Thanks for the feedback @jeherve! I updated the code and tested it.

**Review by jeherve — APPROVED** [review]
