### PR TITLE
Calendly Block: Show an error when the embed url is not found

### LINKED ISSUE #14805: Calendly Block: Show an error when the embed url is not found
#### Steps to reproduce the issue

**Calendly**

1. In the block editor, paste a Calendly url that doesn't exist, like `http://calendly.com/not-an-appointment`
1. I expected to see an error message, but instead I see an event not found message, without a clear way of how to fix it (because the URL is hidden)

Screen Shot 2020-02-25 at 22 53 10

#### What I expected

The block uses the `resolve-redirect` API endpoint to check the url before embedding to make sure it returns a valid response/status code, in addition to resolving any redirects for the url.

Screen Shot 2020-02-25 at 22 59 47

(note this is a mockup, the Eventbrite block actually still needs to be updated to show the error in a notice)

#### What happened instead

It doesn't!

### PR DESCRIPTION
**Pull request by Copons**
Fixes #14805

#### Changes proposed in this Pull Request:

* Show a loading spinner when loading the embed.
* Show an error when the embed url is not found.

When inserting an URL, the block tests it through the `resolve-redirect` endpoint.
On success, it sets the block's attributes and loads the embed.
On fail, it empties the URL attributes and shows an error notice.

Feb-26-2020 16-45-27

To make this work with the automatic block transformation when pasting a Calendly URL, the `resolve-redirect` check runs on block mount, and whenever the URL attribute changes.
This, unless the block style is `link`, as this implies that the URL passed the test already (and showing a "loading spinner" would look awkward.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

* Insert a Calendly block and add a correct Calendly URL.
* Make sure the block has a loading spinner and then show the embed as expected.
* Insert a second Calendly block with a correct URL, and set it as `link` style.
* Save and reload the editor.
* Make sure both blocks show up fine; the embedded one should show the loading spinner, while the other should not.
* Insert another Calendly block, this time using an incorrect Calendly URL (e.g. `https://calendly.com/totally-incorrect-url`).
* After the loading spinner, the block should revert to the placeholder with an error notice.
* Save and reload. The incorrect block should show up in placeholder state.
* Try again by pasting a correct and an incorrect URL in the editor. Make sure the behaviour of both transforms is the same as described above.

#### Proposed changelog entry for your changes:

* Calendly block: Show an error when the embed URL is not found.

### CODE REVIEW

**Review by jeherve — DISMISSED** [review]
This works well for me. 🚢

**Review by apeatling — DISMISSED** [review]
Followed all steps and they worked as described. :+1:

File: extensions/blocks/calendly/edit.js [hunk 1]
```diff
@@ -65,6 +68,25 @@ export default function CalendlyEdit( props ) {
 			</>
 		);
 
+	useEffect( () => {
+		if ( ! url || 'link' === style ) {
```
Comment (pablinos) [inline extensions/blocks/calendly/edit.js]: As you can change the URL and get it wrong, do you think it would be good to cover checking the URL for the `link` style too? I realise we probably don't want to show the spinner, but it would be good to let them it's invalid.

image

**Review by scruffian — COMMENTED** [review]
I agree that it would be good to do this check for both styles of embed...

**Comment by Copons** [comment]
@pablinos The `useEffect` here is triggered when the block mounts and the `url` changes.
It happens in these cases:
1. When the visual editor loads from scratch.
2. When the user switches from code to visual editor.
3. When the user pastes a Calendly URL that gets transformed into a Calendly block.

Cases 1 and 2: we don't really need to check the URL, as it's implied that it has been already checked (more about it later).
If you try to change the URL in the code editor, the block should break anyway.

Case 3 is where this comes into play.
Since pasting a link always results in an embedded block, we can safely avoid testing for link style blocks.
On the other hand, for the same reason we are basically forced to test on embedded blocks regardless.

---
Now, the resolve-redirect check runs always when you manually change the embed code (see the `parseEmbedCode` method).
So if you have a link style block and change its URL, it will pass through resolve-redirect.

---

Now, by testing this again I could see two things that look off to me:

1. I'm kinda wondering why the `useEffect` is not triggered when the URL changes after a `parseEmbedCode`.
I mean, it works as it should, but I'm curious why. 😄 
I'm probably failing to notice something that I already solved a few days ago and totally forgot, though.

2. Unfortunately, the `useEffect` is triggered by the block preview in the style selector as well...
I'm not super keen in having dozens of useless calls to `/resolve-redirect/https://calendly.com/wordpresscom/jetpack-block-example`, so I'll need to discard that case as well.

**Comment by scruffian** [comment]
This looks good. My only concern is that it really slows down the preview in the sidebar. I see this for quite a long time:
Screenshot 2020-03-04 at 15 47 47

**Comment by Copons** [comment]
> I'm kinda wondering why the `useEffect` is not triggered when the URL changes after a `parseEmbedCode`.

Ok, for some reasons I was wrong on this, or my dev tools skills aren't good enough.
`useEffect` was indeed being triggered when the `url` was changed by `parseEmbedCode` resulting in one additional, unnecessary, `apiFetch` call.

This happened because the `useEffect` was conditionally running whenever `props.attributes.url` changed, as I was under the impression that pasting an URL would first create an empty block, and then fill it with the URL, thus requiring the check to run on `url` change.

This is not the case: as it turns out, pasting an URL directly creates the block with the `url` prefilled.
So `useEffect` effectively needs to only run on component mount (empty array `[]` as second argument), instead of on `url` change (`[ url ]` as second argument).

What does this mean practically? Let's see case by case.

1. **Normal block creation**
Block is inserted empty. `useEffect` exits immediately. When the user inserts the URL, `parseEmbedCode` tests it.

2. **Block transform on pasted URL**
User pastes a Calendly URL. Block is created with the `url` attribute prefilled. `useEffect` tests it.

3. **URL is changed from sidebar**
`parseEmbedCode` tests the URL. Since the block is already mounted, `useEffect` doesn't even run.

4. **Editor loads with block in embed mode**
If block has no URL, nothing happens. Otherwise, `useEffect` tests it.
This is an unintended (but unavoidable as far as I know) side effect of the case 2.

5. **Editor loads with block in link mode**
Since case 2 (pasting a Calendly URL) can only create a block in embed mode, we don't need to test the URL on old blocks in link mode. `useEffect` exits immediately.

6. **Block example renders in the inserter or the sidebar**
`useEffect` exists immediately when the URL to test is the Calendly example URL.

**Comment by Copons** [comment]
> My only concern is that it really slows down the preview in the sidebar.

@scruffian have you tried with the latest changes? Specifically 08f921a should fix exactly that, as before we were also unintentionally resolving the example URL, and so slowing down the render of the preview embed.

Mar-04-2020 10-01-21

**Comment by scruffian** [comment]
I wonder if we could do away with `useEffect` altogether by calling `parseEmbedCode` when we paste the embed code...

**Comment by Copons** [comment]
> I wonder if we could do away with `useEffect` altogether by calling `parseEmbedCode` when we paste the embed code...

I've tried this a bit, as it seems like the most sensible solution, but I think the async gets in the way.
If I try to run the resolve test with `await` in the transform before creating the block, nothing happens when the response come back.
Though, I might be doing something dumb in there, so feel free to give it a try if you have some spare cycles.

File: extensions/blocks/calendly/edit.js [hunk 2]
```diff
@@ -65,6 +69,25 @@ export default function CalendlyEdit( props ) {
 			</>
 		);
 
+	useEffect( () => {
+		if ( ! url || CALENDLY_EXAMPLE_URL === url || 'link' === style ) {
+			return;
+		}
+		setResolveUrl( true );
+		apiFetch( { path: `/wpcom/v2/resolve-redirect/${ url }` } ).then(
```
Comment (jeherve) [inline extensions/blocks/calendly/edit.js]: Now that we rely on `wpcom/v2/resolve-redirect` here, in the Pinterest block, and in the Eventbrite block, would it make sense / be possible to extract this into a shared function maybe? What do you think?

Comment (Copons) [reply extensions/blocks/calendly/edit.js]: Good thinking!
I'll update this PR by adding an utility function, and then will take care of the other blocks separately to avoid bloating this.

**Review by scruffian — APPROVED** [review]
LGTM

**Review by apeatling — APPROVED** [review]
Tested and confirmed working. :+1:

**Review by jeherve — APPROVED** [review]
This looks good to me. It should be good to merge!

Since it introduces a new file, you'll need to rebuild the matching wpcom diff manually I'm afraid.

**Comment by Copons** [comment]
r204401-wpcom
