### PR TITLE
Connection package: Don't throw warnings if the database is corrupted somehow

### LINKED ISSUE #16299: Connection package throws a warning in some cases
As reported by @parkcityj 

It seems that the updates to "connection tools" are causing PHP errors when the domain doesn't "really" exist - Jetpack is throwing a PHP warning and causing a generic wp_die error from WP Core.

```
Error message
E_WARNING: count(): Parameter must be an array or an object that implements Countable
Stack trace
…gins/jetpack/vendor/automattic/jetpack-connection/src/
class-plugin-storage.php (159)
…ion\Plugin_Storage::configure called at /var/www/wp-includes/
class-wp-hook.php (288)
in WP_Hook::apply_filters called at /var/www/wp-includes/class-wp-hook.php (312)
in WP_Hook::do_action called at /var/www/wp-includes/plugin.php (478)
in do_action called at /var/www/wp-settings.php (392)
in require called at /var/www/wp-admin/setup-config.php (33)
```

Even though the `wp_die` trigger seems to be unrelated, we should keep this warning from happening.

### PR DESCRIPTION
**Pull request by leogermani**
Fixes #16299

Typecast values fetched from the database to avoid warnings.

#### Does this pull request change what data or activity we track or use?

No 

#### Testing instructions:

Just run phpunit tests

#### Proposed changelog entry for your changes:

* No need

### CODE REVIEW

File: packages/connection/src/class-plugin-storage.php [hunk 1]
```diff
@@ -147,7 +147,7 @@ public static function configure() {
 		}
 
 		// If a plugin was activated or deactivated.
-		$number_of_plugins_differ = count( self::$plugins ) !== count( get_option( self::ACTIVE_PLUGINS_OPTION_NAME, array() ) );
+		$number_of_plugins_differ = count( self::$plugins ) !== count( (array) get_option( self::ACTIVE_PLUGINS_OPTION_NAME, array() ) );
```
Comment (kraftbj) [inline packages/connection/src/class-plugin-storage.php:150]: Without being able to reproduce this, this is likely enough. Ideally, if we can run this code on an impacted site and confirm it isn't the `$plugins` that is a problematic. (I don't see how, but I don't trust myself).
