### PR TITLE
Translate Widget: update layout to be responsive.

### LINKED ISSUE #5962: Widgets: Google Translate widget popover isn't responsive
#### Steps to reproduce the issue
1. Add the Google Translate widget to a widget area on your site.
2. Open the site on a mobile device and click on the Translate option.
3. Notice that the resulting popover for language selection doesn't show all available languages and can't seem to be navigated or resized.

img_0643

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #5962

#### Changes proposed in this Pull Request:

This PR includes 2 changes:
1. Change the default layout of the widget displayed by Google. Until now the widget used the "Dropdown Only" mode. It now uses
the "Vertical" mode. This layout is more compatible with mobile devices.
2. Create a new filter, `jetpack_google_translate_widget_layout`, allowing one to switch between layouts if needed:
```php
/**
 * Change the Google Translate Widget layout.
 */
function jeherve_dropdown_only_translate_layout() {
        return 'google.translate.TranslateElement.InlineLayout.SIMPLE';
}
add_filter( 'jetpack_google_translate_widget_layout', 'jeherve_dropdown_only_translate_layout' );
```

Before:

screenshot 2017-06-02 at 14 35 02

After:

screenshot 2017-06-02 at 14 45 21

#### Testing instructions:

1. Make sure the widget is displayed properly on desktop and mobile devices. I'd recommend using an incognito window when switching to the branch to test , as things tend to get cached.
2. Add the snippet above to a functionality plugin and make sure the widget layout can be changed. You can also use the `google.translate.TranslateElement.InlineLayout.HORIZONTAL` string for another layout.

#### Proposed changelog entry for your changes:
* Google Translate Widget: update layout to be responsive.

### CODE REVIEW

File: modules/widgets/google-translate.php [hunk 1]
```diff
@@ -66,7 +66,27 @@ public function widget( $args, $instance ) {
...
+					 *
+					 * @see https://translate.google.com/manager/website/
+					 *
+					 * @module widgets
+					 *
+					 * @since 5.1.0
+					 *
+					 * @param string $layout layout of the Google Translate Widget.
+					 */
+					'layout' => esc_js( apply_filters( 'jetpack_google_translate_widget_layout', '' ) ),
```
Comment (eliorivero) [inline modules/widgets/google-translate.php]: On one hand, this is incompatible with what `google.translate.TranslateElement` accepts for the `layout` property, it accepts a number, not a string.
Logging in console:
`google.translate.TranslateElement.InlineLayout.VERTICAL` throws `0`
`google.translate.TranslateElement.InlineLayout.HORIZONTAL` throws `1`
`google.translate.TranslateElement.InlineLayout.SIMPLE` throws `2`
So this filter should accept a number and validate that number. Otherwise a method should be devised in JS to parse the route received as string and resolve it in the `google` object to get the right value.

However, this is very cumbersome for users. I'd rather have a `<select>` controls that user can pull to choose the desired layout.

Comment (jeherve) [reply modules/widgets/google-translate.php]: That makes sense. I don't know that we need a UI for this though; we don't really receive requests for that option.

I updated the PR to validate the filter and only accept integers between 0 and 2. If anything else, we fallback to the default.
