### PR TITLE
Dynamically embed gists on posts using jsonp calls.

### LINKED ISSUE #2839: Gist oEmbed breaks when posts are loaded dynamically (e.g. in o2)
When post content is loaded dynamically (e.g. in o2 or in infinite scroll), the gist will fail to load because #131 (#96) references a script that does `document.write()`. The o2 plugin specifically [catches this and prints an error](https://github.com/Automattic/o2/blob/83e9833d3d1accfc4c63ac09b9a27007918bcfa4/js/app/main.js#L563-L578):

> document.write called after page load and ignored

The solution is simple, however. Instead of embedding the JS which does `document.write()`: the oEmbed should just embed a container element like:

```html
<div class="gist-oembed" data-id="9d1c1b9d782fa8d86df3"><!-- actual gist contents could get put here for SEO --></div>
```

And then Jetpack can watch for new `gist-oembed` elements added (via `post-load` event) and then it can load the Gist's contents via the JSONP callback instead.

So instead of embedding a script linking to:

https://gist.github.com/9d1c1b9d782fa8d86df3.js

Instead embed as script linking to:

https://gist.github.com/9d1c1b9d782fa8d86df3.json?callback=jetpack_oembed_9d1c1b9d782fa8d86df3

And then inject the HTML into the container `div` via this `jetpack_oembed_9d1c1b9d782fa8d86df3()` function (or the like).

### PR DESCRIPTION
**Pull request by osiux**
What this does:

 * Loads stylesheet only once
 * Still works with `file` attribute on shortcode
 * Replaces the entire div generated by jetpack with the gist html (or maybe should put the code inside the div?)

Fixes #2839

### CODE REVIEW

**Comment by dereksmart** [comment]
I like this.  

However when testing, the gist wasn't being embedded into the wp-admin editor.  Can you look into that?

**Comment by osiux** [comment]
You are right, this is interesting. The function [wp_ajax_parse_embed](https://github.com/WordPress/WordPress/blob/677762f6cfb4aea3394bd9bf13072088245c5bcc/wp-admin/includes/ajax-actions.php#L2857-L2941) is the one used to preview the embeds on editor.

You can [see](https://github.com/WordPress/WordPress/blob/677762f6cfb4aea3394bd9bf13072088245c5bcc/wp-admin/includes/ajax-actions.php#L2907-L2925) that when the embed is audio or video, some styles and scripts are added on the response, I assume those are needed for the preview of those shortcodes to work. There's no filter we can hook there to add our script to display the gist.

I'm looking for an event or something (maybe in [mce-view.js](https://github.com/WordPress/WordPress/blob/677762f6cfb4aea3394bd9bf13072088245c5bcc/wp-includes/js/mce-view.js)?) I can hook on the editor to render the gist html code. Any idea?

File: modules/shortcodes/js/gist.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+                    gistStylesheetLoaded = true;
+                }
+            });
+        });
+    };
+
+    $(document).ready(gistEmbed);
+    $('body').on('post-load', gistEmbed);
+})(jQuery);
```
Comment (zinigor) [inline modules/shortcodes/js/gist.js]: Looks nice, but needs a little work to make it compliant with the WP JS standards: https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/
Can you please go one step further? Thanks :)

**Comment by osiux** [comment]
@zinigor I think it's done :)

I'm still looking at the issue with the editor preview, but have been a bit busy with other things.

**Comment by osiux** [comment]
@dereksmart seems like with the new commit the visual editor preview works. It's a little hackish, I think, but similar to what it [currently does with audio and video](https://github.com/WordPress/WordPress/blob/677762f6cfb4aea3394bd9bf13072088245c5bcc/wp-admin/includes/ajax-actions.php#L2920-L2922) previews.

**Comment by zinigor** [comment]
This works fine, but in order to avoid using `wp_print_script` let's use the JS from github directly? I have prepared a small patch that achieves that. Can you please try it on and commit if it works for you?
https://gist.github.com/zinigor/48597632a5b53e63dea0

**Comment by osiux** [comment]
@zinigor great idea! Works flawlesly! Definitelly a better solution. Commited!
