### PR TITLE
Admin Page: Hide pro set up button for searchable modules

### LINKED ISSUE #8525: Widget Visibility Module shows "setup" button, when it should be "activate"
#### Steps to reproduce the issue

I haven't been able to consistently reproduce the issue to track exactly what is causing it, but going to wp-admin > Jetpack > Settings and searching for the "Widget Visibility" module are the steps to produce it.  

#### What I expected

screen shot 2018-01-08 at 2 19 14 pm

#### What happened instead

image

VIP Ticket for reference: #72898-z

### LINKED ISSUE #9113: Contact Form: "Set up" button in settings leads to strange message/dead end
#### Steps to reproduce the issue

1. Start on a Jetpack site with the Contact Form module activated.
2. Go to Jetpack > Settings.
3. Search for `contact form` to find the contact form settings.
4. Note that the only actions to take here are "Learn more" (under the i popover, to go to the support doc) and "Set up." Click the "Set up" button.

#### What I expected

I expected this button to set up a contact form for me.

#### What happened instead

I was taken to https://wordpress.com/plugins/setup/{SITE_ADDRESS}?only=contact-form which showed the message "Setting up your Premium Plan" and then auto-advanced to the message "Nothing to do here..."

The flow ended on that screen with no clear path forward.

#### Screencast

jpcontactformsetup

### PR DESCRIPTION
**Pull request by oskosk**
Fixes #8525 
Fixes #9113

#### Changes proposed in this Pull Request:

* Makes the Set Up show only for paid features related to plugins.

#### Testing instructions:

* Go to wp-admin > Jetpack > Settings,
*  Search for the "Widget Visibility" . Expect to see no setup button.

**Searchable module active Before**

When Akismet is active: 
image

When Akismet is deactivated:

image

Note that the ACTIVE label is intended for paid features depending on plugin configuration

**Searchable module active After**

image

### CODE REVIEW

File: _inc/client/pro-status/index.jsx [hunk 1]
```diff
@@ -144,10 +144,14 @@ class ProStatus extends React.Component {
 
 	render() {
 		const sitePlan = this.props.sitePlan(),
-			vpData = this.props.getVaultPressData(),
-			pluginSlug = 'scan' === this.props.proFeature || 'backups' === this.props.proFeature || 'vaultpress' === this.props.proFeature
-				? 'vaultpress/vaultpress.php'
-				: 'akismet/akismet.php';
+			vpData = this.props.getVaultPressData();
+		let pluginSlug = '';
+		if ( 'scan' === this.props.proFeature || 'backups' === this.props.proFeature || 'vaultpress' === this.props.proFeature ) {
```
Comment (eliorivero) [inline _inc/client/pro-status/index.jsx]: I think this needs`rewind` here?

File: _inc/client/pro-status/index.jsx [hunk 2]
```diff
@@ -212,7 +216,7 @@ class ProStatus extends React.Component {
 				}
 			}
 
-			if ( sitePlan.product_slug ) {
+			if ( sitePlan.product_slug && pluginSlug ) {
 				if ( ! hasFree ) {
```
Comment (eliorivero) [inline _inc/client/pro-status/index.jsx]: this line can be combined with the previous if

Comment (oskosk) [reply _inc/client/pro-status/index.jsx]: Addressed in 7def6fde6f0bce1195beac705db37fbead11ce77

File: _inc/client/pro-status/index.jsx (hunk 1 above)
Comment (oskosk) [reply _inc/client/pro-status/index.jsx]: If `rewind` does not depend on the plugin, then its `pluginSlug` should be empty and this feature (`rewind`) is caught by https://github.com/Automattic/jetpack/blob/f4382811a3e4dcd3f6845e5db4aea8454191c5df/_inc/client/pro-status/index.jsx#L166

File: _inc/client/pro-status/index.jsx [hunk 3]
```diff
@@ -211,15 +215,13 @@ class ProStatus extends React.Component {
...
 			}
-
-			if ( sitePlan.product_slug ) {
-				if ( ! hasFree ) {
-					if ( active && installed ) {
-						return this.getProActions( 'active' );
-					}
-
-					return this.getSetUpButton( feature );
+			// Show set up or active status only for paid features that depend on a plugin, and only under a pid plan
```
Comment (eliorivero) [inline _inc/client/pro-status/index.jsx]: `under a pid plan` => `under a paid plan`

**Comment by bsessions85** [comment]
I tested this and it looks good to me!

**Comment by rebeccahum** [comment]
Tested this on VIP Go and it works.

**Comment by dereksmart** [comment]
Merge conflicts now :(

**Comment by oskosk** [comment]
@dereksmart I'm  on it...
