### PR TITLE
Sync: avoid conflicts with other plugins using the filter

### LINKED ISSUE #39654: Fatal error for plugin_action_links_ when using strict strong typing
### Impacted plugin

Jetpack

### Quick summary

A fatal error occurs when the Tokenpay Payment Gateway plugin is used alongside the Jetpack plugin, specifically due to using a null parameter instead of an array in the plugin_action_links_ hook.

### Steps to reproduce

1. Install and activate the Tokenpay Payment Gateway plugin.
2. Install and activate the Jetpack plugin.
3. Navigate to the plugins overview page in the WordPress admin dashboard.
[tokenpay-payment-gateway.zip](https://github.com/user-attachments/files/17274788/tokenpay-payment-gateway.zip)

### A clear and concise description of what you expected to happen.

The action links for the Tokenpay Payment Gateway plugin should display without any errors.

### What actually happened

A fatal error is thrown, preventing the admin dashboard from loading properly.

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Yes, the issue can be temporarily resolved by removing strict typing from the affected code.

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #39654

## Proposed changes:

As mentioned in the original issue:

> I did notice two locations where Jetpack code is calling the filter with a null value rather than the documented array for the $plugin_data parameter.
-- https://github.com/Automattic/jetpack/issues/39654#issuecomment-2397134979

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* N/A

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

I wasn't able to reproduce the issue on my end, so it makes this hard to test. It would be worth installing WooCommerce as well as the Tokenpay Payment Gateway plugin, and checking if the plugin action links from WooCommerce are still there and correct.

### CODE REVIEW

**Review by coder-karen — DISMISSED** [review]
I also couldn't replicate the issue, but testing this PR with all plugins involved, all plugin action links continued to work.

**Review by darssen — DISMISSED** [review]
I tested as well without luck reproducing.

The result from the add_filter in the TokenPay plugin using `onepix_tokenpay()->get_option( 'plugin_file' )`  was `"tokenpay-payment-gateway/index.php"` while the sync code the plugin_file part was  `"tokenpay-payment-gateway/tokenpay-payment-gateway.php"` when applying filters.

In any case changes make sense since and I think it is safe to approve

File: projects/packages/sync/src/modules/class-callables.php [hunk 1]
```diff
@@ -396,13 +396,13 @@ public function set_plugin_action_links() {
 				'edit'       => '',
 			);
 			/** This filter is documented in src/wp-admin/includes/class-wp-plugins-list-table.php */
-			$action_links = apply_filters( 'plugin_action_links', $action_links, $plugin_file, null, 'all' );
+			$action_links = apply_filters( 'plugin_action_links', $action_links, $plugin_file, array(), 'all' );
```
Comment (anomiex) [inline projects/packages/sync/src/modules/class-callables.php]: Would it be worth trying to provide the actual plugin data, in case something tries to use it?

Looks like we could do that pretty easily by changing the code above from
```php
$plugins = array_keys( Functions::get_plugins() );
foreach ( $plugins as $plugin_file ) {
```
to
```php
$plugins = Functions::get_plugins();
foreach ( $plugins as $plugin_file => $plugin_data ) {
```

Comment (jeherve) [reply projects/packages/sync/src/modules/class-callables.php]: That's a good point. Done in f83ba87c19fa878530aee2ce3bb5f6c158c16abb

File: projects/packages/sync/src/modules/class-callables.php [hunk 2]
```diff
@@ -384,7 +384,7 @@ public function set_plugin_action_links() {
 			return;
 		}
 		$plugins = array_keys( Functions::get_plugins() );
```
Comment (anomiex) [inline projects/packages/sync/src/modules/class-callables.php]: Without this it won't work right. 😉
```suggestion
		$plugins = Functions::get_plugins();
```

**Review by anomiex — COMMENTED** [review]
Looks reasonable to me to fix the reported bug. I don't know how to test that Sync is still syncing correctly though.
