### PR TITLE
VideoPress: Add nudge to Video block

### LINKED ISSUE #14733: VideoPress: Fix the Upgrade Flow via the Video Block
## Steps to reproduce the issue

1. Go to WordPress.com and a free site
2. Add a Video block to the editor
3. Try and upload an MP4 file

screen-shot-2020-02-17-at-22 31 16

#### What I expected
See a banner notifying me that I should upgrade to a premium plan so that I can upload videos and get our VideoPress player:

videopress-upgrade-promo

#### What happened instead

I get the error above.

Related:
https://github.com/Automattic/wp-calypso/issues/33013
https://github.com/Automattic/wp-calypso/issues/27772
https://github.com/Automattic/jetpack/issues/14392

### PR DESCRIPTION
**Pull request by apeatling**
Fixes #14733

This will add an upgrade banner nudge to the core video block when using Jetpack on WordPress.com with a free plan.

video-upgrade-1

#### Changes proposed in this Pull Request:
* When using a free plan on a WordPress.com site you will see the above banner when adding the core video block. The buttons will also be disabled. This makes it clear that you cannot upload a video file until you upgrade to a Premium plan.

#### Testing instructions:

* Apply D39101-code to your sandbox
* Insert the video block into a post or page on a WordPress.com site that does not have a paid plan (and thus no VideoPress access)
* Confirm that you see an upgrade banner (wording will be specific to WordPress.com)
* Confirm that the upgrade banner upgrade button takes you to the payment flow for a premium plan
* Confirm that you are not able to upload a video via the dropzone.
* Confirm that the "Upload File" and "Media Library" buttons are disabled.
* Confirm you can still use the URL option and embed a video via an external URL
* Confirm other paid blocks still show the correct upgrade banner with their original wording.
* Confirm that when on a WordPress.com site with a paid plan, the original video block placeholder is restored, there is no upgrade banner, and you can upload and embed videos with VideoPress.

#### Proposed changelog entry for your changes:
* No changes needed.

**TODO:**

- [x] Determine the correct plan check, test this on WordPress.com
- [x] Get upgrade button visible and linking to correct place on WordPress.com
- [x] Disable upload buttons when banner is present
- [x] Update the nudge component to accept a custom main title
- [x] Code review to determine the correct place to load this filter

### CODE REVIEW

File: extensions/shared/videopress-plan-check.js [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+import { __ } from '@wordpress/i18n';
+
+/**
+ * Internal dependencies
+ */
+import UpgradeNudge from './components/upgrade-nudge';
+
+const replaceMediaPlaceholder = createHigherOrderComponent(
+	OriginalPlaceholder => props => {
+		if ( 'wp-block-video' !== props.className ) {
```
Comment (creativecoder) [inline extensions/shared/videopress-plan-check.js]: I think there might be a `name` prop for the block name (`core/video`)? (but I can't remember for sure). If so, that might be more stable than checking the the className.

**Review by creativecoder — COMMENTED** [review]
I haven't tried to test this, but looking over the code so far, this is how I imagined we might be able to add this nudge.

File: extensions/shared/videopress-plan-check.js (hunk 1 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.js]: With this filter, I don't think there is. I had a look and couldn't see that prop available. There might be another way though.

**Comment by apeatling** [comment]
This PR is now ready for review, here is the current visual state:

Screen Shot 2020-02-20 at 2 32 59 PM

I have currently commented out the simpleSite check, so that it can easily be tested locally and on a WordPress.com sandbox via a sync. I can re-enable this check if preferred.

I will update the testing instructions shortly.

File: extensions/editor.js [hunk 2]
```diff
@@ -5,6 +5,7 @@ import './shared/public-path';
 import './shared/block-category';
 import './shared/plan-upgrade-notification';
 import './shared/stripe-connection-notification';
+import './shared/videopress-plan-check';
```
Comment (apeatling) [inline extensions/editor.js]: Is it appropriate to load this check here? Another option might be to load these changes inside of the VideoPress block code, since this is already checking for a core video block and modifying it.

File: extensions/shared/components/upgrade-nudge/index.jsx [hunk 3]
```diff
@@ -19,7 +19,26 @@ import './store';
 
 import './style.scss';
 
-export const UpgradeNudge = ( { planName, trackEvent, upgradeUrl } ) => (
+const getTitle = ( customTitle, planName ) => {
```
Comment (apeatling) [inline extensions/shared/components/upgrade-nudge/index.jsx]: I'm interested in feedback on setting a custom title. I didn't want to mess with the plan name setting since this is constructed separately. Is there a better way to handle a custom title?

File: extensions/shared/videopress-plan-check.js [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+import { createHigherOrderComponent } from '@wordpress/compose';
+import { __, _x } from '@wordpress/i18n';
+
+/**
+ * Internal dependencies
+ */
+import './videopress-plan-check.scss';
+import UpgradeNudge from './components/upgrade-nudge';
+import getJetpackExtensionAvailability from './get-jetpack-extension-availability';
+//import isSimpleSite from './site-type-utils';
```
Comment (apeatling) [inline extensions/shared/videopress-plan-check.js]: I will re-enable this check once this is ready to merge. If it's preferred to do this now, I can also do that too.

File: extensions/shared/videopress-plan-check.scss [hunk 5]
```diff
@@ -0,0 +1,13 @@
+.no-videopress-media-placeholder {
```
Comment (apeatling) [inline extensions/shared/videopress-plan-check.scss]: Same question for this custom CSS, would this be better in the VideoPress block and an editor.scss file?

File: extensions/shared/videopress-plan-check.js (hunk 1 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.js]: The only other possible way I can see is to piggyback off the existing VideoPress modification block.

**Comment by scruffian** [comment]
I think there's a better way to do this without building something custom. We already have a `wrapPaidBlock` component that adds the nudge:

https://github.com/Automattic/jetpack/blob/a998fb84c69fa83c79c9ae4302d3d179c9813e3a/extensions/shared/register-jetpack-block.js#L50

You can look at how it's done in Calendly and OpenTable as an example. HTH

**Comment by apeatling** [comment]
@scruffian I don't think it's possible with this block because it's a core block. It'd definitely simple with a custom built block.

**Comment by scruffian** [comment]
Ah ok 👍

**Comment by apeatling** [comment]
Having said that, I am totally open writing it a different way if there's something easier! This was kind of a gnarly task but it was a great learning opportunity for me to understand internals better.

File: extensions/shared/videopress-plan-check.js [hunk 6]
```diff
@@ -0,0 +1,66 @@
...
+
+const replaceMediaPlaceholder = createHigherOrderComponent(
+	OriginalPlaceholder => props => {
+		const { available } = getJetpackExtensionAvailability( 'videopress' );
+
+		if (
+			//! isSimpleSite || // Only show nudge on dotcom simple sites.
+			'wp-block-video' !== props.className || // Only show nudge on core video blocks.
```
Comment (glendaviesnz) [inline extensions/shared/videopress-plan-check.js]: This breaks if the user adds a custom class to the block (got caught by this on google calendar block) as className prop becomes a space separated string of all the class names in this instance.

Screen Shot 2020-02-21 at 12 38 32 PM

Screen Shot 2020-02-21 at 12 38 41 PM

It is possible to get just the base class name like this https://github.com/Automattic/jetpack/pull/13999/files#diff-79dff83b7f1000a7b0f61a8752aa35cfR113

File: extensions/shared/videopress-plan-check.js [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+				/>
+			</>
+		);
+	},
+	'replaceMediaPlaceholder'
+);
+
+addFilter(
+	'editor.MediaPlaceholder',
+	'apeatling/replace-media-placeholder',
```
Comment (glendaviesnz) [inline extensions/shared/videopress-plan-check.js]: temporary name space left in by mistake?

File: extensions/shared/videopress-plan-check.js (hunk 6 above)
Comment (glendaviesnz) [reply extensions/shared/videopress-plan-check.js]: ... just saw comment above that `name` prop is not available, so the suggested call to get the default class name won't work as this requries `name` 🤦

File: extensions/shared/videopress-plan-check.js (hunk 7 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.js]: Oops, yes, thanks. Will update.

File: extensions/shared/components/upgrade-nudge/index.jsx (hunk 3 above)
Comment (glendaviesnz) [reply extensions/shared/components/upgrade-nudge/index.jsx]: I am thinking this may cause the translators some challenges to keep grammar structure correct in all languages without knowing all the options that customTitle could be (but I am no translations expert so could be wrong) - but haven't managed to think of an alternative yet - will keep thinking about it.

Comment (glendaviesnz) [reply extensions/shared/components/upgrade-nudge/index.jsx]: the only other option I could think of was to pass two title alternatives into the nudge component in the title prop, eg.

```javascript
				<UpgradeNudge
					plan="value_bundle"
					blockName="core/video"
					title={ { knownPlan: __(
								'Upgrade to %(planName)s to upload videos.',
								'jetpack'
							),
							unknownPlan: __(
								'Upgrade to a paid plan to upload videos.',
								'jetpack'
							),
						} 
					}
					subtitle={ __(
						'Upload unlimited videos to your website and \
						display them using a fast, unbranded, \
						customizable player.',
						'jetpack'
					) }
				/>
```
The the code in the nudge component is simplified to:

```javascript
const getTitle = ( customTitle, planName ) => {
	if ( customTitle ) {
		return planName ? sprintf( customTitle.knownPlan, { planName } ) : customTitle.unknownPlan;
	}

	return planName
		? sprintf( __( 'Upgrade to %(planName)s to use this block on your site.', 'jetpack' ), {
				planName,
				title,
		  } )
		:  __( 'Upgrade to a paid plan to use this block on your site.', 'jetpack' );
};
```

File: extensions/shared/videopress-plan-check.js (hunk 6 above)
Comment (glendaviesnz) [reply extensions/shared/videopress-plan-check.js]: Had a quick look and there don't seem to be many other options with the props available, but you could do:

```
props.className.indexOf( 'wp-block-video' ) !== -1;
```
or
```
props.accept === 'video/*'
```

**Comment by pablinos** [comment]
> @scruffian I don't think it's possible with this block because it's a core block so it needs to be done using filters. It'd definitely be simple with a custom built block.

Could you add something to the `blocks.registerBlockType` filter and wrap the `edit` component in `wrapPaidBlock`? It would be great if they could all use the same mechanism

**Comment by apeatling** [comment]
> Could you add something to the blocks.registerBlockType filter and wrap the edit component in wrapPaidBlock? It would be great if they could all use the same mechanism

Good idea @pablinos, let me try this. If it works it would be very straightforward.

File: extensions/shared/videopress-plan-check.js (hunk 6 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.js]: Using @pablinos's tip below and the `blocks.registerBlockType` filter, I can get the block name prop, and then use that to limit the `editor.MediaPlaceholder` filter. Refactor coming up. 👍

File: extensions/shared/videopress-plan-check.scss (hunk 5 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.scss]: In the process of refactoring this so no longer relevant.

File: extensions/editor.js (hunk 2 above)
Comment (apeatling) [reply extensions/editor.js]: This is resolved with an upcoming refactor.

File: extensions/shared/components/upgrade-nudge/index.jsx (hunk 3 above)
Comment (apeatling) [reply extensions/shared/components/upgrade-nudge/index.jsx]: This works great, and I agree makes a lot more sense to read, and for translators. Thanks!

**Comment by apeatling** [comment]
Refactor now in place to use `wrapPaidBlock`, thanks @scruffian and @pablinos for the tips!

File: extensions/shared/videopress-plan-check.js (hunk 6 above)
Comment (apeatling) [reply extensions/shared/videopress-plan-check.js]: Looking at this again now the refactor is in, I still need to check inside the filter function despite it only being applied after a block name check in the `blocks.registerBlockType` filter. The filter is still broadly applied to every block.

File: extensions/blocks/videopress/editor.js [hunk 8]
```diff
@@ -22,12 +49,19 @@ const addVideoPressSupport = ( settings, name ) => {
 	}
 
 	const { attributes, deprecated, edit, save, supports, transforms } = settings;
-
 	const { available, unavailableReason } = getJetpackExtensionAvailability( 'videopress' );
 
+	// Check if VideoPress is unavailable and filter the mediaplaceholder to limit options
+	if ( [ 'missing_plan', 'unknown' ].includes( unavailableReason ) ) {
+		addFilter( 'editor.MediaPlaceholder', 'jetpack/videopress', videoPressNoPlanMediaPlaceholder );
```
Comment (pablinos) [inline extensions/blocks/videopress/editor.js]: I'm not sure if this would be the right place, but we should also add the filter to include the extra CSS classes when the nudge is displayed. From what I can tell, this is so that the borders display properly and to override the `pointer-events: none` setting applied to blocks with warnings.

https://github.com/Automattic/jetpack/blob/master/extensions/shared/register-jetpack-block.js#L54

Comment (scruffian) [reply extensions/blocks/videopress/editor.js]: I tried to find a way to do this within `wrapPaidPlan` but it caused a loop because every time we added the filter the component was rerendering because of the way the filter is applied.

Comment (scruffian) [reply extensions/blocks/videopress/editor.js]: I pushed a commit to add this.

Comment (apeatling) [reply extensions/blocks/videopress/editor.js]: @scruffian Should I add in the filter manually in that case?

**Comment by apeatling** [comment]
This is the current state, and I think ready for review on WordPress.com. Until core patch https://github.com/WordPress/gutenberg/pull/20444 merges we cannot selectively disable buttons, so they are removed instead:

Screen Shot 2020-02-25 at 10 18 49 AM

Once the core patch merges I can open another PR to disable the buttons instead as per the original screenshot in this PR. /cc @lessbloat

**Comment by davemart-in** [comment]
Let's go ahead and merge, then update once the core patch ships. Thanks!

File: extensions/blocks/videopress/editor.js [hunk 9]
```diff
@@ -22,12 +51,24 @@ const addVideoPressSupport = ( settings, name ) => {
...
+			withHasWarningIsInteractiveClassNames( `core/video` )
+		);
+	}
+
 	// We customize the video block even if VideoPress it not available so we can support videos that were uploaded to
 	// VideoPress if it was available in the past (i.e. before a plan downgrade).
-	if ( available || [ 'missing_plan', 'missing_module' ].includes( unavailableReason ) ) {
+	if (
+		available ||
+		[ 'missing_plan', 'missing_module', 'unknown' ].includes( unavailableReason )
```
Comment (glendaviesnz) [inline extensions/blocks/videopress/editor.js]: IE11 doesn't support the array .includes method - not sure if we have a polyfill for that not.

File: extensions/blocks/videopress/editor.js [hunk 10]
```diff
@@ -14,6 +16,33 @@ import withVideoPressEdit from './edit';
 import withVideoPressSave from './save';
 import getJetpackExtensionAvailability from '../../shared/get-jetpack-extension-availability';
 import deprecatedV1 from './deprecated/v1';
+import wrapPaidBlock from '../../shared/wrap-paid-block';
+import isSimpleSite from '../../shared/site-type-utils';
```
Comment (glendaviesnz) [inline extensions/blocks/videopress/editor.js]: this isn't a default export so should be `import { isSimpleSite } from '../../shared/site-type-utils';

File: extensions/blocks/videopress/editor.js [hunk 11]
```diff
@@ -22,12 +51,24 @@ const addVideoPressSupport = ( settings, name ) => {
 	}
 
 	const { attributes, deprecated, edit, save, supports, transforms } = settings;
-
 	const { available, unavailableReason } = getJetpackExtensionAvailability( 'videopress' );
 
+	// Check if VideoPress is unavailable and filter the mediaplaceholder to limit options
+	if ( isSimpleSite && [ 'missing_plan', 'unknown' ].includes( unavailableReason ) ) {
```
Comment (glendaviesnz) [inline extensions/blocks/videopress/editor.js]: `isSimpleSite` is a method so needs to be invoked here with `isSimpleSite()`

File: extensions/blocks/videopress/editor.js (hunk 9 above)
Comment (glendaviesnz) [reply extensions/blocks/videopress/editor.js]: but i see that there are lots of uses of .includes in jetpack codebase already so I assume it isn't a problem 😃

**Comment by glendaviesnz** [comment]
This looks much better with reusing the wrapPaidBlock component 🎉 

When I fixed the two issues with the isSimpleSite import this worked as expected on my simple sandboxed site, except the dragging and dropping of a video onto the block, which caused a second block to be added in which the dropped video uploaded:

video-drop

**Comment by pablinos** [comment]
Until the core patch is in, could we insert the disabled buttons as children of the placeholder, and then change the flex order to get them rendered first?

File: extensions/blocks/videopress/editor.js (hunk 10 above)
Comment (apeatling) [reply extensions/blocks/videopress/editor.js]: Done, thanks!

File: extensions/blocks/videopress/editor.js (hunk 11 above)
Comment (apeatling) [reply extensions/blocks/videopress/editor.js]: 🤦‍♂ Thanks :)

**Comment by apeatling** [comment]
> except the dragging and dropping of a video onto the block, which caused a second block to be added in which the dropped video uploaded:

@glendaviesnz Can you confirm this worked on a simple site on a free plan? The dropzone is disabled on the block, which I think is why it auto created a new block.

File: extensions/blocks/videopress/editor.js (hunk 9 above)
Comment (apeatling) [reply extensions/blocks/videopress/editor.js]: Yes, it was actually already being used in this file before I edited it, so I'm assuming it's okay. :)

**Comment by apeatling** [comment]
@pablinos Adding the dummy buttons as child components worked great! Smart idea, thanks for that.

**Comment by apeatling** [comment]
All changes made, so this one is ready for a final review.

**Comment by apeatling** [comment]
Rebased, patch is updated and rebuilt. This should be good to test on your sandbox now.

**Review by glendaviesnz — DISMISSED** [review]
This works as expected for me with the nudge showing on a simple site and upgrade button redirecting correctly and other buttons disabled.

On a paid plan the upgrade nudge does not display and block operates as normal

**Comment by glendaviesnz** [comment]
> @glendaviesnz Can you confirm the video file upload worked (and completed) on a simple site on a free plan?

It doesn't the upload, but this might be just might sandbox site as video upload has never worked for me on sandbox. 

If it is important to stop the new block being created when video is dropped I think this should be done is a separate PR - it is a bit of an edge case, and with the nudge clearly visible now the user at least has a clear indication of what the issue is.

**Comment by scruffian** [comment]
This throws an error for the Simple Payments block. I have added a commit to fix it.

File: extensions/blocks/videopress/editor.scss [hunk 12]
```diff
@@ -0,0 +1,20 @@
+.no-videopress-media-placeholder {
+	.components-placeholder__fieldset {
+		flex-direction: row-reverse;
+		align-items: flex-start;
+		justify-content: flex-end;
+
+		button {
+			display: none;
```
Comment (scruffian) [inline extensions/blocks/videopress/editor.scss]: It would be nice if we could prevent these from showing, rather than hiding them, but I couldn't find a way...

Comment (apeatling) [reply extensions/blocks/videopress/editor.scss]: Yes, not much can be done here without core support for stopping them from rendering

**Comment by apeatling** [comment]
@Automattic/jetpack-crew This one is ready for a final review whenever you get a chance. Thanks!

**Comment by gwwar** [comment]
Jetpack PRs usually need a ✅ from the team plus a quick check over from Crew. Besides the conflict on the branch @glendaviesnz did things look good to go here https://github.com/Automattic/jetpack/pull/14735#pullrequestreview-368235383 ?

**Review by scruffian — DISMISSED** [review]
LGTM

**Review by jeherve — CHANGES_REQUESTED** [review]
I am afraid this now needs a rebase.

**Comment by apeatling** [comment]
Rebased ✅

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍

**Comment by lancewillett** [comment]
@apeatling What do you think about pushing live, and asking internally for further testing any edge cases?

**Review by davemart-in — APPROVED** [review]
I agree. Let's go ahead and push this live.

**Comment by scruffian** [comment]
r204097-wpcom
