### PR TITLE
Forms: Fix block previews

### LINKED ISSUE #29151: JP Forms: Inspector Sidebar -> Style variations - Preview not working
As mentioned here: https://github.com/Automattic/jetpack/pull/28212#issuecomment-1385732019

The "previews" in the inspector sidebar when hovering the styling options are sometimes not showing yet:

image

And if they do, it's not something useful for the user... it shows the placeholder.  Anything we can do here?

image

### PR DESCRIPTION
**Pull request by jcheringer**
Fixes #29151

## Proposed changes:

* Updates the `form-style.js` to run in the context of the Form block and allow the previews to be stylized correctly.
* It also removes the code that handles the blur effect since we're trying to improve the general form style on https://github.com/Automattic/jetpack/pull/29140 

image

image

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:

* Check if the Form block previews are working well in the Block Library and in the style variation buttons

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import './form-styles.js';
+import { useCallback } from '@wordpress/element';
+
+export const withStyleVariables = WrappedComponent => props => {
+	const EDITOR_SELECTOR = '[data-type="jetpack/contact-form"]';
+	/* eslint-disable-next-line no-undef */
+	const generateVariables = useCallback( () => generateStyleVariables( EDITOR_SELECTOR ), [] );
```
Comment (ice9js) [inline projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: Hmm, is there any particular reason why we need `useCallback` here or is it just to make the linter happy? Like, right now I see little difference between this or calling `generateStyleVariables( EDITOR_SELECTOR )` directly.

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+
+	return <WrappedComponent style={ generateVariables() } { ...props } />;
```
Comment (ice9js) [inline projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: I'm also wondering if we can optimize this so we're not re-rendering the entire probe on every render 🤔. 
Doing it on every render would certainly pick up on any changes quicker than otherwise but it doesn't guarantee that either.

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/form-styles.js [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+		backgroundColorNode.parentNode.nodeType === window.Node.ELEMENT_NODE
+	) {
+		backgroundColorNode = backgroundColorNode.parentNode;
+		backgroundColor = window.getComputedStyle( backgroundColorNode ).backgroundColor;
+	}
+	return backgroundColor;
+}
+
+/* eslint-disable-next-line no-unused-vars */
+function generateStyleVariables( selector ) {
```
Comment (ice9js) [inline projects/plugins/jetpack/extensions/blocks/contact-form/util/form-styles.js]: Let's do the same here :)

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/form-styles.js [hunk 4]
```diff
@@ -0,0 +1,86 @@
+function getBackgroundColor( backgroundColorNode ) {
```
Comment (ice9js) [inline projects/plugins/jetpack/extensions/blocks/contact-form/util/form-styles.js]: Because this file is not compiled and goes into the global scope as is, I think it might be best to give it a slightly more specific name or make it a property on a global `window.jetpackForms` or something. Or just make it private.

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js (hunk 1 above)
Comment (ice9js) [inline projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: Nit: `window.generateStyleVariables` or `import { generateStyleVariables } from window;` might be a little more clear.

**Review by ice9js — CHANGES_REQUESTED** [review]
Looks good. I'm still thinking if there's a way we can not have it re-render all the probes for all the blocks on every editor render which quickly adds up, but it's still a good improvement so I think we can deal with that separately since it's not as straightforward.

One thing I would like to address though is make the global functions from `form-styles.js` slightly more specific to prevent any accidental conflicts.

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js (hunk 2 above)
Comment (jcheringer) [reply projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: Theoretically, we only need to generate the variables when the Form block is mounted.
Would it make sense to encapsulate the function in a `useEffect(()=> {}, [])`? Or would `useMemo` be the correct react hook for that?

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js (hunk 1 above)
Comment (jcheringer) [reply projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: That would be one of my questions, but I forgot to add it to the PR 😅 
Glad you mention it. I'll remove the `useCallback`

**Review by digitalwaveride — DISMISSED** [review]
image

image


👍  Worked for me as advertised!
Nice João! Thank you!!!

File: projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js (hunk 2 above)
Comment (ice9js) [reply projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js]: Both work, `useMemo` is particularly useful if you're doing an expensive calculation that you might have to run every now and then if something changes, but don't want to run it every time the component renders.  

In this case, `useEffect` would ensure it only runs once.

**Review by ice9js — DISMISSED** [review]
LGTM!

**Comment by sdixon194** [comment]
Tested this with twenty-twenty-three on Firefox and Chrome and it looks like there are some regressions for the styles with this change on the front end of the site:

## Outlined:

**Trunk:** 
outline-trunk

**This branch:**
outline-branch

## Animated:

**Trunk:**
animated-trunk



**This branch:**

animated-branch

The previews worked fine, but I think something is goofing up the front end styles.

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php [hunk 5]
```diff
@@ -401,11 +401,21 @@ private static function enqueue_contact_forms_style_script() {
 
 		wp_enqueue_script(
 			'contact-form-styles',
-			plugins_url( 'js/form-styles.js', __FILE__ ),
+			plugins_url( 'extensions/blocks/contact-form/util/form-styles.js', JETPACK__PLUGIN_FILE ),
```
Comment (jcheringer) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: Hey @Automattic/jetpack-crew, could you help me here?

I've created this file: `projects/plugins/jetpack/extensions/blocks/contact-form/util/form-styles.js`, which I want to use in the blocks and in the Frontend.

I'm trying to enqueue this script here, but it's not working. 
My guess is that it is because `extensions/blocks/contact-form/*` isn't available in production builds. Am I right?
What would be the correct way to share (and enqueue) a script between the blocks (editor) and the Frontend?

Comment (jeherve) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php]: > My guess is that it is because extensions/blocks/contact-form/* isn't available in production builds.

That's correct; the .js files in the `extensions` directory all get transpiled and bundled into the block JS bundle that lives in `_inc/blocks` in production. They do not get shipped separately.

> What would be the correct way to share (and enqueue) a script between the blocks (editor) and the Frontend?

For other blocks, we rely on our existing `load_assets_as_required` method to load a `view.js` file on the frontend. In that file, we can include the `form-styles.js` file.
To load that file in the editor as well, we can import it in the `edit.js` file.

Something like this should help:

```diff
diff --git a/projects/plugins/jetpack/extensions/blocks/contact-form/edit.js b/projects/plugins/jetpack/extensions/blocks/contact-form/edit.js
index b7aaa6bd10..21ba32e147 100644
--- a/projects/plugins/jetpack/extensions/blocks/contact-form/edit.js
+++ b/projects/plugins/jetpack/extensions/blocks/contact-form/edit.js
@@ -33,6 +33,7 @@ import SalesforceLeadFormSettings, {
 } from './components/jetpack-salesforce-lead-form/jetpack-salesforce-lead-form-settings';
 import { withStyleVariables } from './util/with-style-variables';
 import defaultVariations from './variations';
+import './util/form-styles.js';
 
 const ALLOWED_BLOCKS = [
 	...map( childBlocks, block => `jetpack/${ block.name }` ),
diff --git a/projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js b/projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js
index 42862ee099..e9ec4d5644 100644
--- a/projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js
+++ b/projects/plugins/jetpack/extensions/blocks/contact-form/util/with-style-variables.js
@@ -1,5 +1,3 @@
-import './form-styles.js';
-
 export const withStyleVariables = WrappedComponent => props => {
 	const EDITOR_SELECTOR = '[data-type="jetpack/contact-form"]';
 	const { generateStyleVariables } = window.jetpackForms;
diff --git a/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php b/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
index 579dc3bf5e..d72c9eb309 100644
--- a/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
+++ b/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php
@@ -399,14 +399,6 @@ class Grunion_Contact_Form_Plugin {
 	private static function enqueue_contact_forms_style_script() {
 		add_filter( 'js_do_concat', array( __CLASS__, 'disable_forms_style_script_concat' ), 10, 3 );
 
-		wp_enqueue_script(
-			'contact-form-styles',
-			plugins_url( 'extensions/blocks/contact-form/util/form-styles.js', JETPACK__PLUGIN_FILE ),
-			array(),
-			JETPACK__VERSION,
-			true
-		);
-
 		if ( ! is_admin() ) {
 			wp_enqueue_script(
 				'contact-form-styles-frontend',
@@ -537,6 +529,8 @@ class Grunion_Contact_Form_Plugin {
 			);
 		}
 
+		Jetpack_Gutenberg::load_assets_as_required( 'contact-form' );
+
 		return Grunion_Contact_Form::parse( $atts, do_blocks( $content ) );
 	}
 
```

This will work in the Jetpack plugin, but in the package we do not have access to the `Jetpack_Gutenberg` class so we'll have to find a different solution there. We'll most likely need to rely on the `Assets` package to manually register the frontend script. @retrofox can speak to that a bit more. However, in this specific PR and since we're aiming to fix something in this release, I think we could do with the above.

**Comment by jcheringer** [comment]
Nice catch, @sdixon194! 
The issue should be fixed now.

**Review by sdixon194 — APPROVED** [review]
Nice, things work for me, thanks for fixing!

**Review by samiff — APPROVED** [review]

**Comment by samiff** [comment]
cherry-picked to `jetpack/branch-11.9` in 39003dd6f8435546f57fb9867e22dba97f1b1194
