### PR TITLE
Breadcrumbs: Support position itemprop

### LINKED ISSUE #10062: Structured Schema Data error with Breadcrumbs
#### Steps to reproduce the issue

1. Turned ON breadcrumbs in WordPress via Customizing ▸ Theme Options ▸ General Options
2. Tested page, for example, at: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.garnetriver.com%2Ftechnical-staffing%2F
3. Discovered three errors in schema markup for "BreadcrumbList"; two for position and one for item.

#### What I expected
No errors.

#### What happened instead
Google's testing tool reports errors.
A value for the position field is required.
A value for the item field is required.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #10062 

#### Changes proposed in this Pull Request:
* Adds the position itemprop to resolve schema error.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* n/a

#### Testing instructions:
* Jetpack + Edin theme (https://wordpress.com/theme/edin) (or another that supports JP breadcrumbs.
* Via Customizer, Theme Options and activate Breadcrumbs option.
* With various pages (a page by itself, a page that itself is a child to another page), run the URLs through the Google testing tool ( https://search.google.com/structured-data/testing-tool/ )
* Ensure the Breadcrumbs are compliant.

Before:
2020-05-20 at 5 14 PM

After:
2020-05-20 at 5 15 PM

#### Proposed changelog entry for your changes:
* Theme Tools: Add correct schema.org value for Jetpack Breadcrumbs.

### CODE REVIEW

File: modules/theme-tools/site-breadcrumbs.php [hunk 1]
```diff
@@ -21,16 +28,18 @@ function jetpack_breadcrumbs() {
...
 	$breadcrumb = '';
+	$position   = 1;
 
 	if ( $is_post_type_hierarchical ) {
 		$post_id   = get_queried_object_id();
 		$ancestors = array_reverse( get_post_ancestors( $post_id ) );
 		if ( $ancestors ) {
 			foreach ( $ancestors as $ancestor ) {
-				$breadcrumb .= '<span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="' . esc_url( get_permalink( $ancestor ) ) . '" itemprop="item"><span itemprop="name">' . esc_html( get_the_title( $ancestor ) ) . '</span></a></span>';
+				$breadcrumb .= '<span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><meta itemprop="position" content="' . esc_html( $position ) . '"><a href="' . esc_url( get_permalink( $ancestor ) ) . '" itemprop="item"><span itemprop="name">' . esc_html( get_the_title( $ancestor ) ) . '</span></a></span>';
```
Comment (jeherve) [inline modules/theme-tools/site-breadcrumbs.php:38]: Do we want to `esc_attr` all those instead of `esc_html`?

File: modules/theme-tools/site-breadcrumbs.php [hunk 2]
```diff
@@ -42,12 +51,12 @@ function jetpack_breadcrumbs() {
 			$breadcrumb = jetpack_get_term_parents( $current->parent, $taxonomy );
 		}
 
-		$breadcrumb .= '<span class="current-category" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><span itemprop="name">' . esc_html( $current->name ) . '</span></span>';
+		$breadcrumb .= '<span class="current-category" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><meta property="position" content="' . esc_html( $position ) . '"><span itemprop="name">' . esc_html( $current->name ) . '</span></span>';
 	}
 
-	$home = '<span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><a href="' . esc_url( home_url( '/' ) ) . '" class="home-link" itemprop="item" rel="home"><span itemprop="name">' . esc_html__( 'Home', 'jetpack' ) . '</span></a></span>';
+	$home = '<span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><meta itemprop="position" content="' . $position . '"><meta itemprop="position" content="0"><a href="' . esc_url( home_url( '/' ) ) . '" class="home-link" itemprop="item" rel="home"><span itemprop="name">' . esc_html__( 'Home', 'jetpack' ) . '</span></a></span>';
```
Comment (jeherve) [inline modules/theme-tools/site-breadcrumbs.php:57]:
```suggestion
	$home = '<span itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem"><meta itemprop="position" content="' . esc_attr( $position ) . '"><meta itemprop="position" content="0"><a href="' . esc_url( home_url( '/' ) ) . '" class="home-link" itemprop="item" rel="home"><span itemprop="name">' . esc_html__( 'Home', 'jetpack' ) . '</span></a></span>';
```

Comment (kraftbj) [reply modules/theme-tools/site-breadcrumbs.php]: b0ec59a

File: modules/theme-tools/site-breadcrumbs.php (hunk 1 above)
Comment (kraftbj) [reply modules/theme-tools/site-breadcrumbs.php]: Good idea. Blanked a bit. In theory, it probably isn't needed since $position is set all in the code, but better to future-proof it since the spec allows the position field to be text.

b0ec59a

**Comment by mdbitz** [comment]
Tests out good for me.
Screen Shot 2020-05-21 at 3 43 24 PM
