### PR TITLE
Simple Payments Block: Fix email field cut and paste bug

### LINKED ISSUE #11906: Simple Payments block: Cut, copy in fields doesn't work as expected
#### Steps to reproduce
1. Create a Simple Payment block
2. Edit the block
3. Select text in email field
4. Try to copy (unexpect result in clipboard) or cut (no text removed, same unexpected clipboard)

#### What I expected

Cut and copy of selected text work as expected

#### What happened instead

Block HTML is copied:

```html
<!-- wp:jetpack/simple-payments {"currency":"JPY","content":"This mostly works fine","email":"a.payment.address@example.com","paymentId":247,"price":42,"title":"An example Simple Payment"} -->
[simple-payment id="247"]
<!-- /wp:jetpack/simple-payments -->
```

#### Screenshot / Video

screen shot 2018-11-15 at 18 11 26

### LINKED ISSUE #15121: Gutenberg 7.7.1/7.8: Simple Payments Block is removed if pasting into the email field
**Describe the bug**

**To reproduce**
1. Edit a page
2. Add a Simple Payments Block
3. Paste any text into the **Email** field
4. See that the field is removed

**Expected behavior**
The text should be pasted into the field

**Screenshots**
Screen Capture on 2020-03-25 at 16-45-37

**Desktop (please complete the following information):**
 - OS: MacOS V10.15.4 (19E266)
 - Browser Firefox
 - Version 74.0 (64-bit)

**Additional context**
- Started with Gutenberg 7.7.1. Also tested on the 7.8 edge version.
- This issue does not happen on previous versions
- Discovered in WPCOM Calypso, also tested on JN with 7.7.1 and 7.8 Gutenberg versions

### PR DESCRIPTION
**Pull request by glendaviesnz**
Currently the Gutenberg paste handler is bypassed for input fields of type text, but not of type email, which causes the block to be killed and replaced with a paragraph if text is pasted into the email field.

Fixes #15121
Fixes #11906

#### Changes proposed in this Pull Request:

* Temporarily change email field type to `text` to prevent gutenberg paste handler hijacking native copy/cut/past for the field.

#### Testing instructions:

- Add this patch to local jetpack text env, along with latest gutenberg plugin
- Add Simple Payments Block
- Try cutting and pasting in the email field - should work as expected
- Try removing focus from block and then selecting and cut/paste email field again
- Try loading a page with block saved and make sure no console errors

**before:**

before

**after:**

after

#### Proposed changelog entry for your changes:
* No entry needed

### CODE REVIEW

**Comment by scruffian** [comment]
Is this tracked in in the Gutenberg repo? Is that what https://github.com/WordPress/gutenberg/issues/12780 is?

**Review by scruffian — APPROVED** [review]
I can confirm that this fixes the bug. We should merge, but we should also make sure it's tracked in core.

**Review by jeherve — APPROVED** [review]
This should do the trick for now 👍

**Comment by scruffian** [comment]
r205001-wpcom

File: extensions/blocks/simple-payments/edit.js [hunk 1]
```diff
@@ -524,7 +524,8 @@ class SimplePaymentsEdit extends Component {
 						onChange={ this.handleEmailChange }
 						placeholder={ __( 'Email', 'jetpack' ) }
 						required
-						type="email"
+						// TODO: switch this back to type="email" once Gutenberg paste handler ignores inputs of type email
```
Comment (simison) [inline extensions/blocks/simple-payments/edit.js:527]: Age-old PR but came up in my search when looking for something else...

You could use `inputmode="email"` meanwhile to get the right keyboard on mobile. Otherwise, the type doesn't matter that much.

https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/
