### PR TITLE
Jetpack SEO: Ensure we add post type support for custom fields

### LINKED ISSUE #38597: Jetpack Seo: doesn't support custom post types
### Impacted plugin

Jetpack

### Quick summary

Currently if you have a custom post type you can't use Jetpack SEO to save/update the post meta that need to show up the correct SEO data. 

This is due to the meta data now showing up in the editor after you save it. 

### Steps to reproduce

1.Activate jetpack seo. 

2. install a plugin that adds a new custom post type such as https://nl.wordpress.org/plugins/ultimate-faqs/ 
on the new FAQ post type editor. Notice that you are able to see the SEO settings but once you set them and save the document. they are removed. 

### A clear and concise description of what you expected to happen.

The seo setting for the custom post type should be persistant across saves. 

### What actually happened

The settings disapear after you save them as if you haven't saved them at all. 

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

This happends on the latest build of WP and Jetpack. 
Reported in https://wordpress.org/support/topic/seo-title-and-description-are-empty-but-are-active-on-the-page/

### PR DESCRIPTION
**Pull request by coder-karen**
Fixes https://github.com/Automattic/jetpack/issues/38597

## Proposed changes:
* The issue was that it wasn't possible to add an SEO title or description for custom post types (they do not save).
* Adding the Jetpack SEO Meta fields to the Rest API for Custom post types proved challenging, however adding it directly using `add_post_type_support` does work. For this we also need to hook into `rest_api_init` as `init` is too early (before REST API is initialized).
* This also ensures that the 'Hide page from search engines' toggle works as well.
* As an addition, this PR also adds a filter that allows third party modification of the post types that will be processed to add support for custom fields if they do not already support it.
* Regarding the phan baseline addition - phan appears to be incorrectly linking the param name with the filtered param used in the function closure, so I've added it to the phan baseline file. The alternative would have been to create a named function with the logic, which adds unnecessary complexity.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [x] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/38597

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

**Self-hosted / Atomic**

To replicate the issue:

* On trunk, enable Testimonials: `/wp-admin/admin.php?page=jetpack#/writing`.
* Add a new testimonial. Try to add an SEO title and / or description, or using the 'Hide page from search engines' toggle. None will save.
* You can also visit `http://{yoursiteurl.com}/wp-json/wp/v2/jetpack-testimonial/{yourtestimonialid}` after saving, and notice there are no meta fields in the returned JSON.
* You can also visit the testimonial on the front-end and view source. The title / description you added should not be present.

To test the fix:
* Apply this PR.
* Follow the steps above - the fields / settings should save and be retained on page refresh. On visiting the REST API URL, notice the meta fields in the returned values. Also, the title / description you added should be visible in the source for the testimonial.

**Simple**

This feature is not available on Simple sites.

### CODE REVIEW

File: projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo.php [hunk 1]
```diff
@@ -57,6 +57,47 @@ public function init() {
...
+			function ( $post_type ) {
+				return ! post_type_supports( $post_type, 'custom-fields' );
+			}
+		);
+
+		foreach ( $unsupported_post_types as $post_type ) {
+			if ( ! post_type_supports( $post_type, 'custom-fields' ) ) {
+				add_post_type_support( $post_type, 'custom-fields' );
+			}
+		}
```
Comment (bindlegirl) [inline projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo.php]: Could this part be simplified like this:
```suggestion
    foreach ( $post_types as $post_type ) {
        if ( ! post_type_supports( $post_type, 'custom-fields' ) ) {
            add_post_type_support( $post_type, 'custom-fields' );
        }
    }
```

Comment (coder-karen) [reply projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo.php]: Good call.
I think keeping `array_filter` is only beneficial performance-wise with a much larger array of post types. For most cases it should be fine to simplify - though keeping the additional check in, from what I understand, makes negligible difference for performance and memory.
It is simpler to read though without the `array_filter`. I'll make the change - I'll add a separate commit instead of commit your suggestion though as I think the linter will complain about the spaces :)

Comment (bindlegirl) [reply projects/plugins/jetpack/modules/seo-tools/class-jetpack-seo.php]: :old_man_yells_at_spaces_vs_tabs

**Review by bindlegirl — APPROVED** [review]
Tests well. Thank you for fixing this
