### PR TITLE
Fix DIY migration failing to fetch migration key and throwing 403 on page reload

### LINKED ISSUE #96510: Error when returning to the migration DIY flow
### Quick summary

This error was originally reported in p7DVsv-lGw-p2#comment-51714 by @cuemarie.

When we choose the DIY flow and continue later, sometimes it gives an error "Getting the migration key". I didn't find the exact reason, but I recorded a video with the error coming from the API.

https://github.com/user-attachments/assets/b3c90203-5a92-4117-b018-425bdefe6af2

### Steps to reproduce

1. Start a migration choosing the "I'll do it myself" option in the "How do you want to migrate?" step. This can be done following the steps:
  1.1.  Navigate to `/start`.
  1.2. Choose "Import existing content or website" in the goals step.
  1.3. Navigate through the flow, selecting to migrate from a WordPress site, and the "I'll do it myself" option.
3. When you are in the migration instructions screen, close the window.
4. Navigate to `/sites`.
5. Click on the site with the pending migration.
6. Click on "Start your migration".
7. I didn't identify the best way to reproduce it, but as you can see in the video I sent, it worked the first time it was loaded, but it was broken after the refresh with the error 403 - "Sorry, you are not allowed to do that" coming from the API.
### What you expected to happen

Return the key properly.

### What actually happened

An error happened while fetching it from the API.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Imran92**
Fixes https://github.com/Automattic/wp-calypso/issues/96510

## Proposed changes:

* Removed the 'read' check so that users can see the migration key multiple times

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Start a migration choosing the "I'll do it myself" option in the "How do you want to migrate?" step. This can be done following the steps:
  1.1.  Navigate to `/start`.
  1.2. Choose "Import existing content or website" in the goals step.
  1.3. Navigate through the flow, selecting to migrate from a WordPress site, and the "I'll do it myself" option.
3. When you are in the migration instructions screen, check the key by clicking the closed eye icon, and then close the window.
4. Navigate to `/sites`.
5. Click on the site with the pending migration.
6. Click on "Start your migration".
7. In the migration instructions page, make sure you see the error or at least the key does not load for you. Also check the network tab for a call made to `/wpcom-migration-key` API and make sure it has returned 403
8. Now apply this branch to your newly created site using the _Jetpack Beta Tester_ plugin following the instructions in https://github.com/Automattic/jetpack/pull/39377#issuecomment-2346557311. In this case, in the beta tester page, click the "Manage" button on the "_WordPress.com Features_" item, and then apply this branch
9. Now try steps 4-6 again. This time, you shouldn't see any error. You should also be able to see and copy the migration key

### CODE REVIEW

**Comment by donnapep** [comment]
@Imran92 Looks like this one needs a rebase.

**Comment by Imran92** [comment]
@donnapep thanks! I've rebased it

**Comment by donnapep** [comment]
I've tried several times, but I'm not able to reproduce this error. There was a time where I saw it quite frequently, but even without this change, it seems to work for me. I guess I'll leave it for someone else to review to see if they can reproduce the error.

**Comment by Imran92** [comment]
> I've tried several times, but I'm not able to reproduce this error. There was a time where I saw it quite frequently, but even without this change, it seems to work for me. I guess I'll leave it for someone else to review to see if they can reproduce the error.

Sure! Just to recheck - did you unhide the migration key after generating it? This error is generated only if you unhide it at lest once, and then retry loading the page

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php [hunk 1]
```diff
@@ -73,10 +73,6 @@ public function can_access() {
 			return false;
 		}
 
-		if ( 'read' === get_option( $this->key_is_read_option_name, false ) ) {
```
Comment (m1r0) [inline projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php:76]: It looks like the `key_is_read_option_name` option is not used anymore. What do you think of cleaning up the related logic (removing the variable and the update_option call)?

**Review by m1r0 — COMMENTED** [review]
I had no issues reproducing it and the fix works as described! I've left one small suggestion.

File: projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php (hunk 1 above)
Comment (Imran92) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php:76]: I was thinking that it can be useful to keep this data around maybe? 🤔 Just in case we want to bring this logic back or use it elsewhere? Just a thought, no strong opinion

Comment (m1r0) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php:76]: I would prefer it if we could clean it up. I see it as technical debt otherwise. If we ever need it again, it would be very easy to add it back. 🙂 

Maybe a more relatable example would be overengineering a feature with things that may potentially come in handy. It’s a common pitfall and I confess of being guilty there as well. 😄

Comment (Imran92) [reply projects/packages/jetpack-mu-wpcom/src/features/wpcom-endpoints/class-wpcom-rest-api-v2-endpoint-site-migration-wpcom-migration-key.php:76]: Makes sense, removed it here https://github.com/Automattic/jetpack/pull/40270/commits/2871fce298dd39858f6dc7298ca51ec8e973affe

**Review by m1r0 — APPROVED** [review]
Thanks for the cleanup!
