### PR TITLE
AI Assistant: store last prompt to be able to retry the request

### LINKED ISSUE #30558: AI Assistant: Retry doesn't fill the endpoint request properly
When the request fails, the retry action doesn't build properly the endpoint request payload.

### PR DESCRIPTION
**Pull request by retrofox**
This PR exposes a new `retryRequest` helper function from the `useSuggestionsFromOpenAI()` custom hook.
Under the hood, the app stores the last prompt and uses it when it requires to retry the request.

Fixes https://github.com/Automattic/jetpack/issues/30558

## Proposed changes:

* AI Assistant: store last prompt to be able to retry the request

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to Block editor
* Create an AI Assistant block instance
* Generate content
* Expect the request fails by timeout
* Retry button should appear
* Click on the button
* Confirm the app retries the same request as before

https://github.com/Automattic/jetpack/assets/77539/52c305d1-1025-418d-a4cd-35c25569b8ab

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/edit.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ import ShowLittleByLittle from './show-little-by-little';
 import useSuggestionsFromOpenAI from './use-suggestions-from-openai';
 import './editor.scss';
 
-export default function Edit( { attributes, setAttributes, clientId } ) {
+export default function AIAssistantEdit( { attributes, setAttributes, clientId } ) {
```
Comment (oskosk) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/edit.js:21]: Why the rename here?

Comment (retrofox) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/edit.js:21]: Because it's easier to find the component when debugging.

Comment (retrofox) [reply projects/plugins/jetpack/extensions/blocks/ai-assistant/edit.js:21]: Screenshot 2023-05-09 at 17 05 56

Having a custom name for the function helps to search the component in the React dev tool

**Comment by oskosk** [comment]
The changes here are breaking the regular queries I think. With a written query it sends an empty payload

image

**Comment by retrofox** [comment]
> The changes here are breaking the regular queries I think. With a written query it sends an empty payload
> 

correct, p1683667625700839/1683658226.886499-slack-C054LN8RNVA

**Comment by retrofox** [comment]
> The changes here are breaking the regular queries I think. With a written query it sends an empty payload
> 

I think it has been fixed. Thanks for the report.

**Review by nunyvega — APPROVED** [review]
It is now fixed and works as intended

🚢
