### PR TITLE
Prevent attempting to do Gravatar Hovercards for Pingbacks and Trackbacks

### LINKED ISSUE #19052: AMP: Gravatar Hovercards break pingback URLs
When Gravatar Hovercards are enabled, a pingback URL is broken, being replaced with just `#!`:

> Screen Shot 2021-03-05 at 10 48 34

This is the problematic code in question: 

https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/gravatar-hovercards.php#L133-L147

Originally reported at https://github.com/ampproject/amp-wp/issues/5949.

Newspack site post URL on which the issue occurred: https://fitzrovianews.com/2021/02/27/westminster-council-allows-more-outdoor-eating-and-drinking-for-summer/

#### Steps to reproduce the issue

1. Enable AMP plugin in Standard mode.
2. Navigate to a post that has a pingback.
3. Inspect the pingback link.

#### What I expected

Pingback links should link back to the post and not attempt to display a Gravatar Hovercard.

#### What happened instead

Link is broken.

### PR DESCRIPTION
**Pull request by westonruter**
Fixes #19052

#### Changes proposed in this Pull Request:

* Prevent attempting to do Gravatar Hovercards for non-comment comments (e.g. Pingbacks and Trackbacks).

#### Testing instructions:

1. Activate the AMP plugin.
2. Enable Standard template mode or Transitional template mode.
3. Navigate to the AMP version of a post that has comments including pingbacks.
4. Verify the pingback URL goes to the expected location and not `#!`.

#### Proposed changelog entry for your changes:

* Fix AMP compatibility with Gravatar Hovercards for Pingbacks and Trackbacks

### CODE REVIEW

File: projects/plugins/jetpack/modules/gravatar-hovercards.php [hunk 1]
```diff
@@ -135,11 +135,13 @@ function grofiles_gravatars_to_append( $author = null ) {
...
  * @param string $url The comment author's URL.
+ * @param int    $id  The comment ID.
  *
  * @return string The adjusted URL
  */
-function grofiles_amp_comment_author_url( $url ) {
-	if ( class_exists( 'Jetpack_AMP_Support' ) && Jetpack_AMP_Support::is_amp_request() ) {
+function grofiles_amp_comment_author_url( $url, $id ) {
+	if ( 'comment' === get_comment_type( $id ) && class_exists( 'Jetpack_AMP_Support' ) && Jetpack_AMP_Support::is_amp_request() ) {
+		// @todo Disabling the comment author link in this way is not ideal since clicking the link does not cause the lightbox to open in the same way as clicking the gravatar. Likely get_comment_author_url_link should be used instead so that the href attribute can be replaced with an `on` attribute that activates the gallery.
```
Comment (westonruter) [inline projects/plugins/jetpack/modules/gravatar-hovercards.php:144]: This can be addressed in a subsequent PR.

Comment (westonruter) [reply projects/plugins/jetpack/modules/gravatar-hovercards.php:144]: The Gravatar Hovercards implementation in AMP doesn't seem ideal:

1. It doesn't seem like the author link should be overridden at all, since the link in the non-AMP version is not overridden. 
2. The AMP lightbox to show the avatar is huge. It should be much smaller to be appropriate for the size of the avatar.
3. The image in the lightbox shouldn't be linked with other images on the page. There's no need to cycle through them all.

**Review by jeherve — APPROVED** [review]
