### PR TITLE
Fix memory and performance issues of the Widget Visibility module

### LINKED ISSUE #6955: Widget Visibility: memory issues on sites with lots of authors / editors
For large user base (more than 25K), get_user() on line 55 of https://github.com/Automattic/jetpack/blob/master/modules/widget-visibility/widget-conditions.php exhausts the memory, causing a blank screen on the widgets page.

### PR DESCRIPTION
**Pull request by david-binda**
The Widget Visibility feature requires a lot of data in order to provide a very flexible visibility settings for the widgets. For instance, it lists all the pages on a site in a dropdown, which may be an issue for sites with a huge amount of pages, or sites with very large pages, so they don't fit into a single memcache key=>value pair.

In order to preserve the current behaviour (listing all the pages), but optimize the loading times, this patch is introducing a custom direct SQL query for fetching only necessary data of all pages (ID, post_parent, and post_title). The direct SQL query is being cached under plugin's own group, and is taking advantage of the `wp_cache_get_last_changed( 'posts' )` value, which is being flushed whenever a new page is being added, so the listing should be always fresh (the `wp_cache_get_last_changed( 'posts' )` is being used also inside the `get_pages` function call, which the custom implementation is replacing).

The custom `get_pages` function does not trigger the memcache gets for all the pages, as we really don't need whole post objects here.

This changeset also limits the fields returned by the `get_users` call to `ID` and `display_name`, since that's really all we need here.

Fixes #6955

#### Changes proposed in this Pull Request:

* Should not contain any functional changes, but rather optimise the performance of an existing feature, while keeping it working as it is now.

#### Jetpack product discussion
- p7H4VZ-2KJ-p2

#### Does this pull request change what data or activity we track or use?
Nope.

#### Testing instructions:

* Have a site with many users (authors) and/or with many pages.
* Go to '/wp-admin/widgets.php' and make sure you can see all the pages and authors in the dropdowns of the Visibility feature of a widget
* Check what related SQL queries are run, what memcache keys are being fetched (eg.: using the Debug Bar or any other similar plugin), and whether the page load was reasonably fast.

#### Proposed changelog entry for your changes:
* Improves performance of the Widget Visibility module

### CODE REVIEW

File: modules/widget-visibility/widget-conditions.php [hunk 1]
```diff
@@ -126,10 +127,23 @@ public static function widget_admin_setup() {
...
+			'echo'                  => false,
+			'name'                  => 'page_id',
+			'id'                    => '',
+			'class'                 => '',
+			'show_option_none'      => '',
+			'show_option_no_change' => '',
+			'option_none_value'     => '',
+			'value_field'           => 'ID',
+		);
+		$pages_dropdown = walk_page_dropdown_tree( $pages, 0, $dropdown_tree_args );
```
Comment (jeherve) [inline modules/widget-visibility/widget-conditions.php:145]: TIL about `walk_page_dropdown_tree`! 👍

File: modules/widget-visibility/widget-conditions.php [hunk 2]
```diff
@@ -199,6 +213,19 @@ public static function widget_admin_setup() {
...
+		global $wpdb;
+
+		$last_changed = wp_cache_get_last_changed( 'posts' );
+		$cache_key    = "get_pages:$last_changed";
+		$pages        = wp_cache_get( $cache_key, 'widget_conditions' );
+		if ( false === $pages ) {
+			$pages = $wpdb->get_results( "SELECT {$wpdb->posts}.ID, {$wpdb->posts}.post_parent, {$wpdb->posts}.post_title FROM {$wpdb->posts} WHERE {$wpdb->posts}.post_type = 'page' AND {$wpdb->posts}.post_status = 'publish' ORDER BY {$wpdb->posts}.post_date DESC" );
+			wp_cache_set( $cache_key, $pages, 'widget_conditions' );
+		}
+		return $pages;
```
Comment (jeherve) [inline modules/widget-visibility/widget-conditions.php:226]: I wonder if we should add the `get_pages` filter in there, just in case folks are using the filter in their installs today, and would expect that filter to continue to have an impact on the Widget Visibility feature as well?

File: modules/widget-visibility/widget-conditions.php [hunk 3]
```diff
@@ -199,6 +213,19 @@ public static function widget_admin_setup() {
 		wp_localize_script( 'widget-conditions', 'widget_conditions_parent_pages', $all_parents );
 	}
 
+	public static function get_pages() {
```
Comment (jeherve) [inline modules/widget-visibility/widget-conditions.php:216]: What do you think about adding a docblock here, explaining a bit why we chose to move away from Core's `get_pages()`, and maybe linking to https://core.trac.wordpress.org/ticket/51469 for future reference?

**Review by jeherve — COMMENTED** [review]
This tests well for me. I only have some minor questions.

File: modules/widget-visibility/widget-conditions.php (hunk 3 above)
Comment (david-binda) [reply modules/widget-visibility/widget-conditions.php:229]: Great suggestion! Done 👍

File: modules/widget-visibility/widget-conditions.php (hunk 2 above)
Comment (david-binda) [reply modules/widget-visibility/widget-conditions.php:261]: Added. But, there's a concern I have. Since we are not returning full page object (the object we return only contains ID, post_title, and post_paren), and actually is not even a `WP_Post` object, there might be some confusion in the callback, where some of the properties are not present. But, since the `fields` argument can also limit the fields in the object in standard `get_pages` call, it might not really be an issue. Thoughts?

Comment (jeherve) [reply modules/widget-visibility/widget-conditions.php:261]: Ah yes, you're right, I didn't think of that. I see [there are actually quite a few plugins that rely on the filter](https://wpdirectory.net/search/01EN3C8VR33KFVQHKX1CQXG1Y1), so it may be a bit risky for us to play with that filter here if some folks expect a `WP_Post`.

Maybe we skip using the filter for now, and I'll keep in mind if reports come up after the release. What do you think?

Comment (david-binda) [reply modules/widget-visibility/widget-conditions.php:261]: Another approach would be to introduce a Jetpack specific filter and mention it in the release notes, so folks who want to take advantage of the filter in terms of the Widget Visibility feature, would have a path forward.

Comment (jeherve) [reply modules/widget-visibility/widget-conditions.php:261]: Yeah, I like that idea! 👍

Comment (david-binda) [reply modules/widget-visibility/widget-conditions.php]: Done ✅

File: modules/widget-visibility/widget-conditions.php [hunk 4]
```diff
@@ -199,6 +213,58 @@ public static function widget_admin_setup() {
...
+			'exclude_tree' => array(),
+			'number'       => '',
+			'offset'       => 0,
+			'post_type'    => 'page',
+			'post_status'  => 'publish',
+		);
+
+		/**
+		 * Filters the retrieved list of pages.
+		 *
```
Comment (jeherve) [inline modules/widget-visibility/widget-conditions.php:261]:
```suggestion
		 *
		 * @module widget-visibility
		 *
		 * @since 9.1.0
		 *
```

We use to categorize hooks by feature in the Jetpack Codex.

File: modules/widget-visibility/widget-conditions.php [hunk 5]
```diff
@@ -199,6 +213,58 @@ public static function widget_admin_setup() {
...
+		 * @param stdClass[] $pages       Array of objects containing only the ID, post_parent, and post_title fields.
+		 * @param array      $parsed_args Array of get_pages() arguments.
+		 */
+		return apply_filters( 'widget_conditions_get_pages', $pages, $parsed_args );
```
Comment (jeherve) [inline modules/widget-visibility/widget-conditions.php:265]:
```suggestion
		return apply_filters( 'jetpack_widget_visibility_get_pages', $pages, $parsed_args );
```

**Review by jeherve — CHANGES_REQUESTED** [review]

**Review by jeherve — APPROVED** [review]
This should be all good now! 🚢

**Review by jeherve — CHANGES_REQUESTED** [review]
Do you think you could rebase against `master`? Unit tests are failing right now because of changes in Core, and we've fixed those in `master` yesterday (see https://github.com/Automattic/jetpack/pull/17570) so rebasing should fix this.

**Review by jeherve — APPROVED** [review]

**Comment by jeherve** [comment]
r217718-wpcom
