### PR TITLE
Subscriptions Block: Remove inline styling for colors on status message

### LINKED ISSUE #19113: Subscription Block: Success message forces a white background
The Subscription block's post-submit messages force a white background via an inline style rule, but do not specify a text color. If the inherited text color happens to be white (or some other light color), this makes it unreadable. 

I'd suggest that the block either supply a foreground color too, or (more preferably) just leave the background as is. 

#### Steps to reproduce the issue

1. Add a Subscription block inside of a page or block that has a black background and white text. 
2. On the front-end, enter an email address, select Subscribe. 

Sample Content: 

```
<!-- wp:group {"style":{"color":{"text":"#ffffff","background":"#000000"}}} -->
<div class="wp-block-group has-text-color has-background" style="background-color:#000000;color:#ffffff"><div class="wp-block-group__inner-container"><!-- wp:jetpack/subscriptions -->
<div class="wp-block-jetpack-subscriptions wp-block-jetpack-subscriptions__supports-newline">[jetpack_subscription_form show_subscribers_total="false" button_on_newline="false" custom_font_size="16px" custom_border_radius="0" custom_border_weight="1" custom_padding="15" custom_spacing="10" submit_button_classes="" email_field_classes="" show_only_email_and_button="true"]</div>
<!-- /wp:jetpack/subscriptions --></div></div>
<!-- /wp:group -->
```

**Screenshots**

Form before submission:
Screen Shot 2021-03-10 at 8 56 45 AM

Form after submission:
Screen Shot 2021-03-10 at 9 00 20 AM

Form after submission (with text selected to show it's there):
Screen Shot 2021-03-10 at 8 59 37 AM

### PR DESCRIPTION
**Pull request by stacimc**
Fixes #19113

#### Changes proposed in this Pull Request:

The post-submit status message for the Subscriptions block had hard-coded inline styles to set the `background-color` and text `color` to the styles defined in the global `$themecolors`. This can cause bugs if the theme only defines a value for one or the other; for example, if the theme sets the `background-color` to white but does not define a text color, the message's text color may inherit from the parent block -- and if this also happens to be white, the text is not readable.

This PR removes the hard-coded inline color styles. It should affect only the post-submit message, not the rest of the block. See screenshots.

#### Testing instructions:

If testing on a sandbox, you will need to manually copy the changes into your sandbox, as it will not be picked up by the awe sync.

**First verify that you can see the bug**
* Activate the Seedlet theme (which sets `$themecolors['bg'] ='FFFFFF'` but does not set `$themecolors['text']`)
* Create a new post and insert a Group block.
* In the Group block's Inspector Controls, set the background-color to black and the text color to white.
* Insert a Subscriptions block into the Group block.
* View the post on the frontend.
* Enter an email address and submit the Subscriptions form (any status will do).
* Observe that the background of the submit message is white (coming from the theme) and the text color is also white (coming from the Group block).

Screen Shot 2021-03-19 at 3 21 49 PM

_Text partially highlighted so it is visible._

**Test that the bug is resolved**
* Now checkout this branch and refresh the post.
* Observe that the status message text and background color are now inherited from the Group block.
* Go back to the editor and insert another Subscriptions block outside of the Group block.
* On the frontend, verify that the status message now inherits colors from the theme
Screen Shot 2021-03-19 at 3 40 02 PM

_The message inside the Group block has black background and white text. The message outside the block has the default green background and dark text from the Twenty Twenty One theme_

You can easily test all of the status messages by appending the status type to the URL, like:
`<mytestsite.wordpress.com>?p=431&preview=true&blogsub=<status>`, where `status` is each of: `confirming, blocked, flooded, spammed, subscribed, pending, confirmed`.

### CODE REVIEW

**Comment by stacimc** [comment]
I'd like some feedback on this approach. I may be missing something with theme configuration; should we actually expect all themes to define both `bg` and `text`? I notice Seedlet does define `txt`.

File: projects/plugins/jetpack/modules/subscriptions/views.php [hunk 1]
```diff
@@ -210,43 +210,36 @@ static function render_widget_status_messages( $instance ) {
...
 					break;
 				case 'confirmed':
-					echo "<div style='background-color: #{$themecolors['bg']}; border: 1px solid #{$themecolors['border']}; color: #{$themecolors['text']}; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;'>";
-					_e( 'Congrats, you&rsquo;re subscribed! You&rsquo;ll get an email with the details of your subscription and an unsubscribe link.' );
-					echo "</div>";
+					$message = __( 'Congrats, you&rsquo;re subscribed! You&rsquo;ll get an email with the details of your subscription and an unsubscribe link.', 'jetpack' );
 					break;
 			}
+
+			echo sprintf( "<div style='border: 1px solid #%s; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;'>", esc_attr( $themecolors['border'] ) );
```
Comment (ramonjd) [inline projects/plugins/jetpack/modules/subscriptions/views.php:240]: During my tests (using Spearhead) I noticed that, where `$themecolors['border']` is empty, the following invalid CSS is output:

`border: 1px solid #; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;`

Do you think it'd be better to only print the inline style `border: 1px solid #; ` if `$themecolors['border']` is empty?

**Review by ramonjd — DISMISSED** [review]
Curiously, this didn't work for me on Seedlet, but I re-ran using Spearhead and the fix is noticeable.

The background colour inline style is gone and the success message background reflects the group block setting.

I have one question as to whether we should ensure the inline style is valid, that is, ensure no empty values in the border declaration: `border: 1px solid #`


**Before**
Screen Shot 2021-03-22 at 10 44 19 am

```
<div style="background-color: #FFFFFF; border: 1px solid #; color: #; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;">Congrats, you’re subscribed! You’ll get an email with the details of your subscription and an unsubscribe link.</div>
```

**After**
Screen Shot 2021-03-22 at 10 44 28 am


```
<div style="border: 1px solid #; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;">Congrats, you’re subscribed! You’ll get an email with the details of your subscription and an unsubscribe link.</div>
```

**Comment by scruffian** [comment]
IMO we should just not output any styles here and let it fall back to the theme defaults. This will be a lot easier once we have this in place: https://github.com/WordPress/gutenberg/pull/29714

**Comment by stacimc** [comment]
> IMO we should just not output any styles here and let it fall back to the theme defaults. This will be a lot easier once we have this in place: WordPress/gutenberg#29714

@scruffian I think we're on the same page, but to clarify -- in this approach we're removing the inline-styles and not explicitly setting the theme colors on the block, so that it only falls back to theme defaults when more specific colors are not set on it/its container blocks. Does that sound correct to you?

The border color is the only style that does not automatically fall back to the theme default, so I'm keeping the inline style for that. The CSS var approach in your linked PR would definitely make that easier.

File: projects/plugins/jetpack/modules/subscriptions/views.php (hunk 1 above)
Comment (stacimc) [reply projects/plugins/jetpack/modules/subscriptions/views.php]: Agreed 👍 I kept the `1px solid` border but removed the empty color value, rather than omitting the border altogether. The border takes on the text-color in this case.

Screen Shot 2021-03-22 at 2 05 52 PM

Per the discussion below -- once we can access the theme border color with CSS variables, we can move all of the styling out into the stylesheets and it will be much cleaner :)

**Review by apeatling — DISMISSED** [review]
Confirmed this works much better now with the default styles removed, and border color kept in place.

File: projects/plugins/jetpack/modules/subscriptions/views.php [hunk 2]
```diff
@@ -210,43 +210,37 @@ static function render_widget_status_messages( $instance ) {
...
-					_e( 'Congrats, you&rsquo;re subscribed! You&rsquo;ll get an email with the details of your subscription and an unsubscribe link.' );
-					echo "</div>";
+					$message = __( 'Congrats, you&rsquo;re subscribed! You&rsquo;ll get an email with the details of your subscription and an unsubscribe link.', 'jetpack' );
 					break;
 			}
+
+			$border_color = isset( $themecolors['border'] ) ? " #{$themecolors['border']}" : '';
+			echo sprintf( "<div style='border: 1px solid%s; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;'>", esc_attr( $border_color ) );
+			echo wp_kses_post( $message );
+			echo '</div>';
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/subscriptions/views.php:243]: What would you think about simplifying things even more?

```suggestion
			printf(
				'<div style="border: 1px solid%1$s; padding-left: 5px; padding-right: 5px; margin-bottom: 10px;">%2$s</div>',
				esc_attr( $border_color ),
				wp_kses_post( $message )
			);
```

**Review by jeherve — CHANGES_REQUESTED** [review]
That simplifies quite a bit, nice work. I only have a minor suggestion, below.

File: projects/plugins/jetpack/modules/subscriptions/views.php (hunk 2 above)
Comment (stacimc) [reply projects/plugins/jetpack/modules/subscriptions/views.php]: Nice, even better. Committed!

**Review by andrewserong — APPROVED** [review]
This is testing nicely for me @stacimc! Nice work cleaning up the code in the process, too 👍  

image

**Review by jeherve — APPROVED** [review]

**Comment by stacimc** [comment]
r223723
