### PR TITLE
required-review: Add `is-author-or-reviewer` condition

### LINKED ISSUE #41933: Bug in action-required-review
### Impacted plugin

Jetpack

### Quick summary

**action-required-review** will never satisfy requirements if @someUser is an author of a PR and requirements are configured like this:

```
  teams:
    - all-of:
      - some-team
      - '@someUser'
```

It's impossible to make a self-review and impossible to merge the PR. An empty team should be excluded from the requirements check. An empty virtual team for @someUser in this case/

### Steps to reproduce

1. Configure requirements 

```
- name: Misc
  paths: unmatched
  teams:
    - all-of:
      - some-team
      - '@someUser'
```

2. Open a PR by @someUser as an author
3. Get approval from any user of "some-team"

Result: Requirement "Misc" is not satisfied by the existing reviews.

Expected result: Requirement "Misc" is satisfied by the existing reviews.
 

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Major

### What other impact(s) does this issue have?

_No response_

### If a workaround is available, please outline it here.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### PR DESCRIPTION
**Pull request by anomiex**
## Proposed changes:

Sometimes people want to allow someone (or some team) to "self-review" code. GitHub doesn't support self-reviews directly, but we can assume that the author has reviewed their own PR in the writing of it.

Also, this is well past needing some automated testing. Add some for the file being touched here.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

Fixes #41933

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* CI happy? Tests look like the cover everything?

### CODE REVIEW

**Comment by anomiex** [comment]
Too bad it only does five, it missed out on having this line 😀

| File | Coverage |
| :--- | :------: |
| projects/github-actions/required-review/src/requirement.js |  110/110 (100.00%) 💚 |

File: projects/github-actions/required-review/src/requirement.js [hunk 1]
```diff
@@ -52,32 +53,29 @@ function buildReviewerFilter( config, teamConfig, indent ) {
 	const op = keys[ 0 ];
 	let arg = teamConfig[ op ];
 
+	// Shared validation.
```
Comment (tbradsha) [inline projects/github-actions/required-review/src/requirement.js:56]: Any reason we don't just do an `items.includes( op )` instead of a `switch`?

File: projects/github-actions/required-review/src/requirement.js [hunk 2]
```diff
@@ -126,7 +124,35 @@ function buildReviewerFilter( config, teamConfig, indent ) {
...
+			}
+			return printSet(
+				`${ indent }=>`,
+				[ ...new Set( requirementsMet.flat( 1 ) ) ],
+				[ ...new Set( neededTeams.flat( 1 ) ) ]
+			);
+		};
+	}
+
 	throw new RequirementError( `Unrecognized operation "${ op }"`, {
```
Comment (tbradsha) [inline projects/github-actions/required-review/src/requirement.js:156]: Why don't we return early like we did before with the `default`?

**Review by tbradsha — APPROVED** [review]
Two tangential inline comments, but from what I can tell this looks good.

File: projects/github-actions/required-review/src/requirement.js (hunk 1 above)
Comment (anomiex) [reply projects/github-actions/required-review/src/requirement.js:56]: Not really. The way I think about this code a `switch` just makes more sense to me.

File: projects/github-actions/required-review/src/requirement.js (hunk 2 above)
Comment (anomiex) [reply projects/github-actions/required-review/src/requirement.js:156]: No real reason. I couldn't cover this line before because of the early return, and I wound up deciding that there was no harm in leaving the throw until the end here instead.
