### PR TITLE
Remove composer dependency listing for built branches

### LINKED ISSUE #13497: Incompatibility with a WP Composer installation
### Context
* Install WordPress and Jetpack using Composer
* Use Jetpack v7.5+ (since #12857)
* Run a WP CLI command

### Output
```shell
PHP Fatal error:  Uncaught Error: Call to undefined function add_action() in /var/www/example.com/vendor/automattic/jetpack-compat/functions.php:23
Stack trace:
#0 /var/www/example.com/vendor/composer/autoload_real.php(66): require()
#1 /var/www/example.com/vendor/composer/autoload_real.php(56): composerRequire9e2e0155ae2296865e0a62cb9575b86b('009de6aaa0d497e...', '/var/www/...')
#2 /var/www/example.com/vendor/autoload.php(7): ComposerAutoloaderInit9e2e0155ae2296865e0a62cb9575b86b::getLoader()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1198) : eval()'d code(6): require_once('/var/www/stagin...')
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1198): eval()
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1159): WP_CLI\Runner->load_wordpress()
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner in /var/www/example.com/vendor/automattic/jetpack-compat/functions.php on line 23
```

### Notes

Seems very related to the `jetpack-compat` package.

### PR DESCRIPTION
**Pull request by LeoColomb**
Fixes #13497

#### Changes proposed in this Pull Request:

* Remove composer dependency listing for built branches.
Ref: https://github.com/Automattic/jetpack/issues/13497

See my comments inline for detail, and please let me know if there is a better way!

#### Testing instructions:

N/A

#### Proposed changelog entry for your changes:

* Not sure it's really needed.

🚀

### CODE REVIEW

File: tools/build-release-branch.sh [hunk 1]
```diff
@@ -238,6 +238,13 @@ yarn cache clean
 COMPOSER_MIRROR_PATH_REPOS=1 yarn run build-production
 echo "Done"
 
+# Remove composer dependencies listing.
+# Workaround for https://github.com/Automattic/jetpack/issues/13497
+# TODO: Keep dependencies away from built branches and fetch them before publishing on WP-org plugins repository.
+awk '!/automattic\/jetpack-/' composer.json > temp && mv temp composer.json
```
Comment (LeoColomb) [inline tools/build-release-branch.sh]: Remove all lines mentioning a jetpack package.

File: tools/build-release-branch.sh [hunk 2]
```diff
@@ -238,6 +238,13 @@ yarn cache clean
...
+sed 's/openssl": "\*",/openssl": "\*"/' composer.json > temp && mv temp composer.json
```
Comment (LeoColomb) [inline tools/build-release-branch.sh]: Remove the extra comma on the new last line of the `require` object.

File: tools/build-release-branch.sh [hunk 3]
```diff
@@ -238,6 +238,13 @@ yarn cache clean
...
+rm -f composer.lock
```
Comment (jeherve) [inline tools/build-release-branch.sh]: That should not be necessary. I've just pushed #14905 to ensure it never makes it to the built branch.

**Review by jeherve — CHANGES_REQUESTED** [review]
Thank you! I left a few comments below.

Right now, we're left with modified files once the script is done running. It may be good to add something like `git checkout -- composer.json` after `cd $DIR` in the cleaning up step.

File: tools/build-release-branch.sh (hunk 2 above)
[the remark this answers is not in the document]
Comment (LeoColomb) [reply tools/build-release-branch.sh]: That was not ideal at all, but I was not aware of Composer regexp capability. Good one! 😄

File: tools/build-release-branch.sh (hunk 3 above)
Comment (LeoColomb) [reply tools/build-release-branch.sh]: Ok!

File: tools/build-release-branch.sh (hunk 1 above)
[the remark this answers is not in the document]
Comment (LeoColomb) [reply tools/build-release-branch.sh]: Done. Let me know if good enough.

**Review by jeherve — APPROVED** [review]
This seems to work well in my tests. Merging. Thanks again for the contribution!

**Review by jeherve — CHANGES_REQUESTED** [review]
Do you think you could rebase this PR to include some of the latest changes we've made to our end to end tests? Right now the end to end tests fail for this PR, so we can't merge it as is.

Thank you!

**Comment by LeoColomb** [comment]
@jeherve Could you just use the update button? Would much more handy 🙂

**Comment by jeherve** [comment]
True, I've rebased now.

@brbrr Could you take another look at that test? Thank you!

**Comment by brbrr** [comment]
https://github.com/Automattic/jetpack/pull/15031 should disable E2E tests for forks. Rebase should fix the issue

**Review by jeherve — DISMISSED** [review]

**Review by jeherve — APPROVED** [review]

File: tools/build-release-branch.sh (hunk 3 above)
Comment (LeoColomb) [reply tools/build-release-branch.sh]: @jeherve The `composer.lock` seems to still be included in built branches: https://github.com/Automattic/jetpack/blob/branch-8.4-built/composer.lock

Are you sure we should not add this line anyway?
Thx!

Comment (jeherve) [reply tools/build-release-branch.sh]: This was because of a hiccup when building the built branch the first time around. It will not happen in the future.
