### PR TITLE
Sharing: fix a11y issues in buttons' links

### LINKED ISSUE #30474: Sharing: use aria-label and aria-haspopup instead of hidden screen-reader elements
### Impacted plugin

Jetpack

### Quick summary

Social sharing icon markup contains hidden SPAN elements with the class `sharing-screen-reader-text`. Despite being styles as hidden, these elements add text to the page, which dilutes keyword density, while not providing sufficient support for accessibility.

Along with an empty SPAN element, these also add unnecessarily to the DOM size, and the `title` attribute can be confusing for screen readers when combined with similar attributes for the same element.

Example:

```
<li class="share-twitter"><a rel="nofollow noopener noreferrer" data-shared="sharing-twitter-2" class="share-twitter sd-button share-icon no-text" href="https://www.plastic2go.com.au/?share=twitter" target="_blank" title="Click to share on Twitter" ><span></span><span class="sharing-screen-reader-text">Click to share on Twitter (Opens in new window)</span></a></li>
```

A better way to achieve this, and more, is using `aria-label` on the anchor tag, as well as `aria-haspopup` to let the visitor know about the social media popup that the click will trigger:

```
<li class="share-twitter"><a aria-label="Click to share on Twitter" aria-haspopup="true" rel="nofollow noopener noreferrer" data-shared="sharing-twitter-2" class="share-twitter sd-button share-icon no-text" href="https://www.plastic2go.com.au/?share=twitter" target="_blank"></a></li>
```

### Steps to reproduce

1. Enable social sharing icons
2. Check the HTML code of the rendered page

### Impact

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### PR DESCRIPTION
**Pull request by monsieur-z**
Fixes https://github.com/Automattic/jetpack/issues/30474

## Proposed changes:

This PR fixes the accessibility problems mentioned in the linked issue. In detail:
- It removes the `title` attribute from the `a` tag. A title is not the recommended way to specify an accessible name.
- Instead, the accessible name is specified by linking a text element with `aria-labelledby`. It's preferred over the `aria-label` attribute as the latter [may not be picked up by automated translation services](https://adrianroselli.com/2019/11/aria-label-does-not-translate.html).
- It deprecates `jetpack_sharing_display_title` in favor of a new filter named `jetpack_sharing_accessible_name` to mitigate confusion.
- It removes the `sharing-screen-reader-text` class (and the associated CSS rules) which is no longer necessary since the accessible name is specified with `aria-labelledby`.
- It was suggested in the issue to add the `aria-haspopup` attribute. According to [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-haspopup), this doesn't seem appropriate to this use case since activating the link opens a new window. The accessible name mentions a new window will be open.
- It formats the markup returned by `get_link` for better readability.
KA additions:
- It also ensures we do the same for the sharing buttons in the Sharing Buttons block.
- Noting here that some 'official' buttons (legacy sharing buttons only) have not been included, due to more complex DOM element creation, including injected iframes and other content.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

_Note: on this branch like on trunk, sharing buttons are rendered the same no matter the value of the Sharing_Source::button_style attribute._

- Spin up a Jetpack site with this branch
- Toggle on the _Add sharing buttons to your posts and pages_ option in `/wp-admin/admin.php?page=jetpack#sharing`
- Create a new post
- Publish it (saving a draft is not sufficient)
- View the post
- Notice the sharing buttons below the post. Verify they work as expected.
- If you're able to use a screen reader, check it announces something like _link, Click to share on Facebook (Opens in new window)_ when it reaches a sharing button
- Otherwise, verify the button markup is similar to:
Screenshot 2025-04-01 at 2 18 10 PM

KA additions:
- You can add more sharing buttons by visiting Settings > Sharing: `/wp-admin/options-general.php?page=sharing`. On a self-hosted site, to view this page you will need to ensure the site is in offline mode, so you would need to add this to `wp-config.php`: `define('JETPACK_DEV_DEBUG', true );`. In Jurassic Ninja, you can enable offline mode in `wp-admin/options-general.php?page=companion_settings` You should be able to view this page on WoA and Simple though. If still no luck, you may be able to use the WPcom page at `wordpress.com/marketing/sharing-buttons/`.
- You will also need a legacy theme such as Twenty Ten installed and active.
- Test all legacy buttons, including custom buttons. As a most basic test, you can add a dummy link for the URL and for the icon add something like https://icons.iconarchive.com/icons/pictogrammers/material-light/16/link-icon.png.
- Test with icon, icon and text, and text only. Note that official buttons haven't been included (see description above).

Testing the Jetpack Sharing block:
- Ensure Jetpack Blocks are enabled at Jetpack > Settings > Writing: `/wp-admin/admin.php?page=jetpack#writing`
- Add a Sharing button block to a post
- Add any service button (in it's different formats: text, icon, icon + text)
- Test the markup is similar to the legacy sharing buttons. Primarily, for each button there is an 'aria-labelledby' attribute, whose value should match the child span id. That span should be hidden (this should also be the same for legacy sharing buttons, see earlier testing instructions).

### CODE REVIEW

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php [hunk 1]
```diff
@@ -315,13 +315,33 @@ public function get_link( $url, $text, $title, $query = '', $id = false, $data_a
...
 		 * @param string $title Sharing service title.
 		 * @param object $this Sharing service properties.
 		 * @param string|false $id Sharing ID.
 		 * @param array $args Array of sharing service options.
 		 */
-		$title = apply_filters( 'jetpack_sharing_display_title', $title, $this, $id, $args );
+		$accessible_name = apply_filters_deprecated(
+			'jetpack_sharing_display_title',
+			array( $accessible_name, $this, $id, $args ),
+			'jetpack-14.6',
```
Comment (monsieur-z) [inline projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: `replace-next-version-tag.sh` doesn't replace `$$next-version$$` in this instance.

Comment (manzoorwanijk) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: It should be a single line to make work.

**Review by jeherve — COMMENTED** [review]
Do we need to do the same for the Sharing Buttons block?

https://github.com/Automattic/jetpack/blob/d0f8e92d4769905b1d182346e73c290d76529e27/projects/plugins/jetpack/extensions/blocks/sharing-button/class-sharing-source-block.php#L172

File: projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php (hunk 1 above)
Comment (coder-karen) [reply projects/plugins/jetpack/modules/sharedaddy/sharing-sources.php]: Modified in 9813d6cf97f1eb283057364eb5864c7b5e88d819

**Comment by coder-karen** [comment]
> Do we need to do the same for the Sharing Buttons block?

Thanks @jeherve. I've taken this PR over, and also done the same for Sharing Button blocks now too.

File: projects/plugins/jetpack/extensions/blocks/sharing-button/sharing-button.php [hunk 2]
```diff
@@ -66,37 +66,33 @@ function render_block( $attr, $content, $block ) {
...
 		esc_html( $title )
 	);
 
-	$link_props = $service->get_link(
-		$post_id,
-		'share=' . esc_attr( $service_name ) . '&nb=1',
-		false,
-		esc_attr( $data_shared )
-	);
+	$accessible_name .= ' ' . __( '(Opens in new window)', 'jetpack' );
```
Comment (jeherve) [inline projects/plugins/jetpack/extensions/blocks/sharing-button/sharing-button.php]: I think the space should be part of the translatable string, so the thing can work on RTL languages.

Comment (coder-karen) [reply projects/plugins/jetpack/extensions/blocks/sharing-button/sharing-button.php]: Good point, I see we did that in the Sharing_Source class for the $accessible_name as well. Added in 626e9fea9839b6c6617f80fec2be9c297eae5850

**Review by jeherve — APPROVED** [review]
This tests well for me! 🚢
