### PR TITLE
SSO: Fixes an issue where bypassing login form always logged out user from WP.com

### LINKED ISSUE #3934: SSO: need to enter WordPress.com log in details each time I access my Jetpack site
I use the following filter to redirect all log in forms to WordPress.com:

```php
// Redirect all logins to WordPress.com
add_filter( 'jetpack_sso_bypass_login_forward_wpcom', '__return_true' );
```

It works well and redirects me to WordPress.com whenever I want to access my W.org site. However, it now prompts me to enter my password and 2FA code every time, even though I'm already logged in to my WordPress.com account. In the past, it would only ask me to log in if I was logged out of WordPress.com.

@ebinnion Could this be related to your latest changes?

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #3934.

In #3934, @jeherve pointed out an issue where the user was always forced to log in to WordPress.com when bypassing the default log in form like this:

`add_filter(  'jetpack_sso_bypass_login_forward_wpcom', '__return_true' );`

I was able to narrow down the issue to the fact that WP.org also uses the `$_GET['reauth']` parameter. To fix, the link to login as a different WP.com user now uses `force_reauth`.

To test:

- Checkout `fix/sso-bypass-reauth` branch
- In a compat plugin: `add_filter(  'jetpack_sso_bypass_login_forward_wpcom', '__return_true' );`
- Go to `$site/wp-admin`
- You should be automatically redirected to WP.com, and maybe even automatically redirected to the wp-admin of your site
- Remove the filter above
- Go to `$site/wp-admin`
- Click the "Login with WordPress.com" button. You should be logged in to your wp-admin.
- Click the "Login as a different WP.com user" link. You should have to login again on WP.com

cc @lezama for review and @jeherve in case he'd like to test.

### CODE REVIEW

File: modules/sso.php [hunk 1]
```diff
@@ -490,7 +490,7 @@ function login_form() {
 				<?php echo $this->build_sso_button( array(), 'is_primary' ); ?>
 
 				<?php if ( $display_name && $gravatar ) : ?>
-					<a class="jetpack-sso-wrap__reauth" href="<?php echo $this->build_sso_button_url( array( 'reauth' => '1' ) ); ?>">
+					<a class="jetpack-sso-wrap__reauth" href="<?php echo $this->build_sso_button_url( array( 'force_reauth' => '1' ) ); ?>">
```
Comment (lezama) [inline modules/sso.php]: not from this PR, is it safe to not `url_esc` here?

Comment (ebinnion) [inline modules/sso.php]: Thanks for pointing that out. I'll do an audit on these in a separate PR.

**Comment by jeherve** [comment]
It seems to work for me! 👍  LGTM!
