### PR TITLE
Fix blog stats block for simple sites

### LINKED ISSUE #34506: Top Posts & Blog Stats: support WPCOM
```[tasklist]
### Tasks
- [ ] <strike>Resolve the stats/top-posts call for the endpoint</strike>
- [x] Boot up the endpoint on WPCOM
- [x] Register block on WPCOM
```

### PR DESCRIPTION
**Pull request by kangzj**
Partially Fixes https://github.com/Automattic/jetpack/issues/34506
Related changes: 180209-ghe-Automattic/wpcom

## Proposed changes:

* Use stats functions directly for simple sites as I didn't find a way to forward the requests correctly even after discussion: p1743129864485969-slack-CDLH4C1UZ

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

p1743129864485969-slack-CDLH4C1UZ

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

* Install the branch on WPCOM sandbox
* Sandbox public-api and a simple site
* Create a post
* Insert Blog Stats block
* Play with block settings
* Ensure it shows correct number in the editor
* Publish it
* Ensure it works well on the front end

Note: optionally you can test with 180209-ghe-Automattic/wpcom for correct post views in editor

image

### CODE REVIEW

**Review by dognose24 — DISMISSED** [review]
Works as Atomic sites to have the data aligned with Stats. 👍🏼

截圖 2025-04-11 上午11 10 57

截圖 2025-04-11 上午11 12 15

截圖 2025-04-11 上午11 08 38

One thing I noticed is that the `post-views` of a new post is `null`, but the value of the Atomic site is `0`.

|Simple|Atomic
|-|-|
|截圖 2025-04-11 上午11 14 06|截圖 2025-04-11 上午11 14 25|

File: projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php [hunk 1]
```diff
@@ -0,0 +1,94 @@
...
+				// @phan-suppress-next-line PhanUndeclaredFunction
+				return get_all_time_postviews( $stats_option['postId'] );
+			}
+		} else {
+			// Simple sites.
+			$_blog_id = get_current_blog_id();
+			if ( $stats_option['statsData'] === 'views' && function_exists( 'stats_grandtotal_views' ) ) {
+				// This is cached so no need to cache it again.
+				// @phan-suppress-next-line PhanUndeclaredFunction
+				return stats_grandtotal_views( $_blog_id );
```
Comment (dognose24) [inline projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php:76]:
```suggestion
				return stats_grandtotal_views( $_blog_id ) || 0;
```
Do we need to avoid returning `null` for a new post?

File: projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php [hunk 2]
```diff
@@ -0,0 +1,94 @@
...
+				if ( $stats_option['statsData'] === 'visitors' && isset( $data->stats->visitors ) ) {
+					return $data->stats->visitors;
+				}
+			}
+		} elseif ( $stats_option['statsOption'] === 'post' ) {
+			// Simple sites.
+			if ( function_exists( 'get_all_time_postviews' ) ) {
+				// This is cached so no need to cache it again.
+				// @phan-suppress-next-line PhanUndeclaredFunction
+				return get_all_time_postviews( $stats_option['postId'] );
```
Comment (dognose24) [inline projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php]:
```suggestion
				return get_all_time_postviews( $stats_option['postId'] ) ?? 0;
```
Do we need to avoid returning `null` for a new post?

Comment (kangzj) [reply projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php]: I forced a type convert in [eb32dd2](https://github.com/Automattic/jetpack/pull/43000/commits/eb32dd2043636f9095b4c751cf959f61904bb1dc) which does a similar thing 😄

Comment (dognose24) [reply projects/plugins/jetpack/_inc/lib/class-jetpack-blog-stats-helper.php]: LGTM!
