### PR TITLE
Lazy Images: Prefer Jetpack lazy loading over loading attribute tag

### LINKED ISSUE #23553: Lazy load intermittently causing images to not load in Safari 15.4
### Impacted plugin

Jetpack

### Steps to Reproduce

I was able to reliably replicate using the core gallery block on two different themes (Neve and Twenty Twenty). It seems to only happen on some themes, not all.

1. Add a core gallery block to a page with a few images
2. Load the page in Safari 15.4
3. Only the first image in the gallery loads, the rest of the thumbnails load blank. If you don't see this happen initially, refresh a few times and it should eventually occur. 

Note: this issue seems to be impacting more than just galleries (for example, we received a user report mentioning it impacted featured images and category images on their custom theme, which were loading in blank) but I'm mentioning galleries here since it's a reliable way to reproduce.

Deactivating lazy load in the Jetpack settings resolves the issue.

Screen Shot 2022-03-22 at 12 21 36 PM
 

### Operating System

macOS

### OS Version

12.3

### Browser

Safari

### Browser Version(s)

15.4

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #23553

#### Changes proposed in this Pull Request:

While debugging #23553, I observed that in `master`, when I loaded a page with many images and then scrolled, that the images outside the viewport would load but the images that were initially in the viewport would not load.

This led me to think that there was some conflict between Safari's implementation and our JavaScript implementation. As I thought more about it, it doesn't make much sense to me to use a JavaScript implementation of lazy images and the core browser implementation. So, this PR chooses to solve the conflict by removing the `loading` tag when initializing an image for lazy loading via Jetpack.

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Checkout PR
* Create a post with multiple images in a gallery, enough to create multiple rows ideally
* Try to load the post starting with different viewport sizes and ensure that images always load

### CODE REVIEW

**Review by thingalon — DISMISSED** [review]
👍 Tested, and this works. Appears to be a decent fix for the immediate compatibility issue.

**Comment by thingalon** [comment]
Passes muster with @Automattic/heart-of-gold, but requires a crew / ground control 👍 before merge.

File: projects/packages/lazy-images/src/lazy-images.php [hunk 1]
```diff
@@ -122,6 +122,8 @@ private function __construct() {
 
 		add_filter( 'wp_kses_allowed_html', array( $this, 'allow_lazy_attributes' ) );
 		add_action( 'wp_head', array( $this, 'add_nojs_fallback' ) );
+
+		add_filter( 'wp_img_tag_add_loading_attr', array( $this, 'maybe_skip_core_loading_attribute' ), 10, 2 );
```
Comment (jeherve) [inline projects/packages/lazy-images/src/lazy-images.php:126]: I wonder if we should filter through something else, like maybe `the_content`, to catch more use-cases such as the images in the Latest Instagram Posts block?

**Review by jeherve — COMMENTED** [review]
This seems to work well for some of the content, but not all, like the images in Latest Instagram Posts blocks. Would it be worth trying to catch that too?

File: projects/packages/lazy-images/src/lazy-images.php (hunk 1 above)
Comment (ebinnion) [reply projects/packages/lazy-images/src/lazy-images.php:126]: Possibly. I would expect this to catch any issues that rely on the core function for adding the loading attribute. But, in looking for `loading="` in the Jetpack repo, I guess that we've manually set this loading attribute in many places instead of calling a core function.

Comment (ebinnion) [reply projects/packages/lazy-images/src/lazy-images.php:126]: We were already hooking on the `the_content` filter. But, we were pretty conservative on re-processing the content. If we'd already processed any of the images in the content, we didn't touch any of the content. So, I made some changes to always process the content and to handle the logic to not reprocess and image on each image.

**Review by samiff — APPROVED** [review]
Tested in Chrome, Safari, Firefox at different resolutions and on mobile and this seemed to work well 👍 

We have an Atomic release next week so that will be a good test for this change since we've had a good number of HE reports on this issue.
