### PR TITLE
Stats: Fix date processing for At a Glance chart

### LINKED ISSUE #30344: At a Glance Stats: Different dates from the same data period
The Stats chart on the `At a Glance` page shows different dates compared to the chart of Calypso Stats.

#### Jetpack Stats in At a Glance
截圖 2023-04-28 上午2 07 53

#### Calypso Stats
截圖 2023-04-28 上午2 08 11

### PR DESCRIPTION
**Pull request by a8ck3n**
Fixes https://github.com/Automattic/jetpack/issues/30344

## Proposed changes:

Date values from the Stats endpoint are GMT so we need to make sure that is properly observed when displaying the At a Glance chart. Previous behaviour was treating the date string as coming from the browser (ie: the browser's local time).

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Visit the Stats → Traffic page and switch to the 30 days view. Note the last date on the chart.
* Visit Jetpack → Dashboard → At a Glance. Confirm the dates match.
* Test for weeks & years as well. Results in At a Glance should match the Traffic page when the date range and period match.

### CODE REVIEW

File: projects/plugins/jetpack/_inc/client/at-a-glance/stats/index.jsx [hunk 1]
```diff
@@ -77,14 +77,19 @@ export class DashStats extends Component {
 				chartLabel = '',
 				tooltipLabel = '';
 
+			// Dates from API are GMT so we want to make sure that is properly observed.
+			if ( 'week' === unit ) {
+				date = date.replace( /W/g, '-' );
+			}
+			date = new Date( `${ date }T00:00:00Z` ).toISOString();
```
Comment (kangzj) [inline projects/plugins/jetpack/_inc/client/at-a-glance/stats/index.jsx:84]: Nice fix! This is something we have been dealing with for a while. Very confusing Date constructor 😢

**Review by kangzj — APPROVED** [review]
LGTM!
