### PR TITLE
Managed Plugins: Maintain list of atomic managed plugins

### LINKED ISSUE #98422: Plugin autoupdate toggle not enabling
### Context and steps to reproduce

When I try to toggle autoupdates on for plugins, the toggle doesn't get enabled, even though it seems like the setting _does_ get enabled.

To reproduce:

1. Go to [Manage Plugins](https://wordpress.com/plugins/manage/sites)
2. Under Actions for one of the plugins, click Manage Plugin.
3. Click Manage Sites.
4. Toggle Autoupdate `on` for any site on which the plugin is installed. 

[Video here](https://www.loom.com/share/4a8d1a1f78d74c2982cb3ce71fe5a117).

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Moderate

### What other impact(s) does this issue have?

Agency or developer revenue

### If a workaround is available, please outline it here.

I'm unsure if a workaround is available, especially given autoupdates may actually be enabled even if the toggle indicator doesn't change.

### Platform

Atomic

### PR DESCRIPTION
**Pull request by gavande1**
Related: https://github.com/Automattic/wp-calypso/issues/98422

## Proposed changes:

* Save a list of atomic-managed plugins into a separate option. 

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

1. Create a new Business site, mark it as a WoA Dev site, and take it Atomic.
2. Open up an SSH session to the site, and run the following commands:

```
wp shell
> get_option( 'wpcomsh_at_managed_plugins' )
```

3. This should show the following output:

```
=> bool(false)
```

4. Exit the WP shell using the `exit` command
5. Build the wpcomsh plugin and synchronize it to the WoA Dev site

```
git checkout BRANCH
composer install
jetpack rsync wpcomsh SSH_USERNAME@sftp.wp.com:htdocs/wp-content/mu-plugins
```

6. Once wpcomsh has been updated.
7. Install or remove any plugin on the site.
8. Open up an SSH session to the site, and run the following commands:

```
wp shell
> get_option( 'wpcomsh_at_managed_plugins' )
```

9. Verify that it prints a list of atomic managed plugins.

### CODE REVIEW

File: projects/plugins/wpcomsh/feature-plugins/managed-plugins.php [hunk 1]
```diff
@@ -559,3 +559,39 @@ function wpcomsh_remove_managed_plugins_from_update_plugins( $current ) {
...
+	}
+
+	if ( ! function_exists( 'wpcomsh_is_managed_plugin' ) ) {
+		return;
+	}
+
+	$plugin_files    = array_keys( get_plugins() );
+	$managed_plugins = array_filter( $plugin_files, 'wpcomsh_is_managed_plugin' );
+
+	update_option( 'wpcomsh_at_managed_plugins', $managed_plugins );
```
Comment (epeicher) [inline projects/plugins/wpcomsh/feature-plugins/managed-plugins.php:581]: Just curious, why have you decided to use a new option instead of the [suggestion of synchronizing he existing option](https://github.com/Automattic/wp-calypso/issues/98422#issuecomment-2636840473)? 

Also, does the `at` in the name of the option `wpcomsh_at_managed_plugins` stands for `atomic`? If so, maybe it is clearer to use the explicit word `atomic` (unless it is conventional to use `at` 😄 )

**Review by epeicher — DISMISSED** [review]
I have tested it, and it works as advertised, I am able to see the new option updated after installing a plugin. Also, deleting a plugin updates the option as expected. LGTM!

CleanShot 2025-03-05 at 12 21 13

File: projects/plugins/wpcomsh/feature-plugins/managed-plugins.php (hunk 1 above)
Comment (epeicher) [reply projects/plugins/wpcomsh/feature-plugins/managed-plugins.php:581]: Ok, I think I've found why you are not using `wpcomsh_plugins_considered_for_auto_update`, it is probably because that option contains plugins that are not symlinked, that makes sense

**Review by gcsecsey — DISMISSED** [review]
I tested the changes as well, I used the Jetpack Beta plugin to install the branch version of the wpcomsh on my WoA site. The changes work as described, I can see the managed plugins being printed: 

image

File: projects/plugins/wpcomsh/feature-plugins/managed-plugins.php (hunk 1 above)
Comment (gavande1) [reply projects/plugins/wpcomsh/feature-plugins/managed-plugins.php:581]: > does the at in the name of the option wpcomsh_at_managed_plugins stands for atomic?

Yes. that's correct. 

>it is probably because that option contains plugins that are not symlinked, that makes sense 

Exactly. Great slauthing there!
