### PR TITLE
Search: Fix widget preview with settings

### LINKED ISSUE #22442: Search: Search widget breaks when switching from Instant to Classic search
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Purchase a Jetpack Search plan for your site.
2. Ensure that Jetpack Search and Instant Search have been automatically enabled for your site.
3. Add a Jetpack Search widget to your footer (or a sidebar available on all pages).
4. Navigate to `/` and ensure that the widget and the search overlay works as expected.
5. Disable Instant Search.
6. Navigate to `/` or `/wp-admin/widgets.php`.

### A clear and concise description of what you expected to happen.

- For search box and sort selector to render for the Jetpack Search widget.
- For the Jetpack Search widget to preview correctly.

### What actually happened

- Search box and sort selector are absent from the Jetpack Search widget.
image

- Widget preview is broken.
image

### Other information

_No response_

### Operating System

_No response_

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by dognose24**
Fixes #22442 

> Updating the Instant Search footer widget and then disabling Instant Search would reset the displaying of the search box and sort selection dropdown on the Classic Search footer widget, which also breaks the widget preview.

The `search box` and `sort selector` would appear on the site only when `search_box_enabled` and `user_sort_enabled` settings are turned on. This change would make the widget preview the same as what is appeared on the site.

截圖 2022-08-23 下午3 26 31

截圖 2022-08-23 下午3 26 37

#### Changes proposed in this Pull Request:

* Enable widget preview no matter whether filters or settings set
* Keep widget `search_box_enabled` and `user_sort_enabled` settings when updating on Instant Search mode

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

No.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

1. Purchase a Jetpack Search plan for your site.
2. Ensure that Jetpack Search and Instant Search have been automatically enabled for your site.
3. Add a Jetpack Search widget to your footer (or a sidebar available on all pages).
4. Navigate to `/` and ensure that the widget and the search overlay work as expected.
5. Disable Instant Search.
6. Navigate to `/wp-admin/widgets.php`.
7. Ensure the widget preview exists.

|  Before   | After  |
|  ----  | ----  |
| 截圖 2022-08-23 下午3 04 06 | 截圖 2022-08-23 下午3 05 04 |

8. Check search widget `search_box_enabled` and `user_sort_enabled` settings and submit the update.
9. Enable Instant Search.
10. Navigate to `/wp-admin/widgets.php`.
11. Change something of the widget and submit the update.
12. Disable Instant Search.
13. Navigate to `/wp-admin/widgets.php`.
14. Ensure the `search_box_enabled` and `user_sort_enabled` settings are kept as checked in step 8.

|  Before   | After  |
|  ----  | ----  |
| 截圖 2022-08-23 下午3 09 48 | 截圖 2022-08-23 下午3 10 02 |

### CODE REVIEW

**Review by kangzj — COMMENTED** [review]
Thanks for the fix @dognose24 which I found so hard to replicate. 

This is an impressive start, and I just dumped my thoughts below for consideration:

- For Classic Search, should we default the value of `search_box_enabled` to 1? Or say if the value is not explicitly set to 0, then we should treat them as 1. By doing so, we could align it with the experience with the Instant Search.
- `user_sort_enabled` is okay to be defaulted either way I guess, however it might still be better to align with Instant Search. Hidden by default?
- The last thing is, it fails my test when I switched from Instant to Classic Search as the search widget with filters in theme sidebar (footer in this case) doesn't show anything anymore (blank). 

----UPDATE----
I guess I know why the filters aren't showing up, which is by design I guess. I think in the future we could improve this, however I don't think it should be fixed by the PR.

I'd be happy if the `search_box_enabled` is made enabled by default, so when we switch from Instant to Classic, the search input shows up. 😄

File: projects/packages/search/src/widgets/class-search-widget.php [hunk 1]
```diff
@@ -338,10 +338,6 @@ public function widget_non_instant( $args, $instance ) {
 			}
 		}
 
-		if ( ! $display_filters && empty( $instance['search_box_enabled'] ) && empty( $instance['user_sort_enabled'] ) ) {
```
Comment (kangzj) [inline projects/packages/search/src/widgets/class-search-widget.php]: I guess we could possibly just leave this as is because when the search input is not set to display and it would still look broken. What do you think?

**Comment by dognose24** [comment]
Thanks for the quick review, @kangzj!

> For Classic Search, should we default the value of search_box_enabled to 1?

Has the [default value of `search_box_enabled`](https://github.com/Automattic/jetpack/blob/a32a887c6b339da0f5f6d5e3db491198c4831a13/projects/packages/search/src/widgets/class-search-widget.php#L251-L252) already been set to `true`?

> Or say if the value is not explicitly set to 0, then we should treat them as 1.

The behavior changing `search_box_enabled` is to update the widget on Instant Search, which does not contain a checkbox for `search_box_enabled`, which would make `form_data` for API the same as unchecked `search_box_enabled` on Classic Search.

File: projects/packages/search/src/widgets/class-search-widget.php (hunk 1 above)
Comment (dognose24) [reply projects/packages/search/src/widgets/class-search-widget.php]: Yes! I agree that the preview only shows the widget title is kind of weird.

截圖 2022-08-24 下午9 53 20

I would set `search_box_enabled` and `user_sort_enabled` settings default to '1' when creating a NEW widget, which could reduce most cases that users see the `No preview available`.

Thus, leaving this expression for preview checking would keep the original intention.

**Comment by dognose24** [comment]
As mentioned by @kangzj:

> I'd be happy if the search_box_enabled is made enabled by default, so when we switch from Instant to Classic, the search input shows up. 😄

I would set `search_box_enabled` and `user_sort_enabled` settings default to '1' when creating a NEW widget, which could reduce most cases that users see the `No preview available` message. Unless users uncheck `search_box_enabled` and `user_sort_enabled` settings on their own, they would not find the settings changed unexpectedly.

**Comment by kangzj** [comment]
> I would set search_box_enabled and user_sort_enabled settings default to '1' when creating a NEW widget, which could reduce most cases that users see the No preview available message. Unless users uncheck search_box_enabled and user_sort_enabled settings on their own, they would not find the settings changed unexpectedly.

Hi @dognose24  I can confirm it works now switching from Instant Search to Classic Search. <strike>However the filters for Instant Search doesn't seem to render any more in theme sidebars (e.g. in footer). Could you please have a look?</strike>

image

**Review by kangzj — APPROVED** [review]
Thanks for fixing the aged issue @dognose24!

It works as described and looks good to me! ❤️
