### PR TITLE
Sync Package: Replace use of Brute_Force_Protection class with a filter hook

### LINKED ISSUE #38460: Protect / Sync: Brute_Force_Protection class not found
I ran into this error on a site running Jetpack Boost, Jetpack Protect, Jetpack Social, and Jetpack. The Protect module is enabled on the site.

The error appears to be triggered during a log in attempt.

```
An error of type E_ERROR was caused in line 49 of the file /wp-content/plugins/jetpack-boost/jetpack_vendor/automattic/jetpack-sync/src/modules/class-protect.php. Error message: Uncaught Error: Class 'Automattic\Jetpack\Waf\Brute_Force_Protection\Brute_Force_Protection' not found in /wp-content/plugins/jetpack-boost/jetpack_vendor/automattic/jetpack-sync/src/modules/class-protect.php:49
Stack trace:
#0 /wp-includes/class-wp-hook.php(308): Automattic\Jetpack\Sync\Modules\Protect->maybe_log_failed_login_attempt(Array)
#1 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 /wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wp-content/plugins/jetpack/modules/protect.php(404): do_action('jpp_log_failed_...', Array)
#4 /wp-includes/class-wp-hook.php(310): Jetpack_Protect_Module->log_failed_attempt('admin')
#5 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#6 /wp-includes/plugin.php(51
```

### PR DESCRIPTION
**Pull request by nateweller**
Fixes https://github.com/Automattic/jetpack/issues/38460

## Proposed changes:

* Adds a new `jpp_has_login_ability` filter to the `waf` package.
* Uses the new `jpp_has_login_ability` filter in the `sync` package – when the `waf` package is available, it will provide the computed value through the WordPress hook. If it is unavailable, which technically/ideally should not happen, a default value of `false` is used.
* Keeps the use of `Brute_Force_Protection::has_login_ability()` in the `sync` package, but with a conditional to prevent exceptions. This ensures functionality in cases where the sync package is updated (starts using filter), but the waf package is not (has not started providing filter).

### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

https://github.com/Automattic/jetpack/issues/38460

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

* **Test on a site where the sync package is autoloaded from Jetpack Boost.**
* Install Jetpack (current release) and Jetpack Boost (feature branch) on a JN site.
* Test the brute force login protection feature - repeatedly fail login attempts and verify you are presented the math challenge, and then eventually get hard blocked from accessing the login page.

### CODE REVIEW

File: projects/packages/sync/src/modules/class-protect.php [hunk 1]
```diff
@@ -46,8 +60,9 @@ public function init_listeners( $callback ) {
 	 * @param array $failed_attempt Failed attempt data.
 	 */
 	public function maybe_log_failed_login_attempt( $failed_attempt ) {
-		$brute_force_protection = Brute_Force_Protection::instance();
-		if ( $brute_force_protection->has_login_ability() && ! Jetpack_Constants::is_true( 'XMLRPC_REQUEST' ) ) {
+		$has_login_ability = apply_filters( 'jpp_has_login_ability', $this->has_login_ability_fallback() );
```
Comment (jeherve) [inline projects/packages/sync/src/modules/class-protect.php]: Could you add a docblock for this new filter, so it can be parsed and a Codex page can be automatically created? This may be an opportunity to rename it to use the proper `jetpack_` prefix too?

Comment (nateweller) [reply projects/packages/sync/src/modules/class-protect.php]: Thanks @jeherve, applied these adjustments via https://github.com/Automattic/jetpack/pull/38518/commits/d00182e90e0e021cd8333920ebd96c5b165ed6a8 :+1:

**Review by jeherve — APPROVED** [review]
This seems to test well for me. 👍
