### PR TITLE
Stats: do not add tracking pixel to embed views

### LINKED ISSUE #22179: Enhancement: Exclude Embed Block Views from Stats
### Impacted plugin

Jetpack

### What

Exclude posts/pages in Embed Blocks from being counted in Stats

### How

Steps to reproduce:

1. Add an Embed Block into a page or post, and paste a page or post URL into the Embed Block.
2. View the page/post with that Embed Block.
3. The page/post that is embedded in the Embed Block gets a view (as does the page/post in which it's embedded).

User report: 4634341-zen

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #22179

#### Changes proposed in this Pull Request:

* When a post is embedded into another site, it's not really a view of that post; only an excerpt of the post is displayed. As a result, it is best not to count a view when such an embedded post is displayed.

#### Jetpack product discussion

* N/A

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

* You'll need 2 sites for this;
    * The Stats module needs to be active on both sites.
    * one of them has to be running this branch (call it Site B).
* On site A, publish a new post. In that post, include (on its own line) a link to a post from Site B.
* In an incognito window (so you're not logged in to those sites), visit the post you just published.
* In your network tab in dev tools, filter for `g.gif`
* Notice that the tracking pixel is called once for the post you are viewing.
* Now, on site B, revert to using latest stable.
* Refresh the post in the incognito window; the bug will now be back. You will see the tracking pixel getting called for both the post you are viewing and the post from site B.

### CODE REVIEW

File: projects/plugins/jetpack/modules/stats.php [hunk 1]
```diff
@@ -173,7 +173,14 @@ function stats_map_meta_caps( $caps, $cap, $user_id ) {
 function stats_template_redirect() {
 	global $current_user;
 
-	if ( is_feed() || is_robots() || is_trackback() || is_preview() || jetpack_is_dnt_enabled() ) {
+	if (
+		is_feed()
+		|| is_robots()
+		|| is_embed()
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/stats.php:179]: This is what I added.

**Review by anomiex — APPROVED** [review]
Seems ok. I couldn't reproduce the original bug while following the test instructions on a pair of JN sites, though.
