### PR TITLE
Hides the Blaze badge on the Stats page when the feature is disabled

### LINKED ISSUE #101987: Stats: do not display Blaze icon when user is not connected
### Context and steps to reproduce

> [!NOTE]
> This is easier to test on an active site, where you already have recorded stats.

2. Go to Jetpack > Jetpack
3. At the bottom of the page, disconnect your user, and then your site from WordPress.com.
4. Start the connection process again from scratch. When you receive the prompt to connect your account, **do not connect**. Instead go back to wp-admin.
5. Go to Jetpack > Stats
6. You should see the Blaze icon displayed next to posts with visits.

That icon should not be visible, because you cannot blaze posts until your account is connected to WordPress.com.

Image
Image

### Site owner impact

Fewer than 20% of the total website/platform users

### Severity

Minor

### What other impact(s) does this issue have?

No revenue impact

### If a workaround is available, please outline it here.

_No response_

### Platform

_No response_

### PR DESCRIPTION
**Pull request by sbarbosa**
Fixes https://github.com/Automattic/wp-calypso/issues/101987

We are displaying the Blaze link on the Stats page when the Blaze feature is off; if users click it, they will end up on an invalid page. The main problem is that the site and user connection are now handled separately, and it's more common to land on this case. (Blaze needs both connections to work correctly).

## Proposed changes:

Include the `can_blaze` flag as one of the initial parameters for the Jetpack Stats module (Odyssey app). 

**Note for Reviewers:** Because of a phan error, I had to include the blaze package as a dependency in the Stats. Please let me know if there are different ways to do this. I guarded my code in case the stats module is working on a standalone solution.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No

## Testing instructions:

You will need to have a site with some stats, so try to access the posts a couple of times before starting the test.

* Access any self-hosted and navigate to Jetpack->Stats
* Verify that you see the Blaze badge on any of the posts from the "Post & Pages" section:
Screenshot 2025-04-11 at 5 02 40 PM
* Now disconnect your user from WPCOM (just the user)
* Go back to Jetpack->Stats and verify that you no longer see the Blaze Badge.

### CODE REVIEW

File: projects/packages/stats-admin/src/class-odyssey-config-data.php [hunk 1]
```diff
@@ -40,6 +40,8 @@ public function get_data() {
 		$blog_id = Jetpack_Options::get_option( 'id' );
 		$host    = new Host();
 
+		$can_blaze = class_exists( 'Automattic\Jetpack\Blaze' ) && \Automattic\Jetpack\Blaze::should_initialize()['can_init'] === true;
```
Comment (timur987) [inline projects/packages/stats-admin/src/class-odyssey-config-data.php]: I see Phan static analysis gone mad and returned according error.

image

I found that there's a way to calm it a bit. Previously folks used this approach to make it happier: https://github.com/Automattic/jetpack/pull/41857/files

**Review by timur987 — APPROVED** [review]
Thanks @sbarbosa!

The code LGTM and works as advertised.

## For next reviewers
Using a local Jetpack is not the best way to test this PR because when I tried it I wasn't able to bring views there even after waiting for significant amount of time and trying various devices (tried accessing a post from phone, using VPN and so on).

Instead, please use a one-time Jurassic Ninja site together with Beta Tester plugin ([link](https://jetpack.com/download-jetpack-beta/)) by putting a feature branch as on the image below.

Screenshot 2025-04-14 at 16 12 23

---

## Side note

Even though what I want to mention is far beyond this PR, it still should be mentioned.
I noticed that blaze icon is shown for posts but is not shown for pages as on a gif below.

blaze-only-posts

File: projects/packages/stats-admin/src/class-odyssey-config-data.php (hunk 1 above)
Comment (sbarbosa) [reply projects/packages/stats-admin/src/class-odyssey-config-data.php]: Yes, I changed how I guard the code and explicitly use an if wrapper. I still had to add the blaze package in the composer. 

I will update the ticket to mention that so I can get feedback from the Jetapck team if I need to solve that problem differently.

**Review by therocket-gr — APPROVED** [review]
tested using a jurrasic site and worked as described
code changes LGTM

**Review by jeherve — APPROVED** [review]
