### PR TITLE
Admin: add text for Scan, Akismet and Backups cards.

### LINKED ISSUE #4885: Settings cards for Backups and Akismet show a blank space when plugins not installed
#### Steps to reproduce the issue

1. Deactivate akimset and/or Vaultpress plugins
2. Get to the Settings page under the **Security**
3. Expand Akismet or Backups card
4. See a blank card content

#### What I expected

It's expected that the cards for these modules in Admin Page's settings show a descriptive text instead of a blank space when the plugins are not active. 

#### What happened instead

A blank content shows in the cards when the plugins are not active

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #4885

#### Testing instructions:
- go to Jetpack > Settings > Security and expand the cards. If Akismet, Scan and Backups aren't active, they should display the text given by Jesse in the issue.
- when they're active, it should display a link to configure the settings.

### CODE REVIEW

File: _inc/client/components/module-settings/modules-per-tab-page.jsx [hunk 1]
```diff
@@ -93,7 +99,16 @@ export const AllModuleSettings = React.createClass( {
 				return <span className="jp-form-setting-explanation">{ __( 'This module has no configuration options' ) } </span>;
 			case 'akismet':
 			case 'backups':
-				return '' === module.configure_url ? null : (
+				return '' === module.configure_url ? (
+					<div>
+						{
+							module.module === 'akismet' ?
+								__( 'Let search engines and visitors know that you are serious about your websites integrity by upgrading Jetpack. Our anti-spam tools will eliminate comment spam, protect your SEO, and make it easier for visitors to stay in touch..' )
```
Comment (oskosk) [inline _inc/client/components/module-settings/modules-per-tab-page.jsx]: Extra dot here at the end

File: _inc/client/components/module-settings/modules-per-tab-page.jsx [hunk 2]
```diff
@@ -55,7 +55,13 @@ export const AllModuleSettings = React.createClass( {
 			case 'monitor':
 				return ( <MonitorSettings module={ module } { ...this.props } /> );
 			case 'scan':
-				return '' === module.configure_url ? null : (
+				return '' === module.configure_url ? (
+					<div>
+						{
+							__( 'Upgrade Jetpack and our state-of-the-art security scanner will hunt out malicious files and report them immediately so that you’re never unaware of what is happening on your website.' )
```
Comment (oskosk) [inline _inc/client/components/module-settings/modules-per-tab-page.jsx]: There's a weird quote here in `we're`. I think it should be replaced by regular quote

**Comment by oskosk** [comment]
LGTM and works as expected. Left a few comments on the code about characters. 

🚢

File: _inc/client/components/module-settings/modules-per-tab-page.jsx (hunk 2 above)
Comment (samhotchkiss) [inline _inc/client/components/module-settings/modules-per-tab-page.jsx]: Agreed!
