### PR TITLE
Settings  UI: allow non admins to use AtD, PbE and Publicize

### LINKED ISSUE #6475: Settings UI: non-admins need love too
#### Steps to reproduce the issue
Activate all modules `wp jetpack module activate all` & sign in as an editor.

#### What I expected
I expected to see the settings available at the user level.  These include: 
- Publicize
- After the Deadline
- Post by email

screen shot 2017-02-22 at 10 31 11 am
screen shot 2017-02-22 at 10 31 38 am

#### What happened instead
I don't see any settings. 

screen shot 2017-02-22 at 10 32 21 am

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #6475

#### Changes proposed in this Pull Request:

* allow non admin to use After the Deadline, Post by Email, and, if Publicize is active, display the Sharing tab. This tab is not visible when only Sharing is active because it gives non admins the ability to change the appearance of the site and that's only something admins should do.

* extend GUI tests to verify that a non admin can access After the Deadline settings group, the Post by Email settings card. If Publicize is active, display the Sharing tab.

* if  user is unlinked, hide Sharing tab and block PbE settings card

* don't show main toggles when user can't manage modules

* the `/settings` endpoint was updated. There was an issue where it wasn't allowing non-admins to set AtD options or regenerate PbE address.

* if user is subscriber, don't show the notice "You are currently running a development version of Jetpack"

* when AtD or PbE are disabled don't show their card in settings available to non admins.

* if AtD and PbE are disabled, a message explaining why the tab is empty will be shown to non admins.

* if non admin is unlinked, display a clickable card explaining that PbE is disabled because the account needs to be linked

#### Testing instructions:

* log in as a non-admin and make sure you can see AtD and PbE. If Publicize is active, you should see the Sharing tab.
* contributors must not have the Sharing tab available
* disable AtD or PbE (not both), the disabled feature should no longer display a card for non admins
* disable both AtD and PbE, cards should not be displayed for non admins and instead a message should be displayed
* with PbE active, if user is unlinked, a message should be displayed below the card prompting user to link.

### CODE REVIEW

File: _inc/client/components/settings-card/index.jsx [hunk 1]
```diff
@@ -26,35 +27,42 @@ import Banner from 'components/banner';
...
-		header = props.header
-			? props.header
-			: '',
-		isSaving = props.isSavingAnyOption(),
+			: false;
+
+	// Non admin users only get Publicize, After the Deadline, and Post by Email settings. The UI doesn't have settings for Publicize.
+	// composing is not a module slug but it's used so the Composing card is rendered to show AtD.
+	if ( ! props.userCanManageModules && ! includes( [ 'composing', 'post-by-email' ], props.module ) ) {
+		return <span />;
```
Comment (zinigor) [inline _inc/client/components/settings-card/index.jsx]: To avoid unneeded elements let's `return null` here, this improves processing time as well because there's no need to create an empty element.

File: _inc/client/components/settings-group/index.jsx [hunk 2]
```diff
@@ -17,8 +18,15 @@ import { userCanManageModules, isSitePublic } from 'state/initial-state';
...
 
 export const SettingsGroup = props => {
-	const module = props.module,
-		disableInDevMode = props.disableInDevMode && props.isUnavailableInDevMode( module.module ),
+	const module = props.module;
+
+	// Non admin users only get Publicize, After the Deadline, and Post by Email settings. The UI doesn't have settings for Publicize.
+	// composing is not a module slug but it's used so the Composing card is rendered to show AtD.
+	if ( module.module && ! props.userCanManageModules && ! includes( [ 'after-the-deadline', 'post-by-email' ], module.module ) ) {
+		return <span />;
```
Comment (zinigor) [inline _inc/client/components/settings-group/index.jsx]: Same here, let's `return null`.

**Comment by zinigor** [comment]
Here's what I get when I try to regenerate the email address:
regen-error

File: _inc/client/components/settings-card/index.jsx (hunk 1 above)
Comment (eliorivero) [inline _inc/client/components/settings-card/index.jsx]: That would be possible if we were using React 15 which allows this in stateless components. It's not possible in .14 that we're currently using.

**Comment by eliorivero** [comment]
The PbE and Sharing tabs are based on user link, I've got to update that. I forgot to switch the labels to In Progress last Friday, sorry.

File: _inc/client/components/settings-card/index.jsx (hunk 1 above)
Comment (zinigor) [inline _inc/client/components/settings-card/index.jsx]: Yes, I see now, nevermind that then.

**Comment by eliorivero** [comment]
captura de pantalla 2017-03-06 a las 16 35 20

This is now updated:
- don't show Sharing tab and when user is unlinked
- PbE settings card is blocked when user is unlinked
- it doesn't show main toggles when user can't manage modules
- the `/settings` endpoint was updated. There was an issue where it wasn't allowing non-admins to set AtD options or regenerate PbE address.

**Comment by dereksmart** [comment]
This is the view for an unlinked `subscriber`.  We probably shouldn't be showing any settings tabs at all for this role.  

screen shot 2017-03-09 at 4 00 58 pm

**Comment by dereksmart** [comment]
When unlinked contributor, PBE is greyed out but I have no idea why (as a user). 
screen shot 2017-03-09 at 4 03 37 pm

We should probably say something like we do in wp-admin settings area: 
screen shot 2017-03-09 at 4 04 57 pm

**Comment by dereksmart** [comment]
With PBE and AtD _disabled_, I can still see the settings areas as a contributor.  Maybe we should hide them, since it may be unclear to them why they can't use them.  

screen shot 2017-03-09 at 4 06 28 pm

**Comment by eliorivero** [comment]
Updated: if user is subscriber, don't show the notice "You are currently running a development version of Jetpack"

**Comment by eliorivero** [comment]
Updates:

- when AtD or PbE are disabled don't show their card in settings available to non admins. In the example below, AtD is disabled so its card is not visible.

captura de pantalla 2017-03-14 a las 14 21 18

- if AtD and PbE are disabled, a message explaining why the tab is empty will be shown to non admins.

captura de pantalla 2017-03-14 a las 14 21 50

**Comment by eliorivero** [comment]
Updates:

- if non admin is unlinked, display a clickable card explaining that PbE is disabled because the account needs to be linked

captura de pantalla 2017-03-14 a las 15 25 29

**Comment by dereksmart** [comment]
This is looking really good.  The only thing I can find that's broken is that subscribers are not able to view stats if admin's have chosen to show them in Stats Settings.

**Comment by eliorivero** [comment]
It's fixed now, thank you!
