### PR TITLE
Masterbar: fix admin menu upsell banner layout shift

### LINKED ISSUE #87509: Delayed layout shift in wp-admin when upsell banner is injected
### Quick summary

👋🏻 There have been a few times recently when I've needed to repetitively shift between the front-end and admin views while testing some workflows.

On the front-end of the site, I'll hover over the site name, click dashboard, and then immediately move my mouse to where I see the "Posts" menu item and click.

But! That click happens milliseconds after a "Free domain available" upsell banner is injected into the menu. The entire navigation shifts down by 56px and I end up in the WordPress.com stats viewer instead of the list of posts.

The site is in development, so I can't show a video of the full front/back end, but here's a clip of the relevant section:

CleanShot 2024-02-15 at 10 02 44 2

Every time I refresh the page, it starts without the upsell banner and then shifts to include it.

### Steps to reproduce

1. Start on https://example.org
2. Navigate to https://example.org/wp-admin/
3. Try to click on Posts

### What you expected to happen

Ideally, the upsell banner is placed in a way that does not cause layout shift.

Or maybe: I have a way to enable developer mode where I'm not shown upsells while working on others' sites.

### What actually happened

The navigation layout shifted.

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

I'm using Firefox 122.0.1 on macOS 12.7.2

### PR DESCRIPTION
**Pull request by arcangelini**
Fixes https://github.com/Automattic/wp-calypso/issues/87509

## The Problem

When you load `/wp-admin` there is an upsell banner that appears after page load which is really annoying. This bumps the entire menu down and often causes me to click the wrong link. There was a PR that addressed this in the jetpack-mu-wpcom plugin, but this is not being used when a site chooses the "Default" Admin Interface Style from the general site settings.

### Before
https://github.com/user-attachments/assets/68c2e29e-a334-4465-9ce4-a4c8263d32ed

### After
https://github.com/user-attachments/assets/1f8d996a-0fbd-4aa7-a813-36eedd17e1b9

Applies the same approach from #41480 to the masterbar package:

- Replaced the `wp_ajax_upsell_nudge_jitm` AJAX handler with a `render_upsell_nudge()` method that renders the banner HTML directly via the `adminmenu` hook (priority 100)
- Uses an inline script to instantly move the banner to the top of `#adminmenu` before the browser paints (same technique as #41480)
- Skips rendering when jetpack-mu-wpcom is already handling the banner (detected via `has_action()` on `wpcom_add_sidebar_notice_menu_page`)
- Removed the `wpcom-upsell-nudge-jitm-fix.js` MutationObserver (no longer needed since there is no async DOM insertion)
- Removed the AJAX fetch call from `admin-menu.js` (dismiss handler remains intact)
- Removed the `upsellNudgeJitm` nonce from localized script data

## Does this pull request change what data or activity we track or use?
No

## Testing instructions:
1. Go to `/wp-admin/options-general.php` and set `Admin Interface Style` to "Default WordPress.com" and SAVE.
2. Go to `/wp-admin` and make sure the upsell banner loads with the page rather than after. There should be no flash load.
3. Change the admin interface to Classic and make sure this is also working.
4. Verify the scrollbar behaves correctly when the banner is present (no extra scrollbar appearing).

### CODE REVIEW

**Comment by arcangelini** [comment]
I added @ellatrix and @arthur791004 just because yall tested/created the original fix so I figured it could be a quick look for y'all 🙏

File: projects/packages/masterbar/src/admin-menu/class-wpcom-admin-menu.php [hunk 1]
```diff
@@ -31,8 +31,7 @@ protected function __construct() {
 
 		add_action( 'wp_ajax_sidebar_state', array( $this, 'ajax_sidebar_state' ) );
 		add_action( 'wp_ajax_jitm_dismiss', array( $this, 'wp_ajax_jitm_dismiss' ) );
-		add_action( 'wp_ajax_upsell_nudge_jitm', array( $this, 'wp_ajax_upsell_nudge_jitm' ) );
-		add_action( 'admin_enqueue_scripts', array( $this, 'wpcom_upsell_nudge_jitm_fix' ) );
+		add_action( 'adminmenu', array( $this, 'render_upsell_nudge' ), 100 );
```
Comment (arcangelini) [inline projects/packages/masterbar/src/admin-menu/class-wpcom-admin-menu.php:34]: This is all being run in a mu-plugin so we should have priority, but this adds a little safety JIC

**Review by arthur791004 — APPROVED** [review]
Looks good to me 👍

`wpcom_add_sidebar_notice_menu_page` did the same thing to add the notice so I think the changes make sense.
