### PR TITLE
Carousel: Fixes single image galleries loaded from infinite scroll

### LINKED ISSUE #6305: Carousel: Single image carousel doesn't when post loaded from infinite scroll
In Jetpack 4.5, we added support to open single images in a gallery, as long as the image was linked to the attachment page.

This works well when on the single post view or on the front page of my blog. But, after scrolling and loading more posts through infinite scroll, and then clicking on a single image that is on the second page of results, clicking on the single image takes me to the actual attachment page. 

I would expected that clicking the single image, even on the second page of posts, would load the gallery.

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #6305.

In #6305, I pointed out an issue where single image galleries did not work when loaded through infinite scroll. This PR fixes that.

The solution here was to factor out the logic that adds the `single-image-gallery` class into a function, then call that when the JS file is initially loaded as well as when new posts are loaded.

To test:

- Ensure you have posts with single image galleries in the front page and second page of your blog archive
- Click the first image and ensure gallery opens
- Scroll until infinite scroll loads second page
- Click the image in the second post and ensure gallery opens

### CODE REVIEW

**Comment by dereksmart** [comment]
Just needs a rebase

**Comment by zinigor** [comment]
Rebase in progress...

File: modules/carousel/jetpack-carousel.js [hunk 1]
```diff
@@ -435,6 +435,42 @@ jQuery(document).ready(function($) {
...
+
+			// skip if image was already added to gallery by shortcode
+			if( container.parent( '.gallery-icon' ).length ) {
+				return;
+			}
+
+			var valid = false;
+
+			// if link points to 'Media File' (ignoring GET parameters) and flag is set allow it
+			if ( $( container ).attr( 'href' ).split( '?' )[0] === $( this ).attr( 'data-orig-file' ).split( '?' )[0] &&
```
Comment (zinigor) [inline modules/carousel/jetpack-carousel.js]: @thingalon I have ported your changes from #6296 into this PR, can you please take a look?
