### PR TITLE
Change the Contact Form "Empty Spam" button to empty the spam in batches so the page doesn't time out when there's a lot of spam.

### LINKED ISSUE #15661: Emptying feedback Spam when there are a lot of spam feedbacks can fail due to a timeout.
When there are hundreds of spam feedbacks, clicking "Empty Spam" can lead to a timeout, and even though the deletion process can continue, it stops after processing about 400 feedbacks.

#### Steps to reproduce the issue

1. Amass a thousand spam feedbacks
2. Go to /wp-admin/edit.php?post_status=spam&post_type=feedback
3. Click "Empty Spam"
4. Wait
5. The page will likely lead to an error page.

#### What I expected

All spam feedbacks would be removed.

#### What happened instead

Only a couple hundred feedbacks were removed, and I saw an error page.

#### Solution

Change the "Empty Spam" button to function like the "Check for Spam" button that Akismet adds to the Comments page. It processes comments in batches, so it avoids timing out, and it reports its progress, so it's clear how long it will take. I'll plan on working on a pull request for this.

### PR DESCRIPTION
**Pull request by cfinke**
This is modeled after how the "Check for Spam" button in Akismet (and also the Jetpack Contact Form admin page) functions.

Fixes #15661

#### Changes proposed in this Pull Request:

* This changes the "Empty Spam" button from performing a simple POST request that deletes all spam feedbacks to a button that initiates a series of AJAX requests to delete spam in batches of 25.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?

This improves an existing part of Jetpack.

#### Testing instructions:

1. Amass a thousand spam feedbacks
2. Go to /wp-admin/edit.php?post_status=spam&post_type=feedback
3. Click "Empty Spam"
4. Wait
5. The page will likely time out or lead to an error page.

Apply the patch.

1. Amass a thousand spam feedbacks
2. Go to /wp-admin/edit.php?post_status=spam&post_type=feedback
3. Click "Empty Spam"
4. Observe that the button changes to say "Emptying Spam (0%)" along with a loading indicator.
5. Observe that the button updates with the progress percentage as spam is deleted.
6. The page should reload/redirect to the "All" feedbacks page after the spam is emptied.

Also test that reloading the page while the spam is being emptied does show that the spam folder has been partially emptied.

#### Proposed changelog entry for your changes:
* Improve the "Empty Spam" process for the Contact Form so that it does not time out on large spam folders.

### CODE REVIEW

File: modules/contact-form/admin.php [hunk 1]
```diff
@@ -902,3 +940,65 @@ function grunion_recheck_queue() {
...
+		return;
+	}
+
+	$query = 'post_type=feedback&post_status=spam';
+
+	if ( isset( $_POST['limit'] ) ) {
+		$query .= '&posts_per_page=' . intval( $_POST['limit'] );
+	}
+
+	$spam_feedbacks = get_posts( $query );
```
Comment (jeherve) [inline modules/contact-form/admin.php:964]: I wonder if we should tighten this a bit, use `WP_Query`, and always provide a limit to avoid having too big queries? Something like this:

```php
$number_to_delete = absint( $_POST['limit'] );
if ( 1 > $number_to_delete ) {
		$number_to_delete  = 20;
} elseif ( 100 < $number_to_delete ) {
	// Let's avoid processing too many at a time.
	$number_to_delete = 100;
}

$query_args     = array(
	'post_type'      => 'feedback',
	'post_status'    => 'spam',
	'posts_per_page' => $number_to_delete,
);
$spam_feedbacks = new WP_Query( $query_args );
```

File: modules/contact-form/admin.php [hunk 2]
```diff
@@ -902,3 +940,65 @@ function grunion_recheck_queue() {
...
+	if ( ! wp_verify_nonce( $_POST['nonce'], 'jetpack_delete_spam_feedbacks' ) ) {
+		wp_send_json(
+			array(
+				'error' => __( 'You don&#8217;t have permission to do that.', 'jetpack' ),
+			)
+		);
+
+		return;
+	}
+
```
Comment (jeherve) [inline modules/contact-form/admin.php:957]: Should we check for capabilities here, before we go any further and query for feedback posts?

File: modules/contact-form/admin.php [hunk 3]
```diff
@@ -148,17 +146,43 @@ function grunion_add_empty_spam_button() {
...
+			var jetpack_empty_spam_feedbacks_spinner = $( '<span />' )
+				.addClass( 'jetpack-empty-spam-spinner' )
+				;
+
+			jetpack_empty_spam_feedbacks_button_container.append( jetpack_empty_spam_feedbacks_spinner );
+
+			// Add the button both above and below the list of spam feedbacks.
+			$( '.tablenav.top .actions, .tablenav.bottom .actions' ).not( '.bulkactions' ).append( jetpack_empty_spam_feedbacks_button_container );
+		} );
+	</script>
```
Comment (jeherve) [inline modules/contact-form/admin.php:185]: Part of me wonders if it wouldn't be cleaner to build the button in `grunion-admin.js` right away, and rely on `wp_localize_script` for all the variables. What do you think?

File: modules/contact-form/admin.php [hunk 4]
```diff
@@ -902,3 +940,65 @@ function grunion_recheck_queue() {
...
+/**
+ * Delete a number of spam feedbacks via an AJAX request.
+ */
+function grunion_delete_spam_feedbacks() {
+	if ( ! wp_verify_nonce( $_POST['nonce'], 'jetpack_delete_spam_feedbacks' ) ) {
+		wp_send_json(
+			array(
+				'error' => __( 'You don&#8217;t have permission to do that.', 'jetpack' ),
+			)
+		);
```
[the remark this answers is not in the document]
Comment (cfinke) [reply modules/contact-form/admin.php]: Good call; I've fixed this in a7b488616.

File: modules/contact-form/admin.php (hunk 1 above)
Comment (cfinke) [reply modules/contact-form/admin.php]: I've updated this in 3696f911e to eliminate the $_POST['limit'] parameter altogether, since it wasn't really necessary.  I've also switched it to use WP_Query and put a limit on the number of feedbacks that can be selected, since the limit is now configurable via a filter.

File: modules/contact-form/admin.php (hunk 2 above)
Comment (cfinke) [reply modules/contact-form/admin.php:956]: Do you think it's reasonable to replace the `current_user_can( 'delete_post', $feedback->ID )` calls below with a single `current_user_can( 'delete_posts' )` here?  Or maybe `delete_others_posts` is more appropriate?

File: modules/contact-form/admin.php (hunk 3 above)
Comment (cfinke) [reply modules/contact-form/admin.php]: Good call; I've done so in 78123282f.

File: modules/contact-form/admin.php [hunk 5]
```diff
@@ -902,3 +907,73 @@ function grunion_recheck_queue() {
...
+			403
+		);
+
+		return;
+	}
+
+	$deleted_feedbacks = 0;
+
+	$delete_limit = 25;
+	$delete_limit = apply_filters( 'jetpack_delete_spam_feedbacks_limit', $delete_limit );
```
Comment (jeherve) [inline modules/contact-form/admin.php:927]: Let's add a docblock here so the parser can create a Codex page from this:

```suggestion
	/**
	 * Filter the amount of Spam feedback one can delete at once.
	 *
	 * @module contact-form
	 *
	 * @since 8.6.0
	 *
	 * @param int $delete_limit Number of spam to process at once. Default to 25.
	 */
	$delete_limit = apply_filters( 'jetpack_delete_spam_feedbacks_limit', $delete_limit );
```

File: modules/contact-form/admin.php (hunk 2 above)
Comment (jeherve) [reply modules/contact-form/admin.php:923]: Yeah, that would make sense and simplify things even more 👍. `delete_others_posts` seems fine here.

Comment (cfinke) [reply modules/contact-form/admin.php:923]: I made the change in a786416b4.

File: modules/contact-form/admin.php [hunk 6]
```diff
@@ -902,3 +907,82 @@ function grunion_recheck_queue() {
...
+
+	$deleted_feedbacks = 0;
+
+	$delete_limit = 25;
+	/**
+	 * Filter the amount of Spam feedback one can delete at once.
+	 *
+	 * @module contact-form
+	 *
+	 * @since 8.6.0
```
Comment (jeherve) [inline modules/contact-form/admin.php:941]:
```suggestion
	 * @since 8.7.0
```
