### PR TITLE
Contact form: remove double quotes in names in email headers

### LINKED ISSUE #7350: Contact-Form quotes "To:" and "Reply-To:" fields when PHP documentation does not
#### Steps to reproduce the issue

Read or run any of these tests:

* [pre_test_process_submission_sends_correct_single_email](https://github.com/Automattic/jetpack/blob/31818315b48a8a867d259c9de91287940763d930/tests/php/modules/contact-form/test_class.grunion-contact-form.php#L331)
* [pre_test_process_submission_sends_correct_multiple_email](https://github.com/Automattic/jetpack/blob/31818315b48a8a867d259c9de91287940763d930/tests/php/modules/contact-form/test_class.grunion-contact-form.php#L368)

#### What I expected

According to the [PHP documentation for `mail`](http://php.net/manual/en/function.mail.php), the "name" part of the mailbox should not be quoted, even when there is whitespace (note the fourth example, where `Another User <anotheruser@example.com>` is represented without quotes. This implies that their "RFC2822-compliant formatting" is actually not compliant, but that's what we're playing with here.

Given that PHP's mail function only gives examples without quotes, I expect that there should be no quotes around the `display-name` portion of the the mailbox.

This matters because somewhere between Jetpack and the `mail` function, the double-quote gets mangled into a form that gets communicated incorrectly. You can see how this looks in GMail in the following screenshot.

Example mangled To and Reply-To

_NB: Since the "name" part of the mailbox is a `dot-atom` according to RFC2822, it should not be represented as a `quoted-string` (see the first paragraph of [section 3.4.1 of RFC2822](http://www.faqs.org/rfcs/rfc2822.html)). This means that the contact form implementation of RFC2822 is incorrect as well since `john@example.com` is a dot-atom._

#### What happened instead

The contact form _always_ uses the `quoted-string` version of name, i.e. `"Sally User" <sally@example.com>`. This gets mangled into the following: `To: \"\\\"Sally User\\\"\" <sally@example.com>`, which is unparsable by the mail agent.

I have attached [an output of an `strace`](https://github.com/Automattic/jetpack/files/1078042/strace.txt) showing what it looks like when sent to the mail agent.

The root cause is in two places:

* [add_name_to_address](https://github.com/Automattic/jetpack/blob/0ff86590990c28b185e959fd9aed9fca0b4db85e/modules/contact-form/grunion-contact-form.php#L2249-L2256)
* [headers concatenation](https://github.com/Automattic/jetpack/blob/0ff86590990c28b185e959fd9aed9fca0b4db85e/modules/contact-form/grunion-contact-form.php#L2019-L2020)

/cc @splitinfinities

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #7350

#### Changes proposed in this Pull Request:

In this PR, we remove the double quotes around names in email headers for emails sent via the Contact form module (e.g. `"Jeremy Herve" <wordpress@example.com>`, where the double quotes  should not be neccesary).
`Jeremy Herve <wordpress@example.com>` should be enough.

For more background around this, see the discussion in the original issue, #7350.

#### Jetpack product discussion

* Internal references: 3921793-zen, 6569-gh-jpop-issues

#### Does this pull request change what data or activity we track or use?

* No

#### Testing instructions:

This may prove a bit tricky, as we'll need to test in different configurations to be sure this doesn't break things.

1. Go to Pages > Add New
1. Add a new contact form to your post content.
1. In the form settings, ensure the form is set to be sent to an email address you control.
1. Publish the page.
1. View the page, and submit a test form.
1. Ensure you receive the email from WordPress.
1. Copy the original full email contents.
1. Paste them [here](https://spamcheck.postmarkapp.com/), and ensure you get no errors.

One could also check when using a plugin like [this one](https://wordpress.org/plugins/mailin/) to send out the emails.

### CODE REVIEW

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php [hunk 1]
```diff
@@ -2842,8 +2842,13 @@ function process_submission() {
...
 
-		$headers = 'From: "' . $comment_author . '" <' . $from_email_addr . ">\r\n" .
-		           'Reply-To: "' . $comment_author . '" <' . $reply_to_addr . ">\r\n";
+		$headers = sprintf(
+			'From: %1$s <%2$s>%4$sReply-To: %1$s <%3$s>%4$s',
+			$comment_author,
+			$from_email_addr,
+			$reply_to_addr,
+			"\r\n"
+		);
```
Comment (jeherve) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2851]: I had to do more than just remove the quotes here to avoid phpcs warnings on the indenting, that would stop me from committing.

Comment (anomiex) [inline projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2851]: Why are you passing the "\r\n" in as a parameter instead of including it in the string?
```suggestion
		$headers = sprintf(
			"From: %1\$s <%2\$s>\r\nReply-To: %1\$s <%3\$s>\r\n",
			$comment_author,
			$from_email_addr,
			$reply_to_addr
		);
```
Or if you don't like having to escape the `$`, go closer to the original code with fixed indenting:
```suggestion
		$headers = 'From: ' . $comment_author . ' <' . $from_email_addr . ">\r\n" .
			'Reply-To: ' . $comment_author . ' <' . $reply_to_addr . ">\r\n";
```

**Review by anomiex — COMMENTED** [review]
I have a feeling we might run into something (PHP? WordPress?) trying to be too smart for its own good.

A quoted string is valid here: [RFC 5322 § 3.4](https://tools.ietf.org/html/rfc5322#section-3.4) defines a `display-name` as a `phrase`, which is defined in [§ 3.2.5](https://tools.ietf.org/html/rfc5322#section-3.2.5) as consisting of 1 or more whitespace-separated `word`s with a `word` being an `atom` or a `quoted-string`.

From the linked bug, it seems something somewhere is expecting something else and is intending to convert it to a `quoted-string`, and seems to be broken. It'd be nice to understand the exact bounds of its brokenness. I'll try to look into that later today.

File: projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php (hunk 1 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php:2851]: I may have been trying to be too smart about it here. :) You're right. I'll go with solution 2, it's probably the more readable choice.

**Review by anomiex — APPROVED** [review]
So, PHP's `mail()` function is not trying to be smart. It passes through exactly the headers you give it. It does minimal processing of the `$to` parameter only to remove control characters.

WordPress's `wp_mail()` function is where all the attempted smartness happens. And it turns out that WordPress isn't really all that smart about it.

* For `From`, it assumes anything before the `<` is the from name, blindly strips all double quotes, runs it through a filter, then passes it to a copy of PHPMailer that will return it as either one or more `atom` words (with [RFC 2047](https://tools.ietf.org/html/rfc2047) applied, if applicable) or a single `quoted-string` word.
* For `To`, `CC`, `BCC`, and `Reply-To`, it just checks whether the string contains a pair of angle brackets and decides that anything before is the "name" and anything inside is the "address", and passes them on to PHPMailer without any further processing. Which is why it winds up doubling the quotes.

The real solution there would be to have WordPress use `PHPMailer::parseAddresses()` to correctly parse the addresses out of the values passed. But that would require callers construct the header fields correctly in the first place, which I doubt they do.

Case in point, Contact Form. Just slapping the string inside double-quotes isn't enough to be correct. In a plain printable-ASCII world you'd still have to escape any double-quotes and backslashes in the string. And in a modern Unicode world, you need to apply [RFC 2047](https://tools.ietf.org/html/rfc2047) to any "word" that contains a non-ASCII character.

So, as things stand currently, this PR probably does do the right thing: it passes the name through to `wp_mail()` without any attempt at escaping, so `wp_mail()`'s lack of correct unescaping will wind up doing the right thing. If WordPress ever does fix `wp_mail()`, though, it'd probably start breaking on edge cases. But how likely is that?

I might suggest adding a comment in here somewhere pointing out that we're relying on specific undocumented behavior out of `wp_mail()`, though. But if you don't want to, I won't insist.

**Comment by jeherve** [comment]
Thanks for digging into this, and for the thorough report. 🙇 

I've added a comment in 3897b325b12ab658966345cb45855f9e6dd862c8, linking to this PR and your explanation.

**Review by anomiex — APPROVED** [review]

**Comment by jeherve** [comment]
r225337-wpcom
