### PR TITLE
Slideshow: do not render markup when user doesn't select any images

### LINKED ISSUE #15273: Slideshow block: Don't output anything if the block is empty
#### Steps to reproduce the issue

1. Publish a post with empty slideshow block
2. Check frontend, the block markup will be present in DOM
3. Check frontend in the AMP view. Huge gray rectangle will be rendered

#### What I expected
No markup is added/generated for empty blocks

#### What happened instead
Some markup is added

(AMP view)
Jetpack blocks – Jetpack Tests Sakura 2020-04-03 13-16-05

### PR DESCRIPTION
**Pull request by cpapazoglou**
This PR resolves #15273, where adding a slideshow block, without selecting any image, results to obsolete markup in the frontend. Especially, in the case of AMP rendering there was an extra **visible** markup.

#### Changes proposed in this Pull Request:

* Return null when images array is empty so that no obsolete markup is rendered both for normal and AMP rendering

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

* Setup local jetpack env with ngrok tunneling as per [instructions](https://github.com/Automattic/jetpack/blob/master/docs/development-environment.md) 
* Install the AMP plugin By AMP Project Contributors here /wp-admin/plugin-install.php?s=amp&tab=search&type=term
* Go to /wp-admin/post-new.php
* Add a slideshow block AND do not select any image
* Save and visit the above post
* Visit the the same post by appending `/amp` to the URL to inspect how AMP renders

**Before**
CleanShot 2020-06-22 at 16 34 02

**After**
CleanShot 2020-06-22 at 16 36 09

**Before AMP**
CleanShot 2020-06-22 at 16 37 13

**After AMP**
CleanShot 2020-06-22 at 16 39 02

#### Proposed changelog entry for your changes:

* Slideshow: do not render markup when user doesn't select any images

#### Notices ####
The above changes will work for:
* new content both for normal and AMP rendering
* old content for AMP rendering

The above changes will **not** work for:
* old content for normal rendering

### CODE REVIEW

File: extensions/blocks/slideshow/slideshow.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ function render_amp( $attr ) {
 	);
 	$classes  = Jetpack_Gutenberg::block_classes( FEATURE_NAME, $attr, $extras );
 
-	return sprintf(
+	return empty( $ids ) ? null : sprintf(
```
Comment (obenland) [inline extensions/blocks/slideshow/slideshow.php:67]: That empty check should probably happen further up the function to bail early. According to function docs it also expects to always return a string.

File: extensions/blocks/slideshow/slideshow.js [hunk 2]
```diff
@@ -116,6 +116,12 @@ class Slideshow extends Component {
 
 	render() {
 		const { autoplay, className, delay, effect, images } = this.props;
+
+		// If user has not selected any images, don't print any markup.
+		if ( ! images.length ) {
```
Comment (retrofox) [inline extensions/blocks/slideshow/slideshow.js:121]: This could probably happen further up the function, too, before to understructure the `props` object. Also, not sure but maybe it worths check if `images` is `undefined`.

```es6
// check if images has items...
if ( ! this.props?.images?.length ) {
  return null;
}

// Now, time to understructure the object!
const { autoplay, className, delay, effect, images } = this.props;
```

Comment (cpapazoglou) [reply extensions/blocks/slideshow/slideshow.js:121]: Sure! Thanks !

File: extensions/blocks/slideshow/slideshow.php (hunk 1 above)
Comment (cpapazoglou) [reply extensions/blocks/slideshow/slideshow.php]: Sure, I return now `''`. I think it is preferred than having a mixed return?

**Comment by cpapazoglou** [comment]
r209584-wpcom
