### PR TITLE
Jetpack Setup Wizard: Fix setup page being blank after connection

### LINKED ISSUE #15936: Wizard: blank setup page following connection
#### Steps to reproduce the issue

0. In Chrome (we want the connect-in-place flow)
1. Start with a brand new Jurassic Ninja site
2. Under Jetpack > Beta, pick 8.6-beta in the "Search for a Jetpack tag" section
3. In a functionality plugin, add the following: 
```php
add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );
add_filter( 'jetpack_show_setup_wizard', '__return_true' );
```
4. Go to the Jetpack menu
5. Click tho connect the site to WordPress.com.
6. After the connection, you'll be redirected to the plans prompt page, `wp-admin/admin.php?page=jetpack#/plans-prompt`
7. Pick the free option at the bottom of the page (leading you to `wp-admin/admin.php?page=jetpack`
8. You'll be redirected to `wp-admin/admin.php?page=jetpack#/setup`
9. You'll see the page URL briefly flash to the intro route
10. You'll be redirected back to `wp-admin/admin.php?page=jetpack#/setup`
11. The page will be blank
```
react-dom.min.js?ver=16.9.0:103 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
```
https://reactjs.org/docs/error-decoder.html/?invariant=185

> Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

@robertf4 Do you think you can take a look?

Thanks!

### PR DESCRIPTION
**Pull request by robertf4**
Fixes #15936

#### Changes proposed in this Pull Request:

When a user visits `/wp-admin/admin.php?page=jetpack` and the state of the plugin is such that it redirects to `/wp-admin/admin.php?page=jetpack#/setup` there was an infinite loop causing React to crash and the page to be blank.

This was happening because the `useRouteMatch()` hook in `SetupWizardComponent` was returning `/*` for this case, even after the URL had been changed to `#/setup`.

To fix this I have just hardcoded `/setup`, as there is no real need to dynamically get the URL here since these routes are not expected to change dynamically.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* If you're an Automattician, include a shortlink to the p2 discussion with Jetpack Product here.

#### Testing instructions:

1. Add the following to your wp-config.php:
```
add_filter( 'jetpack_show_setup_wizard', '__return_true' );
add_filter( 'jetpack_pre_connection_prompt_helpers', '__return_true' );
```
2. Go through the connect flow.
3. Choose the free plan, which should take you to `/wp-admin/admin.php?page=jetpack`.
4. Verify that you are redirected to `/wp-admin/admin.php?page=jetpack/setup/intro`, and the setup wizard loads.

#### Proposed changelog entry for your changes:
None needed

### CODE REVIEW

File: _inc/client/setup-wizard/index.jsx [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * External dependencies
  */
 import React from 'react';
-import { Redirect, Route, Switch, useRouteMatch } from 'react-router-dom';
+import { Redirect, Route, Switch, useLocation, useRouteMatch } from 'react-router-dom';
```
Comment (kbrown9) [inline _inc/client/setup-wizard/index.jsx:5]: It looks like `useLocation` and `useRouteMatch` aren't used. Can they be removed?

```suggestion
import { Redirect, Route, Switch } from 'react-router-dom';
```

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.6` in 4b901056e2b579409a1d4980e033b3a195a4197d
