### PR TITLE
Related Posts: Revert "Removing enabled and published checks"

### LINKED ISSUE #11546: Related Posts: Enable filter no longer functional
#### Steps to reproduce the issue

I added this custom code long ago to hide related posts in WooCommerce products. It was taken from here: https://jetpack.com/support/related-posts/customize-related-posts/

```
function exclude_jetpack_related_from_products( $options ) {
if ( is_product() ) {
$options['enabled'] = false;
}
 
return $options;
}
 
add_filter( 'jetpack_relatedposts_filter_options', 'exclude_jetpack_related_from_products' );
```
It was working perfectly until the few latest updates of Jetpack.

#### What I expected
Not to see related posts in WooCommerce product pages.

#### What happened instead
I see related posts in WooCommerce product pages.

### PR DESCRIPTION
**Pull request by kraftbj**
Fixes #11546 

This commit regressed the fix added in #9495 and breaks the jetpack_relatedposts_filter_options filter's use of "enabled".

This reverts commit 237c30f0a281e572b961cc9b057bd375ff479749.

#### Changes proposed in this Pull Request:
* Replace the enabled and publish post checks.

#### Testing instructions:
* On a Jetpack site with RPs enabled and RPs displaying as normal.
* Try the filter in 11546, except remove the conditional to return false always.
* Do RPs show? If not, good.

#### Proposed changelog entry for your changes:
* Related Posts: Restore use of the jetpack_relatedposts_filter_options filter and prevent HTTP errors when editing drafts in the Block Editor.

cc: @aldavigdis

### CODE REVIEW

**Comment by aldavigdis** [comment]
Hey @kraftbj — thanks for reaching out! — I am going to review and test the PR today.

**Comment by kraftbj** [comment]
@aldavigdis Just checking in on this since code freeze is EOD Monday. Thanks!

File: modules/related-posts/jetpack-related-posts.php [hunk 1]
```diff
@@ -796,7 +796,7 @@ public function get_for_post_id( $post_id, array $args ) {
 			$options['size'] = $args['size'];
 		}
 
-		if ( 0 === (int) $post_id || empty( $options['size'] ) ) {
```
Comment (enejb) [inline modules/related-posts/jetpack-related-posts.php]: Can we break it down to a few lines so that it is easier to understand. 

Maybe something like:
```
if (
 ! $options['enabled'] 
|| 0 === (int)$post_id 
|| empty( $options['size'] ) 
|| ( $post_id && get_post_status( $post_id ) !== 'publish' )
) {
```

Comment (kraftbj) [reply modules/related-posts/jetpack-related-posts.php]: Addressed in 5fdc6d700ec558dd644b44b1588b48a07462db37

**Review by jeherve — DISMISSED** [review]
This seems to work well for me. 👍

**Comment by kraftbj** [comment]
Re-added the removal of the publish check so RP previews work again and confirmed it does not cause a regression of #9494.

**Review by jeherve — APPROVED** [review]
still good. 👍

File: modules/related-posts/jetpack-related-posts.php [hunk 2]
```diff
@@ -796,19 +796,23 @@ public function get_for_post_id( $post_id, array $args ) {
...
+		if (
+			! $options['enabled']
+			|| 0 === (int) $post_id
```
Comment (eliorivero) [inline modules/related-posts/jetpack-related-posts.php]: Casting `$post_id` to `int` defeats the purpose of the strict comparison operator.

**Comment by eliorivero** [comment]
Left a comment about the casting.

File: modules/related-posts/jetpack-related-posts.php (hunk 2 above)
Comment (kraftbj) [reply modules/related-posts/jetpack-related-posts.php]: True, I'm going to leave it for a future PR since that was pre-existing.

Comment (kraftbj) [reply modules/related-posts/jetpack-related-posts.php]: https://github.com/Automattic/jetpack/issues/11683
