### PR TITLE
[Boost] Fix toggling Image Guide from requesting page speed refresh

### LINKED ISSUE #28255: [Boost] Toggling Image Guide on/off causes page speed to refresh
### Impacted plugin

Boost

### Steps to Reproduce

1. Install bleeding edge of Jetpack Boost and get Image Guide up and running (pc9hqz-1sC-p2)
2. Go to Boost settings page
3. Make sure a Page Speed request isn't running
4. Toggle Image Guide
5. Check Page Speed UI to see that a request is running

### A clear and concise description of what you expected to happen.

Toggling Image Guide on or off shouldn't cause Page Speed to re-run.

### What actually happened

Toggling Image Guide on or off causes Page Speed to re-run.

### Browser

Google Chrome/Chromium

### Other information

https://user-images.githubusercontent.com/11799079/211555094-8bba7d33-5803-48a2-ac34-179602c36e00.mov

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

### Workaround details

I imagine all UI options cause a page speed refresh, as they are directly linked to page speed. Excluding the Image Guide option from that list should solve the problem.

### PR DESCRIPTION
**Pull request by dilirity**
Fixes #28255.

## Proposed changes:

* These changes should prevent page speed refresh requests when enabling/disabling Image Guide from the settings page.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

N/A

## Does this pull request change what data or activity we track or use?

No.

## Testing instructions:

* Setup latest version of Jetpack Boost with the Image Guide feature (pc9hqz-1sC-p2);
* Go to the Settings page and enable Image Guide. It shouldn't request a page speed scores refresh.

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte [hunk 1]
```diff
@@ -54,13 +54,17 @@
 	 */
 	const scoreConfigString = derived(
 		[ modules, criticalCssStatus ],
-		( [ $modules, $criticalCssStatus ] ) =>
-			JSON.stringify( {
-				modules: $modules,
+		( [ $modules, $criticalCssStatus ] ) => {
+			const scoreModules = Object.assign( {}, $modules );
+			delete scoreModules[ 'image-guide' ];
```
Comment (dilirity) [inline projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte:59]: I'm not very happy with this solution.

Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte:59]: I wanted to exclude the image guide module so a page speed refresh is no longer triggered, but I wasn't able to figure out how to do it properly.

Comment (haqadn) [reply projects/plugins/boost/app/assets/src/js/pages/settings/sections/Score.svelte:59]: This looks like the correct solution to me :)

**Review by haqadn — APPROVED** [review]
👍🏼
