### PR TITLE
VideoPress: Fix thumb selector error when video or site are private

### LINKED ISSUE #27397: VideoPress: thumbnail selector fails on library page if the video or the site is private
How to replicate:

* Upload one video
* Set it to private
* Click the "Update thumbnail" quick action
* Click the "Select from video" option
* A pop up box will open, but the video will not load so it's not possible to select a frame as the thumbnail

The issue will not happen if the video is public, as well as in the "Edit video details" page.

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #27397.

#### Changes proposed in this Pull Request:

* Changed the resolver to set the playback token on the video URL when the video needs it
* Changed the poster update action to set the token on the new poster URL when the poster needs it

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Let the browser console open to inspect errors and the network activity
* Turn on the "Video Privacy: Restrict views to members of this site" checkbox:

Screen Shot 2022-11-11 at 19 16 20

* Upload a new video
* Click the "Update thumbnail" quick action
* Click the "Select from video" option
* Before the fix, the video would not load and it was not possible to select a frame to set as the new thumb:

Screen Shot 2022-11-15 at 19 14 55

* After the fix, the video will load properly and a frame can be selected; also, the video will be loaded with a `playback_token` added to the URL:

Screen Shot 2022-11-15 at 18 50 39

* Choose some frame as the new thumbnail and then click the "Select this frame" button
* After the fix, the new thumbnail will load properly and will use a `playback_token` on the URL:

Screen Shot 2022-11-15 at 19 02 10

### CODE REVIEW

File: projects/packages/videopress/src/client/admin/components/edit-video-details/index.tsx [hunk 1]
```diff
@@ -159,7 +159,6 @@ const EditVideoDetails = () => {
 		description,
 		caption,
 		// Playback Token
-		playbackToken,
```
Comment (retrofox) [inline projects/packages/videopress/src/client/admin/components/edit-video-details/index.tsx:162]: 💯 All these stuff need to be handled at the data-handling level

**Review by retrofox — APPROVED** [review]
LGTM! 🚢 

The logic is getting tricky to follow, but I think it's part of the complexity inherent in the implementation. 
Some day, we should tidy, re-organize and document the whole implementation. Re-write in TS too.

**Comment by lhkowalski** [comment]
> Some day, we should tidy, re-organize and document the whole implementation.

@retrofox agreed!
