### PR TITLE
Carousel: improve detection of containers where we should add data

### LINKED ISSUE #13428: Tiled Gallery Block causes pointer cursor on every block that has nesting
#### Steps to reproduce the issue

1. Go to block editor
2. Insert a Tiled Gallery block and add some images
3. Insert any block that features nesting. E.g. Group, Columns, Media & Text.
4. Preview the page and observe that every nesting block has a `pointer` cursor

**Probably cause**

The gallery appears to change the container divs of every block containing child blocks, not just the tiled gallery itself, and adds `data-carousel-extra` with a few image properties. This on its own seems a bit overreachy, but the actual cursor happens because this CSS is output by Jetpack:

```
[data-carousel-extra] { cursor: pointer }
```

**Expected behavior**

Tiled Gallery should probably just affect itself.

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #13428

#### Changes proposed in this Pull Request:

Until now we would rely on 2 str_replace to add Carousel data to div and ul containers in post content.
This worked, but wasn't smart enough to know to ignore specific divs like Columns blocks.

By using DOMDocument, we can go through the post content in a more readable way, to detect gallery blocks as well as regular galleries and images.

#### Testing instructions:

* In a new post, insert a variety of blocks:
	- A classic block with a gallery
	- A classic block with a tiled gallery
	- A classic block with a single image  (still testing, but I think this may not work, neither with my branch or on the latest stable).
	- An image block (still testing, but I think this may not work, neither with my branch or on the latest stable).
	- A gallery block
	- A Tiled Gallery block
	- A column block with some text
	- A column block with a gallery block in it.
* Publish your post
* When moving your mouse over each block, make sure the cursor only becomes a pointer when the element can be expanded to a Carousel modal.

#### Proposed changelog entry for your changes:

* Carousel: improve detection of containers where we should add the Carousel modal.

### CODE REVIEW

File: modules/carousel/jetpack-carousel.php [hunk 1]
```diff
@@ -540,9 +540,50 @@ class_exists( 'Jetpack_AMP_Support' )
 			 * @param array $extra_data Array of data about the site and the post.
 			 */
 			$extra_data = apply_filters( 'jp_carousel_add_data_to_container', $extra_data );
+
 			foreach ( (array) $extra_data as $data_key => $data_values ) {
-				$html = str_replace( '<div ', '<div ' . esc_attr( $data_key ) . "='" . json_encode( $data_values ) . "' ", $html );
-				$html = str_replace( '<ul class="wp-block-gallery', '<ul ' . esc_attr( $data_key ) . "='" . json_encode( $data_values ) . "' class=\"wp-block-gallery", $html );
+				// Let's grab all containers from the HTML.
+				$dom_doc = new DOMDocument();
```
Comment (kraftbj) [inline modules/carousel/jetpack-carousel.php]: DOMDocument can be disabled, so should have a graceful fallback or bail out, e.g. https://github.com/Automattic/jetpack/blob/7.7/class.jetpack-post-images.php#L389

**Review by kraftbj — DISMISSED** [review]

File: modules/carousel/jetpack-carousel.php (hunk 1 above)
Comment (jeherve) [reply modules/carousel/jetpack-carousel.php]: 👍 	fef2a1a6b02b5af974adae7302306125bc34f14c

Comment (kraftbj) [reply modules/carousel/jetpack-carousel.php]: fef2a1a

File: modules/carousel/jetpack-carousel.php [hunk 2]
```diff
@@ -540,9 +540,57 @@ class_exists( 'Jetpack_AMP_Support' )
...
+				}
+
+				// Let's grab all containers from the HTML.
+				$dom_doc = new DOMDocument();
+
+				/*
+				 * The @ is not enough to suppress errors when dealing with libxml,
+				 * we have to tell it directly how we want to handle errors.
+				 */
+				libxml_use_internal_errors( true );
```
Comment (mdawaffe) [inline modules/carousel/jetpack-carousel.php]: `libxml_use_internal_errors()` returns the previous value, which we should store and use below.

```suggestion
				$old_libxml_use_internal_errors = libxml_use_internal_errors( true );
```

File: modules/carousel/jetpack-carousel.php [hunk 3]
```diff
@@ -540,9 +540,57 @@ class_exists( 'Jetpack_AMP_Support' )
...
+				@$dom_doc->loadHTML( $html ); // phpcs:ignore WordPress.PHP.NoSilencedErrors.Discouraged
+				libxml_use_internal_errors( false );
```
Comment (mdawaffe) [inline modules/carousel/jetpack-carousel.php]:
```suggestion
				libxml_use_internal_errors( $old_libxml_use_internal_errors );
```

File: modules/carousel/jetpack-carousel.php [hunk 4]
```diff
@@ -540,9 +540,57 @@ class_exists( 'Jetpack_AMP_Support' )
...
+
+				// Let's look for lists and divs.
+				$ul_tags  = $dom_doc->getElementsByTagName( 'ul' );
+				$div_tags = $dom_doc->getElementsByTagName( 'div' );
+
+				// Loop through each ul, and add the data to it if it is a gallery block.
+				foreach ( $ul_tags as $ul_tag ) {
+					if ( false !== strpos( $ul_tag->getAttribute( 'class' ), 'wp-block-gallery' ) ) {
+						$ul_tag->setAttribute(
+							esc_attr( $data_key ),
```
Comment (mdawaffe) [inline modules/carousel/jetpack-carousel.php]: We should not need to `esc_attr()` here.
```suggestion
						$data_key,
```

File: modules/carousel/jetpack-carousel.php [hunk 5]
```diff
@@ -540,9 +540,57 @@ class_exists( 'Jetpack_AMP_Support' )
...
+
+				/*
+				 * Loop through each div and add the data, only when it's a gallery block div.
+				 * We want to avoid adding data to divs like wp-block-columns.
+				 * We do however want data on divs like wp-block-jetpack-tiled-gallery.
+				 */
+				foreach ( $div_tags as $div_tag ) {
+					if (
+						false === strpos( $div_tag->getAttribute( 'class' ), 'wp-block-' )
+						|| false !== strpos( $div_tag->getAttribute( 'class' ), 'gallery' )
```
Comment (mdawaffe) [inline modules/carousel/jetpack-carousel.php]: Should this be `&&`?

As written, we add the attribute to all divs that are not `wp-block-` divs (including divs with no class at all).

File: modules/carousel/jetpack-carousel.php [hunk 6]
```diff
@@ -540,9 +540,57 @@ class_exists( 'Jetpack_AMP_Support' )
...
+					) {
+						$div_tag->setAttribute(
+							esc_attr( $data_key ),
```
Comment (mdawaffe) [inline modules/carousel/jetpack-carousel.php]:
```suggestion
						$data_key,
```

**Review by mdawaffe — DISMISSED** [review]
I don't think it strictly matters for this use case, but we should wrap the DOM usage in:

```php
$old_libxml_disable_entity_loader = libxml_disable_entity_loader( true );
// … DOM use
libxml_disable_entity_loader( $old_libxml_disable_entity_loader );
```

File: modules/carousel/jetpack-carousel.php (hunk 5 above)
Comment (jeherve) [reply modules/carousel/jetpack-carousel.php]: That's the current behaviour, I didn't want to change that. We currently add the attributes to all divs. With this change, it will be added to all divs, except if they include a class including `wp-block-`. The second parameter is here to add an additional exception: `wp-block-` is okay if it's a gallery block, like `wp-block-jetpack-tiled-gallery`.

Maybe there would be a more readable way to do that? Or should we instead move to more of a whitelist where we don't add the data to all the divs, but only to some specific ones?

Comment (kraftbj) [reply modules/carousel/jetpack-carousel.php]: I'd support keeping the behavior the way it is for the sake of the PR, but open an enhancement issue to explore refactoring it.

Comment (jeherve) [reply modules/carousel/jetpack-carousel.php]: Logged in #13499

**Review by kraftbj — APPROVED** [review]
I did some performance testing locally of the `the_content` filter before and after with a very large post (105k words, ~750k characters). There didn't seem to be a functional difference between them.

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.8` in 7e44a01de713252199ffd50544b6b015c1d1acfc
