### PR TITLE
Fix/5151 add in progress notice

### LINKED ISSUE #5151: Subscriptions/Publicize: Provide UI to confirm sub was successfully submitted
Within wp-admin, there is no indication that a post was successfully send to e-mail subscribers or Publicize services.

We should add one to help site admins get a better sense of where problems lie (exposing the failure data that wp.com has for a failed Pub connection or having a reasonable belief that WP.com sent the e-mails and that an issue might with a specific end user, etc).

I'd like to figure out a scope for this sooner rather than later so we can pinpoint an accurate milestone.

### PR DESCRIPTION
**Pull request by enejb**
Fixes #5151 

#### Changes proposed in this Pull Request:

* Add wording to publicize and subscription that tells the user that we are going to send emails to subscribers and publicize to the different accounts.

#### Testing instructions:
Set up publicize and subscriptions. 
You should now see the new notice in the wp-admin when you are publish a post.
screen shot 2018-03-21 at 4 41 32 pm

When you have publicize disabled. 
screen shot 2018-03-21 at 4 42 39 pm

When you have subscriptions disabled. (Note the grouping of the twitter account)
screen shot 2018-03-21 at 4 38 52 pm

### CODE REVIEW

File: modules/publicize/publicize.php [hunk 1]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
 
+	public function update_published_message( $messages ) {
+		global $post_type, $post_type_object, $post;
+		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
+			return $messages;
+		}
+		$view_post_link_html = '';
+		$viewable = is_post_type_viewable( $post_type_object );
+		if ( $viewable ) {
+			$view_text = __( 'View post' );
```
Comment (beaulebens) [inline modules/publicize/publicize.php]: Needs a textdomain.

Comment (enejb) [reply modules/publicize/publicize.php]: No I am intentionally sing the core text domain here. But that should be explained in a comment. :)

Comment (beaulebens) [reply modules/publicize/publicize.php]: 👍 I actually wondered that right after I commented :)

**Comment by bsessions85** [comment]
I tested this and confirmed that it works. I did notice it doesn't have translations, so I wanted to make note of that in case it should have them.

File: modules/publicize/publicize.php [hunk 2]
```diff
@@ -177,8 +178,8 @@ function get_profile_link( $service_name, $c ) {
 	/**
 	* Returns a display name for the connection
 	*/
-	function get_display_name( $service_name, $c ) {
-		$cmeta = $this->get_connection_meta( $c );
+	function get_display_name( $service_name, $connecton ) {
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Should it be `$connection` here?

File: modules/publicize/publicize.php [hunk 3]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+		global $post_type, $post_type_object, $post;
+		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
+			return $messages;
+		}
+		$view_post_link_html = '';
+		$viewable = is_post_type_viewable( $post_type_object );
+		if ( $viewable ) {
+			$view_text = __( 'View post' ); // intentinally omitted domain
+
+			if ( $post_type == 'jetpack-portfolio' ) {
```
Comment (jeherve) [inline modules/publicize/publicize.php]: I think we should use Yoda style here.

File: modules/publicize/publicize.php [hunk 4]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			}
+
+			$view_post_link_html = sprintf( ' <a href="%1$s">%2$s</a>',
+				esc_url( get_permalink( $post ) ),
+				$view_text
+			);
+		}
+
+		$services = $this->get_publicizing_services( $post->ID );
+		if( empty( $services ) ) {
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space before opening parenthesis here

File: modules/publicize/publicize.php [hunk 5]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			return $messages;
+		}
+
+		$labels = array();
+		foreach( $services as $service ) {
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space before opening parenthesis here

File: modules/publicize/publicize.php [hunk 6]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			$labels[] = sprintf(
+				_x( '%1$s: %2$s', 'Service: Account publicizing to', 'jetpack' ),
```
Comment (jeherve) [inline modules/publicize/publicize.php]: I think we would benefit from a translator comment here to make it clear what 1 and 2 are

File: modules/publicize/publicize.php [hunk 7]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+				esc_html(  $service['display_name'] )
+			);
+		}
+
+		$messages['post'][6] = sprintf(
+			_x( 'Post published and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+			implode(',', $labels ),
+			$view_post_link_html );
+
+		if ( $post_type == 'post' && class_exists('Jetpack_Subscriptions' ) ) {
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Yoda style here, and a missing space before opening parenthesis

File: modules/publicize/publicize.php [hunk 8]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+				$messages['post'][6] = sprintf(
+					_x( 'Post published, sending emails to subscribers and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+					implode(',', $labels ),
+					$view_post_link_html );
+			}
+		}
+
+		$messages['jetpack-portfolio'][6] = sprintf(
+			_x( 'Project published and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+			implode(',', $labels ),
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space here

File: modules/publicize/publicize.php [hunk 9]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			_x( 'Post published and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+			implode(',', $labels ),
+			$view_post_link_html );
+
+		if ( $post_type == 'post' && class_exists('Jetpack_Subscriptions' ) ) {
+			$subscription = Jetpack_Subscriptions::init();
+			if ( $subscription->should_email_post_to_subscribers( $post ) ) {
+				$messages['post'][6] = sprintf(
+					_x( 'Post published, sending emails to subscribers and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+					implode(',', $labels ),
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space here

File: modules/publicize/publicize.php [hunk 10]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			$labels[] = sprintf(
+				_x( '%1$s: %2$s', 'Service: Account publicizing to', 'jetpack' ),
+				esc_html( $service['service_name'] ),
+				esc_html(  $service['display_name'] )
+			);
+		}
+
+		$messages['post'][6] = sprintf(
+			_x( 'Post published and publicizing to %1$s. %2$s', 'Published Message: Accounts to publish to, link to view published post', 'jetpack' ),
+			implode(',', $labels ),
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space here

File: modules/publicize/publicize.php [hunk 11]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+	}
+
+	function get_publicizing_services( $post_id ) {
+		$services = array();
+
+		foreach ( (array) $this->get_services( 'connected' ) as $service_name => $connections ) {
+			// services have multiple connections.
+			foreach ( $connections as $connection ) {
+				$unique_id = '';
+				if ( !empty( $connection->unique_id ) )
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space here

File: modules/publicize/publicize.php [hunk 12]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+					$unique_id = $connection->unique_id;
+				else if ( !empty( $connection['connection_data']['token_id'] ) )
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing space here

File: modules/publicize/publicize.php (hunk 11 above)
Comment (jeherve) [inline modules/publicize/publicize.php]: Can we use braces here, as per https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

File: modules/publicize/publicize.php [hunk 13]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+					$unique_id = $connection['connection_data']['token_id'];
+
+				// Did we skip this connection?
+				if ( get_post_meta( $post_id, $this->POST_SKIP . $unique_id,  true ) ) {
+					continue;
+				}
+
+				$services[] = array(
+					'service_name' => $this->get_service_label( $service_name ),
+					'display_name' => $this->get_display_name( $service_name, $connection )
```
Comment (jeherve) [inline modules/publicize/publicize.php]: Missing comma at the end of the declaration here

**Comment by designsimply** [comment]
Nitpick: would it be more friendly to say "sharing" instead of "publicizing"? I noticed we tend to say "sharing" elsewhere. (No need to hold up shipping for this comment imo though.)

screen shot 2018-03-20 at tue mar 20 11 09 11 am
<sup>Seen at https://fancy-finfoot-485.jurassic.ninja/wp-admin/admin.php?page=jetpack#/sharing using Firefox 59.0.1 on macOS 10.13.3.</sup>

File: modules/publicize/publicize.php [hunk 14]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
 
+	public function update_published_message( $messages ) {
+		global $post_type, $post_type_object, $post;
+		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
+			return $messages;
+		}
+		$view_post_link_html = '';
+		$viewable = is_post_type_viewable( $post_type_object );
+		if ( $viewable ) {
+			$view_text = __( 'View post' ); // intentinally omitted domain
```
Comment (lezama) [inline modules/publicize/publicize.php]: intentionally

File: modules/publicize/publicize.php [hunk 15]
```diff
@@ -107,6 +107,7 @@ function __construct() {
 		// then check meta and publicize based on that. stage 3 implemented on wpcom
 		add_action( 'transition_post_status', array( $this, 'flag_post_for_publicize' ), 10, 3 );
 		add_action( 'save_post', array( &$this, 'save_meta' ), 20, 2 );
+		add_filter( 'post_updated_messages', array( &$this, 'update_published_message' ), 20, 1 );
```
Comment (lezama) [inline modules/publicize/publicize.php]: why do we do `&this`?

File: modules/publicize/publicize.php [hunk 16]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+		if ( empty( $services ) ) {
+			return $messages;
+		}
+
+		$labels = array();
+		foreach ( $services as $service ) {
+			$labels[] = sprintf(
+				_x( '%1$s: %2$s', 'Service name is %1$s, and account name is %2$s.', 'jetpack' ),
+				esc_html( $service['service_name'] ),
+				esc_html(  $service['display_name'] )
```
Comment (lezama) [inline modules/publicize/publicize.php]: extra whitespace

File: modules/publicize/publicize.php [hunk 17]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			);
+		}
+
+		$messages['post'][6] = sprintf(
+			_x( 'Post published and publicizing to %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
+			implode(', ', $labels ),
```
Comment (lezama) [inline modules/publicize/publicize.php]: missing space

File: modules/publicize/publicize.php [hunk 18]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+				$messages['post'][6] = sprintf(
+					_x( 'Post published, sending emails to subscribers and publicizing to %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
+					implode(', ', $labels ),
+					$view_post_link_html );
+			}
+		}
+
+		$messages['jetpack-portfolio'][6] = sprintf(
+			_x( 'Project published and publicizing to %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
+			implode(', ', $labels ),
```
Comment (lezama) [inline modules/publicize/publicize.php]: missing space

File: modules/publicize/publicize.php [hunk 19]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+			$subscription = Jetpack_Subscriptions::init();
+			if ( $subscription->should_email_post_to_subscribers( $post ) ) {
+				$messages['post'][6] = sprintf(
+					_x( 'Post published, sending emails to subscribers and publicizing to %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
+					implode(', ', $labels ),
+					$view_post_link_html );
+			}
+		}
+
+		$messages['jetpack-portfolio'][6] = sprintf(
```
Comment (lezama) [inline modules/publicize/publicize.php]: is it normal that we set `$messages['jetpack-portfolio'][6]` here?

File: modules/publicize/publicize.php [hunk 20]
```diff
@@ -418,6 +419,91 @@ function save_meta( $post_id, $post ) {
...
+		$labels = array();
+		foreach ( $services as $service ) {
+			$labels[] = sprintf(
+				_x( '%1$s: %2$s', 'Service name is %1$s, and account name is %2$s.', 'jetpack' ),
+				esc_html( $service['service_name'] ),
+				esc_html(  $service['display_name'] )
+			);
+		}
+
+		$messages['post'][6] = sprintf(
```
Comment (lezama) [inline modules/publicize/publicize.php]: why do we set the 6th element?

Comment (enejb) [reply modules/publicize/publicize.php]: That is just the error number that we need to overwrite 
See https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L169

**Comment by enejb** [comment]
Just Just updated to the copy to read 
screen shot 2018-03-21 at 4 38 52 pm
screen shot 2018-03-21 at 4 41 32 pm
screen shot 2018-03-21 at 4 42 39 pm

File: modules/publicize/publicize.php [hunk 21]
```diff
@@ -418,6 +419,87 @@ function save_meta( $post_id, $post ) {
...
+			);
+		}
+
+		$services = $this->get_publicizing_services( $post->ID );
+		if ( empty( $services ) ) {
+			return $messages;
+		}
+
+		$labels = array();
+		foreach ( $services as $service => $dispay_names ) {
```
Comment (akirk) [inline modules/publicize/publicize.php]: `dispay_names`: typo

File: modules/publicize/publicize.php [hunk 22]
```diff
@@ -418,6 +419,87 @@ function save_meta( $post_id, $post ) {
...
+			$labels[] = sprintf(
+				_x( '%1$s (%2$s)', 'Service name is %1$s, and account name is %2$s.', 'jetpack' ),
```
Comment (akirk) [inline modules/publicize/publicize.php]: Please don't use the context to explain the variables but rather a `/* translators: */` comment

File: modules/subscriptions.php [hunk 23]
```diff
@@ -160,6 +162,20 @@ function maybe_send_subscription_email( $new_status, $old_status, $post ) {
...
 	}
 
+	function update_published_message( $messages ) {
+		global $post;
+		if ( ! $this->should_email_post_to_subscribers( $post ) ) {
+			return $messages;
+		}
+
+		$messages['post'][6] = sprintf(
+				__( 'Post published and sending emails to subscribers. <a href="%1$s">%2$s</a>', 'jetpack' ),
```
Comment (akirk) [inline modules/subscriptions.php]: The link should not be in the translatable text.

File: modules/publicize/publicize.php [hunk 24]
```diff
@@ -418,6 +419,87 @@ function save_meta( $post_id, $post ) {
...
+		$messages['post'][6] = sprintf(
+			_x( 'Post published and sharing on %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
+			implode( ', ', $labels ),
+			$view_post_link_html );
+
+		if ( $post_type == 'post' && class_exists('Jetpack_Subscriptions' ) ) {
+			$subscription = Jetpack_Subscriptions::init();
+			if ( $subscription->should_email_post_to_subscribers( $post ) ) {
+				$messages['post'][6] = sprintf(
+					_x( 'Post published, sending emails to subscribers and sharing post on %1$s. %2$s', 'Published Message: services and account string is %1$s, link to view published post is %2$s', 'jetpack' ),
```
Comment (akirk) [inline modules/publicize/publicize.php]: Having the different variations of text is not bad for translation. Just the extravariable at the end should be appende outside of the translatable te.xt

File: modules/publicize/publicize.php [hunk 25]
```diff
@@ -418,15 +419,102 @@ function save_meta( $post_id, $post ) {
...
+                	implode( ', ', $labels ),
+                	$view_post_link_html
+				);
+			}
+		}
+
+		$messages['jetpack-portfolio'][6] = sprintf(
+			/* translators: Published Message: services and account string is %1$s, link to view published post is %2$s */
+			_x( 'Project published and sharing project on %1$s. %2$s', 'Post published notice', 'jetpack' ),
+			implode( ', ', $labels ),
```
Comment (simison) [inline modules/publicize/publicize.php]: Should `,` be translated in this context? I.e. would this work in left-to-right text?

Comment (enejb) [reply modules/publicize/publicize.php]: @akirk Any suggestions here?

Comment (akirk) [reply modules/publicize/publicize.php]: That will be ok in RTL.

Comment (akirk) [reply modules/publicize/publicize.php]: Please remove the `%2$s` here. This is more confusing to translators than helpful. Thanks!

Comment (akirk) [reply modules/publicize/publicize.php]: (i.e. just append the link outside of the translate function)

File: modules/publicize/publicize.php [hunk 26]
```diff
@@ -418,15 +419,102 @@ function save_meta( $post_id, $post ) {
...
+		$services = $this->get_publicizing_services( $post->ID );
+		if ( empty( $services ) ) {
+			return $messages;
+		}
+
+		$labels = array();
+		foreach ( $services as $service => $display_names ) {
+			$labels[] = sprintf(
+				/* translators: Service name is %1$s, and account name is %2$s. */
+				_x( '%1$s (%2$s)', 'Service and account string', 'jetpack' ),
```
Comment (akirk) [inline modules/publicize/publicize.php]: Please convert all `_x()` that you added in this PR to just `__()`. The context prevents re-usage of translations and the comment is already helpful.

File: modules/subscriptions.php [hunk 27]
```diff
@@ -160,6 +162,25 @@ function maybe_send_subscription_email( $new_status, $old_status, $post ) {
...
+		}
+
+		$view_post_link_html = sprintf( ' <a href="%1$s">%2$s</a>',
+			esc_url( get_permalink( $post ) ),
+			__( 'View post' ) // intentinally omitted domain
+		);
+
+		$messages['post'][6] = sprintf(
+				/* translators: Link to view published post is %1$s */
+				esc_html__( 'Post published and sending emails to subscribers. %1$s', 'jetpack' ),
```
Comment (akirk) [inline modules/subscriptions.php]: Please remove `%1$s` here and put the link outside of the translate function.

File: modules/publicize/publicize.php [hunk 28]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
+				__( '%1$s (%2$s)', 'jetpack' ),
+				esc_html( $service ),
+				esc_html( implode( ', ', $display_names ) )
+			);
+		}
+
+		$messages['post'][6] = sprintf(
+			/* translators: Services and account string is %1$s */
+			esc_html__( 'Post published and sharing on %1$s.', 'jetpack' ),
+			implode( ', ', $labels )
```
Comment (lezama) [inline modules/publicize/publicize.php]: should we limit this to a max number of characters?

File: modules/publicize/publicize.php [hunk 29]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
+		) . $view_post_link_html;
+
+		if ( $post_type == 'post' && class_exists('Jetpack_Subscriptions' ) ) {
+			$subscription = Jetpack_Subscriptions::init();
+			if ( $subscription->should_email_post_to_subscribers( $post ) ) {
+				$messages['post'][6] = sprintf(
+					/* translators: Services and account string is %1$s */
+               		esc_html__( 'Post published, sending emails to subscribers and sharing post on %1$s.', 'jetpack' ),
+                	implode( ', ', $labels )
+				). $view_post_link_html;
```
Comment (lezama) [inline modules/publicize/publicize.php]: espace missing before `.`

File: modules/subscriptions.php [hunk 30]
```diff
@@ -160,6 +162,25 @@ function maybe_send_subscription_email( $new_status, $old_status, $post ) {
...
+			return $messages;
+		}
+
+		$view_post_link_html = sprintf( ' <a href="%1$s">%2$s</a>',
+			esc_url( get_permalink( $post ) ),
+			__( 'View post' ) // intentinally omitted domain
+		);
+
+		$messages['post'][6] = sprintf(
+				/* translators: Message shown after a post is published */
```
Comment (ebinnion) [inline modules/subscriptions.php]: I would move this and the next few lines one tab to the left.

File: modules/publicize/publicize.php [hunk 31]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
-	 * @param string $post_type The post type to check.
-	 * $return bool True if the post type can be Publicized.
-	 */
+	* Is a given post type Publicize-able?
+	*
+	* Not every CPT lends itself to Publicize-ation.  Allow CPTs to register by adding their CPT via
+	* the publicize_post_types array filter.
+	*
+	* @param string $post_type The post type to check.
+	* $return bool True if the post type can be Publicized.
```
Comment (ebinnion) [inline modules/publicize/publicize.php]: This should be `@return` instead of `$return`

File: modules/subscriptions.php [hunk 32]
```diff
@@ -160,6 +162,25 @@ function maybe_send_subscription_email( $new_status, $old_status, $post ) {
...
 
+	function update_published_message( $messages ) {
+		global $post;
+		if ( ! $this->should_email_post_to_subscribers( $post ) ) {
+			return $messages;
+		}
+
+		$view_post_link_html = sprintf( ' <a href="%1$s">%2$s</a>',
+			esc_url( get_permalink( $post ) ),
+			__( 'View post' ) // intentinally omitted domain
```
Comment (ebinnion) [inline modules/subscriptions.php]: Can we make this `esc_html__()`?

File: modules/publicize/publicize.php [hunk 33]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
+				}
+				$services[ $this->get_service_label( $service_name ) ][] = $this->get_display_name( $service_name, $connection );
+			}
+		}
+
+		return $services;
+	}
+
 	/**
-	 * Is a given post type Publicize-able?
```
Comment (ebinnion) [inline modules/publicize/publicize.php]: Lines `507` to `514` should be indented one extra space.

File: modules/publicize/publicize.php [hunk 34]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
 
+	public function update_published_message( $messages ) {
+		global $post_type, $post_type_object, $post;
+		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
+			return $messages;
+		}
+		$view_post_link_html = '';
+		$viewable = is_post_type_viewable( $post_type_object );
+		if ( $viewable ) {
+			$view_text = __( 'View post' ); // intentionally omitted domain
```
Comment (ebinnion) [inline modules/publicize/publicize.php]: Can we make this `esc_html__()`?

File: modules/publicize/publicize.php [hunk 35]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
+
+			if ( 'jetpack-portfolio' == $post_type ) {
+				$view_text = esc_html__( 'View project', 'jetpack' );
+			}
+
+			$view_post_link_html = sprintf( ' <a href="%1$s">%2$s</a>',
+				esc_url( get_permalink( $post ) ),
+				$view_text
```
Comment (ebinnion) [inline modules/publicize/publicize.php]: Or maybe just put the `esc_html()` here instead `esc_html__()` above.

File: modules/publicize/publicize.php [hunk 36]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
+		$services = $this->get_publicizing_services( $post->ID );
+		if ( empty( $services ) ) {
+			return $messages;
+		}
+
+		$labels = array();
+		foreach ( $services as $service => $display_names ) {
+			$labels[] = sprintf(
+				/* translators: Service name is %1$s, and account name is %2$s. */
+				__( '%1$s (%2$s)', 'jetpack' ),
```
Comment (ebinnion) [inline modules/publicize/publicize.php]: We should probably use `esc_html__()` here.

**Comment by enejb** [comment]
@ebinnion I made the changes that you suggested. Can I merge this now?

File: modules/publicize/publicize.php [hunk 37]
```diff
@@ -418,15 +419,99 @@ function save_meta( $post_id, $post ) {
...
 
+	public function update_published_message( $messages ) {
+		global $post_type, $post_type_object, $post;
+		if ( ! $this->post_type_is_publicizeable( $post_type ) ) {
+			return $messages;
+		}
+		$view_post_link_html = '';
+		$viewable = is_post_type_viewable( $post_type_object );
+		if ( $viewable ) {
+			$view_text = esc_html__( 'View post' ); // intentionally omitted domain
```
Comment (simison) [inline modules/publicize/publicize.php]: @enejb do you remember why was domain omitted here?

I ran `yarn add-textdomain` (a script that adds textdomains to php files where they are missing) and it caught up on this one.
