### PR TITLE
Admin Menu: Add custom post type menu items to jetpack sites

### LINKED ISSUE #64935: [Bug]: Custom Post Types not displayed in Calypso UI
### Quick summary

One should have access to their allowlisted Custom Post Types when managing their site from the WordPress.com dashboard. This used to be possible, but the CPT do not appear in the sidebar menu anymore.

### Steps to reproduce

1. Start with a Jetpack site that's connected to WordPress.com.
2. Register a new CPT, and allowlist it.
```php
// Register Custom Post Type
function jeherve_rowan_custom_post_type() {

	$labels = array(
		'name'                  => _x( 'Example Post Types', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'An example Post Type', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Example Post Types', 'text_domain' ),
		'name_admin_bar'        => __( 'Post Type', 'text_domain' ),
		'archives'              => __( 'Item Archives', 'text_domain' ),
		'attributes'            => __( 'Item Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Item:', 'text_domain' ),
		'all_items'             => __( 'All Items', 'text_domain' ),
		'add_new_item'          => __( 'Add New Item', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Item', 'text_domain' ),
		'edit_item'             => __( 'Edit Item', 'text_domain' ),
		'update_item'           => __( 'Update Item', 'text_domain' ),
		'view_item'             => __( 'View Item', 'text_domain' ),
		'view_items'            => __( 'View Items', 'text_domain' ),
		'search_items'          => __( 'Search Item', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'An example Post Type', 'text_domain' ),
		'description'           => __( 'An exmaple post type description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'jeherve_rowan', $args );

}
add_action( 'init', 'jeherve_rowan_custom_post_type', 0 );

function jeherve_allow_my_post_types( $allowed_post_types ) {
	$allowed_post_types[] = 'jeherve_rowan';
	return $allowed_post_types;
}
add_filter( 'rest_api_allowed_post_types', 'jeherve_allow_my_post_types' );
```
3. You will see the new post type menu when managing your site in wp-admin.
4. You will not see the menu when in WordPress.com.

**wp-admin**
image

**Calypso**
image

### What you expected to happen

The "Example Post Types" menu item should appear, just like the other Post Types on those screenshots.

### What actually happened

It does not appear.

### Context

5303505-zen

### Browser

Google Chrome/Chromium

### Simple/Atomic

Atomic

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The only way to access the Post Type management screen is by navigating to wp-admin first.

### PR DESCRIPTION
**Pull request by sejas**
- Closes https://github.com/Automattic/wp-calypso/issues/64935

#### Changes proposed in this Pull Request:

Calypso makes a request to WPcom API that proxies the call to jetpack sites to get the admin menu.

* This PR Includes custom post type menu items into that response to display them in the Calypso admin menu.
* If SSO is enabled in Jetpack settings, and the post_type `show_in_rest` is true, these links will navigate to the CPT list in the same tab using the Calypso UI
* If SSO is disabled or the post_type `show_in_rest` is false, the links will open wp-admin on a new tab.
* The Feedback menu item is working without changes. We cannot open it inside Calypso because the UI should be different, like removing the `Add post` button from the UI.

**Before**

Screenshot 2022-08-17 at 12 17 58

**After**

| SSO Disabled | SSO Enabled |
|---|---|
| sso-disabled  | sso-enabled  |

**Screencast**

https://user-images.githubusercontent.com/779993/185950095-6b99bee7-ab65-4fde-bce5-18eb6078e100.mp4

#### Other information:

- [x] Have you written new tests for your changes, if applicable?
- [x] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No

#### Testing instructions:

**1. Apply this PR on a jetpack site**
* On a Jetpack site connected to WPcom
* Install and activate [Jetpack beta](https://jetpack.com/download-jetpack-beta/)
* Go to `/wp-admin/admin.php?page=jetpack-beta&plugin=jetpack`
* Click on `Search for a Feature Branch` and enter this branch `add/cpt-menu-calypso-menu`

**2. Create a CPT and validate that it appears on Calypso**
* Create a new CPT on your site. You can install [Code Snippets Plugin](https://wordpress.org/plugins/code-snippets/) and add include the snippet provided in the issue https://github.com/Automattic/wp-calypso/issues/64935.

<details>
<summary>Click to see the CPT snippet</summary>

```php
// Register Custom Post Type
function cpt_64935_custom_post_type() {

	$labels = array(
		'name'                  => _x( 'New Custom Posts', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'An example Post Type', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'New Custom Posts', 'text_domain' ),
		'name_admin_bar'        => __( 'Post Type', 'text_domain' ),
		'archives'              => __( 'Item Archives', 'text_domain' ),
		'attributes'            => __( 'Item Attributes', 'text_domain' ),
		'parent_item_colon'     => __( 'Parent Item:', 'text_domain' ),
		'all_items'             => __( 'All Items', 'text_domain' ),
		'add_new_item'          => __( 'Add New Item', 'text_domain' ),
		'add_new'               => __( 'Add New', 'text_domain' ),
		'new_item'              => __( 'New Item', 'text_domain' ),
		'edit_item'             => __( 'Edit Item', 'text_domain' ),
		'update_item'           => __( 'Update Item', 'text_domain' ),
		'view_item'             => __( 'View Item', 'text_domain' ),
		'view_items'            => __( 'View Items', 'text_domain' ),
		'search_items'          => __( 'Search Item', 'text_domain' ),
		'not_found'             => __( 'Not found', 'text_domain' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'text_domain' ),
		'featured_image'        => __( 'Featured Image', 'text_domain' ),
		'set_featured_image'    => __( 'Set featured image', 'text_domain' ),
		'remove_featured_image' => __( 'Remove featured image', 'text_domain' ),
		'use_featured_image'    => __( 'Use as featured image', 'text_domain' ),
		'insert_into_item'      => __( 'Insert into item', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'text_domain' ),
		'items_list'            => __( 'Items list', 'text_domain' ),
		'items_list_navigation' => __( 'Items list navigation', 'text_domain' ),
		'filter_items_list'     => __( 'Filter items list', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'An example Post Type', 'text_domain' ),
		'description'           => __( 'An exmaple post type description', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor' ),
		'taxonomies'            => array( 'category', 'post_tag' ),
		'hierarchical'          => true,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
		'show_in_rest'          => true,
	);
	register_post_type( 'cpt_64935', $args );

}
add_action( 'init', 'cpt_64935_custom_post_type', 0 );

function cpt_64935_allow_my_post_types( $allowed_post_types ) {
	$allowed_post_types[] = 'cpt_64935';
	return $allowed_post_types;
}
add_filter( 'rest_api_allowed_post_types', 'cpt_64935_allow_my_post_types' );
```
</details>

* Go to WPcom
* Click on `Switch Site` on the left menu
* Select your jetpack site
* Observe your CPT appears on the left menu
* If you have WPcom SSO enabled on your Jetpack Settings, clicking on the CPT menu item will navigate you to the correct Calypso screen.
* Otherwise, the `wp-admin` custom posts list will open on a new tab.

### CODE REVIEW

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php [hunk 1]
```diff
@@ -13,6 +13,41 @@
...
 class Jetpack_Admin_Menu extends Admin_Menu {
+
+	/**
+	 * Returns an array with the CPT menu items different form post and page types.
+	 *
+	 * @param array $menu The menu array to filter from.
+	 * @return array The filtered menu array.
+	 */
+	private function filter_cpt_menu_items( $menu ) {
+		$exclude_slugs = array( 'menu-posts', 'menu-pages' );
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: Non-blocking question: Why don't we need to exclude `menu-feedback` here? That's another CPT so I expected the Feedback menu to be duplicated, but it is not for some reason I don't understand.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php [hunk 2]
```diff
@@ -13,6 +13,41 @@
...
+		);
+	}
+
+	/**
+	 * Replaces the wp-admin CPT URLs with the WPcom calypso url.
+	 *
+	 * @param array $menu_item The CPT menu item to replace.
+	 * @return array The CPT menu item with the replaced URL.
+	 */
+	private function replace_admin_link_to_calypso( $menu_item ) {
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: One can easily infer with this method name that all WP-Admin links will be replaced, while only the CPT ones are replaced.

For consistency with how the rest of the menus are added/modified, I recommend creating a new method like `add_cpt_menus` and keep the `$menu = array()` reset.

This new method would need to iterate over [all the registered CPTs](https://developer.wordpress.org/reference/functions/get_post_types/) (remember to use the `_builtin` param to exclude the default post types!) and register the new menu items ([if `show_in_menu` is enabled](https://developer.wordpress.org/reference/functions/register_post_type/#show_in_menu)) with a link to Calypso (or to WP Admin is the SSO module is disabled) and ensure they are positioned below the Feedback menu item (we could also register the Feedback menu item in this method and get rid of `add_feedback_menu`).

**Review by mmtr — COMMENTED** [review]
This tests well, nice work! As discussed in https://github.com/Automattic/wp-calypso/issues/64935, let's keep the WP Admin link as a fallback for when the SSO module is disabled.

It'd be also good if the menu items are moved below the Feedback menu entry. Otherwise the CPTs menus would appear way up, giving less visibility to more important menu entries such as Posts, Media, or Pages.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 2 above)
Comment (sejas) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: @mmtr , Thanks for your suggestions. I like this new approach.

The PR is ready to review, and I've updated the description and test instructions to match the new behavior.

My only question is should we show only the CPTs with `show_in_rest` equal to true?.
In the example provided in the issue https://github.com/Automattic/wp-calypso/issues/64935 we had this option `show_in_rest` equal to true. However, I think we should show all the CPT available on the menu, regardless of the `show_in_rest` value.
In this commit, I've removed filtering by this option: https://github.com/Automattic/jetpack/pull/25670/commits/ef4a1764291578519a5108fdfe1a62566c1b570a

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 1 above)
Comment (sejas) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: The `menu-feedback` has the `show_in_menu` equal to false, and that's why it doesn't appear by default on the global variable `$menu`.

https://github.com/Automattic/jetpack/blob/765e0cea4851ae116b59a0408b312ebbd90b01ce/projects/plugins/jetpack/modules/contact-form/grunion-contact-form.php#L326

File: projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu [hunk 3]
```diff
@@ -0,0 +1,5 @@
+Significance: patch
```
Comment (danielbachhuber) [inline projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu]:
```suggestion
Significance: minor
```

I kinda feel this is a significant-enough change to call it `minor`. What do you think?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php [hunk 4]
```diff
@@ -55,6 +57,21 @@ public function get_preferred_view( $screen, $fallback_global_preference = true
...
+	/**
+	 * Get the link to the CPT screen. If SSO is enabled, the link will inside calypso,
+	 * otherwise it will be a link to wp-admin.
+	 *
+	 * @param string $post_type The ID of the post type.
+	 * @return string The link to Calypso if SSO is enabled or to WP Admin if SSO is disabled.
+	 */
+	public function get_cpt_menu_link( $post_type ) {
+		if ( \Jetpack::is_module_active( 'sso' ) ) {
+			return 'https://wordpress.com/types/' . $post_type . '/' . $this->domain;
```
Comment (danielbachhuber) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php:72]: One thing worth noting: the post type will also need to `support = [ 'editor' ]` in order to be editable in Calypso.

image

However, I tried removing support for `editor` and it elegantly redirected to the classic editor.

Although, do we need to accommodate `show_in_rest=true` too?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php [hunk 5]
```diff
@@ -55,6 +57,21 @@ public function get_preferred_view( $screen, $fallback_global_preference = true
...
 	}
 
+	/**
+	 * Get the link to the CPT screen. If SSO is enabled, the link will inside calypso,
+	 * otherwise it will be a link to wp-admin.
+	 *
+	 * @param string $post_type The ID of the post type.
+	 * @return string The link to Calypso if SSO is enabled or to WP Admin if SSO is disabled.
+	 */
+	public function get_cpt_menu_link( $post_type ) {
```
Comment (danielbachhuber) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: I thought we maybe needed to support this 'View' switcher too:

image

However, it doesn't seem the feature is supported for Jetpack-connected sites (only Simple and Atomic sites).

**Review by danielbachhuber — COMMENTED** [review]
Works great in my testing! Using a jurassic.ninja site + Jetpack Beta tester plugin = 🤌

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 1 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: Nice finding! I guess we want to show the menu in Calypso but not in WP Admin, so that explains why we still need the `add_feedback_menu` exception.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 2 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: >  should we show only the CPTs with show_in_rest equal to true?

I think we should ignore that, since it could lead to a confusing behavior (why a CPT that is registered to show up in the REST API but not in the admin menu should appear in the Calypso menu?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 5 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php]: Correct, this is part of what we call "the unified navbar across Calypso / WP Admin" which is intentionally unsupported on self-hosted Jetpack sites (see https://github.com/Automattic/wp-calypso/issues/66068#issuecomment-1199012300 for more context).

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 4 above)
Comment (mmtr) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php:72]: > Although, do we need to accommodate show_in_rest=true too?

Good question! I guess Calypso is unable to edit CPTs if `show_in_rest=false` because it cannot interact with them through the REST API. In that case, let's ignore what I said in https://github.com/Automattic/jetpack/pull/25670#discussion_r953626247 and maybe link to WP-Admin as a fallback if `show_in_rest=false`?

**Review by mmtr — COMMENTED** [review]
Thanks for latest changes, this looks pretty close!

File: projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu (hunk 3 above)
Comment (sejas) [reply projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu]: Sure!, minor is a better significance for this change 👌

File: projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php (hunk 4 above)
Comment (sejas) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/class-jetpack-admin-menu.php:72]: I've added the exception for `show_in_rest`, we will link to wp-admin on a new tab when `show_in_rest` is false.
Screenshot 2022-08-24 at 13 11 17

File: projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu [hunk 6]
```diff
@@ -0,0 +1,5 @@
+Significance: minor
+Type: enhancement
+Comment: Include custom post types items inside the calypso admin menu
```
Comment (mmtr) [inline projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu]: The changelog cannot be omitted now that this is a minor change.
```suggestion

Include custom post types items inside the calypso admin menu
```

**Review by mmtr — COMMENTED** [review]
This tests very well! Just left a minor (but blocking) comment regarding the changelog message.

**Review by mmtr — APPROVED** [review]

File: projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu (hunk 6 above)
Comment (sejas) [reply projects/plugins/jetpack/changelog/add-cpt-menu-calypso-menu]: Oh!, thank you!, I thought the Significance type was what made the "comment" public or not.

**Comment by sejas** [comment]
r251232-wpcom
