### PR TITLE
Subs Widget: better error for when emails has blocked subscriptions

### LINKED ISSUE #2007: Subscriptions: Better error message when user has "blocked all emails".
Steps to reproduce.
1. Go to your WordPress.com account Notifications page here: https://wordpress.com/me/notifications
2. Check off "Block all email updates from blogs you’re following on WordPress.com"
3. Try to sign up to any Jetpack connected blog through Subscriptions
4. Get this error:
`There was an error when subscribing. Please try again.`

Problem: That error suggests that there is a problem with Jetpack or our Subscriptions, when really the problem is that they have blocked all emails, so it's *never* going to work.  The `please try again` is deceiving and leads to support emails.

Suggestion: Let's have a better error message!   Something like:
```You are unable to subscribe to this blog right now because you have blocked all emails from your WordPress.com account.  Please enable email notifications by going to your *WordPress.com Notifications page*```

### PR DESCRIPTION
**Pull request by dereksmart**
Fixes #2007

To test: 
append this to a url that has the subscription widget `?subscribe=opted_out`

### CODE REVIEW

**Comment by kraftbj** [comment]
Not at a computer to adjust the PR, but we could make the language better. "This e-mail address has opted out of subscriptions e-mails. You can adjust this preference at https://subscribe.wordpress.com." or something like that.

**Comment by dereksmart** [comment]
sure, but the option could also be set in their "wordpress.com/me/notifications" page under "Block all email updates from blogs you’re following on WordPress.com".

**Comment by kraftbj** [comment]
I'm not sure if those are the same or different settings, tbh. The subscribe. site works for any e-mail adr; not wp.com user dependent.

**Comment by dereksmart** [comment]
me neither.  time to test :)

**Comment by dereksmart** [comment]
Confirmed it's the same option in both `wordpress.com/me/notifications` and `subscribe.wordpress.com/?option=settings`

File: modules/subscriptions.php [hunk 1]
```diff
@@ -734,6 +737,12 @@ function widget( $args, $instance ) {
 				case 'invalid_email' : ?>
 					<p class="error"><?php esc_html_e( 'The email you entered was invalid. Please check and try again.', 'jetpack' ); ?></p>
 				<?php break;
+				case 'opted_out' : ?>
+					<p class="error"><?php printf( _x( "The email address has opted out of subscription emails. %1s You can manage your preferences at %2s", '%1s is a line break, %2s is a website', 'jetpack' ),
```
Comment (zinigor) [inline modules/subscriptions.php]: Let's embed the HTML into translation and only insert links. Also please use a translator comment here instead of context to provide explanations for translation placeholders.

**Comment by zinigor** [comment]
Looking good except for the i18n issue. This has my :+1: after fixing

**Comment by finlanderid** [comment]
I am getting the case 'opted_out' error (The email address has opted out of subscription emails.) when there is no reason for me to be getting that error. The email address is following the particular blog and is _not_ opting out of receiving email notifications, either from the blog or from wordpress.com globally. 

I actually **should** be getting the case 'already' error (You have already subscribed to this site.), though. I previously signed up on the blog for subscription, and that sign-up process went fine.

Has anyone else reported this? I am certain that I should not be getting first error above, and that I should be getting the second error instead.

**Comment by jeherve** [comment]
@finlanderid Could you contact us via [this contact form](http://jetpack.me/contact-support/) and let us know your email address, so we can look into this with you?

Thanks!

**Comment by csonnek** [comment]
@jeherve: 2416945-t

Checked and showing:
1) Not blocking emails from WordPress.com
2) Subscribed to site on `2015-11-11 09:58:34` per our system.

**Comment by finlanderid** [comment]
@jeherve <https://github.com/jeherve>: 2416945-t
@csonnek <https://github.com/csonnek>

exactly, that's why it's odd that I get the:

     switch/case 'opted_out' error ("The email address has opted out of 
subscription emails.")

instead of the:

     switch/case 'already' error ("You have already subscribed to this 
site.")

when I attempt to subscribe with an email address that is already 
subscribed.

**Comment by jeherve** [comment]
@finlanderid I replied to your email a few minutes ago.

Thanks for the extra details.
