### PR TITLE
VideoPress: Use playback tokens to get resources when the VideoPress site privacy is set to private

### LINKED ISSUE #27314: VideoPress: Broken thumbnails with 403 status
Steps that caused the problem here:

1 - I was logged in my wpcom account before a scheduled auto-logout

2 - I turned on the `Video Privacy` flag:
Image

3 - I uploaded a video through the `VideoPress (beta)` block that got stuck on 99%:
Image

4 - On the VideoPress dashboard, that specific thumbnail broke, with a `403` status:
Image

5 - At this point I visited a wpcom link and had to re-login

6 - After login, all thumbnails gave me `403`:
Image

7 - I uploaded another video, from the VideoPress dashboard this time, and the new video immediately got a broken thumbnail (`403`)

8 - I turned off `Video Privacy` and reloaded the dashboard

9 - All thumbnails, including the thumbnail of the video that got stuck on 99%, were displayed correctly

10 - I turned `Video Privacy` on again and the thumbnails still displayed correctly

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #27314, #26938 and #27391.

#### Changes proposed in this Pull Request:

* Renamed the `videoIsPrivate` flag to `needsPlaybackToken`
* Changed the resolver to rely on the new `needsPlaybackToken` flag when deciding if a video needs a playback token
* Exposed the `needsPlaybackToken` flag for all the videos on the client initial state

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion

N/A.

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Check the "Video Privacy: Restrict views to members of this site" setting:

Screen Shot 2022-11-11 at 19 16 20

* Upload some videos to the media library, leaving the privacy setting as default
* Open the browser console to inspect errors and the network activity
* Do a hard refresh on the page
* Before the fix, the thumbnails for the added videos were broken:

Screen Shot 2022-11-11 at 19 32 20

* After the fix, you should see all the thumbnais properly:

Screen Shot 2022-11-11 at 19 22 52

* Before the fix, you would see failed `403` responses for the thumbnail files:

Screen Shot 2022-11-11 at 19 33 18

* After the fix, no `403` responses should appear on the console
* After the fix, you also will see requests to the playback token endpoint on the network log, showing that the application is now requesting the tokens that it will need:

Screen Shot 2022-11-11 at 19 26 15

* Make sure to test the list view as well as the grid view

### CODE REVIEW

File: projects/packages/videopress/src/client/state/resolvers.js [hunk 1]
```diff
@@ -18,8 +18,6 @@ import {
 	SET_LOCAL_VIDEOS_QUERY,
 	WP_REST_API_USERS_ENDPOINT,
 	WP_REST_API_VIDEOPRESS_PLAYBACK_TOKEN_ENDPOINT,
-	VIDEO_PRIVACY_LEVELS,
-	VIDEO_PRIVACY_LEVEL_PRIVATE,
```
Comment (retrofox) [inline projects/packages/videopress/src/client/state/resolvers.js:22]: should we remove these constants, too?

Comment (lhkowalski) [reply projects/packages/videopress/src/client/state/resolvers.js:22]: @retrofox Remove the import? Yes, because they are not being used in any other place of the file.

**Review by dhasilva — APPROVED** [review]
LGTM
