### PR TITLE
Plan: Add support for Monthly pay period to products.

### LINKED ISSUE #15094: Plans: Monthly toggle doesn't apply to Single Products
#### Steps to reproduce the issue

1. Navigate to `/wp-admin/admin.php?page=jetpack#/plans`
2. Click on `Monthly` at the top of the page.

#### What I expected
Monthly pricing to be shown in the Backups product card.

#### What happened instead
Yearly pricing was shown in the Backups product card.

**Screenshots**

Screen Shot 2020-03-23 at 5 52 36 PM

### PR DESCRIPTION
**Pull request by enejb**
Make the monthly and yearly toggle work for Products. 

Fixes https://github.com/Automattic/jetpack/issues/15094

This is what the page looks like now. 

Screen Shot 2020-03-31 at 5 26 08 PM

#### Changes proposed in this Pull Request:
* This PR adds a plan duration to the redux store. This way the pay period can be accessed from any component. 

#### Testing instructions:
1. Build this PR. 
2. Notice that you can toggle the monthly and yearly toggle on the plans page in wp-admin.
3. Notice that you can buy the correct product. 

#### Proposed changelog entry for your changes:
Make the monthly prices available in wp-admin plans page.

### CODE REVIEW

**Review by gibrown — DISMISSED** [review]
I think @keoshi should weigh in, but I think I prefer the radio button that shows monthly and yearly pricing side by side for Search. The toggle at the top of the page is very tough to find, and for our high end tiers I am afraid that the yearly pricing could scare folks off. What about adding that same yearly/monthly toggle inside the product cards?

Screen Shot 2020-03-30 at 9 39 33 AM

Looks like we are missing a space in the text here:

Screen Shot 2020-03-30 at 9 37 43 AM

Can we get rid of this backups link please:

Screen Shot 2020-03-30 at 9 42 27 AM

**Comment by keoshi** [comment]
Yeah, I like the idea of showing monthly next to yearly plans for Search inside a single card. That gives customers a clear choice of what's available.

However, this could create a lot of inconsistencies between the cards for single products, and could also create confusion of why the toggle doesn't work for these. Even though the most likely scenario is that they don't see both the toggle and the cards below at the same time in the first place.

I've started a discussion about this here p1585583677212300-slack-jetpack-design and the consensus seems to be:

- These plan pages are going to be tackled soon on a much bigger project.
- Ignore the fact the toggle might not be visible and still use it to switch the content (pricing) on the SP cards.

**Review by keoshi — CHANGES_REQUESTED** [review]
I don't know if this is within the scope of this PR but Ieaving some testing notes:

- It would be cool to add crossed prices to Search as we're doing for Backup.
- Either get rid of the “You are saving €17 by paying yearly” on Search or add “You would save €6/€40 by paying yearly” to Backup. The two cards are too inconsistent right now in regards to pricing.
- Also make the CTAs consistent. cc @robertbpugh because of our chat on https://github.com/Automattic/jetpack/issues/15183
- Fix the missing space [Greg reported earlier](https://github.com/Automattic/jetpack/pull/15193#pullrequestreview-383988191).
- Based on the [decision here](https://github.com/Automattic/jetpack/pull/15193#issuecomment-606093509), let's go with the behavior on this PR for now.

File: _inc/client/plans/plan-grid.jsx [hunk 1]
```diff
@@ -14,16 +14,14 @@ import Button from 'components/button';
 import ButtonGroup from 'components/button-group';
 import { getSiteRawUrl, getUpgradeUrl, getUserId, showBackups } from 'state/initial-state';
 import { getSitePlan, getAvailablePlans, isFetchingSiteData } from 'state/site/reducer';
+import { setPlanDuration } from 'state/period-toggle/actions';
+import { getPlanDuration } from 'state/period-toggle/reducer';
```
Comment (jsnmoon) [inline _inc/client/plans/plan-grid.jsx]: This can actually just be:

```js
import { getPlanDuration, setPlanDuration } from 'state/period-toggle';
```

File: _inc/client/plans/single-product-search/index.jsx [hunk 2]
```diff
@@ -45,17 +46,12 @@ function getTierLabel( priceTierSlug, recordCount ) {
 	}
 }
 
-function handleSelectedTimeframeChangeFactory( setTimeframe ) {
-	return event => setTimeframe( event.target.value );
-}
-
 export function SingleProductSearchCard( props ) {
-	const [ timeframe, setTimeframe ] = useState( 'yearly' );
```
Comment (jsnmoon) [inline _inc/client/plans/single-product-search/index.jsx]: We'll want to remove the unused `useState` import with this change.

File: _inc/client/plans/single-product-search/index.jsx [hunk 3]
```diff
@@ -86,32 +82,24 @@ export function SingleProductSearchCard( props ) {
...
-						fullPrice={ monthlyPrice }
-						onChange={ handleSelectedTimeframeChange }
-						planName="Monthly"
-						radioValue="monthly"
-					/>
-					<PlanRadioButton
-						billingTimeFrame="yearly"
-						checked={ timeframe === 'yearly' }
+						billingTimeFrame={ planDuration }
+						checked={ true }
```
Comment (jsnmoon) [inline _inc/client/plans/single-product-search/index.jsx]:
```suggestion
						checked
```

File: _inc/client/state/period-toggle/actions.js [hunk 4]
```diff
@@ -0,0 +1,13 @@
+/**
```
Comment (jsnmoon) [inline _inc/client/state/period-toggle/actions.js]: Unless we're planning on using this period toggle state elsewhere, we might want to make this page-specific by using `_inc/client/state/plans/actions.js` instead.

File: _inc/client/state/period-toggle/actions.js [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+ * Internal dependencies
+ */
+import { SET_PLAN_DURATION } from 'state/action-types';
+
+export const setPlanDuration = duration => {
+	return dispatch => {
+		dispatch( {
+			type: SET_PLAN_DURATION,
+			duration: duration,
```
Comment (jsnmoon) [inline _inc/client/state/period-toggle/actions.js]:
```suggestion
			duration,
```

File: _inc/client/state/period-toggle/reducer.js [hunk 6]
```diff
@@ -0,0 +1,32 @@
...
+	planDuration,
+} );
+
+/**
+ * Determines if the DevCard should be displayed.
+ * @param  {Object}  state Global state tree
+ * @return {Boolean}       whether the devCard can be displayed
+ */
+export function getPlanDuration( state ) {
+	return state.jetpack.planDuration.planDuration;
```
Comment (jsnmoon) [inline _inc/client/state/period-toggle/reducer.js]: If we were to go with my recommendation earlier for using `_inc/client/state/plans/`, this selector would become more readable:

```suggestion
	return state.jetpack.plans.planDuration;
```

File: _inc/client/state/period-toggle/reducer.js [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+		case SET_PLAN_DURATION:
+			return action.duration;
+
+		default:
+			return initialState;
+	}
+};
+
+export const reducer = combineReducers( {
+	planDuration,
```
Comment (jsnmoon) [inline _inc/client/state/period-toggle/reducer.js]: How about using a more explicit key?

```suggestion
	selectedPlanDuration,
```

File: _inc/client/plans/product-selector.jsx [hunk 8]
```diff
@@ -22,6 +22,7 @@ import {
 	isFetchingSiteData,
```
Comment (jsnmoon) [inline _inc/client/plans/product-selector.jsx]: It's a little unrelated, but we could knock out two birds with one stone here in the `renderTitleSection` method:

1) Relocate the `Which backup option is best for me?` link into the Backups card.
2) Add another plan period toggle, like so:

Screen Shot 2020-03-30 at 3 36 18 PM

File: _inc/client/plans/single-product-search/index.jsx [hunk 9]
```diff
@@ -86,32 +82,24 @@ export function SingleProductSearchCard( props ) {
...
 						currencyCode={ currencyCode }
-						fullPrice={ yearlyPrice }
-						onChange={ handleSelectedTimeframeChange }
-						planName="Annual"
-						radioValue="yearly"
+						fullPrice={ planDuration === 'yearly' ? yearlyPrice : monthlyPrice }
+						planName={ planDuration === 'yearly' ? 'Annual' : 'Monthly' }
```
Comment (jsnmoon) [inline _inc/client/plans/single-product-search/index.jsx]: We'll probably want to use `Yearly` since that seems to be the norm elsewhere on the page. 
We'll also want to translate these... Whoops :)

```suggestion
						planName={ planDuration === 'yearly' ? __( 'Yearly' ) : __( 'Monthly' ) }
```

**Review by jsnmoon — CHANGES_REQUESTED** [review]
Looks good, although I suppose one could make a case for moving `PlanGrid.state.period` into `Plans.state.period` instead of migrating it into Redux. We'd have to deal with passing the value and setter into the child components if we kept it as a React state though, so I'm fine with the tradeoff presented by this implementation.

Like other reviewers before me, I think the vertical separation between the period toggle and single products to be too great. It'd be great to see another set of period toggles vertically adjacent to the `Solutions` header.

This is definitely a step in the right direction and absolutely must land in 8.4.

**Comment by jsnmoon** [comment]
Oh, one more thing: It looks like the spacing isn't correct for the Backups card with a monthly period toggle. Note the lack of horizontal spacing between the price and `per month`.

Screen Shot 2020-03-30 at 4 07 09 PM

File: _inc/client/plans/plan-grid.jsx (hunk 1 above)
Comment (enejb) [reply _inc/client/plans/plan-grid.jsx]: fixed!

File: _inc/client/plans/single-product-search/index.jsx (hunk 2 above)
Comment (enejb) [reply _inc/client/plans/single-product-search/index.jsx]: Removed useState

File: _inc/client/plans/single-product-search/index.jsx (hunk 3 above)
Comment (enejb) [reply _inc/client/plans/single-product-search/index.jsx]: Done.

File: _inc/client/state/period-toggle/actions.js (hunk 4 above)
Comment (enejb) [reply _inc/client/state/period-toggle/actions.js]: Great suggestion. Updated to use plans folder.

File: _inc/client/state/period-toggle/actions.js (hunk 5 above)
Comment (enejb) [reply _inc/client/state/period-toggle/actions.js]: Fixed.

File: _inc/client/state/period-toggle/reducer.js (hunk 7 above)
Comment (enejb) [reply _inc/client/state/period-toggle/reducer.js]: Sounds good. Updated with your suggestion.

File: _inc/client/plans/single-product-search/index.jsx (hunk 9 above)
Comment (enejb) [reply _inc/client/plans/single-product-search/index.jsx]: Also updated this with your suggestion.

File: _inc/client/plans/product-selector.jsx (hunk 8 above)
Comment (keoshi) [reply _inc/client/plans/product-selector.jsx]: YES, please!

**Review by keoshi — CHANGES_REQUESTED** [review]
This is looking really good though not all previous notes have been addressed. Maybe we can create smaller PRs for those.

One thing I'd really like to see land before merging is duplicating the "Monthly/Yearly" toggle as [Jason mocked here](https://github.com/Automattic/jetpack/pull/15193#discussion_r400509393):

Screen Shot 2020-03-30 at 3 36 18 PM

**Comment by enejb** [comment]
A note about code climate
I think there is a lot of refactoring opportunity in the whole plans page. Especially on the Product/Solutions page. 

I am leaving this as it is for now since there is major work planned for this part.

**Comment by enejb** [comment]
@keoshi 
This is what the page currently looks like .

Screen Shot 2020-03-31 at 1 55 21 PM

**Comment by keoshi** [comment]
@enejb Oops, sorry — that's not what I got in my testing. Let me review it once again real quick.

**Comment by enejb** [comment]
I think the Search Card could still be improved to match what we have in calypso right now. 
Screen Shot 2020-03-31 at 3 29 39 PM

VS this PR. 
Screen Shot 2020-03-31 at 3 55 58 PM

**Review by keoshi — DISMISSED** [review]
I can now see the toggle replicated in the single products section! This is a pretty great change.

image

**Comment by keoshi** [comment]
> I think the Search Card could still be improved to match what we have in calypso right now.

I agree @enejb — that should be done on a different PR, right?

**Comment by enejb** [comment]
Just updated it to look like this and also hide it on the Mobile View. 
Screen Shot 2020-03-31 at 4 48 42 PM

**Comment by jsnmoon** [comment]
@jeherve & @mdbitz: Could we get a 👍/👎 for including this in the 8.4 beta release?

**Review by jsnmoon — DISMISSED** [review]

**Review by jsnmoon — DISMISSED** [review]

**Review by zinigor — DISMISSED** [review]
Everything is working fine, code looks good, but I found one minor problem.

File: _inc/client/plans/style.scss [hunk 10]
```diff
@@ -257,3 +263,8 @@ $plan-features-sidebar-width: 272px;
 		margin: 0 1px;
 	}
 }
+
+.single-product__landing-page {
+  text-align: center;
```
Comment (jeherve) [inline _inc/client/plans/style.scss:268]: You'll want to use tabs instead of spaces here, or the next person editing this file may transform all those on save.

**Review by jeherve — DISMISSED** [review]

File: _inc/client/plans/single-product-search/index.jsx [hunk 11]
```diff
@@ -18,13 +18,14 @@ import {
...
+import { getPlanDuration } from 'state/plans/reducer';
 import { getUpgradeUrl } from 'state/initial-state';
 import { SEARCH_DESCRIPTION, SEARCH_TITLE } from '../constants';
 import PlanRadioButton from '../single-product-components/plan-radio-button';
 import ProductSavings from '../single-product-components/product-savings';
 
-function getTierLabel( priceTierSlug, recordCount ) {
-	switch ( priceTierSlug ) {
+function getTierLabel( productObject, recordCount ) {
+	switch ( productObject.price_tier_slug ) {
```
[the remark this answers is not in the document]
Comment (jsnmoon) [reply _inc/client/plans/single-product-search/index.jsx:28]: I reverted changes to the `getTierLabel` and its invocation. This should no longer occur.

File: _inc/client/plans/single-product-search/index.jsx [hunk 12]
```diff
@@ -35,27 +36,23 @@ function getTierLabel( priceTierSlug, recordCount ) {
 			return __( 'Up to 100,000 records' );
 		case JETPACK_SEARCH_TIER_UP_TO_1M_RECORDS:
 			return __( 'Up to 1,000,000 records' );
-		case JETPACK_SEARCH_TIER_MORE_THAN_1M_RECORDS:
+		case JETPACK_SEARCH_TIER_MORE_THAN_1M_RECORDS: {
 			const tierMaximumRecords = 1000000 * Math.ceil( recordCount / 1000000 );
-			return __( 'Up to %(tierMaximumRecords)s records', {
+			return __( 'Tier %(tierNumber)s: Up to %(tierMaximumRecords)s records', {
```
[the remark this answers is not in the document]
Comment (jsnmoon) [reply _inc/client/plans/single-product-search/index.jsx]: Ah, good catch. I forgot to revert this specific line; thanks!

File: _inc/client/plans/single-product-components/upgrade-button.jsx [hunk 13]
```diff
@@ -28,7 +28,7 @@ export default function UpgradeButton( {
 	return (
 		<div className="single-product-backup__upgrade-button-container">
 			<Button href={ link } onClick={ onClickHandler( type ) } primary>
-				{ __( 'Upgrade to %(name)s for {{price/}} %(billingTimeFrame)s', {
```
[the remark this answers is not in the document]
Comment (jsnmoon) [reply _inc/client/plans/single-product-components/upgrade-button.jsx:31]: Good catch. I've updated the translate function call and removed the corresponding props.

File: _inc/client/plans/style.scss (hunk 10 above)
Comment (jsnmoon) [reply _inc/client/plans/style.scss]: I went ahead and applied a Prettier transformation on this file.

**Comment by jsnmoon** [comment]
@jeherve & @zinigor: This should be ready for another round of reviews. Thank you for your patience!

**Review by zinigor — APPROVED** [review]
Thanks for reverting the switch change, it now works well for me, no more console errors.

**Comment by jeherve** [comment]
Cherry-picked to `branch-8.4` in 9ed0894fc5e4ee9f4eeab49d0ada165f79f1ce6e
