### PR TITLE
Fixes sitemaps PHP compatibility issue.

### LINKED ISSUE #6918: Array dereferencing in Jetpack 4.8 sitemap module breaks sites running PHP < 5.4
#### Steps to reproduce the issue

1. Have a site running a version of PHP lower than 5.4. Mine is running 5.2.17.
2. Install Jetpack 4.7.
3. Activate the Sitemap module.
4. Attempt to upgrade to Jetpack 4.8.

The site will now be inaccessible due to PHP 5.2's inability to parse the array dereferencing on line 87 of `modules/sitemaps/sitemap-state.php`:

```
$state['max'] = get_option( 'jetpack-sitemap-state', self::initial() )['max'];
```

wp-admin reported that the update failed, but it apparently still succeeded far enough to break the site.  The failure report may have just been because the AJAX endpoint was broken too, so the still-loaded front end interpreted that as an update failure.

#### Steps to prevent this issue in the future.

On a host running the bare minimum version of PHP that will be supported, this command will list any PHP files that cannot be parsed by this version of PHP:

```
for file in `find . -name "*.php"`; do php -l "$file" | grep -v "No syntax errors detected"; done
```

### PR DESCRIPTION
**Pull request by zinigor**
Fixes #6918 

#### Changes proposed in this Pull Request:
* Fixes array dereference in the sitemaps code.
* Adds a unit test to run linting on all PHP files in the plugin, huge props co @cfinke for the suggestion and the code.

#### Testing instructions:
* Make sure Sitemaps work as they did before.
* See if Travis runs OK for all PHP versions.

#### Proposed changelog entry for your changes:
* Made changes to the code to make it compatible with PHP versions older than 5.4.

### CODE REVIEW

File: tests/php/test_php-lint.php [hunk 1]
```diff
@@ -0,0 +1,24 @@
+<?php
+
+class WP_Test_Jetpack_PHP_Lint extends WP_UnitTestCase {
+
+	/**
+	 * Props to cfinke for the amazing piece of code.
+	 * @author zinigor
+	 * @since 4.8.1
+	 */
+	public function test_php_lint() {
```
Comment (dereksmart) [inline tests/php/test_php-lint.php]: This is very nice

**Comment by dereksmart** [comment]
Ship this!

**Comment by dereksmart** [comment]
Moved to 4.8 as well f7a8c0b2a
