### PR TITLE
Search: fix upgrade paths for free plan

### LINKED ISSUE #27003: Search: Upgrade paths for Search in Jetpack broken
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install and connect the bleeding edge Jetpack plugin. Just a Free plan.
2. Poke around in the wp-admin UI to see the upsells for Search:
- /wp-admin/admin.php?page=my-jetpack#/add-search (Linked from My Jetpack)
- /wp-admin/admin.php?page=jetpack#/product/search (Linked from At a Glance)

### A clear and concise description of what you expected to happen.

When using the Store Sandbox you should see the new pricing and new pricing page. When not using the store sandbox you should see the old pricing and old pricing page.

### What actually happened

Without store sandbox the upgrade pages look like (the second one is fine and the first is ugly, not sure why we need two):
Screen Shot 2022-10-21 at 12 35 13

Screen Shot 2022-10-21 at 12 35 32

With the store sandbox (and so we should see Free as an option) everything is wrong:
Screen Shot 2022-10-21 at 12 38 11

Screen Shot 2022-10-21 at 12 38 37

### Browser

Google Chrome/Chromium

### Other information

_No response_

### Platform (Simple, Atomic, or both?)

Self-hosted

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by trakos**
Fixes #27003

#### Changes proposed in this Pull Request:
Our free plan should be visible once we flip the `pricing_version` field in API to `202208`.
Currently, in two places it still had to be forced by adding `&new_pricing_202208=1` to URL manually.
Those places were reachable from `My Jetpack`, `Settings -> Performance`, and `Dashboard -> At a glance`.

In this commit, I'm fixing the "My Jetpack" page so that it uses return value from API to see if the new pricing is active.

I also made it so that we redirect to the Search dashboard (which doubles as a pricing page when search isn't purchased)
instead of page `/wp-admin/admin.php?page=my-jetpack#/add-search`.
Search dashboard already does the API check, so it resolves this issue.

The remaining known issue is that `Settings` and `At a glance` still show `Purchase` instead of `Start for free` for Search.
We'll fix that in the next version, once free plan and new pricing is fully released.
It's probably not worth doing the API call to check for it.

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Jetpack product discussion
p1666377950913959-slack-C02ME06LF

#### Does this pull request change what data or activity we track or use?
No

#### Testing instructions:
This requires the "Jetpack Sandbox Store" plugin activated to make sure that the free option shows up.

There are 3 places in the full Jetpack plugin to check:
- `My Jetpack`
- `Settings` -> `Performance`
- `Dashboard` -> `At a glance`

In all 3 of those places, the link to Purchase Jetpack Search should lead to a page providing an option to start free plan when the store is sandboxed. With live store, it should show only the paid plan.

### CODE REVIEW

File: projects/packages/my-jetpack/src/products/class-search.php [hunk 1]
```diff
@@ -155,11 +155,21 @@ public static function get_wpcom_free_product_slug() {
...
 	 */
 	public static function is_new_pricing_202208() {
 		// phpcs:ignore WordPress.Security.NonceVerification.Recommended, WordPress.Security.ValidatedSanitizedInput.InputNotSanitized, WordPress.Security.ValidatedSanitizedInput.MissingUnslash
-		return isset( $_GET['new_pricing_202208'] ) && $_GET['new_pricing_202208'];
+		if ( isset( $_GET['new_pricing_202208'] ) && $_GET['new_pricing_202208'] ) {
+			return true;
+		}
+
+		$record_count   = intval( Search_Stats::estimate_count() );
+		$search_pricing = static::get_pricing_from_wpcom( $record_count );
```
Comment (trakos) [inline projects/packages/my-jetpack/src/products/class-search.php:167]: Note that we aren't concerned with `$record_count` here, but since we use it as a key in static array, effectively cache, typically we won't have to do the actual API call that way.

**Review by kangzj — APPROVED** [review]
LGTM
