### PR TITLE
Gutenframe: Redirect logged out users

### LINKED ISSUE #32904: Gutenframe: "Please log in" prompt is broken or confusing for users.
p7DVsv-6sB-p2 (`#comment-20126`)

Some users' issues have been fixed by disconnecting and reconnecting Jetpack, but it's unclear if the users had any issues with just logging in.

**Steps to reproduce**
- Make sure you are unproxied and logged in as a non-A8C user with access to an Atomic site.
- In order to ensure you don't have any auth cookie from the WP Admin side, use a private/incognito session.
- Go to https://wpcalypso.wordpress.com/block-editor and select an Atomic site.
- ❌See the ‘Please log into your Jetpack-connected site to use the block editor on WordPress.com.’ screen

### PR DESCRIPTION
**Pull request by obenland**
Fixes https://github.com/Automattic/wp-calypso/issues/32904

Rather than just presenting users an error message, let's show them the login form. If the SSO module is enabled, then we don't show the SSO login form, but just logs in users by going through WP.com. The nice side effect of that is that Jetpack sites with SSO enabled won't even know they were ever logged out.

### Testing instructions:

Note: While testing an Atomic site, you can ensure you're logged out by being unproxied, logged in as a non-A8C user and using a private / incognito session.

#### Jetpack and Atomic sites with SSO disabled
* Go to https://wpcalypso.wordpress.com/block-editor/post/ and select a Jetpack or Atomic site where you're logged out.
* Confirm you see the login form.
* Submit your self-hosted credentials.
* Make sure you see the block editor now.

#### Jetpack and Atomic sites with SSO enabled
* Go to https://wpcalypso.wordpress.com/block-editor/post/ and select a Jetpack or Atomic site where you're logged out.
* Make sure you see the block editor without entering any credentials.

### Proposed changelog entry for your changes:
* Block Editor on WordPress.com: Redirects logged-out users to their sites block editor, rather than just showing an error message.

### CODE REVIEW

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 1]
```diff
@@ -87,6 +82,39 @@ public function disable_send_frame_options_header() {
...
+		// phpcs:ignore WordPress.Security.NonceVerification
+		if ( empty( $_GET['redirect_to'] ) ) {
+			return;
+		}
+
+		// phpcs:ignore WordPress.Security.NonceVerification
+		$query = wp_parse_url( urldecode( $_GET['redirect_to'] ), PHP_URL_QUERY );
+		$args  = wp_parse_args( $query );
+
+		if ( $this->framing_allowed( $args['frame-nonce'] ) ) {
```
Comment (mdawaffe) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: We should probably bail if `$args['frame-nonce']` is empty.

**Review by mdawaffe — DISMISSED** [review]

**Review by codebykat — DISMISSED** [review]
This is a beautiful flow and I love it! Works very well for me.

**Comment by kwight** [comment]
This is a much-improved experience <3

I noticed that the login gives the option to log in as a different user; this flow will break (ending in Mr. Sad Browser). However, reloading again will present a different version of the login modal that _doesn't_ have that option; can we go straight to _that_ modal?

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 2]
```diff
@@ -96,7 +96,7 @@ public function allow_block_editor_login() {
 		$query = wp_parse_url( urldecode( $_GET['redirect_to'] ), PHP_URL_QUERY );
 		$args  = wp_parse_args( $query );
 
-		if ( $this->framing_allowed( $args['frame-nonce'] ) ) {
+		if ( ! empty( $args['frame-nonce'] ) && $this->framing_allowed( $args['frame-nonce'] ) ) {
```
Comment (kwight) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Can we move this up to with the `redirect_to` check?

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: I'm not sure how, we first have to parse it out of the `redirect_to` parameter to be able to test it

Comment (kwight) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Oh! Now I see, got it. 👍

**Comment by mmtr** [comment]
Nice enhancement!

Note that, since we don't have enabled JP Gutenframe yet on production, I couldn't test this on wordpress.com, so I tested locally and in wpcalypso.wordpress.com / horizon.wordpress.com. Also, note that while testing on `wpcalypso` or `horizon` I had to select a JP site with a SSL cert, since we don't use Gutenframe flows if we cannot embed the iframe over a HTTPS secure connection.

Once I have chosen the appropriate environment, I can see the login form within the iframe. But when I click on the login button, a new tab is opened. Not sure if the new tab is expected. Can we keep the navigation in the iframe?

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 3]
```diff
@@ -67,14 +68,8 @@ public function is_iframed_block_editor() {
 	 */
 	public function show_error_if_logged_out() {
```
Comment (mmtr) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: We probably want to rename this function and its docstring.

Comment (mmtr) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Actually, we don't need this function at all since this is the default behavior of WordPress: if redirects the user to the login page with the URL they are attempting to access as `redirect_to` param.

Comment (mmtr) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Removed in 537b61b3a9f748bcaaf3cbb6d71447f3404f5f5b

**Comment by mmtr** [comment]
> I can see the login form within the iframe. But when I click on the login button, a new tab is opened. Not sure if the new tab is expected. Can we keep the navigation in the iframe or at least in the same tab?

Checked this only happens when SSO is enabled. Definitely not a blocker for this PR.

**Review by mmtr — DISMISSED** [review]

**Review by jeherve — COMMENTED** [review]
When SSO is not active on the site, I find the flow a bit confusing. I am on WordPress.com, I am logged in, and I am asked to log in again? 

image

It turns out that I have to enter my self-hosted site credentials here, not my WordPress.com credentials, even though I am on WordPress.com.

The error message appearing above the form is also a bit confusing: I logged out, my session did not expire.

> Your session has expired. Please log in to continue where you left off.

If I then try to enter my self-hosted credentials and submit, no new page loads. I stay on ``, and the following error appears in my JS console:

`Unchecked runtime.lastError: The message port closed before a response was received.` -- wp-login.php?redirect_to=...

Hm, actually while I was copying that error message and pasting it here, the page refreshed and now displays the block editor. That was odd. Is this how the flow should go?

**Comment by obenland** [comment]
Yeah it's for sure not perfect. Let me see if we can change the message somehow.
I do think that the flow is less jarring than the wp_die message, but I'm more than open to alternative approaches.

**Comment by obenland** [comment]
> If I then try to enter my self-hosted credentials and submit, no new page loads. I stay on ``, and the following error appears in my JS console:
> 
> `Unchecked runtime.lastError: The message port closed before a response was received.` -- wp-login.php?redirect_to=...

I also see the runtime error when trying to log in. @dmsnell Does that sound familiar to you?

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 4]
```diff
@@ -58,35 +58,69 @@ public function is_iframed_block_editor() {
...
+		if ( empty( $_REQUEST['redirect_to'] ) ) {
+			return;
+		}
+
+		// phpcs:ignore WordPress.Security.NonceVerification
+		$query = wp_parse_url( urldecode( $_REQUEST['redirect_to'] ), PHP_URL_QUERY );
+		$args  = wp_parse_args( $query );
+
+		if ( ! empty( $args['frame-nonce'] ) && $this->framing_allowed( $args['frame-nonce'] ) ) {
+			$_REQUEST['interim-login'] = true;
```
Comment (kwight) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Directly manipulating `$_REQUEST` like this feels wrong (like changing `$_GET` query params). Is there any other way to accomplish this?

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: [There is not](https://core.trac.wordpress.org/browser/tags/5.1.1/src/wp-login.php#L486).

**Comment by kwight** [comment]
The sign-in prompt has lost all of its top margin, and has a widow in the message now:

Screen Shot 2019-05-02 at 10 50 44 AM

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php (hunk 4 above)
Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Well, that's not entirely true. We could add it to the iframe url.

**Comment by obenland** [comment]
> The sign-in prompt has lost all of its top margin

Yes, in Core this version of the login form is displayed in a modal, overlaying the Editor or Customizer.

> [The sign-in prompt] has a widow in the message now:

I'm open to suggestions as to how to shape that message better!

**Comment by kwight** [comment]
A few more notes:
* I'm also seeing the new tab open when clicking "Log in with WordPress.com".
* Re: the runtime message, I'm 99% sure it's from the https://github.com/gatsbyjs/gatsby/issues/9899#issuecomment-465887318 (it triggers when the modal to save my login form credentials pops up). I can replicate this outside of the iframe, in a different tab.

**Comment by kwight** [comment]
> I'm open to suggestions as to how to shape that message better!

I think we could leave it as "Please log in to your Jetpack site."?..

**Comment by obenland** [comment]
Thanks for the feedback everyone! I'll do more testing with SSO before putting it up for review again

**Comment by obenland** [comment]
I think this is ready for another round of reviews.

It now doesn't even show the SSO login form, but just logs in users by going through wp.com. The nice side effect of that is that Jetpack sites with SSO enabled won't even know they were ever logged out.

I also brought back the top margin of the login form.

**Comment by mmtr** [comment]
The experience for SSO users seems perfect now, and this also fixes the strange issue we have with Atomic sites (https://github.com/Automattic/wp-calypso/issues/32904).

Although I have some concerns about showing the login form when SSO is disabled (I think it can be confusing, especially for Atomic users), I believe this is better than showing the current error message.

Maybe we could use a different message than "Before we continue, please log in to your Jetpack site."? Atomic users probably won't understand what _Jetpack site_ means (and maybe Jetpack users too?), so how do you feel about saying something like "Before we continue, please enter your WP Admin credentials."?

Other thing I noted is that after entering my credentials and clicking on the submit button, I don't see any change in the UI (I still see the login form) and it takes about 10/15 seconds to see the block editor (see [this video](https://cloudup.com/c-uHyRgLnJt)). Do we have any way of making clear we're loading the editor? Something like disabling the Submit button and replace the text with "Submitting..." should be enough.

**Comment by mmtr** [comment]
> Other thing I noted is that after entering my credentials and clicking on the submit button, I don't see any change in the UI (I still see the login form) and it takes about 10/15 seconds to see the block editor (see [this video](https://cloudup.com/c-uHyRgLnJt)). Do we have any way of making clear we're loading the editor? Something like disabling the Submit button and replace the text with "Submitting..." should be enough.

Managed to implement something exploring that approach but it feels very hacky:

```php
wp_register_script( 'wpcom-block-editor-login', '', [], false, true );
wp_enqueue_script( 'wpcom-block-editor-login' );
$logging_in = __( 'Logging In…', 'jetpack' );
$script = "document.getElementById( 'loginform' ).addEventListener( 'submit' , function() {
	document.getElementById( 'wp-submit' ).setAttribute( 'disabled', 'disabled' );
	document.getElementById( 'wp-submit' ).value = '$logging_in';
} );";
wp_add_inline_script( 'wpcom-block-editor-login', $script );
```

But seems to offer a better user experience: https://cloudup.com/cVqz2m-OZ5t

**Comment by jeherve** [comment]
> I have some concerns about showing the login form when SSO is disabled (I think it can be confusing, especially for Atomic users)

I agree it can be confusing, but I don't think that's something Atomic site owners will run into, since SSO is always active for them.

**Comment by obenland** [comment]
> Other thing I noted is that after entering my credentials and clicking on the submit button, I don't see any change in the UI

Yeah I noticed that too. I'm sure we can make your script look a little bit less hacky, if that's our only concern. I like where it's going

File: modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php [hunk 5]
```diff
@@ -104,13 +145,15 @@ public function add_iframed_body_class( $classes ) {
...
 	 *
+	 * @param string $nonce Optional. Nonce to verify. Default $_GET['frame-nonce'].
 	 * @return bool
 	 */
-	public function framing_allowed() {
-		$verified = $this->verify_frame_nonce(
-			$_GET['frame-nonce'], // phpcs:ignore WordPress.Security.NonceVerification
-			'frame-' . Jetpack_Options::get_option( 'id' )
-		);
+	public function framing_allowed( $nonce = '' ) {
```
Comment (kwight) [inline modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: Since we're the only consumers of this method, can we just make it require a nonce, rather than the backup value dance below (that may or may not exist)? That way we can have `framing_allowed` always called with a param, and just skip the empty check.

Comment (obenland) [reply modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php]: I'm not sure how I feel about f196f4b, but if it gets this approved faster…

**Comment by kwight** [comment]
This tests really well now, with both Atomic and Jetpack sites, and admin and non-admin users (also SSO and without). I was able to find a particular test user of mine that always hits a server (not WP) 401 on a certain v1 Atomic site; however, the same user works on other Atomic sites, and other users work on that Atomic site, so I have no explanation of what edge-case I'm hitting, or if it's an issue non-a11s will see in production. Considering the positive testing of everything else, I wouldn't want it to be a blocker.

I also found an edge case that causes the user to hit [this wall](https://github.com/Automattic/jetpack/blob/master/modules/wpcom-block-editor/class-jetpack-wpcom-block-editor.php#L176):

Screen Shot 2019-05-09 at 11 35 39 AM

If a user:
* is logged in as user A,
* loads the block editor, successfully setting the auth cookies on the Jetpack site,
* then logs out of WordPress.com,
* and back into WordPress.com as user B,
* then loads the same JP site's block editor again,
* the existing cookies for the Jetpack site will be for user A (triggering the mismatch).

I'm not sure how best to handle this; is there a way to have logging out of WordPress.com invalidate cookies on other sites set by that session (I know not of the things I speak of)? Or maybe we could go to the `wp_die()` approach for handling this, with instructions to clear cookies for that domain (ewwww)?

**Review by kwight — DISMISSED** [review]
Tests well, and I couldn't find any blockers.

**Review by mmtr — DISMISSED** [review]

**Comment by jeherve** [comment]
Rebasing to test, I hope you don't mind. I was getting quite a few unrelated errors while testing.

**Review by jeherve — APPROVED** [review]
> I also found an edge case that causes the user to hit this wall
I ran into the same error when logged in to WordPress.com with my regular user, but logged in to the site with a different, non-connected user.	

-------

I also ran into another edge-case:

0. Unproxied, logged in to a non-a11n wpcom account.
1. Start on a Jetpack site with SSO enabled.
2. You are logged in as an editor on the site.
3. You link your editor account to the non-a11n wpcom account using the button in the Jetpack menu.
4. Once that's complete, log out of your editor account.
5. Log back in using your admin account, go to Jetpack > Settings, and turn on that option: `Require accounts to use WordPress.com Two-Step Authentication`
6. Log out again.
7. Go to https://wpcalypso.wordpress.com/block-editor/post/, pick the site

image

```
Refused to display 'https://xxx.jurassic.ninja/wp-login.php?action=jetpack-sso&result=success&user_id=50931389&sso_nonce=zbd9pqyagkrgdi5ddkwp' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

- That User ID is correct.
- It seems to happen when I am proxied as well.
- What I should be seeing instead is something similar to this:
image

I think we could merge this PR and address those 2 edge-cases in another PR? Approving this one, the decision is yours!

**Comment by kwight** [comment]
https://github.com/Automattic/jetpack/issues/12336 for followup.

**Comment by jeherve** [comment]
Cherry-picked to `branch-7.3` in 9da6976db71b07e59b760697590969506e499196
