### PR TITLE
Lazy Images: Add callback for processing image attributes array

### LINKED ISSUE #8320: Lazy load not working on archive pages
#### Steps to reproduce the issue

Visit archive pages on https://dev.get-business-online.com/ronitbaras/ and look at the code.

#### What I expected

Lazy loading attributes on IMG tags.

#### What happened instead

No lazy loading attributes and no lazy loading behavior. WooCommerce archives are OK and so are posts and pages, but archives just load their images normally.

#### Environment

Genesis Framework with custom child theme - no relevant image or thumbnail filters. No caching and no other plugins involved in serving images that I can think of.

On another site, which isn't based on Genesis, lazy loading works OK on archive pages.

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #8320

In #8320, @galbaras reported that Lazy Images wasn't working on archive pages in Genesis. He further determined that this is because Genesis uses the `wp_get_attachment_image` function to display images on the archive page. Because of this, we weren't hooking in to lazily load those images.

This PR fixes that by refactoring Lazy Images so that there is a static method to modify an array of image attributes. This method is now called by `Jetpack_Lazy_Images::process_image()`, but it can also be used to handle lazy loading images generated via `wp_get_attachment_image`, since that function sends an array of attributes via the `wp_get_attachment_image_attributes` filter.

To test:

- Test that lazy images continue to load properly on a test site
- `phpunit --filter=WP_Test_Lazy_Images`
- In `wp shell`, run the following and ensure lazy load attributes get added.

```php
add_filter( 'wp_get_attachment_image_attributes', array( 'Jetpack_Lazy_Images', 'process_image_attributes' ), PHP_INT_MAX );
return wp_get_attachment_image( $some_attachment_id_here );
```

### CODE REVIEW

**Comment by gravityrail** [comment]
I bought and installed the Genesis theme and was able to reproduce by going into the Genesis settings and enabling a left-aligned, resized thumbnail.

I confirmed that it was not lazy-loaded before, and is now! Huzzah!

File: modules/lazy-images/lazy-images.php [hunk 1]
```diff
@@ -81,6 +83,15 @@ public function add_image_placeholders( $content ) {
 		return $content;
 	}
 
+	/**
+	 * Processes images in content by acting as the preg_replace_callback
+	 *
+	 * @since 5.6.0
```
Comment (oskosk) [inline modules/lazy-images/lazy-images.php]: Maybe should be 5.7 now

Comment (ebinnion) [reply modules/lazy-images/lazy-images.php]: That method was actually added in 5.6. I'm just now added a docblock though.

Comment (oskosk) [reply modules/lazy-images/lazy-images.php]: hahaha great. Thanks!
