### PR TITLE
Carousel: Update to manage new core gallery block format

### LINKED ISSUE #21097: Carousel: new gallery block format breaks carousel
### Impacted plugin

Jetpack

### Steps to Reproduce

- Turn on Jetpack carousel option and the gutenberg gallery experiment (need to install latest gutenberg plugin)
- Add a gallery block with images notice the carousel is not loading as expected in frontend

### A clear and concise description of what you expected to happen.

Expected carousel to load with the new gallery block format

### What actually happened

Carousel did not load when the Gutenberg new gallery block experiment is enabled

### Other information

_No response_

### Operating System

macOS

### OS Version

_No response_

### Browser

Chrome/Chromium

### Browser Version(s)

_No response_

### PR DESCRIPTION
**Pull request by glendaviesnz**
Fixes #21097

#### Changes proposed in this Pull Request:

* Upates handling of new core gallery block in the carousel as the selectors were changed in some of the core block iterations

#### Does this pull request change what data or activity we track or use?
no

#### Testing instructions:
* Check out this PR and run in local dev env along with latest release of gutenberg plugin with the experimental gallery flag enabled and the carousel lightbox option enabled
* Add a new gallery block with a number of images and check that the carousel loads correctly in the frontend
* Try changing the block to a few different alignments and check that the carousel continues to work
* Also test a number of galleries on the same post and page and that carousel runs for each
* Disable the gallery experiment flag and add another old style gallery block to the same page/post and make sure carousel runs for this also

### CODE REVIEW

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.php [hunk 1]
```diff
@@ -756,7 +756,7 @@ class_exists( 'Jetpack_AMP_Support' )
 				$html = str_replace( '<div ', '<div ' . esc_attr( $data_key ) . "='" . wp_json_encode( $data_values ) . "' ", $html );
 				$html = str_replace( '<ul class="wp-block-gallery', '<ul ' . esc_attr( $data_key ) . "='" . wp_json_encode( $data_values ) . "' class=\"wp-block-gallery", $html );
 				$html = str_replace( '<ul class="blocks-gallery-grid', '<ul ' . esc_attr( $data_key ) . "='" . wp_json_encode( $data_values ) . "' class=\"blocks-gallery-grid", $html );
-				$html = str_replace( '<figure class="wp-block-gallery blocks-gallery-grid', '<figure ' . esc_attr( $data_key ) . "='" . wp_json_encode( $data_values ) . "' class=\"wp-block-gallery  blocks-gallery-grid", $html );
+				$html = preg_replace( '/\<figure class="(wp-block-gallery.*has-nested-images.*)"/', '<figure ' . esc_attr( $data_key ) . "='" . wp_json_encode( $data_values ) . "' class=\"$1\"", $html );
```
Comment (andrewserong) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.php:759]: This has been working for me in testing, but I'm wondering if this regex is slightly too greedy? This is a bit of a fabricated example, but the regex group will match across multiple tags if the post content includes a figure element with `wp-block-gallery` but not `has-nested-images`, and any other element that has `has-nested-images` in it:

image

Are there any situations where `wp-block-gallery blocks-gallery-grid` isn't the first set of classes? If not, we might be able to swap it out for the `str_replace`, but if the order does change sometimes, then maybe something like the following might fix the above issue?

```
\<figure class="(wp-block-gallery[^"].*?has-nested-images.*?)"
```

The above adds a negated set after the gallery class to check that it doesn't include `"` before `has-nested-images` and makes the checks lazy, which seemed to make my test strings in regexr.com happy.

Another potential challenge is that the way the block gap support currently works in Gutenberg is that [it will inject](https://github.com/wordpress/gutenberg/blob/f0ee75922094f4d96cd72947970da4f956af61dd/lib/block-supports/spacing.php#L133-L133) a `style `attribute before the `class` attribute if one doesn't exist in the markup. This would mean that the string `<figure class="wp-block-gallery"` wouldn't match, which will be a problem longer-term for this code that's adding data to the container 🤔

I wonder if longer-term if it'd be worth refactoring the Jetpack code in [check_content_for_blocks](https://github.com/Automattic/jetpack/blob/e063c73904b8da170716b48d804e619fd4e02b9f/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php#L214-L214) to use the blocks' render callbacks to update the markup instead of the entire post content? Since we've parked the gallery block gap support for the time being, I don't think this is a blocker for this PR, just something for us to keep in mind when we do get back to implementing it.

**Review by andrewserong — COMMENTED** [review]
Thanks for picking this one up @glendaviesnz! It's working okay for me on a post that just contains the new gallery block. However if a post contains both the new gallery block and an old gallery block (use case is someone adding an additional gallery to an existing post or page, but not updating the old ones), it looks like the carousel fails when opening the new gallery:

Kapture 2021-09-21 at 16 39 03

The error message is:

```
jetpack-carousel.js?ver=10.2-alpha:80 Uncaught TypeError: Cannot read properties of undefined (reading 'closest')
    at Object.closest (jetpack-carousel.js?ver=10.2-alpha:80)
    at initCarouselSlides (jetpack-carousel.js?ver=10.2-alpha:1337)
    at openCarousel (jetpack-carousel.js?ver=10.2-alpha:1509)
    at loadSwiper (jetpack-carousel.js?ver=10.2-alpha:1456)
    at HTMLBodyElement.<anonymous> (jetpack-carousel.js?ver=10.2-alpha:1647)
```

I couldn't quite work out what was throwing it before wrapping up for the day, and I've left a comment on the regex for matching against the new block markup. Happy to help test further tomorrow!

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.js [hunk 2]
```diff
@@ -305,11 +305,12 @@
 
 		var gallerySelector =
 			'div.gallery, div.tiled-gallery, ul.wp-block-gallery, ul.blocks-gallery-grid, ' +
-			'figure.blocks-gallery-grid, div.wp-block-jetpack-tiled-gallery, a.single-image-gallery';
+			'figure.wp-block-gallery.has-nested-images, div.wp-block-jetpack-tiled-gallery, a.single-image-gallery';
 
 		// Selector for items within a gallery or tiled gallery.
 		var galleryItemSelector =
-			'.gallery-item, .tiled-gallery-item, .blocks-gallery-item, ' + ' .tiled-gallery__item';
+			'.wp-block-image, .gallery-item, .tiled-gallery-item, .blocks-gallery-item, ' +
```
[the remark this answers is not in the document]
Comment (glendaviesnz) [reply projects/plugins/jetpack/modules/carousel/jetpack-carousel.js]: ah, yeh, nice catch, this is redundant, have removed.

**Comment by glendaviesnz** [comment]
@andrewserong thanks for the suggestions re regex. We can't guarantee that `wp-block-gallery` will always be followed by `has-nested-images` as the alignment classes can end up between them. I did think about modifying the gallery block to try and ensure that they followed each other, but that makes the carousel code a bit fragile, and  the gallery block probably shouldn't be worrying about what other blocks might be doing with those class listings.

I have made the change you suggested to the regex and also tried to account for any styles that may come before the classes. It seems to be working as expected now, and I can't replicate the issue with the old and new galleries now - not sure if that was related or not, but can you see if you still have that problem please.

I have also added a note to test adding alignment to the gallery blocks as doing this changes the class structure as mentioned above.

**Review by andrewserong — COMMENTED** [review]
Thanks again @glendaviesnz, and the alignment class situation is a great reason to go for the regex. I've tested it with a few more strings to try to break it on regexr.com, and have added a couple more suggestions for tweaks.

The broken gallery issue that I encountered yesterday appears to still be here for me in testing. I think the issue is pretty edge-casey, here's how I could reliably reproduce it:

1. Insert a new gallery block
2. Switch off the gallery experiment
3. Insert an old gallery further down the post or page, using the same images as in the new gallery
4. Publish the post, and on the front end the new gallery will fail when opening the carousel

When I inspected the markup of the post, the images in the new gallery weren't getting the `data-attachment-id` and related attributes added. This appears to be due to the logic around line 605 in [add_data_img_tags_and_enqueue_assets](https://github.com/Automattic/jetpack/blob/0a391086cf0c2a768f8cd2fe8c93013fd52c6bde/projects/plugins/jetpack/modules/carousel/jetpack-carousel.php#L605-L605). It looks like the logic works as follows:

* Look for an img tag with either `wp-image` or `data-id` attribute
* Grab the attachment id from the class or data id
* Add the markup to the array of `$selected_images`, keyed by the attachment id

In the above situation where there's a new gallery followed by an old gallery, by the time the `img` tags are matched for the old gallery, the markup for the images with the same id in the new gallery gets overridden in `$selected_images` so the new gallery's images don't get the attributes added. Funnily enough, I could only replicate this when the old gallery appears _after_ all the new galleries in the post!

Then, when the carousel is instantiated the [imgSelector](https://github.com/Automattic/jetpack/blob/948156df28062b1923dde4f3178a2487adc2edd2/projects/plugins/jetpack/modules/carousel/jetpack-carousel.js#L1460-L1460) can't find any images in the gallery, so `items` winds up being empty.

Are you able to reproduce this in your environment? It feels very much an edge case, but I can imagine someone potentially winding up running into it in a fairly complex page of galleries that they update over time 🤔

File: projects/plugins/jetpack/modules/carousel/jetpack-carousel.php [hunk 3]
```diff
@@ -606,10 +606,12 @@ class_exists( 'Jetpack_AMP_Support' )
 				! preg_match( '/wp-block-jetpack-slideshow_image/', $image_html ) ) {
 				$attachment_id = absint( $class_id[2] );
 				/**
-				 * If exactly the same image tag is used more than once, overwrite it.
-				 * All identical tags will be replaced later with 'str_replace()'.
+				 * The same image tag may be used more than once but with different attribs,
+				 * so save each of them against the attachment id.
 				 */
-				$selected_images[ $attachment_id  ] = $image_html;
+				if ( ! isset( $selected_images[ $attachment_id ] ) || ! in_array ( $image_html, $selected_images[ $attachment_id ] ) ) {
```
Comment (andrewserong) [inline projects/plugins/jetpack/modules/carousel/jetpack-carousel.php:612]: PHPCS is complaining that `in_array (` has a gap between the function name and the parenthesis, and that `in_array` isn't providing `true` as its third argument.

**Review by andrewserong — COMMENTED** [review]
Nice work @glendaviesnz! That's testing great for me now on a number of different posts with a mix of old and new galleries and standalone image blocks. I haven't been able to fault it 👍 

Just left a comment about a PHPCS error, but other than that, this looks good to me!

**Review by andrewserong — APPROVED** [review]
Works nicely, thanks again for all the fixes, tweaks and follow-ups @glendaviesnz! LGTM 🚀

**Review by jeherve — APPROVED** [review]
Tests well for me. 🚢

**Comment by glendaviesnz** [comment]
rWP232383
