### PR TITLE
Boost: Fix CSS generation failing on single provider failure

### LINKED ISSUE #42055: Boost: Failing to update a provider, shouldn't break the whole process
If for some reason a request to update the CSS of a provider fails (let's say with a 403 due to some firewall rules detecting the CSS as malicious), it shouldn't fail the whole generation.

### Steps to reproduce:

- Setup Boost free;
- Add this snippet to your website (it will cause a 403 when Boost tries to update css for the singular_post group):

```php
add_action( 'rest_api_init', function() {
	add_filter( 'rest_request_before_callbacks', function( $response, $handler, $request ) {
		if ( $request->get_method() === 'POST' && strpos( $request->get_route(), '/set-provider-css' ) !== false ) {
			$params = $request->get_json_params();
			if ( isset( $params['JSON'] ) && isset( $params['JSON']['key'] ) && $params['JSON']['key'] === 'singular_post' ) {
				error_log( 'Blocking POST request to /set-provider-css endpoint for singular_post' );
				status_header(403);
				nocache_headers();
				die();
			}
		}
		return $response;
	}, 10, 3 );
} );
```

- Try to generate Critical CSS;
- You should get an error like this one:

Image

### What should actually happen

The process should complete and show a recommendation about that (we don't have a UI pattern for that, so we may need to create one).

### PR DESCRIPTION
**Pull request by dilirity**
This PR prevents failures to update CSS for a provider, from breaking the Critical CSS generation process. This most often happens when there's a 403 on `set-provider-css`.

<details><summary>This means, that there's a new type of recommendation - about the process itself.</summary>

CleanShot 2025-03-11 at 14 25 23

</details>

<details><summary>This also updates the "show stopper" component to give more details if such an error occurs.</summary>

CleanShot 2025-03-11 at 14 30 25

</details>

Fixes https://github.com/Automattic/jetpack/issues/42055
Fixes https://github.com/Automattic/jpop-issues/issues/9572

## Proposed changes:

* Update DataSync to return a more detailed error message;
* Add a new recommendation - ProviderError;
* Prevent errors thrown by `setProviderCss` from breaking the Critical CSS gen process. If an error occurs, it will be properly handled and shown under the advanced recommendations section;
* Add the "raw error" from a failed provider to the ShowStopper component (as seen on the second screenshot);
* Add missing spacing to "Hide error message" on recommendations;
* Update the error message on a recommendation to be expanded by default. This is to make sure that we can see it in case a user sends us a screenshot of the error;
* Update the URL on the "show stopper" to a new line, instead of being carried from the first to the second row.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

n/a

## Does this pull request change what data or activity we track or use?

no

## Testing instructions:

- Test using Boost free;
- Add this snippet to cause the update request for the `singular_post` provider to fail (simulate blocking the request by a hosting's WAF):

```php
add_action( 'rest_api_init', function() {
	add_filter( 'rest_request_before_callbacks', function( $response, $handler, $request ) {
		if ( $request->get_method() === 'POST' && strpos( $request->get_route(), '/set-provider-css' ) !== false ) {
			$params = $request->get_json_params();
			if ( isset( $params['JSON'] ) && isset( $params['JSON']['key'] ) && $params['JSON']['key'] === 'singular_post' ) {
				error_log( 'Blocking POST request to cloud-css/update endpoint for singular_post' );
				status_header(403);
				nocache_headers();
				die();
			}
		}
		return $response;
	}, 10, 3 );
} );
```

- You can also use this snippet, to reduce the number of providers in the group (so generation happens faster, and you don't have to wait for it). Make sure to update the provider keys accordingly:

```php
add_filter( 'jetpack_boost_critical_css_providers', 'jb_pp_replace_critical_css_providers' );
function jb_pp_replace_critical_css_providers( $providers ) {
	$new_providers = array();
	foreach ( $providers as $provider ) {
		if ( $provider['key'] === 'cornerstone_d41d8cd9' || $provider['key'] === 'singular_post' ) {
			$new_providers[] = $provider;
		}
	}
	return $new_providers;
}
```

### Test that the process no longer breaks when updating CSS fails

- Generate Critical CSS and wait for the process to complete;
- You should get one recommendation and it should be similar to the first screenshot.

### Test that if the process fails for all providers, the new recommendation shows up

- Replace the first snippet with this one (this will force a 403 when updating the CSS for all providers):

```php
add_action( 'rest_api_init', function() {
	add_filter( 'rest_request_before_callbacks', function( $response, $handler, $request ) {
		if ( $request->get_method() === 'POST' && strpos( $request->get_route(), '/set-provider-css' ) !== false ) {
			error_log( 'Blocking POST request to cloud-css/update endpoint for all providers' );
			status_header(403);
			nocache_headers();
			die();
		}
		return $response;
	}, 10, 3 );
} );
```

- Generate Critical CSS and you should see the "Show Stopper" error - the second screenshot.

### CODE REVIEW

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts [hunk 1]
```diff
@@ -504,6 +504,30 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+			),
+		rawError: set => Object.values( set.byUrl )[ 0 ].message,
+		suggestion: _set => ( {
+			paragraph: __(
+				'Jetpack Boost successfully generated Critical CSS, but something prevented it from saving it. Usually, this is due to a security plugin or the hosting provider detecting a false-positive.',
+				'jetpack-boost'
+			),
+			list: [
+				__(
+					'Please contact <support>Jetpack Boost Support</support> with a copy of your error message, so they can help you resolve the issue.',
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: Maybe we can add a step about doing a trial error with the security plugin/hosting WAF settings before they escalate to support?

Also this:
```suggestion
					'Please contact <support>Jetpack Boost Support</support> with a copy of your error message, so we can help you resolve the issue.',
```

File: projects/plugins/boost/app/assets/src/js/features/critical-css/numbered-list/numbered-list.module.scss [hunk 2]
```diff
@@ -1,7 +1,7 @@
 .numbered-list {
 	list-style-type: none;
 	margin-left: 0;
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/numbered-list/numbered-list.module.scss]:
```suggestion
```

**Review by haqadn — CHANGES_REQUESTED** [review]
I have a couple of small nitpicks and it needs a trunk merge. I couldn't get to test it today.

**Review by haqadn — CHANGES_REQUESTED** [review]
I have a couple of small nitpicks and it needs a trunk merge. I couldn't get to test it today.

**Review by haqadn — CHANGES_REQUESTED** [review]
I have a couple of small nitpicks and it needs a trunk merge. I couldn't get to test it today.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts (hunk 1 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: > Maybe we can add a step about doing a trial error with the security plugin/hosting WAF settings before they escalate to support?

Can you elaborate on this? Do you mean like dispatching a request to the home page with `<svg xmlns` in the body and see if we get `Forbidden`?

Comment (haqadn) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: No, I am saying to add a step in the instructions where the user checks WAF plugins and hosting configuration for potential restrictions and tries to mitigate them.

Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: I am not sure what that step should say. It sounds like it can be a beefy one. Should we move it to the documentation page maybe?

Comment (haqadn) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: Something like: "Check your hosting configuration or if you are using any security plugin to see if there are restrictions that might be blocking Jetpack Boost."

Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: Asked for help on this one p1741958433451599-slack-C04H7DLTFE3

File: projects/js-packages/react-data-sync-client/src/DataSync.ts [hunk 3]
```diff
@@ -345,7 +345,7 @@ export class DataSync< Schema extends z.ZodSchema, Value extends z.infer< Schema
 			url = this.maybeRequestDisabled( url );
 			const result = await fetch( url, args );
 			if ( ! result.ok ) {
-				throw new DataSyncError( result.statusText, {
+				throw new DataSyncError( `DS request failed: ${ result.status } - ${ result.statusText }`, {
```
Comment (haqadn) [inline projects/js-packages/react-data-sync-client/src/DataSync.ts]: If there is no response body, this looks a bit weird.

image

```suggestion
				let errorText = result.status;
				if( result.statusText ) {
					errorText = `${errorText} - ${result.statusText}`;
				}
				throw new DataSyncError( `DS request failed: ${errorText}`, {
```

**Review by haqadn — DISMISSED** [review]
Works as expected and no issues found on code. I have suggested a minor improvement. Feel free to merge this after that is addressed.

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts (hunk 1 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts]: @haqadn the steps hav been updated based on the input from @alinclamba  here - https://github.com/Automattic/jpop-quill/issues/486

image

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts [hunk 4]
```diff
@@ -504,6 +504,37 @@ const errorTypeSpecs: { [ type: string ]: ErrorTypeSpec } = {
...
+					'jetpack-boost'
+				),
+				__(
+					'<strong>Check your security plugins.</strong> If you have a firewall or security plugin, it might be blocking Boost. Look for any firewall, bot protection, or request-blocking settings and try temporarily turning them off. Then, <retry>try again</retry>.',
+					'jetpack-boost'
+				),
+				__(
+					'<strong>Still stuck?</strong> <support>Contact Jetpack Boost Support</support> and share this error message visible below, so we can look into this and assist.',
+					'jetpack-boost'
+				),
```
Comment (haqadn) [inline projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts:534]: I really like this!

**Review by haqadn — APPROVED** [review]
LGTM

File: projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts (hunk 4 above)
Comment (dilirity) [reply projects/plugins/boost/app/assets/src/js/features/critical-css/lib/describe-critical-css-recommendations.ts:534]: Props to @alinclamba for the suggestion!
