### PR TITLE
Instant Search: Add product ratings to search results

### LINKED ISSUE #18403: Instant Search: Long search result titles breaks multiple layout types
#### Steps to reproduce the issue

1. This occurs in all three result format types (`minimal`, `expanded`, and `product`.
2. Create a post with an excessively long title (e.g. `Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu`.)
3. Search for it.

#### What I expected
For the long title to be truncated somehow.

#### What happened instead
Minimal:
Screen Shot 2021-01-18 at 3 30 41 PM

Expanded:
Screen Shot 2021-01-18 at 3 30 37 PM

Product:
Screen Shot 2021-01-18 at 3 30 47 PM

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Changes proposed in this Pull Request:
* Fixes #18403.
* Render product ratings for the currently unreleased Product search layout.
* Rearrange the Product search result component.
* Tweaks ESLint configuration for the Jetpack Search module to accommodate the `jsx` pragma for Preact.

#### Jetpack product discussion
None.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:

* Apply this change to your Jetpack site with WooCommerce products. You may need to rate some of your products to see the result of this PR.
* Perform a search in the product search layout by appending `result_format=product` to the query string.

#### Proposed changelog entry for your changes:
* None. (Product search layout has not yet been released to the public.)

#### Visual changes:
After: 
Screen Shot 2021-01-12 at 2 25 34 PM

Before:
Screen Shot 2021-01-12 at 2 29 51 PM

### CODE REVIEW

File: modules/search/instant-search/components/product-ratings.jsx [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+ *
+ * @param {object} props - Component properties.
+ * @param {number} props.count - Number of ratings.
+ * @param {number} props.rating - Average rating out of five.
+ * @returns {object} Product rating component.
+ */
+export default function ProductRatings( { rating = 0, count = 0 } ) {
+	return (
+		<div className="jetpack-instant-search__search-result-product-rating">
+			<span className="jetpack-instant-search__search-result-product-rating-stars">
```
Comment (bluefuton) [inline modules/search/instant-search/components/product-ratings.jsx:28]: I think we need to consider how this would work in a screenreader. How about `aria-hidden` on the stars themselves, then adding some descriptive text after the count hidden with the class `screen-reader-text`?

File: modules/search/instant-search/components/product-ratings.jsx [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+				{ Array( 5 )
+					.fill( <Gridicon size={ 16 } icon="star-outline" /> )
+					.fill( <Gridicon size={ 16 } icon="star" />, 0, rating ) }
+			</span>{ ' ' }
+			<span className="jetpack-instant-search__search-result-product-rating-count">{ count }</span>
```
Comment (bluefuton) [inline modules/search/instant-search/components/product-ratings.jsx:33]:
```suggestion
			<span className="jetpack-instant-search__search-result-product-rating-count"><span className="screen-reader-text">Rating:</span> { count }<span className="screen-reader-text">/5</span></span>
```

File: modules/search/instant-search/components/product-ratings.jsx (hunk 1 above)
Comment (jsnmoon) [reply modules/search/instant-search/components/product-ratings.jsx:28]: 👍 Went ahead and implemented something similar.

File: modules/search/instant-search/components/product-ratings.jsx [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+			<span aria-hidden className="jetpack-instant-search__search-result-product-rating-stars">
+				{ Array( 5 )
+					.fill( <Gridicon size={ 16 } icon="star-outline" /> )
+					.fill( <Gridicon size={ 16 } icon="star" />, 0, rating ) }
+			</span>{ ' ' }
+			<span aria-hidden className="jetpack-instant-search__search-result-product-rating-count">
+				{ count }
+			</span>
+			<span className="screen-reader-text">
+				Average rating of { Number( rating ).toFixed( 2 ) } out of 5 from { count } ratings.
```
Comment (bluefuton) [inline modules/search/instant-search/components/product-ratings.jsx:37]: Much better! 👍 Need to translate this though.

Comment (jsnmoon) [reply modules/search/instant-search/components/product-ratings.jsx]: Fixed!

**Review by bluefuton — DISMISSED** [review]
Currently outputs '0' under the price if there's no rating set for the product:

Screen Shot 2021-01-14 at 14 39 59

Also needs a small rebase on api.js 👍

**Comment by bluefuton** [comment]
Tests out well! 

Screen Shot 2021-01-21 at 14 38 06

^ It's not totally clear what the '1' is. Shall we do:

* * * *  * (1 review)

or

* * * * * from 1 review

Thoughts @jeffgolenski?

File: projects/plugins/jetpack/modules/search/instant-search/components/product-ratings.jsx [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+					.fill( <Gridicon size={ 16 } icon="star-outline" /> )
+					.fill( <Gridicon size={ 16 } icon="star" />, 0, rating ) }
+			</span>{ ' ' }
+			<span aria-hidden className="jetpack-instant-search__search-result-product-rating-count">
+				{ count }
+			</span>
+			<span className="screen-reader-text">
+				{ sprintf(
+					_n(
+						'Average rating of %s out of 5 from %s rating.',
```
Comment (bluefuton) [inline projects/plugins/jetpack/modules/search/instant-search/components/product-ratings.jsx:40]: Shall we do "from %s review" / "from %s reviews" instead? That's how the Woo frontend refers to it:

Screen Shot 2021-01-21 at 14 42 25

Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/product-ratings.jsx:40]: 👍

**Comment by jsnmoon** [comment]
> It's not totally clear what the '1' is. @bluefuton 

Let's iterate on the design in a future PR/async? I think it'd be better to get this out the door first.

**Comment by bluefuton** [comment]
> Let's iterate on the design in a future PR/async? I think it'd be better to get this out the door first.

Sounds like a plan 👍 Don't want to hold this up.

**Review by jeherve — CHANGES_REQUESTED** [review]
This doesn't seem to work quite well for me. It displays `11` for a `1.1` reviews:

image

This is a product with 2 reviews, one 1-star, one 4-star.

**Comment by gibrown** [comment]
> This is a product with 2 reviews, one 1-star, one 4-star.

I haven't looked at the site, but I suspect the 11 is coming from two 1s, one for the 4 star and one for the 1 star. I think you should be using the _wc_review_count field (total number of ratings) instead of the _wc_rating_count field (breakdown of ratings). Maybe I should completely remove the _wc_rating_count also. It is pretty useless since it is an array of values and so just confusing. Maybe add some wp.rating_1_count, wp.rating_2_count, wp.rating_3_count, wp.rating_4_count, wp.rating_5_count fields?

**Comment by jeherve** [comment]
> I haven't looked at the site

If this can help with testing, this is the product I was testing with: `sites/176738923/posts/14738`

File: projects/plugins/jetpack/modules/search/instant-search/components/product-ratings.jsx [hunk 5]
```diff
@@ -0,0 +1,58 @@
...
+			>
+				{ count }
+			</span>
+			<span className="screen-reader-text">
+				{ sprintf(
+					_n(
+						'Average rating of %s out of 5 from %s review.',
+						'Average rating of %s out of 5 from %s reviews.',
+						count,
+						'jetpack'
```
[the remark this answers is not in the document]
Comment (jsnmoon) [reply projects/plugins/jetpack/modules/search/instant-search/components/product-ratings.jsx:52]: Done! I've never added translator comments for _n before, so let me know if I need to adjust anything.

**Comment by jsnmoon** [comment]
> This doesn't seem to work quite well for me. It displays `11` for a `1.1` reviews
> This is a product with 2 reviews, one 1-star, one 4-star. (@jeherve)

This should be fixed!

**Comment by jsnmoon** [comment]
> Maybe add some wp.rating_1_count, wp.rating_2_count, wp.rating_3_count, wp.rating_4_count, wp.rating_5_count fields? (@gibrown)

I don't think there's any rush for us to implement this, but it'd be nice if we could get something like `wc_review_counts` that returns an object formatted like so: `{ [ratingValue]: ratingCounts }`.

**Review by jeherve — APPROVED** [review]
This tests well for me now. ⭐⭐⭐⭐⭐

**Comment by jeherve** [comment]
I'll merge this for now so we can ship it in 9.4. I'll let you handle its WordPress.com counterpart.

**Comment by jsnmoon** [comment]
Thanks @jeherve! Deployed in r219988-wpcom.
