### PR TITLE
Widgets: enqueue stylesheet directly in the widget display method

### LINKED ISSUE #39813: Extra Sidebar Widgets: CSS no longer enqueued on Elementor pages including a widget
### Impacted plugin

Jetpack

### Quick summary

This is a long-standing issue with the Elementor plugin. I reported it here: https://github.com/elementor/elementor/issues/29010

However, until #39518 this was a bug that was not noticeable since we enqueued all the CSS on all pages with the concatenated `jetpack.css` file. Now that we rely on each individual CSS file being enqueued, we're starting to notice the issue. 

*********

Plugins can register WordPress widgets using the Widgets API (`register_widget` and extending the `WP_Widget` class). When they do that, they can enqueue scripts and styles for their widget, by hooking `wp_enqueue_scripts`. A good practice when enqueuing custom scripts and styles is to only enqueue them when the widget is present on the page. That can be checked with the `is_active_widget` feature. Unfortunately, `is_active_widget` does not return `true` on pages where a widget has been added to the page via the Elementor editor.

### Steps to reproduce

1. Start by installing the latest version of the Elementor plugin.
2. Add Jetpack, connect it to WordPress.com
3. Go to Jetpack > Settings > Writing and enable the Extra Sidebar Widgets
4. Go to Pages > Add New
5. Open the Elementor Editor
6. Add a new container.
7. In that container, add the Top Posts widget (scroll down to the "WordPress" part of the inserter, you should see the widget there)
7. Publish the page.
8. View it on the frontend.

### A clear and concise description of what you expected to happen.

I would expect the `top-posts/style.css` stylesheet to be enqueued on the page.

### What actually happened

It is not.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

As a work-around, one can manually copy and paste the widget's CSS from [this file](https://raw.githubusercontent.com/Automattic/jetpack-production/refs/tags/13.9/modules/widgets/top-posts/style.css) into WordPress CSS editor.

### Platform (Simple and/or Atomic)

Atomic, Self-hosted

### Logs or notes

This was reported here:
https://wordpress.org/support/topic/grid-layout-doesnt-work-in-the-top-posts-and-pages-widget/

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #39813

## Proposed changes:

Instead of relying on a conditional check to see if the widget is active, let's call the widgets' enqueuing methods directly from within the widget display method. That should simplify things, and ensure compatiblity with systems that are not compatible with `is_active_widget`.

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion

* No

## Does this pull request change what data or activity we track or use?

* No

## Testing instructions:

1. This is easier to test on a site using a classic theme with multiple widget areas. Twenty Ten is a good choice. Install it.
2. Edit the theme's `sidebar.php` and `sidebar-footer.php` files, and add conditionals around some of the widget areas. For example you could change `if ( is_active_sidebar( 'secondary-widget-area' ) ) :` into `if ( is_active_sidebar( 'secondary-widget-area' ) && is_single() ) :` in `sidebar.php`, so the secondary sidebar is only visible when looking at single posts.
3. Install and activate the Classic Widgets plugin.
4. Connect Jetpack to WordPress.com.
5. Purchase a complete plan (you'll need a plan to be able to add the Pay with PayPal widget)
6. Under Jetpack > Settings > Writing, activate the extra sidebar widgets at the bottom of the page.
7. Go to Appearance > Widgets
8. Add widgets to different sidebar areas, loaded on different pages.
9. Configure those widgets so they display information.
10. View the site's frontend, and view source. Search for the different stylesheets that should be loaded for each widget.
    * Those stylesheets should only be loaded when the widget is present on the page.
11. Now install and activate the Elementor plugin.
12. Go to Pages > Add New
13. Enter the Elementor editor.
14. Add a new container.
15. In that container, add the Top Posts widget (scroll down to the "WordPress" part of the inserter, you should see the widget there)
16. Publish the page.
17. View it on the frontend.
    * The widget's stylesheet should be loaded on the page.

### CODE REVIEW

File: projects/packages/search/src/widgets/class-search-widget.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ public function widget_admin_setup() {
 	 * @since 5.8.0
 	 */
 	public function enqueue_frontend_scripts() {
-		if ( ! is_active_widget( false, false, $this->id_base, true ) || Options::is_instant_enabled() ) {
+		if ( Options::is_instant_enabled() ) {
```
Comment (kraftbj) [inline projects/packages/search/src/widgets/class-search-widget.php:165]: Should we remove this function from being hooked on L85 of this file?

File: projects/plugins/jetpack/modules/widgets/authors.php [hunk 2]
```diff
@@ -34,7 +34,7 @@ public function __construct() {
 			)
 		);
 
-		if ( is_active_widget( false, false, $this->id_base ) || is_active_widget( false, false, 'monster' ) || is_customize_preview() ) {
+		if ( is_customize_preview() ) {
```
Comment (kraftbj) [inline projects/plugins/jetpack/modules/widgets/authors.php]: Untested question: Do we need to add this for the preview if it is in the widget instance? Wouldn't the preview fire off the widget code that enqueues it?

**Review by kraftbj — CHANGES_REQUESTED** [review]
This makes a lot of sense. I didn't do major testing, waiting for it to be marked as ready for review, but some questions/ideas while it is in the works.

File: projects/packages/search/src/widgets/class-search-widget.php (hunk 1 above)
Comment (jeherve) [reply projects/packages/search/src/widgets/class-search-widget.php:165]: Yes, missed that! Done in fac6440b074d4f3c1a641ab9ebc14caf1c828bb7

File: projects/plugins/jetpack/modules/widgets/authors.php (hunk 2 above)
Comment (jeherve) [reply projects/plugins/jetpack/modules/widgets/authors.php]: Good point. Done in 984e9b0f16144da289a0fb585fe9db1fc7ca561e

**Review by kraftbj — APPROVED** [review]
