### PR TITLE
Fix out-of-bounds menus on the admin

### LINKED ISSUE #71198: [Bug]: Submenus are shown outside of screen - Nav Unification
### Quick summary

When you're on a wp-admin page (ie wp-admin/site-health.php) and hovering over a menu item that is close to the bottom of the screen, it gets positioned outside of the screen

image

If you try to access a menu item of that menu, at some point, it causes an endless flickering

https://user-images.githubusercontent.com/2484390/207607018-9eb23dae-b775-47be-b0e5-98a313ed6c42.mp4

### Steps to reproduce

- Visit wp-admin/site-health.php
- Adjust your screen to a size of a 13-14" Macbook
- Hover over Settings
- The menu item is positioned outside of the screen
- Further more a flickering happens if you leave your cursor at a certain point

### What you expected to happen

- The menu item should be positioned correctly, inside the window and with no need to scroll down to see it

### What actually happened

- The menu item is positioned outside of the screen, and you need to scroll down to access it

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

_No response_

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

After some digging, I found out that due to Nav Unification, the native WordPress `#wp-admin-bar-menu-toggle` is not added to the admin bar.

https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L941 relies on `#wp-admin-bar-menu-toggle` to be present (and hidden) in order to calculate the `margin-top` of the submenu.

As discussed in slack with @mmtr , this is caused because https://github.com/Automattic/jetpack/blob/fc10b4ff5e8e9b3d566618124502d2166b6b1e99/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js is missing this calculation

Quoting @mmtr conversation from Slack

> Nav Unification completely overrides the menu behavior provided by Core by performing a custom logic that it’s in  `modules/masterbar/admin-menu` in Jetpack.

> That includes the JS logic that handles things like opening submenus, positioning them in the right place, etc.

> The issue you found is a Nav Unification issue that should be addressed in `admin-menu.js` . I know that `admin-menu.js` was partially inspired by the `common.js` file but that doesn’t necessarily mean it should have the same code.

> So if the issue doesn’t happen in Core because `common.js` handles it, we should incorporate that into `admin-menu.js` but adapting it to the Nav Unification specifics (such as using the DOM elements rendered by the Nav Unification menu) 

> I think the `wp-calypso` repo is preferable for this one, since that’s where most of the Nav Unification issues are reported (remember to add the Nav Unification level).
you can leave it unassigned then, and it would be prioritized by the folks triaging issues

I've added this issue as a Blocker Priority, as it blocks @Automattic/somewherewarm from releasing peapX7-Um-p2#comment-1029

cc @manospsyx @xristos3490 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by valterlorran**
The submenu could be displayed outside of the user's screen visibility. Beyond that, hovering the `Settings` menu had the potential of causing endless flickering.

#### Before
Screen Shot 2022-12-15 at 10 02 40

#### After
Screen Shot 2022-12-15 at 10 02 06

Fixes https://github.com/Automattic/wp-calypso/issues/71198

#### Changes proposed in this Pull Request:

* Display the submenu upwards when it is out of bounds

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

#### Jetpack product discussion

n/a

#### Does this pull request change what data or activity we track or use?

n/a

#### Testing instructions:

* Visit wp-admin/site-health.php
* Adjust your screen to a size of a 13-14" Macbook
* Hover over Settings
* The submenu should show upwards
* Flickering should no longer occur

### CODE REVIEW

File: projects/plugins/jetpack/changelog/fix-out-of-bounds-menu [hunk 1]
```diff
@@ -0,0 +1,3 @@
+Significance: patch
+Type: bugfix
+Comment: Fix the submenus shown outside of screen
```
Comment (daledupreez) [inline projects/plugins/jetpack/changelog/fix-out-of-bounds-menu]: It may be worth specifying that this fix is in the masterbar module.
```suggestion
Comment: Fix the submenu positioning for the masterbar left nav
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 2]
```diff
@@ -109,6 +109,34 @@
...
+					submenu.style.top = ( 34 - submenu.clientHeight ) + 'px';
+				}
+			} );
+
+			el.addEventListener('mouseleave', function() {
+				submenu.style.display = 'none';
+				submenu.style.top = null;
+			} );
+		} );
+	}
```
Comment (daledupreez) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Nit: the code here is not using the same whitespace defaults as the rest of the file. Please ignore if the linter autocorrected to this state!
```suggestion
		document.querySelectorAll( 'li.wp-has-submenu.wp-not-current-submenu' ).forEach( function ( el ) {
			const submenu = el.querySelector( '.wp-submenu' );

			el.addEventListener( 'mouseover', function() {
				submenu.style.display = null;
				submenu.style.top = '-1px';
				if ( ! isElementInViewport( submenu ) ) {
					submenu.style.top = ( 34 - submenu.clientHeight ) + 'px';
				}
			} );

			el.addEventListener( 'mouseleave' , function() {
				submenu.style.display = 'none';
				submenu.style.top = null;
			} );
		} );
	}
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 3]
```diff
@@ -109,6 +109,34 @@
...
+
+	function isElementInViewport (el) {
```
Comment (daledupreez) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Nit: the whitespace here also feels incorrect.
```suggestion
	function isElementInViewport( el ) {
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 4]
```diff
@@ -109,6 +109,34 @@
...
+		var rect = el.getBoundingClientRect();
+
+		return (
+			rect.top >= 0 &&
+			rect.left >= 0 &&
+			rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
+			rect.right <= (window.innerWidth || document.documentElement.clientWidth)
```
Comment (daledupreez) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Could you add a comment about why we need the fallthrough check?

**Review by mmtr — COMMENTED** [review]
Thanks for the speedy fix!

It tests well but I think there is a small regression.

When I test this on an Atomic site, the "arrow" is missing on submenus that are displayed downwards:

Before | After
--- | ---
Screenshot 2022-12-15 at 15 28 42 | Screenshot 2022-12-15 at 15 27 30

**Comment by mmtr** [comment]
Also, when I test this on a Simple site, the submenus are moved to the top somehow?


https://user-images.githubusercontent.com/1233880/207889863-d56530c4-ebdf-417a-b8cf-5b00d61380c6.mov

**Review by daledupreez — DISMISSED** [review]
This isn't working as expected. I used the Jetpack Beta plugin to run this branch, and I now see the menus jumping up too high.

https://user-images.githubusercontent.com/3376401/207890299-da31d6c0-c583-4b55-95ba-4f30b7406585.mov

**Comment by valterlorran** [comment]
The problem with the simple site is that the `common.js` code is also being executed. Causing the dropdown to be positioned twice.

**Comment by valterlorran** [comment]
Let me know what you think about the check that I added:
https://github.com/Automattic/jetpack/blob/852f478647a2523329a4e74bc65ed80537663b9d/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js#L113
This will prevent it from running this code on simple sites.

**Comment by samiff** [comment]
Looks like it won't run for simple sites now, and the placement is looking good to me. I did notice maybe something odd with the color of the small arrow:

https://user-images.githubusercontent.com/15803018/207976895-c231bf11-a90b-46f0-859b-ac1c1beca1ed.mov

I wonder if you see that on your end?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 5]
```diff
@@ -109,6 +109,40 @@
...
+		if ( document.querySelector('body.jetpack-masterbar') ) {
+			document.querySelectorAll( 'li.wp-has-submenu.wp-not-current-submenu' ).forEach( function ( el ) {
+				const submenu = el.querySelector( '.wp-submenu' );
+				const linkElement = el.querySelector( 'a' );
+
+				el.addEventListener( 'mouseover', function() {
+					submenu.style.display = null;
+					submenu.style.top = '-1px';
+					if ( ! isElementInViewport( submenu ) ) {
+						submenu.style.top = ( 34 - submenu.clientHeight ) + 'px';
```
Comment (PanosSynetos) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Just out of curiosity - what's the reasoning for choosing 34px? Why does it have to be so specific?

**Comment by PanosSynetos** [comment]
Thanks so much for the prompt action and solving this issue! Much appreciated! 

It might be a good idea to test this on mobiles too, I have it on my todo list for Monday, but speaking out loud just in case someone has already tested it :)

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 5 above)
Comment (valterlorran) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: 34px is the height of the menu item, I will add a comment to make it more clear.

**Comment by valterlorran** [comment]
@samiff I fixed the problem you mentioned. Thanks for catching it!

**Comment by valterlorran** [comment]
@samiff, thanks for catching it. The arrow depends on the focus of the menu item to display, so we should remove the focus when the mouse leaves the menu item.

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 5 above)
Comment (PanosSynetos) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Thanks for the disclaimer. Wouldn't it be more appropriate to calculate the height of the menu item, rather than hardcoding it?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 6]
```diff
@@ -109,6 +109,44 @@
 				}
 			);
 		}
+
+		if ( document.querySelector('body.jetpack-masterbar') ) {
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Nitpick (non-blocking): Rather than checking the existence of this class to determine whether this is an Atomic sites, what do you think about adding a new global variable [here](https://github.com/Automattic/jetpack/blob/823886c5c5ea471ea25e3c33163640acda9960df/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php#L274-L282) to make this check more explicit?

```diff
diff --git a/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js b/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
index 686246e030..c89c0c9e01 100644
--- a/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
+++ b/projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js
@@ -110,7 +110,7 @@
 			);
 		}
 
-		if ( document.querySelector('body.jetpack-masterbar') ) {
+		if ( jetpackAdminMenu.isAtomic ) {
 			document.querySelectorAll( 'li.wp-has-submenu.wp-not-current-submenu' ).forEach( function ( el ) {
 				const submenu = el.querySelector( '.wp-submenu' );
 				const linkElement = el.querySelector( 'a' );
diff --git a/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
index 4d2cd067a4..b5fbe25680 100644
--- a/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
+++ b/projects/plugins/jetpack/modules/masterbar/admin-menu/class-base-admin-menu.php
@@ -8,6 +8,7 @@
 namespace Automattic\Jetpack\Dashboard_Customizations;
 
 use Automattic\Jetpack\Status;
+use Automattic\Jetpack\Status\Host;
 
 /**
  * Class Base_Admin_Menu
@@ -277,6 +278,7 @@ abstract class Base_Admin_Menu {
 			array(
 				'upsellNudgeJitm'  => wp_create_nonce( 'upsell_nudge_jitm' ),
 				'jitmDismissNonce' => wp_create_nonce( 'jitm_dismiss' ),
+				'isAtomic'         => ( new Host() )->is_woa_site(),
 			)
 		);
 	}
```

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js [hunk 7]
```diff
@@ -109,6 +109,44 @@
...
+	function isElementInViewport( el ) {
+		var rect = el.getBoundingClientRect();
+
+		return (
+			rect.top >= 0 &&
+			rect.left >= 0 &&
+			// Tries to primarily use the window viewport, but if that's not available, uses the documentElement.
+			// The innerWidth attribute must return the viewport width including the size of a rendered scroll bar (if any), or zero if there is no viewport.
+			rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) &&
+			rect.right <= (window.innerWidth || document.documentElement.clientWidth)
```
Comment (mmtr) [inline projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Nitpick: Minor coding standards improvement.
```suggestion
			rect.bottom <= ( window.innerHeight || document.documentElement.clientHeight ) &&
			rect.right <= ( window.innerWidth || document.documentElement.clientWidth )
```

**Review by mmtr — COMMENTED** [review]
Pretty close! There is a small regression when the menu is collapsed that places the submenus too separated from the sidebar:

Screenshot 2022-12-19 at 12 25 29

**Comment by valterlorran** [comment]
@mmtr I was not able to reproduce it. Can you share the steps it took to break it?

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 6 above)
Comment (valterlorran) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Resolved with this commit: https://github.com/Automattic/jetpack/pull/27958/commits/3822602e67a1334569c14934f5bc17eb32ad0709

File: projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js (hunk 7 above)
Comment (valterlorran) [reply projects/plugins/jetpack/modules/masterbar/admin-menu/admin-menu.js]: Resolved with this commit: https://github.com/Automattic/jetpack/commit/3822602e67a1334569c14934f5bc17eb32ad0709

**Comment by mmtr** [comment]
@valterlorran Super weird, I cannot reproduce it now, so maybe it was a temporary glitch 🤔.

**Review by mmtr — DISMISSED** [review]

**Review by mmtr — APPROVED** [review]

**Comment by valterlorran** [comment]
@mmtr I don't understand why the check `codecov/patch` is failing. Do you know what is happening?

**Comment by mmtr** [comment]
@valterlorran I think you can ignore that, it's failing in other PRs as well.
