### PR TITLE
DataSync: Cancel all previous mutations upon new mutation of same key

### LINKED ISSUE #40642: Boost: Racing condition when toggling modules on a slow connection
We had this fixed at one point.

It appears to be back!

https://github.com/user-attachments/assets/edd68f3e-1ffd-4d72-8735-f24a1e5accae

### Steps to reproduce

- Setup Boost (free version should be enough);
- Load the Boost UI;
- Throttle your network connection;
- Toggle some features quickly.

### Thoughts on this

State is no longer shared across modules. Sharing it via a context might be a solution. We can also expose the mutation to allow us to have more control over when we're showing settings for each module (this is OOS for this ticket).

### PR DESCRIPTION
**Pull request by LiamSarsfield**
Fixes #40642

## Proposed changes:
* Cancel all previous mutations upon new mutation of same key within react-data-sync-client

### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?
- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Jetpack product discussion
N/A

## Does this pull request change what data or activity we track or use?
N/A

## Testing instructions:
1. Setup Boost (free version should be enough);
2. Load the Boost UI;
3. Throttle your network connection;
4. Toggle some features quickly.

**With changes:** Features that are toggled quickly persist their new toggled status. 
**Without changes:** Features that are toggled quickly have their toggle switched inadvertently.

See below demo for applied changes.

https://github.com/user-attachments/assets/63b1002b-03e0-4257-ad4a-65be70791333

### CODE REVIEW

File: projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts [hunk 1]
```diff
@@ -98,6 +99,14 @@ export function useDataSync<
 	const abortController = useRef< AbortController | null >( null );
```
Comment (haqadn) [inline projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts]: Do we still need to use a ref now that it's part of the mutation state?

**Review by haqadn — DISMISSED** [review]
Perfect! I am a bit unsure if we still need to `useRef` for the abort controller. If we do, LGTM.

File: projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts (hunk 1 above)
Comment (LiamSarsfield) [reply projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts]: Good point! After thinking about it further, we don't, and can fully leverage React Query for this instead. I've updated the PR to reflect this.

File: projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts [hunk 2]
```diff
@@ -125,8 +125,13 @@ export function useDataSync<
 	// AbortController is used to track rapid value mutations
 	// and will cancel in-flight requests and prevent
 	// the optimistic value from being reverted.
-	const getAbortController = () =>
-		queryClient.getMutationDefaults( queryKey )?.meta?.abortController as AbortController;
+	const getAbortController = () => {
+		const defaults = queryClient.getMutationDefaults( queryKey );
+		return defaults?.meta?.abortController instanceof AbortController
```
Comment (LiamSarsfield) [inline projects/js-packages/react-data-sync-client/src/DataSyncHooks.ts:130]: Per discussion with @dilirity, this avoids unnecessary type casts. Thanks for pushing this!

**Review by dilirity — APPROVED** [review]
Nice work on this! :shipit:
