### PR TITLE
VideoPress: Keep filter UI state between pages

### LINKED ISSUE #27739: VideoPress: previously set filters are empty when returning from the Edit details page
When we apply a filter to the list of videos, go to the Edit details page and then go back to the list, the videos are filtered but the filter controllers are empty.

Steps to reproduce:

- go to the list of videos
- apply one filter, like the "Private" one:

Screen Shot 2022-12-02 at 12 27 04

- the list will be updated to show filtered videos
- click on the "Edit video details" button for some of the videos
- on the Details page, click the "Go Back" link at the top of the page:

Screen Shot 2022-12-02 at 12 28 58

- you will be sent back to the list of filtered videos
- open the panel of filters
- notice that, despite de videos being filtered, the filter controllers are empty:

Screen Shot 2022-12-02 at 12 30 18

Inspecting the local state, I saw that the filter properties are still there, they are just not reflected on the UI:

Screen Shot 2022-12-02 at 12 32 58

### PR DESCRIPTION
**Pull request by lhkowalski**
Fixes #27739.

#### Changes proposed in this Pull Request:

* Use the filter local state to check/uncheck the checkboxes associated to each filter value

#### Other information:

- [ ] Have you written new tests for your changes, if applicable?
- [ ] Have you checked the E2E test CI results, and verified that your changes do not break them?

#### Does this pull request change what data or activity we track or use?

No.

#### Testing instructions:

* Go to `Jetpack > VideoPress`
* Make sure you have videos with different ratings and privacy settings, so we can filter the results on the video list
* Apply a filter (for example, filter by the "Private" privacy):

Screen Shot 2022-12-02 at 12 27 04

* Notice that the list of videos will be updated
* On the new list of videos, click the "Edit video details" button for some video
* On the Video Details page, click the "Go back" link at the top of the page:

Screen Shot 2022-12-02 at 12 28 58

* This will send you back to the list of videos
* Notice that the list is still filtered
* Click the "Filters" button at the top of the page:

Screen Shot 2022-12-02 at 18 47 17

* **Before the fix**, the checkboxes that you selected before would not be selected anymore (but the videos were still filtered)
* **After the fix**, the checkboxes that you selected will be selected, so you can know which filters are in place on the current video list:

Screen Shot 2022-12-02 at 18 48 41

* Make sure to test using multiple filters as well, and combining it with search queries

### CODE REVIEW

File: projects/packages/videopress/src/client/admin/components/video-filter/index.tsx [hunk 1]
```diff
@@ -112,16 +124,19 @@ export const FilterSection = ( props: {
 						for="filter-g"
 						label={ __( 'G', 'jetpack-videopress-pkg' ) }
 						onChange={ checked => props.onChange?.( 'rating', 'G', checked ) }
+						checked={ filterIsChecked( 'rating', 'G' ) }
```
Comment (dhasilva) [inline projects/packages/videopress/src/client/admin/components/video-filter/index.tsx]: We should probably use constants here.
https://github.com/Automattic/jetpack/blob/trunk/projects/packages/videopress/src/client/state/constants.js#L86

**Comment by retrofox** [comment]
As mentioned in slack today, we may tackle this by using react routes straight on the client-side. Issue: https://github.com/Automattic/jetpack/issues/26720

**Review by dhasilva — APPROVED** [review]
:rocket:
