### PR TITLE
AI Extension: do not extend Jetpack Form when it's inside of a query loop

### LINKED ISSUE #32554: AI Extension: multiple buttons on the toolbar when using the block on a query loop block
When using the full site editor, if I place the form block on a location that is inside a query loop block, the assistant toolbar button will be repeated multiple times.

How to reproduce:

- test on a site with some published posts
- go to the full site editor
- add a Jetpack Form block on a location inside the frontpage query loop; this is a `twenty twenty-three` example location:

Screenshot 2023-08-17 at 12 32 19

- confirm the toolbar button is repeated multiple times:

Screenshot 2023-08-17 at 12 32 53

### PR DESCRIPTION
**Pull request by retrofox**
This PR is the first attempt to avoid extending the Jetpack Form block when it's inside of a query loop instance. Let's keep researching to see if we can get an approach more solid.

Fixes #

## Proposed changes:

* AI Extension: do not extend Jetpack Form when it's inside of a query loop

### Other information:

- [ ] Have you tested your changes on WordPress.com, if applicable (if so, you'll see a generated comment below with a script to run)?

## Testing instructions:

* Go to the block editor
* Create a Jetpack Form block instance inside of a Query Loop instance
* Confirm the Jetpack Form block instance is not extended
* Create a new Jetpack Form block but outside of the Query Loop
* Confirm that the Jetpack Form block instance now gets extended

Inside the loop | Outside the loop
-------|--------
Screenshot 2023-08-17 at 17 40 40 | Screenshot 2023-08-17 at 17 41 15

### CODE REVIEW

File: projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/jetpack-contact-form/index.tsx [hunk 1]
```diff
@@ -41,6 +48,18 @@ export function isPossibleToExtendJetpackFormBlock(
 		return false;
 	}
 
+	// ClientId gets required
```
Comment (lhkowalski) [inline projects/plugins/jetpack/extensions/blocks/ai-assistant/extensions/jetpack-contact-form/index.tsx]:
```suggestion
	// clientId is required
```

**Review by lhkowalski — APPROVED** [review]
Tested on the FSE.

- When inside a query loop block, the assistant is not present:

Screenshot 2023-08-17 at 14 47 20

- When outside a query loop, the assistant is present:

Screenshot 2023-08-17 at 14 50 05

---

Same thing for form inner blocks.

- When inside the query loop, no button:

Screenshot 2023-08-17 at 14 58 16

- When out of the query loop, a button working correctly:

Screenshot 2023-08-17 at 14 57 27

Screenshot 2023-08-17 at 14 57 46
