### PR TITLE
Instant Search: Add support for hiding search sort selector

### LINKED ISSUE #15735: Search: 'Display "Powered by Jetpack"' option doesn't save
#### Steps to reproduce the issue

1. Navigate to **Appearance --> Customize**
2. Open the **Jetpack Search** options
3. Uncheck the `Display "Powered by Jetpack"` option
4. Click **Publish**
5. Close the Customizer, and refresh the site to see that the Jetpack footer is still present
6. Navigate back to the Customizer
7. The `Display "Powered by Jetpack"` option is once again checked

Tested Jetpack Search in Twenty Twenty.

#### What I expected

The `Powered by Jetpack` text and logo should be hidden, while the Customizer option should save state.

#### What happened instead

The `Powered by Jetpack` text and logo continued to display, and the Customizer option did not save state.

**Screenshots**

Screen Recording 2020-05-10 at 01 26 pm

### PR DESCRIPTION
**Pull request by jsnmoon**
Split out from #15727.

Fixes #15735 

#### Changes proposed in this Pull Request:
* Adds a site-wide option to hide the sort selector in the Jetpack Search overlay.
* Removes the `Show search box` option from the Jetpack Search widget when instant search is enabled.
* Removes the `Show sort selection dropdown` option from the Jetpack Search widget when instant search is enabled. 
* Rewords various Jetpack Search customizer section descriptions for brevity and consistency.
* Adds a custom `Label_Control` class to be used in the Jetpack Search customizer section.
* Refactors the bridging logic between the Customizer and the Instant Search app to avoid duplicating code.

#### Is this a new feature or does it add/remove features to an existing part of Jetpack?
* Yes, it adds the ability to hide the sort selector in the Jetpack Search overlay. The search overlay is only available to customers with the Search product plan.

#### Does this pull request change what data or activity we track or use?
No.

#### Testing instructions:
1. Apply this change to a site with Jetpack Instant Search enabled.

2. Add a Jetpack Search widget to your site's footer or sidebar in the customizer.

3. Ensure that neither `Show search box` nor `Show sort selection dropdown` checkboxes are available. 

> Screen Shot 2020-05-28 at 5 33 35 PM

4. Ensure that the widget title, post types checkboxes, default sort order, and filter controls work as expected. These options should not be affected by this change.

5. Navigate to the Jetpack Search section of the customizer. 

6. Ensure there's a group of checkboxes titled `Additional Jetpack Search Settings`. 

> Screen Shot 2020-05-28 at 5 35 55 PM

7. Try toggling the newly added `Show Sort Selector` checkbox. Verify that unchecking the checkbox hides the sort selector in the search overlay without refreshing the page.

> Screen Shot 2020-05-11 at 3 13 39 PM
> Screen Shot 2020-05-11 at 3 14 36 PM

8. Try disabling instant search via `/wp-admin/admin.php?page=jetpack#/performance` and repeat step 3. Both `Show search box` and `Show sort selection dropdown` checkboxes should be available again.

#### Proposed changelog entry for your changes:
* Adds a Customizer control for hiding the sort selector in the Jetpack Search overlay.

### CODE REVIEW

File: modules/search/class-jetpack-instant-search.php [hunk 1]
```diff
@@ -8,6 +8,7 @@
 
 use Automattic\Jetpack\Connection\Client;
 use Automattic\Jetpack\Constants;
+require_once dirname( __FILE__ ) . '/class.jetpack-search-helpers.php';
```
Comment (bluefuton) [inline modules/search/class-jetpack-instant-search.php:11]: You can use `__DIR__` instead of `dirname( __FILE__)` :)

File: modules/search/customize-controls/class-label-control.php [hunk 2]
```diff
@@ -0,0 +1,49 @@
...
+
+/**
+ * Label Control class.
+ */
+class Label_Control extends WP_Customize_Control {
+	/**
+	 * Enqueue styles related to this control.
+	 */
+	public function enqueue() {
+		require_once dirname( dirname( __FILE__ ) ) . '/class.jetpack-search-helpers.php';
```
Comment (bluefuton) [inline modules/search/customize-controls/class-label-control.php:17]: You can use `dirname( __FILE__, 2 )` to avoid repeating dirname 👍

**Comment by bluefuton** [comment]
I think the checkbox labels should be in sentence case, to match the rest of the Customiser. For example:

Screen Shot 2020-06-17 at 14 22 38

**Comment by bluefuton** [comment]
Great testing instructions (as always).

On my test site, turning off the 'Show sort selector' checkbox made the sort selector disappear in the Customiser preview 👍

However, the setting did not seem to persist, and the sort selector continued appearing in the search on the site front end. When I revisit the Customiser, the 'Show sort selector' box is checked again.

File: modules/search/customize-controls/class-label-control.php (hunk 2 above)
Comment (jsnmoon) [reply modules/search/customize-controls/class-label-control.php:17]: According to PHPCS, `dirname()` doesn't have a "levels" parameter in PHP version 5.6 or earlier. Since Jetpack supports PHP 5.6, I'll keep this as-is.

**Comment by jsnmoon** [comment]
> I think the checkbox labels should be in sentence case, to match the rest of the Customiser. @bluefuton 

✅ 

> However, the setting did not seem to persist, and the sort selector continued appearing in the search on the site front end. When I revisit the Customiser, the 'Show sort selector' box is checked again. @bluefuton 

I found an issue where checkbox customizer values weren't being properly sanitized before being written to the DB. This should be fixed.

**Review by bluefuton — DISMISSED** [review]
The setting now persists correctly 👍 Looks good!

Also seems to have fixed the 'powered by Jetpack' toggle (https://github.com/Automattic/jetpack/issues/15735).

:shipit:

**Review by jeherve — CHANGES_REQUESTED** [review]
I think there was a bit of a mishap during the rebase, the PR now includes unrelated changes?

**Comment by jsnmoon** [comment]
> I think there was a bit of a mishap during the rebase, the PR now includes unrelated changes?

🤦 You're right, fixing now.

**Comment by jsnmoon** [comment]
@jeherve: Should be fixed, thanks!

File: modules/search/class-jetpack-instant-search.php [hunk 3]
```diff
@@ -8,6 +8,7 @@
 
 use Automattic\Jetpack\Connection\Client;
 use Automattic\Jetpack\Constants;
+require_once __DIR__ . '/class.jetpack-search-helpers.php';
```
Comment (jeherve) [inline modules/search/class-jetpack-instant-search.php:11]: Do we need this here, even though the file is already required by the base class?

File: modules/search/class-jetpack-search-customize.php [hunk 4]
```diff
@@ -10,7 +10,9 @@
 	exit;
 }
 
+require_once dirname( __FILE__ ) . '/class.jetpack-search-helpers.php';
```
Comment (jeherve) [inline modules/search/class-jetpack-search-customize.php:13]: Do we need the require here?

File: modules/search/customize-controls/class-label-control.css [hunk 5]
```diff
@@ -0,0 +1,18 @@
+#sub-accordion-section-jetpack_search .customize-control {
+  margin-bottom: 14px;
```
Comment (jeherve) [inline modules/search/customize-controls/class-label-control.css:2]: You'll probably want to move from spaces to tabs, to avoid someone accidentally changing all those at once on save when they next edit this file.

File: modules/search/customize-controls/class-label-control.php [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+			</label>
+		<?php endif; ?>
+		<?php if ( ! empty( $this->description ) ) : ?>
+			<span class="description customize-control-description">
+				<?php echo esc_html( $this->description ); ?>
+			</span>
+		<?php endif;
+	}
+}
+?>
```
Comment (jeherve) [inline modules/search/customize-controls/class-label-control.php:49]: Can we do without the closing tag here?

**Review by jeherve — DISMISSED** [review]
This seems problematic on sites that already have a widget set up; the sort selector is then hidden by default on the frontend once you update to this branch. I think it should remain on by default in those cases.

Other than that, I only have minor remarks below.

File: modules/search/class-jetpack-instant-search.php (hunk 3 above)
Comment (jsnmoon) [reply modules/search/class-jetpack-instant-search.php:11]: Ah, good point; this require is unnecessary.

File: modules/search/class-jetpack-search-customize.php (hunk 4 above)
Comment (jsnmoon) [reply modules/search/class-jetpack-search-customize.php:13]: No, although it was necessary at one point during development. I'll remove this.

**Comment by jsnmoon** [comment]
> This seems problematic on sites that already have a widget set up; the sort selector is then hidden by default on the frontend once you update to this branch. I think it should remain on by default in those cases. @jeherve 

Agreed, it looks like my fix overlooked this scenario. Here are what `get_option` for these checkbox customizer values can return:

> Truthy values:
> - `'1'` (after being set via the Customizer)
> - `true` (before customizer write, in customizer iframe, when default set to `true`)
> - `x` (before customizer write, in customizer iframe, when default set to `x`)
> 
> Falsy values:
> - `''` (after being set via the Customizer)
> - `false` (before customizer write, outside the customizer iframe, regardless of default value)

I went ahead and changed the default setting values for these checkboxes to `'1'` and added a `=== '1'` comparison when getting these option values. This approach should fix the issue for good.

**Comment by gibrown** [comment]
@jsnmoon will this also fix https://github.com/Automattic/jetpack/issues/16123 ? While deploying onto support sites I've had a lot of questions about the default sorting order before the user has searched.

**Review by jeherve — APPROVED** [review]
This works well in my tests now. 🚢

**Comment by jsnmoon** [comment]
> will this also fix #16123? While deploying onto support sites I've had a lot of questions about the default sorting order before the user has searched. @gibrown 

This doesn't address #16123; #16017 might, though.
